#+TITLE: Week3

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Show that the collection of formulas \(x>a\) for \(a\in M\) generates a complete
type \(\tau_M(x)\in S_1(M)\). In other words, show that the partial type \(\{(x>a):a\in M\}\) has a unique
completion
#+END_exercise

#+BEGIN_proof
Let \(\Sigma(x)=\{x>a:a\in M\}\), \(p,q\in S_1(M)\), \(p,q\supseteq \Sigma(x)\), \(p\neq q\). Since \(\DLO\) has quantifier
elimination, there is a quantifier free formula \(\varphi(x)\in p\setminus q\). \varphi has the form
\begin{equation*}
\bigwedge_{a\in A}x>a\wedge\bigwedge_{b\in B}x\le b\wedge\bigwedge_{c\in C}x\neq c\wedge\bigwedge_{d\in D}x=d
\end{equation*}
where \(A,B,C,D\) are finite. But since \(p,q\supseteq\Sigma(x)\), \(B=D=\emptyset\). Also \(x\neq c\) is implied
by \(\Sigma(x)\). Thus if we choose \(a'=\max\{a:a\in A\}\), then
\begin{equation*}
M\vdash\varphi\leftrightarrow x>a'
\end{equation*}
Thus \(\varphi\in q\), a contradiction. Hence \(p=q\)
#+END_proof

#+BEGIN_exercise
Show that \(\tau_M\) is definable
#+END_exercise

#+BEGIN_proof
By exercise 3 for each \(N\succeq M\), \(\tau_M\) has a unique heir and thus \(\tau_M\) is definable
#+END_proof

#+BEGIN_exercise
Suppose \(N\succeq M\). Show that \(\tau_N\) is an heir of \(\tau_M\)
#+END_exercise

#+BEGIN_proof
Let \(q\in S_1(N)\) be an heir of \(\tau_M\) and suppose \(x\le a\in q(x)\)  for some \(a\in N\). Then there
is \(a'\in M\) s.t. \(x\le a'\in\tau_M\), which is impossible. Thus \(\{x>a:a\in N\}\subseteq q\) and \(q=\tau_N\).
Hence \(\tau_N\) is the unique heir of \(\tau_M\) by Exercise 1
#+END_proof

#+BEGIN_exercise
Suppose \(N\succeq M\) and \(N\) is \(\abs{M}^+\)-saturated. Show that \(\tau_N\) is not a coheir of \(\tau_M\)
#+END_exercise

#+BEGIN_proof
Since \(N\) is \(\abs{M}^+\)-saturated, there is \(c\in N\) s.t. \(N\vDash\tau_M(c)\). Then there is
no \(a\in M\) satisfying \(x>c\).
#+END_proof

#+BEGIN_exercise
If \(N\succeq M\), show that \(\tau_M\) has a unique coheirs over \(N\)
#+END_exercise

#+BEGIN_proof
Suppose \(\tau_M\) has two different coheirs \(p,q\in S_1(N)\). Because \(p\) and \(q\) are the same thing
as cuts, we may assume that there is \(c\in N\) s.t. \(x<c\in p\)
and \(x>c\in q\). But for any \(x\) realizing, \(x>m\) for all \(m\in M\). Thus there is
no \(m\in M\) satisfying \(x>c\). Hence \(p\) is not a coheir of \(\tau_M\), a contradiction
#+END_proof

#+BEGIN_exercise
Give an example of models \(M\preceq N\) of \(\DLO\) where \(\tau_N\) is a coheir of \(\tau_M\)
#+END_exercise

#+BEGIN_proof
\(M=\Q\), \(N=\R\)
#+END_proof
