#+TITLE: Homework3

#+AUTHOR: 陈淇奥@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}

#+ATTR_LATEX: :options [1.5.26]
#+BEGIN_exercise
证明任何序数都可表示为\(\alpha+n\)，其中\alpha 是0或极限序数，而\(n\in\omega\)。并且这种表示唯一。
#+END_exercise

#+BEGIN_proof
由定理1.4.12，任何非0序数\beta 都可唯一表示为
\begin{equation*}
\beta=\omega^{\gamma_0}\cdot\delta_0+\dots+\omega^{\gamma_{k-1}}\cdot\delta_{k-1}
\end{equation*}
其中\(k\in\omega\)，\(\delta_i\)和\(\gamma_i\)都是序数，\(\gamma_i\in\omega\)，并且\(\gamma_0>\cdots>\gamma_{k-1}\)。若\(\gamma_{k-1}\neq 0\)，由练习1.5.31，
\beta 是极限序数且\(\beta=\beta+0\)。若\(\gamma_{k-1}=0\)，令\(\alpha=\omega^{\gamma_0}\cdot\delta_0+\dots+\omega^{\gamma_{k-2}}\cdot\delta_{k-2}\)，由练习1.5.31，
\alpha 是极限序数，\(\beta=\alpha+\delta_{k-1}\)
#+END_proof

#+ATTR_LATEX: :options [1.5.30]
#+BEGIN_exercise
如果\(\alpha<\beta\)，则
1. \(\alpha+\gamma\le\beta+\gamma\)
2. \(\alpha\cdot\gamma\le\beta\cdot\gamma\)


而\(\le\)不能替换为<
#+END_exercise

#+BEGIN_proof
1. 对\gamma 应用超穷归纳证明：若\(\gamma=0\)，由条件可知\(\alpha\le\beta\)；若\(\gamma=\delta+1\)，由归纳假设，\(\alpha+\delta\le\beta+\delta\)。若\(\alpha+\delta=\beta+\delta\)，
    则\((\alpha+\delta)+1=(\beta+\delta)+1=\alpha+(\delta+1)=\beta+(\delta+1)\)；若\(\alpha+\delta<\beta+\delta\)，
    于是\((\alpha+\delta)+1\le\beta+\delta<(\beta+\delta)+1\)，而\((\alpha+\delta)+1=\alpha+(\delta+1)\)，\((\beta+\delta)+1=\beta+(\delta+1)\)，
    因此\(\alpha+(\delta+1)<\beta+(\delta+1)\)。综上，\(\alpha+\gamma\le\beta+\gamma\)。

    若\gamma是极限序数，对于任意\(\alpha+\theta\in\bigcup\{\alpha+\delta\mid\delta<\gamma\}\)，由归纳假设，有\(\alpha+\theta\le\beta+\theta\)。于
    是\(\bigcup\{\alpha+\delta\mid\delta<\gamma\}\subseteq\bigcup\{\beta+\delta\mid\delta<\gamma\}\) ，于是\(\alpha+\gamma\le\beta+\gamma\)。

    若\(\alpha,\beta\in\omega\)且\(\gamma=\omega\)，则\(\alpha+\omega=\beta+\omega\)。

2. 对\gamma 应用超穷归纳证明：若\(\gamma=0\)，则\(\alpha\cdot\gamma=0=\beta\cdot\gamma\)；若\(\gamma=\delta+1\)，
    \(\alpha\cdot\gamma=\alpha\cdot(\delta+1)=\alpha\cdot\delta+\delta\le\beta\cdot\delta+\delta=\beta\cdot(\delta+1)=\beta\cdot\gamma\)；若\gamma
    是极限序数，对于任意\(\alpha\cdot\theta\in\bigcup\{\alpha\cdot\theta\mid\theta<\gamma\}\)，都
   有\(\alpha\cdot\theta\le\beta\cdot\theta\)，于是\(\alpha\cdot\gamma\subseteq\beta\cdot\gamma\)，因此\(\alpha\cdot\gamma\le\beta\cdot\gamma\)

   若\(\alpha,\beta\in\omega\)，则\(\alpha\cdot\omega=\beta\cdot\omega\)
#+END_proof

#+ATTR_LATEX: :options [1.5.31]
#+BEGIN_exercise
一个序数\alpha 是极限序数当且仅当存在\beta ，\(\alpha=\omega\cdot\beta\)
#+END_exercise

#+BEGIN_proof
若\(\alpha=\omega\cdot\beta\)，对于任意\(\omega\le\gamma<\alpha\)，由定理1.4.12，\(\gamma=\omega\cdot\delta_0+\delta_1\)，其中\(\delta_0<\beta\)。于是
\begin{equation*}
\gamma+1=(\omega\cdot\delta_0+\delta_1)+1=\omega\cdot\delta_0+(\delta_1+1)<\omega\cdot\delta_0+\omega=\omega\cdot(\delta_0+1)\le\omega\cdot\beta
\end{equation*}
对于任意\(\gamma<\omega\)，\(\gamma+1<\omega<\alpha\)。因此\alpha 不是后继序数，于是它是极限序数

若\alpha 是极限序数，由定理1.4.12可知
\begin{equation*}
\alpha=\omega^{\gamma_0}\cdot\delta_0+\dots+\omega^{\gamma_{k-1}}\cdot\delta_{k-1}
\end{equation*}
其中\(k\in\omega\),\(\delta_i\)和\(\gamma_i\)都是序数且\(\gamma_0>\dots>\gamma_{k-1}\)。若\(\gamma_{k-1}=0\)，则因
为\(\delta_{k-1}\in\omega\)是后继序数，所以\(\delta_{k-1}=\delta_{k-1}'+1'\)，于是
\begin{equation*}
\alpha=\left( \omega^{\gamma_0}\cdot\delta_0+\dots+\omega^{\gamma_{k-2}}\cdot\delta_{k-2}+\delta_{k-1}' \right)+1
\end{equation*}
是后继序数，矛盾。因此\(\gamma_{k-1}\neq 0\)，于是
\begin{equation*}
\alpha=\omega\cdot(\omega^{\gamma_0-1}\cdot\delta_0+\dots+\omega^{\gamma_{k-1}-1}\cdot\delta_{k-1})
\end{equation*}
#+END_proof

#+ATTR_LATEX: :options [1.5.33]
#+BEGIN_exercise
找到函数\(f:\omega\to\omega+\omega\)和\(g:\omega+\omega\to\omega+\omega+\omega\)满足
1. \(\sup(f[\omega])=\omega+\omega\)
2. \(\sup(g[\omega+\omega])=\omega+\omega+\omega\)
3. 如果\(h=g\circ f\)，有\(\sup(h[\omega])<\omega+\omega+\omega\)
#+END_exercise

#+BEGIN_proof
对于任意\(x\in\omega\)
\begin{equation*}
f(x)=
\begin{cases}
\omega+x&x\text{是偶数}\\
0&x\text{是奇数}
\end{cases}
\end{equation*}
\begin{equation*}
g(x)=
\begin{cases}
0&x\text{是偶数}\\
\omega+x&x\text{是奇数}
\end{cases}\hspace{1cm}
g(\omega+x)=
\begin{cases}
0&x\text{是偶数}\\
\omega+\omega+x&x\text{是奇数}
\end{cases}
\end{equation*}
#+END_proof

#+ATTR_LATEX: :options [1.5.38]
#+BEGIN_exercise
对任意集合\(X\)，存在一个序数\(H(X)\)，\(H(X)\)不与\(X\)的任意子集等势，并且是具有如此性质的最小序数。
令\(W=\{w\subseteq X\mid w\text{上存在良序}\}\)，
\begin{equation*}
H(X)=\{\alpha\mid\text{存在}w\in W,\alpha\text{是与$w$同构的唯一序数}\}
\end{equation*}
证明\(W\)是集合，\(H(X)\)是序数。
#+END_exercise

#+BEGIN_proof
令
\begin{align*}
\varphi(w)&=\exists R(R\subseteq X\times X\wedge\forall x\forall y((x,x)\notin R\wedge((x,y)\in R\to\neg(y,x)\notin R))\\&\wedge\forall Y(Y\subseteq X\wedge Y\neq\emptyset\wedge\exists y_0(y_0\in Y\wedge\forall y(y\in Y\to y_0=y\vee y_0<y))))
\end{align*}
于是\(\varphi(w)\)表达了\(w\)上存在良序，于是\(W=\{w\in\calp(X)\mid\varphi(w)\}\)是集合。

由替换公理，\(H(X)\)是集合。由引理1.3.28，\(\in\)在\(H(X)\)是良序。对于任意非空\(y\in H(X)\)与\(x\in y\)，
\(y\)与某个\(w\in W\)同构，记为\(f:y\to w\)，则\(f|x\)依然是同构。因为\(x\)是序数，\(f\)保序，于
是\(f(x)\)是良序集，因此\(f(x)\in W\)，所以\(x\in H(X)\)。从而\(H(X)\)是传递的，于是\(H(X)\)是序数。
#+END_proof
