#+TITLE: Homework7

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Let \(M\) and \(N\) be \(L\)-structures. Let \(T\) be the set of all \(L\)-sentences satisfied
by \(M\). Show that \(M\equiv N\) iff \(N\vDash T\)
#+END_exercise

#+BEGIN_proof
If \(M\equiv N\), then for any \(L\)-sentence \varphi, if \(M\vDash\varphi\Leftrightarrow N\vDash\varphi\). Hence \(N\vDash T\).

If \(N\vDash T\), then for any \(L\)-sentence \varphi, if \(M\vDash\varphi\), then \(N\vDash\varphi\). If there is a sentence \psi such
that \(N\vDash\psi\) and \(M\vDash\neg\psi\). Then as \(\neg\psi\in T\), we have \(N\vDash\neg\psi\), a contradiction. Thus if \(N\vDash\varphi\)
then \(M\vDash\varphi\). Hence \(M\equiv N\)
#+END_proof

#+BEGIN_exercise
Show that if \((M,\le)\) is a countable linear order, then there is an embedding \((M,\le)\to(\Q,\le)\)
#+END_exercise

#+BEGIN_proof
Take a element \(m\) from \(M\) and \(q\in \Q\) and let \(f_0=\{(m,q)\}\). We build a chain of map
\begin{equation*}
f_0\subset f_1\subset f_2\subset\cdots
\end{equation*}
such that if \(m_1,m_2\in f_i\), then \(m_1\le m_2\) iff \(f(m_1)\le f(m_2)\). Suppose \(f_i\) is defined and we can enumerate it \(\{(m_0,q_0),\dots,(m_{i-1},q_{i-1})\}\)
such that \(m_0<m_1<\dots<m_{i-1}\).. Take an
element \(m_i\) of \(M\setminus\dom(f_i)\), there are three cases
1. If \(m_i>m_{i-1}\), then take \(q_i=\max\{q_0,\dots,q_{i-1}\}+1=q_{i-1}+1\)
2. If there is \(j\) such that \(m_j<m_i<m_{j+1}\), then take a \(q_i\in(q_j,q_{j+1})\)
3. If \(m_i<m_0\), then take \(q_i=q_0-1\)


Let \(f_{i+1}=f_i\cup\{(m_i,q_i)\}\). Then for any \(n\in\dom(f_i)\), \(m_i<n\) if and only
if \(f_{i+1}(m_i)<f_{i+1}(n)\). Hence for any \(m,n\in\dom(f_{i+1})\), we have \(m<n\) if and only
if \(f_{i+1}(m)<f_i(n)\).

Let \(f=\bigcup_{i\in\abs{M}}f_i=\bigcup_{i\in\omega}f_0\). For any \(a,b\in M\), there is \(i\in\omega\) s.t. \(a,b\in\dom(f_i)\)
and \(a\le b\) if and only if \(f(a)=f_i(a)\le f_i(b)=f(b)\). Hence \(f\)  is an embedding.
#+END_proof

#+BEGIN_exercise
Let \(L\) be a language and \(L'\) be a bigger language. Let \(M_1\) be an \(L\)-structure and \(M_2\)
be an \(L'\)-structure. Suppose that \(M_1\equiv M_2\upharpoonright L\). Show that there is
an \(L'\)-structure \(M_3\) with an \(L'\)-elementary embedding \(i_2:M_2\to M_3\) and an \(L\)-elementary
embedding \(i_1:M_1\to (M_3\upharpoonright L)\)
#+END_exercise

#+BEGIN_proof
Let \(T_L(M_1)=\{\varphi(\barm)\mid\varphi\;L\text{-formula and }M_1\vDash\varphi(\barm)\}\)
and \(T_{L'}(M_2)=\{\psi(\barm')\mid\psi\;L'\text{-formula and }M_2\vDash\psi(\barm')\}\).
Let \(L''=L'\cup M_1\cup M_2\) and \(\Gamma =T_L(M_1)\cup T_{L'}(M_2)\) an \(L''\)-theory. For
any \(\phi(\barm)\wedge\psi(\barm')\) where \(\phi(\barm)\in T_L(M_1)\) and \(\psi(\barm')\in T_{L'}(M_1)\). We
have \(M_1\vDash\phi(\barm)\) and hence \(M_1\vDash\exists\barx\;\phi(\barx)\).
As \(M_1\equiv M_2\upharpoonright L\), \(M_2\vDash\exists\barx\;\phi(\barx)\) and there is \(\barn\in M_2^m\) such
that \(M_2\vDash\phi(\barn)\). By interpreting \(\barm\) to \(\barn\) and \(M_1\setminus\barm\) by arbitrary \(M_2\)
element, we have \(M_2\vDash\phi(\barn)\wedge\psi(\barm')\) and hence \(\phi(\barm)\wedge\psi(\barm')\) is satisfiable.

Thus by compactness, \Gamma is satisfiable and there is a \(L''\)-structure \(N\) such that \(N\vDash\Gamma\).
Let \(M_3=N\upharpoonright L'\),we have \(M_3\vDash T(M_2)\) and \(M_3\upharpoonright L\vDash T(M_1)\).
Hence \(M_3\) is an elementary extension of \(M_2\) and \(M_3\upharpoonright L\) is an elementary
extension of \(M_1\)
#+END_proof

#+BEGIN_exercise
Show that there is a structure \((N,\le,P^N)\equiv(M,\le,P)\)  and an embedding \(i:(\Q,\le)\to(P^N,\le)\)
#+END_exercise

#+BEGIN_proof
Consider a new language \(L'=L\cup\Q\) and \(L'\)-theory \(\Gamma =\Th(M,\le,P)\cup\Diag(\Q,\le)\cup\{P(q):q\in\Q\}\).
For any finite \(\Delta_1\cup\Delta_2\cup\Delta_3\subseteq_f\Gamma\) where \(\Delta_1\subseteq_f\Th(M,\le,P)\), \(\Delta_2\subseteq_f\Diag(\Q,\le)\)
and \(\Delta_3\subseteq_f\{P(q):q\in\Q\}\). Let \(A\subseteq\Q\) denote the constants of \(\Q\) occurring in \(\Delta_2\cup\Delta_3\). As \(A\)
is finite and \(M\) is an infinite linear order, we can find suitable interpretation such that for
any \(a_1,a_2\in A\), \(\Q\vDash a_1\le a_2\) if and only if \((M,\le,P)\vDash a_1^M\le a_2^M\). By interpreting \(\Q\setminus A\) to
arbitrary elements of \(M\), we have \((M,\le,P,\Q^M)\vDash\Delta_1\cup\Delta_2\cup\Delta_3\).

Hence \Gamma is satisfiable and
suppose \(N'\vDash\Gamma\). Let \((N,\le,P^N)=N'\upharpoonright L\).
Then as \((N,\le,P^N)\vDash\Th(M,\le,P)\), we have \((N,\le,P^N)\equiv(M,\le,P)\). Also as for
any \(q\in\Q\), \(q^{N'}\in N'\) and so \(q^{N'}\in N\) and \(P(q^{N'})\). Thus for
any \(q_1,q_2\in\Q\), \(\Q\vDash q_1\le q_2\) if and only if \(N'\vDash q_1^{N'}\le q_2^{N'}\) if and only
if \(N\vDash q_1^{N'}\le q_2^{N'}\) if and only if \(P^N\vDash q_1^{N'}\le q_2^{N'}\) since \(P^N\subseteq N=N'\).
#+END_proof


#+BEGIN_exercise
Show that there is a countable structure \((N,\le,P^N)\equiv(M,\le,P)\) and an embedding \(i:(\Q,\le)\to(P^N,\le)\)
#+END_exercise

#+BEGIN_proof
From previous exercise we get a structure \((N,\le,P^N)\equiv(M,\le,P)\) and an embedding \(i:(\Q,\le)\to(P^N,\le)\).
Let \(S=i(\Q)\subseteq N\), then Downward Löwenheim–Skolem Theorem we can get a countable elementary
substructure \((N',\le,P^{N'})\) of \((N,\le,P^N)\) containing \(i(\Q)\). Hence \((N',\le,P^{N'})\equiv(M,\le,P)\).
For any \(q\in\Q\), as \(N'\vDash P^{N'}i(q)\) if and only if \(N\vDash P^Ni(q)\), \(\Q\) is a subset of \(P^{N'}\) and hence \(i\)
is still an embedding but from \((\Q,\le)\) to \((P^{N'},\le)\).
#+END_proof

#+BEGIN_exercise
Show that there is a structure \((N,\le,P^N)\equiv(M,\le,P)\) and an embedding \(f:(N,\le)\to(P^N,\le)\)
#+END_exercise

#+BEGIN_proof
Suppose we have a countable structure \((N,\le,P^N)\equiv(M,\le,P)\) and an embedding \(i:(\Q,\le)\to(P^N,\le)\). Then
\(N\) is a countable linear order and by Exercise 2 we have an embedding \(j:(N,\le)\to(\Q,\le)\).
Then \(i\circ j\) is still an embedding as for any \(a,b\in N\), \(M\vDash a\le b\Leftrightarrow\Q\vDash j(a)\le j(b)\Leftrightarrow P^N\vDash ij(a)\le ij(b)\)
#+END_proof

#+BEGIN_exercise
Show that there is an elementary extension \((N,\le,P^N)\succeq(M,\le,P)\) and an embedding \(f:(N,\le)\to(P^N,\le)\)
#+END_exercise

#+BEGIN_proof
Consider a new language \(L'=L\cup M\cup\{f\}\), let
\(\varphi\) be \(\forall x,y(x\le y\leftrightarrow f(x)\le f(y)\wedge P(f(x))\wedge P(f(y)))\)
and a theory
\(\Gamma =\Diag_{\el}(M,\le,P)\cup\{\varphi\}\)

From previous exercise, we have a structure \((N,\le,P^N)\equiv(M,\le,P)\) and an embedding \(g:(N,\le)\to(P^N,\le)\).
For any \(\psi(\barm)\wedge\varphi\) where \(\psi(\barm)\in\Diag_{\el}(M,\le,P)\), \(M\vDash\exists\barx\psi(\barx)\)
and \(N\vDash\exists\barx\psi(\barx)\). So there is \(\barn\in N^n\) such that \(N\vDash\psi(\barn)\). By
interpreting \(\barm\) as \(\barn\) and \(M\setminus\barm\) as arbitrary elements
of \(N\), \((N,\le,P^N,M^N,g)\vDash\psi(\barm)\wedge\varphi\), hence \(\psi\wedge\varphi\) is satisfiable and thus \Gamma is satisfiable.

Then there is a model \((O,\le,P^O,M^O,f^O)\vDash\Gamma\) such that \((O,\le,P^O)\succeq(M,\le,P)\) and \(f^O:(O,\le)\to(P^O,\le)\) is
an embedding
#+END_proof
