#+TITLE: Homework12
#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Show that if \(p\in S_n(T)\) then \(S_n(T)\setminus\{p\}\) is open
#+END_exercise

#+BEGIN_proof
\(S_n(T)\setminus\{p\}=\bigcup_{\varphi\in p}[\neg\varphi]\)
#+END_proof

#+BEGIN_exercise
Suppose \(X\subseteq S_n(T)\) is open and the complement \(S_n(T)\setminus X\) is also open. Show that \(X\) is clopen
#+END_exercise

#+BEGIN_proof
Since \(X\) and \(S_n(T)\setminus X\) are open, \(X=\bigcup_{\varphi\in E}[\varphi]\) and \(S_n(T)\setminus X=\bigcup_{\psi\in D}[\psi]\) for some
sets \(E,D\) of formulas. If one of \(E\) or \(D\) is finite, then \(X\) is clopen. Now
suppose \(E\) and \(D\) are infinite, then since \(S_n(T)=\bigcup_{\varphi\in E}[\varphi]\cup\bigcup_{\psi\in D}[\psi]\), by Lemma 5,
there are finite subsets \(E'\subseteq E\) and \(D'\subseteq D\) s.t. \(S_n(T)=\bigcup_{\varphi\in E'}[\varphi']\cup\bigcup_{\psi\in D'}[\psi']\).
Thus \(X=\bigcup_{\varphi\in E'}[\varphi']=[\bigvee_{\varphi\in E'}\varphi']\) and hence it is clopen.
#+END_proof

#+BEGIN_exercise
Suppose \(I\) is a set and \(U_i\subseteq S_n(T)\) is open for each \(i\in I\). Suppose \(\bigcup_{i\in I}U_i=S_n(T)\).
Show that there is a finite set \(I_0\subseteq I\) s.t. \(\bigcup_{i\in I_0}U_i=S_n(T)\)
#+END_exercise

#+BEGIN_proof
For each \(i\in I\), since \(U_i\) is open, it is a union of clopen sets, that
is, \(U_i=\bigcup_{\varphi_i\in E_i}[\varphi_i]\) for some \(E_i\). Hence \(S_n(T)=\bigcup_{i\in I}U_i=\bigcup_{i\in  I}\bigcup_{\varphi_i\in E_i}[\varphi_i]\). Thus
by Lemma 5, there is a finite subset \(E\) of \(\bigcup_{i\in I}E_i\) s.t. \(S_n(T)=\bigcup_{\varphi\in E}[\varphi]\). Since
for each \(\varphi\in E\), \([\varphi]\subseteq U_i\) for some \(i\in I\), there is a finite set \(I_0\subseteq I\) s.t. \(\bigcup_{i\in I_0}U_i=S_n(T)\)
#+END_proof

#+BEGIN_exercise
Let \(S_3(DLO)\) be the space of 3-types in DLO. What is the cardinality of \(S_3(DLO)\)?
#+END_exercise

#+BEGIN_proof
Since DLO has quantifier elimination and has no constant, for variables \(x,y,z\), the basic
formulas are of the form
\begin{equation*}
o=o,\quad o<o'
\end{equation*}
where \(o\) and \(o'\) is one of \(x,y,z\). Thus there is 13 kinds of relation between \(x,y\)
and \(z\):
\begin{alignat*}{3}
&x=y=z\quad&&x=y<z\quad&&x<y<z\\
&&&z<x=y&&x<z<y\\
&&&y<x=z&&y<x<z\\
&&&x=z<y&&y<z<x\\
&&&x<y=z&&z<x<y\\
&&&y=z<x&&z<y<x
\end{alignat*}
And thus \(\abs(S_3(DLO))=13\)
#+END_proof

#+BEGIN_exercise
Let \(K\) be an infinite field and \(t\in K\) be a non-zero element. Suppose the
type-space \(S_1(\{t\})\) is finite. Show that there is a positive integer \(n\) s.t. \(t^n=1\)
#+END_exercise

#+BEGIN_proof
If there is no such \(n\), then for each different \(i,j\in\N^+\), \(t^i\neq t^j\). Thus for
each \(i\in\N^+\), \(x=t^i\) determines a unique type in \(S_1(\{t\})\) and hence \(S_1(\{t\})\) is infinite, a contradiction
#+END_proof

#+BEGIN_exercise
Let \(T\) be a complete theory of infinite fields. Show that \(T\) is not \omega-categorical
#+END_exercise

#+BEGIN_proof
Suppose \(M\vDash T\) and  \(T\) is \omega-categorical, then by
Ryll-Nardzewski theorem \(S_2(T)\) is finite.
Then for each \(a\in M\), \(\abs{S_1(\{a\})}\le\abs{S_2(T)}\) and hence there is a least positive \(n_a\)
s.t. \(a^{n_a}=1\).

Let \(d=\sup\{n_a:a\in M\}\). If \(d=\omega\), then consider
\begin{equation*}
\Gamma(x)=\{x^n\neq 1:n\in\omega\}
\end{equation*}
is finitely satisfiable and hence there is a countable model \(N\vDash T\) and a element \(t\in N\)
s.t. \(S_1(\{t\})\) is infinite, a contradiction. Thus \(d<\omega\).
#+END_proof
