#+TITLE: Homework

#+AUTHOR: 陈淇奥@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}

#+ATTR_LATEX: :options [3.2.13]
#+BEGIN_exercise
如果\(F\)是由\(G\)生成的滤，则\(F\)是包含\(G\)的最小的滤，即\(G\subseteq F\)并且如果\(F'\supseteq G\)也是滤，
则\(F\subseteq F'\)
#+END_exercise

#+BEGIN_proof
对任意\(x\in F\)，存在\(g\in G\)使得\(g\le b\)。因为\(F'\)是包含\(G\)的滤，\(g\in F'\)，于是对于任意\(g\le b\)
都有\(b\in F'\)，因此\(x\in F'\)
#+END_proof

#+ATTR_LATEX: :options [3.2.16]
#+BEGIN_exercise
假设\(G\subseteq B\)为非空子集，\(F\)是由\(G\)生成的滤，则以下命题等价
1. \(G\)是单点集
2. \(F\)是超滤
3. \(F\)是主超滤
#+END_exercise

#+BEGIN_proof
若\(G\)有有限交性质，\(F\)是由\(G\)生成的主滤（书上这里写了主滤），则以下命题等价
1. \(G\)包含原子的单点集
2. \(F\)是超滤
3. \(F\)是主超滤



\(1\to 2\)。因为\(G\)有有限交性质，\(G\)只包含一个原子\(a\)，因为对任意\(b\in B\)，或者\(a\le b\)或者\(a\le -b\)，因此\(G\)是超滤。

\(3\to 2\)。显然。

\(3\to 1\)。若\(F\)是主超滤，假设它由\(\{a\}\)生成，则对于任意\(b\in B\)，\(a\le b\)或者\(a\le -b\)。因此\(a\)
是原子且\(a\in G\)。

\(2\to 3\)。显然。
#+END_proof

#+ATTR_LATEX: :options [3.2.18]
#+BEGIN_exercise
如果\(a\neq b\)，则存在超滤\(U\)，\(a\in U\)但\(b\notin U\)
#+END_exercise

#+BEGIN_proof
如果\(a<b\)，则任何包含\(a\)的滤都包含\(b\)
#+END_proof

#+ATTR_LATEX: :options [3.2.19]
#+BEGIN_exercise
令\(F\)是\(\calb\)上的滤，令\((\{0,1\},+,\cdot,-,0,1)\)为两个元素的布尔代数。定义\(f:B\to\{0,1\}\)为
\begin{align*}
f(b)=
\begin{cases}
1&b\in F\\
0&b\notin F
\end{cases}
\end{align*}
证明：\(F\)是超滤当且仅当\(f\)是布尔代数\(\calb\)到\(\{0,1\}\)的同态映射
#+END_exercise

#+BEGIN_proof
若\(F\)是超滤，则\(f(0)=0\)且\(f(1)=1\)。因为\(a\cdot b\in F\)当且仅当\(a\in F\wedge b\in F\)，因
此\(f(a\cdot b)=f(a)\cdot f(b)\)。而\(a+b\in F\)当且仅当\(a\in F\vee b\in F\)，因此\(f(a+b)=f(a)+f(b)\)。因此\(f\)是
同态映射

若\(f\)是同态映射，于是有\(a\cdot b\in F\Leftrightarrow a\in F\wedge b\in F\)且\(a+b\in F\Leftrightarrow a\in F\vee b\in F\)。若\(a,-a\notin F\)，
则\(a+(-a)=1\notin F\)，矛盾。因此\(F\)是超滤。
#+END_proof

#+ATTR_LATEX: :options [3.2.33]
#+BEGIN_exercise
令\(X\)为任意集合。
1. 如果\(X\)是可数集合，则\(\calp(X)\)上的所有\(\aleph_1\)-完全滤都是主滤
2. 如果\(X\)不可数，则\(\{G\subset X\mid\abs{G}\le\aleph_0\}\)是\(X\)上\(\aleph_1\)-完全的理想
3. 如果\(\kappa>\aleph_1\)正则，而\(\abs{X}\ge\kappa\)，则\(I=\{G\subset S\mid\abs{G}<\kappa\}\)是\(\kappa\)-完全的理想
#+END_exercise

#+BEGIN_proof
1.
2. 令\(I=\{G\subset X\mid\abs{G}\le\aleph_0\}\)，因为可数集合的可数并依然可数，因此\(I\)是\(\aleph_1\)-完全的。下证\(I\)是理
   想。首先\(\emptyset\in I\)，对于任意\(X,Y\in I\)，\(\abs{X\cap Y}\le\abs{X}\le\aleph_0\)，因此\(X\cap Y\in I\)。若\(X\in I\)
   且\(Y\subset X\)，则\(Y\in I\)
3. 对\(I\)的任意子集\(I'\)且\(\abs{I'}=\gamma<\kappa\)，有一个枚举\(I'=\{I_\alpha\mid\alpha<\gamma\}\)，定义\(Y_\alpha\)为
   \begin{align*}
    &Y_0=\{I_0\}\\
    &Y_\alpha=Y_\beta\cup \{I_\alpha\}\hspace{1cm}\alpha=\beta+1\\
    &Y_\gamma=\bigcup_{\alpha<\gamma}Y_\alpha\hspace{1cm}\alpha\text{是极限序数}
   \end{align*}
   于是有
   \begin{equation*}
   Y_0\subseteq Y_1\subseteq Y_2\subseteq\cdots
   \end{equation*}
   且对于任意\(\alpha<\gamma\)，\(\abs{Y_\alpha}<\gamma\)。因为\(I'=\bigcup_{\alpha<\gamma} Y_\alpha\)，又因为\(\kappa\)正则，于是\(\abs{I'}<\kappa\)，
   因此\(\bigcap I'\in I\)，\(I\)是\(\kappa\)-完全的理想

#+END_proof
