#+LATEX_HEADER: \usepackage{cancel}
#+LATEX_HEADER: \usepackage{bussproofs}
* Prelude
  $\perp$ perp absurdity
  $\vdash$ vdash turnstile
  $\models$ models models
  $\forall$ forall
  $\exists$ exists there is
  $t_A$ the interpretation of $t$ in $A$
  $\models_A\phi$ $A$ is a model of $\phi$
  $\approx$ approx has the same cardinality as
  $\prec$ prec has smaller cardinality than
  $x\mapsto y$ mapsto $x$ maps to $y$
  $A\Rightarrow B$ Rightarrow If $A$ then $B$
  $\mathbb{N}$ the set of natural numbers

  | Frege: FRAY-ga                   | Peirce: PURSE             |
  | Hintikka: HIN-ticka              | Helena Rasiowa: he-LAY-na |
  | Leibniz: LIBE-nits               | ra-SHOW-va                |
  | Łoś: WASH                        | Scholz: SHOLTS            |
  | Łukasiewicz: woo-ka-SHAY-vitch   | Dana Scott: DAY-na SCOTT  |
  | Matiyasevich: ma-ti-ya-SAY-vitch | Sikorski: shi-COR-ski     |
  | Giuseppe Peano: ju-SEP-pe        | Van Dalen: fan DAH-len    |
  | pay-AH-no                        | Zermelo: tser-MAY-low     |
* Chap2 informal natural deduction
** sequent
   + $(\Gamma\text{ }\vdash\text{ }\psi)$ (or $\Gamma\vdash\psi$ when there is no ambiguity)
   + $\psi$ is a statement(the /conclusion/ of the sequent) and $\Gamma$ is a set of statements
     (the /assumptions/ of the sequent). Read $\Gamma$ entails $\psi$
   + means there is a proof whose conclusion is $\psi$ and whose undischarged assumptions are
     all in the set $\Gamma$
   + when $(\Gamma\text{ }\vdash\text{ }\psi)$ is true, we say the sequent is /correct/
   + if $\Gamma$ is empty, we can write $(\vdash\psi)$ (read turnstile $\psi$)
** sequent rule
   + axiom rule ::
     + if $\psi\in\Gamma$, then the sequent $(\Gamma\vdash\psi)$ is correct
   + transitive rule ::
     + if $(\Delta\vdash\psi)$ is correct and $\forall\delta\in\Delta$ $(\Gamma\vdash\delta)$,
       then $(\Gamma\vdash\psi)$
   + $\wedge I$ ::
     + if $(\Gamma\vdash\psi)$ and $(\Delta\vdash\psi)$ are correct sequents, then
       $(\Gamma\lor\Delta\vdash(\phi\wedge\psi))$
     + this is a rule about $\wedge$ and the symbol is introduced in the last sequent of the rule.
       \[\wedge\]-introduction
     + we write
       \begin{tabular}{cl}D&\\$\phi$&
       \end{tabular}
        to stand for a proof $D$ whose conclusion is $\phi$. Then \[\wedge\]-introduction is
   + $\wedge$ E ::
     + if $\Gamma\vdash(\phi\wedge\psi)$ is correct, then so are $(\Gamma\vdash\phi)$ and $(\Gamma\vdash\psi)$
   + $\to I$ ::
     + if the sequent $(\Gamma\cup\{\phi\}\vdash\psi)$ is correct then so is the sequent
       $(\Gamma\vdash(\phi\to\psi))$
   + $\to E$ ::
     + if $(\Gamma\vdash\phi)$ and ($\Delta\vdash(\phi\to\psi)$) are both correct, then $(\Gamma\cup\Delta\vdash\psi)$ is correct
     +
   + $\neg E$ ::
     + if $(\Gamma\vdash\phi)$ and $(\Delta\vdash(\neg\phi))$, then $\Gamma\cup\Delta\vdash\perp$
   + $\neg I$ ::
     + if $(\Gamma\cup\{\phi\}\vdash\perp)$, then $(\Gamma\vdash(\neg\phi))$
   + RAA ::
     + if $(\Gamma\cup\{(\neg\phi)\}\vdash\perp)$, then $(\Gamma\vdash\phi)$
   + $\lor I$ ::
     + if at least one of $(\Gamma\vdash\phi)$ and $(\Gamma\vdash\phi)$ is correct, then $(\Gamma\vdash(\phi\lor\psi))$ is true
   + $\lor E$ ::
     + if $\Gamma\cup\{\phi\}\vdash\chi$ and $\Delta\cup\{\psi\}\vdash\chi$ are correct, then $(\Gamma\cup\Delta\cup\{(\phi\lor\psi)\}\vdash\chi$) is correct
     +
** natural deduction rule
   + axiom rule ::
     + let $\psi$ be a statement, then $\psi$ is a derivation. Its conclusion is $\psi$, and it has
       one undischarged assumption, namely $\psi$
   + $\wedge$ I ::
     + if
       \begin{tabular}{c}D\\$\phi$\end{tabular} and \begin{tabular}{c}D'\\$\psi$\end{tabular}
       are derivations of $\phi$ and $\psi$ respectively, then
       \begin{tabular}{cccl}
       $D$&&$D'$&\\
       $\phi$&&$\psi$&($\wedge$I)\\\cline{1-3}
       &$(\phi\wedge\psi)$&&
       \end{tabular}
       is a derivation of $(\phi\wedge\psi)$
     + Since by axiom rule, $\phi$ by itself is a derivation of $\phi$ with undischarged
       assumption $\phi$, so D could be this derivation, thus we can write
       $\{\phi,\psi,\chi\}\vdash((\phi\wedge\psi)\wedge\chi)$
   + ($\wedge E$) ::
     + if
       \begin{tabular}{c}D\\$(\phi\wedge\psi)$\end{tabular} is a derivation of $(\phi\wedge\psi)$, then
       \begin{tabular}{cl}D&\\$(\phi\wedge\psi)$&($\wedge E$)\\\cline{1-1}$\phi$\end{tabular} and
       \begin{tabular}{cl}D&\\$(\phi\wedge\psi)$&($\wedge E$)\\\cline{1-1}$\psi$\end{tabular}

     + E is elimination and this rule is $\wedge$-elimination since the occurrence of the symbol $\wedge$
       is eliminated in the conclusion
     + wef
       \begin{prooftree}
       \AxiomC{$\phi\wedge\psi$}
       \RightLabel{$\wedge$E}
       \UnaryInfC{$\psi$}
       \AxiomC{$\phi\wedge\psi$}
       \RightLabel{$\wedge$E}
       \UnaryInfC{$\phi$}
       \RightLabel{$\wedge$I}
       \BinaryInfC{$\psi\wedge\phi$}
       \end{prooftree}
   + $\to$ I ::
     + suppose
       \begin{prooftree}
       \AxiomC{D}
       \noLine
       \UnaryInfC{$\psi$}
       \end{prooftree}
       is a derivation of $\psi$, and $\phi$ is a statement, then the following is a
       derivation of $(\phi\to\psi)$
       \begin{prooftree}
       \AxiomC{$\not\phi$}
       \noLine
       \UnaryInfC{D}
       \noLine
       \UnaryInfC{$\psi$}
       \RightLabel{$(\to$I)}
       \UnaryInfC{($\phi\to\psi$)}
       \end{prooftree}
       Its undischarged assumptions are those of $D$, except $\phi$
     + $\not\phi$ means /we are allowed to discharge any occurrencess of the/
       /assumption $\phi$ written in $D$/
   + $\to E$ ::
     + if
       \begin{prooftree}
       \AxiomC{D}
       \noLine
       \UnaryInfC{$\phi$}
       \end{prooftree}
       and
       \begin{prooftree}\AxiomC{$D'$}\noLine\UnaryInfC{$(\phi\to\psi)$}\end{prooftree}
       are derivations of $\phi$ and $(\phi\to\psi)$, then
       \begin{prooftree}
       \AxiomC{$D$}
       \noLine
       \UnaryInfC{$\phi$}
       \AxiomC{$D'$}
       \noLine
       \UnaryInfC{$(\phi\to\psi)$}
       \RightLabel{($\to$E)}
       \BinaryInfC{$\psi$}
       \end{prooftree}
       is a derivation of $\psi$. Its undischarged assumptions are
       those of $D$ together with those of $D'$
   + $\leftrightarrow I$ ::
     + If
       \begin{prooftree}
       \AxiomC{$D$}\UnaryInfC{$\phi\to\psi$}\end{prooftree} and
       \begin{prooftree}
       \AxiomC{$D'$}\UnaryInfC{$\psi\to\phi$}\end{prooftree} are derivations of ..., then
       \begin{prooftree}
       \AxiomC{$D$}
       \noLine\UnaryInfC{$(\phi\to\psi)$}
       \AxiomC{$D'$}
       \noLine\UnaryInfC{$(\psi\to\phi)$}
       \RightLabel{($\leftrightarrow$I)}
       \BinaryInfC{($\phi\leftrightarrow\psi$)}
       \end{prooftree}
   + $\leftrightarrow E$ ::
     + If
       \begin{prooftree}
       \AxiomC{$D$}
       \UnaryInfC{($\phi\leftrightarrow\psi$)}
       \end{prooftree} then
       \begin{prooftree}
       \AxiomC{$D$}
       \noLine\UnaryInfC{($\phi\leftrightarrow\psi$)}
       \RightLabel{($\leftrightarrow$)E}
       \UnaryInfC{($\phi\to\psi$)}
       \end{prooftree}
   + $\neg E$ ::
     + if
       \begin{prooftree}\AxiomC{$D$}\noLine\UnaryInfC{$\phi$}\end{prooftree} and
       \begin{prooftree}\AxiomC{$D'$}\noLine\UnaryInfC{$\neg\phi$}\end{prooftree} are derivations of $\phi$ and $\neg\phi$, then
       \begin{prooftree}
       \AxiomC{$D$}\noLine\UnaryInfC{$\phi$}
       \AxiomC{$D'$}\noLine\UnaryInfC{$\neg\phi$}
       \RightLabel{($\neg$E)}
       \BinaryInfC{$\perp$}
       \end{prooftree}
   + $(\neg I)$ ::
     + suppose
       \begin{prooftree}\AxiomC{D}\noLine\UnaryInfC{$\perp$}\end{prooftree}
       is a derivation of $\perp$, and $\phi$ is a statement, then
       \begin{prooftree}
       \AxiomC{$\not\phi$}\noLine\UnaryInfC{$D$}\noLine\UnaryInfC{$\perp$}
       \RightLabel{($\neg$I)}
       \UnaryInfC{($\neg\phi$)}
       \end{prooftree}
     + e.g. $\vdash((\neg(\phi\to\psi))\to(\neg\psi))$
       \begin{prooftree}
       \AxiomC{$\cancel{\phi}$}
       \AxiomC{$\cancel{\psi}$}
       \RightLabel{$\to$I}
       \BinaryInfC{$\phi\to\psi$}
       \AxiomC{$\neg(\phi\to\psi)$}
       \RightLabel{$\neg$E}
       \BinaryInfC{$\perp$}
       \RightLabel{$\neg$I}
       \UnaryInfC{$\neg\psi$}
       \end{prooftree}
   + RAA ::
     + woeif
       \begin{prooftree}
       \AxiomC{$\cancel{(\neg\phi)}$}
       \noLine
       \UnaryInfC{$D$}
       \noLine
       \UnaryInfC{$\perp$}
       \RightLabel{RAA }
       \UnaryInfC{$\phi$}
       \end{prooftree}
   + $\lor I$ ::
     + if
       \begin{prooftree}
       \AxiomC{$D$}
       \noLine
       \UnaryInfC{$\phi$}
       \end{prooftree} is a derivation with conclusion $\phi$, then
       \begin{prooftree}
       \AxiomC{$D$}
       \noLine
       \UnaryInfC{$\phi$}
       \UnaryInfC{$(\phi\lor\psi)$}
       \end{prooftree}
   + $\lor E$ ::
     + Given derivations
       \begin{tabular}{ccc}
       $D$&$D'$&$D''$\\
       $(\phi\lor\psi)$&$\chi$&$\chi$\\
       \end{tabular}
       we have
       \begin{tabular}{ccc}
       &$\cancel{\phi}$&$\cancel{\psi}$\\
       D &D'&D''\\
       $(\phi\lor\psi)$&$\chi$&$\chi$\\
       \hline
       &$\chi$&\\
       \end{tabular}
* Propositional logic
** LP, the language of propositions
   + propositional signature(signature)
     for each choice of signature $\sigma$ there is a dialect $LP(\sigma)$ of $LP$
   + truth function symbols :: $\wedge, \lor,\to,\leftrightarrow,\neg,\perp$
   + for each signature $\sigma$ ::
     + lexicon ::
       + of $LP(\sigma)$ is the set of symbols consisting of the truth function symbols, the parentheses,
         and the symbols
     + expression ::
       + string of one or more symbols from the lexicon of $LP(\sigma)$, the _length_ of the expression
         is the number of occurrences of symbols in it.
   + metavaraible :: $\phi,\psi,\chi$
   + formular ::
     + $\perp$ is a formula of $LP(\sigma)$, and so is every symbol in $\sigma$
     + If $\phi$ is a formula, then so is $(\neg\phi)$
     + If $\phi$ and $\psi$ are formulas of $LP(\sigma)$, then so are $(\phi\wedge\psi),(\phi\lor\psi), (\phi\to\psi),(\phi\leftrightarrow\psi)$
** Parsing trees
   + (planar) tree is an ordered pair $(N,D)$ ::
     + $N$ is a finite non-empty set whose elements are called _nodes_
     + $D$ is a function takes each node $\mu$ in $N$ to a sequence of distinct nodes
       $D(\mu)=(\nu_1,\dots,\nu_n)$, $\nu_1,\dots,\nu_n$ are called the _daughters_ of $\mu$, and $\mu$ is _mother_
     + every node except _root($\surd$)_ has exactly one mother
     + there are no cycles, that is no sequence $\nu_1,\dots,\nu_k(k>1)$ where $\nu_k=\nu_1$, and each
       $\nu_i$ with $1\le i<k$ has mother $\nu_{i+1}$
   + _labelling_ of a tree ::
     + a function $f$ defined on the set of nodes.
   + _parsing tree_ for $LP(\sigma)$ ::
     + right-labelled tree
     + $arity\le 2$
     + labelled with either $\perp$ or a symbol from $\sigma$
     + node of arity one is labelled with $\neg$
     + other node is labelled with $\wedge,\lor,\to,\leftrightarrow$
   + compositional definition $\delta$ ::
     + how to put a left labelling on any parsing tree, the left label $\delta(\mu)$ on any node $\mu$
       is determined by
       + right-hand label on $\mu$
       + the sequence of values $(\delta(\nu_1),\dots,\delta(\nu_n))$, where $\mu$ has daughters $\nu_1,\dots,\nu_n$ from left to right
   + formular ::
     + $\pi$ is a parsing tree for $LP(\sigma)$
     + _formular associated to $\pi$_ is $\delta(\pi)$, $\delta$ is compisitional definition.
     +
