#+LATEX_HEADER: \usepackage{bussproofs}
#+LATEX_HEADER: \newcommand{\bl}[1] {\boldsymbol{#1}}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \newcommand\bolden[1]{{\boldmath\bfseries#1}}
* Overview
  we call a logic *constructive* if its proofs describe effective constructions, or describe
  *algorithms*
* natural deduction
  + a
    \begin{prooftree}
    \AxiomC{}
    \RightLabel{$\top I$}
    \UnaryInfC{$\top true$}
    \end{prooftree}
  + it looks like a derivation of A ⊃ B true from
    the hypothesis A true. But the assumption A true
    is introduced in the process of proving A ⊃ B true; the conclusion should not depend
    on it! Certainly, whether the implication A⊃B is true is independent of the question
    whether A itself is actually true.
  + b
    \begin{prooftree}
    \AxiomC{$\perp$ true}
    \RightLabel{$\perp E$}
    \UnaryInfC{C true}
    \end{prooftree}
    since $\perp$ cannot be true
  + $\neg A=(A\supset \perp)$
* Proofs as program
** Propositions as types
   + $M:A$ $M$ is a proof term for proposition A, $M$ is a program of type A
     ∀M:A should correspond to a deduction of /A true/ with an identical structure and vice versa.
     Hence $M$ will correspond directly to the corresponding proof of A true
   + conjunction ::
     + a
       \begin{prooftree}
       \AxiomC{$M:A$}
       \AxiomC{$N:B$}
       \RightLabel{$\wedge I$}
       \BinaryInfC{$<M,N>:A\wedge B$}
       \end{prooftree}
       \begin{prooftree}
       \AxiomC{$M:A\wedge B$}
       \RightLabel{$\wedge E_1$}
       \UnaryInfC{\textbf{fst} $M:A$}
       \end{prooftree}
   + truth ::
     + we
        \begin{prooftree}
        \AxiomC{}
        \RightLabel{$\top I$}
        \UnaryInfC{$<>:\top$}
        \end{prooftree}
       unit type *1*
   + implication ::
     + w
       \begin{prooftree}
       \AxiomC{}
       \RightLabel{$u$}
       \UnaryInfC{$u:A$}
       \noLine
       \UnaryInfC{$\vdots$}
       \noLine
       \UnaryInfC{$M:B$}
       \RightLabel{$\supset I^u$}
       \UnaryInfC{\textbf{fn} $u\Rightarrow M:A\supset B$}
       \end{prooftree}

       \begin{prooftree}
       \AxiomC{$M:A\supset B$  $N:A$}
       \RightLabel{$\supset E$}
       \UnaryInfC{$MN:B$}
       \end{prooftree}
   + Disjunction ::
     + w
       \begin{prooftree}
       \AxiomC{$M:A$}
       \RightLabel{$\lor I_1$}
       \UnaryInfC{\textbf{inl} $M:A\lor B$}
       \end{prooftree}
       injection l/r
       \begin{prooftree}
       \AxiomC{$M:B$}
       \RightLabel{$\lor I_2$}
       \UnaryInfC{\textbf{inr} $M:A\lor B$}
       \end{prooftree}

       \begin{prooftree}
       \AxiomC{$M:A\lor B$}
       \AxiomC{}
       \RightLabel{$u$}
       \UnaryInfC{$u:A$}
       \noLine
       \UnaryInfC{$\vdots$}
       \noLine
       \UnaryInfC{$N:C$}
       \AxiomC{}
       \RightLabel{$w$}
       \UnaryInfC{$w:B$}
       \noLine
       \UnaryInfC{$\vdots$}
       \noLine
       \UnaryInfC{$O:C$}
       \RightLabel{$\lor E^{u,w}$}
       \TrinaryInfC{\textbf{case} $M$ \textbf{of inl} $u\Rightarrow N$ | \textbf{inr} $w\Rightarrow O:C$}
       \end{prooftree}
   + Falsehood ::
     + w
       \begin{prooftree}
       \AxiomC{$M:\perp$}
       \RightLabel{$\perp E$}
       \UnaryInfC{\textbf{abort} $M:C$}
       \end{prooftree}
   + guiding principles behind the assignment of proof terms to deductions ::
     1. For every deduction of A true there is a proof term M and deduction of $M:A$
     2. For every deduction of M : A there is a deduction of A true
     3. The correspondence between proof terms M and deductions of A true is a bijection.
** Reduction
   + Conjunction ::
     + $\textbf{fst}<M,N>\Rightarrow_R M$
   + Implication ::
     + *λ-abstraction*
       $f(3)=(\lambda x.x^2+x-1)(3)=[3/x](x^2+x-1)=11$
       $(\textbf{fn} u\Rightarrow M)N\Rightarrow_R[N/u]M$
   + Disjunction ::
     + $\textbf{case inl } M \textbf{of inl } u\Rightarrow N | \textbf{inr} w\Rightarrow O
       \Rightarrow_R[M/u]N$
   + Example ::
     + for $\textsf{comp}:((A\supset B)\wedge(B\supset C))\supset(A\supset C)$
       \begin{align*}
       \textsf{comp}<f,g>(w)&=g(f(w))\\
       \textsf{comp}<f,g>&=\textsf{fn } w\Rightarrow g(f(w))\\
       \textsf{comp } u&=\textsf{fn } w\Rightarrow (\textbf{snd } u)((\textbf{fst } u)(w))\\
       \textsf{comp}&=\textsf{fn } u\Rightarrow \textsf{fn } w\Rightarrow(\textbf{snd } u)((\textbf{fst } u) w)
       \end{align*}
     +
* Harmony
** Local soundness and local completeness
   + local soundness ::
     + the elimination rules are not too strong : no matter how we apply
       elimination rules to the result of an introduction we cannot gain
       any new information.
       Witnessed by a *local reduction*
   + local completeness ::
     + the elimination rules are not too weak: there is always a way to apply elimination
       rules so that we can reconsitute a proof of the original proposition from the
       results by applying introduction rules.
       Witnessed by a *local expansion*
   +
#+BEGIN_SRC latex
  \begin{prooftree}
    \AxiomC{$\mathcal{D}$}
    \noLine
    \UnaryInfC{A true}
  \end{prooftree}
  $\Rightarrow_R$
  \begin{prooftree}
    \AxiomC{$\mathcal{D'}$}
    \noLine
    \UnaryInfC{A true}
  \end{prooftree}
#+END_SRC
     for the local reduction of a deduction $\mathcal{D}$ to another deduction $\mathcal{D'}$ of the same judgement
     $A true$
   +
* Verification
** Introduction
   + the meaning of a proposition is determined by its *verification*
   + $A\uparrow$ for _A has a verification_
   + $A\downarrow$ A may be used
   + conjunction ::
     + w
       \begin{prooftree}
       \AxiomC{$A\uparrow$ $B\uparrow$}
       \RightLabel{$\wedge I$}
       \UnaryInfC{$A\wedge B\uparrow$}
       \end{prooftree}
       A verification $A\wedge B\uparrow$ of $A\wedge B$ will continue to seek a verification
       $A\uparrow$ of A as well as a verification $B\uparrow$ of B
       \begin{prooftree}
       \AxiomC{$A\wedge B\downarrow$}
       \RightLabel{$\wedge E_1$}
       \UnaryInfC{$A\downarrow$}
       \end{prooftree}
       If we have license $A\wedge B\downarrow$ to use $A\wedge B$, then we also have license $A\downarrow$ to use A
   + implication ::
     + Introduction rules creates a new hypothesis, which we may use in a proof.
       \begin{prooftree}
       \AxiomC{}
       \RightLabel{$u$}
       \UnaryInfC{$A\downarrow$}
       \noLine
       \UnaryInfC{$\vdots$}
       \noLine
       \UnaryInfC{$B\uparrow$}
       \RightLabel{$\supset I^u$}
       \UnaryInfC{$A\supset B\uparrow$}
       \end{prooftree}
       consist of a verification $B\uparrow$ of B that has license $A\downarrow$ to use the
       additional hypothesis A
       in order to use an implication $A\supset$ we first require a verification of A
       \begin{prooftree}
       \AxiomC{$A\supset B\downarrow$ $A\uparrow$}
       \RightLabel{$\supset E$}
       \UnaryInfC{$B\downarrow$}
       \end{prooftree}

   + disjunction ::
     + w
       \begin{prooftree}
     +
     +
