#+TITLE: Logic and Game Theory
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: latex/LogicandGameTheory/LogicandGameTheory.tex

* Lec 2 An invitation to game theory
  Every game has three main ingredients:
  1. the set of players, $[n]=\lb 1,2,\dots,n\rb$
  2. the rule of game
  3. *outcomes* or winning conditions


  The game arena, that gives the rules of the game, can be envisaged as a finite
  graph
  * vertices denote game positions
  * edges correspond to moves
  * each vertex is labelled by the player whose turn it is to move
  * winning conditions are not present in the arena


  Game tree: the tree unfolding of a game arena is *extensive form*
  

  Consider two-person zero-sum games of perfect information. $N=\lb 1,2\rb$.
  $\Sigma=\lb a_1,a_2,\dots,a_m\rb$ is a finite set of action symbols,
  representing move of players, common for both players. Such games are referred
  as *bipartisan games*


  A *game arena* is a graph 
  $\calg=(W,\to,s_0)$ with $W=\bcup_{i\in N}W^i\bcup\lb W^\text{leaf}\rb$. For
  $i\in N, W^i$ is the set of /game positions/ for player $i$ and $W^\text{leaf}$
  is the set of terminal game positions. $s_0$ is the initial node of the game.
  $\to:(W\times \Sigma)\to W$, is a partial function called the move function


  If a player $i$ owns the game position $s_0, s_0\in W^i$ then she picks an
  action $a'$ and moves to token to $s'$, $s_0\xrightarrow{a} s'$
  A play in $calg$ is a path $\rho:s_0a_0s_1a_1\dots$ where 
  $\forall j:s_j\xrightarrow{a_j}s_{j+1}$
