#+TITLE: Logic and Game Theory
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: latex/LogicandGameTheory/LogicandGameTheory.tex

* Lec 2 An invitation to game theory
  Every game has three main ingredients:
  1. the set of players, $[n]=\lb 1,2,\dots,n\rb$
  2. the rule of game
  3. *outcomes* or winning conditions


  The game arena, that gives the rules of the game, can be envisaged as a finite
  graph
  * vertices denote game positions
  * edges correspond to moves
  * each vertex is labelled by the player whose turn it is to move
  * winning conditions are not present in the arena


  Game tree: the tree unfolding of a game arena is *extensive form*
  

  Consider two-person zero-sum games of perfect information. $N=\lb 1,2\rb$.
  $\Sigma=\lb a_1,a_2,\dots,a_m\rb$ is a finite set of action symbols,
  representing move of players, common for both players. Such games are referred
  as *bipartisan games*


  A *game arena* is a graph 
  $\calg=(W,\to,s_0)$ with $W=\bcup_{i\in N}W^i\bcup\lb W^\text{leaf}\rb$. For
  $i\in N, W^i$ is the set of /game positions/ for player $i$ and $W^\text{leaf}$
  is the set of terminal game positions. $s_0$ is the initial node of the game.
  $\to:(W\times \Sigma)\to W$, is a partial function called the move function


  If a player $i$ owns the game position $s_0, s_0\in W^i$ then she picks an
  action $a'$ and moves to token to $s'$, $s_0\xrightarrow{a} s'$
  A play in $calg$ is a path $\rho:s_0a_0s_1a_1\dots$ where 
  $\forall j:s_j\xrightarrow{a_j}s_{j+1}$


  let $\calg_t$ denote the tree unfolding of the arena $\calg$. A *strategy* for
  player $i,\mu=(W_\mu,\to_\mu,s_0)$ is a maximal connected subtree of $\calg_T$
  where for each player $i$ node, there is a unique outgoing edge and for the
  other player every move is included. That is, for $s\in W_\mu$, if $s\in
  W^i_\mu$ then there exists a unique $a\in\Sigma$ s.t. $s\xrightarrow{a}_\mu
  s'$ where we have $s\xrightarrow{a}_T s'$. If $s\in W_\mu^j(j\neq i)$, then
  for each $s'$ s.t. $s\xrightarrow{a}_Ts'$, we have $s\xrightarrow{a}_\mu s'$ 


  A *strategy profile* is a pair $<\mu,\tau>$ that fixes a strategy for each
  player. A *winning strategy* $\sigma$ for player $i$ if every strategy $\tau$ of
  the opponent $i$ wins.


  A win/lose game is *determined* if starting from any game position, one of the
  players has a winning strategy


  \begin{theorem}
  In every \textbf{finite} extensive form game of perfect information, we can compute whether
  player $i$ can win. (Zermelo 1913)
  \end{theorem}
  \begin{proof}
  Backward induction
  \end{proof}

** Analysis of Nim
   \begin{lemma}
   For all $m,n\ge0, (m,n)$ is winning iff $m\neq n$
   \end{lemma}

   Every finite extensive form game is of the form $0$ or
   \begin{equation*}
   g_1+g_2+\dots+g_m
   \end{equation*}
   0 is the empty game, where no player can make any move
   , $g_1,g_2,\dots,g_m$ are subgames


   If $g=g_1+\dots+g_m, h=h_1+\dots+h_m$, then
   \begin{equation*}
   g+h=(g_1+h)+\dots+(g_m+h)+(g+h_1)+\dots+(g+h_n)
   \end{equation*}
   When $g$ is a subgame of $h$, we write $g\le h$


   *$g_1\equiv g_2$* if for all $h$, $g_1+h$ is winning(losing) iff $g_2+h$ is
   winning(losing).


   $\equiv$ is an equivalence relation


   \begin{lemma}[The loser's lemma]\leavevmode
   If $g$ is losing then $g\equiv 0$
   \end{lemma}

   \begin{proof}
   \;\par
   \begin{enumerate}
   \item fix a losing game $g$
   \item prove: for all $h, g+h$ is losing iff $h$ is losing
   \item Assuming this, suppose $h$ is winning, then there is a move to $h'$
   that is losing. Hence $g+h'$ is losing and $g+h$ is winning
   \end{enumerate}
   \end{proof}
   

   \begin{lemma}
   If $h$ and $g$ are losing, so is $g+h$
   \end{lemma}
   \begin{proof}
   IH1(inductive hypothesis): for all $g'\le g$, if $h$ is losing, then so is $g'+h$

   IH2: for all $h'\le h$, if $h$ is losing, then so is $g+h'$

   Every initial move in $g+h$ is either in $g$ or $h$. First consider the latter.
   $h$ is losing, so every move in $h$ to $h'$ is winning
   \end{proof}


   \begin{corollary}
   if $h$ is losing, then for all $g$, $g+h=g$
   \end{corollary}
* lec3: Normal form games
  $N=\{1,2,\dots,n\}$ the set of players

  For each $i\in N$, a *finite* set $S_i=\{1,\dots,m_i\}$ of 
  \textcolor{cyan}{pure strategies}. $S=\displaystyle\prod_{i\in N}S_i$  set of
  combinations of pure strategies

  For each $i\in N$, a *payoff(utility)* function $u_i:S\to \mathcal{R}$

  *Iterate elimination of dominated strategies*. Dominated equilibrium(no matter
  what the opponent chooses)


  *Nash equilibrium*. each player chooses the best according to what his opponent
  chooses

  $p_i:S\to\mathcal{R}$.
  $s_{-i}$ denotes the tupple $(s_j)_{j\neq i}$. A strategy $s_i\in S_i$ is a
  *best response* to $s_{-i}$ if for all $s_i'\in S_i,p_i(s_i,s_{-i})\ge
  p_i(s_i',s_{-i})$. A profile $s$ is a *Nash equilibrium* if for all $i$, $s_i$
  is a best response to $s_{-i}$. A profile $s$ is *Pareto efficient* if there
  doesn't exist any profile $s'$ s.t. for all $i$, $p_i(s')\ge p_i(s)$ and for
  some $i$, $p_i(s')>p_i(s)$


  $s_i$ *strictly dominates* $s_i'$ if for all $s_{-i}$,
  $p_i(s_i,s_{-i})>p_i(s_i',s_{-i})$. *Dominate* if $\ge$. $s_i$ *weakly dominates*
  $s_i'$ if for all $s_{-i}$, $p_i(s_i,s_{-i})\ge p_i(s_i',s_{-i})$ and there
  exists $s_{-i}$ s.t. $p_i(s_i,s_{-i})>p_i(s_i',s_{-i})$

  \begin{proposition}
  \begin{itemize}
  \item If $s$ is a profile s.t. each $s_i$ is dominant, then $s$ is a Nash 
  equilibrium
  \item If $s$ is a profile s.t. each $s_i$ is weakly dominant, then $s$ is a 
  Nash equilibrium
  \item If each $s_i$ is strictly dominant, then $s$ is a unique Nash 
  equilibrium. The converse is not true
  \end{itemize}
  \end{proposition}


  Fix $R_i\subseteq S_i$. $R=(R_1,\dots,R_n,p_1,\dots,p_n)$ is a *restriction* of
  the game. Let $R=\displaystyle\prod_{i\in N}R_i$. *Reduction* between
  restrictions: $R\to_S R'$ if $R'$ results as a result of removing from it some
  SDS's: $R\neq R'$, for all $i$, $R_i'\subseteq R_i$ and for all $i$, for all
  $s_i\in(R_i-R_i')$ there exists $s_i'\in R_i$ s.t. $s_i'$ strictly dominates
  $s_i$. If no restriction $R'$ of $G$, $R\to_S R'$, then R is an *outcome* of
  IESDS. If $\abs{R_i}=1$ for all $i$, then $G$ is *solved* by IESDS

  /IESDS is justified by the assumption of common knowledge of rationality/


  \begin{proposition}
  \begin{itemzie}
  \item Let $G'$ be an IESDS outcome of $G$. Then every Nash equilibrium of $G$ is also
  a Nash equilibrium of $G'$
  \item If $G$ is finite, then every Nash equilibrium of $G'$ is also a Nash
  equilibrium of $G$
  \item If G is finite and solve by IESDS the outcome is a unique Nash equilibrium
  \end{itemzie}
  \end{proposition}


  *weakly dominated strategies*. In general, outcomes are not unique.
  \begin{proposition}
  \begin{itemzie}
  \item Let $G'$ be an IEWDS outcome of $G$. If $G$ is finite, then every Nash equilibrium
  of $G'$ is also a Nash equilibrium
  \item If G is finite and solved by IEWDS the outcome is a Nash equilibrium of G
  \end{itemzie}
  \end{proposition}


  It also makes sense to eliminate strategies that are not best responses to any
  opponent strategies.
