#+TITLE: Rough Sets: Theoretical aspects of reasoning about data

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: latex/RoughSets/RoughSets.tex
* Knowledge
** Knowledge base
   Given a finite set $U\neq \emptyset$ (the universe). Any subset $X\subset U$
   of the universe is called a *concept* or a *category* in $U$. And any family of
   concepts in $U$ will be referred to as *abstract knowledge* about $U$.
   
   *partition* or *classification* of a certain universe $U$ is a family 
   $C=\lb X_1,X_2,\dots,X_n\rb$ s.t. $X_i\subset U,X_i\neq\emptyset,X_i\cap
   X_j=\emptyset$ and $\bigcup X_i=U$

   A family of classifications is called a *knowledge base* over $U$


   $R$ an equivalence relation over $U$, $U/R$ family of all equivalence classes
   of $R$, referred to be *categories* or *concepts* of $R$, and $[x]_R$ denotes a
   category in $R$ containing an element $x\in U$

   By a *knowledge base* we can understand a relational system $K=(U,\bR)$, $\bR$
   is a family of equivalence relations over $U$

   If $\bP\subset \bR$ and $\bP\neq\emptyset$, then $\bigcap\bP$ is also an
   equivalence relation, and will be denoted by $IND(\bP)$, called an
   *indiscernibility relation* over $\bP$
   \begin{equation*}
   [x]_{IND(\bP)}=\bigcap_{R\in\bP}[x]_R
   \end{equation*}
   
   $U/IND(\bP)$ called $\bP\textbf{-basic}$ *knowledge about* $U$ in $K$. For
   simplicity, $U/\bP=U/IND(\bP)$ and $\bP$ will be also called
   $\bP\textbf{-basic}$ *knowledge*
   . Equivalence classes of $IND(\bP)$ are called
   *basic categories* of knowledge $\bP$. If $Q\in\bR$, then $Q$ is a
   $Q\textbf{-elementary}$ *knowledge* and equivalence classes of $Q$ are referred
   to as $Q\textbf{-elementary}$ *concepts* of knowledge $\bR$

   The family of all $\bP\text{-basic}$ categories for all
   $\empty\neq\bP\subset\bR$ will be called the *family of basic categories* in
   knowledge base $K=(U,\bR)$

   Let $K=(U,\bR)$ be a knowledge base. By $IND(K)$ we denote the family of all
   equivalence relations defined in $K$ as $IND(K)=\lb
   IND(\bP):\emptyset\neq\bP\subseteq\bR\rb$.
   
   Thus $IND(K)$ is the minimal set of equivalence relations.

   Every union of $\bP\text{-basic}$ categories will be $\bP\textbf{-category}$

   The family of all categories in the knowledge base $K=(U,\bR)$ will be
   referred to as $K\textbf{-categories}$
** Equivalence, generalization and specialization of knowledge
   Let $K=(U,\bP),K'=(U,\bQ)$. $K$ and $K'$ are *equivalent* $K\simeq
   K',(\bP\simeq\bQ)$ if $IND(\bP)=IND(\bQ)$. Hence $K\simeq K'$ if both $K$ and
   $K'$ have the same set of elememtary categories. /This means that knowledge in
   knowledge bases $K$ and $K'$ enables us to express exactly the same facts about the universe./

   If $IND(\bP)\subset IND(\bQ)$ then knowledge $\bP$ is *finer* than knowledge
   $\bQ$ (*coarser*). $\bP$ is *specialization* of $\bQ$ and $\bQ$ is *generalization*
   of $\bP$
* Imprecise categories, approximations and rough sets
** Rough sets
   Let $X\subseteq U$. $X$ is $R\textbf{-definable}$ or $R\textbf{-exact}$ if $X$ is the union of some
   $R\text{-basic}$ categories. otherwise
   $R\textbf{-undefinable},R\textbf{-rough},R\textbf{-inexact}$  .
** Approximations of set
   Given $K=(U,\bR), R\in IND(K)$
   \begin{align*}
   &\underline{R}X=\bigcup\lb Y\in U/R:Y\subseteq X\rb\\
   &\overline{R}X=\bigcup\lb Y\in U/R:Y\cap X\neq\emptyset\rb\\
   \end{align*}
   called the $R\textbf{-lower}$ and $R\textbf{-upper}$ *approximation* of $X$

   $BN_R(X)=\overline{R}X-\underline{R}X$ is $R\textbf{-boundary}$ of $X$.
   $BN_R(X)$ is the set of elements which cannot be classified either to $X$ or
   to $-X$ having knowledge $R$

   \begin{align*}
   &POS_R(X)=\underline{R}X,R\text{-positive region of } X\\
   &NEG_R(X)=U-\overline{R}X,R\text{-negative region of } X\\
   &BN_R(X) - R\text{-borderline region of } X\\
   \end{align*}

   If $x\in POS(X)$, then $x$ will be called an $R\textbf{-positive}$ *example of* $X$

   \begin{proposition}
   \begin{enumerate}
   \item $X$ is $R$-definable if and only if $\underline{R}X=\overline{R}X$
   \item $X$ is rought w.r.t. $R$ if and only if $\underline{R}X\neq\overline{R}X$
   \end{enumerate}
   \end{proposition}
** Properties of approximations
   #+ATTR_LATEX: :options [2.2]
   #+BEGIN_proposition
   1. $\uR X\subseteq X\subseteq \oR X$   
   2. $\uR\emptyset=\uR\emptyset=\emptyset;\quad \uR U=\oR U=U$
   3. $\oR(X\cup Y)=\oR X\cup \oR Y$
   4. $\uR(X\cap Y)=\uR X\cap \uR Y$
   5. $X\subseteq Y$ implies $\uR X\subseteq \uR Y$
   6. $X\subseteq Y$ implies $\oR X\subseteq\oR Y$
   7. $\uR(X\cup Y)\subseteq \uR X\cup \uR Y$
   8. $\uR(-X)=-\oR X$
   9. $\oR(-X)=-\uR X$
   10. $\oR(-X)=-\uR X$
   11. $\uR\uR X=\oR\uR X=\uR X$
   12. $\oR\oR X=\uR\oR X=\oR X$
   #+END_proposition

   The equivalence relation $R$ over $U$ uniquely defines a topological space
   $T=(U,DIS(R))$ where $DIS(R)$ is the familty of all open and closed set in
   $T$ and $U/R$ is a base for $T$. The $R\text{-lower}$ and $R\text{-upper}$
   approximation of $X$ in $A$ are *interior* and *closure* operations in the
   topological space $T$
** Approximations and membership relation
   \begin{align*}
   &x\underline{\in}_RX \text{if and only if } x\in\underline{R}X\\
   &x\overline{\in}_RX \text{if and only if } x\in\overline{R}X\\
   \end{align*}
   where $\underline{\in}_R$ read "$x$ *surely belongs* to $X$ w.r.t. $R$" and
   $\overline{\in}_R$ - "$x$ *possibly belongs* to $X$ w.r.t. $R$". The *lower* and
   *upper* membership.
   \begin{proposition}
   \begin{enumerate}
   \item $x\uin X$ implies $x\in X$ implies $x\oin X$
   \item $X\subset Y$ implies ($x\uin X$ implies $x\uin Y$ and $x\oin X$ implies $x\oin Y$)
   \item $x\oin(X\cup Y)$ if and only if $x\oin X$ or $x\oin Y$
   \item $x\uin(X\cap Y)$ if and only if $x\uin X$ and $x\uin Y$
   \item $x\uin X$ or $x\uin Y$ implies $x\uin (X\cup Y)$
   \item $x\oin X\cap Y$ implies $x\oin X$ and $x\oin Y$
   \item $x\uin (-X)$ if and only if non $x\oin X$
   \item $x\oin (-X)$ if and only if non $x\uin X$
   \end{enumerate}
   \end{proposition}
** Numerical characterization of imprecision
   *accuracy measure*
   \begin{equation*}
   \alpha_R(X)=\frac{card\;\uR}{card\;\oR}
   \end{equation*}
** Topological characterization of imprecision
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   1. If $\uR X\neq\emptyset$ and $\oR X\neq U$, then we say that $X$ is
      *roughly R-definable*. We can decide whether some elements belong to $X$
      or $-X$
   2. If $\uR X=\emptyset$ and $\oR X\neq U$, then we say that $X$ is
      *internally R-undefinable*. We can decide whether some elemnts belong
      to $-X$
   3. If $\uR X\neq\emptyset$ and $\oR X=U$, then we say that $X$ is
      *externally R-undefinable*. We can decide whether some elements belong
      to $X$
   4. If $\uR X=\emptyset$ and $\oR X=U$, then we say that $X$ is
      *totally R-undefinable*. unable to decide
   #+END_definition

   #+ATTR_LATEX: :options [2.4]
   #+BEGIN_proposition
   1. Set $X$ is R-definable(roughly R-definable, totally R-undefinable) if and
      only if so is $-X$
   2. Set $X$ is externally R-undefinable if and only if $-X$ is internally
      R-undefinable 
   #+END_proposition

   #+BEGIN_proof
   1. 
      \begin{align*}
      R\text{-definable}&\Leftrightarrow \uR X=\oR X, \uR\neq\emptyset,\oR\neq U\\
      &\Leftrightarrow -\uR X=-\oR X\\
      &\Leftrightarrow \oR(-X)=\uR(-X)\\
      \end{align*}

      \begin{align*}
      $X$ \text{ is roughly } R\text{-definable}
      &\Leftrightarrow \uR X\neq \emptyset\wedge\oR X\neq U\\
      &\Leftrightarrow -\uR X\neq U\wedge -\oR X\neq \emptyset\\
      &\Leftrightarrow \oR(-X)\neq U\wedge \uR(-X)\neq \emptyset\\
      \end{align*}
   #+END_proof
** Approximation of classifications
   If $F=\lb X_1,\dots,X_n\rb$ is a family of non empty sets, then
   $\uR F=\lb \uR X_1,\dots,\uR X_n\rb$ and $\oR F=\lb\oR X_1,\dots,\oR X_n\rb$,
   called the $R\textbf{-lower}$ *approximation* and the $R\textbf{-upper}$
   *approximation* of the family $F$

   The *accuracy of approximation* of $F$ by $R$ is
   \begin{equation*}
   \alpha_R(F)=\frac{\displaystyle\sum card\;\uR X_i}
   {\displaystyle\sum card\;\oR X_i}
   \end{equation*}

   *quality of approximation* of $F$ by $R$
   \begin{equation*}
   \gamma_R(F)=\frac{\displaystyle\sum card\;\uR X_i}{card\; U}
   \end{equation*}

   #+ATTR_LATEX: :options [2.5]
   #+BEGIN_proposition
   Let $F=\lb X_1,\dots,X_n\rb$ where $n>1$ be a classification of $U$ and let
   $R$ be an equivalence relation. If there exists $i\in\lb 1,2,\dots,n\rb$ s.t.
   $\uR X_i\neq\emptyset$, then for each $j\neq i$ and $j\in\lb 1,\dots,n\rb$,
   $\oR X_j\neq U$
   #+END_proposition
