#+TITLE: Rough Sets: Theoretical aspects of reasoning about data

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: latex/RoughSets/RoughSets.tex
* Knowledge
** Knowledge base
   Given a finite set $U\neq \emptyset$ (the universe). Any subset $X\subset U$
   of the universe is called a *concept* or a *category* in $U$. And any family of
   concepts in $U$ will be referred to as *abstract knowledge* about $U$.
   
   *partition* or *classification* of a certain universe $U$ is a family 
   $C=\lb X_1,X_2,\dots,X_n\rb$ s.t. $X_i\subset U,X_i\neq\emptyset,X_i\cap
   X_j=\emptyset$ and $\bigcup X_i=U$

   A family of classifications is called a *knowledge base* over $U$


   $R$ an equivalence relation over $U$, $U/R$ family of all equivalence classes
   of $R$, referred to be *categories* or *concepts* of $R$, and $[x]_R$ denotes a
   category in $R$ containing an element $x\in U$

   By a *knowledge base* we can understand a relational system $K=(U,\bR)$, $\bR$
   is a family of equivalence relations over $U$

   If $\bP\subset \bR$ and $\bP\neq\emptyset$, then $\bigcap\bP$ is also an
   equivalence relation, and will be denoted by $IND(\bP)$, called an
   *indiscernibility relation* over $\bP$
   \begin{equation*}
   [x]_{IND(\bP)}=\bigcap_{R\in\bP}[x]_R
   \end{equation*}
   
   $U/IND(\bP)$ called $\bP\textbf{-basic}$ *knowledge about* $U$ in $K$. For
   simplicity, $U/\bP=U/IND(\bP)$ and $\bP$ will be also called
   $\bP\textbf{-basic}$ *knowledge*
   . Equivalence classes of $IND(\bP)$ are called
   *basic categories* of knowledge $\bP$. If $Q\in\bR$, then $Q$ is a
   $Q\textbf{-elementary}$ *knowledge* and equivalence classes of $Q$ are referred
   to as $Q\textbf{-elementary}$ *concepts* of knowledge $\bR$

   The family of all $\bP\text{-basic}$ categories for all
   $\empty\neq\bP\subset\bR$ will be called the *family of basic categories* in
   knowledge base $K=(U,\bR)$

   Let $K=(U,\bR)$ be a knowledge base. By $IND(K)$ we denote the family of all
   equivalence relations defined in $K$ as $IND(K)=\lb
   IND(\bP):\emptyset\neq\bP\subseteq\bR\rb$.
   
   Thus $IND(K)$ is the minimal set of equivalence relations.

   Every union of $\bP\text{-basic}$ categories will be $\bP\textbf{-category}$

   The family of all categories in the knowledge base $K=(U,\bR)$ will be
   referred to as $K\textbf{-categories}$
** Equivalence, generalization and specialization of knowledge
   Let $K=(U,\bP),K'=(U,\bQ)$. $K$ and $K'$ are *equivalent* $K\simeq
   K',(\bP\simeq\bQ)$ if $IND(\bP)=IND(\bQ)$. Hence $K\simeq K'$ if both $K$ and
   $K'$ have the same set of elememtary categories. /This means that knowledge in
   knowledge bases $K$ and $K'$ enables us to express exactly the same facts about the universe./

   If $IND(\bP)\subset IND(\bQ)$ then knowledge $\bP$ is *finer* than knowledge
   $\bQ$ (*coarser*). $\bP$ is *specialization* of $\bQ$ and $\bQ$ is *generalization*
   of $\bP$
* Imprecise categories, approximations and rough sets
** Rough sets
   Let $X\subseteq U$. $X$ is $R\textbf{-definable}$ or $R\textbf{-exact}$ if $X$ is the union of some
   $R\text{-basic}$ categories. otherwise
   $R\textbf{-undefinable},R\textbf{-rough},R\textbf{-inexact}$  .
** Approximations of set
   Given $K=(U,\bR), R\in IND(K)$
   \begin{align*}
   &\underline{R}X=\bigcup\lb Y\in U/R:Y\subseteq X\rb\\
   &\overline{R}X=\bigcup\lb Y\in U/R:Y\cap X\neq\emptyset\rb\\
   \end{align*}
   called the $R\textbf{-lower}$ and $R\textbf{-upper}$ *approximation* of $X$

   $BN_R(X)=\overline{R}X-\underline{R}X$ is $R\textbf{-boundary}$ of $X$.
   $BN_R(X)$ is the set of elements which cannot be classified either to $X$ or
   to $-X$ having knowledge $R$

   \begin{align*}
   &POS_R(X)=\underline{R}X,R\text{-positive region of } X\\
   &NEG_R(X)=U-\overline{R}X,R\text{-negative region of } X\\
   &BN_R(X) - R\text{-borderline region of } X\\
   \end{align*}

   If $x\in POS(X)$, then $x$ will be called an $R\textbf{-positive}$ *example of* $X$

   \begin{proposition}
   \begin{enumerate}
   \item $X$ is $R$-definable if and only if $\underline{R}X=\overline{R}X$
   \item $X$ is rought w.r.t. $R$ if and only if $\underline{R}X\neq\overline{R}X$
   \end{enumerate}
   \end{proposition}
** Properties of approximations
   #+ATTR_LATEX: :options [2.2]
   #+BEGIN_proposition
   1. $\uR X\subseteq X\subseteq \oR X$   
   2. $\uR\emptyset=\uR\emptyset=\emptyset;\quad \uR U=\oR U=U$
   3. $\oR(X\cup Y)=\oR X\cup \oR Y$
   4. $\uR(X\cap Y)=\uR X\cap \uR Y$
   5. $X\subseteq Y$ implies $\uR X\subseteq \uR Y$
   6. $X\subseteq Y$ implies $\oR X\subseteq\oR Y$
   7. $\uR(X\cup Y)\subseteq \uR X\cup \uR Y$
   8. $\uR(-X)=-\oR X$
   9. $\oR(-X)=-\uR X$
   10. $\oR(-X)=-\uR X$
   11. $\uR\uR X=\oR\uR X=\uR X$
   12. $\oR\oR X=\uR\oR X=\oR X$
   #+END_proposition

   The equivalence relation $R$ over $U$ uniquely defines a topological space
   $T=(U,DIS(R))$ where $DIS(R)$ is the familty of all open and closed set in
   $T$ and $U/R$ is a base for $T$. The $R\text{-lower}$ and $R\text{-upper}$
   approximation of $X$ in $A$ are *interior* and *closure* operations in the
   topological space $T$
** Approximations and membership relation
   \begin{align*}
   &x\underline{\in}_RX \text{if and only if } x\in\underline{R}X\\
   &x\overline{\in}_RX \text{if and only if } x\in\overline{R}X\\
   \end{align*}
   where $\underline{\in}_R$ read "$x$ *surely belongs* to $X$ w.r.t. $R$" and
   $\overline{\in}_R$ - "$x$ *possibly belongs* to $X$ w.r.t. $R$". The *lower* and
   *upper* membership.
   \begin{proposition}
   \begin{enumerate}
   \item $x\uin X$ implies $x\in X$ implies $x\oin X$
   \item $X\subset Y$ implies ($x\uin X$ implies $x\uin Y$ and $x\oin X$ implies $x\oin Y$)
   \item $x\oin(X\cup Y)$ if and only if $x\oin X$ or $x\oin Y$
   \item $x\uin(X\cap Y)$ if and only if $x\uin X$ and $x\uin Y$
   \item $x\uin X$ or $x\uin Y$ implies $x\uin (X\cup Y)$
   \item $x\oin X\cap Y$ implies $x\oin X$ and $x\oin Y$
   \item $x\uin (-X)$ if and only if non $x\oin X$
   \item $x\oin (-X)$ if and only if non $x\uin X$
   \end{enumerate}
   \end{proposition}
** Numerical characterization of imprecision
   *accuracy measure*
   \begin{equation*}
   \alpha_R(X)=\frac{card\;\uR}{card\;\oR}
   \end{equation*}
** Topological characterization of imprecision
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   1. If $\uR X\neq\emptyset$ and $\oR X\neq U$, then we say that $X$ is
      *roughly R-definable*. We can decide whether some elements belong to $X$
      or $-X$
   2. If $\uR X=\emptyset$ and $\oR X\neq U$, then we say that $X$ is
      *internally R-undefinable*. We can decide whether some elemnts belong
      to $-X$
   3. If $\uR X\neq\emptyset$ and $\oR X=U$, then we say that $X$ is
      *externally R-undefinable*. We can decide whether some elements belong
      to $X$
   4. If $\uR X=\emptyset$ and $\oR X=U$, then we say that $X$ is
      *totally R-undefinable*. unable to decide
   #+END_definition

   #+ATTR_LATEX: :options [2.4]
   #+BEGIN_proposition
   1. Set $X$ is R-definable(roughly R-definable, totally R-undefinable) if and
      only if so is $-X$
   2. Set $X$ is externally R-undefinable if and only if $-X$ is internally
      R-undefinable 
   #+END_proposition

   #+BEGIN_proof
   1. 
      \begin{align*}
      R\text{-definable}&\Leftrightarrow \uR X=\oR X, \uR\neq\emptyset,\oR\neq U\\
      &\Leftrightarrow -\uR X=-\oR X\\
      &\Leftrightarrow \oR(-X)=\uR(-X)\\
      \end{align*}

      \begin{align*}
      X \text{ is roughly } R\text{-definable}
      &\Leftrightarrow \uR X\neq \emptyset\wedge\oR X\neq U\\
      &\Leftrightarrow -\uR X\neq U\wedge -\oR X\neq \emptyset\\
      &\Leftrightarrow \oR(-X)\neq U\wedge \uR(-X)\neq \emptyset\\
      \end{align*}
   #+END_proof
** Approximation of classifications
   If $F=\lb X_1,\dots,X_n\rb$ is a family of non empty sets, then
   $\uR F=\lb \uR X_1,\dots,\uR X_n\rb$ and $\oR F=\lb\oR X_1,\dots,\oR X_n\rb$,
   called the $R\textbf{-lower}$ *approximation* and the $R\textbf{-upper}$
   *approximation* of the family $F$

   The *accuracy of approximation* of $F$ by $R$ is
   \begin{equation*}
   \alpha_R(F)=\frac{\displaystyle\sum card\;\uR X_i}
   {\displaystyle\sum card\;\oR X_i}
   \end{equation*}

   *quality of approximation* of $F$ by $R$
   \begin{equation*}
   \gamma_R(F)=\frac{\displaystyle\sum card\;\uR X_i}{card\; U}
   \end{equation*}

   #+ATTR_LATEX: :options [2.5]
   #+BEGIN_proposition
   Let $F=\lb X_1,\dots,X_n\rb$ where $n>1$ be a classification of $U$ and let
   $R$ be an equivalence relation. If there exists $i\in\lb 1,2,\dots,n\rb$ s.t.
   $\uR X_i\neq\emptyset$, then for each $j\neq i$ and $j\in\lb 1,\dots,n\rb$,
   $\oR X_j\neq U$
   #+END_proposition

   #+BEGIN_proof
   If $\uR X_i\neq\emptyset$ then there exists $x\in X$ s.t. $[x]_R\subseteq X$,
   which implies $[x]_R\cap X_j=\emptyset$ for each $j\neq i$. This yields $\oR
   X_j\cap[x]_R=\emptyset$.
   #+END_proof

   #+ATTR_LATEX: :options [2.6]
   #+BEGIN_proposition
   Let $F=\lb X_1,\dots,X_n\rb,n>1$ be a classification of $U$ and let $R$ be an
   equivalence relation. If there exists $i\in\lb 1,\dots,n\rb$ s.t. $\oR
   X_i=U$, then for each $j\neq i$ and $j\in\lb 1,\dots,n\rb$ $\uR X_j=\emptyset$
   #+END_proposition

   #+ATTR_LATEX: :options [2.7]
   #+BEGIN_proposition
   Let $F=\lb X_1,\dots,X_n\rb,n>1$ be a classification of $U$ and let $R$ be an
   equivalence relation. If for each $i\in\lb 1,2,\dots,n\rb$ $\uR
   X_i\neq\emptyset$ holds, then $\oR X_i\neq U$ for each $i\in\lb 1,\dots,n,\rb$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $F=\lb X_1,\dots,X_n\rb,n>1$ be a classification of $U$ and let $R$ be an
   equivalence relation. If for each $i\in\lb 1,2,\dots,n\rb$ $\oR X_i=U$ holds,
   then $\uR X_i=\emptyset$ for each $i\in\lb 1,\dots,n\rb$
   #+END_proposition
** Rough equality of sets
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $K=(U,\bR)$ be a knowledge base, $X,Y\subseteq U$ and $R\in IND(K)$, then
   1. Sets $X$ and $Y$ are *bottom* $R\textbf{-equal}$ $(X\eqsim_R Y)$ if $\uR X=\uR
      Y$
   2. Sets $X$ and $Y$ are *top* $R-\textbf{equal}$ $(X\simeq_R Y)$ if $\oR X=\oR
      Y$
   3. Sets $X$ and $Y$ are $R\textbf{-equal}$ $(X\approx_R Y)$ if $X\simeq_R Y$
      and $X\eqsim_R Y$
   #+END_definition
   
   #+ATTR_LATEX: :options [2.9]
   #+BEGIN_proposition
   1. $X\eqsim Y$ iff $X\cap Y\eqsim X$ and $X\cap Y\eqsim Y$
   2. $X\simeq Y$ iff $X\cup Y\simeq X$ and $X\cup Y\simeq Y$
   3. If $X\simeq X'$ and $Y\simeq Y'$ then $X\cup Y\simeq X'\cup Y'$
   4. If $X\eqsim X'$ and $Y\eqsim Y'$ then $X\cap Y\eqsim X'\cap Y'$
   5. If $X\simeq Y$, then $X\cup -Y\simeq U$
   6. If $X\eqsim Y$, then $X\cap -Y\eqsim\emptyset$
   7. If $X\subseteq Y$ and $Y\simeq\emptyset$, then $X\simeq\emptyset$
   8. If $X\subseteq Y$ and $X\subseteq U$ then $Y\subseteq U$
   9. $X\simeq Y$ iff $-X\eqsim -Y$
   10. If $X\eqsim \emptyset$ or $Y\eqsim\emptyset$, then $X\cap
       Y\eqsim\emptyset$
   11. If $X\simeq U$ or $Y\simeq U$, then $X\cup Y\simeq U$
   #+END_proposition

   #+ATTR_LATEX: :options [2.10 ]
   #+BEGIN_proposition
   For any equivalence relation $R$
   1. $\uR X$ is the intersection of all $Y\subseteq U$ s.t. $X\eqsim_R Y$
   2. $\oR$ is the union of all $Y\subseteq U$ s.t. $X\simeq_R Y$
   #+END_proposition
** Rough inclusion of sets
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $K=(U,\bR)$ be a knowledge base, $X,Y\subseteq U$ and $R\in IND(K)$.
   1. Set $X$ is *bottom* $R\textbf{-included}$ in $Y$ $(X\subsetsim_R  Y)$ iff $\uR
      X\subseteq\uR Y$
   2. Set $X$ is *top* $R\textbf{-included}$ in $Y$ $(X\simsubset_R Y)$ iff $\oR
      X\subseteq \oR Y$
   3. Set $X$ is $R\textbf{-included}$ in $Y$ $(X\simsubsetsim_R Y)$ iff
      $X\simsubset_R Y$ and $X\subsetsim_R Y$
   #+END_definition

   #+ATTR_LATEX: :options [2.11]
   #+BEGIN_proposition
   1. If $X\subseteq Y$, then $X\subsetsim Y, X\simsubset Y$ and $X\simsubsetsim
      Y$
   2. If $X\subsetsim Y$ and $Y\subsetsim X$, then $X\eqsim Y$
   3. If $X\simsubset Y$ and $Y\simsubset X$, then $X\simeq Y$
   4. If $X\simsubsetsim Y$ and $Y\simsubsetsim X$ then $X\approx Y$
   5. $X\simsubset Y$ iff $X\cup Y\simeq Y$
   6. $X\subsetsim Y$ iff $X\cap Y\eqsim X$
   7. If $X\subseteq Y, X\eqsim X',Y\eqsim Y'$, then $X'\subsetsim Y'$
   8. If $X\subseteq Y, X\simeq X',Y\simeq Y'$, then $X'\simsubset Y'$
   9. If $X\subseteq Y, X\approx X',Y\approx Y'$, then $X'\simsubsetsim Y'$
   10. If $X'\simsubset X$ and $Y'\simsubset Y$, then $X'\cup Y'\simsubset X\cup
       Y$
   11. If $X'\subsetsim X,Y'\subsetsim$ then $X'\cap Y'\subsetsim X\cap Y$
   12. $X\cap Y\subsetsim X\simsubset X\cup Y$
   13. If $X\subsetsim Y$ and $X\eqsim Z$ then $Z\subsetsim Y$
   14. If $X\simsubset Y$ and $X\simeq Z$ then $Z\simsubset Y$
   15. If $X\simsubsetsim Y$ and $X\approx$ then $Z\simsubsetsim Y$
   #+END_proposition
* Reduction of knowledge
** Reduct and Core of Knowledge
   Let $\bR$ be a family of equivalence relations and let $P\in\bR$. $R$ is
   *dispensable* in $\bR$ if $IND(\bR)=IND(\bR-\lb R\rb)$. Otherwise $R$ is
   *indispensable* in $\bR$. The family of $\bR$ is *independent* if each $R\in\bR$
   is indispensable in $\bR$. Otherwise $\bR$ is *dependent*

   #+ATTR_LATEX: :options [3.1]
   #+BEGIN_proposition
   If $\bR$ is independent and $\bP\subseteq \bR$, then $\bP$ is also independent
   #+END_proposition

   #+BEGIN_proof
   $IND(\bR)=IND(\bP\cup(\bR-\bP))=IND(\bP)\cap IND(\bR-\bP)$
   #+END_proof

   $\bQ\subseteq \bR$ is a *reduct* of $\bP$ if $\bQ$ is independent and
   $IND(\bQ)=IND(\bP)$


   The set of all indispensable relations in $\bP$ is called the *core* of $\bP$
   denoted by $CORE(\bP)$

   #+ATTR_LATEX: :options [3.2]
   #+BEGIN_proposition
   \begin{equation*}
   CORE(\bP)=\bigcap RED(\bP)
   \end{equation*}
   where $RED(\bP)$ is the family of all reducts of $\bP$
   #+END_proposition

   #+BEGIN_proof
   If $\bQ$ is a reduct of $\bP$ and $R\in\bP-\bQ$, then $IND(\bP)=IND(\bQ)$. If
   $\bQ\subseteq\bR\subseteq\bP$ then $IND(\bQ)=IND(\bR)$. Assuming $\bR=\bP-\lb
   R\rb$ then $R\notin CORE(\bP)$

   If $R\notin CORE(\bP)$. This means $IND(\bP)=IND(\bP-\lb R\rb)$ which implies
   that there exists an independent subset $\bS\subseteq \bP-\lb R\rb$ s.t.
   $IND(\bS)=IND(\bP)$. Hence $R\notin\bigcap RED(\bP)$
   #+END_proof
** Relative reduct and relative core of knowledge
   Let $P$ and $Q$ be equivalence relations over $U$

   $P\textbf{-positive}$
   \begin{equation*}
   POS_P(Q)=\displaystyle\bigcup_{X\in U/Q}\uP X
   \end{equation*}
   The $P\text{-positive}$ region of $Q$ is the set of all objects of the
   universe $U$ which can be properly classified to classes of $U/Q$ employing
   knowledge expressed by the classification $U/P$


   Let $\bP$ and $\bQ$ be families of equivalence relations over $U$

   $R\in\bP$ is $\bQ\textbf{-dispensable}$ in $\bP$ if
   \begin{equation*}
   POS_{IND(\bP)}(IND(\bQ))=POS_{IND(\bP-\lb R\rb)}(IND(\bQ))
   \end{equation*}
   otherwise $R$ is $\bQ\text{-indispensable}$ in $\bP$

   If every $R$ 
