#+TITLE: Rough Set Theory: A True Landmark in Data Analysis
#+AUTHOR: gouziwu
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: latex/RoughSetTheory/RoughSetTheory.tex
* Rough Sets on Fuzzy Approximation Spaces and Intuitionistic Fuzzy Approximation Spaces
  :PROPERTIES:
  :AUTHOR:   B.K. Tripathy
  :END:
  
** Introduction
*** Fuzzy Sets
*** Intuitionistic Fuzzy Sets
    the membership and nonmembership values of an element with respect to a
    collection of elements from a universe may not add up to 1 in all possible
    cases   

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An /intuitionistic fuzzy set/ $A$ on a universe $U$ is defined by two
    functions: /membership function/ $\mu_A$ and /non-membership function/ \nu s.t.
    \begin{equation*}
    \mu_A, \nu_A: U\to [0,1]
    \end{equation*}
    where $0\le \mu_A(x)+\nu_A(x)\le 1$ for all $x\in U$.
    #+END_definition

    The /hesitation function/ $\Pi_A$ for an intuitionistic fuzzy set is given by
    \begin{equation*}
    \Pi_A(x)=1-\mu_A(x)-\nu_A(x)
    \end{equation*}
*** Rough set
    A knowledge base is also called an *approximation space*
*** Motivation
*** Fuzzy proximity relation
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let $U$ be a universal set and $X\subseteq U$. Then a /fuzzy relation/ on $X$
    is defined as any fuzzy set defined on $X\times X$
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A fuzzy relation $R$ is said to be /fuzzy reflexive/ on $X\subseteq U$ if it
    satisfies
    \begin{equation*}
    \mu_R(x,x)=1\quad\text{for all } x\
    \end{equation*}
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A fuzzy relation $R$ is said to be /fuzzy symmetric/ on $X\subseteq U$ if it
    satisfies
    \begin{equation*}
    \mu_R(x,y)=\mu_R(y,x)\quad\text{for all } x,y\in X
    \end{equation*}
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A fuzzy relation on $X\subseteq U$ is said to be a /fuzzy proximity relation/
    if it is fuzzy reflexive and fuzzy symmetric.
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let $X,Y\subseteq U$. A fuzzy relation from $X$ to $Y$ is a fuzzy set
    defined on $X\times Y$ characterized by the membership function $\mu_R:X\times Y\to
    [0,1]$ 
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any $\alpha\in [0,1]$, the $\alpha\textit{-cut}$ of $R$, denoted by $R_\alpha$ is a subset
    of $X\times Y$ given by $R_\alpha=\lb(x,y):\mu_R(x,y)\ge\alpha\rb$
    #+END_definition
    Let $R$ be a fuzzy proximity relation on $U$. Then for any $\alpha\in [0,1]$ the
    elements of $R_\alpha$ are said to be $\alpha\textit{-similar}$ to each
    other. $xR_\alpha y$. 

    Two elements $x$ and $y$ in $U$ are said to be $\alpha\textit{-identical}$
    w.r.t. $R$ ($xR(\alpha)y$) if either $x$ and $y$ are $\alpha\text{-similar}$ or $x$
    and $y$ are /transitively/ $\alpha\textit{-similar}$, that is, there exists a
    sequence of elements $u_1, u_2, \dots,u_n$ in $U$ s.t. \linebreak
    $xR_\alpha u_1, u_1 R_\alpha u_2
    ,\dots,u_n R_\alpha y$
*** Intuitionistic fuzzy proximity relation
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An /intuitionistic fuzzy relation/ on a universal set $U$ is an intuitionistic
    fuzzy set defined on $U\times U$
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An intuitionistic fuzzy relation $R$ on a universal set $U$ is said to be 
    /intuitionstic fuzzy reflexive/ if 
    \begin{equation*}
    \mu_R(x,x)=1\text{ and } \nu_R(x,x)=0\quad\text{for all } x\in X
    \end{equation*}
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An intuitionistic fuzzy relation $R$ on a universal set $U$ is said to be 
    /intuitionistic fuzzy symmetric/ if
    \begin{equation*}
    \mu_R(x,y)=\mu_R(y,x)\text{ and } \nu_R(x,y)=\nu_R(y,x)\quad\text{for all } x,y\in X
    \end{equation*}
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    /intuitionistic fuzzy proximity/
    #+END_definition
    Define
    \begin{equation*}
    J=\lb(m,n)\mid m,n\in[0,1] \text{ and } 0\le m+n\le 1\rb
    \end{equation*}
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Le $R$ be an IF-proximity relation on $U$. Then for any $(\alpha,\beta)\in J$ the 
    $(\alpha,\beta)\textit{-cut}$ of $R$, denoted by R_\alpha,\beta is 
    \begin{equation*}
    R_{\alpha,\beta}=\lb(x,y)\mid\mu_R(x,y)\ge\alpha\text{ and } \nu_R(x,y)\le\beta\rb
    \end{equation*}
    #+END_definition
    The relation $R(\alpha,\beta)$ is an equivalence relation.
** Rough Sets on Fuzzy Approximation
*** Preliminaries
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any set of fuzzy proximity relation $K=(U,\mathfrak{R})$ is called a
    /fuzzy approximation space/
    #+END_definition

    For any fixed $\alpha\in[0,1]$, $\fR$ generates a set of equivalence relation
    $\fR(\alpha)$ and we call the associated space $\bK(\alpha)=(U,\fR(\alpha))$ as the 
    /generated approximation space/ corresponding to $\bK$ and \alpha
*** Properties
*** Reduction of Knowledge in Fuzzy Approximation Spaces
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let $\fR$ be a family of fuzzy proximity relations on $U$ and $\alpha\in[0,1]$.
    For any $R\in \fR$, we say that $R$ is $\alpha\textit{-dispensable}$ or 
    $\alpha\textit{-superfluous}$ in $\fR$ if and only if 
    $IND(\fR(\alpha))=IND(\fR(\alpha)-R(\alpha))$
    #+END_definition

    
    Consider $U=\lb x_1,\dots,x_n\rb$. Define the fuzzy proximity relations
    $P,Q,R$ and $S$ over $U$ corresponding to the attributes $a,b,c$ and $d$
    respectively.

    #+CAPTION: Fuzzy proximity relation for attribute $R$
    |----+-----+-----+-----+-----+-----|
    | P  |  x_1 |  x_2 |  x_3 |  x_4 |  x_5 |
    |----+-----+-----+-----+-----+-----|
    | x_1 |   1 | 0.3 | 0.6 | 0.8 | 0.5 |
    | x_2 | 0.3 |   1 | 0.7 | 0.4 | 0.4 |
    | x_3 | 0.6 | 0.7 |   1 | 0.2 | 0.8 |
    | x_4 | 0.8 | 0.4 | 0.2 |   1 | 0.5 |
    | x_5 | 0.5 | 0.4 | 0.8 | 0.5 |   1 |
    |----+-----+-----+-----+-----+-----|
    
    #+CAPTION: Fuzzy proximity relation for attribute $Q$
    |-----+-----+-----+-----+-----+-----|
    | P   |  x_1 |  x_2 |  x_3 |  x_4 |  x_5 |
    |-----+-----+-----+-----+-----+-----|
    | x_1  |   1 | 0.3 | 0.4 | 0.2 | 0.5 |
    | x_2  | 0.3 |   1 | 0.8 | 0.6 | 0.6 |
    | x_3  | 0.4 | 0.8 |   1 | 0.3 | 0.9 |
    | x_4  | 0.2 | 0.6 | 0.3 |   1 | 0.7 |
    | 0.5 | 0.2 | 0.2 | 0.9 | 0.7 |   1 |
    |-----+-----+-----+-----+-----+-----|

    #+CAPTION: Fuzzy proximity relation for attribute $R$
    |----+-----+-----+-----+-----+-----|
    | R  |  x_1 |  x_2 |  x_3 |  x_4 |  x_5 |
    |----+-----+-----+-----+-----+-----|
    | x_1 |   1 | 0.3 | 0.2 | 0.8 | 0.7 |
    | x_2 | 0.3 |   1 | 0.5 | 0.3 | 0.5 |
    | x_3 | 0.2 | 0.5 |   1 | 0.6 | 0.4 |
    | x_4 | 0.8 | 0.3 | 0.6 |   1 | 0.9 |
    | x_5 | 0.7 | 0.5 | 0.4 | 0.9 |   1 |
    |----+-----+-----+-----+-----+-----|

    #+CAPTION: Fuzzy proximity relation for attribute $S$
    |----+-----+-----+-----+-----+-----|
    | S  |  x_1 |  x_2 |  x_3 |  x_4 |  x_5 |
    |----+-----+-----+-----+-----+-----|
    | x_1 |   1 | 0.3 | 0.2 | 0.2 | 0.5 |
    | x_2 | 0.3 |   1 | 0.5 | 0.3 | 0.2 |
    | x_3 | 0.2 | 0.5 |   1 | 0.2 | 0.4 |
    | x_4 | 0.2 | 0.3 | 0.2 |   1 | 0.5 |
    | x_5 | 0.5 | 0.4 | 0.4 | 0.5 |   1 |
    |----+-----+-----+-----+-----+-----|

    #+CAPTION: Fuzzy proximity relation for $IND(\fR(\alpha))$
    |----------------+-----+-----+-----+-----+-----+---|
    | $IND(\fR(\alpha))$ |  x_1 |  x_2 |  x_3 |  x_4 |  x_5 |   |
    |----------------+-----+-----+-----+-----+-----+---|
    |      <c>       |     |     |     |     |     |   |
    |       x_1       |   1 | 0.3 | 0.2 | 0.2 | 0.5 |   |
    |       x_2       | 0.3 |   1 | 0.3 | 0.3 | 0.2 |   |
    |       x_3       | 0.2 | 0.3 |   1 | 0.2 | 0.4 |   |
    |       x_4       | 0.2 | 0.3 | 0.2 |   1 | 0.4 |   |
    |       x_5       | 0.5 | 0.2 | 0.4 | 0.4 |   1 |   |
    |----------------+-----+-----+-----+-----+-----+---|

    Suppose $\alpha=0.6$, then we get
    \begin{align*}
      &U/P(\alpha)=\{\{x_1,x_2,x_3,x_4,x_5\}\}\\
      &U/Q(\alpha)=\{\{x_1\},\{x_2,x_3,x_4,x_5\}\}\\
      &U/R(\alpha)=\{\{x_1,x_3,x_4,x_5\},\{x_2\}\}\\
      &U/S(\alpha)=\{\{x_1\},\{x_2\},\{x_3\},\{x_4\},\{x_5\}\}\\
    \end{align*}
*** Relative reducts and relative core of knowledge in fuzzy approximation spaces
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let $P$ and $Q$ be two fuzzy proximity relations over the universe $U$. For
    every fixed $\alpha\in[0,1]$, the $\alpha\textit{-positive region}$ of $P$ w.r.t. $Q$
    can be defined as
    \begin{equation*}
    \alpha\text{-}POS_P Q=\displaystyle\bigcup_{X_\alpha\in U/Q} \underline{P}X_\alpha
    \end{equation*}
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let $\bP$ and $\bQ$ be two families of fuzzy proximity relations on $U$. For
    every fixed $\alpha\in [0,1]$ and $R\in \bP$ ,$R$ is
    $(\bQ,\alpha)\textit{-dispensable}$ in $\bP$ if 
    \begin{equation*}
    \alpha\text{-}POS_{IND} (\bQ)=\alpha\text{-}POS_{IND(\bP-\lb R\rb)}IND(\bQ)
    \end{equation*}
    If every $R\in\bP$ is $(\bQ,\alpha)\text{-indispensable}$, then $\bP$ is 
    $(\bQ,\alpha)\textit{-indepedent}$
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For every fixed $\alpha\in[0,1]$, the family $\bS\subseteq\bP$ is a 
    $(\bQ,\alpha)\text{-reduct}$ of $\bP$ if and only if
    \begin{gather*}
    \bS\text{ is } (\bQ,\alpha)\text{-indepedent}\\
    \alpha\text{-}POS_{\bS}\bQ=\alpha\text{-}POS_{\bP}\bQ
    \end{gather*}
    #+END_definition
    
    Consider another attribute $T$, let's find the relative reduct and the
    relative core, that is $(T,\alpha)\text{-reduct}$ and
    $(T,\alpha)\text{-core}$ of the family of fuzzy proximity relations 
    $\calr=\lb P,Q,R,S\rb$
    #+CAPTION: Fuzzy proximity relation for attribute $T$
    |-----+-----+-----+-----+-----+-----|
    | T   | x_1 | x_2 | x_3 | x_4 | x_5 |
    |-----+-----+-----+-----+-----+-----|
    | x_1 |   1 | 0.4 | 0.5 | 0.6 | 0.8 |
    | x_2 | 0.4 |   1 | 0.9 | 0.3 | 0.5 |
    | x_3 | 0.5 | 0.9 |   1 | 0.2 | 0.4 |
    | x_4 | 0.6 | 0.3 | 0.2 |   1 | 0.5 |
    | x_5 | 0.8 | 0.5 | 0.4 | 0.5 |   1 |
    |-----+-----+-----+-----+-----+-----|
    \begin{gather*}
      U/T(\alpha)=\{\{x_1,x_4,x_5\},\{x_2,x_3\}\}\\
      U/IND\calr(\alpha)=\{\{x_1\},\{x_2\},\{x_3\},\{x_4\},\{x_5\}\}\\
      \alpha\text{-}POS_{\calr(\alpha)}T(\alpha)=
      \displaystyle\bigcup_{X\in U/T(\alpha)}\calr X_\alpha=U
    \end{gather*}
*** Dependency of knowledge in fuzzy approximation spaces
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say knowledge $\bQ$ is $\alpha\textit{-derivable}$ from knowledge $\bP$ if
    the elementary $\alpha\text{-categories}$ of $\bQ$ can be defined in terms
    of some elementary $\alpha\text{-categories}$ of knowledge P
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If $\bQ$ is $\alpha\text{-derivable}$ from $\bP$, we say that knowledge $\bQ$
    $\alpha\textit{-depends}$ on knowledge $\bP$ and we denote it by
    $\bP\xRightarrow{\alpha}\bQ$. So, $\bP\xRightarrow{\alpha}\bQ$ if and only
    if $IND(\bP(\alpha))\subseteq IND(\bQ(\alpha))$
    #+END_definition
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Knowledge $\bP$ and $\bQ$ are $\alpha\textit{-equivalent}$, denoted by 
    $\bP\stackrel{\alpha}{\equiv}\bQ$ iff $IND(\bP(\alpha))=IND(\bQ(\alpha))$
    #+END_definition

*** partial dependency of knowledge in fuzzy approximation spaces
    It may happen that the $\alpha\text{-derivation}$ of one knowledge $P$ from
    another knowledge $Q$ can be partial. That is only a part of knowledge P can
    be $\alpha\text{-derivation}$ from P 

    Suppose $\calk(\alpha)=(U,\calr(\alpha))$ is a fuzzy approximation space and
    $P,Q\subseteq \calr$. Then $Q$ $\alpha\textit{-depends}$ /in a degree/
    $k(\alpha)$, $0\le k(\alpha)\le 1$ denoted by $P\xRightarrow{\alpha}_{k}Q$
    if 
    \begin{equation*}
    k(\alpha)=\gamma_{P(\alpha)}(Q(\alpha))=\frac{\abs{POS_{P(\alpha)}(Q(\alpha))}}{\abs{U}}
    \end{equation*}
    $k(\alpha)=1$ then /totally/, $0<k(\alpha)<1$ /partially(roughly)/

** Rough Sets in Intuitionistic Fuzzy Approximation Spaces
