#+TITLE: \aunclfamily\Huge Abstract and Concrete Categories @@latex:\\@@ The Joy of Cats @@latex:\\@@ \includegraphics[scale=1.2]{cat.png}
#+AUTHOR: Jiří Adámek & Horst Herrlich & George E. Strecker
#+OPTIONS: toc:2
#+LATEX_HEADER: \input{../preamble.tex}
#+EXPORT_FILE_NAME: ../latex/AbstractAndConcreteCategories/AbstractAndConcreteCategories.org
#+LATEX_HEADER: \graphicspath{{../../images/CAT/}}
#+LATEX_HEADER: \DeclareMathOperator{\Rel}{\textbf{Rel}}
#+LATEX_HEADER: \DeclareMathOperator{\Sym}{\textbf{Sym}}
* Categories, Functors, and Natural Transformations
** Categories and Functors
*** Categories
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *category* is a quadruple $\bA=(\calo,\hom,id,\circ)$ consisting
   1. a class $\calo$, whose members are called *\(\bA\)-objects*
   2. for each pair $(A,B)$ of \(\bA\)-objects, a set \(\hom(A,B)\) whose
      members are called *\(\bA\)-morphisms from $A$ to $B$*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. The following *constructs*; i.e., categories of structured sets and
      structure-preserving functions between them
      1. \(\Alg(\Omega)\) with objects all *\(\Omega\)-algebras* and morphisms all \par
         *\(\Omega\)-homomorphisms* between them. Here \(\Omega=(n_i)_{i\in I}\) is a
         family of natural numbers \(n_i\), indexed by a set $I$. An
         \(\Omega\)-algebra is a pair \(X,(\omega_i)_{i\in I}\) consisting of a set
         $X$ and a family of functions \(\omega_i:X^{n_i}\to X\), called *\(n_i\)-ary
         operations* on $X$. An \(\Omega\)-homomorphism \(f:(X,(\omega_i)_{i\in
         I}\to(\widehat{X},(\widehat{\omega}_i)_{i\in I})\) is a function \(f:X\to\widehat{X}\) for
         which the diagram
         \begin{center}
         \begin{tikzcd}
         X^{n_i}\arrow[r,"f^{n_i}"]\arrow[d,"\omega_i"']&
         \widehat{X}^{n_i}\arrow[d,"\widehat{\omega}_i"]\\
         X\arrow[r,"f"']&\widehat{X}
         \end{tikzcd}
         \end{center}
         commutes for each $i\in I$.
      2. *\(\Sigma\)-Seq* with objects all (deterministic, sequential)
         *\(\Sigma\)-acceptor*, where \Sigma is a finite set of input symbols. Objects
         are quadruples \((Q,\delta,q_0,F)\) where $Q$ is a finite set of states, 
         \(\delta:\Sigma\times Q\to Q\) is a transition map, \(q_0\in Q\) is the
         initial state, and \(F\subseteq Q\) is the set of final states.

         A morphism \(f:(Q,\delta,q_0,F)\to(Q',\delta',q_0',F')\) (called a
         *simulation*) is a function \(f:Q\to Q'\) that preserves
         1. transitions, i.e., \(\delta'(\sigma,f(q))=f(\delta(\sigma,q))\)
         2. the initial state, i.e., \(f(q_0)=q_0'\)
         3. the final states, i.e., \(f[F]\subseteq F'\)
   2. The following categories where the objects and morphisms are /not/
      constructed sets and structure-preserving functions:
      1. $\Mat$ with objects all natural numbers, and for which \(\hom(m,n)\) is
         the set of all real \(m\times n\) matrices, \(id_n:n\to n\) is the unit
         diagonal matrix, and composition is defined by \(A\circ B=BA\)

      2. $\Aut$ with objects all (deterministic, sequential, Moore) *automata*.
         Objects are sectuples \((Q,\Sigma,Y,\delta,q_0,y)\), where $Q$ is the set of
         states, \Sigma and $Y$ are the sets of input symbols and output symbols,
         respectively, \(\delta:\Sigma\times Q\to Q\) is the transition map, 
         \(q_0\in Q\) is the initial state, and \(y:Q\to Y\) is the output map.
         Morphisms from an automaton \((Q,\Sigma,Y,\delta,q_0,y)\) to an automaton
         \((Q',\Sigma',Y',\delta',q_0',y')\) are triples \((f_Q,f_{\Sigma},f_Y)\) of
         functions satisfying the following conditions
         1. preservation of transitions:
            \(\delta'(f_{\Sigma}(\sigma),f_Q(q))=f_Q(\delta(\sigma,q))\)

         2. preservation of outputs: \(f_Y(y(q))=y'(f_Q(q))\)

         3. preservation of initial state: \(f_Q(q_0)=q_0'\)
   #+END_examplle
*** The Dual Principle
   [[index:dual category]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any category \(\bA=(\calo,\hom_{\bA},id,\circ)\) the *dual* (or *opposite*)
   *category of \(\bA\)* is the category
   \(\bA^{\op}=(\calo,\hom_{\bA^{\op}},id,\circ^{\op})\), where
   \(\hom_{\bA^{\op}}(A,B)=\hom_{\bA}(B,A)\) and \(f\circ^{\op}g=g\circ f\)
   #+END_definition
   
   Consider the property of objects $X$ in \(\bA\):
   \begin{equation*}
   \calp_{\bA}(X)\equiv \textit{ For any } \bA\textit{-object } A
   \textit{ there exists exactly one }
   \bA\textit{-morphism } f:A\to X
   \end{equation*}

   Step1: In \(\calp_{\bA}(X)\) replace all occurrences of $\bA$ by $\bA^{\op}$,
   thus obtaining the property
   \begin{equation*}
   \calp_{\bA^{\op}}(X)\equiv \textit{ For any } \bA^{\op}\textit{-object } A
   \textit{ there exists exactly one }
   \bA^{\op}\textit{-morphism } f:A\to X
   \end{equation*}

   Step2: Translate $\calp_{\bA^{\op}}(X)$ into the logically equivalent
   statement
   \begin{equation*}
   \calp_{\bA}^{\op}(X)\equiv \textit{ For any } \bA\textit{-object } A
   \textit{ there exists exactly one }
   \bA\textit{-morphism } f:X\to A
   \end{equation*}

   The *Duality Principle for Categories* states
   \begin{center}
   \textit{Whenever a property \(\calp\) holds for all categories,}\\
   \textit{then the property \(\calp^{\op}\) holds for all categories.}
   \end{center}
*** Isomorphism
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A morphism \(f:A\to B\) in a category is called an *isomorphism* provided that
   there exists a morphism \(g:B\to A\) with \(g\circ f=id_A\) and \(f\circ
   g=id_B\). Such a morphism $g$ is called an *inverse* of $f$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $f:A\to B,g:B\to A,h:B\to A$ are morphisms s.t. \(g\circ f=id_A\) and
   \(f\circ h=id_B\), then \(g=h\)
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(F:\bA\to\bB\)  be a functor
   1. \(F\) is called an *embedding* provided that \(F\) is injective on morphisms
   2. \(F\) is called *faithful* provided that all the hom-set restrictions
      \begin{equation*}
      F:\hom_{\bA}(A,A')\to\hom_{\bB}(FA,FA')
      \end{equation*}
      are injective
   3. \(F\) is called *full* provided that all hom-set restrictions are surjective
   4. \(F\) is called *amnestic* provided that an \(\bA\)-isomorphism \(f\) is an
      identity whenever \(Ff\) is an identity

   #+END_definition

** Subcategories
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A category \(\bA\) is said to be a *subcategory* of a category \(\bB\) provided
   that the following conditions are satisfied
   1. \(Ob(\bA)\subseteq Ob(\bB)\)
   2. for each \(A,A'\in Ob(\bA)\), \(\hom_{\bA}(A,A')\subseteq\hom_{\bB}(A,A')\)
   3. for each \(\bA\)-object \(A\), the \(\bB\)-identity on \(A\) is the
      \(\bA\)-identity on \(A\)
   4. the composition law in \(\bA\) is the restriction of the composition law
      in \(\bB\) to the morphisms of \(\bA\)


   \(\bA\) is called a *full subcategory* of \(\bB\) if in addition to the above,
   for each \(A,A'\in Ob(A)\), \(\hom_{\bA}(A,A')=\hom_{\bB}(A,A')\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. A functor \(F:\bA\to\bB\) is a (full) embedding if and only if there exists a
      (full) subcategory \(\bC\) of \(\bB\) with inclusion function \(E:\bC\to\bB\)
      and an isomorphism \(G:\bA\to\bC\) with \(F=E\circ G\)

   2. A functor \(F:\bA\to\bB\) is faithful iff there exists embeddings
      \(E_1:\bD\to\bB\) and \(E_2:\bA\to\bC\) and an equivalence \(G:\bC\to\bD\)
      s.t. the diagram
      \begin{center}\begin{tikzcd}
      \bA\arrow[r,"F"]\arrow[d,"E_2"]&\bB\\
      \bC\arrow[r,"G"]&\bD\arrow[u,"E_1"]
      \end{tikzcd}\end{center}
   
   #+END_proposition

   #+BEGIN_proof
   2. Let \(E_1:\bD\to\bB\) be the inclusion of the full subcategory \(\bD\) of
      \(\bB\) that has as objects all images of \(\bA\)-objects. Let \(\bC\) be
      the category with \(Ob(\bC)=Ob(\bA)\), with
      \begin{equation*}
      \hom_{\bC}(A,A')=\hom_{\bB}(FA,FA')
      \end{equation*}
      Now define functors \(E_2:\bA\to\bC\) and \(G:\bC\to\bD\) by
      \begin{equation*}
      E_2(A\xrightarrow{f}A')=A\xrightarrow{Ff}A' \quad\text{ and }\quad
      G(C\xrightarrow{g}C')=FC\xrightarrow{g}FC'
      \end{equation*}
      Then \(E_2\) is an embedding, \(G\) is an equivalence and \(F=E_1\circ
      G\circ E_2\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A category \(\bA\) is said to be *fully embeddable* into \(\bB\) provided that
   there exists a full embedding \(\bA\to\bB\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A full subcategory \(\bA\) of a category \(\bB\) is called
   1. *isomorphism-closed* provided that every \(\bB\)-object that is isomorphic
      to some \(\bA\)-object is itself an \(\bA\)-object
   2. *isomorphism-dense* provided that every \(\bB\)-object is isomorphic to
   some \(\bA\)-object
   #+END_definition

   #+BEGIN_remark
   If \(\bA\) is a full subcategory of \(\bB\), then the following conditions
   are equivalent
   1. \(\bA\) is an isomorphism-dense subcategory of \(\bB\)
   2. the inclusion functor \(\bA\hookrightarrow\bB\) is isomorphism-dense
   3. the inclusion functor \(\bA\hookrightarrow\bB\) is an equivalence
   #+END_remark

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The full subcategory of \(\Set\) with the single object \(\N\) is neither
   isomorphism-closed nor isomorphism-dense in \(\Set\). It is equivalent to the
   isomorphism-closed full subcategory of \(\Set\) consisting of all countable
   infinite sets.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *skeleton* of a category is a full, isomorphism-dense subcategory in which no
   two distinct objects are isomorphic
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. The full subcategory of all cardinal numbers is a skeleton for \(\Set\)
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. Every category has a skeleton
   2. Any two skeletons of a category are isomorphic
   3. Any skeleton of a category \(\bC\) is equivalent to \(\bC\)
   #+END_proposition

   #+BEGIN_proof
   1. This follows from the Axiom of Choice applied to the equivalence relation
      "is isomorphic to" on the class of objects of the category
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Two categories are equivalent iff they have isomorphic skeletons
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\bA\) be a subcategory of \(\bB\), and let \(B\) be a \(\bB\)-object
   1. An *\(\bA\)-reflection* (or *\(\bA\)-reflection arrow*) for \(B\) is a
      \(\bB\)-morphism \(B\xrightarrow{r}A\) from \(B\) to an \(\bA\)-object
      \(A\) with the following universal property:
      
      for any \(\bB\)-morphism \(B\xrightarrow{f}A'\) from \(B\) into some
      \(\bA\)-object \(A'\), there exists a unique \(\bA\)-morphism \(f':A\to
      A\) s.t. the triangle
      \begin{center}\begin{tikzcd}
      B\arrow[r,"r"]\arrow[dr,"f"]&A\arrow[d,"f'"]\\
      &A'
      \end{tikzcd}\end{center}
      commutes
   2. \(\bA\) is called a *reflective subcategory* of \(\bB\) provided that each
      \(\bB\)-object has an \(\bA\)-reflection

   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. *Modifications of the Structure*
      1. Making a relation symmetric: \(\bB=\Rel,\bA=\Sym\), the full subcategory
         of symmetric relations, \((X,\rho)\xrightarrow{id_X}(X,\rho\cup\rho^{-1})\)
         is an \(\bA\)-reflection for \((X,\rho)\)
   2. *Improving Objects by Forming Quotients*
      1. Making a reachable acceptor minimal: \(\bB=\) the full subcategory of
         *\(\Sigma\)-Seq* consisting of all *reachable acceptors* (i.e., those for
         which each state can be reached from the initial one by an input word),
         \(\bA=\) the full subcategory of \(\bB\) consisting of all *minimal
         acceptors* (i.e. those reachable acceptors with the property that no two
         different states are *observably equivalent*. The observability
         equivalence \(\approx\) on a reachable acceptor \(B\) is given by:
         \(q\approx q'\) provided that whenever the initial state of \(B\) is
         changed to \(q\), the resulting acceptor recognizes the same language
         as it does when the initial state is changed to \(q'\)). Then the
         canonical map \(B\to B/\approx\) is an \(\bA\)-reflection for \(B\)
   3. *Completions*
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Reflections are essentially unique, i.e.
   1. if \(B\xrightarrow{r}A\) and \(B\xrightarrow{\hat{r}}\hat{A}\) are
      \(\bA\)-reflections for \(B\), then there exists an \(\bA\)-isomorphism
      \(k:A\to\hat{A}\) s.t. the triangle
      \begin{center}\begin{tikzcd}
      B\arrow[r,"r"]\arrow[rd,"\hat{r}"']&A\arrow[d,"k"]\\
      &\hat{A}
      \end{tikzcd}\end{center}
      commutes
   2. if \(B\xrightarrow{r}A \) is an \(\bA\)-reflection for \(B\) and
      \(A\xrightarrow{k}\hat{A}\) is an \(\bA\)-isomorphism, then
      \(B\xrightarrow{k\circ r}\hat{A}\) is an \(\bA\)-reflection for \(B\)

   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop4.20
   If \(\bA\) is reflective subcategory of \(\bB\), then the following
   conditions are equivalent
   1. \(\bA\) is a full subcategory of \(\bB\)
   2. for each \(\bA\)-object \(A\), \(A\xrightarrow{id_A}A\) is an \(\bA\)-reflection
   3. for each \(\bA\)-object \(A\), \(\bA\)-reflection arrows
      \(A\xrightarrow{r_A}A^*\) are \(\bA\)-isomorphism
   4. for each \(\bA\)-object \(A\), \(\bA\)-reflection arrows
      \(A\xrightarrow{r_A}A^*\) are \(\bA\)-morphisms
   #+END_proposition

   #+BEGIN_proof
   \(2\to3\).
   \begin{center}\begin{tikzcd}
   A\arrow[r,"r_A"]\arrow[ddr,"r_A"']&A^*\arrow[d,"f"]\\
   &A\arrow[d,"r_A"]\\
   &A^*
   \end{tikzcd}\end{center}

   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(\bA\) be a reflective subcategory of \(\bB\), and for each
   \(\bB\)-object \(B\) let \(r_B:B\to A_B\) be an \(\bA\)-reflection arrow.
   Then there exists a unique functor \(R:\bB\to\bA\) s.t. the following
   conditions are satisfied
   1. \(R(B)=A_B\) for each \(\bB\)-object \(B\)
   2. for each \(\bB\)-morphism \(f:B\to B'\) the diagram
      \begin{center}\begin{tikzcd}
      B\arrow[r,"r_B"]\arrow[d,"f"']&R(B)\arrow[d,"R(f)"]\\
      B'\arrow[r,"r_{B'}"']&R(B')
      \end{tikzcd}\end{center}
      commutes

   #+END_proposition

   #+BEGIN_proof
   Show that functor is well-defined and preserves identities and compositions
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A functor \(R:\bB\to\bA\) constructed according to the above proposition is
   called a *reflector for \(\bA\)*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\bA\) be a subcategory of \(\bB\) and let \(B\) be a \(\bB\)-object
   1. An *\(\bA\)-coreflection* (or *\(A\)-coreflection arrow*) for \(B\) is a
      \(\bB\)-morphism \(A\xrightarrow{c}B\) form an \(\bA\)-object \(A\) to
      \(B\) with the following universal property:

      for any \(\bB\)-morphism \(A'\xrightarrow{f}B\) from some \(\bA\)-object
      \(A'\) to \(B\) there exists a unique \(\bA\)-morphism \(f':A'\to A\) s.t.
      the triangle
      \begin{center}\begin{tikzcd}
      A'\arrow[d,"f'"']\arrow[dr,"f"]\\
      A\arrow[r,"c"']&B
      \end{tikzcd}\end{center}
      commutes

   2. \(\bA\) is called a *coreflective subcategory* of \(\bB\) provided that each
      \(\bB\)-object has an \(\bA\)-coreflection

   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If \(\bA\) is a coreflective subcategory of \(\bB\) and for each
   \(\bB\)-object \(B\), \(A_B\xrightarrow{c_B}B\) is an \(\bA\)-coreflection
   arrow, then there exists a unique functor \(C:\bB\to\bA\) (called a
   *coreflector for* \(\bA\)) s.t. the following conditions are satisfied
   1. \(C(B)=A_B\) for each \(\bB\)-object \(B\)
   2. for each \(\bB\)-morphism \(f:B\to B'\) the diagram
      \begin{center}\begin{tikzcd}
      C(B)\arrow[r,"c_B"]\arrow[d,"C(f)"']&
      B\arrow[d,"f"]\\
      C(B')\arrow[r,"c_{B'}"']&B'
      \end{tikzcd}\end{center}
      commutes

   #+END_proposition

   #+BEGIN_exercise
   A subcategory \(\bA\) of a category \(\bB\) is called *isomorphism-closed*
   provided that every \(\bB\)-isomorphism with domain in \(\bA\) belongs to
   \(\bA\). Show that every subcategory \(\bA\) of \(\bB\) can be embedded into
   a smallest isomorphism-closed subcategory \(\bA'\) of \(\bB\) that contains
   \(\bA\). The inclusion functor \(\bA\hookrightarrow\bA'\) is an equivalence
   iff all \(\bB\)-isomorphisms between \(\bA\)-objects belong to \(\bA\)
   #+END_exercise

   #+BEGIN_exercise
   1. Show that a category is discrete iff each of its subcategories is full
   2. Show that in a poset, considered as a category
      * every subcategory is isomorphism-closed
      * every (co)reflective subcategory is full
   #+END_exercise
** Concrete categories and concrete functors
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\bX\) be a category. A *concrete category* over \(\bX\) is a pair
   \((\bA,U)\) where \(\bA\) is the category and \(U:\bA\to\bX\) is a faithful
   functors. Sometimes \(U\) is called the *forgetful* (or *underlying*) *functor* of
   the concrete category and \(\bX\) is called the *base category* for \((\bA,U)\)

   A concrete category over \(\Set\) is called a *construct*
   #+END_definition

   #+BEGIN_remark
   We adopt the following conventions:
   1. Since faithful functors are injective on hom-sets, we usually assume that
      \(\hom_{\bA}(A,B)\) is a subset of \(\hom_{\bX}(UA,UB)\) for each pair
      \((A,B)\) of \(\bA\)-objects. This allows one to express the property that
      "for \(bA\)-objects \(A\) and \(B\) and an \(\bX\)-morphism
      \(UA\xrightarrow{f}UB\) there exists a (necessarily unique)
      \(\bA\)-morphism \(A\to B\) with \(U(A\to B)=UA\xrightarrow{f}UB\)" much
      more succinctly, by stating
      \begin{equation*}
      UA\xrightarrow{f}UB\text{ is an $\bA$-morphism (from $A$ to $B$)}
      \end{equation*}
      Observe, however, that since \(U\) doesn't need to be injective on
      objects, the expression
      \begin{equation*}
      UA\xrightarrow{id_X}UB\text{ is an $\bA$-morphism (from $A$ to $B$)}
      \end{equation*}
      does not imply that \(A=B\) or that \(id_X=id_A\), although it does imply
      that \(UA=UB=X\). We call an \(\bA\)-morphism \(A\xrightarrow{f}B\)
      *identity-carried* if \(Uf=id_X\)
   2. Sometimes we will write \(\bA\) for the concrete category \((\bA,U)\) over
      \(\bX\), when \(U\) is clear from the context. In these cases the
      underlying object of an \(\bA\)-object \(A\) will sometimes be denoted by \(\abs{A}\)
   3. If \(P\) is a property of categories (or of functors), then we will say
      that a concrete category \((\bA,U)\) *has property* \(P\) provided that
      \(\bA\) (or \(U\)) has property \(P\)
   #+END_remark

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \((\bA,U)\) be a concrete category over \(\bX\)
   1. The *fibre* of an \(\bX\)-object \(X\) is the preordered class consisting of
      all \(\bA\)-objects \(A\) with \(U(A)=X\) ordered by
      \begin{equation*}
      A\le B \quad\text{ iff }\quad
      id_X:UA\to UB\text{ is an $\bA$-morphism}
      \end{equation*}
   2. \(\bA\)-objects \(A,B\) are *equivalent* if \(A\le B\) and \(B\le A\)
   3. \((\bA,U)\) is said to be *amnestic* provided that its fibres are partially
      ordered classes; i.e., no two different \(\bA\)-objects are equivalent
   4. \((\bA,U)\) is said to be *fibre-small* provided that each of its fibres is
      small, i.e., a preordered set
   #+END_definition

   #+BEGIN_remark
   A concrete category \((\bA,U)\) is amnestic iff the functor \(U\) is
   amnestic. Most of the familiar concrete categories are both amnestic and
   fibre-small. 
   #+END_remark

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A concrete category is called
   1. *fibre-complete* provided that its fibres are (possibly large) complete lattices
   2. *fibre-discrete* provided that its fibres are ordered by equality
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A concrete category \((\bA,U)\) over \(\bX\) is fibre-discrete iff \(U\)
   *reflects identities* (i.e. if \(U(k)\) is an \(\bX\)-identity, then \(k\) must
   be an \(\bA\)-identity)
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \((\bA,U)\) and \((\bB,V)\) are concrete categories over \(\bX\), then a
   *concrete functor from* \((\bA,U)\) *to* \((\bB,V)\) is a functor \(F:\bA\to\bB\)
   with \(U=V\circ F\). We denote such a functor by \(F:(\bA,U)\to(\bB,V)\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. Every concrete functor is faithful
   2. Every concrete functor is completely determined by its values on objects
   3. Objects that are identified by a full concrete functor are equivalent
   4. Every full concrete functor with amnestic domain is an embedding
   #+END_proposition

   #+BEGIN_proof
   1. \(U\) and \(V\) are faithful
   2. Suppose that \(G:(\bA,U)\to(\bB,V)\) is a concrete functor with
      \(G(A)=F(A)\) for each \(\bA\)-object \(A\). Then for any \(\bA\)-morphism
      \(A\xrightarrow{f}A'\) we have the \(\bB\)-morphism
      \begin{center}\begin{tikzcd}
      GA=FA\arrow[r,shift left,"Ff"]\arrow[r,shift right,"Gf"']
      &FA'=GA'
      \end{tikzcd}\end{center}
      with \(V(Ff)=U(f)=V(Gf)\). Since \(V\) is faithful, \(Ff=Gf\). Hence \(F=G\)
   3. Let \(A\)  and \(A'\) be \(\bA\)-objects with \(FA=FA'\). Then
      \(id_B:FA\to FA'\) can be lifted to an \(\bA\)-isomorphism \(g:A\to A'\).
      Hence \(A\) and \(A'\) are equivalent
   #+END_proof

   #+BEGIN_remark
   If \(F:(\bA,U)\to(\bB,V)\) is a concrete isomorphism, then its inverse
   \(F^{-1}:\bB\to\bA\) is concrete from \((\bB,V)\) to \((\bA,U)\).
   Unfortunately, the corresponding result does not hold for concrete
   equivalences. If \(F:(\bA,U)\to(\bB,V)\) is a concrete equivalence from
   \((\bB,V)\) to \((\bA,U)\) even though there are equivalences from \(\bB\) to
   \(\bA\). For example, the embedding of the skeleton of cardinal numbers into
   \(\Set\) is such a concrete categories over \(\bX\) that is not invertible
   #+END_remark

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. The identity functor on a concrete category is a concrete isomorphism
   2. Any composite of concrete functors over \(\bX\) is a concrete functor over \(\bX\)
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The quansicategory that has as objects all concrete categories over \(\bX\)
   and as morphisms all concrete functors between them is denoted by
   \(\CAT(\bX)\). In particular, \(\CONST=\CAT(\Set)\) is the quasicategory of
   all constructs.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \(F\) and \(G\) are both concrete functors from \((\bA,U)\) to
   \((\bB,V)\), then \(F\) is *finer than* \(G\) (or \(G\) is *coaser than \(F\)*),
   denoted by \(F\le G\), provided that \(F(A)\le G(A)\) for each \(\bA\)-object \(A\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. For order-preserving functions considered as concrete functors over
      \(\bone\), \(f\le g\) iff this relation holds pointwise
   #+END_examplle

   #+BEGIN_remark
   For every concrete category \((\bA,U)\) over \(\bX\), its dual
   \((\bA^{\op},U^{\op})\) is a concrete category over \(\bX^{\op}\). Moreover,
   for every concrete functor \(F:(\bA,U)\to(\bB,V)\) over \(\bX\) its dual
   functor \(F^{\op}:(\bA^{\op},U^{\op})\to(\bB^{\op},V^{\op})\) is a concrete
   functor over \(\bX^{\op}\). However, unless \(\bX=\bX^\op\) there is *no*
   duality for concrete categories over a fixed base category \(\bX\). In
   particular, we don't have a duality principle for constructs. However, since
   \(\bone=\bone^\op\), there is a duality principle for concrete categories
   over \(\bone\) (i.e., for preordered classes)
   #+END_remark

   If \((\bB,U)\) is a concrete category over \(\bX\) and \(\bA\) is a
   subcategory of \(\bB\) with inclusion \(E:\bA\hookrightarrow\bB\), then
   \(\bA\) will often be regarded (via the functor \(U\circ E\)) as a concrete
   category \((\bA,U\circ E)\) over \(\bX\). In such cases we will call
   \((\bA,U\circ E)\) a *concrete subcategory* of \((\bB,U)\). In the case that
   the base category is \(\Set\), we will call \((\bA,U\circ E)\) a *subconstruct*
   of \((\bB,U)\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A concrete subcategory \((\bA,U)\) of \((\bB,V)\) is called *concretely
   reflective* in \((\bB,V)\) provided that for each \((\bB)\)-object there
   exists an identity-carried \(\bA\)-reflection arrow

   Relectors induced by identity-carried reflection arrows are called *concrete reflectors*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. Let \(\bX\) be a category consisting of a single object \(X\) and two
      morphisms \(id_X\) and \(s\) with \(s\circ s=id_X\). Let \(\bA\) be the
      concrete category over \(\bX\), consisting of two objects \(A_0\) and
      \(A_1\) and the morphism sets
      \begin{equation*}
      \hom_{\bA}(A_i,A_j)=
      \begin{cases}
      \{id_X\}&i=j\\
      \{s\}&i\neq j
      \end{cases}
      \end{equation*}
      Consider \(\bA\) as a concretely reflective subcategory of itself. Then
      \(id_{\bA}:\bA\to\bA\) is a concrete reflector, and the concrete functor
      \(R:\bA\to\bA\), defined by \(R(A_i)=A_{1-i}\) is a reflector that is not
      a concrete reflector
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every concretely reflective subcategory of an amnestic concrete category is a
   full subcategory
   #+END_proposition

   #+BEGIN_proof
   Let \((\bA,U)\) be a concretely reflective subcategory of an amnestic
   \((\bB,V)\), let \(A\) be an \(r:A\to A^*\) be an identity-carried
   \(\bA\)-reflection arrow for \(A\). We wish to show that \(r=id_A\) so that
   Proposition ref:prop4.20 can be applied. By reflectivity there exists a
   unique \(\bA\)-morphism \(s:A^*\to A\) s.t. the diagram
   \begin{center}\begin{tikzcd}
   A\arrow[r,"r"]\arrow[rd,"id_A"]&A^*\arrow[d,"s"]\\
   &A
   \end{tikzcd}\end{center}
   commutes.

   Since \(r\) is identity-carried, \(V(r)=id_{VA}\). Since also
   \(V(id_A)=id_{VA}\), we conclude that \(V(s)=id_{VA}\). Faithfulness of \(V\)
   gives us \(r\circ s=id_{A^*}\). Hence \(r\) is a \(\bB\)-isomorphism with
   \(V(r)=id_{VA}\). Amnesticity of \((\bB,V)\) yields \(r=id_A\). 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   For a concrete full subcategory \((\bA,U)\) of a concrete category
   \((\bB,V)\) over \(\bX\), with inclusion functor
   \(E:(\bA,U)\hookrightarrow(\bB,V)\), the following are equivalent
   1. \((\bA,U)\) is concretely reflective in \((\bB,V)\)
   2. there exists a concrete functor \(R:(\bB,V)\to(\bA,U)\) that is a
      reflector with \(R\circ E=id_{\bA}\) and \(id_{\bB}\le E\circ R\)
   3. there exists a concrete functor \(R:(\bB,V)\to(\bA,U)\) with \(R\circ E\le id_{\bA}\) and \(id_{\bB}\le E\circ R\)
   #+END_proposition

   #+BEGIN_proof
   \(1\to2\).
   #+END_proof
* Natural transformations
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(F,G:\bA\to\bB\) be functors. A *natural transformation \tau from \(F\) to
  \(G\)* (denoted by \(\tau:F\to G\) or \(F\xrightarrow{\tau}G\)) is a function that
  assigns to each \(\bA\)-object \(A\) a \(\bB\)-morphism \(\tau_A:FA\to GA\) in
  such a way that the following *naturality condition* holds: for each
  \(\bA\)-morphism \(A\xrightarrow{f}A'\) the square
  \begin{center}\begin{tikzcd}
  FA\arrow[r,"\tau_A"]\arrow[d,"Ff"]&GA\arrow[d,"Gf"]\\
  FA'\arrow[r,"\tau_{A'}"]&GA'
  \end{tikzcd}\end{center}
  commutes
  #+END_definition


* Index
  # This eliminates the duplicate Index section name
  \renewcommand{\indexname}{}
  [[printindex:nil]]

** COMMENT awef
   definition

   proposition

   lemma

   theorem

   corollary
