#+TITLE: A Course in Model Theory
#+AUTHOR: Katin Tent & Martin Ziegler

#+STARTUP: noindent
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \setcounter{secnumdepth}{2}
#+LATEX_HEADER: \setcounter{tocdepth}{2}
#+EXPORT_FILE_NAME: ../latex/ACourseInModelTheory/ACourseInModelTheory.tex
#+LATEX_HEADER: \def \acl {\text{acl}}
#+LATEX_HEADER: \def \Graph {\textsf{Graph}}
#+LATEX_HEADER: \def \RG {\textsf{RG}}
#+LATEX_HEADER: \def \qf {\text{qf}}
#+LATEX_HEADER: \def \EM {\textbf{EM}}
#+LATEX_HEADER: \def \Skolem {\textsf{Skolem}}
#+LATEX_HEADER: \def \Tree {\textsf{Tree}}
* The Basics

** Structures
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *language* \(L\) is a set of constants, function symbols and relation symbols
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(L\) be a language. An *\(L\)-structure* is a pair \(\fA=(A,(Z^{\fA})_{Z\in L})\) where
   | \(A\)           | if a non-empty set, the *domain* or *universe* of \(\fA\) |
   | \(z^{\fA}\in A\)    | if \(Z\) is a constant                              |
   | \(Z^{\fA}:A^n\to A\) | if \(Z\) is an \(n\)-ary function symbol            |
   | \(Z^{\fA}\subseteq A^n\)   | if \(Z\) is an \(n\)-ary relation symbol            |
   #+END_definition


   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA,\fB\) be \(L\)-structures. A map \(h:A\to B\) is called a
   *homomorphism* if for all \(a_1,\dots,a_n\in A\)
   \begin{equation*}
    \begin{array}{rcl}
    h(c^{\fA})&=&c^{\fB}\\
    h(f^{\fA}(a_1,\dots,a_n))&=&f^{\fB}(h(a_1),\dots,h(a_n))\\
    R^{\fA}(a_1,\dots,a_n)&\Rightarrow&R^{\fB}(h(a_1),\dots,h(a_n))
    \end{array}
   \end{equation*}

   We denote this by
   \begin{equation*}
    h:\fA\to\fB
   \end{equation*}
   
   If in addition \(h\) is injective and
   \begin{equation*}
    R^{\fA}(a_1,\dots,a_n)\Leftrightarrow R^{\fB}(h(a_1),\dots,h(a_n))
   \end{equation*}
   for all \(a_1,\dots,a_n\in A\), then \(h\) is called an (isomorphic)
   *embedding*. An *isomorphism* is a surjective embedding

   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We call \(\fA\) a *substructure* of \(\fB\) if \(A\subseteq B\) and if the inclusion map is an embedding
   from \(\fA\) to \(\fB\). We denote this by
   \begin{equation*}
   \fA\subseteq\fB
   \end{equation*}
   We say \(\fB\) is an *extension* of \(\fA\) if \(\fA\) is a substructure of \(\fB\)
   #+END_definition


   

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.1.8
   Let \(h:\fA \isoto\fA'\) be an isomorphism and \(\fB\) an
   extension of \(\fA\). Then there exists an extension \(\fB'\) of \(\fA'\) and
   an isomorphism \(g:\fB \isoto\fB' \) extending \(h\)
   #+END_lemma

   For any family \(\fA_i\) of substructures of \(\fB\), the intersection of the
   \(A_i\) is either empty or a substructure of \(\fB\). Therefore if \(S\) is
   any non-empty subset of \(\fB\), then there exists a smallest substructure
   \(\fA=\la S\ra^{\fB}\) which contains \(S\). We call the \(\fA\) the
   substructure *generated* by \(S\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \(\fa=\la S\ra\), then every homomorphism \(h:\fA\to\fB\) is determined by
   its values on \(S\)
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
    Let \((I,\le)\) be a *directed partial order*. This means that for all
    \(i,j\in I\) there exists a \(k\in I\) s.t. \(i\le k\) and \(j\le k\). A
    family \((\fA_i)_{i\in I}\) of \(L\)-structures is called *directed* if
    \begin{equation*}
    i\le j\Rightarrow\fA_i\subseteq\fA_j
    \end{equation*}
    If \(I\) is linearly ordered, we call \((\fA_i)_{i\in I}\) a *chain*
   #+END_definition

   If a structure \(\fA_1\) is isomorphic to a substructure \(\fA_0\) of itself,
   \begin{equation*}
    h_0:\fA_0\isoto\fA_1
   \end{equation*}
   then Lemma ref:lemma1.1.8 gives an extension
   \begin{equation*}
    h_1:\fA_1\isoto\fA_2
   \end{equation*}
   Continuing in this way we obtain a chain 
   \(\fA_0\subseteq \fA_1\subseteq\fA_2\subseteq\dots\)
   and an increasing sequence
   \(h_i:\fA_i\isoto\fA_{i+1}\) of isomorphism

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \((\fA_i)_{i\in I}\) be a directed family of \(L\)-structures. Then
   \(A=\bigcup_{i\in I}A_i\) is the universe of a (uniquely determined)
   \(L\)-structure
   \begin{equation*}
   \fA=\bigcup_{i\in I}\fA_i
   \end{equation*}
   which is an extension of all \(\fA_i\)
   #+END_lemma
   
   A subset \(K\) of \(L\) is called a *sublanguage*. An \(L\)-structure becomes a
   \(K\)-structure, the *reduct*.
   \begin{equation*}
   \fA\restriction K=(A,(Z^{\fA})_{Z\in K})
   \end{equation*}
   Conversely we call \(\fA\) an *expansion* of \(\fA\restriction K\).
   1. Let \(B\subseteq A\) , we obtain a new language
      \begin{equation*}
      L(B)=L\cup B
      \end{equation*}
      and the \(L(B)\)-structure 
      \begin{equation*}
      \fA_B=(\fA,b)_{b\in B}
      \end{equation*}
      Note that \(\Aut(\fA_B)\) is the group of automorphisms of \(\fA\) fixing
      \(B\) elementwise. We denote this group by \(\Aut(\fA/B)\)
      
      
   Let \(S\) be a set, which we call the set of sorts. An \(S\)-sorted
   language \(L\) is given by a set of constants for each sort in \(S\), and
   typed function and relations. For any tuple \((s_1,\dots,s_n)\) and
   \((s_1,\dots,s_n,t)\) there is a set of relation symbols and function
   symbols respectively. An \(S\)-sorted structure is a pair
   \(\fA=(A,(Z^{\fA})_{Z\in L})\), where 
   \begin{alignat*}{2}      
   &A&&\text{if a family $(A_s)_{s\in S}$ of non-empty sets}\\
   &Z^{\fA}\in A_s&&\text{if $Z$ is a constant of sort $s\in S$}\\
   &Z^{\fA}:A_{s_1}\times\dots\times A_{s_n}\to A_t&&\text{if $Z$ is a
   function symbol of type $(s_1,\dots,s_n,t)$}\\
   &Z^{\fA}\subseteq A_{s_1}\times\dots\times A_{s_n}&&\text{if $Z$ is a
   relation symbol of type $(s_1,\dots,s_n)$}
   \end{alignat*}

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Consider the two-sorted language \(L_{Perm}\) for permutation groups with a
   sort \(x\) for the set and a sort \(g\) for the group. The constants and
   function symbols for \(L_{Perm}\) are those of \(L_{Group}\) restricted to
   the sort \(g\) and an additional function symbol \varphi of type \((x,g,x)\). Thus
   an \(L_{Perm}\)-structure \((X,G)\) is given by a set \(X\) and an
   \(L_{Group}\)-structure \(G\) together with a function \(X\times G\to X\)
   #+END_examplle

** Language
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.2.11
   Suppose \(\vv{b}\) and \(\vv{c}\) agree on all variables which are free
   in \varphi. Then 
   \begin{equation*}
   \fA\vDash\varphi[\vv{b}]\Leftrightarrow\fA\vDash\varphi[\vv{c}]
   \end{equation*}
   #+END_lemma

   We define
   \begin{equation*}
   \fA\vDash\varphi[a_1,\dots,a_n]
   \end{equation*}
   by \(\fA\vDash\varphi[\vv{b}]\), where \(\vv{b}\) is an assignment
   satisfying \(\vv{b}(x_i)=a_i\). Because of Lemma ref:lemma1.2.11 this is
   well defined.

   


   Thus \(\varphi(x_1,\dots,x_n)\) defines an \(n\)-ary relation
   \begin{equation*}
   \varphi(\fA)=\{\bbar{a}\mid\fA\vDash\varphi[\bbar{a}]\}
   \end{equation*}
   on \(A\), the *realisation set* of \varphi. Such realisation sets are called
   *0-definable subsets* of \(A^n\), or 0-definable relations

   Let \(B\) be a subset of \(A\). A *\(B\)-definable* subset of \(\fA\) is a set
   of the form \(\varphi(\fA)\) for an \(L(B)\)-formula \(\varphi(x)\). We also say that \varphi
   are defined *over* \(B\) and that the set \(\varphi(\fA)\) is defined by \varphi. We call
   two formulas *equivalent* if in every structure they define the same set.

   Atomic formulas and their negations are called *basic*. Formulas without
   quantifiers are Boolean combinations of basic formulas. It is convenient to
   allow the empty conjunction and the empty disjunction. For that we introduce
   two new formulas: the formula \(\top\), which is always true, and the formula
   \(\bot\), which is always false. We define
   \begin{align*}
   &\bigwedge_{i<0}\pi_i=\top\\
   &\bigvee_{i<0}\pi_i=\bot
   \end{align*}

   A formula is in *negation normal form* if it is built from basic formulas using
   \(\wedge,\vee,\exists,\forall\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Every formula can be transformed into an equivalent formula which is in negation normal form
   #+END_lemma

   #+BEGIN_proof
   Let \(\sim\) denote equivalence of formulas. We consider formulas which are built
   using \(\wedge,\vee,\exists,\forall,\neg\) and move the negation symbols in front of atomic formulas using
   \begin{align*}
   \neg(\varphi\wedge\psi)&\sim(\neg\varphi\vee\neg\psi)\\
   \neg(\varphi\vee\psi)&\sim(\neg\varphi\wedge\neg\psi)\\
   \neg\exists x\varphi&\sim\forall x\neg\varphi\\
   \neg\forall x\varphi&\sim\exists x\neg\varphi\\
   \neg\neg\varphi&\sim\varphi
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A formula in negation normal form which does not contain any existential
   quantifier is called *universal*. Formulas in negation normal form without
   universal quantifiers are called *existential*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.2.16
   Let \(h:\fA\to\fB\) be an embedding. Then for all existential formulas \(\varphi(x_1,\dots,x_n)\) and
   all \(a_1,\dots,a_n\in A\) we have
   \begin{equation*}
   \fA\vDash\varphi[a_1,\dots_,a_n]\Rightarrow\fB\vDash\varphi[h(a_1),\dots,h(a_n)]
   \end{equation*}
   For universal \varphi, the dual holds
   \begin{equation*}
   \fB\vDash\varphi[h(a_1),\dots,h(a_n)]\Rightarrow
   \fA\vDash\varphi[a_1,\dots,a_n]
   \end{equation*}
   #+END_lemma

   
   Let \(\fA\) be an \(L\)-structure. The *atomic diagram* of \(\fA\) is
   \begin{equation*}
   \Diag(\fA)=\{\varphi\text{ basic $L(A)$-sentence}\mid\fA_A\vDash\varphi\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   The models of \(\Diag(\fA)\) are precisely those structures
   \((\fB,h(a))_{a\in A}\) for embeddings \(h:\fA\to\fB\)
   #+END_lemma

   #+BEGIN_proof
   The structures \((\fB,h(a))_{a\in A}\) are models of the atomic diagram by Lemma ref:1.2.16.  For
   the converse, note that a map \(h\) is an embedding iff it preserves the validity of all formulas
   of the form
   \begin{align*}
   &(\neg)x_1\dot{=}x_2\\
   &c\dot=x_1\\
   &f(x_1,\dots,x_n)\dot=x_0\\
   &(\neg)R(x_1,\dots,x_n)
   \end{align*}
   #+END_proof

   #+BEGIN_exercise
   label:ex1.2.3
   Every formula is equivalent to a formula in prenex normal form:
   \begin{equation*}
   Q_1x_1\dots Q_nx_n\varphi
   \end{equation*}
   The \(Q_i\) are quantifiers and \varphi is quantifier-free
   #+END_exercise

   #+BEGIN_proof
   \begin{align*}
   &(\forall x)\phi\wedge\psi\vDash\rmodels
   \forall x(\phi\wedge\psi)\text{ if }\exists x\top(\text{at least one individual exists})\\
   &(\forall x\phi)\vee\psi\vDash\rmodels\forall x(\phi\vee\psi)\\
   &(\exists x\phi)\wedge\psi\vDash\rmodels\exists x(\phi\wedge\psi)\\
   &(\exists x\phi)\vee\psi\vDash\rmodels\exists x(\phi\vee\psi)\text{ if }\exists x\top\\
   &\neg\exists x\phi\vDash\rmodels\forall x\neg\phi\\
   &\neg\forall x\phi\vDash\rmodels\exists x\neg\phi\\
   &(\forall x\phi)\to\psi\vDash\rmodels\exists x(\phi\to\psi)\text{ if }\exists x\top\\
   &(\exists x\phi)\to\psi\vDash\rmodels\forall x(\phi\to\psi)\\
   &\phi\to(\exists x\psi)\vDash\rmodels\exists x(\phi\to\psi)\text{ if }\exists x\top\\
   &\phi\to(\forall x\psi)\vDash\rmodels\forall x(\phi\to\psi)
   \end{align*}
   #+END_proof

** Theories
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An *\(L\)-theory* \(T\) is a set of \(L\)-sentences
   #+END_definition
   
   A theory which has a model is a *consistent* theory. We call a set \Sigma of
   \(L\)-formulas *consistent* if there is an \(L\)-structure and *an assignment*
   \(\vv{b}\) *s.t.* \(\fA\vDash\Sigma[\vv{b}]\) for all \(\varphi\in\Sigma\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(T\) be an \(L\)-theory and \(L'\) be an extension of \(L\). Then \(T\)
   is consistent as an \(L\)-theory iff \(T\) is consistent as a \(L'\)-theory
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.3.4
   1. If \(T\vDash\varphi\) and \(T\vDash(\varphi\to\psi)\), then \(T\vDash\psi\)
   2. If \(T\vDash\varphi(c_1,\dots,c_n)\) and the constants \(c_1,\dots,c_n\)
      occur neither in \(T\) nor in \(\varphi(x_1,\dots,x_n)\), then
      \(T\vDash\forall x_1\dots x_n\varphi(x_1,\dots,x_n)\)
   #+END_lemma

   #+BEGIN_proof
   2. [@2] Let \(L'=L\setminus\{c_1,\dots,c_n\}\). If the \(L'\)-structure is a
      model of \(T\) and \(a_1,\dots,a_n\) are arbitrary elements, then
      \((\fA,a_1,\dots,a_n)\vDash\varphi(c_1,\dots,c_n)\). This means
      \(\fA\vDash\forall x_1\dots x_n\varphi(x_1,\dots,x_n)\).
   #+END_proof

   \(S\) and \(T\) are called *equivalent*, \(S\equiv T\), if \(S\) and \(T\) have
   the same models

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A consistent \(L\)-theory \(T\) is called *complete* if for all \(L\)-sentences
   \varphi
   \begin{equation*}
   T\vDash\varphi \quad\text{ or }\quad T\vDash\neg\varphi
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For a complete theory \(T\) we define
   \begin{equation*}
   \abs{T}=\max(\abs{L},\aleph_0)
   \end{equation*}
   #+END_definition

   The typical example of a complete theory is the theory of a structure \(\fA\)
   \begin{equation*}
   \Th(\fA)=\{\varphi\mid\fA\vDash\varphi\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.3.7
   A consistent theory is complete iff it is maximal consistent, i.e., if it is
   equivalent to every consistent extension
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Two \(L\)-structures \(\fA\) and \(\fB\) are called *elementary equivalent*
   \begin{equation*}
   \fA\equiv\fB
   \end{equation*}
   if they have the same theory
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(T\) be a consistent theory. Then the following are equivalent
   1. \(T\) is complete
   2. All models of \(T\) are elemantarily equivalent
   3. There exists a structure \(\fA\) with \(T\equiv\Th(\fA)\)
   #+END_lemma

   #+BEGIN_proof
   \(1\to3\to2\to1\)
   #+END_proof


   


* Elementary Extensions and Compactness
** Elementary substructures
   Let \(\fA,\fB\) be two \(L\)-structures. A map \(h:A\to B\) is called
   *elementary* if for all \(a_1,\dots,a_n\in A\) we have
   \begin{equation*}
   \fA\vDash\varphi[a_1,\dots,a_n]\Leftrightarrow
   \fB\vDash\varphi[h(a_1),\dots,h(a_n)]
   \end{equation*}
   which is actually saying \((\fA,a)_{a\in A}\equiv(\fB,a)_{a\in A}\).
   We write
   \begin{equation*}
   h:\fA\embto\fB
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.1.1
   The models of \(\Th(\fA_A)\) are exactly the structures of the form
   \((\fB,h(a))_{a\in A}\) for elementary embeddings \(h:\fA\embto\fB\)
   #+END_lemma

   We call \(\Th(\fA_A)\) the *elemantary diagram* of \(\fA\)

   A substructure \(\fA\) of \(\fB\) is called *elementary* if the inclusion map
   is elementary. In this case we write
   \begin{equation*}
   \fA\prec\fB
   \end{equation*}

   #+ATTR_LATEX: :options [Tarski's Test]
   #+BEGIN_theorem
   label:thm2.1.2
   Let \(\fB\) be an \(L\)-structure and \(A\) a subset of \(B\). Then \(A\) is
   the universe of an elementary substructure iff every \(L(A)\)-formula
   \(\varphi(x)\) which is satisfiable in \(\fB\) can be satisfied by an element of \(A\)
   #+END_theorem

   #+BEGIN_proof
   If \(\fA\prec\fB\) and \(\fB\vDash\exists x\varphi(x)\), we also have \(\fA\vDash\exists x\varphi(x)\) and there exists \(a\in A\)
   s.t. \(\fA\vDash\varphi(a)\). Thus \(\fB\vDash\varphi(a)\)

   Conversely, suppose that the condition of Tarski'test is satisfied. First we show that \(A\) is
   the universe of a substructure \(\fA\). The \(L(A)\)-formula \(x\dot=x\) is satisfiable in \(\fA\),
   so \(A\) is not empty. If \(f\in L\) is an \(n\)-ary function symbol \((n\ge 0)\) and \(a_1,\dots,a_n\) is
   from \(A\), we consider the formula
   \begin{equation*}
   \varphi(x)=f(a_1,\dots,a_n)\dot=x
   \end{equation*}
   Since \(\varphi(x)\) is always satisfied by an element of \(A\), it follows that \(A\) is closed
   under \(f^{\calb}\)

   Now we show, by induction on \psi, that
   \begin{equation*}
   \fA\vDash\psi\Leftrightarrow\fB\vDash\psi
   \end{equation*}
   for all \(L(A)\)-sentences \psi.

   For \(\psi=\exists x\varphi(x)\). If \psi holds in \(\fA\), there exists \(a\in A\)
   s.t. \(\fA\vDash\varphi(a)\). The induction hypothesis yields \(\fB\vDash\varphi(x)\), thus \(\fB\vDash\psi\). For the converse
   suppose \psi holds in \(\fB\). Then \(\varphi(x)\) is satisfied in \(\calb\) and by Tarski's test we
   find \(a\in A\) s.t. \(\fB\vDash\varphi(a)\). By induction \(\fA\vDash\varphi(a)\) and \(\fA\vDash\psi\)
   #+END_proof

   We use Tarski's Test to construct small elementary substructures

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor2.1.3
   Suppose \(S\) is a subset of the \(L\)-structure \(\fB\). Then \(\fB\) has a
   elementary substructure \(\fA\) containing \(S\) and of cardinality at most
   \begin{equation*}
   \max(\abs{S},\abs{L},\aleph_0)
   \end{equation*}
   #+END_corollary

   #+BEGIN_proof
   We construct \(A\) as the union of an ascending sequence \(S_0\subseteq S_1\subseteq\dots\) of subsets of \(B\). We
   start with \(S_0=S\). If \(S_i\) is already defined, we choose an element \(a_\varphi\in B\) for
   every \(L(S_i)\)-formula \(\varphi(x)\) which is satisfiable in \(\fB\) and define \(S_{i+1}\) to
   be \(S_i\) together with these \(a_{\varphi}\).

   An \(L\)-formula is a finite sequence of symbols from \(L\), auxiliary symbols and logical
   symbols. These are \(\abs{L}+\aleph_0=\max(\abs{L},\aleph_0)\) many symbols and there are
   exactly\(\max(\abs{L},\aleph_0)\) many \(L\)-formulas

   Let \(\kappa=\max(\abs{S},\abs{L},\aleph_0)\). There are \kappa many
   \(L(S)\)-formulas: therefore \(\abs{S_1}\le\kappa\). Inductively it follows
   for every \(i\) that \(\abs{S_i}\le\kappa\). Finally we have \(\abs{A}\le\kappa\cdot\aleph_0=\kappa\)
   #+END_proof

   A directed family \((\fA_i)_{i\in I}\) of structures is *elementary* if
   \(\fA_i\prec\fA_j\) for all \(i\le j\)

   #+ATTR_LATEX: :options [Tarski's Chain Lemma]
   #+BEGIN_theorem
   label:thm2.1.4
   The union of an elementary directed family is an elementary extension of all
   its members
   #+END_theorem

   #+BEGIN_proof
   Let \(\fA=\bigcup_{i\in I}(\fA_i)_{i\in I}\). We prove by induction on
   \(\varphi(\bbar{x})\) that for all \(i\) and \(\bbar{a}\in\fA_i\)
   \begin{equation*}
   \fA_i\vDash\varphi(\bbar{a})\Leftrightarrow\fA\vDash\varphi(\bbar{a})
   \end{equation*}
   #+END_proof

   #+BEGIN_exercise
   label:ex2.1.1
   Let \(\fA\) be an \(L\)-structure and \((\fA_i)_{i\in I}\) a chain of elementary substructures of \(\fA\).
   Show that \(\bigcup_{i\in I}A_i\) is an elementary substructure of \(\fA\).
   #+END_exercise

   #+BEGIN_exercise
   label:ex2.1.2
   Consider a class \(\calc\) of \(L\)-structures. Prove
   1. Let \(\Th(\calc)=\{\varphi\mid \fA\vDash\varphi\text{ for all }\fA\in\calc\}\) be the *theory of* \(\calc\). Then \(\fM\) is a model
      of \(\Th(C)\) iff \(\fM\) is elementary equivalent to an ultraproduct of elements of \(\calc\)
   2. Show that \(\calc\) is an elementary class iff \(\calc\) is closed under ultraproduct and elementary equivalence
   3. Assume that \(\calc\) is a class of finite structures containing only finitely many structures of
      size \(n\) for each \(n\in\omega\). Then the infinite models of \(\Th(\calc)\) are exactly the models of
      \begin{equation*}
      \Th_a(\calc)=\{\varphi\mid\fA\vDash\varphi\text{ for all but finitely many }\fA\in\calc\}
      \end{equation*}
   #+END_exercise

   #+BEGIN_proof
   Chang&Keisler p220
   #+END_proof


** The Compactness Theorem
   We call a theory \(T\) *finitely satisfiable* if every finite subset of \(T\) is consistent

   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   Finitely satisfiable theories are consistent
   #+END_theorem
   
   Let \(L\) be a language and \(C\) a set of new constants. An \(L(C)\)-theory
   \(T'\) is called a *Henkin theory* if for every \(L(C)\)-formula \(\varphi(x)\) there
   is a constant \(c\in C\) s.t.
   \begin{equation*}
   \exists x\varphi(x)\to\varphi(c)\in T'
   \end{equation*}
   The elements of \(C\) are called *Henkin constants* of \(T'\)

   An \(L\)-theory \(T\) is *finitely complete* if it is finitely satisfiable and if
   every \(L\)-sentence \varphi satisfies \(\varphi\in T\) or \(\neg\varphi\in T\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Every finitely satisfiable \(L\)-theory \(T\) can be extended to a finitely
   complete Henkin Theory \(T^*\)
   #+END_lemma

   Note that conversely the lemma follows directly from the Compactness Theorem. Choose a
   model \(\fA\) of \(T\). Then \(\Th(\fA_A)\) is a finitely complete Henkin theory with \(A\) as a set
   of Henkin constants

   #+BEGIN_proof
   We define an increasing sequence \(\emptyset=C_0\subseteq C_1\subseteq\cdots\) of new constants by assigning to
   every \(L(C_i)\)-formula \(\varphi(x)\) a constant \(c_{\varphi(x)}\) and
   \begin{equation*}
   C_{i+1}=\{c_{\varphi(x)}\mid \varphi(x)\text{ a }L(C_i)\text{-formula}\}
   \end{equation*}
   Let \(C\) be the union of the \(C_i\) and \(T^H\) the set of all Henkin axioms
   \begin{equation*}
   \exists x\varphi(x)\to\varphi(c_{\varphi(x)})
   \end{equation*}
   for \(L(C)\)-formulas \(\varphi(x)\). It is easy to see that one can expand every \(L\)-structure to a
   model of \(T^H\). Hence \(T\cup T^H\) is a finitely satisfiable Henkin theory. Using the fact that the
   union of a chain of finitely satisfiable theories is also finite satisfiable, we can apply Zorn's
   Lemma and get a maximal finitely satisfiable \(L(C)\)-theory \(T^*\) which contains \(T\cup T^H\). As
   in Lemma ref:lemma1.3.7 we show that \(T^*\) is finitely complete: if neither \(\varphi\) nor \(\neg\varphi\)
   belongs to \(T^*\), neither \(T^*\cup\{\varphi\}\) nor \(T^*\cup\{\neg\varphi\}\) would be finitely satisfiable. Hence
   there would be a finite subset \Delta of \(T^*\) which would be consistent neither with \varphi nor
   with \(\neg\varphi\). Then \Delta itself would be inconsistent and \(T^*\) would not be finite satisfiable.
   This proves the lemma.
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.2.3
   Every finitely satisfiable \(L\)-theory \(T\) can be extended to a finitely
   complete Henkin theory \(T^*\)
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Every finitely complete Henkin theory \(T^*\) has a model \(\fA\) (unique up
   to isomorphism) consisting of constants; i.e.,
   \begin{equation*}
   (\fA,a_c)_{c\in C}\vDash T^*
   \end{equation*}
   with \(A=\{a_c\mid c\in C\}\)
   #+END_lemma

   #+BEGIN_proof
   Since \(T^*\) is finite complete, every sentence which follows from a finite subset of \(T^*\)
   belongs to \(T^*\)

   Define for \(c,d\in C\)
   \begin{equation*}
   c\simeq d\Leftrightarrow c\dot=d\in T^*
   \end{equation*}
   \(\simeq\) is an equivalence relation. We denote the equivalence class of \(c\) by \(a_c\), and set
   \begin{equation*}
   A=\{a_c\mid c\in C\}
   \end{equation*}
   We expand \(A\) to an \(L\)-structure \(\fA\) by defining
   \begin{align*}
   R^{\fA}(a_{c_1},\dots,a_{c_n})&\Leftrightarrow R(c_1,\dots,c_n)\in T^*\tag{\star}\\
   f^{\fA}(a_{c_1},\dots,a_{c_n})&\Leftrightarrow f(c_1,\dots,c_n)\dot=c_0\in T^*\tag{\star\star}
   \end{align*}

   We have to show that this is well-defined. For (\(\star\)) we have to show that
   \begin{equation*}
   a_{c_1}=a_{d_1},\dots,a_{c_n}=a_{d_n}, R(c_1,\dots,c_n)\in T^*
   \end{equation*}
   implies \(R(d_1,\dots,d_n)\in T^*\), which is obvious.

   For (\(\star\star\)), we have to show that for all \(c_1,\dots,c_n\) there exists \(c_0\)
   with \(f(c_1,\dots,c_n)\dot=c_0\in T^*\).

   Let \(\fA^*\) be the \(L(C)\)-structure \((\fA,a_c)_{c\in C}\). We show by induction on the complexity
   of \varphi that for every \(L(C)\)-sentence \varphi
   \begin{equation*}
   \fA^*\vDash\varphi\Leftrightarrow\varphi\in T^*
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   We have \(T\vDash\varphi\) iff \(\Delta\vDash\varphi\) for a finite subset \Delta of \(T\)
   #+END_corollary
   

   
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor2.2.5
   A set of formulas \(\Sigma(x_1,\dots,x_n)\) is consistent with \(T\) if and only
   if every finite subset of \Sigma is consistent with \(T\)
   #+END_corollary
   
   #+BEGIN_proof
   Introduce new constants \(c_1,\dots,c_n\). Then \Sigma is consistent with \(T\) is
   and only if \(T\cup\Sigma(c_1,\dots,c_n)\) is consistent. Now apply the
   Compactness Theorem
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA\) be an \(L\)-structure and \(B\subseteq A\). Then \(a\in A\)
   *realises* a set of \(L(B)\)-formulas \(\Sigma(x)\) if \(a\) satisfied all formulas
   from \(\Sigma\). We write 
   \begin{equation*}
   \fA\vDash\Sigma(a)
   \end{equation*}
   
   We call \(\Sigma(x)\) *finitely satisfiable* in \(\fA\) if every finite subset of \Sigma
   is realised in \(\fA\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.2.7
   The set \(\Sigma(x)\) is finitely satisfiable in \(\fA\) iff there is an
   elementary extension of \(\fA\) in which \(\Sigma(x)\) is realised
   #+END_lemma

   #+BEGIN_proof
   By Lemma ref:lemma2.1.1 \Sigma is realised in an elementary extension of \(\fA\)
   iff \Sigma is consistent with \(\Th(\fA_A)\). So the lemma follows from the
   observation that a finite set of \(L(A)\)-formulas is consistent with
   \(\Th(\fA_A)\) iff it is realised in \(\fA\)
   #+END_proof

   [[index:type]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA\) be an \(L\)-structure and \(B\) a subset of \(A\). A set \(p(x)\)
   of \(L(B)\)-formulas is a *type* over \(B\) if \(p(x)\) is maximal finitely
   satisfiable in \(\fA\). We call \(B\) the *domain* of \(p\). Let
   \begin{equation*}
   S(B)=S^{\fA}(B)
   \end{equation*}
   denote the set of types over \(B\).
   #+END_definition

   Every element \(a\) of \(\fA\) determines a type
   \begin{equation*}
   \tp(a/B)=tp^{\fA}(a/B)=\{\varphi(x)\mid\fA\vDash\varphi(a),\varphi\text{ an $L(B)$-formula}\}
   \end{equation*}
   So an element \(a\) realises the type \(p\in S(B)\) exactly if
   \(p=\tp(a/B)\). If \(\fA'\) is an elementary extension of \(\fA\), then
   \begin{equation*}
   S^{\fA}(B)=S^{\fA'}(B)\quad\text{ and }\quad
   \tp^{\fA'}(a/B)=\tp^{\fA}(a/B)
   \end{equation*}
   If \(\fA'\vDash p(x)\) then \(\fA'\vDash\exists xp(x)\), so
   \(\fA\vDash\exists xp(x)\).

   We use the notation \(\tp(a)\) for \(\tp(a/\emptyset)\)

   Maximal finitely satisfiable sets of formulas in \(x_1,\dots,x_n\) are called
   *\(n\)-types* and
   \begin{equation*}
   S_n(B)=S_N^{\fA}(B)
   \end{equation*}
   denotes the set of \(n\)-types over \(B\).
   \begin{equation*}
   \tp(C/B)=\{\varphi(x_{c_1},\dots,x_{c_n})\mid\fA\vDash\varphi(c_1,\dots,c_n),\varphi
   \text{ an $L(B)$-formula}\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor2.2.9
   Every structure \(\fA\) has an elementary extension \(\fB\) in which all
   types over \(A\) are realised
   #+END_corollary

   #+BEGIN_proof
   We choose for every \(p\in S(A)\) a new constant \(c_p\). We have to find a
   model of
   \begin{equation*}
   \Th(\fA_A)\cup\bigcup_{p\in S(A)}p(c_p)
   \end{equation*}
   This theory is finitely satisfiable since every \(p\) is finitely satisfiable
   in \(\fA\).

   Or use Lemma ref:lemma2.2.7. Let \((p_\alpha)_{\alpha<\lambda}\) be an enumeration of
   \(S(A)\). Construct an elementary chain
   \begin{equation*}
   \fA=\fA_0\prec\fA_1\prec\dots\prec\fA_\beta\prec\dots(\beta\le\lambda)
   \end{equation*}
   s.t. each \(p_\alpha\) is realised in \(\fA_{\alpha+1}\) (by recursion
   theorem on ordinal numbers)

   Suppose that the elementary chain \((\fA_{\alpha'})_{\alpha'<\beta}\) is already
   constructed. If \beta is a limit ordinal, we let
   \(\fA_\beta=\bigcup_{\alpha<\beta}\fA_\alpha\), which is elementary by Lemma ref:thm2.1.4. If
   \(\beta=\alpha+1\) we  first note that \(p_\alpha\) is also finitely
   satisfiable in \(\fA_\alpha\), therefore we can realise \(p_\alpha\) in a
   suitable elementary extension \(\fA_\beta\succ\fA_\alpha\) by Lemma
   ref:lemma2.2.7. Then \(\fB=\fA_\lambda\) is the model we were looking for
   #+END_proof

** The Löwenheim-Skolem Theorem
   #+ATTR_LATEX: :options [Löwenheim-Skolem]
   #+BEGIN_theorem
   label:thm2.3.1
   Let \(\fB\) be an \(L\)-structure, \(S\) a subset of \(B\) and \kappa an infinite
   cardinal
   1. If
      \begin{equation*}
      \max(\abs{S},\abs{L})\le\kappa\le\abs{B}
      \end{equation*}
      then \(\fB\) has an elementary substructure of cardinality \kappa containing \(S\)
   2. If \(\fB\) is infinite and
      \begin{equation*}
      \max(\abs{\fB},\abs{L})\le\kappa
      \end{equation*}
      then \(\fB\) has an elementary extension of cardinality \kappa
   #+END_theorem

   #+BEGIN_proof
   1. Choose a set \(S\subseteq S'\subseteq B\) of cardinality \kappa and apply Corollary ref:cor2.1.3
   2. We first construct an elementary extension \(\fB'\) of cardinality at least \kappa. Choose a
      set \(C\) of new constants of cardinality \kappa. As \(\fB\) is infinite, the theory
      \begin{equation*}
      \Th(\fB_B)\cup\{\neg c\dot=d\mid c,d\in C,c\neq d\}
      \end{equation*}
      is finitely satisfiable. By Lemma ref:lemma2.1.1 any model \((\fB'_B,b_c)_{c\in C}\) is an
      elementary extension of \(\calb\) with \kappa many different elements \((b_c)\)

      Finally we apply the first part of the theorem to \(\calb'\) and \(S=B\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   A theory which has an infinite model has a model in every cardinality \(\kappa\ge\max(\abs{L},\aleph_0)\)
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal. A theory \(T\) is called
   *\(\kappa\)-categorical* if for all models of \(T\) of cardinality \kappa are isomorphic
   #+END_definition

   #+ATTR_LATEX: :options [Vaught's Test]
   #+BEGIN_theorem
   label:thm2.3.4
   A \(\kappa\)-categorical theory \(T\) is complete if the following conditions
   are satisfied
   1. \(T\) is consistent
   2. \(T\) has no finite model
   3. \(\abs{L}\le\kappa\)
   #+END_theorem

   #+BEGIN_proof
   We have to show that all models \(\fA\) and \(\fB\) of \(T\) are elemantarily
   equivalent. As \(\fA\) and \(\fB\) are infinite, \(\Th(\fA)\) and
   \(\Th(\fB)\) have models \(\fA'\) and \(\fB'\) of cardinality \kappa. By
   assumption \(\fA'\) and \(\fB'\) are isomorphic, and it follows that
   \begin{equation*}
   \fA\equiv\fA'\equiv\fB'\equiv\fB
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. The theory \(\DLO\) of dense linear orders without endpoints is
      \(\aleph_0\)-categorical and by Vaught's test complete. Let
      \(A=\{a_i\mid i\in\omega\}\), \(B=\{b_i\mid i\in\omega\}\).
      We inductively define
      sequences \((c_i)_{i<\omega}\), \((d_i)_{i<\omega}\) exhausting \(A\) and \(B\).
      Assume that \((c_i)_{i<m},(d_i)_{i<m}\) have defined so that \(c_i\mapsto
      d_i,i<m\) is an order isomorphism. If \(m=2k\) let \(c_m=a_j\) where
      \(a_j\) is the element with minimal index in \(\{a_i\mid i\in\omega\}\)
      not occurring in \((c_i)_{i<m}\). Since \(\fB\) is a dense linear order
      without endpoints there is some element \(d_m\in\{b_i\mid i\in\omega\}\)
      s.t. \((c_i)_{i\le m}\) and \((d_i)_{i\le m}\) are order isomorphic. If
      \(m=2k+1\) we interchange the roles of \(\fA\) and \(\fB\)
   2. For any prime \(p\) or \(p=0\), the theory \(\ACF_p\) of algebraically closed fields of
      characteristic \(p\) is \kappa-categorical for any \(\kappa>\aleph_0\)
   #+END_examplle


   Consider the Theorem ref:thm2.3.4 we strengthen our definition
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal. A theory \(T\) is called
   *\(\kappa\)-categorical* if it is complete, \(\abs{T}\le\kappa\) and, up to
   isomorphism, has exactly one model of cardinality \kappa
   #+END_definition




* Quantifier Elimination
** Preservation theorems
   #+ATTR_LATEX: :options [Separation Lemma]
   #+BEGIN_lemma
   Let \(T_1, T_2\) be two theories. Assume \(\calh\) is a set of sentences
   which is closed under \(\wedge,\vee\) and contains \(\bot\) and \(\top\).
   Then the following are equivalent
   1. There is a sentence \(\varphi\in\calh\) which separates \(T_1\) from
      \(T_2\). This means
      \begin{equation*}
        T_1\vDash\varphi \quad\text{ and }\quad
        T_2\vDash\neg\varphi
      \end{equation*}
   2. All models \(\fA_1\) of \(T_1\) can be separated from all models \(\fA_2\)
      of \(T_2\) by a sentence \(\varphi\in\calh\). This means
      \begin{equation*}
        \fA_1\vDash\varphi \quad\text{ and }\quad\fA_2\vDash\neg\varphi
      \end{equation*}
   #+END_lemma

   For 1, suppose \(T_1=T\cup\{\psi\}\) and \(T_2=T\cup\{\neg\psi\}\). If \(T_1\vDash\varphi\) and \(T_2\vDash\neg\varphi\), then
   \(T\vDash\psi\to\varphi\) and \(T\vDash\neg\psi\to\neg\varphi\) which is equivalent to \(T\vDash\varphi\to\psi\). Thus we have \(T\vDash\varphi\leftrightarrow\psi\).

   #+BEGIN_proof
   \(2\to1\). For any model \(\fA_1\) of \(T_1\) let \(\calh_{\fA_1}\) be the
   set of all sentences from \(\calh\) which are true in \(\fA_1\). (2) implies
   that \(\calh_{\fA_1}\) and \(T_2\) cannot have a common model. By the
   Compactness Theorem there is a finite conjunction \(\varphi_{\fA_1}\) of
   sentences from \(\calh_{\fA_1}\) inconsistent with \(T_2\). Clearly
   \begin{equation*}
    T_1\cup\{\neg\varphi_{\fA_1}\mid\fA_1\vDash T_1\}
   \end{equation*}
   is inconsistent. Again by compactness \(T_1\) implies a disjunction \varphi of
   finitely many of the \(\varphi_{\fA_1}\) (Corollary ref:cor2.2.5) and
   \begin{equation*}
   T_1\vDash\varphi \quad\text{ and }\quad T_2\vDash\neg\varphi
   \end{equation*}
   #+END_proof



   For structures \(\fA,\fB\) and a map \(f:A\to B\) preserving all formulas
   from a set of formulas \Delta, we use the notation
   \begin{equation*}
   f:\fA\to_\Delta\fB
   \end{equation*}
   We also write
   \begin{equation*}
   \quad\fA\Rightarrow_\Delta\fB
   \end{equation*}
   to express that all sentences from \Delta true in \(\fA\) are also true in \(\fB\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.1.2
   Let \(T\) be a theory, \(\fA\) a structure and \Delta a set of formulas, closed
   under existential quantification, conjunction and substitution of variables.
   Then the following are equivalent
   1. All sentences \(\varphi\in\Delta\) which are true in \(\fA\) are
      consistent with \(T\)
   2. There is a model \(\fB\vDash T\) and a map \(f:\fA\to_\Delta\fB\)
   #+END_lemma

   #+BEGIN_proof
   \(2\to 1\). Assume \(f:\fA\to_\Delta\fB\vDash T\). If \(\varphi\in\Delta\) is true in \(\fA\), it is also true in \(\fB\) and
   therefore consistent with \(T\).

   \(1\to2\). Consider \(\Th_\Delta(\fA_A)\), the set of all sentences \(\delta(\bbar{a})\)
   (\(\delta(\bbar{x})\in\Delta\)), which are true in \(\fA_A\). The models
   \((\fB,f(a)_{a\in A})\) of this theory correspond to maps
   \(f:\fA\to_\Delta\fB\). *This means that we have to find a model of*
   \(T\cup\Th_\Delta(\fA_A)\). To show finite satisfiability it is enough to
   show that \(T\cup D\) is consistent for every finite subset \(D\) of
   \(\Th_\Delta(\fA_A)\). Let \(\delta(\bbar{a})\) be the conjunction of the elements
   of \(D\). Then \(\fA\) is a model of \(\varphi=\exists\bar{x}\delta(\barx)\), so by assumption \(T\) has a
   model \(\fB\) which is also a model of \varphi. This means that there is a tuple \(\barb\) s.t. \((\fB,\barb)\vDash\delta(\bara)\)
   #+END_proof

   Lemma ref:lemma3.1.2 applied to \(T=\Th(\fB)\) shows that
   \(\fA\Rightarrow_\Delta\fB\) iff there exists a map \(f\) and a structure
   \(\fB'\equiv\fB\) s.t. \(f:\fA\to_\Delta\fB'\)

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.3
   Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
   1. There is a universal sentence which separates \(T_1\) from \(T_2\)
   2. No model of \(T_2\) is a substructure of a model of \(T_1\)
   #+END_theorem

   #+BEGIN_proof
   \(1\to 2\).  Let \varphi be a universal sentence which separates \(T_1\) and \(T_2\). Let \(\fA_1\) be a model
   of \(T_1\) and \(\fA_2\) a substructure of \(\fA_1\). Since \(\fA_1\) is a model of \varphi, \(\fA_2\) is also a
   model of \varphi. Therefore \(\fA_2\) cannot be a model of \(T_2\)

   \(2\to1\).   Here we add some details for the proof \(2\to 1\). If \(T_1\) and \(T_2\) cannot be separated by a
  universal sentence, then they have models \(\fA_1\) and \(\fA_2\)  which cannot be separated by a
  universal sentence. That is, for all universal sentence \varphi, if \(\fA_1\vDash\varphi\) then \(\fA_2\vDash\varphi\).
  Thus \(\fA_1\Rightarrow_\forall\fA_2\), here \(\Rightarrow_\forall\) means for all universal sentence.

  Now note that
  \begin{equation*}
  \fA_1\vDash\varphi\to\fA_2\vDash\varphi\quad\Leftrightarrow\quad\fA_2\vDash\neg\varphi\to\fA_2\vDash\neg\varphi
  \end{equation*}
  and \(\neg\varphi\) is an existential sentence. Hence we have
  \begin{equation*}
  \fA_2\Rightarrow_{\exists}\fA_1
  \end{equation*}

  The reason that we want to use \(\exists\) is that it holds in the substructure case and we could
  imagine that \(\fA_2\subseteq\fA_1\) (I guess this is our intuition). Now by Lemma ref:lemma3.1.2 we
  have \(\fA_1'\equiv\fA_1\) and a map \(f:\fA_2\to_\exists\fA_1'\).
  Apparently \(\fA_1'\vDash\Diag(\fA_2)\) and \(f\) is an embedding. Hence \(\fA_1'\) is a model of \(T_1\) and \(T_2\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any \(L\)-theory \(T\), the formulas \(\varphi(\bbar{x}),\psi(\bbar{x})\) are said
   to be *equivalent* modulo \(T\) (or relative to \(T\)) if \(T\vDash\forall\bbar{x}(\varphi(\bbar{x})\leftrightarrow\psi(\bbar{x}))\)
   #+END_definition

   [[index:universal theory]]
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor3.1.5
   Let \(T\) be a theory
   1. Consider a formula \(\varphi(x_1,\dots,x_n)\). The following are equivalent
      1. \(\varphi(x_1,\dots,x_n)\) is, modulo \(T\), equivalent to a universal formula
      2. If \(\fA\subseteq\fB\) are models of \(T\) and \(a_1,\dots,a_n\in A\),
         then \(\fB\vDash\varphi(a_1,\dots,a_n)\) implies \(\fA\vDash\varphi(a_1,\dots,a_n)\)
   2. We say that a theory which consists of universal sentences is universal.
      Then \(T\) is equivalent to a universal theory iff all substructures of
      models of \(T\) are again models of \(T\)
   #+END_corollary

   #+BEGIN_proof
   1. Assume (2). We extend \(L\) by an \(n\)-tuple \(\bbar{c}\) of new
      constants \(c_1,\dots,c_n\) and consider theory
      \begin{equation*}
      T_1=T\cup\{\varphi(\bbar{c})\}\quad\text{ and }\quad
      T_2=T\cup\{\neg\varphi(\bbar{c})\}
      \end{equation*}
      Then (2) says the substructures of models of \(T_1\) cannot be models of
      \(T_2\). By Theorem ref:thm3.1.3 \(T_1\) and \(T_2\) can be separated by a
      universal \(L(\bbar{c})\)-sentence \(\psi(\bbar{c})\). By Lemma
      ref:lemma1.3.4, \(T_1\vDash\psi(\bbar{c})\) implies
      \begin{equation*}
      T\vDash\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))
      \end{equation*}
      and from \(T_2\vDash\neg\psi(\bbar{c})\) we see
      \begin{equation*}
      T\vDash\forall\bbar{x}(\neg\varphi(\bbar{x})\to\neg\psi(\bbar{x}))
      \end{equation*}
   2. Suppose a theory \(T\) has this property. Let \varphi be an axiom of \(T\). If
      \(\fA\) is a substructure of \(\fB\), it is not possible for \(\fB\) to be
      a model of \(T\) and for \(\fA\) to be a model of \(\neg\varphi\) at the same
      time. By Theorem ref:thm3.1.3 there is a universal sentence \psi with
      \(T\vDash\psi\) and \(\neg\varphi\vDash\neg\psi\). Hence all axioms of
      \(T\) follow from
      \begin{equation*}
      T_\forall=\{\psi\mid T\vDash\psi,\psi\text{ universal}\}
      \end{equation*}
   #+END_proof

   An \(\forall\exists\)-formula is of the form
   \begin{equation*}
   \forall x_1\dots x_n\psi
   \end{equation*}
   where \psi is existential
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.1.6
   Suppose \varphi is an \(\forall\exists\)-sentence, \((\fA_i)_{i\in I}\) is a
   directed family of models of \varphi and \(\fB\) the union of the \(\fA_i\). Then
   \(\fB\) is also a model of \varphi.
   #+END_lemma

   #+BEGIN_proof
   Write
   \begin{equation*}
   \varphi=\forall\bbar{x}\psi(\bbar{x})
   \end{equation*}
   where \psi is existential. For any \(\bbar{a}\in B\) there is an \(A_i\)
   containing \(\bbar{a}\), clearly \(\psi(\bbar{a})\) holds in \(\fA_i\). As
   \(\psi(\bbar{a})\) is existential it must also hold in \(\fB\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We call a theory \(T\) *inductive* if the union of any directed family of
   models of \(T\) is again a model
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.8
   Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
   1. there is an \(\forall\exists\)-sentence which separates \(T_1\) and \(T_2\)
   2. No model of \(T_2\) is the union of a chain (or of a directed family) of
      models of \(T_1\)
   #+END_theorem


   #+BEGIN_proof
   \(1\to 2\). Assume \varphi is a \(\forall\exists\)-sentence which separates \(T_1\) from \(T_2\), \((\fA_i)_{i\in I}\) is a
   directed family of models of \varphi, by Lemma ref:lemma3.1.6 \(\fB\) is also a model of \varphi.
   Since \(\fB\vDash\varphi\), \(\fB\) cannot be a model of \(T_2\)

   \(2\to1\). If (1) is not true, Suppose \(\fA\vDash T_1\) and \(\fB^0\vDash T_2\). Then
  \begin{equation*}
  \fA\Rightarrow_{\forall\exists}\fB^0
  \end{equation*}
  Again we have
  \begin{equation*}
  \fB^0\Rightarrow_{\exists\forall}\fA
  \end{equation*}
  we have a map
  \begin{equation*}
  f':\fB^0\to_{\exists\forall}\fA^0
  \end{equation*}
  where \(\fA^0\equiv\fA\). Since \(\forall\)-sentences are also \(\exists\forall\)-sentences, we thus have a map \(f:\fB^0\to_{\forall}\fA^0\).

  Here we need to prove that \(\fB^0\) is isomorphic to a substructure of \(\fA^0\), which is clear
  since \(f\) is an embedding.
  Then we can assume that \(\fB^0\subseteq\fA^0\) and \(f\) is the inclusion map. Then
  \begin{equation*}
  \fA_B^0\Rightarrow_\exists\fB_B^0
  \end{equation*}
  (Here we are talking about existential sentences in the original language.
   If \(\fB^0\vDash\exists\barx\varphi(\barx)\) for some \(\varphi(\barx)\), then \(\fB^0\vDash\varphi(\barb)\). So we can use constants
   \(B\) to talk about existential sentences)
   Applying Lemma ref:lemma3.1.2 again, we obtain an extension \(\fB_B^1\) of
   \(\fA_B^0\) with \(\fB_B^1\equiv\fB_B^0\), i.e. \(\fB^0\prec\fB^1\). Hence we
   have an infinite chain
   \begin{gather*}
   \fB^0\subseteq\fA^0\subseteq^1\fB^1\subseteq\fA^1\subseteq\fB^2\subseteq\cdots\\
   \fB^0\prec\fB^1\prec\fB^2\prec\cdots\\
   \fA^i\equiv\fA
   \end{gather*}
   Let \(\fB\) be the union of the \(\fA^i\).  Since \(\fB\) is also the union
   of the elementary chain of the \(\fB^i\), it is an elementary extension of
   \(\fB^0\) and hence a model of \(T_2\). But the \(\fA^i\) are models of
   \(T_1\), so (2) does not hold
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(T\) be a theory
   1. For each sentence \varphi the following are equivalent
      1. \varphi is, modulo \(T\), equivalent to an \(\forall\exists\)-sentence
      2. If
         \begin{equation*}
         \fA^0\subseteq\fA^1\subseteq\cdots
         \end{equation*}
         and their union \(\fB\) are models of \(T\), then \varphi holds in \(\fB\) if
         it is true in all the \(\fA^i\)
   2. \(T\) is inductive iff it can be axiomatised by \(\forall\exists\)-sentences
   #+END_corollary

   #+BEGIN_proof
   1. Theorem ref:lemma3.1.6 shows that \(\forall\exists\)-formulas are preserved
      by unions of chains. Hence (a)\(\Rightarrow\)(b). For the converse
      consider the theories
      \begin{equation*}
      T_1=T\cup\{\varphi\} \quad\text{ and }\quad T_2=T\cup\{\neg\varphi\}
      \end{equation*}
      Part (b) says that the union of a chain of models of \(T_1\) cannot be a
      model of \(T_2\). By Theorem ref:thm3.1.8 we can separate \(T_1\) and
      \(T_2\) by an \(\forall\exists\)-sentence \psi. Hence
      \(T\cup\{\varphi\}\vDash\psi\) and
      \(T\cup\{\neg\varphi\}\vDash\neg\psi\)
   2. Clearly \(\forall\exists\)-axiomatised theories are inductive. For the
      converse assume that \(T\) is inductive and \varphi is an axiom of \(T\). Ifpp
      \(\fB\) is a union of models of \(T\), it cannot be a model of
      \(\neg\varphi\). By Theorem ref:thm3.1.8 there is an
      \(\forall\exists\)-sentence \psi with \(T\vDash\psi\) and
      \(\neg\varphi\vDash\neg\psi\). Hence all axioms of \(T\) follows from
      \begin{equation*}
      T_{\forall\exists}=\{\psi\mid T\vDash\psi,\psi\text{ $\forall\exists$-formula}\}
      \end{equation*}
   #+END_proof

   #+BEGIN_exercise
   label:ex3.1.1
   Let \(X\) be a topological space, \(Y_1\) and \(Y_2\) quasi-compact (compact but not necessarily
   Hausdorff) subsets, and \(\calh\) a  set of clopen subsets. Then the following are equivalent
   1. There is a positive Boolean combination \(B\) of elements from \(\calh\) s.t. \(Y_1\subseteq B\)
      and \(Y_2\cap B=\emptyset\)
   2. For all \(y_1\in Y_1\) and \(y_2\in Y_2\) there is an \(H\in\calh\) s.t. \(y_1\in H\) and \(y_2\not\in H\)
   #+END_exercise

   #+BEGIN_proof
   \(2\to 1\). Consider an element \(y_1\in Y_1\) and \(\calh_{y_1}\), the set of all elements of \(\calh\)
   containing \(y_1\). 2 implies that the intersection of the sets in \(\calh_{y_1}\) is disjoint
   from \(Y_2\). So a finite intersection \(h_{y_1}\) of elements of \(\calh_{y_1}\) is disjoint
   from \(Y_2\). The \(h_{y_i},y_1\in Y_1\), cover \(Y_1\). So \(Y_1\) is contained in the union \(H\) of
   finitely many of the \(h_{y_i}\). Hence \(H\) separates \(Y_1\) from \(Y_2\)


   #+END_proof
** Quantifier elimination
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A theory \(T\) has *quantifier elimination* if every \(L\)-formula
   \(\varphi(x_1,\dots,x_n)\) in the theory is equivalent modulo \(T\) to some
   quantifier-free formula \(\rho(x_1,\dots,x_n)\)
   #+END_definition

   For \(n=0\), this means that modulo \(T\) every sentence is equivalent to a quantifier-free
   sentence. _If \(L\) has no constants, \(\top\) and \(\bot\) are the only quantifier free sentences._
   _Then \(T\) is either inconsistent or complete._

   It's easy to transform any theory \(T\) into a theory with quantifier
   elimination if one is willing to expand the language: just enlarge \(L\) by
   adding an \(n\)-place relation symbol \(R_{\varphi}\) for every \(L\)-formula
   \(\varphi(x_1,\dots,x_n)\) and \(T\) by adding all axioms
   \begin{equation*}
   \forall x_1,\dots,x_n(R_\varphi(x_1,\dots,x_n)\leftrightarrow\varphi(x_1,\dots,x_n))
   \end{equation*}
   The resulting theory, the *Morleyisation* \(T^m\) of \(T\), has quantifier
   elimination

   A *prime structure* of \(T\) is a structure which embeds into all models of
   \(T\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.2.2
   A consistent theory \(T\) with quantifier elimination which possess a prime
   structure is complete
   #+END_lemma

   #+BEGIN_proof
   If \(\fM,\fN\vDash T\) and \(\fM\vDash\varphi\) and
   \(\fN\vDash\neg\varphi\). Suppose prime structure is \(\fH\), then \(\fH\vDash\varphi\) and \(\fH\vDash\neg\varphi\) since we have quantifier elimination
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *simple existential formula* has the form
   \begin{equation*}
   \varphi=\exists y\rho
   \end{equation*}
   for a quantifier-free formula \rho. If \rho is a conjunction of basic formulas, \varphi
   is called *primitive existential*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.2.4
   The theory \(T\) has quantifier elimination iff every primitive existential
   formula is, modulo \(T\), equivalent to a quantifier-free formula
   #+END_lemma

   #+BEGIN_proof
   We can write every simple existential formula in the form \(\exists y\bigvee_{i<n}\rho_i\) for \(\rho_i\) which are
   conjunctions of basic formulas. This shows that every simple existential formula is equivalent to
   a disjunction of primitive existential formulas, namely to \(\bigvee_{i<n}(\exists y\rho_i)\). We can therefore
   assume that every simple existential formula is, modulo \(T\), equivalent to a quantifier-free
   formula

   We are now able to eliminate the quantifiers in arbitrary formulas in prenex normal form
   (Exercise ref:ex1.2.3)
   \begin{equation*}
   Q_1x_1\dots Q_nx_n\rho
   \end{equation*}
   if \(Q_n=\exists\), we choose a quantifier-free formula \(\rho_0\) which,
   modulo \(T\), is equivalent to \(\exists x_n\rho\) and proceed with the
   formula \(Q_1x_1\dots Q_{n-1}x_{n-1}\rho_0\). If \(Q_n=\forall\), we
   find a quantifier-free \(\rho_1\) which is, modulo \(T\), equivalent to
   \(\exists x_n\neg\rho\) and proceed with \(Q_1x_1\dots Q_{n-1}x_{n-1}\neg\rho_1\)
   #+END_proof
   

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.2.5
   For a theory \(T\) the following are equivalent
   1. \(T\) has quantifier elimination
   2. For all models \(\fM^1\) and \(\fM^2\) of \(T\) with a common substructure
      \(\fA\) we have
      \begin{equation*}
      \fM_A^1\equiv\fM_A^2
      \end{equation*}
   3. For all models \(\fM^1\) and \(\fM^2\) of \(T\) with a common substructure
      \(\fA\) and for all primitive existential formulas \(\varphi(x_1,\dots,x_n)\)
      and parameter \(a_1,\dots,a_n\) from \(A\) we have
      \begin{equation*}
      \fM^1\vDash\varphi(a_1,\dots,a_n)\Rightarrow\fM^2\vDash\varphi(a_1,\dots,a_n)
      \end{equation*}
      (this is exactly the equivalence relation)

   If \(L\) has no constants, \(\fA\) is allowed to be the empty "structure"
   #+END_theorem

   #+BEGIN_proof
   \(1\to 2\). Let \(\varphi(\bara)\) be an \(L(A)\)-sentence which holds in \(\fM^1\). Choose a
   quantifier-free \(\rho(\barx)\) which is, modulo \(T\), equivalent to \(\varphi(\barx)\). Then
   | \(\fM^1\) | \(\vDash\) | \(\varphi(\bara)\)  | \(\Rightarrow\) | \(\fM^1\) | \(\vDash\) | \(\rho(\bara)\)  |       |
   |        |       |               | \(\Rightarrow\) | \(\fA\)  | \(\vDash\) | \(\rho(\bara))\) | \(\Rightarrow\) |
   | \(\fM^2\) | \(\vDash\) | \(\rho(\bara))\) | \(\Rightarrow\) | \(\fM^2\) | \(\vDash\) | \(\varphi(\bara)\)  |       |

   \(3\to1\). Let \(\varphi(\bbar{x})\) be a primitive existential formula. In order
   to show that \(\varphi(\bbar{x})\) is equivalent, modulo \(T\), to a
   quantifier-free formula \(\rho(\bbar{x})\) we extend \(L\) by an \(n\)-tuple
   \(\bbar{c}\) of new constants \(c_1,\dots,c_n\). *We have to show that we can*
   *separate \(T\cup\{\varphi(\bbar{c})\}\) and \(T\cup\{\neg\varphi(\bbar{c})\}\) by a*
   *quantifier free sentence \(\rho(\bbar{c})\)*. Then \(T\vDash\varphi(\barc)\to\rho(\barc)\)
   and \(T\vDash\neg\varphi(\barc)\to\neg\rho(\barc)\). Hence \(T\vDash\varphi(\barc)\leftrightarrow\rho(\barc)\).

   We apply the Separation Lemma
   (\(\calh\) hear is the set of quantifier-free sentence). Let
   \(\fM^1\) and \(\fM^2\) be two models of \(T\) with two distinguished
   \(n\)-tuples \(\bbar{a}^1\) and \(\bbar{a}^2\). Suppose that
   \((\fM^1,\bbar{a}^1)\) and \((\fM^2,\bbar{a}^2)\) satisfy the same
   quantifier-free \(L(\bbar{c})\)-sentences. We have to show that
   \begin{equation*}
   \fM^1\vDash\varphi(\bbar{a}^1)\Rightarrow
   \fM^2\vDash\varphi(\bbar{a}^2)\tag{\star}
   \end{equation*}
   which says that if \(T\)'s model \(\fA_1,\fA_2\) satisfies the same quantifier-free sentences, then
   \(\fM^1\Rightarrow_{\exists}\fM^2\). If \(\fM^1\vDash T\cup\{\varphi(\barc)\}\) and \(\fM^2\vDash T\cup\{\neg\varphi(\barc)\}\) and satisfy the same
   quantifier-free \(L(\barc)\) sentence, then \(\fM^1\subseteq \fM^2\) , a contradiction.
   Thus we finish the proof

   Consider the substructure \(\fA^i=\la\bbar{a}^i\ra^{\fM^i}\), generated by
   \(\bbar{a}^i\). If we can show that there is an isomorphism
   \begin{equation*}
   f:\fA^1\to\fA^2
   \end{equation*}
   taking \(\bbar{a}\) to \(\bbar{a}\), we may assume that \(\fA^1=\fA^2=\fA\)
   and \(\bbar{a}^1=\bbar{a}^2=\bbar{a}\). Then \(\star\) follows directly from 3.

   Every element of \(\fA^1\) has the form \(t^{\fM^1}[\bbar{a}^1]\) for an
   \(L\)-term \(t(\bbar{x})\). The isomorphism \(f\)to be constructed must
   satisfy
   \begin{equation*}
   f(t^{\fM^1}[\bbar{a}^1])=t^{\fM^2}[\bbar{a}^2]
   \end{equation*}
   We define \(f\) by this equation and have to check that \(f\) is well defined
   and injective. Assume
   \begin{equation*}
   s^{\fM^1}[\bbar{a}^1]=t^{\fM^1}[\bbar{af^1}]
   \end{equation*}
   Then \(\fM^1,\bbar{a}^1\vDash s(\bbar{c})\dot{=}t(\bbar{c})\), and by our
   assumption, \(\fM^1\) and \(\fM^2\) satisfy the same quantifier-free \(L(\barc)\)-sentence,  it also
   holds in \((\fM^2,\bbar{a}^2)\), which means
   \begin{equation*}
   s^{\fM^2}[\bbar{a}^2]=t^{\fM^2}[\bbar{a}^2]
   \end{equation*}
   Swapping the two sides yields injectivity.

   Surjectivity is clear. It remains to show that \(f\) commutes with the
   interpretation of the relation symbols. Now
   \begin{equation*}
   \fM^1\vDash R\left[t_1^{\fM^1}[\bbar{a}^1],\dots,t_m^{\fM^1}[\bbar{a}^1]\right]
   \end{equation*}
   is equivalent to \((\fM^1,\bbar{a}^1)\vDash R(t_1(\bbar{c}),\dots,t_m(\bbar{c}))\), which is equivalent to
   \((\fM^2,\bbar{a}^2)\vDash R(t_1(\bbar{c}),\dots,t_m(\bbar{c}))\), which in turn is equivalent to
   \begin{equation*}
   \fM^2\vDash R\left[t_1^{\fM^2}[\bbar{a}^2],\dots,t_m^{\fM^2}[\bbar{a}^2]\right]
   \end{equation*}
   #+END_proof

   Note that (2) of Theorem ref:thm3.2.5 is saying that \(T\) is *substructure
   complete*; i.e., for any model \(\fM\vDash T\) and substructure
   \(\fA\subseteq\fM\) the theory \(T\cup\Diag(\fA)\) is complete

   [[index:model complete]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We call \(T\) *model complete* if for all models \(\fM^1\) and \(\fM^2\) of
   \(T\)
   \begin{equation*}
   \fM^1\subseteq\fM^2\Rightarrow\fM^1\prec\fM^2
   \end{equation*}
   #+END_definition

   \(T\) is model complete iff for any \(\fM\vDash T\) the theory
   \(T\cup\Diag(\fM)\) is complete

   Note that if \(\fM_1\vDash\Diag(\fM)\), then there is an embedding \(h:\fM\to\fM_1\) and \(\fM_1\) is isomorphic to
   an extension \(\fM_1'\) of \(\fM\). Then we have \(\fM\subseteq\fM_1'\).

   So here we are actually saying that all embeddings are elementary

   #+ATTR_LATEX: :options [Robinson's Test]
   #+BEGIN_lemma
   label:lemma3.2.7
   Let \(T\) be a theory. Then the following are equivalent
   1. \(T\) is model complete
   2. For all models \(\fM^1\subseteq\fM^2\) of \(T\) and all existential
      sentences \varphi from \(L(M^1)\)
      \begin{equation*}
      \fM^2\vDash\varphi\Rightarrow\fM^1\vDash\varphi
      \end{equation*}
   3. Each formula is, modulo \(T\), equivalent to a universal formula
   #+END_lemma

   #+BEGIN_proof
   \(1\leftrightarrow3\). Corollary ref:cor3.1.5

   (2) and Corollary ref:cor3.1.5 shows that all existential sentences are, modulo \(T\), equivalent
   to a universal sentence. Then by induction we can show 3. [[https://math.stackexchange.com/questions/321737/proof-of-robinsons-test/2050990][(Details)]]

   #+END_proof

   If \(\fM^1\subseteq\fM^2\) satisfies (2), we call \(\fM^1\) *existentially
   closed* in \(\fM^2\). We denote this by
   \begin{equation*}
   \fM^1\prec_1\fM^2
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(T\) be a theory. A theory \(T^*\) is a *model companion* of \(T\) if the
   following three conditions are satisfied
   1. Each model of \(T\) can be extended to a model of \(T^*\)
   2. Each model of \(T^*\) can be extended to a model of \(T\)
   3. \(T^*\) is model complete
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.2.9
   A theory \(T\) has, up to equivalence, at most one model companion \(T^*\)
   #+END_theorem

   #+BEGIN_proof
   If \(T^+\) is another model companion of \(T\), every model of \(T^+\) is
   contained in a model of \(T^*\) and conversely. Let \(\fA_0\vDash T^+\) .
   Then \(\fA_0\) can be embedded in a model \(\fB_0\) of \(T^*\). In turn
   \(\fB_0\) is contained in a model \(\fA_1\) of \(T^+\). In this way we find
   two elementary chains \((\fA_i)\) and \((\fB_i)\), which have a common union
   \(\fC\). Then \(\fA_0\prec\fC\) and \(\fB_0\prec\fC\) implies
   \(\fA_0\equiv\fB_0\) since \(T\) are all sentences. Thus \(\fA_0\) is a model of \(T^*\)
   #+END_proof
*** Existentially closed structures and the Kaiser hull
    Let \(T\) be an \(L\)-theory. It follows from ref:thm3.1.3 that the models
    of \(T_\forall=\{\varphi\mid T\vDash\varphi\text{ where $\varphi$ is universal}\}\) are the substructures of models of \(T\). The conditions
    (1) and (2) in the definition of "model companion" can therefore be
    expressed as
    \begin{equation*}
    T_{\forall}=T_{\forall}^*
    \end{equation*}
    (1 and 2 says \(\Mod(T_\forall)=\Mod(T_\forall^*)\))
    Hence the model companion of a theory \(T\) depends only on \(T_{\forall}\).


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An \(L\)-structure \(\fA\) is called *\(T\)-existentiallay closed* (or
    *\(T\)-ec*) if
    1. \(\fA\) can be embedded in a model of \(T\)
    2. \(\fA\) is existentially closed in every extension which is a model of \(T\)
    #+END_definition

    A structure \(\fA\) is \(T\)-ec exactly if it is \(T_{\forall}\)-ec. Since
    every model of \(\fB\) of \(T_{\forall}\) can be embedded in a model \(\fM\)
    of \(T\) and \(\fA\subseteq\fB\subseteq\fM\) and \(\fA\prec_1\fM\) implies \(\fA\prec_1\fB\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.2.11
    Every model of a theory \(T\) can be embedded in a \(T\)-ec structure
    #+END_lemma

    #+BEGIN_proof
    Let \(\fA\) be a model of \(T_{\forall}\). We choose an enumeration
    \((\varphi_\alpha)_{\alpha<\kappa}\) of all existential \(L(A)\)-sentences and
    construct an ascending chain \((\fA_\alpha)_{\alpha\le\kappa}\) of models of
    \(T_{\forall}\). We begin with \(\fA_0=\fA\). Let \(\fA_\alpha\) be
    constructed. If \(\varphi_\alpha\) holds in an extension of \(\fA_\alpha\)
    which is a model of \(T\) we let \(\fA_{\alpha+1}\) be such a model.
    Otherwise we set \(\fA_{\alpha+1}=\fA_{\alpha}\). For limit ordinals \lambda we define
    \(\fA_\lambda\) to be the union of all \(\fA_\alpha\). \(\fA_\lambda\) is
    again a model of \(T_{\forall}\)

    The structure \(\fA^1=\fA_\kappa\) has the following property: every existential \(L(A)\)-sentence which
    holds in an extension of \(\fA^1\) that is a model of \(T\) holds in \(\fA^1\). Now in the same
    manner, we construct \(\fA^2\) from \(\fA^1\), etc. The union \(\fM\) of the chain \(\fA^0\subseteq\fA^1\subseteq\fA^2\subseteq\dots\) is the
    desired \(T\)-ec structure
    #+END_proof

    Every elementary substructure \(\fN\) of a \(T\)-ec structure \(\fM\) is
    again \(T\)-ec: Let \(\fN\subseteq\fA\) be a model of \(T\). Since
    \(\fM_N\Rightarrow_{\exists}\fA_N\), there is an embedding of \(\fM\) in an
    elementary extension \(\fB\) of \(\fA\) which is the identity on \(N\).
    Since \(\fM\) is existentially closed in \(\fB\), it follows that \(\fN\) is
    existentially closed in \(\fB\) and therefore also in \(\fA\)

    \begin{center}\begin{tikzcd}
    &\fB&\\
    \fA\arrow[ur,"\prec"]&&\fM\arrow[ul,"\prec_1"']\\
    &\fN\arrow[ul,"\prec_1"]\arrow[ur,"\prec"']&
    \end{tikzcd}\end{center}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(T\) be a theory. Then there is a biggest inductive theory \(T^{\KH}\)
    with \(T_{\forall}=T_{\forall}^{\KH}\). We call \(T^{\KH}\) the *Kaiser hull*
    of \(T\)
    #+END_lemma

    #+BEGIN_proof
    Let \(T^1\) and \(T^2\) be two inductive theories with
    \(T_{\forall}^1=T_{\forall}^2=T_{\forall}\). We have to show
    that \((T^1\cup T^2)_\forall=T_\forall\). Note that for every model \(\fA\vDash T^1\) and \(\fB\vDash T^2\) we have
    \(\fA\Rightarrow_\forall\fB\) and vice versa. Then we have the embeddings just like model companions.
    Let \(\fM\) be a model
    of \(T\), as in the proof of ref:thm3.2.9 we extend \(\fM\) by a chain
    \(\fA_0\subseteq\fB_0\subseteq\fA_1\subseteq\fB_1\subseteq\cdots\) of models
    of \(T^1\) and \(T^2\). The union of this chain is a model of \(T^1\cup T^2\)


    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.2.13
    The Kaiser hull \(T^{KH}\) is the \(\forall\exists\)-part of the theory of
    all \(T\)-ec structures
    #+END_lemma

    #+BEGIN_proof
    Let \(T^*\) be the \(\forall\exists\)-part of the theory of all \(T\)-ec
    structures. Since \(T\)-ec structures are models of \(T_{\forall}\), we have
    \(T_\forall\subseteq T^*_\forall\). It follows from ref:lemma3.2.11 that
    \(T_\forall^*\subseteq T_\forall\). Hence \(T^*\) is contained in the Kaiser Hull.

    It remains to show that every \(T\)-ec structure \(\fM\) is a model of the Kaiser hull. Choose a
    model \(\fN\) of \(T^{KH}\) which contains \(\fM\). Then \(\fM\prec_1\fN\). This implies \(\fN\Rightarrow_{\forall\exists}\fM\) and
    therefore \(\fM\vDash T^{KH}\)
    #+END_proof

    This implies that \(T\)-ec strctures are models of \(T_{\forall\exists}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any theory \(T\) the following are equivalent
    1. \(T\) has a model companion \(T^*\)
    2. All models of \(K^{\KH}\) are \(T\)-ec
    3. The \(T\)-ec structures form an elementary class.


    If \(T^*\) exists, we have
    \begin{equation*}
    T^*=T^{\KH}=\text{ theory of all $T$-ec structures}
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    \(1\to 2\): let \(T^*\) be the model companion of \(T\). As a model complete theory

    \(3\to 1\): Assume that the \(T\)-ec structures are exactly the models of the theory \(T^+\). By
    ref:lemma3.2.11 we have \(T_\forall=T_\forall^+\). Criterion ref:lemma3.2.7 implies that \(T^+\) is model
    complete. So \(T^+\) is the model companion of \(T\).

    #+END_proof


    #+BEGIN_exercise
    label:ex3.2.1
    Let \(L\) be the language containing a unary function \(f\) and a binary
    relation symbol \(R\) and consider the \(L\)-theory \(T=\{\forall x\forall
    y(R(x,y)\to (R(x,f(y))))\}\). Showing the follow
    1. For any \(T\)-structure \(\fM\) and \(a,b\in M\) with
       \(b\not\in\{a,f^{\fM}(a),(f^{\fM})^2(a),\dots\}\) we have
       \(\fM\vDash\exists z(R(z,a)\wedge\neg R(z,b))\)
    2. Let \(\fM\) be a model of \(T\) and \(a\) an element of \(M\) s.t.
       \(\{a,f^{\fM}(a),(f^{\fM})^2(a),\dots\}\) is infinite. Then in an
       elementary extension \(\fM'\) there is an element \(b\) with
       \(\fM'\vDash\forall z(R(z,a)\to R(z,b))\)
    3. The class of \(T\)-ec structures is not elementary, so \(T\) does not
       have a model companion
    #+END_exercise

    #+BEGIN_exercise
    label:ex3.2.3
    A theory \(T\) with quantifier elimination is axiomatisable by sentences of
    the form
    \begin{equation*}
    \forall x_1\dots x_n\psi
    \end{equation*}
    where \psi is primitive existential formula
    #+END_exercise
** Examples
   *Infinite sets*. The models of the theory  \(\Infset\) of *infinite sets* are all
   infinite sets without additional structure. The language \(L_{\emptyset}\) is
   empty, the axioms are (for \(n=1,2,\dots\))
   * \(\exists x_0\dots x_{n-1}\bigwedge_{i<j<n}\neg x_i\dot{=}x_j\)

     #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The theory \(\Infset\) of infinite sets has quantifier elimination and is complete
   #+END_theorem

   #+BEGIN_proof
   Since the language is empty, the only basic formula is \(x_i=x_j\) and
   \(\neg(x_i=x_j)\). By Lemma ref:lemma3.2.4 we only need to consider primitive
   existential formulas. Then every sentence is actually saying there is \(n\) different elements.
   Then for any \(\fM^1,\fM^2\vDash\Infset\), they have a common substructure \(\fA\) with \omega different elements.
   Visibly, \(\fM^1_A\equiv\fM^2_A\)
   #+END_proof

   *Dense linear orderings*.
   \begin{align*}
   &\forall a,b(a\le b\wedge b\le a\to a\dot{=}b)\\
   &\forall a,b,c(a\le b\wedge b\le c\to a\le c)\\
   &\forall a,b(a\le b\vee b\le a)\\
   &\forall a,b\exists c(a< b\to a< c< b)
   \end{align*}
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   \(\DLO\) has quantifier elimination
   #+END_theorem

   #+BEGIN_proof
   Let \(A\) be a finite common substructure of the two models \(O_1\) and
   \(O_2\). We choose an ascending enumeration \(A=\{a_1,\dots,a_n\}\). Let
   \(\exists y\rho (y)\) be a simple existential \(L(A)\)-sentence, which is
   true in \(O_1\) and assume \(O_1\vDash\rho(b_1)\). We want to extend the
   order preserving map \(a_i\mapsto a_i\) to an order preserving map
   \(A\cup\{b_1\}\to O_2\). For this we have an image \(b_2\) of \(b_1\). There
   are four cases
   1. \(b_1\in A\), we set \(b_2=b_1\)
   2. \(b_1\in(a_i,a_{i+1})\). We choose \(b_2\) in \(O_2\) with the same property
   3. \(b_1\) is smaller than all elements of \(A\). We choose a \(b_2\in O_2\)
      of the same kind
   4. \(b_1\) is bigger than all \(a_i\). Choose \(b_2\) in the same manner


   This defines an isomorphism \(A\cup\{b_1\}\to A\cup\{b_2\}\), which show that \(O_2\vDash\rho(b_2)\)
   #+END_proof


   *Modules*. Let \(R\) be a (possibly non-commutative) ring with 1. An
   \(R\)-module
   \begin{equation*}
   \fM=(,0,+,-,r)_{r\in R}
   \end{equation*}
   is an abelian group \((M,0,+,-)\) together with operations \(r:M\to M\) for
   every ring element \(r\in R\). We formulate the axioms in the language
   \(L_{Mod}(R)=L_{AbG}\cup\{r\mid r\in R\}\). The theory \(\sfMod(R)\) of
   \(R\)-modules consists of
   \begin{align*}
   &\AbG\\
   &\forall x,y\; r(x+y)\dot{=}rx+ry\\
   &\forall x\;(r+s)x\dot{=}rx+sx\\
   &\forall x\;(rs)x\dot{=}r(sx)\\
   &\forall x\;1x\dot{=}x
   \end{align*}
   for all \(r,s\in R\). Then \(\Infset\cup\sfMod(R)\) is the theory of all
   infinite \(R\)-modules

   A module over fields is a vector space

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \(K\) be a field. Then the theory of all infinite \(K\)-vector spaces has
   quantifier elimination and is complete
   #+END_theorem

   #+BEGIN_proof
   Let \(A\) be a common finitely generated substructure (i.e., a subspace) of
   the two infinite \(K\)-vector spaces \(V_1\) and \(V_2\). Let \(\exists y\rho(y)\) be a simple
   existential \(L(A)\)-sentence which holds in \(V_1\).
   Choose a \(b_1\) from \(V_1\) which satisfies \(\rho(y)\). If \(b_1\) belongs to
   \(A\), we finished. If not, we choose a \(b_2\in V_2\setminus A\). Possibly
   we have to replace \(V_2\) by an elementary extension. The vector spaces
   \(A+Kb_1\) and \(A+Kb_2\) are isomorphic by an isomophism which maps \(b_1\)
   to \(b_2\) and fixes \(A\) elementwise. Hence \(V_2\vDash\rho(b_2)\)

   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An *equation* is an \(L_{Mod}(R)\)-formula \(\gamma(\bbar{x})\) of the form
   \begin{equation*}
   r_1x_1+\dots+r_mx_m=0
   \end{equation*}
   A *positive primitive* formula (*pp*-formula) is of the form
   \begin{equation*}
   \exists\bbar{y}(\gamma_1\wedge\dots\wedge\gamma_n)
   \end{equation*}
   where the \(\gamma_i(\bbar{xy})\) are equations
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.3.5
   For every ring \(R\) and any \(R\)-module \(M\), every \(L_{Mod}(R)\)-formula
   is equivalent (modulo the theory of \(M\)) to a Boolean combination of
   positive primitive formulas
   #+END_theorem

   #+BEGIN_remark
   1. We assume the class of positive primitive formulas to be closed under \(\wedge\)
   2. A pp-formula \(\varphi(x_1,\dots,x_n)\) defines a subgroup \(\varphi(M^n)\) of \(M^n\):
      \begin{equation*}
      M\vDash\varphi(0) \quad\text{ and }\quad M\vDash\varphi(x)\wedge\varphi(y)\to\varphi(x-y)
      \end{equation*}
   #+END_remark

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.3.7
   Let \(\varphi(x,y)\) be a pp-formula and \(a\in M\). Then \(\varphi(M,a)\) is empty or a coset of \(\varphi(M,0)\)
   #+END_lemma

   #+BEGIN_proof
   \(M\vDash\varphi(x,a)\to(\varphi(y,0)\leftrightarrow\varphi(x+y,a))\)

   Or, if \(x,y\in \varphi(M,a)\), then \(\varphi(x-y,0)\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(a,b\in M\), \(\varphi(x,y)\) a pp-formula. Then (in \(M\)) \(\varphi(x,a)\) and \(\varphi(x,b)\) are equivalent
   or contradictory
   #+END_corollary

   #+ATTR_LATEX: :options [B. H. Neumann]
   #+BEGIN_lemma
   label:lemma3.3.9
   Let \(H_i\) denote subgroups of some abelian group. If \(H_0+a_0\subseteq\bigcup_{i=1}^nH_i+a_i\)
   and \(H_0/(H_0\cap H_i)\) is infinite for \(i>k\), then \(H_0+a_0\subseteq\bigcup_{i=1}^kH_i+a_i\)
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(A_i,i\le k\), be any sets. If \(A_0\) is finite, then \(A_0\subseteq\bigcup_{i=1}^k A_i\) iff
   \begin{equation*}
   \sum_{\Delta\subseteq\{1,\dots,k\}}(-1)^{\abs{\Delta}}\abs{A_0\cap\bigcap_{i\in\Delta}A_i}=0
   \end{equation*}
   #+END_lemma

   *Algebraically closed fields*.
   #+ATTR_LATEX: :options [Tarski]
   #+BEGIN_theorem
   The theory \(\sfACF\) of algebraically closed fields has quantifier elimination
   #+END_theorem

   #+BEGIN_proof
   Let \(K_1\) and \(K_2\) be two algebraically closed fields and \(R\) a common
   subring. Let \(\exists y\rho(y)\) be a simple existential sentence with
   parameters in \(R\) which hold in \(K_1\). We have to show that \(\exists y\rho(y)\) is also true in \(K_2\).

   Let \(F_1\) and \(F_2\) be the quotient fields of \(R\) in \(K_1\) and
   \(K_2\), and let \(f:F_1\to F_2\) be an isomorphism which is the identity on
   \(R\). Then \(f\) extends to an isomorphism \(g:G_1\to G_2\) between the
   relative algebraic closures \(G_i\) of \(F_i\) in \(K_i\). Choose an element \(b_1\in K_1\) which
   satisfies \(\rho(y)\)

   \begin{center}\begin{tikzcd}[column sep=40pt]
   K_1&K_2\\
   G_1\ar[u,dash,"G_1(b_1)" description]\ar[r,"g"]&G_2\ar[u,dash]\\
   F_1\ar[u,dash]\ar[r,"f"]&F_2\ar[u,dash]\\
   R\ar[u,dash]\ar[r,"id"]&R\ar[u,dash]
   \end{tikzcd}\end{center}
   There are two cases

   Case 1: \(b_1\in G_1\). Then \(b_2=g(b_1)\) satisfies the formula \(\rho(y)\) in \(K_2\)

   Case 2: \(b_1\not\in G_1\). Then \(b_1\) is transcendental over \(G\) and the field
   extension \(G_1(b_1)\) is isomorphic to the rational function field \(G_1(X)\). If \(K_2\) is a
   proper extension of \(G_2\), we choose any element from \(K_2\setminus G_2\) for \(b_2\). Then \(g\) extends
   to an isomorphism between \(G_1(b_1)\) and \(G_2(b_2)\) which maps \(b_1\) to \(b_2\). Hence \(b_2\)
   satisfies \(\rho(y)\) in \(K_2\). In case that \(K_2=G_2\) we take a proper elementary
   extension \(K_2'\) of \(K_2\) (Such a \(K_2'\) exists by ref:thm2.3.1 since \(K_2\) is infinite).
   Then \(\exists y\rho(y)\) holds in \(K_2'\) and therefore in \(K_2\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   \(\ACF\) is model complete
   #+END_corollary

   \(\ACF\) is not complete: for prime numbers \(p\) let
   \begin{equation*}
   \ACF_p=\ACF\cup\{p\cdot 1\dot=0\}
   \end{equation*}
   be the theory of algebraically closed fields of characteristic \(p\) and
   \begin{equation*}
   \ACF_0=\ACF\cup\{\neg n\cdot 1\dot=0\mid n=1,2,\dots\}
   \end{equation*}
   be the theory of algebraically closed fields of characteristic 0.

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   The theories \(\ACF_p\)  and \(\ACF_0\) are complete
   #+END_corollary

   #+BEGIN_proof
   This follows from Lemma ref:lemma3.2.2 since the prime fields are prime structures for these theories
   #+END_proof

   #+ATTR_LATEX: :options [Hilbert's Nullstellensatz]
   #+BEGIN_corollary
   Let \(K\) be a field. Then any proper ideal \(I\) in \(K[X_1,\dots,X_n]\) has a zero in the algebraic
   closure \(\acl(K)\)
   #+END_corollary

   #+BEGIN_proof
   As a proper ideal, \(I\) is contained in a maximal ideal \(P\). Then \(L=K[X_1,\dots,X_n]/P\) is an
   extension field of \(K\) in which the cosets of the \(X_i\) are a zero of \(I\).
   #+END_proof

   *Real closed fields*. It is axiomatised in the language \(L_{ORing}\) of ordered rings

   #+ATTR_LATEX: :options [Tarski-Seidenberg]
   #+BEGIN_theorem
   \(\RCF\) has quantifier elimination and is complete
   #+END_theorem

   #+BEGIN_proof
   Let \((K_1,<)\) and \((K_2,<)\) be two real closed field with a common subring \(R\). Consider
   an \(L_{ORing}(R)\)-sentence \(\exists y\rho(y)\) (for a quantifier-free \rho), which holds in \((K_1,<)\).
   We have to show \(\exists y\rho(y)\) also holds in \((K_2,<)\)

   We build first the quotient fields \(F_1\) and \(F_2\) of \(R\) in \(K_1\) and \(K_2\). By ref:B.1.1
   there is an isomorphism \(f:(F_1,<)\to(F_2,<)\) which fixes \(R\). The relative algebraic
   closure \(G_i\) of \(F_i\) in \(K_i\) is a real closure of \((F_i,<)\). By ref:B.1.5 \(f\) extends to
   an isomorphism \(g:(G_1,<)\to(G_2,<)\)

   Let \(b_1\in K_1\) which satisfies \(\rho(y)\). There are two cases

   Case 1: \(b_1\in G_1\): Then \(b_2=g(b_1)\) satisfies \(\rho(y)\) in \(K_2\)

   Case 2: \(b_1\not\in G_1\). Then \(b_1\) is transcendental over \(G_1\) and the field
   extension \(G_1(b_1)\) is isomorphic to the rational function field \(G_1(X)\). Let \(G_1^l\) be the
   set of all elements of \(G_1\) which are smaller than \(b_1\), and \(G_1^r\) be the set of all
   elements of \(G_1\) which are larger than \(b_1\). Then all elements of \(G_2^l=g(G_1^l)\) are smaller
   than all elements of \(G_2^r=g(G_1^r)\). Since fields are densely ordered, we find in an elementary
   extension \((K_2',<)\) of \((K_2,<)\) an element \(b_2\) which lies between the elements of \(G_2^l\)
   and the elements of \(G_2^r\). Since \(b_2\) is not in \(G_2\), it is transcendental over \(G_2\).
   Hence \(g\) extends to an isomorphism \(h:G_1(b_1)\to G_2(b_2)\) which maps \(b_1\) to \(b_2\)

   In order to how that \(h\) is order preserving it suffices to show that \(h\) is order preserving
   on \(G_1[b_1]\). Let \(p(b_1)\) be an element of \(G_1[b_1]\). Corollary ref:B.1.8 gives us a
   decomposition
   \begin{equation*}
   p(X)=\epsilon\prod_{i<m}(X-a_i)\prod_{j<n}((X-c_j)^2+d_j)
   \end{equation*}
   with positive \(d_j\). The sign of \(p(b_1)\) depends only on the signs of the factors
   \(\epsilon,b_1-a_0,\dots,b_1-a_{m-1}\). The sign of \(h(p(b_1))\) depends in the same way on the signs
   of \(g(\epsilon),b_2-g(a_0),\dots,b_2-g(a_{m-1})\). But \(b_2\) was chosen in such a way that
   \begin{equation*}
   b_1<a_i\Longleftrightarrow b_2<g(a_i)
   \end{equation*}
   Hence \(p(b_1)\) is positive iff \(h(p(b_1))\) is positive

   Finally we have
   \begin{alignat*}{3}
   &(K_1,<)\vDash\rho(b_1)&&\Rightarrow (G_1(b_1),<)\vDash\rho(b_1)&&\Rightarrow(G_2(b_2),<)\vDash\rho(b_2)\Rightarrow\\
   &&&\Rightarrow(K_2',<)\vDash\exists y\rho(y)&&\Rightarrow(K_2,<)\vDash\exists y\rho(y)
   \end{alignat*}
   \(\RCF\) is complete since the ordered field of the rationals is a prime structure
   #+END_proof

   #+ATTR_LATEX: :options [Hilbert's 17th Problem]
   #+BEGIN_corollary
   Let \((K,<)\) be a real closed field. A polynomial \(f\in K[X_1,\dots,X_n]\) is a sum of squares
   \begin{equation*}
   f=g_1^2+\dots+g_k^2
   \end{equation*}
   of rational functions \(g_i\in K(X_1,\dots,X_n)\) iff
   \begin{equation*}
   f(a_1,\dots,a_n)\ge 0
   \end{equation*}
   for all \(a_1,\dots,a_n\in K\)
   #+END_corollary

   #+BEGIN_proof
   Clearly a sum of squares cannot have negative values. For the converse,
   assume that \(f\) is not a sum of squares. Then by Corollary ref:B.1.3, \(K(X_1,\dots,X_n)\) has an
   ordering in which \(f\) is negative. Since in \(K\) the positive elements are squares, this
   ordering , which we denote by <, extends the ordering of \(K\). Let \((L,<)\) be the real closure
   of \((K(X_1,\dots,X_n),<)\). In \((L,<)\), the sentence
   \begin{equation*}
   \exists x_1,\dots,x_n f(x_1,\dots,x_n)<0
   \end{equation*}
   is true. Hence it is also true in \((K,<)\)
   #+END_proof

   #+BEGIN_exercise
   label:ex3.3.1
   Let \(\Graph\) be the theory of graphs. The theory \(\RG\) of the *random graph* is the extension
   of \(\Graph\) by the following axiom scheme
   \begin{align*}
   \forall x_0\dots x_{m-1}y_1\dots y_{n-1}\Big(&\bigwedge_{i\neq j}\neg x_i\dot=y_j\to\\
   &\exists z(\bigwedge_{i<m}zRx_i)\wedge(\bigwedge_{j<n}\neg zRy_j\wedge\neg z\dot=y_j)
    \Big)
   \end{align*}
   #+END_exercise

   From [[http://www.math.uchicago.edu/~may/VIGRE/VIGRE2010/REUPapers/Fuchs.pdf][here]], some definitions of random graphs

   Let \(p\in[0,1]\) denote the probability with which a given pair is included. We assume all the
   edges have the same probability of occurrence. We denote the set of graphs constructed in this
   manner by \(\calg(n,p)\), where \(n\) is the number of elements in the vertex set.

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A graph \(G\) has property \(\calp_{i,j}\) with \(i,j=0,1,2,3,\dots\) if, for any disjoint vertex
   sets \(V_1\) and \(V_2\) with \(\abs{V_1}\le i\) and \(\abs{V_2}\le j\), there exists a vertex \(v\in G\)
   that satisfies three conditions
   1. \(v\not\in V_1\cup V_2\)
   2. \(v\leftrightarrow x\) for every \(x\in V_1\) and
   3. \(v\not\leftrightarrow y\) for every \(y\in V_2\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   An infinite graph \(G\in\calg(\aleph_0,p)\) has all the properties \(\calp_{i,j}\) with probability 1
   #+END_lemma



* Countable Models
** The omitting types theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(T\) be an \(L\)-theory and \(\Sigma(x)\) a set of \(L\)-formulas. A model
   \(\fA\) of \(T\) not realizing \(\Sigma(x)\) is said to *omit* \(\Sigma(x)\). A
   formula \(\varphi(x)\) *isolates* \(\Sigma(x)\) if
   1. \(\varphi(x)\) is consistent with \(T\)
   2. \(T\vDash\forall x(\varphi(x)\to\sigma(x))\) for all \(\sigma(x)\in\Sigma(x)\)
   #+END_definition

   A set of formulas is often called a *partial type*.

   #+ATTR_LATEX: :options [Omitting Types]
   #+BEGIN_theorem
   label:thm4.1.2
   If \(T\) is countable and consistent and if \(\Sigma(x)\) is not isolated in
   \(T\), then \(T\) has a model which omits \(\Sigma(x)\)
   #+END_theorem

   If \(\Sigma(x)\) is isolated by \(\varphi(x)\) and \(\fA\) is a model of \(T\), then
   \(\Sigma(x)\) is realised in \(\fA\) by all realisations \(\varphi(x)\). Therefore the
   converse of the theorem is true for *complete* theories \(T\): if \(\Sigma(x)\) is
   isolated in \(T\), then it is realised in every model of \(T\) 
   
   #+BEGIN_proof
   We choose a countable set \(C\) of new constants and extend \(T\) to a theory
   \(T^*\) with the following properties
   1. \(T^*\) is a Henkin theory: for all \(L(C)\)-formulas \(\psi(x)\) there
      exists a constant \(c\in C\) with \(\exists x\psi(x)\to\psi(c)\in T^*\)
   2. for all \(c\in C\) there is a \(\sigma(x)\in\Sigma(x)\) with \(\neg\sigma(c)\in T^*\)


   We construct \(T^*\) inductively as the union of an ascending chain
   \begin{equation*}
   T=T_0\subseteq T_1\subseteq T_1\subseteq\dots
   \end{equation*}
   of consistent extensions of \(T\) by finitely many axioms from \(L(C)\), in
   each step making an instance of (1) or (2) true.

   Enumerate \(C=\{c_i\mid i<\omega\}\) and let \(\{\psi_i(x)\mid i<\omega\}\)
   be an enumeration of the \(L(C)\)-formulas

   Assume that \(T_{2i}\) is the already constructed. Choose some \(c\in C\)
   which doesn't occur in \(T_{2i}\cup\{\psi_i(x)\}\) and set
   \(T_{2i+1}=T_{2i}\cup\{\exists x\psi_i(x)\to\psi_i(c)\}\).

   Up to equivalence \(T_{2i+1}\) has the form \(T\cup\{\delta(c_i,\bbar{c})\}\) for
   an \(L\)-formula \(\delta(x,\bbar{y})\) and a tuple \(\bbar{c}\in C\) which
   doesn't contain \(c_i\). Since \(\exists\bbar{y}\delta(x,\bbar{y})\) doesn't
   isolate \(\Sigma(x)\), for some \(\sigma\in\Sigma\) the formula
   \(\exists\bbar{y}\delta(x,\bbar{y})\wedge\neg\sigma(x)\) is consistent with \(T\).
   Thus \(T_{2i+2}=T_{2i+1}\cup\{\neg\sigma(c_i)\}\) is consistent

   Take a model \((\fA',a_c)_{c\in C}\) of \(T^*\). Since \(T^*\) is a Henkin
   theory, Tarski's Test ref:thm2.1.2 shows that \(A=\{a_c\mid c\in C\}\) is the
   universe of an elementary substructure \(\fA\) (Lemma ref:lemma2.2.3). By
   property (2), \(\Sigma(x)\) is omitted in \(\fA\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor4.1.3
   label:ex4.1.1
   Let \(T\) be countable and consistent and let
   \begin{equation*}
   \Sigma_0(x_0,\dots,x_{n_0}),\Sigma_1(x_1,\dots,x_{n_1}),\dots
   \end{equation*}
   be a sequence of partial types. If all \(\Sigma_i\) are not isolated, then
   \(T\) has a model which omits all \(\Sigma_i\)
   #+END_corollary

   #+BEGIN_proof
   
   If \(\Sigma_0(x),\Sigma_1(x),\dots\). Then
   \(T_{2i+2}=T_{2i+1}\cup\{\neg\sigma_m(c_{mn})\}\)

   If \(\Sigma(x_1,\dots,x_n)\), then
   \(T_{2i+1}=T_{2i}\cup\{\exists\bbar{x}\psi_i(\bbar{x})\to\psi_i(\bbar{c})\}\).

   Combine the two case
   #+END_proof
** The space of types
   Fix a theory \(T\). An *\(n\)-type* is a maximal set of formulas
   \(p(x_1,\dots,x_n)\) consistent with \(T\). We denote by \(S_n(T)\) the set
   of all \(n\)-types of \(T\). We also write \(S(T)\) for \(S_1(T)\).
   \(S_0(T)\) is all complete extensions of \(T\)

   If \(B\) is a subset of an \(L\)-structure \(\fA\), we recover
   \(S_n^{\fA}(B)\) as \(S_n(\Th(\fA_B))\). In particular, if \(T\) is complete
   and \(\fA\) is any model of \(T\), we have \(S^{\fA}(\emptyset)=S(T)\)

   For any \(L\)-formula \(\varphi(x_1,\dots,x_n)\), let \([\varphi]\) denote the set of all
   types containing \varphi.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. \([\varphi]=[\psi]\) iff \varphi and \psi are equivalent modulo \(T\)
   2. The sets \([\varphi]\) are closed under Boolean operations. In fact
      \([\varphi]\cap[\psi]=[\varphi\wedge\psi]\), \([\varphi]\cup[\psi]=[\varphi\vee\psi]\),
      \(S_n(T)\setminus[\varphi]=[\neg\varphi]\), \(S_n(T)=[\top]\) and \(\emptyset=[\bot]\)
   #+END_lemma

   It follows that the collection of sets of the form \([\varphi]\) is closed under
   finite intersection and includes \(S_n(T)\). So these sets form a basis of a
   topology on \(S_n(T)\)

   In this book, compact means finite cover and Hausdorff
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   The space \(S_n(T)\) is 0-dimensional and compact
   #+END_lemma

   #+BEGIN_proof
   Being 0-dimensional means having a basis of clopen sets. Our basic open sets
   are clopen since their complements are also basic open

   If \(p\) and \(q\) are two different types, there is a formula \varphi contained in
   \(p\) but not in \(q\). It follows that \([\varphi]\) and \([\neg\varphi]\) are
   open sets which separate \(p\) and \(q\). This shows that \(S_n(T)\) is
   Hausdorff

   To prove compactness, we need to show that any collection of closed subsets
   of \(X\) with the finite intersection property has nonempty intersection.
   Could check  [[http://www.msc.uky.edu/droyster/courses/fall99/math4181/classnotes/notes5.pdf][this]]

   Consider a family \([\varphi_i]\) (\(i\in I\)), with the finite intersection property.This
   means that \(\varphi_{i_i}\wedge\dots\wedge\varphi_{i_k}\) are consistent
   with \(T\). So Corollary ref:cor2.2.5 \(\{\varphi_i\mid i\in I\}\) is
   consistent with \(T\) and can be extended to a type \(p\), which then belongs
   to all \([\varphi_i]\).  
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   All clopen subsets of \(S_n(T)\) has the form \([\varphi]\)
   #+END_lemma

   #+BEGIN_proof
   Closed subset of a compact space is compact. It follows from Exercise ref:ex3.1.1 that we can
   separate any two disjoint
   closed subsets of \(S_n(T)\) by a basic open set.
   #+END_proof

   The Stone duality theorem asserts that the map
   \begin{equation*}
   X\mapsto\{C\mid C\text{ clopen subset of }X\}
   \end{equation*}
   yields an equivalence between the category of 0-dimensional compact spaces
   and the category of Boolean algebras. The inverse map assigns to every
   Boolean algebra to its *Stone space*

   #+ATTR_LATEX: :options []
   #+BEGIN_definition

   A map \(f\) from a subset of a structure \(\fA\) to a structure \(\fB\) is
   *elementary* if it preserves the truth of formulas; i.e., \(f:A_0\to B\) is
   elementary if for every formula \(\varphi(x_1,\dots,x_n)\) and \(\bbar{a}\in A_0\)
   we have
   \begin{equation*}
   \fA\vDash\varphi(\bbar{a})\Rightarrow\fB\vDash\varphi(f(\bbar{a}))
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma4.2.5
   Let \(\fA\) and \(\fB\) be \(L\)-structures, \(A_0\) and \(B_0\) subsets of
   \(A\) and \(B\), respectively. Any elementary map \(A_0\to B_0\) induces a
   continuous surjective map \(S_n(B_0)\to S_n(A_0)\)
   #+END_lemma

   #+BEGIN_proof
   If \(q(\bbar{x})\in S_n(B_0)\), we define
   \begin{equation*}
   S(f)(q)=\{\varphi(x_1,\dots,x_n,\bbar{a})\mid\bbar{a}\in A_0,\varphi(x_1,\dots,x_n,f(\bbar{a}))\in q(\bbar{x})\}
   \end{equation*}
   If \(\varphi(\bbar{x},f(\bbar{a}))\not\in q(\bbar{x})\), then
   \(\fB\not\vDash\varphi(\bbar{x},\bbar{a})\). Therefore \(\fA\not\vDash\varphi(\bbar{x},\bbar{a})\).
   \(S(f)\) defines a map from \(S_n(B_0)\) to \(S_n(A_0)\). Moreover, it is surjective since
   \(\{\varphi(x_1,\dots,x_n,f(\bbar{a}))\mid\varphi(x_1,\dots,x_n,a)\in p\}\) is finitely satisfiable for all \(p\in S_n(A_0)\).
   And \(S(f)\) is continuous since \([\varphi(x_1,\dots,x_n,f(\bbar{a}))]\) is the preimage of
   \([\varphi(x_1,\dots,x_n,\bbar{a})]\) under \(S(f)\)
   #+END_proof

   There are two main cases
   1. An elementary bijection \(f:A_0\to B_0\) defines a homeomorphism
      \(S_n(A_0)\to S_n(B_0)\). We write \(f(p)\) for the image of \(p\)
   2. If \(\fA=\fB\) and \(A_0\subseteq B_0\), the inclusion map induces the
      *restriction* \(S_n(B_0)\to S_n(A_0)\). We write \(q\restriction A_0\) for
      the restriction of \(q\) to \(A_0\). We call \(q\) an extension of
      \(q\restriction A_0)\)



    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma4.2.6
      A type \(p\) is isolated in \(T\) iff \(p\) is an isolated point in
      \(S_n(T)\). In fact, \varphi isolates \(p\) iff \([\varphi]=\{p\}\). That is, \([\varphi]\)
      is an *atom* in the Boolean algebra of clopen subsets of \(S_n(T)\)
    #+END_lemma

    #+BEGIN_proof
    \(p\) being an isolated point means that \(\{p\}\) is open, that is, \(\{p\}=[\varphi]\).

    The set \([\varphi]\) is a singleton iff \([\varphi]\) is non-empty and cannot be
      divided into two non-empty clopen subsets \([\varphi\wedge\psi]\) and
      \([\varphi\wedge\neg\psi]\). This means that for all \psi either \psi or
      \(\neg\psi\) follows from \varphi modulo \(T\). So \([\varphi]\) is a singleton iff \varphi
      generates the type
      \begin{equation*}
      \la\varphi\ra=\{\psi(\bbar{x})\mid T\vDash\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))\}
      \end{equation*}
      which is the only element of \([\varphi]\)

      This shows that \([\varphi]=\{p\}\) implies that \varphi isolates \(p\).

      Conversely, \varphi isolates \(p\), this means that \(\la\varphi\ra\) is consistent with \(T\) and
      contains \(p\). Since \(p\) is a type, we have \(p=\la\varphi\ra\)
    #+END_proof

      We call a formula \(\varphi(x)\) *complete* if
      \begin{equation*}
      \{\psi(\bbar{x})\mid T\vDash\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))\}
      \end{equation*}
      is a type.
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor4.2.7
   A formula isolates a type iff it is complete
   #+END_corollary

   #+BEGIN_exercise
   label:ex4.2.2
   1. Closed subsets of \(S_n(T)\) have the form
      \(\{p\in S_n(T)\mid\Sigma\subseteq p\}\), where \Sigma is any set of formulas 
   2. Let \(T\) be countable and consistent. Then any meagre[fn:1] subset \(X\)
      of \(S_n(T)\) can be omitted, i.e., there is a model which omits all
      \(p\in X\)
   #+END_exercise

   #+BEGIN_proof
   1. The sets \([\varphi]\) are a basis for the closed subsets of \(S_n(T)\). So the
      closed sets of \(S_n(T)\) are exactly the intersections
      \(\bigcap_{\varphi\in\Sigma}[\varphi]=\{p\in S_n(T)\mid\Sigma\subseteq p\}\)
   2. The set \(X\) is the union of a sequence of countable nowhere dense sets
      \(X_i\). We may assume that \(X_i\) are closed, i.e., of the form
      \(\{p\in S_n(T)\mid \Sigma_i\subseteq p\}\). That \(X_i\) has no interior means
      that \(\Sigma_i\) is not isolated. The claim follows now from Corollary ref:cor4.1.3
   #+END_proof

   #+BEGIN_exercise
   label:ex4.2.3
   Consider the space \(S_\omega(T)\) of all complete types in variables
   \(v_0,v_1,\dots\). Note that \(S_\omega(T)\) is again a compact space and
   therefore not meagre by Baire's theorem
   1. Show that
      \(\{\tp(a_0,a_1,\dots)\mid\text{ the $a_i$ enumerate a model of }T\}\)
       is comeagre in \(S_\omega(T)\)
   
   #+END_exercise

   #+BEGIN_exercise
   label:ex4.2.5
   Let \(B\) be a subset of \(\fA\). Show that the *restriction* (restriction of variables)
   map \(S_{m+n}(B)\to S_n(B)\) is open, continuous and surjective. Let \(a\) be an \(n\)-tuple
   in \(A\). Show that the fibre over \(\tp(a/B)\) is canonically homeomorphic to \(S_m(aB)\).

   Consider the restriction map \(\pi:S_{m+1}(B)\to S_1(B)\). Then \(\pi^{-1}(\tp(a/B))\cong S_m(aB)\)
   #+END_exercise

   #+BEGIN_proof
   We define the restriction map \(f:S_{m+n}(B)\to S_n(B)\) as: for \(q(\barx,\bary)\in S_{m+n}(B)\), we
   let \(f(q(\barx,\bary))=\{\varphi(\bary):\varphi(\bary)\in q(\barx,\bary)\}\), where \(\barx\) and \(\bary\) are
   of size \(m\) and \(n\) respectively.

   continuous is easy

   Now given an open set \([\phi(\barv,\barw)]\subseteq S_{m+n}(B)\). We need to
   prove \(f([\phi(\barv,\barw)])=[\exists\barv\phi(\barv,\barw)]\) which is clear

   Now the problem is, for \(\tp(a/B)\subset q(\bary,x,\barb)\in \pi^{-1}(\tp(a/B))\), is it realized
   by \(\barc a\) in some \(\fA\prec \fB\)?

   So what will happen if \(\tp(a/B)=\tp(c/B)\) for some \(c\in A\).

   For any \(\fM\vDash q(\barc,d,\barb)\), for any \(\phi(\bary,x,\barb)\in q(\bary,x,\barb)\),
   \(\fM\vDash\exists\bary\;\phi(\bary,d,\barb)\) and \(\fM\vDash\exists\bary\;\phi(\bary,d,\barb)\leftrightarrow\exists\bary\;\phi(\bary,a,\barb)\). Hence
   we have \(\fM\vDash q(\barc',a,\barb)\) for some \(\barc'\).

   Hence for any \(q(\bary,x,\barb)\in\pi^{-1}(\tp(a/B))\), we can assume \(\fM\vDash(\barc,a,\barb)\).
   Hence \(a\) is fixed as \(\barb\). Thus, in fact, we are talking about some types in \(S_m(aB)\).
   #+END_proof

   #+BEGIN_exercise
   label:ex4.2.6
   A theory \(T\) has quantifier elimination iff every type is implied by its quantifier-free part
   #+END_exercise

   #+BEGIN_exercise
   label:ex4.2.7
   Consider the structure \(\fM=(\Q,<)\). Determine all types in \(S_1(\Q)\). Which of these types are
   realised in \(\R\)? Which extensions does a type over \(\Q\) have to a type over \(\R\)?
   #+END_exercise

   #+BEGIN_proof

   #+END_proof


** \(ℵ_0\)-categorical theories
   #+ATTR_LATEX: :options [Ryll-Nardzewski]
   #+BEGIN_theorem
   label:thm4.3.1
   Let \(T\) be a countable complete theory. Then \(T\) is
   \(\aleph_0\)-categorical iff for every \(n\) there are only finitely many
   formulas \(\varphi(x_1,\dots,x_n)\) up to equivalence relative to \(T\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(L\)-structure \(\fA\) is *\(\omega\)-saturated* if all types over finite
   subsets of \(A\) are realised in \(\fA\)
   #+END_definition

   The types in the definition are meant to be 1-types. On the other hand, it is
   not hard to see that an \(\omega\)-saturated structure realises all
   \(n\)-types over finite sets (Exercise ref:ex4.3.9) for all \(n\ge1\). The
   following lemma is a generalisation of the \(\aleph_0\)-categoricity of \(\DLO\).

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma4.3.3
   Two elementarily equivalent, countable and \(\omega\)-saturated structures
   are isomorphic
   #+END_lemma

   #+BEGIN_proof
   Suppose \(\fA\) and \(\fB\) are as in the lemma. We choose enumerations
   \(A=\{a_0,a_1,\dots\}\) and \(B=\{b_0,b_1,\dots\}\). Then we construct an
   ascending sequence \(f_0\subseteq f_1\subseteq \cdots\) of finite elementary
   maps
   \begin{equation*}
   f_i:A_i\to B_i
   \end{equation*}
   between finite subsets of \(\fA\) and \(\fB\). We will choose the \(f_i\) in
   such a way that \(A\) is the union of the \(A_i\) and \(B\) the union of the
   \(B_i\). The union of the \(f_i\) is then the desired isomorphism between
   \(\fA\) and \(\fB\)

   The empty map \(f_0=\emptyset\) is elementary since \(\fA\) and \(\fB\) are
   elementarily equivalent. Assume that \(f_i\) is already constructed. There
   are two cases:

   \(i=2n\); We will extend \(f_i\) to \(A_{i+1}=A_i\cup\{a_n\}\). Consider the
   type
   \begin{equation*}
   p(x)=\tp(a_n/A_i)=\{\varphi(x)\mid\fA\vDash\varphi(a_n), \varphi(x)\text{ a $L(A_i)$-formula}\}
   \end{equation*}
   Since \(f_i\) is elemantarily, \(f_i(p)(x)\) is in \(\fB\) a type over
   \(B_i\). (note that \(f_i\) is elementary iff \(\fA_{A_i}\equiv\fB_{B_i}\))
   Since \(\fB\) is \(\omega\)-saturated, there is a realisation \(b'\)
   of this type. So for \(\bbar{a}\in A_i\)
   \begin{equation*}
   \fA\vDash\varphi(a_n,\bbar{a}) \Rightarrow\fB\vDash\varphi(b',f_i(\bbar{a}))
   \end{equation*}
   Given \(b'\), then the type that it realises is fixed. Hence
   \begin{equation*}
   \fB\vDash\varphi(b',f_i(\bara))\Rightarrow\fA\vDash\varphi(a_n,\bara)
   \end{equation*}
   This shows that \(f_{i+1}(a_n)=b'\) defines an elementary extension of
   \(f_i\)

   \(i=2n+1\); we exchange \(\fA\) and \(\fB\)
   #+END_proof

   #+ATTR_LATEX: :options [Proof of Theorem \ref{thm4.3.1}]
   #+BEGIN_proof
   Assume that there are only finitely many \(\varphi(x_1,\dots,x_n)\) relative to
   \(T\) for every \(n\). By Lemma ref:lemma4.3.3 it suffices to show that all
   models of \(T\) are \(\omega\)-saturated. Let \(\fM\) be a model of \(T\) and
   \(A\) an \(n\)-element subset. If there are only \(N\) many formulas, up to
   equivalence, in the variable \(x_1,\dots,x_{n+1}\), there are, up to
   equivalence in \(\fM\), at most \(N\) many \(L(A)\)-formulas \(\varphi(x)\). Thus,
   each type \(\varphi(x)\in S(A)\) is isolated (w.r.t. \(\Th(\fM_A)\)) by a smallest formula \(\varphi_p(x)\)
   (\(\bigwedge p(x)\)). Each element of \(M\) which realises
   \(\varphi_p(x)\) also realises \(p(x)\), so \(\fM\) is \(\omega\)-saturated.

   Conversely, if there are infinitely many \(\varphi(x_1,\dots,x_n)\) modulo \(T\)
   for some \(n\), then - as the type space \(S_n(T)\) is compact - there must
   be some non-isolated type \(p\) (if \(p\) is isolated, then \(\{p\}\) is open). Then by Lemma
   ref:lemma4.2.6 \(p\) is not isolated in \(T\).
   By the Omitting Types Theorem there is a
   countable model of \(T\) in which this type is not realised. On the other
   hand, there also exists a countable model of \(T\) realizing this type. So
   \(T\) is not \(\aleph_0\)-categorical
   #+END_proof

   The proof shows that a countable complete theory with infinite models is
   \(\aleph_0\)-categorical iff all countable models are \(\omega\)-saturated

   given a variables \(\varphi_i(a_i)\) where \(a_i\in A\), we can consider \(\bigwedge\exists x_i\varphi_i(x_i)\).

   [[index:$\omega$-homogeneous]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(L\)-structure \(\fM\) is *\(\omega\)-homogeneous* if for every elementary
   map \(f_0\) defined on a finite subset \(A\) of \(M\)  and for any \(a\in M\)
   there is some element \(b\in M\) s.t.
   \begin{equation*}
   f=f_0\cup\{\la a,b\ra\}
   \end{equation*}
   is elementary
   #+END_definition

   \(f=f_0\cup\{\la a,b\ra\}\) is elementary iff \(b\) realises
   \(f_0(\tp(a/A))\)

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(\fA\) be a structure and \(a_1,\dots,a_n\) elements of \(\fA\). Then
   \(\Th(\fA)\) is \(\aleph_0\)-categorical iff \(\Th(\fA,a_1,\dots,a_n)\) is \(\aleph_0\)-categorical
   #+END_corollary

   #+BEGIN_proof
   If \(\Th(\fA)\) is \(\aleph_0\)-categorical, then for any \(m+n\) there is only finitely many
   formulas \(\varphi(x_1,\dots,x_{m+n})\) up to equivalence relative to \(\Th(\fA)\), hence there is only finitely
   many \(\varphi(x_1,\dots,x_m,a_1,\dots,a_n)\) up to equivalence relative to \(\Th(\fA,a_1,\dots,a_n)\)

   For the converse, \(\Th(\fA)\subset\Th(\fA,a_1,\dots,a_n)\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The following theories and \(\aleph_0\)-categorical
   1. \(\Infset\) (saturated)
   2. For every finite field \(\F_q\), the theory of infinite \(\F_q\)-vector
      spaces. (Vector spaces over the same field and of the same dimension are
      isomorphic)
   3. The theory \(\DLO\) of dense linear orders without endpoints. This follows
      from Theorem ref:thm4.3.1 since \(\DLO\) has quantifier elimination: for
      every \(n\) there are only finitely many (say \(N_n\)) ways to order \(n\)
      elements. Each of these possibility corresponds to a complete formula
      \(\psi(x_1,\dots,x_n)\). Hence there are up to equivalence, exactly
      \(2^{N_n}\) many formulas \(\varphi(x_1,\dots,x_n)\)
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A theory \(T\) is *small* if \(S_n(T)\) are at most countable for all \(n<\omega\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   A countable complete theory is small iff it has a countable
   \(\omega\)-saturated model
   #+END_lemma

   #+BEGIN_proof
   If \(T\) has a finite model \(\fA\), \(T\) is small and \(\fA\) is
   \(\omega\)-saturated: since \(T\) is complete, for any type \(p(x)\in S_n(T)\), \(T\vDash p(x)\). For finite
   model \(\fA\), there are only finitely many assignments. If we have two distinct
   types \(p(x),q(x)\in S_n(T)\), then there is \(\phi(x)\in p(x)\) and \(\phi(x)\not\in q(x)\). Since they are
   maximally consistent, \(q(x)\vDash\neg\phi(x)\) hence \(p(x)\) and \(q(x)\) cannot be realised by the same
   element. So we may assume that \(T\) has infinite
   models

   If all types can be realised in a single countable model, there can be at most countably many
   types.

   if conversely all \(S_{n+1}(T)\) are at most countable, then over any \(n\)-element subset of a
   model of \(T\) there are at most countably many types. We construct an elementary chain
   \begin{equation*}
   \fA_0\prec\fA_1\prec\dots
   \end{equation*}
   of models of \(T\). For \(\fA_0\) we take any countable model. if \(\fA_i\) is already constructed, we
   use Corollary ref:cor2.2.9 and Theorem ref:thm2.3.1 to construct a countable model \(\fA_{i+1}\) in
   such a way that all types over finite subsets of \(A_i\) are realised in \(\fA_{i+1}\). This can be
   done since there are only countable many such types. The union \(\fA=\bigcup_{i\in\omega}\fA_i\) is countable
   and \(\omega\)-saturated since every type over a finite subset \(B\) of \(\fA\) is realised
   in \(\fA_{i+1}\) if \(B\subseteq A_i\)
   #+END_proof

   #+ATTR_LATEX: :options [Vaught]
   #+BEGIN_theorem
   A countable complete theory cannot have exactly two countably models
   #+END_theorem

   #+BEGIN_proof
   We can assume that \(T\) is small and not \(\aleph_0\)-categorical (if \(T\) is not small, then it has
   no countable model). We will show that \(T\) has at
   least three non-isomorphic countable models. First, \(T\) has an \(\omega\)-saturated countable
   model \(\fA\) and there is a non-isolated type \(p(\barx)\) which can be omitted in a countable
   model \(\fB\). Let \(p(\barx)\) be realised in \(\fA\) by \(\bara\). Since \(\Th(\fA,\bara)\) is
   not \(\aleph_0\)-categorical as \(T\subset\Th(\fA,\bara)\), \(\Th(\fA,\bara)\) has a countable model \((\fC,\barc)\) which is not
   \omega-saturated. Then \(\fC\) is not \omega-saturated and therefore not isomorphic to \(\fA\). But \(\fC\)
   realises \(p(\barx)\) and is therefore not isomorphic to \(\fB\)
   #+END_proof

   #+BEGIN_exercise
   label:ex4.3.3
   Show that \(T\) is \(\aleph_0\)-categorical iff \(S_n(T)\) is finite for all \(n\)
   #+END_exercise

   #+BEGIN_exercise
   label:ex4.3.5
   Show that for every \(n>2\) there is a countable complete theory with exactly \(n\) countable models
   #+END_exercise

   #+BEGIN_proof
   [[https://math.stackexchange.com/questions/213721/a-theory-with-exactly-n-countable-models-for-each-n1/581921][StackExchange]]
   #+END_proof

   #+BEGIN_exercise
    label:ex4.3.9
    If \(\fA\) is \omega-saturated, all \(n\)-types over finite sets are realised.
   #+END_exercise

   #+BEGIN_proof
   Assume that \(\fA\) is \kappa-saturated, \(B\) a subset of \(A\) of smaller cardinality than \kappa
   and \(p(x,\bary)\) a \((n+1)\)-type over \(B\). Let \(\barb\in A\) be a realisation
   of \(q(\bary)=p\restriction\bary\) and \(a\in A\) a realisation of \(p(x,\barb)\).
   Then \((a,\barb)\) realises \(p\).
   #+END_proof


** The amalgamation method
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any language \(L\), the *skeleton* \(\calk\) of an \(L\)-structure \(\fM\) is the class of all
    finitely-generated \(L\)-structures which are isomorphic to a substructure of \(\fM\). We say that
    an \(L\)-structure \(\fM\) is *\(\calk\)-saturated* if its skeleton is \(\calk\) and if for
    all \(\fA\), \(\fB\) in \(\calk\) and all embeddings \(f_0:\fA\to\fM\) and \(f_1:\fA\to\fB\) there is an
    embedding \(g_1:\fB\to\fM\) with \(f_0=g_1\circ f_1\)

    \begin{center}\begin{tikzcd}[sep column=tiny]
    \fA\ar[rr,"f_0"]\ar[rd,"f_1"']&&\fM\\
    &\fB\ar[ur,"g"']
    \end{tikzcd}\end{center}

    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm4.4.2
    Let \(L\) be a countable language. Any two countable \(\calk\)-saturated structures are isomorphic
    #+END_theorem

    #+BEGIN_proof
    Let \(\fM\) and \(\fN\) be countable \(L\)-structures with the same skeleton \(\calk\), and assume
    that \(\fM\) and \(\fN\) are \(\calk\)-saturated. As in the proof of Lemma ref:lemma4.3.3 we construct
    an isomorphisms between \(\fM\) and \(\fN\) as the union of an ascending sequence of isomorphisms
    between finitely-generated substructures of \(M\) and \(N\).

    If \(f_1:\fA\to\fN\) is an embedding of a finitely-generated substructure of \(\fA\) of \(\fM\) into \(\fN\),
    and \(a\) is an element of \(\fM\), then by \(\calk\)-saturation \(f_1\) can be extended to an
    embedding \(g_1:\fA'\to\fN\) where \(\fA'=\la Aa\ra^{\fM}\). Now interchange the roles of \(\fM\) and \(\fN\).
    #+END_proof

    The proof shows that any countable \(\calk\)-saturated structure \(\fM\) is *ultrahomogeneous* i.e., any
    isomorphism between finitely generated substructure extends to an automorphism of \(\fM\).

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(L\) be a countable language and \(\calk\) a countable class of
    finitely-generated \(L\)-structures. There is a countable \(\calk\)-saturated \(L\)-structure \(\fM\)
    iff
    1. (Heredity) if \(\fA_0\in\calk\), then all elements of the skeleton of \(\fA_0\) also belongs to \(\calk\)
    2. (Joint Embedding) for \(\fB_0,\fB_1\in\calk\) there are some \(\cald\in\calk\) and embeddings \(g_i:\fB_i\to\fD\)
    3. (Amalgamation) if \(\fA,\fB_0,\fB_1\in\calk\) and \(f_i:\fA\to\fB_i\), (\(i=0,1\)) are embeddings, there is
       some \(\cald\in\calk\) and two embeddings \(g_i:\fB_i\to\fD\) s.t. \(g_0\circ f_0=g_1\circ f_1\)

       \begin{center}\begin{tikzcd}
       &\fD\\
       \fB_0\ar[ur,"g_0"]&&\fB_1\ar[ul,"g_1"']\\
       &\fA\ar[ul,"f_0"]\ar[ur,"f_1"']
       \end{tikzcd}\end{center}
       in this case, \(\fM\) is unique up to isomorphism and is called the Fraïssé limit of \(\calk\)
    #+END_theorem

    #+BEGIN_proof
    Let \(\calk\) be the skeleton of a countably \(\calk\)-saturated structure \(\fM\). Clearly, \(\calk\) has the
    hereditary property (substructure of a substructure is still a substructure).  To see that \(\calk\)
    has the Amalgamation Property, let \(\fA,\fB_0,\fB_1,f_0\) and \(f_1\) be as in 3. We may assume
    that \(\fB_0\subseteq\fM\) and \(f_0\) is the inclusion map. Furthermore we can assume \(\fA\subseteq\fB_1\) and
    that \(f_1\) is the inclusion map. Now the embedding \(g_1:\fB_1\to\fM\) is the extension of the
    isomorphism \(f_0:\fA\to f_0(\fA)\) to \(\fB_1\) and satisfies \(f_0=g_1\circ f_1\). For \(\fD\) we choose a
    finitely-generated substructure of \(\fM\) which contains \(\fB_0\) and the image of \(g_1\).
    For \(g_0:\fB_0\to\fD\) take the inclusion map. For Joint Embedding Property take \(\la B_0B_1\ra^{\fM}\)

    For the converse assume that \(\calk\) has properties 1, 2 and 3. Choose an
    enumeration \((\fB_i)_{i\in\omega}\) of all isomorphism types in \(\calk\) (they are not isomorphic). We
    construct \(\fM\) as the union of
    an ascending chain
    \begin{equation*}
    \fM_0\subseteq\fM_1\subseteq\dots\subseteq\fM
    \end{equation*}
    of elements of \(\calk\). Suppose that \(\fM_i\) is already constructed. If \(i=2n\), we
    choose \(\fM_{i+1}\) as the top of a diagram
    \begin{center}\begin{tikzcd}
    &\fM_{i+1}\\
    \fM_i\ar[ur,"g_0"]&&\fB_n\ar[lu,"g_1"']
    \end{tikzcd}\end{center}
    where we can assume that \(g_0\) is the inclusion map. if \(i=2n+1\), let \(\fA\) and \(\fB\)
    from \(\calk\) and two embeddings \(f_0:\fA\to\fM_i\) and \(f_1:\fA\to\fB\) be given.
    \begin{center}\begin{tikzcd}
    &\fM_{i+1}\\
    \fM_i\ar[ur,"g_0"]&&\fB\ar[ul,"g_1"']\\
    &\fA\ar[ul,"f_0"]\ar[ru,"f_1"']
    \end{tikzcd}\end{center}
    To ensure that \(\fM\) is \(\calk\)-saturated we have in the odd steps to make the right choice
    of \(\fA,\fB,f_0\) and \(f_1\). Assume that we have \(\fA,\fB\in\calk\) and embeddings \(f_0:\fA\to\fM\)
    and \(f_1:\fA\to\fB\). For large \(j\) the image of \(f_0\) will be contained in \(\fM_j\). During the
    construction of the \(\fM_i\), in order to guarantee the \(\calk\)-saturation of \(\fM\), we have to
    ensure that eventually, for some odd \(i\ge j\), the embeddings \(f_0:\fA\to\fM_i\) and \(f_1:\fA\to\fB\) were
    used in the construction of \(\fM_{i+1}\). This can be done since for each \(j\) there are - up to
    isomorphism - at most countably many possibilities. Thus there exists an
    embedding \(g_1:\fB\to\fM_{i+1}\) with \(f_0=g_1\circ f_1\).

    \(\calk\) is the skeleton of \(\fM\): the finitely-generated substructure are the substructures of
    the \(\fM_1\). Since \(\fM_i\in\calk\), their finitely-generated substructure also belong to \(\calk\). On the
    other hand each \(B_n\) is isomorphic to a substructure of \(\fM_{2n+1}\)

    Uniqueness follows from Theorem ref:thm4.4.2
    #+END_proof

    For finite relational languages \(L\), any non-empty finite subset is itself a
    (finitely-generated) substructure. For such languages, the construction
    yields \(\aleph_0\)-categorical structures.  We now take a look at \(\aleph_0\)-categorical theories with
    quantifier elimination in a *finite relational language*

    #+BEGIN_remark
    A complete theory \(T\) in a finite relational language with quantifier elimination
    is \(\aleph_0\)-categorical. So all its models are \omega-homogeneous
    #+END_remark

    #+BEGIN_proof
    For every \(n\) there is only a finite number of non-equivalent quantifier free
    formulas \(\rho(x_1,\dots,x_n)\). If \(T\) has quantifier elimination, this number is also the number of
    all formulas \(\varphi(x_1,\dots,x_n)\) modulo \(T\) and so \(T\) is \(\aleph_0\)-categorical by Theorem ref:thm4.3.1
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(T\) be a complete theory in a finite relational language and \(\fM\) an infinite model
    of \(T\). TFAE
    1. \(T\) has quantifier elimination
    2. Any isomorphism between finite substructures is elementary
    3. the domain of any isomorphism between finite substructures can be extended to any further element
    #+END_lemma

    #+BEGIN_proof
    \(2\to 1\). if any isomorphism between finite substructure of \(\fM\) is elementary,
    all \(n\)-tuples \(\bara\) which satisfy in \(\fM\) the same quantifier-free type
    \begin{equation*}
    \tp_{\qf}(\bara)=\{\rho(\barx)\mid\fM\vDash\rho(\bara),\rho(\barx)\text{ quantifier-free}\}
    \end{equation*}
    satisfy the same simple existential formulas. We will show from this that every simple
    existential formula \(\varphi(x_1,\dots,x_n)=\exists y\rho(x_1,\dots,x_n,y)\) is, modulo \(T\), equivalent to a
    quantifier-free formula. Let \(r_1(\barx),\dots,r_{k-1}(\barx)\) be the quantifier-free types of
    all \(n\)-tuples in \(\fM\) which satisfy \(\varphi(\barx)\). Let \(\rho_i(\barx)\) be equivalent to the
    conjunction of all formulas from \(r_i(\barx)\). Then
    \begin{equation*}
    T\vDash\forall \barx(\varphi(\barx)\leftrightarrow\bigvee_{i<k}\rho_i(\barx))
    \end{equation*}


    \(1\to 3\) the theory \(T\) is \(\aleph_0\)-categorical and hence all models are \omega-homogeneous. Since
    any isomorphism between finite substructures is elementary, 3 follows.

    \(3\to 2\). If the domain of any finite isomorphism can be extended to any further element, it is
    easy to see that every finite isomorphism is elementary. Here we can only consider \(\exists x\varphi(x)\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(L\) be a finite relational language and \(\calk\) a class of finite \(L\)-structures. If the
    Fraïssé limit of \(\calk\) exists, its theory is \(\aleph_0\)-categorical and has quantifier elimination
    #+END_theorem

** Prime Models
    Let \(T\) be a countable complete theory with infinite models
    [[index: prime model]]
    [[index:atomic model]]
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(T\) be a countable theory with infinite models, not necessarily complete
    1. We call \(\fA_0\) a *prime model* of \(T\) if \(\fA_0\) can be elementarily embedded into all
       models of \(T\)
    2. A structure \(\fA\) is called *atomic* if all \(n\)-tuples \(\bara\) of elements of \(\fA\) are
       atomic. This means that the types \(\tp(\bara)\) are isolated in \(S_n^{\fA}(\emptyset)=S_n(T)\)
    #+END_definition

    Prime models need not exists. By Corollary ref:cor4.2.7, a tuple \(\bara\) is atomic iff it
    satisfies a complete formula.

    Since \(T\) has countable models, prime models must be countable and since non-isolated types
    can be omitted in suitable models by Theorem ref:thm4.1.2, only isolated types can be realised
    in prime models. So any \(\tp(\bara)\) of a prime model must be isolated.

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    A model of \(T\) is prime iff it is countable and atomic
    #+END_theorem

    #+BEGIN_proof
    As just noted, a prime model has to be countable and atomic.

    Let \(\fM_0\) be a countable and atomic model of \(T\) and \(\fM\) any model of \(T\). We construct
    an elementary embedding of \(\fM_0\) to \(\fM\) as a union of an ascending sequence of elementary
    maps
    \begin{equation*}
    f:A\to B
    \end{equation*}
    between finite subsets \(A\) of \(M_0\) and \(B\) of \(M\). The empty map is elementary
    since \(T\) is complete and \(\fM_0\equiv\fM\)

    We show that \(f\) can be extended to any given \(A\cup\{a\}\). Let \(p(x)=\tp(a/A)\)
    and \(f(p)=f(p(x))\). We show that \(f(p)\) has a realisation \(b\in M\)

    Let \(\bara\) be a tuple which enumerates the elements of \(A\) and \(\varphi(x,\barx)\)
    an \(L\)-formula which isolates the \(\tp(a\bara/A)\) since \(\fM_0\) is atomic. Then \(p(x)\) is
    isolated by \(\varphi(x,\bara)\): clearly \(\varphi(x,\bara)\in\tp(a/\bara)\) and
    if \(\rho(x,\bara)\in\tp(a/\bara)\) we have  \(\rho(x,y)\in\tp(a,\bara)\). This implies
    that \(\fM_0\vDash\forall x,y(\varphi(x,y)\to\rho(x,y))\) and \(\fM\vDash\forall x(\varphi(x,\bara)\to\rho(x,\bara))\). Thus \(f(p)\) is
    isolated by \(\varphi(x,f(\bara))\) and since \(\varphi(x,f(\bara))\) can be realised in \(\fM\), so can be \(f(p)\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The isolated types are *dense* in \(T\) if every consistent \(L\)-formulas \(\psi(x_1,\dots,x_n)\) belongs
    to an isolated type \(p(x_1,\dots,x_n)\in S_n(T)\)
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(T\) be the language having a unary predicate \(P_s\) for every finite
    0-1-sequence \(s\in 2^{<\omega}\). The axioms of \(\Tree\) say that the \(P_s,s\in 2^{<\omega}\), form a
    binary decomposition of the universe
    * \(\forall x\;P_\emptyset(x)\)
    * \(\exists x\;P_s(x)\)
    * \(\forall x\;((P_{s0}(x)\vee P_{s1}(x))\leftrightarrow P_s(x))\)
    * \(\forall x\;\neg(P_{s0}(x)\wedge P_{s1}(x))\)


    \(\Tree\) is complete and has quantifier elimination. There are no complete formulas and no
    prime model
    #+END_examplle


    See Marker to see the full content
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A family of formulas \(\varphi_s(\barx)\), \(s\in 2^{<\omega}\) is a *binary tree* if for all \(s\in 2^{<\omega}\) the
    following holds
    1. \(T\vDash\forall \barx\;((\varphi_{s0}(\barx)\vee\varphi_{s1}(\barx))\to\varphi_s(\barx))\)
    2. \(T\vDash\forall\barx\;\neg(\varphi_{s0}(\barx)\wedge\varphi_{s1}(\barx))\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm4.5.9
    Let \(T\) be a complete theory
    1. If \(T\) is small, it has no binary tree of consistent \(L\)-formulas. If \(T\) is countable,
       the converse holds as well
    2. If \(T\) has no binary tree of consistent \(L\)-formulas, the isolated types are dense
    #+END_theorem

    #+BEGIN_proof
    1. Let \((\varphi_s(x_1,\dots,x_n))\) be a binary tree of consistent formulas. Then, for all \(\eta\in 2^\omega\),
       the set
       \begin{equation*}
       \{\varphi_s(\barx)\mid s\subseteq\eta\}
       \end{equation*}
       is consistent and therefore is contained in some type \(p_{\eta}(\barx)\in S_n(T)\).
       The \(p_\eta(\barx)\) are all different showing that \(T\) is not small.
    #+END_proof

    #+BEGIN_exercise
    Countable theories without a binary tree of consistent formulas are small
    #+END_exercise

    #+BEGIN_proof
    If countable theory \(T\) is not small.
    #+END_proof

    #+BEGIN_exercise
    label:ex4.5.2
    Show that isolated types being dense is equivalent to isolated types being (topologically) dense
    in the Stone space \(S_n(T)\).
    #+END_exercise

    #+BEGIN_proof
    Let \(S=\{\text{the isolated types in }S_n(T)\}\). \(S\) is dense in \(S_n(T)\)
    iff \(\barS=S_n(T)\). For any \(p\in S_n(T)\setminus S\), \(p\) is non-isolated. For any \(p\in[\phi]\), \phi
    belongs to an isolated type \(q\). Thus \(q\in S_n(T)\cap S\). Hence \(\barS=S_n(T)\).
    #+END_proof



* $\aleph_1$-categorical Theories

** Indiscernibles
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(I\) be a linear order and \(\fA\) an \(L\)-structure. A family \((a_i)_{i\in I}\) of elements
    of \(A\) is called a *sequence of indiscernibles*  if for all \(L\)-formulas \(\varphi(x_1,\dots,x_n)\) and
    all \(i_1<\dots<i_n\) and \(j_1<\dots<j_n\) from \(I\)
    \begin{equation*}
    \fA\vDash\varphi(a_{i_1},\dots,a_{i_n})\leftrightarrow\varphi(a_{j_1},\dots,a_{j_n})
    \end{equation*}
    #+END_definition

    if two of the \(a_i\) are equal, all \(a_i\) are the same. Therefore it is often assumed that
    the \(a_i\) are distinct

    Sometimes sequences of indiscernibles are also called *order indiscernible* to distinguish them
    from *totally indiscernible* sequences in which the ordering of the index set does not matter.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(I\) be an infinite linear order and \(\cali=(a_i)_{i\in I}\) a sequence of \(k\)-tuples
    in \(\fM\), \(A\subseteq M\). The *Ehrenfeucht-Mostowski type* \(\EM(\cali/A)\) of \(\cali\) over \(A\) is the set
    of \(L(A)\)-formulas \(\varphi(x_1,\dots,x_n)\) with \(\fM\vDash\varphi(a_{i_1},\dots,a_{i_n})\) for all \(i_1<\dots<i_n\in I\), \(n<\omega\)
    #+END_definition

    #+ATTR_LATEX: :options [The Standard Lemma]
    #+BEGIN_lemma
    label:lemma5.1.3
    Let \(I\) and \(J\) be two infinite linear orders and \(\cali=(a_i)_{i\in I}\) a sequence of elements
    of a structure \(\fM\). Then there is structure \(\fN\equiv\fM\) with an indiscernible
    sequences \((b_j)_{j\in J}\) realizing the Ehrenfeucht-Mostowski type \(\EM(\cali)\) of \(\cali\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume that \(T\) has an infinite model. Then for any linear order \(I\), \(T\) has a model with
    a sequence \((a_i)_{i\in I}\) of distinct indiscernibles
    #+END_corollary

    Let \([A]^n\) denote the set of all \(n\)-element subsets of \(A\)

    #+ATTR_LATEX: :options [Ramsey]
    #+BEGIN_theorem
    Let \(A\) be infinite and \(n\in\omega\). Partition the set of \(n\)-elements subsets \([A]^n\) into
    subsets \(C_1,\dots,C_k\). Then there is an infinite subset of \(A\) whose \(n\)-element subsets all
    belong to the same subset \(C_i\)
    #+END_theorem

    #+BEGIN_proof
    Thinking of the partition as a colouring on \([A]^n\), we are looking for an infinite
    subset \(B\) of \(A\) s.t. \([B]^n\) is monochromatic. We prove the theorem by induction
    on \(n\). For \(n=1\), the statement is evident from the pigeonhole principle since there are
    infinite elements and finite colors.

    Assuming the theorem is true for \(n\), we now prove it for \(n+1\). Let \(a_0\in A\). Then any
    colouring of \([A]^{n+1}\) induces a colouring of the \(n\)-element subsets of \(A'=A\setminus\{a_0\}\):
    just colour \(x\in[A']^n\) by the colour of \(\{a_0\}\cup x\in[A]^{n+1}\). By the induction hypothesis,
    there exists an infinite monochromatic subset \(B_1\) of \(A'\) in the induced colouring. Thus,
    all the \((n+1)\)-element subsets of \(A\) consisting of \(a_0\) and \(n\) elements of \(B_1\)
    have the same colour but \(\{a_0\}\cup B\) is not our desired set.

    Now pick any \(a_1\in B_1\). By the same argument we obtain an infinite
    subset \(B_2\subseteq B_1\) with the same properties. We thus construct an infinite
    sequence \(A=B_0\supset B_1\supset B_2\supset\dots\) and elements \(a_i\in B_i\setminus B_{i+1}\) s.t.
    the colour of each \((n+1)\)-element subset \(\{a_{i(0)},\dots,a_{i(n)}\}\) with \(i(0)<i(1)<\dots<i(n)\)
    depends only on the value of \(i(0)\).
    \begin{equation*}
    a_0,a_1,a_2,\dots,a_n,\dots
    \end{equation*}
    Again by the pigeonhole principle there are infinitely
    many values of \(i(0)\) for which this colour will be the same and we take \(\{a_{i(0)}\}\).
    These \(a_{i(0)}\) then yields
    the desired monochromatic set.
    #+END_proof

    #+ATTR_LATEX: :options [Proof of Lemma \ref{ref:lemma5.1.3}]
    #+BEGIN_proof
    Choose a set \(C\) of new constants with an ordering isomorphic to \(J\). Consider the theories
    \begin{align*}
    T'&=\{\varphi(\barc)\mid\varphi(\barx)\in\EM(\cali)\}\\
    T''&=\{\varphi(\barc)\leftrightarrow\varphi(\bard)\mid\barc,\bard\in C\}
    \end{align*}
    Here the \(\varphi(\barx)\) are \(L\)-formulas and \(\barc,\bard\) tuples in increasing order. We have
    to show that \(T\cup T'\cup T''\) is consistent. It is enough to show that
    \begin{equation*}
    T_{C_0,\Delta}=T\cup\{\varphi(\barc)\in T'\mid\barc\in C_0\}\cup\{\varphi(\barc)\leftrightarrow\varphi(\bard)\mid\varphi(\barx)\in\Delta,\barc,\bard\in C_0\}
    \end{equation*}
    is consistent for finite sets \(C_0\) and \Delta. Note that \(\Diag_{\el}(\fM)\subseteq T\).
    We can assume that the elements of \Delta are formulas
    with free variables \(x_1,\dots,x_n\) and that all tuples \(\barc\) and \(\bard\) have the same
    length

    for notational simplicity we assume that all \(a_i\) are different. So we may
    consider \(A=\{a_i\mid i\in I\}\) as an ordered set, which is the interpretation of \(C\). We define an
    equivalence relation on \([A]^n\) by
    \begin{equation*}
    \bara\sim\barb\Longleftrightarrow\fM\vDash\varphi(\bara)\leftrightarrow\varphi(\barb)\text{ for all }\varphi(x_1,\dots,x_n)\in\Delta
    \end{equation*}
    where \(\bara,\barb\) are tuples in increasing order. Since this equivalence has at
    most \(2^{\abs{\Delta}}\) many classes, by Ramsey's Theorem there is an infinite subset \(B\subseteq A\) with
    all \(n\)-element subsets in the same equivalence class. We interpret the constants \(c\in C_0\)
    by elements \(b_c\) in \(B\) ordered in the same way as the \(c\). Then \((\fM,b_c)_{c\in C_0}\) is
    a model of \(T_{C_0,\Delta}\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma5.1.6
    Assume \(L\) is countable. If the \(L\)-structure \(\fM\) is generated by a well-ordered
    sequence \((a_i)\) of indiscernibles, then \(\fM\) realises only countably many types over every
    countable subset of \(M\)
    #+END_lemma

    #+BEGIN_proof
    <<BIG Problem>>: need more time to think

    If \(A=\{a_i\mid i\in I\}\), then every element \(b\in M\) has the form \(b=t(\bara)\), where \(t\) is
    an \(L\)-term and \(\bara\) is a tuple from \(A\) since \(\fM\) is generated by \((a_i)\)

    Consider a countable subset \(S\) of \(M\). Write
    \begin{equation*}
    S=\{t_n^{\calm}(\bara^n)\mid n\in\omega\}
    \end{equation*}
    Let \(A_0=\{a_i\mid i\in I_0\}\) be the (countable) set of elements of \(A\) which occur in
    the \(\bara^n\). Then every type \(\tp(b/S)\) is determined by \(\tp(b/A_0)\) since
    every \(L(S)\)-formula
    \begin{equation*}
    \varphi(x,t_{n_1}^{\calm}(\bara^{n}),\dots)
    \end{equation*}
    can be replaced by the \(L(A_0)\)-formula \(\varphi(x,t_{n_1}(\bara^{n_1}),\dots)\)

    \(\tp(b/A_0)=\tp(t(\bara)/A_0)=\{\varphi(\barx)\; \call_{A_0}\text{-formula}: \fM\vDash\varphi(t(\bara))\}\).

    Now the type of \(b=t(\bara)\) over \(A_0\) depends only on \(t(\barx)\) (countably many
    possibilities) and the type \(\tp(\bara/A_0)\) (really?). Write \(\bara=a_{\bari}\) for a tuple \(\bari\)
    from \(I\). _Since the \(a_i\) are indiscernible, the type depends only on_
    _the quantifier-free type \(\tp_{\qf}(\bari/I_0)\) in the structure \((I,<)\)_ since it has
    quantifier elimination. This type again depends on \(\tp_{\qf}(\bari)\) (finitely many
    possibilities) and on the types  \(p(x)=\tp_{\qf}(i/I_0)\) of the elements \(i\) (Note the
    quantifier elimination, then we only need to Booleanly combine these things to get \(\tp_{\qf}(\bari/I_0)\))
    of \(\bari\). There are three kinds of such types:
    1. \(i\) is bigger than all elements of \(I_0\)
    2. \(i\) is an element \(i_0\) of \(I_0\)
    3. For some \(i_0\in I_0\), \(i\) is smaller than \(i_0\) but bigger than all elements
       of \(\{j\in I_0\mid j<i_0\}\)


    There is only one type in the first case, in the other case the type is determined by \(i_0\).
    This results in countably many possibilities for each component of \(\bari\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(L\) be a language. A *Skolem theory* \(\Skolem(L)\) is a theory in a bigger
    language \(L_{\Skolem}\) with the following properties
    1. \(\Skolem(L)\) has quantifier elimination
    2. \(\Skolem(L)\) is universal
    3. Every \(L\)-structure can be expanded to a model of \(\Skolem(L)\)
    4. \(\abs{L_{\Skolem}}\le\max(\abs{L},\aleph_0)\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Every language \(L\) has a Skolem theory.
    #+END_theorem

    #+BEGIN_proof
    Nice [[http://www-verimag.imag.fr/~monin/EnseignementPublic/Misc/L2/INF242/Slides/cours09skolem_En.pdf][slide]]. We have
    1. \(\exists xP(x)\) is a consequence of \(P(a)\)
    2. \(P(a)\) is not a consequence of \(\exists xP(x)\), but a model of \(\exists xP(x)\) *provides* a model
       of \(P(a)\)


    Skolemization eliminates existential quantifiers and transforms a closed formula \(A\) to a formula \(B\) such that :
    * \(A\) is a consequence of \(B\), \(B\vDash A\)
    * every model of A *provides* a model of B


    Hence, \(A\) has a model if and only if \(B\) has a model : /skolemization preserves the
    existence of a model/, in other words /it preserves satisfiability/.


    We define an ascending sequence of languages
    \begin{equation*}
    L=L_0\subseteq L_1\subseteq L_2\subseteq\cdots
    \end{equation*}
    by introducing for every quantifier-free \(L_i\)-formula \(\varphi(x_1,\dots,x_n,y)\) a new \(n\)-place
    *Skolem function*  \(f_\varphi\) (if \(n=0\), \(f_\varphi\) is a constant) and defining \(L_{i+1}\) as the
    union of \(L_i\) and the set of these function symbols. The language \(L_{\Skolem}\) is the union
    of all \(L_i\). We now define the Skolem theory as
    \begin{equation*}
    \Skolem=\{\forall\barx(\exists y\varphi(\barx,y)\to\varphi(\barx,f_\varphi(\barx)))\mid\varphi(\barx,y)\text{ q.f. $L_{\Skolem}$-formula}\}
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor5.1.9
    Let \(T\) be a countable theory with an infinite model and let \kappa be an infinite cardinal.
    Then \(T\) has a model of cardinality \kappa which realises only countably many types over every
    countable subset.
    #+END_corollary

    #+BEGIN_proof
    Consider the theory \(T^*=T\cup\Skolem(L)\). Then \(T^*\) is countable, has an infinite model and
    quantifier elimination

    *Claim*. \(T^*\) is equivalent to a universal theory

    /Proof/. Modulo \(\Skolem(L)\) every axiom \varphi of \(T\) is equivalent to a
    quantifier-free \(L_\Skolem\)-sentence \(\varphi^*\). Therefore \(T^*\) is equivalent to the universal
    theory

    Let \(I\) be a well-ordering of cardinality \kappa and \(\fN^*\) a model of \(T^*\) with
    indiscernibles \((a_i)_{i\in I}\) (Existence by the Standard Lemma ref:lemma5.1.3). The claim
    implies that the substructure \(\fM^*\) generated by
    the \(a_i\) is a model of \(T^*\) and \(\fM^*\) has cardinality \kappa (As we can't control the size of
    an elementary extension and Corollary ref:cor3.1.5). Since \(T^*\) has quantifier
    elimination, \(\fM^*\) is an elementary substructure of \(\fN^*\) and \((a_i)\) is indiscernible
    in \(\fM^*\). By Lemma ref:lemma5.1.6, there are only countably many types over every countable
    set realised in \(\fM^*\). The same is then true for the reduct \(\fM=\restr{\fM^*}{L}\)
    #+END_proof

    #+BEGIN_exercise
    label:ex5.1.1
    A sequence of elements in \((\Q,<)\) is indiscernible iff it is either constant, strictly
    increasing or strictly decreasing
    #+END_exercise

    #+BEGIN_proof
    For any formula \(\varphi(x_1,x_2,\dots,x_n)\),
    \begin{equation*}
    \Q\vDash\varphi(x_1,x_2,\dots,x_n)\leftrightarrow
    \end{equation*}
    #+END_proof

** \omega-stable theories
    In this section we fix a complete theory \(T\) with infinite models

    In the previous section we saw that we may add indiscernible elements to a model without
    changing the number of realised types. We will now use this to show that \(\aleph_1\)-categorical
    theories a small number of types, i.e., they are \omega-stable. Conversely, with few types it is
    easier to be saturated and since saturated structures are unique we find the connection to
    categorical theories.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \kappa be an infinite cardinal. We say \(T\) is *\kappa-stable* if in each model of \(T\), over
    every set of parameters of size at most \kappa, and for each \(n\), there are at most \kappa
    many \(n\)-types, i.e.,
    \begin{equation*}
    \abs{A}\le\kappa\Rightarrow\abs{S_n(A)}\le\kappa
    \end{equation*}
    #+END_definition

   Note that if \(T\) is \kappa-stable, then - up to logical equivalence - we have \(\abs{T}\le\kappa\)
   (Exercise ref:ex5.2.6)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   \(T\) is \kappa-stable iff \(T\) is \kappa-stable for 1-types, i.e.,
   \begin{equation*}
    \abs{A}\le\kappa\Rightarrow\abs{S(A)}\le\kappa
   \end{equation*}
   #+END_lemma

   #+BEGIN_proof
   Assume that \(T\) is \kappa-stable for 1-types. We show that \(T\) is \kappa-stable for \(n\)-types by
   induction on \(n\). Let \(A\) be a subset of the model \(\fM\) and \(\abs{A}\le\kappa\). We may assume
   that all types over \(A\) are realised in \(\fM\) (otherwise we take some elementary extensions by
   Corollary ref:cor2.2.9). Consider the restriction map \(\pi:S_n(A)\to S_1(A)\). By assumption the
   image \(S_1(A)\) has cardinality at most \kappa.
   Every \(p\in S_1(A)\) has the form \(\tp(a/A)\) for some \(a\in M\) since all types over \(A\) are
   realized in \(\fM\). By Exercise ref:ex4.2.5, the fibre \(\pi^{-1}(p)\) is in bijection
   with \(S_{n-1}(aA)\) and so has cardinality at most \kappa by induction. This shows \(\abs{S_n(A)}<\kappa\).
   #+END_proof

   #+ATTR_LATEX: :options [Algebraically closed fields]
   #+BEGIN_examplle
   The theories \(\ACF_p\) for \(p\) a prime or 0 are \(\kappa\)-stable for all \kappa
   #+END_examplle

   Note that by Theorem ref:thm5.2.6 below it would suffice to prove that the theories \(\ACF_p\)
   are \omega-stable

   #+BEGIN_proof
   <<Problem1>>
   Let \(K\) be a subfield of an algebraically closed field. By quantifier elimination, the type of
   _an element \(a\) over \(K\) is determined by the isomorphism type of the extension \(K[a]/K\)_.
   If \(a\) is transcendental over \(K\), \(K[a]\) is isomorphic to the polynomial ring \(K[X]\).
   If \(a\) is algebraic with minimal polynomial \(f\in K[X]\), then \(K[a]\) is isomorphic
   to \(K[X]/(f)\). _So there is one more 1-type over \(K\) than there are irreducible polynomials_
   #+END_proof

   That \(\ACF_p\) is \kappa-stable for \(n\)-types has a direct algebraic proof: the isomorphism type
   of \(K[a_1,\dots,a_n]/K\) is determined by the vanishing ideal \(P\) of \(a_1,\dots,a_n\). By :((((

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm5.2.4
   A countable theory \(T\) which is categorical in an uncountable cardinal \kappa is \omega-stable
   #+END_theorem

   #+BEGIN_proof
   Let \(\fN\) be a model and \(A\subseteq N\) countable with \(S(A)\) uncountable. Let \((b_i)_{i\in I}\) be a
   sequence of \(\aleph_1\) many elements with pairwise distinct types over \(A\). (Note that we can
   assume that all types over \(A\) are realised in \(\fN\)) We choose first an elementary
   substructure \(\fM_0\) of cardinality \(\aleph_1\) which contains \(A\) and all \(b_i\). Then we choose an
   elementary extension \(\fM\) of \(\fM_0\). The model \(\fM\) is of cardinality \kappa and realises
   uncountably many types over the countable set \(A\). By Corollary ref:cor5.1.9, \(T\) has another
   model where this is not the case. So \(T\) cannot be \kappa-categorical
   #+END_proof

   [[index:totally transcendental]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A theory \(T\) is *totally transcendental* if it has no model \(\fM\) with a binary tree of
   consistent \(L(M)\)-formulas
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm5.2.6
   1. \omega-stable theories are totally transcendental
   2. Totally transcendental theories are \kappa-stable for all \(\kappa\ge\abs{T}\)
   #+END_theorem

   It follows that a countable theory \(T\) is \omega-stable iff it is totally transcendental

   #+BEGIN_proof
   1. Let \(\fM\) be a model with a binary tree of consistent \(L(M)\)-formulas with free variables
      among \(x_1,\dots,x_n\). The set \(A\) of parameters which occur in the tree's formulas is
      countable but \(S_n(A)\) has cardinality \(2^{\aleph_0}\)
   2. Assume that there are there are more than \kappa many \(n\)-types over some set \(A\) of
      cardinality \kappa. Let us call an \(L(A)\)-formula *big* if it belongs to more than \kappa many types
      over \(A\) (\(\abs{[\phi]}>\kappa\)) and *thin* otherwise. By assumption the true formula is big. If we
      can show that each big formula decomposes into two big formulas, we can construct a binary
      tree of big formulas, which finishes the proof.

      So assume that \varphi is big. Since each thin formula belongs to at most \kappa types and since there
      are at most \kappa formulas, there are at most \kappa types which contain thin formulas. Therefore
      \varphi belongs to two distinct types \(p\) and \(q\) which contain only big formulas. If we
      separate \(p\) and \(q\) by \(\psi\in p\) and \(\neg\psi\in q\), we decompose \varphi into the big
      formulas \(\varphi\wedge\psi\) and \(\varphi\wedge\neg\psi\).
   #+END_proof

   The general case follows from Exercise ref:ex5.2.5

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal. An \(L\)-structure \(\fA\) is *\kappa-saturated* if in \(\fA\) all
   types over sets of cardinality less than \kappa are realised. An infinite structure \(\fA\) is *saturated*
   if it is \(\abs{\fA}\)-saturated
   #+END_definition

   Lemma ref:lemma4.3.3 generalises to sets

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma5.2.8
   Elementarily equivalent saturated structures of the same cardinality are isomorphic
   #+END_lemma

   #+BEGIN_proof
   Let \(\fA\) and \(\fB\) be elementary equivalent saturated structures each of cardinality \kappa. We
   choose enumerations \((a_\alpha)_{\alpha<\kappa}\) and \((b_\alpha)_{\alpha<\kappa}\) of \(A\) and \(B\) and construct an
   increasing sequence of elementary maps \(f_\alpha:A_\alpha\to B_\alpha\). Assume that the \(f_\beta\) are constructed
   for all \(\beta<\alpha\). The union of the \(f_\beta\) is an elementary map \(f_\alpha^*:A_\alpha^*\to B_\alpha^*\). The
   construction will imply that \(A_\alpha^*\) and \(B_\alpha^*\) have cardinality at most \(\abs{\alpha}\), which
   is smaller than \kappa

   We write \(\alpha=\lambda+n\), and distinguish two cases

   \(n=2i\): In this case, we consider \(p(x)=\tp(a_{\lambda+i}/A_\alpha^*)\). Realise \(f_\alpha^*(p)\) by \(b\in B\)
   and define
   \begin{equation*}
   f_\alpha=f_\alpha^*\cup\{\la a_{\lambda+i},b\ra\}
   \end{equation*}

   \(n=2i+1\): Similarly, we find an extension
   \begin{equation*}
   f_\alpha=f_\alpha^*\cup\{\la a,b_{\lambda+i}\ra\}
   \end{equation*}
   Thus \(\bigcup_{\alpha<\kappa}f_\alpha\) is the desired isomorphism
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma5.2.9
   If \(T\) is \kappa-stable, then for all regular \(\lambda\le\kappa\), there is a model of cardinality \kappa which is \lambda-saturated
   #+END_lemma

   #+BEGIN_proof
   By Exercise ref:ex5.2.6 we may assume that \(\abs{T}\le\kappa\).  Consider a model \(\fM\) of cardinality
   \kappa. Since \(S(M_\alpha)\) has cardinality \kappa, Corollary ref:cor2.2.9 and the Löwenheim–Skolem theorem
   give an elementary extension of cardinality \kappa in which all types over \(\fM\) are realised. So can
   construct a continuous elementary chain
   \begin{equation*}
   \fM_0\prec\fM_1\prec\dots\prec\fM_\alpha\prec\cdots(\alpha<\lambda)
   \end{equation*}
   of models of \(T\) with cardinality \kappa s.t. all \(p\in S(M_\alpha)\) are realised in \(\fM_{\alpha+1}\).
   Then \(\fM\) is \lambda-saturated. In fact, if \(\abs{A}<\lambda\) and if \(a\in A\) is contained in \(M_{\alpha(a)}\)
   then \(\Lambda=\bigcup_{a\in A}\alpha(a)\) is an initial segment of \lambda of smaller cardinality than \lambda. So \Lambda has an
   upper bound \(\mu<\lambda\). It follows that \(A\subseteq\fM_\mu\) and all types over \(A\) are realised in \(\fM_{\mu+1}\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm5.2.11
   A countable theory \(T\) is \kappa-categorical iff all models of cardinality \kappa are saturated
   #+END_theorem

   #+BEGIN_proof
   If all models of cardinality \kappa are saturated, it follows from Lemma ref:lemma5.2.8 that \(T\) is
   \kappa-categorical

   Assume, for the converse that \(T\) is \kappa-categorical. For \(\kappa=\aleph_0\) the theorem follows from
   Theorem ref:thm4.3.1. So we may assume that \kappa is uncountable. Then \(T\) is totally
   transcendental by Theorem ref:thm5.2.4 and ref:thm5.2.6 and therefore \kappa-stable by Theorem
   ref:thm5.2.6.

   By Lemma ref:lemma5.2.9, _all models of \(T\) of cardinality \kappa are \(\mu^+\)-saturated for_
   _all \(\mu<\kappa\). i.e., \kappa-saturated_
   #+END_proof

   #+BEGIN_exercise
   label:ex5.2.2
   Show that the theory of an equivalence relation with two infinite classes has quantifier
   elimination and is \omega-stable. Is it \(\aleph_1\)-categorical?
   #+END_exercise


   #+BEGIN_exercise
   label:ex5.2.5
   If \(T\) is an \(L\)-theory and \(K\) is a sublanguage of \(L\), the *reduct* \(T\restriction K\) is
   the set of all \(K\)-sentences which follow from \(T\). Show that \(T\) is totally transcendental
   iff \(T\restriction K\) is \omega-stable for all at most countable \(K\subseteq L\)
   #+END_exercise

   #+BEGIN_proof

   #+END_proof

   #+BEGIN_exercise
   label:ex5.2.6
   If \(T\) is \kappa-stable, then /essentially/ (i.e., up to logical equivalence) \(\abs{T}\le\kappa\)
   #+END_exercise

   #+BEGIN_proof
   If \(T\) is \kappa-stable, then \(\abs{S_n(\emptyset)}\le\kappa\). Choose for any two \(n\)-types over the empty set a
   separating formula. Then any formula is logically equivalent to a finite Boolean combination of
   these \kappa-many formulas
   #+END_proof

** Prime extensions
   #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\fM\) be a model of \(T\) and \(A\subseteq M\).
    1. \(\fM\) is a *prime extension* of \(A\) (or *prime over* \(A\)) if every elementary map \(A\to\fN\)
       extends to an elementary map \(\fM\to\fN\)
       \begin{center}\begin{tikzcd}
       \fM\ar[r]&\fN\\
       A\ar[u,"id_A"]\ar[ur]
       \end{tikzcd}\end{center}
    2. \(B\subseteq M\) is *constructible* over \(A\) if \(B\) has an enumeration
       \begin{equation*}
       B=\{b_\alpha\mid\alpha<\lambda\}
       \end{equation*}
       where each \(b_\alpha\) is atomic over \(A\cup B_\alpha\) (\(\tp(b_\alpha/A\cup B_\alpha)\) is isolated), with \(B_\alpha=\{b_\mu\mid \mu<\alpha\}\)

       \(b_\alpha\) is atomic on the sense of \(\Th(\calm_A)\), maybe \(S_1(\Th(\calm_A))\)
    #+END_definition

    So \(\fM\) is a prime extension of \(A\) iff \(\fM_A\) is a prime model of \(\Th(\fM_A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma5.3.2
    If a model \(M\) is constructible over \(A\), then \(\fM\) is prime over \(A\)
    #+END_lemma

    #+BEGIN_proof
    Let \((m_\alpha)_{\alpha<\lambda}\) an enumeration of \(M\), s.t. each \(m_\alpha\) is atomic over \(A\cup M_\alpha\).
    Let \(f:A\to\fN\) be an elementary map. We define inductively an increasing sequence of elementary
    maps \(f_\alpha:A\cup M_{\alpha+1}\to\fN\) with \(f_0=f\). Assume that \(f_\beta\) is defined for all \(\beta<\alpha\). The
    union of these \(f_\beta\) is an elementary map \(f_\alpha':A\cup M_\alpha\to\fN\). Since \(p(x)=\tp(a_\alpha/A\cup M_\alpha)\) is
    isolated, \(f_\alpha'(p)\in S(f_\alpha'(A\cup M_\alpha))\) is also isolated and has a realisation \(b\) in \(\fN\). We
    set \(f_\alpha=f_\alpha'\cup\{\la a_\alpha,b\ra\}\)

    Finally, the union of all \(f_\alpha\) (\(\alpha<\lambda\)) is an elementary embedding \(\fM\to\fN\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm5.3.3
    If \(T\) is totally transcendental, every subset of a model of \(T\) has a constructible prime extension
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(T\) is totally transcendental, the isolated types are dense over every subset of any model
    #+END_lemma

    #+BEGIN_proof
    Consider a subset \(A\) of a model \(\fM\). Then \(\Th(\fM_A)\supset T\) has no binary tree of consistent
    formulas. Then \(\Th(\fM_A)\) has no binary tree of consistent formulas. By Theorem ref:thm4.5.9
    #+END_proof

    #+ATTR_LATEX: :options [Proof of Theorem \ref{thm5.3.3}]
    #+BEGIN_proof
    By Lemma ref:lemma5.3.2 it suffices to construct an elementary substructure \(\fM_0\prec\fM\) which
    contains \(A\) and is constructible over \(A\).
    #+END_proof


* Appendix :ignore:
  #+LATEX: \appendix
** Fields
*** Ordered fields
    Let \(R\) be an integral domain. A linear < ordering on \(R\) is *compatible* with the ring
    structure if for all \(x,y,z\in R\)
    \begin{align*}
    x<y&\to x+z<y+z\\
    x<y\wedge 0<z&\to xz<yz
    \end{align*}
    A field \((K,<)\) together with a compatible ordering is an *ordered field*

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(R\) be an integral domain and < a compatible ordering of \(R\). Then the ordering < can be
    uniquely extended to an ordering of the quotient field of \(R\)
    #+END_lemma

    It is easy to see that in an ordered field sums of squares can never be negative. In particular,
    1, 2, . . . are always positive and so the characteristic of an ordered field is 0. A field K in
    which −1 is not a sum of squares is called *formally real*.
* TODO Don't understand
  Lemma ref:lemma3.2.13

  Exercise ref:ex3.2.3

  theorem ref:thm4.3.1 need to enhance my TOPOLOGY and ALGEBRA!!!

  [[BIG Problem]]

  [[Problem1]]
* Footnotes                                                          :ignore:

[fn:1] A subset of a topological space is *nowhere dense* if its closure has no interior. A countable union of nowhere dense sets is meagre
