#+TITLE: A Course in Model Theory
#+AUTHOR: Katin Tent & Martin Ziegler

#+STARTUP: noindent
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \setcounter{secnumdepth}{2}
#+LATEX_HEADER: \setcounter{tocdepth}{2}
#+EXPORT_FILE_NAME: ../latex/ACourseInModelTheory/ACourseInModelTheory.tex

* The Basics

** Structures
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA,\fB\) be \(L\)-structures. A map \(h:A\to B\) is called a
   *homomorphism* if for all \(a_1,\dots,a_n\in A\)
   \begin{equation*}
    \begin{array}{rcl}
    h(c^{\fA})&=&c^{\fB}\\
    h(f^{\fA}(a_1,\dots,a_n))&=&f^{\fB}(h(a_1),\dots,h(a_n))\\
    R^{\fA}(a_1,\dots,a_n)&\Rightarrow&R^{\fB}(h(a_1),\dots,h(a_n))
    \end{array}
   \end{equation*}

   We denote this by
   \begin{equation*}
    h:\fA\to\fB
   \end{equation*}
   
   If in addition \(h\) is injective and
   \begin{equation*}
    R^{\fA}(a_1,\dots,a_n)\Leftrightarrow R^{\fB}(h(a_1),\dots,h(a_n))
   \end{equation*}
   for all \(a_1,\dots,a_n\in A\), then \(h\) is called an (isomorphic)
   *embedding*. An *isomorphism* is a surjective embedding
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.1.8
   Let \(h:\fA \isoto\fA'\) be an isomorphism and \(\fB\) an
   extension of \(\fA\). Then there exists an extension \(\fB'\) of \(\fA'\) and
   an isomorphism \(g:\fB \isoto\fB' \) extending \(h\)
   #+END_lemma

   For any family \(\fA_i\) of substructures of \(\fB\), the intersection of the
   \(A_i\) is either empty or a substructure of \(\fB\). Therefore if \(S\) is
   any non-empty subset of \(\fB\), then there exists a smallest substructure
   \(\fA=\la S\ra^{\fB}\) which contains \(S\). We call the \(\fA\) the
   substructure *generated* by \(S\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \(\fa=\la S\ra\), then every homomorphism \(h:\fA\to\fB\) is determined by
   its values on \(S\)
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
    Let \((I,\le)\) be a *directed partial order*. This means that for all
    \(i,j\in I\) there exists a \(k\in I\) s.t. \(i\le k\) and \(j\le k\). A
    family \((\fA_i)_{i\in I}\) of \(L\)-structures is called *directed* if
    \begin{equation*}
    i\le j\Rightarrow\fA_i\subseteq\fA_j
    \end{equation*}
    If \(I\) is linearly ordered, we call \((\fA_i)_{i\in I}\) a *chain*
   #+END_definition

   If a structure \(\fA_1\) is isomorphic to a substructure \(\fA_0\) of itself,
   \begin{equation*}
    h_0:\fA_0\isoto\fA_1
   \end{equation*}
   then Lemma ref:lemma1.1.8 gives an extension
   \begin{equation*}
    h_1:\fA_1\isoto\fA_2
   \end{equation*}
   Continuing in this way we obtain a chain 
   \(\fA_0\subseteq \fA_1\subseteq\fA_2\subseteq\dots\)
   and an increasing sequence
   \(h_i:\fA_i\isoto\fA_{i+1}\) of isomorphism

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \((\fA_i)_{i\in I}\) be a directed family of \(L\)-structures. Then
   \(A=\bigcup_{i\in I}A_i\) is the universe of a (uniquely determined)
   \(L\)-structure
   \begin{equation*}
   \fA=\bigcup_{i\in I}\fA_i
   \end{equation*}
   which is an extension of all \(\fA_i\)
   #+END_lemma
   
   A subset \(K\) of \(L\) is called a *sublanguage*. An \(L\)-structure becomes a
   \(K\)-structure, the *reduct*.
   \begin{equation*}
   \fA\restriction K=(A,(Z^{\fA})_{Z\in K})
   \end{equation*}
   Conversely we call \(\fA\) an *expansion* of \(\fA\restriction K\).
   1. Let \(B\subseteq A\) , we obtain a new language
      \begin{equation*}
      L(B)=L\cup B
      \end{equation*}
      and the \(L(B)\)-structure 
      \begin{equation*}
      \fA_B=(\fA,b)_{b\in B}
      \end{equation*}
      Note that \(\Aut(\fA_B)\) is the group of automorphisms of \(\fA\) fixing
      \(B\) elementwise. We denote this group by \(\Aut(\fA/B)\)
      
      
   Let \(S\) be a set, which we call the set of sorts. An \(S\)-sorted
   language \(L\) is given by a set of constants for each sort in \(S\), and
   typed function and relations. For any tuple \((s_1,\dots,s_n)\) and
   \((s_1,\dots,s_n,t)\) there is a set of relation symbols and function
   symbols respectively. An \(S\)-sorted structure is a pair
   \(\fA=(A,(Z^{\fA})_{Z\in L})\), where 
   \begin{alignat*}{2}      
   &A&&\text{if a family $(A_s)_{s\in S}$ of non-empty sets}\\
   &Z^{\fA}\in A_s&&\text{if $Z$ is a constant of sort $s\in S$}\\
   &Z^{\fA}:A_{s_1}\times\dots\times A_{s_n}\to A_t&&\text{if $Z$ is a
   function symbol of type $(s_1,\dots,s_n,t)$}\\
   &Z^{\fA}\subseteq A_{s_1}\times\dots\times A_{s_n}&&\text{if $Z$ is a
   relation symbol of type $(s_1,\dots,s_n)$}
   \end{alignat*}

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Consider the two-sorted language \(L_{Perm}\) for permutation groups with a
   sort \(x\) for the set and a sort \(g\) for the group. The constants and
   function symbols for \(L_{Perm}\) are those of \(L_{Group}\) restricted to
   the sort \(g\) and an additional function symbol \varphi of type \((x,g,x)\). Thus
   an \(L_{Perm}\)-structure \((X,G)\) is given by a set \(X\) and an
   \(L_{Group}\)-structure \(G\) together with a function \(X\times G\to X\)
   #+END_examplle

** Language
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.2.11
   Suppose \(\vv{b}\) and \(\vv{c}\) agree on all variables which are free
   in \varphi. Then 
   \begin{equation*}
   \fA\models\varphi[\vv{b}]\Leftrightarrow\fA\models\varphi[\vv{c}]
   \end{equation*}
   #+END_lemma

   We define
   \begin{equation*}
   \fA\models\varphi[a_1,\dots,a_n]
   \end{equation*}
   by \(\fA\models\varphi[\vv{b}]\), where \(\vv{b}\) is an assignment
   satisfying \(\vv{b}(x_i)=a_i\). Because of Lemma ref:lemma1.2.11 this is
   well defined.

   


   Thus \(\varphi(x_1,\dots,x_n)\) defines an \(n\)-ary relation
   \begin{equation*}
   \varphi(\fA)=\{\bbar{a}\mid\fA\models\varphi[\bbar{a}]\}
   \end{equation*}
   on \(A\), the *realisation set* of \varphi. Such realisation sets are called
   *0-definable subsets* of \(A^n\), or 0-definable relations

   Let \(B\) be a subset of \(A\). A *\(B\)-definable* subset of \(\fA\) is a set
   of the form \(\varphi(\fA)\) for an \(L(B)\)-formula \(\varphi(x)\). We also say that \varphi
   are defined *over* \(B\) and that the set \(\varphi(\fA)\) is defined by \varphi. We call
   two formulas *equivalent* if in every structure they define the same set.

   Atomic formulas and their negations are called *basic*. Formulas without
   quantifiers are Boolean combinations of basic formulas. It is convenient to
   allow the empty conjunction and the empty disjunction. For that we introduce
   two new formulas: the formula \(\top\), which is always true, and the formula
   \(\bot\), which is always false. We define
   \begin{align*}
   &\bigwedge_{i<0}\pi_i=\top\\
   &\bigvee_{i<0}\pi_i=\bot
   \end{align*}

   A formula is in *negation normal form* if it is built from basic formulas using
   \(\wedge,\vee,exists,\forall\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A formula in negation normal form which does not contain any existential
   quantifier is called *universal*. Formulas in negation normal form without
   universal quantifiers are called *existential*
   #+END_definition

   
   Let \(\fA\) be an \(L\)-structure. The *atomic diagram* of \(\fA\) is
   \begin{equation*}
   \Diag(\fA)=\{\varphi\text{ basic $L(A)$-sentence}\mid\fA_A\models\varphi\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   The models of \(\Diag(\fa)\) are precisely those structures
   \((\fB,h(a))_{a\in A}\) for embeddings \(h:\fA\to\fB\)
   #+END_lemma

   #+BEGIN_exercise
   label:ex1.2.3
   Every formula is equivalent to a formula in prenex normal form:
   \begin{equation*}
   Q_1x_1\dots Q_nx_n\varphi
   \end{equation*}
   The \(Q_i\) are quantifiers and \varphi is quantifier-free
   #+END_exercise

   #+BEGIN_proof
   \begin{align*}
   &(\forall x)\phi\wedge\psi\models\rmodels
   \forall x(\phi\wedge\psi)\text{ if }\exists x\top(\text{at least one individual exists})\\
   &(\forall x\phi)\vee\psi\models\rmodels\forall x(\phi\vee\psi)\\
   &(\exists x\phi)\wedge\psi\models\rmodels\exists x(\phi\wedge\psi)\\
   &(\exists x\phi)\vee\psi\models\rmodels\exists x(\phi\vee\psi)\text{ if }\exists x\top\\
   &\neg\exists x\phi\models\rmodels\forall x\neg\phi\\
   &\neg\forall x\phi\models\rmodels\exists x\neg\phi\\
   &(\forall x\phi)\to\psi\models\rmodels\exists x(\phi\to\psi)\text{ if }\exists x\top\\
   &(\exists x\phi)\to\psi\models\rmodels\forall x(\phi\to\psi)\\
   &\phi\to(\exists x\psi)\models\rmodels\exists x(\phi\to\psi)\text{ if }\exists x\top\\
   &\phi\to(\forall x\psi)\models\rmodels\forall x(\phi\to\psi)
   \end{align*}
   #+END_proof

** Theories
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An *\(L\)-theory* \(T\) is a set of \(L\)-sentences
   #+END_definition
   
   A theory which has a model is a *consistent* theory. We call a set \Sigma of
   \(L\)-formulas *consistent* if there is an \(L\)-structure and *an assignment*
   \(\vv{b}\) *s.t.* \(\fA\models[\vv{b}]\) for all \(\varphi\in\Sigma\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(T\) be an \(L\)-theory and \(L'\) be an extension of \(L\). Then \(T\)
   is consistent as an \(L\)-theory iff \(T\) is consistent as a \(L'\)-theory
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.3.4
   1. If \(T\models\varphi\) and \(T\models(\varphi\to\psi)\), then \(T\models\psi\)
   2. If \(T\models\varphi(c_1,\dots,c_n)\) and the constants \(c_1,\dots,c_n\)
      occur neither in \(T\) nor in \(\varphi(x_1,\dots,x_n)\), then \(T\models\forall
      x_1\dots x_n\varphi(x_1,\dots,x_n)\)
   #+END_lemma

   #+BEGIN_proof
   2. [@2] Let \(L'=L\setminus\{c_1,\dots,c_n\}\). If the \(L'\)-structure is a
      model of \(T\) and \(a_1,\dots,a_n\) are arbitrary elements, then
      \((\fA,a_1,\dots,a_n)\models\varphi(c_1,\dots,c_n)\). This means
      \(\fA\models\forall x_1\dots x_n\varphi(x_1,\dots,x_n)\).
   #+END_proof

   \(S\) and \(T\) are called *equivalent*, \(S\equiv T\), if \(S\) and \(T\) have
   the same models

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A consistent \(L\)-theory \(T\) is called *complete* if for all \(L\)-sentences
   \varphi
   \begin{equation*}
   T\models\varphi \quad\text{ or }\quad T\models\neg\varphi
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For a complete theory \(T\) we define
   \begin{equation*}
   \abs{T}=\max(\abs{L},\aleph_0)
   \end{equation*}
   #+END_definition

   The typical example of a complete theory is the theory of a structure \(\fA\)
   \begin{equation*}
   \Th(\fA)=\{\varphi\mid\fA\models\varphi\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   A consistent theory is complete iff it is maximal consistent, i.e., if it is
   equivalent to every consistent extension
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Two \(L\)-structures \(\fA\) and \(\fB\) are called *elementary equivalent*
   \begin{equation*}
   \fA\equiv\fB
   \end{equation*}
   if they have the same theory
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(T\) be a consistent theory. Then the following are equivalent
   1. \(T\) is complete
   2. All models of \(T\) are elemantarily equivalent
   3. There exists a structure \(\fA\) with \(T\equiv\Th(\fA)\)
   #+END_lemma

   #+BEGIN_proof
   \(1\to3\to2\to1\)
   #+END_proof


   


* Elementary Extensions and Compactness
** Elementary substructures
   Let \(\fA,\fB\) be two \(L\)-structures. A map \(h:A\to B\) is called
   *elementary* if for all \(a_1,\dots,a_n\in A\) we have
   \begin{equation*}
   \fA\models\varphi[a_1,\dots,a_n]\Leftrightarrow
   \fB\models\varphi[h(a_1),\dots,h(a_n)]
   \end{equation*}
   We write
   \begin{equation*}
   h:\fA\embto\fB
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.1.1
   The models of \(\Th(\fA_A)\) are exactly the structures of the form
   \((\fB,h(a))_{a\in A}\) for elementary embeddings \(h:\fA\embto\fB\)
   #+END_lemma

   We call \(\Th(\fA_A)\) the *elemantary diagram* of \(\fA\)

   A substructure \(\fA\) of \(\fB\) is called *elementary* if the inclusion map
   is elementary. In this case we write
   \begin{equation*}
   \fA\prec\fB
   \end{equation*}

   #+ATTR_LATEX: :options [Tarski's Test]
   #+BEGIN_theorem
   label:thm2.1.2
   Let \(\fB\) be an \(L\)-structure and \(A\) a subset of \(B\). Then \(A\) is
   the universe of an elementary substructure iff every \(L(A)\)-formula
   \(\varphi(x)\) which is satisfiable in \(\fB\) can be satisfied by an element of \(A\)
   #+END_theorem

   We use Tarski's Test to construct small elementary substructures

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor2.1.3
   Suppose \(S\) is a subset of the \(L\)-structure \(\fB\). Then \(\fB\) has a
   elementary substructure \(\fA\) containing \(S\) and of cardinality at most
   \begin{equation*}
   \max(\abs{S},\abs{L},\aleph_0)
   \end{equation*}
   #+END_corollary

   #+BEGIN_proof
   We construct \(A\) as the union of an ascending sequence \(S_0\subseteq
   S_1\subseteq\dots\) of subsets of \(B\). We start with \(S_0=S\). If \(S_i\)
   is already defined, we choose an element \(a_\varphi\in B\) for every
   \(L(S_i)\)-formula \(\varphi(x)\) which is satisfiable in \(\fB\) and define
   \(S_{i+1}\) to be \(S_i\) together with these \(a_{\varphi}\).

   An \(L\)-formula is a finite sequence of symbols from \(L\), auxiliary
   symbols and logical symbols. These are
   \(\abs{L}+\aleph_0=\max(\abs{L},\aleph_0)\) many symbols and there are
   exactly\(\max(\abs{L},\aleph_0)\) many \(L\)-formulas

   Let \(\kappa=\max(\abs{S},\abs{L},\aleph_0)\). There are \kappa many
   \(L(S)\)-formulas: therefore \(\abs{S_1}\le\kappa\). Inductively it follows
   for every \(i\) that \(\abs{S_i}\le\kappa\). Finally we have \(\abs{A}\le\kappa\cdot\aleph_0=\kappa\)
   #+END_proof

   A directed family \((\fA_i)_{i\in I}\) of structures is *elementary* if
   \(\fA_i\prec\fA_j\) for all \(i\le j\)

   #+ATTR_LATEX: :options [Tarski's Chain Lemma]
   #+BEGIN_theorem
   label:thm2.1.4
   The union of an elementary directed family is an elementary extension of all
   its members
   #+END_theorem

   #+BEGIN_proof
   Let \(\fA=\bigcup_{i\in I}(\fA_i)_{i\in I}\). We prove by induction on
   \(\varphi(\bbar{x})\) that for all \(i\) and \(\bbar{a}\in\fA_i\)
   \begin{equation*}
   \fA_i\models\varphi(\bbar{a})\Leftrightarrow\fA\models\varphi(\bbar{a})
   \end{equation*}
   #+END_proof


** The Compactness Theorem
   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   Finitely satisfiable theories are consistent
   #+END_theorem
   
   Let \(L\) be a language and \(C\) a set of new constants. An \(L(C)\)-theory
   \(T'\) is called a *Henkin theory* if for every \(L(C)\)-formula \(\varphi(x)\) there
   is a constant \(c\in C\) s.t.
   \begin{equation*}
   \exists x\varphi(x)\to\varphi(c)\in T'
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Every finitely satisfiable \(L\)-theory \(T\) can be extended to a finitely
   complete Henkin Theory \(T^*\)
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.2.3
   Every finitely satisfiable \(L\)-theory \(T\) can be extended to a finitely
   complete Henkin theory \(T^*\)
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Every finitely complete Henkin theory \(T^*\) has a model \(\fA\) (unique up
   to isomorphism) consisting of constants; i.e.,
   \begin{equation*}
   (\fA,a_c)_{c\in C}\models T^*
   \end{equation*}
   with \(A=\{a_c\mid c\in C\}\)
   #+END_lemma
   

   
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor2.2.5
   A set of formulas \(\Sigma(x_1,\dots,x_n)\) is consistent with \(T\) if and only
   if every finite subset of \Sigma is consistent with \(T\)
   #+END_corollary
   
   #+BEGIN_proof
   Introduce new constants \(c_1,\dots,c_n\). Then \Sigma is consistent with \(T\) is
   and only if \(T\cup\Sigma(c_1,\dots,c_n)\) is consistent. Now apply the
   Compactness Theorem
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA\) be an \(L\)-structure and \(B\subseteq A\). Then \(a\in A\)
   *realises* a set of \(L(B)\)-formulas \(\Sigma(x)\) if \(a\) satisfied all formulas
   from \(\Sigma\). We write 
   \begin{equation*}
   \fA\models\Sigma(a)
   \end{equation*}
   
   We call \(\Sigma(x)\) *finitely satisfiable* in \(\fA\) if every finite subset of \Sigma
   is realised in \(\fA\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.2.7
   The set \(\Sigma(x)\) is finitely satisfiable in \(\fA\) iff there is an
   elementary extension of \(\fA\) in which \(\Sigma(x)\) is realised
   #+END_lemma

   #+BEGIN_proof
   By Lemma ref:lemma2.1.1 \Sigma is realised in an elementary extension of \(\fA\)
   iff \Sigma is consistent with \(\Th(\fA_A)\). So the lemma follows from the
   observation that a finite set of \(L(A)\)-formulas is consistent with
   \(\Th(\fA_A)\) iff it is realised in \(\fA\)
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(\fA\) be an \(L\)-structure and \(B\) a subset of \(A\). A set \(p(x)\)
   of \(L(B)\)-formulas is a *type* over \(B\) if \(p(x)\) is maximal finitely
   satisfiable in \(\fA\). We call \(B\) the *domain* of \(p\). Let
   \begin{equation*}
   S(B)=S^{\fA}(B)
   \end{equation*}
   denote the set of types over \(B\).
   #+END_definition

   Every element \(a\) of \(\fA\) determines a type
   \begin{equation*}
   \tp(a/B)=tp^{\fA}(a/B)=\{\varphi(x)\mid\fA\models\varphi(a),\varphi\text{ an $L(B)$-formula}\}
   \end{equation*}
   So an element \(a\) realises the type \(p\in S(B)\) exactly if
   \(p=\tp(a/B)\). If \(\fA'\) is an elementary extension of \(\fA\), then
   \begin{equation*}
   S^{\fA}(B)=S^{\fA'}(B)\quad\text{ and }\quad
   \tp^{\fA'}(a/B)=\tp^{\fA}(a/B)
   \end{equation*}
   If \(\fA'\models p(x)\) then \(\fA'\models\exists xp(x)\), so
   \(\fA\models\exists xp(x)\).

   We use the notation \(\tp(a)\) for \(\tp(a/\emptyset)\)

   Maximal finitely satisfiable sets of formulas in \(x_1,\dots,x_n\) are called
   *\(n\)-types* and
   \begin{equation*}
   S_n(B)=S_N^{\fA}(B)
   \end{equation*}
   denotes the set of \(n\)-types over \(B\).
   \begin{equation*}
   \tp(C/B)=\{\varphi(x_{c_1},\dots,x_{c_n})\mid\fA\models\varphi(c_1,\dots,c_n),\varphi
   \text{ an $L(B)$-formula}\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Every structure \(\fA\) has an elementary extension \(\fB\) in which all
   types over \(A\) are realised
   #+END_corollary

   #+BEGIN_proof
   We choose for every \(p\in S(A)\) a new constant \(c_p\). We have to find a
   model of
   \begin{equation*}
   \Th(\fA_A)\cup\bigcup_{p\in S(A)}p(c_p)
   \end{equation*}
   This theory is finitely satisfiable since every \(p\) is finitely satisfiable
   in \(\fA\).

   Or use Lemma ref:lemma2.2.7. Let \((p_\alpha)_{\alpha<\lambda}\) be an enumeration of
   \(S(A)\). Construct an elementary chain
   \begin{equation*}
   \fA=\fA_0\prec\fA_1\prec\dots\prec\fA_\beta\prec\dots(\beta\le\lambda)
   \end{equation*}
   s.t. each \(p_\alpha\) is realised in \(\fA_{\alpha+1}\) (by recursion
   theorem on ordinal numbers)

   Suppose that the elementary chain \((\fA_{\alpha'})_{\alpha'<\beta}\) is already
   constructed. If \beta is a limit ordinal, we let
   \(\fA_\beta=\bigcup_{\alpha<\beta}\fA_\alpha\), which is elementary by Lemma ref:thm2.1.4. If
   \(\beta=\alpha+1\) we  first note that \(p_\alpha\) is also finitely
   satisfiable in \(\fA_\alpha\), therefore we can realise \(p_\alpha\) in a
   suitable elementary extension \(\fA_\beta\succ\fA_\alpha\) by Lemma
   ref:lemma2.2.7. Then \(\fB=\fA_\lambda\) is the model we were looking for
   #+END_proof

** The Löwenheim-Skolem Theorem
   #+ATTR_LATEX: :options [Löwenheim-Skolem]
   #+BEGIN_theorem
   Let \(\fB\) be an \(L\)-structure, \(S\) a subset of \(B\) and \kappa an infinite
   cardinal
   1. If
      \begin{equation*}
      \max(\abs{S},\abs{L})\le\kappa\le\abs{B}
      \end{equation*}
      then \(\fB\) has an elementary substructure of cardinality \kappa containing \(S\)
   2. If \(\fB\) is infinite and
      \begin{equation*}
      \max(\abs{\fB},\abs{L})\le\kappa
      \end{equation*}
      then \(\fB\) has an elementary extension of cardinality \kappa
   #+END_theorem

* Quantifier Elimination
** Preservation theorems
   #+ATTR_LATEX: :options [Separation Lemma]
   #+BEGIN_lemma
   Let \(T_1, T_2\) be two theories. Assume \(\calh\) is a set of sentences
   which is closed under \(\wedge,\vee\) and contains \(\bot\) and \(\top\).
   Then the following are equivalent
   1. There is a sentence \(\varphi\in\calh\) which separates \(T_1\) from
      \(T_2\). This means
      \begin{equation*}
        T_1\models\varphi \quad\text{ and }\quad
        T_2\models\neg\varphi
      \end{equation*}
   2. All models \(\fA_1\) of \(T_1\) can be separated from all models \(\fA_2\)
      of \(T_2\) by a sentence \(\varphi\in\calh\). This means
      \begin{equation*}
        \fA_1\models\varphi \quad\text{ and }\quad\fA_2\models\neg\varphi
      \end{equation*}
   #+END_lemma

   #+BEGIN_proof
   \(2\to1\). For any model \(\fA_1\) of \(T_1\) let \(\calh_{\fA_1}\) be the
   set of all sentences from \(\calh\) which are true in \(\fA_1\). (2) implies
   that \(\calh_{\fA_1}\) and \(T_2\) cannot have a common model. By the
   Compactness Theorem there is a finite conjunction \(\varphi_{\fA_1}\) of
   sentences from \(\calh_{\fA_1}\) inconsistent with \(T_2\). Clearly
   \begin{equation*}
    T_1\cup\{\neg\varphi_{\fA_1}\mid\fA_1\models T_1\}
   \end{equation*}
   is inconsistent. Again by compactness \(T_1\) implies a disjunction \varphi of
   finitely many of the \(\varphi_{\fA_1}\)
   #+END_proof

   For structures \(\fA,\fB\) and a map \(f:A\to B\) preserving all formulas
   from a set of formulas \Delta, we use the notation
   \begin{equation*}
   f:\fA\to_\Delta\fB
   \end{equation*}
   We also write
   \begin{equation*}
   \quad\fA\Rightarrow_\Delta\fB
   \end{equation*}
   to express that all sentences from \Delta true in \(\fA\) are also true in \(\fB\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.1.2
   Let \(T\) be a theory, \(\fA\) a structure and \Delta a set of formulas, closed
   under existential quantification, conjunction and substitution of variables.
   Then the following are equivalent
   1. All sentences \(\varphi\in\Delta\) which are true in \(\fA\) are
      consistent with \(T\) (There is a model \(\fB\models\Th_\Delta(\fA_A)\cup T\) and \(\fA\Rightarrow_\Delta\fB\))
   2. There is a model \(\fB\models T\) and a map \(f:\fA\to_\Delta\fB\)
   #+END_lemma

   #+BEGIN_proof
   \(1\to2\). Consider \(\Th_\Delta(\fA_A)\), the set of all sentences
   \(\delta(\bbar{a})\)
   (\(\delta(\bbar{x})\in\Delta\)), which are true in \(\fA_A\). The models
   \((\fB,f(a)_{a\in A})\) of this theory correspond to maps
   \(f:\fA\to_\Delta\fB\). *This means that we have to find a model of*
   \(T\cup\Th_\Delta(\fA_A)\). To show finite satisfiability it is enough to
   show that \(T\cup D\) is consistent for every finite subset \(D\) of
   \(\Th_\Delta(\fA_A)\). Let \(\delta(\bbar{a})\) be the conjunction of the elements
   of \(D\). Then \(T\) has a model   \(\fB\) which is also a model of \(\varphi=\exists\bbar{x}\delta(\bbar{x})\)
   #+END_proof

   Lemma ref:lemma3.1.2 applied to \(T=\Th(\fB)\) shows that
   \(\fA\Rightarrow_\Delta\fB\) iff there exists a map \(f\) and a structure
   \(\fB'\equiv\fB\) s.t. \(f:\fA\to_\Delta\fB'\)

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.3
   Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
   1. There is a universal sentence which separates \(T_1\) from \(T_2\)
   2. No model of \(T_2\) is a substructure of a model of \(T_1\)
   #+END_theorem

   #+BEGIN_proof
   \(2\to1\). If \(T_1\) and \(T_2\) cannot be separated by a universal
   sentence, then they have models \(\fA_1\) and \(\fA_2\) which cannot be separated
   by a universal sentence. This can be denoted by
   \begin{equation*}
   \fA_2\Rightarrow_\exists\fA_1
   \end{equation*}
   Now Lemma ref:lemma3.1.2 implies that \(\fA_2\) there is a map
   \(\fA_2\to_\exists\fA_1'\) where \(\fA_1'\models T_1\)
  . Hence \(\fA_2\) has an extension \(\fA_2'\) s.t. \(\fA_2'\equiv\fA_1'\).
  Then \(\fA'\) is gain a model of \(T_1\) contradicting (2)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any \(L\)-theory \(T\), the formulas \(\varphi(\bbar{x}),\psi(\bbar{x})\) are said
   to be *equivalent* modulo \(T\) (or relative to \(T\)) if \(T\models\forall\bbar{x}(\varphi(\bbar{x})\leftrightarrow\psi(\bbar{x}))\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor3.1.5
   Let \(T\) be a theory
   1. Consider a formula \(\varphi(x_1,\dots,x_n)\). The following are equivalent
      1. \(\varphi(x_1,\dots,x_n)\) is, modulo \(T\), equivalent to a universal formula
      2. If \(\fA\subseteq\fB\) are models of \(T\) and \(a_1,\dots,a_n\in A\),
         then \(\fB\models\varphi(a_1,\dots,a_n)\) implies \(\fA\models\varphi(a_1,\dots,a_n)\)
   2. We say that a theory which consists of universal sentences is universal.
      Then \(T\) is equivalent to a universal theory iff all substructures of
      models of \(T\) are again models of \(T\)
   #+END_corollary

   #+BEGIN_proof
   1. Assume (2). We extend \(L\) by an \(n\)-tuple \(\bbar{c}\) of new
      constants \(c_1,\dots,c_n\) and consider theory
      \begin{equation*}
      T_1=T\cup\{\varphi(\bbar{c})\}\quad\text{ and }\quad
      T_2=T\cup\{\neg\varphi(\bbar{c})\}
      \end{equation*}
      Then (2) says the substructures of models of \(T_1\) cannot be models of
      \(T_2\). By Theorem ref:thm3.1.3 \(T_1\) and \(T_2\) can be separated by a
      universal \(L(\bbar{c})\)-sentence \(\psi(\bbar{c})\). By Lemma
      ref:lemma1.3.4, \(T_1\models\psi(\bbar{c})\) implies
      \begin{equation*}
      T\models\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))
      \end{equation*}
      and from \(T_2\models\neg\psi(\bbar{c})\) we see
      \begin{equation*}
      T\models\forall\bbar{x}(\neg\varphi(\bbar{x})\to\neg\psi(\bbar{x}))
      \end{equation*}
   2. Suppose a theory \(T\) has this property. Let \varphi be an axiom of \(T\). If
      \(\fA\) is a substructure of \(\fB\), it is not possible for \(\fB\) to be
      a model of \(T\) and for \(\fA\) to be a model of \(\neg\psi\) at the same
      time. By Theorem ref:thm3.1.3 there is a universal sentence \psi with
      \(T\models\psi\) and \(\neg\varphi\models\neg\psi\). Hence all axioms of
      \(T\) follow from
      \begin{equation*}
      T_\forall=\{\psi\mid T\models\psi,\psi\text{ universal}\}
      \end{equation*}
   #+END_proof

   An \(\forall\exists\)-formula is of the form
   \begin{equation*}
   \forall x_1\dots x_n\psi
   \end{equation*}
   where \psi is existential
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose \varphi is an \(\forall\exists\)-sentence, \((\fA_i)_{i\in I}\) is a
   directed family of models of \varphi and \(\fB\) the union of the \(\fA_i\). Then
   \(\fB\) is also a model of \varphi.
   #+END_lemma

   #+BEGIN_proof
   Write
   \begin{equation*}
   \varphi=\forall\bbar{x}\psi(\bbar{x})
   \end{equation*}
   where \psi is existential. For any \(\bbar{a}\in B\) there is an \(A_i\)
   containing \(\bbar{a}\), clearly \(\psi(\bbar{a})\) holds in \(\fA_i\). As
   \(\psi(\bbar{a})\) is existential it must also hold in \(\fB\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We call a theory \(T\) *inductive* if the union of any directed family of
   models of \(T\) is again a model
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.8
   Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
   1. there is an \(\forall\exists\)-sentence which separates \(T_1\) and \(T_2\)
   2. No model of \(T_2\) is the union of a chain (or of a directed family) of
      models of \(T_1\)
   #+END_theorem


   #+BEGIN_proof
   \(2\to1\). If (1) is not true, \(T_1,T_2\) have models which cannot be
   separated by an \(\forall\exists\)-sentence. Since
   \(\exists\forall\)-formulas are equivalent to negated
   \(\forall\exists\)-formulas (since \(\forall\) is too strong), we have
   \begin{equation*}
   \fB^0\Rightarrow_{\exists\forall}\fA
   \end{equation*}
   By Lemma ref:lemma3.1.2 there is a map
   \begin{equation*}
   f:\fB^0\to_{\forall}\fA^0
   \end{equation*}
   with \(\fA^0\equiv\fA\) (since \(\fB^0\to_{\exists\forall}\fA^0\)). We can assume that\(\fB^0\subseteq\fA^0\) and \(f\)
   is the inclusion map. Then
   \begin{equation*}
   \fA_B^0\Rightarrow_{\exists}\fB^0_B
   \end{equation*}

   Applying Lemma ref:lemma3.1.2 again, we obtain an extension \(\fB_B^1\) of
   \(\fA_B^0\) with \(\fB_B^1\equiv\fB_B^0\), i.e. \(\fB^0\prec\fB^1\). Hence we
   have an infinite chain
   \begin{gather*}
   \fB^0\subseteq\fA^0\subseteq^1\fB^1\subseteq\fA^1\subseteq\fB^2\subseteq\cdots\\
   \fB^0\prec\fB^1\prec\fB^2\prec\cdots\\
   \fA^i\equiv\fA
   \end{gather*}
   Let \(\fB\) be the union of the \(\fA^i\).  Since \(\fB\) is also the union
   of the elementary chain of the \(\fB^i\), it is an elementary extension of
   \(\fB^0\) and hence a model of \(T_2\). But the \(\fA^i\) are models of
   \(T_1\), so (2) does not hold
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(T\) be a theory
   1. For each sentence \varphi the following are equivalent
      1. \varphi is, modulo \(T\), equivalent to an \(\forall\exists\)-sentence
      2. If
         \begin{equation*}
         \fA^0\subseteq\fA^1\subseteq\cdots
         \end{equation*}
         and their union \(\fB\) are models of \(T\), then \varphi holds in \(\fB\) if
         it is true in all the \(\fA^i\)
   2. \(T\) is inductive iff it can be axiomatised by \(\forall\exists\)-sentences
   #+END_corollary

   #+BEGIN_proof
   1. Theorem ref:thm3.1.8 shows that \(\forall\exists\)-formulas are preserved
      by unions of chains. Hence (a)\(\Rightarrow\)(b). For the converse
      consider the theories
      \begin{equation*}
      T_1=T\cup\{\varphi\} \quad\text{ and }\quad T_2=T\cup\{\neg\varphi\}
      \end{equation*}
      Part (b) says that the union of a chain of models of \(T_1\) cannot be a
      model of \(T_2\). By Theorem ref:thm3.1.8 we can separate \(T_1\) and
      \(T_2\) by an \(\forall\exists\)-sentence \psi. Hence
      \(T\cup\{\varphi\}\models\psi\) and
      \(T\cup\{\neg\varphi\}\models\neg\psi\)
   2. Clearly \(\forall\exists\)-axiomatised theories are inductive. For the
      converse assume that \(T\) is inductive and \varphi is an axiom of \(T\). If
      \(\fB\) is a union of models of \(T\), it cannot be a model of
      \(\neg\varphi\). By Theorem ref:thm3.1.8 there is an
      \(\forall\exists\)-sentence \psi with \(T\models\psi\) and
      \(\neg\varphi\models\neg\psi\). Hence all axioms of \(T\) follows from
      \begin{equation*}
      T_{\forall\exists}=\{\psi\mid T\models\psi,\psi\text{ $\forall\exists$-formula}\}
      \end{equation*}
   #+END_proof
** Quantifier elimination
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A theory \(T\) has *quantifier elimination* if every \(L\)-formula
   \(\varphi(x_1,\dots,x_n)\) in the theory is equivalent modulo \(T\) to some
   quantifier-free formula \(\rho(x_1,\dots,x_n)\)
   #+END_definition

   It's easy to transform any theory \(T\) into a theory with quantifier
   elimination if one is willing to expand the language: just enlarge \(L\) by
   adding an \(n\)-place relation symbol \(R_{\varphi}\) for every \(L\)-formula
   \(\varphi(x_1,\dots,x_n)\) and \(T\) by adding all axioms
   \begin{equation*}
   \forall x_1,\dots,x_n(R_\varphi(x_1,\dots,x_n)\leftrightarrow\varphi(x_1,\dots,x_n))
   \end{equation*}
   The resulting theory, the *Morleyisation* \(T^m\) of \(T\), has quantifier
   elimination

   A *prime structure* of \(T\) is a structure which embeds into all models of
   \(T\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   A consistent theory \(T\) with quantifier elimination which posseses a prime
   structure is complete
   #+END_lemma

   #+BEGIN_proof
   If \(\fM,\fN\models T\) and \(\fM\models\varphi\) and
   \(\fN\models\neg\varphi\). The prime structure is \(\fH\). Then we have
   \(h_1:\fH\to\fM\) and \(h_2:\fH\to\fN\). If \varphi doesn't contain existential
   quantification, then there is a contradiction.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *simple existential formula* has the form
   \begin{equation*}
   \varphi=\exists y\rho
   \end{equation*}
   for a quantifier-free formula \rho. If \rho is a conjunction of basic formulas, \varphi
   is called *primitive existential*
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.2.4
   The theory \(T\) has quantifier elimination iff every primitive existential
   formula is, modulo \(T\), equivalent to a quantifier-free formula
   #+END_lemma

   #+BEGIN_proof
   We can write every simple existential formula in the form \(\exists
   y\bigvee_{i<n}\rho_i\) for \(\rho_i\) which are conjunctions of basic
   formulas. This shows that every simple existential formula is equivalent to a
   disjunction of primitive existential formulas, namely to
   \(\bigvee_{i<n}(\exists y\rho_i)\). We can therefore assume that every simple
   existential formula is, modulo \(T\), equivalent to a quantifier-free formula

   We are now able to eliminate the quantifiers in arbitrary formulas in prenex
   normal form (Exercise ref:ex1.2.3)
   \begin{equation*}
   Q_1x_1\dots Q_nx_n\rho
   \end{equation*}
   if \(Q_n=\exists\), we choose a quantifier-free formula \(\rho_0\) which,
   modulo \(T\), is equivalent to \(\exists x_n\rho\) and proceed with the
   formula \(Q_1x_1\dots Q_{n-1}x_{n-1}\rho_0\). If \(Q_n=\forall\), we
   find a quantifier-free \(\rho_1\) which is, modulo \(T\), equivalent to
   \(\exists x_n\neg\rho\) and proceed with \(Q_1x_1\dots Q_{n-1}x_{n-1}\neg\rho_1\)
   #+END_proof
   

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.2.5
   For a theory \(T\) the following are equivalent
   1. \(T\) has quantifier elimination
   2. For all models \(\fM^1\) and \(\fM^2\) of \(T\) with a common substructure
      \(\fA\) we have
      \begin{equation*}
      \fM_A^1\equiv\fM_A^2
      \end{equation*}
   3. For all models \(\fM^1\) and \(\fM^2\) of \(T\) with a common substructure
      \(\fA\) and for all primitive existential formulas \(\varphi(x_1,\dots,x_n)\)
      and parameter \(a_1,\dots,a_n\) from \(A\) we have
      \begin{equation*}
      \fM^1\models\varphi(a_1,\dots,a_n)\Rightarrow\fM^2\models\varphi(a_1,\dots,a_n)
      \end{equation*}
      (this is exactly the equivalence relation)

   If \(L\) has no constants, \(\fA\) is allowed to be the empty "structure"
   #+END_theorem

   #+BEGIN_proof
   \(3\to1\). Let \(\varphi(\bbar{x})\) be a primitive existential formula. In order
   to show that \(\varphi(\bbar{x})\) is equivalent, modulo \(T\), to a
   quantifier-free formula \(\rho(\bbar{x})\) we extend \(L\) by an \(n\)-tuple
   \(\bbar{c}\) of new constants \(c_1,\dots,c_n\). *We have to show that we can*
   *separate \(T\cup\{\varphi(\bbar{c})\}\) and \(T\cup\{\neg\varphi(\bbar{c})\}\) by a*
   *quantifier free sentence \(\rho(\bbar{c})\)*. We apply the Separation Lemma
   (\(\calh\) hear is the set of quantifier-free sentence). Let
   \(\fM^1\) and \(\fM^2\) be two models of \(T\) with two distinguished
   \(n\)-tuples \(\bbar{a}^1\) and \(\bbar{a}^2\). Suppose that
   \((\fM^1,\bbar{a}^1)\) and \((\fM^2,\bbar{a}^2)\) satisfy the same
   quantifier-free \(L(\bbar{c})\)-sentences. We have to show that
   \begin{equation*}
   \fM^1\models\varphi(\bbar{a}^1)\Rightarrow
   \fM^2\models\varphi(\bbar{a}^2)
   \end{equation*}
   then there is no \(L(\bbar{c})\)-sentence that can separate the models of
   \(T\cup\{\varphi(\bbar{c})\}\) and the models of \(T\cup\{\neg\varphi(\bbar{c})\}\)
   Consider the substructure \(\fA^i=\la\bbar{a}^i\ra^{\fM^i}\), generated by
   \(\bbar{a}^i\). If we can show that there is an isomorphism
   \begin{equation*}
   f:\fA^1\to\fA^2
   \end{equation*}
   taking \(\bbar{a}\) to \(\bbar{a}\), we may assume that \(\fA^1=\fA^2=\fA\)
   and \(\bbar{a}^1=\bbar{a}^2=\bbar{a}\).

   Every element of \(\fA^1\) has the form \(t^{\fM^1}[\bbar{a}^1]\) for an
   \(L\)-term \(t(\bbar{x})\). The isomorphism \(f\)to be constructed must
   satisfy
   \begin{equation*}
   f(t^{\fM^1}[\bbar{a}^1])=t^{\fM^2}[\bbar{a}^2]
   \end{equation*}
   We define \(f\) by this equation and have to check that \(f\) is well defined
   and injective. Assume
   \begin{equation*}
   s^{\fM^1}[\bbar{a}^1]=t^{\fM^1}[\bbar{af^1}]
   \end{equation*}
   Then \(\fM^1,\bbar{a}^1\models s(\bbar{c})\dot{=}t(\bbar{c})\), and by out
   assumption it also holds in \((\fM^2,\bbar{a}^2)\), which means
   \begin{equation*}
   s^{\fM^2}[\bbar{a}^2]=t^{\fM^2}[\bbar{a}^2]
   \end{equation*}
   Swapping the two sides yields injectivity.

   Surjectivity is clear. It remains to show that \(f\) commutes with the
   interpretation of the relation symbols. Now
   \begin{equation*}
   \fM^1\models R\left[t_1^{\fM^1}[\bbar{a}^1],\dots,t_m^{\fM^1}[\bbar{a}^1]\right]
   \end{equation*}
   is equivalent to \((\fM^1,\bbar{a}^1)\models
   R(t_1(\bbar{c}),\dots,t_m(\bbar{c}))\), which is equivalent to
   \((\fM^2,\bbar{a}^2)\models
   R(t_1(\bbar{c}),\dots,t_m(\bbar{c}))\), which in turn is equivalent to
   \begin{equation*}
   \fM^2\models R\left[t_1^{\fM^2}[\bbar{a}^2],\dots,t_m^{\fM^2}[\bbar{a}^2]\right]
   \end{equation*}
   #+END_proof

   Note that (2) of Theorem ref:thm3.2.5 is saying that \(T\) is *substructure
   complete*; i.e., for any model \(\fM\models T\) and substructure
   \(\fA\subseteq\fM\) the theory \(T\cup\Diag(\fA)\) is complete

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We call \(T\) *model complete* if for all models \(\fM^1\) and \(\fM^2\) of
   \(T\)
   \begin{equation*}
   \fM^1\subseteq\fM^2\Rightarrow\fM^1\prec\fM^2
   \end{equation*}
   #+END_definition

   \(T\) is model complete iff for any \(\fM\models T\) the theory
   \(T\cup\Diag(\fM)\) is complete

   #+ATTR_LATEX: :options [Robinson's Test]
   #+BEGIN_lemma
   Let \(T\) be a theory. Then the following are equivalent
   1. \(T\) is model complete
   2. For all models \(\fM^1\subseteq\fM^2\) of \(T\) and all existential
      sentences \varphi from \(L(M^1)\)
      \begin{equation*}
      \fM^2\models\varphi\Rightarrow\fM^1\models\varphi
      \end{equation*}
   3. Each formula is, modulo \(T\), equivalent to a universal formula
   #+END_lemma

   #+BEGIN_proof
   \(1\leftrightarrow3\). Corollary ref:cor3.1.5

   (2) implies that every existential formula is, modulo \(T\), equivalent to a
   universal formula
   #+END_proof

   If \(\fM^1\subseteq\fM^2\) satisfies (2), we call \(\fM^1\) *existentially
   closed* in \(\fM^2\). We denote this by
   \begin{equation*}
   \fM^1\prec_1\fM^2
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(T\) be a theory. A theory \(T^*\) is a *model companion* of \(T\) if the
   following three conditions are satisfied
   1. Each model of \(T\) can be extended to a model of \(T^*\)
   2. Each model of \(T^*\) can be extended to a model of \(T\)
   3. \(T^*\) is model complete
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.2.9
   A theory \(T\) has, up to equivalence, at most one model companion \(T^*\)
   #+END_theorem

   #+BEGIN_proof
   If \(T^+\) is another model companion of \(T\), every model of \(T^+\) is
   contained in a model of \(T^*\) and conversely. Let \(\fA^0\models T^+\) .
   Then \(\fA_0\) can be embedded in a model \(\fB_0\) of \(T^*\). In turn
   \(\fB_0\) is contained in a model \(\fA^1\) of \(T^+\). In this way we find
   two elementary chains \((\fA_i)\) and \((\fB_i)\), which have a common union
   \(\fC\). Then \(\fA_0\prec\fC\) and \(\fB_0\prec\fC\) implies
   \(\fA_0\equiv\fB_0\) since \(T\) are all sentences. Thus \(\fA_0\) is a model of \(T^*\)
   #+END_proof
*** Existentially closed structures and the Kaiser hull
    Let \(T\) be an \(L\)-theory. It follows from ref:lemma3.1.2 that the models
    of \(T_\forall\) are the substructures of models of \(T\). The conditions
    (1) and (2) in the definition of "model companion" can therefore be
    expressed as
    \begin{equation*}
    T_{\forall}=T_{\forall}^*
    \end{equation*}
    Hence the model companion of a theory \(T\) depends only on \(T_{\forall}\).
    (Note that \(T_{\forall}\) is model complete)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An \(L\)-structure \(\fA\) is called *\(T\)-existentiallay closed* (or
    *\(T\)-ec*) if
    1. \(\fA\) can be embedded in a model of \(T\)
    2. \(\fA\) is existentially closed in every extension which is a model of \(T\)
    #+END_definition

    A structure \(\fA\) is \(T\)-ec exactly if it is \(T_{\forall}\)-ec. Since
    every model of \(\fB\) of \(T_{\forall}\) can be embedded in a model \(\fM\)
    of \(T\) and \(\fA\subseteq\fB\subseteq\fM\) and \(\fA\prec_1\fM\) implies \(\fA\prec_1\fB\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.2.11
    Every model of a theory \(T\) can be embedded in a \(T\)-ec structure
    #+END_lemma

    #+BEGIN_proof
    Let \(\fA\) be a model of \(T_{\forall}\). We choose an enumeration
    \((\varphi_\alpha)_{\alpha<\kappa}\) of all existential \(L(A)\)-sentences and
    construct an ascending chain \((\fA_\alpha)_{\alpha\le\kappa}\) of models of
    \(T_{\forall}\). We begin with \(\fA_0=\fA\). Let \(\fA_\alpha\) be
    constructed. If \(\varphi_\alpha\) holds in an extension of \(\fA_\alpha\)
    which is a model of \(T\) we let \(\fA_{\alpha+1}\) be such a model.
    Otherwise we set \(\fA_{\alpha+1}=\fA_{\alpha}\). For limit ordinals \lambda we define
    \(\fA_\lambda\) to be the union of all \(\fA_\alpha\). \(\fA_\lambda\) is
    again a model of \(T_{\forall}\)
    #+END_proof

    Every elementary substructure \(\fN\) of a \(T\)-ec structure \(\fM\) is
    again \(T\)-ec. Let \(\fN\subseteq\fA\) be a model of \(T\). Since
    \(\fM_N\Rightarrow_{\exists}\fA_N\), there is an embedding of \(\fM\) in an
    elementary extension \(\fB\) of \(\fA\) which is the identity on \(N\).
    Since \(\fM\) is existentially closed in \(\fB\), it follows that \(\fN\) is
    existentially closed in \(\fB\) and therefore also in \(\fA\)

    \begin{center}\begin{tikzcd}
    &\fB&\\
    \fA\arrow[ur,"\prec"]&&\fM\arrow[ul,"\prec_1"']\\
    &\fN\arrow[ul,"\prec_1"]\arrow[ur,"\prec"']&
    \end{tikzcd}\end{center}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(T\) be a theory. Then there is a biggest inductive theory \(T^{\KH}\)
    with \(T_{\forall}=T_{\forall}^{\KH}\). We call \(T^{\KH}\) the *Kaiser hull*
    of \(T\)
    #+END_lemma

    #+BEGIN_proof
    Let \(T^1\) and \(T^2\) be two inductive theories with
    \(T_{\forall}^1=T_{\forall}^2=T_{\forall}\). We have to show that \((T^1\cup
    T^2)_\forall=T_\forall\).  Let \(\fM\) be a model of \(T\), as in the proof
    of ref:thm3.2.9 we extend \(\fM\) by a chain
    \(\fA_0\subseteq\fB_0\subseteq\fA_1\subseteq\fB_1\subseteq\cdots\) of models
    of \(T^1\) and \(T^2\). The union of this chain is a model of \(T^1\cup
    T^2\)

    (Both of \(T_{\forall}^1\) and \(T_{\forall}^2\) and model companion and
    hence equivalent)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.2.13
    The Kaiser hull \(T^{KH}\) is the \(\forall\exists\)-part of the theory of
    all \(T\)-ec structures
    #+END_lemma

    #+BEGIN_proof
    Let \(T^*\) be the \(\forall\exists\)-part of the theory of all \(T\)-ec
    structures. Since \(T\)-ec structures are models of \(T_{\forall}\), we have
    \(T_\forall\subseteq T^*_\forall\). It follows from ref:lemma3.2.11 that
    \(T_\forall^*\subseteq T_\forall\). Hence \(T^*\) is contained in the Kaiser Hull.
    #+END_proof

    This implies that \(T\)-ec strctures are models of \(T_{\forall\exists}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any theory \(T\) the following are equivalent
    1. \(T\) has a model companion \(T^*\)
    2. All models of \(K^{\KH}\) are \(T\)-ec
    3. The \(T\)-ec structures form an elementary class.


    If \(T^*\) exists, we have
    \begin{equation*}
    T^*=T^{\KH}=\text{ theory of all $T$-ec structures}
    \end{equation*}
    #+END_theorem


    #+BEGIN_exercise
    label:ex3.2.1
    Let \(L\) be the language containing a unary function \(f\) and a binary
    relation symbol \(R\) and consider the \(L\)-theory \(T=\{\forall x\forall
    y(R(x,y)\to (R(x,f(y))))\}\). Showing the follow
    1. For any \(T\)-structure \(\fM\) and \(a,b\in M\) with
       \(b\not\in\{a,f^{\fM}(a),(f^{\fM})^2(a),\dots\}\) we have
       \(\fM\models\exists z(R(z,a)\wedge\neg R(z,b))\)
    2. Let \(\fM\) be a model of \(T\) and \(a\) an element of \(M\) s.t.
       \(\{a,f^{\fM}(a),(f^{\fM})^2(a),\dots\}\) is infinite. Then in an
       elementary extension \(\fM'\) there is an element \(b\) with
       \(\fM'\models\forall z(R(z,a)\to R(z,b))\)
    3. The class of \(T\)-ec structures is not elementary, so \(T\) does not
       have a model companion
    #+END_exercise

    #+BEGIN_exercise
    label:ex3.2.3
    A theory \(T\) with quantifier elimination is axiomatisable by sentences of
    the form
    \begin{equation*}
    \forall x_1\dots x_n\psi
    \end{equation*}
    where \psi is primitive existential formula
    #+END_exercise
** Examples
   *Infinite sets*. The models of the theory  \(\Infset\) of *infinite sets* are all
   infinite sets without additional structure. The language \(L_{\emptyset}\) is
   empty, the axioms are (for \(n=1,2,\dots\))
   * \(\exists x_0\dots x_{n-1}\bigwedge_{i<j<n}\neg x_i\dot{=}x_j\)

     #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The theory \(\Infset\) of infinite sets has quantifier elimination and is complete
   #+END_theorem

   #+BEGIN_proof
   Since the language is empty, the only basic formula is \(x_i=x_j\) and
   \(\neg(x_i=x_j)\). By Lemma ref:lemma3.2.5 we only need to consider primitive
   existential formulas. 
   #+END_proof

   *Dense linear orderings*.
   \begin{align*}
   &\forall a,b(a\le b\wedge b\le a\to a\dot{=}b)\\
   &\forall a,b,c(a\le b\wedge b\le c\to a\le c)\\
   &\forall a,b(a\le b\vee b\le a)\\
   &\forall a,b\exists c(a< b\to a< c< b)
   \end{align*}
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   \(\DLO\) has quantifier elimination
   #+END_theorem

   #+BEGIN_proof
   Let \(A\) be a finite common substructure of the two models \(O_1\) and
   \(O_2\). We choose an ascending enumeration \(A=\{a_1,\dots,a_n\}\). Let
   \(\exists y\rho (y)\) be a simple existential \(L(A)\)-sentence, which is
   true in \(O_1\) and assume \(O_1\models\rho(b_1)\). We want to extend the
   order preserving map \(a_i\mapsto a_i\) to an order preserving map
   \(A\cup\{b_1\}\to O_2\). For this we have an image \(b_2\) of \(b_1\). There
   are four cases
   1. \(b_1\in A\), we set \(b_2=b_1\)
   2. \(b_1\in(a_i,a_{i+1})\). We choose \(b_2\) in \(O_2\) with the same property
   3. \(b_1\) is smaller than all elements of \(A\). We choose a \(b_2\in O_2\)
      of the same kind
   4. \(b_1\) is bigger than all \(a_i\). Choose \(b_2\) in the same manner


   This defines an isomorphism \(A\cup\{b_1\}\to A\cup\{b_2\}\), which show that \(O_2\models\rho(b_2)\)
   #+END_proof

   *Modules*. Let \(R\) be a (possibly non-commutative) ring with 1. An
   \(R\)-module
   \begin{equation*}
   \fM=(,0,+,-,r)_{r\in R}
   \end{equation*}
   is an abelian group \((M,0,+,-)\) together with operations \(r:M\to M\) for
   every ring element \(r\in R\). We formulate the axioms in the language
   \(L_{Mod}(R)=L_{AbG}\cup\{r\mid r\in R\}\). The theory \(\sfMod(R)\) of
   \(R\)-modules consists of
   \begin{align*}
   &\AbG\\
   &\forall x,y\; r(x+y)\dot{=}rx+ry\\
   &\forall x\;(r+s)x\dot{=}rx+sx\\
   &\forall x\;(rs)x\dot{=}r(sx)\\
   &\forall x\;1x\dot{=}x
   \end{align*}
   for all \(r,s\in R\). Then \(\Infset\cup\sfMod(R)\) is the theory of all
   infinite \(R\)-modules

   A module over fields is a vector space

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \(K\) be a field. Then the theory of all infinite \(K\)-vector spaces has
   quantifier elimination and is complete
   #+END_theorem

   #+BEGIN_proof
   Let \(A\) be a common finitely generated substructure (i.e., a subspace) of
   the two infinite \(K\)-vector spaces \(V_1\) and \(V_2\). Let \(\exists
   y\rho(y)\) be a simple existential \(L(A)\)-sentence which holds in \(V_1\).
   Choose a \(b_1\) from \(V_1\) which satisfies \(\rho(y)\). If \(b_1\) belongs to
   \(A\), we finished. If not, we choose a \(b_2\in V_2\setminus A\). Possibly
   we have to replace \(V_2\) by an elementary extension. The vector spaces
   \(A+Kb_1\) and \(A+Kb_2\) are isomorphic by an isomophism which maps \(b_1\)
   to \(b_2\) and fixes \(A\) elementwise. Hence \(V_2\models\rho(b_2)\)

   The theory is complete since a quantifier-free sentence is true in a vector
   space iff it is true in the zero-vector space.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An *equation* is an \(L_{Mod}(R)\)-formula \(\gamma(\bbar{x})\) of the form
   \begin{equation*}
   r_1x_1+\dots+r_mx_m=0
   \end{equation*}
   A *positive primitive* formula (*pp*-formula) is of the form
   \begin{equation*}
   \exists\bbar{y}(\gamma_1\wedge\dots\wedge\gamma_n)
   \end{equation*}
   where the \(\gamma_i(\bbar{xy})\) are equations
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For every ring \(R\) and any \(R\)-module \(M\), every \(L_{Mod}(R)\)-formula
   is equivalent (modulo the theory of \(M\)) to a Boolean combination of
   positive primitive formulas
   #+END_theorem

   *Algebraically closed fields*.
   #+ATTR_LATEX: :options [Tarski]
   #+BEGIN_theorem
   The theory \(\sfACF\) of algebraically closed fields has quantifier elimination
   #+END_theorem

   #+BEGIN_proof
   Let \(K_1\) and \(K_2\) be two algebraically closed fields and \(R\) a common
   subring. Let \(\exists y\rho(y)\) be a simple existential sentence with
   parameters in \(R\) which hold in \(K_1\). We have to show that \(\exists
   y\rho(y)\) is also true in \(K_2\).

   Let \(F_1\) and \(F_2\) be the quotient fields of \(R\) in \(K_1\) and
   \(K_2\), and let \(f:F_1\to F_2\) be an isomorphism which is the identity on
   \(R\). Then \(f\) extends to an isomorphism \(g:G_1\to G_2\) between the
   relative algebraic closures \(G_i\) of \(F_i\) in \(K_i\).
   #+END_proof
* Countable Models
** The omitting types theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(T\) be an \(L\)-theory and \(\Sigma(x)\) a set of \(L\)-formulas. A model
   \(\fA\) of \(T\) not realizing \(\Sigma(x)\) is said to *omit* \(\Sigma(x)\). A
   formula \(\varphi(x)\) *isolates* \(\Sigma(x)\) if
   1. \(\varphi(x)\) is consistent with \(T\)
   2. \(T\models\forall x(\varphi(x)\to\sigma(x))\) for all \(\sigma(x)\in\Sigma(x)\)
   #+END_definition

   A set of formulas is often called a *partial type*.

   #+ATTR_LATEX: :options [Omitting Types]
   #+BEGIN_theorem
   If \(T\) is countable and consistent and if \(\Sigma(x)\) is not isolated in
   \(T\), then \(T\) has a model which omits \(\Sigma(x)\)
   #+END_theorem

   If \(\Sigma(x)\) is isolated by \(\varphi(x)\) and \(\fA\) is a model of \(T\), then
   \(\Sigma(x)\) is realised in \(\fA\) by all realisations \(\varphi(x)\). Therefore the
   converse of the theorem is true for *complete* theories \(T\): if \(\Sigma(x)\) is
   isolated in \(T\), then it is realised in every model of \(T\) 
   
   #+BEGIN_proof
   We choose a countable set \(C\) of new constants and extend \(T\) to a theory
   \(T^*\) with the following properties
   1. \(T^*\) is a Henkin theory: for all \(L(C)\)-formulas \(\psi(x)\) there
      exists a constant \(c\in C\) with \(\exists x\psi(x)\to\psi(c)\in T^*\)
   2. for all \(c\in C\) there is a \(\sigma(x)\in\Sigma(x)\) with \(\neg\sigma(c)\in
      T^*\)


   We construct \(T^*\) inductively as the union of an ascending chain
   \begin{equation*}
   T=T_0\subseteq T_1\subseteq T_1\subseteq\dots
   \end{equation*}
   of consistent extensions of \(T\) by finitely many axioms from \(L(C)\), in
   each step making an instance of (1) or (2) true.

   Enumerate \(C=\{c_i\mid i<\omega\}\) and let \(\{\psi_i(x)\mid i<\omega\}\)
   be an enumeration of the \(L(C)\)-formulas

   Assume that \(T_{2i}\) is the already constructed. Choose some \(c\in C\)
   which doesn't occur in \(T_{2i}\cup\{\psi_i(x)\}\) and set
   \(T_{2i+1}=T_{2i}\cup\{\exists x\psi_i(x)\to\psi_i(c)\}\).

   Up to equivalence \(T_{2i+1}\) has the form \(T\cup\{\delta(c_i,\bbar{c})\}\) for
   an \(L\)-formula \(\delta(x,\bbar{y})\) and a tuple \(\bbar{c}\in C\) which
   doesn't contain \(c_i\). Since \(\exists\bbar{y}\delta(x,\bbar{y})\) doesn't
   isolate \(\Sigma(x)\), for some \(\sigma\in\Sigma\) the formula
   \(\exists\bbar{y}\delta(x,\bbar{y})\wedge\neg\sigma(x)\) is consistent with \(T\).
   Thus \(T_{2i+2}=T_{2i+1}\cup\{\neg\sigma(c_i)\}\) is consistent

   Take a model \((\fA',a_c)_{c\in C}\) of \(T^*\). Since \(T^*\) is a Henkin
   theory, Tarski's Test ref:thm2.1.2 shows that \(A=\{a_c\mid c\in C\}\) is the
   universe of an elementary substructure \(\fA\) (Lemma ref:lemma2.2.3). By
   property (2), \(\Sigma(x)\) is omitted in \(\fA\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor4.1.3
   label:ex4.1.1
   Let \(T\) be countable and consistent and let
   \begin{equation*}
   \Sigma_0(x_0,\dots,x_{n_0}),\Sigma_1(x_1,\dots,x_{n_1}),\dots
   \end{equation*}
   be a sequence of partial types. If all \(\Sigma_i\) are not isolated, then
   \(T\) has a model which omits all \(\Sigma_i\)
   #+END_corollary

   #+BEGIN_proof
   
   If \(\Sigma_0(x),\Sigma_1(x),\dots\). Then
   \(T_{2i+2}=T_{2i+1}\cup\{\neg\sigma_m(c_{mn})\}\)

   If \(\Sigma(x_1,\dots,x_n)\), then
   \(T_{2i+1}=T_{2i}\cup\{\exists\bbar{x}\psi_i(\bbar{x})\to\psi_i(\bbar{c})\}\).

   Combine the two case
   #+END_proof
** The space of types
   Fix a theory \(T\). An *\(n\)-type* is a maximal set of formulas
   \(p(x_1,\dots,x_n)\) consistent with \(T\). We denote by \(S_n(T)\) the set
   of all \(n\)-types of \(T\). We also write \(S(T)\) for \(S_1(T)\).
   \(S_0(T)\) is all complete extensions of \(T\)

   If \(B\) is a subset of an \(L\)-structure \(\fA\), we recover
   \(S_n^{\fA}(B)\) as \(S_n(\Th(\fA_B))\). In particular, if \(T\) is complete
   and \(\fA\) is any model of \(T\), we have \(S^{\fA}(\emptyset)=S(T)\)

   For any \(L\)-formula \(\varphi(x_1,\dots,x_n)\), let \([\varphi]\) denote the set of all
   types containing \varphi.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. \([\varphi]=[\psi]\) iff \varphi and \psi are equivalent modulo \(T\)
   2. The sets \([\varphi]\) are closed under Boolean operations. In fact
      \([\varphi]\cap[\psi]=[\varphi\wedge\psi]\), \([\varphi]\cup[\psi]=[\varphi\vee\psi]\),
      \(S_n(T)\setminus[\varphi]=[\neg\varphi]\), \(S_n(T)=[\top]\) and \(\emptyset=[\bot]\)
   #+END_lemma

   It follows that the collection of sets of the form \([\varphi]\) is closed under
   finite intersection and includes \(S_n(T)\). So these sets form a basis of a
   topology on \(S_n(T)\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   The space \(S_n(T)\) is 0-dimensional and compact
   #+END_lemma

   #+BEGIN_proof
   Being 0-dimensional means having a basis of clopen sets. Our basic open sets
   are clopen since their complements are also basic open

   If \(p\) and \(q\) are two different types, there is a formula \varphi contained in
   \(p\) but not in \(q\). It follows that \([\varphi]\) and \([\neg\varphi]\) are
   open sets which separate \(p\) and \(q\). This shows that \(S_n(T)\) is
   Hausdorff

   Consider a family \([\varphi_i]\), with the finite intersection property.This
   means that \(\varphi_{i_i}\wedge\dots\wedge\varphi_{i_k}\) are consistent
   with \(T\). So Corollary ref:cor2.2.5 \(\{\varphi_i\mid i\in I\}\) is
   consistent with \(T\) and can be extended to a type \(p\), which then belongs
   to all \([\varphi_i]\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   All clopen subsets of \(S_n(T)\) has the form \([\varphi]\)
   #+END_lemma

   #+BEGIN_proof
   It follows from Exercise ref:ex4.1.1 that we can separate any two disjoint
   closed subsets of \(S_n(T)\) by a basic open set.
   #+END_proof

   The Stone duality theorem asserts that the map
   \begin{equation*}
   X\mapsto\{C\mid C\text{ clopen subset of }X\}
   \end{equation*}
   yields an equivalence between the category of 0-dimensional compact spaces
   and the category of Boolean algebras. The inverse map assigns to every
   Boolean algebra to its *Stone space*

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A map \(f\) from a subset of a structure \(\fA\) to a structure \(\fB\) is
   *elementary* if it preserves the truth of formulas; i.e., \(f:A_0\to B\) is
   elementary if for every formula \(\varphi(x_1,\dots,x_n)\) and \(\bbar{a}\in A_0\)
   we have
   \begin{equation*}
   \fA\models\varphi(\bbar{a})\Rightarrow\fB\models\varphi(f(\bbar{a}))
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(\fA\) and \(\fB\) be \(L\)-structures, \(A_0\) and \(B_0\) subsets of
   \(A\) and \(B\), respectively. Any elementary map \(A_0\to B_0\) induces a
   continuous surjective map \(S_n(B_0)\to S_n(A_0)\)
   #+END_lemma

   #+BEGIN_proof
   If \(q(x)\in S_n(B_0)\), we define
   \begin{equation*}
   S(f)(q)=\{\varphi(x_1,\dots,x_n,\bbar{a})\mid\bbar{a}\in A_0,\varphi(x_1,\dots,x_n,f(\bbar{a}))\in q\}
   \end{equation*}
   \(S(f)\) defines a map from \(S_n(B_0)\) to \(S_n(A_0)\). Moreover, it is
   surjective since
   \(\{\varphi(x_1,\dots,x_n,f(\bbar{a}))\mid\varphi(x_1,\dots,x_n,a)\in p\}\) is
   finitely satisfiable for all \(p\in S_n(A_0)\). And \(S(f)\) is continuous
   since \([\varphi[x_1,\dots,x_n,f(\bbar{a})]]\) is the preimage of
   \([\varphi(x_1,\dots,x_n,\bbar{a})]\) under \(S(f)\)
   #+END_proof

   There are two main cases
   1. An elementary bijection \(f:A_0\to B_0\) defines a homeomorphism
      \(S_n(A_0)\to S_n(B_0)\). We write \(f(p)\) for the image of \(p\)
   2. If \(\fA=\fB\) and \(A_0\subseteq B_0\), the inclusion map induces the
      *restriction* \(S_n(B_0)\to S_n(A_0)\). We write \(q\restriction A_0\) for
      the restriction of \(q\) to \(A_0\). We call \(q\) an extension of
      \(q\restriction A_0)\)

      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      A type \(p\) is isolated in \(T\) iff \(p\) is an isolated point in
      \(S_n(T)\). In fact, \varphi isolates \(p\) iff \([\varphi]=\{p\}\). That is, \([\varphi]\)
      is an *atom* in the Boolean algebra of clopen subsets of \(S_n(T)\)
      #+END_lemma

      #+BEGIN_proof
      If \varphi isolates \(p\). Then \(\varphi\in p\) and hence \([\varphi]=\{\varphi\}\).

      If \([\varphi]=\{p\}\), then \(\varphi\in p\). What's more,
      \(\fM\models\varphi\Leftrightarrow \fM\models p\) in \(T\)


      The set \([\varphi]\) is a singleton iff \([\varphi]\) is non-empty and cannot be
      divided into two non-empty clopen subsets \([\varphi\wedge\psi]\) and
      \(\varphi\wedge\neg\psi\). This means that for all \psi either \psi or
      \(\neg\psi\) follows from \varphi modulo \(T\). So \([\varphi]\) is a singleton iff \varphi
      generates the type
      \begin{equation*}
      \la\varphi\ra=\{\psi(\bbar{x})\mid T\models\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))\}
      \end{equation*}
      #+END_proof

      We call a formula \(\varphi(x)\) *complete* if
      \begin{equation*}
      \{\psi(\bbar{x})\mid T\models\forall\bbar{x}(\varphi(\bbar{x})\to\psi(\bbar{x}))\}
      \end{equation*}
      is a type.
      #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   A formula isolates a type iff it is complete
   #+END_corollary

   #+BEGIN_exercise
   label:ex4.2.2
   1. Closed subsets of \(S_n(T)\) have the form \(\{p\in
      S_n(T)\mid\Sigma\subseteq p\}\), where \Sigma is any set of formulas
   2. Let \(T\) be countable and consistent. Then any meagre[fn:1] subset \(X\)
      of \(S_n(T)\) can be omitted, i.e., there is a model which omits all
      \(p\in X\)
   #+END_exercise

   #+BEGIN_proof
   1. The sets \([\varphi]\) are a basis for the closed subsets of \(S_n(T)\). So the
      closed sets of \(S_n(T)\) are exactly the intersections
      \(\bigcap_{\varphi\in\Sigma}[\varphi]=\{p\in S_n(T)\mid\Sigma\subseteq p\}\)
   2. The set \(X\) is the union of a sequence of countable nowhere dense sets
      \(X_i\). We may assume that \(X_i\) are closed, i.e., of the form \(\{p\in
      S_n(T)\mid \Sigma_i\subseteq p\}\). That \(X_i\) has no interior means
      that \(\Sigma_i\) is not isolated. The claim follows now from Corollary ref:cor4.1.3
   #+END_proof
      

   [fn:1] A subset of a topological space is *nowhere dense* if its closure has no
   interior. A countable union of nowhere dense sets is meagre

   #+BEGIN_exercise
   label:ex4.2.3
   Consider the space \(S_\omega(T)\) of all complete types in variables
   \(v_0,v_1,\dots\). Note that \(S_\omega(T)\) is again a compact space and
   therefore not meagre by Baire's theorem
   1. Show that \(\{\tp(a_0,a_1,\dots)\mid\text{ the $a_i$ enumerate a model of
      }T\}\) is comeagre in \(S_\omega(T)\)
   #+END_exercise
** \(\aleph_0\)-categorical theories
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm4.3.1
   Let \(T\) be a countable complete theory. Then \(T\) is
   \(\aleph_0\)-categorical iff for every \(n\) there are only finitely many
   formulas \(\varphi(x_1,\dots,x_n)\) up to equivalence relative to \(T\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(L\)-structure \(\fA\) is *\(\omega\)-saturated* if all types over finite
   subsets of \(A\) are realised in \(\fA\)
   #+END_definition

   The types in the definition are meant to be 1-types. On the other hand, it is
   not hard to see that an \(\omega\)-saturated structure realises all
   \(n\)-types over finite sets (Exercise ref:ex4.3.9) for all \(n\ge1\). The
   following lemma is a generalisation of the \(\aleph_0\)-categoricity of \(\DLO\).

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Two elementarily equivalent, countable and \(\omega\)-saturated structures
   are isomorphic
   #+END_lemma

   #+BEGIN_proof
   Suppose \(\fA\) and \(\fB\) are as in the lemma. We choose enumerations
   \(A=\{a_0,a_1,\dots\}\) and \(B=\{b_0,b_1,\dots\}\). Then we construct an
   ascending sequence \(f_0\subseteq f_1\subseteq \cdots\) of finite elementary
   maps
   \begin{equation*}
   f_i:A_i\to B_i
   \end{equation*}
   between finite subsets of \(\fA\) and \(\fB\). We will choose the \(f_i\) in
   such a way that \(A\) is the union of the \(A_i\) and \(B\) the union of the
   \(B_i\). The union of the \(f_i\) is then the desired isomorphism between
   \(\fA\) and \(\fB\)

   The empty map \(f_0=\emptyset\) is elementary since \(\fA\) and \(\fB\) are
   elementarily equivalent. Assume that \(f_i\) is already constructed. There
   are two cases:
   #+END_proof

   

* TODO Don't understand
  Lemma ref:lemma3.2.13

  Exercise ref:ex3.2.3
  
