#+TITLE: Advanced Modern Algebra
#+AUTHOR: Joseph J. Rotman
#+OPTIONS: tex:imagemagick
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/AdvancedModernAlgebra/AdvancedModernAlgebra.tex
* Things Past
** Roots of Unity
   #+ATTR_LATEX: :options [Polar Decomposition]
   #+BEGIN_proposition
   Every complex number $z$ has a factorization
   \begin{equation*}
   z=r(\cos\theta+i\sin\theta)
   \end{equation*}
   where $r=\abs{z}\ge0$ and $0\le\theta\le 2\pi$
   #+END_proposition

   #+ATTR_LATEX: :options [Addition Theorem]
   #+BEGIN_proposition
   If $z=\cos\theta+i\sin\theta$ and $w=\cos\psi+i\sin\psi$, then
   \begin{equation*}
   zw=\cos(\theta+\psi)+i\sin(\theta+\psi)
   \end{equation*}
   #+END_proposition
   
   #+ATTR_LATEX: :options [De Moivre]
   #+BEGIN_theorem
   $\forall x\in\R,n\in\N$
   \begin{equation*}
   \cos(nx)+i\sin(nx)=(\cos x+i\sin x)^n
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options [Euler]
   #+BEGIN_theorem
   $e^{ix}=\cos x+i\sin x$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $n\in\N\ge 1$ , an \tf{nth root of unity} is a complex number $\xi$ with
   $\xi^n=1$

   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Every nth root of unity is equal to
   \begin{equation*}
   e^{2\pi ik/n}=\cos(\frac{2\pi k}{n})+i\sin(\frac{2\pi k}{n})
   \end{equation*}
   for $k=0,1,\dots,n-1$
   #+END_corollary

   \begin{equation*}
   x^n-1=\displaystyle\prod_{\xi^n=1}(x-\xi)
   \end{equation*}

   If $\xi$ is an nth root of unity and if $n$ is the smallest, then $\xi$ is a
   \tf{primitive } n\tf{th root of unity}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $d\in\N^+$ , then the $d$th \tf{cyclotomic polynomial} is 
   \begin{equation*}
   \Phi_d(x)=\displaystyle\prod(x-\xi)
   \end{equation*}
   where $\xi$ ranges over all the /primitive dth/ roots of unity
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   For every integer $n\ge 1$
   \begin{equation*}
   x^n-1=\displaystyle\prod_{d|n}\Phi_d(x)
   \end{equation*}
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Define \tf{Euler} \phi\tf{-function} as the degree of the nth cyclotomic
   polynomial
   \begin{equation*}
   \phi(n)=\deg(\Phi_n(x))
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $n\ge1$ is an integer, then $\phi(n)$ is the number of integers $k$ with
   $1\le k\le n$ and $(k,n)=1$
   #+END_proposition

   #+BEGIN_proof
   Suffice to prove $e^{2\pi ik/n}$ is a primitive nth root of unity if and only
   if $k$ and $n$ are relatively prime
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   For every integer $n\ge 1$, we have
   \begin{equation*}
   n=\displaystyle\sum_{d|n}\phi(d)
   \end{equation*}
   #+END_corollary
* Group \rom{1}
** Permutations
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{permutation} of a set $X$ is a bijection from $X$ to itself.
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The family of all the permutations of a set $X$, denoted by $S_X$ is called
   the \textbf{symmetric group} on $X$. When $X=\lb 1,2,\dots,n\rb$, $S_X$ is
   usually denoted by $X_n$ and is called the \textbf{symmetric group on } $n$
   \textbf{letters} 
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $i_1,i_2,\dots,i_r$ be distinct integers in $\lb 1,2,\dots,n\rb$. If
   $\alpha\in S_n$ fixes the other integers and if
   \begin{equation*}
   \alpha(i_1)=i_2,\alpha(i_2)=i_3,\dots,\alpha(i_{r-1})=i_r,\alpha(i_r)=i_1
   \end{equation*}
   then \alpha is called an textbf{r-cycle}. \alpha is a cycle of
   \textbf{length} $r$ and denoted by
   \begin{equation*}
   \alpha=(i_1\; i_2\;\dots\; i_r)
   \end{equation*}
   #+END_definition

   2-cycles are also called the *transpositions*.

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Two permutations $\alpha,\beta\in S_n$ are \textbf{disjoint} if every $i$
   moved by one is fixed by the other.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Disjoint permutations $\alpha,\beta\in S_n$ commute
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every permutation $\alpha\in S_n$ is either a cycle or a product of disjoint cycles.
   #+END_proposition

   #+BEGIN_proof
   Induction on the number $k$ of points moved by $\alpha$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{complete factorization} of a permutation $\alpha$ is a
   factorization of $\alpha$ into disjoint cycles that contains exactly one
   1-cycle $(i)$ for every $i$ fixed by $\alpha$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let $\alpha\in S_n$ and let $\alpha=\beta_1\dots\beta_t$ be a complete
   factorization into disjoint cycles. This factorization is unique except for
   the order in which the cycles occur
   #+END_theorem

   #+BEGIN_proof
   for all $i$, if $\beta_t(i)\neq i$, then $\beta_t^k(i)\neq\beta_t^{k-1}(i)$
   for any $k\ge 1$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\gamma,\alpha\in S_n$, then $\alpha\gamma\alpha^{-1}$ has the same cycle
   structure as $\gamma$. In more detail, if the complete factorization of
   $\gamma$ is
   \begin{equation*}
   \gamma=\beta_1\beta_2\dots(i_1\; i_2\;\dots)\dots\beta_t
   \end{equation*}
   then $\alpha\gamma\alpha^{-1}$ is permutation that is obtained from $\gamma$
   by applying $\alpha$ to the symbols in the cycles of $\gamma$
   #+END_lemma

   Example. Suppose
   \begin{gather*}
   \beta=(1\;2\;3)(4)(5)\\
   \gamma=(5\;2\;4)(1)(3)
   \end{gather*}
   then we can easily find the $\alpha$
   \begin{equation*}
   \alpha=
   \begin{pmatrix}
   1&2&3&4&5\\
   5&2&4&1&3
   \end{pmatrix}
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Permutations $\gamma$ and $\sigma$ in $S_n$ has the same cycle structure if
   and only if there exists $\alpha\in S_n$ with $\sigma=\alpha\gamma\alpha^{-1}$
   #+END_theorem


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $n\ge 2$ then every $\alpha\in S_n$ is a product of tranpositions
   #+END_proposition
   #+BEGIN_proof
   $(1\;2\;\dots\; r)=(1\; r)(1\; r-1)\dots(1\; 2)$
   #+END_proof


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A permutation $\alpha\in S_n$ is \textbf{even} if it can be factored into a
   product of an even number of transpositions. Otherwise \textbf{odd}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\alpha\in S_n$ and $\alpha=\beta_1\dots\beta_t$ is a complete
   factorization, then \textbf{signum} $\alpha$ is defined by
   \begin{equation*}
   \sgn(\alpha)=(-1)^{n-t}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For all $\alpha,\beta\in S_n$
   \begin{equation*}
   \sgn(\alpha\beta)=\sgn(\alpha)\sgn(\beta)
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   1. Let $\alpha\in S_n$; if $\sgn(\alpha)=1$ then $\alpha$ is even. otherwise
      odd
   2. A permutation $\alpha$ is odd if and only if it's a product of an odd
      number of transpositions
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let $\alpha,\beta\in S_n$. If $\alpha$ and $\beta$ have the same parity, then
   $\alpha\beta$ is even while if $\alpha$ and $\beta$ have distinct parity,
   $\alpha\beta$ is odd
   #+END_corollary
** Groups
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{binary operation} on a set $G$ is a function
   \begin{equation*}
   *:G\times G\to G
   \end{equation*}
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{group} is a set $G$ equipped with a binary operation * s.t.
   1. the \textbf{associative law} holds
   2. \textbf{identity}
   3. every $x\in G$ has an \textbf{inverse}, there is a $x'\in G$  with 
      $x*x'=e=x'*x$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A group $G$ is called \textbf{abelian} if it satisfies the
   \textbf{commutative law}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $G$ be a group
   1. The \textbf{cancellation laws} holds: if either $x*a=x*b$ or $a*x=b*x$, then
      $a=b$
   2. $e$ is unique
   3. Each $x\in G$ has a unique inverse
   4. $(x^{-1})^{-1}=x$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An expression $a_1a_2\dots a_n$ \textbf{needs no parentheses} if all the ultimate
   products it yields are equal
   #+END_definition

   #+ATTR_LATEX: :options [Generalized Associativity]
   #+BEGIN_theorem
   If $G$ is a group and $a_1,a_2,\dots,a_n\in G$ then the expression
   $a_1a_2\dots a_n$ needs no parentheses
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $G$ be a group and let $a\in G$. If $a^k=1$ for some $k>1$ then the
   smallest such exponent $k\ge 1$ is called the \tf{order} or $a$; if no such
   power exists, then one says that $a$ has \tf{infinite order}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $G$ is a finite group, then every $x\in G$ has finite order
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \tf{motion} is a distance preserving bijection $\varphi:\R^2\to\R^2$. If
   \pi is a polygon in the plane, then its \tf{symmetry group} $\Sigma(\pi)$
   consists of all the motions $\varphi$ for which $\varphi(\pi)=\pi$. The
   elements of $\Sigma(\pi)$ are called the \tf{symmetries} of \pi
   #+END_definition

   Let $\pi_4$ be a square. Then the group $\Sigma(\pi_4)$ is called the
   \tf{dihedral group} with 8 elements, denoted by $D_8$

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\pi_n$ is a regular polygon with $n$ vertices $v_1,\dots,v_n$ and center
   $O$, then the symmetry group $\Sigma(\pi_n)$ is called the \tf{dihedral
   group} with $2n$ elements, and it's denoted by $D_{2n}$
   #+END_definition
** Lagrange's theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A subset $H$ of a group $G$ is a \tf{subgroup} if
   1. $1\in H$
   2. if $x,y\in H$, then $xy\in H$
   3. if $x\in H$, then $x^{-1}\in H$
   #+END_definition

   If $H$ is a subgroup of $G$, we write $H\le G$. If $H$ is a proper subgroup,
   then we write $H<$G

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A subset $H$ of a group $G$ is a subgroup if and only if $H$ is nonempty and
   whenever $x,y\in H$, $xy^{-1}\in H$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A nonempty subset $H$ of a finite group $G$ is a subgroup if and only if $H$
   is closed; that is, if $a,b\in H$, then $ab\in H$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a group and $a\in G$
   \begin{equation*}
   \langle a\rangle=\{a^n:n\in\Z\}=\{\text{all powers of } a\}
   \end{equation*}
   $\la a\ra$ is called the \tf{cyclic subgroup} of $G$ \tf{generated} by $a$. A
   group $G$ is called \tf{cyclic} if there exists $a\in G$ s.t. $G=\la a\ra$,
   in which case $a$ is called the \tf{generator}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The \tf{integers mod $m$}, denoted by $\I_m$ is the family of all congruence
   classes mod $m$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $m\ge 2$ be a fixed integer
   1. If $a\in \Z$, then $[a]=[r]$ for some $r$ with $0\le r<m$
   2. If $0\le r'<r<m$, then $[r']\neq[r]$
   3. $\I_m$ has exactly $m$ elements
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   1. If $G=\la a\ra$ is a cyclic group of order $n$, then $a^k$ is a generator
      of $G$ if and only if $(k,n)=1$
   2. If $G$ is a cyclic group of order $n$ and $\gen(G)=\{\text{all generators
      of } G\}$, then
      \begin{equation*}
      \abs{\gen(G)}=\phi(n)
      \end{equation*}
      where $\phi$ is the Euler \phi-function
   #+END_theorem
   #+BEGIN_proof
   1. there is $t\in\N$ s.t. $a^{kt}=a$ hence $a^{kt-1}=1$ and $n\mid kt-1$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $G$ be a finite group and let $a\in G$. Then the order of $a$ is
   $\abs{\la a\ra}$.
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a finite group, then the number of elements in $G$, denoted by
   $\abs{G}$ is called the \tf{order} of $G$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The intersection $\bigcap_{i\in I}H_i$ of any family of subgroups of a group
   $G$ is again a subgroup of $G$
   #+END_proposition


   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $X$ is a subset of a group $G$, then there is a subgroup $\la X\ra$ of $G$
   containing $X$ tHhat is \tf{smallest} in the sense that $\la X\ra\le H$ for
   every subgroup $H$ 
   of $G$ that contains $X$
   
   #+END_corollary


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $X$ is a subset of a group $G$, then $\la X\ra$ is called the \tf{subgroup
   generated by} $X$
   #+END_definition

   A \tf{word} on $X$ is an element $g\in G$ of the form $g=x_1^{e_1}\dots
   x_n^{e_n}$ where $x_i\in X$ and $e_i=\pm 1$ for all $i$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $X$ is a nonempty subset of a group $G$, then $\la X\ra$ is the set of all
   words on $X$
   #+END_proposition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $H\le G$ and $a\in G$, then the \tf{coset} $aH$ is the subset $aH$ of $G$,
   where
   \begin{equation*}
   aH=\{ah:h\in H\}
   \end{equation*}
   #+END_definition
   $aH$ \tf{left coset}, $Ha$ \tf{right coset}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $H\le G,a,b\in G$
   1. $aH=bH$ if and only if $b^{-1}a\in H$
   2. if $aH\cap bH\neq\emptyset$, then $aH=bH$
   3. $\abs{aH}=\abs{H}$ for all $a\in G$
   #+END_lemma
   #+BEGIN_proof
   define a relation $a\equiv b$ if $b^{-1}a\in H$
   #+END_proof


   #+ATTR_LATEX: :options [Lagrange's Theorem]
   #+BEGIN_theorem
   If $H$ is a subgroup of a finite group $G$, then $\abs{H}$ is a divisor of $\abs{G}$
   #+END_theorem

   #+BEGIN_proof
   Let $\{a_1H,a_2H,\dots,a_tH\}$ be the family of all the distinct cosets of
   $H$ in $G$. Then
   \begin{equation*}
   G=a_1H\cup a_2H\cup\dots\cup a_tH
   \end{equation*}
   hence
   \begin{equation*}
   \abs{G}=\abs{a_1H}+\dots+\abs{a_tH}
   \end{equation*}
   But $\abs{a_iH}=\abs{H}$ for all $i$. Hence $\abs{G}=t\abs{H}$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The \tf{index} of a subgroup $H$ in $G$ denoted by $[G:H]$, is the number of
   left cosets of $H$ in $G$
   #+END_definition

   Note that $\abs{G}=[G:H]\abs{H}$

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $G$ is a finite group and $a\in G$, then the order of $a$ is a divisor of
   $\abs{G}$ 
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $G$ is a finite group, then $a^{\abs{G}}=1$ for all $a\in G$
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $p$ is a prime, then every group $G$ of order $p$ is cyclic
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The set $U(\I_m)$, defined by
   \begin{equation*}
    U(\I_m)=\{[r]\in\I_m:(r,m)=1\}
   \end{equation*}
   is a multiplicative group of order $\phi(m)$. If $p$ is a prime, then
   $U(\I_m)=\I_m^{\times}$, the nonzero elements of $\I_p$.
   #+END_proposition

   #+ATTR_LATEX: :options [Fermat]
   #+BEGIN_corollary
   If $p$ is a prime and $a\in\Z$, then
   \begin{equation*}
   a^p\equiv a\mod p
   \end{equation*}
   #+END_corollary

   #+BEGIN_proof
   suffices to show $[a^p]=[a]$ in $\I_p$. If $[a]=[0]$, then $[a^p]=[a]^p=[0]$.
   Else, since $\abs{\I_p^\times}=p-1$, $[a]^{p-1}=[1]$
   #+END_proof


   #+ATTR_LATEX: :options [Euler]
   #+BEGIN_theorem
   If $(r,m)=1$, then
   \begin{equation*}
   r^{\phi(m)}\equiv 1\mod m
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options [Wilson's Theorem]
   #+BEGIN_theorem
   An integer $p$ is a prime if and only if
   \begin{equation*}
   (p-1)!\equiv -1\mod p
   \end{equation*}
   #+END_theorem
** Homomorphisms
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $(G,*)$ and $(H,\circ)$ are groups, then a function $f:G\to H$ is a
   \tf{homomorphism} if
   \begin{equation*}
   f(x*y)=f(x)\circ f(y)
   \end{equation*}
   for all $x,y\in G$. If $f$ is also a bijection, then $f$ is called an
   \tf{isomorphism}. $G$ and $H$ are called \tf{isomorphic}, denoted by $G\cong H$
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $f:G\to H$ be a homomorphism
   1. $f(1)=1$
   2. $f(x^{-1})=f(x)^{-1}$
   3. $f(x^n)=f(x)^n$ for all $n\in\Z$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $f:G\to H$ is a homomorphism, define
   \begin{equation*}
   \tf{kernel}f=\{x\in G:f(x)=1\}
   \end{equation*}
   and
   \begin{equation*}
   \tf{image}f=\{h\in H:h=f(x)\text{ for some } x\in G\}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $f:G\to H$ be a homomorphism
   1. $\ker f$ is a subgroup of $G$ and $\im f$ is a subgroup of $H$
   2. if $x\in\ker f$ and if $a\in G$, then $axa^{-1}\in\ker f$
   3. $f$ is an injection if and only if $\ker f=\{1\}$
   #+END_proposition

   #+BEGIN_proof
   3. $f(a)=f(b)\Leftrightarrow f(ab^{-1})=1$
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A subgroup $K$ of a group $G$ is called a \tf{normal subgroup} if $k\in K$
   and $g\in G$ imply $gkg^{-1}\in K$, denoted by $K\triangleleft G$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a group and $a\in G$, then a \tf{conjugate} of $a$ is any element
   in $G$ of the form
   \begin{equation*}
   gag^{-1}
   \end{equation*}
   where $g\in G$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a group and $g\in G$, define \tf{conjugation} $\gamma_g:G\to G$ by
   \begin{equation*}
   \gamma_g(a)=gag^{-1}
   \end{equation*}
   for all $a\in G$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. If $G$ is a group and $g\in G$, then conjugation $\gamma_g:G\to G$ is an
      isomorphism
   2. Conjugate elements have the same order
   #+END_proposition

   #+BEGIN_proof
   1. bijection: $\gamma_g\circ\gamma_{g^{-1}}=1=\gamma_{g^{-1}}\circ\gamma_g$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. If $H$ is a subgroup of index 2 in a group $G$, then $g^2\in H$ for every
      $g\in G$
   2. If $H$ is a subgroup of index 2 in a group $G$, then $H$ is a normal
      subgroup of $G$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The group of \tf{quaternions} is the group $\bQ$ of order 8 consisting of the
   following matrices in $GL(2, \C)$
   \begin{equation*}
   \bQ=\{I,A,A^2,A^3,B,BA,BA^2,BA^3\}
   \end{equation*}
   where $I$ is the identity matrix
   \begin{equation*}
   A=
   \begin{pmatrix}
   0&1\\
   -1&0
   \end{pmatrix}, \text{ and }
   B=\begin{pmatrix}
   0&i\\
   i&0
     \end{pmatrix}
   \end{equation*}
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The alternating group $A_4$ is a group of order 12 having no subgroup of
   order 6
   #+END_proposition
** Quotient group
   $\cals(G)$ is the set of all nonempty subsets of a group $G$. If
   $X,Y\in\cals(G)$, define
   \begin{equation*}
   XY=\{xy:x\in X\text{ and } y\in Y\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $K\le G$ is normal if and only if
   \begin{equation*}
   gK=Kg
   \end{equation*}
   #+END_lemma

   A natural question is that whether $HK$ is a subgroup when $H$ and $K$ are
   subgroups. The answer is no. Let $G=S_3,H=\la(1\;2)\ra,K=\la(1\;3)\ra$


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. If $H$ and $K$ are subgroups of a group $G$, and if one of them is normal,
      then $HK\le G$ and $HK=KH$
   2. If $H,K\tril G$, then $HK\tril G$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let $G/K$ denote the family of all the left cosets of a subgroup $K$ of $G$.
   If $K\tril G$, then
   \begin{equation*}
   aKbK=abK
   \end{equation*}
   for all $a,b\in G$ and $G/K$ is a group under this operation
   #+END_theorem

   #+BEGIN_proof
   $aKbK=abKK=abK$
   #+END_proof

   $G/K$ is called the \tf{quotient group} $G$ mod $K$

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Every $K\tril G$ is the kernel of some homomorphism
   #+END_corollary
   
   #+BEGIN_proof
   Define the \tf{natural map} $\pi:G\to G/K$, $a\mapsto aK$
   #+END_proof

   #+ATTR_LATEX: :options [First Isomorphism Theorem]
   #+BEGIN_theorem
   If $f:G\to H$ is a homomorphism, then
   \begin{equation*}
   \ker f\tril G\quad\text{ and }\quad G/\ker f\cong\im f
   \end{equation*}
   If $\ker f=K$ and $\varphi:G/K\to\im f\le H,aK\mapsto f(a)$, then $\varphi$
   is an isomorphism
   #+END_theorem

   \tf{Remark}\quad
   \begin{tikzcd}
   G \arrow[rr,"f"] \arrow[dr,"\pi"]& &
   H\\ 
   &G/K \arrow[ur,"\varphi"]&
   \end{tikzcd}

   #+ATTR_LATEX: :options [Product Formula]
   #+BEGIN_proposition
   If $H$ and $K$ are subgroups of a finite group $G$, then
   \begin{equation*}
   \abs{HK}\abs{H\cap K}=\abs{H}\abs{K}
   \end{equation*}
   #+END_proposition

   #+BEGIN_proof
   Define a function $f:H\times K\to HK,(h,k)\mapsto hk$. Show that
   $\abs{f^{-1}(x)}=\abs{H\cap K}$. 

   Claim that if $x=hk$, then
   \begin{equation*}
   f^{-1}(x)=\{(hd,d^{-1}k):d\in H\cap K\}
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options [Second Isomorphism Theorem]
   #+BEGIN_theorem
   If $H\tril G, K\le G$, then $HK\le G,H\cap K\tril G$ and
   \begin{equation*}
   K/(H\cap K)\cong HK/H
   \end{equation*}
   #+END_theorem

   #+BEGIN_proof
   $hkH=kk^{-1}hkH=kh'H=kH$
   #+END_proof

   #+ATTR_LATEX: :options [Third Isomorphism Theorem]
   #+BEGIN_theorem
   If $H,K\tril G$ with $K\le H$, then $H/K\tril G/K$ and
   \begin{equation*}
   (G/K)/(H/K)\cong G/H
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options [Correspondence Theorem]
   #+BEGIN_theorem
   If $K\tril G, \pi:G\to G/K$ is the natural map, then
   \begin{equation*}
   S\mapsto \pi(S)=S/K
   \end{equation*}
   is a bijection between $Sub(G;K)$, the family of all those subgroups $S$ of
   $G$ that contain $K$, and $Sub(G/K)$, the family of all the subgroups of
   $G/K$. If we denote $S/K$ by $S^*$, then
   1. $T\le S\le G$ if and only if $T^*\le S^*$, in which case $[S:T]=[S^*:T^*]$
   2. $T\tril S$ if and only if $T^*\tril S^*$, in which case $S/T\cong S^*/T^*$
   #+END_theorem

   \begin{center}
   \begin{tikzcd}
   G \arrow[d,dash] \arrow[rd]&\\
   S \arrow[d,dash] \arrow[rd] & G/K \arrow[d,dash]\\
   T \arrow[d,dash] \arrow[rd] & S/K=S^* \arrow[d,dash]\\
   K  \arrow[rd] & T/K=T^* \arrow[d,dash]\\
   & \{1\}
   \end{tikzcd}
   \end{center}

   #+BEGIN_proof
   Use $\pi^{-1}\pi=1$ and $\pi\pi^{-1}=1$ to prove injectivity and surjectivity
   respectively. 

   For $[S:T]=[S^*:T^*]$, show there is a bijection between the family of all
   cosets of the form $sT$ and the family of all the cosets of the form
   $s^*T^*$.

   injective:
   \begin{align*}
   \pi(m)T^*=\pi(n)T^*&\Leftrightarrow \pi(m)\pi(n)^{-1}\in T^*\\
   &\Leftrightarrow mn^{-1}K\in T/K\\
   &\Rightarrow mn^{-1}t^{-1}\in K\\
   &\Rightarrow mn^{-1}=tk\in T\\
   &\Leftrightarrow mT=nT\\
   \end{align*}
   
   surjective:
   
   
   If $G$ is finite, then
   \begin{align*}
   [S^*:T^*]&=\abs{S^*}/\abs{T^*}\\
   &=\abs{S/K}/\abs{T/K}\\
   &=(\abs{S}/\abs{K})/(\abs{T}/\abs{K})\\
   &=\abs{S}/\abs{T}\\
   &=[S:T]
   \end{align*}

   If $T\tril S$, by third isomorphism theorem, $T/S\cong (T/K)/(S/K)=T^*/S^*$

   If $T^*\tril S^*$, 
   \begin{equation*}
   \pi(sts^{-1})\in \pi(s)T^*\pi(s)^{-1}=T^*
   \end{equation*}
   so that $sts^{-1}\in \pi^{-1}(T^*)=T$
   #+END_proof
   

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $G$ is a finite abelian group and $d$ is a divisor of $\abs{G}$, then $G$
   contains a subgroup of order $d$
   #+END_proposition

   #+BEGIN_proof
   Abelian group's subgroup is normal and hence we can build quotient groups.
   p90 for proof. Use the correspondence theorem
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $H$ and $K$ are grops, then their \tf{direct product}, denoted by $H\times
   K$, is the set of all ordered pairs $(h,k)$ with the operation
   \begin{equation*}
   (h,k)(h',k')=(hh',kk')
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $G$ and $G'$ be groups and $K\tril G, K'tril G'$. Then $K\times K'\tril
   G\times G'$ and
   \begin{equation*}
   (G\times G')/(K\times K')\cong (G/K)\times(G'/K')
   \end{equation*}
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $G$ is a group containing normal subgroups $H$ and $K$ and $H\cap K=\{1\}$
   and $HK=G$, then $G\cong H\times K$
   #+END_proposition

   #+BEGIN_proof
   Note $\abs{HK}\abs{H\cap K}=\abs{H}\abs{K}$. Consider $\varphi:G\to H\times
   K$. Show it's homo and bijective.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $m,n$ are relatively prime, then
   \begin{equation*}
   \I_{mn}\cong\I_m\times\I_n
   \end{equation*}
   #+END_theorem

   #+BEGIN_proof
   $\Z/\la mn\ra\cong\I_m\times\I_n$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $G$ be a group, and $a,b\in G$ be commuting elements of orders $m,n$. If
   $(m,n)=1$, then $ab$ has order $mn$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $(m,n)=1$, then $\phi(mn)=\phi(m)\phi(n)$
   #+END_corollary


   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   1. If $p$ is a prime, then $\phi(p^e)=p^e-p^{e-1}=p^e(1-\frac{1}{p})$
   2. If $n=p_1^{e_1}\dots p_t^{e_t}$, then
      \begin{equation*}
      \phi(n)=n(1-\frac{1}{p_1})\dots(1-\frac{1}{p_t})
      \end{equation*}
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   A cyclic group of order $n$ has a unique subgroup of order $d$, for each
   divisor $d$ of $n$, and this subgroup is cyclic.
   #+END_lemma

   Define an equivalence relation on a group $G$ by $x\equiv y$ if $\la x\ra=\la
   y\ra$. Denote the equivalence class containing $x$ by $\gen(C)$, where $C=\la
   x\ra$. Equivalence classes form a partition and we get
   \begin{equation*}
   G=\displaystyle\prod_{C}\gen(C)
   \end{equation*}
   where $C$ ranges over all cyclic subgroups of $G$. Note $\abs{\gen(C)}=\phi(n)$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   A group $G$ of order $n$ is cyclic if and only if for each divisor $d$ of
   $n$, there is at most one cyclic subgroup of order $d$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $G$ is an abelian group of order $n$ having at most one cyclic subgroup o
f
   order $p$ for each prime divisor $p$ of $n$, then $G$ is cyclic
   #+END_theorem

   Exercise:
   * 2.71 Suppose $H\le G, \abs{H}=\abs{K}$. Since $\abs{H}=[H:K]\abs{K}$,
     $[H:K]=1$. Hence $H=K$
   * 2.67 1. $\inn(S_3)\cong S_3/Z(S_3)\cong S_3$ and $\abs{\aut(S_3)}\le 6$.
     Hence $\aut(S_3)=\inn(S_3)$
** Group Actions
   #+ATTR_LATEX: :options [Cayley]
   #+BEGIN_theorem
   Every group $G$ is isomorphic to a subgroup of the symmetric group $S_G$. In
   particular, if $\abs{G}=n$, then $G$ is isomorphic to a subgroup of $S_n$
   #+END_theorem

   #+BEGIN_proof
   For each $a\in G$, define $\tau_a(x)=ax$ for every $x\in G$. $\tau_a$ is a
   bijection for its inverse is $\tau_{a^{-1}}$
   \begin{equation*}
   \tau_a\tau_{a^{-1}}=\tau_1=\tau_{a^{-1}}\tau_a
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options [Representation on Cosets]
   #+BEGIN_theorem
   Let $G$ be a group and $H\le G$ having finite index $n$. Then there exists a
   homomorphism $\varphi:G\to S_n$ with $\ker\varphi\le H$
   #+END_theorem
  
   When $H=\{1\}$, this is the Cayley theorem.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every group $G$ of order 4 is isomorphic to either $\I_4$ or the four-group
   $\bV$. And $\I_4\not\cong\bV$
   #+END_proposition

   #+BEGIN_proof
   By lagrange's theorem, every element in $G$ other than 1 has order 2 or 4. If
   4, then $G$ is cyclic.

   Suppose $x,y\neq 1$, then $xy\neq x,y$. Hence $G=\{1,x,y,xy\}$.
   #+END_proof
   

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $G$ is a group of order 6, then $G$ is isomorphic to either $\I_6$ or
   $S_3$. Moreover $\I_6\not\cong S_3$
   #+END_proposition

   #+BEGIN_proof
   If $G$ is not cyclic. Since $\abs{G}$ is even, it has some elements having
   order 2, say $t$.

   If $G$ is abelian. Suppose it has another different element $a$ with order 2.
   Then $H=\{1,a,t,at\}$ is a subgroup which contradict. Hence it must contain
   an element $b$ of order 3. Then $bt$ has order 6 and $G$ is cyclic.

   If $G$ is not abelian. If $G$ doesn't have elements of order 3, then it's
   abelian. Hence $G$ has an element $s$ of order 3.

   Now $\abs{\la s\ra}=3$, so $[G:\la s\ra]=\abs{G}/\abs{\la s\ra}=2$ and $\la
   s\ra$ is normal. Since $t=t^{-1}$, $tst\in\la s\ra$. If $tst=s^0=1$, $s=1$.
   If $tst=s$, $\abs{\la st\ra}=6$. If $tst=s^2=s^{-1}$.

   Let $H=\la t\ra$, $\varphi:G\to S_{G/\la t\ra}$ given by
   \begin{equation*}
   \varphi(g):x\la t\ra\to gx\la t\ra
   \end{equation*}
   By representation on cosets, $\ker\varphi\le\la t\ra$. Hence
   $\ker\varphi=\{1\}$ or $\ker\varphi=\la t\ra$. Since
   \begin{equation*}
   \varphi(t)=
   \begin{pmatrix}
   \la t\ra&s\la t\ra&s^2\la t\ra\\
   t\la t\ra&ts\la t\ra&ts^2\la t \ra
   \end{pmatrix}
   \end{equation*}
   If $\varphi(t)$ is the identity permutation, then $ts\la t\ra=s\la t\ra$, so
   that $s^{-1}ts\in\la t\ra=\{1,t\}$. But now $s^{-1}ts=t$. Therefore
   $t\not\in\ker\varphi$ and $\ker\varphi=\{1\}$. Therefore $\varphi$ is
   injective. Because $\abs{G}=\abs{S_3}$, $G\cong S_3$
   #+END_proof


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $X$ is a set and $G$ is a group, then $G$ \tf{acts} on $X$ if there is a
   function $G\times X\to X$, denoted by $(g,x)\to gx$ s.t.
   1. (gh)x=g(hx) for all $g,h\in G$ and $x\in X$
   2. $1x=x$ for all $x\in X$

      
   $X$ is a $G\textbf{ -set }$ if $G$acts on $X$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$acts on $X$ and $x\in X$, then the \tf{orbit} of $x$, denoted by
   $\calo(x)$, is the subset of $X$
   \begin{equation*}
   \calo(x)=\{gx:g\in G\}\subseteq X
   \end{equation*}
   the \tf{stabilizer} of $x$, denoted by $G_x$, is the subgroup
   \begin{equation*}
   G_x=\{g\in G:gx=x\}\le G
   \end{equation*}
   #+END_definition

   $G$ acts \tf{transitively} on $X$ if there is only one orbit.
   \tf{centralizer} $C_G(x)=\{g\in G:gxg^{-1}=x\}$

   
