#+TITLE: Advanced Modern Algebra
#+AUTHOR: Joseph J. Rotman

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/AdvancedModernAlgebra/AdvancedModernAlgebra.tex

* Group \rom{1}
** Permutations
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{permutation} of a set $X$ is a bijection from $X$ to itself.
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The family of all the permutations of a set $X$, denoted by $S_X$ is called
   the \textbf{symmetric group} on $X$. When $X=\lb 1,2,\dots,n\rb$, $S_X$ is
   usually denoted by $X_n$ and is called the \textbf{symmetric group on } $n$
   \textbf{letters} 
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $i_1,i_2,\dots,i_r$ be distinct integers in $\lb 1,2,\dots,n\rb$. If
   $\alpha\in S_n$ fixes the other integers and if
   \begin{equation*}
   \alpha(i_1)=i_2,\alpha(i_2)=i_3,\dots,\alpha(i_{r-1})=i_r,\alpha(i_r)=i_1
   \end{equation*}
   then \alpha is called an textbf{r-cycle}. \alpha is a cycle of
   \textbf{length} $r$ and denoted by
   \begin{equation*}
   \alpha=(i_1\; i_2\;\dots\; i_r)
   \end{equation*}
   #+END_definition

   2-cycles are also called the *transpositions*.

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Two permutations $\alpha,\beta\in S_n$ are \textbf{disjoint} if every $i$
   moved by one is fixed by the other.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Disjoint permutations $\alpha,\beta\in S_n$ commute
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every permutation $\alpha\in S_n$ is either a cycle or a product of disjoint cycles.
   #+END_proposition

   #+BEGIN_proof
   Induction on the number $k$ of points moved by $\alpha$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{complete factorization} of a permutation $\alpha$ is a
   factorization of $\alpha$ into disjoint cycles that contains exactly one
   1-cycle $(i)$ for every $i$ fixed by $\alpha$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let $\alpha\in S_n$ and let $\alpha=\beta_1\dots\beta_t$ be a complete
   factorization into disjoint cycles. This factorization is unique except for
   the order in which the cycles occur
   #+END_theorem

   #+BEGIN_proof
   for all $i$, if $\beta_t(i)\neq i$, then $\beta_t^k(i)\neq\beta_t^{k-1}(i)$
   for any $k\ge 1$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\gamma,\alpha\in S_n$, then $\alpha\gamma\alpha^{-1}$ has the same cycle
   structure as $\gamma$. In more detail, if the complete factorization of
   $\gamma$ is
   \begin{equation*}
   \gamma=\beta_1\beta_2\dots(i_1\; i_2\;\dots)\dots\beta_t
   \end{equation*}
   then $\alpha\gamma\alpha^{-1}$ is permutation that is obtained from $\gamma$
   by applying $\alpha$ to the symbols in the cycles of $\gamma$
   #+END_lemma

   Example. Suppose
   \begin{gather*}
   \beta=(1\;2\;3)(4)(5)\\
   \gamma=(5\;2\;4)(1)(3)
   \end{gather*}
   then we can easily find the $\alpha$
   \begin{equation*}
   \alpha=
   \begin{pmatrix}
   1&2&3&4&5\\
   5&2&4&1&3
   \end{pmatrix}
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Permutations $\gamma$ and $\sigma$ in $S_n$ has the same cycle structure if
   and only if there exists $\alpha\in S_n$ with $\sigma=\alpha\gamma\alpha^{-1}$
   #+END_theorem


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $n\ge 2$ then every $\alpha\in S_n$ is a product of tranpositions
   #+END_proposition
   #+BEGIN_proof
   $(1\;2\;\dots\; r)=(1\; r)(1\; r-1)\dots(1\; 2)$
   #+END_proof


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A permutation $\alpha\in S_n$ is \textbf{even} if it can be factored into a
   product of an even number of transpositions. Otherwise \textbf{odd}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\alpha\in S_n$ and $\alpha=\beta_1\dots\beta_t$ is a complete
   factorization, then \textbf{signum} $\alpha$ is defined by
   \begin{equation*}
   \sgn(\alpha)=(-1)^{n-t}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For all $\alpha,\beta\in S_n$
   \begin{equation*}
   \sgn(\alpha\beta)=\sgn(\alpha)\sgn(\beta)
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   1. Let $\alpha\in S_n$; if $\sgn(\alpha)=1$ then $\alpha$ is even. otherwise
      odd
   2. A permutation $\alpha$ is odd if and only if it's a product of an odd
      number of transpositions
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let $\alpha,\beta\in S_n$. If $\alpha$ and $\beta$ have the same parity, then
   $\alpha\beta$ is even while if $\alpha$ and $\beta$ have distinct parity,
   $\alpha\beta$ is odd
   #+END_corollary
** Groups
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{binary operation} on a set $G$ is a function
   \begin{equation*}
   *:G\times G\to G
   \end{equation*}
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \textbf{group} is a set $G$ equipped with a binary operation * s.t.
   1. the \textbf{associative law} holds
   2. \textbf{identity}
   3. every $x\in G$ has an \textbf{inverse}, there is a $x'\in G$  with 
      $x*x'=e=x'*x$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A group $G$ is called \textbf{abelian} if it satisfies the
   \textbf{commutative law}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $G$ be a group
   1. The \textbf{cancellation laws} holds: if either $x*a=x*b$ or $a*x=b*x$, then
      $a=b$
   2. $e$ is unique
   3. Each $x\in G$ has a unique inverse
   4. $(x^{-1})^{-1}=x$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An expression $a_1a_2\dots a_n$ \textbf{needs no parentheses} if all the ultimate
   products it yields are equal
   #+END_definition

   #+ATTR_LATEX: :options [Generalized Associativity]
   #+BEGIN_theorem
   If $G$ is a group and $a_1,a_2,\dots,a_n\in G$ then the expression
   $a_1a_2\dots a_n$ needs no parentheses
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $G$ be a group and let $a\in G$. If $a^k=1$ for some $k>1$ then the
   smallest such exponent $k\ge 1$ is called the \tf{order} or $a$; if no such
   power exists, then one says that $a$ has \tf{infinite order}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $G$ is a finite group, then every $x\in G$ has finite order
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A \tf{motion} is a distance preserving bijection $\varphi:\R^2\to\R^2$. If
   \pi is a polygon in the plane, then its \tf{symmetry group} $\Sigma(\pi)$
   consists of all the motions $\varphi$ for which $\varphi(\pi)=\pi$. The
   elements of $\Sigma(\pi)$ are called the \tf{symmetries} of \pi
   #+END_definition

   Let $\pi_4$ be a square. Then the group $\Sigma(\pi_4)$ is called the
   \tf{dihedral group} with 8 elements, denoted by $D_8$

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\pi_n$ is a regular polygon with $n$ vertices $v_1,\dots,v_n$ and center
   $O$, then the symmetry group $\Sigma(\pi_n)$ is called the \tf{dihedral
   group} with $2n$ elements, and it's denoted by $D_{2n}$
   #+END_definition
** Lagrange's theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A subset $H$ of a group $G$ is a \tf{subgroup} if
   1. $1\in H$
   2. if $x,y\in H$, then $xy\in H$
   3. if $x\in H$, then $x^{-1}\in H$
   #+END_definition

   If $H$ is a subgroup of $G$, we write $H\le G$. If $H$ is a proper subgroup,
   then we write $H<$G

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A subset $H$ of a group $G$ is a subgroup if and only if $H$ is nonempty and
   whenever $x,y\in H$, $xy^{-1}\in H$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A nonempty subset $H$ of a finite group $G$ is a subgroup if and only if $H$
   is closed; that is, if $a,b\in H$, then $ab\in H$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a group and $a\in G$
   \begin{equation*}
   \langle a\rangle=\{a^n:n\in\Z\}=\{\text{all powers of } a\}
   \end{equation*}
   $\la a\ra$ is called the \tf{cyclic subgroup} of $G$ \tf{generated} by $a$. A
   group $G$ is called \tf{cyclic} if there exists $a\in G$ s.t. $G=\la a\ra$,
   in which case $a$ is called the \tf{generator}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The \tf{integers mod $m$}, denoted by $\I_m$ is the family of all congruence
   classes mod $m$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $m\ge 2$ be a fixed integer
   1. If $a\in \Z$, then $[a]=[r]$ for some $r$ with $0\le r<m$
   2. If $0\le r'<r<m$, then $[r']\neq[r]$
   3. $\I_m $ has exactly $m$ elements
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   1. If $G=\la a\ra$ is a cyclic group of order $n$, then $a^k$ is a generator
      of $G$ if and only if $(k,n)=1$
   2. If $G$ is a cyclic group of order $n$ and $\gen(G)=\{\text{all generators
      of } G\}$, then
      \begin{equation*}
      \abs{\gen(G)}=\phi(n)
      \end{equation*}
      where $\phi$ is the Euler \phi-function
   #+END_theorem
   #+BEGIN_proof
   1. there is $t\in\N$ s.t. $a^{kt}=a$ hence $a^{kt-1}=1$ and $n\mid kt-1$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $G$ be a finite group and let $a\in G$. Then the order of $a$ is
   $\abs{\la a\ra}$.
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $G$ is a finite group, then the number of elements in $G$, denoted by
   $\abs{G}$ is called the \tf{order} of $G$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The intersection $\bigcap_{i\in I}H_i$ of any family of subgroups of a group
   $G$ is again a subgroup of $G$
   #+END_proposition


   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $X$ is a subset of a group $G$, then there is a subgroup $\la X\ra$ of $G$
   containing $X$ tHhat is \tf{smallest} in the sense that $\la X\ra\le H$ for
   every subgroup $H$ 
   of $G$ that contains $X$
   
   #+END_corollary


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $X$ is a subset of a group $G$, then $\la X\ra$ is called the \tf{subgroup
   generated by} $X$
   #+END_definition

   A \tf{word} on $X$ is an element $g\in G$ of the form $g=x_1^{e_1}\dots
   x_n^{e_n}$ where $x_i\in X$ and $e_i=\pm 1$ for all $i$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $X$ is a nonempty subset of a group $G$, then $\la X\ra$ is the set of all
   words on $X$
   #+END_proposition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $H\le G$ and $a\in G$, then the \tf{coset} $aH$ is the subset $aH$ of $G$,
   where
   \begin{equation*}
   aH=\{ah:h\in H\}
   \end{equation*}
   #+END_definition
   $aH$ \tf{left coset}, $Ha$ \tf{right coset}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $H\le G,a,b\in G$
   1. $aH=bH$ if and only if $b^{-1}a\in H$
   2. if $aH\cap bH\neq\emptyset$, then $aH=bH$
   3. $\abs{aH}=\abs{H}$ for all $a\in G$
   #+END_lemma
   #+BEGIN_proof
   define a relation $a\equiv b$ if $b^{-1}a\in H$
   #+END_proof


   #+ATTR_LATEX: :options [Lagrange's Theorem]
   #+BEGIN_theorem
   If $H$ is a subgroup of a finite group $G$, then $\abs{H}$ is a divisor of $\abs{G}$
   #+END_theorem

   #+BEGIN_proof
   Let $\{a_1H,a_2H,\dots,a_tH\}$ be the family of all the distinct cosets of
   $H$ in $G$. Then
   \begin{equation*}
   G=a_1H\cup a_2H\cup\dots\cup a_tH
   \end{equation*}
   hence
   \begin{equation*}
   \abs{G}=\abs{a_1H}+\dots+\abs{a_tH}
   \end{equation*}
   But $\abs{a_iH}=\abs{H}$ for all $i$. Hence $\abs{G}=t\abs{H}$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The \tf{index} of a subgroup $H$ in $G$ denoted by $[G:H]$, is the number of
   left cosets of $H$ in $G$
   #+END_definition

   Note that $\abs{G}=[G:H]\abs{H}$

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $G$ is a finite group and $a\in G$, then the order of $a$ is a divisor of
   $\abs{G}$ 
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $G$ is a finite group, then $a^{\abs{G}}=1$ for all $a\in G$
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $p$ is a prime, then every group $G$ of order $p$ is cyclic
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The set $U(\I_m)$, defined by
   \begin{equation*}
    U(\I_m)=\{[r]\in\I_m:(r,m)=1\}
    
   \end{equation*}
   is a multiplicative group of order $\varphi(m)$. If $p$ is a prime, then
   $U(\I_m)=\I_m^{\times}$, the nonzero elements of $\I_p$.
   #+END_proposition

   #+ATTR_LATEX: :options [Fermat]
   #+BEGIN_corollary
   If $p$ is a prime and $a\in\Z$, then
   \begin{equation*}
   a^p\equiv a\mod p
   \end{equation*}
   #+END_corollary

   #+BEGIN_proof
   suffices to show $[a^p]=[a]$ in $\I_p$. If $[a]=[0]$, then $[a^p]=[a]^p=[0]$.
   Else, since $\abs{\I_p^\times}=p$, $[a]^{p-1}=[1]$
   #+END_proof


   #+ATTR_LATEX: :options [Euler]
   #+BEGIN_theorem
   If $(r,m)=1$, then
   \begin{equation*}
   r^{\phi(m)}\equiv 1\mod m
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options [Wilson's Theorem]
   #+BEGIN_theorem
   An integer $p$ is a prime if and only if
   \begin{equation*}
   (p-1)!\equiv -1\mod p
   \end{equation*}
   #+END_theorem
** Homomorphisms
