#+TITLE: A Guide to Nip Theories
#+AUTHOR: Pierre Simon

#+EXPORT_FILE_NAME: ../latex/AGuideToNIPTheories/AGuideToNIPTheories.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Introduction
** Preliminaries
    We work with a complete, usually one-sorted, theory \(T\) in language \(L\). We have a monster
    model \(\calu\)

    We often work with *partitioned formulas*, namely formulas \(\phi(x;y)\) with a separation of
    variables into object and parameter variables.

    A type \(p\) *concentrates* on a definable set \(\phi(x)\) if \(p\vdash\phi(x)\).

    We use the notation \(\phi^0\) to mean \(\neg\phi\) and \(\phi^1\) to mean \phi. If \(\phi(x;y)\) is a partitioned
    formula, a *\phi-type* over \(A\) is a maximal consistent set of formulas of the
    form \(\phi(x;a)^\epsilon\) for a\(a\in A\) and \(\epsilon\in\{0,1\}\).
* The NIP Property and Invariant Types
**   NIP formulas
    Let \(\phi(x;y)\) be a partitioned formula. Set \(A\) of \(\abs{x}\)-tuples is *shattered*
    by \(\phi(x;y)\) if we can find a family \((b_I:I\subseteq A)\) of \(\abs{y}\)-tuples s.t.
    \begin{equation*}
    \calu\vDash\phi(a;b_I)\Leftrightarrow a\in I,\quad\forall a\in A
    \end{equation*}
    By compactness, this is equivalent to saying that every finite subset of \(A\) is shattered
    by \(\phi(x;y)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A partitioned formula \(\phi(x;y)\) is NIP if no infinite set of \(\abs{x}\)-tuples is shattered by \(\phi(x;y)\)
    #+END_definition

    #+BEGIN_remark
    If \(\phi(x;y)\) is NIP, then by compactness, there is some integer \(n\) s.t. no set of size \(n\)
    is shattered by \(\phi(x;y)\)

    The maximal integer \(n\) for which there is some \(A\) of size \(n\) shattered by \(\phi(x;y)\) is
    called the *VC-dimension* of \phi. If there is no such integer, then its VC-dimension is infinite
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    * Let \(T\) be \(\DLO\). Then \(\phi(x;y):=(x\le y)\) is NIP of VC-dimension 1.
      If \(A\) is shattered by \(\phi(x;y)\) and \(\abs{A}\ge 2\). Then take \(a_1<a_2\in A\)
      and \(\vDash\phi(a;b_{\{a_1\}})\Leftrightarrow a=a_1\). Thus \(\vDash a_1\le b_{\{a_1\}}\wedge a_2>b_{\{a_1\}}\), a contradiction.
    * If \(\phi(x;y)\) is stable, then it is NIP
    * If \(T\) is the theory of arithmetic, then \(\phi(x;y)\)="\(x\) divides \(y\)" has IP. To see
      this, take \(N\in\N\) and \(A=\{p_0,\dots,p_{N-1}\}\) a set of distinct prime numbers. For
      any \(I\subseteq N\), set \(b_I\) to be \(\prod_{i\in I}p_i\). We have \(\vDash\phi(p_i,b_I)\Leftrightarrow i\in I\). Thus \(A\) is
      shattered and \(\phi(x;y)\) has infinite VC-dimension
    * If \(T\) is the random graph in the language \(L=\{R\}\), then the formula \(\phi(x;y):=xRy\) has
      IP. In fact any set of elements is shattered by \phi. Note that we are working in a monster
      model.
    * If \(T\) is a theory of an infinite Boolean algebra, in the natural language \(\{0,1,\neg,\vee,\wedge\}\),
      then the formula \(x\le y\) (defined as \(x\wedge y=x\)) has IP. Indeed, it shatters any set \(A\)
      with \(a\wedge b=0\) for \(a\neq b\in A\)
    #+END_examplle

    If \(\phi(x;y)\) is a partitioned formula, we let \(\phi^{opp}(y;x)=\phi(x;y)\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    The formula \(\phi(x;y)\) is NIP iff \(\phi^{opp}(y;x)\) is NIP
    #+END_lemma

    #+BEGIN_proof
    Assume that \(\phi(x;y)\) has IP. Then by compactness, we can find some \(A=\{a_i:i\in\fP(\omega)\}\) which is
    shattered by \(\phi(x;y)\) as witnessed by tuples \(b_I\), \(I\subseteq\fP(\omega)\). Let \(B=\{b_j:j\in\omega\}\)
    where \(b_j:=b_I\) and \(I_j:=\{X\subseteq\omega:j\in X\}\). Then for any \(J_0\subseteq\omega\), we have
    \begin{equation*}
    \vDash\phi(a_{J_0},b_j)\Leftrightarrow j\in J_0
    \end{equation*}
    #+END_proof

    #+BEGIN_remark
    The VC-dimension of a formula \phi need not be equal to the VC-dimension of the opposite
    formula \(\phi^{opp}\). For example, let \(T\) be the theory of equality, then the
    formula \(\phi(x;y_1y_2y_3):=(x=y_1\vee x=y_2\vee x=y_3)\) has VC-dimension 3, but the opposite formula only
    has VC-dimension 2
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    The formula \(\phi(x;y)\) has IP iff there is an indiscernible sequence \((a_i:i<\omega)\) and a
    tuple \(b\) s.t.
    \begin{equation*}
    \vDash\phi(a_i;b)\Leftrightarrow i\text{ is even}
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    <<Problem1>>
    \(\Leftarrow\): Assume that there is a sequence \((a_i:i<\omega)\) and a tuple \(b\) as above. Let \(I\subseteq\omega\).
    We show that there is some \(b_I\) s.t. \(\phi(a_i;b_I)\Leftrightarrow i\in I\)
    We can find an increasing one-to-one map \(\tau:\omega\to\omega\) s.t. for all \(i\in\omega\), \(\tau(i)\) is even
    iff \(i\in I\). Then by indiscenibility the map sending \(a_i\) to \(a_{\tau(i)}\) for all \(i<\omega\) is
    a partial isomorphism. It extends to a global automorphism \sigma. Then take \(b_I=\sigma^{-1}(b)\)

    \(\Rightarrow\): Assume that \(\phi(x;y)\) has IP. Let \(A=(a_i:i<\omega)\) be a sequence of \(\abs{x}\)-tuples
    which is shattered by \(\phi(x;y)\). By Ramsey and compactness, we can find some indiscernible
    sequence \(I=(c_i:i<\omega)\) of \(\abs{x}\)-tuples realizing the EM-type of \(A\). It follows that
    for any two disjoint finite sets \(I_0\) and \(I_1\) of \(I\), the partial
    type \(\{\phi(c;y):c\in I_0\}\cup\{\neg\phi(c;y):c\in I_1\}\) is consistent.
    #+LATEX: \wu{

    #+LATEX: }
    Then by compactness \(I\) is shattered
    by \(\phi(x;y)\). In particular, there is \(b\) s.t. \(\phi(c_i;b)\) holds iff \(i\) is even
    #+END_proof

    Let \(\phi(x;y)\) be an NIP formula, then there is a finite set \Delta of formulas and an
    integer \(n_{\phi,\Delta}\) s.t. the following do not exist:
    * \((a_i:i<n_{\phi,\Delta})\) a \Delta-indiscernible sequence of \(\abs{x}\)-tuples
    * \(b\) a \(\abs{y}\)-tuple, s.t. \(\neg(\phi(a_i;b)\leftrightarrow\phi(a_{i+1};b))\) holds for \(i<n_{\phi,\Delta}-1\)


    Indeed, if we could not find such \Delta and \(n_{\phi,\Delta}\), then the partial type in
    variables \((x_i:i<\omega)\verb!^! y\) stating that \((x_i:i<\omega)\) is an indiscernible sequence and

* Problems
    |[[Problem1]]|
