#+TITLE: Algebra
#+AUTHOR: Serge Lang
#+EXPORT_FILE_NAME: ../latex/Algebra/Algebra.tex
#+LATEX_HEADER: \input{../preamble.tex}
* Real Fields
** Ordered Fields
    Let \(K\) be a field. An *ordering* of \(K\) is a subset \(P\) of \(K\)
    having the following properties
    \bigskip
    \begin{itemize}[itemindent=3em]
    \item[\textbf{ORD 1.}] Given \(x\in K\), we have either \(x\in P\) ,or \(x=0\) or
    \(-x\in P\), and these three possibilities are mutually exclusive
    \item[\textbf{ORD 2.}] If \(x,y\in P\), then \(x+y,xy\in P\)
    \end{itemize}

    \(K\) is *ordered by* \(P\), and we call \(P\) the set of *positive
    elements*

    Suppose \(K\) is ordered by \(P\). Since \(1\neq0\) and \(1=1^2=(-1)^2\), we
    see that \(1\in P\). By *ORD 2*, it follows that \(1+\dots+1\in P\), whence \(K\)
    has characteristic 0. If \(x\in P\) and \(x\neq0\), then \(xx^{-1}=1\in P\) implies
    that \(x^{-1}\in P\)

    #+BEGIN_center
    /Let \(E\) be a field. Then a product of sums of squares in \(E\) is a sum
    of squares./

    /If \(a,b\in E\) are sum of squares and \(b\neq0\), then \(a/b\) is a sum of
    squares/
    #+END_center

    Consider complex number:)

    Let \(x,y\in K\). We define \(x<y\) to mean that \(y-x\in P\). If \(x<0\) we say
    that \(x\) is *negative*.

    If \(K\) is ordered and \(x\in K\), \(x\neq0\), then \(x^2\) is positive

    If \(E\) has characteristic \(\neq2\), and \(-1\) is a sum of squares in \(E\),
    then every element \(a\in E\) is a sum of squares, because
    \(4a=(1+a)^2-(1-a)^2\)

    If \(K\) is a field with an ordering \(P\), and \(F\) is a subfield, then
    obviously, \(P\cap F\) defines an ordering of \(F\), which is called the
    *induced* ordering

    Let \(K\) be an ordered field and let \(F\) be a subfield with the induced
    ordering. We put \(\abs{x}=x\) if \(x>0\) and \(\abs{x}=-x\) if \(x<0\). An
    element \(\alpha\in K\) is *infinitely large* over \(F\) if \(\abs{\alpha}\ge x\) for all
    \(x\in F\). It is *infinitely small* over \(F\) if \(0\le\abs{\alpha}\le\abs{x}\) for
    all \(x\in F\), \(x\neq0\). \alpha is infinitely large if and only if \(\alpha^{-1}\) is
    infinitely small. \(K\) is *archimedean* over \(F\) if \(K\) has no elements
    which are infinitely large over \(F\). An intermediate field \(F_1\),
    \(K\supset F_1\supset F\) is *maximal archimedean over* \(F\) in \(K\) if it is
    archimedean over \(F\) and no other intermediate field containing \(F_1\) is
    archimedean over \(F\). We say that \(F\) is *maximal archimedean in* \(K\)
    if it is maximal archimedean over itself in \(K\)

    Let \(K\) be an ordered field and \(F\) a subfield. Let \(K\) be an ordered
    field and \(F\) a subfield. Let \(\fo\) be the set of elements of \(K\)
    which are not infinitely large over \(F\). Then \(\fo\) is a ring and that
    for any \(\alpha\in K\), we have \(\alpha\) or \(\alpha^{-1}\in\fo\). Hence \(\fo\) is what is
    called a valuation ring, containing \(F\). Let \(\fm\) be the ideal of all
    \(\alpha\in K\) which are infinitely small over \(F\). Then \(\fm\) is the unique
    maximal ideal of \(\fo\), because any element in \(\fo\) which is not in
    \(\fm\) has an inverse in \(\fo\). We call \(\fo\) the
    *valuation ring determined by the ordering of* \(K/F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(K\) be an ordered field and \(F\) a subfield. Let \(\fo\) be the
    valuation ring determined by the ordering of \(K/F\), and let \(\fm\) be its
    maximal ideal. Then \(\fo/\fm\) is a real field.
    #+END_proposition

    #+BEGIN_proof
    Otherwise, we could write
    \begin{equation*}
    -1=\displaystyle\sum\alpha_i^2+a
    \end{equation*}
    with \(\alpha_i\in\fo\) and \(a\in\fm\). Since \(\sum\alpha_i^2\) is positive and \(a\) is
    infinitely small, such a relation is clearly impossible
    #+END_proof
