#+TITLE: Algebraic Curves

#+AUTHOR: William Fulton
#+EXPORT_FILE_NAME: ../latex/AlgebraicCurves/AlgebraicCurves.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\Rad}{\text{Rad}}

This [[https://ziyuzhang.github.io/ma40188/Lecture_Notes_Long.pdf][notes]] seems a good companion
* Affine Algebraic Sets
** Affine Space and Algebraic Sets
    Let \(k\) be any field. By \(\A^n(k)\), or simply \(\A^n\), we shall mean the Cartesian product
    of \(k\) with itself \(n\) times. We call \(\A^n(k)\) *affine \(n\)-space* over \(k\); its elements
    will be called *points*. In particular, \(\A^1(k)\) is the *affine line*, \(\A^2(k)\) is the *affine
    space*

    If \(F\in k[X_1,\dots,X_n]\), a point \(P=(a_1,\dots,a_n)\in\A^n(k)\) is called a *zero* of \(F\) if \(F(P)=0\).
    If \(F\) is not a constant, the set of zeros of \(F\) is called the *hypersurface* defined
    by \(F\), and is denoted by \(V(F)\). A hypersurface in \(\A^2(k)\) is called an *affine plane
    curve*. If \(F\) is a polynomial of degree one, \(V(F)\) is called a *hyperplane* in \(\A^n(k)\);
    if \(n=2\), it is a *line*

    More generally, if \(S\) is any set of polynomials in \(k[X_1,\dots,X_n]\), we
    let \(V(S)=\{P\in\A^n\mid F(P)=0\text{ for all }F\in S\}\), \(V(S)=\bigcap_{F\in S}V(F)\). If \(S=\{F_1,\dots,F_r\}\), we
    usually write \(V(F_1,\dots,F_r)\). A subset \(X\subseteq\A^n(k)\) is an *affine algebraic set*, or simply an
    *algebraic set*, if \(X=V(S)\) for some \(S\)

    1. If \(I\) is the ideal in \(k[X_1,\dots,X_n]\) generated by \(S\), then \(V(S)=V(I)\); so every
       algebraic set \(V(I)\) is equal to some ideal \(I\)
    2. If \(\{I_\alpha\}\) is any collection of ideals, then \(V(\bigcup_\alpha I_\alpha)=\bigcap_\alpha V(I_\alpha)\).
    3. If \(I\subset J\), then \(V(I)\supset V(J)\)
    4. \(V(FG)=V(F)\cup V(G)\)

       \(x\in V(FG)\Leftrightarrow FG(x)\Leftrightarrow F(x)=0\vee G(x)=0\) since \(k\) is a field and \(k[X_1,\dots,X_n]\) is a domain

       \(V(I)\cup V(J)=V(\{FG\mid F\in I,G\in J\})\)
    5. \(V(0)=\A^n(k)\), \(V(1)=\emptyset\), \(V(X_1-a_1,\dots,X_n-a_n)=\{(a_1,\dots,a_n)\}\) for \(a_i\in k\). So any finite
       subset of \(\A^n(k)\) is an algebraic set


    #+BEGIN_exercise
    label:ex1.13
    Show that each of the following sets is not algebraic
    1. \(A=\{(x,y)\in\A^2(\R)\mid y=\sin x\}\)
    #+END_exercise

    #+BEGIN_proof
    1. Suppose \(f\in I(A)\) and fix a \(a\in\R\), then \(f(x,a)\in\R[x]\) but has infinitely many
       solutions, a contradiction
    #+END_proof
** The Ideal of a Set of Points
    For any subset \(X\subseteq\A^n(k)\), we consider those polynomials that vanish on \(X\); they form an
    ideal in \(k[X_1,\dots,X_n]\), called the *ideal* of \(X\), and
    written \(I(X)\), \(I(X)=\{F\in k[X_1,\dots,X_n]\mid F(a_1,\dots,a_n)=0\text{ for all }(a_1,\dots,a_n)\in X\}\).
    1. If \(X\subset Y\), then \(I(X)\supset I(Y)\)
    2. \(I(\emptyset)=k[X_1,\dots,X_n]\) \(I(\A^n(k))=(0)\) if \(k\) is an infinite
       field; \(I(\{(a_1,\dots,a_n)\})=(X_1-a_1,\dots,X_n-a_n)\) for \(a_1,\dots,a_n\in k\)
    3. \(I(V(S))\supset S\) for any set \(S\) of polynomials; \(V(I(X))\supset X\) for any set \(X\) of points
    4. \(V(I(V(S)))=V(S)\) for any set \(S\) of polynomials; \(I(V(I(X)))=I(X)\) for any set \(X\)
       of points. So if \(X\) is an algebraic set, \(X=V(I(X))\); and if \(J\) is an ideal of an
       algebraic set, \(I(V(J))=J\)


    An ideal that is the ideal of an algebraic set has a property not shared with all ideals:
    if \(J=I(X)\) and \(F^n\in I\) for some integer \(n>0\), then \(F\in I\). If \(I\) is any ideal in a
    ring \(R\), we define the *radical* of \(I\), written \(\Rad(I)\), to
    be \(\{a\in R\mid a^n\in I\text{ for some integer }n>0\}\). Then \(\Rad(I)\) is an ideal containing \(I\).
    An ideal \(I\) is called a *radical ideal* if \(I=\Rad(I)\). So we have
    5. [@5] \(I(X)\) is a radical ring for any \(X\subset\A^n(k)\)


    #+BEGIN_exercise
    label:ex1.14
    Let \(F\) be a nonconstant polynomial in \(k[X_1,\dots,X_n]\), \(k\) algebraically closed. Show
    that \(\A^n(k)\setminus V(F)\) is infinite if \(n\ge 1\) and \(V(F)\) is infinite if \(n\ge 2\)
    #+END_exercise

    #+BEGIN_proof
    \(\A^1(k)\setminus V(F)\) is infinite. Now if \(\A^n(k)\setminus V(F)\) is infinite, then for
    each \((a_1,\dots,a_n,a_{n+1})\in V(F)\), \((\A^n(k)\setminus V(F))\times\{a_{n+1}\}\) is infinite.

    \(V(F)=\bigcup_{a_1\in k}\cdots\bigcup_{a_{n-1}\in k}V(F(a_1,\dots,a_{n-1},X_n))\)
    #+END_proof
** The Hilbert Basis Theorem
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Every algebraic set is the intersection of a finite number of hypersurface
    #+END_theorem

    #+BEGIN_proof
    Let the algebraic set be \(V(I)\) for some ideal \(I\subset k[X_1,\dots,X_n]\). It is enough to show
    that \(I\) is finitely generated, for if \(I=(F_1,\dots,F_r)\), then \(V(I)=V(F_1)\cap\dots\cap V(F_r)\). To prove
    this we need some algebra:
    #+END_proof

    A ring is *Noetherian* if every ideal in the ring is finitely generated. Fields and PID's are
    Noetherian rings. Theorem, therefore, is a consequence of

    #+ATTR_LATEX: :options [Hilbert Basis Theorem]
    #+BEGIN_theorem
    If \(R\) is a Noetherian ring, then \(R[X_1,\dots,X_n]\) is a Noetherian ring
    #+END_theorem

    #+BEGIN_proof
    Since \(R[X_1,\dots,X_n]\cong R[X_1,\dots,X_{n-1}][X_n]\) , the theorem will follow by induction if we can
    prove that \(R[X]\) is Noetherian whenever \(R\) is Noetherian. Let \(I\) be an ideal
    in \(R[X]\). We must find a finite set of generators for \(I\)

    If \(F=\sum_{i=0}^da_iX^i\in R[X]\), \(a_d\neq 0\), we call \(a_d\) the leading coefficient of \(F\).
    Let \(J\) be the set of leading coefficients of all polynomials in \(I\). It is easy to check
    that \(J\) is an ideal in \(R\), so there are polynomials \(F_1,\dots,F_r\in I\) whose leading
    coefficients generate \(J\). Take an integer \(N\) larger than the degree of each \(F_i\). For
    each \(m\le N\), let \(J_m\) be the ideal in \(R\) consisting of all leading coefficients of all
    polynomials \(F\in I\) s.t. \(\deg(F)\le m\). Let \(\{F_{m,j}\}\) be a finite set of polynomials
    in \(I\) of degree \(\le m\) whose leading coefficients generate \(J_m\). Let \(I'\) be the ideal
    generated by the \(F_i\)'s and all the \(F_{m,j}\)'s. It suffices to show that \(I=I'\)

    Suppose \(I'\) were smaller than \(I\); let \(G\) be an element of \(I\) of lowest degree that
    is not in \(I'\). If \(\deg(G)>N\), we can find polynomials \(Q_i\) s.t. \(\sum Q_iF_i\) and \(G\)
    have the same leading term. But then \(\deg(G-\sum Q_iF_i)<\deg G\) so \(G-\sum Q_iF_i\in I'\) and
    so \(G\in I'\).  Similarly if \(\deg(G)=m\le N\), we can lower the degree by subtracting
    off \(\sum Q_jF_{m,j}\) for some \(Q_j\). This proves the theorem
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(k[X_1,\dots,X_n]\) is Noetherian for any field \(k\).
    #+END_corollary

    #+BEGIN_exercise
    label:ex1.22
    Let \(I\) be an ideal in a ring \(R\), \(\pi:R\to R/I\) the natural homomorphism
    1. Show that for every ideal \(J'\) of \(R/I\), \(\pi^{-1}(J')=J\) is an ideal of \(R\)
       containing \(I\). And for every ideal \(J\) of \(R\) containing \(I\), \(\pi(J)=J'\) is an
       ideal of \(R/I\).

       This sets up a natural one-to-one correspondence between ideals of \(R/I\) and ideals
       of \(R\) that contains \(I\)

    2. Show that \(J'\) is a radical ideal iff \(J\) is radical. Similarly for prime and maximal ideals

    3. Show that \(J'\) is finitely generated if \(J\) is. Conclude that \(R/I\) is Noetherian
       if \(R\) is Noetherian. Any ring of the form \(k[X_1,\dots,X_n]/I\) is Noetherian
    #+END_exercise
** Irreducible Components of an Algebraic Set
    An algebraic set \(V\subset\A^n\) is *reducible* if \(V=V_1\cup V_2\) where \(V_1\) and \(V_2\) are algebraic sets
    in \(\A^n\) and \(V_i\neq V\) for \(i=1,2\). Otherwise \(V\) is reducible

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:prop1.1
    An algebraic set \(V\) is irreducible iff \(I(V)\) is prime
    #+END_proposition

    #+BEGIN_proof
    If \(I(V)\) is not prime and suppose \(F_1F_2\in I(V)\), \(F_1,F_2\notin I(V)\).
    Then \(V=(V\cap V(F_1))\cup(V\cap V(F_2))\) and \(V\cap V(F_i)\subsetneq V\), so \(V\) is reducible

    If \(V=V_1\cup V_2\) and \(V_i\subsetneq V\), then \(I(V_i)\supsetneq I(V)\); let \(F_i\in I(V_i)\setminus I(V)\).
    Then \(F_1F_2\in I(V)\) , so \(I(V)\) is not prime
    #+END_proof

    We want to show that an algebraic set is the union of a finite number of irreducible algebraic
    set.s

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\cali\) be any nonempty collection of ideals in a Noetherian ring \(R\). Then \(\cali\) has a
    maximal member
    #+END_lemma

    #+BEGIN_proof
    Choose (using the axiom of choice) an ideal from each subset of \(\cali\). Let \(I_0\) be the chosen
    ideal for \(\cali\) itself. Let \(\cali_1=\{I\in\cali\mid I\supsetneq I_0\}\), and let \(I_1\) be the chosen ideal
    of \(\cali\), etc. It suffices to show that some \(\cali_n\) is empty. If not let \(I=\bigcup_{i=0}^\infty I_i\),
    an ideal of \(R\). Let \(F_1,\dots,F_r\) generate \(I\); each \(F_i\in I_n\) if \(n\) is chosen
    sufficiently large. But then \(I_n=I\), so \(I_{n+1}=I_n\), a contradiction
    #+END_proof

    It follows that any collection of algebraic sets in \(\A^n(k)\) has a minimal member. For
    if \(\{V_\alpha\}\) is such a collection, take a maximal member \(I(V_{\alpha_0})\) from \(\{I(V_\alpha)\}\),
    then \(V_{\alpha_0}\) is the minimal

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(V\) be an algebraic set in \(\A^n(k)\). Then there are unique irreducible algebraic
    sets \(V_1,\dots,V_m\) s.t. \(V=V_1\cup\cdots\cup V_m\) and \(V_i\not\subset V_j\) for all \(i\neq j\)
    #+END_theorem

    #+BEGIN_proof
    Let
    \(\cali=\{\text{algebraic sets }V\subset\A^n(k)\mid V\text{ is not the union of a finite number of irreducible algebraic sets}\}\).
    We want to show that \(\cali\) is empty. If not, let \(V\) be a minimal member of \(\cali\).
    Since \(V\in\cali\), \(V\) is not irreducible, so \(V=V_1\cup V_2\), \(V_i\subsetneq V\). Then \(V_i\notin\cali\),
    so \(V_i=V_{i1}\cup\dots\cup V_{im_i}\), \(V_{ij}\) irreducible. But then \(V=\bigcup_{i,j}V_{ij}\) , a
    contradiction.

    So any algebraic set \(V\) may be written as \(V=V_1\cup\dots\cup V_m\), \(V_i\) irreducible. We can throw
    away any \(V_i\) s.t. \(V_i\subset V_j\) for some \(i\neq j\). To show uniqueness, let \(V=W_1\cup\dots\cup W_m\).
    Then \(V_i=\bigcup_j(W_j\cap V_i)\), so \(V_i\subset W_{j(i)}\) for some \(j(i)\) since \(V_i\) is irreducible. Similarly \(V_{j(i)}\subset V_k\) for
    some \(k\).
    #+END_proof

    The \(V_i\) are called the *irreducible components* of \(V\); \(V=V_1\cup\cdots\cup V_m\) is the *decomposition*
    of \(V\) into irreducible components

    #+BEGIN_exercise
    label:ex1.25
    1. Show that \(V(Y-X^2)\subset\A^2(\C)\) is irreducible; in fact, \(I(V(Y-X^2))=(Y-X^2)\)
    2. Decompose \(V(Y^4-X^2,Y^4-X^2Y^2+XY^2-X^3)\subset\A^2(\C)\) into irreducible components
    #+END_exercise

    #+BEGIN_proof
    1. Consider \(h:\C[X,Y]\to\C[X]\) by \(h(f(x,y))=f(x,x^2)\). This is a homomorphism and
       thus \(\C[X,Y]/(Y-X^2)\cong\C[X]\). Thus \((Y-X^2)\) is prime
    2. Solution is finite
    #+END_proof

    #+BEGIN_exercise
    label:ex1.28
    If \(V=V_1\cup\dots\cup V_r\) is the decomposition of an algebraic set into irreducible components, show
    that \(V_i\not\subset\bigcup_{j\neq i}V_j\)
    #+END_exercise

    #+BEGIN_proof
    suppose \(V_i\subset\bigcup_{j\neq i}V_j\), then \(V_i=\bigcup_{j\neq i}(V_j\cap V_i)\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.29
    Show that \(\A^n(k)\) is irreducible if \(k\) is infinite
    #+END_exercise

    #+BEGIN_proof
    \(\A^1(k)\) is irreducible

    For each \(a\in k\), \(\A^n(k)\times\{a\}\) is irreducible
    #+END_proof
** Algebraic Subsets of the Plane
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:prop1.2
    Let \(F\) and \(G\) be polynomials in \(k[X,Y]\) with no common factors.
    Then \(V(F,G)=V(F)\cap V(G)\) is a finite set of points
    #+END_proposition

    #+BEGIN_proof
    \(F\) and \(G\) have no common factors in \(k[X][Y]\), so they also have no common factors
    in \(k(X)[Y]\). Since \(k(X)[Y]\) is a PID, \((F,G)=(1)\) in \(k(X)[Y]\), so \(RF+SG=1\) for
    some \(R,S\in k(X)[Y]\). There is a nonzero \(D\in k{X}\) s.t. \(DR=A,DS=B\in k[X,Y]\).
    Therefore \(AF+BG=D\). If \((a,b)\in V(F,G)\) then \(D(a)=0\). But \(D\) has only a finite number
    of zeros, this shows that a finite number of \(X\)-coordinates appear among the points
    of \(V(F,G)\). Since the same reasoning applies to the \(Y\)-coordinates, there can be only a
    finite number of points
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(F\) is an irreducible polynomials in \(k[X,Y]\) s.t. \(V(F)\) is infinite,
    then \(I(V(F))=(F)\) and \(V(F)\) is irreducible
    #+END_corollary

    #+BEGIN_proof
    If \(G\in I(V(F))\), then \(V(F,G)\) is infinite, so \(F\) divides \(G\) by the proposition,
    i.e., \(G\in(F)\). \(V(F)\) is irreducible follows from Proposition ref:prop1.1.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Suppose \(k\) is infinite. Then the irreducible algebraic subsets of \(\A^2(k)\)
    are: \(\A^2(k)\), \(\emptyset\), points, and irreducible plane curves \(V(F)\) where \(F\) is an
    irreducible polynomial and \(V(F)\) is infinite
    #+END_corollary

    #+BEGIN_proof
    Let \(V\) be an irreducible algebraic set in \(\A^2(k)\). If \(V\) is finite
    or \(I(V)=(0)\), \(V\) is of the required type. Otherwise \(I(V)\) contains a nonconstant
    polynomial \(F\); since \(I(V)\) is prime, some irreducible polynomial factor of \(F\) belongs
    to \(I(V)\), so we may assume \(F\) is irreducible. Then \(I(V)=(F)\); for
    if \(G\in I(V)\), \(G\notin(F)\), then \(V\subset V(F,G)\) is finite.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume \(k\) is algebraically closed, \(F\) a nonconstant polynomial in \(k[X,Y]\).
    Let \(F=F_1^{n_1}\dots F_r^{n_r}\) be the decomposition of \(F\) into irreducible factors.
    Then \(V(F)=V(F_1)\cup\dots\cup V(F_r)\) is the decomposition of \(V(F)\) into irreducible components,
    and \(I(V(F))=(F_1,\dots,F_r)\)
    #+END_corollary

    #+BEGIN_proof
    No \(F_i\) divides any \(F_j\), \(j\neq i\), so there are no inclusion relations among
    the \(V(F_i)\). And \(I(\bigcup_iV(F_i))=\bigcap_iI(V(F_i))=\bigcap_i(F_i)\). Since any polynomial divisible by
    each \(F_i\) is also divisible by \(F_1\cdots F_r\), \(\bigcap_i(F_i)=(F_1\cdots F_r)\). Note that the \(V(F_i)\) are
    infinite since \(k\) is algebraically closed
    #+END_proof
** Hilbert's Nullstellensatz
    Assume \(k\) is algebraically closed

    #+ATTR_LATEX: :options [Weak Nullstellensatz]
    #+BEGIN_theorem
    If \(I\) is a proper ideal in \(k[X_1,\dots,X_n]\), then \(V(I)\neq\emptyset\)
    #+END_theorem

    #+BEGIN_proof
    We may assume that \(I\) is a maximal ideal, for there is a maximal ideal \(J\) containing \(I\)
    and \(V(J)\subset V(I)\). So \(L=k[X_1,\dots,X_n]/I\) is a field, and \(k\) may be regared as a subfield
    of \(L\)

    Suppose we knew that \(k=L\), then for each \(i\) there is an \(a_i\in k\) s.t. the \(I\)-residue
    of \(X_i\) is \(a_i\), or \(X_i-a_i\in I\). But \((X_1-a_1,\dots,X_n-a_n)\) is a maximal ideal,
    so \(I=(X_1-a_1,\dots,X_n-a_n)\) and \(V(I)=\{(a_1,\dots,a_n)\}\neq\emptyset\)

    Thus we have reduced problem to showing:

    *Claim (\(*\))*: If an algebraically closed field \(k\) is a subfield of a field \(L\), and there is a
     ring homomorphism from \(k[X_1,\dots,X_n]\) onto \(L\) (identity on \(k\)), then \(k=L\)

     This will be proved later
    #+END_proof

    #+ATTR_LATEX: :options [Hilbert's Nullstellensatz]
    #+BEGIN_theorem
    Let \(I\) be an ideal in \(k[X_1,\dots,X_n]\), then \(I(V(I))=\Rad(I)\)
    #+END_theorem

    This says the following: if \(F_1,\dots,F_r\) and \(G\) are in \(k[X_1,\dots,X_n]\) and \(G\) vanishes
    whenever \(F_1,\dots,F_r\) vanish, then there is an equation \(G^N=A_1F_1+A_2F_2+\dots+A_rF^r\) for some \(N>0\)
    and some \(A_i\in k[X_1,\dots,X_n]\)

    #+BEGIN_proof
    \(\Rad(I)\subset I(V(I))\) is easy. Suppose \(G\in I(V(F_1,\dots,F_r))\), \(F_i\in k[X_1,\dots,X_n]\).
    Let \(J=(F_1,\dots,F_r,X_{n+1}G-1)\subset k[X_1,\dots,X_n,X_{n+1}]\). Then \(V(J)\subset\A^{n+1}(k)\) is empty,
    since \(G\) vanishes whenever all that \(F_i\)'s are zero. Applying the Weak Nullstellensatz
    to \(J\), we see that \(1\in J\), so there is an
    equation \(1=\sum A_i(X_1,\dots,X_{n+1})F_i+B(X_1,\dots,X_{n+1})(X_{n+1}G-1)\). Let \(Y=1/X_{n+1}\), and
    multiply the equation by a higher power of \(Y\), so that an equation
    \(Y^N=\sum C_i(X_1,\dots,X_n,Y)F_i+D(X_1,\dots,X_n,Y)(G-Y)\) in \(k[X_1,\dots,X_n,Y]\) results. Substituting \(G\)
    for \(Y\) gives the required equation
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(I\) is a radical ideal in \(k[X_1,\dots,X_n]\), then \(I(V(I))=I\). So there is a one-to-one
    correspondence between radical ideals and algebraic sets
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(I\) is a prime ideal, then \(V(I)\) is irreducible. There is a one-to-one correspondence
    between prime ideals and irreducible algebraic sets. The maximal ideals correspond to points
    #+END_corollary

    #+BEGIN_proof
    \(I\) is prime \(\Rightarrow\) \(I\) is radical \(\Rightarrow\) \(I(V(I))=I\). \(V(I)\) is irreducible \(\Leftrightarrow\) \(I(V(I))\) is prime
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(F\) be a nonconstant polynomial in \(k[X_1,\dots,X_n]\), \(F=F_1^{n_1}\dots F_r^{n_r}\) the
    decomposition of \(F\) into irreducible factors. Then \(V(F)=V(F_1)\cup\dots\cup V(F_r)\) is the decomposition
    of \(V(F)\) into irreducible components, and \(I(V(F))=(F_1\cdots F_r)\). There is a one-to-one
    correspondence between irreducible polynomials \(F\in k[X_1,\dots,X_n]\) (up to multiplication by a
    nonzero element of \(k\)) and irreducible hypersurfaces in \(\A^n(k)\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(I\) be an ideal in \(k[X_1,\dots,X_n]\). Then \(V(I)\) is a finite set iff \(k[X_1,\dots,X_n]/I\) is
    a finite dimensional vector space over \(k\). If this occurs, the number of points in \(V(I)\)
    is *at most* \(\dim_k(k[X_1,\dots,X_n]/I)\)
    #+END_corollary

    #+BEGIN_proof
    Let \(P_1,\dots,P_r\in V(I)\). Choose \(F_1,\dots,F_r\in k[X_1,\dots,X_n]\) s.t. \(F_i(P_j)=0\) iff \(i\neq j\)
    and \(F_i(P_i)=1\); let \(\barF_i\) be the \(I\)-residue of \(F_i\). If \(\sum\lambda_i\barF_i=0\), \(\lambda_i\in k\),
    then \(\sum\lambda_iF_i\in I\), so \(\lambda_j=(\sum\lambda_iF_i)(P_j)=0\). Thus the \(\barF_i\) are linearly independent
    over \(k\), so \(r\le\dim_k(k[X_1,\dots,X_n]/I)\)

    Conversely if \(V(I)=\{P_1,\dots,P_r\}\) is finite, let \(P_i=(a_{i1},\dots,a_{in})\), and define \(F_j\)
    by \(F_j=\prod_{i=1}^r(X_j-a_{ij})\), \(j=1,\dots,n\). Then \(F_j\in I(V(I))\), so \(F_j^N\in I\) for
    some \(N>0\) (Take \(N\) large enough to work for all \(F_j\)).
    Taking \(I\)-residues, \(\barF_j^N=0\), so \(\barX_j^{rN}\) is a \(k\)-linear combination
    of \(\bar{1},\barX_j,\dots,\barX_j^{rN-1}\). It follows by induction that \(\barX_j^s\) is
    a \(k\)-linear combination of \(\bar{1},\barX_j,\dots,\barX_j^{rN-1}\) for all \(s\), and hence that
    the set \(\{\barX_1^{m_1},\dots,\barX_n^{m_n}\mid m_i<rN\}\) generates \(k[X_1,\dots,X_n]/I\) as a vector space
    over \(k\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.32
    Show that both theorems and all of the corollaries are false if \(k\) is not algebraically closed
    #+END_exercise

    #+BEGIN_proof
    Consider \(h:\R[X]\to\C\) by \(h(X)=i\). Then this is a surjection but \(\R\neq\C\). Thus (*) is false.
    #+END_proof

    #+BEGIN_exercise
    1. Decompose \(V(X^2+Y^2-1,X^2-Z^2-1)\subseteq\A^3(\C)\) into irreducible components
    2. Let \(V=\{(t,t^2,t^3)\in\A^3(\C)\mid t\in\C\}\). Find \(I(V)\) and show that \(V\) is irreducible
    #+END_exercise

    #+BEGIN_proof
    1. \(X^2+Y^2-1=0\wedge X^2-Z^2-1=0\Rightarrow Y=Z=0\wedge X^2=1\)
    2. \(V=V(Y-X^2,Z-X^3)\). Consider \(h:\C[X,Y,Z]\to\C[X]\) by \(h(f(x,y,z))=f(x,x^2,x^3)\). Then
       \(\C[X,Y,Z]/(Y-X^2,Z-X^3)\cong\C[X]\) and hence \((Y-X^2,Z-X^3)\) is prime and so \(I(V)=(Y-X^2,Z-X^3)\)
    #+END_proof

    #+BEGIN_exercise
    Let \(R\) be a UFD
    1. Show that a monic polynomial of degree two or three in \(R[X]\) is irreducible iff it has no
       roots in \(R\)
    2. The polynomial \(X^2-a\in R[X]\) is irreducible iff \(a\) is not a square in \(R\)
    #+END_exercise

    #+BEGIN_exercise
    label:ex1.35
    Show that \(V(Y^2-X(X-1)(X-\lambda))\subset\A^2(k)\) is an irreducible curve for any algebraically closed
    field \(k\), and any \(\lambda\in k\)
    #+END_exercise

    #+ATTR_LATEX: :options [Eisenstein's criterion]
    #+BEGIN_theorem
    Let \(R\) be an integral domain and let \(f=a_0+a_1T+\dots+a_nT^n\in R[T]\) be a polynomial. Suppose
    that there exists a prime ideal \(\fp\) of \(R\) s.t.
    1. \(a_i\in\fp\) for \(i=0,\dots,n-1\)
    2. \(a_n\notin\fp\)
    3. \(a_0\notin\fp^2\)


    Then \(f\) is irreducible in \(R[T]\)
    #+END_theorem


    #+BEGIN_proof
    [[https://math.stackexchange.com/questions/2668988/exercise-1-35-in-fultons-algebraic-curves][Solution]]
    If \(\lambda=0\) and take \(\fp=(x)\). Then \(a_2=1\notin(x)\) and \(a_0=x(x-1)(x-\lambda)\in(x)\) while \(a_0\notin(x^2)\)
    as \(\lambda\neq 0\). Thus \(f(y)\) is irreducible

    Suppose that \(\lambda=0\). Consider \(\fp=(x-1)\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.36
    Let \(I=(Y^2-X^2,Y^2+X^2)\subset\C[X,Y]\). Find \(V(I)\) and \(\dim_{\C}(\C[X,Y]/I)\)
    #+END_exercise

    #+BEGIN_proof
    \(I=(X^2,Y^2)\). Thus element of  \(\C[X,Y]/I\) is of the form \(a+bx+cy+dxy+I\). So \(\{1,x,y,xy\}\)
    is a basis for \(\C[X,Y]/I\)
    #+END_proof

    #+BEGIN_exercise
    label:1.37
    Let \(K\) be any field, \(F\in K[X]\) a polynomial of degree \(n>0\). Show that the
    residues \(\bar{1},\barX,\dots,\barX^{n-1}\) form a basis of \(K[X]/(F)\) over \(K\)
    #+END_exercise

    #+BEGIN_proof
    We can view \(F\) as a monic polynomial. Then every residue has degree less than \(n\).
    Thus \(\bar{1},\barX,\dots,\barX^{n-1}\) generate \(K[X]/(F)\).
    Suppose \(a_0\bar{1}+a_1\barX+\dots+a_{n-1}\barX^{n-1}=\bbar{a_0+a_1X+\dots+a_{n-1}X^{n-1}}=0\). Then
    \(a_0+a_1X+\dots+a_{n-1}X^{n-1}\in(F)\). Hence \(a_0=\dots=a_{n-1}=0\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.38
    Let \(R=k[X_1,\dots,X_n]\), \(k\vDash\ACF\), \(V=V(I)\). Show that there is a natural one-to-one
    correspondence between algebraic subsets of \(V\) and radical ideals in \(k[X_1,\dots,X_n]/I\) and
    that irreducible algebraic sets (resp. points) correspond to prime ideals (resp. maximal ideals)
    #+END_exercise
** Modules; Finiteness Conditions
    Let \(R\) be a ring. An *\(R\)-module* is a commutative group \(M\) together with a scalar
    multiplication

    Let \(R\) be a subring of \(S\).
    1. \(S\) is said to be *module-finite* over \(R\), if \(S\) is finitely generated as
       an \(R\)-module. If \(R\) and \(S\) are fields, and \(S\) is a module finite over \(R\), we
       denote the dimension of \(S\) over \(R\) by \([S:R]\)
    2. Let \(v_1,\dots,v_n\in S\). Let \(\varphi:R[X_1,\dots,X_n]\to S\) be the ring homomorphism taking \(X_i\)
       to \(v_i\). The image of \varphi is written \(R[v_1,\dots,v_n]\). It is a subring of \(S\)
       containing \(R\) and \(v_1,\dots,v_n\), and it is the smallest such ring. The ring \(S\) is
       *ring-finite* over \(R\) if \(S=R[v_1,\dots,v_n]\) for some \(v_1,\dots,v_n\in S\)
    3. Suppose \(R=K,S=L\) are fields. If \(v_1,\dots,v_n\in L\), let \(K(v_1,\dots,v_n)\) be the quotient field
       of \(K[v_1,\dots,v_n]\). We regard \(K(v_1,\dots,v_n)\) as a subfield of \(L\); it is the smallest
       subfield of \(L\) containing \(K\) and \(v_1,\dots,v_n\). The field \(L\) is said to be *finitely
       generated field extension* of \(K\) if \(L=K(v_1,\dots,v_n)\) for some \(v_1,\dots,v_n\in L\)
** Integral Elements
    Let \(R\) be a subring of \(S\). An element \(v\in S\) is *integral* over \(R\) if there is a monic
    polynomial \(F=X^n+a_1X^{n-1}+\dots+a_n\in R[X]\) s.t. \(F(v)=0\). If \(R\) and \(S\) are fields, we
    usually say that \(v\) is *algebraic* over \(R\) if \(v\) is integral over \(R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(R\) be a subring of a domain \(S\), \(v\in S\). TFAE
    1. \(v\) is integral over \(R\)
    2. \(R[v]\) is module-finite over \(R\)
    3. There is a subring \(R'\) of \(S\) containing \(R[v]\) that is module-finite over \(R\)
    #+END_proposition

    #+BEGIN_proof
    \(1\to 2\). If \(v^n+a_1v^{n-1}+\dots+a_n=0\), then \(v^n\in\sum_{i=0}^{n-1}Rv^i\). It follows
    that \(v^m\in\sum_{i=0}^{n-1}Rv^i\) for all \(m\), so \(R[v]=\sum_{i=0}^{n-1}Rv^i\)

    \(2\to 3\). \(R'=R\)

    \(3\to 1\). If \(R'=\sum_{i=1}^nRw_i\), then \(vw_i =\sum_{j=1}^na_{ij}w_j\) for some \(a_{ij}\in R\).
    Then \(\sum_{j=1}^n(\delta_{ij}v-a_{ij})w_j=0\) where \(\delta_{ij}=0\) if \(i\neq j\) and 1 otherwise. If we
    consider these equations in the quotient field of \(S\), we see that \((w_1,\dots,w_n)\) is a
    nontrivial solution, so \(\det(\delta_{ij}v-a_{ij})=0\). Since \(v\) appears only in the diagonal of
    the matrix, this determinant has the form \(v^n+a_1v^{n-1}+\dots+a_n\), \(a_i\in R\). So \(v\) is
    integral over \(R\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The set of elements of \(S\) that are integral over \(R\) is a subring of \(S\) containing \(R\)
    #+END_corollary

    #+BEGIN_proof
    If \(a,b\) are integral over \(R\), then \(b\) is integral over \(R[a]\supset R\), so \(R[a,b]\) is
    module-finite over \(R\). And \(a\pm b,ab\in R[a,b]\), so \(R[a\pm b],R[ab]\subset R[a,b]\), so they are
    integral over \(R\) by the proposition
    #+END_proof

    \(S\) is *integral* over \(R\) if every element of \(S\) is integral over \(R\). If \(R\)
    and \(S\) are fields, \(S\) is an *algebraic extension* of \(R\) if \(S\) is integral over \(R\)

    #+BEGIN_exercise
    label:ex1.46
    Let \(R\) be a subring of \(S\), \(S\) a subring of (a domain) \(T\). If \(S\) is integral
    over \(R\), \(T\) is integral over \(S\), then \(T\) is integral over \(R\)
    #+END_exercise

    #+BEGIN_proof
    Let \(z\in T\), then \(z^n+a_1z^{n-1}+\dots+a_n=0\), \(a_i\in S\). Then \(R[a_1,\dots,a_n,z]\) is module-finite
    over \(R\). Then \(R[a_1,\dots,a_n,z]\supset R[z]\) is module finite and hence \(z\) is integral over \(R\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.47
    Suppose (a domain) \(S\) is ring-finite over \(R\). Show that \(S\) is module-finite over \(R\)
    iff \(S\) is integral over \(R\)
    #+END_exercise

    #+BEGIN_proof
    Suppose \(S=R[s_1,\dots,s_n]\) where \(s_1,\dots,s_n\in S\). \(S\) is integral over \(R\) \(\Leftrightarrow\) \(s_1,\dots,s_n\)
    are integral over \(R\).
    #+END_proof

    #+BEGIN_exercise
    label:ex1.48
    Let \(L\) be a field, \(k\) an algebraically closed subfield of \(L\)
    1. Show that any element of \(L\) that is algebraic over \(k\) is already in \(k\)
    #+END_exercise

    #+BEGIN_proof
    Suppose \(t\in L\) and \(t^n+a_1t^{n-1}+\dots+a_n=0\) where \(a_1,\dots,a_n\in k\). Then \(t\) is integral
    over \(k[a_1,\dots,a_n]\) and hence
    #+END_proof
