#+TITLE: Algebra
#+AUTHOR: Serge Lang
#+EXPORT_FILE_NAME: ../latex/Algebra/Algebra.tex
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \def \Map {\operatorname{Map}}
#+LATEX_HEADER: \def \ev {\text{ev}}
* Groups
** Monoids
** Groups
** Normal Subgroups
   Let \(f:G\to G'\) be a group homomorphism, and let \(H\) be its kernel. If \(x\) is an element
   of \(G\), then \(xH=Hx\), because both are equal to \(f^{-1}(f(x))\). We can also rewrite this
   relation as \(xHx^{-1}=H\)

   Conversely, let \(G\) be a group and let \(H\) be a subgroup. Assume that for all
   elements \(x\in G\), we have \(xH\subset Hx\) (or equivalently, \(xHx^{-1}\subset H\)), which
   implies \(H\subset xHx^{-1}\). Thus our condition is equivalent to the condition \(xHx^{-1}=H\) for
   all \(x\in G\). A subgroup \(H\) satisfying this condition will be called *normal*

   Let \(G'\) be the set of cosets of \(H\). (A left coset is equal to a right coset). If \(xH\)
   and \(yH\) are cosets, then their product
   \begin{equation*}
   xHyH=xyHH=xyH
   \end{equation*}
   is also a coset. Hence \(G'\) is a group.

   Let \(f:G\to G'\) be the mapping s.t. \(f(x)\) is the coset \(xH\). Then \(f\) is clearly a
   homomorphism and \(H\) is equal to the kernel.

   The group of cosets of a normal subgroup \(H\) is denoted by \(G/H\) (which we read \(G\)
   modulo \(H\), or \(G\) mod \(H\)). The map \(f\) of \(G\) onto \(G/H\) constructed above is
   called the *canonical map*, and \(G/H\) is called the *factor group* of \(G\) by \(H\)
* Rings
** Rings and Homomorphisms
   A *ring* \(A\) is a set
   1. w.r.t. addition, \(A\) is a commutative group
   2. the multiplication is associative, and has a unit element
   3. for all \(x,y,z\in A\) we have
      \begin{equation*}
      (x+y)z=xz+yz \quad\text{ and }\quad z(x+y)=zx+zy
      \end{equation*}
   (called *distributivity*)

   We denote the unit element for addition by 0, and the unit element for multiplication by 1.
   Observe that \(0x=0\) for all \(x\in A\). /Proof:/ \(0x+x=(0+1)x=x\)

   For any \(x,y\in A\) we have \((-x)y=-(xy)\)

   Let \(A\) be a ring, and let \(U\) be the set of elements of \(A\) which have both a right and
   left inverse. Then \(U\) is a multiplicative group. Indeed, if \(a\) has a right inverse \(b\),
   so that \(ab=1\), and a left inverse \(c\), so that \(ca=1\), then \(cab=b\), whence \(c=b\), and
   we see that \(c\) is a two-sided inverse, and that \(c\) itself has a two-sided inverse,
   namely \(a\). Therefore \(U\) satisfies all the axioms of a multiplicative group, and is called
   the group of *units* of \(A\). It is sometimes denoted by \(A^*\), and is also called the group of
   *invertible* elements of \(A\). A ring \(A\) s.t. \(1\neq 0\) and s.t. every non-zero element is
   invertible is called a *division ring*.

   #+ATTR_LATEX: :options [The Shift Operator]
   #+BEGIN_examplle
   Let \(E\) be the set of all sequences
   \begin{equation*}
   a=(a_1,a_2,a_3,\dots`)
   \end{equation*}
   of integers. One can define addition componentwise. Let \(R\) be the set of all
   mappings \(f:E\to E\) of \(E\) into itself s.t. \(f(a+b)=f(a)+f(b)\). Then \(R\) is a ring. Let
   \begin{equation*}
   T(a_1,a_2,a_3,\dots)=(0,a_1,a_2,a_3,\dots)
   \end{equation*}
   Verify that \(T\) is left invertible but not right invertible
   #+END_examplle

   A ring \(A\) is said to be *commutative* if \(xy=yx\) for all \(x,y\in A\). A commutative division
   ring is called a *field*. By definition, a field contains at least two elements, namely 0 and 1.

   A subset \(B\) of ring \(A\) is called a *subring* if it is an additive subgroup, if it contains
   the multiplicative unit, and if \(x,y\in B\) implies \(xy\in B\). If that is the case, then \(B\) is
n   itself a ring, the laws of operation in \(B\) being the same as the laws of operation in \(A\)

   For example, the *center* of a ring \(A\) is the subset of \(A\) consisting of all
   elements \(a\in A\) s.t. \(ax=xa\) for all \(x\in A\). The center of \(A\) is a subring.

   If \(x,y_1,\dots,y_n\) are elements of a ring, then by induction one sees that
   \begin{equation*}
   x(y_1+\dots+y_n)=xy_1+\dots+xy_n
   \end{equation*}
   If \(x_i(i=1,\dots,n)\) and \(y_j(j=1,\dots,m)\) are elements of \(A\), then it is also easily proved that
   \begin{equation*}
   \left( \sum_{i=1}^nx_i \right)\left( \sum_{j=1}^my_j \right)=
   \sum_{i=1}^n\sum_{j=1}^mx_iy_j
   \end{equation*}
   Furthermore, distributivity holds for subtraction, e.g.
   \begin{equation*}
   x(y_1-y_2)=xy_1-xy_2
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(S\) be a set and \(A\) a ring. Let \(\Map(S,A)\) be the set of mappings of \(S\)
   into \(A\). Then \(\Map(S,A)\) is a ring if for \(f,g\in\Map(S,A)\) we define
   \begin{equation*}
   (fg)(x)=f(x)g(x)\quad\text{ and }\quad (f+g)(x)=f(x)+g(x)
   \end{equation*}
   for all \(x\in S\).

   Let \(M\) be an additive abelian group, and let \(A\) be the set \(\End(M)\) of
   group-homomorphisms of \(M\) into itself. We define addition in \(A\) to be the addition of
   mappings, and we define multiplication to be *composition* of mappings
   #+END_examplle

   #+ATTR_LATEX: :options [The convolution product]
   #+BEGIN_examplle
   Let \(G\) be a group and let \(K\) be a field. Denote by \(K[G]\) the set of all formal linear
   combinations \(\alpha=\sum a_xx\) with \(x\in G\) and \(a_x\in K\), s.t. all but finite number of \(a_x\) are
   equal to 0. If \(\beta=\sum b_xx\in K[G]\), then one can define the product
   \begin{equation*}
   \alpha\beta=\sum_{x\in G}\sum_{y\in G}a_xb_yxy=\sum_{z\in G}\left( \sum_{xy=z}a_xb_y \right)z
   \end{equation*}
   With this product, the *group ring* \(K[G]\) is a ring. \(K[G]\) is commutative iff \(G\) is
   commutative. The second sum on the right  defines what is called a *convolution product*.
   If \(f,g\) are functions on a group \(G\), we define their *convolution* \(f*g\) by
   \begin{equation*}
   (f*g)(z)=\sum_{xy=z}f(x)g(y)
   \end{equation*}
   #+END_examplle

   A *left ideal* \(\fa\) in a ring \(A\) is a subset of \(A\) which is a subgroup of the additive group
   of \(A\), s.t. \(A\fa\subset\fa\) (and hence \(A\fa=\fa\) since \(A\) contains 1). To define a right ideal, we
   quire \(\fa A=\fa\), and a *two-sided ideal* is a subset which is both a left and right ideal. A
   two-sided ideal is called an *ideal* in this section.

   If \(A\) is a ring and \(a\in A\), then \(Aa\) is a left ideal, called *principal*. We say that \(a\)
   is a generator of \(\fa\) (over \(A\)). \(AaA\) is a principal two-sided ideal
   if \(AaA=\{\sum x_iay_i\mid x_i,y_i\in A\}\). More generally, let \(a_1,\dots,a_n\in A\). We denote by \((a_1,\dots,a_n)\)
   the set of elements of \(A\) which can be written in the form
   \begin{equation*}
   x_1a_1+\dots+x_na_n\quad\text{with}\quad x_i\in A
   \end{equation*}
   Then this set of elements is immediately verified to be a left ideal, and \(a_1,\dots,a_n\) are called
   *generators* of the left ideal.

   If \(\{\fa_i\}_{i\in I}\) is a family of ideals, then their intersection
   \begin{equation*}
   \bigcap_{i\in I}\fa_i
   \end{equation*}
   is also an ideal

   A *commutative* ring s.t. every ideal is principal and s.t. \(1\neq 0\) is called a *principal* ring

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The integers \(\Z\) form a ring, which is commutative. Let \(\fa\) be an ideal \(\neq\Z\) and \(\neq 0\).
   If \(n\in\fa\) then \(-n\in\fa\). Let \(d\) be the smallest integer \(>0\) lying in \(\fa\). If \(n\in\fa\)
   then there exists integers \(q,r\) with \(0\le r<d\) s.t.
   \begin{equation*}
   n=dq+r
   \end{equation*}
   Since \(\fa\) is an ideal, it follows that \(r\) lies in \(\fa\), hence \(r=0\). Hence \(\fa\) consists
   of all multiples \(qd\) of \(d\), which \(q\in\Z\), and \(\Z\) is a principal ring.
   #+END_examplle

   Let \(\fa,\fb\) be ideals of \(A\). We define \(\fa\fb\) to be the set of all sums
   \begin{equation*}
   x_1y_1+\dots+x_ny_n
   \end{equation*}
   with \(x_i\in\fa\) and \(y_i\in\fb\). \(\fa\fb\) is an ideal, and that the set of ideals forms a multiplicative
   monoid, the unit element being the ring itself. This unit element is called the *unit ideal* and is
   often written (1).

   If \(\fa,\fb\) are left ideals of \(A\), then \(\fa+\fb\) (the sum being taken as additive subgroup
   of \(A\)) is obviously a left ideal. Thus ideals also form a monoid under addition. We also have
   distributivity: if \(\fa_1,\dots,\fa_n,\fb\) are ideals of \(A\), then
   \begin{equation*}
   \fb(\fa_1+\dots+\fa_n)=\fb\fa_1+\dots+\fb\fa_n
   \end{equation*}

   Let \(\fa\) be a left ideal. Define \(\fa A\) to be the set of all sums \(a_1x_1+\dots+a_nx_n\)
   with \(a_i\in\fa\) and \(x_i\in A\). Then \(\fa A\) is an ideal.

   Suppose that \(A\) is commutative. Let \(\fa,\fb\) be ideals. Then trivially
   \begin{equation*}
   \fa\fb\subset\fa\cap\fb
   \end{equation*}
   If \(\fa+\fb=A\) then \(\fa\fb=\fa\cap \fb\).  Suppose \(x\in\fa\cap\fb\) and \(x=a_x+b_x\), where \(a_x\in\fa\) and \(b_x\in\fb\).
   Then \(a_x\in\fb\) and \(b_x\in\fa\). If \(1=a_1+b_1\) then \(x\cdot 1=(a_x+b_x)(a_1+b_1)\in\fa\fb\)

   [[index:ring homomorphism]]
   By a *ring homomorphism* one means a mapping \(f:A\to B\) where \(A,B\) are rings, and s.t. \(f\) is
   a monoid-homomorphism for the multiplicative structures on \(A\) and \(B\), and also a monoid
   homomorphism for the additive structure. In other words
   \begin{alignat*}{2}
   &f(a+a')=f(a)+f(a')\quad&&f(aa')=f(a)f(a')\\
   &f(1)=1&&f(0)=0
   \end{alignat*}
   for all \(a,a'\in A\).

   The kernel of a ring homomorphism \(f:A\to B\) is an ideal of \(A\).

   Conversely, let \(\fa\) be an ideal of the ring \(A\). We can construct the *factor ring* \(A/\fa\) as
   follows. Viewing \(A\) and \(\fa\) as additive groups, let \(A/\fa\) be the factor group. If \(x+\fa\)
   and \(y+\fa\) are two cosets of \(\fa\), we define \((x+\fa)(y+\fa)\) to be the coset \(xy+\fa\). This
   coset is well-defined, for if \(x_1,y_1\) are in the same coset as \(x,y\) respectively, then one
   verifies that \(x_1y_1\) is in the same coset as \(xy\). Unit element is \(1+\fa\).

   We therefore defined a ring structure on \(A/\fa\) and the caonical map
   \begin{equation*}
   f:A\to A/\fa
   \end{equation*}
   is then clearly a ring homomorphism

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If \(g:A\to A'\) is a ring homomorphism whose kernel contains \(\fa\), then there exists a unique
   ring homomorphism \(g_*:A/\fa\to A'\) making the following diagram commutative
   \begin{center}\begin{tikzcd}[column sep=small]
   A\ar[rr,"g"]\ar[rd,"f"']&&A'\\
   &A/\fa\ar[ur,"g_*"']
   \end{tikzcd}\end{center}

   #+END_proposition

   Indeed, viewing \(f,g\) as group homomorphisms, there is a unique group homomorphism \(g_*\)
   making our diagram commutative

   #+BEGIN_proof
   If \(x\in A\) then \(g(x)=g_*f(x)\). Hence for \(x,y\in A\)
   \begin{align*}
   g_*(f(x)f(y))&=g_*(f(xy))=g(xy)=g(x)g(y)\\
   &=g_*f(x)g_*f(y)
   \end{align*}
   Given \(\xi,\eta\in A/\fa\), there exists \(x,y\in A\) s.t. \(f(x)=\xi\) and \(f(y)=\eta\). Since \(f(1)=1\), we
   get \(g_*f(1)=g(1)=1\) and hence the two conditions that \(g_*\) be a multiplicative
   monoid-homomorphism are satisfied
   #+END_proof

   Let \(A\) be a ring, and denote its unit element by \(e\) for the moment. The map
   \begin{equation*}
   \lambda:\Z\to A
   \end{equation*}
   s.t. \(\lambda(n)=ne\) is a ring homomorphism, and its kernel is an ideal \((n)\), generated by an
   integer \(n\ge 0\). We have a canonical injective homomorphism \(\Z/n\Z\to A\) which is a (ring)
   isomorphism between \(\Z/n\Z\) and a subring of \(A\). If \(n\Z\) is a prime ideal, then \(n=0\)
   or \(n=p\) for some prime number \(p\). In the first place, \(A\) contains as a subring a ring
   which is isomorphic to \(\Z\), and which is often identified with \(\Z\). In that case, we say
   that \(A\) has *characteristic* 0. if on the other hand \(n=p\) then we say that \(A\) has
   *characteristic* \(p\), and \(A\) contains (an isomorphic image of) \(\Z/p\Z\) as a subring. We
   abbreviate \(\Z/p\Z\) by \(\F_p\).

   If \(K\) is a field, then \(K\) has characteristic 0 or \(p>0\). (if its characteristic
   is \(a\cdot b\), then \(a\cdot b\cdot 1=0\) but field is an integral domain). In the first case, \(K\)
   contains as a subfield an isomorphic image of the rational numbers, and in the second case, it
   contains an isomorphic image of \(\F_p\). In either case, this subfield will be called the *prime
   field* (contained in \(K\)). Since this prime field is the smallest subfield of \(K\) containing 1
   and has no automorphism except the identity, it is customary to identiy it with \(\Q\) or \(\F_p\)
   as the case may be. By the *prime ring* (in \(K\)) we shall mean either the integers \(\Z\) if \(K\)
   has characteristic 0 or \(\F_p\) if \(K\) has characteristic \(p\). <<Problem1>>

   Let \(A\) be a subring of a ring \(B\). Let \(S\) be a subset of \(B\) commuting with \(A\). We
   denote by \(A[S]\) the set of all elements
   \begin{equation*}
   \sum a_{i_1\dots i_n}s_1^{i_1}\dots s_n^{i_n}
   \end{equation*}
   the sum ranging over a finite number of \(n\)-tuples \((i_1,\dots,i_n)\) of integers \(\ge 0\),
   and \(a_{i_1,\dots,i_n}\in A\), \(s_1,\dots,s_n\in S\). If \(B=A[S]\) , we say that \(S\) is a set of
   *generators* (or *ring generators*) for \(B\) over \(A\), or that \(B\) is *generated* by \(S\)
   over \(A\). If \(S\) is finite, \(B\) is *finitely generated as a ring over* \(A\). Note that \(S\)
   is not commutative.

   Let \(A\) be a ring, \(\fa\) an ideal, and \(S\) a subset of \(A\). We write
   \begin{equation*}
   S\equiv 0\mod \fa
   \end{equation*}
   if \(S\subset\fa\). If \(x,y\in A\) we write
   \begin{equation*}
   x\equiv y\mod\fa
   \end{equation*}
   if \(x-a\in\fa\).  If \(\fa\) is principal, equal to \((a)\), then we also write
   \begin{equation*}
   x\equiv y\mod a
   \end{equation*}
   If \(f:A\to A/\fa\) is the canonical homomorphism, then \(x\equiv y\mod\fa\) means that \(f(x)=f(y)\)

   The factor ring \(A/\fa\) is also called a *residue class ring*. Cosets of \(\fa\) in \(A\) are called
   *residue classes* modulo \(\fa\), and if \(x\in A\), then the coset \(x+\fa\) is called the *residue class*
   *of \(x\) modulo \(\fa\)*

   An injective ring homomorphism \(f:A\to B\) establishes a ring isomorphism between \(A\) and its
   image. Such a homomorphism will be called an *embedding*

   Let \(f:A\to A'\) be a ring homomorphism, and let \(\fa'\) be an ideal of \(A'\). Then \(f^{-1}(a')\)
   is an ideal \(\fa\) in \(A\), and we have an induced injective homomorphism
   \begin{equation*}
   A/\fa\to A'/\fa'
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Products exist in the category of rings
   #+END_proposition

   Let \(A\) be a ring. Elements \(x,y\in A\) are said to be *zero divisors* if \(x\neq 0\), \(y\neq 0\)
   and \(xy=0\). A ring \(A\) is *entire* if \(1\neq 0\), if \(A\) is commutative and if there are no
   zero divisors in the ring. (Entire rings are also called *integral domains*)

   Let \(m\) be a positive integer \(\neq 1\). The ring \(\Z/m\Z\) has zero divisors iff \(m\) is not
   prime.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(A\) be an entire ring, and let \(a,b\) be non-zero elements of \(A\). Then \(a,b\) generate
   the same ideal iff there exists a unit \(u\) of \(A\) s.t. \(b=au\).
   #+END_proposition

   #+BEGIN_proof
   Assume \(Aa=Ab\). Then \(a=bc\) and \(b=ad\) for some \(c,d\in A\). Hence \(a=adc\)
   whence \(a(1-dc)=0\) and therefore \(dc=1\). Hence \(c\) is a unit
   #+END_proof

** Commutative Rings
   Assume \(A\) is commutative

   A *prime* ideal in \(A\) is an ideal \(\fp\neq A\) s.t. \(A/\fp\) is entire. Equivalently, we could say
   that it is an ideal \(\fp\neq A\) s.t. whenever \(x,y\in A\) and \(xy\in\fp\) then \(x\in\fp\) or \(y\in\fp\). A
   prime ideal is often called simply a *prime*

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every maximal ideal is prime
   #+END_proposition

   #+BEGIN_proof
   Let \(\fm\) be maximal and let \(x,y\in A\) s.t. \(xy\in\fm\). Suppose \(x\not\in\fm\), then \(\fm+Ax\) is an
   ideal properly containing \(\fm\), hence equal to \(A\). Hence we can write
   \begin{equation*}
   1=u+ax
   \end{equation*}
   with \(u\in\fm\) and \(a\in A\). Multiplying by \(y\) we find
   \begin{equation*}
   y=yu+axy
   \end{equation*}
   whence \(y\in\fm\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(\fa\) be an ideal \(\neq A\). Then \(\fa\) is contained in some maximal ideal \(\fm\)
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The ideal \(\{0\}\) is a prime ideal of \(A\) iff \(A\) is entire
   #+END_proposition

   The only ideals of a field are itself and the zero ideal

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If \(\fm\) is a maximal ideal of \(A\), then \(A/\fm\) is a field
   #+END_proposition

   #+BEGIN_proof
   If \(x\in A\), we denote by \(\barx\) its residue class mod \(\fm\). Since \(\fm\neq A\) we note
   that \(A/\fm\)  has a unit element \(\neq 0\). Any non-zero element of \(A/\fm\) can be written
   as \(\barx\) for some \(x\in A\), \(x\not\in\fm\). To find its inverse, note that \(\fm+Ax\) is an ideal
   of \(A\neq\fm\) and hence equal to \(A\). Hence we can write
   \begin{equation*}
   1=u+yx
   \end{equation*}
   with \(u\in\fm\) and \(y\in A\). This means that \(\bary\barx=1=\bar{1}\) and hence that \(\barx\) has
   an inverse.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(f:A\to A'\) be a homomorphism of commutative rings. Let \(\fp'\) be a prime ideal of \(A'\) and
   let \(\fp=f^{-1}\fp'\). Then \(\fp\) is prime
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(\Z\) be the ring of integers. Since an ideal is also an additive subgroup of \(\Z\), every
   ideal \(\neq\{0\}\) is principal, of the form \(n\Z\) for some integer \(n>0\). ([[https://math.stackexchange.com/questions/101348/show-that-every-ideal-of-the-ring-mathbb-z-is-principal][proof]])

   Let \(\fp\) be a prime ideal \(\neq\{0\}\), \(\fp=n\Z\). Then \(n\) must be a prime number. Conversely,
   if \(p\) is a prime number, then \(p\Z\) is a prime ideal. Furthermore, \(p\Z\) is a maximal ideal.
   Suppose \(p\Z\) is contained in some ideal \(n\Z\), then \(p=nm\) for some integer \(m\),
   whence \(n=p\) or \(n=1\), thereby proving \(p\Z\) maximal
   #+END_examplle

   if \(n\) is an integer, the factor ring \(\Z/n\Z\) is called the ring of *integers modulo* \(n\). We
   also denote
   \begin{equation*}
   \Z/n\Z=\Z(n)
   \end{equation*}
   If \(n\) is a prime number \(p\), then the ring of integers modulo \(p\) is in fact a field,
   denoted by \(\F_p\). In particular, the multiplicative group of \(\F_p\) is called the group of
   non-zero integers modulo \(p\). From the elementary properties of groups, we get a standard fact
   of elementary number theory: if \(x\) is an integer \(\neq 0\mod p\), then \(x^{p-1}\equiv 1\mod p\)
   (Fermat's Theorem). Similarly given an integer \(n>1\), the units in the ring \(\Z/n\Z\) consist
   of those residue class mod \(n\Z\) which are represented by integers \(m\neq 0\) and prime to \(n\).
   The order of the group of units in \(\Z/n\Z\) is called by definition \(\varphi(n)\) (where \varphi is known as
   the *Euler phi-function*). Consequently, if \(x\) is an integer prime to \(n\),
   then \(x^{\varphi(n)}\equiv 1\mod n\)


   #+ATTR_LATEX: :options [Chinese Remainder Theorem]
   #+BEGIN_theorem
   Let \(\fa_1,\dots,\fa_n\) be ideals of \(A\) s.t. \(\fa_i+\fa_j=A\) for all \(i\neq j\). Given
   elements \(x_1,\dots,x_n\in A\) ,there exists \(x\in A\) s.t. \(x\equiv x_i\mod\fa_i\) for all \(i\)
   #+END_theorem

   #+BEGIN_proof
   For \(n=2\) we have an expression
   \begin{equation*}
   1=a_1+a_2
   \end{equation*}
   for some \(a_i\in\fa_i\), and we let \(x=x_2a_1+x_1a_2\)

   For each \(i\ge 2\) we can find elements \(a_i\in\fa_1\) and \(b_i\in\fa_i\) s.t.
   \begin{equation*}
   a_i+b_i=1,\quad i\ge 2
   \end{equation*}
   The products \(\prod_{i=2}^n(a_i+b_i)\) is equal to 1, and lies in
   \begin{equation*}
   \fa_1+\prod_{i=2}^n\fa_i
   \end{equation*}
   Hence
   \begin{equation*}
   \fa_1+\prod_{i=2}^n\fa_i=A
   \end{equation*}
   By theorem for \(n=2\), we can find an element \(y_1\in A\) s.t.
   \begin{align*}
   &y_1\equiv 1\mod\fa_1\\
   &y_1\equiv 0\mod\prod_{i=2}^n\fa_i
   \end{align*}
   We find similarly elements \(y_2,\dots,y_n\) s.t.
   \begin{equation*}
   y_j\equiv 1\mod\fa_j \quad\text{ and }\quad y_j\equiv 0\mod\fa_i\text{ for }i\neq j
   \end{equation*}
   Then \(x=x_1y_1+\dots+x_ny_n\) satisfies our requirements
   #+END_proof

   In the same vein as above, we observe that if \(\fa_1,\dots,\fa_n\) are ideals of a ring \(A\) s.t.
   \begin{equation*}
   \fa_1+\dots+\fa_n=A
   \end{equation*}
   and if \(v_1,\dots,v_n\) are positive integers, then
   \begin{equation*}
   \fa_1^{v_1}+\dots+\fa_n^{v_n}=A
   \end{equation*}
   <<Problem2>>

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(\fa_1,\dots,\fa_n\) be ideals of \(A\). Assume that \(\fa_i+\fa_j=A\) for \(i\neq j\). Let
   \begin{equation*}
   f:A\to\prod_{i=1}^nA/\fa_i=(A/\fa_1)\times\dots\times(A/\fa_n)
   \end{equation*}
   be the map of \(A\) into the product induced by the canonical map of \(A\) onto \(A/\fa_i\) for each
   factor. Then the kernel of \(f\) is \(\bigcap_{i=1}^n\fa_i\) and \(f\) is surjective, thus giving an
   isomorphism
   \begin{equation*}
   A/\bigcap\fa_i\cong\prod A/\fa_i
   \end{equation*}
   #+END_corollary

   #+BEGIN_proof
   Surjectivity follows from the theorem
   #+END_proof

   Let \(m\) be an integer \(>1\), and let
   \begin{equation*}
   m=\prod_ip_i^{r_i}
   \end{equation*}
   be a factorization of \(m\) into primes, with exponents \(r_i\ge 1\). Then we have a ring
   isomorphism
   \begin{equation*}
   \Z/m\Z\cong\prod_i\Z/p_i^{r_i}\Z
   \end{equation*}
   If \(A\) is a ring, we denote as usual by \(A^*\) the multiplicative group of invertible elements
   of \(A\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The preceding ring isomorphism of \(\Z/m\Z\) onto the product induces a group isomorphism
   \begin{equation*}
   (\Z/m\Z)^*\cong\prod_i(\Z/p_i^{r_i}\Z)^*
   \end{equation*}
   #+END_proposition

   In view of our isomorphism, we have
   \begin{equation*}
   \varphi(m)=\prod_i\varphi(p_i^{r_i})
   \end{equation*}
   If \(p\) is a prime number and \(r\) an integer \(\ge 1\), then
   \begin{equation*}
   \varphi(p^r)=(p-1)p^{r-1}
   \end{equation*}
   If \(r=1\), then \(\Z/p\Z\) is a field, and the multiplicative group of that field has
   order \(p-1\). Let \(r\) be \(\ge 1\), and consider the canonical ring homomorphism
   \begin{equation*}
   \Z/p^{r+1}\Z\to\Z/p^r\Z
   \end{equation*}
   arising from the inclusion of ideals \((p^{r+1})\subset(p^r)\). We get an induced group homomorphism
   \begin{equation*}
   \lambda:(Z/p^{r+1}\Z)^*\to(\Z/p^r\Z)^*
   \end{equation*}
   which is surjective because any integer \(a\) which represents an element of \(\Z/p^r\Z\) and is
   prime to \(p\) will represent an element of \((\Z/p^{r+1}\Z)^*\). Let \(a\) be an integer
   representing an element of \((\Z/p^{r+1}\Z)^*\) s.t. \(\lambda(a)=1\). Then
   \begin{equation*}
   a\equiv 1\mod p^{r}\Z
   \end{equation*}
   P96

   *Application: The ring of endomorphisms of a cyclic group*.
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \(A\) be a cyclic group of order \(n\). For each \(k\in\Z\) let \(f_k:A\to A\) be the
   endomorphism \(x\mapsto kx\) (writing \(A\) additively). Then \(k\mapsto f_k\) induces a ring
   homomorphism \(\Z/n\Z\cong\End(A)\), and a group isomorphism \((\Z/n\Z)^*\cong\Aut(A)\)
   #+END_theorem

   #+BEGIN_proof
   The fact that \(k\mapsto f_k\) is ring homomorphism is a restatement of the formulas
   \begin{equation*}
   1a=a,\quad (k+k')a=ka+k'a,\quad (kk')a=k(k'a)
   \end{equation*}
   #+END_proof


** Polynomials and Group Rings
   Consider an infinite cyclic group generated by an element \(X\). We let \(S\) be the subset
   consisting of powers \(X^r\) with \(r\ge 0\). Then \(S\) is a monoid. We define the set of
   *polynomials* \(A[X]\) to be the set of functions \(S\to A\) which are equal to 0 except for a finite
   number  of elements of \(S\). For each element \(a\in A\) we denote by \(aX^n\) the function which
   has the value \(a\) on \(X^n\) and the value 0 for all other elements of \(S\). Then it is
   immediate that a polynomial can be written uniquely as a finite sum
   \begin{equation*}
   a_0X^0+\dots+a_nX^n
   \end{equation*}
   for some integer \(n\in\N\) and  \(a_i\in A\). Such a polynomial is denoted by \(f(X)\). The
   elements \(a_i\in A\) are called the *coefficients* of \(f\). We define the product according to the
   convolution rule. Thus, given polynomials
   \begin{equation*}
   f(X)=\sum_{i=0}^na_iX^i \quad\text{ and }\quad g(X)=\sum_{j=0}^mb_jX^j
   \end{equation*}
   we define the product to be
   \begin{equation*}
   f(X)g(X)=\sum_{k=0}^{m+n}\left( \sum_{i+j=k}a_ib_j \right)X^k
   \end{equation*}
   This product is associative and distributive. \(1X^0\) is the unit element.  There is also an
   embedding
   \begin{gather*}
   A\to A[X]\\
   a\mapsto aX^0
   \end{gather*}
   Let \(A\) be a subring of a commutative ring \(B\). Let \(x\in B\). If \(f\in A[X]\) is a polynomial,
   we define the associated *polynomial function*
   \begin{equation*}
   f_B:B\to B
   \end{equation*}
   by letting
   \begin{equation*}
   f_B(x)=f(x)=a_0+a_1x+\dots+a_nx^n
   \end{equation*}
   Given an element \(b\in B\), directly from the definition of multiplication of polynomials, we find
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The association
   \begin{equation*}
   \ev_b:f\mapsto f(b)
   \end{equation*}
   is a ring homomorphism of \(A[X]\) into \(B\)
   #+END_proposition

   This homomorphism is called the *evaluation homomorphism*, and is also said to be obtained by
   *substituting* \(b\) for \(X\) in the polynomial

   Let \(x\in B\). We see that the subring \(A[x]\) of \(B\) generated by \(x\) over \(A\) is a ring
   of all polynomial values \(f(x)\) for \(f\in A[X]\). If the evaluation map \(f\mapsto f(x)\) gives an
   isomorphism of \(A[X]\) with \(A[x]\), then we say that \(x\) is *transcendental* over \(A\), or
   that \(x\) is a *variable* over \(A\). In particular, \(X\) is a variable over \(A\)

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(\alpha=\sqrt{2}\). Then the set of all real numbers of the form \(a+b\alpha\), with \(a,b\in\Z\) is a
   subring of the real numbers, generated by \(\sqrt{2}\). \alpha is not transcendental over \(\Z\),
   because the polynomial \(X^2-2\) lies in the kernel of the evaluation map \(f\mapsto f(\sqrt{2})\). On
   the other hand, it can be shown that \(e\) and \pi are transcendental over \(\Q\)
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(p\) be a prime number and let \(K=\Z/p\Z\). Then \(K\) is a field. Let \(f(X)=X^p-X\in K[X]\).
   Then \(f\) is not the zero polynomials. But \(f_K\) is the zero function. Indeed, \(f_K(0)=0\).
   If \(x\in K\), \(x\neq 0\), then since the multiplicative group of \(K\) has order \(p-1\). it follows
   that \(x^{p-1}=1\), whence \(x^p=x\), so \(f(x)\). Thus a non-zero polynomial gives rise to the
   zero function on \(K\)
   #+END_examplle

   Let
   \begin{equation*}
   \varphi:A\to B
   \end{equation*}
   be a homomorphism of commutative rings. Then there is an associated homomorphism of the
   polynomial rings \(A[X]\to B[X]\) s.t.
   \begin{equation*}
   f(X)=\sum a_iX^i\mapsto\sum\varphi(a_i)X^i=(\varphi f)(X)
   \end{equation*}
   We call \(f\mapsto\varphi f\) the *reduction map*

   Let \(\fp\) be a prime ideal of \(A\). Let \(\varphi:A\to A'\) be the canonical homomorphism of \(A\)
   onto \(A/\fp\). If \(f(X)\) is a polynomial in \(A[X]\), then \(\varphi f\) will sometimes be called the
   *reduction of \(f\) modulo \(\fp\)*.

   For example, taking \(A=\Z\) and \(\fp=(p)\) for some prime number \(p\), we can speak of the
   polynomial \(3X^4-X+2\) as a polynomial mod 5, viewing the coefficients as elements of \(\Z/5\Z\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(\varphi:A\to B\) be a homomorphism of commutative rings. Let \(x\in B\). There is a unique
   homomorphism extending \varphi
   \begin{equation*}
   A[X]\to B\quad\text{ s.t. }\quad X\mapsto x
   \end{equation*}
   and for this homomorphism \(\sum a_iX^i\mapsto\sum\varphi(a_i)x^i\)
   #+END_proposition

   The homomorphism of the above statement may be views as the composite
   \begin{center}\begin{tikzcd}
   A[X\ar[r]]&B[X]\ar[r,"\ev_x"]&B
   \end{tikzcd}\end{center}

   When writing a polynomial \(f(X)=\displaystyle\sum_{i=1}^na_iX^i\), if \(a_n\neq 0\) then we define \(n\) to be the
   *degree* of \(f\). Thus the degree of \(f\) is the smallest integer \(n\) s.t. \(a_r=0\)
   for \(r>n\). If \(f=0\) (i.e. \(f\) is the zero polynomial), then by convention, we define the
   degree of \(f\) to be \(-\infty\). We agree to the convention that
   \begin{equation*}
   -\infty+-\infty=-\infty,\quad-\infty+n=-\infty,\quad-\infty<n
   \end{equation*}
   for all \(n\in\Z\), and no other operation with \(-\infty\) is defined. A polynomial of degree 1 is also
   called a *linear* polynomial. If \(f\neq 0\) and \(\deg f=n\) then we call \(a_n\) the *leading
   coefficient* of \(f\). We call \(a_0\) its *constant term*

   Let
   \begin{equation*}
   g(X)=b_0+\dots+b_mX^m
   \end{equation*}
   be a polynomial in \(A[X]\), of degree \(m\), and assume \(g\neq 0\). Then
   \begin{equation*}
   f(X)g(X)=a_0b_0+\dots+a_nb_mX^{m+n}
   \end{equation*}
   Therefore
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If we assume that at least one of the leading coefficients \(a_n\) or \(b_m\) is not a divisor of
   0 in \(A\), then
   \begin{equation*}
   \deg(fg)=\deg f+\deg g
   \end{equation*}
   and the leading coefficient of \(fg\) is \(a_nb_m\). This holds in particular when \(a_n\)
   or \(b_m\) is a unit in \(A\), or when \(A\) is entire. Consequently, when \(A\) is
   entire, \(A[X]\) is also entire
   #+END_proposition

   If \(f=0\) or \(g=0\) we still have
   \begin{equation*}
   \deg(fg)=\deg f+\deg g
   \end{equation*}
   if we agree that \(-\infty+m=-\infty\) for any integer \(m\)

   Let \(A\) be a subring of a commutative ring \(B\). Let \(x_1,\dots,x_n\in B\). For each \(n\)-tuple of
   integers \((v_1,\dots,v_n)=\bv\in\N^n\), let \(\bx=(x_1,\dots,x_n)\), and
   \begin{equation*}
   M_{\bv}(\bx)=x_1^{v_1}\dots x_n^{v_n}
   \end{equation*}
   The set of such elements forms a monoid under multiplication. Let \(A[x]=A[x_1,\dots,x_n]\) be the
   subring of \(B\) generated by \(x_1,\dots,x_n\) over \(A\). Then every element of \(A[x]\) can be
   written as a finite sum
   \begin{equation*}
   \sum a_{\bv}M_{\bv}(\bx) \quad\text{ and }\quad a_{\bv}\in A
   \end{equation*}

   Using the construction of polynomials in one variable repeatedly, we may form the ring
   \begin{equation*}
   A[X_1,\dots,X_n]=A[X_1][X_2]\dots[X_n]
   \end{equation*}
   selecting \(X_n\) to be variable over \(A[X_1,\dots,X_{n-1}]\). Then every element \(f\)
   of \(A[X_1,\dots,X_n]=A[X]\) has a /unique/ expression as a finite sum
   \begin{equation*}
   f=\sum_{j=0}^{d_n}f_j(X_1,\dots,X_{n-1})X_n^j \quad\text{with}\quad f_j\in A[X_1,\dots,X_{n-1}]
   \end{equation*}
   Therefore by induction we can write \(f\) uniquely as a sum
   \begin{align*}
   f&=\sum_{v_n=0}^{d_n}\left(
   \sum_{v_1,\dots,v_{n-1}}a_{v_1\dots v_n}X_1^{v_1}\dots X_{n-1}^{v_{n-1}} \right)X^{v_n}_n\\
   &=\sum a_{\bv}M_{\bv}(X)=\sum a_{\bv}X_1^{v_1}\dots X_n^{v_n}
   \end{align*}
   with elements \(a_{\bv\in A}\), which are called the *coefficients* of \(f\). The products
   \begin{equation*}
   M_{\bv}(X)=X_1^{v_1}\dots X_n^{v_n}
   \end{equation*}
   will be called *primitive monomials*. Elements of \(A[X]\) are called *polynomials* (in \(n\)
   variables). We call \(a_{\bv}\) its *coefficients*

   GIven \(\bx=(x_1,\dots,x_n)\) and \(f\), we define
   \begin{equation*}
   f(x)=\sum a_{\bv}M_{\bv}(\bx)=\sum a_{\bv}x_1^{v_1}\dots x_n^{v_n}
   \end{equation*}
   Then the *evaluation map*
   \begin{equation*}
   \ev_{\bx}:A[X]\to B \quad\text{with}\quad f\mapsto f(x)
   \end{equation*}
   is a ring homomorphism

   Elements \(x_1,\dots,x_n\in B\) are called *algebraically independent* over \(A\) if the evaluation map
   \begin{equation*}
   f\mapsto f(x)
   \end{equation*}
   is injective. Equivalently, we could say that if \(f\in A[X]\) is a polynomial and \(f(x)=0\)
   then \(f=0\).; in other words, there are no non-trivial polynomial relations among \(x_1,\dots,x_n\)
   over \(A\).

   By the *degree* of a primitive monomial
   \begin{equation*}
   M_{\bv}(X)=X_1^{v_1}\dots X_n^{v_n}
   \end{equation*}
   we shall mean the integer \(\abs{v}=v_1+\dots+v_n\)

   A polynomial
   \begin{equation*}
   aX_1^{v_1}\dots X_n^{v_n}\quad(a\in A)
   \end{equation*}
   will be called a *monomial*

   If \(f(X)\) is a polynomial in \(A[X]\) written as
   \begin{equation*}
   f(X)=\sum a_{\bv}X_1^{v_1}\dots X_n^{v_n}
   \end{equation*}
   we define the *degree* of \(f\) to be the maximum of the degrees of the monomials \(M_{\bv}(X)\)
   s.t. \(a_{\bv}\neq 0\). (Such monomials are said to *occur* in the polynomial)

   For each integer \(d\ge 0\), given a polynomial \(f\), let \(f^{(d)}\) be the sum of all monomials
   occuring in \(f\) and having degree \(d\). Then
   \begin{equation*}
   f=\sum_df^{(d)}
   \end{equation*}
   Suppose \(f\neq 0\), we say that \(f\) is *homogeneous* of degree \(d\) if \(f=f^{(d)}\)

   Algebraically independent elements will also be called *variables*

** Localization
   \(A\) a commutative ring

   By a *multiplicative subset* of \(A\) we shall mean a submonoid of \(A\)

   We shall now construct the *quotient ring of \(A\) by \(S\)*, also known as the *ring of fractions*
   *of \(A\) by \(S\)*

   We consider pairs \((a,s)\) with \(a\in A\) and \(s\in S\). We define a relation
   \begin{equation*}
   (a,s)\sim (a',s')
   \end{equation*}
   if there exists \(s_1\in S\) s.t.
   \begin{equation*}
   s_1(s'a-sa')=0
   \end{equation*}
   The equivalence class containing a pair \((a,s)\) is denoted by \(a/s\). The set of equivalence
   classes is denoted by \(S^{-1}A\)

   if \(0\in  S\), then \(S^{-1}A\) has precisely one element \(0/1\)
   \begin{gather*}
   (a/s)(a'/s')=aa'/ss'\\
   \frac{a}{s}+\frac{a'}{s'}=\frac{s'a+sa'}{ss'}
   \end{gather*}

   Let \(\varphi_S:A\to S^{-1}A\) be the s.t. \(\varphi_S(a)=a/1\). Every element of \(\varphi_S(S)\) is invertible
   in \(S^{-1}(A)\) (the inverse of \(s/1\) is \(1/s\))

   Let \(\calc\) be the category whose objects are ring homomorphism
   \begin{equation*}
   f:A\to B
   \end{equation*}
   s.t. for every \(s\in S\) the elements \(f(s)\) is invertible in \(B\). If \(f:A\to B\) and

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(A\) be an entire ring, and let \(S\) be a multiplicative subset which does not contain 0.
   Then
   \begin{equation*}
   \varphi_S:A\to S^{-1}A
   \end{equation*}
   is injective
   #+END_proposition

   Let \(A\) be an entire ring, and let \(S\) be the set of non-zero elements of \(A\). Then \(S\)
   is a multiplicative set, and \(S^{-1}A\) is then a field, called the *quotient field* or the *field
   of fractions of \(A\).



* Modules

** Basic Definitions
   Let \(A\) be a ring. A *left module* over \(A\), or a left \(A\)-module \(M\) is an abelian group,
   together with an operation of \(A\) on \(M\), s.t. for all \(a,b\in A\) and \(x,y\in M\)
   \begin{equation*}
   (a+b)x=ax+bx \quad\text{ and }\quad a(x+y)=ax+ay
   \end{equation*}

   Let \(A\) be an entire ring and let \(M\) be an \(A\)-module. We define the *torsion
   submodule* \(M_{tor}\) to be the subset of elements \(x\in M\) s.t. there exist\(a\in A\)s , \(a\neq 0\)
   s.t. \(ax=0\).

      By a *module homomorphism* we means a map
   \begin{equation*}
   f:M\to M'
   \end{equation*}
   which is an additive group homomorphism and s.t.
   \begin{equation*}
   f(ax)=af(x)
   \end{equation*}
   for all \(a\in A\) and \(x\in M\). If we wish to refer to the ring \(A\), we also say that \(f\) is
   an *\(A\)-homomorphism*, or also that it is an *\(A\)-linear map*

   For any module \(M\) and \(M'\), the map \(\zeta:M\to M'\) s.t.
   \(\zeta(x)=0\) for all \(x\in M\) is a homomorphism, called *zero*

   Let \(f:M\to M'\) be a homomorphism. By the *cokernel* of \(f\) we mean the factor module
   \(M'\im f=M'/f(M)\).

   Like groups
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(N,N'\) be two submodules of a module of \(M\). Then \(N+N'\) is also a submodule, and we
   have an isomorphism
   \begin{equation*}
   N/(N\cap N')\cong(N+N')/N'
   \end{equation*}
   If \(M\supset M'\supset M''\) are modules, then
   \begin{equation*}
   (M/M'')/(M'/M'')\cong M/M'
   \end{equation*}
   If \(f:M\to M'\) is a module homomorphism, and \(N'\) is a submodule of \(M'\), then \(f^{-1}(N')\)
   is a submodule of \(M\) and we have a canonical injective homomorphism
   \begin{equation*}
   \barf:M/f^{-1}(N')\to M'/N'
   \end{equation*}
   If \(f\) is surjective, then \(\barf\) is a module isomorphism
   #+END_proposition

   A sequence of module homomorphisms
   \begin{center}\begin{tikzcd}
   M'\ar[r,"f"]&M\ar[r,"g"]&M''
   \end{tikzcd}\end{center}
   is *exact* if \(\im f=\ker g\). If \(N\) is a submodule of \(M\), then
   \begin{center}\begin{tikzcd}
   0\ar[r]&N\ar[r]&M\ar[r]&M/N\ar[r]&0
   \end{tikzcd}\end{center}

   If a homomorphism \(u:N\to M\) is s.t.
   \begin{center}\begin{tikzcd}
   0\ar[r]&N\ar[r,"u"]&M
   \end{tikzcd}\end{center}

   is exact, then we also say that \(u\) is a *monomorphism* or an *embedding*. Dually
   if
   \begin{center}\begin{tikzcd}
   N\ar[r,"u"]&M\ar[r]&0
   \end{tikzcd}\end{center}
   is exact, we say that \(u\) is an *epimorphism*

   Let \(A\) be a commutative ring. Let \(E,F\) be modules. By a *bilinear map*
   \begin{equation*}
   g:E\times E\to F
   \end{equation*}
   we mean a map s.t. given \(x\in E\) the map \(y\mapsto g(x,y)\) is \(A\)-linear and given \(y\in E\), the
   map \(x\mapsto g(x,y)\) is \(A\)-linear. By an *\(A\)-algebra* we mean a module together with a bilinear
   map \(g:E\times E\to E\) . We view such a map as a law of composition on \(E\).

** The Group of Homomorphisms
   Let \(A\) be a ring, and let \(X,X'\) be \(A\)-modules. We denote by \(\Hom_A(X',X)\) the set
   of \(A\)-homomorphisms of \(X'\) into \(X\). Then \(\Hom_A(X',X)\) is an abelian group, the law
   of addition being that of addition for mappings into an abelian group.

   If \(A\) is /commutative/ then we can make \(\Hom_A(X',X)\) into an \(A\)-module by defining \(af\)
   for \(a\in A\) and \(f\in\Hom_A(X',X)\) to be the map s.t.
   \begin{equation*}
   (af)(x)=af(x)
   \end{equation*}

   Let \(Y\) be an \(A\)-module, and let
   \begin{center}\begin{tikzcd}
   X'\ar[r,"f"]&X
   \end{tikzcd}\end{center}
   be an \(A\)-homomorphism. Then we get an induced homomorphism
   \begin{equation*}
   \Hom_A(f,Y):\Hom_{A}(X,Y)\to\Hom_A(X',Y)
   \end{equation*}
   given by \(g\mapsto g\circ f\). The fact that \(\Hom_A(f,Y)\) is a homomorphism is a rephrasing of the
   \((g_1+g_2)\circ f=g_1\circ f+g_2\circ f\)

   If we have a sequence of \(A\)-homomorphisms
   \begin{center}\begin{tikzcd}
   X'\ar[r]&X\ar[r]&X''
   \end{tikzcd}\end{center}
   then we get an induced sequence
   \begin{center}\begin{tikzcd}
   \Hom_A(X',Y)&\Hom_A(X,Y)\ar[l]&\Hom_A(X'',Y)\ar[l]
   \end{tikzcd}\end{center}

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A sequence
   \begin{center}\begin{tikzcd}
   X'\ar[r,"\lambda"]&X\ar[r]&X''\ar[r]&0
   \end{tikzcd}\end{center}
   is exact iff the sequence
   \begin{center}\begin{tikzcd}
   \Hom_A(X',Y)&\Hom_A(X,Y)\ar[l]&\Hom_A(X'',Y)\ar[l]&0\ar[l]
   \end{tikzcd}\end{center}
   is exact for all \(Y\)

   #+END_proposition


* Algebraic Extensions
** Finite and Algebraic Extensions
   Let \(F\) be a field. If \(F\) is a subfield of a field \(E\), then we also say that \(E\) is an
   *extension field* of \(F\). We may view \(E\) as a vector space over \(F\), and we say \(E\) is
   *finite* or *infinite* extension of \(F\) according as the dimension of this vector space is finite
   or infinite.

   Let \(F\) be a subfield of a field \(E\). An element \alpha of \(E\) is said to be *algebraic*
   over \(F\) if there exists elements \(a_0,\dots,a_n\in F\), not all equal to 0, s.t.
   \begin{equation*}
   a_0+a_1\alpha+\dots+a_n\alpha^n=0
   \end{equation*}
   If \(\alpha\neq 0\), and \alpha is algebraic, then we can always find elements \(a_i\) as above s.t. \(a_0\neq 0\)

   Let \(X\) be a variable over \(F\). We can also say that \alpha is algebraic over \(F\) if the
   homomorphism
   \begin{equation*}
   F[X]\to E
   \end{equation*}
   which is the identity on \(F\) and maps \(X\) on \alpha has a non-zero kernel. In that case the kernel
   is an ideal which is principal, generated by a single polynomial \(p(X)\), which we may assume
   has leading coefficient 1. We then have an isomorphism
   \begin{equation*}
   F[X]/(p(X))\cong F[\alpha]
   \end{equation*}
* Real Fields
** Ordered Fields
    Let \(K\) be a field. An *ordering* of \(K\) is a subset \(P\) of \(K\)
    having the following properties
    \bigskip
    \begin{itemize}[itemindent=3em]
    \item[\textbf{ORD 1.}] Given \(x\in K\), we have either \(x\in P\) ,or \(x=0\) or
    \(-x\in P\), and these three possibilities are mutually exclusive
    \item[\textbf{ORD 2.}] If \(x,y\in P\), then \(x+y,xy\in P\)
    \end{itemize}

    \(K\) is *ordered by* \(P\), and we call \(P\) the set of *positive
    elements*

    Suppose \(K\) is ordered by \(P\). Since \(1\neq0\) and \(1=1^2=(-1)^2\), we
    see that \(1\in P\). By *ORD 2*, it follows that \(1+\dots+1\in P\), whence \(K\)
    has characteristic 0. If \(x\in P\) and \(x\neq0\), then \(xx^{-1}=1\in P\) implies
    that \(x^{-1}\in P\)

    #+BEGIN_center
    /Let \(E\) be a field. Then a product of sums of squares in \(E\) is a sum
    of squares./

    /If \(a,b\in E\) are sum of squares and \(b\neq0\), then \(a/b\) is a sum of
    squares/
    #+END_center

    Consider complex number:)

    Let \(x,y\in K\). We define \(x<y\) to mean that \(y-x\in P\). If \(x<0\) we say
    that \(x\) is *negative*.

    If \(K\) is ordered and \(x\in K\), \(x\neq0\), then \(x^2\) is positive

    If \(E\) has characteristic \(\neq2\), and \(-1\) is a sum of squares in \(E\),
    then every element \(a\in E\) is a sum of squares, because
    \(4a=(1+a)^2-(1-a)^2\)

    If \(K\) is a field with an ordering \(P\), and \(F\) is a subfield, then
    obviously, \(P\cap F\) defines an ordering of \(F\), which is called the
    *induced* ordering

    Let \(K\) be an ordered field and let \(F\) be a subfield with the induced
    ordering. We put \(\abs{x}=x\) if \(x>0\) and \(\abs{x}=-x\) if \(x<0\). An
    element \(\alpha\in K\) is *infinitely large* over \(F\) if \(\abs{\alpha}\ge x\) for all
    \(x\in F\). It is *infinitely small* over \(F\) if \(0\le\abs{\alpha}\le\abs{x}\) for
    all \(x\in F\), \(x\neq0\). \alpha is infinitely large if and only if \(\alpha^{-1}\) is
    infinitely small. \(K\) is *archimedean* over \(F\) if \(K\) has no elements
    which are infinitely large over \(F\). An intermediate field \(F_1\),
    \(K\supset F_1\supset F\) is *maximal archimedean over* \(F\) in \(K\) if it is
    archimedean over \(F\) and no other intermediate field containing \(F_1\) is
    archimedean over \(F\). We say that \(F\) is *maximal archimedean in* \(K\)
    if it is maximal archimedean over itself in \(K\)

    Let \(K\) be an ordered field and \(F\) a subfield. Let \(K\) be an ordered
    field and \(F\) a subfield. Let \(\fo\) be the set of elements of \(K\)
    which are not infinitely large over \(F\). Then \(\fo\) is a ring and that
    for any \(\alpha\in K\), we have \(\alpha\) or \(\alpha^{-1}\in\fo\). Hence \(\fo\) is what is
    called a valuation ring, containing \(F\). Let \(\fm\) be the ideal of all
    \(\alpha\in K\) which are infinitely small over \(F\). Then \(\fm\) is the unique
    maximal ideal of \(\fo\), because any element in \(\fo\) which is not in
    \(\fm\) has an inverse in \(\fo\). We call \(\fo\) the
    *valuation ring determined by the ordering of* \(K/F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(K\) be an ordered field and \(F\) a subfield. Let \(\fo\) be the
    valuation ring determined by the ordering of \(K/F\), and let \(\fm\) be its
    maximal ideal. Then \(\fo/\fm\) is a real field.
    #+END_proposition

    #+BEGIN_proof
    Otherwise, we could write
    \begin{equation*}
    -1=\displaystyle\sum\alpha_i^2+a
    \end{equation*}
    with \(\alpha_i\in\fo\) and \(a\in\fm\). Since \(\sum\alpha_i^2\) is positive and \(a\) is
    infinitely small, such a relation is clearly impossible
    #+END_proof
* COMMENT Problem
  <<Problem1>>

  <<Problem2>>
