#+TITLE: Algebra
#+AUTHOR: Serge Lang
#+EXPORT_FILE_NAME: ../latex/Algebra/Algebra.tex
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \def \Map {\operatorname{Map}}

* Rings
** Rings and Homomorphisms
   A *ring* \(A\) is a set
   1. w.r.t. addition, \(A\) is a commutative group
   2. the multiplication is associative, and has a unit element
   3. for all \(x,y,z\in A\) we have
      \begin{equation*}
      (x+y)z=xz+yz \quad\text{ and }\quad z(x+y)=zx+zy
      \end{equation*}
   (called *distributivity*)

   We denote the unit element for addition by 0, and the unit element for multiplication by 1.
   Observe that \(0x=0\) for all \(x\in A\). /Proof:/ \(0x+x=(0+1)x=x\)

   For any \(x,y\in A\) we have \((-x)y=-(xy)\)

   Let \(A\) be a ring, and let \(U\) be the set of elements of \(A\) which have both a right and
   left inverse. Then \(U\) is a multiplicative group. Indeed, if \(a\) has a right inverse \(b\),
   so that \(ab=1\), and a left inverse \(c\), so that \(ca=1\), then \(cab=b\), whence \(c=b\), and
   we see that \(c\) is a two-sided inverse, and that \(c\) itself has a two-sided inverse,
   namely \(a\). Therefore \(U\) satisfies all the axioms of a multiplicative group, and is called
   the group of *units* of \(A\). It is sometimes denoted by \(A^*\), and is also called the group of
   *invertible* elements of \(A\). A ring \(A\) s.t. \(1\neq 0\) and s.t. every non-zero element is
   invertible is called a *division ring*.

   #+ATTR_LATEX: :options [The Shift Operator]
   #+BEGIN_examplle
   Let \(E\) be the set of all sequences
   \begin{equation*}
   a=(a_1,a_2,a_3,\dots`)
   \end{equation*}
   of integers. One can define addition componentwise. Let \(R\) be the set of all
   mappings \(f:E\to E\) of \(E\) into itself s.t. \(f(a+b)=f(a)+f(b)\). Then \(R\) is a ring. Let
   \begin{equation*}
   T(a_1,a_2,a_3,\dots)=(0,a_1,a_2,a_3,\dots)
   \end{equation*}
   Verify that \(T\) is left invertible but not right invertible
   #+END_examplle

   A ring \(A\) is said to be *commutative* if \(xy=yx\) for all \(x,y\in A\). A commutative division
   ring is called a *field*. By definition, a field contains at least two elements, namely 0 and 1.

   A subset \(B\) of ring \(A\) is called a *subring* if it is an additive subgroup, if it contains
   the multiplicative unit, and if \(x,y\in B\) implies \(xy\in B\). If that is the case, then \(B\) is
   itself a ring, the laws of operation in \(B\) being the same as the laws of operation in \(A\)

   For example, the *center* of a ring \(A\) is the subset of \(A\) consisting of all
   elements \(a\in A\) s.t. \(ax=xa\) for all \(x\in A\). The center of \(A\) is a subring.

   If \(x,y_1,\dots,y_n\) are elements of a ring, then by induction one sees that
   \begin{equation*}
   x(y_1+\dots+y_n)=xy_1+\dots+xy_n
   \end{equation*}
   If \(x_i(i=1,\dots,n)\) and \(y_j(j=1,\dots,m)\) are elements of \(A\), then it is also easily proved that
   \begin{equation*}
   \left( \sum_{i=1}^nx_i \right)\left( \sum_{j=1}^my_j \right)=
   \sum_{i=1}^n\sum_{j=1}^mx_iy_j
   \end{equation*}
   Furthermore, distributivity holds for subtraction, e.g.
   \begin{equation*}
   x(y_1-y_2)=xy_1-xy_2
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(S\) be a set and \(A\) a ring. Let \(\Map(S,A)\) be the set of mappings of \(S\)
   into \(A\). Then \(\Map(S,A)\) is a ring if for \(f,g\in\Map(S,A)\) we define
   \begin{equation*}
   (fg)(x)=f(x)g(x)\quad\text{ and }\quad (f+g)(x)=f(x)+g(x)
   \end{equation*}
   for all \(x\in S\).
   #+END_examplle
* Algebraic Extensions
** Finite and Algebraic Extensions
   Let \(F\) be a field. If \(F\) is a subfield of a field \(E\), then we also say that \(E\) is an
   *extension field* of \(F\). We may view \(E\) as a vector space over \(F\), and we say \(E\) is
   *finite* or *infinite* extension of \(F\) according as the dimension of this vector space is finite
   or infinite.

   Let \(F\) be a subfield of a field \(E\). An element \alpha of \(E\) is said to be *algebraic*
   over \(F\) if there exists elements \(a_0,\dots,a_n\in F\), not all equal to 0, s.t.
   \begin{equation*}
   a_0+a_1\alpha+\dots+a_n\alpha^n=0
   \end{equation*}
   If \(\alpha\neq 0\), and \alpha is algebraic, then we can always find elements \(a_i\) as above s.t. \(a_0\neq 0\)

   Let \(X\) be a variable over \(F\). We can also say that \alpha is algebraic over \(F\) if the
   homomorphism
   \begin{equation*}
   F[X]\to E
   \end{equation*}
   which is the identity on \(F\) and maps \(X\) on \alpha has a non-zero kernel. In that case the kernel
   is an ideal which is principal, generated by a single polynomial \(p(X)\), which we may assume
   has leading coefficient 1. We then have an isomorphism
   \begin{equation*}
   F[X]/(p(X))\cong F[\alpha]
   \end{equation*}
* Real Fields
** Ordered Fields
    Let \(K\) be a field. An *ordering* of \(K\) is a subset \(P\) of \(K\)
    having the following properties
    \bigskip
    \begin{itemize}[itemindent=3em]
    \item[\textbf{ORD 1.}] Given \(x\in K\), we have either \(x\in P\) ,or \(x=0\) or
    \(-x\in P\), and these three possibilities are mutually exclusive
    \item[\textbf{ORD 2.}] If \(x,y\in P\), then \(x+y,xy\in P\)
    \end{itemize}

    \(K\) is *ordered by* \(P\), and we call \(P\) the set of *positive
    elements*

    Suppose \(K\) is ordered by \(P\). Since \(1\neq0\) and \(1=1^2=(-1)^2\), we
    see that \(1\in P\). By *ORD 2*, it follows that \(1+\dots+1\in P\), whence \(K\)
    has characteristic 0. If \(x\in P\) and \(x\neq0\), then \(xx^{-1}=1\in P\) implies
    that \(x^{-1}\in P\)

    #+BEGIN_center
    /Let \(E\) be a field. Then a product of sums of squares in \(E\) is a sum
    of squares./

    /If \(a,b\in E\) are sum of squares and \(b\neq0\), then \(a/b\) is a sum of
    squares/
    #+END_center

    Consider complex number:)

    Let \(x,y\in K\). We define \(x<y\) to mean that \(y-x\in P\). If \(x<0\) we say
    that \(x\) is *negative*.

    If \(K\) is ordered and \(x\in K\), \(x\neq0\), then \(x^2\) is positive

    If \(E\) has characteristic \(\neq2\), and \(-1\) is a sum of squares in \(E\),
    then every element \(a\in E\) is a sum of squares, because
    \(4a=(1+a)^2-(1-a)^2\)

    If \(K\) is a field with an ordering \(P\), and \(F\) is a subfield, then
    obviously, \(P\cap F\) defines an ordering of \(F\), which is called the
    *induced* ordering

    Let \(K\) be an ordered field and let \(F\) be a subfield with the induced
    ordering. We put \(\abs{x}=x\) if \(x>0\) and \(\abs{x}=-x\) if \(x<0\). An
    element \(\alpha\in K\) is *infinitely large* over \(F\) if \(\abs{\alpha}\ge x\) for all
    \(x\in F\). It is *infinitely small* over \(F\) if \(0\le\abs{\alpha}\le\abs{x}\) for
    all \(x\in F\), \(x\neq0\). \alpha is infinitely large if and only if \(\alpha^{-1}\) is
    infinitely small. \(K\) is *archimedean* over \(F\) if \(K\) has no elements
    which are infinitely large over \(F\). An intermediate field \(F_1\),
    \(K\supset F_1\supset F\) is *maximal archimedean over* \(F\) in \(K\) if it is
    archimedean over \(F\) and no other intermediate field containing \(F_1\) is
    archimedean over \(F\). We say that \(F\) is *maximal archimedean in* \(K\)
    if it is maximal archimedean over itself in \(K\)

    Let \(K\) be an ordered field and \(F\) a subfield. Let \(K\) be an ordered
    field and \(F\) a subfield. Let \(\fo\) be the set of elements of \(K\)
    which are not infinitely large over \(F\). Then \(\fo\) is a ring and that
    for any \(\alpha\in K\), we have \(\alpha\) or \(\alpha^{-1}\in\fo\). Hence \(\fo\) is what is
    called a valuation ring, containing \(F\). Let \(\fm\) be the ideal of all
    \(\alpha\in K\) which are infinitely small over \(F\). Then \(\fm\) is the unique
    maximal ideal of \(\fo\), because any element in \(\fo\) which is not in
    \(\fm\) has an inverse in \(\fo\). We call \(\fo\) the
    *valuation ring determined by the ordering of* \(K/F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(K\) be an ordered field and \(F\) a subfield. Let \(\fo\) be the
    valuation ring determined by the ordering of \(K/F\), and let \(\fm\) be its
    maximal ideal. Then \(\fo/\fm\) is a real field.
    #+END_proposition

    #+BEGIN_proof
    Otherwise, we could write
    \begin{equation*}
    -1=\displaystyle\sum\alpha_i^2+a
    \end{equation*}
    with \(\alpha_i\in\fo\) and \(a\in\fm\). Since \(\sum\alpha_i^2\) is positive and \(a\) is
    infinitely small, such a relation is clearly impossible
    #+END_proof
