#+TITLE: Basic Topology
#+AUTHOR: M. A. Armstrong

#+EXPORT_FILE_NAME: ../latex/BasicTopology/BasicTopology.tex
#+LATEX_HEADER: \input{preamble.tex}
* Introduction
** Abstract spaces
   We ask for a set \(X\) and for each point \(x\) of \(X\) a nonempty
   collection of subsets of \(X\), called neighbourhoods of \(x\). These
   neighbourhoods are required to satisfy four axioms
   1. \(x\) lies in each of its neighbourhoods
   2. The intersection of two neighbourhoods of \(x\) is itself a neighbourhood
      of \(x\)
   3. If \(N\) is a neighbourhood of \(x\) and if \(U\) is a subset of \(X\)
      which contains \(N\), then \(U\) is a neighbourhood of \(x\)
   4. If \(N\) is a neighbourhood of \(x\) and if \(\mathring{N}\) denotes the set
      \(\{z\in N\mid N\text{ is a neighbourhood of }z\}\), then \(\mathring{N}\) is a
      neighbourhood of \(x\). (The set \(\mathring{N}\) is called the *interior* of \(N\))


   This whole structure is called a *topological space*. The assignment of a
   collection of neighbourhoods satisfying axioms \((1)\to(4)\) to each point
   \(x\in X\) is called a *topology* on the set \(X\).

   Let \(X\) and \(Y\) be topological spaces. A function \(f:X\to Y\) is
   *continuous* if for each point \(x\in X\) and each neighbourhood \(N\) of
   \(f(x)\) in \(Y\) the set\(f^{-1}(N)\) is a neighbourhood of \(x\) in \(X\).
   A function \(h:X\to Y\) is called a *homeomorphism* if it is one-one, onto,
   continuous and has a continuous inverse. When such a function exists, \(X\)
   and \(Y\) are called *homeomorphic* spaces

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. Let \(X\) be a topological space and let \(Y\) be a subset of \(X\). We
      can define a topology on \(Y\) as follows. Given a point \(y\in Y\) take
      the collection of its neighbourhoods in the topological space \(X\) and
      intersect each of these neighbourhood with \(Y\). The resulting sets are
      the neighbourhoods of \(y\) in \(Y\). We say that \(Y\) has the *subspace topology*.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *surface* is a topological space in which each point has a neighbourhood
   homeomorphic to the plane, and for which any two distinct points possess
   disjoint neighbourhoods
   #+END_definition

* Continuity

** Open and closed sets
   Let \(X\) be a topological space and call a subset \(O\) of \(X\) *open* if
   it is a neighbourhood of each of its points. The union of any collection of
   open sets is open by axiom (3) and the intersection of /finite/ number of
   open sets is open by axiom (2).


   Suppose we have a set \(X\) together with a nonempty collection of subsets of
   \(X\), which we call open sets, such that any union of open sets is itself
   open, any finite intersection of open sets is open, and both the whole set
   and the empty set are open. Given a point \(x\) of \(X\), we shall call a
   subset \(N\) of \(x\) a *neighbourhood of* \(x\) if we can find an open set
   \(O\) s.t. \(x\in O\subseteq N\)


   We claim that this definition of neighbourhood makes \(X\) into a topological
   space.

   Verification for axiom (4). Suppose \(N\) is a neighbourhood of \(x\) and let
   \(\mathring{N}\) denote the set of points \(z\) s.t. \(N\) is a neighbourhood of
   \(z\). Choose an open set \(O\) s.t. \(x\in O\subseteq N\). Now \(O\), being
   open, is a neighbourhood of each of its points, so \(O\) is contained in
   \(\mathring{N}\).

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *topology* on a set \(X\) is a nonempty collection of subsets of \(X\),
   called open sets, such that any union of open sets is open, any finite
   intersection of open sets is open, and both \(X\) and the empty set are open.
   A set together with a topology on it is called a *topological space*
   #+END_definition

   The open sets of the "usual" topology on \(\R^n\) are characterized as
   follows. A set \(U\) is open if given \(x\in U\) we can always find a
   positive real number \epsilon s.t. the ball with centre \(x\) and radius
   \epsilon lies entirely in \(U\).

   For *discrete topology* on \(X\), every subset of \(X\) is an open set and we
   call \(X\) discrete space.

   A subset of a topological space is *closed* if its complement is open.

   Consider the set \(A\) on \(\R^2\) whose points \(x,y\) satisfy \(x\ge0\) and
   \(y>0\). This set is neither closed nor open. Take the space \(X\) whose
   points are those points \((x,y)\in\R^2\) s.t. \(x\ge1\) or \(x\le-1\) and
   whose topology is induced from \(\R^2\). The subsets of \(X\) consisting of
   those points with positive first coordinate is both open and closed.

   Let \(A\) be a subset of a topological space \(X\) and call a point \(p\) of
   \(X\) a *limit point* (or accumulation point) of \(A\) if every neighbourhood
   of \(p\) contains at least one point of \(A-\{p\}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. Take \(X\) to be the real line \(\R\), and let \(A\) consist of the points
      \(1/n\), \(n=1,2,\dots\). Then \(A\) has exactly one limit point, namely
      the origin
   2. X the real line, take \(A=[0,1)\). Then each point of \(A\) is a limit
      point of \(A\), and in addition \(1\) is a limit point
   3. Let \(X\subseteq\R^3\) and let \(A\) consist of those points all of whose
      coordinates are rational. Then every point of \(\R^3\) is a limit point of \(A\)
   4. Let \(A\subseteq\R^3\) be the set of points which have integer
      coordinates. Then \(A\) does not have any limit points
   5. Take \(X\) to be the set of all real numebers with the so called
      *finite-complement topology*. Here a set is open if its complement is
      finite or all of \(X\). If we now take \(A\) to be an infinite subset of
      \(X\) (say the set of all integers), then every point of \(X\) is a limit
      point of \(A\). On the other hand a finite subset of \(X\) has no limit
      points in this topology
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   A set is closed if and only if it contains all its limit points
   #+END_theorem

   #+BEGIN_proof
   If \(A\) is closed, its complement \(X-A\) is open. Since an open set is a
   neighbourhood of each of its points, no point of \(X-A\) can be a limit point
   of \(A\).

   Suppose \(A\) contains all its limit point and let \(x\in X-A\). Since \(x\)
   is not a limit point of \(A\), we can find a neighbourhood \(N\) of \(x\)
   which does not meet \(A\). So \(N\) is inside \(X-A\), showing \(X-A\) to be
   a neighbourhood of each of its points and consequently open. Therefore \(A\)
   is clsoed.
   #+END_proof

   The union of \(A\) and all its limit points is called the *closure* of \(A\)
   and is written \(\overbar{A}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The closure of \(A\) is the smallest closed set containing \(A\), in other
   words the intersection of all closed sets which contain \(A\)
   #+END_theorem

   #+BEGIN_proof
   For if \(x\in X-\overbar{A}\), we can find an open neighbourhood \(U\) of \(x\)
   which does not contain any points of \(A\). Since an open set is a
   neighbourhood of each of its points, \(U\) cannot contain any of the limit
   points of \(A\). Therefore we have an open set \(U\) s.t.
   \(x\in U\subseteq X-\overbar{A}\). Consequently \(X-\overbar{A}\) is a
   neighbourhood of each of its points and must be open.

   Now let \(B\) be a closed set which contains \(A\). Then every limit point of
   \(A\) is a limit point of \(B\) and therefore must lie in \(B\) since \(B\)
   is closed. This gives \(\overbar{A}\subseteq B\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   A set is closed if and only if it is equal to its closure
   #+END_corollary

   A set whose closure is the whole space is said to be *dense* in the space

   The *interior* of a set, usually written \(\mathring{A}\), is the union of
   all open sets contained in \(A\). A point lies in \(\mathring{A}\) if and
   only if it's a neighbourhood of \(A\).

   We define the *frontier* of \(A\) to be the \(\overbar{A}\cap\overbar{X-A}\).

   Suppose we have a topology on a set \(X\), and a collection \beta of open set
   s.t. every open set is a union of members of \beta. Then \beta is called a
   *base* for the topology and elements of \beta are called *basic open sets*.
   An equivalent formulation is to ask that given a point \(x\in X\), and a
   neighbourhood \(N\) of \(x\), there is always an element \(B\) of \beta s.t.
   \(x\in B\subseteq N\).

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \beta be a nonempty collection of subsets of a set \(X\). If the
   intersection of any finite number of members of \beta is always in \beta, and
   if \(\bigcup\beta=X\), then \beta is a base for a topology on \(X\)
   #+END_theorem


** Continuous functions
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   A function from \(X\) to \(Y\) is continuous if and only if the inverse image
   of each open set of \(Y\) is open in \(X\)
   #+END_theorem

   A continuous function is often called a *map*

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The composition of two maps is a map
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose \(f:X\to Y\) is continuous, and let \(A\subseteq X\) have the
   subspace topology. Then the restriction \(f|A:A\to Y\) is continuous
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following are equivalent
   1. \(f:X\to Y\) is a map
   2. If \beta is a base for the topology of \(Y\), the inverse image of every
      member of \beta is open in \(X\)
   3. \(f(\overbar{A})\subseteq\overbar{f(A)}\) for any subset \(A\) of \(X\)
   4. \(\overbar{f^{-1}(B)}\subseteq f^{-1}(\overbar{B})\) for any subset \(B\)
      of \(Y\)
   5. The inverse image of each closed set in \(Y\) is closed in \(X\)
   #+END_theorem

   #+BEGIN_proof
   \((2)\to(3)\). \(f(A)\subseteq\overbar{f(A)}\). If \(x\in\overbar{A}-A\) and
   \(f(x)\not\in f(A)\). If \(N\) is a neighbourhood of \(f(x)\) we can find a
   basic open set \(B\) in \beta s.t. \(f(x)\in B\subseteq N\). \(f^{-1}(B)\) is
   open and is therefore a neighbourhood of \(x\). But \(x\) is a limit point of
   \(A\), which means that \(f^{-1}(B)\) must contain a point of \(A\). So
   \(B\), and therefore \(N\), contains a point of \(f(A)\).

   \((3)\to(4)\).
   \(f(\overbar{f^{-1}(B)})\subseteq ff^{-1}(\overbar{B})\Leftrightarrow
   f(\overbar{f^{-1}(B)})\subseteq\overbar{ff^{-1}(B)}\)

   \((4)\to(5)\).
   \(\overbar{f^{-1}(B)}\subseteq f^{-1}(\overbar{B})=f^{-1}(B)\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(C\) denote the unit circle in the complex plane, taken with the
   subspace topology, and give the interval \([0,1)\) the induced topology from
   the real line. Define \(f:[0,1)\to C\) by \(f(x)=e^{2\pi ix}\). \(f\) is
   continuous.
   We can take the set of all open segments of the circle as a base for the
   topology on \(C\). Now if \(S\) is such a segment and if \(S\) does not
   contain the complex number 1, then \(f^{-1}(S)\) is just an open interval of
   the form \((a,b)\) where \(0<a<b<1\). If \(S\) does happen to contain 1, then
   \(f^{-1}(S)\) has the form \([0,a)\cup(b,1)\), where \(0<a<b<1\). This is
   open in \([0,1)\) because it is the intersection of the open set
   \((-1,a)\cup(b,1)\) of the real line with \([0,1)\).

   However its inverse is not continuous. Take \(O\) to be the interval
   \([0,\1/2]\); this is open in \([0,1)\) but its image is not open in \(C\)
   #+END_examplle
