#+TITLE: Basic Topology
#+AUTHOR: M. A. Armstrong

#+EXPORT_FILE_NAME: ../latex/BasicTopology/BasicTopology.tex
#+LATEX_HEADER: \input{../preamble.tex}
* Introduction
** Abstract spaces
   We ask for a set \(X\) and for each point \(x\) of \(X\) a nonempty
   collection of subsets of \(X\), called neighbourhoods of \(x\). These
   neighbourhoods are required to satisfy four axioms
   1. \(x\) lies in each of its neighbourhoods
   2. The intersection of two neighbourhoods of \(x\) is itself a neighbourhood
      of \(x\)
   3. If \(N\) is a neighbourhood of \(x\) and if \(U\) is a subset of \(X\)
      which contains \(N\), then \(U\) is a neighbourhood of \(x\)
   4. If \(N\) is a neighbourhood of \(x\) and if \(\mathring{N}\) denotes the set
      \(\{z\in N\mid N\text{ is a neighbourhood of }z\}\), then \(\mathring{N}\) is a
      neighbourhood of \(x\). (The set \(\mathring{N}\) is called the *interior* of \(N\))


   This whole structure is called a *topological space*. The assignment of a
   collection of neighbourhoods satisfying axioms \((1)\to(4)\) to each point
   \(x\in X\) is called a *topology* on the set \(X\).

   Let \(X\) and \(Y\) be topological spaces. A function \(f:X\to Y\) is
   *continuous* if for each point \(x\in X\) and each neighbourhood \(N\) of
   \(f(x)\) in \(Y\) the set\(f^{-1}(N)\) is a neighbourhood of \(x\) in \(X\).
   A function \(h:X\to Y\) is called a *homeomorphism* if it is one-one, onto,
   continuous and has a continuous inverse. When such a function exists, \(X\)
   and \(Y\) are called *homeomorphic* spaces

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. Let \(X\) be a topological space and let \(Y\) be a subset of \(X\). We
      can define a topology on \(Y\) as follows. Given a point \(y\in Y\) take
      the collection of its neighbourhoods in the topological space \(X\) and
      intersect each of these neighbourhood with \(Y\). The resulting sets are
      the neighbourhoods of \(y\) in \(Y\). We say that \(Y\) has the *subspace topology*.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *surface* is a topological space in which each point has a neighbourhood
   homeomorphic to the plane, and for which any two distinct points possess
   disjoint neighbourhoods
   #+END_definition

* Continuity

** Open and closed sets
   Let \(X\) be a topological space and call a subset \(O\) of \(X\) *open* if
   it is a neighbourhood of each of its points. The union of any collection of
   open sets is open by axiom (3) and the intersection of /finite/ number of
   open sets is open by axiom (2).


   Suppose we have a set \(X\) together with a nonempty collection of subsets of
   \(X\), which we call open sets, such that any union of open sets is itself
   open, any finite intersection of open sets is open, and both the whole set
   and the empty set are open. Given a point \(x\) of \(X\), we shall call a
   subset \(N\) of \(x\) a *neighbourhood of* \(x\) if we can find an open set
   \(O\) s.t. \(x\in O\subseteq N\)


   We claim that this definition of neighbourhood makes \(X\) into a topological
   space.

   Verification for axiom (4). Suppose \(N\) is a neighbourhood of \(x\) and let
   \(\mathring{N}\) denote the set of points \(z\) s.t. \(N\) is a neighbourhood of
   \(z\). Choose an open set \(O\) s.t. \(x\in O\subseteq N\). Now \(O\), being
   open, is a neighbourhood of each of its points, so \(O\) is contained in
   \(\mathring{N}\).

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *topology* on a set \(X\) is a nonempty collection of subsets of \(X\),
   called open sets, such that any union of open sets is open, any finite
   intersection of open sets is open, and both \(X\) and the empty set are open.
   A set together with a topology on it is called a *topological space*
   #+END_definition

   The open sets of the "usual" topology on \(\R^n\) are characterized as
   follows. A set \(U\) is open if given \(x\in U\) we can always find a
   positive real number \epsilon s.t. the ball with centre \(x\) and radius
   \epsilon lies entirely in \(U\).

   For *discrete topology* on \(X\), every subset of \(X\) is an open set and we
   call \(X\) discrete space.

   A subset of a topological space is *closed* if its complement is open.

   Consider the set \(A\) on \(\R^2\) whose points \(x,y\) satisfy \(x\ge0\) and
   \(y>0\). This set is neither closed nor open. Take the space \(X\) whose
   points are those points \((x,y)\in\R^2\) s.t. \(x\ge1\) or \(x\le-1\) and
   whose topology is induced from \(\R^2\). The subsets of \(X\) consisting of
   those points with positive first coordinate is both open and closed.

   Let \(A\) be a subset of a topological space \(X\) and call a point \(p\) of
   \(X\) a *limit point* (or accumulation point) of \(A\) if every neighbourhood
   of \(p\) contains at least one point of \(A-\{p\}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   1. Take \(X\) to be the real line \(\R\), and let \(A\) consist of the points
      \(1/n\), \(n=1,2,\dots\). Then \(A\) has exactly one limit point, namely
      the origin
   2. X the real line, take \(A=[0,1)\). Then each point of \(A\) is a limit
      point of \(A\), and in addition \(1\) is a limit point
   3. Let \(X\subseteq\R^3\) and let \(A\) consist of those points all of whose
      coordinates are rational. Then every point of \(\R^3\) is a limit point of \(A\)
   4. Let \(A\subseteq\R^3\) be the set of points which have integer
      coordinates. Then \(A\) does not have any limit points
   5. Take \(X\) to be the set of all real numebers with the so called
      *finite-complement topology*. Here a set is open if its complement is
      finite or all of \(X\). If we now take \(A\) to be an infinite subset of
      \(X\) (say the set of all integers), then every point of \(X\) is a limit
      point of \(A\). On the other hand a finite subset of \(X\) has no limit
      points in this topology
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   A set is closed if and only if it contains all its limit points
   #+END_theorem

   #+BEGIN_proof
   If \(A\) is closed, its complement \(X-A\) is open. Since an open set is a
   neighbourhood of each of its points, no point of \(X-A\) can be a limit point
   of \(A\).

   Suppose \(A\) contains all its limit point and let \(x\in X-A\). Since \(x\)
   is not a limit point of \(A\), we can find a neighbourhood \(N\) of \(x\)
   which does not meet \(A\). So \(N\) is inside \(X-A\), showing \(X-A\) to be
   a neighbourhood of each of its points and consequently open. Therefore \(A\)
   is clsoed.
   #+END_proof

   The union of \(A\) and all its limit points is called the *closure* of \(A\)
   and is written \(\overbar{A}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The closure of \(A\) is the smallest closed set containing \(A\), in other
   words the intersection of all closed sets which contain \(A\)
   #+END_theorem

   #+BEGIN_proof
   For if \(x\in X-\overbar{A}\), we can find an open neighbourhood \(U\) of \(x\)
   which does not contain any points of \(A\). Since an open set is a
   neighbourhood of each of its points, \(U\) cannot contain any of the limit
   points of \(A\). Therefore we have an open set \(U\) s.t.
   \(x\in U\subseteq X-\overbar{A}\). Consequently \(X-\overbar{A}\) is a
   neighbourhood of each of its points and must be open.

   Now let \(B\) be a closed set which contains \(A\). Then every limit point of
   \(A\) is a limit point of \(B\) and therefore must lie in \(B\) since \(B\)
   is closed. This gives \(\overbar{A}\subseteq B\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   A set is closed if and only if it is equal to its closure
   #+END_corollary

   A set whose closure is the whole space is said to be *dense* in the space

   The *interior* of a set, usually written \(\mathring{A}\), is the union of
   all open sets contained in \(A\). A point lies in \(\mathring{A}\) if and
   only if it's a neighbourhood of \(A\).

   We define the *frontier* of \(A\) to be the \(\overbar{A}\cap\overbar{X-A}\).

   Suppose we have a topology on a set \(X\), and a collection \beta of open set
   s.t. every open set is a union of members of \beta. Then \beta is called a
   *base* for the topology and elements of \beta are called *basic open sets*.
   An equivalent formulation is to ask that given a point \(x\in X\), and a
   neighbourhood \(N\) of \(x\), there is always an element \(B\) of \beta s.t.
   \(x\in B\subseteq N\).

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \beta be a nonempty collection of subsets of a set \(X\). If the
   intersection of any finite number of members of \beta is always in \beta, and
   if \(\bigcup\beta=X\), then \beta is a base for a topology on \(X\)
   #+END_theorem

*** Exercise
    #+BEGIN_exercise
    label:ex2.1.5
    If \(A\)is a dense subset of a space \(X\), and if \(O\) is open in \(X\),
    show that \(O\subseteq\overbar{A-O}\)
    #+END_exercise

    #+BEGIN_proof
    Suppose \(O\not\subseteq\overbar{A\cap O}\), then there is \(x\in O\) and
    \(x\not\in\overbar{A\cap O}\). Hence there is a open set \(x\in O_x\) s.t.
    \begin{equation*}
    \overbar{A\cap O}\cap(O_x-\{x\})=\emptyset
    \end{equation*}
    But as \(x\not\in\overbar{A\cap O}\), we have
    \begin{equation*}
    \overbar{A\cap O}\cap O_x=\emptyset
    \end{equation*}
    and consequently, \(A\cap O\cap O_x=\emptyset\). But then, setting \(B=O\cap
    O_x\), \(B\) is open, but \(A\cap B=\emptyset\)
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.10
    Show that the frontier of a set always contains the frontier of its
    interior. How does the frontier of \(A\cup B\) relate to the frontiers of
    \(A\) and \(B\)
    #+END_exercise

    #+BEGIN_proof
    Let \((X,\tau)\) be a topological space, and let \(A\susbet X\). Let
    \(x\in\Fr\interior\). Then
    \begin{equation*}
    x\in\overbar{\interior{A}}\cap\overbar{X-\interior{A}}=
    \overbar{\interior{A}}\cup\overbar{(X-A)\cup(X-\interior{A})}
    \end{equation*}
    Now if \(x\in\overbar{\interior{A}}\) and \(x\in\overbar{X-A}\), we are done.
    So suppose that \(x\in\overbar{\interior{A}}\) and
    \(x\in\overbar{A-\interior{A}}\). But then
    \(x\in\overbar{\interior{A}}\cup\overbar{A-\interior{A}}=\overbar{A}\).

    \(\Fr(A\cup B)\subset\Fr(A)\cup\Fr(B)\)
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.11
    Let \(X\) be the set of real numbers and \beta the family of all subsets of the
    form \(\{x\mid a\le x<b\text{ where }a<b\}\). Prove that \beta is a base for a
    topology on \(X\) and that in this topology each member of \beta is both open
    and closed. Show that this topology does not have a countable base.
    #+END_exercise

    #+BEGIN_proof
    Suppose this topology has a countable base \(\{B_n\}_{n\in\omega}\). Define
    the function \(f:\R\to\N\) as follows: for each \(x\in\R\), let \(f(x)=n\)
    s.t. \(B_n\subset[x,1+x)\)

    Suppose \(x<y\) and \(f(x)=f(y)\). Hence \([x,x+1)\subset[y,y+1)\), a
    contradiction 
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.12
    Show that if \(X\) has a countable base for its topology, then \(X\)
    contains a countable dense subset. A space whose topology has a countable
    base is called a *second countable* space. A space which contains a countable
    dense subset is said to be *separable*.
    #+END_exercise

    #+BEGIN_proof
    Let \(\{B_n\}_{n\in\omega}\) be a countable base for \tau.  By the Axiom of
    Choice, let \(A\) be the elements of elements \(\{a_i\}_{i\in\omega}\) s.t.
    \(a_i\in B_i\). The claim is that \(\overbar{A}=X\)

    Let \(\calo\in\tau\). Then \(\calo=\bigcup_jB_j\). Now, as
    \(A=\bigcup_ix_i\), we have \(A\cap\calo\neq\emptyset\).
    #+END_proof

























** Continuous functions
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm2.6
   A function from \(X\) to \(Y\) is continuous if and only if the inverse image
   of each open set of \(Y\) is open in \(X\)
   #+END_theorem

   A continuous function is often called a *map*

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The composition of two maps is a map
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose \(f:X\to Y\) is continuous, and let \(A\subseteq X\) have the
   subspace topology. Then the restriction \(f|A:A\to Y\) is continuous
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following are equivalent
   1. \(f:X\to Y\) is a map
   2. If \beta is a base for the topology of \(Y\), the inverse image of every
      member of \beta is open in \(X\)
   3. \(f(\overbar{A})\subseteq\overbar{f(A)}\) for any subset \(A\) of \(X\)
   4. \(\overbar{f^{-1}(B)}\subseteq f^{-1}(\overbar{B})\) for any subset \(B\)
      of \(Y\)
   5. The inverse image of each closed set in \(Y\) is closed in \(X\)
   #+END_theorem

   #+BEGIN_proof
   \((2)\to(3)\). \(f(A)\subseteq\overbar{f(A)}\). If \(x\in\overbar{A}-A\) and
   \(f(x)\not\in f(A)\). If \(N\) is a neighbourhood of \(f(x)\) we can find a
   basic open set \(B\) in \beta s.t. \(f(x)\in B\subseteq N\). \(f^{-1}(B)\) is
   open and is therefore a neighbourhood of \(x\). But \(x\) is a limit point of
   \(A\), which means that \(f^{-1}(B)\) must contain a point of \(A\). So
   \(B\), and therefore \(N\), contains a point of \(f(A)\).

   \((3)\to(4)\).
   \(f(\overbar{f^{-1}(B)})\subseteq ff^{-1}(\overbar{B})\Leftrightarrow
   f(\overbar{f^{-1}(B)})\subseteq\overbar{ff^{-1}(B)}\)

   \((4)\to(5)\).
   \(\overbar{f^{-1}(B)}\subseteq f^{-1}(\overbar{B})=f^{-1}(B)\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(C\) denote the unit circle in the complex plane, taken with the
   subspace topology, and give the interval \([0,1)\) the induced topology from
   the real line. Define \(f:[0,1)\to C\) by \(f(x)=e^{2\pi ix}\). \(f\) is
   continuous.
   We can take the set of all open segments of the circle as a base for the
   topology on \(C\). Now if \(S\) is such a segment and if \(S\) does not
   contain the complex number 1, then \(f^{-1}(S)\) is just an open interval of
   the form \((a,b)\) where \(0<a<b<1\). If \(S\) does happen to contain 1, then
   \(f^{-1}(S)\) has the form \([0,a)\cup(b,1)\), where \(0<a<b<1\). This is
   open in \([0,1)\) because it is the intersection of the open set
   \((-1,a)\cup(b,1)\) of the real line with \([0,1)\).

   However its inverse is not continuous. Take \(O\) to be the interval
   \([0,\1/2]\); this is open in \([0,1)\) but its image is not open in \(C\)
   #+END_examplle

   A *homeomorphism* \(h:X\to Y\) is a function which is continuous, one-one, and
   onto, and which has continuous inverse. From Theorem ref:thm2.6  we see that
   a set \(O\) is open iff \(h(O)\) is open. Therefore, \(h\) induces a one-one
   onto correspondence between the topologies of \(X\) and \(Y\)

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(S^n\) denote the \(n\)-dimensional sphere whose points are those of
   \(\R^{n+1}\) which have distance 1 from the origin, taken with the subspace
   topology. We claim that removing a single point from \(S^n\) gives a space
   homeomorphic to \(\R^n\).

   Which point we remove is irrelevant because we can rotate any point of
   \(S^n\) into any other; for convenience we choose to remove the point
   \(p=(0,\dots,0,1)\). Now the set of points of \(\R^{n+1}\), which have zero
   as their final coordinate, when given the induced topology, is clearly
   homeomorphic to \(\R^n\). We define a function \(h:S^n-\{p\}\to\E\), called
   *stereographic projection* as follows. If \(x\in S^n-\{p\}\), then \(h(x)\) is
   the point of intersection of \(\R^n\)  and the straight line determined by
   \(x\) and \(p\)

   \begin{center}
      \begin{tikzpicture} % CENT
\newcommand\pgfmathsinandcos[3]{%
  \pgfmathsetmacro#1{sin(#3)}%
  \pgfmathsetmacro#2{cos(#3)}%
}
\newcommand\LongitudePlane[3][current plane]{%
  \pgfmathsinandcos\sinEl\cosEl{#2} % elevation
  \pgfmathsinandcos\sint\cost{#3} % azimuth
  \tikzset{#1/.estyle={cm={\cost,\sint*\sinEl,0,\cosEl,(0,0)}}}
}
\newcommand\LatitudePlane[3][current plane]{%
  \pgfmathsinandcos\sinEl\cosEl{#2} % elevation
  \pgfmathsinandcos\sint\cost{#3} % latitude
  \pgfmathsetmacro\yshift{\cosEl*\sint}
  \tikzset{#1/.estyle={cm={\cost,0,0,\cost*\sinEl,(0,\yshift)}}} %
}
\newcommand\DrawLongitudeCircle[2][1]{
  \LongitudePlane{\angEl}{#2}
  \tikzset{current plane/.prefix style={scale=#1}}
   % angle of "visibility"
  \pgfmathsetmacro\angVis{atan(sin(#2)*cos(\angEl)/sin(\angEl))} %
  \draw[current plane] (\angVis:1) arc (\angVis:\angVis+180:1);
  \draw[current plane,dashed] (\angVis-180:1) arc (\angVis-180:\angVis:1);
}
\newcommand\DrawLatitudeCircle[2][1]{
  \LatitudePlane{\angEl}{#2}
  \tikzset{current plane/.prefix style={scale=#1}}
  \pgfmathsetmacro\sinVis{sin(#2)/cos(#2)*sin(\angEl)/cos(\angEl)}
  % angle of "visibility"
  \pgfmathsetmacro\angVis{asin(min(1,max(\sinVis,-1)))}
  \draw[current plane] (\angVis:1) arc (\angVis:-\angVis-180:1);
  \draw[current plane,dashed] (180-\angVis:1) arc (180-\angVis:\angVis:1);
}

\tikzset{%
  >=latex, % option for nice arrows
  inner sep=0pt,%
  outer sep=2pt,%
  mark coordinate/.style={inner sep=0pt,outer sep=0pt,minimum size=3pt,
    fill=black,circle}%
}
%% some definitions

\def\R{2.5} % sphere radius
\def\angEl{35} % elevation angle
\def\angAz{-105} % azimuth angle
\def\angPhi{-40} % longitude of point P
\def\angBeta{19} % latitude of point P

%% working planes

\pgfmathsetmacro\H{\R*cos(\angEl)} % distance to north pole
\tikzset{xyplane/.estyle={cm={cos(\angAz),sin(\angAz)*sin(\angEl),-sin(\angAz),
                              cos(\angAz)*sin(\angEl),(0,-\H)}}}
\LongitudePlane[xzplane]{\angEl}{\angAz}
\LongitudePlane[pzplane]{\angEl}{\angPhi}
\LatitudePlane[equator]{\angEl}{0}

%% draw xyplane and sphere

\draw[xyplane] (-2*\R,-2*\R) rectangle (2.2*\R,2.8*\R);
\fill[ball color=white] (0,0) circle (\R); % 3D lighting effect
\draw (0,0) circle (\R);

%% characteristic points

\coordinate (O) at (0,0);
\coordinate[mark coordinate] (N) at (0,\H);
\coordinate[mark coordinate] (S) at (0,-\H);
\path[pzplane] (\angBeta:\R) coordinate[mark coordinate] (P);
\path[pzplane] (\R,0) coordinate (PE);
\path[xzplane] (\R,0) coordinate (XE);
\path (PE) ++(0,-\H) coordinate (Paux); % to aid Phat calculation
\coordinate[mark coordinate] (Phat) at (intersection cs: first line={(N)--(P)},
                                        second line={(S)--(Paux)});

%% draw meridians and latitude circles

\DrawLatitudeCircle[\R]{0} % equator
\DrawLongitudeCircle[\R]{\angAz} % xzplane
\DrawLongitudeCircle[\R]{\angAz+90} % yzplane
\DrawLongitudeCircle[\R]{\angPhi} % pzplane

%% draw xyz coordinate system

\draw[xyplane,<->] (1.8*\R,0) node[below] {$x,\xi$} -- (0,0) -- (0,2.4*\R)
    node[right] {$y$};
\draw[->] (0,-\H) -- (0,1.6*\R) node[above] {$z$};

%% draw lines and put labels

\draw[blue,dashed] (P) -- (N) +(0.3ex,0.6ex) node[above left,black] {$\mathbf{N}$};
\draw[blue] (P) -- (Phat) node[above right,black] {$\mathbf{\hat{P}}$};
\path (S) +(0.4ex,-0.4ex) node[below] {$\mathbf{0}$};
\draw (P) node[above right] {$\mathbf{P}$};
\end{tikzpicture}
   \end{center}
   #+END_examplle

   By a *disc* we mean any space homeomorphic to the closed unit disc \(D\) in
   \(\R^2\). \(C\) stands for the unit circle. If \(A\) is a disc, and if
   \(h:A\to D\) is a homeomorphism, then \(h^{-1}(C)\) is called the *boundary* of
   \(A\) and is written \(\partial A\).

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.10
   Any homeomorphism from the boundary of a disc to itself can be extended to a
   homeomorphism of the whole disc
   #+END_lemma

   #+BEGIN_proof
   Let \(A\) be a disc and choose a homeomorphism \(h:A\to D\). Given a
   homeomorphism \(g:\partial A\to\partial A\), we can easily extend \(hgh^{-1}:C\to
   C\) to a homeomorphism of all of \(D\)as follows. Send 0 to 0, and if \(x\in
   D-\{0\}\) send \(x\) to the point \(\norm{x}hgh^{-1}(x/\norm{x})\). In other
   words extend conically
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(A\) and \(B\) be discs which intersect along their boundaries in an
   arc. Then \(A\cup B\) is a disc.
   #+END_lemma

   #+BEGIN_proof
   Let \gamma denote the arc \(A\cap B\), and use \alpha, \beta for the complementary arcs in
   the boundaries of \(A\) and \(B\). We construct a homeomorphism from \(A\cup
   B\) to \(D\) with the aid of lemma ref:lemma2.10

   The \(y\) axis in the plain divides up \(D\) as the union of two discs
   \(D_1\) and \(D_2\). We label the three arcs which together make up the
   boundaries of \(D_1\) and \(D_2\) as \(\alpha'\), \(\beta'\) and \(\gamma'\).
   Both \alpha and \(\alpha'\) are homeomorphic to the clsoed unit interval
   \([0,1]\), so we can find a homeomorphism from \alpha to \(\alpha'\). We first
   extend this over \gamma, to give a homeomorphism from \(\alpha\cup\gamma\) to
   \(\alpha'\cup\gamma'\); then over \(A\) to give a homeomorphism from \(A\) to
   \(D_1\), which take \gamma to \(\gamma'\), using lemma ref:lemma2.10.
   #+END_proof


*** Exercise
    #+BEGIN_exercise
    label:ex2.13
    If \(f:\R\to\R\) is a map, show that the set of points which are left fixed
    by \(f\) is a closed subset of \(\R\). If \(g\) is a continuous real-valued
    function on \(X\) show that the set \(\{x\mid g(x)=0\}\) is closed
    #+END_exercise

    #+BEGIN_proof
    Define \(f_0(x)=f(x)-x\)
    #+END_proof

    #+BEGIN_exercise
    label:ex2.25
    Let \(f:\R\to\R\) be a map and define its graph \(\Gamma_f:\R\to\R^2\) by
    \(\Gamma_f(x)=(x,f(x))\). Show that \(\Gamma_f\) is continuous and that its
    image (taken with the topology induced from \(\R^2\)) is homeomorphic to \(\R\)
    #+END_exercise

    #+BEGIN_proof
    The function \(p_1:\im\Gamma_f\to\E\) defined by \((x,f(x)\mapsto x)\) is
    the desired homeomorphism
    #+END_proof

    #+BEGIN_exercise
    label:ex2.16
    What topology must \(X\) have if every real-valued function defined on \(X\)
    is continuous
    #+END_exercise

    #+BEGIN_proof
    Discrete topology. It suffices to show points in \(X\) are open

    Fix \(x\in X\) and define \(f:X\to\R\) by
    \begin{equation*}
    f(x)=
    \begin{cases}
    f(x)=0\\
    f(y)=1&y\neq x
    \end{cases}
     \end{equation*}
     Then \(f^{-1}((-0.5,0.5))=\{x\}\)
    #+END_proof

    #+BEGIN_exercise
    An *open map* is one which sends open sets to open sets: a *closed map* takes
    closed sets to closed sets. Which of the following maps are open or closed
    1. The exponential map \(x\mapsto e^{ix}\) from the real line to the circle
    2. The folding map \(f:\R^2\to\R^2\) given by \((x,y)\mapsto(x,\abs{y})\)
    3. The map which winds the plane three times on itself given in terms of
       complex numbers, by \(z\mapsto z^3\)
    #+END_exercise

    #+BEGIN_proof
    1.
    2. not open. closed.
    3. open. closed
    #+END_proof
** A space-filling curve
