#+TITLE: Boolean Reasoning: The Logic of Boolean Equations
#+AUTHOR: Frank Markham Brown

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/BooleanReasoning/BooleanReasoning.tex
#+LATEX_HEADER: \def \ceq {\overset{\circ}{=}}
* The Blake Canonical Form
** Definitions and Terminology
   Two SOP formulas will be called *equivalent* (\(\equiv\)) in case they
   represent the same Boolean function. We call two SOP formulas *congruent* (\(\ceq\))in
   case one can be transformed into the other using only the commutative rule.
   Thus congruent SOP formulas may differ only in the order of enumerations of
   their terms and in the order of the literals in any term.

   An *implicant* of a Boolean function \(f\) is a term \(p\) s.t. \(p\le f\).
   
   An SOP formula \(F\) will be called *absorptive* in case no term in \(F\) is
   absorbed by any other term in \(F\). If \(F\) is not absorptive, then an
   equivalent absorptive formula, which we call \(ABS(F)\), may be obtained
   from \(F\) by successive deletion of terms absorbed by other terms in \(F\).
** Syllogistic & Blake Canonical Formulas
   Let \(F\) and \(G\) be SOP formulas. We say that \(G\) is *formally included*
   in \(F\) written \(G\ll F\) ,in case each term of \(G\) is inclused in some
   term of \(F\). Formal inclusion implies inclusion,
   i.e., \(G\ll F\Rightarrow G\le F\) for any \(F,G\) pair.

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let
   \begin{align*}
   &F_1=wy'+w'z+w'x'y+wx'yz'\\
   &G=w'y'z+w'x'y\\
   &H=xy'z+x'yz'
   \end{align*}
   \(G\le F_1\) and \(H\le F_1\). Also \(G\ll F_1\) and \(H\not\ll F_1\)
   #+END_examplle

      A formula \(F\) will be called *syllogistic* in case for every SOP
   formula \(G\)
   \begin{equation*}
   G\le F\Rightarrow G\ll F
   \end{equation*}
   Thus \(F\) is syllogistic iff every implicant of \(F\) is included in some
   term of \(F\)
   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The formula
   \begin{equation*}
   F_2=wy'+w'z+w'x'y+x'yz'+y'z+wx'z'
   \end{equation*}
   is a syllogistic formula equivalent to \(F_1\). Every SOP in \(F_2\) is
   formally included in \(F_2\).
   #+END_examplle

   Given SOP formulas \(F\) and \(G\), we define \(F\times G\) to be the SOP
   formula produced by multiplying out the conjunction \(FG\), suing the
   distributive laws. If \(F=\sum_is_i\) and \(G=\sum_jt_j\), then
   \begin{equation*}
   F\times G=\sum_i\sum_js_i\cdot t_j
   \end{equation*}
   where repeated literals are dropped in each product \(s_i\cdot t_j\) of
   terms. A product is dropped if it contains a complementary pair of literals.

   Let \(a\) be any letter. Two terms will be said to have an *opposition* in case
   one term contains the literal \(a\) and the other the literal \(a'\). For
   example \(x'yz\) and \(wy'z\) have a single opposition. Suppose two
   terms \(r\) and \(s\)have exactly one opposition. Then the *consensus* of \(r\)
   and \(s\), denoted by \(c(r,s)\) , is the term obtained from the
   conjunction \(rs\) by deleting the two opposed literals as well as any
   repeated literals.

   Let \(F\) be a syllogistic formula for a Boolean function \(f\). We call the
   formula \(ABS(f)\) the *Blake canonical form* for \(f\), and we denote it by \(BCF(f)\).
   Blake showed that \(BCF(f)\) is minimal within the class of syllogistic
   formulas for \(f\).
** Generation of \(BCF(f)\)
   1. Find a syllogistic formula for \(f\)
   2. Delete absorbed terms
** Exhaustion of implicants
** Iterated Consensus
   Theorem ref:thma-2-3 guarantees that any SOP formula is transformed into a
   syllogistic formula by repeated application of the following rule
   #+BEGIN_center
   If the formula contains a pair \(r,s\) of terms whose consensus \(c(r,s)\)
   exists and is not included in any term of the formula, then adjoin \(c(r,s)\)
   to the formula.
   #+END_center

   The process of iterated consensus terminates in a finite number of steps,
   becuase
   * If a pair \(r,s\) of terms meets the specified condition at a given stop,
     it cannot meet that condition at any subsequent stop
   * the number of pairs of terms to be considered is finite, inasmuch as no
     more than \(3^n\) terms can be produced from \(n\) letters


   We say that a consensus is *applicable* to the formula from which it is derived
   if the consensus is not inclused in any term of that formula

   
* Appendix                                                             :ignore:
  #+LATEX: \appendix
  
** Absorptive Formulas
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   The formula \(ABS(F)\) is unique to within congruence
   #+END_lemma 
   
** Syllogistic Formulas
      A formula \(F\) will be called *syllogistic* in case for every SOP
   formula \(G\)
   \begin{equation*}
   G\le F\Rightarrow G\ll F
   \end{equation*}
   Thus \(F\) is syllogistic iff every implicant of \(F\) is included in some
   term of \(F\).
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(F,G\) and \(H\) be SOP formulas. If \(F\ll G+H\) and \(G\ll H\),
   then \(F\ll H\).
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(F\) be an SOP formula. \(F\) is syllogistic iff \(ABS(F)\) is syllogistic
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(F_1\) and \(F_2\) be syllogistic. If \(F_1\equiv F_2\)
   then \(ABS(F_1)\ceq ABS(F_2)\)
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thma-2-1
   Let \(F_1,\dots,F_k\) be syllogistic formulas.
   Then \(F_1\times\dots\times F_k\) is syllogistic
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If terms \(r\) and \(s\) have no oppositions, then \(r+s\) is syllogistic
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thma-2-2
   Let \(r\) and \(s\)be terms. The formula \(r+s\) is non-syllogistic iff \(r\)
   and \(s\) have exactly one opposition
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(r+s\) be a non-syllogistic SOP formula. Then
   1. \(r+s+c(r,s)\equiv r+s\)
   2. \(r+s+c(r,s)\) is syllogistic
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thma-2-3
   If an SOP formula \(F\) is not syllogistic, it contains terms \(p\)
   and \(q\), having exactly one opposition, s.t. \(c(p,q)\) is not formally
   included in \(F\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If an SOP formula \(F\) is not syllogistic, then \(ABS(F)\) contains
   terms \(p\)and \(q\), having  exactly one opposition, s.t. \(c(p,q)\not\ll ABS(F)\)
   #+END_corollary

** Prime Implicants
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   An implicant \(p\) of a Boolean function \(f\) is a prime implicant of \(f\)
   in case the implication
   \begin{equation*}
   p\le q\le f\Rightarrow p=q
   \end{equation*}
   holds for every term \(q\)
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \(F\) be an SOP formula for a Boolean function \(f\). Then \(F\)is
   syllogistic iff every prime implicant of \(f\) is a term of \(F\)
   #+END_theorem

** The Blake Canonical Form
   Let \(F\) be a syllogistic formula for a Boolean
   function \(f\). \(ABS(F)=BCF(F)\)

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \(f\) be a Boolean function. Then \(BCF(f)\) is the disjunction of all of
   the prime implicants of \(f\)
   #+END_theorem
