#+TITLE: Introduction to Commutative Algebra
#+AUTHOR: M. F. Atiyah & I. G. MacDonald

#+EXPORT_FILE_NAME: ../latex/CommutativeAlgebraAtiyah/CommutativeAlgebraAtiyah.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \DeclareMathOperator{\Max}{Max}
#+LATEX_HEADER: \DeclareMathOperator{\Adj}{Adj}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex


* Rings and Ideals
    A *ring* \(A\) is a set with two binary operations s.t.
    1. \(A\) is an abelian group w.r.t. addition
    2. Multiplication is associative (\((xy)z=x(yz)\)) and distributive over addition (\(x(y+z)=xy+xz,(y+z)x=yx+zx\))

    A *ring homomorphism* is a mapping \(f\) of a ring \(A\) into a ring \(B\) s.t.
    1. \(f(x+y)=f(x)+f(y)\)
    2. \(f(xy)=f(x)f(y)\)
    3. \(f(1)=1\)


    An *ideal* \(\fa\) of a ring \(A\) is a subset of \(A\) which is an additive subgroup and is
    s.t. \(A\fa\subseteq\fa\). The quotient group \(A/\fa\) inherits a uniquely defined multiplication from \(A\)
    which makes it into a ring, called the *quotient ring* \(A/\fa\). The elements of \(A/\fa\) are the
    cosets of \(\fa\) in \(A\), and the mapping \(\phi:A\to A/\fa\) which maps each \(x\in A\) to its
    coset \(x+\fa\) is a surjective ring homomorphism

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.1
    There is a one-to-one order-preserving correspondence between the ideals \(\fb\) of \(A\) which
    contain \(\fa\), and the ideals \(\bar{\fb}\) of \(A/\fa\), given by \(\fb=\phi^{-1}(\bar{\fb})\).
    #+END_proposition

    #+BEGIN_proof
    Let \(S_1=\{\fb:\fb\text{ an ideal of $A$ and }\fa\subseteq\fb\}\)
    and \(S_2=\{\bar{\fb}:\bar{\fb}\text{ an ideal of }A/\fa\}\), \(\pi\) is the natural map \(\pi(S)=S/\fa\), we prove that
    \begin{equation*}
    \varphi:S_1\to S_2\hspace{1cm}\fb\mapsto\pi(\fb)
    \end{equation*}
    is an bijection.

    First assume that \(\fa\subseteq\fb\), we prove that \(\pi^{-1}\pi(\fb)=\fb\). Apparently \(\fb\subseteq\pi^{-1}\pi(\fb)\). For
    any \(b\in\pi^{-1}\pi(\fb)\), there is a \(s\in\fb\) s.t. \(\pi(b)=\pi(s)\). Thus \(b-s\in\ker\pi=\fa\). As \(\fa\subseteq\fb\),
    we have \(b\in\fb\). Hence \(\pi^{-1}\pi(\fb)=\fb\).

    Thus for any \(\fb_1,\fb_2\in S_1\) and \(\varphi(\fb_1)=\pi(\fb_1)=\pi(\fb_2)=\varphi(\fb_2)\), we have \(\pi^{-1}\pi(\fb_1)=\pi^{-1}\pi(\fb_2)\).
    Thus \varphi is injective.

    For any \(\bar{\fb}\in S_2\), \(\pi^{-1}(\bar{\fb})\) contains \(\fa=\pi^{-1}(\{0\})\). Hence \varphi is surjective

    Order-preserving means \(\fa\subseteq\fb\subseteq\fc\) iff \(\bar{\fb}\subseteq\bar{\fc}\)
    #+END_proof

    If \(f:A\to B\) is any ring homomorphism, the *kernel* of \(f\) is an ideal \(\fa\) of \(A\), and the
    image of \(f\) is a subring \(C\) of \(B\); and \(f\) induces a ring isomorphism \(A/\fa\cong C\)

    We shall sometimes use the notation \(x\equiv y\mod\fa\); this means that \(x-y\in\fa\)

    A *zero-divisor* in a ring \(A\) is an element \(x\) which divides 0, i.e., for which there
    exists \(y\neq 0\) in \(A\) s.t. \(xy=0\). A ring with no zero-divisor \(\neq 0\) (and in
    which \(1\neq 0\)) is called an *integral domain*.

    An element \(x\in A\) is *nilpotent* if \(x^n=0\) for some \(n>0\). A nilpotent element is a
    zero-divisor (unless \(A=0\))

    A *unit* in \(A\) is an element \(x\) which "divides 1", i.e., an element \(x\) s.t. \(xy=1\) for
    some \(y\in A\). The element \(y\) is then uniquely determined by \(x\), and is
    written \(x^{-1}\). The units in \(A\) form a (multiplicative) abelian group

    The multiples \(ax\) of an element \(x\in A\) from a *principal* ideal, denoted by \((x)\)
    or \(Ax\). \(x\) is a unit iff \((x)=A=(1)\). The *zero* ideal \((0)\) is denoted by 0

    A *field* is a ring \(A\) in which \(1\neq 0\) and every non-zero element is a unit. Every field is
    an integral domain

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(A\) be a ring \(\neq 0\). Then the following are equivalent:
    1. \(A\) is a field
    2. the only ideals in \(A\) are 0 and (1)
    3. every homomorphism of \(A\) into a non-zero ring \(B\) is injective
    #+END_proposition

    #+BEGIN_proof
    \(2\to 3\). Let \(\phi:A\to B\) be a ring homomorphism. Then \(\ker\phi\) is an ideal \(\neq(1)\) in \(A\),
    hence \(\ker\phi=0\), hence \phi is injective

    \(3\to 1\). Let \(x\) be an element of \(A\) which is not a unit. Then \((x)\neq(1)\),
    hence \(B=A/(x)\) is not the zero ring. Let \(\phi:A\to B\) be the natural homomorphism of \(A\)
    onto \(B\) with kernel \((x)\). By hypothesis, \phi is injective, hence \((x)=0\), hence \(x=0\)
    #+END_proof

    [[index:prime]]
    An ideal \(\fp\) in \(A\) is *prime* if \(\fp\neq(1)\) and if \(xy\in\fp\Rightarrow x\in\fp\) or \(y\in\fp\)

    An ideal \(\fm\) in \(A\) is *maximal* if \(\fm\) in \(A\) is *maximal* if \(\fm\neq(1)\) and if no
    ideal \(\fa\) s.t. \(\fm\subset\fa\subset(1)\) (*strict* inclusions). Equivalently
    \begin{gather*}
    \fp\text{ is prime } \Leftrightarrow A/\fp\text{ is an integral domain}\\
    \fm\text{ is maximal } \Leftrightarrow A/\fm\text{ is a field}
    \end{gather*}
    #+BEGIN_proof
    If \(\fm\) is maximal and suppose \(a\notin\fm\). Then \(J=\{ra+i:i\in \fm\text{ and }r\in A\}\) is an ideal.
    Hence \(J=A\). So there is \(r\in A, \fm\in I\) s.t. \(1=ra+i\). So we have \(1\equiv ra\mod \fm\). Hence we
    find the inverse of \(a+\fm\)

    If \(A/\fm\) is a field and suppose \(\fm\subset\fn\subset A\). Let \(a\in\fm\setminus\fn\), then there exists a \(b\in A\)
    s.t. \(ab-1\in\fm\). So \(ab+m=1\) for some \(m\in\fm\). But \(ab\in\fn\) and \(m\in\fm\subset\fn\), then we
    have \(1\in\fn\) and \(\fn=A\).
    #+END_proof

    Hence a maximal ideal is prime. The zero ideal is prime iff \(A\) is an integral domain

    If \(f:A\to B\) is a ring homomorphism and \(\fq\) is a prime ideal in \(B\), then \(f^{-1}(\fq)\) is
    a prime ideal in \(A\), for \(A/f^{-1}(\fq)\) is isomorphic to a subring of \(B/\fq\) and hence has
    no zero-divisor \(\neq 0\). ([[https://asgarli.wordpress.com/2013/04/21/inverse-image-of-a-prime-ideal-is-prime/][Explanation]]. Since \(\fq\) is prime, \(B/\fq\) is an integral domain and a
    subring of an integral domain is still an integral domain. Define the map
    \(\varphi(a+f^{-1}(\fq))=f(a)+\fq\) and we need to show its a homomorphism. Then we show its injective.)

    But if \(\fn\) is a maximal ideal of \(B\) it is not necessarily true that \(f^{-1}(\fn)\) is
    maximal in \(A\); all we can say for sure is that it is prime. (Example: \(A=\Z\), \(B=\Q\), \(\fn=0\)).

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:1.3
    Every ring \(A\neq 0\) has at least one maximal ideal
    #+END_theorem

    #+BEGIN_proof
    This is the standard application of Zorn's lemma. Let \Sigma be the set of all ideals \(\neq(1)\)
    in \(A\). Order \Sigma by inclusion. \Sigma is not empty, since \(0\in\Sigma\). To apply Zorn's lemma we must
    show that every chain in \Sigma has an upper bound in \Sigma; let then \((\fa_\alpha)\) be a chain of ideals in
    \Sigma, so that for each pair of indices \alpha, \beta we have either \(\fa_\alpha\subseteq \fa_\beta\) or \(\fa_\beta\subseteq\fa_\alpha\).
    Let \(\fa=\bigcup_\alpha\fa_\alpha\). Then \(\fa\) is an ideal and \(1\notin\fa\). Hence \(\fa\in\Sigma\) and is an upper bound of the
    chain. Hence \Sigma has a maximal element
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(\fa\neq(1)\) is an ideal of \(A\), there exists a maximal ideal of \(A\) containing \(\fa\)
    #+END_corollary

    #+BEGIN_proof
    Apply ref:1.3 to \(A/\fa\) and ref:1.3
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:1.5
    Every non-unit of \(A\) is contained in a maximal ideal.
    #+END_corollary

    [[index:local ring]]
    A ring \(A\) with exactly one maximal ideal \(\fm\) is called a *local ring*. The field \(k=A/\fm\) is
    called the *residue field* of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(A\) be a ring and \(\fm\neq(1)\) an ideal of \(A\) s.t. every \(x\in A-\fm\) is a unit in \(A\).
       Then \(A\) is a local ring and \(\fm\) its maximal ideal.
    2. Let \(A\) be a ring and \(\fm\) a maximal ideal of \(A\) s.t. every element of \(1+\fm\) is a
       unit in \(A\). Then \(A\) is a local ring
    #+END_proposition

    #+BEGIN_proof
    2. [@2] Let \(x\in A-\fm\). Since \(\fm\) is maximal, the ideal generated by \(x\) and \(\fm\)
       is \((1)\), hence there exist \(y\in A\) and \(t\in\fm\) s.t. \(xy+t=1\); hence \(xy=1-t\) belongs
       to \(1+\fm\) and therefore is a unit. Now use 1
    #+END_proof

    A ring with only a finite number of maximal ideals is called *semi-local*

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. \(A=k[x_1,\dots,x_n]\), \(k\) a field. Let \(f\in A\) be an irreducible polynomial. By unique
       factorization, the ideal \((f)\) is prime
    2. \(A=\Z\). Every ideal in \(\Z\) is of the form \((m)\) for some \(m\ge 0\). The ideal \((m)\) is
       prime iff \(m=0\) or a prime number. All the ideals \((p)\), where \(p\) is a prime number,
       are maximal: \(\Z/(p)\) is the field of \(p\) elements
    3. A *principal ideal domain* is an integral domain in which every ideal is principal. In such a
       ring every non-zero prime ideal is maximal. For if \((x)\neq 0\) is a prime ideal
       and \((y)\supset(x)\), we have \(x\in(y)\), say \(x=yz\), so that \(yz\in(x)\) and \(y\notin(x)\),
       hence \(z\in(x)\); say \(z=tx\). Then \(x=yz=ytx\), so that \(yt=1\) and therefore \((y)=(1)\).
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.7
    The set \(\fN\) of all nilpotent elements in a ring \(A\) is an ideal, and \(A/\fN\) has no
    nilpotent \(\neq 0\)
    #+END_proposition

    #+BEGIN_proof
    If \(x\in\fN\), clearly \(ax\in\fN\) for all \(a\in A\). Let \(x,y\in\fN\): say \(x^m=0\), \(y^n=0\). By the
    binomial theorem, \((x+y)^{n+m-1`}\) is a sum of integer multiples of products \(x^ry^s\),
    where \(r+s=m+n-1\);

    Let \(\barx\in A/\fN\) be represented by \(x\in A\). Then \(\barx^n\) is represented by \(x^n\), so
    that \(\barx^n=0\Rightarrow x^n\in\fN\Rightarrow(x^n)^k=0\) for some \(k>0\Rightarrow x\in\fN\Rightarrow\barx=0\)
    #+END_proof

    The ideal \(\fN\) is called the *nilradical* of \(A\)

    Check [[https://math.stackexchange.com/questions/786393/when-is-nilradical-not-a-prime-ideal][When is nilradical not a prime ideal]], which is related to Exercise ref:ex1.19.

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.8
    The nilradical of \(A\) is the intersection of all the prime ideals of \(A\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\fN'\) denote the intersection of all the prime ideals of \(A\). If \(f\in A\) is nilpotent
    and if \(\fp\) is a prime ideal, then \(f^n=0\in\fp\) for some \(n>0\), hence \(f\in\fp\). Hence \(f\in\fN'\)

    Conversely, suppose that \(f\) is not nilpotent. Let \Sigma be the set of ideals \(\fa\) with the
    property
    \begin{equation*}
    n>0\Rightarrow f^n\notin\fa
    \end{equation*}
    Then \Sigma is not empty because \(0\in\Sigma\). Zorn's lemma can be applied to the set \Sigma, ordered by
    inclusion, and therefore \Sigma has a maximal element. We shall show that \(\fp\) is a prime ideal.
    Let \(x,y\notin\fp\). Then the ideals \(\fp+(x)\), \(\fp+(y)\) strictly contain \(\fp\) and therefore do not
    belong to \Sigma; hence
    \begin{equation*}
    f^m\in\fp+(x),\quad f^n\in\fp+(y)
    \end{equation*}
    for some \(m,n\). It follows that \(f^{m+n}\in\fp+(xy)\), hence the ideal \(\fp+(xy)\) is not in
    \Sigma and therefore \(xy\notin\fp\). Hence we have a prime ideal \(\fp\) s.t. \(f\notin\fp\), so that \(f\notin\fN'\)
    #+END_proof

    The *Jacobson radical* \(\fR\) of \(A\) is defined to be the intersection of all the maximal ideals
    of \(A\). It can be characterized as follows:

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.9
    \(x\in\fR\) iff \(1-xy\) is a unit in \(A\) for all \(y\in A\)
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\): Suppose \(1-xy\) is not a unit. By ref:1.5 it belongs to some maximal ideal \(\fm\);
    but \(x\in\fR\subseteq\fm\), hence \(xy\in\fm\) and therefore \(1\in\fm\), which is absurd

    \(\Leftarrow\): Suppose \(x\notin\fm\) for some maximal ideal \(\fm\). Then \(\fm\) and \(x\) generate the unit
    ideal \((1)\), so that we have \(u+xy=1\) for some \(u\in\fm\) and some \(y\in A\). Hence \(1-xy\in\fm\)
    and is therefore not a unit.
    #+END_proof

    If \(\fa,\fb\) are ideals in a ring \(A\), their *sum* \(\fa+\fb\) is the set of all \(x+y\) where \(x\in\fa\)
    and \(y\in\fb\). It is the smallest ideal containing \(\fa\) and \(\fb\). More generally, we may define
    the sum \(\sum_{i\in I}a_i\) of any family (possibly infinite) of ideals \(\fa_i\) of \(A\); is elements
    are all sums \(\sum x_i\), where \(x_i\in\fa_i\) for all \(i\in I\) and almost all of the \(x_i\) (i.e., all
    but a finite set) are zero. It is the smallest ideal of \(A\) which contains all the ideals \(\fa_i\)

    The *product* of two ideals \(\fa,\fb\) in \(A\) is the ideal \(\fa\fb\) *generated* by all products \(xy\),
    where \(x\in\fa\) and \(y\in\fb\). It is the set of all finite sums \(\sum x_iy_i\) where each \(x_i\in\fa\) and
    each \(y_i\in\fb\)

    We have the *distributive law*
    \begin{equation*}
    \fa(\fb+\fc)=\fa\fb+\fa\fc
    \end{equation*}
    In the ring \(\Z\), \(\cap\) and + are distributive over each other. This is not the case in
    general. *modular law*
    \begin{equation*}
    \fa\cap(\fb+\fc)=\fa\cap\fb+\fa\cap\fb\text{ if }\fa\supseteq\fb\text{ or }\fa\supseteq\fc
    \end{equation*}
    \begin{equation*}
    \fa\cap\fb=\fa\fb\text{ provided }\fa+\fb=(1)
    \end{equation*}
    If \(x\in\fa\cap\fb\), there is \(a+b=1\). Hence \(xa+xb=x\in\fa\fb\)

    Two ideals \(\fa,\fb\) are said to be *coprime* if \(\fa+\fb=(1)\). Thus for coprime ideals we
    have \(\fa\cap\fb=\fa\fb\).

    Let \(A\) be a ring and \(\fa_1,\dots,\fa_n\) ideals of \(A\). Define a homomorphism
    \begin{equation*}
    \phi:A\to\prod_{i=1}^n(A/\fa_i)
    \end{equation*}
    by the rule \(\phi(x)=(x+\fa_1,\dots,x+\fa_n)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. If \(\fa_i,\fa_j\) are coprime whenever \(i\neq j\), then \(\prod\fa_i=\bigcap\fa_i\)
    2. \phi is surjective iff \(\fa_i\), \(\fa_j\) are coprime whenever \(i\neq j\)
    3. \phi is injective iff \(\bigcap\fa_i=(0)\)
    #+END_proposition

    #+BEGIN_proof
    1. Induction on \(n\). The case \(n=2\) is dealt with above. Suppose \(n>2\) and the result true
       for \(\fa_1,\dots,\fa_{n-1}\), and let \(\fb=\prod_{i=1}^{n-1}\fa_i=\bigcap_{i=1}^{n-1}\fa_i\). As we have \(x_i+y_i=1\)
       (\(x_i\in\fa_i,y_i\in\fa_n\)) and therefore
       \begin{equation*}
       \prod_{i=1}^{n-1}x_i=\prod_{i=1}^{n-1}(1-y_i)\equiv 1\mod \fa_n
       \end{equation*}
       Hence \(\fa_n+\fb=(1)\) and so
       \begin{equation*}
       \prod_{i=1}^n\fa_i=\fb\fa_n=\fb\cap\fa_n=\bigcap_{i=1}^n\fa_i
       \end{equation*}
    2. \(\Rightarrow\): Let's show for example that \(\fa_1,\fa_2\) are coprime. There exists \(x\in A\)
       s.t. \(\phi(x)=(1,0,\dots,0)\); hence \(x\equiv 1\mod\fa_1\) and \(x\equiv 0\mod\fa_2\), so that
       \begin{equation*}
       1=(1-x)+x\in\fa_1+\fa_2
       \end{equation*}
       \(\Leftarrow\): It is enough to show, for example, that there is an element \(x\in A\)
       s.t. \(\phi(x)=(1,0,\dots,0)\). Since \(\fa_1+\fa_i=(1)\) (\(i>1\)) we have \(u_i+v_i=1\) (\(u_i\in\fa_1,v_i\in\fa_i\)).
       Take \(x=\prod_{i=2}^nv_i\), then \(x=\prod(1-u_i)\equiv 1\mod\fa_1\). Hence \(\phi(x)=(1,0,\dots,0)\)
    3. \(\bigcap\fa_i\) is the kernel of \phi
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.11
    1. Let \(\fp_1,\dots,\fp_n\) be prime ideals and let \(\fa\) be an ideal contained in \(\bigcup_{i=1}^n\fp_i\).
       Then \(\fa\subseteq\fp_i\) for some \(i\).
    2. Let \(\fa_1,\dots,\fa_n\) be ideals and let \(\fp\) be a prime ideal containing \(\bigcap_{i=1}^n\fa_i\).
       Then \(\fp\supseteq\fa_i\) for some \(i\). If \(\fp=\bigcap\fa_i\), then \(\fp=\fa_i\) for some \(i\)
    #+END_proposition

    #+BEGIN_proof
    1. induction on \(n\) in the form
       \begin{equation*}
       \fa\not\subseteq\fp_i(1\le i\le n)\Rightarrow\fa\not\subseteq\bigcup_{i=1}^n\fp_i
       \end{equation*}
       It is true for \(n=1\). If \(n>1\) and the result is true for \(n-1\), then for each \(i\)
       there exists \(x_i\in\fa\) s.t. \(x_i\notin\fp_j\) whenever \(j\neq i\). If for some \(i\) we have \(x_i\notin\fp_i\),
       we are through. If not, then \(x_i\in\fp_i\) for all \(i\). Consider the element
       \begin{equation*}
       y=\sum_{i=1}^nx_1x_2\cdots x_{i-1}x_{i+1}\cdots x_n
       \end{equation*}
       we have \(y\in\fa\) and \(y\notin\fp_i\) (\(1\le i\le n\)). Hence \(\fa\not\subseteq\bigcup_{i=1}^n\fp_i\)
    2. Suppose \(\fp\not\supseteq\fa_i\) for all \(i\). Then there exist \(x_i\in\fa_i\), \(x_i\notin\fp\) (\(1\le i\le n\)) and
       therefore \(\prod x_i\in\prod\fa_i\subseteq\bigcap\fa_i\); but \(\prod x_i\notin\fp\) since \(\fp\) is prime. Hence \(\fp\not\supseteq\bigcap\fa_i\)

       If \(\fp=\bigcap\fa_i\), then \(\fp\subseteq\fa_i\) and hence \(\fp=\fa_i\) for some \(i\).
    #+END_proof

    #+LATEX: \wu{
    For prime ideals \(\fp_1,\dots,\fp_n\), if \(\bigcap_{i=1}^n\fp_i=\fp\) is a prime ideal, then \(\fp=\fp_i\) for
    some \(i\). If there are more than one minimal ideal, this could never happen
    #+LATEX: }

    If \(\fa,\fb\) are ideals in a ring \(A\), their *ideal quotient* is
    \begin{equation*}
    (\fa:\fb)=\{x\in A:x\fb\subseteq\fa\}
    \end{equation*}
    which is an ideal. In particular, \((0:\fb)\) is called the *annihilator* of \(\fb\) and is also
    denoted by \(\Ann(\fb)\): it is the set of all \(x\in A\) s.t. \(x\fb=0\). In this notation the set of
    all zero-divisors in \(A\) is
    \begin{equation*}
    D=\bigcup_{x\neq 0}\Ann(x)
    \end{equation*}

    If \(\fb\) is a principal ideal \((x)\), we shall write \((\fa:x)\) in place of \((\fa:(x))\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \(A=\Z\), \(\fa=(m)\), \(\fb=(n)\), where say \(m=\prod_pp^{\mu_p}\), \(n=\prod_pp^{\nu_p}\),
    then \((\fa:\fb)=(q)\) where \(q=\prod_pp^{\gamma_p}\) and
    \begin{equation*}
    \gamma_p=\max(\mu_p-\nu_p,0)=\mu_p-\min(\mu_p,\nu_p)
    \end{equation*}
    Hence \(q=m/(m,n)\), where \((m,n)\) is the h.c.f. of \(m\) and \(n\)
    #+END_examplle

    #+BEGIN_exercise
    1. \(\fa\subseteq(\fa:\fb)\)
    2. \((\fa:\fb)\fb\subseteq\fa\)
    3. \((\fa:\fb):\fc=(\fa:\fb\fc)=((\fa:\fc):\fb)\)
    4. \((\bigcap_i\fa_i:\fb)=\bigcap_i(\fa_i:\fb)\)
    5. \((\fa:\sum_i\fb_i)=\bigcap(\fa:\fb_i)\)

    #+END_exercise

    #+BEGIN_proof
    3. [@3] \((\fa:\fb):\fc=\{x\in A:x\fc\subseteq\fa:\fb\}\). for any \(c\in\fc\), \(xc\fb\subseteq\fa\). Hence \(x\fc\fb\subseteq\fa\).
    5. [@5] \((\fa:\sum_i\fb_i)=\{x\in A:x\sum_i\fb_i\subseteq\fa\}\)
    #+END_proof

    If \(\fa\) is any ideal of \(A\), the *radical* of \(\fa\) is
    \begin{equation*}
    r(\fa)=\{x\in A:x^n\in\fa\text{ for some }n>0\}
    \end{equation*}
    if \(\phi:A\to A/\fa\) is the standard homomorphism, then \(r(\fa)=\phi^{-1}(\fN_{A/\fa})\) and hence \(r(\fa)\)
    is an ideal by ref:1.7

    #+BEGIN_exercise
    1. \(r(\fa)\supseteq\fa\)
    2. \(r(r(\fa))=r(\fa)\)
    3. \(r(\fa\fb)=r(\fa\cap\fb)=r(\fa)\cap r(\fb)\)
    4. \(r(\fa)=(1)\) iff \(\fa=(1)\).
    5. \(r(\fa+\fb)=r(r(\fa)+r(\fb))\)
    6. if \(\fp\) is prime, \(r(\fp^n)=\fp\) for all \(n>0\)
    #+END_exercise

    #+BEGIN_proof
    5. [@5] \(x\in r(\fa+\fb)\) iff \(x^n\in\fa+\fb\). \(y\in r(r(\fa)+r(\fb))\) iff \(y^m=a+b\), where \(a^{n_a}\in\fa\)
       and \(b^{n_b}\in\fb\).
       Then \((y^m)^{n_a+n_b}=(a+b)^{n_a+n_b}\in\fa+\fb\)
    6. \(x\in r(\fp^n)\) iff \(x^m\in\fp^n\), then \(x^m=p_1\cdots p_n\in\fp\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.14
    The radical of an ideal \(\fa\) is the intersection of the prime ideals which contain \(\fa\)
    #+END_proposition

    #+BEGIN_proof
    Apply ref:1.8 to \(A/\fa\).

    Nilradical of \(A/\fa\) is the radical of \(\fa\).
    #+END_proof

    More generally, we may define the radical \(r(E)\) of any *subset* \(E\) of \(A\) in the same way.
    It is *not* an ideal in general. We have \(r(\bigcup_\alpha E_\alpha)=\bigcup r(E_\alpha)\) for any family of subsets \(E_\alpha\)
    of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(D=\) set of zero-divisors of \(A=\bigcup_{x\neq 0}r(\Ann(x))\)
    #+END_proposition

    #+BEGIN_proof
    \(D=r(D)=r(\bigcup_{x\neq 0}\Ann(x))=\bigcup_{x\neq 0}r(\Ann(x))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \(A=\Z\), \(\fa=(m)\), let \(p_i\) (\(1\le i\le r\)) be the distinct prime divisors of \(m\).
    Then \(r(\fa)=(p_1\cdots p_r)=\bigcap_{i=1}^n(p_i)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\fa\), \(\fb\) be ideals in a ring \(A\) s.t. \(r(\fa)\), \(r(\fb)\) are coprime. Then \(\fa\)
    and \(\fb\) are coprime.
    #+END_proposition

    #+BEGIN_proof
    \(r(\fa+\fb)=r(r(\fa)+r(\fb))=r(1)=(1)\), hence \(\fa+\fb=(1)\)
    #+END_proof

    Let \(f:A\to B\) be a ring homomorphism. If \(\fa\) is an ideal in \(A\), the set \(f(\fa)\) is not
    necessarily an ideal in \(B\) (e.g. \(\Z\to\Q\)). We define the *extension* \(\fa^e\) of \(\fa\) to be the
    ideal \(Bf(\fa)\) generated by \(f(\fa)\) in \(B\): explicitly, \(\fa^e\) is the set of all
    sums \(\sum y_if(x_i)\) where \(x_i\in\fa\), \(y_i\in B\)

    If \(\fb\) is an ideal of \(B\), then \(f^{-1}(\fb)\) is always an ideal of \(A\), called the
    *contraction* \(\fb^c\) of \(\fb\). If \(\fb\) is prime, then \(\fb^c\) is prime. If \(\fa\) is prime, \(\fa^e\)
    need not be prime (\(f:\Z\to\Q\),\(\fa\neq 0\), then \(\fa^e=\Q\), which is not a prime ideal)

    We can factorize \(f\) as follows:
    \begin{equation*}
    f\xrightarrow{p}f(A)\xrightarrow{j}B
    \end{equation*}
    where \(p\) is surjective and \(j\) is injective

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Consider \(\Z\to\Z[i]\), where \(i=\sqrt{-1}\). A prime ideal \((p)\) of \(\Z\) may or may not stay
    prime when extended to \(\Z[i]\). In fact \(\Z[i]\) is a principal ideal domain (because it has a
    Euclidean algorithm, i.e., a Euclidean ring) and the situation is as follows:
    1. \((2^e)=((1+i)^2)\), the *square* of a prime ideal in \(\Z[i]\)
    2. if \(p\equiv 1\mod 4\) then \((p)^e\) is the product of two distinct prime ideals
       (for example, \((5)^e=(2+i)(2-i)\))
    3. if \(p\equiv 3\mod 4\) then \((p)^e\) is prime in \(\Z[i]\)
    #+END_examplle

    Let \(f:A\to B\), \(\fa\) and \(\fb\) be as before. Then
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(\fa\subseteq\fa^{ec}\), \(\fb\supseteq\fb^{ce}\)
    2. \(\fb^c=\fb^{cec}\), \(\fa^e=\fa^{ece}\)
    3. If \(C\) is the set of contracted ideals in \(A\) and if \(E\) is the set of extended ideals
       in \(B\), then \(C=\{\fa\mid\fa^{ec}=\fa\}\), \(E=\{\fb\mid\fb^{ce}=\fb\}\), and \(\fa\mapsto\fa^e\) is a bijective map
       of \(C\) onto \(E\), whose inverse is \(\fb\mapsto\fb^c\).
    #+END_proposition

    #+BEGIN_proof
    3. [@3] If \(\fa\in C\), then \(\fa=\fb^c=\fb^{cec}=\fa^{ec}\); conversely if \(\fa=\fa^{ec}\) then \(\fa\) is the
       contraction of \(\fa^e\).
    #+END_proof

    #+BEGIN_proof
    1.
    #+END_proof

    #+BEGIN_exercise
    If \(\fa_1,\fa_2\) are ideals of \(A\) and if \(\fb_1,\fb_2\) are ideals of \(B\), then
    \begin{alignat*}{2}
    &(\fa_1+\fa_2)^e=\fa_1^e+\fa_2^e\quad&&(\fb_1+\fb_2)^c\supseteq\fb_1^c+\fb_2^c\\
    \end{alignat*}
    #+END_exercise
** Exercise
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For \(f:X\to Y\), given any \(B\subseteq Y\), \(f(f^{-1}(B))\subseteq B\). If \(f\) is surjective, \(f(f^{-1}(B))=B\)
    #+END_proposition

    #+BEGIN_proof
    For any \(x\in f(f^{-1}(B))\), there is \(y\in f^{-1}(B)\) s.t. \(f(y)=x\). Thus \(x\in B\).

    For any \(y\in B\), as \(f\) is surjective, there is \(x\in X\) s.t. \(f(x)=y\). So \(x\in f^{-1}(B)\)
    and hence \(y\in f(f^{-1}(B))\)
    #+END_proof


    #+BEGIN_exercise
    label:ex1.1
    Let \(x\) be a nilpotent element of a ring \(A\). Show that \(1+x\) is a unit of \(A\). Deduce
    that the sum of a nilpotent element and a unit is a unit
    #+END_exercise

    #+BEGIN_proof
    \(x\) is a element of a nilradical, which is the intersection all prime ideals. Since every
    maximal ideal is a prime ideal, then nilradical is a subset of Jacobson radical.
    Then \(1-(-u^{-1})x\) is a unit for some unit \(u\), hence \(u+x\) is a unit
    #+END_proof

    #+BEGIN_exercise
    label:ex1.2
    Let \(A\) be a ring and let \(A[x]\) be the ring of polynomials in an indeterminate \(x\), with
    coefficients in \(A\). Let \(f=a_0+a_1x+\cdots+a_nx^n\in A[x]\). Prove that
    1. \(f\) is a unit in \(A[x]\) iff \(a_0\) is a unit in \(A\) and \(a_1,\dots,a_n\) are nilpotent [if
       \(b_0+b_1x+\dots+b_mx^m\) is the inverse of \(f\), prove by induction on \(r\)
       that \(a_n^{r+1}b_{m-r}=0\). Hence show that \(a_n\) is nilpotent and then use Exercise ref:ex1.1]
    2. \(f\) is nilpotent iff \(a_0,\dots,a_n\) is nilpotent
    3. \(f\) is a zero-divisor iff there exists \(a\neq 0\) in \(A\) s.t. \(af=0\)
    4. \(f\) is said to be *primitive* if \((a_0,\dots,a_n)=(1)\). Prove that if \(f,g\in A[x]\),
       then \(fg\) is primitive iff \(f\) and \(g\) are primitive
    #+END_exercise

    #+BEGIN_proof
    1. Suppose \(g=\sum_{i=0}^mb_ix^i\) s.t. \(fg=1\). For \(r=0\), \(a_nb_m=0\) obviously.

       Now suppose this is true for all \(p<r\). Now we prove \(a_n^{r+1}b_{m-r}=0\). The \(m+n-r\)th term's
       coefficient is \(\sum_{i=0}^ra_{n-i}b_{m-r+i}=0\). Then
       \begin{equation*}
       a_n^{r+1}\sum_{i=0}^ra_{n-i}b_{m-r+i}=a_n^{r+1}b_{m-r}=0
       \end{equation*}
       Thus \(a_n^{m+1}b_0=0\) and hence \(a_n^{m+1}=0\) as \(b_0\) is a unit. So \(f-a_nx^n\) is a
       unit and we can continue.

    2. \(\Rightarrow\). Goal: for any prime ideal \(\fp\) in \(A\), \(f\) is 0 in \((A/\fp)[x]\). This is
       because \(f^n\) is 0 in \((A/\fp)[x]\) and \(A/\fp\) is an integral domain. Then for \(a_0,\dots,a_n\)
       is contained in every prime ideal and hence are nilpotent

       If \(f\) is nilpotent and \(a_k\) is nilpotent, then \(f-a_kx^k\) is still nilpotent since
       nilradical is an ideal

       \(\Leftrightarrow\). Nilradical \(\fR\) is an ideal. As \(a_0,\dots,a_n\) is nilpotent in \(A[x]\),
       their \(A[x]\)-combination is still nilpotent

    3. Choose a polynomial \(g=b_0+b_1x+\dots+b_mx^m\) of least degree \(m\) s.t. \(fg=0\).
       Then \(a_nb_m=0\) and \(a_ngf=0\). As \(g\) is of least degree, we have \(a_ng=0\). Then
       \(fg=a_0g+\dots+a_{n-1}x^{n-1}g+a_ng=a_0g+\dots+a_{n-1}x^{n-1}g=0\). Hence for
       all \(0\le i\le n\), \(a_ig=0\). Arbitrary coefficient of \(g\) is what we want

    4. If \(fg\) is primitive, then \((\sum^{\min\{n,k\}}_{\max\{0,k-m\}}a_ib_{k-i})_{k\in[0,n+m]}=(1)\).
       Change the coefficient one by one

       By extract, we can get \((a_0^kb_k)_{k\in[0,n+m]}=(1)\). Then \((b_k)=(1)\).

    #+END_proof

    #+BEGIN_exercise
    label:ex1.4
    In the ring \(A[x]\), the Jacobson radical is equal to the nilradical
    #+END_exercise

    #+BEGIN_proof
    Suppose \(\fR\) is the Jacobson radical and \(f\in\fR\), then \(1-fx\)is a unit by Proposition
    ref:1.9. By Exercise ref:ex1.2 (1) all coefficients of \(f\) are nilpotent, then \(f\) is
    nilpotent by Exercise ref:ex1.2 (2)
    #+END_proof

    #+BEGIN_exercise
    label:1.5
    Let \(A\) be the ring and let \(A[[x]]\) be the ring of formal power series \(f=\sum_{n=0}^\infty a_nx^n\)
    with coefficients in \(A\). Show that
    1. \(f\) is a unit in \(A[[x]]\) iff \(a_0\) is a unit in \(A\)
    2. If \(f\) is nilpotent, then \(a_n\) is nilpotent for all \(n\ge 0\).
    3. \(f\) belongs to the Jacobson radical of \(A[[x]]\) iff \(a_0\) belongs to the Jacobson radical
       of \(A\)
    4. The contraction of a maximal ideal \(\fm\) of \(A[[x]]\) is a maximal ideal of \(A\), and \(\fm\) is
       generated by \(\fm^c\) and \(x\).
    5. Every prime ideal of \(A\) is the contraction of a prime ideal of \(A[[x]]\).
    #+END_exercise

    #+BEGIN_proof
    1. \(\Leftarrow\). We compute \(b_n\) from \(a_0,\dots,a_n\), \(b_0,\dots,b_{n-1}\)  and \(\sum_{i=0}^na_ib_{n-i}=0\).
       Multiply it with \(a_0\), we get \(b_n+a_0\sum_{i=1}^na_ib_{n-i}=0\)
    2. Note that nilradical is an ideal. If \(a_k\) is nilpotent in \(A\), then \(a_kx\) is
       nilpotent in \(A[[x]]\), and \(f-a_kx^k\) is nilpotent. And we continue
    3. For any \(b\in A\), \(1-bf\) is a unit, and by (1), \(1-ba_0\) is a unit.
    4. From (3), a maximal ideal \(\fm\) at least contains \(xA[[x]]\). Let \(\fm=\fm^c+xA[[x]]\).
       Now
       \begin{equation*}
       A[[x]]/\fm\cong(A[[x]]/xA[[x]])/(\fm/xA[[x]])\cong A/\fm^c
       \end{equation*}
       Thus \(\fm\) is maximal
    5. Given a prime ideal \(\fp\) of \(A\), consider
       \begin{equation*}
       \phi:A[[x]]\to A\to A/\fp
       \end{equation*}
       Then \(\ker\phi=\fp+xA[[x]]\) and \(A[[x]]/\ker\phi\cong A/\fp\) and hence \(\ker\phi\) is a prime ideal.
    #+END_proof

    #+BEGIN_exercise
    label:ex1.6
    A ring \(A\) is s.t. every ideal not contained in the nilradical contains a nonzero idempotent
    (that is, an element \(e\) s.t. \(e^2=e\neq 0\)). Prove that the nilradical and Jacobson radical
    of \(A\) are equal
    #+END_exercise

    #+BEGIN_proof
    If there is a \(x\in A\) s.t. \(x\in\fR\) and \(x\notin\fN\). Then \((x)\not\subseteq\fN\) and there is \(y\in A\)
    s.t. \(y^2x^2=x^2\) and hence \((y^2-1)x^2=0\). As \(x^2\neq 0\), \(y^2=1\). Hence \(\fR=(1)\), which is not possible
    #+END_proof

    #+BEGIN_exercise
    label:ex1.7
    Let \(A\) be a ring where every element \(x\) satisfies \(x^n=x\) for some \(n>1\) (depending
    on \(x\)). Show that every prime ideal in \(A\) is maximal
    #+END_exercise

    #+BEGIN_proof
    \(\fp\) the prime ideal and \(x\notin\fp\), as \(x(x^{n-1}-1)=0\in\fp\), \(x^{n-1}-1\in\fp\).
    Then \(x^{n-1}\equiv 1\mod\fp\) and \((x+\fp)(x^{n-2}+\fp)=1+\fp\).
    #+END_proof

    #+BEGIN_exercise
    label:ex1.8
    Let \(A\) be a ring \(\neq 0\). Show that the set of prime ideals of \(A\) has minimal elements
    w.r.t. inclusion
    #+END_exercise

    #+BEGIN_proof
    Equivalently to say that nilradical is prime.
    #+END_proof

    #+BEGIN_exercise
    label:ex1.9
    Let \(\fa\) be an ideal \(\neq(1)\) in a ring \(A\). Show that \(\fa=r(\fa)\) iff \(\fa\) is an
    intersection of prime ideals
    #+END_exercise

    #+BEGIN_proof
    \(\Rightarrow\). From Proposition ref:1.14

    \(\Leftarrow\). If \(x^n\in\fa\), then \(x\in\fa\).
    #+END_proof

    #+BEGIN_exercise
    label:ex1.10
    Let \(A\) be a ring, \(\fN\) its nilradical. Show that the following are equivalent
    1. \(A\) has exactly one prime ideal
    2. every element of \(A\) is either a unit or nilpotent
    3. \(A/\fN\) is a field
    #+END_exercise

    #+BEGIN_proof
    \(2\to 3\). \(\fN\) is maximal

    \(1\to 2\). Obvious:D

    \(3\to 1\). Then \(\fN\) is maximal
    #+END_proof

    #+BEGIN_exercise
    label:ex1.11
    A ring is *Boolean* if \(x^2=x\) for all \(x\in A\). In a Boolean ring \(A\), show that
    1. \(2x=0\) for all \(x\in A\)
    2. every prime ideal \(\fp\) is maximal, and \(A/\fp\) is a field with two elements
    3. every finitely generated ideal in \(A\) is principal
    #+END_exercise

    #+BEGIN_proof
    1. \(2x=x+x^2=0\)
    2. Maximality by Exercise ref:ex1.7. For any \(x\notin\fp\), \((x+\fp)(1+\fp)=1+\fp\) and so \(x\equiv 1\mod\fp\).
       For any \(x\in\fp\), \(x\equiv 0\mod\fp\).
    3. Let \(x,y\) be elements of an ideal \(\fa\). Define \(z:=x+y+xy\), note that \(xz=x+y+y=x\).
       Hence \((x,y)=(z)\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.12
    A local ring contains no idempotent \(\neq 0,1\)
    #+END_exercise

    #+BEGIN_proof
    If \(\fm\) is the unique maximal ring. Then \(x\in\fm\) iff for all \(y\in A\), \(1-xy\) is a unit.

    If \(x^2=x\), then \(x(1-x)=0\). As \(1-x\) is not a unit, \(x\notin\fm\).
    #+END_proof

    /Construction of an algebraic closure of a field/
    #+BEGIN_exercise
    label:ex1.13
    Let \(K\) be a field and let \Sigma be the set of all irreducible monic polynomials \(f\) in one
    indeterminate with coefficients in \(K\). Let \(A\) be the polynomial ring over \(K\) generated
    by indeterminate \(x_f\), one for each \(f\in\Sigma\). Let \(\fa\) be the ideal of \(A\) generated by the
    polynomials \(f(x_f)\) for all \(f\in\Sigma\). Show that \(\fa\neq(1)\)

    Let \(\fm\) be a maximal ideal of \(A\) containing \(\fa\), and let \(K_1=A/\fm\). Then \(K_1\) is an
    extension field of \(K\) in which each \(f\in\Sigma\) has a root. Repeat the construction with \(K_1\)
    in place of \(K\), obtaining a field \(K_2\), and so on. Let \(L=\bigcup_{n=1}^\infty K_n\). Then \(L\) is a
    field in which each \(f\in\Sigma\) splits completely into linear factors. Let \(\barK\) be the set of
    all elements of \(L\) which are algebraic over \(K\). Then \(\barK\) is an algebraic closure of \(K\).
    #+END_exercise

    #+BEGIN_proof
    Irreducible polynomials have degree greater than 1. There is no linear combination that the
    degree of the sum is 0

    Let \(K_0=K\) be a field. Given a non-negative integer \(n\) for which the field, \(K_n\), is
    defined, let \(\Sigma_n\) be the set of monic irreducible elements of \(K_n[x]\) and let \(A_n\) be
    the polynomial ring over \(K_n\) generated by the set of indeterminates \(\{x_f\mid f\in\Sigma\}\).
    Define \(\fa_n\) be the ideal of \(A_n\) generated by the set \(\{f(x_f)\in A\mid f(\Sigma_n)\}\).
    Since \(K_n\) is a field, \(A_n\) is a domain. Thus every element of \(\fa_n\) has positive degree
    and \(\fa_n\) doesn't contain 1. Let \(\fm_n\) be a maximal ideal of \(A_n\) containing \(\fa_n\) and
    define \(K_{n+1}=A_n/\fm_n\). The map
    \begin{equation*}
    K_n\to A_n\to A_n/\fm_n=K_{n+1}
    \end{equation*}
    given by the inclusion and quotient maps, is a field homomorphism. Thus it is injective and we
    may identify \(K_n\) with a subfield of \(K_{n+1}\). Note that for any \(0\neq k\in K_n\), \(k\notin\fm\).
    Thus the kernel of the map is only \(\{0\}\).

    Let \(\barK=\bigcup_{n\ge 0}K_n\). If \(x,y\in\barK\) , then they are contained in some
    subfields \(K_n,K_m\). Letting \(k=\max\{m,n\}\), \(x,y\in K_k\). Therefore the sum, difference, and
    product of \(x,y\) are in \(K_k\).  Any field arithmetic of \(\barK\) can be performed in a
    subfield, \(\barK\) is a field.

    Let \(f\) be an irreducible monic polynomial in \(\barK[x]\). Since \(f\) has only finitely many
    coefficients, there is some \(n\) s.t. \(f\) is an irreducible monic polynomial in \(K_n[x]\).
    By construction, \(f\) has a root in \(K_{n+1}\), hence in \(\barK\). By the Euclidean
    division, \(f\) must have degree 1. Therefore, \(\barK\) is algebraic closed.

    By construction, the field extension \(K_{n+1}/K_n\) is algebraic for every \(n\).
    #+END_proof

    #+BEGIN_exercise
    label:ex1.14
    In a ring \(A\), let \Sigma be the set of all ideals in which every element is a zero-divisor. Show
    that the set \Sigma has minimal elements and that every maximal element of \Sigma is a prime ideal. Hence
    the set of zero-divisors in \(A\) is a union of prime ideals
    #+END_exercise

    #+BEGIN_proof
    If \(x\) is a zero-divisor, then \(Ax\) is a set of zero-divisors. Thus \Sigma is not empty and has a
    minimal element w.r.t. inclusion.

    For a maximal ideal \(\fp\) in \Sigma, suppose \(x,y\notin\fp\), then \(\fp+(x)+(y)\notin\Sigma\). Then there is an
    element \(p+x'x+y'y\) that is not a zero-divisor. If \(xy\) is zero-divisor,
    then \((p'xy)(p+x'x+y'y)=0\), a contradiction
    #+END_proof

    /The prime spectrum of a ring/

    #+BEGIN_exercise
    label:ex1.15
    Let \(A\) be a ring and let \(X\) be the set of all prime ideals of \(A\). For each subset \(E\)
    of \(A\), let \(V(E)\) denote the set of all prime ideals of \(A\) which contain \(E\). Prove
    that
    1. if \(\fa\) is the ideal generated by \(E\), then \(V(E)=V(\fa)=V(r(\fa))\)
    2. \(V(0)=X\), \(V(1)=\emptyset\)
    3. if \((E_i)_{i\in I}\) is any family of subsets of \(A\), then
       \begin{equation*}
       V\left( \bigcup_{i\in I}E_i \right)=\bigcap_{i\in I}V(E_i)
       \end{equation*}
    4. \(V(\fa\cap\fb)=V(\fa\fb)=V(\fa)\cup V(\fb)\) for any ideals \(\fa,\fb\) of \(A\)


    These results show that the sets \(V(E)\) satisfy the axioms for closed sets in a topological
    space. The resulting topology is called the *Zariski topology*. The topological space \(X\) is
    called the *prime spectrum* of \(A\), and is written as \(\Spec(A)\)
    #+END_exercise

    #+BEGIN_proof
    1. If \(\fa=(E)\), then \(\fa\) is the minimal ideal containing \(E\). Hence \(V(E)=V(\fa)\). For
       any prime ideal \(\fp\) containing \(\fa\) and any \(a\in r(\fa)\). Then \(a^n\in\fa\) for some \(n\).
       Then \(a^n\in\fp\), implying \(a\in\fp\). Hence \(V(\fa)\subseteq V(r(\fa))\).
    2. Obvious
    3. trivial
    4. As \(\fa\fb\subseteq\fa\cap\fb\), if \(\fa\cap\fb\subseteq\fp\) then \(\fa\fb\subseteq\fp\). On the other hand, if \(\fa\fb\subseteq\fp\), then we have shown
       either \(\fa\subseteq\fp\) or \(\fb\subseteq\fp\) (Proposition ref:1.11). Thus \(\fa\cap\fb\subseteq\fp\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.16
    Draw pictures of \(\Spec(\Z)\), \(\Spec(\R)\), \(\Spec(\C[x])\), \(\Spec(\R[x])\), \(\Spec(\Z[x])\)
    #+END_exercise

    #+BEGIN_proof
    \(\Z\) is PID, for any \(E\subseteq\Z\), let \(n=\min\{m\in E\mid m> 1\}\). Let \(\fa=(n)\). Then \((E)=\fa\).
    Suppose \(n=p_1^{n_1}\dots p_r^{n_r}\), then \(V(E)=\{p_1\Z,\dots,p_r\Z\}\).

    \(\R\) is a field and so there is only trivial ideals.

    \(\C[x]\) is a PID. Prime ideals are of the form \((f)\), where \(f\) is a monic irreducible
    or \(f=0\). As irreducible elements of \(\C[x]\) is of the form \(x-a\). Thus \(\Spec\C[x]\) is
    actually the complex plane.

    For any ideal \(\fa\) of \(\C[x]\), \(\fa=(f)\). By the Fundamental Theorem of
    Algebra, \(f=\prod_{i=1}^k(x-a_i)^{\alpha_i}\) for some complex numbers \(a_1,\dots,a_k\) and positive
    integers \(\alpha_1,\dots,\alpha_k\). Define \(\sqrt{f}\) as \(\prod_{i=1}^k(x-a_i)\). Since non-zero prime ideals
    of \(\C[x]\) are maximal, we have
    \begin{equation*}
    V(\fa)=V(f)=V(\sqrt{f})=\bigcup_{i=1}^kV(x-a_i)=\{(x-a_1),\dots,(x-a_k)\}
    \end{equation*}
    Therefore non-empty open subsets of \(\Spec\C[x]\) are cofinite sets containing \(\{0\}\)

    <<Problem1>>
    #+END_proof

    #+BEGIN_exercise
    label:ex1.17
    For each \(f\in A\), let \(X_f\) denote the complement of \(V(f)\) in \(X=\Spec(A)\). The
    sets \(X_f\) are open. Show that they form a basis of open sets for the Zariski topology, and
    that
    1. \(X_f\cap X_g=X_{fg}\)
    2. \(X_f=\emptyset\) iff \(f\) is nilpotent
    3. \(X_f=X\) iff \(f\) is a unit
    4. \(X_f=X_g\) iff \(r((f))=r((g))\)
    5. \(X\) is quasi-compact (that is, every open covering of \(X\) has a finite sub-covering)
    6. More generally, each \(X_f\) is quasi-compact
    7. An open subset of \(X\) is quasi-compact iff it is a finite union of sets \(X_f\)

       The sets \(X_f\) are called *basic open sets* of \(X=\Spec(A)\)

    #+END_exercise

    #+BEGIN_proof
    For any \(\fp\in X\), let \(x\in A\setminus\fp\). Then \(\fp\notin V(x)\). Hence \(\fp\in X_x\)

    If \(\fp\in X_f\cap X_g\), then as \(V(f)\cup V(g)=V(fg)\), then \(\fp\in X_{fg}\). Hence this form a basis of
    open sets for the Zariski topology

    1. \(X_f\cap X_g=V(f)^c\cap V(g)^c=(V(f)\cup V(g))^c=(V(fg))^c=X_{fg}\)

    2. \(X_f=\emptyset\) iff \(V(f)=X\) iff \(f\in\fN\)
    3. \(X_f=X\) iff \(V(f)=\emptyset\). Note that any ideal can be extended to a maximal ideal which is
       prime, thus \(f\) is not contained in any ideal, which means \(f\) is a unit
    4. \(r((f))\subseteq r((g))\) iff every ideal containing \((g)\) contains \((f)\) iff \(V(f)\subseteq V(g)\).
    5. A collection \(\calc\) of closed sets has finite intersection property iff for any
       finite \(V(E_1),\dots,V(E_n)\in\calc\), \(\bigcap V(E_i)=V(\bigcup E_i)\neq\emptyset\) iff for any
       finite \(V(E_1),\dots,V(E_n)\in\calc\), \(\bigcup E_i\) doesn't contain a unit. Thus \(\bigcup_{\calc}V(E_i)\) doesn't
       contain a unit and hence \(\bigcap_{\calc} V(E_i)\neq\emptyset\)

       Let \(\{X_f\}_{f\in E}\) be an open cover of \(X\). Taking complements shows that \(V(E)\) is
       empty. Therefore \((E)=(1)\). This in turn implies that there are \(f_1,\dots,f_n\in E\)
       and \(a_1,\dots,a_n\in A\) s.t. \(1=\sum_{i=1}^na_if_i\). Thus \(V(f_1,\dots,f_n)\) is empty
    6. Suppose an open covering \(\{X_g\}_{g\in E}\) of \(X_f\),
       then \(\bigcap_{g\in E}V(g)=V(\bigcup_{g\in E}g)=V(E)\subseteq V(f)\), which means that every prime containing \(E\)
       contains \(f\), then \(f\in r((E))\) (Proposition ref:1.14). So there
       are \(g_1,\dots,g_n\in E\), \(a_1,\dots,a_n\in A\) and a positive integer \(m\) s.t. \(f^m=\sum_{i=1}^na_ig_i\).
       Thus \(V(f)\supseteq V(g_1,\dots,g_n)\). Hence \(X_f\subseteq\bigcup_{i=1}^n X_{g_i}\)
    7. For any quasi-compact open sets \(U\) of \(X\), \(U=\bigcup_{f\in E}X_f\). And as it's quasi-compact,
       there is \(E_0\subseteq_fE\) s.t. \(U=\bigcup_{f\in E_0}X_f\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.18
    It is sometimes convenient to denote a prime ideal of \(A\) by a letter such as \(x\) or \(y\)
    when thinking of it as a point of \(X=\Spec(A)\). When thinking of \(x\) as a prime ideal
    of \(A\), we denote it by \(\fp_x\). Show that
    1. the set \(\{x\}\) is closed (we say that \(x\) is a "closed point") in \(\Spec(A)\) iff \(\fp_x\)
       is maximal
    2. \(\bbar{\{x\}}=V(\fp_x)\)
    3. \(y\in\bbar{\{x\}}\) iff \(\fp_x\subseteq\fp_y\)
    4. \(X\) is a \(T_0\)-space (this means that if \(x,y\) are disjoint points of \(X\), then
       either there is a neighborhood of \(x\) which does not contain \(y\), or else there is a
       neighborhood of \(y\) which does not contain \(x\))
    #+END_exercise

    #+BEGIN_proof
    1. \(\{x\}\) is closed iff there is \(E\subseteq A\) s.t. \(\{x\}=V(E)\) which means \(\fp_x\) cannot be
       expanded anymore
    2. \(y\in\bbar{\{x\}}\) iff \(\forall\) open \(U\ni y\), \(x\in U\) iff \(\forall E\; y\notin V(E)\), \(x\notin V(E)\) iff
       \(\forall E\; x\in V(E)\Rightarrow y\in V(E)\). As \(x\in V(x)\), \(y\in V(x)\). If \(y\in V(x)\), for any \(x\in V(E)\),
       we have \(y\in V(x)\subseteq V(E)\)
    3. \(y\in\bbar{\{x\}}\) iff \(y\in V(x)\) iff \(x\subseteq y\)
    4. If \(x\subseteq y\), then \(x\notin V(y)\) and \(y\in V(y)\). If \(x\not\subseteq y\), then \((x)\not\subseteq y\) and
       so \(y\notin V(x)\).

       If every neighborhood of \(x\) contains \(y\) and vice versa. Then \(y\in\bbar{\{x\}}\)
       and \(x\in\bbar{\{y\}}\). So \(x=y\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.19
    A topological space \(X\) is said to be *irreducible* if \(X\neq\emptyset\) and if every pair of non-empty
    open sets in \(X\) intersect, or equivalently if every non-empty open set is dense in \(X\).
    Show that \(\Spec(A)\) is irreducible iff the nilradical of \(A\) is a prime ideal
    #+END_exercise

    #+BEGIN_proof
    \(\Spec(A)\) is irreducible iff for
    any \(V(E)^c,V(F)^c\neq\emptyset\), \(V(E)^c\cap V(F)^c=(V(E)\cup V(F))^c=V(EF)^c\neq\emptyset\) iff \(V(E),V(F)\neq X\Rightarrow V(EF)\neq X\)
    iff \(V(EF)=X\Rightarrow V(E)=X\vee V(F)=X\).

    For any \(xy\in\fN\), \(x^ny^n=0\). Thus \(V(xy)=X\) and hence either \(V(x)=X\) or \(V(y)=X\). Thus
    either \(x\in\fN\) or \(y\in\fN\).

    If \(\fN\) is prime and if \(V(EF)=X\), then \(EF\subseteq\fN\) and either \(E\subseteq\fN\) or \(F\subseteq\fN\). Note that \(V(\fN)=X\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.20
    Let \(X\) be a topological space
    1. If \(Y\) is an irreducible subspace of \(X\), then the closure \(\barY\) of \(Y\) in \(X\) is irreducible
    2. Every irreducible subspace of \(X\) is contained in a maximal irreducible subspace
    3. The maximal irreducible subspaces of \(X\) are closed and cover \(X\). They are called the
       *irreducible components* of \(X\). What are the irreducible components of a Hausdorff space?
    4. If \(A\) is a ring and \(X=\Spec(A)\), then the irreducible components of \(X\) are the
       closed sets \(V(\fp)\), where \(\fp\) is a minimal prime ideal of \(A\)
    #+END_exercise

    #+BEGIN_proof
    1. For any open \(U,V\subseteq X\), then \(U\cap Y\neq\emptyset\wedge V\cap Y\neq\emptyset\Rightarrow U\cap V\cap Y\neq\emptyset\).

       Let \(U,V\) be open subsets of \(X\) s.t. \(U\cap\barY\) and \(V\cap\barY\) are nonempty. By the
       definition of closure, \(U\cap Y\) and \(V\cap Y\) are nonempty and hence \(U\cap V\cap Y\) is nonempty,
       which is a subset of \(U\cap V\cap\barY\)

    2. If \(Y\) is an irreducible subspace of \(X\), let \Sigma be the set of irreducible subspaces
       of \(X\) containing \(Y\), ordered by inclusion. Let \(\{Z_n\}_{n\ge 1}\) be a chain in \Sigma and
       let \(Z=\bigcup_{i=1}^nZ_n\). Suppose \(U\cap Z\neq\emptyset\) and \(V\cap Z\neq\emptyset\). Then there is \(i,j\)
       s.t. \(U\cap Z_i\neq\emptyset\) and \(V\cap Z_j\neq\emptyset\). So \(U\cap V\cap Z_{\max\{i,j\}}\neq\emptyset\). Then by Zorn's Lemma
    3. Note that \(\{x\}\) is irreducible subspace.

       In Hausdorff space, any subspace with more than one point has disjoint non-empty open sets,
       and is thus not irreducible
    4. Show \(V(\fp)\) is irreducible and maximal

       For any \(E,F\subseteq A\), suppose \(V(E)^c\cap V(\fp)\) and \(V(F)^c\cap V(\fp)\) are nonempty, then there is
       \(\fp\subseteq\fm\in V(E)^c\cap V(\fp)\) and \(\fp\subseteq\fn\in V(F)^c\cap V(\fp)\). As \(\fp\) is
       minimal, \(\fp\subseteq\fm\cap\fn\in V(E)^c\cap V(F)^c\cap V(\fp)\)

       If \(V(\fp)\)  is not maximal, then there is \(E\) s.t. \(V(\fp)\subsetneq V(E)\), which implies
       that \((E)\subsetneq\fp\), a contradiction

       Given any irreducible components \(V(E)=V((E))=V(\fa)\) of \(X\). If \(\fa\) is not minimal, then
       there is \(\fb\subsetneq\fa\) and \(V(\fb)\supseteq V(\fa)\). Then \(V(\fb)\) is an irreducible component
    #+END_proof

    #+BEGIN_remark
    Let \(X=\Spec(A)\) and \(Y\subseteq X\). Note that \(Y\subseteq V(\fa)\Leftrightarrow\fa\subseteq\bigcap_{y\in Y}y\). Thus
    \begin{align*}
    \barY&=\bigcap\left\{ V(\fa):Y\subseteq V(\fa) \right\}=\bigcap\left\{ V(\fa):\fa\subseteq\bigcap_{y\in Y}y \right\}\\&=V\left( \bigcup\{\fa:\fa\subseteq\bigcap_{y\in Y}y\} \right)
    =V\left( \bigcap_{y\in Y}y \right)
    \end{align*}
    #+END_remark

    #+BEGIN_exercise
    label:ex1.21
    Let \(\phi:A\to B\) be a ring homomorphism. Let \(X=\Spec(A)\) and \(Y=\Spec(B)\). If \(\fq\in Y\),
    then \(\phi^{-1}(\fq)\) is a prime ideal, i.e., a point of \(X\). Hence \phi induces a
    mapping \(\phi^*:Y\to X\). Show that
    1. If \(f\in A\) then \(\phi^{*-1}(X_f)=X_{\phi(f)}\) and hence that \(\phi^*\) is continuous
    2. If \(\fa\) is an ideal of \(A\), then \(\phi^{*-1}(V(\fa))=V(\fa^e)\)
    3. If \(\fb\) is an ideal of \(B\), then \(\bbar{\phi^*(V(\fb))}=V(\fb^c)\)
    4. If \phi is surjective, then \(\phi^*\) is a homeomorphism of \(Y\) onto the closed
       subset \(V(\ker(\phi))\) of \(X\) (In particular, \(\Spec(A)\) and \(\Spec(A/\fN)\) where \(\fN\) is
       the nilradical of \(A\) are naturally homeomorphic)
    5. If \phi is injective, then \(\phi^*(Y)\) is dense in \(X\). More precisely, \(\phi^*(Y)\) is dense
       in \(X\) iff \(\ker(\phi)\subseteq\fN\)
    6. Let \(\psi:B\to C\) be another ring homomorphism. Then \((\psi\circ\phi)^*=\phi^*\circ\psi^*\)
    7. Let \(A\) be an integral domain with just one non-zero prime ideal \(\fp\), and let \(K\) be
       the field of fractions of \(A\). Let \(B=(A/\fp)\times K\). Define \(\phi:A\to B\) by \(\phi(x)=(\barx,x)\)
       where \(\barx\) is the image of \(x\) in \(A/\fp\). Show that \(\phi^*\) is bijection but not a homeomorphism
    #+END_exercise

    #+BEGIN_proof
    1. \(\fq\in X_{\phi(f)}\) iff \(\fq\notin V(\phi(f))\).  \(\phi^*(\fq)\in X_f\) iff \(\phi^*(\fq)\notin V(f)\)
        iff \(\phi^{-1}(\fq)\notin V(f)\).

        If \(\phi^{-1}(\fq)\in V(f)\), then \((f)\subseteq\phi^{-1}(\fq)\), then \(\phi((f))\subseteq\fq\).
        Now we show \(\phi((f))=(\phi(f))\). \(x\in\phi((f))\) iff \(x=\phi(af)\) iff \(x=\phi(a)\phi(f)\)
        iff \(x\in(\phi(f))\). Thus \((\phi(f))\subseteq\fq\) and so \(\fq\in V(\phi(f))\).

        If \(\fq\in V(\phi(f))\), then \((\phi(f))\subseteq\fq\), \(\phi(f)\in\fq\) and so \(\phi^{-1}(\phi(f))\in\phi^{-1}(\fq)\).

        \begin{equation*}
        \fq\in\phi^{* -1 }(X_f)\Leftrightarrow\phi^*(\fq)\in X_f\Leftrightarrow f\notin\phi^*(\fq)=\phi^{-1}(\fq)\Leftrightarrow\fq\in Y_{\phi(f)}
        \end{equation*}
    2. \(x\in\phi^{*-1}(V(\fa))\) iff \(\phi^*(x)\in V(\fa)\) iff \(\phi^{-1}(x)\in V(\fa)\) iff \(\fa\subseteq\phi^{-1}(x)\)
       iff \(\phi(\fa)\subseteq x\) iff \(\fa^e\subseteq x\) iff \(x\in V(\fa^e)\)
       \begin{equation*}
        \fq\in\phi^{* -1}(V(\fa))\Leftrightarrow\phi^*(\fq)\in V(\fa)\Leftrightarrow\fa\subseteq\phi^*(\fq)\Leftrightarrow\fa^e\subseteq\fq\Leftrightarrow\fq\in V(\fa^e)
       \end{equation*}
    3. By remark, \(\bbar{\phi^*(V(\fb))}\) is the set of prime ideals containing \(\bigcap\phi^*(V(\fb))\), which
       equals
       \begin{align*}
       &\bigcap\{\fq^c:\fq\in V(\fb)\}=\bigcap\{\fq^c:\fb\subseteq\fq\}=\left( \bigcap_{\fb\subseteq\fq\in Y}\fq \right)^c=r(\fb)^c=r(\fb^c)\\
       &x\in\bigcap_{\fq\in X}\fq^c\Leftrightarrow\forall\fq\in X(x\in\fq^c)\Leftrightarrow\forall\fq\in X(f(x)\in\fq)\\&\Leftrightarrow f(x)\in\bigcap_{\fq\in X}\fq\Leftrightarrow x\in(\bigcap\fq)^c\\
       &x\in r(\fb)^c\Leftrightarrow f(x)^n\in\fb\Leftrightarrow f(x^n)\in\fb\Leftrightarrow x^n\in\fb^c\Leftrightarrow x\in r(\fb^c)
       \end{align*}
    4. If \(\phi:A\to B\) is surjective, then the image of ideal of \(A\) is an ideal of \(B\). [[https://math.stackexchange.com/questions/1805457/how-to-prove-that-the-image-of-a-prime-ideal-is-also-a-prime-ideal][Image of
       prime ideal]]. For any \(x\in V(\ker(\phi))\), \(\phi(x)\) is prime and is its preimage.
       If \(\phi^*(y_1)=\phi^*(y_2)\), then \(\phi^{-1}(y_1)=\phi^{-1}(y_2)\). Hence \(y_1=y_2\) as \phi is surjective.
       Thus \phi is a bijection

       For any \(Y_f\in Y\)
       \begin{equation*}
       \fq\in\phi^*(Y_f)\Leftrightarrow\fq=\phi^*(\fp)\notin\phi^*(f)\Leftrightarrow \phi^{-1}(f)\notin\fq\Leftrightarrow\fq\in X_{\phi^{-1}(x)}
       \end{equation*}
       So \(\phi^*(Y_f)=X_{\phi^{-1}(f)}\)

       Consider the canonical map \(\phi:A\to A/\fN\). Then we have \(\Spec(A/\fN)\cong V(\fN)=\Spec(A)\)
    5. Note that \(\phi^*(Y)=V(\ker(\phi))\). Thus
       \begin{equation*}
       \bbar{\phi^*(Y)}=V(\bigcap\phi^*(Y))=V(\bigcap V(\ker(\phi))=V(r(\ker(\phi)))=V(\ker(\phi))
       \end{equation*}
    6. For any \(\fp\in Z=\Spec(C)\)
       \begin{equation*}
       (\psi\circ\phi)^*(\fp)=(\psi\circ\phi)^{-1}(\fp)=\phi^{-1}(\psi^{-1}(\fp))=\phi^*\circ\psi^*(\fp)
       \end{equation*}
    7. \(\fp\) is maximal and \(A/\fp\) is a field. Thus \(B\) has
       ideal \(0\times 0\), \(0\times K\), \((A/\fp)\times 0\) and \((A/\fp)\times K\)

       \(A\) has prime ideals \((0)\) and \(\fp\). \(B\) has prime ideals \(0\times K\) and \((A/\fp)\times 0\).
       In \(\Spec(B)=\{\fq_1,\fq_2\}\), we have \(\{\fq_1\}=V(\fq_1)\) is closed as \(\fq_1\not\subseteq\fq_2\), but \(\phi^*(\fq_1)\)
       is not closed in \(\Spec(A)\) as \(0\) is not a maximal ideal of \(A\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.22
    Let \(A=\prod_{i=1}^nA_i\) be the direct product of rings \(A_i\). Show that \(\Spec(A)\) is the
    disjoint union of open (and closed) subspaces \(X_i\), where \(X_i\) is canonically homeomorphic
    with \(\Spec(A_i)\)

    Conversely let \(A\) be any ring. Show that TFAE
    1. \(X=\Spec(A)\) is disconnected
    2. \(A\cong A_1\times A_2\) where neither of the rings \(A_1,A_2\) is the zero ring
    3. \(A\) contains an idempotent \(\neq 0,1\)


    In particular, the spectrum of a local ring is always connected (Exercise ref:ex1.12)
    #+END_exercise

    #+BEGIN_proof
    Let \(\pi_i:A\to A_i\) be the canonical projection, and \(\fb_i=\prod_{j\neq i}A_j\) its kernel; then by
    ref:ex1.21 (4) \(\pi^*_i\) is a homeomorphism \(\Spec(A_i)\cong V(\fb_i)\). Since \(\bigcap_{i=1}^n\fb_i=0\), it
    follows that \(\bigcup V(\fb_i)=V(\bigcap\fb_i)=V(0)=\Spec(A)\), so that \(V(\fb_i)\) cover \(\Spec(A)\).
    Since \(\fb_i+\fb_j=A\) for \(i\neq j\) and hence \(V(\fb_i)\cap V(\fb_j)=V(\fb_i+\fb_j)=V(1)=\emptyset\), it follows
    that \(V(\fb_j)\) are disjoint. Since the complement \(\bigcup_{j\neq i}V(\fb_j)\) of each \(V(\fb_i)\) is a
    finite union of closed sets, the \(V(\fb_i)\) are also open. (VERY NICE PROOF)

    \(2\to 1\) follows as above

    \(X\) is disconnected iff there is non-zero \(\fa\) and \(\fb\)
    s.t. \(X=V(\fa)\cup V(\fb)=V(\fa\fb)\) and \(\emptyset=V(\fa)\cap V(\fb)=V(\fa\cup\fb)=V(\fa+\fb)\). Thus \(\fa+\fb=(1)\)
    and \(r(\fa\fb)=\fN\). There are \(f\in\fa,g\in\fb,n\in\N_+\) s.t. \(f+g=1\) and \((fg)^n=0\).
    Since \((f,g)\subseteq r((f^n,g^n))\) and \(V(f,g)\) is not empty, \(V(f^n,g^n)\) is not empty.
    Thus \((f^n)+(g^n)=(1)\).

    \(1\to 3\). the Chinese Remainder Theorem implies that \(A\to (A/(f^n))\times (A/(g^n))\)
    is an isomorphism. Neither of \(f,g\) is a unit, because they are elements of the proper
    ideals \(\fa,\fb\)

    \(1\to 2\). we can find  \(e\in(f^n)\) s.t. \(1-e\in(g^n)\). We then have \(e-e^2=e(1-e)\in(ab)^n=0\),
    so \(e=e^2\)

    \(3\to 2\). Suppose \(e\neq 0,1\) is an idempotent. Then \(1-e\) is also an idempotent \(\neq 0,1\), and
    neither is a unit. This means \((e)\) and \((1-e)\) are proper, nonzero ideals, and they are
    coprime since \(e+(1-e)=1\). Since \((e)(1-e)=(e-e^2)=0\), then \((e)\cap(1-e)=(0)\). Hence we have
    an isomorphism \(\phi:A\to (A/(e))\times(A/(1-e))\).
    #+END_proof

    #+BEGIN_exercise
    label:ex1.23
    Let \(A\) be a Boolean ring and let \(X=\Spec(A)\)
    1. For each \(f\in A\) the set \(X_f\) is both open and closed in \(X\)
    2. Let \(f_1,\dots,f_n\in A\) .Show that \(X_{f_1}\cup\dots\cup X_{f_n}=X_f\) for some \(f\in A\)
    3. The sets \(X_f\) are the only subsets of \(X\) which are both open and closed
    4. \(X\) is a compact Hausdorff space

    #+END_exercise

    #+BEGIN_proof
    1. For any \(\fp\in X\), \(f(1-f)=0\in\fp\) and hence either \(f\in\fp\) or \(1-f\in\fp\). Thus \(X=X_f\cup X_{1-f}\)
    2. \(x\in X_{f_1}\cup\dots\cup X_{f_n}\) iff \(x\in V(f_1)^c\cup\dots\cup V(f_n)^c\) iff \(x\in(V(f_1)\cap\dots\cap V(f_n))^c\) iff
       \(x\in(V((f_1,\dots,f_n)))^c\). By Exercise ref:ex1.11, \((f_1,\dots,f_n)=(g)\) for some \(g\).
       Hence \(X_{f_1}\cup\dots\cup X_{f_n}=X_g\)
    3. Let \(Y\subseteq X\) be both open and closed. Since \(Y\) is open, it is a union of basic open
       sets \(X_f\). Since \(Y\) is closed and \(X\) is quasi-compact (Exercise ref:ex1.17), \(Y\)
       is quasi-compact. Hence \(Y\) is a finite union of basic open sets and hence equals a basic
       open sets.
    4. For any \(\fp\neq\fq\in X\), \(\fp\) and \(\fq\) are maximal according to Exercise ref:ex1.11.
       Hence \(\fp\in V(\fp)\) and \(\fq\notin V(\fq)\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.24
    Let \(L\) be a lattice, where the sup and inf of two elements \(a,b\) are denoted by \(a\vee b\)
    and \(a\wedge b\) respectively. \(L\) is a *Boolean lattice* (or *Boolean algebra*) if
    1. \(L\) has a least element and a greatest element (denoted by 0,1 respectively)
    2. Each of \(\vee\), \(\wedge\) is distributive over the other
    3. Each \(a\in L\) has a unique "complement" \(a'\in L\) s.t. \(a\vee a'=1\) and \(a\wedge a'=0\)


    Let \(L\) be a Boolean lattice. Define addition and multiplication in \(L\) by rules
    \begin{equation*}
    a+b=(a\wedge b')\vee(a'\wedge b),\quad ab=a\wedge b
    \end{equation*}
    Verify that in this way \(L\) becomes a Boolean ring, say \(A(L)\)

    Conversely, starting from a Boolean ring \(A\), define an ordering on \(A\) as follows: \(a\le b\)
    means \(a=ab\). Show that, w.r.t. this ordering, \(A\) is a Boolean lattice. In this way we
    obtain a one-to-one correspondence between (isomorphism classes of) Boolean rings
    and (isomorphism classes of) Boolean lattices
    #+END_exercise

    #+BEGIN_proof
    De Morgan's laws: \((x\vee y)'=x'\wedge y'\) and \((x\wedge y)'=x'\vee y'\)
    \begin{align*}
    &(x'\wedge y')\wedge(x\vee y)=(x'\wedge y'\wedge x)\vee(x'\wedge y'\wedge y)=0\vee 0=0\\
    &(x'\wedge y')\vee(x\vee y)=(x\vee y\vee x')\wedge(x\vee y\vee y')=1\wedge 1=1
    \end{align*}
    As complement is unique, \(x'\wedge y'=(x\vee y)'\)

    \(a+a=(a\wedge a')\vee(a'\wedge a)=a\wedge a'=0\). Thus \(a+a=0\). \(a+b=b+a\).

    \(a+a'=(a\wedge a'')\vee(a'\wedge a')=a\vee a'=1\).

    \((ab)c=a(bc)\). \(x^2=x\wedge x=x\)


    \(a\vee b=a+b+ab\), \(a\wedge b=ab\). 0 and 1 are minimum and maximum respectively.
    \(a\wedge(b\vee c)=a(b+c+bc)=ab+ac+abc=ab+ac+a^2bc=(ab)\vee(ac)\). As \(a+a=0\),
    \(a\vee a=a+a+a^2=a\).

    \(a\vee a'=a+a'+aa'=1\), \(a\wedge a'=aa'=0\). Hence \(a'=1-a\).

    #+END_proof

    #+BEGIN_exercise
    label:ex1.25
    From the last two exercises deduce Stone's theorem, that every Boolean lattice is isomorphic to
    the lattice of open-and-closed subsets of some compact Hausdorff topological space
    #+END_exercise

    #+BEGIN_proof
    Given a Boolean lattice \(L\), define
    \begin{equation*}
    \phi:L\to\calp(\Spec(A(L))):f\mapsto X_f
    \end{equation*}
    if \(f\le g\), then \(f=fg\) and so \(X_f\cap X_g=X_{fg}=X_f\), which yields \(X_f\subseteq X_g\).

    If \(X_f=X_g\), then as \(1+g=g'\), then \(g\in\fp\) iff \(g'\notin\fp\)
    \begin{equation*}
    X_f=X_g=X_{(1+g)}^c
    \end{equation*}
    So \(X_f\cap X_{(1+g)}=X_{f(1+g)}\) is empty. Therefore \(f(1+g)\) is nilpotent.
    Then \(f^n(1+g)^n=f^{n-1}(1+g)^{n-1}=\dots=f(1+g)=0\). In particular \(f=-fg=fg\). So \(f\le g\).

    On the other hand, the image of \phi is precisely the class of open-and-closed subspaces of the
    compact Hausdorff space
    #+END_proof

    #+BEGIN_exercise
    label:ex1.26
    Let \(A\) be a ring.  The subspace of \(\Spec(A)\) consisting of the /maximal/ ideals of \(A\),
    with the induced topology, is called the *maximal spectrum* of \(A\) is denoted by \(\Max(A)\).
    For arbitrary commutative rings it does not have the nice functorial properties of \(\Spec(A)\)
    (Exercise ref:ex1.21), because the inverse image of a maximal ideal under a ring homomorphism
    need not be maximal (consider \(i:\Z\to\Q\), as \(\Q\) is a field, its maximal ideal is \((0)\),
    which is not a maximal ideal in \(\Z\))

    Let \(X\) be a compact Hausdorff space and let \(C(X)\) denote the ring of all real-valued
    continuous functions on \(X\) (add and multiply functions by adding and multiplying their
    values). For each \(x\in X\), let \(\fm_x\) be the set of all \(f\in C(X)\) s.t. \(f(x)\). The
    ideal \(\fm_x\) is maximal, because it is the kernel of the (surjective) homomorphism \(C(X)\to\R\)
    which takes \(f\) to \(f(x)\). If \(\tilX\) denotes \(\Max(C(X))\), we have therefore defined a
    mapping \(\mu:X\to\tilX\), namely \(x\mapsto\fm_x\)

    We shall show that \mu is a homeomorphism of \(X\) onto \(\tilX\)

    1. Let \(\fm\) be any maximal ideal of \(C(X)\), and let \(V=V(\fm)\) be the set of common zeros of
       the functions in \(\fm\): that is,
       \begin{equation*}
       V=\{x\in X:f(x)=0\text{ for all }f\in\fm\}
       \end{equation*}
       Suppose that \(V\) is empty. Then for each \(x\in X\) there exists \(f_x\in\fm\) s.t. \(f_x(x)\neq 0\).
       Since \(f_x\) is continuous, there is an open neighborhood \(U_x\) of \(x\) in \(X\) on
       which \(f_x\) does not vanish. By compactness a finite number of the neighborhoods,
       say \(U_{x_1},\dots,U_{x_n}\), cover \(X\). Let
       \begin{equation*}
       f=f_{x_1}^2+\dots+f_{x_n}^2
       \end{equation*}
       Then \(f\) does not vanish at any point of \(X\), hence is a unit in \(C(X)\). But this
       contradicts \(f\in\fm\), hence \(V\) is not empty

       Let \(x\in V\). Then \(\fm\subseteq\fm_x\), hence \(\fm=\fm_x\) because \(\fm\) is maximal. Hence \mu is surjective

    2. By Urysohn's lemma, the continuous functions separate the points of \(X\).
       Hence \(x\neq y\Rightarrow \fm_x\neq\fm_y\), and therefore \mu is injective

    3. Let \(f\in C(X)\); let
       \begin{equation*}
       U_f=\{x\in X:f(x)\neq 0\}
       \end{equation*}
       and let
       \begin{equation*}
       \tilU_f=\{\fm\in\tilX:f\notin\fm\}
       \end{equation*}
       Show that \(\mu(U_f)=\tilU_f\). The open set \(U_f\) (resp. \(\tilU_f\)) form a basis of the
       topology of \(X\) (resp. \(\tilX\)) and therefore \mu is a homeomorphism

       Thus \(X\) can be reconstructed from the ring of functions \(C(X)\)
    #+END_exercise

    /Affine algebraic variesties/

    #+BEGIN_exercise
    label:ex1.27
    Let \(k\) be an algebraic closed field and let
    \begin{equation*}
    f_\alpha(t_1,\dots,t_n)=0
    \end{equation*}
    be a set of polynomial equations in \(n\) variables with coefficients in \(k\). The set \(X\) of
    all points \(x=(x_1,\dots,x_n)\in k^n\) which satisfy these equations is an *affine algebraic variety*

    Consider the set of all polynomials \(g\in k[t_1,\dots,t_n]\) with the property that \(g(x)=0\) for
    all \(x\in X\). This set is an ideal \(I(X)\) in the polynomial ring, and is called the *ideal of
    the variety* \(X\). The quotient ring
    \begin{equation*}
    P(X)=k[t_1,\dots,t_n]/I(X)
    \end{equation*}
    is the ring of polynomial functions on \(X\), because two polynomials \(g,h\) define the same
    polynomial function on \(X\) iff \(g-h\) vanishes at every point of \(X\) iff \(g-h\in I(X)\)

    Let \(\xi_i\) be the image of \(t_i\) in \(P(X)\). The \(\xi_i\) (\(1\le i\le n\)) are the *coordinate
    functions* on \(X\): if \(x\in X\), then \(\xi_i(x)\) is the \(i\)th coordinate of \(x\). \(P(X)\) is
    generated as a \(k\)-algebra by the coordinate functions, and is called the *coordinate ring* (or
    affine algebra) of \(X\)

    As
    #+END_exercise
* Modules
    Let \(A\) be a ring (commutative, as always). An *\(A\)-module* is an abelian group \(M\) (written
    additively) on which \(A\) acts linearly: more precisely, it is a pair \((M,\mu)\), where \(M\) is
    an abelian group and \mu is a mapping of \(A\times M\) into \(M\), s.t., if we write \(ax\)
    for \(\mu(a,x)\), the following axioms are satisfied for \(a,b\in A\) and \(x,y\in M\)
    \begin{align*}
    a(x+y)&=ax+ay\\
    (a+b)x&=ax+bx\\
    (ab)x&=a(bx)\\
    1x&=x
    \end{align*}
    Equivalently, \(M\) is an abelian group together with a ring homomorphism \(A\to E(M)\),
    where \(E(M)\) is a ring of endomorphisms of the abelian group \(M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. An ideal \(\fa\) of \(A\) is an \(A\)-module. In particular \(A\) itself is an \(A\)-module
    2. If \(A\) is a field \(k\), then \(A\)-module = \(k\)-vector space
    3. \(A=\Z\), then \(\Z\)-module = abelian group (define \(nx\) to \(x+\dots+x\))
    4. \(A=k[x]\) where \(k\) is a field; an \(A\)-module is a \(k\)-vector space with a linear transformation.
    5. \(G\)=finite group, \(A=k[G]\)=group-algebra of \(G\) over the field \(k\) (thus \(A\) is not
       commutative, unless \(G\) is). Then \(A\)-module=\(k\)-representation of \(G\)
    #+END_examplle

    Let \(M,N\) be \(A\)-modules. A mapping \(f:M\to N\) is an *\(A\)-module homomorphism* (or is
    *\(A\)-linear*) if
    \begin{align*}
    f(x+y)&=f(x)+f(y)\\
    f(ax)&=a\cdot f(x)
    \end{align*}
    for all \(a\in A\) and all \(x,y\in M\). Thus \(f\) is a homomorphism of abelian groups which
    commutes with the action of each \(a\in A\). If \(A\) is a field, an \(A\)-module homomorphism is
    the same thing as a linear transformation of vector space

    The composition of \(A\)-module homomorphism is again an \(A\)-homomorphism

    The set of all \(A\)-module homomorphism from \(M\) to \(N\) can be turned into an \(A\)-module
    as follows: we define \(f+g\) and \(af\) by the rules
    \begin{align*}
    (f+g)(x)&=f(x)+g(x)\\
    (af)(x)&=a\cdot f(x)
    \end{align*}
    for all \(x\in M\). This \(A\)-module is denoted by \(\Hom_A(M,N)\)

    Homomorphisms \(u:M'\to M\) and \(v:N\to N''\) induces mappings
    \begin{equation*}
    \baru:\Hom(M,N)\to\Hom(M,N)\quad\text{ and }\quad\barv:\Hom(M,N)\to\Hom(M,N'')
    \end{equation*}
    defined as follows
    \begin{equation*}
    \baru(f)=f\circ u,\quad\barv(f)=v\circ f
    \end{equation*}

    For any module \(M\) there is a natural isomorphism \(\Hom(A,M)\cong M\): any \(A\)-module
    homomorphism \(f:A\to M\) is uniquely determined by \(f(1)\), which can be any element of \(M\)

    A *submodule* \(M'\) of \(M\) is a subgroup of \(M\) which is closed under multiplication by
    elements of \(A\). Then abelian group \(M/M'\) then inherits an \(A\)-module structure
    from \(M\), defined by \(a(x+M')=ax+M'\). The \(A\)-module \(M/M'\) is the *quotient* of \(M\)
    by \(M'\). There is a one-to-one order-preserving correspondence between submodules of \(M\)
    which contain \(M'\), and submodules \(M''=M/M'\)

    If \(f:M\to N\) is an \(A\)-module homomorphism, the *kernel* of \(f\) is the set
    \begin{equation*}
    \ker(f)=\{x\in M:f(x)=0\}
    \end{equation*}
    and is a submodule of \(M\). The *image* of \(f\) is the set
    \begin{equation*}
    \im(f)=f(M)
    \end{equation*}
    and is a submodule of \(N\). The *cokernel* of \(f\) is
    \begin{equation*}
    \coker(f)=N/\im(f)
    \end{equation*}
    which is a quotient module of \(N\).

    If \(M'\) is a submodule of \(M\) s.t. \(M'\subseteq\ker(f)\), then \(f\) give rise to a
    homomorphism \(\barf:M/M'\to N\) defined as follows: if \(\barx\in M/M'\) is the image of \(x\in M\),
    then \(\barf(\barx)=f(x)\). The kernel of \(\barf\) is \(\ker(f)/M'\)

    Let \(M\) be an \(A\)-module and let \((M_i)_{i\in I}\) be a family of submodules of \(M\). Their
    *sum* \(\sum M_i\) is the set of all (finite) sums \(\sum x_i\), where \(x_i\in M_i\) for all \(i\in I\), and
    almost all the \(x_i\) are zero. \(\sum M_i\) is the smallest submodule of \(M\) which contains all
    the \(M_i\)

    The intersection \(\bigcap M_i\) is again a submodule of \(M\). Thus the submodules of \(M\) form a
    complete lattice w.r.t. inclusion

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. If \(L\supseteq M\supseteq N\) are \(A\)-modules, then
       \begin{equation*}
       (L/N)/(M/N)\cong L/M
       \end{equation*}
    2. If \(M_1,M_2\) are submodules of \(M\), then
       \begin{equation*}
       (M_1+M_2)/M_1\cong M_2/(M_1\cap M_2)
       \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    1. Define \(\theta:L/N\to L/M\) by \(\theta(x+N)=x+M\). Then \theta is a well-defined \(A\)-module homomorphism
       of \(L/N\) onto \(L/M\), and its kernel is \(M/N\);
    2. The composite homomorphism \(M_2\to M_1+M_2\to(M_1+M_2)/M_1\) is surjective, and its kernel
       is \(M_1\cap M_2\)
    #+END_proof

    We cannot in general define the *product* of two submodules, but we can define the product \(\fa M\)
    where \(\fa\) is an ideal and \(M\) an \(A\)-module; it is the set of all finite sums \(\sum a_ix_i\)
    with \(a_i\in\fa\), \(x_i\in M\) and is a submodule of \(M\)

    If \(N,P\) are submodule of \(M\), we define \((N:P)\) to be the set of all \(a\in A\)
    s.t. \(aP\subseteq N\); it is an *ideal* of \(A\). In particular, \((0:M)\) is the set of all \(a\in A\)
    s.t. \(aM=0\); this ideal is called the *annihilator* of \(M\) and is also denoted by \(\Ann(M)\).
    If \(\fa\subseteq\Ann(M)\), we may regard \(M\) as an \(A/\fa\)-module as follows: if \(\barx\in A/\fa\) is
    represented by \(x\in A\), define \(\barx m\) to be \(xm\)

    An \(A\)-module is *faithful* if \(\Ann(M)=0\). If \(\Ann(M)=\fa\), then \(M\) is faithful as
    an \(A/\fa\)-module

    #+BEGIN_exercise
    1. \(\Ann(M+N)=\Ann(M)\cap\Ann(N)\)
    2. \((N:P)=\Ann((N+P)/N)\)
    #+END_exercise

    #+BEGIN_proof
    2. [@2] \(a((N+P)/N)=0\) iff \(a(N+P)\subseteq N\) iff \(aP\subseteq N\)
    #+END_proof

    If \(x\in M\), the set of all multiples \(ax\) (\(a\in A\)) is a submodule of \(M\), denoted
    by \(Ax\) or \(x\). If \(M=\sum_{i\in I}Ax_i\), the \(x_i\) are said to be a *set of generators*
    of \(M\). An \(A\)-module is said to be *finitely generated* if it has a finite set of generators

    If \(M,N\) are \(A\)-modules, their *direct sum* \(M\oplus N\) is the set of all pairs \((x,y)\)
    with \(x\in M\), \(y\in N\). This is an \(A\)-module if we define addition and scalar multiplication
    in the obvious way:
    \begin{align*}
    (x_1,y_1)+(x_2,y_2)&=(x_1+x_2,y_1+y_2)\\
    a(x,y)&=(ax,ay)
    \end{align*}
    More generally, if \((M_i)_{i\in I}\) is any family of \(A\)-modules, we can define their *direct
    sum* \(\bigoplus_{i\in I}M_i\); its elements are families \((x_i)_{i\in I}\) s.t. \(x_i\in M_i\) for each \(i\in I\)
    and almost all \(x_i\) are 0. If we drop the restriction on the number of non-zero \(x\)'s we
    have the *direct product* \(\prod_{i\in IM_i}\).

    Suppose that the ring \(A\) is a direct product \(\prod_{i=1}^nA_i\). Then the set of all elements
    of \(A\) of the form
    \begin{equation*}
    (0,\dots,0,a_i,0,\dots,0)
    \end{equation*}
    with \(a_i\in A_i\) is an *ideal* \(\fa_i\) of \(A\). The ring \(A\), considered as an \(A\)-module, is
    the direct sum of the ideals \(\fa_1,\dots,\fa_n\). Conversely, given a module decomposition
    \begin{equation*}
    A=\fa_1\oplus\dots\oplus\fa_n
    \end{equation*}
    of \(A\) as a direct sum of ideals, we have
    \begin{equation*}
    A\cong\prod_{i=1}^n(A/\fb_i)
    \end{equation*}
    where \(\fb_i=\oplus_{j\neq i}\fa_j\). Each ideal \(\fa_i\) is a ring (isomorphic to \(A/\fb_i\)). The identity
    element \(e_i\) of \(\fa_i\) is an idempotent in \(A\), and \(\fa_i=(e_i)\)

    A *free* \(A\)-module is one which is isomorphic to an \(A\)-module of the form \(\bigoplus_{i\in I}M_i\),
    where each \(M_i\cong A\) (as an \(A\)-module). The notation \(A^{(I)}\) is sometimes used. A finite
    generated free \(A\)-module is therefore isomorphic to \(A\oplus\dots\oplus A\) (\(n\) summands), which is
    denoted by \(A^n\). (Conventionally, \(A^0\) is the zero module, denoted by 0)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(M\) is a finitely generated \(A\)-module iff \(M\) is isomorphic a quotient of \(A^n\) for some
    integer \(n>0\)
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\). Let \(x_1,\dots,x_n\) generate \(M\). Define \(\phi:A^n\to M\) by \(\phi(a_1,\dots,a_n)=a_1x_1+\dots+a_nx_n\).
    Then \phi is an \(A\)-module homomorphism onto \(M\), and therefore \(M\cong A^n/\ker(\phi)\)

    \(\Leftarrow\). We have an \(A\)-module homomorphism \phi of \(A^n\) onto \(M\). If \(e_i=(0,\dots,0,1,0,\dots,0)\)
    (the 1 being in the \(i\)th place), then the \(e_i\) generate \(A^n\), hence the \(\phi(e_i)\)
    generate \(M\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:2.4
    Let \(M\) be a finitely generated \(A\)-module, let \(\fa\) be an ideal of \(A\), and let \phi be
    an \(A\)-module endomorphism of \(M\) s.t. \(\phi(M)\subseteq\fa M\) and let
    \(\psi:A\to\End_A(M)\) be the natural morphism. Then \phi satisfies an equation of the
    form
    \begin{equation*}
    \phi^n+\psi(a_1)\phi^{n-1}+\dots+\psi(a_n)=0
    \end{equation*}
    where the \(a_i\in\fa\).
    #+END_proposition

    #+BEGIN_proof
    Let \(x_1,\dots,x_n\) be a set of generators of \(M\). Then each \(\phi(x_i)\in\fa M\), so that we have to
    say \(\phi(x_i)=\sum_{j=1}^na_{ij}x_j\) (\(1\le i\le n;a_{ij}\in\fa\)), i.e.,
    \begin{equation*}
    \sum_{j=1}^n(\delta_{ij}\phi-a_{ij})x_j=0
    \end{equation*}
    where \(\delta_{ij}\) is the Kronecker delta. By multiplying on the left by the adjoint of the
    matrix \((\delta_{ij}\phi-a_{ij})\) it follows that \(\det(\delta_{ij}\phi-a_{ij})\) annihilates each \(x_i\),
    hence is the zero endomorphism of \(M\). Expanding out the determinant, we have an equation of
    the required form

    <<Problem2>>
    [[https://math.stackexchange.com/questions/1197842/proof-of-proposition-2-4-in-atiyah-macdonald/1197946][Explanation]]
    Consider the commutative ring \(R=A[\phi]\subset\End_A(M)\) generated by \phi; then \(R\) acts on \(M\), and
    thus \(M_n(R)\) acts \(M^n\). The equations
    \begin{equation*}
    \phi(x_j)=\sum_{i=1}^na_{ij}x_i
    \end{equation*}
    for \(j=1,\dots,n\) can be reinterpreted with the action of \(M_n(R)\) on \(M^n\): write
    \begin{equation*}
    B=
    \begin{pmatrix}
    a_{11}-\phi&a_{12}&a_{13}&\dots\\
    a_{21}&a_{22}-\phi&a_{23}&\dots\\
    a_{31}&a_{32}&a_{33}-\phi&\dots\\
    \vdots&\vdots&\vdots&\ddots
    \end{pmatrix}\in M_n(R) \quad\text{ and }\quad
    X=
    \begin{pmatrix}
    x_1\\x_2\\\vdots\\x_n
    \end{pmatrix}\in M^n
    \end{equation*}
    Then the \(n\) equations we wrote are equivalent to
    \begin{equation*}
    BX=0
    \end{equation*}
    Since \(R\) is commutative, we have
    \begin{equation*}
    \Adj(B)\times B=\det(B)I_n=B\times \Adj(B)
    \end{equation*}
    which is an equation which holds in \(M_n(R)\) (NEED TO VERIFY). If we multiply the previous
    equation on the left by \(\Adj(B)\), we get
    \begin{equation*}
    0=\Adj(B)BX=
    \begin{pmatrix}
    \det(B)&&&\\
    &\det(B)&&\\
    &&\ddots&\\
    &&&\det(B)
    \end{pmatrix}
    \begin{pmatrix}
    x_1\\x_2\\\vdots\\x_n
    \end{pmatrix}=
    \begin{pmatrix}
    \det(B)x_1\\\det(B)x_2\\\vdots\\\det(B)x_n
    \end{pmatrix}
    \end{equation*}
    Since the \(x_i\) generate \(M\), this is equivalent to say that \(\det(B)\), which is an element
    of \(R\), hence an endomorphism of \(M\), *is the zero endomorphism of* \(M\).

    The determinant \(\det(B)\in R\subset\End_A(M)\) can be calculated by the standard formula
    \begin{equation*}
    \det(B)=\sum_{\sigma\in \fS_n}(-1)^\sigma\prod_{j=1}^nB_{\sigma(j),j}
    \end{equation*}
    which is polynomial in \phi of degree \(n\) with coefficients in the ideal \(\fa\). The coefficient
    in front of \(\phi^n\) is \((-1)^n\) and since \(\det(B)=0\), we get
    \begin{equation*}
    \phi^n+a_1\phi^{n-1}+\dots+a_{n-1}\phi+a_n id_M=0
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:2.5
    Let \(M\) be a finitely generated \(A\)-module and let \(\fa\) be an ideal of \(A\)
    s.t. \(\fa M=M\). Then there exists \(x\equiv 1\mod\fa\)  s.t. \(xM=0\)
    #+END_corollary

    #+BEGIN_proof
    Take \(\phi=\id\), then \(1+a_1+\dots+a_n=0\in\End_A(M)\). Let
    \(x=1+a_1+\dots+a_n\in\fa\)
    by ref:2.4
    #+END_proof

    #+ATTR_LATEX: :options [Nakayama's lemma]
    #+BEGIN_proposition
    label:2.6
    Let \(M\) be a finitely generated \(A\)-module and \(\fa\) an ideal of \(A\) contained in the
    Jacobson radical \(\fR\) of \(A\). Then \(\fa M=M\) implies \(M=0\)
    #+END_proposition

    #+ATTR_LATEX: :options [First Proof]
    #+BEGIN_proof
    By ref:2.5 we have \(xM=0\) for some \(x\equiv 1\mod\fR\). By ref:1.9 \(x\) is a unit in \(A\), hence \(M=x^{-1}xM=0\)
    #+END_proof

    #+ATTR_LATEX: :options [Second Proof]
    #+BEGIN_proof
    Suppose \(M\neq 0\), and let \(u_1,\dots,u_n\) be a minimal set of generators of \(M\). Then \(u_n\in\fa M\)
    hence we have an equation of the form \(u_n=a_1u_1+\dots+a_nu_n\) with the \(a_i\in\fa\). Hence
    \begin{equation*}
    (1-a_n)u_n=a_1u_1+\dots+a_{n-1}u_{n-1}
    \end{equation*}
    since \(a_n\in\fR\), it follows from ref:1.9 that \(1-a_{n}\) is a unit in \(A\). Hence \(u_n\)
    belongs to the submodule of \(M\) generated by \(u_1,\dots,u_{n-1}\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:2.7
    Let \(M\) be a finitely generated \(A\)-module, \(N\) is a submodule of \(M\), \(\fa\subseteq\fR\) an ideal.
    Then \(M=\fa M+N\Rightarrow M=N\)
    #+END_corollary

    #+BEGIN_proof
    Apply ref:2.6 to \(M/N\), observing that \(\fa(M/N)=\fa M/N=(\fa M+N)/N\). Thus \(M/N=\fa(M/N)\) and
    thus \(M/N=0\).
    #+END_proof

    Let \(A\) be a local ring, \(\fm\) its maximal ideal, \(k=A/\fm\) its residue field. Let \(M\) be a
    finitely generated \(A\)-module. \(M/\fm M\) is annihilated by \(\fm\), hence is naturally
    an \(A/\fm\)-module, i.e., a \(k\)-vector space, and as such is finite-dimensional

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(x_i\) (\(1\le i\le n\)) be elements of \(M\) whose images in \(M/\fm M\) form a basis of this
    vector space. Then the \(x_i\) generate \(M\)
    #+END_proposition

    #+BEGIN_proof
    Let \(N\) be the submodule of \(M\) generated by the \(x_i\). Then the composite
    map \(N\to M\to M/\fm M\) maps \(N\) onto \(M/\fm M\), hence \(N+\fm M=M\), hence \(N=M\) by ref:2.7
    #+END_proof

    If \(A=C/B\), then \(A+B=C\)

    A sequence of \(A\)-modules and \(A\)-homomorphisms
    \begin{center}\begin{tikzcd}
    \cdots\ar[r]&M_{i-1}\ar[r,"f_i"]&M_i\ar[r,"f_{i+1}"]&M_{i+1}\ar[r]&\cdots
    \end{tikzcd}\end{center}
    is said to be *exact at* \(M_i\) if \(\im(f_i)=\ker(f_{i+1})\). The sequence is *exact* if it is exact
    at each \(M_i\). In particular
    1. \(0\to M'\xrightarrow{f}M\) is exact \(\Leftrightarrow\) \(f\) is injective
    2. \(M\xrightarrow{g}M''\to 0\) is exact \(\Leftrightarrow\) \(g\) is surjective
    3. \(0\to M'\xrightarrow{f}M\xrightarrow{g}M''\to 0\) is exact \(\Leftrightarrow\) \(f\) is injective, \(g\) is surjective and \(g\)
       induces an isomorphism of \(\coker(f)=M/f(M')\) onto \(M''\).
       \(M''\cong M/\ker(g)=M/\im(f)\)


    A sequence of type 3 is called a *short exact sequence*. Any long exact sequence can be split up
    into short exact sequences: if \(N_i=\im(f_i)=\ker(f_{i+1})\), we have short exact
    sequences \(0\to N_i\to M_i\to N_{i+1}\to 0\) for each \(i\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let
       \begin{center}\begin{tikzcd}
       M'\ar[r,"u"]&M\ar[r,"v"]&M''\ar[r]&0
       \end{tikzcd}\end{center}
       be a sequence of \(A\)-modules and homomorphisms. Then the sequence is exact \(\Leftrightarrow\) for
       all \(A\)-modules \(N\), the sequence
       \begin{center}\begin{tikzcd}
       0\ar[r]&\Hom(M'',N)\ar[r,"\barv"]&\Hom(M,N)\ar[r,"\baru"]&\Hom(M',N)
       \end{tikzcd}\end{center}
       is exact
    2. Let
       \begin{center}\begin{tikzcd}
       0\ar[r]&N'\ar[r,"u"]&N\ar[r,"v"]&N''
       \end{tikzcd}\end{center}
       be a sequence of \(A\)-modules and homomorphisms. Then the sequence is exact \(\Leftrightarrow\) for
       all \(A\)-modules \(M\), the sequence
       \begin{center}\begin{tikzcd}
       0\ar[r]&\Hom(M,N')\ar[r,"\baru"]&\Hom(M,N)\ar[r,"\barv"]&\Hom(M,N'')
       \end{tikzcd}\end{center}

    #+END_proposition

    #+BEGIN_proof
    \begin{center}\begin{tikzcd}
    M'\ar[r,"u"]\ar[rrd,""{name=A}]&M\ar[rr,"v"]\ar[rd,""{name=B}]&&M''\ar[r]\ar[ld,""{name=C}]
    &0\ar[lld,""{name=D}]\\
    &&N\ar[from=B,to=A,"\baru"]\ar[from=C,to=B,"\barv"]\ar[from=D,to=C]
    \end{tikzcd}\end{center}
    Need to modify a bit
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let
    \begin{center}\begin{tikzcd}
    0\ar[r]&M'\ar[r,"u"]\ar[d,"f'"']&M\ar[r,"v"]\ar[d,"f"']&M''\ar[r]\ar[d,"f''"]&0\\
    0\ar[r]&N'\ar[r,"u'"']&N\ar[r,"v'"']&N''\ar[r]&0
    \end{tikzcd}\end{center}
    be a commutative diagram of \(A\)-modules and homomorphisms, with the rows exact. Then there
    exists an exact sequence
    \begin{center}\begin{tikzcd}
    0\ar[r]&\ker(f')\ar[r,"\baru"]&\ker(f)\ar[r,"\barv"]&\ker(f'')\ar[r,"d"]&{}&\\
    &\coker(f')\ar[r,"\baru'"]&\coker(f)\ar[r,"\barv'"]&\coker(f'')\ar[r]&0
    \end{tikzcd}\end{center}

    #+END_proposition

    #+BEGIN_proof
    \(\baru=u\upharpoonright\ker(f')\). For any \(m\in\ker(f')\), \(f(\baru(m))=fu(m)=u'f'(m)=0\). Thus \(\baru(m)\in\ker(f)\). \(\baru\) is injective as \(u\) is.

    \(\barv=v\upharpoonright\ker(f)\). For
    any
    \(m\in\im(\baru)=u(\ker(f'))\),
    \(\im(u)=\ker(v)\). \(\ker(\barv)=\ker(f)\cap\ker(v)\). \(\im(\baru)=u(\ker(f'))\).
    \(x\in\ker(\barv)\Leftrightarrow x\in\ker(v)\cap\ker(f)\Leftrightarrow x\in\im(u)\cap\ker(f)\Leftrightarrow x\in\im(\baru)\)

    The *boundary homomorphism* \(d\) is defined as follows: if \(x''\in\ker(f'')\), we
    have \(x''=v(x)\) for some \(x\in M\) and \(v'(f(x))=f''(v(x))\),
    hence \(f(x)\in\ker(v') =\im(u')\), so that \(f(x)=u'(y')\) for some \(y'\in N'\).  Then \(d(x'')\)
    is defined to be the image of \(y'\) in \(\coker(f')\).

    Suppose there is \(x_1,x_2\) s.t. \(x''=v(x_1)=v(x_2)\). Then \(f(x_1)=u'(y_1')\)
    and \(f(x_2)=u'(y_2')\).
    \begin{align*}
    y_1'+\im(f')=y_2' +\im(f')&\Leftrightarrow\exists x_0'\in M'\; y_1'-y_2'=f(x_0')\\&\Leftrightarrow\exists x_0'\in M'\; u'^{-1}(f(x_1))-u'^{-1}f(x_2)=f'(x_0')
    \\&\Leftrightarrow\exists x_0'\in M'\; f(x_1-x_2)=u'f'(x_0')=fu(x_0')\\&\Leftrightarrow\exists x_0'\in M'\; f(x_1-x_2-u(x_0'))=0
    \\&\Leftrightarrow\exists y\in\im(u)=\ker(v)\;x_1-x_2-y\in\ker(f)
    \end{align*}
    But as \(x_1-x_2\in\ker(v)\), we can simply take \(y=x_1-x_2\)

    Define \(\baru'\) as \(x'+\im(f')\mapsto u'(x')+ \im(f)\). For any \(x''\in M''\), then \(x''=v(x)\).
    Suppose \(f(x)=u'(y')\). Then \(\baru'(y'+\im(f'))=u'(y')+\im(f)=f(x)+\im(f) =\im(f)\).
    Hence \(\im(d) =\ker(\baru')\).
    #+END_proof

    #+begin_src latex
\begin{center}\begin{tikzpicture}[>=angle 90,scale=2.2,text height=1.5ex, text depth=0.25ex]
    %% First place the nodes
    \node (k-1) at (0,3) {$0$};
    \node (k0) [right=of k-1] {$\ker f$};
    \node (k1) [right=of k0] {$\ker a$};
    \node (k2) [right=of k1] {$\ker b$};
    \node (k3) [right=of k2] {$\ker c$};
    \node (a1) [below=of k1] {$A$};
    \node (a2) [below=of k2] {$B$};
    \node (a3) [below=of k3] {$C$};
    \node (a4) [right=of a3] {$0$};
    \node (b1) [below=of a1] {$A$};
    \node (b0) [left=of b1] {$0$};
    \node (b2) [below=of a2] {$B$};
    \node (b3) [below=of a3] {$C$};
    \node (c1) [below=of b1] {$\coker a$};
    \node (c2) [below=of b2] {$\coker b$};
    \node (c3) [below=of b3] {$\coker c$};
    \node (c4) [right=of c3] {$\coker g$};
    \node (c5) [right=of c4] {$0$};
    %% Draw the red arrows
    \draw[->,red,font=\scriptsize]
    (k-1) edge (k0)
    (k0) edge (k1)
    (k1) edge (k2)
    (k2) edge (k3)
    (c1) edge (c2)
    (c2) edge (c3)
    (c3) edge (c4)
    (c4) edge (c5);
    %% Draw the curvy red arrow
    \draw[->,red]
    (k3) edge[out=0,in=180,red] node[pos=0.55,yshift=5pt] {$d$} (c1);
    %% Draw the black arrows
    \draw[->]
    (k1) edge (a1)
    (k2) edge (a2)
    (k3) edge (a3)
    (b1) edge (c1)
    (b2) edge (c2)
    (b3) edge (c3);
    %% Draw the thick blue arrows
    \draw[->,font=\scriptsize,blue,thick]
    (a1) edge node[auto] {$f$} (a2)
    (a2) edge node[auto] {$g$} (a3)
    (a3) edge (a4)
    (a1) edge node[auto] {$a$} (b1)
    (a2) edge node[auto] {$b$} (b2)
    (a3) edge node[auto] {$c$} (b3)
    (b0) edge (b1)
    (b1) edge node[below] {$f$} (b2)
    (b2) edge node[below] {$g$} (b3);
  \end{tikzpicture}\end{center}

    #+end_src

    Let \(C\) be a class of \(A\)-modules and let \lambda be a function on \(C\) with values in \(\Z\) (or,
    more generally, with values in an abelian group \(G\)). The function \lambda is *additive* if, for each
    short exact sequence in which all the terms belongs to \(C\), we have \(\lambda(M')-\lambda(M)+\lambda(M'')=0\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(A\) be a field \(k\), and let \(C\) be the class of all finite-dimensional \(k\)-vector
    spaces \(V\). Then \(V\mapsto\dim V\) is an additive function on \(V\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(0\to M_0\to M_1\to\cdots\to M_n\to 0\) be an exact sequence of \(A\)-modules where all the modules \(M_i\)
    and the kernels of all the homomorphisms belong to \(C\). Then for any additive function \lambda
    on \(C\) we have
    \begin{equation*}
    \sum_{i=0}^n(-1)^i\lambda(M_i)=0
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    Split up the sequence into short exact sequences
    \begin{equation*}
    0\to N_i\to M_i\to N_{i+1}\to 0
    \end{equation*}
    (\(N_0=N_{n+1}=0\) and \(\lambda(M_0)=\lambda(M_n)=2\lambda(0)\)). Then we have \(\lambda(M_i)=\lambda(N_i)+\lambda(N_{i+1})\).
    #+END_proof

    Let \(M,N,P\) be three \(A\)-modules. A mapping \(f:M\times N\to P\) is said to be *\(A\)-bilinear* if
    for each \(x\in M\) the mapping \(y\mapsto f(x,y)\) of \(N\) into \(P\) is \(A\)-linear, and for
    each \(y\in N\) the mapping \(x\mapsto f(x,y)\) of \(M\) into \(P\) is \(A\)-linear

    We shall construct an \(A\)-module \(T\), called the *tensor product* of \(M\) and \(N\), with the
    property that the \(A\)-bilinear mappings \(M\times N\to P\) are in a natural one-to-one correspondence
    with the \(A\)-linear mappings \(T\to P\), for all \(A\)-modules \(P\). More precisely:

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(M,N\) be \(A\)-modules. Then there exists a pair \((T,g)\) consisting of
    an \(A\)-module \(T\) and an \(A\)-bilinear mapping \(g:M\times N\to T\), with the following property:

    Given any \(A\)-module \(P\) and any \(A\)-bilinear mapping \(f:M\times N\to P\), there exists a
    unique \(A\)-linear mapping \(f':T\to P\) s.t. \(f=f'\circ g\)

    Moreover, if \((T,g)\) and \((T',g')\) are two pairs with this property, then there is a unique
    isomorphism \(j:T\to T'\) s.t. \(j\circ g=g'\)
    #+END_proposition

    #+BEGIN_proof
    label:2.12
    1. Uniqueness. Replacing \((P,f)\) by \((T',g')\) we get a unique \(j:T\to T'\) s.t. \(g'=j\circ g\).
    2. Existence. Let \(C\) denote the free \(A\)-module \(A^{(M\times N)}\). The elements of \(C\) are
       formal linear combinations of elements of \(M\times N\) with coefficients in \(A\), i.e., they are
       expressions of the form \(\sum_{i=1}^na_i\cdot(x_i,y_i)\) (\(a_i\in A,x_i\in M,y_i\in N\))
       #+LATEX: \wu{
       here \((x_i,y_i)=(0,\dots,0,1,0,\dots,0)\) where \((x_i,y_i)\)th position is not 0 i think. And direct
       sum only admits finite sum
       #+LATEX: }

       Let \(D\) be the submodule of \(C\) generated by all elements of \(C\) of the following
       types:
       \begin{gather*}
    (x+x',y)-(x,y)-(x',y)\\
    (x,y+y')-(x,y)-(x,y')\\
    (ax,y)-a\cdot(x,y)\\
    (x,ay)-a\cdot(x,y)
       \end{gather*}
       Let \(T=C/D\). For each basis element \((x,y)\) of \(C\), let \(x\otimes y\) denote its image
    in \(T\). Then \(T\) is generated by the elements of the form \(x\otimes y\) and from our definition
    we have
    \begin{gather*}
    (x+x')\otimes y=x\otimes y+x'\otimes y,\quad x\otimes(y+y')=x\otimes y+x\otimes y'\\
    (ax)\otimes y=x\otimes (ay)=a(x\otimes y)
    \end{gather*}
    Equivalently, the mapping \(g:M\times N\to T\) defined by \(g(x,y)=x\otimes y\) is \(A\)-bilinear

    Any map \(f\) of \(M\times N\) into an \(A\)-module \(P\) extends by linearity to an \(A\)-module
    homomorphism \(\barf:C\to P\)
    #+LATEX: \wu{
    \(\barf(\sum_{i=1}^na_i\cdot(x_i,y_i))=\sum_{i=1}^na_i\cdot f(x_i,y_i)\)
    #+LATEX: }
    Suppose in particular that \(f\) is \(A\)-bilinear. Then, from the
    definitions, \(\barf\) vanishes on all the generators of \(D\), hence on the whole of \(D\), and
    therefore induces a well-defined \(A\)-homomorphism \(f'\) of \(T=C/D\) into \(P\)
    s.t. \(f'(x\otimes y)=f(x,y)\)
    #+END_proof

    #+BEGIN_remark
    1. The module \(T\) constructed above is called the *tensor product* of \(M\) and \(N\), and is
       denoted by \(M\otimes_AN\). It is generated as an \(A\)-module by the "products" \(x\otimes y\).
       If \((x_i)_{i\in I},(y_i)_{j\in J}\) are families of generators of \(M,N\) respectively, then the
       elements \(x_i\otimes y_j\) generated \(M\otimes N\)
    2. The notation \(x\otimes y\) is inherently ambiguous unless we specify the tensor product to which
       it belongs. Let \(M',N'\) be submodules of \(M,N\) respectively, and let \(x\in M'\)
       and \(y\in N'\). Then it can happen that \(x\otimes y\) as an element of \(M\otimes N\) is zero
       whilst \(x\otimes y\) as an element of \(M'\otimes N'\) is non-zero. For example,
       take \(A=\Z,M=\Z,N=\Z/2\Z\), and let \(M'\) be the submodule \(2\Z\) of \(\Z\), whilst \(N'=N\).
       Let \(x\) be the non-zero element of \(N\) and consider \(2\otimes x\). As an element
       of \(M\otimes N\), it is zero because \(2\otimes x=1\otimes 2x=1\otimes 0=0\). But as an element of \(M'\otimes N'\) it is
       not zero
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:2.13
    Let \(x_i\in M\), \(y_i\in N\) be s.t. \(\sum x_i\otimes y_i=0\) in \(M\otimes N\). Then there exist finitely generated
    submodules \(M_0\) of \(M\) and \(N_0\) of \(N\) s.t. \(\sum x_i\otimes y_i=0\) in \(M_0\otimes N_0\)
    #+END_corollary

    #+BEGIN_proof
    If \(\sum x_i\otimes y_i=0\), then \(\sum(x_i,y_i)\in D\) and therefore \(\sum(x_i,y_i)\) is a finite sum of generators
    of \(D\). Let \(M_0\) be the submodule of \(M\) generated by the \(x_i\) and all the elements
    of \(M\) which occur as first coordinates in these generators of \(D\), and define \(N_0\)
    similarly. Then \(\sum x_i\otimes y_i=0\) as an element of \(M_0\otimes N_0\)
    #+END_proof


    #+BEGIN_remark
    3. [@3] We shall never again need to use the construction of the tensor product given in
       ref:2.12. What is essential to keep in mind is the defining property of the tensor product
    4. Instead of starting with bilinear mappings we could have started with multilinear
       mappings \(f:M_1\times\cdots\times M_r\to P\) defined in the same way.
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(M_1,\dots,M_r\) be \(A\)-modules. Then there is a pair \((T,g)\) consisting of
    an \(A\)-module \(T\) and an \(A\)-multilinear mapping \(g:M_1\times\dots\times M_r\to T\) with the following
    property:

    Given any \(A\)-module \(P\) and any \(A\)-multilinear mapping \(f:M_1\times\cdots\times M_r\to T\), there exists a
    unique \(A\)-homomorphism \(f':T\to P\) s.t. \(f'\circ g=f\)

    Moreover, if \((T,g)\) and \((T',g')\) are two pairs with this property, then there exists a
    unique isomorphism \(j:T\to T'\) s.t. \(j\circ g=g'\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(M,N,P\) be \(A\)-modules. Then there exist unique isomorphisms
    1. \(M\otimes N\to N\otimes M\)
    2. \((M\otimes N)\otimes P\to M\otimes(N\otimes P)\to M\otimes N\otimes P\)
    3. \((M\oplus N)\otimes P\to(M\otimes P)\oplus(N\otimes P)\)
    4. \(A\otimes M\to M\)


    s.t., respectively
    1. \(x\otimes y\mapsto y\otimes x\)
    2. \((x\otimes y)\otimes z\mapsto x\otimes(y\otimes z)\to x\otimes y\otimes z\)
    3. \((x,y)\otimes z\mapsto(x\otimes z,y\otimes z)\)
    4. \(a\otimes x\mapsto ax\)

    #+END_proposition

    #+BEGIN_proof
    1. commute
       \begin{center}\begin{tikzcd}
       M\otimes N\ar[r,dashed]&N\otimes M\ar[r,dashed]&M\otimes N\\
       M\times N\ar[r]\ar[u]&N\times M\ar[r]\ar[u]&M\times N\ar[u]
       \end{tikzcd}\end{center}

    2. We shall construct homomorphisms
       \begin{equation*}
       (M\otimes N)\otimes P\xrightarrow{f}M\otimes N\otimes P\xrightarrow{g}(M\otimes N)\otimes P
       \end{equation*}
       s.t. \(f((x\otimes y)\otimes z)=x\otimes y\otimes z\) and \(g(x\otimes y\otimes z)=(x\otimes y)\otimes z\) for all \(x\in M,y\in N,z\in P\)

       To construct \(f\), fix the element \(z\in P\). The mapping \((x,y)\mapsto x\otimes y\otimes z\) is bilinear and
       therefore induces a homomorphism \(f_z:M\otimes N\to M\otimes N\otimes P\). Next consider the
       mapping \((t,z)\mapsto f_z(t)\) of \((M\otimes N)\times P\) into \(M\otimes N\otimes P\). This is bilinear in \(t\)
       and \(z\) and therefore induces a homomorphism
       \begin{equation*}
       f:(M\otimes N)\otimes P\to M\otimes N\otimes P
       \end{equation*}
       s.t. \(f((x\otimes y)\otimes z)=x\otimes y\otimes z\)

       To construct \(g\), consider the mapping \((x,y,z)\mapsto(x\otimes y)\otimes z\) of \(M\times N\times P\)
       into \((M\otimes N)\otimes P\). This is linear in each variable and therefore induces a homomorphism
       \begin{equation*}
       g:M\otimes N\otimes P\to(M\otimes N)\otimes P
       \end{equation*}
       s.t. \(g(x\otimes y\otimes z)=(x\otimes y)\otimes z\)

       Clearly \(f\circ g\) and \(g\circ f\) are identity, hence \(f\) and \(g\) are isomorphisms

    3. Show For any \(p\in P\), \(f(m,n,ap)=af(m,n,p)\). For
       any \((m,n)\in M\times N\), \(f(am,an,p)=af(m,n,p)\).

       Define
       \begin{equation*}
       g_1:M\otimes P\to(M\oplus N)\otimes P
       \end{equation*}
       as \(g_1(m\otimes p)=(m,0)\otimes p\)
    #+END_proof

    #+BEGIN_exercise
    Let \(A,B\) be rings, let \(M\) be an \(A\)-module, \(P\) a \(B\)-module and \(N\)
    an \((A,B)\)-bimodule (that is, \(N\) is simultaneously an \(A\)-module and a \(B\)-module and
    the two structures are compatible in the sense that \(a(xb)=(ax)b\) for all \(a\in A,b\in B,x\in N\)).
    Then \(M\otimes_AN\) is naturally a \(B\)-module, \(N\otimes_BP\) an \(A\)-module and we have
    \begin{equation*}
    (M\otimes_AN)\otimes_BP\cong M\otimes_A(N\otimes_BP)
    \end{equation*}
    #+END_exercise

    #+BEGIN_proof
       \begin{align*}
       b(x\otimes_Ay+x'\otimes_Ay')&=b((x+x')\otimes_A(y+y'))=(x+x')\otimes_A(yb+y'b)\\
       &=(x+x')\otimes_A(yb)+(x+x')\otimes_A(y'b)=b(x\otimes_Ay)+b(x\otimes_A y')
       \end{align*}
    #+END_proof



* TODO Problems
    [[Problem1]]: need more field knowledge to deal with \(\R[x]\) and \(\Z[x]\)

    [[Problem2]]: need more matrix

    [[https://mathoverflow.net/questions/42241/errata-for-atiyah-macdonald][Errata]]
