#+TITLE: Commutative Algebra
#+AUTHOR: M. F. Atiyah & I. G. MacDonald

#+EXPORT_FILE_NAME: ../latex/CommutativeAlgebraAtiyah/CommutativeAlgebraAtiyah.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex

* Rings and Ideals
    A *ring homomorphism* is a mapping \(f\) of a ring \(A\) into a ring \(B\) s.t.
    1. \(f(x+y)=f(x)+f(y)\)
    2. \(f(xy)=f(x)f(y)\)
    3. \(f(1)=1\)


    An *ideal* \(\fa\) of a ring \(A\) is a subset of \(A\) which is an additive subgroup and is
    s.t. \(A\fa\subseteq\fa\). The quotient group \(A/\fa\) inherits a uniquely defined multiplication from \(A\)
    which makes it into a ring, called the *quotient ring* \(A/\fa\). The elements of \(A/\fa\) are the
    cosets of \(\fa\) in \(A\), and the mapping \(\phi:A\to A/\fa\) which maps each \(x\in A\) to its
    coset \(x+\fa\) is a surjective ring homomorphism

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.1
    There is a one-to-one order-preserving correspondence between the ideals \(\fb\) of \(A\) which
    contain \(\fa\), and the ideals \(\bar{\fb}\) of \(A/\fa\), given by \(\fb=\phi^{-1}(\bar{\fb})\).
    #+END_proposition

    #+BEGIN_proof
    Let \(S_1=\{\fb:\fb\text{ an ideal of $A$ and }\fa\subseteq\fb\}\)
    and \(S_2=\{\bar{\fb}:\bar{\fb}\text{ an ideal of }A/\fa\}\), \(\pi\) is the natural map \(\pi(S)=S/\fa\), we prove that
    \begin{equation*}
    \varphi:S_1\to S_2\hspace{1cm}\fb\mapsto\pi(\fb)
    \end{equation*}
    is an bijection.

    First assume that \(\fa\subseteq\fb\), we prove that \(\pi^{-1}\pi(\fb)=\fb\). Apparently \(\fb\subseteq\pi^{-1}\pi(\fb)\). For
    any \(b\in\pi^{-1}\pi(\fb)\), there is a \(s\in\fb\) s.t. \(\pi(b)=\pi(s)\). Thus \(b-s\in\ker\pi=\fa\). As \(\fa\subseteq\fb\),
    we have \(b\in\fb\). Hence \(\pi^{-1}\pi(\fb)=\fb\).

    Thus for any \(\fb_1,\fb_2\in S_1\) and \(\varphi(\fb_1)=\pi(\fb_1)=\pi(\fb_2)=\varphi(\fb_2)\), we have \(\pi^{-1}\pi(\fb_1)=\pi^{-1}\pi(\fb_2)\).
    Thus \varphi is injective.

    For any \(\bar{\fb}\in S_2\), \(\pi^{-1}(\bar{\fb})\) contains \(\fa=\pi^{-1}(\{0\})\). Hence \varphi is surjective

    Order-preserving means \(\fa\subseteq\fb\subseteq\fc\) iff \(\bar{\fb}\subseteq\bar{\fc}\)
    #+END_proof

    If \(f:A\to B\) is any ring homomorphism, the *kernel* of \(f\) is an ideal \(\fa\) of \(A\), and the
    image of \(f\) is a subring \(C\) of \(B\); and \(f\) induces a ring isomorphism \(A/\fa\cong C\)

    We shall sometimes use the notation \(x\equiv y\mod\fa\); this means that \(x-y\in\fa\)

    A *zero-divisor* in a ring \(A\) is an element \(x\) which divides 0, i.e., for which there
    exists \(y\neq 0\) in \(A\) s.t. \(xy=0\). A ring with no zero-divisor \(\neq 0\) (and in
    which \(1\neq 0\)) is called an *integral domain*.

    An element \(x\in A\) is *nilpotent* if \(x^n=0\) for some \(n>0\). A nilpotent element is a
    zero-divisor (unless \(A=0\))

    A *unit* in \(A\) is an element \(x\) which "divides 1", i.e., an element \(x\) s.t. \(xy=1\) for
    some \(y\in A\). The element \(y\) is then uniquely determined by \(x\), and is
    written \(x^{-1}\). The units in \(A\) form a (multiplicative) abelian group

    The multiples \(ax\) of an element \(x\in A\) from a *principal* ideal, denoted by \((x)\)
    or \(Ax\). \(x\) is a unit iff \((x)=A=(1)\). The *zero* ideal \((0)\) is denoted by 0

    A *field* is a ring \(A\) in which \(1\neq 0\) and every non-zero element is a unit. Every field is
    an integral domain

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(A\) be a ring \(\neq 0\). Then the following are equivalent:
    1. \(A\) is a field
    2. the only ideals in \(A\) are 0 and (1)
    3. every homomorphism of \(A\) into a non-zero ring \(B\) is injective
    #+END_proposition

    #+BEGIN_proof
    \(2\to 3\). Let \(\phi:A\to B\) be a ring homomorphism. Then \(\ker\phi\) is an ideal \(\neq(1)\) in \(A\),
    hence \(\ker\phi=0\), hence \phi is injective

    \(3\to 1\). Let \(x\) be an element of \(A\) which is not a unit. Then \((x)\neq(1)\),
    hence \(B=A/(x)\) is not the zero ring. Let \(\phi:A\to B\) be the natural homomorphism of \(A\)
    onto \(B\) with kernel \((x)\). By hypothesis, \phi is injective, hence \((x)=0\), hence \(x=0\)
    #+END_proof

    An ideal \(\fp\) in \(A\) is *prime* if \(\fp\neq(1)\) and if \(xy\in\fp\Rightarrow x\in\fp\) or \(y\in\fp\)

    An ideal \(\fm\) in \(A\) is *maximal* if \(\fm\) in \(A\) is *maximal* if \(\fm\neq(1)\) and if no
    ideal \(\fa\) s.t. \(\fm\subset\fa\subset(1)\) (*strict* inclusions). Equivalently
    \begin{gather*}
    \fp\text{ is prime } \Leftrightarrow A/\fp\text{ is an integral domain}\\
    \fm\text{ is maximal } \Leftrightarrow A/\fm\text{ is a field}
    \end{gather*}
    #+BEGIN_proof
    If \(\fm\) is maximal and suppose \(a\notin A\). Then \(J=\{ra+i:i\in \fm\text{ and }r\in A\}\) is an ideal.
    Hence \(J=A\). So there is \(r\in A, \fm\in I\) s.t. \(1=ra+i\). So we have \(1\equiv ra\mod \fm\). Hence we
    find the inverse of \(a+\fm\)

    If \(A/\fm\) is a field and suppose \(\fm\subset\fn\subset A\). Let \(a\in\fm\setminus\fn\), then there exists a \(b\in A\)
    s.t. \(ab-1\in\fm\). So \(ab+m=1\) for some \(m\in\fm\). But \(ab\in\fn\) and \(m\in\fm\subset\fn\), then we
    have \(1\in\fn\) and \(\fn=A\).
    #+END_proof

    Hence a maximal ideal is prime. The zero ideal is prime iff \(A\) is an integral domain

    If \(f:A\to B\) is a ring homomorphism and \(\fq\) is a prime ideal in \(B\), then \(f^{-1}(\fq)\) is
    a prime ideal in \(A\), for \(A/f^{-1}(\fq)\) is isomorphic to a subring of \(B/\fq\) and hence has
    no zero-divisor \(\neq 0\). ([[https://asgarli.wordpress.com/2013/04/21/inverse-image-of-a-prime-ideal-is-prime/][Explanation]]. Since \(\fq\) is prime, \(B/\fa\) is an integral domain and a
    subring of an integral domain is still an integral domain. Define the map
    \(\varphi(a+f^{-1}(\fq))=f(a)+\fq\) and we need to show its a homomorphism. Then we show its injective.)

    But if \(\fn\) is a maximal ideal of \(B\) it is not necessarily true that \(f^{-1}(\fn)\) is
    maximal in \(A\); all we can say for sure is that it is prime. (Example: \(A=\Z\), \(B=\Q\), \(\fn=0\)).

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:1.3
    Every ring \(A\neq 0\) has at least one maximal ideal
    #+END_theorem

    #+BEGIN_proof
    This is the standard application of Zorn's lemma. Let \Sigma be the set of all ideals \(\neq(1)\)
    in \(A\). Order \Sigma by inclusion. \Sigma is not empty, since \(0\in\Sigma\). To apply Zorn's lemma we must
    show that every chain in \Sigma has an upper bound in \Sigma; let then \((\fa_\alpha)\) be a chain of ideals in
    \Sigma, so that for each pair of indices \alpha, \beta we have either \(\fa_\alpha\subseteq \fa_\beta\) or \(\fa_\beta\subseteq\fa_\alpha\).
    Let \(\fa=\bigcup_\alpha\fa_\alpha\). Then \(\fa\) is an ideal and \(1\notin\fa\). Hence \(\fa\in\Sigma\) and is an upper bound of the
    chain. Hence \Sigma has a maximal element
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(\fa\neq(1)\) is an ideal of \(A\), there exists a maximal ideal of \(A\) containing \(\fa\)
    #+END_corollary

    #+BEGIN_proof
    Apply ref:1.3 to \(A/\fa\) and ref:1.3
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:1.5
    Every non-unit of \(A\) is contained in a maximal ideal.
    #+END_corollary

    A ring \(A\) with exactly one maximal ideal \(\fm\) is called a *local ring*. The field \(k=A/\fm\) is
    called the *residue field* of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(A\) be a ring and \(\fm\neq(1)\) an ideal of \(A\) s.t. every \(x\in A-\fm\) is a unit in \(A\).
       Then \(A\) is a local ring and \(\fm\) its maximal ideal.
    2. Let \(A\) be a ring and \(\fm\) a maximal ideal of \(A\) s.t. every element of \(1+\fm\) is a
       unit in \(A\). Then \(A\) is a local ring
    #+END_proposition

    #+BEGIN_proof
    2. [@2] Let \(x\in A-\fm\). Since \(\fm\) is maximal, the ideal generated by \(x\) and \(\fm\)
       is \((1)\), hence there exist \(y\in A\) and \(t\in\fm\) s.t. \(xy+t=1\); hence \(xy=1-t\) belongs
       to \(1+\fm\) and therefore is a unit. Now use 1
    #+END_proof

    A ring with only a finite number of maximal ideals is called *semi-local*

    #+ATTR_LATEX: :options []n
    #+BEGIN_examplle
    1. \(A=k[x_1,\dots,x_n]\), \(k\) a field. Let \(f\in A\) be an irreducible polynomial. By unique
       factorization, the ideal \((f)\) is prime
    2. \(A=\Z\). Every ideal in \(\Z\) is of the form \((m)\) for some \(m\ge 0\). The ideal \((m)\) is
       prime iff \(m=0\) or a prime number. All the ideals \((p)\), where \(p\) is a prime number,
       are maximal: \(\Z/(p)\) is the field of \(p\) elements
    3. A *principal ideal domain* is an integral domain in which every ideal is principal. In such a
       ring every non-zero prime ideal is maximal. For if \((x)\neq 0\) is a prime ideal
       and \((y)\supset(x)\), we have \(x\in(y)\), say \(x=yz\), so that \(yz\in(x)\) and \(y\notin(x)\),
       hence \(z\in(x)\); say \(z=tx\). Then \(x=yz=ytx\), so that \(yt=1\) and therefore \((y)=(1)\).
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.7
    The set \(\fN\) of all nilpotent elements in a ring \(A\) is an ideal, and \(A/\fN\) has no
    nilpotent \(\neq 0\)
    #+END_proposition

    #+BEGIN_proof
    If \(x\in\fN\), clearly \(ax\in\fN\) for all \(a\in A\). Let \(x,y\in\fN\): say \(x^m=0\), \(y^n=0\). By the
    binomial theorem, \((x+y)^{n+m-1`}\) is a sum of integer multiples of products \(x^ry^s\),
    where \(r+s=m+n-1\);

    Let \(\barx\in A/\fN\) be represented by \(x\in A\). Then \(\barx^n\) is represented by \(x^n\), so
    that \(\barx^n=0\Rightarrow x^n\in\fN\Rightarrow(x^n)^k=0\) for some \(k>0\Rightarrow x\in\fN\Rightarrow\barx=0\)
    #+END_proof

    The ideal \(\fN\) is called the *nilradical* of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.8
    The nilradical of \(A\) is the intersection of all the prime ideals of \(A\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\fN'\) denote the intersection of all the prime ideals of \(A\). If \(f\in A\) is nilpotent
    and if \(\fp\) is a prime ideal, then \(f^n=0\in\fp\) for some \(n>0\), hence \(f\in\fp\). Hence \(f\in\fN'\)

    Conversely, suppose that \(f\) is not nilpotent. Let \Sigma be the set of ideals \(\fa\) with the
    property
    \begin{equation*}
    n>0\Rightarrow f^n\notin\fa
    \end{equation*}
    Then \Sigma is not empty because \(0\in\Sigma\). Zorn's lemma can be applied to the set \Sigma, ordered by
    inclusion, and therefore \Sigma has a maximal element. We shall show that \(\fp\) is a prime ideal.
    Let \(x,y\notin\fp\). Then the ideals \(\fp+(x)\), \(\fp+(y)\) strictly contain \(\fp\) and therefore do not
    belong to \Sigma; hence
    \begin{equation*}
    f^m\in\fp+(x),\quad f^n\in\fp+(y)
    \end{equation*}
    for some \(m,n\). It follows that \(f^{m+n}\in\fp+(xy)\), hence the ideal \(\fp+(xy)\) is not in
    \Sigma and therefore \(xy\notin\fp\). Hence we have a prime ideal \(\fp\) s.t. \(f\notin\fp\), so that \(f\notin\fN'\)
    #+END_proof

    The *Jacobson radical* \(\fR\) of \(A\) is defined to be the intersection of all the maximal ideals
    of \(A\). It can be characterized as follows:

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(x\in\fR\) iff \(1-xy\) is a unit in \(A\) for all \(y\in A\)
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\): Suppose \(1-xy\) is not a unit. By ref:1.5 it belongs to some maximal ideal \(\fm\);
    but \(x\in\fR\subseteq\fm\), hence \(xy\in\fm\) and therefore \(1\in\fm\), which is absurd

    \(\Leftarrow\): Suppose \(x\notin\fm\) for some maximal ideal \(\fm\). Then \(\fm\) and \(x\) generate the unit
    ideal \((1)\), so that we have \(u+xy=1\) for some \(u\in\fm\) and some \(y\in A\). Hence \(1-xy\in\fm\)
    and is therefore not a unit.
    #+END_proof

    If \(\fa,\fb\) are ideals in a ring \(A\), their *sum* \(\fa+\fb\) is the set of all \(x+y\) where \(x\in\fa\)
    and \(y\in\fb\). It is the smallest ideal containing \(\fa\) and \(\fb\). More generally, we may define
    the sum \(\sum_{i\in I}a_i\) of any family (possibly infinite) of ideals \(\fa_i\) of \(A\); is elements
    are all sums \(\sum x_i\), where \(x_i\in\fa_i\) for all \(i\in I\) and almost all of the \(x_i\) (i.e., all
    but a finite set) are zero. It is the smallest ideal of \(A\) which contains all the ideals \(\fa_i\)

    The *product* of two ideals \(\fa,\fb\) in \(A\) is the ideal \(\fa\fb\) *generated* by all products \(xy\),
    where \(x\in\fa\) and \(y\in\fb\). It is the set of all finite sums \(\sum x_iy_i\) where each \(x_i\in\fa\) and
    each \(y_i\in\fb\)

    We have the *distributive law*
    \begin{equation*}
    \fa(\fb+\fc)=\fa\fb+\fa\fc
    \end{equation*}
    In the ring \(\Z\), \(\cap\) and + are distributive over each other. This is not the case in
    general. *modular law*
    \begin{equation*}
    \fa\cap(\fb+\fc)=\fa\cap\fb+\fa\cap\fb\text{ if }\fa\supseteq\fb\text{ or }\fa\supseteq\fc
    \end{equation*}
    \begin{equation*}
    \fa\cap\fb=\fa\fb\text{ provided }\fa+\fb=(1)
    \end{equation*}
    If \(x\in\fa\cap\fb\), there is \(a+b=1\). Hence \(xa+xb=x\in\fa\fb\)

    Two ideals \(\fa,\fb\) are said to be *coprime* if \(\fa+\fb=(1)\). Thus for coprime ideals we
    have \(\fa\cap\fb=\fa\fb\).

    Let \(A\) be a ring and \(\fa_1,\dots,\fa_n\) ideals of \(A\). Define a homomorphism
    \begin{equation*}
    \phi:A\to\prod_{i=1}^n(A/\fa_i)
    \end{equation*}
    by the rule \(\phi(x)=(x+\fa_1,\dots,x+\fa_n)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. If \(\fa_i,\fa_j\) are coprime whenever \(i\neq j\), then \(\prod\fa_i=\bigcap\fa_i\)
    2. \phi is surjective iff \(\fa_i\), \(\fa_j\) are coprime whenever \(i\neq j\)
    3. \phi is injective iff \(\bigcap\fa_i=(0)\)
    #+END_proposition

    #+BEGIN_proof
    1. Induction on \(n\). The case \(n=2\) is dealt with above. Suppose \(n>2\) and the result true
       for \(\fa_1,\dots,\fa_{n-1}\), and let \(\fb=\prod_{i=1}^{n-1}\fa_i=\bigcap_{i=1}^{n-1}\fa_i\). As we have \(x_i+y_i=1\)
       (\(x_i\in\fa_i,y_i\in\fa_n\)) and therefore
       \begin{equation*}
       \prod_{i=1}^{n-1}x_i=\prod_{i=1}^{n-1}(1-y_i)\equiv 1\mod \fa_n
       \end{equation*}
       Hence \(\fa_n+\fb=(1)\) and so
       \begin{equation*}
       \prod_{i=1}^n\fa_i=\fb\fa_n=\fb\cap\fa_n=\bigcap_{i=1}^n\fa_i
       \end{equation*}
    2. \(\Rightarrow\): Let's show for example that \(\fa_1,\fa_2\) are coprime. There exists \(x\in A\)
       s.t. \(\phi(x)=(1,0,\dots,0)\); hence \(x\equiv 1\mod\fa_1\) and \(x\equiv 0\mod\fa_2\), so that
       \begin{equation*}
       1=(1-x)+x\in\fa_1+\fa_2
       \end{equation*}
       \(\Leftarrow\): It is enough to show, for example, that there is an element \(x\in A\)
       s.t. \(\phi(x)=(1,0,\dots,0)\). Since \(\fa_1+\fa_i=(1)\) (\(i>1\)) we have \(u_i+v_i=1\) (\(u_i\in\fa_1,v_i\in\fa_i\)).
       Take \(x=\prod_{i=2}^nv_i\), then \(x=\prod(1-u_i)\equiv 1\mod\fa_1\). Hence \(\phi(x)=(1,0,\dots,0)\)
    3. \(\bigcap\fa_i\) is the kernel of \phi
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(\fp_1,\dots,\fp_n\) be prime ideals and let \(\fa\) be an ideal contained in \(\bigcup_{i=1}^n\fp_i\).
       Then \(\fa\subseteq\fp_i\) for some \(i\).
    2. Let \(\fa_1,\dots,\fa_n\) be ideals and let \(\fp\) be a prime ideal containing \(\bigcap_{i=1}^n\fa_i\).
       Then \(\fp\supseteq\fa_i\) for some \(i\). If \(\fp=\bigcap\fa_i\), then \(\fp=\fa_i\) for some \(i\)
    #+END_proposition

    #+BEGIN_proof
    1. induction on \(n\) in the form
       \begin{equation*}
       \fa\not\subseteq\fp_i(1\le i\le n)\Rightarrow\fa\not\subseteq\bigcup_{i=1}^n\fp_i
       \end{equation*}
       It is true for \(n=1\). If \(n>1\) and the result is true for \(n-1\), then for each \(i\)
       there exists \(x_i\in\fa\) s.t. \(x_i\notin\fp_j\) whenever \(j\neq i\). If for some \(i\) we have \(x_i\notin\fp_i\),
       we are through. If not, then \(x_i\in\fp_i\) for all \(i\). Consider the element
       \begin{equation*}
       y=\sum_{i=1}^nx_1x_2\cdots x_{i-1}x_{i+1}\cdots x_n
       \end{equation*}
       we have \(y\in\fa\) and \(y\notin\fp_i\) (\(1\le i\le n\)). Hence \(\fa\not\subseteq\bigcup_{i=1}^n\fp_i\)
    2. Suppose \(\fp\not\supseteq\fa_i\) for all \(i\). Then there exist \(x_i\in\fa_i\), \(x_i\notin\fp\) (\(1\le i\le n\)) and
       therefore \(\prod x_i\in\prod\fa_i\subseteq\bigcap\fa_i\); but \(\prod x_i\notin\fp\) since \(\fp\) is prime. Hence \(\fp\not\supseteq\bigcap\fa_i\)

       If \(\fp=\bigcap\fa_i\), then \(\fp\subseteq\fa_i\) and hence \(\fp=\fa_i\) for some \(i\).
    #+END_proof

    If \(\fa,\fb\) are ideals in a ring \(A\), their *ideal quotient* is
    \begin{equation*}
    (\fa:\fb)=\{x\in A:x\fb\subseteq\fa\}
    \end{equation*}
    which is an ideal. In particular, \((0:\fb)\) is called the *annihilator* of \(\fb\) and is also
    denoted by \(\Ann(\fb)\): it is the set of all \(x\in A\) s.t. \(x\fb=0\). In this notation the set of
    all zero-divisors in \(A\) is
    \begin{equation*}
    D=\bigcup_{x\neq 0}\Ann(x)
    \end{equation*}

    If \(\fb\) is a principal ideal \((x)\), we shall write \((\fa:x)\) in place of \((\fa:(x))\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \(A=\Z\), \(\fa=(m)\), \(\fb=(n)\), where say \(m=\prod_pp^{\mu_p}\), \(n=\prod_pp^{\nu_p}\),
    then \((\fa:\fb)=(q)\) where \(q=\prod_pp^{\gamma_p}\) and
    \begin{equation*}
    \gamma_p=\max(\mu_p-\nu_p,0)=\mu_p-\min(\mu_p,\nu_p)
    \end{equation*}
    Hence \(q=m/(m,n)\), where \((m,n)\) is the h.c.f. of \(m\) and \(n\)
    #+END_examplle

    #+BEGIN_exercise
    1. \(\fa\subseteq(\fa:\fb)\)
    2. \((\fa:\fb)\fb\subseteq\fa\)
    3. \((\fa:\fb):\fc=(\fa:\fb\fc)=((\fa:\fc):\fb)\)
    4. \((\bigcap_i\fa_i:\fb)=\bigcap_i(\fa_i:\fb)\)
    5. \((\fa:\sum_i\fb_i)=\bigcap(\fa:\fb_i)\)

    #+END_exercise

    #+BEGIN_proof
    3. [@3] \((\fa:\fb):\fc=\{x\in A:x\fc\subseteq\fa:\fb\}\). for any \(c\in\fc\), \(xc\fb\subseteq\fa\). Hence \(x\fc\fb\subseteq\fa\).
    5. [@5] \((\fa:\sum_i\fb_i)=\{x\in A:x\sum_i\fb_i\subseteq\fa\}\)
    #+END_proof

    If \(\fa\) is any ideal of \(A\), the *radical* of \(\fa\) is
    \begin{equation*}
    r(\fa)=\{x\in A:x^n\in\fa\text{ for some }n>0\}
    \end{equation*}
    if \(\phi:A\to A/\fa\) is the standard homomorphism, then \(r(\fa)=\phi^{-1}(\fN_{A/\fa})\) and hence \(r(\fa)\)
    is an ideal by ref:1.7

    #+BEGIN_exercise
    1. \(r(\fa)\supseteq\fa\)
    2. \(r(r(\fa))=r(\fa)\)
    3. \(r(\fa\fb)=r(\fa\cap\fb)=r(\fa)\cap r(\fb)\)
    4. \(r(\fa)=(1)\) iff \(\fa=(1)\).
    5. \(r(\fa+\fb)=r(r(\fa)+r(\fb))\)
    6. if \(\fp\) is prime, \(r(\fp^n)=\fp\) for all \(n>0\)
    #+END_exercise

    #+BEGIN_proof
    5. [@5] \(x\in r(\fa+\fb)\) iff \(x^n\in\fa+\fb\). \(y\in r(r(\fa)+r(\fb))\) iff \(y^m=a+b\), where \(a^{n_a}\in\fa\)
       and \(b^{n_b}\in\fb\).
       Then \((y^m)^{n_a+n_b}=(a+b)^{n_a+n_b}\in\fa+\fb\)
    6. \(x\in r(\fp^n)\) iff \(x^m\in\fp^n\), then \(x^m=p_1\cdots p_n\in\fp\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The radical of an ideal \(\fa\) is the intersection of the prime ideals which contain \(\fa\)
    #+END_proposition

    #+BEGIN_proof
    Apply ref:1.8 to \(A/\fa\).

    Nilradical of \(A/\fa\) is the radical of \(\fa\).
    #+END_proof

    More generally, we may define the radical \(r(E)\) of any *subset* \(E\) of \(A\) in the same way.
    It is *not* an ideal in general. We have \(r(\bigcup_\alpha E_\alpha)=\bigcup r(E_\alpha)\) for any family of subsets \(E_\alpha\)
    of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(D=\) set of zero-divisors of \(A=\bigcup_{x\neq 0}r(\Ann(x))\)
    #+END_proposition

    #+BEGIN_proof
    \(D=r(D)=r(\bigcup_{x\neq 0}\Ann(x))=\bigcup_{x\neq 0}r(\Ann(x))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \(A=\Z\), \(\fa=(m)\), let \(p_i\) (\(1\le i\le r\)) be the distinct prime divisors of \(m\).
    Then \(r(\fa)=(p_1\cdots p_r)=\bigcap_{i=1}^n(p_i)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\fa\), \(\fb\) be ideals in a ring \(A\) s.t. \(r(\fa)\), \(r(\fb)\) are coprime. Then \(\fa\)
    and \(\fb\) are coprime.
    #+END_proposition

    #+BEGIN_proof
    \(r(\fa+\fb)=r(r(\fa)+r(\fb))=r(1)=(1)\), hence \(\fa+\fb=(1)\)
    #+END_proof

    Let \(f:A\to B\) be a ring homomorphism. If \(\fa\) is an ideal in \(A\), the set \(f(\fa)\) is not
    necessarily an ideal in \(B\) (e.g. \(\Z\to\Q\)). We define the *extension* \(\fa^e\) of \(\fa\) to be the
    ideal \(Bf(\fa)\) generated by \(f(\fa)\) in \(B\): explicitly, \(\fa^e\) is the set of all
    sums \(\sum y_if(x_i)\) where \(x_i\in\fa\), \(y_i\in B\)

    If \(\fb\) is an ideal of \(B\), then \(f^{-1}(\fb)\) is always an ideal of \(A\), called the
    *contraction* \(\fb^c\) of \(\fb\). If \(\fb\) is prime, then \(\fb^c\) is prime. If \(\fa\) is prime, \(\fa^e\)
    need not be prime (\(f:\Z\to\Q\),\(\fa\neq 0\), then \(\fa^e=\Q\), which is not a prime ideal)

    We can factorize \(f\) as follows:
    \begin{equation*}
    f\xrightarrow{p}f(A)\xrightarrow{j}B
    \end{equation*}
    where \(p\) is surjective and \(j\) is injective

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Consider \(\Z\to\Z[i]\), where \(i=\sqrt{-1}\). A prime ideal \((p)\) of \(\Z\) may or may not stay
    prime when extended to \(\Z[i]\). In fact \(\Z[i]\) is a principal ideal domain (because it has a
    Euclidean algorithm, i.e., a Euclidean ring) and the situation is as follows:
    1. \((2^e)=((1+i)^2)\), the *square* of a prime ideal in \(\Z[i]\)
    2. if \(p\equiv 1\mod 4\) then \((p)^e\) is the product of two distinct prime ideals
       (for example, \((5)^e=(2+i)(2-i)\))
    3. if \(p\equiv 3\mod 4\) then \((p)^e\) is prime in \(\Z[i]\)
    #+END_examplle

    Let \(f:A\to B\), \(\fa\) and \(\fb\) be as before. Then
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(\fa\subseteq\fa^{ec}\), \(\fb\supseteq\fb^{ce}\)
    2. \(\fb^c=\fb^{cec}\), \(\fa^e=\fa^{ece}\)
    3. If \(C\) is the set of contracted ideals in \(A\) and if \(E\) is the set of extended ideals
       in \(B\), then \(C=\{\fa\mid\fa^{ec}=\fa\}\), \(E=\{\fb\mid\fb^{ce}=\fb\}\), and \(\fa\mapsto\fa^e\) is a bijective map
       of \(C\) onto \(E\), whose inverse is \(\fb\mapsto\fb^c\).
    #+END_proposition

    #+BEGIN_proof
    3. [@3] If \(\fa\in C\), then \(\fa=\fb^c=\fb^{cec}=\fa^{ec}\); conversely if \(\fa=\fa^{ec}\) then \(\fa\) is the
       contraction of \(\fa^e\).
    #+END_proof

    #+BEGIN_proof
    1.
    #+END_proof

    #+BEGIN_exercise
    If \(\fa_1,\fa_2\) are ideals of \(A\) and if \(\fb_1,\fb_2\) are ideals of \(B\), then
    \begin{alignat*}{2}
    &(\fa_1+\fa_2)^e=\fa_1^e+\fa_2^e\quad&&(\fb_1+\fb_2)^c\supseteq\fb_1^c+\fb_2^c\\
    \end{alignat*}
    #+END_exercise
** Exercise
    #+BEGIN_exercise
    label:ex1.1
    Let \(x\) be a nilpotent element of a ring \(A\). Show that \(1+x\) is a unit of \(A\). Deduce
    that the sum of a nilpotent element and a unit is a unit
    #+END_exercise

    #+BEGIN_proof
    \(x\) is a element of a nilradical, which is the intersection all prime ideals. Since every
    maximal ideal is a prime ideal, then nilradical is a subset of Jacobson radical.
    Then \(1-(-u^{-1})x\) is a unit for some unit \(u\), hence \(u+x\) is a unit
    #+END_proof
