#+TITLE: Commutative Algebra
#+AUTHOR: M. F. Atiyah & I. G. MacDonald

#+EXPORT_FILE_NAME: ../latex/CommutativeAlgebraAtiyah/CommutativeAlgebraAtiyah.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex

* Rings and Ideals
    A *ring homomorphism* is a mapping \(f\) of a ring \(A\) into a ring \(B\) s.t.
    1. \(f(x+y)=f(x)+f(y)\)
    2. \(f(xy)=f(x)f(y)\)
    3. \(f(1)=1\)


    An *ideal* \(\fa\) of a ring \(A\) is a subset of \(A\) which is an additive subgroup and is
    s.t. \(A\fa\subseteq\fa\). The quotient group \(A/\fa\) inherits a uniquely defined multiplication from \(A\)
    which makes it into a ring, called the *quotient ring* \(A/\fa\). The elements of \(A/\fa\) are the
    cosets of \(\fa\) in \(A\), and the mapping \(\phi:A\to A/\fa\) which maps each \(x\in A\) to its
    coset \(x+\fa\) is a surjective ring homomorphism

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.1
    There is a one-to-one order-preserving correspondence between the ideals \(\fb\) of \(A\) which
    contain \(\fa\), and the ideals \(\bar{\fb}\) of \(A/\fa\), given by \(\fb=\phi^{-1}(\bar{\fb})\).
    #+END_proposition

    #+BEGIN_proof
    Let \(S_1=\{\fb:\fb\text{ an ideal of $A$ and }\fa\subseteq\fb\}\)
    and \(S_2=\{\bar{\fb}:\bar{\fb}\text{ an ideal of }A/\fa\}\), \(\pi\) is the natural map \(\pi(S)=S/\fa\), we prove that
    \begin{equation*}
    \varphi:S_1\to S_2\hspace{1cm}\fb\mapsto\pi(\fb)
    \end{equation*}
    is an bijection.

    First assume that \(\fa\subseteq\fb\), we prove that \(\pi^{-1}\pi(\fb)=\fb\). Apparently \(\fb\subseteq\pi^{-1}\pi(\fb)\). For
    any \(b\in\pi^{-1}\pi(\fb)\), there is a \(s\in\fb\) s.t. \(\pi(b)=\pi(s)\). Thus \(b-s\in\ker\pi=\fa\). As \(\fa\subseteq\fb\),
    we have \(b\in\fb\). Hence \(\pi^{-1}\pi(\fb)=\fb\).

    Thus for any \(\fb_1,\fb_2\in S_1\) and \(\varphi(\fb_1)=\pi(\fb_1)=\pi(\fb_2)=\varphi(\fb_2)\), we have \(\pi^{-1}\pi(\fb_1)=\pi^{-1}\pi(\fb_2)\).
    Thus \varphi is injective.

    For any \(\bar{\fb}\in S_2\), \(\pi^{-1}(\bar{\fb})\) contains \(\fa=\pi^{-1}(\{0\})\). Hence \varphi is surjective

    Order-preserving means \(\fa\subseteq\fb\subseteq\fc\) iff \(\bar{\fb}\subseteq\bar{\fc}\)
    #+END_proof

    If \(f:A\to B\) is any ring homomorphism, the *kernel* of \(f\) is an ideal \(\fa\) of \(A\), and the
    image of \(f\) is a subring \(C\) of \(B\); and \(f\) induces a ring isomorphism \(A/\fa\cong C\)

    We shall sometimes use the notation \(x\equiv y\mod\fa\); this means that \(x-y\in\fa\)

    A *zero-divisor* in a ring \(A\) is an element \(x\) which divides 0, i.e., for which there
    exists \(y\neq 0\) in \(A\) s.t. \(xy=0\). A ring with no zero-divisor \(\neq 0\) (and in
    which \(1\neq 0\)) is called an *integral domain*.

    An element \(x\in A\) is *nilpotent* if \(x^n=0\) for some \(n>0\). A nilpotent element is a
    zero-divisor (unless \(A=0\))

    A *unit* in \(A\) is an element \(x\) which "divides 1", i.e., an element \(x\) s.t. \(xy=1\) for
    some \(y\in A\). The element \(y\) is then uniquely determined by \(x\), and is
    written \(x^{-1}\). The units in \(A\) form a (multiplicative) abelian group

    The multiples \(ax\) of an element \(x\in A\) from a *principal* ideal, denoted by \((x)\)
    or \(Ax\). \(x\) is a unit iff \((x)=A=(1)\). The *zero* ideal \((0)\) is denoted by 0

    A *field* is a ring \(A\) in which \(1\neq 0\) and every non-zero element is a unit. Every field is
    an integral domain

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(A\) be a ring \(\neq 0\). Then the following are equivalent:
    1. \(A\) is a field
    2. the only ideals in \(A\) are 0 and (1)
    3. every homomorphism of \(A\) into a non-zero ring \(B\) is injective
    #+END_proposition

    #+BEGIN_proof
    \(2\to 3\). Let \(\phi:A\to B\) be a ring homomorphism. Then \(\ker\phi\) is an ideal \(\neq(1)\) in \(A\),
    hence \(\ker\phi=0\), hence \phi is injective

    \(3\to 1\). Let \(x\) be an element of \(A\) which is not a unit. Then \((x)\neq(1)\),
    hence \(B=A/(x)\) is not the zero ring. Let \(\phi:A\to B\) be the natural homomorphism of \(A\)
    onto \(B\) with kernel \((x)\). By hypothesis, \phi is injective, hence \((x)=0\), hence \(x=0\)
    #+END_proof

    An ideal \(\fp\) in \(A\) is *prime* if \(\fp\neq(1)\) and if \(xy\in\fp\Rightarrow x\in\fp\) or \(y\in\fp\)

    An ideal \(\fm\) in \(A\) is *maximal* if \(\fm\) in \(A\) is *maximal* if \(\fm\neq(1)\) and if no
    ideal \(\fa\) s.t. \(\fm\subset\fa\subset(1)\) (*strict* inclusions). Equivalently
    \begin{gather*}
    \fp\text{ is prime } \Leftrightarrow A/\fp\text{ is an integral domain}\\
    \fm\text{ is maximal } \Leftrightarrow A/\fm\text{ is a field}
    \end{gather*}
    #+BEGIN_proof
    If \(\fm\) is maximal and suppose \(a\notin A\). Then \(J=\{ra+i:i\in \fm\text{ and }r\in A\}\) is an ideal.
    Hence \(J=A\). So there is \(r\in A, \fm\in I\) s.t. \(1=ra+i\). So we have \(1\equiv ra\mod \fm\). Hence we
    find the inverse of \(a+\fm\)

    If \(A/\fm\) is a field and suppose \(\fm\subset\fn\subset A\). Let \(a\in\fm\setminus\fn\), then there exists a \(b\in A\)
    s.t. \(ab-1\in\fm\). So \(ab+m=1\) for some \(m\in\fm\). But \(ab\in\fn\) and \(m\in\fm\subset\fn\), then we
    have \(1\in\fn\) and \(\fn=A\).
    #+END_proof

    Hence a maximal ideal is prime. The zero ideal is prime iff \(A\) is an integral domain

    If \(f:A\to B\) is a ring homomorphism and \(\fq\) is a prime ideal in \(B\), then \(f^{-1}(\fq)\) is
    a prime ideal in \(A\), for \(A/f^{-1}(\fq)\) is isomorphic to a subring of \(B/\fq\) and hence has
    no zero-divisor \(\neq 0\). ([[https://asgarli.wordpress.com/2013/04/21/inverse-image-of-a-prime-ideal-is-prime/][Explanation]]. Since \(\fq\) is prime, \(B/\fa\) is an integral domain and a
    subring of an integral domain is still an integral domain. Define the map
    \(\varphi(a+f^{-1}(\fq))=f(a)+\fq\) and we need to show its a homomorphism. Then we show its injective.)

    But if \(\fn\) is a maximal ideal of \(B\) it is not necessarily true that \(f^{-1}(\fn)\) is
    maximal in \(A\); all we can say for sure is that it is prime. (Example: \(A=\Z\), \(B=\Q\), \(\fn=0\)).

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:1.3
    Every ring \(A\neq 0\) has at least one maximal ideal
    #+END_theorem

    #+BEGIN_proof
    This is the standard application of Zorn's lemma. Let \Sigma be the set of all ideals \(\neq(1)\)
    in \(A\). Order \Sigma by inclusion. \Sigma is not empty, since \(0\in\Sigma\). To apply Zorn's lemma we must
    show that every chain in \Sigma has an upper bound in \Sigma; let then \((\fa_\alpha)\) be a chain of ideals in
    \Sigma, so that for each pair of indices \alpha, \beta we have either \(\fa_\alpha\subseteq \fa_\beta\) or \(\fa_\beta\subseteq\fa_\alpha\).
    Let \(\fa=\bigcup_\alpha\fa_\alpha\). Then \(\fa\) is an ideal and \(1\notin\fa\). Hence \(\fa\in\Sigma\) and is an upper bound of the
    chain. Hence \Sigma has a maximal element
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(\fa\neq(1)\) is an ideal of \(A\), there exists a maximal ideal of \(A\) containing \(\fa\)
    #+END_corollary

    #+BEGIN_proof
    Apply ref:1.3 to \(A/\fa\) and ref:1.3
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Every non-unit of \(A\) is contained in a maximal ideal.
    #+END_corollary

    A ring \(A\) with exactly one maximal ideal \(\fm\) is called a *local ring*. The field \(k=A/\fm\) is
    called the *residue field* of \(A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(A\) be a ring and \(\fm\neq(1)\) an ideal of \(A\) s.t. every \(x\in A-\fm\) is a unit in \(A\).
       Then \(A\) is a local ring and \(\fm\) its maximal ideal.
    2. Let \(A\) be a ring and \(\fm\) a maximal ideal of \(A\) s.t. every element of \(1+\fm\) is a
       unit in \(A\). Then \(A\) is a local ring
    #+END_proposition

    #+BEGIN_proof
    2. [@2] Let \(x\in A-\fm\). Since \(\fm\) is maximal, the ideal generated by \(x\) and \(\fm\)
       is \((1)\), hence there exist \(y\in A\) and \(t\in\fm\) s.t. \(xy+t=1\); hence \(xy=1-t\) belongs
       to \(1+\fm\) and therefore is a unit. Now use 1
    #+END_proof

    A ring with only a finite number of maximal ideals is called *semi-local*

    #+ATTR_LATEX: :options []n
    #+BEGIN_examplle
    1. \(A=k[x_1,\dots,x_n]\), \(k\) a field. Let \(f\in A\) be an irreducible polynomial. By unique
       factorization, the ideal \((f)\) is prime
    2. \(A=\Z\). Every ideal in \(\Z\) is of the form \((m)\) for some \(m\ge 0\). The ideal \((m)\) is
       prime iff \(m=0\) or a prime number. All the ideals \((p)\), where \(p\) is a prime number,
       are maximal: \(\Z/(p)\) is the field of \(p\) elements
    3. A *principal ideal domain* is an integral domain in which every ideal is principal. In such a
       ring every non-zero prime ideal is maximal. For if \((x)\neq 0\) is a prime ideal
       and \((y)\supset(x)\), we have \(x\in(y)\), say \(x=yz\), so that \(yz\in(x)\) and \(y\notin(x)\),
       hence \(z\in(x)\); say \(z=tx\). Then \(x=yz=ytx\), so that \(yt=1\) and therefore \((y)=(1)\).
    #+END_examplle
