#+TITLE: Commutative Algebra with a View Toward Algebraic Geometry
#+AUTHOR: David Eisenbud

#+EXPORT_FILE_NAME: ../latex/CommutativeAlgebra/CommutativeAlgebra.tex
#+LATEX_HEADER: \input{../preamble.tex}
* Roots of Commutative Algebra
** The Basis Theorem
   A ring \(R\) is *Noetherian* if every ideal of \(R\) is finitely generated,
   which is equivalent to the *ascending chain condition on ideals of \(R\)*,
   which says that every strictly ascending chain of ideals must terminate

   #+ATTR_LATEX: :options [Hilbert Basis Theorem]
   #+BEGIN_theorem
   If a ring \(R\) is Noetherian, then the polynomial ring \(R[x]\) is Noetherian
   #+END_theorem

   If \(f=a_nx^n+a_{n-1}x^{n-1}+\dots+a_n\in R[x]\) with \(a_n\neq0\), we define
   the *initial term* of \(f\) to be \(a_nx^n\), and *initial coefficient* of \(f\)
   to be \(a_n\)

   #+BEGIN_proof
   Let \(I\subset R[x]\) be an ideal; we shall show that \(I\) is finitely
   generated. Choose a sequence of elements \(f_1,f_2,\dots\in I\) as folows:
   Let \(f_1\) be a nonzero element of least degree in \(I\). For \(i\ge1\), if
   \((f_1,\dots,f_i)\neq I\), then choose \(f_{i+1}\) to be an element of least
   degree among \(I\setminus(f_1,\dots,f_i)\). If \((f_1,\dots,f_i)=I\), stop
   choosing.

   Let \(a_j\) be the initial coefficient of \(f_j\). Since \(R\) is Noetherian,
   the ideal \(J=(a_1,a_2,\dots)\) of all the \(a_i\) produced is finitely
   generated. We may choose a set of generators from among the \(a_i\)
   themselves. Let \(m\) be the first integer s.t. \(a_1,\dots,a_m\) generate
   \(J\). We claim that \(I=(f_1,\dots,f_m)\)

   In the contrary case, our process chose an element \(f_{m+1}\). We may write
   \(a_{m+1}=\displaystyle\sum_{j=1}^mu_ja_j\), for some \(u_j\in R\). Since the
   degree of \(f_{m+1}\) is at least as great as the degree of any of the
   \(f_1,\dots,f_m\), we any define a polynomial \(g\in R\) having the same
   degree and initial term as \(f_{m+1}\) by the formula
   \begin{equation*}
   g=\sum_{j=1}^mu_jf_jx^{\deg f_{m+1}-\deg f_j}\in (f_1,\dots,f_m)
   \end{equation*}
   The difference \(f_{m+1}-g\in I\) but not in \((f_1,\dots,f_m)\), and has
   degree strictly less than the degree of \(f_{m+1}\). This contradicts the
   choice of \(f_{m+1}\) as having minimal degree
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Any homomorphic image of a Noetherian ring is Noetherian. Furthermore, if
   \(R_0\) is a Noetherian ring, and \(R\) is a finitely generated algebra over
   \(R_0\), then \(R\) is Noetherian
   #+END_corollary

   #+BEGIN_proof
   Given an ideal \(I\) in \(R/J\), with \(R\) Noetherian, the preimage of \(I\)
   in \(R\) is finitely generated, and the images of its generators generate \(I\)
   #+END_proof

   An \(R\)-module \(M\) is *Noetherian* if every submodule of \(N\) is finitely
   generated

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop1.4
   If \(R\) is a Noetherian ring and \(M\) is a finitely generated \(R\)-module,
   then \(M\) is Noetherian
   #+END_proposition

   #+BEGIN_proof
   Suppose that \(M\) is generated by \(f_1,\dots,f_t\), and let \(N\) be a
   submodule. We shall show that \(N\) is finitely generated by induction on
   \(t\).

   If \(t=1\), then the map \(R\to M\) sending 1 to \(f_1\) is surjective. The
   preimage of \(N\) is an ideal, which is finitely generated since \(R\) is
   Noetherian. The images of its generators generate \(N\)

   Now suppose \(\iffalse<\fi t>1\). The image \(\bbar{N}\) of \(N\) in \(M/Rf_1\) is
   finitely generated by induction. Let \(g_1,\dots,g_s\) be elements of \(N\)
   whose images generate \(\bbar{N}\). Since \(Rf_1\subset M\)  is generated by
   one element, its submodule \(N\cap Rf_1\) is finitely generated, say by
   \(h_1,\dots,h_r\)

   We shall show that the elements \(h_1,\dots,h_r\) and \(g_1,\dots,g_s\)
   together generate \(N\)
   #+END_proof
** Graded Rings
   A *graded ring* is a ring \(R\) together with a direct sum decomposition
   \begin{equation*}
   R=R_0\oplus R_1\oplus R_2\oplus\cdots\quad\text{ as abelian groups}
   \end{equation*}
   s.t.
   \begin{equation*}
   R_iR_j\subset R_{i+j}\quad\text{ for }i,j\ge0
   \end{equation*}
   A *homogeneous element* of \(R\) is an element of one of the groups \(R_i\),
   and a *homogeneous ideal* of \(R\) is an ideal that is generated by homogeneous
   elements. If \(f\in R\), there is a unique expression for \(f\) of the form
   \begin{equation*}
   f=f_0+f_1+\cdots\quad\text{ with } f_i\in R_i\text{ and }f_j=0\text{ for }j\gg0
   \end{equation*}
   the \(f_i\) are called the *homogeneous components* of \(f\).

   The simplest example of a graded ring is the ring of polynomials
   \(S=k[x_1,\dots,x_r]\) *graded by degree*: that is, with grading
   \begin{equation*}
   S=S_0\oplus S_1\oplus\cdots
   \end{equation*}
   where \(S_d\) is the vector space of homogeneous polynomials (also called
   forms) of degree \(d\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A polynomial is *homogeneous of degree* \(d\) if its a linear combination of
   monomials of degree \(d\)

   A monomial in \(n\) variables is \(x_1^{i_1}\dots x_n^{i_n}\), its *degree* is \(i_1+\dots+i_n\)
   #+END_definition

   The space of all homogeneous polynomials of a given degree \(d\) in \(n\)
   variables is /finite dimensional/

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The number of monomials of degree \(d\) in 3 variables is \(C_{d+2}^2\). And
   for \(n\) variables, the number is \(C_{d+n-1}^{n-1}\)
   #+END_proposition

   Suppose that \(I\) is a homogeneous ideal of a graded ring \(R\), and \(I\)
   is generated by homogeneous elements \(f_1,\dots,f_s\). If \(f\in I\) is any
   homogeneous elements, then we can write \(f=\sum g_if_i\) with each \(g_i\)
   homogeneous of degree \(\deg g_i=\deg f-\deg f_i\)
** Algebra and Geometry: The Nullstellensatz
   Gauss' *fundamental theorem of algebra* establishes the basic link between
   algebra and geometry: It says that a polynomial in one variable over \(\C\),
   an algebra object, is determined up to a scalar factor by the set of its
   roots(with multiplicites), a geometric object

   A polynomial \(f\in k[x_1,\dots,x_n]\) with coefficients in a field \(k\)
   defines a function \(f:k^n\to k\); the value of \(f\) at a point
   \((a_1,\dots,a_n)\in k^n\) is obtained by substituting the \(a_i\) for the
   \(x_i\) in \(f\). The function defined by \(f\) is called a *polynomial
   function* on the \(n\)-dimensional vector space \(k^n\) over \(k\), with
   values in \(k\). If \(k\) is infinite, then no polynomial function other than
   0 can vanish identically (always 0) on \(k^n\). (The case of one variable is
   the statement that a polynomial in one variable can have only finitely many
   roots, and follows from Euclid's algorithm for division. In the general case
   we think of a nonzero polynomial \(f(x_1,\dots,x_n)\) in \(n\) variables as a
   polynomial in \(n-1\) variables with coefficients that are polynomials in one
   variable)

   If follows that if \(k\) is infinite, then distinct polynomials define
   distinct functions. Thus we may regard the polynomial ring
   \(k[x_1,\dots,x_n]\) as the ring of polynomial functions on \(k^n\).  Viewed
   with its ring of polynomial functions, \(k^n\) is usually called *affine
   \(n\)-space* over \(k\), written \(\bA^n(k)\) or simply \(\bA^n\)

   Given a subset \(I\subset k[x_1,\dots,x_n]\), we define a corresponding
   *algebraic subset* of \(k^n\) to be
   \begin{equation*}
   Z(I)=\{(a_1,\dots,a_n)\in k^n\mid f(a_1,\dots,a_n)=0\text{ for all }f\in I\}
   \end{equation*}
   Such algebraic sets are sometimes called an *affine algebraic sets*

   If \(X=Z(I)\) is an algebraic set, then an *algebraic subset* \(Y\subset X\) is
   a set of the form \(Y=Z(J)\) that happens to be contained in \(X\). An
   algebraic set is called *irreducible* if it not the union to two smaller
   algebraic subsets. Irreducible algebraic sets are called *algebraic varieties*

   If \(k=\R\) or \(k=\C\), then \(k^r\) is naturally a topological space, and
   an algebraic subset \(X\subset\bA^r\) inherits the subspace topology, called
   the *classical topology*. But there is another, coarser topology on \(X\) that
   is defined over any filed. Polynomial functions on \(X\) will play the role
   of continuous functions, even when the fields we are working over have no
   topology, and by analogy with the continuous case it is natural to think of
   an algebraic subset \(Y\) as a *closed* subset of \(X\). Since we  obviously
   have \(\bigcap_iZ(J_i)=Z(\bigcup_iJ_i)\). Furthermore, if we define
   \(\prod_{r=1}^nJ_i\) to be the set consisting of all products of one function
   from each \(J_i\), then \(\bigcup_{i=1}^nZ(J_i)=Z(\prod_{i=1}^nJ_i)\). Thus
   we may define a topology on \(X\) by taking the closed sets to be the
   algebraic subsets of \(X\). This topology is called the *Zariski topology*.

   Given any set \(X\subset k^n\), we define
   \begin{equation*}
   I(X)=\{f\in k[x_1,\dots,x_n]\mid f(a_1,\dots,a_n)=0\text{ for all }(a_1,\dots,a_n)\in X\}
   \end{equation*}
   It is clear that \(I(X)\) is an ideal. A *polynomial function* (or *regular
   function* ) on \(X\) is the restriction of a polynomial function on \(k^n\) on
   \(X\). Identifying two polynomial functions if they agree at all the points
   of \(X\), we get the *coordinate ring* \(A(X)\) of \(X\). Clearly we have
   \(A(X)=k[x_1,\dots,x_n]/I(X)\)

   Not every homomorphic image \(A=k[x_1,\dot,x_n]/I\) could be the coordinate
   ring of a set. For suppose an element \(f\in A\) satisfies \(f^n=0\). If
   \(f\) were a function on some set \(X\), we would have \(0=f^d(p)=f(p)^d\);
   that is, \(f(p)\) is *nilpotent* for all \(p\in X\). But the values of \(f\)
   are elements of \(k\), a field; so they are all 0, and \(f\) itself is the
   zero element of \(A(X)\). In general, a ring is said to be *reduced* if its
   only nilpotent element is 0; we have just shown that \(A(X)\) is reduced

   If \(R\) is a ring and \(I\subset R\) is an ideal, then the set
   \begin{equation*}
   \rad I:=\{f\in R\mid f^m\in I\text{ for some integer }m\}
   \end{equation*}
   is an ideal. It is called the *radical* of \(I\). An ideal \(I\) is called a
   *radical ideal* if \(I=\rad I\). It follows that \(R/I\) is a reduced ring iff
   \(I\) is a radical ideal. Thus, the ideals \(I(X)\) are all radical ideals

   Not even every radical ideal in \(S\) can occur as \(I(X)\): For example, the
   ideal \(I=(x^2+1)\subset \R[x]\) is radical because \(\R[x]/(x^2+1)\cong\C\)
   is reduced. But \(Z(I)=\emptyset\), so \(I\) is not of the form \(I(X)\) for
   any \(X\). If \(k\) is algebraically closed, the situation is better. For
   example, every polynomial in one variable is a product of linear factors, and
   a polynomial \(f\in k[x]\) generates a radical ideal iff it has no multiple
   roots. In this case if \(X\) is the set of roots of \(f\), then \(I(X)=(f)\).
   Hilbert's Nullstellensatz extends this to polynomial rings with many
   variables
   #+ATTR_LATEX: :options [Nullstellensatz]
   #+BEGIN_theorem
   Let \(k\) be an algebraically closed field. If \(I\subset k[x_1,\dots,x_n]\)
   is an ideal, then
   \begin{equation*}
   I(Z(I))=\rad I
   \end{equation*}
   Thus, the correspondences \(I\mapsto Z(I)\) and \(X\mapsto I(X)\) induce a
   bijection between the collection of algebraic subsets of \(\bA^n_k=k^n\) and
   radical ideals of \(k[x_1,\dots,x_n]\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   A system of polynomial equations
   \begin{align*}
   &f_1(x_1,\dots,x_n)=0\\
   &\dots\\
   &f_m(x_1,\dots,x_n)=0
   \end{align*}
   over an algebraically closed field \(k\) has no solution in \(k^n\) iff 1 can
   be expressed as a linear combination
   \begin{equation*}
   1=\sum p_if_i
   \end{equation*}
   with polynomial coefficients \(p_i\)
   #+END_corollary

   #+BEGIN_proof
   By the Nullstellensatz, if \(Z(f_1,\dots,f_m)=\emptyset\), then 1 is in the
   radical of \((f_1,\dots,f_m)\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If \(k\) is an algebraically closed field and \(A\) is a \(k\)-algebra, then
   \(A=A(X)\) for some algebraic set \(X\) iff \(A\) is reduced and finitely
   generated as a \(k\)-algebra
   #+END_corollary

   #+BEGIN_proof
   If \(A=A(X)\) for some \(X\subset k^n\), then \(A=k[x_1,\dots,x_n]/I(X)\) is
   generated as a \(k\)-algebra by \(x_1,\dots,x_n\). Since \(I(X)\) is radical,
   \(A\) is reduced

   Conversely, if \(A\) is a finitely generated \(k\)-algebra, then after
   choosing generators we may write \(A=k[x_1,\dots,x_n]/I\) for some ideal
   \(I\). Since \(A\) is reduced, \(I\) is radical. Thus \(I=I(Z(I))\) by the
   Nullstellensatz, and we may take \(X=Z(I)\)
   #+END_proof
** Hilbert Functions and Polynomials
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \(R=R_0\oplus R_1\oplus\cdots\) is a graded ring, then a *graded module*
   over \(R\) is a module \(M\) with a docomposition
   \begin{equation*}
   M=\bigoplus_{-\infty}^{+\infty}M_i\quad\text{as abelian groups}
   \end{equation*}
   s.t. \(R_iM_j\subset M_{i+j}\) for all \(i,j\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(M\) be a finitely generated graded module over \(k[x_1,\dots,x_r]\),
   with grading by degree. The numerical function
   \begin{equation*}
   H_M(s):=\dim_kM_s
   \end{equation*}
   is called the *Hilbert function of \(M\)* (These dimensions are all finite; if
   \(M_s\) were not finite dimensional, then the submodule
   \(\oplus_s^{\infty}M_i\) would not be finitely generated, contradicating
   Proposition ref:prop1.4)
   #+END_definition

   #+ATTR_LATEX: :options [Hilbert]
   #+BEGIN_theorem
   label:thm1.11
   If \(M\) is a finitely generated graded module over \(k[x_1,\dots,x_r]\),
   then \(H_M(s)\) agrees, for large \(s\), with a polynomial of degree \(\le r-1\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   This polynomial, denoted \(P_M(s)\), is called the *Hilbert polynomial of \(M\)*
   #+END_definition

   We define \(M(d)\) to be this graded module; more formally, \(M(d)\) is
   isomorphic to \(M\) as a module and has grading defined by
   \begin{equation*}
   M(d)_e=M_{d+e}
   \end{equation*}
   \(M(d)\) is sometimes referred to as the *\(d\)th twist of \(M\)*.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(H(s)\in\Z\) be defined for all for all natural numbers \(s\). If the
   "first difference" \(H'(s)=H(s)-H(s-1)\) agrees with a polynomial of degree
   \(\le n-1\) having rational coefficients for \(s\ge s_0\), then \(H(s)\)
   agrees with a polynomial of degree \(\le n\) having rational coefficients for
   all \(s\ge s_0\)
   #+END_lemma

   #+BEGIN_proof
   Suppose that \(Q(s)\) is a polynomial of degree \(\le n-1\) with rational
   coefficients s.t. \(H'(s)=Q(s)\) for \(s\ge s_0\). For any integer \(s\) set
   \(P(s)=H(s_0)+\sum_{t=s_0+1}^sQ(t)\), where the sum is taken over all
   integers between \(s_0+1\) and \(s\) whether \(s\ge s_0+1\) or \(s\le
   s_0+1\).
   For \(s\ge s_0\) we have \(P(s)=H(s)\). For all \(s\) we have
   \(P(s)-P(s-1)=Q(s)\). It follows that \(P(s)\) is a polynomial of degree
   \(\le n\) with rational coefficients
   #+END_proof

   #+ATTR_LATEX: :options [Proof of Theorem \ref{thm1.11}]
   #+BEGIN_proof
   We do induction on \(r\). If \(r=0\), then \(M\) is simply a
   finite-dimensional graded vector space. In this case \(H_M(s)=0\)
   #+END_proof
* Localization
  A *local ring* is a ring with just one maximal ideal.
** Fractions
   Given a ring \(R\), an \(R\)-module \(M\), and a multiplicatively closed
   subset \(U\subset R\), we define the *localization of \(M\) at \(U\)*, written
   as \(M[U^{-1}]\) or \(U^{-1}M\), to be the set of equivalence classes of pair
   \((m,u)\) with \(m\in M\) and \(u\in U\) with equivalence relation
   \((m,u)\sim (m',u')\) if there is an element \(v\in U\) s.t. \(v(u'm-um')=0\)
   in \(M\). The equivalence class of \((m,u)\) is denoted \(m/u\). We make
   \(M[U^{-1}]\) into an \(R\)-module by defining
   \begin{align*}
   &m/u+m'/u'=(u'm+um')/uu'\\
   &r(m/u)=(rm)/u
   \end{align*}
   for \(m,m'\in M,u,u'\in U,r\in R\). Note that \(u'm/u'u=m/u\). The
   localization comes equipped with a natural map of \(R\)-modules \(M\to
   M[U^{-1}]\) carrying \(m\) to \(m/1\)

   It is convenient to extend the notation a little further: If \(U\subset R\)
   is an arbitrary set, and \(\bbar{U}\subset R\)  is the multiplicatively
   closed set of all products of elements in \(U\), then we set
   \(M[U^{-1}]:=M[\bbar{U}^{-1}]\)

   If we apply the definition in the case \(M=R\), the resulting localization is
   a ring, with multiplication defined by
   \begin{equation*}
   (r/u)(r'/u')=rr'/uu'
   \end{equation*}
   and in fact \(M[U^{-1}]\) is an \(R[U^{-1}]\)-module with action defined by
   \begin{equation*}
   (r/u)(m/u')=rm/uu'\quad\text{for }r\in R,m\in M,u,u'\in U
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.1
   Let \(U\) be a multiplicatively closed set of \(R\), and let \(M\) be an
   \(R\)-module. An element \(m\in M\) goes to 0 in \(M[U^{-1}]\) iff \(m\) is
   annihilated by an element \(u\in U\). In particular, if \(M\) is finitely
   generated, then \(M[U^{-1}]=0\) iff \(M\) is annihilated by an element of \(U\)
   #+END_proposition

   #+BEGIN_proof
   If generators \(m_i\in M\) are annihilated by elements \(u_i\in U\), then
   \(M\) is annihilated by the product of the \(u_i\)
   #+END_proof

   The quotient field of an integral domain \(R\), which we shall denote by
   \(K(R)\), is the localization \(R[U^{-1}]\) where \(U=R-\{0\}\). For an
   arbitrary ring \(R\), take \(U\) to be the set of nonzerodivisors of \(R\),
   and define the *total quotient ring* \(K(R)\) of \(R\) by \(K(R):=R[U^{-1}]\).
   By Proposition ref:prop2.1 \(K(R)\) is the "biggest" localization of \(R\) s.t.
   the natural map \(R\to R[U^{-1}]\) is an injection

   An ideal \(P\subset R\) is prime iff \(R-P\) is a multiplicatively closed
   set. If \(P\) is a prime ideal and \(U=R-P\), then we write \(R_P\)for
   \(R[U^{-1}]\). Similarly, for any \(R\)-module \(M\), we write \(M_P\) for
   \(M[U^{-1}]\). We write \(\kappa(P)\) for the ring \(R_P/P_P\), the
   *residue class field  of \(R\) at \(P\)*.

* COMMENT nonsense
  definition

  lemma

  corollary

  proof

  theorem
