#+TITLE: Definable Groups,@@latex:\\@@ Nip Theories, and@latex:\\@@ the Ellis Group Conjecture
#+AUTHOR: Rosario Mennuni
#+EXPORT_FILE_NAME: ../latex/DefinableGroupsNIPTheoriesEllisGroupConjecture/DefinableGroupsNIPTheoriesEllisGroupConjecture.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\Homeo}{Homeo}
* Conventions
    All theories and types will be supposed first-order with equality, consistent and complete with
    infinite models.

    \(S(A)\) denotes the space of types in any number of variables.

    \(a\equiv_Ab\) for \(\tp(a/A)=\tp(b/A)\)

    \(\psi\triangle\varphi\) means \(\neg(\varphi\leftrightarrow\psi)\)
* Enveloping Semigroups and Stone Spaces
** Classical Ellis Theory
*** \texorpdfstring{\(G\)}{G}-Flows
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((G,\cdot)\) be a group. A *\(G\)-flow* is a continuous action of \(G\) on a compact Hausdorff space
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *topological group* \(G\) is a topological space that is also a group s.t. the group operation
    and the inversion map are continuous. Here \(G\times G\) is viewed as a topological space with the
    product topology
    #+END_definition

    Some words from wikipedia

    The product map is continuous iff for any \(x,y\in G\) and any neighborhood \(W\) of \(xy\)
    in \(G\), there exist neighborhoods \(U\) of \(x\) and \(V\) of \(y\) in \(G\)
    s.t. \(U\cdot V\subseteq W\), where \(U\cdot V:=\{u\cdot v:u\in U,v\in V\}\). The inversion map is continuous iff for
    any \(x\in G\) and any neighborhood \(V\) of \(x^{-1}\) in \(G\), there exists a
    neighborhood \(U\) of \(x\) in \(G\) s.t. \(U^{-1}\subseteq V\), where \(U^{-1}:=\{u^{-1}:u\in U\}\)

    To show that a topology is compatible with the group operations, it suffices to check that the
    map
    \begin{equation*}
    G\times G\to G, (x,y)\mapsto xy^{-1}
    \end{equation*}
    is continuous

    Withe the words "continuous action" on a topological space \(X\) we mean that \(G\) is a
    topological group and the action is continuous as a map \(G\times X\to X\). Unless mentioned otherwise,
    we will put on \(G\) the discrete topology; hence \(G\) will automatically be a topological
    group and a continuous action will simply be a group homomorphism \(\theta:G\to\Homeo(X,X)\).
    For \(g\in G\) and \(p\in X\), the image \((\theta(g))(p)\) of \(p\) under the homeomorphism
    corresponding to \(g\) will be also denoted in one of the following ways
    \begin{equation*}
    \theta_g(p)=g\cdot p=gp=\alpha_p(g)
    \end{equation*}
    We usually identify a \(G\)-flow with the underlying topological space \(X\) (e.g.
    a \(G\)-flow \(X\)) whenever the action is unspecified or clear from context

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Any homeomorphism \(f\) of a compact Hausdorff space \(X\) into itself gives rise to
    a \(\Z\)-flow on \(X\) with the action given by \(n\cdot p=f^n(p)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *morphism of \(G\)-flows* is a continuous \(\varphi:X_0\to X_1\) that commutes with the action of \(g\),
    i.e. s.t. for all \(p\in X_0\) and \(g\in G\) we have \(\varphi(g\cdot p)=g\cdot\varphi(p)\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \((X_0,f_0)\) and \((X_1,f_1)\) are two \(\Z\)-flows, a morphism \(X_0\to X_1\) is a continuous
    map \(\varphi:X_0\to X_1\) s.t. \(f_1\circ\varphi=\varphi\circ f_0\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *subflow* of a \(G\)-flow \(X\) is a nonempty, closed, \(G\)-invariant subset of \(X\).
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The *orbit closure* \(\ove{Gp}\) of a point \(p\in X\) is a subflow of \(X\): it is a closed
    subspace and is closed under the action of \(G\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *minimal subflow* is a subflow which is minimal under inclusion
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Minimal subflows exist
    #+END_proposition

    #+BEGIN_proof
    Every descending chain of subflows is still \(G\)-invariant and has non-empty intersection by
    compactness. Then we can use Zorn's lemma
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A subset \(A\subseteq G\) will be called *syndetic* if there is a finite \(F\subseteq G\) s.t. \(G=F\cdot A\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A point \(p\in X\) is *almost periodic* iff, for each of its neighborhoods \(U\), the
    set \(\alpha^{-1}_p(U)=\{g\in G\mid gp\in U\}\) is syndetic in \(G\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    A point \(p\) is almost periodic iff its orbit closure is a minimal flow
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\): It it enough to show that, for every \(q\in\ove{Gp}\), we have \(p\in\ove{Gq}\). Hence, given
    a compact neighborhood \(U\) of \(p\) (Compact Hausdorff spaces are locally compact), we need to
    show that \(Gq\cap U\neq\emptyset\). Since, by hypothesis, there are \(g_0,\dots,g_{n-1}\)
    s.t. \(G=\bigcup_{i<n}g_i\cdot\alpha_p^{-1}(U)\), we have
    \begin{equation*}
    q\in\ove{Gp}=\ove{\bigcup_{i<n}g_i\alpha_p^{-1}(U)\cdot p}\subseteq\ove{\bigcup_{i<n}g_iU}=\bigcup_{i<n}g_iU
    \end{equation*}
    where the last equality follows from the fact that the compact subspaces of an Hausdorff space
    are closed. This implies that \(g_i^{-1}q\in U\) for some \(i<n\)

    \(\Leftarrow\): If \(U\) is an open neighborhood of \(p\) then \(\ove{Gp}\setminus GU\) is a closed, invariant,
    and proper subset of \(\ove{Gp}\), hence it is empty and by compactness there are finitely
    many \(g_i\in G\) s.t. \(Gp\subseteq\ove{Gp}\subseteq\bigcup_{i<n}g_iU\). But this means that for every \(g\in G\) there
    is \(i<n\) s.t. \(gp\in g_iU\), i.e., \(g_i^{-1}g\in\alpha_p^{-1}(U)\) and thus \(G=\bigcup_{i<n}g_i\alpha_p^{-1}(U)\)
    #+END_proof
*** The Enveloping Semigroup
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(X\) is a \(G\)-flow, its *enveloping semigroup* \(E(X)\) is the closure of \(\{\theta_g\mid g\in G\}\)
    w.r.t. the product topology on \(X^X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(f:X\to Y\) is a function and \(\calf\) is a filter on \(X\), the *pushforward* \(f^*(\calf)\) is the
    ultrafilter on \(Y\) defined as
    \begin{equation*}
    U\in f^*(\calf)\Leftrightarrow f^{-1}(U)\in\calf
    \end{equation*}
    #+END_definition

    The pushforward of an ultrafilter is an ultrafilter

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(\calf\)  is a filter on a topological space \(Y\), and \(l\in Y\), we say that \(l=\lim\calf\) iff
    every neighborhood of \(l\) is in \(\calf\). If \(f:Z\to Y\) is a function and \(\calf\)is the
    pushforward \(f^*(\calf_0)\) of a filter \(\calf_0\) on \(Z\), we also write \(\lim_{z\to\calf_0}f(z)\) for \(\lim\calf\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Every element of \(E(X)\) can be written as \(\theta_{\calu}=\lim_{g\to\calu}\theta_g\) for a suitable (not
    necessarily unique) ultrafilter \(\calu\) on \(G\). Conversely, for every ultrafilter \(\calu\)
    on \(G\), we have \(\theta_{\calu}\in E(X)\)
    #+END_lemma

    #+BEGIN_proof

    #+END_proof
** Newelski's Set-Up
*** Definable Groups
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Fix an \(L\)-theory \(T\) and work modulo \(T\). A *definable group* is given by
    * a formula \varphi defining a non-empty subset \(G\)
    * a definable function \(-\cdot-:G\times G\to G\)
    * a definable function \(-^{-1}:G\to G\)


    s.t. \(G\) equipped with \(\cdot\) and \(^{-1}\) satisfies the group axioms
    #+END_definition

    \(S_G(M)\) carries a natural \(G(M)\)-flow structure given by \(g\cdot p(x)=gp(x)=p(g^{-1}\cdot x)\)
    where \(\varphi(x)\in gp(x)\) iff \(g^{-1}\varphi(x):=\varphi(g\cdot x)\in p(x)\)
