#+TITLE: Essential Stability Theory

#+AUTHOR: Steven Buechler

#+EXPORT_FILE_NAME: ../latex/EssentialStabilityTheory/EssentialStabilityTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Preliminaries and Notations
    #+BEGIN_exercise
    label:ex1.1.11
    Let \(\calm\) be a finite model in a language \(L\). Show that
    \begin{equation*}
    \caln\equiv\calm\Rightarrow\caln\cong\calm
    \end{equation*}
    #+END_exercise
* Constructing Models with Special Properties
** Prime and Atomic Models
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(T\) complete countable theory
    1. A countable \(\calm\vDash T\) is prime iff \(\calm\) is atomic
    2. If \(\calm\) and \(\caln\) are both countable atomic models of \(T\), then \(\calm\cong\caln\)
    #+END_proposition

    Then our question is: *does every complete theory have a prime model, or can we find a meaningful*
    *characterization of those which do?*

    #+ATTR_LATEX: :options [A countable complete theory with no atomic model]
    #+BEGIN_examplle
    Let \(L=\{P_i:i<\omega\}\) where each \(P_i\) is a unary relation symbol. Let \(X=2^{<\omega}\). The
    theory \(T\) is defined so that for any model \(\calm\vDash T\) and \(s\in X\), the intersection of the
    family of sets \(\{P_i(\calm):s(i)=0\}\cup\{M\setminus P_i(\calm):s(i)=1\}\) is nonempty. Let \(P^0_i(v)\) denote the
    formula \(P_i(v)\), and \(P_i^1(v)\) the formula \(\neg P_i(v)\).

    For \(s\in X\), let \(\varphi_s(v):=\bigwedge_{i<lh(s)}P_i^{s(i)}(v)\) where \(lh\) is the length function, \(\sigma_s:=\exists v\varphi_s(v)\)
    and \(T=\{\sigma_s:s\in X\}\). \(T\) is a complete quantifier-eliminable theory.

    Thus, if \(\calm\vDash T\) and \(a\in M\), \(\tp(a)\) is implied by \(\{P_i^j(v):\calm\vDash P_i^j(a),i<\omega,j=0,1\}\). We
    claim that every complete 1-type in \(T\) is nonisolated. If, to the contrary, \(p\) is an
    isolated 1-type, then by the characterization of types just mentioned \(p\) is isolated by
    some \(\varphi_s\in p\). However, if \(j=lh(s)\), both \(\exists v(\varphi_s(v)\wedge P_j(v))\)
    and \(\exists v(\varphi_s(v)\wedge\neg P_j(v))\) are in \(T\), proving that \(\varphi_s\) does not isolate a complete type
    in \(T\). Since \(T\) has no isolated 1-types over \(\emptyset\), no model of \(T\) can be atomic
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(T\) be a countable complete theory. Then \(T\) has a countable atomic model iff the
    isolated types of \(T\) are dense
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(T\) is a complete theory with \(\abs{S(\emptyset)}<2^{\aleph_0}\) then the isolated types of \(T\) are dense
    #+END_lemma

    Thus, for a countable complete theory, having fewer than continuum many complete types is
    sufficient to guarantee the existence of a prime model.

    But this condition is not necessary. Consider \(\Th(\Z,+,1)\). \(\abs{S_1(\emptyset)}=2^{\aleph_0}\). However,
    since every element of the model \((\Z,+,1)\) interprets a term of the language, it is an
    elementary submodel of any model of \(T\)

    #+BEGIN_remark
    An algebraic formula is contained in only finitely many complete types in \(T\), each of which
    is isolated
    #+END_remark

    #+BEGIN_proof
    \varphi algebraic and \(\varphi\in p\). Then \(p(\calm)\) is finite

    \(p=q\Leftrightarrow p(\calm)=q(\calm)\)
    #+END_proof


    If \(\calm\) is a model and \(A\subset M\), \(\calm\) is called a *prime model over* \(A\) if \(\calm_A\) is a prime
    model over \(\Th(\calm_A)\). Note that \(\caln\vDash\Th(\calm_A)\) iff \(\caln\equiv\calm\) and there is a elementary
    map \(f:A\to\caln\)

    #+BEGIN_exercise
    label:ex2.1.2
    Let \(T\) be a complete theory and \varphi a formula in \(n\) variables which is contained in only
    finitely many complete \(n\)-types of \(T\). Show that every complete \(n\)-types containing
    \varphi is isolated
    #+END_exercise

    #+BEGIN_proof
    If there are \(p_1,\dots,p_n\), then there is \(\phi_1,\dots,\phi_n\) implying \varphi s.t. for any \(q\)
    \(\phi_i\in q\Leftrightarrow  q=p_i\). Thus \([\phi_i]=\{p_i\}\). Thus for any \(\theta\), either \([\phi_i\wedge\theta]\)
    or \([\phi_i\vee\neg\theta]\) is empty. Hence \(\phi_i\) is complete
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.3
    Suppose \(\bara\) and \(\barb\) are sequences from a model \(\calm\) which have the same complete
    types in \(\calm\) and \(\varphi(v,\bara)\) isolates a complete type over \(\bara\). Show
    that \(\varphi(v,\barb)\) isolates a complete type over \(\barb\)
    #+END_exercise

    #+BEGIN_proof
    If \(\varphi(v,\bara)\) isolates \(p(v)=\{\varphi(v,\bara)\}\). First, \(q(v)=\{\varphi(v,\barb)\}\) is a complete
    type.

    Then \(\varphi(v,\barb)\) isolates it
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.4
    Suppose that \(\bara\) and \(\barb\) be finite sequences from the universe of the model \(\calm\).
    Prove that \(\tp_{\calm}(\bara\barb)\) is isolated iff \(\tp_{\calm}(\bara/\barb)\) and \(\tp(\barb)\)
    are both isolated. Using this fact show that when \(\calm\) is an atomic model and \(\bara\) is a
    finite sequence from \(M\), then \(\calm\) is atomic over \(\bara\). Conversely, if \(\calm\) is atomic
    over \(\bara\) and \(\tp_{\calm}(\bara)\) is isolated, then \(\calm\) is atomic
    #+END_exercise

    #+BEGIN_proof
    If \(\varphi(\barx,\bary)\) isolates \(\tp_{\calm}(\bara\barb)\), then \(\varphi(\barx,\barb)\)
    isolates \(\tp_{\calm}(\bara/\barb)\) and \(\exists\barx\varphi(\barx,\bary)\) isolates \(\tp_{\calm}(\barb)\)

    If \(\varphi(\barx,\barb)\) isolates \(\tp_{\calm}(\bara/\barb)\) and \(\psi(\bary)\)
    isolates \(\tp(\barb)\). Then \(\psi(\bary)\wedge\varphi(\barx,\bary)\) isolates \(\tp(\bara\barb)\).

    For any \(\theta(\barx,\bary)\in\tp(\bara\barb)\). \(\calm\vDash\forall\barx(\varphi(\barx,\barb)\to\theta(\barx,\barb))\).
    Hence \(\calm\vDash\forall\bary(\psi(\bary)\to\forall\barx(\varphi(\barx,\bary)\to\theta(\barx,\bary)))\)
    #+END_proof

    #+BEGIN_exercise
    Show that the complete type realized by 1 in \((\Z,+)\) is non-isolated
    #+END_exercise

    #+BEGIN_proof
    \(\tp(1/2)\) is isolated by \(x+x=2\).
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.6
    Show that \(\Th(\Z,+e)\) has continuum many complete 1-types over \(\emptyset\)
    #+END_exercise

    #+BEGIN_exercise
    label:ex2.1.7
    Given an example of a model \(\calm\) containing an element \(a\) which is the only realization
    of \(\tp_{\calm}(a)\) in \(\calm\), although this type is not even isolated
    #+END_exercise

    #+BEGIN_proof
    Not isolated means there is no minimum element under \(\subseteq\) in \(\{\varphi(\calm):\varphi\in\tp(a)\}\)
    #+END_proof

    #+BEGIN_exercise
    label:ex2.1.8
    Let \(\calm\) be a model s.t. the type in \(\calm\) of each tuple from \(M\) is algebraic. Prove
    that \(\calm\) is a prime and minimal model of its theory
    #+END_exercise

    #+BEGIN_proof

    #+END_proof
** Saturated and Homogeneous Models
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    A countable complete theory \(T\) has a saturated countable model iff it is small
    #+END_proposition


    Let \(T\) be a countable complete theory. We proved that \(T\) has a countable atomic model
    when \(\abs{S(\emptyset)}<2^{\aleph_0}\) and \(T\) has a countable saturated model when
    when \(S(\emptyset)\) is countable. It is natural to ask *if there is a countable complete theory*
    *with \(\abs{S(\emptyset)}\) strictly between \(\aleph_0\) and \(2^{\aleph_0}\)*

    The Cantor-Bendixson Theorem from point-set topology quickly gives a negative answer: \(S_n(\emptyset)\)
    is strictly between \(\aleph_0\) and \(2^{\aleph_0}\)

    First, we prove Cantor-Bendixson theorem first from [[http://ozark.hendrix.edu/~yorgey/settheory/08-more-real-line.pdf][here]]

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(a\in X\) is *isolaed in* \(X\) iff \(\{a\}\) is open. Otherwise \(a\) is a limit point
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\) is a *perfect set* iff \(X\) is closed and has no isolated points
    #+END_definition

    Cantor set is perfect since each point of it is a limit point

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:K1
    If \(P\) is a perfect set and \(I\) is an open interval on \(\R\) s.t. \(I\cap P\neq\emptyset\), then there
    exist disjoint closed intervals \(J_0,J_1\subset I\) s.t. \(int(J_0)\cap P\neq\emptyset\) and \(int(J_1)\cap P\neq\emptyset\).
    Moreover, we can pick \(J_0\) and \(J_1\) s.t. their lengths are both less than any \(\epsilon>0\)
    #+END_lemma

    #+BEGIN_proof
    Since \(P\) has no isolated points, there must be at least two points \(a_0,a_1\in I\cap P\). Then
    pick \(J_0\ni a_0\) and \(J_1\ni a_1\) to be small enough
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(P\) is a nonempty perfect set, then \(\abs{P}=\fc\)
    #+END_lemma

    #+BEGIN_proof
    We exhibit a one-to-one mapping \(G:2^\omega\to P\)

    We build a binary tree. For each \(s\in 2^{<\omega}\), we associate an interval \(I_s\) s.t.
    * \(I_s\) is closed
    * \(I_s\cap P\neq\emptyset\)
    * \(I_{s,b}\subset I_s\)
    * \(I_{s,0}\cap I_{s,1}=\emptyset\)
    * \(\abs{I_s}<1/(\abs{s}+1)\)


    where \(\abs{I}\) denotes the length of interval \(I\) and \(\abs{s}\) denotes the length of
    sequence \(s\)

    Let \(\la\ra\) denotes the emptyset sequence, let \(I_{\la\ra}\) be the closure of \(I\cap P\) for some
    open interval \(I\) with length at most 1 whose intersection with \(P\) is nonempty. Then by
    ref:K1 choose appropriate \(I_{s,0}\) and \(I_{s,1}\)

    Now for all \(f\in 2^{\omega}\), define
    \begin{equation*}
    G(f)=\bigcap_{i\in\omega}I_{f\uhr i}
    \end{equation*}
    If we pick elements from each \(I_{f\uhr i}\), then \(G(f)\) is their limit, which is contained
    in \(P\) since \(P\) is closed

    Suppose \(f,f'\in 2^\omega\) and \(f\neq f'\). Let \(n\in\omega\) be the smallest index s.t. \(f(n)\neq f'(n)\).
    Then \(I_{f\uhr n}\cap I_{f'\uhr n}=\emptyset\)
    #+END_proof

    #+ATTR_LATEX: :options [Cantor-Bendixson]
    #+BEGIN_theorem
    If \(C\subseteq\R\) is closed and uncountable, then there exists some perfect, nonempty \(P\subseteq C\).
    #+END_theorem

    #+BEGIN_proof
    Let \(C\subseteq\R\) be closed. Define the *Cantor-Bendixson derivative*
    \begin{equation*}
    C'=\{a\in C\mid a\text{ is a limit point of }C\}
    \end{equation*}
    This operation maps closed sets to closed sets, since closed sets in \(\R\) are those which
    contain all their limit points, and the derivative is monotone and retains all limit points.
    Then define
    \begin{align*}
    C_0&=C\\
    C_{\alpha+1}&=(C_\alpha)'\\
    C_\lambda'&=\bigcap_{\beta<\lambda}C_\beta
    \end{align*}
    Note that \(C_\beta\) is closed for all \beta by induction

    Claim: \(C_\gamma=C_{\gamma+1}\) for some \gamma. For if not, \(C_\alpha\neq C_\beta\) for any \(\alpha\neq\beta\), since \(C\) is
    monotone, then \(C_{-}\) would be an injection \(Ord\to\calp(C)\), which is absurd

    Note that \(C_\gamma\) is perfect, since it consists solely of limit points and is closed. If \(C_\gamma\neq\emptyset\),
    we are done

    We claim that \(C_\gamma\) cannot be \(\emptyset\) since this would imply that \(C\)  is countable.
    Consider \(C_\beta-C_{\beta+1}\), which contains all the isolated points in \(C_\beta\). That is,
    if \(a\in C_\beta-C_{\beta+1}\), there exists an open interval \(I_a\ni a\) s.t. \(C_\beta\cap I_a=\{a\}\). In
    particular, we may choose \(I_a\) to be an open interval with rational endpoints

    Note that \(I_a\) is distinct; otherwise, at the earliest stage when \(I_a\) arose, it would have
    contained more than one point. Therefore we have an injection from \(C\) into the set of
    intervals with rational endpoints, which is countable
    #+END_proof

    #+BEGIN_remark
    The above proof shows that every closed set can be decomposed into a perfect subset and a
    countable subset.
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The smallest \gamma in the above proof for which \(C_\gamma=C_{\gamma+1}\) is called the *Cantor-Bendixson rank*
    of \(C\), and the above proofs shows that \(\gamma<\aleph_1\)
    #+END_definition

    It can be shown that for every \(\gamma<\aleph_1\), there exists a closed \(C\subseteq\R\) with Cantor-Bendixson
    rank \gamma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    There are \(2^{\aleph_0}\) perfect sets
    #+END_lemma

    #+BEGIN_proof
    There is an injection from \(\calp(\N)\) to the set of all perfect sets: for each set of naturals,
    identify each natural with a small closed interval containing it, and take the union. There are
    at most \(2^{\aleph_0}\) perfect sets since there are \(2^{\aleph_0}\) closed sets
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    There exists a set \(X\) with \(\abs{X}=2^{\aleph_0}=\abs{\R-X}\) s.t. for every perfect
    set \(P\), \(P\not\subseteq X\) and \(P\not\subseteq\R-X\)
    #+END_theorem

    #+BEGIN_proof
    Let \((P_\alpha:\alpha<2^{\aleph_0})\) be an enumeration of the perfects sets. Also let \(x_\alpha\) be an
    enumeration of \(\R\). Now define \(r_\gamma\)
    #+END_proof


    Now we come back to book

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(T\) be a complete theory. \varphi a formula in \(n\) variables
    1. \(CB(\varphi)=-1\) if \varphi is inconsistent
    2. Let \(\Psi_\alpha=\{\psi:CB(\psi)=\beta<\alpha\}\)

       \(CB(\varphi)=\alpha\) if \(\{p\in S_n(\emptyset):\varphi\in p\wedge\forall\psi\in\Psi_\alpha(\neg\psi\in p)\}\) is nonempty and finite. Equivalently,
       \(\{p\in S_n(\emptyset):\varphi\in p\wedge CB(p)\ge\alpha\}\) is finite and nonempty


    For \(p\in S_n(T)\), \(CB(p)\) is
    \begin{equation*}
    \inf\{CB(\varphi):p\vDash\varphi\}
    \end{equation*}
    When \(CB(p)=\alpha\) we say that the *Cantor-Bendixson rank* of \(p\) is \alpha. If there is no such
    \alpha, \(CB(p)=\infty\) and say that the Cantor-Bendixson rank of \(p\) does not exist
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.2.3
    \(T\) complete, \(p\) \(n\)-type, \alpha ordinal
    1. If \(p\) is complete, \(CB(p)=0\Leftrightarrow\) p is isolated
    2. \(CB(p)=\alpha\Leftrightarrow\) there is a formula \varphi implied by \(p\) s.t. \(\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)=\alpha\}\) is
       finite and nonempty. Moreover, when \(CB(p)=\alpha\) we can find a \varphi implied by \(p\) s.t.
       \(\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)=\alpha\}=\{q\in S_n(\emptyset):p\subset q\wedge CB(q)=\alpha\}\) <<Problem1>>
    3. If \(CB(p)=\alpha\) there is \(q\in S_n(\emptyset)\) s.t. \(q\supset p\) and \(CB(q)=\alpha\)
    4. If \(p\) is complete and \(CB(p)=\alpha\) there is a \(\varphi\in p\) s.t. \(p\) is the only element
       of \(q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\alpha\)
    5. \(CB(p)\ge\alpha\) iff for all \(\beta<\alpha\) and all \varphi implied by \(p\), \(\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\beta\}\) is
       infinite
    6. \(CB(\varphi)\) is the least ordinal \alpha s.t.
       \(\{p\in S_n(\emptyset):\varphi\in p\wedge CB(p)\ge\alpha\}\) is finite
    #+END_lemma

    #+BEGIN_proof
    1. If \(p\) is isolated by \varphi, then \(CB(\varphi)=0\).

       If \(CB(p)=0\), there is a \(\varphi\in p\) which is contained in only finitely many complete types,
       say \(q_0,\dots,q_k\) with \(q_0=p\). Let \psi be a formula in \(p\) implying \(\varphi\) and not in any
       of \(q_1,\dots,q_k\). Then \psi isolates \(p\)

    2. Let \(\Psi=\{\psi:p\vDash\psi\wedge CB(\psi)=\alpha\}\). Then
        \(\psi\in\Psi\Rightarrow X_\psi=\{q\in S_n(\emptyset):\psi\in q\wedge CB(q)\ge\alpha\}\) is finite and nonempty. Furthermore if \(\psi,\psi'\in\Psi\)
       and \(\psi\to\psi'\), \(X_\psi\subset X_{\psi'}\). Thus there is a \(\varphi\in\Psi\) s.t. \(X_\varphi=X_\psi\) for all \(\psi\in\Psi\) which
       imply \varphi.
       #+LATEX: \wu{
       First we can pick an arbitrary \varphi, if it doesn't have the property, then there is a \(\varphi'\)
       such that \(X_{\varphi'}\) is a proper subset of \(X_\varphi\). Since \(X_\varphi\) is finite, this process
       will end.
       #+LATEX: }
       Since \Psi is implied by \(p\) each element of \(X_\varphi\) contain \(p\);
       i.e., \(X_\varphi=\{q\in S_n(\emptyset):p\subset q\wedge CB(q)=\alpha\}\). Since \(X_\varphi\) is finite and nonempty the proof is
       complete

       \(\Leftarrow\).

    3. [@5] \(\Leftarrow\). \(CB(p)\ge\alpha\) iff for all \(p\vDash\varphi\), \(\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\alpha\}\) is nonempty iff
       for all \(p\vDash\varphi\), \(\{\varphi\}\cup\{\neg\psi:CB(\psi)<\alpha\}\) is consistent.

       Suppose there is \(p\vDash\varphi\) and \(\{\varphi\}\cup\{\neg\psi:CB(\psi)<\alpha\}\) is inconsistent, then there
       is \(\psi_0,\dots,\psi_n\) of CB-rank \(<\alpha\) s.t. \(\varphi\to\bigvee_{i=0}^n\psi_i\). \(\beta=\max\{CB(\psi_0),\dots,CB(\psi_n)\}<\alpha\).
       For each \(i\le n\), \(X_i=\{q\in S_n(\emptyset):\psi_i\in q\wedge CB(q)\ge\beta\}\) is finite,
       hence \(X_0\cup\dots\cup X_n=\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\beta\}\) is finite

       \(\Rightarrow\). Suppose there is \(\beta<\alpha\) and \(p\vDash\varphi\) s.t. \(X=\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\beta\}\) is finite.
       If \(X\) is empty then \(CB(\varphi)<\beta\) by 2.
    #+END_proof

    When \(p\) is a complete type of CB-rank \alpha and \(\varphi\in p\) is s.t. \(p\) is the only completion of
    \varphi of CB-rank \(\ge\alpha\), we say that \varphi *isolates* \(p\) relative to the types of CB-rank \(\ge\alpha\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(L_1=\{E\}\), where \(E\) is a binary relation. The theory \(T_1\) in \(L_1\), expressing
    that \(E\) is an equivalence relation with two classes, each infinite, is
    quantifier-eliminable. Let \(\calm\vDash T_1\)  and \(T=\Th(\calm_M)\). What does \(S_1(\emptyset)\) in \(T\) look
    like? The isolated elements of \(S_1(\emptyset)\), hence the elements of CB-rank 0, are exactly those
    containing \(x=a\) for some \(a\in M\).

    Let \(p\) be a complete 1-type containing \(\{x\neq b:b\in M\}\). There is some \(a\in M\)
    s.t. \(E(x,a)\in p\). If \(b\in M\), \(E(x,b)\in p\Leftrightarrow \calm\vDash E(a,b)\). By QE, \(p\) is the only element
    of \(S_1(\emptyset)\) containing \(\{E(x,a)\}\cup\{x\neq b:b\in M\}=\{E(x,a)\}\cup\{\neg\psi(x):CB(\psi(x))=0\}\),
    hence \(CB(E(x,a))=CB(p)=1\)
    #+END_examplle



    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \alpha be an ordinal, and for \(1\le\beta\le\alpha\), let \(E_\beta\) be a binary relation. Let \(T_1\) be the
    theory sayting that each \(E_\beta\) is an equivalence relation with only infinite classes and
    for \(1\le\beta<\gamma\le\alpha\), \(E_\beta\) refines \(E_\gamma\) and each \(E_\gamma\)-classes contains infinitely
    many \(E_\beta\)-classes. These two properties are guaranteed with the axioms
    \begin{gather*}
    \forall xy(E_\beta(x,y)\to E_\gamma(x,y))\text{ and, for all }n<\omega\\
    \forall x\exists y_0\dots y_n\left( \bigwedge_{i\neq j\le n}E_\gamma(x,y_i)\wedge\neg E_\beta(y_i,y_j) \right)
    \end{gather*}
    For \(\calm\vDash T_1\), let \(T=\Th(\calm_M)\). \(T\) has q.e.. Let \(E_0(x,y)\) denote \(x=y\)

    *Claim* For \(\beta\le\alpha\) and \(a\in M\), \(CB(E_\beta(x,a))=\beta\)

    \(\beta=0\) trivial. Let \(\beta>0\) and fix \(\gamma<\beta\). There is an infinite set \(B\subset M\) s.t. \(E_\gamma(x,b)\)
    implies \(E_\beta(x,a)\) and \(b\neq b'\Rightarrow\neg E_\gamma(b,b')\) for all \(b,b'\in B\). By induction, \(E_\gamma(x,b)\) has
    CB-rank \gamma, and extends to a complete 1-type of CB-rank \gamma by Lemma ref:lemma2.2.3 (3). Since \(\)
    #+END_examplle

    #+BEGIN_proof
    \(p\) being nonalgebraic implies that \(x\neq a\in p\) for all \(a\in M\). Thus \(p\) is not isolated.

    Goal: if \(CB(p)\ge\alpha\) then \(\{q\in S_n(\emptyset):\varphi\in q\wedge CB(q)\ge\alpha\}\) is infinite
    #+END_proof
** Skolem Functions
    here we show how to expand a theory \(T\) to a theory \(T^*\) in a larger language so that
    whenever \(\calm\vDash T^*\) and \(\caln\subset\calm\), \(\caln\prec\calm\)

    #+ATTR_LATEX: :options [Skolem]
    #+BEGIN_theorem
    Let \(T\) be a theory in a language \(L\). Then there is a theory \(T^*\)  in a language \(L^*\)
    s.t.
    1. \(L\subset L^*\), \(T\subset T^*\) \(\abs{T^*}=\abs{T}\)
    2. every model of \(T\) can be expanded to a model of \(T^*\)
    3. if \(\calm^*\vDash T^*\) and \(\caln^*\subset\calm^*\), then \(\caln^*\prec\calm^*\)
    #+END_theorem

    A theory \(T\) having the property that whenever \(\calm\vDash T\) and \(\caln\subset\calm\) then \(\caln\prec\calm\) is said to
    *have Skolem functions*

* TODO PROBLEMS
    |[[Problem1]]|
