#+TITLE: Fields and Galois Theory

#+AUTHOR: J. S. Milne
#+EXPORT_FILE_NAME: ../latex/FieldsAndGaloisTheory/FieldsAndGaloisTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Basic Definitions and Results
** The characteristic of a field
    Given a field \(F\) and consider a map
    \begin{equation*}
    \Z\to F,\quad n\mapsto n\cdot 1_F
    \end{equation*}
    If the kernel of the map is \(\neq (0)\), so that \(n\cdot 1_F=0\) for some \(n\neq 0\). The smallest
    positive such \(n\) will be a prime \(p\) (otherwise \((m\cdot n)\cdot 1_F=(m\cdot 1_F)\cdot (n\cdot 1_F)=0\) there
    will be two nonzero elements in \(F\) whose product is zero, but a field is an integral domain)
    and \(p\) generates the kernel. Thus the map \(n\mapsto n\cdot 1_F:\Z\to F\) defines an isomorphism
    from \(\Z/p\Z\) onto the subring
    \begin{equation*}
    \{m\cdot 1_F\mid m\in\Z\}
    \end{equation*}
    of \(F\). In this case, \(F\) contains a copy of \(\F_p\)

    A field isomorphic to one of the fields \(\F_2,\F_3,\F_5,\dots,\Q\) is called a *prime field*. Every field
    contains exactly one prime field (as a subfield)

    A commutative ring \(R\) is said to have *characteristic* \(p\) (resp. 0) if it contains a prime
    field (as a subring) of characteristic \(p\) (resp. 0). Then the prime field is unique and, by
    definition, contains \(1_R\). Thus if \(R\) has characteristic \(p\neq 0\), then \(1_R+\dots+1_R=0\)
    (\(p\) terms)

    Let \(R\) be a nonzero commutative ring. If \(R\) has characteristic \(p\neq 0\), then
    \begin{equation*}
    pa:=\underbrace{a+\dots+a}_{p\text{ terms}}=\underbrace{(1_R+\dots+1_R)}_{p\text{ terms}}a=0a=0
    \end{equation*}
    for all \(a\in R\). Conversely, if \(pa=0\) for all \(a\in R\), then \(R\) has characteristic \(p\)

    Let \(R\) be a nonzero commutative ring. The usual proof by induction shows that the binomial
    theorem
    \begin{equation*}
    (a+b)^m=a^m+\binom{m}{1}a^{m-1}b+\binom{m}{2}a^{m-2}b^2+\dots+b^m
    \end{equation*}
    holds in \(R\). If \(p\) is prime, then it divides
    \begin{equation*}
    \binom{p}{r}:=\frac{p!}{r!(p-r)!}
    \end{equation*}
    for all \(r\) with \(1\le r\le p-1\). Therefore, when \(R\) has characteristic \(p\)
    \begin{equation*}
    (a+b)^p=a^p+b^p\quad\text{ for all }a,b\in R
    \end{equation*}
    and so the map \(a\mapsto a^p:R\to R\) is a homomorphism of rings (even of \(\F_p\)-algebras). It is
    called the *Frobenius endomorphsim* of \(R\). The map \(a\mapsto a^{p^n}:R\to R\), \(n\ge 1\), is hte
    composite of \(n\) copies of the Frobenius endomorphsim, and so it also is a homomorphism.
    Therefore
    \begin{equation*}
    (a_1,\dots,a_m)^{p^n}=a_1^{p^n}+\dots+a_m^{p^n}
    \end{equation*}
    for all \(a_i\in R\).

    When \(F\) is a field, the Frobenius endomorphsim is injective
** Factoring polynomials
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(r\in\Q\) be a root of a polynomial
    \begin{equation*}
    a_mX^m+a_{m-1}X^{m-1}+\dots+a_0,\quad a_i\in\Z
    \end{equation*}
    and write \(r=c/d\), \(c,d\in\Z\), \(\gcd(c,d)=1\). Then \(c\mid a_0\) and \(d\mid a_m\)
    #+END_proposition

    #+BEGIN_proof
    \begin{equation*}
    a_mc^m+a_{m-1}c^{m-1}d+\dots+a_0d^m=0
    \end{equation*}
    \(d\mid a_mc^m\) and therefore \(d\mid a_m\). Similarly \(c\mid a_0\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The polynomial \(f(X)=X^3-3X-1\) is irreducible in \(\Q[X]\) because its only possible roots
    are \(\pm 1\) and \(f(1)\neq 0\neq f(-1)\)
    #+END_examplle

    #+ATTR_LATEX: :options [Gauss's Lemma]
    #+BEGIN_proposition
    Let \(f(X)\in\Z[X]\). If \(f(X)\) factors nontrivially in \(\Q[X]\), then it factors nontrivially in \(\Z[X]\)
    #+END_proposition
