#+TITLE: Fields and Galois Theory

#+AUTHOR: J. S. Milne
#+EXPORT_FILE_NAME: ../latex/FieldsAndGaloisTheory/FieldsAndGaloisTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Basic Definitions and Results
** The characteristic of a field
    Given a field \(F\) and consider a map
    \begin{equation*}
    \Z\to F,\quad n\mapsto n\cdot 1_F
    \end{equation*}
    If the kernel of the map is \(\neq (0)\), so that \(n\cdot 1_F=0\) for some \(n\neq 0\). The smallest
    positive such \(n\) will be a prime \(p\) (otherwise \((m\cdot n)\cdot 1_F=(m\cdot 1_F)\cdot (n\cdot 1_F)=0\) there
    will be two nonzero elements in \(F\) whose product is zero, but a field is an integral domain)
    and \(p\) generates the kernel. Thus the map \(n\mapsto n\cdot 1_F:\Z\to F\) defines an isomorphism
    from \(\Z/p\Z\) onto the subring
    \begin{equation*}
    \{m\cdot 1_F\mid m\in\Z\}
    \end{equation*}
    of \(F\). In this case, \(F\) contains a copy of \(\F_p\)

    A field isomorphic to one of the fields \(\F_2,\F_3,\F_5,\dots,\Q\) is called a *prime field*. Every field
    contains exactly one prime field (as a subfield)

    A commutative ring \(R\) is said to have *characteristic* \(p\) (resp. 0) if it contains a prime
    field (as a subring) of characteristic \(p\) (resp. 0). Then the prime field is unique and, by
    definition, contains \(1_R\). Thus if \(R\) has characteristic \(p\neq 0\), then \(1_R+\dots+1_R=0\)
    (\(p\) terms)

    Let \(R\) be a nonzero commutative ring. If \(R\) has characteristic \(p\neq 0\), then
    \begin{equation*}
    pa:=\underbrace{a+\dots+a}_{p\text{ terms}}=\underbrace{(1_R+\dots+1_R)}_{p\text{ terms}}a=0a=0
    \end{equation*}
    for all \(a\in R\). Conversely, if \(pa=0\) for all \(a\in R\), then \(R\) has characteristic \(p\)

    Let \(R\) be a nonzero commutative ring. The usual proof by induction shows that the binomial
    theorem
    \begin{equation*}
    (a+b)^m=a^m+\binom{m}{1}a^{m-1}b+\binom{m}{2}a^{m-2}b^2+\dots+b^m
    \end{equation*}
    holds in \(R\). If \(p\) is prime, then it divides
    \begin{equation*}
    \binom{p}{r}:=\frac{p!}{r!(p-r)!}
    \end{equation*}
    for all \(r\) with \(1\le r\le p-1\). Therefore, when \(R\) has characteristic \(p\)
    \begin{equation*}
    (a+b)^p=a^p+b^p\quad\text{ for all }a,b\in R
    \end{equation*}
    and so the map \(a\mapsto a^p:R\to R\) is a homomorphism of rings (even of \(\F_p\)-algebras). It is
    called the *Frobenius endomorphsim* of \(R\). The map \(a\mapsto a^{p^n}:R\to R\), \(n\ge 1\), is hte
    composite of \(n\) copies of the Frobenius endomorphsim, and so it also is a homomorphism.
    Therefore
    \begin{equation*}
    (a_1,\dots,a_m)^{p^n}=a_1^{p^n}+\dots+a_m^{p^n}
    \end{equation*}
    for all \(a_i\in R\).

    When \(F\) is a field, the Frobenius endomorphsim is injective
** Review of polynomial rings
    The \(F\)-algebra \(F[X]\) has the following universal property: for any \(F\)-algebra \(R\) and
    element \(r\in R\), \(\exists!\) \(F\)-homomorphism \(\alpha:F[X]\to R\) s.t. \(\alpha(X)=r\)
** Factoring polynomials
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(r\in\Q\) be a root of a polynomial
    \begin{equation*}
    a_mX^m+a_{m-1}X^{m-1}+\dots+a_0,\quad a_i\in\Z
    \end{equation*}
    and write \(r=c/d\), \(c,d\in\Z\), \(\gcd(c,d)=1\). Then \(c\mid a_0\) and \(d\mid a_m\)
    #+END_proposition

    #+BEGIN_proof
    \begin{equation*}
    a_mc^m+a_{m-1}c^{m-1}d+\dots+a_0d^m=0
    \end{equation*}
    \(d\mid a_mc^m\) and therefore \(d\mid a_m\). Similarly \(c\mid a_0\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The polynomial \(f(X)=X^3-3X-1\) is irreducible in \(\Q[X]\) because its only possible roots
    are \(\pm 1\) and \(f(1)\neq 0\neq f(-1)\)
    #+END_examplle

    #+ATTR_LATEX: :options [Gauss's Lemma]
    #+BEGIN_proposition
    Let \(f(X)\in\Z[X]\). If \(f(X)\) factors nontrivially in \(\Q[X]\), then it factors nontrivially in \(\Z[X]\)
    #+END_proposition

    #+BEGIN_proof
    Let \(f=gh\in\Q[X]\) with \(g,h\) nonconstant. For suitable integers \(m\) and \(n\), \(g_1:=mg\)
    and \(h_1:=nh\) have coefficients in \(\Z\), so we have a factoriztion
    \begin{equation*}
    mnf=g_1\cdot h_1
    \end{equation*}
    in \(\Z[X]\). If a prime \(p\) divides \(mn\), then looking modulo \(p\), we obtain
    \begin{equation*}
    0=\bbar{g_1}\cdot\bbar{h_1}\in\F_p[X]
    \end{equation*}
    Since \(\F_p[X]\) is an integral domain, this implies that \(p\) divides all the coefficients of
    at least one of the polynomials \(g_1,h_1\), say \(g_1\), so that \(g_1=pg_2\) for some \(g_2\in\Z[X]\).
    Thus we have a factoriztion
    \begin{equation*}
    (mn/p)f=g_2\cdot h_1\in\Z[X]
    \end{equation*}
    Continuing in this fashion, we eventually remove all the prime factors of \(mn\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f\in\Z[X]\) is monic, then every monic factor of \(f\) in \(\Q[X]\) lies in \(\Z[X]\)
    #+END_proposition

    #+BEGIN_proof
    Let \(g\) be a monic factor of \(f\) in \(\Q[X]\), so that \(f=gh\) with \(h\in\Q[X]\) also monic.
    Let \(m,n\) be the positive integers with the fewest prime factors s.t. \(mg,nh\in\Z[X]\). As in
    the proof of Gauss's Lemma, if a prime \(p\) divides \(mn\), then it divides all the
    coefficients of at least one of the polynomials \(mg,nh\), say \(mg\), in which case it
    divides \(m\) because \(g\) is monic. Now \(\frac{m}{p}g\in\Z[X]\) which contradicts the definition
    of \(m\).
    #+END_proof

    #+ATTR_LATEX: :options [Eisenstein's Criterion]
    #+BEGIN_proposition
    label:1.16
    Let
    \begin{equation*}
    f=a_mX^m+\dots+a_0,\quad a_i\in\Z
    \end{equation*}
    suppose that there is a prime \(p\) s.t.
    1. \(p\nmid a_m\)
    2. \(p\mid a_i\)  for \(i=0,\dots,m-1\)
    3. \(p^2\nmid a_0\)


    Then \(f\) is irreducible in \(\Q[X]\)
    #+END_proposition

    #+BEGIN_proof
    If \(f(X)\) factors nontrivially in \(\Q[X]\), then it factors nontrivially in \(\Z[X]\), say
    \begin{equation*}
    a_mX^m+\dots+a_0=(b_rX^r+\dots+b_0)(c_sX^s+\dots+c_0)
    \end{equation*}
    where \(b_i,c_i\in\Z\). Since \(p\), but not \(p^2\), divides \(a_0=b_0c_0\), \(p\) must divide
    exactly one of \(b_0,c_0\), say \(b_0\). Now from the equation
    \begin{equation*}
    a_1=b_0c_1+b_1c_0
    \end{equation*}
    we see that \(p\mid b_1\), and from the equation
    \begin{equation*}
    a_2=b_0c_2+b_1c_1+b_2c_0
    \end{equation*}
    that \(p\mid b_2\). By continuing in this way, we find that \(p\) divides \(b_0,b_1,\dots,b_r\), which
    contradicts the condition that \(p\) does not divide \(a_m\)
    #+END_proof
** Extensions
    Let \(F\) be a field. A field containing \(F\) is called an *extension* of \(F\). In other words,
    an extension is an \(F\)-algebra whose underlying ring is a field. An extension \(E\) of \(F\)
    is, in particular, an \(F\)-vector space, whose dimension is called the *degree* of \(E\)
    over \(F\). It is denoted by \([E:F]\). An extension is *finite* if its degree is finite.

    When \(E\) and \(E'\) are extensions of \(F\), an *\(F\)-homomorphism* \(E\to E'\) is a
    homomorphism \(\varphi:E\to E'\) s.t. \(\varphi(c)=c\) for all \(c\in F\)

    #+ATTR_LATEX: :options [Multiplicity of degrees]
    #+BEGIN_proposition
    label:1.20
    Consider fields \(L\supset E\supset F\). Then \(L/F\) is of finite degree iff \(L/E\) and \(E/F\) are both
    of finite degree, in which case
    \begin{equation*}
    [L:F]=[L:E][E:F]
    \end{equation*}
    #+END_proposition
** The subring generated by a subset
    Let \(F\) be a subfield of a field \(E\) and let \(S\) be a subset of \(E\). The intersection of
    all the subrings of \(E\) containing \(F\) and \(S\) is obviously the smallest subring of \(E\)
    containing both \(F\) and \(S\). We call it the subring of \(E\) *generated by \(F\) and \(S\)*
    (*generated over \(F\) by \(S\)*), and we denote it by \(F[S]\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    The ring \(F[S]\) consists of the elements of \(E\) that can be expressed as finite sums of the
    form
    \begin{equation*}
    \sum a_{i_1\cdots i_n}\alpha_1^{i_1}\cdots\alpha_n^{i_n},\quad a_{i_1\cdots i_n}\in F,\quad\alpha_i\in S,\quad i_j\in\N
    \end{equation*}
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(R\) be an integral domain containing a subfield \(F\) (as a subring). If \(R\) is
    finite-dimensional when regarded as an \(F\)-vector space, then it is a field
    #+END_lemma

    #+BEGIN_proof
    Let \(\alpha\in R\) be nonzero. The map \(h:x\mapsto\alpha x\) is an injective linear map of
    finite-dimensional \(F\)-vector spaces, and is therefore surjective. In particular, there is an
    element \(\beta\in R\) s.t. \(\alpha\beta=1\)

    \(\alpha x=\alpha y\), we need \(R\) to be integral domain to make \(x=y\)

    Also for \(f\in R\), we need \(R\) to be a field to make \(\alpha fx=f\alpha x\)

    Surjection is trivial
    #+END_proof
** The subfield generated by a subset
    The intersection of all the subfields of \(E\) containing \(F\) and \(S\) is the smallest
    subfield of \(E\) containing both \(F\) and \(S\). We call it the subfield of \(E\) *generated
    by \(F\) and \(S\)*, and we denote it by \(F(S)\), it is the fraction field of \(F[S]\)

    An extension \(E\) of \(F\) is *simple* if \(E=F(\alpha)\) for some \(\alpha\in E\)

    Let \(F\) and \(F'\) be subfields of a field \(E\). The intersection of the subfields of \(E\)
    containing both \(F\) and \(F'\) is obviously the smallest subfield of \(E\) containing
    both \(F\)and \(F\). We call it the *composite* of \(F\) and \(F'\) in \(E\), and we denote it
    by \(F\cdot F'\). It can also be described as the subfield of \(E\) generated over \(F\) by \(F'\),
    or the subfield generated over \(F'\) by \(F\)
    \begin{equation*}
    F(F')=F\cdot F'=F'(F)
    \end{equation*}
** Construction of some extensions
    Let \(f(X)\in F(X)\) be a monic polynomial of degree \(m\). Consider the quotient \(F[X]/(f(X))\),
    and write \(x\) for the image of \(X\) in \(F[X]/(f(X))\), i.e., \(x=X+(f(X))\)
    1. The map
       \begin{equation*}
       P(X)\mapsto P(x):F[X]\to F[x]
       \end{equation*}
       is a homomorphism sending \(f(X)\) to 0, therefore \(f(x)=0\).
       \(F[x]=F[X]/(f)\) since for each \(x^n=(X+(f(X))^n)=X^n+(f(X))\).
    2. The division algorithm shows that every element \(g\in F[X]/(f)\)  is represented by a unique
       polynomial \(r\) of degree \(<m\). Hence each element of \(F[x]\) can be expressed uniquely
       as a sum
       \begin{equation*}
       a_0+a_1x+\dots+a_{m-1}x^{m-1},\quad a_i\in F
       \end{equation*}
    3. /Now assume that \(f(X)\) is irreducible/. Then every nonzero \(\alpha\in F[x]\) has an inverse, which
       can be found as follows. Use 2 to write \(\alpha=g(x)\) with \(g(X)\) a polynomial of
       degree \(\le m-1\), and apply Euclid's algorithm in \(F[X]\) to find polynomials \(a(X)\)
       and \(b(X)\) s.t.
       \begin{equation*}
       a(X)f(X)+b(X)g(X)=d(X)
       \end{equation*}
       with \(d(X)\) the gcd of \(f\) and \(g\). In our case, \(d(X)\) is 1 because \(f(X)\) is
       irreducible and \(\deg g(X)<\deg f(X)\). When we replace \(X\) with \(x\), the equality
       becomes
       \begin{equation*}
       b(x)g(x)=1
       \end{equation*}
       Hence \(b(x)\) is the inverse of \(g(x)\)



    We have proved the following statement
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.25
    For a monic irreducible polynomial \(f(X)\) of degree \(m\) in \(F[X]\)
    \begin{equation*}
    F[x]:=F[X]/(f(X))
    \end{equation*}
    is a field of degree \(m\) over \(F\). Computations in \(F[x]\) come down to computations
    in \(F\)
    #+END_proposition

    Since \(F[x]\) is a field, \(F(x)=F[x]\)


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(f(X)=X^2+1\in\R[X]\). Then \(\R[x]\) has elements \(a+bx,a,b\in\R\)

    We usually write \(i\) for \(x\) and \(\C\) for \(\R[x]\)
    #+END_examplle
** Stem fields
    Let \(f\) be a monic irreducible polynomial in \(F[X]\). A pair \((E,\alpha)\) consisting of an
    extension \(E\) of \(F\) and an \(\alpha\in E\) is called a *stem field for* \(f\) if \(E=F[\alpha]\)
    and \(f(\alpha)=0\). For example, the pair \((E,\alpha)\) with \(E=F[X]/(f)=F[x]\) and \(\alpha=x\).

    Let \((E,\alpha)\) be a stem field, and consider the surjective homomorphism of \(F\)-algebras
    \begin{equation*}
    g(X)\to g(\alpha):F[X]\to E
    \end{equation*}
    Its kernel is generated by a nonzero monic polynomial, which divides \(f\), and so must equal
    it. Therefore the homomorphism defines an \(F\)-isomorphism
    \begin{equation*}
    x\mapsto\alpha:F[x]\to E,\quad F[x]=F[X]/(f)
    \end{equation*}
    In other words, the stem field \((E,\alpha)\) of \(f\) is \(F\)-isomorphic to the standard stem field
    \((F[X]/(f),x)\). It follows that every element of a stem field \((E,\alpha)\) for \(f\) can be
    written uniquely in the form
    \begin{equation*}
    a_0+a_1\alpha+\dots+a_{m-1}\alpha^{m-1},\quad a_i\in F,\quad m=\deg(f)
    \end{equation*}
    and that arithmetic in \(F[\alpha]\) can be performed using the same rules in \(F[x]\).

** Algebraic and transcendental elements

    Let \(F\) be a field. An element \alpha of an extension \(E\) of \(F\) defines a homomorphism
    \begin{equation*}
    f(X)\mapsto f(\alpha):F[X]\to E
    \end{equation*}
    There are two possibilities:
    1. Kernel is \((0)\), so that for \(f\in F[X]\)
       \begin{equation*}
       f(\alpha)=0\Rightarrow f=0 (\text{in }F[X])
       \end{equation*}
       In this case we say that \alpha *transcendental over* \(F\). The homomorphism \(X\mapsto\alpha\) is an
       isomorphism, and it extends to an isppomorphism \(F(X)\to F(\alpha)\)
    2. The kernel \(\neq(0)\), so that \(g(\alpha)=0\) for some nonzero \(g\in F[X]\). In this case, we say
       that \alpha is *algebraic over* \(F\).  The polynomials \(g\) s.t. \(g(\alpha)=0\) form a nonzero ideal
       in \(F[X]\), which is generated by the monic polynomial \(f\) of least degree
       such \(f(\alpha)=0\). We call \(f\) the *minimal polynomial* of \alpha over \(F\).

       Note that \(F[X]/(f)\cong F[\alpha]\), since the first is a field, so is the second


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(\alpha\in\C\) be s.t. \(\alpha^3-3\alpha-1=0\). Then \(X^3-3X-1\) is monic, irreducible in \(\Q[X]\) and  has
    \alpha as a root, and so it is the minimal polynomial of \alpha over \(\Q\). The set \(\{1,\alpha,\alpha^2\}\) is a
    basis for \(\Q[\alpha]\) over \(\Q\).
    #+END_examplle

    An extension \(E\) of \(F\) is *algebraic* (\(E\) is *algebraic over* \(F\)) if all elements
    of \(E\) are algebraic over \(F\); otherwise it is said to be *transcendental*

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(E\supset F\) be fields. If \(E/F\) is finite, then \(E\) is algebraic and finitely generated (as
    a field) over \(F\); conversely if \(E\) is generated over \(F\) by a finite set of algebraic
    elements, then it is finite over \(F\)
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\). \alpha of \(E\) is transcendental over \(F\) iff \(1,\alpha,\alpha^2,\dots\) are linearly independent
    over \(F\) iff \(F[\alpha]\) is of infinite degree. Thus if \(E\) is finite over \(F\), then every
    element of \(E\) is algebraic over \(F\). If \(E\neq F\), then we can pick \(\alpha_1\in E\setminus F\) and
    compare \(E\) and \(F[\alpha_1]\). If \(E\neq F[\alpha_1]\), then there exists an \(\alpha_2\in E\setminus F[\alpha_1]\), and so on.
    Since
    \begin{equation*}
    [F[\alpha_1]:F]<[F[\alpha_1,\alpha_2]:F]<\cdots<[E:F]
    \end{equation*}
    this process terminates with \(E=F[\alpha_1,\dots,\alpha_n]\)

    \(\Leftarrow\): Let \(E=F(\alpha_1,\dots,\alpha_n)\) with \(\alpha_1,\dots,\alpha_n\) algebraic over \(F\). The extension \(F(\alpha_1)/F\)
    is finite because \(\alpha_1\) is algebraic over \(F\). And \(F(\alpha_1,\alpha_2)/F\) is finite because \(\alpha_2\) is
    algebraic over \(F\) and hence over \(F(\alpha_1)\). Thus by ref:1.20 \(F(\alpha_1,\alpha_2)\) is finite over \(F\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    1. If \(E\) is algebraic over \(F\), then every subring \(R\) of \(E\) containing \(F\) is a field
    2. Consider fields \(L\supset E\supset F\). If \(L\) is algebraic over \(E\) and \(E\) is algebraic
       over \(F\), then \(L\) is algebraic over \(F\)
    #+END_corollary

    #+BEGIN_proof
    1. If \(\alpha\in R\), then \(F[\alpha]\subset R\). But \(F[\alpha]\) is a field because \alpha is algebraic, and so \(R\)
       contains \(\alpha^{-1}\)
    2. By assumption, every \(\alpha\in L\) is a root of a monic polynomial
       \begin{equation*}
       X^m+a_{m-1}X^{m-1}+\dots+a_0\in E[X]
       \end{equation*}
       Each of the extensions
       \begin{equation*}
       F[a_0,\dots,a_{m-1},\alpha]\supset F[a_0,\dots,a_{m-1}]\supset\dots\supset F
       \end{equation*}
       is finite. Therefore \(F[a_0,\dots,a_{m-1},\alpha]\) is finite over \(F\), which implies that \alpha is
       algebraic over \(F\)
    #+END_proof

** Transcendental numbers
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The set of algebraic numbers is countable
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    The number \(\alpha=\sum\frac{1}{2^{n!}}\) is transcendental
    #+END_theorem

** Constructions with straight-edge and compass
    A real number (length) is *constructible* if it can be constructed by forming successive intersections of
    * lines drawn through two points already constructed
    * circles with center a point already constructed and radius a constructed length


    This led them to three famous questions: is it possible to
    duplicate the cube, trisect an angle, or square the circle by straight-edge and compass
    constructions? We’ll see that the answer to all three is negative.

    Let \(F\) be a subfield of \(\R\). For a positive \(a\in F\), The *\(F\)-plane* is \(F\times F\subset\R\times\R\)

    An *\(F\)-line* is a line in \(\R\times\R\) through two points in the \(F\)-plane. These are the lines
    given by equations
    \begin{equation*}
    ax+by+c=0,\quad a,b,c\in F
    \end{equation*}
    An *\(F\)-circle* is a circle in \(\R\times\R\) with center an \(F\)-point and radius an element
    of \(F\). These are the circles given by the equations
    \begin{equation*}
    (x-a)^2+(y-b)^2=c^2,\quad a,b,c\in F
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(L\neq L'\) be \(F\)-lines, and let \(C\neq C'\) be \(F\)-circles
    1. \(L\cap L'=\emptyset\) or consists of a single \(F\)-point
    2. \(L\cap C=\emptyset\) or consists of one or two points in the \(F[\sqrt{e}]\)-plane, some \(e\in F\), \(e>0\)
    3. \(C\cap C'=\emptyset\) or consists of one or two poitns in the \(F[\sqrt{e}]\)-plane, some \(e\in F\), \(e>0\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(c\) and \(d\) are constructive, then so also are \(c+d,-c,cd\)
       and \(\frac{c}{d}\), \(d\neq 0\)
    2. If \(c>0\) is constructible, then so is \(\sqrt{c}\)
    #+END_lemma

    #+BEGIN_proof
    First show that it is possible to construct a line perpendicular to a given line through a given
    point ([[https://qb.zuoyebang.com/xfe-question/question/ccd48609d90b8dd2e9aef5b5abaf3fe2.html][link]]), and then a line parallel to a given line through a given point ([[https://zhidao.baidu.com/question/239781112?from=&ssid=&uid=bd_1458321853_37&pu=sz%40224_240%2Cos%40&fr=solved&step=22&bd_page_type=1&init=middle][link]]). Hence it is
    possible to construct a triangle similar to a given one on a side with given length.


    \(\sqrt{c}\) [[https://zhidao.baidu.com/question/553468349.html][link]]
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    1. The set of constructible numbers is a field
    2. A number \alpha is constructible iff it is contained in a subfield of \(\R\) of the form
       \begin{equation*}
       \Q[\sqrt{a_1},\dots,\sqrt{a_r}],\quad a_i\in\Q[\sqrt{a_1},\dots,\sqrt{a_{i-1}}],\quad a_i>0
       \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \alpha is constructible, then \alpha is algebraic over \(\Q\), and \([\Q[\alpha]:\Q]\) is a power of 2
    #+END_corollary

    #+BEGIN_proof
    \([\Q[\alpha]:\Q]\) divides \([\Q[\sqrt{a_1}]\dots[\sqrt{a_r}]:\Q]\) and \([\Q[\sqrt{a_1},\dots,\sqrt{a_r}]:\Q]\) is a
    power of 2
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    It is impossible to duplicate the cube by straight-edge and compass constructions
    #+END_corollary

    #+BEGIN_proof
    This requires constructing the real root of the polynomial \(X^3-2\). But this polynomial is
    irreducible and \([\Q[\sqrt[3]{2}]:\Q]=3\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    In general, it is impossible to trisect an angle by straight-edge and compass constructions
    #+END_corollary

    #+BEGIN_proof
    Knowing an angle is equivalent to knowing the cosine of the angle. Therefore, to trisect \(3\alpha\),
    we have to construct a solution to
    \begin{equation*}
    \cos3\alpha=4\cos^3\alpha-3\cos\alpha
    \end{equation*}
    For example take \(3\alpha=\ang{60}\). As \(\cos\ang{60}=0.5\), we have to solve \(8x^3-6x-1=0\),
    which is irreducible, and so \([\Q[\alpha]:\Q]=3\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    It is impossible to square the circle by straight-edge and compass constructions
    #+END_corollary

    #+BEGIN_proof
    A square with the same area as a circle of radius \(r\) has side \(\sqrt{\pi}r\). Since \pi is
    transcendental, so also is \(\sqrt{\pi}\)
    #+END_proof

    \(X^p-1=(X-1)(X^{p-1}+X^{p-2}+\dots+1)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(p\) is prime, then \(X^{p-1}+\cdots+1\) is irreducible; hence \(\Q[e^{2\pi i/p}]\) has
    degree \(p-1\) over \(\Q\)
    #+END_lemma

    #+BEGIN_proof
    Let \(f(X)=(X^p-1)/(X-1)=X^{p-1}+\dots+1\); then
    \begin{equation*}
    f(X+1)=\frac{(X+1)^p-1}{X}=X^{p-1}+\dots+a_iX^i+\dots+p
    \end{equation*}
    with \(a_i=\binom{p}{i+1}\)

    \(p\mid a_i\) for \(i=1,\dots,p-2\), and so \(f(X+1)\) is irreducible by Eisenstein's criterion
    ref:1.16. This implies that \(f(X)\) is irreducible
    #+END_proof

** Algebraically closed fields
    Let \(F\) be a field. A polynomial is said to *split* in \(F[X]\) if it is a product of
    polynomials of degree at most 1 in \(F[X]\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.42
    For a field \Omega, TFAE
    1. Every nonconstant polynomial in \(\Omega[X]\) splits in \(\Omega[X]\)
    2. Every nonconstant polynomial in \(\Omega[X]\) has at least one root in \Omega
    3. The irreducible polynomials in \(\Omega[X]\) are those of degree 1
    4. Every field of finite degree over \Omega equals \Omega
    #+END_proposition

    #+BEGIN_proof
    \(3\to 4\): Let \(E\) be a finite extension of \Omega, and let \(\alpha\in E\). The minimal polynomial of \alpha,
    being irreducible, has degree 1, and so \(\alpha\in\Omega\)

    \(4\to 3\): Let \(f\) be an irreducible polynomial of \Omega, then \(\Omega[X]/(f)\) is an extension of
    \Omega of degree \(\deg(f)\), and so \(\deg(f)=1\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. A field \Omega is *algebraically closed* if it satisfies the equivalent statements in Proposition ref:1.42
    2. A field \Omega is an *algebraic closure* of a subfield \(F\) if it is algebraically closed and
       algebraic over \(F\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.44
    If \Omega is algebraic over \(F\) and every polynomial \(f\in F[X]\) splits in \(\Omega[X]\), then \Omega is
    algebraically closed
    #+END_proposition

    #+BEGIN_proof
    Let \(f\) be a nonconstant polynomial in \(\Omega[X]\). We know (ref:1.25) that \(f\) has a root
    \alpha in some finite extension \(\Omega'\) of \Omega. Set
    \begin{equation*}
    f=a_nX^n+\dots+a_0,\quad a_i\in\Omega
    \end{equation*}
    and consider the fields
    \begin{equation*}
    F\subset F[a_0,\dots,a_n]\subset F[a_0,\dots,a_n,\alpha]
    \end{equation*}
    Each extension generated by a finite set of algebraic elements, and hence is finite (ref:1.30)
    Therefore \alpha lies in a finite extension of \(F\) and so is algebraic over \(F\) - it is a root of
    a polynomial \(g\) with coefficients in \(F\). By assumption, \(g\) splits in \(\Omega[X]\), and so
    the root of \(g\) in \(\Omega'\) all lie in \Omega. In particular, \(\alpha\in\Omega\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\Omega\supset F\), then
    \begin{equation*}
    \{\alpha\in\Omega\mid\alpha\text{ algebraic over }F\}
    \end{equation*}
    is a field
    #+END_proposition

    #+BEGIN_proof
    If \alpha and \beta are algebraic over \(F\), then \(F[\alpha,\beta]\) is a field of finite degree over \(F\).
    Thus every element of \(F[\alpha,\beta]\) is algebraic over \(F\), in particular \(\alpha\pm\beta\), \(\alpha/\beta\)
    and \(\alpha\beta\) are algebraic over \(F\)
    #+END_proof

    The field constructed in the proposition is called the *algebraic closure of \(F\) in \(\Omega\)*

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\Omega\vDash\ACF\), for any subfield \(F\) of \Omega, the algebraic closure \(E\) of \(F\)  in \Omega is an
    algebraic closure of \(F\)
    #+END_corollary

    #+BEGIN_proof
    It is algebraic over \(F\) by definition. Every polynomial in \(F[X]\) splits in \(\Omega[X]\) and
    has its roots in \(E\), and so splits in \(E[X]\). Now apply Proposition ref:1.44
    #+END_proof

** Exercises
    1. \(f(x)=x^3-\alpha^2+\alpha+2\), \(f(x)\) is irreducible in \(\Q[x]\). Thus \(\Q[\alpha]\cong\Q[x]/(f)\), which is a
       field

       \((\alpha-1)^{-1}=-\frac{1}{3}(\alpha^2+1)\)

    2. 4

    3. ​
       1. \(f(X)-f(a)=q(X)(X-a)+r(X)\) and \(\deg r<1\), hence \(\deg r=0\)
       2. obvious
       3. obvious
    5. [@5] Let \(g\) be the irreducible factor in \(E[X]\) and let \((L,\alpha)\) be a stem field
       for \(g\) over \(E\). Then \(L=E[\alpha]\cong E/(f)\). Then \(m\mid[E[\alpha]:F]\).
       Since \(f(\alpha)=0\). \([F[\alpha]:F]=n\). Now \(n\mid[L:F]\). We deduce that \([L:F]=mn\)
       and \([L:E]=n\). But \([E[\alpha]:E]=\deg(g)\). Hence \(\deg(g)=\deg(f)\)
       \begin{center}\begin{tikzcd}
       E[\alpha]\ar[r,dash,"\le n"]\ar[d,dash]&E\ar[r,dash,"m"]&F\\
       F[\alpha]\ar[d,dash,"n"]\\
       F
       \end{tikzcd}\end{center}
    6. The polynomials \(f(X)-1\) and \(f(X)+1\) have only finitely many roots, and so there
       is \(n\in\Z\) s.t. \(f(n)\neq\pm 1\), then there is prime \(p\) s.t. \(p\mid f(n)\). Hence \(f(x)\) is
       reducible in \(\F_p[x]\)
    7. Let \(f(x)=x^3-2\), then \(R\cong\Q[x]/(f)\).




* Splitting Fields; Multiple Roots
**  Homomorphisms from simple extensions
    Let \(F\) be a field and \(E,E'\) fields containing \(F\). Recall that an \(F\)-homomorphism is
    a homomorphim \(\varphi:E\to E'\) s.t. \(\varphi(a)=a\) for all \(a\in F\). Thus an \(F\)-homomorphism \varphi maps a
    polynomial
    \begin{equation*}
    \sum a_{i_1\dots i_m}\alpha^{i_1}_1\dots\alpha_m^{i_m},\quad a_{i_1\dots i_m}\in F,\quad \alpha_i\in E
    \end{equation*}
    to
    \begin{equation*}
    \sum a_{i_1\dots i_m}\varphi(\alpha_1)^{i_1}\dots\varphi(\alpha_m)^{i_m}
    \end{equation*}
    An *\(F\)-isomorphism* is a bijective \(F\)-homomorphism

    An \(F\)-homomorphism \(E\to E'\) of fields is, in particular, an injective \(F\)-linear map
    of \(F\)-vector spaces, and so it is an \(F\)-isomorphism if \(E\) and \(E'\) have the same
    finite degree over \(F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:2.1
    Let \(F(\alpha)\) be a simple extension of \(F\) and \Omega a second extension of \(F\)
    1. Let \alpha be transcendental over \(F\). For every \(F\)-homomorphism \(\varphi:F(\alpha)\to\Omega\), \(\varphi(\alpha)\) is
       transcendental over \(F\), and the map \(\varphi\mapsto\varphi(\alpha)\) defines a one-to-one correspondence
       \begin{equation*}
       \{F\text{-homomorphisms } F(\alpha)\to\Omega\}\leftrightarrow\{\text{elements of $\Omega$ transcendental over }F\}
       \end{equation*}
    2. Let \alpha be algebraic over \(F\) with minimal polynomial \(f(X)\). For
       every \(F\)-homomorphism \(\varphi:F[\alpha]\to\Omega\), \(\varphi(\alpha)\) is a root of \(f(X)\) in \Omega, and the
       map \(\varphi\mapsto\varphi(\alpha)\) defines a one-to-one correspondence
       \begin{equation*}
       \{F\text{-homomorphisms }\varphi:F[\alpha]\to\Omega\}\leftrightarrow\{\text{roots of $f$ in }\Omega\}
       \end{equation*}
       In particular, the number of such maps is the number of distinct roots of \(f\) in \Omega
    #+END_proposition

    #+BEGIN_proof
    1. To say that \alpha is transcendental over \(F\) means that \(F[\alpha]\) is isomorphic to the
       polynomial ring in the symbol \alpha. Therefore for every \(\gamma\in\Omega\), there is a
       unique \(F\)-homomorphism \(\varphi:F[\alpha]\to\Omega\) s.t. \(\varphi(\alpha)=\gamma\). This \varphi extends (uniquely) to the
       field of fractions \(F(\alpha)\) iff nonzero elements of \(F[\alpha]\) are sent to nonzero elements of
       \Omega, which is the case iff \gamma is transcendental over \(F\). Thus there is a one-to-one
       correspondence between
       1. \(F(\alpha)\to\Omega\)
       2. \(\varphi:F[\alpha]\to\Omega\) s.t. \(\varphi(\alpha)\) is transcendental
       3. the transcendental elements of \Omega
    2. If \(\gamma\in\Omega\) is a root of \(f(X)\), then the map \(F[X]\to\Omega\), \(g(X)\mapsto g(\gamma)\), factor
       through \(F[X]/(f(X))\). When composed with the inverse of the canonical
       isomorphism \(F[\alpha]\to F[X]/(f(X))\), this becomes a homomorphism \(F[\alpha]\to\Omega\) sending \alpha to \gamma
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:2.2
    Let \(F(\alpha)\) be a simple extension of \(F\) and \(\varphi_0:F\to\Omega\) a homomorphism from \(F\) into a
    second field \Omega
    \begin{center}\begin{tikzcd}
    F(\alpha)\ar[rr,dash]&&\Omega\\
    F\ar[u,dash]\ar[rd,dash]\ar[rr,dash]&&\varphi_0(F)\ar[ld,dash]\ar[u,dash]\\
    &F
    \end{tikzcd}\end{center}

    1. if \alpha is transcendental over \(F\), then the map \(\varphi\mapsto\varphi(\alpha)\) defines a one-to-one
       correspondence
       \begin{equation*}
       \{\text{extensions }\varphi:F(\alpha)\to\Omega\text{ of }\varphi_0\}\leftrightarrow\{\text{elements of $\Omega$ transcendental over $\varphi_0(F)$}\}
       \end{equation*}
    2. If \alpha is algebraic over \(F\), with minimal polynomial \(f(X)\), then the map \(\varphi\mapsto\varphi(\alpha)\)
       defines a one-to-one correspondence
       \begin{equation*}
       \{\text{extensions }\varphi:F[\alpha]\to\Omega\text{ of }\varphi_0\}\leftrightarrow\{\text{roots of }\varphi_0f\text{ in }\Omega\}
       \end{equation*}
    #+END_proposition
** Splitting fields
    Let \(f\) be a polynomial with coefficients in \(F\). A field \(E\supseteq F\) is said to *split* \(f\)
    if \(f\) splits in \(E[X]\), i.e.,
    \begin{equation*}
    f(X)=a\prod_{i=1}^m(X-\alpha_i),\quad\alpha_i\in E
    \end{equation*}
    If \(E\) splits \(f\) and is generated by the roots of \(f\)
    \begin{equation*}
    E=F[\alpha_1,\dots,\alpha_m]
    \end{equation*}
    then it is called a *splitting* or *root field* for \(f\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:2.4
    Every polynomial \(f\in F[X]\) has a splitting field \(E_f\), and
    \begin{equation*}
    [E_f:F]\le(\deg f)!
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    Let \(F_1=F[\alpha_1]\) be a stem field for some monic irreducible factor of \(f\) in \(F[X]\).
    Then \(f(\alpha_1)=0\), and we let \(F_2=F_1[\alpha_2]\) be a stem field for some monic irreducible factor
    of \(f(X)/(X-\alpha_1)\) in \(F_1[X]\). Continuing in this fashion, we arrive at a splitting
    field \(E_f\). Let \(n=\deg f\). Then \([F_1:F]=\deg g_1\le n\), \([F_2:F_1]\le n-1\), and
    so \([E_f:F]\le n!\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. Let \(f(X)=(X^p-1)/(X-1)\in\Q[X]\), \(p\) prime. If \xi is one root of \(f\), then the remaining
       roots are \(\xi^2,\xi^3,\dots,\xi^{p-1}\), and so the splitting field of \(f\) is \(\Q[\xi]\)
    2. Let \(F\) have characteristic \(p\neq 0\), and let \(f=X^p-X-a\in F[X]\). If \alpha is one root of \(f\)
       in some extension of \(F\), then the remaining roots are \(\alpha+1,\dots,\alpha+p-1\), and so the
       splitting field of \(f\) is \(F[\alpha]\)
    3. If \alpha is one root of \(X^n-a\), then the remaining roots are all of the form \(\xi\alpha\),
       where \(\xi^n=1\). Therefore \(F[\alpha]\) is a splitting field for \(X^n-a\) iff \(F\) contains all
       the \(n\)th roots of 1. Note that if \(p\) is the characteristic of \(F\),
       then \(X^p-1=(X-1)^p\), and so \(F\) automatically contains all the \(p\)th roots of 1
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:2.7
    Let \(f\in F[X]\). Let \(E\) be the extension of \(F\) generated by the roots of \(f\) in \(E\),
    and let \Omega be an extension of \(F\) splitting \(f\)
    1. There exists an \(F\)-homomorphism \(\varphi:E\to\Omega\); the number of such homomorphisms is at
       most \(E:F\), and equals \([E:F]\) if \(f\) has distinct roots in \Omega
    2. If \(E\) and \Omega are both splitting fields for \(f\), then every \(F\)-homomorphism \(E\to\Omega\) is
       an isomorphism. In particular, any two splitting fields for \(f\) are \(F\)-isomorphic
    #+END_proposition

    #+BEGIN_proof
    We may assume that \(f\) is monic

    Let \(F,f,\Omega\) be as in the statement of the proposition, let \(L\) be a subfield of \Omega
    containing \(F\), and let \(g\) be a monic factor of \(f\) in \(L[X]\); as \(g\) divides \(f\)
    in \(\Omega[X]\), it is a product of certain number of the factors \(X-\beta_i\) of \(f\) in \(\Omega[X]\); in
    particular, we see that \(g\) splits in \Omega, and that it has distinct roots in \Omega if \(f\) does

    1. \(E=F[\alpha_1,\dots,\alpha_m]\), each \(\alpha_i\) a root of \(f(X)\) in \(E\). The minimal polynomial of \(\alpha_1\)
       is an irreducible polynomial \(f_1\) dividing \(f\). From the initial observation
       with \(L=F\), we see that \(f_1\) splits in \Omega, and that its roots are distinct if the roots
       of \(f\) are distinct. According to Proposition ref:2.1, there exists
       an \(F\)-homomorphism \(\varphi_1:F[\alpha_1]\to\Omega\) and the number of such homomorphisms is at
       most \([F[\alpha_1]:F]\), with equality holding when \(f\) has distinct roots in \Omega

       The minimal polynomial of \(\alpha_2\) over \(F[\alpha_1]\) is an irreducible factor \(f_2\) of \(f\)
       in \(F[\alpha_1][X]\). On applying the initial observation with \(L=\varphi_1F[\alpha_1]\) and \(g=\varphi_1f_2\) we see
       that \(\varphi_1f_2\) splits in \Omega. According to Proposition ref:2.2, each \(\varphi_1\) extends to a
       homomorphism \(\varphi_2:F[\alpha_1,\alpha_2]\to\Omega\), and the number of extensions is at most \([F[\alpha_1,\alpha_2]:F[\alpha_1]]\),
       with equality holding when \(f\) has distinct roots in \Omega

       On combining these statements we conclude that there exists an \(F\)-homomorphism
       \begin{equation*}
       \varphi:F[\alpha_1,\alpha_2]\to\Omega
       \end{equation*}
       and that the number of such homomorphisms is at most \([F[\alpha_1,\alpha_2]:F]\), with equality holding
       if \(f\) has distinct roots in \Omega

    2. Every \(F\)-homomorphism \(E\to\Omega\) is injective
       #+LATEX: \wu{
       if \(\alpha_1\neq\alpha_2\), then \(\alpha_1\) is not a root of \(f_2\), otherwise \(f_2\) is not minimal
       in \(F[\alpha_1][X]\). Thus \(f_2(\varphi_2\alpha_2)=0\neq f_2(\varphi_2\alpha_1)\), and so \(\varphi_2\alpha_2\neq\varphi_2\alpha_1\). Thus
       every \(F\)-homomorphism is injective.
       #+LATEX: }
        And so, if there exists such a homomorphism,
        then \([E:F]\le[\Omega:F]\). If \(E\) and \Omega are both splitting fields for \(f\), then 1 shows that
        there exist homomorphism \(E\leftrightarrows\Omega\), and so \([E:F]=[\Omega:F]\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(E\) and \(L\) be extension of \(F\), with \(E\) finite over \(F\)
    1. The number of \(F\)-homomorphisms \(E\to L\) is at most \([E:F]\)
    2. There exists a finite extension \(\Omega/L\) and an \(F\)-homomorphism \(E\to\Omega\)
    #+END_corollary

    #+BEGIN_proof
    Write \(E=F[\alpha_1,\dots,\alpha_m]\), and let \(f\in F[X]\) be the product of the minimal polynomials of
    the \(\alpha_i\); thus \(E\) is generated over \(F\) by roots of \(f\). Let \(\Omega\) be a splitting field
    for \(f\) regarded as an element of \(L[X]\). The proposition shows that there exists
    an \(F\)-homomorphism \(E\to\Omega\), and the number of such homomorphisms is \(\le[E:F]\). This proves
    (2). And since an \(F\)-homomorphism \(E\to L\) can be regarded as an \(F\)-homomorphism \(E\to\Omega\),
    it also proves (1)
    #+END_proof

    #+BEGIN_remark
    1. Let \(E_1,\dots,E_m\) be finite extensions of \(F\), and let \(L\) be an extension of \(F\). From
       the corollary we see that there exists a finite extension \(L_1/L\) s.t. \(L_1\) contains an
       isomorphic image of \(E_1\); then there exists a finite extension \(L_2/L_1\) s.t. \(L_2\)
       contains an isomorphic image of \(E_2\). Finally we can find a finite extension \(\Omega/L\) s.t.
       \Omega contains an isomorphic copy of each \(E_i\)
    2.
    #+END_remark
** Multiple roots
    Even when polynomials in \(F[X]\) have no common factor in \(F[X]\), one might expect that they
    could acquire a common factor in \(\Omega[X]\) for some \(\Omega\supset F\). In fact, this doesn't happen

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(f\) and \(g\) be polynomials in \(F[X]\), and let \Omega be an extension of \(F\). If \(r(X)\)
    is the gcd of \(f\) and \(g\) computed in \(F[X]\), then it is also the gcd of \(f\) and \(g\)
    in \(\Omega[X]\). In particular, distinct monic irreducible polynomials in \(F[X]\) do not acquire a
    common root in any extension of \(F\)
    #+END_proposition

    #+BEGIN_proof
    Let \(r_F(X)\) and \(r_\Omega(X)\) be the greatest common divisors of \(f\) and \(g\) in \(F[X]\)
    and \(\Omega[X]\) respectively. Certainly \(r_F(X)\mid r_\Omega(X)\) in \(\Omega[X]\), but Euclid's algorithm
    shows that there are polynomials \(a\) and \(b\) in \(F[X]\) s.t.
    \begin{equation*}
    a(X)f(X)+b(X)g(X)=r_F(X)
    \end{equation*}
    and so \(r_\Omega(X)\) divides \(r_F(X)\) in \(\Omega[X]\)
    #+END_proof

    The proposition allows us to speak of the gcd of \(f\) and \(g\) without reference to a field

    Let \(f\in F[X]\), then \(f\) splits into linear factors
    \begin{equation*}
    f(X)=a\prod_{i=1}^r(X-\alpha_i)^{m_i},\alpha_i\text{ distinct}, m_i\ge 1,\sum_{i=1}^rm_i=\deg(f)
    \end{equation*}
    in \(E[X]\) for some extension \(E\) of \(F\) (ref:2.4). We say that \(\alpha_i\) is a root of \(f\)
    of *multiplicity* \(m_i\) in \(E\). If \(m_i>1\), then \(\alpha_i\) is said to be a *multiple root*
    of \(f\), and otherwise it is a *simple root*

    Let \(E\) and \(E'\) be splitting fields for \(F\), and suppose
    that \(f(X)=a\prod_{i=1}^r(X-\alpha_i)^{m_i}\) in \(E[X]\) and \(f(X)=a'\prod_{i=1}^{r'}(X-\alpha_i')^{m_i'}\)
    in \(E'[X]\). Let \(\varphi:E\to E'\) be an \(F\)-isomorphism, which exists by ref:2.7
