#+TITLE: Fields and Galois Theory

#+AUTHOR: J. S. Milne
#+EXPORT_FILE_NAME: ../latex/FieldsAndGaloisTheory/FieldsAndGaloisTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Basic Definitions and Results
** The characteristic of a field
    Given a field \(F\) and consider a map
    \begin{equation*}
    \Z\to F,\quad n\mapsto n\cdot 1_F
    \end{equation*}
    If the kernel of the map is \(\neq (0)\), so that \(n\cdot 1_F=0\) for some \(n\neq 0\). The smallest
    positive such \(n\) will be a prime \(p\) (otherwise \((m\cdot n)\cdot 1_F=(m\cdot 1_F)\cdot (n\cdot 1_F)=0\) there
    will be two nonzero elements in \(F\) whose product is zero, but a field is an integral domain)
    and \(p\) generates the kernel. Thus the map \(n\mapsto n\cdot 1_F:\Z\to F\) defines an isomorphism
    from \(\Z/p\Z\) onto the subring
    \begin{equation*}
    \{m\cdot 1_F\mid m\in\Z\}
    \end{equation*}
    of \(F\). In this case, \(F\) contains a copy of \(\F_p\)

    A field isomorphic to one of the fields \(\F_2,\F_3,\F_5,\dots,\Q\) is called a *prime field*. Every field
    contains exactly one prime field (as a subfield)

    A commutative ring \(R\) is said to have *characteristic* \(p\) (resp. 0) if it contains a prime
    field (as a subring) of characteristic \(p\) (resp. 0). Then the prime field is unique and, by
    definition, contains \(1_R\). Thus if \(R\) has characteristic \(p\neq 0\), then \(1_R+\dots+1_R=0\)
    (\(p\) terms)

    Let \(R\) be a nonzero commutative ring. If \(R\) has characteristic \(p\neq 0\), then
    \begin{equation*}
    pa:=\underbrace{a+\dots+a}_{p\text{ terms}}=\underbrace{(1_R+\dots+1_R)}_{p\text{ terms}}a=0a=0
    \end{equation*}
    for all \(a\in R\). Conversely, if \(pa=0\) for all \(a\in R\), then \(R\) has characteristic \(p\)

    Let \(R\) be a nonzero commutative ring. The usual proof by induction shows that the binomial
    theorem
    \begin{equation*}
    (a+b)^m=a^m+\binom{m}{1}a^{m-1}b+\binom{m}{2}a^{m-2}b^2+\dots+b^m
    \end{equation*}
    holds in \(R\). If \(p\) is prime, then it divides
    \begin{equation*}
    \binom{p}{r}:=\frac{p!}{r!(p-r)!}
    \end{equation*}
    for all \(r\) with \(1\le r\le p-1\). Therefore, when \(R\) has characteristic \(p\)
    \begin{equation*}
    (a+b)^p=a^p+b^p\quad\text{ for all }a,b\in R
    \end{equation*}
    and so the map \(a\mapsto a^p:R\to R\) is a homomorphism of rings (even of \(\F_p\)-algebras). It is
    called the *Frobenius endomorphsim* of \(R\). The map \(a\mapsto a^{p^n}:R\to R\), \(n\ge 1\), is hte
    composite of \(n\) copies of the Frobenius endomorphsim, and so it also is a homomorphism.
    Therefore
    \begin{equation*}
    (a_1,\dots,a_m)^{p^n}=a_1^{p^n}+\dots+a_m^{p^n}
    \end{equation*}
    for all \(a_i\in R\).

    When \(F\) is a field, the Frobenius endomorphsim is injective
** Factoring polynomials
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(r\in\Q\) be a root of a polynomial
    \begin{equation*}
    a_mX^m+a_{m-1}X^{m-1}+\dots+a_0,\quad a_i\in\Z
    \end{equation*}
    and write \(r=c/d\), \(c,d\in\Z\), \(\gcd(c,d)=1\). Then \(c\mid a_0\) and \(d\mid a_m\)
    #+END_proposition

    #+BEGIN_proof
    \begin{equation*}
    a_mc^m+a_{m-1}c^{m-1}d+\dots+a_0d^m=0
    \end{equation*}
    \(d\mid a_mc^m\) and therefore \(d\mid a_m\). Similarly \(c\mid a_0\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The polynomial \(f(X)=X^3-3X-1\) is irreducible in \(\Q[X]\) because its only possible roots
    are \(\pm 1\) and \(f(1)\neq 0\neq f(-1)\)
    #+END_examplle

    #+ATTR_LATEX: :options [Gauss's Lemma]
    #+BEGIN_proposition
    Let \(f(X)\in\Z[X]\). If \(f(X)\) factors nontrivially in \(\Q[X]\), then it factors nontrivially in \(\Z[X]\)
    #+END_proposition

    #+BEGIN_proof
    Let \(f=gh\in\Q[X]\) with \(g,h\) nonconstant. For suitable integers \(m\) and \(n\), \(g_1:=mg\)
    and \(h_1:=nh\) have coefficients in \(\Z\), so we have a factoriztion
    \begin{equation*}
    mnf=g_1\cdot h_1
    \end{equation*}
    in \(\Z[X]\). If a prime \(p\) divides \(mn\), then looking modulo \(p\), we obtain
    \begin{equation*}
    0=\bbar{g_1}\cdot\bbar{h_1}\in\F_p[X]
    \end{equation*}
    Since \(\F_p[X]\) is an integral domain, this implies that \(p\) divides all the coefficients of
    at least one of the polynomials \(g_1,h_1\), say \(g_1\), so that \(g_1=pg_2\) for some \(g_2\in\Z[X]\).
    Thus we have a factoriztion
    \begin{equation*}
    (mn/p)f=g_2\cdot h_1\in\Z[X]
    \end{equation*}
    Continuing in this fashion, we eventually remove all the prime factors of \(mn\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f\in\Z[X]\) is monic, then every monic factor of \(f\) in \(\Q[X]\) lies in \(\Z[X]\)
    #+END_proposition

    #+BEGIN_proof
    Let \(g\) be a monic factor of \(f\) in \(\Q[X]\), so that \(f=gh\) with \(h\in\Q[X]\) also monic.
    Let \(m,n\) be the positive integers with the fewest prime factors s.t. \(mg,nh\in\Z[X]\). As in
    the proof of Gauss's Lemma, if a prime \(p\) divides \(mn\), then it divides all the
    coefficients of at least one of the polynomials \(mg,nh\), say \(mg\), in which case it
    divides \(m\) because \(g\) is monic. Now \(\frac{m}{p}g\in\Z[X]\) which contradicts the definition
    of \(m\).
    #+END_proof

    #+ATTR_LATEX: :options [Eisenstein's Criterion]
    #+BEGIN_proposition
    Let
    \begin{equation*}
    f=a_mX^m+\dots+a_0,\quad a_i\in\Z
    \end{equation*}
    suppose that there is a prime \(p\) s.t.
    1. \(p\nmid a_m\)
    2. \(p\mid a_i\)  for \(i=0,\dots,m-1\)
    3. \(p^2\nmid a_0\)


    Then \(f\) is irreducible in \(\Q[X]\)
    #+END_proposition

    #+BEGIN_proof
    If \(f(X)\) factors nontrivially in \(\Q[X]\), then it factors nontrivially in \(\Z[X]\), say
    \begin{equation*}
    a_mX^m+\dots+a_0=(b_rX^r+\dots+b_0)(c_sX^s+\dots+c_0)
    \end{equation*}
    where \(b_i,c_i\in\Z\). Since \(p\), but not \(p^2\), divides \(a_0=b_0c_0\), \(p\) must divide
    exactly one of \(b_0,c_0\), say \(b_0\). Now from the equation
    \begin{equation*}
    a_1=b_0c_1+b_1c_0
    \end{equation*}
    we see that \(p\mid b_1\), and from the equation
    \begin{equation*}
    a_2=b_0c_2+b_1c_1+b_2c_0
    \end{equation*}
    that \(p\mid b_2\). By continuing in this way, we find that \(p\) divides \(b_0,b_1,\dots,b_r\), which
    contradicts the condition that \(p\) does not divide \(a_m\)
    #+END_proof
** Extensions
    Let \(F\) be a field. A field containing \(F\) is called an *extension* of \(F\). In other words,
    an extension is an \(F\)-algebra whose underlying ring is a field. An extension \(E\) of \(F\)
    is, in particular, an \(F\)-vector space, whose dimension is called the *degree* of \(E\)
    over \(F\). It is denoted by \([E:F]\). An extension is *finite* if its degree is finite.

    When \(E\) and \(E'\) are extensions of \(F\), an *\(F\)-homomorphism* \(E\to E'\) is a
    homomorphism \(\varphi:E\to E'\) s.t. \(\varphi(c)=c\) for all \(c\in F\)

    #+ATTR_LATEX: :options [Multiplicity of degrees]
    #+BEGIN_proposition
    Consider fields \(L\supset E\supset F\). Then \(L/F\) is of finite degree iff \(L/E\) and \(E/F\) are both
    of finite degree, in which case
    \begin{equation*}
    [L:F]=[L:E][E:F]
    \end{equation*}
    #+END_proposition
** The subring generated by a subset
    Let \(F\) be a subfield of a field \(E\) and let \(S\) be a subset of \(E\). The intersection of
    all the subrings of \(E\) containing \(F\) and \(S\) is obviously the smallest subring of \(E\)
    containing both \(F\) and \(S\). We call it the subring of \(E\) *generated by \(F\) and \(S\)*
    (*generated over \(F\) by \(S\)*), and we denote it by \(F[S]\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    The ring \(F[S]\) consists of the elements of \(E\) that can be expressed as finite sums of the
    form
    \begin{equation*}
    \sum a_{i_1\cdots i_n}\alpha_1^{i_1}\cdots\alpha_n^{i_n},\quad a_{i_1\cdots i_n}\in F,\quad\alpha_i\in S,\quad i_j\in\N
    \end{equation*}
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(R\) be an integral domain containing a subfield \(F\) (as a subring). If \(R\) is
    finite-dimensional when regarded as an \(F\)-vector space, then it is a field
    #+END_lemma

    #+BEGIN_proof
    Let \(\alpha\in R\) be nonzero. The map \(h:x\mapsto\alpha x\) is an injective linear map of
    finite-dimensional \(F\)-vector spaces, and is therefore surjective. In particular, there is an
    element \(\beta\in R\) s.t. \(\alpha\beta=1\)

    \(\alpha x=\alpha y\), we need \(R\) to be integral domain to make \(x=y\)

    Also for \(f\in R\), we need \(R\) to be a field to make \(\alpha fx=f\alpha x\)

    Surjection is trivial
    #+END_proof
** The subfield generated by a subset
    The intersection of all the subfields of \(E\) containing \(F\) and \(S\) is the smallest
    subfield of \(E\) containing both \(F\) and \(S\). We call it the subfield of \(E\) *generated
    by \(F\) and \(S\)*, and we denote it by \(F(S)\), it is the fraction field of \(F[S]\)

    An extension \(E\) of \(F\) is *simple* if \(E=F(\alpha)\) for some \(\alpha\in E\)

    Let \(F\) and \(F'\) be subfields of a field \(E\). The intersection of the subfields of \(E\)
    containing both \(F\) and \(F'\) is obviously the smallest subfield of \(E\) containing
    both \(F\)and \(F\). We call it the *composite* of \(F\) and \(F'\) in \(E\), and we denote it
    by \(F\cdot F'\). It can also be described as the subfield of \(E\) generated over \(F\) by \(F'\),
    or the subfield generated over \(F'\) by \(F\)
    \begin{equation*}
    F(F')=F\cdot F'=F'(F)
    \end{equation*}
** Construction of some extensions
    Let \(f(X)\in F(X)\) be a monic polynomial of degree \(m\). Consider the quotient \(F[X]/(f(X))\),
    and write \(x\) for the image of \(X\) in \(F[X]/(f(X))\), i.e., \(x=X+(f(X))\)
    1. The map
       \begin{equation*}
       P(X)\mapsto P(x):F[X]\to F[x]
       \end{equation*}
       is a homomorphism sending \(f(X)\) to 0, therefore \(f(x)=0\).
       \(F[x]=F[X]/(f)\) since for each \(x^n=(X+(f(X))^n)=X^n+(f(X))\).
    2. The division algorithm shows that every element \(g\in F[X]/(f)\)  is represented by a unique
       polynomial \(r\) of degree \(<m\). Hence each element of \(F[x]\) can be expressed uniquely
       as a sum
       \begin{equation*}
       a_0+a_1x+\dots+a_{m-1}x^{m-1},\quad a_i\in F
       \end{equation*}
    3. /Now assume that \(f(X)\) is irreducible/. Then every nonzero \(\alpha\in F[x]\) has an inverse, which
       can be found as follows. Use 2 to write \(\alpha=g(x)\) with \(g(X)\) a polynomial of
       degree \(\le m-1\), and apply Euclid's algorithm in \(F[X]\) to find polynomials \(a(X)\)
       and \(b(X)\) s.t.
       \begin{equation*}
       a(X)f(X)+b(X)g(X)=d(X)
       \end{equation*}
       with \(d(X)\) the gcd of \(f\) and \(g\). In our case, \(d(X)\) is 1 because \(f(X)\) is
       irreducible and \(\deg g(X)<\deg f(X)\). When we replace \(X\) with \(x\), the equality
       becomes
       \begin{equation*}
       b(x)g(x)=1
       \end{equation*}
       Hence \(b(x)\) is the inverse of \(g(x)\)



    We have proved the following statement
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For a monic irreducible polynomial \(f(X)\) of degree \(m\) in \(F[X]\)
    \begin{equation*}
    F[x]:=F[X]/(f(X))
    \end{equation*}
    is a field of degree \(m\) over \(F\). Computations in \(F[x]\) come down to computations
    in \(F\)
    #+END_proposition

    Since \(F[x]\) is a field, \(F(x)=F[x]\)


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(f(X)=X^2+1\in\R[X]\). Then \(\R[x]\) has elements \(a+bx,a,b\in\R\)

    We usually write \(i\) for \(x\) and \(\C\) for \(\R[x]\)
    #+END_examplle
** Stem fields
    Let \(f\) be a monic irreducible polynomial in \(F[X]\). A pair \((E,\alpha)\) consisting of an
    extension \(E\) of \(F\) and an \(\alpha\in E\) is called a *stem field for* \(f\) if \(E=F[\alpha]\)
    and \(f(\alpha)=0\). For example, the pair \((E,\alpha)\) with \(E=F[X]/(f)=F[x]\) and \(\alpha=x\).

    Let \((E,\alpha)\) be a stem field, and consider the surjective homomorphism of \(F\)-algebras
    \begin{equation*}
    g(X)\to g(\alpha):F[X]\to E
    \end{equation*}
    Its kernel is generated by a nonzero monic polynomial, which divides \(f\), and so must equal
    it. Therefore the homomorphism defines an \(F\)-isomorphism
    \begin{equation*}
    x\mapsto\alpha:F[x]\to E,\quad F[x]=F[X]/(f)
    \end{equation*}
    In other words, the stem field \((E,\alpha)\) of \(f\) is \(F\)-isomorphic to the standard stem field
    \((F[X]/(f),x)\). It follows that every element of a stem field \((E,\alpha)\) for \(f\) can be
    written uniquely in the form
    \begin{equation*}
    a_0+a_1\alpha+\dots+a_{m-1}\alpha^{m-1},\quad a_i\in F,\quad m=\deg(f)
    \end{equation*}
    and that arithmetic in \(F[\alpha]\) can be performed using the same rules in \(F[x]\).
** Algebraic and transcendental elements

    Let \(F\) be a field. An element \alpha of an extension \(E\) of \(F\) defines a homomorphism
    \begin{equation*}
    f(X)\mapsto f(\alpha):F[X]\to E
    \end{equation*}
    There are two possibilities:
    1. Kernel is \((0)\), so that for \(f\in F[X]\)
       \begin{equation*}
       f(\alpha)=0\Rightarrow f=0 (\text{in }F[X])
       \end{equation*}
       In this case we say that \alpha *transcendental over* \(F\). The homomorphism \(X\mapsto\alpha\) is an
       isomorphism, and it extends to an isomorphism \(F(X)\to F(\alpha)\)
    2. The kernel \(\neq(0)\), so that \(g(\alpha)=0\) for some nonzero \(g\in F[X]\). In this case, we say
       that \alpha is *algebraic over* \(F\).  The polynomials \(g\) s.t. \(g(\alpha)=0\) form a nonzero ideal
       in \(F[X]\), which is generated by the monic polynomial \(f\) of least degree
       such \(f(\alpha)=0\). We call \(f\) the *minimal polynomial* of \alpha over \(F\).

       Note that \(F[X]/(f)\cong F[\alpha]\), since the first is a field, so is the second


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(\alpha\in\C\) be s.t. \(\alpha^3-3\alpha-1=0\). Then \(X^3-3X-1\) is monic, irreducible in \(\Q[X]\) and  has
    \alpha as a root, and so it is the minimal polynomial of \alpha over \(\Q\). The set \(\{1,\alpha,\alpha^2\}\) is a
    basis for \(\Q[\alpha]\) over \(\Q\).
    #+END_examplle

    An extension \(E\) of \(F\) is *algebraic* (\(E\) is *algebraic over* \(F\)) if all elements
    of \(E\) are algebraic over \(F\); otherwise it is said to be *transcendental*

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(E\supset F\) be fields. If \(E/F\) is finite, then \(E\) is algebraic and finitely generated (as
    a field) over \(F\); conversely if \(E\) is generated over \(F\) by a finite set of algebraic
    elements, then it is finite over \(F\)
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\). \alpha of \(E\) is transcendental over \(F\) iff \(1,\alpha,\alpha^2,\dots\) are linearly independent
    over \(F\) iff \(F(\alpha)\) is of infinite degree. Thus if \(E\) is finite over \(F\), then every
    element of \(E\) is algebraic over \(F\). If \(E\neq F\), then we can pick \(\alpha_1\in E\setminus F\) and
    compare \(E\) and \(F[\alpha_1]\)
    #+END_proof
