#+TITLE: Group Theory

#+AUTHOR: J. S. Milne

#+EXPORT_FILE_NAME: ../latex/GroupTheory/GroupTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\order}{order}
* Basic Definitions and Results
** Definitions and examples
    The *order* \(\abs{G}\) of a group is its cardinality. A finite group whose order is a power of a
    prime \(p\) is called a *\(p\)-group*

    \(C_n\) denote any cyclic group of order \(n\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(V\) be a finite-dimensional vector space over a field \(F\). A bilinear form on \(V\) is a
    mapping \(\phi:V\times V\to F\) that is linear in each variable. An *automorphism* of such a \phi is an
    isomorphism \(\alpha:V\to V\) s.t.
    \begin{equation*}
    \phi(\alpha v,\alpha w)=\phi(v,w)\text{ for all }v,w\in V
    \end{equation*}
    The automorphism of \phi form a group \(\Aut(\phi)\). Let \(\{e_1,\dots,e_n\}\) be a basis for \(V\), and let
    \begin{equation*}
    P=(\phi(e_i,e_j))_{1\le i,j\le n}
    \end{equation*}
    be the matrix of \phi. The choice of the basis identifies \(\Aut(\phi)\) with the group of invertible
    matrices \(A\) s.t.
    \begin{equation*}
    A^T\cdot P\cdot A=P
    \end{equation*}

    When \phi is symmetric, i.e.,
    \begin{equation*}
    \phi(v,w)=\phi(w,v)\text{ all }v,w\in V
    \end{equation*}
    and nondegenerate, \(\Aut(\phi)\) is called the *orthogonal group* of \phi
    #+END_examplle

    #+ATTR_LATEX: :options [Cayley]
    #+BEGIN_theorem
    There is a canonical injective homomorhism
    \begin{equation*}
    \alpha:G\to\Sym(G)
    \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    A finite group of order \(n\) can be realized as a subgroup of \(S_n\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(H\) be a subgroup of a group \(G\)
    1. An element \(a\in G\)  lies in a left coset \(C\) of \(H\) iff \(C=aH\)
    2. Two left cosets are either disjoint or equal
    3. \(aH=bH\) iff \(a^{-1}b\in H\)
    4. Any two left cosets have the same number of elements
    #+END_proposition

    The *index* \((G:H)\) of \(H\) in \(G\) is defined to be the number of left cosets of \(H\)
    in \(G\). For example, \((G:1)\) is the order of \(G\)

    #+ATTR_LATEX: :options [Lagrange]
    #+BEGIN_theorem
    If \(G\) is finite, then
    \begin{equation*}
    (G:1)=(G:H)(H:1)
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    The left cosets of \(H\) in \(G\) form a partition of \(G\), there are \((G:H)\) of them
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The order of each element of a finite group divides the order of the group
    #+END_corollary

    #+BEGIN_proof
    Consider \(H=\la g\ra\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For any subgroups \(H\supset K\) of \(G\)
    \begin{equation*}
    (G:K)=(G:H)(H:K)
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    \(G=\coprod_{i\in I}g_iH\), and \(H=\coprod_{j\in J}h_jK\)
    #+END_proof
** Normal subgroups
    A subgroup \(N\) of \(G\) is *normal*, denoted \(N\lhd G\), if \(gNg^{-1}=N\) for all \(g\in G\)

    it suffices to check that \(gNg^{-1}\subset N\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    subgroup \(N\) of \(G\) is normal iff every left coset of \(N\) in \(G\) is also a right coset
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. Every subgroup of index two is normal. Indeed, let \(g\in G\setminus H\), then \(G=H\coprod gH=H\coprod Hg\)
    #+END_examplle

    A group \(G\) is *simple* if it has no normal subgroups other than \(G\) and \(\{e\}\).

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(H\) and \(N\) are subgroups of \(G\) and \(N\) is normal, then \(HN\) is a subgroup
    of \(G\). If \(H\) is also normal, then \(HN\) is a normal subgroup of \(G\)
    #+END_proposition


    Intersection of normal subgroups of a group is again a normal subgroup. Therefore we can define
    the *normal subgroup generated by a subset \(X\)* of a group \(G\) to be the intersection of the
    normal subgroups containing \(X\). We say that a subset \(X\) of a group \(G\) is *normal*
    if \(gXg^{-1}\subset X\) for all \(g\in G\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(X\) is normal, then the subgroup \(\la X\ra\) generated by it is normal
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any subset \(X\) of \(G\), the subset \(\bigcup_{g\in G}gXg^{-1}\) is normal, and it is the smallest
    normal set containing \(X\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The normal subgroup generated by a subset \(X\) of \(G\) is \(\la\bigcup_{g\in G}gXg^{-1}\ra\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The map \(a\mapsto aN:G\to G/N\) has the following universal property: for any homomorhism \(\alpha:G\to G'\)
    of groups s.t. \(\alpha(N)=\{e\}\), there exists a unique homomorhism \(G/N\to G'\) making the diagram
    \begin{center}\begin{tikzcd}
    G\ar[r,"a\mapsto aN"]\ar[rd,"\alpha"']&G/N\ar[d,dashed]\\
    &G'
    \end{tikzcd}\end{center}
    commute
    #+END_proposition

    #+BEGIN_proof
    Define \(\baralpha:G/N\to G'\), \(\baralpha(gN)=\alpha(g)\)
    #+END_proof
** Theorems concerning homomorhisms
    The kernel of the homomorhism \(\det:\GL_n(F)\to F^{\times}\) is the group of \(n\times n\) with determinant
    1 - this group \(\SL_n(F)\) is called the *special linear group of degree \(n\)*

    #+ATTR_LATEX: :options [HOMOMORPHISM THEOREM]
    #+BEGIN_theorem
    For any homomorhism \(\alpha:G\to G'\) of groups, \(\ker\alpha\lhd G\), \(\im\alpha\le G'\), and \alpha factors in a
    natural way into the composite of a surjection, an isomorphism, and an injection
    \begin{center}\begin{tikzcd}
    G\ar[d,twoheadrightarrow,"g\mapsto gN"]\ar[r,"\alpha"]&G'\\
    G/N\ar[r,"\sim","gN\mapsto\alpha(g)"']&I\ar[u,rightarrowtail]
    \end{tikzcd}\end{center}

    #+END_theorem

    #+ATTR_LATEX: :options [ISOMORPHISM THEOREM]
    #+BEGIN_theorem
    \(H\le G\), \(N\lhd G\). Then \(HN\le G\), \(H\cap N\lhd G\)
    \begin{equation*}
    h(H\cap N)\mapsto hN:H/H\cap N\to HN/ N
    \end{equation*}
    is an isomorphism
    #+END_theorem

    [[https://math.stackexchange.com/questions/3122468/is-hn-n-equal-to-h-n][link]]

    \(\barG\) is a quotient group of \(G\)
    #+ATTR_LATEX: :options [CORRESPONDENCE THEOREM]
    #+BEGIN_theorem
    Let \(\alpha:G\twoheadrightarrow\barG\) be a surjective homomorhism, and let \(N=\ker\alpha\). Then there is a one-to-one
    correspondence
    \begin{equation*}
    \{\text{subgroups of $G$ containing $N$}\}\leftrightarrow\{\text{subgroups of $\barG$}\}
    \end{equation*}
    under which a subgroup \(H\) of \(G\) containing \(N\) corresponds to \(\barH=\alpha(H)\) and a
    subgroup \(\barH\) of \(\barG\) corresponds to \(H=\alpha^{-1}(\barH)\). Moreover, if \(H\leftrightarrow\barH\)
    and \(H'\leftrightarrow\barH'\), then
    1. \(\barH\subset\barH'\Leftrightarrow H\subset H'\), in which case \((\barH':\barH)=(H':H)\)
    2. \(\barH\lhd\barG\Leftrightarrow H\lhd G\) , in which case \alpha induces an isomorphism
       \begin{equation*}
       G/H\xrightarrow{\simeq}\barG/\barH
       \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(N\lhd G\); then there is a one-to-one correspondence between the set of subgroups of \(G\)
    containing \(N\) and the set of subgroups of \(G/N\), \(H\leftrightarrow H/N\).
    Moreover \(H\lhd G\Leftrightarrow H/N\lhd G/N\), in which case the homomorhism \(g\mapsto gN:G\to G/N\) induces an
    isomorphism
    \begin{equation*}
    G/H\cong(G/N)/(H/N)
    \end{equation*}
    #+END_corollary
** Direct products
    Let \(G\) be a group, and let \(H_1,\dots,H_k\) be subgroups of \(G\). \(G\) is a *direct product* of
    the subgroups \(H_i\) if the map
    \begin{equation*}
    (h_1,\dots,h_k)\mapsto h_1\dots h_k:H_1\times\dots\times H_k\to G
    \end{equation*}
    is an isomorphism of groups

    note that if \(g=h_1\dots h_k\) and \(g'=h_1'\dots h_k'\), then
    \begin{equation*}
    gg'=(h_1h_1')\dots(h_kh_k')
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    A group \(G\) is a direct product of subgroups \(H_1,H_2`\) iff
    1. \(G=H_1H_2\)
    2. \(H_1\cap H_2=\{e\}\)
    3. every element of \(H_1\) commutes with every element of \(H_2\)
    #+END_proposition

    #+BEGIN_proof
    3 shows that \((h_1,h_2)\to h_1h_2\) is a homomorhism, 2 injective, 1 surjective
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    A group \(G\) is a direct product of subgroups \(H_1,H_2`\) iff
    1. \(G=H_1H_2\)
    2. \(H_1\cap H_2=\{e\}\)
    3. \(H_1,H_2\lhd G\)
    #+END_proposition

    #+BEGIN_proof
    The elements \(h_1,h_2\) of a group commute iff their commutator
    \begin{equation*}
    [h_1,h_2]:=(h_1h_2)(h_2h_1)^{-1}
    \end{equation*}
    is \(e\). But
    \begin{equation*}
    (h_1h_2)(h_2h_1)^{-1}=h_1h_2h_1^{-1}h_2^{-2}=
    \begin{cases}
    (h_1h_2h_1^{-1})\cdot h_2^{-1}\\
    h_1\cdot(h_2h_1^{-1}h_2^{-1})
    \end{cases}
    \end{equation*}
    which is in \(H_2\) because \(H_2\) is normal, and is in \(H_1\) because \(H_1\) is normal
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    A group \(G\) is a direct product of subgroups \(H_1,\dots,H_k\) iff
    1. \(G=H_1\dots H_k\)
    2. for each \(j\), \(H_j\cap(H_1\dots H_{j-1}H_{j+1}\dots H_k)=\{e\}\)
    3. \(H_1,\dots,H_k\lhd G\)
    #+END_proposition
** Commutative groups
    Let \(M\) be a commute group. The subgroup \(\la x_1,\dots,x_k\ra\) of \(M\) generated by the
    elements \(x_1,\dots,x_k\) consists of the sums \(\sum m_1x_i\), \(m_i\in\Z\). A subset \(\{x_1,\dots,x_k\}\)
    of \(M\) is a *basis* of \(M\) if it generates \(M\) and
    \begin{equation*}
    \sum m_ix_i=0,m_i\in\Z\Longrightarrow m_ix_i=0\text{ for every }i
    \end{equation*}
    then
    \begin{equation*}
    M=\la x_1\ra\oplus\dots\oplus\la x_k\ra
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(x_1,\dots,x_k\) generate \(M\). For any \(c_1,\dots,c_k\in\N\) with \(\gcd(c_1,\dots,c_k)=1\), there exist
    generators \(y_1,\dots,y_k\) for \(M\) s.t. \(y_1=c_1x_1+\dots+c_kx_k\)
    #+END_lemma

    #+BEGIN_proof
    We argue by induction on \(s=c_1+\dots+c_k\). The lemma certainly holds if \(s=1\), and so we
    assume \(s>1\). Then, at least two \(c_i\) are nonzero, say, \(c_1\ge c_2>0\). Now
    * \(\{x_1,x_2+x_1,x_3,\dots,x_k\}\) generates \(M\)
    * \(\gcd(c_1-c_2,c_2,c_3,\dots,c_k)=1\)
    * \((c_1-c_2)+c_2+\dots+c_k<s\)


    and so, by induction, there exist generators \(y_1,\dots,y_k\) for \(M\) s.t.
    \begin{align*}
    y_1&=(c_1-c_2)x_1+c_2(x_1+x_2)+c_3x_3+\dots+c_kx_k\\
    &=c_1x_1+\dots+c_kx_k
    \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:1.54
    Every finitely generated commutative group \(M\) has a basis; hence it is a finite direct sum of
    cyclic groups
    #+END_theorem

    #+BEGIN_proof
    Induction on the generators of \(M\).

    Among the generating sets \(\{x_1,\dots,x_k\}\) for \(M\) with \(k\) elements there is one for which
    the order of \(x_1\) is the smallest possible. We shall show that \(M\) is the direct sum
    of \(\la x_1\ra\) and \(\la x_2,\dots,x_k\ra\)

    If \(M\) is not the direct sum of \(\la x_1\ra\) and \(\la x_2,\dots,x_k\ra\), then there exists a relation
    \begin{equation*}
    m_1x_1+\dots+m_kx_k=0
    \end{equation*}
    with \(m_1x_1\neq 0\). After possibly changing the sign of some of the \(x_i\), we may suppose
    that \(m_1,\dots,m_k\in\N\) and \(m_1<\order(x_1)\). Let \(d=\gcd(m_1,\dots,m_k)>0\), and let \(c_i=m_i/d\).
    According to the lemma, there exists a generating set \(y_1,\dots,y_k\) s.t. \(y_1=c_1x_1+\dots+c_kx_k\).
    But
    \begin{equation*}
    dy_1=m_1x_1+\dots+m_kx_k=0
    \end{equation*}
    and \(d\le m_1<\order(x_1)\), and so this contradicts the choice of \(\{x_1,\dots,x_k\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    A finite commutative group is cyclic if, for each \(n>0\), it contains at most \(n\) elements of
    order dividing \(n\)
    #+END_corollary

    #+BEGIN_proof
    After Theorem ref:1.54, we may assume that \(G=C_{n_1}\times\dots\times C_{n_r}\) with \(n_i\in\N\). If \(n\)
    divides \(n_i\) and \(n_j\) with \(i\neq j\), then \(G\) has more than \(n\) elements of order
    dividing \(n\)
    #+LATEX: \wu{
    First consider \(n=p\), then in \(C_p\) there are \(p-1\) elements of order dividing \(p\) by
    Lagrange theorem.

    Now consider \(n=p_1p_2\). If \((k,p_1p_2)=1\), then order of \(k\) is \(p_1p_2\). Hence there are at
    least \(p_1p_2-p_1-p_2-1\) elements.
    Check [[https://sites.pitt.edu/~gmc/ch1/node7.html][THIS]]!
    #+LATEX: }
    Therefore the hypothesis implies that the \(n_i\) are relatively prime.
    Let \(a_i\) generate the \(i\)th factor. Then \((a_1,\dots,a_r)\) has order \(n_1\dots n_r\), and so
    generates \(G\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    label:1.56
    Let \(F\) be a field. The elements of order dividing \(n\) in \(F^{\times}\) are the roots of the
    polynomial \(X^n-1\). Because unique factorization holds in \(F[X]\), there are at most \(n\) of
    these, and so corollary shows that every finite subgroup of \(F^{\times}\) is cyclic
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    A nonzero finitely generated commutative group \(M\) can be expressed
    \begin{equation*}
    M\approx C_{n_1}\times\cdots\times C_{n_s}\times C_\infty^r
    \end{equation*}
    for certain integers \(n_1,\dots,n_s\ge 2\) and \(r\ge 0\). Moreover
    1. \(r\) is uniquely determined by \(M\)
    2. the \(n_i\) can be chosen so that \(n_1\ge 2\) and \(n_1\mid n_2,\dots,n_{s-1}\mid n_s\), and then they are
       uniquely determined by \(M\)
    3. the \(n_i\) can be chosen to be powers of prime numbers, and then they are uniquely determined
       by \(M\)
    #+END_theorem

    The number \(r\) is called the *rank* of \(M\). By \(r\) being uniquely determined by \(M\), we
    mean that two decompositions of \(M\) of the form , the number of copies of \(C_\infty\) will be the
    same. The integers in (2) are called the *invariant factors* of \(M\). Statement (3) says
    that \(M\) can be expressed
    \begin{equation*}
    M\approx C_{p_1^{e_1}}\times\dots\times C_{p_t^{e_t}}\times C_\infty^r,\quad e_i\ge 1
    \end{equation*}
    for certain prime powers \(p_i^{e_i}\), and that the integers \(p_1^{e_1},\dots,p_t^{e_t}\) are uniquely
    determined by \(M\); they are called the *elementary divisors* of \(M\)


    #+BEGIN_proof
    The first assertion is a restatement of Theorem ref:1.54
    1. For a prime \(p\) not dividing any of the \(n_i\)
       \begin{equation*}
       M/pM\approx(C_\infty/pC_\infty)^r\cong(\Z/p\Z)^r
       \end{equation*}
       and so \(r\) is the dimension of \(M/pM\) as an \(\F_p\)-vector space
       #+LATEX: \wu{
       suppose \(C_n=\la a\ra\) and \(f:C_n\to pC_n:a\mapsto a^p\). Since \((p,n)=1\), \(\abs{a^p}=n\). Thus this
       is an isomorphism
       #+LATEX: }
    2. 3. If \(\gcd(m,n)=1\), then \(C_m\times C_n\) contains an element of order \(mn\), and so
       \begin{equation*}
       C_m\times C_n\approx C_{mn}
       \end{equation*}
       In this way we can decomposite \(C_{n_i}\) into products of cyclic groups of prime power order.
       Then we can construct what we want

       To prove the uniqueness of (2) and (3), we can replace \(M\) with its torsion subgroup (and
       so assume \(r=0\)).

       uniqueness of elementary divisors is clear.

       \(n_s\) is the smallest integer \(>0\) s.t. \(n_sM=0\); \(n_{s-1`}\) is the smallest
       integer \(>0\) s.t. \(n_{s-1}M\) is cyclic; \(n_{s-2}\) is the smallest integer
       s.t. \(n_{s-2}M\) can be expressed as a product of two cyclic groups, and so on

       in the end, we will get a factoring like
       \begin{alignat*}{4}
       &C_{p_1^{r_1}}\quad&&C_{p_1^{r_2}}\quad&&C_{p_1^{r_3}}\quad&&C_{p_1^{r_4}}\\
       &C_{p_2^{s_1}}&&C_{p_2^{s_2}}\\
       &C_{p_3^{t_1}}&&C_{p_3^{t_2}}&&C_{p_3^{t_3}}
       \end{alignat*}
       and get out invariant factors
    #+END_proof
** The order of \texorpdfstring{\(ab\)}{ab}
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any integers \(m,n,r>1\), there exists a finite group \(G\) with elements \(a\) and \(b\)
    s.t. \(a\) has order \(m\), \(b\) has order \(n\), and \(ab\) has order \(r\)
    #+END_theorem

    #+BEGIN_proof
    We shall show that, for a suitable prime power \(q\), there exist elements \(a\) and \(b\)
    of \(\SL_2(\F_q)\) s.t. \(a,b\) and \(ab\) have orders \(2m,2n\) and \(2r\) respectively.
    As \(-I\) is the unique element of order 2 in \(\SL_2(\F_q)\), the image of \(a,b,ab\)
    in \(\SL_2(\F_q)/\{\pm I\}\) will then have orders \(m,n\) and \(r\) as required.

    Let \(p\) be the prime number not dividing \(2mnr\). Then \(p\) is a unit in the finite
    ring \(\Z/2mnr\Z\), and so some power of it, \(q\) say, is 1 in the ring. This means that \(2mnr\)
    divides \(q-1\). As the group \(\F_q^\times\) has order \(q-1\) and is cyclic (ref:1.56), there exist
    element \(u,v,w\in\F_q^{\times}\) having orders \(2m,2n\) and \(2r\) respectively. Let
    \begin{equation*}
    a=
    \begin{pmatrix}
    u&1\\0&u^{-1}
    \end{pmatrix}\in\SL_2(\F_q)\quad b=
    \begin{pmatrix}
    v&0\\t&v^{-1}
    \end{pmatrix}\in\SL_2(\F_q)
    \end{equation*}
    where \(t\) has been chosen so that
    \begin{equation*}
    uv+t+u^{-1}v^{-1}=w+w^{-1}
    \end{equation*}
    The characteristic polynomial of \(a\) is \((X-u)(X-u^{-1})\)
    #+END_proof

    <<SKIP>>
** Exercises
    #+BEGIN_exercise
    label:ex1.4
    Let \(n=n_1+\dots+n_r\) be a partition of the positive integer \(n\). Use Lagrange's theorem to show
    that \(n!\) is divisible by \(\prod_{i=1}^rn_i!\)
    #+END_exercise

    #+BEGIN_proof
    \(n_1,\dots,n_r\) is a partition of \(n\) elements, and \(S_{n_i}\) is the permutation group of each
    part.

    Apparently each \(S_{n_i}\) is normal. Thus \(S_{n_1}\dots S_{n_r}\) is a subgroup of \(S\).
    Also \(S_{n_i}\cap S_{n_j}=\{\id\}\). Therefore \(S_{n_1}\dots S_{n_r}\cong S_{n_1}\times\dots\times S_{n_r}\)
    #+END_proof

    #+BEGIN_exercise
    label:ex1.5
    Let \(N\lhd G\) of index \(n\). Show that \(g\in G\Rightarrow g^n\in N\)
    #+END_exercise

    #+BEGIN_proof
    Because the group \(G/N\) has order \(n\), \((gN)^n=1\) for every \(g\in G\).
    #+END_proof
* Free Groups and Presentations; Coxeter Groups
** Free monoids
    Let \(X=\{a,b,c,\dots\}\). A *word* is a finite sequence of symbols from \(X\). Empty sequence is
    denoted by \(1\). Write \(SX\) for the set of words together with the binary concatenation.
    Then \(SX\) is a monoid, called the *free monoid* on \(X\)

    \(X\to SX\) has the following universal property: for any map of sets \(\alpha:X\to S\) from \(X\) to a
    monoid \(S\), there exists a unique homomorhism \(SX\to S\) making the diagram
    \begin{center}\begin{tikzcd}
    X\ar[r,"a\mapsto a"]\ar[dr,"\alpha"']&SX\ar[d,dashed]\\
    &S
    \end{tikzcd}\end{center}
    commute
** Free groups
    We want to construct a group \(FX\) contianing \(X\) and having the same universal property.
    Define
    \begin{equation*}
    X'=\{a,a^{-1},b,b^{-1},\dots\}
    \end{equation*}
    Let \(W'\) be the set of words using symbols from \(X'\). A word is *reduced* if it contains no
    pairs of the form \(aa^{-1}\) or \(a^{-1}a\). Starting with a word \(w\), we can perform a
    finite sequence of cancellations to arrive at a reduced word, which will be called the *reduced
    form* \(w_0\) of \(w\).

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    There is only one reduced form of a word
    #+END_proposition

* TODO skip and problems
    |[[SKIP]]|
