#+TITLE: Introduction To Commutative Algebra
#+AUTHOR: Atiyah & Macdonald

#+LATEX_HEADER: \input{../preamble.tex}
#+EXPORT_FILE_NAME: ../latex/IntroductionToCommutativeAlgebra/IntroductionToCommutativeAlgebra.tex
#+options: num:1
* Rings and Ideals
  A *unit* is an element \(u\) with a *reciprocal* \(1/u\) or the
  *multiplicative inverse*. The units form a multiplicative group, denoted
  \(R^\times\)

  A ring *homomorphism*, or simply a *ring map*, \(\varphi:R\to R'\) is a map
  preserving sum, products and 1

  If there is an unspecified isomorphism between rings \(R\) and \(R'\), then we
  write \(R=R'\) when it is *canonical*; that is, it does not depend on any
  artificial choices.

  A subset \(R''\subset R\) is a *subring* if \(R''\) is a ring and the
  inclusion \(R''\hookrightarrow R\) is a ring map. In this case, we call \(R\)
  a *(ring) extension*.

  An *\(R\)-algebra* is a ring \(R'\) that comes equipped with a ring map
  \(\varphi:R\to R'\), called the *structure map*, denoted by \(R'/R\). For
  example, every ring is canonically a \(\Z\)-algebra. An
  *\(R\)-algebra homomorphism*, or *\(R\)-map*, \(R'\to R''\) is a ring map
  between \(R\)-algebras.

  A group \(G\) is said to *act* on \(R\) if there is a homomorphism given from
  \(G\) into the group of automorphism of \(R\). The *ring of invariants*
  \(R^G\) is the subring defined by
  \begin{equation*}
  R^G:=\{x\in R\mid gx=g\text{ for all }g\in G\}
  \end{equation*}

  Similarly a group \(G\) is said to *act* on \(R'/R\) if \(G\) acts on \(R'\)
  and each \(g\in G\) is an \(R\)-map. Note that \(R'^G\) is an \(R\)-subalgebra

** Boolean rings label:sec1.2
  The simplest nonzero ring has two elements, 0 and 1. It's denoted \(\F_2\)


  Given any ring \(R\) and any set \(X\), let \(R^X\) denote the set of
  functions \(f:X\to R\). Then \(R^X\) is a ring.

  For example, take \(R:=\F_2\). Given \(f:X\to R\), put \(S:=f^{-1}\{1\}\).
  Then \(f(x)=1\) if \(x\in S\). In other words, \(f\) is the *characteristic
  function* \(\chi_S\). Thus /the characteristic functions form a ring, namely/, \(\F_2^X\)

  Given \(T\subset X\), clearly \(\chi_S\cdot\chi_T=\chi_{S\cap T}\).
  \(\chi_S+\chi_T=\chi_{S\triangle T}\), where \(S\triangle T\) is the
  *symmetric difference*:
  \begin{equation*}
  S\triangle T:=(S\cup T)-(S\cap T)
  \end{equation*}
  Thus /the subsets of \(X\) form a ring: sum is symmetric difference, and/
  /product is intersection. This ring is canonically isomorphic to \(\F_2^X\)/

  A ring \(B\) is called *Boolean* if \(f^2=f\) for all \(f\in B\). If so, then
  \(2f=0\) as \(2f=(f+f)^2=f^2+2f+f^2=4f\)

  Suppose \(X\) is a topological space, and give \(\F_2\) the *discrete*
  topology; that is, every subset is both open and closed. Consider the
  continuous functions \(f:X\to\F_2\). Clearly, they are just the \(\chi_S\)
  where \(S\) is both open and closed.

** Polynomial rings
   Let \(R\) be a ring, \(P:=R[X_1,\dots,X_n]\). \(P\) has this *Universal
   Mapping Property* (UMP): /given a ring map \(\varphi:R\to R'\) and given an/
   /element \(x_i\) of \(R'\) for each \(i\), there is a unique ring map/
   /\(\pi:P\to R'\) with \(\pi|R=\varphi\) and \(\pi(X_i)=x_i\)./ In fact, since
   \pi is a ring map, necessarily \pi is given by the formula:
   \begin{equation}
   \pi(\sum a_{(i_1,\dots,i_n)}X_1^{i_1}\dots X_n^{i_n})=\sum
   \varphi(a_{(i_1,\dots,i_n)})x_1^{i_1}\dots x_n^{i_n}\label{eq1.3.1}
   \end{equation}
   In other words, \(P\) is universal among \(R\)-algebras equipped with a list
   of \(n\) elements

   Similarly let \(\calx:=\{X_\lambda\}_{\lambda\in\Lambda}\) be any set of
   variables. Set \(P':=R[\calx]\); the elements of \(P'\) are the polynomials
   in any finitely many of the \(X_\lambda\). \(P'\) has essentially the same
   UMP as \(P\)

** Ideals
   Let \(R\) be a ring. A subset \(\fa\) is called an *ideal* if
   1. \(0\in\fa\)
   2. whenever \(a,b\in\fa\), also \(a+b\in\fa\)
   3. whenever \(x\in R\) and \(a\in\fa\) also \(xa\in\fa\)


   Given a subset \(\fa\subset R\), by the ideal \(\la\fa\ra\) that \(\fa\)
   *generates*, we mean the smallest ideal containing \(\fa\)

   All ideal containing all the \(a_\lambda\) contains any (finite) *linear
   combination* \(\sum x_\lambda a_\lambda\) with \(x_\lambda\in R\) and almost
   all 0.

   Given a single element \(a\), we say that the ideal \(\la a\ra\) is
   *principal*

   Given a number of ideals \(\fa_\lambda\), by their *sum* \(\sum\fa_\lambda\)
   we mean the set of all finite linear combinations \(\sum x_\lambda
   a_\lambda\) with \(x_\lambda\in R\) and \(a_\lambda\in\fa_\lambda\)

   Given two ideals \(\fa\) and \(\fb\), by the *transporter* of \(\fb\) into
   \(\fa\) we mean the set
   \begin{equation*}
   (\fa:\fb):=\{x\in R\mid x\fb\subset\fa\}
   \end{equation*}
   \((\fa:\fb)\)  is an ideal. Plainly,
   \begin{equation*}
   \fa\fb\subset\fa\cap\fb\subset\fa+\fb,\quad\fa,\fb\subset\fa+\fb,\quad
   \fa\subset(\fa:\fb)
   \end{equation*}
   Further, for any ideal \(\fc\), the distributive law holds:
   \(\fa(\fb+\fc)=\fa\fb+\fa\fc\)

   Given an ideal \(fa\), notice \(\fa=R\) /if and only if/ \(1\in\fa\). It
   follows that \(\fa=R\) iff \(\fa\) contains a unit.

   Given a ring map \(\varphi:R\to R'\), denote by \(\fa R'\) or \(\fa^e\) the
   ideal of \(R'\) generated by the set \(\varphi(\fa)\). We call it the
   *extension* of \(\fa\)

   Given an ideal \(\fa'\) of \(R'\), its preimage \(\varphi^{-1}(\fa')\) is an
   ideal of \(R\). We call \(\varphi^{-1}(\fa')\) the *contraction* of \(\fa'\)
   and sometimes denote it by \(\fa'^c\)

** Residue rings
   *kernel* \(\ker(\varphi)\) is defined to be the ideal \(\varphi^{-1}(0)\) of
   \(R\)

   Let \(\fa\) be an ideal of \(R\). Form the set of cosets of \(\fa\)
   \begin{equation*}
   R/\fa:=\{x+\fa\mid x\in R\}
   \end{equation*}
   \(R/\fa\) is called the *residure ring* or *quotient ring* or *factor ring* of
   \(R\) *modulo* \(\fa\). From the *quotient map*
   \begin{equation*}
   \kappa:R\to R/\fa\quad\text{ by }\kappa x:=x+\fa
   \end{equation*}
   The element \(\kappa x\in R/\fa\) is called the *residue* of \(x\).

   If \(\ker(\varphi)\supset\fa\), /then there is a ring map/ \(\psi:R/\fa\to R'\)
   /with/ \(\psi\kappa=\varphi\); that is, the following diagram is commutative

   #+BEGIN_center
   \begin{tikzcd}
   R\arrow[r,"\kappa"]\arrow[dr,"\varphi"]&R/\fa\arrow[d,"\psi"]\\
   &R'
   \end{tikzcd}
   #+END_center
   by \(\psi(x\fa)=\varphi(x)\). Then we only need to verify that \(\psi\) is a map
   
   Conversely, /if \psi exists, then/ \(\ker(\varphi)\supset\fa\), /or/
   \(\varphi\fa=0\), /or/ \(\fa R'=0\), since \(\kappa\fa=0\)

   Further, /if \psi exists, then \psi is unique/ as \(\kappa\) is surjective

   Finally, as \kappa is surjective, /if \psi exists, then \psi is surjective/
   /iff \psi is so/. In addition, \psi /is injective iff \(\fa=\ker(\varphi)\)/.
   Hence \psi /is an isomorphism iff \varphi is surjective and/
   \(\fa=\ker(\varphi)\). Therefore,
   \begin{equation*}
   R/\ker(\varphi)\xrightarrow{\sim}\im(\varphi)
   \end{equation*}

   \(R/\fa\) has UMP: \(\kappa(\fa)=0\), and given \(\varphi:R\to R'\) s.t.
   \(\varphi:R\to R'\) s.t. \(\varphi(\fa)=0\), there is a unique ring map
   \(\psi:R/\fa\to R'\) s.t. \(\psi\kappa=\varphi\). In other words, \(R/\fa\)
   is universal among \(R\)-algebras \(R'\) s.t. \(\fa R'=0\)

   If \(\fa\) is the ideal generated by elements \(a_\lambda\),then the UMP can
   be usefully rephrased as follows: \(\kappa(a_\lambda)=0\) for all \lambda,
   and given \(\varphi:R\to R'\) s.t. \(\varphi(a_\lambda)=0\) for all \lambda,
   there is a unique ring map \(\psi:R/\fa\to R'\) s.t. \(\psi\kappa=\varphi\)

   /The UMP serves to determine/ \(R/\fa\) /up to unique isomorphism/.
   Say \(R'\), equipped with \(\varphi:R\to R'\) has the UMP too.
   \(\kappa(\fa)=0\) so there is a unique \(\psi':R'\to R/\fa\) with
   \(\psi'\varphi=\kappa\). Then \(\psi'\psi\kappa=\kappa\). Hence
   \(\psi'\psi=1\) by uniqueness. Thus \(\psi\) and \(\psi'\) are inverse isomorphism
   #+BEGIN_center
   \begin{tikzcd}
   &&R/\fa\arrow[dd,"1"]\arrow[dl,"\psi"]\\
   R\arrow[urr,"\kappa"]\arrow[r,"\varphi"]\arrow[drr,"\kappa"]&
   R'\arrow[dr,"\psi'"]&\\
   &&R/\fa
   \end{tikzcd}
   #+END_center

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(R\) be a ring, \(P:=R[X]\), \(a\in R\) and \(\pi:P\to R\) the
   \(R\)-algebra map defined by \(\pi(X):=a\). Then
   1. \(\ker(\pi)=\{F(X)\in P\mid F(a)=0\}=\la X-a\ra\)
   2. \(R/\la X-a\ra\simeq R\)
   #+END_proposition

   #+BEGIN_proof
   Set \(G:=X-a\). Given \(F\in P\), let's show \(F=GH+r\) with \(H\in P\) and
   \(r\in R\). By linearity, we may assume \(F:=X^n\). If \(n\ge1\), then
   \(F=(G+a)X^{n-1}\), so \(F=GH+aX^{n-1}\) with \(H:=X^{n-1}\).

   Then \(\pi(F)=\pi(G)\pi(H)+\pi(r)=r\). Hence \(F\in\ker(\pi)\) iff \(F=GH\). But
   \(\pi(F)=F(a)\) by ref:eq1.3.1
   #+END_proof


** Degree of a polynomial
   Let \(R\) be a ring, \(P\) the polynomial ring in any number of variables.
   If \(F\) is a monomial \(\bM\), then its degree \(\deg(\bM)\) is the sum of
   its exponents; in general, \(\deg(F)\) is the largest \(\deg(\bM)\) of all
   monomials \(\bM\) in \(F\)

   Given any \(G\in P\) with \(FG\) nonzero, notice that
   \begin{equation*}
   \deg(FG)\le\deg(F)+\deg(G)
   \end{equation*}

** Order of a polynomial
   Let \(R\) be a ring, \(P\) the polynomial ring in variable \(X_\lambda\) for
   \(\lambda\in\Lambda\), and \((x_\lambda)\in R^\Lambda\) a vector. Let
   \(\varphi_{(x_\lambda)}:P\to P\) denote the \(R\)-algebra map defined by
   \(\varphi_{(x_\lambda)}X_\mu:=X_\mu+x_\mu\) for all \(\mu\in\Lambda\). Fix a
   nonzero \(F\in P\)

   The *order* of \(F\) at the zero vector \((0)\), denoted \(\ord_{(0)}F\), is
   defined as the smallest \(\deg(\bM)\) of all the monomials \(\bM\) in \(F\).
   In general, the *order* of \(F\) at the vector \((x_\lambda)\), denoted
   \(\ord_{(x_\lambda)}F\) is defined by the formula: \(\ord_{(x_\lambda)}F:=\ord_{(0)}(\varphi_{(x_\lambda)}F)\)

   Notice that \(\ord_{(x_\lambda)}F=0\) iff \(F(x_\lambda)\neq0\) as \((\varphi_{x_\lambda}F)(0)=F(x_\lambda)\)

   Given \mu and \(x\in R\), form \(F_{\mu,x}\) by substituting \(x\) for \(X_\mu\)
   in \(F\). If \(F_{\mu,x_\mu}\neq0\) , then
   \begin{equation*}
   \ord_{(x_\lambda)}F\le\ord_{(x_\lambda)}F_{\mu,x_\mu}\label{eq1.8.1}
   \end{equation*}
   If \(x_\mu=0\), then \(F_{\mu,x_\mu}\) is the sum of the terms without
   \(x_\mu\) in \(F\). Hence if \((x_\lambda)=(0)\), then ref:eq1.8.1 holds. But
   substituting 0 for \(X_\mu\) in \(\varphi_{(x_\lambda)}F\) is the same as
   substituting \(x_\mu\) for \(X_\mu\) in \(F\) and then applying
   \(\varphi_{(x_\lambda)}\) to the result; that is,
   \((\varphi_{(x_\mu)}F)_{\mu,0}=\varphi_{(x_\lambda)}F_{\mu,x_\mu}\)

   Given any \(G\in P\) with \(FG\) nonzero,
   \begin{equation*}
   \ord_{(x_\lambda)}FG\ge\ord_{(x_\lambda)}F+\ord_{(x_\lambda)}G
   \end{equation*}

** Nested ideals label:1.9
   Let \(R\) be a ring, \(\fa\) an ideal, and \(\kappa:R\to R/\fa\) the quotient map.
   Given an ideal \(\fb\supset\fa\), form the corresponding set of cosets of
   \(\fa\)
   \begin{equation*}
   \fb/\fa:=\{b+\fa\mid b\in\fb\}=\kappa(\fb)
   \end{equation*}
   Clearly, \(\fb/\fa\) is an ideal of \(R/\fa\). Also \(\fb/\fa=\fb(R/\fa)\)

   /The operation/ \(\fb\mapsto\fb/\fa\) /and/ \(\fb'\mapsto\kappa^{-1}(\fb')\) /are/
   /inverse to each other, and establish a bijective correspondence between the/
   /set of ideals \(\fb\) of \(R\) containing \(\fa\) and the set of all ideals/
   \(\fb'\) /of/ \(R/\fa\). /Moreover, this correspondence preserves inclusions/

   Given an ideal \(\fb\supset\fa\), form the composition of the quotient maps
   \begin{equation*}
   \varphi:R\to R/\fa\to (R/\fa)/(\fb/\fa)
   \end{equation*}
   \varphi is surjective and \(\ker(\varphi)=\fb\). Hence \varphi factors
   #+BEGIN_center
   \begin{tikzcd}
   R\arrow[r]\arrow[d]&R/\fb\arrow[d,"\psi","\simeq"']\\
   R/\fa\arrow[r]&(R/\fa)/(\fb/\fa)
   \end{tikzcd}
   #+END_center

** Idempotents
   Let \(R\) be a ring. Let \(e\in R\) be an *idempotent*; that is, \(e^2=e\).
   Then \(Re\) is a ring with \(e\) as 1.

   Set \(e':=1-e\). Then \(e'\) is idempotent and \(e\cdot e'=0\). We call \(e\)
   and \(e'\)  *complementary idempotents*. Conversely, if two elements
   \(e_1,e_2\in R\) satisfy \(e_1+e_2=1\) and \(e_1e_2=0\), then they are
   complementary idempotents, as for each \(i\),
   \begin{equation*}
   e_i=e_i\cdot 1=e_i(e_1+e_2)=e_i^2
   \end{equation*}
   We denote the set of all idempotents by \(\Idem(R)\). Let \(\varphi:R\to R'\)
   be a ring map. Then \(\varphi(e)\) is idempotent. So the restriction of
   \varphi to \(\Idem(R)\) is a map
   \begin{equation*}
   \Idem(\varphi):\Idem(R)\to\Idem(R')
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(R:=R'\times R''\) be a *product* of two rings. Set \(e':=(1,0)\) and
   \(e'':=(0,1)\). Then \(e'\) and \(e''\) are complementary idempotents.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(R\) be a ring, and \(e',e''\) complementary idempotents. Set
   \(R':=Re'\) and \(R'':=Re''\). Define \(\varphi:R\to R'\times R''\) by
   \(\varphi(x):=(xe',xe'')\). Then \varphi is a ring isomorphism. Moreover, \(R'=R/Re''\)
   and \(R''=R/Re'\)
   #+END_proposition

   #+BEGIN_proof
   Define a surjection \(\varphi':R\to R'\) by \(\varphi'(x):=xe'\). Then
   \(\varphi'\) is a ring map, since \(xye'=xye'^2=(xe')(ye')\). Moreover,
   \(\ker(\varphi')=Re''\) since \(x=x\cdot 1=xe'+xe''=xe''\). Thus
   \(R'=R/Re''\)

   Since \varphi is a ring map. It's surjective since \((xe',x'e'')=\varphi(xe'+x'e'')\)
   #+END_proof

** Exercise
   #+BEGIN_exercise
   label:ex1.13
   Let \(\varphi:R\to R'\) be a map of rings, \(\fa_1,\fa_2,\fa\) ideals of \(R\),
   \(\fb_1,\fb_2,\fb\) ideals of \(R'\). Prove
   1. \((\fa_1+\fa_2)^e=\fa_1^e+\fa_2^e\)
   2. \((\fb_1+\fb_2)^c\supset\fb_1^c+\fb_2^c\)
   3. \((\fa_1\cap\fa_2)^e\subset\fa_1^e\cap\fa_2^e\)
   4. \((\fb_1\cap\fb_2)^c=\fb_1^c\cap\fb_2^c\)
   5. \((\fa_1\fa_2)^e=\fa_1^e\fa_2^e\)
   6. \((\fb_1\fb_2)^c\supset\fb_1^c\fb_2^c\)
   7. \((\fa_1:\fa_2)^e\subset(\fa_1^e:\fa_2^e)\)
   8. \((\fb_1:\fb_2)^c\subset(\fb_1^c:\fb_2^c)\)
   #+END_exercise

   #+BEGIN_exercise
   label:ex1.14
   Let \(\varphi:R\to R'\) be a map of rings, \(\fa\) an ideal of \(R\), and \(\fb\)
   an ideal of \(R'\). Prove the following statements:
   1. \(\fa^{ec}\supset\fa\) and \(\fb^{ce}\subset\fb\)
   2. \(\fa^{ece}=\fa^e\) and \(\fb^{cec}=\fb^c\)
   3. If \(\fb\) is an extension, then \(\fb^c\) is the largest ideal of \(R\)
      with extension \(\fb\)
   4. If two extensions have the same contraction, then they are equal
   #+END_exercise

   #+BEGIN_exercise
   label:1.15
   Let \(R\) be a ring, \(\fa\) an ideal, \(\calx\) a set of variables. Prove:
   1. The extension \(\fa(R[\calx])\) is the set \(\fa[\calx]\)
   2. \(\fa(R[\calx])\cap R=\fa\)
   #+END_exercise

   #+BEGIN_exercise
   label:1.16
   Let \(R\) be a ring, \(\fa\) an ideal, and \(\calx\) a set of variables. Set
   \(P:=R[\calx]\). Prove \(P/\fa P=(R/\fa)[\calx]\)
   #+END_exercise

   #+BEGIN_exercise
   label:1.17
   Let \(R\) be a ring, \(P:=R[\{X_\lambda\}]\) the polynomial ring in variables
   \(X_\lambda\) for \(\lambda\in\Lambda\) a vector. Let
   \(\pi_{(x_\lambda)}:P\to R\) denote the \(R\)-algebra map defined by
   \(\pi_{(x_\lambda)}X_\mu:=x_\mu\) for all \(\mu\in\Lambda\). Show:
   1. Any \(F\in P\) has the form \(F=\sum
      a_{(i_1,\dots,i_n)}(X_{\lambda_1}^{i_1}-x_{\lambda_1})\dots
      (X_{\lambda_n}-x_{\lambda_n})^{i_n}\) for unique \(a_{(i_1,\dots,i_n)}\in R\)
   2. \(\ker(\pi_{(x_\lambda)})=\{F\in P\mid F((x_\lambda))=0\}=\la\{X_\lambda-x_\lambda\}\ra\)
   3. \pi induces an isomorphism \(P/\la\{X_\lambda-x_\lambda\}\ra\simeq R\)
   4. Given \(F\in P\), its residue in \(P/\la\{X_\lambda-x_\lambda\}\ra\) is
      equal to \(F((x_\lambda))\)
   5. Let \(\caly\) be a second set of variables. Then
      \(P[\caly]/\la\{X_\lambda-x_\lambda\}\ra\simeq R[\caly]\)
   #+END_exercise

   #+BEGIN_proof
   1. Let \(\varphi_{(x_\lambda)}\) be the \(R\)-automorphism of \(P\). Say
      \(\varphi_{(x_\lambda)}F=\sum a_{(i_1,\dots,i_n)}X_{\lambda_1}^{i_1}\dots
      X_{\lambda_n}^{i_n}\) . And \(\varphi_{(x_\lambda)}^{-1}\varphi_{(x_\lambda)}F=F\)
   2. Note that \(\pi_{(x_\lambda)}F=F((x_\lambda))\). Hence
      \(F\in\ker(\pi_{(x_\lambda)})\) iff \(F((x_\lambda))=0\). If
      \(F((x_\lambda))=0\), then \(a_{(0,\dots,0)}=0\), and so \(F\in\la\{X_\lambda-x_\lambda\}\ra\)
   5. [@5] Set \(R':=R[\caly]\)
   #+END_proof

   #+BEGIN_exercise
   label:ex.1.18
   Let \(R\) be a ring, \(P:=R[X_1,\dots,X_n]\) the polynomial ring in variables
   \(X_i\). Given \(F=\sum a_{(i_1,\dots,i_n)}X_1^{i_1}\dots X_n^{i_n}\in P\),
   formally set
   \begin{equation*}
   \partial F/\partial X_j:=\sum i_ja_{(i_1,\dots,i_n)}
   X_1^{i_i}\dots X_n^{i_n}/X_j\in P
   \end{equation*}
   Given \((x_1,\dots,x_n)\in R^n\), set \(\bx:=(x_1,\dots,x_n)\), set
   \(a_j:=(\partial F/\partial X_j)(\bx)\), and set
   \(\fM:=\la X_1-x_1,\dots,X_n-x_n\ra\). Show \(F=F(\bx)+\sum a_j(X_j-x_j)+G\)
   with \(G\in\fM^2\). First show that if
   \(F=(X_1-x_1)^{i_1}\dots(X_n-x_n)^{i_n}\), then \(\partial F/\partial X_j=i_jF/(X_j-x_j)\)
   #+END_exercise

   #+BEGIN_proof
   \((\partial F/\partial X_j)(\bx)=b_{(\delta_{1j},\dots,\delta_{nj})}\) where
   \(\delta_{ij}\) is the Kronecker delta
   #+END_proof

   #+BEGIN_exercise
   label:ex1.19
   Let \(R\) be a ring, \(X\) a variable, \(F\in P:=R[x]\), and \(a\in R\). Set
   \(F':=\partial F/\partial X\). We call \(a\) a *root* of \(F\) if \(F(a)=0\), a
   *simple root* if also \(F'(a)\neq0\), and a *supersimple root* if also \(F'(a)\)
   is a unit.

   Show that \(a\) is a root of \(F\) iff \(F=(X-a)G\) for some \(G\in P\), and
   if so, then \(G\) is unique; that \(a\) is a simple root iff also
   \(G(a)\neq0\); and that \(a\) is a supersimple root iff also \(G(a)\) is a unit
   #+END_exercise

   #+BEGIN_exercise
   label:ex1.20
   Let \(R\) be a ring, \(P:=R[X_1,\dots,X_n]\), \(F\in P\) of degree \(d\) and
   \(F_i:=X_i^{d_i}+a_1X_i^{d_i-1}+\dots\) a monic polynomial in \(X_i\) aloen
   for all \(i\). Find \(G,G_i\in P\) s.t. \(F=\sum_{i=1}^nF_iG_i+G\) where
   \(G_i=0\) or \(\deg(G_i)\le d-d_i\) and where the highest power of \(X_i\) in
   \(G\) is less than \(d_i\)
   #+END_exercise

   #+BEGIN_proof
   By linearity, we may assume \(F:=X_1^{m_1}\dots X_n^{m_n}\). If \(m_i<d_i\)
   for all \(i\), set \(G_i:=0\) and \(G:=F\) and we're done. Else, fix \(i\)
   with \(m_i\ge d_i\), and set \(G_i:=F/X_i^{d_i}\) and \(G:=(-a_1X_i^{d_i-1}-\dots)G_i\)
   #+END_proof

   #+ATTR_LATEX: :options [Chinese Remainder Theorem]
   #+BEGIN_exercise
   label:ex1.21
   Let \(R\) be a ring
   1. Let \(\fa\) and \(\fb\) be *comaximal* ideals; that is, \(\fa+\fb=R\). Show
      1. \(\fa\fb=\fa\cap\fb\)
      2. \(R/\fa\fb=(R/\fa)\times(R/\fb)\)
   2. Let \(\fa\) be comaximal to both \(\fb\) and \(\fb'\). Show \(\fa\) is
      also comaximal to \(\fb\fb'\)
   3. Given \(m,n\ge1\), show \(\fa\) and \(\fb\) are comaximal iff \(\fa^m\)
      and \(\fb^n\) are.
   4. Let \(\fa_1,\dots,\fa_n\) be pairwise comaximal. Show
      1. \(\fa_1\) and \(\fa_2\dots\fa_n\) are comaximal
      2. \(\fa_1\cap\dots\cap\fa_n=\fa_1\dots\fa_n\)
      3. \(R/(\fa_1\dots\fa_n)\simeq\prod(R/\fa_i)\)
   5. Find an example where \(\fa\) and \(\fb\) satisfy 1.1 but aren't comaximal
   #+END_exercise

   #+BEGIN_proof
   1. \(\fa+\fb=R\) implies \(x+y=1\) with \(x\in\fa\) and \(y\in\fb\). So given
      \(z\in\fa\cap\fb\), we have \(z=xz+yz\in\fa\fb\)
   2. \(R=(\fa+\fb)(\fa+\fb')=(\fa^2+\fb\fa+\fa\fb')+\fb\fb'\subseteq\fa+\fb\fb'\subseteq
      R\)
   3. Build with \(\fa+\fb^2=R\). Conversely, note that \(\fa^n\subset\fa\)
   4. Induction
   5. Let \(k\) be a field. Take \(R:=k[X,Y]\) and \(\fa:=\la X\ra\) and
      \(\fb:=\la Y\ra\). Given \(f\in\la X\ra\cap\la Y\ra\), note that every
      monomial of \(f\) contains both \(X\) and \(Y\), and so \(f\in\la X\ra\la
      Y\ra\). But \(\la X\ra\) and \(\la Y\ra\) are not comaximal
   #+END_proof

   #+BEGIN_exercise
   label:ex1.22
   First given a prime number \(p\) and a \(k\ge1\), find the idempotents in
   \(\Z/\la p^k\ra\). Second, find the idempotents in \(\Z/\la12\ra\). Third,
   find the number of idempotents in \(\Z/\la n\ra\) where
   \(n=\prod_{i=1}^Np_i^{n_i}\) with \(p_i\) distinct prime numbers
   #+END_exercise

   #+BEGIN_proof
   \(x=0,1\)

   Since \(-3+4=1\), the Chinese Remainder Theorem yields
   \begin{equation*}
   \Z/\la 12\ra=\Z/\la3\ra\times\Z/\la4\ra
   \end{equation*}
   \(m\) is idempotent in \(\Z/\la12\ra\) iff it's idempotent in \(\Z/\la3\ra\)
   and \(\Z/\la4\ra\)

   \(p_i^{n_i}\) has a linear combination equal to 1. Hence \(2^N\)
   #+END_proof

   #+BEGIN_exercise
   label:ex1.23
   Let \(R:=R'\times R''\) be a product of rings, \(\fa\subset R\) an ideal.
   Show \(\fa=\fa'\times\fa''\) with \(\fa'\subset R\) and \(\fa''\subset R''\)
   ideals. Show \(R/\fa=(R'/\fa')\times(R''/\fa'')\)
   #+END_exercise

   #+BEGIN_exercise
   label:ex1.24
   Let \(R\) be a ring; \(e,e'\) idempotents. Show
   1. Set \(\fa:=\la e\ra\). Then \(\fa\) is idempotent; that is, \(\fa^2=\fa\)
   2. Let \(\fa\) be a principal idempotent ideal. Then \(\fa=\la f\ra\) with
      \(f\) idempotent
   3. Set \(e'':=e+e'-ee'\). Then \(\la e,e'\ra=\la e''\ra\) and \(e''\) is
      idempotent
   4. Let \(e_1,\dots,e_r\) be idempotents. Then \(\la e_1,\dots,e_r\ra=\la
      f\ra\) with \(f\) idempotent
   5. Assume \(R\) is Boolean. Then every finitely generated ideal is principal
   #+END_exercise

   #+BEGIN_proof
   3. [@3] \(ee''=e^2=e\)
   #+END_proof

   #+BEGIN_exercise
   label:ex1.25
   Let \(L\) be a *lattice*, that is, a partially ordered set in which every pair
   \(x,y\in L\) has a sup \(x\vee y\) and an inf \(x\wedge y\). Assume \(L\) is
   *Boolean*; that is:
   1. \(L\) has a least element 0 and a greatest element 1
   2. The operations \(\vee\) and \(\wedge\) *distribute* over each other
      \begin{equation*}
      x\wedge(y\vee z)=(x\wedge y)\vee(x\wedge z)
      \quad\text{ and }\quad
      x\vee(y\wedge z)=(x\vee y)\wedge(x\vee z)
      \end{equation*}
   3. Each \(x\in L\) has a unique *complement* \(x'\); that is, \(x\wedge x'=0\)
      and \(x\vee x'=1\) .

      
   Show that the following six laws obeyed
   #+ATTR_LATEX: :align rclr
   | \(x\wedge x=x\)                          | and | \(x\vee x=x\)                    | *(idempotent)*  |
   | \(x\wedge0=0,x\wedge1=x\)                | and | \(x\vee1=1,x\vee0=x\)            | *(unitary)*     |
   | \(x\wedge y=y\wedge x\)                  | and | \(x\vee y=y\vee x\)              | *(commutative)* |
   | \(x\wedge(y\wedge z)=(x \wedge y)\wedge z\) | and | \(x\vee(y\vee z)=(x\vee y)\vee z\) | *(associative)* |
   | \(x''=x\)                                | and | \(0'=1,1'=0\)                    | *(involutory)*  |
   | \((x\wedge y)'=x'\vee y'\)               | and | \((x\vee y)'=x'\wedge y'\)       | *(De Morgan's)* |

   Moreover, show that \(x\le y\) iff \(x=x\wedge y\)
   #+END_exercise

   #+BEGIN_exercise
   label:ex1.26
   Let \(L\) be a Boolean lattice. For all \(x,y\in L\), set
   \begin{equation*}
   x+y:=(x\wedge y')\vee(x'\wedge y)\quad\text{ and }\quad
   xy:=x\wedge y
   \end{equation*}
   Show
   1. \(x+y=(x\vee y)(x'\vee y')\)
   2. \((x+y)'=(x'y')\vee(xy)\)
   3. \(L\) is a Boolean ring
   #+END_exercise

   #+BEGIN_exercise
   label:ex1.27
   Given a Boolean ring \(R\), order \(R\) by \(x\le y\) if \(x=xy\). Show \(R\)
   is thus a Boolean lattice. Viewing this construction as a map \rho from the set
   of Boolean-ring structures on the set \(R\) to the set of Boolean-lattice
   structures on \(R\), show \rho is bijective with inverse the map \lambda associated to
   the construction in ref:ex1.26
   #+END_exercise

   #+BEGIN_proof
   First check \(R\) is partially ordered.

   Given \(x,y\in R\), set \(x\vee y:=x+y+xy\) and \(x\wedge y:=xy\). Then
   \(x\le x\vee y\) as \(x(x+y+xy)=x^2+xy+x^2y=x+2xy=x\). If \(z\le x\) and
   \(z\le y\), then \(z=zx\) and \(z=zy\), and so \(z(x\vee y)=z\); thus \(z\le
   x\vee y\)
   #+END_proof

   #+BEGIN_exercise
   label:ex1.28
   Let \(X\) be a set, and \(L\) the set of all subsets of \(X\), partially
   ordered by inclusion. Show that \(L\) is a Boolean lattice and that the ring
   structure on \(L\) constructed in ref:sec1.2 coincides with that constructed
   in ref:ex1.26

   Assume \(X\) is a topological space, and let \(M\) be the set of all its open
   and closed subsets. Show that \(M\) is a sublattice of \(L\), and that the
   subring structure on \(M\) of ref:sec1.2 coincides with the ring structure of
   ref:ex1.26 with \(M\) for \(L\)
   #+END_exercise

* Prime Ideals

** Zerodivisors
   Let \(R\) be a ring. An element \(x\) is called a *zerodivisor* if there is a
   nonzero \(y\) with \(xy=0\); otherwise \(x\) is called a *nonzerodivisor*.
   Denote the set of zerodivisors by \(\zdiv(R)\) and the set of nonzerodivisor
   by \(S_0\)

** Multiplicative subsets, prime ideals
   Let \(R\) be a ring. A subset \(S\) is called *multiplicative* if \(1\in S\)
   and if \(x,y\in S\) implies \(xy\in S\)

   An ideal \(\fp\) is called *prime* if its complement \(R-\fp\) is
   multiplicative, or equivalently, if \(1\not\in\fp\) and if \(xy\in\fp\)
   implies \(x\in\fp\) or \(y\in\fp\)

** Fields, domains
   A ring is called a *field* if \(1\neq0\) and if every nonzero element is a
   unit.

   A ring is called an *integral domain*, or simply a *domain*, if \(\la0\ra\) is
   prime, or equivalently, if \(R\) is nonzero and has no nonzero zerodivisors.

   Every domain \(R\) is a subring of its *fraction field* \(\Frac(R)\).
   Conversely, any subring \(R\) of a field \(K\), including \(K\) itself, is a
   domain. Further, \(\Frac(R)\) has this UMP: the inclusion of \(R\) into any
   field \(L\) extends uniquely to an inclusion of \(\Frac(R)\) into \(L\).


** Polynomials over a domain
   Let \(R\) be a domain, \(\calx:=\{X_\lambda\}_{\lambda\in\Lambda}\) a set of
   variables. Set \(P:=R[\calx]\). Then \(P\) is a domain too. In fact, given
   nonzero \(F,G\in P\), not only is their product \(FG\) nonzero, but also given
   a well ordering of the variables, the grlex leading term of \(FG\) is the
   product of the grlex leading terms of \(F\) and \(G\), and
   \begin{equation*}
   \deg(FG)=\deg(F)+\deg(G)\label{eq2.4.1}
   \end{equation*}
   Using the given ordering of the variables, well order all the monomials
   \(\bM\) of the same degree via the lexicographic order on exponents. Among
   the \(\bM\) in \(F\) with \(\deg(\bM)=\deg(F)\), the largest is called the
   *grlex leading monomial* (graded lexicographic) of \(F\). Its *grlex leading
   term* is the product \(a\bM\) whre \(a\in R\) is the coefficient of \(\bM\) in
   \(F\), and \(a\) is called the *grlex leading coefficient*

   /The grlex leading term of \(FG\) is the product of those \(a\bM\) and/
   /\(b\bN\) of \(F\) and \(G\)/. and ref:eq2.4.1 holds, for the following
   reasons. First, \(ab\neq0\) as \(R\) is domain. Second
   \begin{equation*}
   \deg(\bM\bN)=\deg(\bM)+\deg(\bN)=\deg(F)+\deg(G)
   \end{equation*}
   Third, \(\deg(\bM\bN)\ge\deg(\bM'\bN')\) for every pair of monomials \(\bM'\)
   and \(\bN'\) in \(F\) and \(G\).

   /The grlex hind term of \(FG\) is the product of the grlex hind terms of/
   /\(F\) and \(G\)./ Further, given a vector \((x_\lambda)\in R^\Lambda\), then
   \begin{equation*}
   \ord_{(x_\lambda)}FG=\ord_{(x_\lambda)}F+\ord_{(x_\lambda)}G
   \end{equation*}
   Among the monomials \(\bM\) in \(F\) with \(\ord(\bM)=\ord(F)\), the smallest
   is called the *grlex hind monomial* of \(F\). The *grlex hind term* of \(F\) os
   the product \(a\bM\) where \(a\in R\) is the coefficient of \(\bM\) in \(F\)

   The fraction field \(\Frac(P)\) is called the field of *rational functions*,
   and is also denoted by \(K(\calx)\) where \(K:=\Frac(R)\)

** Unique factorization
   Let \(R\) be a domain, \(p\) a nonzero nonunit. We call \(p\) *prime* if
   whenever \(p\mid xy\), either \(p\mid x\) or \(p\mid y\).
   /\(p\) is prime iff \(\la p\ra\) is prime/

   We call \(p\) *irreducible* if whenever \(p=yz\), either \(y\) or \(z\) is a
   unit. We call \(R\) a *Unique Factorization Domain* (UFD) if
   1. every nonzero nonunit factors into a product of irreducibles
   2. the factorization is unique up to order and units.


   If \(R\) is a UFD, then \(\gcd(x,y)\) always exists

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(\varphi:R\to R'\) be a ring map, and \(T\subset R'\) a subset. If \(T\) is
   multiplicative, then \(\varphi^{-1}T\) is multiplicative; the converse holds if \varphi
   is surjective
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.7
   Let \(\varphi:R\to R'\) be a ring map, and \(\fq\subset R'\) an ideal. Set
   \(\fp:=\varphi^{-1}\fq\). If \(\fq\) is prime, then \(\fp\) is prime; the
   converse holds if \varphi is surjective
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(R\) be a ring, \(\fp\) an ideal. Then \(\fp\) is prime iff \(R/\fp\) is
   a domain
   #+END_corollary

   #+BEGIN_proof
   By Proposition ref:prop2.7, \(\fp\) is prime iff \(\la0\ra\subset R/\fp\) is
   #+END_proof

   #+BEGIN_exercise
   label:ex2.9
   Let \(R\) be a ring, \(P:=R[\calx,\caly]\) the polynomial ring in two sets of
   variables \(\calx\) and \(\caly\). Set \(\fp:=\la\calx\ra\). Show \(\fp\) is
   prime iff \(R\) is a domain
   #+END_exercise

   #+BEGIN_proof
   \(\fp\) is prime iff \(R[\caly]\) is a domain
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(R\) be a ring. An ideal \(\fm\) is said to be *maximal* if \(\fm\) is
   proper and if there is no proper ideal \(\fa\) with \(\fm\subsetneq\fa\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(R\) be a domain, \(R[X,Y]\) the polynomial ring. Then \(\la X\ra\) is
   prime. However, \(\la X\ra\) is not maximal since \(\la X\ra\subsetneq\la X,Y\ra\)
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:2.12
   A ring \(R\) is a field iff \(\la0\ra\) is a maximal ideal
   #+END_proposition

   #+BEGIN_proof
   If \(\la0\ra\) is  maximal. Take \(x\neq0\), then \(\la x\ra\neq0\). So \(\la
   x\ra=R\) and \(x\) is a unit.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:2.13
   Let \(R\) be a ring, \(\fm\) an ideal. Then \(\fm\) is maximal iff \(R/\fm\)
   is a field.
   #+END_corollary

   #+BEGIN_proof
   \(\fm\) is maximal iff \(\la0\ra\) is maximal in \(R/\fm\) by Correspondence Theorem.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(R\) be a ring, \(P\) the polynomial ring in variable \(X_\lambda\), and
   \(x_\lambda\in R\) for all \lambda. Set \(\fm:=\la\{X_\lambda-x_\lambda\}\ra\).
   Then \(P/\fm=R\) by Exercise ref:ex1.17. Thus \(\fm\) is maximal iff \(R\) is a field
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   In a ring, every maximal ideal is prime
   #+END_corollary

** Coprime elements label:2.16
   Let \(R\) be a ring and \(x,y\in R\). We say \(x\) and \(y\) are *(strictly)
   coprime* if their ideals \(\la x\ra\) and \(\la y\ra\) are comaximal

   Plainly, \(x\) and \(y\) are coprime iff there are \(a,b\in R\) s.t.
   \(ax+by=1\)

   Plainly, \(x\) and \(y\) are coprime iff there is \(b\in R\) with
   \(by\equiv1\mod\la x\ra\) iff the residue of \(y\) is a unit in \(R/\la x\ra\)

   Fix \(m,n\ge1\). By Exercise ref:ex1.21, \(x\) and \(y\) are coprim eiff
   \(x^m\) and \(x^n\) are.

   If \(x\) and \(y\) are coprime, then their images in algebra \(R'\) too.

** PIDs
   A domain \(R\) is called a *Principal Ideal Domain* (PID) if every ideal is
   principal. A PID is a UFD

   Let \(R\) be a PID, \(\fp\) a nonzero prime ideal. Say \(\fp=\la p\ra\). Then
   \(p\) is prime, so irreducible. Now let \(q\in R\) be irreducible. Then \(\la
   q\ra\) is maximal for: if \(\la q\ra\subsetneq\la x\ra\), then \(q=xy\) for
   some nonunit \(y\); so \(x\) must be a unit as \(q\) is irreducible. So
   \(R/\la q\ra\) is a field. Also \(\la q\ra\) is prime; so \(q\) is prime
   Thus every irreducible element is prime, and every
   nonzero prime ideal is maximal

   #+BEGIN_exercise
   label:2.18
   Show that, in a PID, nonzero elements \(x\) and \(y\) are *relatively prime*
   (share no prime factor) iff they are coprime
   #+END_exercise

   #+BEGIN_proof
   Say \(\la x\ra+\la y\ra=\la d\ra\). Then \(d=\gcd(x,y)\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(R\) be a PID, and \(p\in R\) a prime. Set \(k:=R/\la p\ra\). Let \(X\)
   be a variable, and set \(P:=R[X]\). Take \(G\in P\); let \(G'\) be its image
   in \(k[X]\); assume \(G'\) is irreducible. Set \(\fm:=\la p,G\ra\). Then
   \(P/\fm\simeq k[X]/\la G'\ra\) by ref:ex1.16 and ref:1.9 and \(k[X]/\la
   G'\ra\) is a field; hence
   \(\fm\) is maximal
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:2.20
   Let \(R\) be a PID. Let \(P:=R[X]\) and \(\fp\) a nonzero prime ideal of
   \(P\)
   1. \(\fp=\la F\ra\) with \(F\) prime or \(\fp\) is maximal
   2. Assume \(\fp\) is maximal. Then either \(\fp=\la F\ra\) with \(F\) prime,
      or \(\fp=\la p,G\ra\) with \(p\in R\) prime, \(pR=\fp\cap R\) and \(G\in
      P\) prime with image \(G'\in(R/pR)[X]\) prime
   #+END_theorem

   #+BEGIN_proof
   \(P\) is a UFD.

   If \(\fp=\la F\ra\) for some \(F\in P\), then \(F\) is prime. Assume \(\fp\)
   isn't principal

   Take a nonzero \(F_1\in\fp\). Since \(\fp\) is prime, \(\fp\) contains a
   prime factor \(F_1'\) of \(F_1\). Replace \(F_1\) by \(F_1'\). As \(\fp\)
   isn't principal, \(\fp\neq\la F_1\ra\). So there is a prime \(F_2\in\fp-\la
   F_1\ra\).
   Set \(K:=\Frac(R)\), Gauss's lemma implies that \(F_1\) and \(F_2\) are also
   prime in \(K[X]\). So \(F_1\) and \(F_2\) are relatively prime in \(K[X]\).
   So ref:2.18 yield \(G_1,G_2\in P\) and \(c\in P\) with
   \((G_1/c)F_1+(G_2/c)F_2=1\). So \(c=G_1F_1+G_2F_2\in R\cap\fp\). Hence
   \(R\cap\fp\neq0\). But \(R\cap\fp\) is prime, and \(R\) is a PID; so
   \(R\cap\fp=pR\) where \(p\) is prime. Also \(pR\) is maximal.

   Set \(k:=R/pR\). Then \(k\) is a field. Set \(\fq:=\fp/pR\subset k[X]\). Then
   \(k[X]/\fq=P/\fp\) by ref:1.9. But \(\fp\) is prime, so \(P/\fp\) is a
   domain. So \(k[X]/\fq\) is a domain too. So \(\fq\) is prime. So \(\fq\) is
   maximal. So \(\fp\) is maximal.

   Since \(k[X]\) is a PID and \(\fq\) is prime, \(\fq=\la G'\ra\) where \(G'\)
   is prime in \(k[X]\). Take \(G\in\fp\)  with image \(G'\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Every proper ideal \(\fa\) is contained in some maximal ideal
   #+END_theorem

   #+BEGIN_proof
   Set \(\cals:=\{\text{ideals }\fb\mid\fb\supset\fa\text{ and }\fb\not\ni1\}\).
   Then \(\fa\in\cals\) and \(\cals\) is partially ordered by inclusion. By
   Zorn's Lemma
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:2.22
   Let \(R\) be a ring, \(x\in R\). Then \(x\) is a unit iff \(x\) belongs to no
   maximal ideal
   #+END_corollary


** Exercise
   #+BEGIN_exercise
   label:2.23
   Let \(\fa\) and \(\fb\) be ideals, and \(\fp\) a prime ideal. Prove that
   these conditions are equivalent
   1. \(\fa\subset\fp\) or \(\fb\subset\fp\)
   2. \(\fa\cap\fb\subset\fp\)
   3. \(\fa\fb\subset\fp\)
   #+END_exercise

   #+BEGIN_exercise
   label:2.24
   Let \(R\)  be a  ring, \(\fp\) a prime ideal, and \(\fm_1,\dots,\fm_n\)
   maximal ideals. Assume \(\fm_1\dots\fm_n=0\). Show \(\fp=\fm_i\) for some \(i\)
   #+END_exercise

   #+BEGIN_proof
   Note \(\fp\supset0=\fm_1\dots\fm_n\). So \(\fp\supset\fm_1\) or
   \(\fp\supset\fm_2\dots\fm_n\) by ref:2.23
   #+END_proof

   #+BEGIN_exercise
   label:2.25
   Let \(R\) be a ring, and \(\fp,\fa_1,\dots,\fa_n\) ideals with \(\fp\) prime
   1. Assume \(\fp\supset\bigcap_{i=1}^n\fa_i\). Show \(\fp\supset\fa_j\) for
      some \(j\)
   2. Assume \(\fp=\bigcap_{i=1}^n\fa_i\). Show \(\fp=\fa_j\) for some \(j\)
   #+END_exercise

   #+BEGIN_exercise
   label:2.26
   Let \(R\) be a ring, \(\cals\) the set of all ideals that consist entirely of
   zerodivisors. Show that \(\cals\) has maximal elements and they're prime.
   Conclude that \(\zdiv(R)\) is a union of primes.
   #+END_exercise

   #+BEGIN_proof
   Order \(\cals\) by inclusion. \(\cals\) is not empty. \(\cals\) consists of a
   maximal element \(\fp\).

   Given \(x,x'\in R\) with \(xx'\in\fp\), but \(x,x'\not\in\fp\). Hence \(\la
   x\ra+\fp,\la x'\ra+\fp\not\in\cals\). So there are \(a,a'\in R\) and
   \(p,p'\in\fp\)  s.t. \(y:=ax+p\) and \(y':=a'x'+p'\) are not zerodivisors. Then
   \(yy'\in\fp\). So \(yy'\in\zdiv(R)\), a contradiction. Thus \(\fp\) is prime.

   Given \(x\in\zdiv(R)\), note \(\la x\ra\in\cals\). So \(\la x\ra\) lies in a
   maximal element \(\fp\) of \(\cals\). Thus \(x\in\fp\) and \(\fp\) is prime
   #+END_proof

   #+BEGIN_exercise
   label:2.27
   Given a prime number \(p\) and an integer \(n\ge2\), prove that the residue
   ring \(\Z/\la p^n\ra\) does not contain a domain as a subring
   #+END_exercise

   #+BEGIN_proof
   Any subring of \(\Z/\la p^n\ra\) must contain 1, and \(1\) generates \(\Z/\la
   p^n\ra\) as an Abelian group. So \(\Z/\la p^n\ra\) contains no proper subrings.
   #+END_proof

   #+BEGIN_exercise
   label:2.28
   Let \(R:=R'\times R''\) be a product of two rings. Show that \(R\) is a
   domain if and only if either \(R'\) or \(R''\) is a domain and the other 0
   #+END_exercise

   #+BEGIN_proof
   Assume \(R\) is a domain. As \((1,0)\cdot(0,1)=(0,0)\), either \(R'\) or
   \(R''\) is 0.
   #+END_proof

   #+BEGIN_exercise
   label:2.29
   Let \(R:=R'\times R''\) be a product of rings, \(\fp\subset R\) an ideal.
   Show \(\fp\) is prime iff either \(\fp=\fp'\times R''\) with \(\fp'\subset
   R'\) prime or \(\fp=R'\times\fp''\) with \(\fp''\subset R''\) prime
   #+END_exercise

   #+BEGIN_proof
   \(1\in\fp\). \((1,0)(0,1)\in\fp\). Hence \((1,0)\in\fp\) or \((0,1)\in\fp\).
   #+END_proof

   #+BEGIN_exercise
   label:2.30
   Let \(R\) be a domain, and \(x,y\in R\). Assume \(\la x\ra=\la y\ra\). Show
   \(x=uy\) for some unit \(u\)
   #+END_exercise

   #+BEGIN_proof
   \((1-tu)y=0\) and domain
   #+END_proof

   #+BEGIN_exercise
   label:2.31
   Let \(k\) be a field, \(R\) a nonzero ring, \(\varphi:k\to R\) a ring map. Prove \varphi
   is injective
   #+END_exercise

   #+BEGIN_proof
   Since \(1\neq0\), \(\ker(\varphi)\neq k\). And by ref:2.12, \(\ker(\varphi)=0\) and hence
   \varphi is injective
   #+END_proof

   #+BEGIN_exercise
   label:2.32
   Let \(R\) be a ring, \(\fp\) a prime, \(\calx\) a set of variables. Let
   \(\fp[\calx]\) denote the set of polynomials with coefficients in \(\fp\).
   Prove
   1. \(\fp R[\calx]\) and \(\fp[\calx]\) and \(\fp R[\calx]+\la\calx\ra\) are
      primes of \(R[\calx]\), which contract to \(\fp\)
   2. Assume \(\fp\) is maximal. Then \(\fp R[\calx]+\la\calx\ra\) is maximal
   #+END_exercise

   #+BEGIN_proof
   1. \(R/\fp\) is a domain. \(\fp R[\calx]=\fp[\calx]\) by ref:1.15.

      \((\fp R[\calx]+\la\calx\ra/\fp R[\calx])\) is equal to
      \(\la\calx\ra\subset(R/\fp)[\calx]\). \((R/\fp)\la\calx\ra/\la\calx\ra\)
      is equal to \(R/\fp\). Hence
      \(R[X]/(\fp R[\calx]+\la\calx\ra)=(R[x]/\fp R[X])/((\fp
      R[\calx]+\la\calx\ra)/\fp R[X])=R/\fp\)

      Since the canonical map \(R/\fp\to R[\calx]/(\fp R[\calx]+\la\calx\ra)\)
      is bijective, it's injective.

   2. \(R/\fp\simeq R[\calx]/(\fp R[\calx]+\la\calx\ra)\)
   #+END_proof

   #+BEGIN_exercise
   label:2.33
   Let \(R\) be a ring, \(X\) a variable, \(H\in P:=R[X]\) and \(a\in R.\)Given
   \(n\ge1\), show \((X-a)^n\) and \(H\) are coprime iff \(H(a)\) is a unit.
   #+END_exercise

   #+BEGIN_proof
   \((X-a)^n\) and \(H\) are coprime iff \(X-a\) and \(H\) are coprime.
   \(R[x]/\la X-a\ra=\la H\ra/\la X-a\ra\), which implies the residue of \(H\)
   modulo \(X-a\) is a unit. Hence \(H(a)\) is a unit.
   #+END_proof

   #+BEGIN_exercise
   label:2.34
   Let \(R\) be a ring, \(X\) a variable, \(F\in P:=R[X]\), and \(a\in R\). Set
   \(F':=\partial F/\partial X\). Show the following statements are equivalent
   1. \(a\) is a supersimple root of \(F\)
   2. \(a\) is a root of \(F\), and \(X-a\) and \(F'\) are coprime
   3. \(F=(X-a)G\) for some \(G\) in \(P\) coprime to \(X-a\)


   Show that if (3) holds, then \(G\) is unique
   #+END_exercise

   #+BEGIN_exercise
   label:2.35
   Let \(R\) be a ring, \(\fp\) a prime; \(\calx\) a set of variables; \(F,G\in
   R[\calx]\). Let \(c(F)\), \(c(G)\), \(c(FG)\) be the ideals of \(R\)
   generated by the coefficients of \(F,G,FG\)
   1. Assume \(\fp\) doesn't contain either \(c(F)\) or \(c(G)\). Show \(\fp\)
      doesn't contain \(c(FG)\)
   2. Assume \(c(F)=R\) and \(c(G)=R\). Show \(c(FG)=R\)
   #+END_exercise

   #+BEGIN_proof
   1. Denote the residues of \(F,G,FG\)  in \((R/\fp)[\calx]\) by
      \(\overbar{F}\), \(\overbar{G}\) and \(\overbar{FG}\). Since
      \(\fp\not\supset c(F),c(G)\), \(\overbar{F},\overbar{G}\neq0\). Since
      \(R/\fp\) is a domain, so is \((R/\fp)[\calx]\) and we have
      \(\overbar{F}\overbar{G}\neq0\). Note that
      \(\overbar{F}\overbar{G}=\overbar{FG}\), we have \(\overbar{FG}\neq0\).
   2. Assume \(c(F)=c(G)=R\), since \(\fp\not\supset c(F),c(G)\) we have
      \(\fp\not\supset c(FG)\) for any prime ideals \(\fp\). Hence \(c(FG)=R\).

      If \(c(FG)=R\), \(c(FG)\subset c(F)\)
   #+END_proof

   #+BEGIN_exercise
   label:2.36
   Let \(B\) be a Boolean ring. Show that every prime \(\fp\) is maximal, and
   that \(B/\fp=\F_2\)
   #+END_exercise

   #+BEGIN_proof
   \(x(x-1)=0\) in \(B/\fp\). Since \(B/\fp\) is a domain, \(x=0\) or \(x=1\).
   #+END_proof

   #+BEGIN_exercise
   label:2.37
   Let \(R\) be a ring. Assume that, given any \(x\in R\), there is an
   \(n\ge2\) with \(x^n=x\). Show that every prime \(\fp\) is maximal
   #+END_exercise

   #+BEGIN_proof
   Same. Every element has an inverse
   #+END_proof

   #+BEGIN_exercise
   label:2.38
   Prove the following statements or give a counterexample
   1. The complement of a multiplicative subset is a prime ideal
   2. Given two prime ideals, their intersection is prime
   3. Given two prime ideals, their sum is prime
   4. Given a ring map \(\varphi:R\to R'\), the operation \(\varphi^{-1}\) carries maximal
      ideals of \(R'\) to maximal ideals of \(R\)
   5. An ideal \(\fm'\subset R/\fa\) is maximal iff \(\kappa^{-1}\fm'\subset R\) is
      maximal in ref:1.9

   #+END_exercise

   #+BEGIN_proof
   1. 0 can be belongs to the multiplicative subset
   2. False. In \(\Z\), \(\la2\ra\cap\la3\ra=\la6\ra\)
   3. False. In \(\Z\), \(\la2\ra+\la3\ra=\Z\)
   4. False. Consider \(\varphi:\Z\to\Q\). \(\varphi^{-1}(\la0\ra)=\la0\ra\)
   5. 
   #+END_proof

* Radicals
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(R\) be a ring. Its (Jacobson) *radical* \(\rad(R)\) is defined to be the
  intersection of all its maximal ideals
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:3.2
  Let \(R\) be a ring, \(\fa\) an ideal, \(x\in R,u\in R^\times\). Then
  \(x\in\rad(R)\) iff \(u-xy\in R^\times\) for all \(x\in R\). In particular,
  the sum of an element of \(\rad(R)\) and a unit is a unit, and
  \(\fa\subset\rad(R)\) if \(1-\fa\in R^\times\)
  #+END_proposition

  #+BEGIN_proof
  Assume \(x\in\rad(R)\). Given a maximal ideal \(\fm\), suppose \(u-xy\in\fm\).
  Since \(x\in\fm\) too, also \(u\in\fm\), a contradiction. Thus \(u-xy\) is a
  unit by ref:2.22. In particular, tkaing \(y:=-1\) yields \(u+x\in R^\times\)

  Conversely, assume \(x\not\in\rad(R)\). Then there is a maximal ideal \(\fm\)
  with \(x\not\in\fm\). So \(\la x\ra+\fm=R\). Hence there exists \(y\in R\) and
  \(m\in\fm\) s.t. \(xy+m=u\). Then \(u-xy=m\in\fm\). A contradiction

  In particular, given \(y\in R\), set \(a:=u^{-1}xy\). Then \(u-xy=u(1-a)\in
  R^\times\) if \(1-a\in R^\times\)
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  label:3.3
  Let \(R\) be a ring, \(\fa\) an ideal, \(\kappa:R\to R/\fa\) the quotient map.
  Assume \(\fa\subset\rad(R)\). Then \(\Idem(\kappa)\) is injective
  #+END_corollary

  #+BEGIN_proof
  Given \(e,e'\in\Idem(R)\) with \(\kappa(e)=\kappa(e')\), set \(x:=e-e'\). Then
  \begin{equation*}
  x^3=e-e'=x
  \end{equation*}
  Hence \(x(1-x^2)=0\). But \(\kappa(x)=0\); so \(x\in\fa\). But
  \(\fa\subset\rad(R)\). Hence \(1-x^2\) is a unit by ref:3.2. Thus \(x=0\).
  Thus \(\Idem(\kappa)\) is injective
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A ring is called *local* if it has exactly one maximal ideal, and *semilocal* if
  it has at least one and at most finitely many

  By the *residue field* of a local ring \(A\), we mean the field \(A/\fm\) where
  \(\fm\) is the maximal ideal of \(A\)
  #+END_definition

  #+ATTR_LATEX: :options [Nonunit Criterion]
  #+BEGIN_lemma
  label:3.5
  Let \(A\) be a ring, \(\fn\) the set of nonunits. Then \(A\) is local iff
  \(\fn\) is an ideal; if so, then \(\fn\) is the maximal ideal
  #+END_lemma

  #+BEGIN_proof
  Assume \(A\) is local with maximal ideal \(\fm\). Then \(A-\fn=A-\fm\) by
  ref:2.22. Thus \(\fn\) is an ideal
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_examplle
  The product ring \(R'\times R''\) is not local by ref:3.5 if both \(R'\) and
  \(R''\) are nonzero. \((1,0)\) and \((0,1)\) are nonunits, but their sum is a unit.
  #+END_examplle

  #+ATTR_LATEX: :options []
  #+BEGIN_examplle
  Let \(R\) be a ring. A *formal power series* in the \(n\) variables
  \(X_1,\dots,X_n\) is a formal /infinite/ sum of the form \(\sum
  a_{(i)}X_1^{i_1}\dots X_n^{i_n}\) where \(a_{(i)}\in R\) and where
  \((i):=(i_1,\dots,i_n)\) with each \(i_j\ge0\). The term \(a_{(0)}\) where
  \((0):=(0,\dots,0)\) is called the *constant term*. Addition and multiplication
  are performed as for polynomials; with these operations, these series form a
  ring \(R[[X_1,\dots,X_n]]\)

  Set \(P:=R[[X_1,\dots,X_n]]\) and \(\fa:=\la X_1,\dots,X_n\ra\). Then \(\sum
  a_{(i)}X_1^{i_1}\dots X_n^{i_n}\mapsto a_{(0)}\) is a canonical surjective
  ring map \(P\to R\) with kernel \(\fa\); hence \(P/\fa=R\)

  Given an ideal \(\fm\subset R\), set \(\fn:=\fa+\fm P\). Then ref:1.9 yields
  \(P/\fn=R/\fm\)

  A power series \(F\) is a unit iff its constant term is a unit. If \(a_{(0)}\)
  is a unit, then \(F=a_{(0)}(1-G)\) with \(G\in\fa\). Set
  \(F':=a_{(0)}^{-1}(1+G+G^2+\dots)\);

  Suppose \(R\) is a local ring with maximal ideal \(\fm\). Given a power series
  \(F\not\in\fn\), its constant term lies outside \(\fm\), so is a unit. So
  \(F\) is itself a unit. Hence the nonunits constitutes \(\fn\). Thus \(P\) is
  local.
  #+END_examplle

  #+ATTR_LATEX: :options []
  #+BEGIN_examplle
  Let \(k\) be a ring, and \(A:=k[[X]]\) the formal power series ring in one
  variables. A *formal Laurent series* is a formal sum of the form
  \(\sum_{i=-m}^\infty a_iX^i\) with \(a_i\in k\) and \(m\in\Z\). Plainly, these
  seires form a ring \(k\{\{X\}\}\). Set \(K:=k\{\{X\}\}\)

  Set \(F:=\sum_{i=-m}^\infty a_iX^i\). If \(a_{-m}\in k^\times\), then \(F\in
  K^\times\); indeed, \(F=a_{-m}X^{-m}(1-G)\) where \(G\in A\) and

  Assume \(k\) is a field. If \(F\neq0\), then \(F=X^{-m}H\) with
  \(H:=a_{-m}(1-G)\in A^\times\). Let \(\fa\subset A\) be a nonzero ideal.
  Suppose \(F\in\fa\). Then \(X^{-m}\in\fa\). Let \(n\) be the smallest integer
  s.t. \(X^n\in\fa\). Then \(-m\ge n\). Set \(E:=X^{-m-n}H\). Then \(E\in A\)
  and \(F=X^nE\). Hence \(\fa=\la X^n\ra\). Thus \(A\) *is a* PID

  Further, \(K\) is a field. In fact, \(K=\Frac(A)\).

  Let \(A[Y]\) be the polynomial ring in one variable, and \(\iota:A\hookrightarrow
  K\) the inclusion.
  Define \(\varphi:A[Y]\to K\) by \(\varphi|A=\iota\) and \(\varphi(Y)=X^{-1}\). Then \varphi is
  surjective. Set \(\fm:=\ker(\varphi)\). Then \(\fm\) is maximal. So by ref:2.20
  \(\fm\) has the form \(\la F\ra\) with \(F\) irreducible, or the form \(\la
  p,G\ra\) with \(p\in A\) irreducible and \(G\in A[Y]\). But \(\fm\cap
  A=\la0\ra\) as \iota is injective. So \(\fm=\la F\ra\). But \(XY-1\) belongs to
  \(\fm\), and is clearly irreducible; hence \(XY-1=FH\) with \(H\) a unit. Thus
  \(\la XY-1\ra\) is maximal

  In addition, \(\la X,Y\ra\) is maximal. Indeed, \(A[Y]/\la X,Y\ra=A/\la
  X\ra=k\). Howevery ,\(\la X,Y\ra\) is not principal, as no nonunit of \(A[Y]\)
  divides both \(X\) and \(Y\). Thus \(A[Y]\) /has both principal and
  nonprincipal maximal ideals, two types allows by ref:2.20/
  #+END_examplle

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:3.9
  Let \(R\) be a ring, \(S\) a multiplicative subset, and \(\fa\) an ideal with
  \(\fa\cap S=\emptyset\). Set \(\cals:=\{\text{ideals
  }\fb\mid\fb\supset\fa\text{ and }\fb\cap S=\emptyset\}\). Then \(\cals\) has a
  maximal element \(\fp\), and every such \(\fp\) is prime
  #+END_proposition

  #+BEGIN_proof
  Take \(x,y\in R-\fp\). Then \(\fp+\la x\ra\) and \(\fp+\la y\ra\) are strictly
  larger than \(\fp\). So there are \(p,q\in\fp\) and \(a,b\in R\) with
  \(p+ax,q+by\in S\). Hence \(pq+pby+qax+abxy\in S\). But \(pq+pby+qax\in\fp\),
  so \(xy\not\in\fp\). Thus \(\fp\) is prime
  #+END_proof

  #+BEGIN_exercise
  label:3.10
  Let \(\varphi:R\to R'\) be a ring map, \(\fp\) an ideal of \(R\). Show
  1. there is an ideal \(\fq\) of \(R'\) with \(\varphi^{-1}(\fq)=\fp\) iff
     \(\varphi^{-1}(\fp R')=\fp\)
  2. if \(\fp\) is prime with \(\varphi^{-1}(\fp R')=\fp\), then there is a prime
     \(\fq\) of \(R'\) with \(\varphi^{-1}(\fq)=\fp\)
  #+END_exercise

** Saturated multiplicative subsets
   Let \(R\) be a ring, and \(S\) a multiplicative subset. We say \(S\) is
   *saturated* if given \(x,y\in R\) with \(xy\in S\), necessarily \(x,y\in S\)

   #+ATTR_LATEX: :options [Prime Avoidance]
   #+BEGIN_lemma
   Let \(R\) be a ring, \(\fa\) a subset of \(R\) that is stable under addition
   and multiplication, and \(\fp_1,\dots,\fp_n\) ideals s.t.
   \(\fp_3,\dots,\fp_n\) are prime. If \(\fa\not\subset\fp_j\) for all \(j\),
   then there is an \(x\in\fa\) s.t. \(x\not\in\fp_j\) for all \(j\); or
   equivalently, if \(\fa\subset\bigcup_{i=1}^n\fp_i\), then \(\fa\subset\fp_i\)
   for some \(i\)
   #+END_lemma

   #+BEGIN_proof
  Assume there is an \(x_i\in\fa\) s.t. \(x_i\not\in\fp_j\) for all
   \(i\neq j\)and \(x_i\in\fp_i\) for every \(i\). If \(n=2\) then clearly
   \(x_1+x_2\not\in\fp_j\) for \(j=1,2\). If \(n\ge3\), then \((x_1\dots
   x_{n-1})+x_n\not\in\fp_j\) for all \(j\) as, if \(j=n\), then \(x_n\in\fp_n\)
   and \(\fp_n\) is prime.
   #+END_proof

** Other radicals
   Let \(R\) be a ring, \(\fa\) a subset. Its *radical* \(\sqrt{\fa}\) is the set
   \begin{equation*}
   \sqrt{\fa}:=\{x\in R\mid x^n\in\fa\text{ for some }n\ge1\}
   \end{equation*}
   If \(\fa\) is an ideal and \(\fa=\sqrt{\fa}\), then \(\fa\) is said to be
   *radical*. For example, suppose \(\fa=\bigcap\fp_\lambda\) with all
   \(\fp_\lambda\) prime. If \(x^n\in\fa\) for some \(n\ge1\), then
   \(x\in\fp_\lambda\). Thus \(\fa\) is radical. Hence two radicals coincide

   We call \(\sqrt{\la0\ra}\) the *nilradical*, and sometimes denote it by
   \(\nil(R)\). We call an element \(x\in R\) *nilpotent* if \(x\) belongs to
   \(\sqrt{\la0\ra}\). We call an ideal \(\fa\) *nilpotent* if \(\fa^n=0\) for
   some \(n\ge1\)

   \(\la0\ra\subset\rad(R)\). So \(\sqrt{\la0\ra}\subset\sqrt{\rad(R)}\). Thus
   \begin{equation*}
   \nil(R)\subset\rad(R)
   \end{equation*}
   We call \(R\) *reduced* if \(\nil(R)=\la0\ra\)

   #+ATTR_LATEX: :options [Scheinnullstellensatz]
   #+BEGIN_theorem
   label:3.14
   Let \(R\) be a ring, \(\fa\) an ideal. Then
   \begin{equation*}
   \sqrt{\fa}=\bigcap_{\fp\supset\fa}\fp
   \end{equation*}
   where \(\fp\) runs through all the prime ideals containing \(\fa\). (By
   convention, the empty intersection is equal to \(R\))
   #+END_theorem

   #+BEGIN_proof
   Take \(x\not\in\sqrt{\fa}\). Set \(S:=\{1,x,x^2,\dots\}\). Then \(S\) is
   multiplicative, and \(\fa\cap S=\emptyset\). By ref:3.9 there is a
   \(\fp\supset\fa\), but \(x\not\in\fp\), but \(x\not\in\fp\). So
   \(x\not\in\bigcap_{\fp\supset\fa}\fp\). Thus
   \(\sqrt{\fa}\supset\bigcap_{\fp\supset\fa}\fp\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:3.15
   Let \(R\) be a ring, \(\fa\) an ideal. Then \(\sqrt{\fa}\) is an ideal
   #+END_proposition

   #+BEGIN_proof
   Assume \(x^n,y^m\in\fa\). Then
   \begin{equation*}
   (x+y)^{m+n-1}=\sum_{i+j=m+n-1}\binom{n+m-1}{j}x^iy^j
   \end{equation*}
   Thus \(x+y\in\fa\)

   Alternatively by ref:3.14
   #+END_proof

   #+BEGIN_exercise
   label:3.16
   Use Zorn's lemma to prove that any prime ideal \(\fp\) contains a prime ideal
   \(\fq\) that is minimal containing any given subset \(\fs\subset\fp\)
   #+END_exercise

** Minimal primes label:3.17
   Let \(R\) be a ring, \(\fa\) an ideal, \(\fp\) a prime. We call \(\fp\) a
   *minimal prime* of \(\fa\), or over \(\fa\), if \(\fp\) is minimal in the set
   of primes containing \(\fa\). We call \(\fp\) a *minimal prime* of \(R\) if
   \(\fp\) is a minimal prime of \(\la0\ra\)

   Owing to ref:3.16, every prime of \(R\) containing \(\fa\) contains a minimal
   prime of \(\fa\). So owing to the Scheinnullstellensatz ref:3.14, the radical
   \(\sqrt{\fa}\) is the intersection of all the minimal primes of \(\fa\).

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A ring \(R\) is reduced and has only one minimal prime if and only if \(R\)
   is a domain
   #+END_proposition

   #+BEGIN_proof
   ref:3.17 implies \(\la0\ra=\fq\)
   #+END_proof

   #+BEGIN_exercise
   label:3.19
   Let \(R\) be a ring, \(\fa\) an ideal, \(X\) a variable, \(R[[X]]\) the formal
   power series ring, \(\fM\subset R[[X]]\) an ideal, \(F:=\sum a_nX_n\in R[[X]]\). Set
   \(\fm:=\fM\cap R\) and \(\fA:=\{\sum b_nX^n\mid b_n\in\fa\}\). Prove the
   following statements:
   1. If \(F\) is a nilpotent, then \(a_n\) is nilpotent for all \(n\). The
      converse is false
   2. \(F\in\rad(R[[X]])\) iff \(a_0\in\rad(R)\)
   3. Assume \(X\in\fM\). Then \(X\) and \(\fm\) generate \(\fM\)
   4. Assume \(\fM\) is maximal. Then \(X\in\fM\) and \(\fm\) is maximal
   5. If \(\fa\) is finitely generated, then \(\fa R[[X]]=\fA\). However, there's an
      example of an \(R\) with a prime ideal \(\fa\) s.t. \(\fa R[[X]]\neq\fA\)
   #+END_exercise

   #+BEGIN_proof
   1. Assume \(F\) and \(a_i\) for \(i<n\) nilpotent. Set \(G:=\sum_{i\ge
      n}a_iX^i\). Then \(G=F-\sum_{i<n}a_iX^i\). So \(G\) is nilpotent by
      ref:3.15; say \(G^m=0\) for some \(m\ge1\). Then \(a^m_n=0\)

      Set \(P:=\Z[X_2,X_3,\dots]\). Set \(R:=P/\la X_2^2,X_3^3,\dots\ra\). Let
      \(a_n\) be the residue of \(X_n\). Then \(a^n_n=0\), but \(\sum a_nX^n\)
      is not nilpotent.

   2. By ref:3.2, suppose \(G=\sum b_iX^i\)
      \begin{equation*}
      \(F\in\rad(R[[X]])\)\Longleftrightarrow 1+FG\in R[[X]]^\times
      \Longleftrightarrow 1+a_0b_0\in R^\times\Longleftrightarrow
      a_0\in\rad(R)
      \end{equation*}

   5. [@5] Take \(R:=\Z[a_1,a_2,\dots]\) and \(\fa:=\la a_1,\dots\ra\). Then
      \(R/\fa=\Z\) and \(\fa\) is prime.

      Given \(G\in\fa R[[X]]\), say \(G=\sum_{i=1}^mb_iG_i\) with \(b_i\in\fa\) and
      \(G_i=\sum_{n\ge0}b_{in}X^n\) and \(F\neq G\) for any \(m\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(R\) be a ring, \(R[[X]]\) the formal power series ring. Then every prime
   \(\fp\) of \(R\) is the contraction of a prime of \(R[[X]]\). Indeed \(\fp R[[X]]\cap
   R=\fp\). So by ref:3.10 there is a prime \(\fq\) of \(R[[X]]\) with \(\fq\cap
   R=\fp\). In fact ,a specific choice for \(\fq\) is the set of series \(\sum
   a_nX^n\) with \(a_n\in\fq\). Indeed, the canonical map \(R\to R/\fp\) induces
   a surjection \(R[[X]]\to(R/\fp)[[X]]\) with kernel \(\fq\); so \(R[[X]]/\fq=(R/\fp)[[X]]\).
   But ref:3.19 shows \(\fq\) may not be equal to \(\fp R[[X]]\)
   #+END_examplle

** Exercise
   #+BEGIN_exercise
   label:3.21
   Let \(R\) be a ring, \(\fa\subset\rad(R)\) an ideal, \(w\in R\) and \(w'\in
   R/\fa\) its residue. Prove that \(w\in R^\times\) iff
   \(w'\in(R/\fa)^\times\). What if \(\fa\not\subset\rad(R)\)?
   #+END_exercise

   #+BEGIN_proof
   Assume \(\fa\subset\rad(R)\). \(\fm\mapsto\fm/\fa\) is a bijection for
   maximal ideal \(\fm\). So \(w\) belongs to a maximal ideal of \(R\) iff \(w'\) belongs
   to one of \(R/\fa\)

   Assume \(\fa\not\subset\rad(R)\), then there is a maximal ideal \(\fm\) s.t.
   \(\fa\not\subset\fm\). So \(\fa+\fm=R\). So there are \(a\in\fa\) and
   \(v\in\fm\) s.t. \(a+v=w\). Then \(v\not\in R^\times\) but the residue of
   \(v\) is \(w'\), even if \(w'\in(R/\fa)^\times\). For example, take \(R:=\Z\)
   and \(\fa=\la2\ra\) and \(w:=3\). Then \(w\not\in R^\times\) but the residue
   of \(w\) is \(1\in(R/\fa)^\times\)
   #+END_proof

   #+BEGIN_exercise
   label:3.22
   Let \(A\) be a local ring, \(e\) an idempotent. Show \(e=1\) or \(e=0\)
   #+END_exercise

   #+BEGIN_proof
   \(1-e+e=1\). Since \(1\not\in\fm\), at least one of \(1-e\) and \(e\) doesn't
   belong to \(\fm\)
   #+END_proof

   #+BEGIN_exercise
   label:3.23
   Let \(A\) be a ring, \(\fm\) a maximal ideal s.t. \(1+m\) is a unit for every
   \(m\in\fm\). Prove \(A\) is local. Is this assertion still true if \(\fm\) is
   not maximal?
   #+END_exercise
