#+TITLE: Introduction To Commutative Algebra
#+AUTHOR: Atiyah & Macdonald

#+LATEX_HEADER: \input{../preamble.tex}
#+EXPORT_FILE_NAME: ../latex/IntroductionToCommutativeAlgebra/IntroductionToCommutativeAlgebra.tex
#+options: num:1
* Rings and Ideals
  A *unit* is an element \(u\) with a *reciprocal* \(1/u\) or the
  *multiplicative inverse*. The units form a multiplicative group, denoted
  \(R^\times\)

  A ring *homomorphism*, or simply a *ring map*, \(\varphi:R\to R'\) is a map
  preserving sum, products and 1

  If there is an unspecified isomorphism between rings \(R\) and \(R'\), then we
  write \(R=R'\) when it is *canonical*; that is, it does not depend on any
  artificial choices.

  A subset \(R''\subset R\) is a *subring* if \(R''\) is a ring and the
  inclusion \(R''\hookrightarrow R\) is a ring map. In this case, we call \(R\)
  a *(ring) extension*.

  An *\(R\)-algebra* is a ring \(R'\) that comes equipped with a ring map
  \(\varphi:R\to R'\), called the *structure map*, denoted by \(R'/R\). For
  example, every ring is canonically a \(\Z\)-algebra. An
  *\(R\)-algebra homomorphism*, or *\(R\)-map*, \(R'\to R''\) is a ring map
  between \(R\)-algebras.

  A group \(G\) is said to *act* on \(R\) if there is a homomorphism given from
  \(G\) into the group of automorphism of \(R\). The *ring of invariants*
  \(R^G\) is the subring defined by
  \begin{equation*}
  R^G:=\{x\in R\mid gx=g\text{ for all }g\in G\}
  \end{equation*}

  Similarly a group \(G\) is said to *act* on \(R'/R\) if \(G\) acts on \(R'\)
  and each \(g\in G\) is an \(R\)-map. Note that \(R'^G\) is an \(R\)-subalgebra

** Boolean rings
  The simplest nonzero ring has two elements, 0 and 1. It's denoted \(\F_2\)


  Given any ring \(R\) and any set \(X\), let \(R^X\) denote the set of
  functions \(f:X\to R\). Then \(R^X\) is a ring.

  For example, take \(R:=\F_2\). Given \(f:X\to R\), put \(S:=f^{-1}\{1\}\).
  Then \(f(x)=1\) if \(x\in S\). In other words, \(f\) is the *characteristic
  function* \(\chi_S\). Thus /the characteristic functions form a ring, namely/, \(\F_2^X\)

  Given \(T\subset X\), clearly \(\chi_S\cdot\chi_T=\chi_{S\cap T}\).
  \(\chi_S+\chi_T=\chi_{S\triangle T}\), where \(S\triangle T\) is the
  *symmetric difference*:
  \begin{equation*}
  S\triangle T:=(S\cup T)-(S\cap T)
  \end{equation*}
  Thus /the subsets of \(X\) form a ring: sum is symmetric difference, and/
  /product is intersection. This ring is canonically isomorphic to \(\F_2^X\)/

  A ring \(B\) is called *Boolean* if \(f^2=f\) for all \(f\in B\). If so, then
  \(2f=0\) as \(2f=(f+f)^2=f^2+2f+f^2=4f\)

  Suppose \(X\) is a topological space, and give \(\F_2\) the *discrete*
  topology; that is, every subset is both open and closed. Consider the
  continuous functions \(f:X\to\F_2\). Clearly, they are just the \(\chi_S\)
  where \(S\) is both open and closed.

** Polynomial rings
   Let \(R\) be a ring, \(P:=R[X_1,\dots,X_n]\). \(P\) has this *Universal
   Mapping Property* (UMP): /given a ring map \(\varphi:R\to R'\) and given an/
   /element \(x_i\) of \(R'\) for each \(i\), there is a unique ring map/
   /\(\pi:P\to R'\) with \(\pi|R=\varphi\) and \(\pi(X_i)=x_i\)./ In fact, since
   \pi is a ring map, necessarily \pi is given by the formula:
   \begin{equation}
   \pi(\sum a_{(i_1,\dots,i_n)}X_1^{i_1}\dots X_n^{i_n})=\sum
   \varphi(a_{(i_1,\dots,i_n)})x_1^{i_1}\dots x_n^{i_n}\label{eq1.3.1}
   \end{equation}
   In other words, \(P\) is universal among \(R\)-algebras equipped with a list
   of \(n\) elements

   Similarly let \(\calx:=\{X_\lambda\}_{\lambda\in\Lambda}\) be any set of
   variables. Set \(P':=R[\calx]\); the elements of \(P'\) are the polynomials
   in any finitely many of the \(X_\lambda\). \(P'\) has essentially the same
   UMP as \(P\)

** Ideals
   Let \(R\) be a ring. A subset \(\fa\) is called an *ideal* if
   1. \(0\in\fa\)
   2. whenever \(a,b\in\fa\), also \(a+b\in\fa\)
   3. whenever \(x\in R\) and \(a\in\fa\) also \(xa\in\fa\)


   Given a subset \(\fa\subset R\), by the ideal \(\la\fa\ra\) that \(\fa\)
   *generates*, we mean the smallest ideal containing \(\fa\)

   All ideal containing all the \(a_\lambda\) contains any (finite) *linear
   combination* \(\sum x_\lambda a_\lambda\) with \(x_\lambda\in R\) and almost
   all 0.

   Given a single element \(a\), we say that the ideal \(\la a\ra\) is
   *principal*

   Given a number of ideals \(\fa_\lambda\), by their *sum* \(\sum\fa_\lambda\)
   we mean the set of all finite linear combinations \(\sum x_\lambda
   a_\lambda\) with \(x_\lambda\in R\) and \(a_\lambda\in\fa_\lambda\)

   Given two ideals \(\fa\) and \(\fb\), by the *transporter* of \(\fb\) into
   \(\fa\) we mean the set
   \begin{equation*}
   (\fa:\fb):=\{x\in R\mid x\fb\subset\fa\}
   \end{equation*}
   \((\fa:\fb)\)  is an ideal. Plainly,
   \begin{equation*}
   \fa\fb\subset\fa\cap\fb\subset\fa+\fb,\quad\fa,\fb\subset\fa+\fb,\quad
   \fa\subset(\fa:\fb)
   \end{equation*}
   Further, for any ideal \(\fc\), the distributive law holds:
   \(\fa(\fb+\fc)=\fa\fb+\fa\fc\)

   Given an ideal \(fa\), notice \(\fa=R\) /if and only if/ \(1\in\fa\). It
   follows that \(\fa=R\) iff \(\fa\) contains a unit.

   Given a ring map \(\varphi:R\to R'\), denote by \(\fa R'\) or \(\fa^e\) the
   ideal of \(R'\) generated by the set \(\varphi(\fa)\). We call it the
   *extension* of \(\fa\)

   Given an ideal \(\fa'\) of \(R'\), its preimage \(\varphi^{-1}(\fa')\) is an
   ideal of \(R\). We call \(\varphi^{-1}(\fa')\) the *contraction* of \(\fa'\)
   and sometimes denote it by \(\fa'^c\)

** Residue rings
   *kernel* \(\ker(\varphi)\) is defined to be the ideal \(\varphi^{-1}(0)\) of
   \(R\)

   Let \(\fa\) be an ideal of \(R\). Form the set of cosets of \(\fa\)
   \begin{equation*}
   R/\fa:=\{x+\fa\mid x\in R\}
   \end{equation*}
   \(R/\fa\) is called the *residure ring* or *quotient ring* or *factor ring* of
   \(R\) *modulo* \(\fa\). From the *quotient map*
   \begin{equation*}
   \kappa:R\to R/\fa\quad\text{ by }\kappa x:=x+\fa
   \end{equation*}
   The element \(\kappa x\in R/\fa\) is called the *residure* of \(x\).

   If \(\ker(\varphi)\supset\fa\), /then there is a ring map/ \(\psi:R/\fa\to R'\)
   /with/ \(\psi\kappa=\varphi\); that is, the following diagram is commutative

   #+BEGIN_center
   \begin{tikzcd}
   R\arrow[r,"\kappa"]\arrow[dr,"\varphi"]&R/\fa\arrow[d,"\psi"]\\
   &R'
   \end{tikzcd}
   #+END_center
   by \(\psi(x\fa)=\varphi(x)\). Then we only need to verify that \(\psi\) is a map
   
   Conversely, /if \psi exists, then/ \(\ker(\varphi)\supset\fa\), /or/
   \(\varphi\fa=0\), /or/ \(\fa R'=0\), since \(\kappa\fa=0\)

   Further, /if \psi exists, then \psi is unique/ as \(\kappa\) is surjective

   Finally, as \kappa is surjective, /if \psi exists, then \psi is surjective/
   /iff \psi is so/. In addition, \psi /is injective iff \(\fa=\ker(\varphi)\)/.
   Hence \psi /is an isomorphism iff \varphi is surjective and/
   \(\fa=\ker(\varphi)\). Therefore,
   \begin{equation*}
   R/\ker(\varphi)\xrightarrow{\sim}\im(\varphi)
   \end{equation*}

   \(R/\fa\) has UMP: \(\kappa(\fa)=0\), and given \(\varphi:R\to R'\) s.t.
   \(\varphi:R\to R'\) s.t. \(\varphi(\fa)=0\), there is a unique ring map
   \(\psi:R/\fa\to R'\) s.t. \(\psi\kappa=\varphi\). In other words, \(R/\fa\)
   is universal among \(R\)-algebras \(R'\) s.t. \(\fa R'=0\)

   If \(\fa\) is the ideal generated by elements \(a_\lambda\),then the UMP can
   be usefully rephrased as follows: \(\kappa(a_\lambda)=0\) for all \lambda,
   and given \(\varphi:R\to R'\) s.t. \(\varphi(a_\lambda)=0\) for all \lambda,
   there is a unique ring map \(\psi:R/\fa\to R'\) s.t. \(\psi\kappa=\varphi\)

   /The UMP serves to determine/ \(R/\fa\) /up to unique isomorphism/.
   Say \(R'\), equipped with \(\varphi:R\to R'\) has the UMP too.
   \(\kappa(\fa)=0\) so there is a unique \(\psi':R'\to R/\fa\) with
   \(\psi'\varphi=\kappa\). Then \(\psi'\psi\kappa=\kappa\). Hence
   \(\psi'\psi=1\) by uniqueness. Thus \(\psi\) and \(\psi'\) are inverse isomorphism
   #+BEGIN_center
   \begin{tikzcd}
   &&R/\fa\arrow[dd,"1"]\arrow[dl,"\psi"]\\
   R\arrow[urr,"\kappa"]\arrow[r,"\varphi"]\arrow[drr,"\kappa"]&
   R'\arrow[dr,"\psi'"]&\\
   &&R/\fa
   \end{tikzcd}
   #+END_center

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(R\) be a ring, \(P:=R[X]\), \(a\in R\) and \(\pi:P\to R\) the
   \(R\)-algebra map defined by \(\pi(X):=a\). Then
   1. \(\ker(\pi)=\{F(X)\in P\mid F(a)=0\}=\la X-a\ra\)
   2. \(R/\la X-a\ra\simeq R\)
   #+END_proposition

   #+BEGIN_proof
   Set \(G:=X-a\). Given \(F\in P\), let's show \(F=GH+r\) with \(H\in P\) and
   \(r\in R\). By linearity, we may assume \(F:=X^n\). If \(n\ge1\), then
   \(F=(G+a)X^{n-1}\), so \(F=GH+aX^{n-1}\) with \(H:=X^{n-1}\).

   Then \(\pi(F)=\pi(G)\pi(H)+\pi(r)=r\). Hence \(F\in\ker(\pi)\) iff \(F=GH\). But
   \(\pi(F)=F(a)\) by ref:eq1.3.1
   #+END_proof


** Degree of a polynomial
   Let \(R\) be a ring, \(P\) the polynomial ring in any number of variables.
   If \(F\) is a monomial \(\bM\), then its degree \(\deg(\bM)\) is the sum of
   its exponents; in general, \(\deg(F)\) is the largest \(\deg(\bM)\) of all
   monomials \(\bM\) in \(F\)

   Given any \(G\in P\) with \(FG\) nonzero, notice that
   \begin{equation*}
   \deg(FG)\le\deg(F)+\deg(G)
   \end{equation*}

** Order of a polynomial
   Let \(R\) be a ring, \(P\) the polynomial ring in variable \(X_\lambda\) for
   \(\lambda\in\Lambda\), and \((x_\lambda)\in R^\Lambda\) a vector. Let
   \(\varphi_{(x_\lambda)}:P\to P\) denote the \(R\)-algebra map defined by
   \(\varphi_{(x_\lambda)}X_\mu:=X_\mu+x_\mu\) for all \(\mu\in\Lambda\). Fix a
   nonzero \(F\in P\)

   The *order* of \(F\) at the zero vector \((0)\), denoted \(\ord_{(0)}F\), is
   defined as the smallest \(\deg(\bM)\) of all the monomials \(\bM\) in \(F\).
   In general, the *order* of \(F\) at the vector \((x_\lambda)\), denoted
   \(\ord_{(x_\lambda)}F\) is defined by the formula: \(\ord_{(x_\lambda)}F:=\ord_{(0)}(\varphi_{(x_\lambda)}F)\)

   Notice that \(\ord_{(x_\lambda)}F=0\) iff \(F(x_\lambda)\neq0\) as \((\varphi_{x_\lambda}F)(0)=F(x_\lambda)\)

   Given \mu and \(x\in R\), form \(F_{\mu,x}\) by substituting \(x\) for \(X_\mu\)
   in \(F\). If \(F_{\mu,x_\mu}\neq0\) , then
   \begin{equation*}
   \ord_{(x_\lambda)}F\le\ord_{(x_\lambda)}F_{\mu,x_\mu}\label{eq1.8.1}
   \end{equation*}
   If \(x_\mu=0\), then \(F_{\mu,x_\mu}\) is the sum of the terms without
   \(x_\mu\) in \(F\). Hence if \((x_\lambda)=(0)\), then ref:eq1.8.1 holds. But
   substituting 0 for \(X_\mu\) in \(\varphi_{(x_\lambda)}F\) is the same as
   substituting \(x_\mu\) for \(X_\mu\) in \(F\) and then applying
   \(\varphi_{(x_\lambda)}\) to the result; that is,
   \((\varphi_{(x_\mu)}F)_{\mu,0}=\varphi_{(x_\lambda)}F_{\mu,x_\mu}\)

   Given any \(G\in P\) with \(FG\) nonzero,
   \begin{equation*}
   \ord_{(x_\lambda)}FG\ge\ord_{(x_\lambda)}F+\org_{(x_\lambda)}G
   \end{equation*}

** Nested ideals
   Let \(R\) be a ring, \(\fa\) an ideal, and \(\kappa:R\to R/\fa\) the quotient map.
   Given an ideal \(\fb\supset\fa\), form the corresponding set of cosets of
   \(\fa\)
   \begin{equation*}
   \fb/\fa:=\{b+\fa\mid b\in\fb\}=\kappa(\fb)
   \end{equation*}
   Clearly, \(\fb/\fa\) is an ideal of \(R/\fa\). Also \(\fb/\fa=\fb(R/\fa)\)

   Given an ideal \(\fb\supset\fa\), form the composition of the quotient maps
   \begin{equation*}
   \varphi:R\to R/\fa\to (R/\fa)/(\fb/\fa)
   \end{equation*}
   \varphi is surjective and \(\ker(\varphi)=\fb\). Hence \varphi factors
   #+BEGIN_center
   \begin{tikzcd}
   R\arrow[r]\arrow[d]&R/\fb\arrow[d,"\psi","\simeq"']\\
   R/\fa\arrow[r]&(R/\fa)/(\fb/\fa)
   \end{tikzcd}
   #+END_center

** Idempotents
   Let \(R\) be a ring. Let \(e\in R\) be an *idempotent*; that is, \(e^2=e\).
   Then \(Re\) is a ring with \(e\) as 1.

** Exercise
   #+BEGIN_exercise
   label:ex1.13
   Let \(\varphi:R\to R'\) be a map of rings, \(\fa_1,\fa_2,\fa_3\) ideals of \(R\),
   \(\fb_1,\fb_2,\fb_3\) ideals of \(R'\). Prove
   1. \((\fa_1+\fa_2)^e=\fa_1^e+\fa_2^e\)
   2.  \((\fb_1+\fb_2)^c\supset\fb_1^c+\fb_2^c\)
   #+END_exercise
