#+TITLE: Logic Language And Meaning
#+AUTHOR: L. T. E. Gamut

#+EXPORT_FILE_NAME: ../latex/LogicLanguageAndMeaning/LogicLanguageAndMeaning.tex
#+LATEX_HEADER: \input{../preamble.tex}

* The Theory of Types and Categorical Grammar

** The Theory of Types
   1. If John is self-satisfied, then there is at least one thing he has in
      common with Peter


   Sentence (1) contains quantification over properties.

   2. [@2] Santa Claus has all the attributes of a sadist


   If we are to quantify not only over entities but also over properties of
   entities, then we need to extend predicate logic by introducing variables
   other than the ones we already have, which only range over entities. Besides
   predicate letters, we need *predicate variables*, so that we can quantify over
   this kind of variable in the syntax. Letting \(X\) be such a variable, (1)
   and (2) may be represented as in (3) and (4):
   3. [@3] \(Zj\to\exists X(Xj\wedge Xp)\)
   4. \(\forall X(\forall x(Sx\to Xx)\to Xs)\)


   But second-order predicate logic does not exhaust the expressive power of
   natural language. For not only are there natural language sentences which
   quantify over properties of entities, but there are also sentences which
   attribute properties to these properties of entities in turn.The predicate
   *red* expresses a property of individuals, so the predicate *color* expresses a
   property of properties of individuals. So in a sentence like *Red is a color*,
   which we represent as \(\calc(R)\), the second-order predicate *color* is
   applied to the first-order predicate *red*. We can also quantify over these
   properties of properties, as in *Red has something in common with green*.

   Besides higher-order predicates, there are other kinds of expressions which
   for linguistic purposes may usefully be added to predicate logic.

   Our first class of examples is formed by expressions with *predicate
   adverbials*
   5. [@5] John is walking quickly


   The expression *quickly* is, form a linguistic perspective, a modifier acting
   on the verb *is walking*. From a logical perspective, the property of walking
   quickly is attributed to an entity, John. This property cannot be seen as a
   conjunction of two properties, 'being quick' and 'walking'. For sentence (5)
   does not mean the same thing as sentence (6):
   6. [@6] John is walking and John is quick


   In logical terms, *quickly* is an expression which when applied to the
   first-order predicate *walking* result in a new first-order predicate *walking
   quickly*. From a logical point of view, the *relative adjectives* are
   expressions of the same kind. Sentence (7) may be represented in first-order
   predicate logic as formula (8)
   7. [@7] Jumbo is a pink elephant
   8. \(Ej\wedge Pj\)


   The adjective *pink* may, in other words, be represented as a standard
   first-order predicate. But the same does not apply to relative adjectives
   like *small*. Sentence (9) is the same kind of sentence as (7)
   9. [@9] Jumbo is a small elephant


   But sentence (9) cannot be analyzed as a conjunction of two first-oder
   predicates. The formula (10) which we would then obtain:
   10. [@10] \(Ej\wedge Sj\)


   expresses something which is generally false. The relative adjective *small*
   works the same way as the predicate adverbial *quickly*. When applied to the
   predicate *elephant*, it results in a new predicate *small elephant*
