#+TITLE: Minimal Flows And Their Extensions
#+AUTHOR: Joseph Auslander
#+EXPORT_FILE_NAME: ../latex/MinimalFlowsAndTheirExtensions/MinimalFlowsAndTheirExtensions.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Flows and Minimal Sets
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *transformation group* is a triple \((X,T,\pi)\) where \(X\) is a topological space, \(T\) is a
    topological group, and \pi is a continuous map of \(X\times T\) to \(X\) satisfying
    1. \(\pi(x,e)=x\)
    2. \(\pi(\pi(x,s),t)=\pi(x,st)\)
    #+END_definition

    A synonym for transformation group is *flow*. \(X\) is called the *phase space* and \(T\) the *phase
    group* or *acting group*

    Each \(t\in T\) defines a continuous map \(\pi^t\) of \(X\) to \(X\) by \(\pi^t(x)=\pi(x,t)\).
    If \(t,s\in T\), \(\pi^s\pi^t=\pi^{ts}\); in particular, \(\pi^t\pi^{t^{-1}}=\pi^e\). So each \(\pi^t\) is a
    homeomorphism of \(X\) onto itself

    We will suppress the map \pi notationally and just write \(xt\) in place of \(\pi(x,t)\). Thus the
    axioms for a flow appear as: the map \((x,t)\mapsto xt\) is continuous, \(xe=x\), and \((xs)t=x(st)\)

    We will usually write \((X,T)\) for a flow

    What we have defined as a transformation group could be called a *right* transformation group (or
    right flow). If \((X,T)\) is a right flow, then a left action of \(T\) can be defined
    by \(tx=xt^{-1}\)

    A *bitransformation group* \((G,X,T)\) consists of a right transformation group \((X,T)\) and a
    left transformation group \((G,X)\) s..t \((gx)t=g(xt)\)

    We will always suppose the phase space \(X\) of a flow is Hausdorff.

    In general, we will identify an element \(t\in T\) with the homeomorphism of \(X\) it defines.
    Thus \(T\) may be regarded as a subgroup of the total homeomorphism group of \(X\). It is
    possible that distinct elements \(s,t\) of \(T\) define the same homeomorphism. The action
    of \(T\) is *effective* if this does not occur. If the action is not effective,
    let \(F=\{t\in T\mid\forall x\in X.xt=x\}\). Then \(F\) is a closed (since \(X\) is Hausdorff) normal subgroup
    of \(T\). The quotient group \(T/F\) acts on \(X\) by \(x(Ft)=xt\), and this action is clearly
    effective. Therefore we can assume that the action of \(T\) on \(X\) is effective

    Moreover, the topology of the group is really not that important. We will frequently assuem
    that \(T\) has the discrete topology

    The most intensively studied cases have been where the acting group \(T\) is \(\Z\) or \(\R\).
    If \(T=\Z\), let \(\varphi(x)=x1\). Then \varphi is a homeomorphism of \(X\) and \(\varphi^n(x)=xn\). Conversely, if
    \varphi is a self homeomorphism of \(X\), it defines an action of \(\Z\) as above.

    We will refer to the pair \((X,\varphi)\) as a *cascade/discrete flow/discrete dynamic system*. Thus a
    cascade consists of a homeomorphism and its powers

    If \(T=\R\), then the action defines a one-parameter group of homeomorphism \(\{\varphi_t\}\), and in
    this case we write \(\varphi_t(x)\) instead of \(xt\). The axioms appear as \(\varphi_0(x)=x\)
    and \(\varphi_s\varphi_t(x)=\varphi_{s+t}(x)\). Customary terms for an \(\R\) action are *dynamic system/real
    flow/continuous flow*.


    Let \((X,T)\) be a flow, let \(K\) be a subset of \(X\), and \(B\) a subset of \(T\). We
    write \(K=\{xb\mid x\in K,b\in B\}\). If \(x\in X\), the set \(xT=\{x\}T\) is called the *orbit* of \(x\).
    If \(T=\Z\) or \(\R\) we will frequently use the notation \(\calo(x)\) for the orbit of \(x\) (also
    called *trajectory*)

    The subset \(K\) of \(X\) is said to be *invariant* if \(KT=K\) (equivalently \(KT\subset K\))

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(K\) be an invariant set. Then the closure, complement, boundary, and interior of \(K\)
       are all invariant sets
    2. If \(\{K_\alpha\}\) is a family of invariant sets, then \(\bigcup K_\alpha\) and \(\bigcap K_\alpha\) are invariant
    #+END_proposition

    Hence the *orbit closure* \(\ove{xT}\) is invariant

    There are several standard ways of obtaining new flows from given ones. The first is trivial.
    Let \((X,T)\) be a flow and let \(Z\) be an invariant subset of \(X\). Then \(T\) acts on \(Z\),
    we say \((Z,T)\) is a "subflow" of \((X,T)\). Secondly, if \((X_\alpha,T)\) (\(\alpha\in A\)) is a family of
    flows, then \(T\) acts on the product space \(\prod_\alpha X_\alpha\). We write \((\prod_\alpha X_\alpha, T)\) for this
    product flow.

    Let \((X,T)\) be a flow. A subset \(M\) of \(X\) is a *minimal set* if \(M\) is closed, non-empty
    and invariant, and if \(M\) has no proper subsets with these properties. Note that a non-empty
    subset \(M\) of \(X\) is minimal iff it is the orbit closure of each of its points.

    Minimal sets are also called "minimal orbit closures"

    If \((X,T)\) is itself minimal, then it is called *minimal transformation group/minimal flow*

    Since the intersection of closed invariant sets is closed invariant, we obtain

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \((X,T)\) be a flow and let \(M_1\) and \(M_2\) be minimal subset of \(X\). Then \(M_1=M_2\)
    or \(M_1\cap M_2=\emptyset\)
    #+END_proposition

    It is not in general the case that \(X\) is a union of minimal sets

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \((X,T)\) be a flow with compact Hausdorff phase space \(X\). Then \(X\) contains a minimal set
    #+END_theorem

    #+BEGIN_proof
    By compactness of \(X\), infinite intersection is nonempty.

    Then by Zorn's lemma
    #+END_proof

    An example of a "trivial" minimal set is a *fixed point* of the flow - a point \(x_0\)
    s.t. \(x_0t=x_0\) for all \(t\in T\). Another simple example - in the case \(T=\Z\) and \varphi the
    generating homeomorphism - is a *periodic orbit* - that is, the orbit of a point \(x_0\) for
    which \(\varphi^p(x_0)=x_0\) (where \(p>1\) is the smallest such positive integer). So
    \(\calo(x_0)=\ove{\calo(x_0)}=\{x_0,\varphi(x_0),\dots,\varphi^{p-1}(x_0)\}\) is minimal

    Similarly, if \(\{\varphi_t\}\) defines an action of \(\R\) on \(X\), and \(x\in X\) is not a fixed point
    of the flow, but \(\varphi_s(x)=x\) for some \(s\neq 0\), then \(x\) is called a *periodic point*, and its
    orbit \(\calo(x)=\{\varphi_t(x)\}\) is a periodic orbit. The minimum \tau of those \(s>0\) s.t. \(\varphi_s(x)=x\) is
    called the *period* of \(x\), and it is easily seen that \(\calo(x)=\{\varphi_t(x)\mid 0\le t<\tau\}\) and so is
    homeomorphic to a circle

    fixed points and periodic orbits are sometimes referred to as "trivial" minimal sets

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \((X,T)\) be a flow with \(T=\Z\) or \(\R\) and \(X\) is Hausdorff. Then an orbit is compact
    iff it is periodic
    #+END_theorem

    #+BEGIN_proof
    A periodic orbit is compact [[https://math.stackexchange.com/questions/337272/show-that-unit-circle-is-compact][Circle is compact]]

    Suppose \(T=\R\) and as usual, the action of \(\R\) is denoted by \(\{\varphi_t\}\). Let \(x\in X\)
    with \(\calo(x)\) compact, so we may suppose \(X=\calo(X)\). Let \(K=[-1,1]\) and
    write \(Kx=\{\varphi_t(x)\mid t\in K\}\). Then there is a countable subset \(C\) of \(\R\)
    s.t. \(X=\calo(x)=\bigcup_{c\in C}\varphi_c(Kx)\). By the Baire category theorem, some \(\varphi_c(Kx)\) has non-empty
    interior, so \(Kx\) has non-empty interior. Let \(\tau\in K\) with \(\varphi_\tau(x)\in int(Kx)\).
    Suppose \(\varphi_t(x)\neq x\) for all \(t\neq 0\). Then the map \sigma of \(\R\) onto \(X\) defined
    by \(\sigma(t)=\varphi_t(x)\) is a continuous bijection. If \sigma were a homeomorphism, the compact
    space \(\calo(x)=X\) would be homeomorphic with \(\R\). So \sigma is not a homeomorphism, and it follows
    that there is a sequence \(\{t_k\}\to\infty\) with \(\varphi_{t_k}(x)\to\varphi_\tau(x)\). Since \(\varphi_\tau(x)\in int(Kx)\),
    there is some \(t_k>1\) and \(s\in K\) with \(\varphi_{t_k}(x)=\varphi_s(x)\), so \(\calo(x)\) is periodic.
    #+END_proof

    Let \(T\) be a topological group. A subset \(A\) of \(T\) is *(left) syndetic* if there is a
    compact subset of \(K\) of \(T\) s.t. \(T=AK=\{ak\mid a\in A,k\in K\}\)

    Let \((X,T)\) be a flow, and let \(x\in X\). We say that \(x\) is an *almost periodic point* if for
    every neighborhood \(U\ni x\), there is a syndetic subset \(A\) of \(T\) s.t. \(xA\subseteq U\)

    Almost periodicity is a strong form of *recurrence* - the orbit returns to an arbitrary
    neighborhood infinitely often. For an action \(\{\varphi_t\}\) of \(\R\), a point \(x\) is recurrent iff
    for every neighborhood \(U\ni x\) and \(\tau>0\), there is a \(t\in\R\) with \(\abs{t}>\tau\)
    s.t. \(\varphi_t(x)\in U\).

    A point is periodic if it returns to itself every hour on the hour and is almost periodic if it
    returns to an arbitrary neighborhood every hour within the hour

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \((X,T)\) be a flow, with \(X\) locally compact Hausdorff. Then if \(x\) is an almost
    periodic point, the orbit closure \(\ove{xT}\) is compact
    #+END_lemma

    #+BEGIN_proof
    Let \(U\) be a compact neighborhood of \(x\), and let \(A=\{t\in T\mid xt\in U\}\). Since \(x\) is almost
    periodic, there is a compact subset \(K\) of \(T\) s.t. \(T=AK\). Thus \(xT=xAK\subset UK\) (Check Gottschalk), which is
    compact, so \(\ove{xT}\) is compact
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \((X,T)\) be a flow, with \(X\) locally compact Hausdorff. Then \(x\in X\) is an almost
    periodic point iff the orbit closure \(\ove{xT}\) is a compact minimal set
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \((X,T)\) is a flow with \(X\) compact Hausdorff, then there is an almost periodic point in \(X\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \((X,T)\) is a flow (with \(X\) locally compact Hausdorff) then \(x\in X\) is almost periodic
    iff it is discretely almost periodic (i.e., almost periodic w.r.t. the discrete topology of \(T\))
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \((X,T)\) be a flow with \(X\) compact Hausdorff. Then \(X\) is a (necessarily disjoint)
    union of minimal subsets iff every point of \(X\) is almost periodic (In this case, we say \(X\)
    is *pointwise almost periodic*)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \((X,T)\) be a minimal flow with \(X\) compact Hausdorff, and let \(U\) be a non-empty open
    subset of \(X\). Then there is a finite subset \(K=\{t_1,\dots,t_n\}\) of \(T\) s.t. \(X=UK=\bigcup_{j=1}^nUt_j\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \((X,T)\) be a flow, and let \(S\) be a normal subgroup of \(T\). Suppose \(x\in X\) is an
    almost periodic point for the flow \((X,S)\). Then if \(t\in T\), \(xt\) is an almost periodic
    point for \((X,S)\)
    #+END_lemma
