#+TITLE: Model Theory for Dummies: An Introduction
#+AUTHOR: David Marker


#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/ModelTheoryAnIntroduction/ModelTheoryAnIntroduction.tex
#+STARTUP: noindent
* Structures and Theories
** Languages and Structures
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A language $\call$ is given by specifying the following data
   1. A set of function symbols $\calf$ and positive integers $n_f$ for each
      $f\in\calf$
   2. a set of relation symbols $\calr$ and positive integers $n_R$ for each
      $R\in\calr$
   3. a set of constant symbols $\calc$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-structure $\calm$ is given by the following data
   1. a nonempty set $M$ called the *universe*, *domain* or *underlying set*
      of $\calm$
   2. a function $f^{\calm}:M^{n_f}\to M$ for each $f\in\calf$
   3. a set $R^{\calm}\subseteq M^{n_R}$ for each $R\in\calr$
   4. an element $c^{\calm}\in M$ for each $c\in\calc$
   #+END_definition

   We refer to $f^{\calm},R^{\calm},c^{\calm}$ as the *interpretations* of the
   symbols $f,R$ and $c$. We often write the structure as
   $\calm=(M,f^{\calm},R^{\calm},c^{\calm}:f\in\calf,R\in\calr,c\in\calc)$

   [[index:\(\call\)-embedding]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose that $\calm$ and $\caln$ are \(\call\)-structures with universes $M$
   and $N$ respectively. An *\(\call\)-embedding* $\eta:\calm\to\caln$ is a
   one-to-one map $\eta:M\to N$ that
   1. $\eta(f^{\calm}(a_1,\dots,a_{n_f}))=f^{\caln}(\eta(a_1),\dots,\eta(a_{n_f}))$
      for all $f\in\calf$ and $a_1,\dots,a_{n_f}\in M$
   2. $(a_1,\dots,a_{m_R})\in R^{\calm}$ if and only if
      $(\eta(a_1),\dots,\eta(a_{m_R}))\in R^{\caln}$ for all $R\in\calr$ and
      $a_1,\dots,a_{m_R}\in M$
   3. $\eta(c^{\calm})=c^{\caln}$ for $c\in\calc$
   #+END_definition


   [[index:substructure]]
   A bijective \(\call\)-embedding is called an *\(\call\)-isomorphism*. If
   $M\subseteq N$ and the inclusion map is an \(\call\)-embedding, we say either
   $\calm$ is a *substrcture* of $\caln$ or that $\caln$ is an *extension*
   of $\calm$

   The *cardinality* of $\calm$ is $\abs{M}$, the cardinality of the universe of \(\calm\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The set of *\(\call\)-terms* is the smallest set $\calt$ s.t.
   1. $c\in\calt$ for each constant symbol $c\in\calc$
   2. each variable symbol $v_i\in\calt$ for $i=1,2,\dots$
   3. if $t_1,\dots,t_{n_f}\in\calt$ and $f\in\calf$ then
      $f(t_1,\dots,n_{n_f})\in\calt$ 
   #+END_definition


   Suppose that $\calm$ is an \(\call\)-structure and that $t$ is a term built
   using variables from $\bar{v}=(v_{i_1},\dots,v_{i_m})$. We want to interpret
   $t$ as a function $t^{\calm}:M^m\to M$. For $s$ a subterm of $t$ and
   $\bar{a}=(a_{i_1},\dots,a_{i_m})\in M$, we inductively define
   $s^{\calm}(\bar{a})$ as follows.
   1. If $s$ is a constant symbol $c$, then $s^{\calm}(\bar{a})=c^{\calm}$
   2. If $s$ is the variable $v_{i_j}$, then $s^{\calm}(\bar{a})=a_{i_j}$
   3. If $s$ is the term $f(t_1,\dots,t_{n_f})$, where $f$ is a function symbol
      of $\call$ and $t_1,\dots,t_{n_f}$ are terms, then 
      $s^{\calm}(\bar{a})=f^{\calm}(t^{\calm}_1(\bar{a}),\dots,t_{n_f}^{\calm}(\bar{a}))$

      
   The function $t^{\calm}$ is defined by $\bar{a}\mapsto t^{\calm}(\bar{a})$

   [[index:atomic formula]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \phi is an *atomic* *\(\call\)-formula* if \phi is either
   1. $t_1=t_2$ where $t_1$ and $t_2$ are terms
   2. $R(t_1,\dots,t_{n_R})$


   The set of *\(\call\)-formulas* is the smallest set $\calw$ containing the
   atomic formulas s.t.
   1. if $\phi\in\calw$, then $\neg\phi\in\calw$
   2. if $\phi,\psi\in\calw$, then $(\phi\wedge\psi),(\phi\vee\psi)\in\calw$
   3. if $\phi\in\calw$, then $\exists v_i\phi,\forall v_i\phi\in\calw$
   #+END_definition

   We say a variable $v$ *occurs freely* in a formula \phi if it is not
   inside a $\exists v$ or $\forall v$ quantifier; otherwise we say that it's
   *bound*. We call a formula a *sentence* if it has no free variables. We
   often write $\phi(v_1,\dots,v_n)$ to make explicit the free variables in \phi

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \phi be a formula with free variables from
   \(\bar{v}=(v_{i_1},\dots,v_{i_m})\)
    and let
    $\bar{a}=(a_{i_1},\dots,a_{i_m})\in M^m$. We inductively define
    $\calm\vDash\phi\bar{a}$ as follows
   1. If \phi is $t_1=t_2$, then $\calm\vDash\phi(\bar{a})$ if
      $t_1^{\calm}(\bar{a})=t_2^{\calm}(\bar{a})$ 
   2. If \phi is $R(t_1,\dots,t_{m_R})$ then $\calm\vDash\phi(\bar{a})$ if
      $(t_1^{\calm}(\bar{a}),\dots,t_{m_R}^{\calm}(\bar{a}))\in R^{\calm}$
   3. If \phi is $\neg\psi$ then $\calm\vDash\phi(\bar{a})$ if
      $\calm\not\vDash\psi(\bar{a})$
   4. If \phi is $(\psi\wedge\theta)$ then $\calm\vDash\phi(\bar{a})$ if
      $\calm\vDash\psi(\bar{a})$ and
      $\calm\vDash\theta(\bar{a})$
   5. If \phi is $(\psi\vee\theta)$ then $\calm\vDash\phi(\bar{a})$ if
      $\calm\vDash\psi(\bar{a})$ or
      $\calm\vDash\theta(\bar{a})$
   6. If \phi is $\exists v_j\psi(\bar{v},v_j)$ then $\calm\vDash\phi(\bar{a})$
      if there is $b\in M$ s.t. $\calm\vDash\psi(\bar{a},b)$
   7. If \phi is $\forall v_j\psi(\bar{v},v_j)$ then $\calm\vDash\phi(\bar{a})$
      if $\calm\vDash\psi(\bar{a},b)$ for all $b\in M$
   #+END_definition


   If $\calm\vDash\phi(\bar{a})$ we say that $\calm$ *satisfies*
   $\phi(\bar{a})$ or $\phi(\bar{a})$ is *true* in $\calm$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop1.1.8
   Suppose that $\calm$ is a substrcture of $\caln$, $\bar{a}\in M$ and
   $\phi(\bar{v})$ is a quantifier-free formula. Then
   $\calm\vDash\phi(\bar{a})$ if and only if $\caln\vDash\psi(\bar{a})$
   #+END_proposition

   #+BEGIN_proof
   *Claim* If $t(\bar{v})$ is a term and $\bar{b}\in M$ then
   $t^{\calm}(\bar{b})=t^{\caln}(\bar{b})$. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that two \(\call\)-strctures $\calm$ and $\caln$ are *elementarily*
   *equivalent* and write $\calm\equiv\caln$ if
   \begin{equation*}
    \calm\vDash\phi\text{ if and only if } \caln\vDash\phi
   \end{equation*}
   for all \(\call\)-sentences \phi
   #+END_definition

   [[index:full theory]]
   We let $\Th(\calm)$, the *full theory* of $\calm$ be the set of
   \(\call\)-sentences \phi s.t. $\calm\vDash\phi$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm1.1.10
   Suppose that $j:\calm\to\caln$ is an isomorphism. Then $\calm\equiv\caln$
   #+END_theorem

   #+BEGIN_proof
   Show by induction on formulas that $\calm\vDash\phi(a_1,\dots,a_n)$ if and
   only if $\caln\vDash\phi(j(a_1),\dots,j(a_n))$ for all formulas \phi
   #+END_proof
** Theories
   [[index:model]]
   [[index:satisfiable]]
   Let $\call$ be a language. An *\(\call\)-theory* $T$ is a set of
   \(\call\)-sentences. We say that $\calm$ is a *model* of $T$ and write
   $\calm\vDash T$ if $\calm\vDash\phi$ for all sentences $\phi\in T$. A
   theory is *satisfiable* if it has a model.

   [[index:elementary class]]
   A class of \(\call\)-structures $\calk$ is an *elementary class* if there
   is an \(\call\)-theory $T$ s.t. $\calk=\{\calm:\calm\vDash T\}$
   #+ATTR_LATEX: :options [Linear Orders]
   #+BEGIN_examplle
   Let \(\call=\{<\}\), where < is a binary relation symbol. The class of linear
   order is axiomatized by the \(\call\)-sentences
   \begin{align*}
   &\forall x\;\neg(x<x)\\
   &\forall x\forall y\forall z\;((x<y\wedge y<z)\to x<z)\\
   &\forall x\forall y\;(x<y\vee x=y\vee y<x)
   \end{align*}
   #+END_examplle

   #+ATTR_LATEX: :options [Groups]
   #+BEGIN_examplle
   Let $\call=\{\cdot,e\}$ where $\cdot$ is a binary function symbol and $e$ is a 
   constant symbol. The class of groups is axiomatized by
   \begin{align*}
   &\forall x\;e\cdot x=x\cdot e=x\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\exists y\;x\cdot y=y\cdot x= e
   \end{align*}
   #+END_examplle

   #+ATTR_LATEX: :options [Ordered Abelian Groups]
   #+BEGIN_examplle
   Let \(\call=\{+,<,0\}\), where + is a binary function, < is a binary relation
   symbol, and 0 is a constant symbol. The axioms for order groups are
   1. the axioms for additive groups
   2. the axioms for linear orders
   3. \(\forall x\forall y\forall z(x<y\to x+z<y+z)\)
   #+END_examplle

   #+ATTR_LATEX: :options [Left \(R\)-modules]
   #+BEGIN_examplle
   Let $R$ be a ring with multiplicative identity 1. Let
   $\call=\{+,0\}\cup\{r:r\in R\}$ where $+$ is a binary function symbol, 0 is a
   constant, and $r$ is a unary function symbol for $r\in R$. In an
   \(R\)-module, we will interpret $r$ as scalar multiplication by $R$. The
   axioms for \(R\)-modules are
   \begin{align*}
   &\forall x\e r(x+y)=r(x)+r(y)\text{ for each }r\in R\\
   &\forall x\e (r+s)(x)=r(x)+s(x)\text{ for each }r,s\in R\\
   &\forall x\e r(s(x))=rs(x)\text{ for } r,s\in R\\
   &\forall x\e 1(x)=x
   \end{align*}
   #+END_examplle
   [[index:ACF]]
   #+ATTR_LATEX: :options [Rings and Fields]
   #+BEGIN_examplle
   Let $\call_r$ be the language of rings $\{+,-,\cdot,0,1\}$, where $+,-$ and $\cdot$
   are binary function symbols and $0$ and $1$ are constants. The axioms for rings are given 
   by
   \begin{align*}
   &\forall x\forall y\forall z\;(x-y=z\leftrightarrow x=y+z)\\
   &\forall x\;x\cdot 0=0\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\;x\cdot 1=1\cdot x=x\\
   &\forall x\forall y\forall z\;x\cdot(y+z)=(x\cdot y)+(x\cdot z)\\
   &\forall x\forall y\forall z\;(x+y)\cdot z=(x\cdot z)+(y\cdot z)
   \end{align*}
   We axiomatize the class of fields by adding
   \begin{align*}
   &\forall x\forall y\;x\cdot y=y\cdot x\\
   &\forall x\;(x\neq 0\to\exists y\;x\cdot y=1)
   \end{align*}
   We axiomatize the class of algebraically closed fields by adding to the field axioms the sentences
   \begin{equation*}
   \forall a_0\dots\forall a_{n-1}\exists x\;x^n+\displaystyle\sum_{i=1}^{n-1}
   a_ix^i=0
   \end{equation*}
   for $n=1,2,\dots$. Let \(\ACF\) be the axioms for algebraically closed fields.

   Let $\psi_p$ be the \(\call_r\)-sentence $\forall x\;
   \underbrace{x+\dots+x}_{p\text{-times}}=0$, which asserts that a field has characteristic
   $p$. For $p>0$ a prime, let $\ACF_p=\ACF\cup\{\psi_p\}$ and
   $\ACF_0=\ACF\cup\{\neg\psi_p:p>0\}$ be the theories of algebraically
   closed fields of characteristic $p$ and zero respectively
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence. We say that
   \phi is a *logical consequence* of $T$ and write $T\vDash\phi$ if
   $\calm\vDash\phi$ whenever $\calm\vDash T$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. Let $\call=\{+,<,0\}$ and let $T$ be the theory of ordered abelian groups.
      Then $\forall x(x\neq 0\to x+x\neq 0)$ is a logical consequence of $T$
   2. Let $T$ be the theory of groups where every element has order 2. Then\par
      $T\not\vDash\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proposition

   #+BEGIN_proof
   2. $\Z/2\Z\vDash T\wedge\neg\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proof
** Definable Sets and Interpretability
   [[index:definable]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\calm=(M,\dots)$ be an \(\call\)-structure. We say that $X\subseteq M^n$
   is *definable* if and only if there is an \(\call\)-formula 
   $\phi(v_1,\dots,v_n,w_1,\dots,w_m)$ and $\bar{b}\in M^b$ s.t. 
   $X=\{\bar{a}\in M^n:\calm\vDash\phi(\bar{a},\bar{b})\}$. We say that
   $\phi(\bar{v},\bar{b})$ *defines* $X$. We say that $X$ is
   *\(A\)-definable* or *definable over*  $A$ if there is a formula 
   $\psi(\bar{v},w_1,\dots,w_l)$ and $\bar{b}\in A^l$ s.t.
   $\psi(\bar{v},\bar{b})$ defines $X$
   #+END_definition

   A number of examples using $\call_r$, the language of rings
   * Let $\calm=(R,+,-,\cdot,0,1)$ be a ring. Let $p(X)\in R[X]$. Then 
     $Y=\{x\in R:p(x)=0\}$ is definable. Suppose that
     $p(X)=\displaystyle\sum_{i=0}^ma_iX^i$. Let $\phi(v,w_0,\dots,w_n)$ be the
     formula
     \begin{equation*}
     w_n\cdot\underbrace{v\cdots v}_{n\text{-times}}+\dots+w_1\cdot v+w_0=0
     \end{equation*}
     Then $\phi(v,a_0,\dots,a_n)$ defines $Y$. Indeed, $Y$ is \(A\)-definable
     for any $A\supseteq\{a_0,\dots,a_n\}$
   * Let $\calm=(\R,+,-,\cdot,0,1)$ be the field of real numbers. Let
     $\phi(x,y)$ be the formula 
     \begin{equation*}
     \exists z(z\neq 0\wedge y=x+z^2)
     \end{equation*}
     Because $a<b$ if and only if $\calm\vDash\phi(a,b)$, the ordering is
     \(\emptyset\)-definable 
   * Consider the natural numbers $\N$ as an $\call=\{+,\cdot,0,1\}$ structure.
     There is an \(\call\)-formula $T(e,x,s)$ s.t. $\N\vDash T(e,x,s)$ if and
     only if the Turing machine with program coded by $e$ halts on input $x$ in
     at most $s$ steops. Thus the Turing machine with program $e$ halts on input
     $x$ if and only if

 $\N\vDash\exists s\;T(e,x,s)$. So the halting
     computations is definable

     
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. Suppose that $D_n$ is a collection of
   subsets of $M^n$ for all $n\ge 1$ and $\cald=(D_n:n\ge 1)$ is the smallest
   collection s.t. 
   1. $M^n\in D_n$
   2. for all \(n\)-ary function symbols $f$ of $\call$, the graph of $f^{\calm}$
      is in $D_{n+1}$
   3. for all \(n\)-ary relation symbols $R$ of $\call$, $R^{\calm}\in D_n$
   4. for all $i,j\le n$, $\{(x_1,\dots,x_n)\in M^n:x_i=x_j\}\in D_n$
   5. if $X\in D_n$, then $M\times X\in D_{n+1}$
   6. each $D_n$ is cloed under complement, union and intersection
   7. if $X\in D_{n+1}$ and $\pi:M^{n+1}\to M^n$ is the projection 
      $(x_1,\dots,x_{n+1})\mapsto(x_1,\dots,x_n)$, then $\pi(X)\in D_n$
   8. if $X\in D_{n+m}$ and $b\in M^m$, then $\{a\in M^n:(a,b)\in X\}\in D_n$
      

   Thus $X\subseteq M^n$ is definable if and only if $X\in D_n$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. If $X\subset M^n$ is \(A\)-definable,
   then every \(\call\)-automorphism of $\calm$ that fixes $A$ pointwise fixes
   $X$ setwise(that is, if \sigma is an automorphism of $M$ and $\sigma(a)=a$
   for all $a\in A$, then $\sigma(X)=X$)
   #+END_proposition

   #+BEGIN_proof
   \begin{equation*}
   \calm\vDash\psi(\bar{v},\bar{a})\leftrightarrow
   \calm\vDash\psi(\sigma(\bar{v}),\sigma(\bar{a}))\leftrightarrow
   \calm\vDash\psi(\sigma(\bar{v}),\bar{a})
   \end{equation*}
   In other words, $\bar{b}\in X$ if and only if $\sigma(\bar{b})\in X$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
    A subset $S$ of a field $L$ is *algebraically independent* over a
    subfield $K$ if the elements of 
    $S$ do not satisfy any non-trivial polynomial equation with
    coefficients in $K$ 
   #+END_definition

   
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
    The set of real numbers is not definable in the field of complex numbers
   #+END_corollary

   #+BEGIN_proof
   If $\R$ where definable, then it would be definable over a finite
   $A\subset\C$. Let $r,s\in\C$ be algebraically independent over $A$ with
   $r\in\R$ and $s\not\in\R$. There is an automorphism \sigma of $\C$ s.t.
   $\sigma|A$ is the identity and $\sigma(r)=s$. Thus $\sigma(\R)\neq\R$ and
   $\R$ is not definable over $A$
   #+END_proof
   
   We say that an \(\call_0\)-structure $\caln$ is *definably interpreted* in
   an \(\call\)-structure $\calm$ if and only if we can find a definable
   $X\subseteq M^n$ for some $n$ and we can interpret the symbols of $\call_0$
   as definable subsets and functions on $X$ so that the resulting
   \(\call_0\)-structure is isomorphic to $\calm$


   For example, let $K$ be a field and $G$ be $\GL_2(K)$, the group of
   invertible $2\times 2$ matrices over $K$. Let $X=\{(a,b,c,d)\in K^4:ad-bc\neq
   0\}$. Let $f:X^2\to X$ by
   \begin{align*}
   f((a_1,b_1,&c_1,d_1),(a_2,b_2,c_2,d_2))=\\
   &(a_1a_2+b_1c_2,a_1b_2+b_1d_2,c_1a_2+d_1c_2,c_1b_2+d_1d_2)
   \end{align*}
   $X$ and $f$ are definable in $(K,+,\cdot)$, and the set $X$ with operation
   $f$ is isomorphic to $\GL_2(K)$, where the identity element of $X$ is
   $(1,0,0,1)$ 

   Clearly, $(\GL_n(K),\cdot,e)$ is definably interpreted in $(K,+,\cdot,0,1)$.
   A *linear algebraic group* over $K$ is a subgroup of $\GL_n(K)$ defined by
   polynomial equations over $K$. Any linear algebraic group over $K$ is
   definably interpreted in $K$

   Let $F$ be an infinite field and let $G$ be the group of matrices of the form 
   #+ATTR_LATEX: :mode math :environment pmatrix
   | a | b |
   | 0 | 1 |

   where $a,b\in F, a\neq 0$. This group is isomorphic to the group of affine
   transformations $x\mapsto ax+b$, where $a,b\in F$ and $a\neq 0$

   We will show that $F$ is definably interpreted in the group $G$. Let
   \begin{equation*}
    \alpha=\begin{pmatrix}
           1&1\\
           0&1\\
           \end{pmatrix}\text{ and }
   \beta=\begin{pmatrix}
   \tau&0\\
   0&1\\
         \end{pmatrix}
   \end{equation*}
   where $\tau\neq 0$. Let
   \begin{gather*}
   A=\{g\in G:g\alpha=\alpha g\}=\{\begin{pmatrix}
   1&x\\
   0&1\\
                                   \end{pmatrix}:x\in F\}\\
   B=\{g\in G:g\beta=\beta g\}=\{\begin{pmatrix}
   x&0\\
   0&1\\
                                   \end{pmatrix}:x\neq 0\}
   \end{gather*}
   Clearly $A,B$ are definable using parameters \alpha and \beta

   $B$ acts on $A$ by conjugation
   \begin{equation*}
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}^{-1}
   \begin{pmatrix}
   1&y\\
   0&1\\
   \end{pmatrix}
   \begin{pmatrix}
   x&0\\
   0&1\\
   \end{pmatrix}=
   \begin{pmatrix}
   1&\frac{y}{x}\\
   0&1
   \end{pmatrix}
   \end{equation*}
   We can define the map $i:A\backslash\{1\}\to B$ by $i(a)=b$ if and only if
   $b^{-1}ab=\alpha$, that is
   \begin{equation*}
   i \begin{pmatrix}
   1&x\\
   0&1
     \end{pmatrix}=
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}
   \end{equation*}
   Define an operation $*$ on $A$ by
   \begin{equation*}
   a*b=
   \begin{cases}
   i(b)a(i(b))^{-1}&\text{if } b\neq I\\
   1&\text{if } b=I
   \end{cases}
   \end{equation*}
   where $I$ is the identity matrix. Now $(F,+,\cdot,0,1)\cong (A,\cdot,*,1,\alpha)$


   Very complicated structures can often be interpreted in seemingly simpler
   ones. For example, any structure in a countable language can be interpreted
   in a graph. Let $(A,<)$ be a linear order. For each $a\in A$, $G_A$ will have
   vertices $a,x_1^a,x_2^a,x_3^a$ and contain the subgraph

   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \node[vertex,label=left:$x_2^a$] (2) at (0,0) {};
   \node[vertex,label=right:$x^a_3$] (3) at (2,0) {};
   \node[vertex,label=right:$x^a_1$] (1) at (1,-1) {};
   \node[vertex,label=right:$a$] (a) at (1,-2) {};
   \draw (2) -- (3) -- (1) -- (2);
   \draw (a) -- (1);
   \end{tikzpicture}
   \end{center}

   If $a<b$, then $G_A$ will have vertices $y_1^{a,b},y_2^{a,b},y_3^{a,b}$ and
   contain the subgraph
   
   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$y_2^{a,b}$] (2) at (2,2) {};
   \node[label=left:$y_1^{a,b}$,inner sep=0] (1) at (1,1) {};
   \node[vertex,label=right:$y_3^{a,b}$] (3) at (2,1) {};
   \node[vertex,label=left:$a$] (a) at (0,0) {};
   \node[vertex,label=right:$b$] (b) at (4,0) {};
   \draw (a) -- (2);
   \draw (1) -- (3);
   \draw (2) -- (b);
   \end{tikzpicture}
   \end{center}


   Let $V_A=A\cup\{x_1^a,x_2^a,x_3^a:a\in
   A\}\cup\{y_1^{a,b},y_2^{a,b},y_3^{a,b}:a,b\in A\text{ and }a<b\}$, and let
   $R_A$ be the smallest symmetric relation containing all edges drawn above.

   For example, if $A$ is the three-element linear order $a<b<c$, then $G_A$ is
   the graph

   \begin{center}
   \begin{tikzpicture}[scale=0.8,transform shape]
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$x_2^a$] (a2) at (0,0) {};
   \node[vertex,label=left:$x_2^b$] (b2) at (4,0) {};
   \node[vertex,label=left:$x_2^c$] (c2) at (8,0) {};
   \node[vertex,label=right:$x_1^c$] (c1) at (9,1) {};
   \node[vertex,label=right:$x_1^b$] (b1) at (5,1) {};
   \node[vertex,label=right:$x_1^a$] (a1) at (1,1) {};
   \node[vertex,label=right:$x_3^a$] (a3) at (2,0) {};
   \node[vertex,label=right:$x_3^b$] (b3) at (6,0) {};
   \node[vertex,label=right:$x_3^c$] (c3) at (10,0) {};
   \node[vertex,label=left:$a$] (a) at (1,2) {};
   \node[vertex,label=above:$b$] (b) at (5,2) {};
   \node[vertex,label=right:$c$] (c) at (9,2) {};
   \node[vertex,label=below:$y_1^{a,b}$] (ab1) at (2,2.5) {};
   \node[vertex,label=below:$y_1^{b,c}$] (bc1) at (6,2.5) {};
   \node[vertex,label=below:$y_3^{a,b}$] (ab3) at (3,2.5) {};
   \node[vertex,label=right:$y_2^{a,b}$] (ab2) at (3,3) {};
   \node[vertex,label=below:$y_3^{b,c}$] (bc3) at (7,2.5) {};
   \node[vertex,label=right:$y_2^{b,c}$] (bc2) at (7,3) {};
   \node[vertex,label=below:$y_3^{a,c}$] (ac3) at (5,4) {};
   \node[vertex,label=below:$y_2^{a,c}$] (ac2) at (5,6) {};
   \node[vertex,label=below:$y_1^{a,c}$] (ac1) at (3,4) {};
   \draw (a2) -- (a1) -- (a3) -- (a2);
   \draw (a1) -- (a);
   \draw (b2) -- (b1) -- (b3) -- (b2);
   \draw (b1) -- (b);
   \draw (c2) -- (c1) -- (c3) -- (c2);
   \draw (c1) -- (c);
   \draw (a) -- (ac2);
   \draw (ac2) -- (c);
   \draw (a) -- (ab2);
   \draw (ab1) -- (ab3);
   \draw (ac1) -- (ac3);
   \draw (bc1) -- (bc3);
   \draw (b) -- (bc2);
   \draw (b) -- (ab2);
   \draw (c) -- (bc2);
   \end{tikzpicture}
   \end{center}

   Let $\call=\{R\}$ where $R$ is a binary relation. Let $\phi(x,u,v,w)$ be the
   formula asserting that $x,u,v,w$ are distinct, there are edges
   $(x,u),(u,v),(v,w),(u,w)$ and these are the only edges involving $u,v,w$.
   $G_A\vDash\phi(a,x_1^a,x_2^a,x_3^a)$ for all $a\in A$.

   $\psi(x,y,u,v,w)$ asserts that $x,y,u,v,w$ are distinct. $(x,u),(u,v),(u,w),(v,y)$

   Define $\theta_i(z)$ as follows:
   \begin{align*}
   &\theta_0(z):=\exists u\exists v\exists w\;\phi(z,u,v,w)\\
   &\theta_1(z):=\exists x\exists v\exists w\;\phi(x,z,v,w)\\
   &\theta_2(z):=\exists u\exists u\exists w\;\phi(x,u,z,w)\\
   &\theta_3(z):=\exists x\exists y\exists v\exists w\;\psi(x,y,z,v,w)\\
   &\theta_4(z):=\exists x\exists y\exists u\exists w\;\psi(x,y,u,z,w)\\
   &\theta_5(z):=\exists x\exists y\exists u\exists v\;\psi(x,y,u,v,z)\\
   \end{align*}
   If $a,b\in A$ and $a<b$, then
   \begin{equation*}
   G_A\vDash\theta_0(a)\wedge\theta_1(x^a_1)\wedge\theta_2(x^a_2)\wedge
   \theta_2(x^a_3)
   \end{equation*}
   and 
   \begin{equation*}
   G_A\vDash\theta_3(y_1^{a,b})\wedge\theta_4(y_2^{a,b})\wedge\theta_5(
   y_3^{a,b})
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then for all vertices $x$ in $G$, there is a
   unique $i\le 5$ s.t. $G_A\vDash\theta_i(x)$
   #+END_lemma

   Let $T$ be the \(\call\)-theory with the following axioms
   1. $R$ is symmetric and irreflexive
   2. for all $x$, exactly one $\theta_i$ holds
   3. if $\theta_0(x)$ and $\theta_0(y)$ then $\neg R(x,y)$
   4. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)\\$ then
      $\forall u_1\forall v_1\forall w_1\neg\psi(y,x,u_1,v_1,w_1)$
   5. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ and 
      $\exists u\exists v\exists w\;\psi(y,z,u,v,w)$ then\par
      $\exists u\exists v\exists w\;\psi(x,z,u,v,w)$
   6. if $\theta_0(x)$ and $\theta_0(y)$, then either $x=y$ or 
      $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ or
      $\exists u\exists v\exists w\;\psi(y,x,u,v,w)$
   7. if $\phi(x,u,v,w)\wedge\phi(x,u',v',w')$, then
      $u=u',v=v',w=w'$
   8. if $\psi(x,y,u,v,w)\wedge\psi(x,y,u',v',w')$, then
      $u'=u,v=v',w=w'$


   If $(A,<)$ is a linear order, then $G_A\vDash T$

   Suppose $G\vDash T$. Let $X_G=\{x\in G:G\vDash\theta_0(x)\}$

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then $(X_{G_A},<_{G_A})\cong(A,<)$. Moreover,
   $G_{X_G}\cong G$ for all $G\vDash T$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call_0\)-structure $\caln$ is *interpretable* in an
   \(\call\)-structure $M$ if there is a definable $X\subseteq M^n$, a definable
   equivalence relation $E$ on $X$, and for each symbol of $\call_0$ we can find
   definable \(E\)-invariant sets on X s.t. $X/E$ with the induced structure is
   isomorphic to $\caln$
   #+END_definition
** Answers to Exercises
   #+BEGIN_exercise
   1. transform $\psi$ to CNF
   2. prenex normal form
   #+END_exercise
   #+BEGIN_exercise
   1. 
      \begin{tikzpicture}[scale=0.6]
      \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
      \node[vertex,label=above:$s$] (1) at (0,1) {};
      \node[vertex,label=above:$e$] (0) at (0,0) {};
      \node[vertex,label=above:$r$] (2) at (1,0) {};
      \node[vertex,label=above:$rs$] (3) at (1,1) {};
      \end{tikzpicture}
   2. enumerate $\calm$'s functions, relations and constants
   #+END_exercise
   #+BEGIN_exercise
   [fn:stack]
   Note that every \(\call\)-structure $\calm$ of size $\kappa$ is isomorphic to an
   \(\call\)-structure with domain $\kappa$. For each relation symbols, we have $2^\kappa$
   options. If the language has size $\lambda$, this is at most 
   $(2^\kappa)^\lambda=2^{\kappa\cdot\lambda}=2^{\max(\lambda,\kappa)}$
   #+END_exercise

   #+BEGIN_exercise
   \begin{align*}
   T\vDash\phi&\Leftrightarrow\forall \calm\;\calm\vDash T\to\calm\vDash\phi\\
   &\Leftrightarrow\forall \calm\;\calm\vDash T'\to\calm\vDash\phi\\
   &\Leftrightarrow T'\vDash\phi
   \end{align*}
   #+END_exercise
   #+BEGIN_exercise
   Follow the definition
   #+END_exercise

   #+BEGIN_exercise
   Since there is no model $\calm$ s.t. $\calm\vDash T$. It's true that 
   $T\vDash \phi$
   #+END_exercise

   #+BEGIN_exercise
   1. Suppose $\calm\vDash\phi$, then $E^{\calm}$ is an equivalent relation and
      each equivalence class's cardinality is 2
   2. follows from number theory
   3. cite:DBLP:journals/bsl/DurandJMM12
   #+END_exercise

   #+BEGIN_exercise
   TBD
   #+END_exercise

   #+BEGIN_exercise
   $G(f)=\{(\bar{x},\bar{y})\in M^{n+m}\mid\phi(\bar{x},\bar{y})\}$ and 
   $G(g)=\{(\bar{y},\bar{z})\in M^{m+l}\mid\psi(\bar{y},\bar{z})\}$. Hence
   $G(g\circ f)=\{(\bar{x},\bar{z})\in M^{n+l}\mid \phi(\bar{x},\bar{y})
   \wedge \psi(\bar{y},\bar{z})\}$
   #+END_exercise

   #+BEGIN_exercise
   $\phi(\bar{a},b)$ really defines a function and since 
   $\phi(\bar{a},y)\to y=b$
   #+END_exercise

* Basic Techniques
** The Compactness Theorem

   Some points of proofs
   * Proofs are finite
   * (Soundness) If \(T\vdash\phi\), then \(T\vDash\phi\)
   * If \(T\) is a finite set of sentences, then there is an algorithm that,
     when given a sequence of \(\call\)-formulas \sigma and an \(\call\)-sentence \phi,
     will decide whether \sigma is a proof of \phi from $T$

   [[index:recursive]]
   A language $\call$ is *recursive* if there is an algorithm that decides
   whether a sequence of symbols is an \(\call\)-formula. An \(\call\)-theory
   $T$ is *recursive* if there is an algorithm that when given an
   \(\call\)-sentence \phi as input, decides whether $\phi\in T$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.1.1
   If \(\call\) is a recursive language and $T$ is a recursive \(\call\)-theory,
   then $\{\phi:T\vdash\phi\}$ is recursively enumerable; that is, there is an
   algorithm that when given \phi as input will halt accepting if $T\vdash\phi$
   and not halt if $T\not\vdash\phi$
   #+END_proposition
   #+BEGIN_proof
   There is $\sigma_0,\sigma_1,\dots$ a computable listing of all finite
   sequence of \(\call\)-formulas. At stage $i$, we check to see whether
   $\sigma_i$ is a proof of \psi from $T$. If it is, then halt.
   #+END_proof

   #+ATTR_LATEX: :options [Gödel's Completeness Theorem]
   #+BEGIN_theorem
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence, then
   $T\vDash\phi$ if and only if $T\vdash \phi$
   #+END_theorem

   We say that an \(\call\)-theory $T$ is *inconsistent* if
   $T\vdash(\phi\wedge\neg\phi)$ for some sentence \phi.

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $T$ is consistent if and only if $T$ is satisfiable
   #+END_corollary

   #+BEGIN_proof
   Supose that $T$ is not satisfiable, then every model of $T$ is a model of
   $\phi\wedge\neg\phi$. Thus by the Completeness theorem
   $T\vdash(\phi\wedge\neg\phi)$ 
   #+END_proof


   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   $T$ is satisfiable if and only if every finite subset of $T$ is satisfiable
   #+END_theorem

   #+BEGIN_proof
   If $T$ is not satisfiable, then $T$ is inconsistent. Let \sigma be a proof of
   a contradiction from  $T$. Because \sigma is finite, only finitely many
   assumptions from $T$ are used in the proof. Thus there is a finite
   $T_0\subseteq T$ s.t. \sigma is a proof of a contradiction from $T_0$
   #+END_proof

*** Henkin Constructions
    [[index:finitely satisfiable]]
    A theory $T$ is *finitely satisfiable* if every finite subset of $T$ is
    satisfiable. We will show that every finitely satisfiable theory $T$ is
    satisfiable.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that an \(\call\)-theory $T$ has the *witness property* if whenever
    $\phi(v)$ is an \(\call\)-formula with one free variable $v$, then there is
    a constant symbol $c\in\call$ s.t. $T\vdash(\exists v\phi(v))\to\phi(c)\in T$

    An \(\call\)-theory $T$ is *maximal* if for all $\phi$ either $\phi\in T$ or
    $\neg\phi\in T$
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.6
    Suppose $T$ is a maximal and finitely satisfiable \(\call\)-theory. If
    $\Delta\subseteq T$ is finite and $\Delta\vDash\psi$, then $\psi\in T$
    #+END_lemma

    #+BEGIN_proof
    If $\psi\not\in T$, then $\neg\psi\in T$ but $\Delta\cup\{\psi\}$ is
    unsatisfiable 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.7
    Suppose that $T$ is a maximal and finitely satisfiable \(\call\)-theory with
    the witness property. Then $T$ has a model. In fact, if \kappa is a cardinal
    and \(\call\) has at most \kappa constant symbols, then there is
    $\calm\vDash T$ with $\abs{\calm}\le\kappa$
    #+END_lemma
    
    #+BEGIN_proof
    Let $\calc$ be the set of constant symbols of \(\call\). For $c,d\in\calc$,
    we say $c\sim d$ if $c=d\in T$

    *Claim 1* $\sim$ is an equivalence relation. 

    The universe of our model will be $M=\calc/\sim$. Clearly
    $\abs{M}\le\kappa$. We let $c^*$ denote the equivalence class of $c$ and
    interprete $c$ as its equivalence class, that is, $c^{\calm}=c^*$

    Suppose that $R$ is an \(n\)-ary relation symbol of \(\call\)

    *Claim 2* Suppose that $c_1,\dots,c_n,d_1,\dots,d_n\in\calc$ and $c_i\sim d_i$
    for $i=1,\dots,n$, then $R(\bar{c})$ if and only if $R(\bar{d})$

    By Lemma ref:lemma2.1.6, if one of \(R(\bar{c})\) and \(R(\bar{d})\) is
    in $T$, then both are in $T$

    
    \begin{equation*}
    R^{\calm}=\{(c_1^*,\dots,c_n^*):R(c_1,\dots,c_n)\in T\}
    \end{equation*}
    Suppose that $f$ is an \(n\)-ary function symbol of \(\call\) and
    $c_1,\dots,c_n\in\calc$. Because  $\underline{\emptyset\vDash\exists
    vf(c_1,\dots,c_n)=v}$, and $T$ has the witness property, then there is
    $c_{n+1}\in\calc$ s.t. $f(c_1,\dots,c_n)=c_{n+1}\in T$. As above, if
    $d_i\sim c_i$ for $i=1,\dots,n+1$, then $f(d_1,\dots,d_n)=d_{n+1}\in T$.
    Thus we get a well-defined function $f^{\calm}:M^n\to M$ by
    \begin{equation*}
    f^{\calm}(c_1^*,\dots,c_n^*)=d^*\text{ if and only if }f(c_1,\dots,c_n)=d\in T
    \end{equation*}

    *Claim 3* Suppose that $t$ is a term using free variables from
    $v_1,\dots,v_n$. If $c_1,\dots,c_n,d\in\calc$, then $t(c_1,\dots,c_n)=d\in
    T$ if and only if $t^{\calm}(c_1^*,\dots,c_n^*)=d^*$

    (\(\Rightarrow\)) If \(t\) is a constant symbol, then \(c=d\in T\) and
    \(c^{\calm}=c^*=d^*\)

    If \(t\) is the variable \(v_i\), then \(c_i=d\in T\) and 
    \(t^{\calm}(c_1^*,\dots,c_n^*)=c_i^*=d^*\)

    Suppose that the claim is true for \(t_1,\dots,t_m\) and \(t\) is
    \(f(t_1,\dots,t_m)\). Using the witness property and Lemma ref:lemma2.1.6,
    we can find \(d,d_1,\dots,d_n\in\calc\) s.t. \(t_i(c_1,\dots,c_n)=d_i\in T\)
    for \(i\le m\) and \(f(d_1,\dots,d_m)=d\in T\). By our induction hypothesis, 
    \(t_i^{\calm}(c_1^*,\dots,c_n^*)=d_i^*\) and
    \(f^{\calm}(d_1^*,\dots,d_m^*)=d^*\). Thus \(t^{\calm}(c_1^*,\dots,c_n^*)=d^*\)

    ($\Leftarrow$) Suppose $t^{\calm}(c_1^*,\dots,c_n^*)=d^*$. By the witness
    property, there is a $e\in\calc$ s.t. $t(c_1,\dots,c_n)=e\in T$. Using the
    $(\Rightarrow)$ direction of the proof, $t^{\calm}(c_1^*,\dots,c_n^*)=e^*$.
    Thus $e^*=d^*$ and $e=d\in T$


    *Claim 4* For all \(\call\)-formulas $\phi(v_1,\dots,v_n)$ and
    $c_1,\dots,c_n\in\calc$, $\calm\vDash\phi(\bar{c}^*)$ if and only if
    $\phi(\bar{c})\in T$

    Suppose that \(\phi\) is \(t_1=t_2\). By Lemma ref:lemma2.1.6 and the
    witness property, we can find \(d_1\) and \(d_2\) s.t. 
    \(t_1(\bar{c})=d_1,t_2(\bar{c})=d_2\in T\). By Claim 3,
    \(t_i^{\calm}(\bar{c}^*)=d_i^*\). Then
    \begin{align*}
    \calm\vDash\phi(\bar{c}^*)&\Leftrightarrow d_1^*=d_2^*\\
    &\Leftrightarrow d_1=d_2\in T\\
    &\Leftrightarrow t_1(\bar{c})=t_2(\bar{c})\in T
    \end{align*}

    Suppose that \phi is \(R(t_1,\dots,t_m)\). There are \(d_1,\dots,d_m\in\calc\)
    s.t. \(t_i(\bar{c})=d_i\in T\). Thus
    \begin{align*}
    \calm\vDash\phi(\bar{c}^*)&\Leftrightarrow \bar{d}^*\in R^{\calm}\\
    &\Leftrightarrow R(\bar{d})\in T\\
    &\Leftrightarrow\phi(\bar{c})\in T
    \end{align*}
    
    Suppose that the claim is true for \phi. If
    \(\calm\vDash\neg\phi(\bar{c}^*)\), then
    \(\calm\not\vDash\phi(\bar{c}^*)\). By the inductive hypothesis,
    \(\phi(\bar{c})\not\in T\). Thus by maximality, \(\neg\phi(\bar{c})\in T\). On
    the other hand, if \(\neg\phi(\bar{c})\in T\), then because $T$ is finitely
    satisfiable, \(\phi(\bar{c})\not\in T\). Thus, by induction,
    \(\calm\not\vDash\phi(\bar{c}^*)\).

    
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.8
    Let $T$ be a finitely satisfiable \(\call\)-theory. There is a language
    $\call^*\supseteq\call$ and $T^*\supseteq T$ a finitely satisfiable
    \(\call^*\)-theory s.t. any \(\call^*\)-theory extending $T^*$ has the
    witness property. We can choose $\call^*$ s.t.
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_lemma

    #+BEGIN_proof
    We first show that there is a language $\call_1\supseteq\call$ and a
    finitely satisfiable \(\call_1\)-theory $\call_1\supseteq T$ s.t. for any
    \(\call\)-formula $\phi(v)$ there is an \(\call_1\)-constant symbol $c$ s.t.
    $T_1\vDash(\exists v\phi(v))\to\phi(c)$. For each \(\call\)-formula
    $\phi(v)$, let $c_\phi$ be a new constant symbol and let
    $\call_1=\call\cup\{c_\phi:\phi(v)\text{ an }\call\text{-formula}\}$. For
    each \(\call\)-formula $\phi(v)$, let $\Theta_\phi$ be the
    \(\call_1\)-sentence
    $(\exists v\phi(v))\to\phi(c_\phi)$. Let
    $T_1=T\cup\{\Theta_\phi:\phi(v)\text{ an }\call\text{-formula}\}$

    *Claim* $T_1$ is finitely satisfiable

    Suppose that $\Delta$ is a finite subset of $T_1$. Then
    $\Delta=\Delta_0\cup\{\Theta_{\phi_1},\dots, \Theta_{\phi_n}\}$ where
    $\Delta_0$ is a finite subset of $T$ and there is $\calm\vDash\Delta_0$. We
    will make $\calm$ into an
    \(\call\cup\{c_{\phi_1},\dots,c_{\phi_n}\}\)-structure $\calm'$. If
    $\calm\vDash\exists v\phi(v)$, choose $a_i$ some element of $M$ s.t.
    $\calm\vDash\phi(a_i)$ and let $c_{\phi_i}^{\calm'}=a_i$. Otherwise, let
    $c_{\phi_i}^{\calm'}$ be any element of $\calm$. Clearly
    $\calm'\vDash\Theta_{\phi_i}$ for $i\le n$. Thus $T_1$ is finitely
    satisfiable.

    We now iterate the construction above to build a sequence of languages
    $\call\subseteq\call_1\subseteq\call_2\subseteq\dots$ and a sequence of
    finitely satisfiable \(\call_i\)-theories $T\subseteq T_1\subseteq
    T_2\subseteq\dots$ s.t. if $\phi(v)$ is an \(\call_i\)-formula then there is
    a constant symbol $c\in\call_{i+1}$ s.t. $T_{i+1}\vDash(\exists
    v\phi(v))\to\phi(c)$

    Let $\call^*=\bigcup\call_i$ and $T^*=\bigcup T_i$. 
    If \(\abs{\call_i}\) is the number of relation, function and constant
    symbols in \(\call_i\), then there are at most \(\abs{\call_i}+\aleph_0\)
    formulas in \(\call_i\).
    Thus by induction,
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:2.1.9
    Suppose that $T$ is a finitely satisfiable \(\call\)-theory and \phi is an
    \(\call\)-sentence, then either $T\cup\{\phi\}$ or $T\cup\{\neg\phi\}$ is
    finitely satisfiable
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor2.1.10
    If $T$ is a finitely satisfiable \(\call\)-theory, then there is a maximal
    finitely satisfiable \(\call\)-theory $T'\supseteq T$
    #+END_corollary
    #+BEGIN_proof
    Let $I$ be the set of all finitely satisfiable \(\call\)-theory containing
    $T$. We partially order $I$ by inclusion. If $C\subseteq I$ is a chain, let
    $T_C=\bigcup\{\Sigma:\Sigma\in C\}$. If $\Delta$ is a finite subset of
    $T_C$, then there is a $\Sigma\in C$ s.t. $\Delta\subseteq\Sigma$, so $T_C$
    is finitely satisfiable and $T_C\supseteq\Sigma$ for all $\Sigma\in C$. Thus
    every chain in $I$ has an upper bound, and we can apply Zorn's lemma to find
    a $T'\in I$ maximal w.r.t. the partial order.
    #+END_proof


    #+ATTR_LATEX: :options [strengthening of Compactness Theorem]
    #+BEGIN_theorem
    label:thm2.1.11
    If $T$ is a finitely satisfiable \(\call\)-theory and \kappa is an infinite
    cardinal with $\kappa\ge\abs{\call}$, then there is a model of $T$ of
    cardinality at most \kappa
    #+END_theorem

    #+BEGIN_proof
    By Lemma ref:lemma2.1.8, we can find \(\call^*\supseteq\call\) and 
    \(T^*\supseteq T\) a finitely satisfiable \(\call^*\)-theory s.t. any
    \(\call^*\)-theory extending \(T^*\) has the witness property and the
    cardinality of \(\call^*\) is at most \kappa. By Corollary ref:cor2.1.10, we can
    find a maximal finitely satisfiable \(\call^*\)-theory 
    \(T'\supseteq T^*\). Because \(T'\) has the witness property, Lemma
    ref:lemma2.1.7 ensures that there is \(\calm\vDash T\) with \(\abs{M}\le\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let $\call=\{\cdot,+,<,0,1\}$ and let $\Th(\N)$ be the full \(\call\)-theory
    of the natural numbers. There is $\calm\vDash\Th(\N)$ and $a\in M$ s.t. $a$
    is larger than every natural number
    #+END_proposition

    #+BEGIN_proof
    Let $\call^*=\call\cup\{c\}$ where $c$ is a new constant symbol and let
    \begin{equation*}
    T=\Th(\N)\cup\{\underbrace{1+1+\dots+1}_{n\text{-times}}<c:\text{for }n=1,2,\dots\} 
    \end{equation*}
    If $\Delta$ is a finite subset of $T$ we can make $\N$ a model of $\Delta$ by
    interpreting $c$ as a suitably large natural number. Thus $T$ is finitely
    satisfiable and there is $\calm\vDash T$.
    #+END_proof
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.14
    If $T\vDash\phi$, then $\Delta\vDash T$ for some finite $\Delta\subseteq T$
    #+END_lemma
    #+BEGIN_proof
    Suppose not. Let $\Delta\subseteq T$ be finite. Because
    $\Delta\not\vDash\phi$, $\Delta\cup\{\neg\phi\}$ is satisfiable. Thus
    $T\cup\{\neg\phi\}$ is finitely satisfiable and by the compactness theorem,
    $T\not\vDash\phi$ 
    #+END_proof


    
** Complete Theories
   [[index:complete]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-theory $T$ is called *complete* if for any \(\call\)-sentence \phi
   either $T\vDash\phi$ or $T\vDash\neg\phi$
   #+END_definition

   For $\calm$ an \(\call\)-structure, then the full theory
   \begin{equation*}
   \Th(\calm)=\{\phi:\phi\text{ is an }\call\text{-sentence and }
   \calm\vDash\phi\}
   \end{equation*}
   is a complete theory.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.2
   Let $T$ be an \(\call\)-theory with infinite models. If \kappa is an infinite
   cardinal and $\kappa\ge\abs{\call}$, then there is a model of $T$ of
   cardinality \kappa
   #+END_proposition

   #+BEGIN_proof
   Let $\call^*=\call\cup\{c_\alpha:\alpha<\kappa\}$, where each $c_\alpha$ is
   new constant symbol, and let $T^*$ be the \(\call^*\)-theory
   $T\cup\{c_\alpha\neq c_\beta:\alpha,\beta<\kappa,\alpha\neq\beta\}$. Clearly
   if $\calm\vDash T^*$, then $\calm$ is a model of $T$ of cardinality at least
   \kappa.
   Thus by Theorem ref:thm2.1.11, it suffices to show that $T^*$ is finitely
   satisfiable. But if $\Delta\subseteq T^*$ is finite, then $\Delta\subseteq
   T\cup\{c_\alpha\neq c_\beta:\alpha\neq\beta,\alpha,\beta\in I\}$, where $I$
   is a finite subset of \kappa. Let $\calm$ be an infinite model of $T$. We can
   interpret the symbols $\{c_\alpha:\alpha\in I\}$ as $\abs{I}$ distinct
   elements of $M$. Because $\calm\vDash\Delta$, $T^*$ is finitely satisfiable.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal and let $T$ be a theory with models of
   size \kappa. We say that $T$ is *\kappa-categorical* if any two models of
   $T$ of cardinality \kappa are isomorphic.
   #+END_definition

   Let $\call=\{+,0\}$ be the language of additive groups and let $T$ be the
   \(\call\)-theory of torsion-free divisible Abelian groups. The axioms of $T$
   are the axioms for Abelian groups together with the axioms
   \begin{gather*}
   \forall x(x\neq 0\to\underbrace{x+\dots+x}_{n\text{-times}}\neq 0)\\
   \forall y\exists x\underbrace{x+\dots+x}_{n\text{-times}}=y
   \end{gather*}
   for $n=1,2,\dots$

   
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The theory of torsion-free divisible Abelian groups is \kappa-categorical for
   all $\kappa>\aleph_0$
   #+END_proposition

   #+BEGIN_proof
   We first argue that models of $T$ are essentially vector spaces over the
   field of rational numbers $\Q$. If $V$ is any vector space over $\Q$, then
   the underlying additive group $V$ is a model of $T$. 
   Check [[https://math.stackexchange.com/questions/1550900/necessary-and-sufficient-conditions-for-an-abelian-group-to-be-a-vector-space-ov/1550954][StackExchange]].
   On the other hand, if
   \(G\vDash T\), \(g\in G\) and \(n\in\N\) with \(g>0\), we can find 
   \(h\in G\) s.t. \(nh=g\). If \(nk=g\), then \(n(h-k)=0\). Because $G$ is
   torsion-free there is a unique \(h\in G\) s.t. \(nh=g\). We call this element 
   \(g/n\). We can view $G$ as a \(\Q\)-vector space under the action
   \(\frac{m}{n}g=m(g/n)\)

   Two \(\Q\)-vector spaces are isomorphic if and only if they have the same
   dimension. Thus the model of $T$ are determined up to isomorphism by their
   dimension. If \(G\) has dimension \lambda, then \(\abs{G}=\lambda+\aleph_0\). If \kappa
   is uncountable and $G$ has cardinality \kappa, then $G$ has dimension \kappa. Thus for
   \(\kappa>\aleph_0\) any two models of $T$ of cardinality \kappa are isomorphic
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemmamy1
   Field of uncountable cardinality \kappa has transcendence degree \kappa
   [fn:proofkappa]
   #+END_lemma

   #+BEGIN_proof
   We prove the theorem for fields with characteristic \(p=0\). 

   Since each characteristic 0 field contains a copy of \(\Q\) as its prime
   field, we can view $F$ as a field extension over \(\Q\). We will show that
   $F$ has a subset of cardinality \kappa which is algebraically independent over
   \(\Q\).

   We build the claimed subset of $F$ by transfinite induction and implicit use
   of the axiom of choice.

   Let \(S_0=\emptyset\)

   Let \(S_1\) be a singleton containing some element of $F$ which is not
   algebraic over \(\Q\). This is possible since algebraic numbers are countable

   Define \(S_{\alpha+1}\) to be \(S_\alpha\) together with an element of $F$
   which is not a root of any non-trivial polynomial with coefficients in 
   \(\Q\cup S_\alpha\) since there are only 
   \(\abs{\Q\cup S_\alpha}=\aleph_0+\abs{\alpha}<\kappa\) polynomials

   Define \(S_\beta=\displaystyle\bigcup_{\alpha<\beta}S_\alpha\)
   
   Let \(P(x_1,\dots,x_n)\) be a non-trivial polynomial with coefficients in
   \(\Q\) and elements \(a_1,\dots,a_n\) in $F$. W.L.O.G., it is assumed that
   \(a_n\) was added at an ordinal \(\alpha+1\) later than the other elements.
   Then \(P(a_1,\dots,a_{n-1},x_n)\) is a polynomial with coefficients in 
   \(\Q\cup S_\alpha\). Hence \(P(a_1,\dots,a_n)\neq0\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.5
   \(\ACF_p\) is \kappa-categorical for all uncountable cardinals \kappa
   #+END_proposition

   #+BEGIN_proof
   Two algebraically closed fields are isomorphic if and only if they have the
   same characteristic and transcendence degree. See
   [[file:AdvancedModernAlgebra.org::Application of Zorn's Lemma]]. By Lemma
   ref:lemmamy1, an algebraically closed field of transcendence degree \lambda has
   cardinality \(\lambda+\aleph_0\).
   #+END_proof

   #+ATTR_LATEX: :options [Vaught's Test]
   #+BEGIN_theorem
   label:thm2.2.6
   Let $T$ be a satisfiable theory with no finite models that is
   \kappa-categorical for some infinite cardinal \(\kappa\ge\abs{\call}\). Then
   $T$ is complete
   #+END_theorem

   #+BEGIN_proof
   Suppose $T$ is not complete. Then there is a sentence \phi s.t. 
   \(T\not\vDash\phi\) and \(T\not\vDash\neg\phi\). Because
   \(T\not\vDash\psi\) if and only if \(T\cup\{\neg\psi\}\) is satisfiable, the
   theories \(T_0=T\cup\{\phi\}\) and \(T_1=T\cup\{\neg\phi\}\) are satisfiable.
   Because $T$ has no finite models, both \(T_0\) and \(T_1\) have infinite
   models. By Proposition ref:prop2.2.2 we can find \(\calm_0\) and
   \(\calm_1\) of cardinality \kappa with \(\calm_i\vDash T_i\). Because \(\calm_0\)
   and \(\calm_1\) disagree about \phi, they are not elementarily equivalent, and
   hence by Theorem ref:thm1.1.10, nonisomorphic. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that an \(\call\)-theory $T$ is *decidable* if there is an algorithm
   that when given an \(\call\)-sentence \phi as input decides whether \(T\vDash\phi\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.2.8
   Let $T$ be a recursive complete satisfiable theory in a recursive language
   \(\call\). Then $T$ is decidable
   #+END_lemma

   #+BEGIN_proof
   Because $T$ is satisfiable \(A=\{\phi:T\vDash\phi\}\) and
   \(B=\{\phi:T\vDash\neg\phi\}\) are disjoint. Because $T$ is consistent 
   \(A\cup B\) is the set of all \(\call\)-sentences. By the Completeness
   Theorem, \(A=\{\phi:T\vdash\phi\}\) and \(B=\{\phi:T\vdash\neg\phi\}\). By
   Proposition ref:prop2.1.1 $A$ and $B$ are recursively enumerable. But any
   recursively enumerable set with a recursively enumerable complement is
   recursive. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   For $p=0$ or $p$ prime, \(ACF_p\) is decidable. In particular, \(\Th(\C)\),
   the first-order theory  of the field of complex numbers, is decidable
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \phi be a sentence in the language of rings. The following are equivalent
   1. \phi is true in the complex number
   2. \phi is true in every algebraically closed field of characteristic zero
   3. \phi is true in some algebraically closed field of characteristic zero
   4. There are arbitrarily large primes $p$ s.t. \phi is true in some
      algebraically closed field of characteristic $p$
   5. There is an $m$ s.t. for all \(p>m\), \phi is true in all algebraically
      closed fields of characteristic $p$
   #+END_corollary

   #+BEGIN_proof
   By Proposition ref:prop2.2.5 and Vaught's Test, \(\ACF_p\) is complete.

   \((2)\to(5)\). Suppose that \(\ACF_0\vDash\phi\). By Lemma ref:lemma2.1.14,
   there is a finite \(\Delta\subseteq\ACF_0\) s.t. \(\Delta\vDash\phi\). Thus
   if we choose \(p\) large enough, then \(\ACF_p\vDash\Delta\).

   \((4)\to(2)\). Suppose \(\ACF_0\not\vDash\phi\). Because \(\ACF_0\) is
   complete, \(\ACF_0\vDash\neg\phi\).
   #+END_proof
   
** Up and Down

   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \(\calm\) and \(\caln\) are \(\call\)-structures, then an
   \(\call\)-embedding \(j:\calm\to\caln\) is called an *elementary embedding* if
   \begin{equation*}
   \calm\vDash\phi(a_1,\dots,a_n)\leftrightarrow\caln\vDash\phi(j(a_1),\dots,j(a_n))
   \end{equation*}
   for all \(\call\)-formulas \(\phi(v_1,\dots,v_n)\) and all \(a_1,\dots,a_n\in
   M\)

   If \(\calm\) is a substructure of \(\caln\), we say that it is an *elementary
   substructure* and write \(\calm\prec\caln\) if the inclusion map is elementary.
   \(\caln\) is an *elementary extension* of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \(\calm\) is an \(\call\)-structure. Let \(\call_M\) be the language where we
   add to \(\call\) constant symbols \(m\) for each element of $M$. The *atomic
   diagram* of \(\calm\) is
   \(\{\phi(m_1,\dots,m_n):\phi\) is either an atomic \(\call\)-formula or the negation of an atomic
   \(\call\)-formula and
   \(\calm\vDash\phi(m_1,\dots.m_n)\}\).
   The *elementary diagram* of $\calm$ is 
   \begin{equation*}
   \{\phi(m_1,\dots,m_n):\calm\vDash\phi(m_1,\dots,m_n),\phi\text{ an 
   \(\call\)-formula}\}
   \end{equation*}

   We let \(\Diag(\calm)\) and \(\Diag_{\el}(\calm)\) denote the atomic and
   elementary diagrams of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.3.3
   1. Suppose that \(\caln\) is an \(\call_M\)-structure and
      \(\caln\vDash\Diag(\calm)\), then viewing \(\caln\) as an
      \(\call\)-structure, there is an \(\call\)-embedding of \(\calm\) into \(\caln\)
   2. If \(\caln\vDash\Diag_{\el}(\calm)\), then there is an elementary
      embedding of \(\calm\) into \(\caln\)
   #+END_lemma

   #+BEGIN_proof
   1. Let \(j:M\to N\) by \(j(m)=m^{\caln}\). If \(m_1\neq m_2\in\Diag(\calm)\);
      thus \(j(m_1)\neq j(m_2)\) so $j$ is an embedding. If \(f\) is a function
      symbols of \(\call\) and \(f^{\calm}(m_1,\dots,m_n)=m_{n+1}\), then
      \(f(m_1,\dots,m_n)=m_{n+1}\) is a formula in \(\Diag(\calm)\) and 
      \(f^{\caln}(j(m_1),\dots,j(m_n))=j(m_{n+1})\). If \(R\) is a relation symbol
      and \(\bar{m}\in R^{\calm}\), then \(R(m_1,\dots,m_n)\in\Diag(\calm)\) and 
      \((j(m_1),\dots,j(m_{n}))\in R^{\caln}\). Hence \(j\) is an
      \(\call\)-embedding
   2. $j$ is elementary.

   #+END_proof

   #+ATTR_LATEX: :options [Upward Löwenheim–Skolem Theorem]
   #+BEGIN_theorem
   Let \(\calm\) be an infinite \(\call\)-structure and \kappa be an infinite
   cardinal \(\kappa\ge\abs{\calm}+\abs{\call}\). Then, there is \(\caln\) an
   \(\call\)-structure of cardinality \kappa and \(j:\calm\to\caln\) is elementary
   #+END_theorem

   #+BEGIN_proof
   Because \(\calm\vDash\Diag_{\el}(\calm)\), \(\Diag_{\el}(\calm)\) is
   satisfiable. By Theorem ref:thm2.1.11, there is
   \(\caln\vDash\Diag_{\el}(\calm)\) of cardinality \kappa. By Lemma ref:lemma2.3.3,
   there is an elementary \(j:\calm\to\caln\)
   #+END_proof

   #+ATTR_LATEX: :options [Tarski-Vaught Test]
   #+BEGIN_proposition
   label:prop2.3.5
   Suppose that \(\calm\) is a substructure of \(\caln\). Then \(\calm\) is an
   elementary substructure if and only if, for any formula \(\phi(v,\bar{w})\) and 
   \(\bar{a}\in M\), if there is \(b\in N\) s.t.
   \(\caln\vDash\phi(b,\bar{a})\), then there is \(c\in M\) s.t.
   \(\caln\vDash\phi(c,\bar{a})\) 
   #+END_proposition

   #+BEGIN_proof
   We need to show that for all \(\bar{a}\in M\) and all \(\call\)-formulas
   \(\psi(\bar{v})\)
   \begin{equation*}
   \calm\vDash\psi(\bar{a})\Leftrightarrow\caln\vDash\psi(\bar{a})
   \end{equation*}

   In Proposition ref:prop1.1.8, we showed that if \(\phi(\bar{v})\) is quantifier
   free then \(\calm\vDash\phi(\bar{a})\) if and only if \(\phi(\bar{a})\)
   #+END_proof

   We say that an \(\call\)-theory $T$ has *built-in Skolem functions* if for all
   \(\call\)-formulas \(\phi(v,w_1,\dots,w_n)\) there is a function symbol $f$ s.t.
   \(T\vDash\forall\bar{w}((\exists v\phi(v,\bar{w}))\to\phi(f(\bar{w}),\bar{w}))\). In other words, there are
   enough function symbols in the language to witness all existential statements.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.3.6
   Let \(T\) be an \(\call\)-theory. There are \(\call^*\supseteq\call\) and 
   \(T^*\supseteq T\) an \(\call^*\)-theory s.t. \(T^*\) has built-in Skolem
   functions, and if \(\calm\vDash T\), then we can expand \(\calm\) to 
   \(\calm^*\vDash T^*\). We can choose \(\call^*\) s.t.
   \(\abs{\call^*}=\abs{\call}+\aleph_0\).

   We call \(T^*\) a *skolemization* of $T$
   #+END_lemma

   #+BEGIN_proof
   We build a sequence of languages
   \(\call=\call_0\subseteq\call_1\subseteq\dots\) and \(\call_i\)-theories
   \(T_i\) s.t. \(T=T_0\subseteq T_1\subseteq\dots\)

   Given \(\call_i\), let
   \(\call_{i+1}=\call\cup\{f_\phi:\phi(v,w_1,\dots,w_n)\text{ an
   }\call_i\text{-formula},n=1,2,\dots\}\), 
   where \(f_\phi\) is an \(n\)-ary function symbol. For \(\phi(v,\bar{w})\) an
   \(\call_i\)-formula, let \(\Psi_\phi\) be the sentence
   \begin{equation*}
   \forall\bar{w}((\exists v\phi(v,\bar{w}))\to\phi(f_\phi(\bar{w}),\bar{w}))
   \end{equation*}
   and let \(T_{i+1}=T_i\cup\{\Psi_\phi:\phi\text{ an }\call_i\text{-formula}\}\)

   *Claim* If \(\calm\vDash T_i\), then we can interpret the function symbols of
   \(\call_{i+1}\backslash\call_i\) so that \(\calm\vDash T_{i+1}\)

   Let \(c\) be some fixed element of $M$. If \(\phi(v,w_1,\dots,w_n)\) is an
   \(\call_i\)-formula, we find a function \(g:M^n\to M\) s.t. 
   \(\bar{a}\in M^n\) and \(X_{\bar{a}}=\{b\in M:\calm\vDash\phi(b,\bar{a})\}\)
   is nonempty, then \(g(\bar{a})\in X_{\bar{a}}\), and if
   \(X_{\bar{a}}=\emptyset\), then \(g(\bar{a})=c\). Thus if 
   \(\calm\vDash\exists v\phi(v,\bar{a})\), then
   \(\calm\vDash\phi(g(\bar{a}),\bar{a})\). If we interpret \(f_\phi\) as
   \(g\), then \(\calm\vDash\Psi_\phi\)

   Let \(\call^*=\bigcup\call_i\) and \(T^*=\bigcup T_i\). If \(\phi(v,\bar{w})\)
   is an \(\call^*\)-formula, then \(\phi\in\call_i\) for some $i$ and 
   \(\Psi_\phi\in T_{i+1}\subseteq T^*\), so \(T^*\) has built in Skolem
   functions. By iterating the claim, we see that for any \(\calm\vDash T\) we
   can interpret the symbols of \(\call^*\backslash\call\) to make
   \(\calm\vDash T^*\)

   \(\abs{\call_{i+1}}=\abs{\call_i}+\aleph_0\)

   #+END_proof

   #+ATTR_LATEX: :options [Löwenheim–Skolem Theorem]
   #+BEGIN_theorem
   Suppose that \(\calm\) is an \(\call\)-structure and \(X\subseteq M\), there
   is an elementary submodel \(\caln\) of \(\calm\) s.t. \(X\subseteq N\) and 
   \(\abs{\caln}\le\abs{X}+\abs{\call}+\aleph_0\)
   #+END_theorem

   #+BEGIN_proof
   By Lemma ref:lemma2.3.6, we may assume that \(\Th(\calm)\) has built in
   Skolem functions (otherwise we may extend \(\call\) to some \(\call^*\)). Let
   \(X_0=X\). Given \(X_i\), let \(X_{i+1}=X_i\cup\{f^{\calm}(\bar{a}):f\text{ an
   }n\text{-ary function symbol},\bar{a}\in X^n_i,n=1,2,\dots\}\). Let
   \(N=\bigcup X_i\), then \(\abs{N}\le\abs{X}+\abs{\call}+\aleph_0\)
   If \(f\) is an \(n\)-ary function symbol of \(\call\) and \(\bar{a}\in N^n\),
   then \(\bar{a}\in X^n_i\) for some $i$ and 
   \(f^{\calm}(\bar{a})\in X_{i+1}\subseteq N\). Thus \(f^{\calm}|N:N^n\to N\). Thus
   we can interpret \(f\) as \(f^{\caln}=f^{\calm}|N^n\). If $R$ is an \(n\)-ary
   relation symbol, let \(R^{\caln}=R^{\calm}\cap N^n\). If \(c\) is a constant
   symbol of \(\call\), there is a Skolem function \(f\in\call\) s.t. 
   \(f(x)=c^{\calm}\) for all \(x\in M\) (for example, \(f\) is the Skolem
   function for the formula \(v=c\)) . Thus \(c^{\caln}\in N\)

   If \(\phi(v,\bar{w})\) is any \(\call\)-formula, \(\bar{a},b\in M\) and
   \(\calm\vDash\phi(b,\bar{a})\), then
   \(\calm\vDash\phi(f(\bar{a}),\bar{a})\) for some function symbol \(f\) of
   \(\call\). By construction, \(f^{\calm}(\bar{a})\in N\). Thus by Proposition
   ref:prop2.3.5 \(\caln\prec\calm\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *universal sentence* is one of the form \(\forall\bar{v}\phi(\bar{v})\), where
   \phi is quantifier-free. We say that an \(\call\)-theory $T$ has a *universal
   axiomatization* if there is a set of universal \(\call\)-sentences \Gamma s.t. 
   \(\calm\vDash\Gamma\) if and only if \(\calm\vDash T\) for all
   \(\call\)-structures \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   An \(\call\)-theory $T$ has a universal axiomatization if and only if
   whenever \(\calm\vDash T\) and \(\caln\) is a substructure of \(\calm\),
   then \(\caln\vDash T\). In other words, a theory is preserved under
   substructure if and only if it has a universal axiomatization
   #+END_theorem

   #+BEGIN_proof
   Suppose that \(\caln\subseteq\calm\). By Proposition ref:prop1.1.8, if
   \(\phi(\bar{v})\) is a quantifier-free formula and \(\bar{a}\in N\), then
   \(\caln\vDash\phi(\bar{a})\) if and only if \(\phi(\bar{a})\). Thus if
   \(\calm\vDash\forall\bar{v}\phi(\bar{v})\), then so does \(\caln\)

   Suppose that \(T\) is preserved under substructures. Let
   \(\Gamma=\{\phi:\phi\text{ is universal and }T\vDash\phi\}\). Clearly, if
   \(\caln\vDash T\), then \(\caln\vDash\Gamma\). For the other direction,
   suppose that \(\caln\vDash\Gamma\). We claim that \(\caln\vDash T\)

   *Claim* \(T\cup\Diag(\caln)\) is satisfiable

   Suppose not. Then, by the Compactness Theorem, there is a finite
   \(\Delta\subseteq\Diag(\caln)\) s.t. \(T\cup\Delta\) is not satisfiable. Let
   \(\Delta=\{\psi_1,\dots,\psi_n\}\). Let \(\bar{c}\) be the new constant
   symbols from \(N\) used in \(\psi_1,\dots,\psi_n\) and say
   \(\psi_i=\phi_i(\bar{c})\), where \(\phi_i\) is a quantifier-free
   \(\call\)-formula. Because the constants in \(\bar{c}\) do not occur in $T$, if
   there is a model of \(T\cup\{\exists\bar{v}\bigwedge\phi_i(\bar{v})\}\), then
   by interpreting \(\bar{c}\) as witness to the existential formula,
   \(T\cup\Delta\) would be satisfiable. Thus
   \(T\vDash\forall\bar{v}\bigvee\neg\phi_i(\bar{v})\). As the latter formula
   is universal, \(\forall\bar{v}\bigvee\neg\phi_i(\bar{v})\in\Gamma\),
   contradicting \(\caln\vDash\Gamma.\)

   By Lemma ref:lemma2.3.3, there is \(\calm\vDash T\) with
   \(\calm\supseteq\caln\). Because $T$ is preserved under substructure,
   \(\caln\vDash T\) and \Gamma is a universal axiomatization
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose that \((I,<)\) is a linear order. Suppose that \(\calm_i\) is an
   \(\call\)-structure for \(i\in I\). We say that \((\calm_i:i\in I)\) is a
   chain of \(\call\)-strctures if \(\calm_i\subseteq\calm_j\) for \(i<j\). If
   \(\calm_i\prec\calm_j\) for \(i<j\), we call \((\calm_i:i\in I)\) an 
   *elementary chain*
   #+END_definition

   If \((\calm_i:i\in I)\) is a nonempty chain of structures, then we can define
   \(\calm=\bigcup_{i\in I}\calm_i\), the union of the chain, as follows. 
   \(M=\bigcup_{i\in I}M_i\). if \(c\) is a constant in the language, then
   \(c^{\calm_i}=c^{\calm_j}\) for all \(i,j\in I\). Let
   \(c^{\calm}=c^{\calm_i}\).

   Suppose that \(\bar{a}\in M\). Because $I$ is linearly ordered, we can find
   \(i\in I\) s.t. \(\bar{a}\in M_i\). If \(f\) is a function symbol of
   \(\call\) and \(i<j\), then \(f^{\calm_i}(\bar{a})=f^{\calm_j}(\bar{a})\).
   Thus \(f^{\calm}=\bigcup_{i\in I}f^{\calm_i}\) is a well-defined function.
   Similarly, \(R^{\calm}=\bigcup_{i\in I}R^{\calm_i}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.3.11
   Suppose that \((I,<)\) is a linear order and \((\calm_i:i\in I)\) is an
   elementary chain. Then \(\calm=\bigcup_{i\in I}\calm_i\) is an elementary
   extension of each \(\calm_i\)
   #+END_proposition

   #+BEGIN_proof
   We prove by induction on formulas that 
   \begin{equation*}
   \calm\vDash\phi(\bar{a})\Leftrightarrow\calm_i\vDash\phi(\bar{a})
   \end{equation*}
   for all \(i\in I\), all formulas \(\phi(\bar{v})\), and all \(\bar{a}\in M_i^n\) 

   Because \(\calm_i\) is a substructure of \(\calm\), by Proposition
   ref:prop1.1.8 this is true for all atomic \phi. \(\neg\phi\) and
   \(\phi\vee\psi\) is easy.

   Suppose that \(\phi\) is \(\exists v\psi(v,\bar{w})\) and the chain holds for
   \psi. If \(\calm_i\vDash\psi(b,\bar{a})\), then so does \(\calm\). Thus if
   \(\calm_i\vDash\phi(\bar{a})\), then so does \(\calm\). On the other hand,
   if \(\calm\vDash\psi(b,\bar{a})\), there is \(j\ge i\) s.t. \(b\in M_j\). By
   induction, \(\calm_j\vDash\psi(b,\bar{a})\), so
   \(\calm_j\vDash\phi(\bar{a})\). Because \(\calm_i\prec\calm_j\), \(\calm_i\vDash\phi(\bar{a})\)
   #+END_proof


** Back and Forth   

*** Dense Linear Orders
    Let \(\call=\{<\}\) and let DLO be the theory of dense linear orders without
    endpoints. DLO is axiomatized by the axioms for linear orders plus the
    axioms
    \begin{align*}
    &\forall x\forall y\;(x<y\to \exists z\;x<z<y)\\
    &\forall x\exists y\exists z\; y<x<z
    \end{align*}
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm2.4.1
    The theory DLO is \(\aleph_0\)-categorical and complete
    #+END_theorem

    #+BEGIN_proof
    Let \((A,<)\) and \((B,<)\) be two countable models of DLO. Let
    \(a_0,a_1,a_2,\dots\) and \(b_0,b_1,b_2,\dots\) be one-to-one enumerations
    of \(A\) and \(B\). We will build a sequence of partial bijections
    \(f_i:A_i\to B_i\) where \(A_i\subset A\) and \(B_i\subset B\) are finite
    s.t. \(f_0\subseteq f_1\subseteq\dots\) and if \(x,y\in A_i\) and \(x<y\),
    then \(f_i(x)<f_i(y)\). We call \(f_i\) a *partial embedding*. We will build
    these sequences s.t. \(A=\bigcup A_i\) and \(B=\bigcup B_i\). In this case,
    \(f=\bigcup f_i\) is the desired isomorphism from \((A,<)\) to \((B,<)\)

    At odd stages of the construction we will ensure that \(\bigcup A_i=A\), and
    at even stages we will ensure that \(\bigcup B_i=B\)

    _stage 0_: Let \(A_0=B_0=f_0=\emptyset\)

    _stage \(n+1=2m+1\)_: We will ensure that \(a_m\in A_{n+1}\).

    If \(a_m\in A_n\), then let \(A_{n+1}=A_n\), \(B_{n+1}=B_n\) and
    \(f_{n+1}=f_n\). Suppose that \(a_m\not\in A_n\). To add \(a_m\) to the
    domain of our partial embedding, we must find \(b\in B\backslash B_n\) s.t.
    \begin{equation*}
    \alpha<a_m\Leftrightarrow f_n(\alpha)<b
    \end{equation*}
    for all \(\alpha\in A_n\). In other words, we must find \(b\in B\), which is
    the image under \(f_n\) of the cut of \(a_m\) in \(A_n\). Exactly one of the
    following holds:
    1. \(a_m\) is greater than every element of \(A_n\), or
    2. \(a_m\) is than than every element of \(A_n\), or
    3. there are \alpha and \(\beta\in A_n\) s.t. \(\alpha<\beta\),\(\gamma\le\alpha\) or
       \(\gamma\ge\beta\) for all \(\gamma\in A_n\) and \(\alpha<a_m<\beta\)


    In case 1 because \(B_n\) is finite and \(B\vDash\DLO\),we can find 
    \(b\in B\) greater than every element of \(B_n\). Similar for case 2. In
    case 3, because \(f_n\) is a partial embedding, \(f_n(\alpha)<f_n(\beta)\) and we can
    choose \(b\in B_n\) s.t. \(f_n(\alpha)<b<f_n(\beta)\). Note that 
    \begin{equation*}
    \alpha<a_m\Leftrightarrow f_n(\alpha)<b
    \end{equation*}
    for all \(\alpha\in A_n\)

    _stage \(n+1=2m+2\)_: We will ensure \(b_m\in B_{n+1}\)

    Again, if \(b_m\) is already in \(B_n\), then we make no changes. Otherwise,
    we must find \(a\in A\) s.t. the image of the cut of \(a\) in \(A_n\) is the
    cut of \(b_m\) in \(B_n\). This is done in odd case.

    Clearly, at odd stages we have ensured that \(\bigcup A_n=A\) and at even
    stages we have ensured that \(\bigcup B_n=B\). Because each \(f_n\) is a
    partial embedding, \(f=\bigcup f_n\) is an isomorphism from \(A\) onto \(B\)

    But there are no finite dense linear orders, Vaught's test implies that DLO
    is complete
    #+END_proof

*** The Random Graph
    Let \(\call=\{R\}\), where $R$ is a binary relation symbol. We will consider
    an \(\call\)-theory containing the graph axioms \(\forall x\;\neg R(x,x)\) and 
    \(\forall x\forall y\; R(x,y)\to R(y,x)\). Let \(\psi_n\) be the "extension
    axiom"
    \begin{equation*}
    \forall x_1\dots\forall x_n\forall y_1\dots\forall y_n\;
    \left(\displaystyle\bigwedge_{i=1}^n\bigwedge_{j=1}^nx_1\neq y_j\to
    \exists z\;\bigwedge_{i=1}^n(R(x_i,z)\wedge\neg R(y_i,z))
    \right)
    \end{equation*}
    We let $T$ be the theory of graphs where we add 
    \(\{\exists x\exists y\; x\neq y\}\cup\{\psi_n:n=1,2,\dots\}\) to the graph
    axioms. A model of $T$ is a graph where for any finite disjoint sets \(X\)
    and \(Y\) we can find a vertex with edges going to every vertex in $X$ and
    no vertex in \(Y\)
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    $T$ is satisfiable and \(\aleph_0\)-categorical. In particular, $T$ is
    complete and decidable
    #+END_theorem
    #+BEGIN_proof
    We first build a countable model of $T$. Let \(G_0\) be any countable graph

    *Claim* There is a graph \(G_1\supseteq G_0\) s.t. \(G_1\) is countable and if
    \(X\) and $Y$are disjoint finite subsets of \(G_0\) then there is 
    \(z\in G_1\) s.t. \(R(x,z)\) for \(x\in X\) and \(\neg R(y,z)\) for \(y\in
    Y\)

    Let the vertices of \(G_1\) be the vertices of \(G_0\) plus new vertices
    \(z_X\) for each \(X\subseteq G_0\). The edges of \(G_1\) are the edges of
    \(G\) together  with new edges between \(x\) and \(z_X\) whenever 
    \(X\subseteq G_0\) is finite and \(x\in X\).

    We iterate this construction to build a sequence of countable graphs 
    \(G_0\subset G_1\subset\dots\) s.t. if \(X\) and \(Y\) are disjoint finite
    subsets of \(G_i\), then there is \(z\in G_{i+1}\) s.t. \(R(x,z)\) for
    \(x\in X\) and \(\neg R(y,z)\) for \(y\in Y\). Thus \(G=\bigcup G_n\) is a
    countable model of \(T\)

    Next we show that \(T\) is \(\aleph_0\)-categorical. Let \(G_1\) and \(G_2\)
    be countable models of \(T\). Let \(a_0,a_1,\dots\) list \(G_1\), and let
    \(b_0,b_1,\dots\) list \(G_2\). We will build a sequence of finite partial
    one-to-one maps \(f_0\subseteq f_1\subseteq f_2\subseteq\dots\) s.t. for all
    \(x,y\) in the doamin of \(f_s\),
    \begin{equation*}
    G_1\vDash R(x,y)\Leftrightarrow G_2\vDash R(f_s(x),f_s(y))
    \end{equation*}
    Let \(f_0=\emptyset\)
    _stage \(s+1=2i+1\)_: We make sure that \(a_i\) is in the domain
    
    If \(a_i\) is in the domain of \(f_s\), let \(f_{s+1}=f_s\). If not, let
    \(\alpha_1,\dots,\alpha_m\) list the domain of \(f_s\) and let 
    \(X=\{j\le m:R(\alpha_j,a_i)\}\) and let \(Y=\{j\le m:\neg
    R(\alpha_j,a_i)\}\). Because 
    \(G_2\vDash T\), we can find \(b\in G_2\) s.t. \(G_2\vDash
    R(f_s(\alpha_j),b)\) for \(j\in X\) and 
    \(G_2\vDash\neg R(f_s(\alpha_j),b)\) for \(j\in Y\). Let
    \(f_{s+1}=f_s\cup\{(a_i,b)\}\). 
    
    _stage \(s+1=2i+2\)_: Similar
    #+END_proof

    Let \(\calg_N\) be the set of all graphs with vertices \(\{1,2,\dots,N\}\).
    We consider a probability measure on \(\calg_N\) where we make all graphs
    equally likely. This is the same as constructing a random graph where we
    independently decide whether there is an edge between \(i\) and \(j\) with
    probability \(\frac{1}{2}\). For any \(\call\)-sentence \phi,
    \begin{equation*}
    p_N(\phi)=\frac{\abs{\{G\in\calg_N:G\vDash\phi\}}}{\abs{\calg_N}}
    \end{equation*}
    is the probability that a random element of \(\calg_N\) satisfies \phi

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.4.3
    \(\lim_{N\to\infty}p_N(\psi_n)=1\)
    #+END_lemma

    #+BEGIN_proof
    Fix $n$. Let \(G\) be a random graph in \(\calg_N\) where \(N>2n\). Fix 
    \(x_1,\dots,x_n,y_1,\dots,y_n,z\in G\) distinct. Let \(q\) be the
    probability that 
    \begin{equation*}
    \neg\left(
    \displaystyle\bigwedge_{i=1}^n(R(x_i,z))\wedge\neg R(y_i,z)
    \right)
    \end{equation*}
    Then \(q=1-2^{-2n}\). Because these probabilities are independent, the
    probability that 
    \begin{equation*}
    G\vDash\neg\exists z\neg\left(
    \displaystyle\bigwedge_{i=1}^n(R(x_i,z))\wedge\neg R(y_i,z)
    \right)
    \end{equation*}
    is \(q^{N-2n}\). Let $M$ be the number of pairs of disjoint subsets of \(G\)
    of size $n$. Thus
    \begin{equation*}
    p_N(\neg\psi_n)\le Mq^{N-2n}<N^{2n}q^{N-2n}
    \end{equation*}
    Because \(q<1\)
    \begin{equation*}
    \lim_{N\to\infty}p_N(\neg\psi_n)=\lim_{N\to\infty}N^{2n}q^N=0
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options [Zero-One Law for Graphs]
    #+BEGIN_theorem
    label:thm2.4.4
    For any \(\call\)-sentence \phi either \(\lim_{N\to\infty}p_N(\phi)=0\) or 
    \(\lim_{N\to\infty}p_N(\phi)=1\). Moreover, \(T\) axiomatizes
    \(\{\phi:\lim_{N\to\infty}p_N(\phi)=1\}\), the *almost sure theory graphs*. The
    almost sure theory of graphs is decidable and complete
    #+END_theorem

    #+BEGIN_proof
    If \(T\vDash\phi\), then there is \(n\) s.t. if \(G\) is a graph and
    \(G\vDash\psi_n\), then \(G\vDash\phi\). Thus,
    \(p_N(\phi)\ge\phi_N(\psi_n)\) and by Lemma ref:lemma2.4.3, \(\lim_{N\to\infty}p_N(\phi)=1\).
    #+END_proof

*** Ehrenfeucht-Fraïssé Games
    Let \(\call\) be a language and \(\calm=(M,\dots)\) and \(\caln=(N,\dots)\)
    be two \(\call\)-structures with \(M\cap N=\emptyset\). If \(A\subseteq M\),
    \(B\subseteq N\) and \(f:A\to B\), we wsay that \(f\) is a *partial embedding*
    if \(f\cup\{(c^{\calm},c^{\caln}):c\text{ a constant of }\call\}\)is a bijection
    preserving all relations and functions of \(\call\)

    We will define an infinite two-player game \(G_\omega(\calm,\caln)\). We
    will call the two players player \rom{1} and player \rom{2}; together they
    will build a partial embedding \(f\) from \(M\) to \(N\). A play of the game
    will consist of \omega stages. At the \(i\)th-stage, player \rom{1} moves first
    and either plays \(m_i\in M\), challenging player \rom{2} to put \(m_i\)
    into the domain of \(f\), or \(n_i\in N\), challenging player \rom{2} to put
    \(n_i\) into the range. If player \rom{1} plays \(m_i\in M\), then player
    \rom{2} must play \(n_i\in N\), whereas if player \rom{1} plays 
    \(n_i\in M\), then player \rom{2} must play \(m_i\in M\). Player \rom{2} wins the
    play of the game if \(f=\{(m_i,n_i):i=1,2,\dots\}\) is the graph of a
    partial embedding.

    A *strategy* for player \rom{2} in \(G_\omega(\calm,\caln)\) is a function \tau
    s.t. if player \rom{1}'s first \(n\) moves are \(c_1,\dots,c_n\) , then
    player \rom{2}'s \(n\)th move will be \(\tau(c_1,\dots,c_n)\). We say that
    player \rom{2} uses the strategy \tau in the play of the game if the play looks
    like
    #+ATTR_LATEX: :align cc
    | Player \rom{1} | Player \rom{2}        |
    | \(c_1\)        |                       |
    |                | \(\tau(c_1)\)         |
    | \(c_2\)        |                       |
    |                | \(\tau(c_1,c_2)\)     |
    | c_3            |                       |
    |                | \(\tau(c_1,c_2,c_3)\) |
    | \(\vdots\)     | \(\vdots\)            |


    We say that \tau is a *winning strategy* for player \rom{2}, if for any sequence
    of plays \(c_1,\dots\) player \rom{1} makes, player \rom{2} will win by
    following \tau. We define strategies for player \rom{1} analogously

    For example, suppose that \(\calm,\caln\vDash\DLO\). Then player \rom{2}
    has a winning strategy. Suppose that up to stage $n$ they have built a
    partial embedding \(g:A\to B\). If player \rom{1} plays \(a\in M\), then
    player \rom{2} plays \(b\in N\) s.t. the cub $b$ makes in \(B\) is the image
    of the cut of \(a\) in \(A\) under \(g\). Similar for player \rom{1}'s
    \(b\in N\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(\calm\) and \(\caln\) is countable, then the second player has a wining
    strategy in \(G_\omega\) if and only if \(\calm\cong\caln\)
    #+END_proposition

    #+BEGIN_proof
    If \(\calm\cong\caln\), player \rom{2} can win by playing according to the
    isomorphism

    Suppose that player \rom{2} has a winning strategy. Let \(m_0,m_1,\dots\)
    list \(M\) and \(n_0,n_1,\dots\) list $N$. Consider a play of the game where
    the second player uses the winning strategy and the first player plays 
    \(m_0,n_0,m_1,n_1,m_2,n_2,\dots\). If \(f\) is the partial embedding build
    during this play of the game then the domain of \(f\) is $M$ and the range
    of \(f\) is $N$. Thus \(f\) is an isomorphism
    #+END_proof

    [[index:Ehrenfeucht-Fraïssé Games]]

    _Fix \(\call\) a finite language with no function symbols_, and let \(\calm\)
    and \(\caln\) be \(\call\)-structures. We define a game \(G_n(\calm,\caln)\)
    for \(n=1,2,\dots\). The game will have \(n\) rounds similar to \omega rounds
    . Player \rom{2} wins if
    \(\{(a_i,b_i):i=1,\dots,n\}\) is the graph of a partial embedding from
    \(\calm\) into \(\caln\). We call \(G_n(\calm,\caln)\) an 
    *Ehrenfeucht-Fraïssé Games*
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(\call\) be a finite language without function symbols and let
    \(\calm\) and \(\caln\) be \(\call\)-structures. Then \(\calm\equiv\caln\)
    if and only if the second player has a wining strategy in
    \(G_n(\calm,\caln)\) for all \(n\)
    #+END_theorem

    We need several lemmas.

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    One of the players has a winning strategy in \(G_n(\calm,\caln)\)
    #+END_lemma

    #+BEGIN_proof
    Suppose that player \rom{2} does not have a winning strategy. Then there is
    some move player \rom{1} can make in round one so that player \rom{2} has no
    move available to force a win. Player \rom{1} makes that move. Now, whatever
    player \rom{2} does, there is still a move that if made by player \rom{1}
    means that player \rom{2} cannot force a win.
    #+END_proof

    We inductively define \(\text{depth}(\phi)\), the *quantifier depth* of an
    \(\call\)-formula \phi, as follows
    
    \(\text{depth}(\phi)=0\) if and only if \phi is quantifier-free

    \(\text{depth}(\neg\phi)=\text{depth}(\phi)\)
    
    \(\text{depth}(\phi\wedge\psi)=\text{depth}(\phi\vee\psi)=
    \max\{\text{depth}(\phi),\text{depth}(\psi)\}\)

    \(\text{depth}(\exists v\phi)=\text{depth}(\phi)+1\)

    We say that \(\calm\equiv_n\caln\) if
    \(\calm\vDash\phi\Leftrightarrow\caln\vDash\phi\) for all sentences of
    depth at most $n$. We will show player \rom{2} has a winning strategy in
    \(G_n(\calm,\caln)\) if and only if \(\calm\equiv_n\caln\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For each \(n\) and \(l\), there is a finite list of formulas
    \(\phi_1,\dots,\phi_k\) of depth at most \(n\) in free variables
    \(x_1,\dots,x_l\) s.t. every formula of depth at most $n$ in free variables
    \(x_1,\dots,x_l\) is equivalent to some \(\phi_i\)
    #+END_lemma

    #+BEGIN_proof
    We first prove this for quantifier-free formulas. Because \(\call\) is
    finite and has no function symbols, there are only finitely many atomic
    \(\call\)-formulas in free variables \(x_1,\dots,x_l\). Let
    \(\sigma_1,\dots,\sigma_s\) list all such formulas.

    If \phi is a Boolean combination of formulas \(\tau_1,\dots,\tau_s\), then
    there is \(S\) a collection of subsets of \(\{1,\dots,s\}\) s.t.
    \begin{equation*}
    \vDash\phi\leftrightarrow\displaystyle
    \bigvee_{X\in S}\left(\bigwedge_{i\in X}\tau_i\wedge
    \bigwedge_{i\not\in X}\neg\tau_i
    \right)
    \end{equation*}
    This gives a list of \(2^{2^s}\) formulas s.t. every Boolean combination of
    \(\tau_1,\dots,\tau_s\) is equivalent to a formula in this list. In
    particular, because quantifier free formulas are Boolean combinations of
    atomic formulas, there is a finite list of depth-zero formulas s.t. every
    depth-zero formula is equivalent to one in the list.

    Because formulas of depth \(n+1\) are Boolean combinations of 
    \(\exists v\phi\) and \(\forall v\phi\) where \phi has depth at most \(n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\call\) be a finite language without function symbols and \(\calm\)
    and \(\caln\) be \(\call\)-structures. The second player has a winning
    strategy in \(G_n(\calm,\caln)\) if and only if \(\calm\equiv_n\caln\)
    #+END_lemma

    #+BEGIN_proof
    Induction on \(n\)

    Suppose that \(\calm\equiv_n\caln\). Consider a play of the game where in
    round one player \rom{1} plays \(a\in M\). We claim that there is
    \(b\in\caln\) s.t. \(\calm\vDash\phi(a)\Leftrightarrow\caln\vDash\phi(b)\)
    whenever \(\depth(\phi)<n\). Let \(\phi_0(v),\dots,\phi_m(v)\) list, up to
    equivalance, all formulas of depth less than \(n\). Let 
    \(X=\{i\le m:\calm\vDash\phi_i(a)\}\), and let \(\Phi(v)\) be the formula
    \begin{equation*}
    \displaystyle\bigwedge_{i\in X}\phi_i(v)\wedge\bigwedge_{i\not\in X}
    \neg\phi_i(v)
    \end{equation*}
    Then, \(\depth(\exists v\Phi(v))\le n\) and \(\calm\vDash\Phi(a)\); thus
    there is \(b\in N\) s.t. \(\caln\vDash\Phi(b)\). Player \rom{2} plays \(b\)
    in round one

    If \(n=1\), the game has now concluded and \(a\mapsto b\) is a partial
    embedding so player \rom{2} wins. Suppose that \(n>1\)

    Let \(\call^*=\call\cup\{c\}\), where \(c\) is a new constant symbol. View
    \(\calm\) and \(\caln\) as \(\call^*\)-structures \((\calm,a)\) and
    \((\caln,b)\) where we interpret the new constant as \(a\) and \(b\)
    respectively. Because 
    \begin{equation*}
    \calm\vDash\phi(a)\Leftrightarrow\caln\vDash\phi(b)
    \end{equation*}
    for \(\phi(v)\) an \(\call\)-formula with \(\depth(\phi)<n\),
    \((\calm,a)\equiv_{n-1}(\caln,b)\). By induction, player \rom{2} has a
    winning strategy in \(G_{n-1}((\calm,a),(\caln,b))\). If player's second
    play is \(d\), player \rom{2} responds as if \(d\) was player \rom{1}'s
    first play in \(G_{n-1}((\calm,a),(\caln,b))\)' and continues playing using
    this strategy, that is, in round $i$ player \rom{1} has plays
    \(a,d_2,\dots,d_i\), then player \rom{2} plays \(\tau(d_2,\dots,d_i)\), where 
    \(\tau\) is his winning strategy in \(G((\calm,a),(\caln,b))\).
    #+END_proof

** Exercises
   #+BEGIN_exercise
   label:ex2.5.1
   We say that an ordered group \((G,+,<)\) is *Archimedean* if for all
   \(x,y\in G\) with \(x,y>0\) there is an integer \(m\) s.t.
   \(\abs{x}<m\abs{y}\). Show that there are non-Archimedean fields elementarily
   equivalent to the field of real numbers
   #+END_exercise

   #+BEGIN_exercise
   label:ex2.5.10
   Let \(T\) be an \(\call\)-theory and \(T_\forall\) be all of the universal
   sentences \phi s.t. \(T\vDash\phi\). Show that \(\cala\vDash T_\forall\) if and only
   if there is \(\calm\vDash T\) with \(\cala\subseteq\calm\)
   #+END_exercise

   #+BEGIN_proof
   Comes from [[http://www.math.uni-konstanz.de/~eleftheriou/teaching/Masterarbeit.pdf][Quantifier Elimination Tests and Examples]]
   
   Consider the theory \(T'=T\cup\Diag(\cala)\) in the language \(\call_A\). We
   will show by contradiction that \(T'\) is satisfiable.

   Suppose that \(T'\) is not satisfiable. Then by the Compactness Theorem,
   already some finite subset \(\Delta\subseteq T'\) is not satisfiable. By forming
   conjunctions we may assume that the part of \Delta coming from \(\Diag(\cala)\)
   consists only of one formula \(\phi(\bar{a})\) for some \(\bar{a}\in\ A\), where
   \(\phi(\bar{a})\) is a conjunction of atomic formulas and the negation of atomic
   formulas. Thus we will assume that \(T\cup\{\phi(\bar{a})\}\) is not satisfiable.

   On the other hand, viewing \(T\) as an \(\call_{\bar{a}}\)-theory, and because
   \(T\cup\{\phi(\bar{a})\}\) is not satisfiable, we obtain
   \(T\vDash\neg\phi(\bar{a})\). We will show that this implies
   \(T\vDash\forall\bar{v}\neg\phi(\bar{v})\): Let \(\calc\) be an
   \(\call\)-structure with \(\calc\vDash T\). Let \(n\) be the number of
   components in \(\bar{a}\) and \(c_1,\dots,c_n\in C\). Let \(C'\) be the
   \(\call_{\bar{a}}\)-structure which expands \(\calc\) by the constant symbols
   that we interpret as \(c_1,\dots,c_n\) respectively. Then \(\calc'\vDash T\) and
   hence \(\calc'\vDash\neg\phi(\bar{c})\). As this follows for any tuple in
   \(C\), we get \(\calc\vDash\forall\bar{v}\neg\phi(\bar{v})\)

   Since \(T_\forall\) consists exactly of the universal formulas which hold in all
   models of \(T\), we obtain \(T_\forall\vDash\forall x\neg\phi(x)\). Hence also
   \(\cala\vDash\forall x\neg\phi(x)\), a contradiction

   Therefore \(T'\) is indeed satisfiable
   #+END_proof

* Algebraic Examples

** Quantifier Elimination
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that a theory $T$ has *quantifier elimination* if for every formula \phi
   there is a quantifier-free formula \psi s.t.
   \begin{equation*}
   T\vDash\phi\leftrightarrow\psi
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \((A,<)\) and \((B,<)\) be countable dense linear orders,
   \(a_1,\dots,a_n\in A\), \(b_1,\dots,b_n\in B\), s.t. \(a_1<\dots<a_n\) and
   \(b_1,\dots<b_n\). Then there is an isomorphism \(f:A\to B\) s.t.
   \(f(a_i)=b_i\) for all \(i=1,\dots,n\)
   #+END_lemma
   
   #+BEGIN_proof
   Modify the proof of Theorem ref:thm2.4.1 starting with
   \(A_0=\{a_1,\dots,a_n\}\), \(B_0=\{b_1,\dots,b_n\}\), and the partial
   isomorphism \(f_0:A_0\to B_0\), where \(f_0(a_i)=b_i\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   DLO has quantifier elimination
   #+END_theorem
   #+BEGIN_proof
   First, suppose that \(\phi\) is a sentence. If \(\Q\vDash\phi\), then
   because DLO is complete, \(\DLO\vDash\phi\), and 
   \begin{equation*}
   \DLO\vDash\phi\leftrightarrow x_1=x_1
   \end{equation*}
   whereas if \(\Q\vDash\neg\phi\)
   \begin{equation*}
   \DLO\vDash\phi\leftrightarrow x_1\neq x_1
   \end{equation*}

   Now suppose that \phi is a formula with free variables \(x_1,\dots,x_n\) where
   \(n\ge1\). We will show that there is a quantifier-free formula \psi with free
   variables from among \(x_1,\dots,x_n\) s.t.
   \begin{equation*}
   \Q\vDash\forall\bar{x}(\phi(\bar{x})\leftrightarrow\psi(\bar{x}))
   \end{equation*}
   Because DLO is complete,
   \begin{equation*}
   \DLO\vDash\forall\bar{x}(\phi(\bar{x})\leftrightarrow\psi(\bar{x}))
   \end{equation*}
   so this will suffices.

   For \(\sigma:\{(i,j):1\le i<j\le n\}\to3\), let \(\chi_\sigma(x_1,\dots,x_n)\) be the formula
   \begin{equation*}
   \displaystyle\bigwedge_{\sigma(i,j)=0}x_i=x_j\wedge
   \bigwedge_{\sigma(i,j)=1}x_i<x_j\wedge
   \bigwedge_{\sigma(i,j)=2}x_i>x_j
   \end{equation*}
   We call \(\chi_\sigma\) a *sign condition*.

   Let \(\call\) be the language of linear orders and \phi be an
   \(\call\)-formula with \(n\ge1\) free variables. Let \(\Lambda_\phi\) be the
   set of sign conditions s.t. there is \(\bar{a}\in\Q\) s.t.
   \(\Q\vDash\chi_\sigma(\bar{a})\wedge\phi(\bar{a})\)

   
   _case 1:_ \(\Lambda_\phi=\emptyset\)

   Then \(\Q\vDash\forall\bar{x}\neg\phi(\bar{x})\) and
   \(\Q\vDash\phi(\bar{x})\leftrightarrow x_1\neq x_1\)

   _case 2:_ \(\Lambda_\phi\neq\emptyset\)

   Let
   \begin{equation*}
   \psi_\phi(\bar{x})=\displaystyle\bigwedge_{\sigma\in\Lambda_\phi}\chi_\sigma(\bar{x})
   \end{equation*}

   By choice of \(\Lambda_\phi\),
   \begin{equation*}
   \Q\vDash\phi(\bar{x})\to\psi_\phi(\bar{x})
   \end{equation*}

   On the other hand, suppose that \(\bar{b}\in\Q\) and
   \(\Q\vDash\psi_\phi(\bar{b})\). Let \(\sigma\in\Lambda_\phi\) s.t. \(\Q\vDash\chi_\sigma(\bar{b})\).
   There is \(\bar{a}\in\Q\) s.t. \(\Q\vDash\phi(\bar{a})\wedge\chi_\sigma(\bar{a})\). By Theorem
   ref:thm2.4.1, there is \(f\), an automorphism of \((\Q,<)\) s.t.
   \(f(\bar{a})=\bar{b}\). By Theorem ref:thm1.1.10, \(\Q\vDash\phi(\bar{b})\).
   Thus \(\phi(\bar{b})\leftrightarrow\psi_\phi(\bar{b})\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.4
   Suppose that \(\call\) contains a constant symbol \(c\), \(T\) is an
   \(\call\)-theory, and \(\phi(\bar{v})\) is an \(\call\)-formula. The following
   are equivalent:
   1. There is a quantifier-free \(\call\)-formula \(\psi(\bar{v})\) s.t.
      \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\)
   2. If \(\calm\) and \(\caln\) are models of \(T\), \(\cala\) is an
      \(\call\)-structure, \(\cala\subseteq\calm\), and \(\cala\subseteq\caln\),
      then \(\calm\vDash\phi(\bar{a})\) if and only if \(\caln\vDash\phi(\bar{a})\)
      for all \(\bar{a}\in\cala\)
   #+END_theorem

   #+BEGIN_proof
   \((1)\to(2)\). Suppose that \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\),
   where \psi is quantifier-free. Let \(\bar{a}\in\cala\), where \(\cala\) is a
   common substructure of \(\calm\) and \(\caln\) and the latter structures are
   models of \(T\). In Proposition ref:prop1.1.8, we saw that quantifer-free
   formulas are preserved under substructure and extension. Thus
   \begin{align*}
   \calm\vDash\phi(\bar{a})&\Leftrightarrow\calm\vDash\psi(\bar{a})\\
   &\Leftrightarrow\cala\vDash\psi(\bar{a})\\
   &\Leftrightarrow\caln\vDash\psi(\bar{a})\\
   &\Leftrightarrow\caln\vDash\phi(\bar{a})
   \end{align*}

   \((2)\to(1)\). First, if \(T\vDash\forall\bar{v}\phi(\bar{v})\), then
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow c=c)\).Second, if
   \(T\vDash\forall\bar{v}\neg\phi(\bar{v})\), then
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow c\neq c)\).

   Thus, we may assume that both \(T\cup\{\phi(\bar{v})\}\) and \(T\cup\{\neg\phi(\bar{v})\}\)
   are satisfiable

   Let \(\Gamma(\bar{v})=\{\psi(\bar{v}):\psi\text{ is quantifier free and
   }T\vDash\forall\bar{v}(\phi(\bar{v})\to\psi(\bar{v}))\}\). Let
   \(d_1,\dots,d_m\) be new constant symbols. We will show that
   \(T\cup\Gamma(\bar{d})\vDash\phi(\bar{d})\). Then, by compactness, there are
   \(\psi_1,\dots,\psi_n\in\Gamma\) s.t.
   \begin{equation*}
   T\vDash\forall\bar{v}\left(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\to\phi(\bar{v})
   \right)
   \end{equation*}
   Thus
   \begin{equation*}
   T\vDash\forall\bar{v}\left(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\leftrightarrow
   \phi(\bar{v})
   \right)
   \end{equation*}
   and \(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\) is quantifier-free

   *Claim* \(T\cup\Gamma(\bar{d})\vDash\phi(\bar{d})\)

   Suppose not. Let \(\calm\vDash T\cup\Gamma(\bar{d})\cup\{\neg\phi(\bar{d})\}\). Let \(\cala\)
   be the substructure of \(\calm\) generated by \(\bar{d}\)

   Let \(\Sigma=T\cup\Diag(\cala)\cup\phi(\bar{d})\). If \Sigma is unsatisfiable, then there are
   quantifier-free formulas \(\psi_1(\bar{d}),\dots,\psi_n(\bar{d})\in\Diag(\cala)\) s.t.
   \begin{equation*}
   T\vDash\forall\bar{v}\left(
   \displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\to\neg\phi(\bar{v})
   \right)
   \end{equation*}
   But then
   \begin{equation*}
   T\vDash\forall\bar{v}\left(\phi(\bar{v})\to
   \displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{v})
   \right)
   \end{equation*}
   so \(\displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{v})\in\Gamma\) and
   \(\cala\vDash\displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{d})\), a
   contradiction. Thus, \Sigma is satisfiable

   Let \(\caln\vDash\Sigma\). Then \(\caln\vDash\phi(\bar{d})\). Because
   \(\Sigma\supseteq\Diag(\cala)\), \(\cala\subseteq\caln\), by Lemma ref:lemma2.3.3.
   But \(\calm\vDash\neg\phi(\bar{d})\); thus \(\caln\vDash\neg\phi(\bar{d})\), a contradiction
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.1.5
   Let \(T\) be an \(\call\)-theory. Suppose that for every quantifier-free
   \(\call\)-formula \(\theta(\bar{v},w)\) there is a quantifier-free formula
   \(\psi(\bar{v})\) s.t. \(T\vDash\exists w\theta(\bar{v},w)\leftrightarrow\psi(\bar{v})\). Then \(T\)
   has quantifier elimination
   #+END_lemma

   #+BEGIN_proof
   Let \(\phi(\bar{v})\) be an \(\call\)-formula. We wish to show to show that
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\) for some quantifier-free
   formula \(\psi(\bar{v})\)

   If \phi is quantifier-free, there is nothing to prove. Suppose that for
   \(i=0,1\), \(T\vDash\forall\bar{v}(\theta_i(\bar{v})\leftrightarrow\psi_i(\bar{v}))\), where
   \(\psi_{i}\) is quantifier-free.

   If \(\phi(\bar{v})=\neg\theta_0(\bar{v})\), then
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\neg\psi_0(\bar{v}))\)

   Suppose that \(T\vDash\forall\bar{v}(\theta(\bar{v},w)\leftrightarrow\psi_0(\bar{v},w))\), where
   \(\psi_0\) is quantifier-free and \(\phi(\bar{v})=\exists w\theta(\bar{v},w)\). Then
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\exists w\psi_0(\bar{v},w))\). By our assumptions,
   there is a quantifier-free \(\psi(\bar{v})\) s.t.
   \(T\vDash\forall\bar{v}(\exists w\psi_0(\bar{v},w)\leftrightarrow\psi(\bar{v}))\). But then
   \(T\vDash\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\)

   #+END_proof

   Combining Theorem ref:thm3.1.4 and Lemma ref:lemma3.1.5 gives us the
   following test for quantifier elimination (Restrict the form of \phi)
   #+ATTR_LATEX: :options [NEED TO RECONSIDER]
   #+BEGIN_corollary
   label:cor3.1.6
   Let \(T\) be an \(\call\)-theory. Suppose that for all quantifier-free
   formulas \(\phi(\bar{v},w)\), if \(\calm,\caln\vDash T\), \(\cala\) is a common
   substructure of \(\calm\) and \(\caln\), \(\bar{a}\in A\), and there is
   \(b\in M\) s.t. \(\calm\vDash\phi(\bar{a},b)\), then there is \(c\in N\) s.t.
   \(\caln\vDash\phi(\bar{a},c)\). Then $T$ has a quantifier elimination
   #+END_corollary

   #+BEGIN_proof
   Check this notes [[http://www.math.uni-konstanz.de/~eleftheriou/teaching/Masterarbeit.pdf][Quantifier Elimination Tests and Examples]]

   We need to show that \(T\vDash\forall\bar{v}(\exists w\phi(\bar{v},w)\leftrightarrow\psi(\bar{v}))\).
   Suppose that \(\calm\vDash\exists w\phi(\bar{v},w)\), then
   \(\caln\vDash\exists w\phi(\bar{v},w)\). Note that \(\calm\) and \(\caln\) are interchangeable.
   #+END_proof

*** Divisible Abelian Groups
    Work with the language \(\call=\{+,-,0\}\) because its convenient

    Let DAG be the \(\call\)-theory of nontrivial torsion-free divisible Abelian
    groups

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.1.7
    Suppose \(G\) and \(H\) are nontrivial torsion free divisible Abelian
    groups, \(G\subseteq H\), \(\psi(\bar{v},w)\) is quantifier-free,
    \(\bar{a}\in G\), \(b\in H\), and \(H\vDash\phi(\bar{a},b)\). Then there is
    \(c\in G\) s.t. \(G\vDash\phi(\bar{a},c)\)
    #+END_lemma

    #+BEGIN_proof
    We first note that \psi can be put in disjunctive normal form.

    Because \(H\vDash\psi(\bar{a},b)\),
    \(H\vDash\bigwedge_{j=1}^m\theta_{i,j}(\bar{a},b)\) for some \(i\). Thus, without
    loss of generality, we may assume that \psi is a conjunction of atomic and
    negated atomic formulas. If \(\theta(v_1,\dots,v_m,w)\) is an atomic formula,
    then for some integers \(n_1,\dots,n_m,m\), \(\theta(\bar{v},w)\) is
    \(\sum n_iv_i+mw=0\)

    Thus we may assume that
    \begin{equation*}
    \psi(\bar{a},w)=\displaystyle\bigwedge_{i=1}^s\sum_{j=1}^mn_{i,j}a_j+m_iw=0\wedge
    \bigwedge_{i=1}^s\sum_{j=1}^mn_{i,j}'a_j+m_i'w\neq0
    \end{equation*}
    Let \(g_i=\sum n_{i,j}a_j\) and \(h_i=\sum n_{i,j}'a_j'\). Then \(g_i,h_i\in G\) and
    \begin{equation*}
    \psi(\bar{a},w)\leftrightarrow\bigwedge g_i+m_iw=0\wedge\bigwedge h_i+m_i'w\neq0
    \end{equation*}

    If any \(m_i\neq0\), then \(b=-g_i/m_i\in G\) and \(G\vDash\theta(\bar{a},b)\),
    so suppose that \(\psi(\bar{a},w)=\bigwedge h_i+m_i'w\neq0\). Thus
    \(\psi(\bar{a},w)\) is satisfied by any element of \(H\) that is not equal to
    any one of \(\frac{-h_1}{m_1'},\dots,\frac{-h_s}{m_s'}\). Because \(G\) is
    infinite, there is an element  of \(G\) satisfying \(\psi(\bar{a},w)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.1.8
    Suppose that \(G\) is a torsion-free Abelian group. Then there is a
    torsion-free divisible Abelian group $H$, called the *divisible hull* of
    \(G\), and an embedding \(i:G\to H\) s.t. if \(j:G\to H'\) is an embedding of
    \(G\) into a torsion-free divisible Abelian group, then there is \(h:H\to H'\) s.t.
    \(j=h\circ i\)
    #+END_lemma

    #+BEGIN_proof
    If \(G\) is the trivial group, then we take \(H=\Q\) since every torsion
    free divisible Abelian group can be viewed as a vector space over \(\Q\). So
    suppose that \(G\) is non-trivial

    Let \(X=\{(g,n):g\in G,n\in\N,n>0\}\). We think of \((g,n)\) as \(g/n\)

    We define an equivalence relation \(\sim\) on \(X\) by \((g,n)\sim(h,m)\) if and
    only if \(mg=nh\). Let \(H=X/\sim\). For \((g,n)\in X\), let \([(g,n)]\) denote
    the \(\sim\)-class of \((g,n)\). We define \(+\) on \(H\) by
    \([(g,n)]+[(h,m)]=[(mg+nh,mn)]\). We must show that \(+\) is well defined

    Suppose that \((g_0,n_0)\sim(g,n)\). We claim that
    \((mg_0+n_0h,mn_0)\sim(mg+nh,mn)\).

    Similarly we can define \(-\) by \([(g,n)]-[(h,m)]=[(mg-nh,mn)]\). It is
    easy to show that \((H,+)\) is an Abelian group

    If \([(g,m)]\in H\) and \(n>0\), then \(n[(g,m)]=[(ng,m)]\). If
    \((ng,m)\sim(0,k)\), then \(kng=0\). Becasue \(k,n>0\) and \(G\) is torsion
    free, \(g=0\). Then \([(g,m)]=[(0,1)]\). Thus \(H\) is torsion free.

    Suppose that \([(g,m)]\in H\) and \(n>0\), then \(n[(g,mn)]=[(g,m)]\). Thus
    \(H\) is divisible.

    We can embed \(G\) into \(H\) by the map \(i(g)=[(g,1)]\)

    Suppose that \(H'\) is a divisible torsion-free Abelian group and
    \(j:G\to H'\) is an embedding. Let \(h:H\to H'\) by \(h([g,n])=j(g)/n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm3.1.9
    DAG has quantifier elimination
    #+END_theorem
    #+BEGIN_proof
    Suppose that \(G_0\) and \(G_1\) are torsion-free divisible Abelian groups,
    \(G\) is a common subgroup of \(G_0\) and \(G_1\), \(\bar{g}\in G\),
    \(h\in G_0\) and \(G_0\vDash\phi(\bar{g},h)\), where \phi is quantifier-free.
    Let \(H\) be the divisible hull of \(G\). Because we can embed \(H\) into
    \(G_0\), by Lemma ref:lemma3.1.7, \(H\vDash\exists w\phi(\bar{g},w)\). Because
    we can embed \(H\) into \(G_1\), there is \(h'\in G_1\) s.t.
    \(G_1\vDash\phi(\bar{g},h')\). By Corollary ref:cor3.1.6, DAG has
    quantifier elimination
    #+END_proof

    Quantifier elimination gives us a good picture of the definable sets in
    a model of DAG. Suppose that \(\phi(v_1,\dots,v_n,w_1,\dots,w_m)\) is an atomic
    formula. Then there are integers \(k_1,\dots,k_n\) and \(l-1,\dots,l_m\) s.t.
    \(\phi(\bar{v},\bar{w})\leftrightarrow\sum k_ix_i+\sum l_iy_i=0\). If \(G\vDash\DAG\) and
    \(a_1,\dots,a_m\in G\), \(\phi(\bar{v},\bar{a})\) defines
    \(\{\bar{g}\in G^n:\sum k_ig_i+\sum l_ia_i=0\}\), a hyperplane in \(G^n\). Because
    any \(\call\)-formula \(\phi(\bar{v},\bar{w})\) is equivalent in DAG to a
    Boolean combination of atomic \(\call\)-formulas, every definable subset of
    \(G^n\) is a Boolean combination of hyperplanes

    In particular, suppose that \(\bar{a}\in G^m\) and \(\phi(v,\bar{a})\) defines a
    subset of \(G\). The "hyperplanes" in \(G\) are just single points. Thus,
    \(\{g\in G:G\vDash\phi(g,\bar{a})\}\) is either finite or cofinite. Thus
    every definable subset of \(G\) was definable already in the language of equality

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that an \(\call\)-theory $T$ is *strongly minimal* if for any
    \(\calm\vDash T\) every definable subset of \(M\) is either finite or cofinite
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    DAG is strongly minimal
    #+END_corollary


    If \(T\) is a theory then \(T_\forall\) is the set of all universal consequences
    of \(T\). In Exercise ref:ex2.5.10 we saw that \(\cala\vDash T_\forall\) if and
    only if there is \(\calm\vDash T\) with \(\cala\subseteq\calm\). One
    consequence of Lemma ref:lemma3.1.8 is that every torsion-free Abelian group
    is a substructure of a nontrivial divisible Abelian group. Because the
    axioms for torsion-free Abelian groups are universal, /\(\DAG_\forall\) is exactly/
    /the theory of torsion-free Abelian groups./

    We say that a theory \(T\) has *algebraically prime models* if for any
    \(\cala\vDash T_\forall\) there is \(\calm\vDash T\) and an embedding
    \(i:\cala\to\calm\) s.t. for all \(\caln\vDash T\) and embeddings
    \(j:\cala\to\caln\) there is \(h:\calm\to\caln\) s.t. \(j=h\circ i\).
    #+BEGIN_center
    \begin{tikzcd}
    \cala\vDash T_\forall\arrow[r,"i"]\arrow[rd,"j"']&\calm\vDash T\arrow[d,"h"]\\
    &\caln\vDash T
    \end{tikzcd}
    #+END_center

    If \(\calm,\caln\vDash T\) and \(\calm\subseteq\caln\), we say that
    \(\calm\) is *simply closed* in \(\caln\) and write \(\calm\prec_s\caln\) if
    for any quantifier free formula \(\phi(\bar{v},w)\) and any \(\bar{a}\in M\),
    if \(\caln\vDash\exists\phi(\bar{a},w)\) then so does \(\calm\). Lemma
    ref:lemma3.1.7 says that if \(G\) and \(H\) are models of DAG and
    \(G\subseteq H\), then \(G\prec_s H\)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor3.1.12
    Suppose that \(T\) is an \(\call\)-theory s.t.
    1. \(T\) has algebraically prime models and
    2. \(\calm\prec_s\caln\) whenever \(\calm\subseteq\caln\) are models of
       \(T\)


    Then \(T\) has quantifier elimination
    #+END_corollary

    #+BEGIN_proof
    Suppose \(\cala\vDash T_\forall\), then 
    #+END_proof


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An \(\call\)-theory \(T\) is *model-complete* \(\calm\prec\caln\) whenever
    \(\calm\subseteq\caln\) and \(\calm,\caln\vDash T\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(T\) has quantifier elimination, then \(T\) is model-complete
    #+END_proposition

    #+BEGIN_proof
    Suppose that \(\calm\subseteq\caln\) are models of \(T\). Let \(\phi(\bar{v})\)
    be an \(\call\)-formula, and let \(\bar{a}\in M\). There is a quantifier-free
    formula \(\psi(\bar{v})\) s.t. \(\calm\vDash\forall\bar{v}(\phi(\bar{v}\leftrightarrow\psi(\bar{v})))\).
    Because quantifier-free formulas are preserved under substructures and
    extensions, \(\calm\vDash\psi(\bar{a})\) if and only if
    \(\caln\vDash\psi(\bar{a})\). Thus \(\calm\prec\caln\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:prop3.1.15
    Let \(T\) be a model-complete theory. Suppose that there is
    \(\calm_0\vDash T\) s.t. \(\calm_0\) embeds into every model of \(T\). Then
    \(T\) is complete
    #+END_proposition

    #+BEGIN_proof
    If \(\calm\vDash T\), then \(\calm_0\prec \calm\). In particular
    \(\calm_0\equiv\calm\).
    #+END_proof

    Because \((\Q,+,0)\) embeds in every model of DAG, this gives another proof
    of the completeness of DAG

*** Ordered Divisible Abelian Groups
    Let \(\call=\{+,0,<,0\}\) and let ODAG be the theory of nontrivial divisible
    ordered Abelian groups.  The axioms for ordered Abelian groups are universal
    and hence contained in \(\ODAG_\forall\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.1.16
    Let \(G\) be an ordered Abelian gorup and \(H\) be the divisible hull of
    \(G\). We can order \(H\) s.t. \(i:G\to H\) is order-preserving,
    \((H,+,<)\vDash\ODAG\) and if \(H'\vDash\ODAG\) and \(j:G\to H'\) is an
    embedding, then there is an embedding \(h:H\to H'\) s.t. \(j=h\circ i\)
    #+END_lemma

    #+BEGIN_proof
    We let \(\frac{g}{n}\) denote \([(g,n)]\). We can order \(H\) by
    \(\frac{g}{n}<\frac{h}{m}\) if and only if \(mg<nh\). If \(g<h\), then
    \(\frac{g}{1}<\frac{h}{1}\) so this extends the ordering of \(G\). If
    \(\frac{g_1}{n_1}<\frac{g_2}{n_2}\) and
    \(\frac{h_1}{m_1}\le \frac{h_2}{m_2}\), then \(n_2g_1<n_1g_2\) and
    \(m_2h_1\le m_1h_2\). Then,
    \begin{equation*}
    m_1m_2n_2g_1+n_1n_2m_2h_1<m_1m_2n_1g_2+n_1n_2m_1h_2
    \end{equation*}
    and
    \begin{equation*}
    \frac{m_1g_1+n_1h_1}{m_1n_1}<\frac{m_2g_2+n_2h_2}{m_2n_2}
    \end{equation*}
    Thus, < makes \(H\) an ordered group

    If \(H'\) is another ordered disivible Abelian group and \(j:G\to H'\) is an
    embedding, let \(h\) be as in Lemma ref:lemma3.1.8
    #+END_proof

    To prove quantifier elimination, we must how that if \(G\) and \(H\) are
    ordered divisible Abelian groups and \(G\subseteq H\), then \(G\prec_s H\)

    Suppose that \(\phi(v,\bar{w})\) is a quantifier-free formula,
    \(\overbar{a}\in G\), and for some \(b\in H\), \(H\vDash\phi(b,\bar{a})\).
    As above, it suffices to consider the case where \phi is a conjunction of
    atomic and negated atomic formulas. If \(\theta(v,\overbar{w})\) is atomic,
    then \theta is equivalent to either \(\sum n_iw_i+mv=0\) or
    \(\sum n_iw_i+mv>0\) for some \(n_i,m\in\Z\). In particular, there is an
    element \(g\in G\) s.t. \(\theta(v,\overbar{a})\) is of the form \(mv=g\) or
    \(mv>g\). Also not that for any formula \(mv\neq g\) is equivalent to
    \(mv>g\) or \(-mv>g\). Thus we may assume that
    \begin{equation*}
    \phi(v,\overbar{a})\leftrightarrow\bigwedge m_iv=g_i
    \bigwedge n_iv>h_i
    \end{equation*}
    where \(g_i,h_i\in G\) and \(m_i,n_i\in\Z\)

    If there is actually a conjunct \(m_iv=g_i\), then we must have
    \(b=\frac{g_i}{m_i}\in G\); otherwise
    \(\phi(v,\overbar{a})=\bigwedge m_iv>h_i\). Let
    \(k_0=\min\{\frac{h_i}{m_i}:m_i<0\}\) and
    \(k_i=\max\{\frac{h_i}{m_i}:m_i>0\}\). Then \(c\in H\) satisfies
    \(\phi(v,\overbar{a})\) if and only if \(k_0<v<k_1\). Because \(b\)
    satisfies \phi, we must have \(k_0<k_1\). But any ordered divisible Abelian
    group is densely ordered because if \(g<h\) then \(g<\frac{g+h}{2}<h\), so
    there is \(d\in G\) s.t. \(k_0<d<k_1\). Thus \(G\prec_s H\)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor3.1.17
    ODAG is a complete decidable theory with quantifier elimination. In
    particular, every ordered divisible Abelian group is elementarily equivalent
    to \(\Q,+,<\)
    #+END_corollary

    #+BEGIN_proof
    By Lemma ref:lemma3.1.16, \(\ODAG_\forall\) is the theory of ordered Abelian
    groups and ODAG has algebraically prime models. From Corollary ref:cor3.1.12
    we see that ODAG has quantifier elimination. The ordered group of rational
    embeds into every ordered divisible Abelian group; thus by Proposition
    ref:prop3.1.15, ODAG is complete. Because ODAG has a recursive
    axiomatization, it is decidable by Lemma ref:lemma2.2.8
    #+END_proof

    ODAG is not strongly minimal. For example, \(\{a\in\Q:a<0\}\) is infinite
    and coinfinite. On the other hand, /definable subsets are quite
    well-behaved/. Suppose that \(G\) is an ordered divisible Abelian group and
    \(X\subseteq G\) definable. By quantifer elimination, \(X\) is a Boolean
    combination of sets defined by atomic formulas. If \(\phi(v,w_1,\dots,w_n)\)
    is atomic, then there are integers \(k_0,\dots,k_n\) s.t. \phi is equivlent
    to either
    \begin{equation*}
    k_0v+\sum k_iw_i=0
    \end{equation*}
    or
    \begin{equation*}
    k_0v+\sum k_iw_i>0
    \end{equation*}
    If \(\overbar{a}\in G^n\), in the first case \(\phi(v,\overbar{a})\) defines
    a finite set whereas in the second case it defines an interval. It follows
    that \(X\) is a finite union of points and intervals with endpoints in
    \(G\cup\{\pm\infty\}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say the an ordered structure \((M,<,\dots)\) is *o-minimal* if for any
    definable \(X\subseteq M\) there are finitely many intervals
    \(I_1,\dots,I_m\) with endpoints in \(M\cup\{\pm\infty\}\) and a finite set
    \(X_0\) s.t. \(X=X_0\cup I_1\cup\dots\cup I_m\)
    #+END_definition

*** Presburger Arithmetic
    Let \(\call=\{+,-,<,0,1\}\) and consider the \(\call\)-theory of the ordered
    group of integers.  In fact this theory will not have quantifer elimination
    in the language \(\call\). Let \(\psi_n(v)\) be the formula
    \begin{equation*}
    \exists y\; v=\underbrace{y+\dots+y}_{n\text{-times}}
    \end{equation*}
    It turns out that this is the only obstruction to quantifer elimination.
    Let \(\call^*=\call\cup\{P_n:n=2,3,\dots\}\) whre \(P_n\) is a unary
    predicate which we will interpret as the elements divisible by \(n\)

    For any language \(\call\) and \(\call\)-theory \(T\), there is a language
    \(\call'\supseteq\call\) and an \(\call'\)-theory \(T'\supseteq T\) s.t. for
    any \(\calm\vDash T\) we can interpret the new symbols of \(\call'\) to
    make \(\calm'\vDash T'\) s.t. for any subset of \(M^k\) definable using
    \(\call'\) is already definable using \(\call\), and any \(\call'\)-formula
    is equivalent to an atomic \(\call'\)-formula

    Let \(\call'=\call\cup\{R_\phi:\phi\text{ an $\call$-formula}\}\), where if
    \phi is a formula in \(n\) free variables, \(R_\phi\) is an \(n\)-ary
    predicate symbol. Let \(T'\) be the theory obtained by adding to \(T\) the
    sentences
    \begin{equation*}
    \forall\overbar{v}(\phi(\overbar{v})\leftrightarrow R_\phi(\overbar{v}))
    \end{equation*}

    Consider the \(\call^*\)-theory, which we call Pr for *Presburger
    arithmetic*, with axioms:
    1. axioms for ordered Abelian groups
    2. \(0<1\)
    3. \(\forall x(x\le0\vee x\ge1)\)
    4. \(\forall x(P_n(x)\leftrightarrow\exists y\;x=
       \underbrace{y+\dots+y}_{n\text{-times}})\), for \(n=2,3,\dots\)
    5. \(\forall x\bigvee_{i=0}^{n-1}[P_n(x+\underbrace{1+\dots+1}_{i\text{
       times}})
       \wedge\bigwedge_{j\neq i}\neg P_n(x+\underbrace{1+\dots+1}_{j\text{
       times}})]\)
       for \(n=2,3,\dots\)


    Suppose that \((G,+,-,<,0,1)\) is a model of Pr. For each \(n\), axiom (4)
    asserts that \(P_n^G=nG\). Axiom (5) asserts that
    \(\frac{G}{nG}\cong \frac{\Z}{n\Z}\)


** Algebraically Closed Fields
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   \(\ACF_\forall\) is the theory of integral domains
   #+END_lemma

   #+BEGIN_proof
   The axioms for integral domains are universal consequences of ACF. If \(D\)
   is an integral domain, then the algebraic closure of the fraction field of
   \(D\) is a model of ACF. Because every integral domain is a subring of an
   algebraically closed field, \(\ACF_\forall\) is the theory of integral
   domains by Exercise ref:ex2.5.10
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.2.2
   ACF has quantifier elimination
   #+END_theorem

   #+BEGIN_proof
   We will apply Corollary ref:cor3.1.12. If \(D\) is an integral domain, then
   the algebraic closure of the fraction field of \(D\) embeds into any
   algebraically closed field containing \(D\). Thus ACF has algebraically prime
   models

   To prove quantifer elimination, we need only show that if \(K\) and \(F\) are
   algebraically closed fields, \(F\subseteq K\), \(\phi(x,\overbar{y})\) is
   quantifier-free, \(\overbar{a}\in F\), and \(K\vDash\phi(b,\overbar{a})\)
   for some \(b\in K\), then \(F\vDash\exists v\;\phi(v,\overbar{a})\)

   As in Lemma ref:lemma3.1.7, we may assume that \(\phi(x,\overbar{y})\) is a
   conjunction of atomic and negated atomic formulas. In the language of rings,
   atomic formulas \(\phi(v_1,\dots,v_n)\) are of the form \(p(\overbar{v})=0\),
   where \(p\in\Z[x_1,\dots,x_n]\). If \(p(X,\overbar{Y})\in\Z[X,\overbar{Y}]\),
   we can view \(p(X,\overbar{a})\) as a polynomial in \(F[X]\). Thus there are
   polynomails \(p_1,\dots,p_n,q_1,\dots,q_m\in F[X]\) s.t.
   \(\phi(v,\overbar{a})\) is equivalent to
   \begin{equation*}
   \bigwedge_{i=1}^np_i(v)=0\wedge
   \bigwedge_{i=1}^mq_i(v)\neq0
   \end{equation*}
   If any of the polynomials \(p_i\) are nonzero, then \(b\) is algebraic over
   \(F\). In this case, \(b\in F\) because \(F\) is algebraically closed. Thus
   we may assume that \(\phi(v,\overbar{a})\) is equivalent to
   \begin{equation*}
   \bigwedge_{i=1}^mq_i(v)\neq0
   \end{equation*}
   But  \(q_i(X)=0\) has only finitely many solutions for each \(i\le m\). Thus
   there are only finitely many elements of \(F\) that do not satisfy \(F\).
   Because algebraically closed fields are infinite, there is a \(c\in F\) s.t.
   \begin{equation*}
   F\vDash\phi(c,\overbar{a})
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:cor3.2.3
   ACF is model-complete and \(\ACF_p\) is complete where \(p=0\) or \(p\) is prime
   #+END_corollary
   #+BEGIN_proof
   Suppose that \(K,L\vDash\ACF_p\). Let \phi be any sentence in the language
   of rings. By quantifer elimination, there is a quantifer-free sentence \psi
   s.t.
   \begin{equation*}
   \ACF\vDash\phi\leftrightarrow\psi
   \end{equation*}
   Because quantifer-free sentences are preserved under extension and
   substructure,
   \begin{equation*}
   K\vDash\psi\Leftrightarrow\F_p\vDash\psi\Leftrightarrow L\vDash\psi
   \end{equation*}
   Thus \(K\equiv L\) and \(\ACF_p\) is complete
   #+END_proof

*** Zariski Closed and Constructible Sets
    Let \(K\) be a field. If \(S\subseteq K[X_1,\dots,X_n]\), let
    \(V(S)=\{a\in K^n:p(a)=0\text{ for all }p\in S\}\). If \(Y\subseteq K^n\),
    we let
    \(I(Y)=\{f\in K[X_1,\dots,X_n]:f(\overbar{a})=0\text{ for all
    }\overbar{a}\in Y\}\).
    We say \(X\subseteq K^n\) is *Zariski closed* if \(X=V(S)\) for some
    \(S\subseteq K[X_1,\dots,X_n]\)

    The *radical* of an ideal \(I\) in a commutative ring \(R\)
    , denoted by \(\sqrt{I}\), is defined as
    \begin{equation*}
    \sqrt{I}=\{r\in R\mid r^n\in I\text{ for some }n\in\Z^+\}
    \end{equation*}

    \(I\) is a radical ideal iff \(I=\sqrt{I}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.2.4
    Let \(K\) be a field
    1. If \(X\subseteq K^n\), then \(I(X)\) is a radical ideal
    2. If \(X\) is Zariski closed, then \(X=V(I(X))\)
    3. If \(X\) and \(Y\) are Zariski closed and \(X\subseteq Y\subseteq K^n\),
       then \(I(Y)\subseteq I(X)\)
    4. If \(X,Y\subseteq K^n\) are Zariski closed, then \(X\cup Y=V(I(X)\cap
       I(Y))\) and \(X\cap Y=V(I(X)+I(Y))\)
    #+END_lemma

    #+BEGIN_proof
    1. Suppose that \(p,q\in I(X)\) and \(f\in K[X_1,\dots,X_n]\). If
       \(a\in X\), then \(p(a)+q(a)=f(a)p(a)=0\). Thus \(p+q,fp\in I(X)\) and
       \(I(X)\) is an ideal. If \(f^n\in I(X)\) and \(a\in X\), then
       \(f^n(a)=0\) so \(f(a)=0\). Thus \(f\in I(X)\) and \(I(X)\) is a radical ideal
    2. If \(a\in X\) and \(p\in I(X)\), then \(p(a)=0\). Thus
       \(X\subseteq V(I(X))\). If \(a\in V(I(X))\setminus X\), then there is
       \(p\in I(X)\) s.t. \(p(a)\neq0\), a contradiction
    3. If \(p\in I(Y)\) and \(a\in X\), then \(p(a)=0\) and \(I(Y)\subseteq
       I(X)\). By (2), if \(I(X)=I(Y)\), then \(X=Y\)
    4. If \(p\in I(X)\cap I(Y)\), then \(p(a)=0\) for \(a\in X\) or \(a\in Y\).
       Thus \(X\cup Y\subseteq V(I(X)\cap I(Y))\). If \(a\not \in X\cup Y\),
       there are \(p\in I(X)\) and \(q\in I(Y)\) s.t. \(p(a)\neq0\) and
       \(q(a)\neq0\). But then \(p(a)q(a)\neq0\). Because \(pq\in I(X)\cap
       I(Y)\), \(a\not\in V(I(X)\cap I(Y))\)

       If \(a\in X\cap Y\), \(p\in I(X)\), \(q\in I(Y)\), then \(p(a)+q(a)=0\).
       Thus \(X\cap Y\subseteq V(I(X)+I(Y))\). If \(a\not\in X\), then there is
       \(p\in I(X)\subseteq I(X)+I(Y)\) s.t. \(p(a)\neq0\). Thus \(a\not\in
       V(I(X)+I(Y))\). Similarly, if \(a\not\in Y\), then \(a\not\in V(I(X)+I(Y))\)
    #+END_proof

    #+ATTR_LATEX: :options [Hilbert's Basis Theorem]
    #+BEGIN_theorem
    If \(K\) is a field, then the polynomial ring \(K[X_1,\dots,X_n]\) is a
    Noetherian ring, (i.e., there are no infinite ascending chains of ideals).
    In particular, every ideal is finitely generated
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    1. There are no infinite descending sequences of Zariski closed sets
    2. If \(X_i\) is Zariski closed for \(i\in I\), then there is a finite
       \(I_0\subseteq I\) s.t.
       \begin{equation*}
       \bigcap_{i\in I}X_i=\bigcap_{i\in I_0}X_i
       \end{equation*}
       In particular, an arbitrary intersection of Zariski closed sets is
       Zariski closed
    #+END_corollary

* Realizing and Omitting Types

** Types
    Suppose that \(\calm\) is an \(\call\)-structure and \(A\subseteq M\). Let \(\call_A\) be the language obtained by
    adding to \(\call\) constant symbols for each \(a\in A\). We can naturally view \(\calm\) as
    an \(\call_A\)-structure by interpreting the new symbols in the obvious way. Let \(\Th_A(\calm)\) be the
    set of all \(\call_A\)-sentences true in \(\calm\). Note that \(\Th_A(\calm)\subseteq\Diag_{el}(\calm)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(p\) be the set of \(\call_A\)-formulas in free variables \(v_1,\dots,v_n\). We call \(p\) an
    *\(n\)-type* if \(p\cup\Th_A(\calm)\) is satisfiable. We say that \(p\) is a *complete \(n\)-type*
    if \(\phi\in p\) or \(\neg\phi\in p\) for all \(\call_A\)-formulas \phi with free variables from \(v_1,\dots,v_n\). We
    let \(S_n^{\calm}(A)\) be the set of all complete \(n\)-types.
    #+END_definition

    #+BEGIN_remark
    Wu's remark: guess here \(p\cup\Th_A(\calm)\) is satisfiable means that there is a model \(\fN\vDash\Th_A(\calm)\)
    that realizes \(p\), which is slightly different from "there is an elementary extension
    of \(\fM\) that realizes \(p\)"
    #+END_remark

    Consider \(\calm=(\Q,<)\)and \(A=\N\), let \(q(v)=\{\phi(v)\in\call_A:\calm\vDash\phi(\frac{1}{2})\}\). \(q(v)\) is a complete 1-type

    We sometimes refer to incomplete types as *partial types*

    By the compactness theorem, we could replace "satisfiable" by "finitely satisfiable"

    If \(\calm\) is any \(\call\)-structure, \(A\subset M\), and \(\bara=(a_1,\dots,a_n)\in M^n\), let
    \(\tp^{\calm}(\bara/A)=\{\phi(v_1,\dots,v_n)\in\call_A:\calm\vDash\phi(a_1,\dots,a_n)\}\). Then \(\tp^{\calm}(\bara/A)\) is a
    complete \(n\)-type. We write \(\tp^{\calm}(\bara)\) for \(\tp^{\calm}(\bara/\emptyset)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(p\) is an \(n\)-type over \(A\), we say that \(\bara\in M^n\) *realizes* \(p\) if \(\calm\vDash\phi(\bara)\)
    for all \(\phi\in p\). If \(p\) is not realized in \(\calm\) we say that \(\calm\) *omits* \(p\).
    #+END_definition

    \(1/2\) realizes \(q(v)\). And there are many realizations of \(q(v)\) in \(\calm\). Suppose
    that \(r\in\Q\) and \(0<r<1\). We can construct an automorphism \sigma of \(\calm\) that fixes every natural
    number but \(\sigma(1/2)=r\). Because \sigma fixes all elements of \(A\), \sigma is also
    an \(\call_A\)-automorphism. By Theorem ref:thm1.1.10
    \begin{equation*}
    \calm\vDash\phi(1/2)\Longleftrightarrow\calm\vDash\phi(r)
    \end{equation*}
    In fact, the elements of \(\Q\) that realize \(q(v)\) are exactly the rational number \(s\) s.t. \(0<s<1\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:prop4.1.3
    Let \(\calm\) be an \(\call\)-structure, \(A\subseteq M\), and \(p\) an \(n\)-type over \(A\). There is \(\caln\) an
    elementary extension of \(\calm\) s.t. \(p\) is realized in \(\caln\).
    #+END_proposition

    #+BEGIN_proof
    Let \(\Gamma=p\cup\Diag_{\el}(\calm)\). We claim that \Gamma is satisfiable

    Suppose that \Delta is a finite subset of \Gamma. W.L.O.G., \Delta is the single formula
    \begin{equation*}
    \phi(v_1,\dots,v_n,a_1,\dots,a_m)\wedge\psi(a_1,\dots,a_m,b_1,\dots,b_l)
    \end{equation*}
    where \(a_1,\dots,a_m\in A\), \(b_1,\dots,b_l\in M\setminus A\), \(\phi(\barv,\bara)\in p\) and \(\calm\vDash\psi(\bara,\barb)\).
    Let \(\caln_0\) be a model of the satisfiable set of sentences \(p\cup\Th_A(\calm)\).
    Because \(\exists\barw\psi(\bara,\barw)\in\Th_A(\calm)\),
    \begin{equation*}
    \caln_0\vDash\phi(\barv,\bara)\wedge\exists\barw\psi(\bara,\barw)
    \end{equation*}
    By interpreting \(b_1,\dots,b_l\) as witnesses to \(\exists\barw\psi(a_1,\dots,a_m,\barw)\), we make \(\caln_0\vDash\Delta\).
    Thus \Delta is satisfiable.

    By the Compactness Theorem, \Gamma is satisfiable. Let \(\caln\vDash\Gamma\). Because \(\caln\vDash\Diag_{\el}(\calm)\), the map
    that sends \(m\in M\) to the interpretation of the constant symbol \(m\) in \(\caln\) is an elementary
    embedding. Let \(c_i\in N\) be the interpretation of \(v_i\). Then \((c_1,\dots,c_n)\) is a realization
    of \(p\).
    #+END_proof

    If \(\caln\) is an elementary extension of \(\calm\), then \(\Th_A(\calm)=\Th_A(\caln)\). Thus \(S_n^{\calm}(A)=S_n^{\caln}(A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(p\in S_n^{\calm}(A)\) iff there is an elementary extension \(\caln\) of \(\calm\) and \(\bara\in N^n\) s.t. \(p=\tp^{\caln}(\bara/A)\)
    #+END_corollary

    #+BEGIN_proof
    If \(\bara\in N^n\), then \(\tp^{\caln}(\bara/A)\in S_n^{\caln}(A)=S_n^{\calm}(A)\).

    On the other hand if \(p\in S_n^{\calm}(A)\), then by Proposition ref:prop4.1.3 there is an elementary
    extension \(\caln\) of \(\calm\) and \(\bara\in\calm\) realizing \(p\). Because \(p\) is complete,
    if \(\phi(\barv)\in\call_A\), then exactly one of \(\phi(\barv)\) and \(\neg\phi(\barv)\) is in \(p\).
    Thus \(\phi(\barv)\in\tp^{\caln}(\bara/A)\) iff \(\phi(\barv)\in p\) and \(p=\tp^{\caln}(\bara/A)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:prop4.1.5
    Suppose that \(\calm\) is an \(\call\)-structure and \(A\subseteq M\). Let \(\bara,\barb\in M^n\)
    s.t. \(\tp^{\calm}(\bara/A)=\tp^{\calm}(\barb/A)\). Then there is \(\caln\) an elementary extension of \(\calm\)
    and \sigma an automorphism of \(\caln\) fixing all elements of \(A\) s.t. \(\sigma(\bara)=\barb\).
    #+END_proposition

    If \(\calm\) and \(\caln\) are \(\call\)-structures and \(B\subseteq M\), we say that \(f:B\to N\) is a *partial*
    *elementary map* iff
    \begin{equation*}
    \calm\vDash\phi(\barb)\Longleftrightarrow\caln\vDash\phi(f(\barb))
    \end{equation*}
    for all \(\call\)-formulas \phi and all finite sequences \(\barb\in B\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma4.1.6
    Let \(\calm,\caln,B\) be as above and let \(f:B\to N\) be partial elementary. If \(b\in M\), there is an
    elementary extension \(\caln_1\) of \(\caln\) and \(g:B\cup\{b\}\to \caln_1\) a partial elementary map extending \(f\).
    #+END_lemma

    #+BEGIN_proof
    Let \(\Gamma=\{\phi(v,f(a_1),\dots,f(a_n)):\calm\vDash\phi(b,a_1,\dots,a_n),a_1,\dots,a_n\in B\}\cup\Diag_{\el}(\caln)\). Note that here we
    have the range of \(f\) and therefore the range of \(\phi(f(\barb))\)

    Suppose that we find a structure \(\caln_1\) and an element \(c\in N_1\) satisfying all of the formulas
    in \Gamma, then we are done.

    Thus it suffices to show that \Gamma is satisfiable. By the Compactness Theorem it suffices to show
    that every finite subset of \Gamma is satisfiable in \(\caln\). Taking conjunctions, it is enough to show
    that if \(\calm\vDash\phi(\b,a_1,\dots,a_n)\), then \(\caln\vDash\exists v\phi(v,f(a_1),\dots,f(a_n))\) but this is clear because
    \(\calm\vDash\exists v\phi(v,a_1,\dots,a_n)\) and \(f\) is partial elementary
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor4.1.7
    If \(\calm\) and \(\caln\) are \(\call\)-structures, \(B\subseteq M\) and \(f:B\to N\) is a partial elementary map,
    then there is \(\caln'\) an elementary extension of \(\caln\) and \(g:\calm\to\caln'\) an elementary embedding
    #+END_corollary

    #+BEGIN_proof
    Let \(\kappa=\abs{M}\), and let \(\{a_\alpha:\alpha<\kappa\}\) be an enumeration of \(M\). Let \(\caln_0=\caln\), \(B_0=B\),
    and \(g_0=f\). Let \(B_\alpha=B\cup\{a_\beta:\beta<\alpha\}\). We inductively build an elementary chain \((N_\alpha:\alpha<\kappa)\)
    and \(g_\alpha:B_\alpha\to N_\alpha\) partial elementary s.t. \(g_\beta\subseteq g_\alpha\) for \(\beta<\alpha\)

    If \(\alpha=\beta+1\) and \(g_\beta:B_\beta\to N_\beta\) is partial elementary, then by Lemma ref:lemma4.1.6  we can
    find \(N_\beta\prec N_\alpha\) and \(g_\alpha:B_\alpha\to N_\alpha\)

    If \alpha is a limit ordinal, let \(N_\alpha=\bigcup_{\beta<\alpha}N_\beta\) and \(g_\alpha=\bigcup_{\beta<\alpha}g_\beta\). By Proposition
    ref:prop2.3.11 \(\caln_\alpha\) is an elementary extension of \(N_\beta\) for \(\beta<\alpha\) and \(f_\alpha\) is a partial
    elementary map.

    Let \(\caln'=\bigcup_{\alpha<\kappa}\caln_\alpha\) and \(g​=\bigcup_{\alpha<\kappa}g_\alpha\). Again by Proposition ref:prop2.3.11 \(\caln\prec\caln'\)
    and \(g\) is partial elementary. But \(\dom(g)=M\), so \(g\) is an elementary embedding of \(\calm\)
    into \(\caln'\)
    #+END_proof

    #+ATTR_LATEX: :options [Proof of \ref{prop4.1.5}]
    #+BEGIN_proof
    Let \(f:A\cup\{\alpha\}\to A\cup\{b\}\) s.t. \(f|A\) is the identity and \(f(a)=b\).
    Because \(\tp^{\calm}(a/A)=\tp^{\calm}(b/A)\), \(f\) is a partial elementary map. By Corollary
    ref:cor4.1.7 there is \(\caln_0\) an elementary extension of \(\calm\) and \(f_0:\calm\to\caln_0\) an elementary
    embedding extending \(f\).  We will build a sequence of elementary extensions
    \begin{equation*}
    \calm=\calm_0\prec\caln_0\prec\calm_1\prec\caln_1\prec\calm_2\prec\caln_2\prec\dots
    \end{equation*}
    and elementary embeddings \(f_i:\calm_i\to\caln_i\) s.t. \(f_0\subseteq f_1\subseteq f_2\dots\) and \(N_i\) is contained in the
    image of \(f_{i+1}\). Having done this, let
    \begin{equation*}
    \caln=\bigcup_{i<\omega}\caln_i=\bigcup_{i<\omega}\calm_i
    \end{equation*}
    and \(\sigma=\bigcup f_i\). By Proposition ref:prop2.3.11 \(\caln\) is an elementary extension of \(\calm\)
    and \(\sigma:\caln\to\caln\) is an elementary map s.t. \(\sigma|A\) is the identity and \(\sigma(a)=b\). By construction
    \sigma is surjective. Thus \sigma is the desired automorphism.

    Given \(f_i:\calm_i\to\caln_i\) we can view \(f_i^{-1}\) as a partial elementary map from the image of \(f_i\)
    into \(\calm_i\prec\caln_i\). By Corollary ref:cor4.1.7 we can find \(\calm_{i+1}\) an elementary extension
    of \(\caln_i\) and extend \(f_i^{-1}\) to an elementary embedding \(g_i:\caln_i\to\calm_{i+1}\)
    #+END_proof

*** Stone Spaces
    For \(\phi\) an \(\call_A\)-formula with free variables from \(v_1,\dots,v_n\), let
    \begin{equation*}
    [\phi]=\{p\in S^{\calm}(A):\phi\in p\}
    \end{equation*}
    If \(p\) is a complete type and \(\phi\vee\psi\in p\), then \(\phi\in p\) or \(\psi\in p\). Thus
    \([\phi\vee\psi]=[\phi]\cup[\psi]\)

    The *Stone topology* on \(S_n^{\calm}(A)\) is the topology by taking the sets \([\phi]\) as basic open
    sets.

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(S_n^{\calm}(A)\) is compact
    2. if \(S_n^{\calm}(A)\) is totally disconnected, that is if \(p,q\in S_n^{\calm}(A)\) and \(p\neq q\), then
       there is a clopen set \(X\) s.t. \(p\in X\) and \(q\not\in X\)
    #+END_lemma

    #+BEGIN_proof
    1. It suffices to show that every cover of \(S_n^{\calm}(A)\) by basic open sets has a finite
    subcover. Suppose not. Let \(C=\{[\phi_i(\barv)]:i\in I\}\) be a cover of \(S_n^{\calm}(A)\) by basic
    open sets with no finite subcover. Let
    \begin{equation*}
    \Gamma=\{\neg\phi_i(\barv):i\in I\}
    \end{equation*}
    We claim that \(\Gamma\cup\Th_A(\calm)\) is satisfiable. If \(I_0\) is a finite subset of \(I\), then
    because there is no finite subcover of \(C\), there is a type \(p\) s.t.
    \begin{equation*}
    p\not\in\bigcup_{i\in I_0}[\phi_i]
    \end{equation*}
    Let \(\caln\) be an elementary extension of \(\calm\) containing a realization \(\bara\) of \(p\). Then
    \begin{equation*}
    \caln\vDash\Th_A(\calm)\cup\bigwedge_{i\in I_0}\neg\phi_i(\bara)
    \end{equation*}
    Hence \Gamma is satisfiable

    Let \(\caln\) be an elementary extension of \(\calm\), and let \(\bara\in\caln\) realize \Gamma. Then
    \begin{equation*}
    \tp^{\caln}(\bara/A)\in S_n^{\calm}(A)\setminus\bigcup_{i\in I}[\phi_i(\barv)]
    \end{equation*}
    a contradiction

    2. [@2] if \(p\neq q\), there is a formula \phi s.t. \(\phi\in p\) and \(\neg\phi\in q\). Thus \([\phi]\) is a basic
       clopen set separating \(p\) and \(q\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(A\subseteq B\subset M\) and \(p\in S_n^{\calm}(B)\), let \(p|A\) be  the set of \(\call_A\)-formulas in \(p\).
       Then \(p|A\in S_n^{\calm}(A)\) and \(p\mapsto p|A\) is a continuous map from \(S_n^{\calm}(B)\) onto \(S_n^{\calm}(A)\)
    2. if \(f:\calm\to\caln\) is an elementary embedding and \(p\in S_n^{\calm}(A)\), let
       \begin{equation*}
       f(p)=\{\phi(\barv,f(\bara)):\phi(\barv,\bara)\in p\}
       \end{equation*}
       Then \(f(p)\in S_n^{\caln}(f(A))\) and \(p\mapsto f(p)\) is continuous
    3. if \(f:A\to\caln\) is partial elementary, then \(S_n^{\calm}(A)\) is homeomorphic to \(S_n^{\caln}(f(A))\)
    #+END_lemma

    #+BEGIN_proof
    1. Because \(p|A\cup\Th_A(\calm)\subseteq p\cup\Th_B(\calm)\), \(p|A\cup\Th_A(\calm)\) is satisfiable.  Because \(p|A\) is
       the set of all \(\call_A\)-formulas in \(p\), \(p|A\) is complete. If \phi is an \(\call_A\)-formula,
       then
       \begin{equation*}
       \{p\in S_n^{\calm}(B):\phi\in p\}=[\phi]
       \end{equation*}
       Thus the map is continuous. Here we consider the basic open sets.

       if \(q\in S_n^{\calm}(A)\), there is an elementary extension \(\caln\) of \(\calm\) and \(\bara\in N\)
       realizing \(q\). Then \(p=\tp^{\caln}(\bara/B)\in S_n^{\calm}(B)\) and \(p|A=q\). Thus the restriction
       map is surjective

    2. Suppose \Delta is a finite subset of \(f(p)\). Say
       \begin{equation*}
       \Delta=\{\phi_1(\barv,f(\bara),\dots,\phi_m(\barv,f(\bara)))\}
       \end{equation*}
       where \(\phi_1(\barv,\bara),\dots,\phi_m(\barv,\bara)\in p\). Because \(p\cup\Th_A(\calm)\) is satisfiable,
       \begin{equation*}
       \calm\vDash\exists\barv\bigwedge_{i=1}^m\phi_i(\barv,\bara)
       \end{equation*}
       Because \(f\) is elementary
       \begin{equation*}
       \caln\vDash\exists\barv\bigwedge_{i=1}^m\phi_i(\barv,\bara)
       \end{equation*}
       and \(f(p)\cup\Th_{f(A)}(\caln)\) is satisfiable. \(f(p)\) is complete since \(\fM\equiv\fN\).

       Because
       \begin{equation*}
       \{p\in S_n^{\calm}(A):\phi(\barv,f(\bara))\in f(p)\}=[\phi(\barv,\bara)]
       \end{equation*}
       \(p\mapsto f(p)\) is continuous

    3. since we map onto \(f(A)\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that \(p\in S_n^{\calm}(A)\) is *isolated* if \(\{p\}\) is an open subset of \(S_n^{\calm}(A)\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(p\in S_n^{\calm}(A)\). The following are equivalent
    1. \(p\) is isolated
    2. \(\{p\}=[\phi(\barv)]\) for some \(\call_A\)-formula \(\phi(\barv)\). We say that \(\phi(\barv)\) isolates \(p\)
    3. There is an \(\call_A\)-formula \(\phi(\barv)\in p\) s.t. for
       all \(\call_A\)-formulas \(\psi(\barv)\), \(\psi(\barv)\in p\) iff
       \begin{equation*}
       \Th_A(\calm)\vDash\phi(\barv)\to\psi(\barv)
       \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    \(1\to 2\). If \(X\) is open, then
    \begin{equation*}
       X=\bigcup_{i\in I}[\phi_i]
    \end{equation*}
    for some collection of formulas \(\{\phi_i:i\in I\}\). If \(\{p\}\) is open, then \(\{p\}=[\phi]\) for some
    formula \phi

    \(2\to 3\).
    #+END_proof

*** Examples
    *Dense Linear Order*.

    Let \(\call=\{<\}\). Let \(\calm=(M,<)\) be a dense linear order without endpoints and let \(A\subseteq M\).
    Let \(p\in S_1^{\calm}(A)\). If \(a\in A\), then because \(p\) is a complete type, exactly one of the
    formulas \(v=a\), \(v<a\), or \(v>a\) is in \(p\).

    _case 1_: \(p\) is realized in \(A\)

    \(v=a\in p\) for some \(a\in A\). In this case, \(p=\{\psi(v):\calm\vDash\psi(a)\}\) and \(p\) is isolated by the
    formula \(v=a\).

    _case 2_: Otherwise

    Let \(L_p=\{a\in A:a<v\in p\}\) and \(U_p=\{a\in A:v<a\in p\}\). If \(a<v,v<b\in p\), because \(p\cup\Th_A(\calm)\)
    is satisfiable, \(a<b\). Thus, \(a<b\) for \(a\in L_p\) and \(b\in U_p\) and \(L_p\) and \(U_p\)
    determine a cut in the ordering \((A,<)\)

    Also note that if \(A\) is the disjoint union of \(L\) and \(U\) where \(a<b\) for \(a\in L\)
    and \(b\in U\), then \(\Th_A(\calm)\cup\{a<v:a\in L\}\cup\{v<b:b\in U\}\) is satisfiable. Thus, there is a
    type \(p\) with \(L_p=L\) and \(U_p=U\).

    We claim that the cut completely determines \(p\); that is,
    \begin{equation*}
    \{p\}=\bigcap_{a\in L_p}[a<v]\cap\bigcap_{a\in U_p}[v<b]
    \end{equation*}
    Suppose that \(q\neq p\), \(L_p=L_q\) and \(U_p=U_q\). Because the only atomic formulas are \(u=v\)
    and \(u<v\), \(p\) and \(q\) determine the same cut in \(A\), and they contain the same atomic
    formulas. Because quantifier-free formulas are Boolean combinations of atomic formulas, \(p\)
    and \(q\) contain the same quantifier-free formulas. Because every formula is equivalent to a
    quantifier-free formula, \(p=q\)

    Using the identification between types and cuts, we can give a complete description of all types
    in \(S_1^{\Q}(\Q)\)

    For \(a\in\Q\), let \(p_a\) be the unique type containing \(v=a\).

    Let \(p_{+\infty}\) be the unique type \(p\) with \(L_p=\infty\) and \(U_p=\emptyset\), and let \(p_{-\infty}\) be the
    unique type \(p\) with \(L_p=\emptyset\) and \(U_p=\Q\). For \(r\in\R\setminus\Q\), let \(p_r\) be the unique
    type \(p\) with \(L_p=\{a\in\Q:a<r\}\) and \(U_p=\{b\in\Q:r<b\}\). For \(c\in\Q\), let \(p_{c^+}\) be the
    unique type \(p\) with \(L_p=\{a\in\Q:a\le c\}\) and \(U_p=\{b\in\Q:c<b\}\) and \(p_{c^-}\) be the unique
    type \(p\) with \(L_p=\{a\in\Q:a<c\}\) and \(U_p=\{b\in\Q:c\le b\}\). These are all possible types. Note in
    particular that \(\abs{S_1^{\Q}(\Q)}=2^{\aleph_0}\)

    We return to the general case where \(\calm\vDash\DLO\) and \(A\subseteq M\) is nonempty. Aside from the types
    realized by elements of \(A\), what types in \(S_1^{\calm}\) are isolated? Suppose that \(L_p\) has a
    largest element \(a\) and \(U_p\) has a smallest element \(b\). Then \(p\in[a<v<b]\).
    Moreover, \(\Th_A(\calm)\vDash a<v<b\to c<v<d\) for all \(c\in L_p\) and \(d\in U_p\). Thus \(a<v<b\)
    isolates \(p\). Similarly, if \(U_p=\emptyset\) and \(L_p\) has a greatest element \(a\), then \(a<v\)
    isolates \(p\), and if \(U_p\) has a smallest element \(b\) and \(L_p=\emptyset\), then \(v<b\)
    isolates \(p\).

    We claim that these are the only possibilities. For example, suppose that \(U_p\neq\emptyset\) and has no
    least element. Suppose that \(\phi(v)\) isolates \(p\). Because \(U_p\) and \(L_p\)
    determine \(p\),
    \begin{equation*}
    \Th_A(\calm)\cup\{a<v:a\in L_p\}\cup\{v<b:v\in U_p\}\vDash\phi(v)
    \end{equation*}
    Thus we can find \(a\in L_p\cup\{-\infty\}\) and \(b\in U_p\) s.t.
    \begin{equation*}
    \Th_A(\calm)\vDash\{a<v<b\}\to\phi(v)
    \end{equation*}
    There is \(c\in U_p\) s.t. \(c<b\). Because \(a<c<b\), \(\calm\vDash\phi(c)\). But then the type
    containing \(v=c\) is in \([\phi(v)]\) contradicting the fact that \([\phi(v)]\) isolates \(p\).

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\calm\vDash\DLO\) and let \(A\subseteq M\) be nonempty. Types in \(S_1^{\calm}(A)\) not realized by elements
    of \(A\) correspond to cuts in the ordering of \(A\). A nonrealized type \(p\) is nonisolated if
    either \(U_p\neq\emptyset\) has no least element or \(L_p\neq\emptyset\) has no greatest element
    #+END_proposition

    *Algebraically Closed Fields*.



* Indiscernibles
** Partition Theorems
    For \(X\) a set and \kappa,\lambda (possibly finite) cardinals, we let \([X]^\kappa\) be the collection of all
    subsets of \(X\) of size \kappa. We call \(f:[X]^\kappa\to\lambda\) a *partition* of \([X]^\kappa\). We say
    that \(Y\subseteq X\) is *homogeneous* for the partition \(f\) if there is \(\alpha<\lambda\) s.t. \(f(A)=\alpha\) for
    all \(A\in[Y]^\kappa\) (i.e. \(f\) is a constant on \([Y]^\kappa\)). Finally, for cardinals \kappa,\eta,\mu, and \lambda, we
    write \(\kappa\to(\eta)_\lambda^\mu\) if whenever \(\abs{X}>\kappa\) and \(f:[X]^\mu\to\lambda\), then there is \(Y\subseteq X\)
    s.t. \(\abs{Y}\ge\eta\) and \(Y\) is homogeneous for \(f\)

    #+ATTR_LATEX: :options [Ramsey's Theorem]
    #+BEGIN_theorem
    If \(k,n<\omega\), then \(\aleph_0\to(\aleph_0)^n_k\)
    #+END_theorem

    Some applications:

    Any sequence of real numbers \((r_0,r_1,\dots)\) has a monotonic subsequence. Let \(f:[\N]^2\to 3\) by
    \begin{equation*}
    f(\{i,j\})=
    \begin{cases}
    0&i<j\text{ and }r_i<r_j\\
    1&i<j\text{ and }r_i=r_j\\
    2&i<j\text{ and }r_i>r_j
    \end{cases}
    \end{equation*}
    By Ramsey's Theorem, there is \(Y\subseteq N\) an infinite homogeneous set for \(f\). Let \(j_0<j_1<\dots\)
    list \(Y\). There is \(c<3\) s.t. \(f(\{j_m,j_n\})=c\) for \(m<n\).

    Suppose \(G\) is an infinite graph. Let \(f:[G]^2\to 2\) by
    \begin{equation*}
    f(\{a,b\})=
    \begin{cases}
    1&(a,b)\text{ is an edge of }G\\
    0&(a,b)\text{ is not an edge of }G
    \end{cases}
    \end{equation*}
    By Ramsey's Theorem, there is an infinite \(H\subseteq G\) homogeneous for \(f\). If \(f\) is constantly
    1 on \([H]^2\), then \(H\) is a complete subgraph, and if \(f\) is constantly 0, there are no
    edges.

    #+BEGIN_proof
    Induction on \(n\). For \(n=1\) Ramsey's Theorem asserts that if \(X\) is infinite, \(k<\omega\),
    and \(f:X\to k\), then \(f^{-1}(i)\) is infinite for some \(i<k\). This is just the Pigeonhole
    Principle.

    Suppose that we have proved that if \(i<n\), \(k<\omega\), \(X\) is infinite, and \(f:[X]^i\to k\), then
    there is an infinite \(Y\subseteq X\) homogeneous for \(f\).

    We could always replace \(X\) by a countable subset of \(X\); thus, W.L.O.G., we may assume
    that \(X=\N\).

    Let \(f:[\N]^n\to k\). For \(a\in\N\), let \(f_a:[\N\setminus\{a\}]^{n-1}\to k\) by \(f_a(A)=f(A\cup\{a\})\). We build a
    sequence \(0=a_0<a_1<\dots\) in \(\N\) and \(\N=X_0\supset X_1\supset\dots\) a sequence of infinite sets as follows.
    Given \(a_i\) and \(X_i\), let \(X_{i+1}\subset X_i\setminus\{0,1,\dots,a_i\}\) be homogeneous for \(f_{a_i}\).
    Let \(a_{i+1}\) be the least element of \(X_{i+1}\)

    Let \(c_i<k\) be s.t. \(f_{a_i}(A)=c_i\) for all \(A\in[X_{i+1}]^{n-1}\). By the Pigeonhole
    Principle, there is \(c<k\) s.t. \(\{i:c_i=c\}\) is infinite. Let \(X=\{a_i:c_i=c\}\). We claim
    that \(X\) is homogeneous for \(f\). Let \(x_1<\dots<x_n\) where each \(x_i\in X\), there is an \(i\)
    s.t. \(x_1=a_i\) and \(x_2,\dots,x_n\in X_i\). Thus
    \begin{equation*}
    f(\{x_1,\dots,x_n\})=f_{x_1}(\{x_2,\dots,x_n\})=c_i=c
    \end{equation*}
    and \(X\) is homogeneous for \(f\).
    #+END_proof

    #+ATTR_LATEX: :options [Finite Ramsey Theorem]
    #+BEGIN_theorem
    For all \(k,n,m<\omega\), there is \(l<\omega\) s.t. \(l\to(m)^n_k\)
    #+END_theorem

    #+BEGIN_proof
    Suppose that there is no \(l\) s.t. \(l\to (m)_k^n\). For each \(l<\omega\),
    let
    \begin{align*}
    T_l=\{&f:[\{0,\dots,l-1\}]^n\to k:\text{ there is no }X\subseteq\{0,\dots,l-1\}\\
    &\text{ of size at least }m, \text{ homogeneous for }f
    \end{align*}
    Clearly each \(T_l\) is finite since \(n\) and \(k\) are finite. if \(f\in T_{l+1}\) there is a
    unique \(g\in T_l\) s.t. \(g\subset f\). Thus if we order \(T=\bigcup T_l\) by inclusion, we get a finite
    branching tree. Each \(T_l\) is not empty, so \(T\) is an infinite finite branching tree. By
    Kőnig's Lemma (Lemma ref:lemmaA.21) we can find \(f_0\subset f_1\subset f_2\dots\) with \(f_i\in T_i\)

    Let \(f=\bigcup f_i\). Then \(f:[\N]^n\to k\). By Ramsey's Theorem, there is an infinite \(X\subseteq\N\)
    homogeneous for \(f\). Let \(x_1,\dots,x_m\) be the first \(m\) elements of \(X\) and let \(s>x_m\).
    Then \(\{x_1,\dots,x_m\}\) is homogeneous for \(f_s\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(2^{\aleph_0}\slashed{\to}(3)^2_{\aleph_0}\)
    #+END_proposition

    #+BEGIN_proof
    We define \(F:[2^\omega]^2\to\omega\) by \(F(\{f,g\})\) is the least \(n\) s.t. \(f(n)=g(n)\). Clearly, we
    cannot find \(\{f,g,h\}\) s.t. \(f(n)\neq g(n)\), \(g(n)\neq h(n)\) and \(f(n)\neq h(n)\)
    #+END_proof

    On the other hand, if \(\kappa>2^{\aleph_0}\), then \(\kappa\to(\aleph_1)_{\aleph_0}^2\). This is the special case of an
    important generalization of Ramsey's Theorem. For \kappa an infinite cardinal and \alpha an ordinal, we
    inductively define \(\beth_\alpha(\kappa)\) by \(\beth_0(\kappa)=\kappa\) and
    \begin{equation*}
    \beth_\alpha(\kappa)=\sup_{\beta<\alpha}2^{\beth_\beta(\kappa)}
    \end{equation*}
    In particular, \(\beth_1(\kappa)=2^\kappa\). We let \(\beth_\alpha=\beth_\alpha(\aleph_0)\). Under the Generalized Continuum
    Hypothesis, \(\beth_\alpha=\aleph_\alpha\)

    #+ATTR_LATEX: :options [Erdős–Rado theorem]
    #+BEGIN_theorem
    \(\beth_n(\kappa)^+\to(\kappa^+)_\kappa^{n+1}\)
    #+END_theorem

    #+BEGIN_proof
    Induction on \(n\). For \(n=0\), \(\kappa^+\to(\kappa^+)^{n+1}_\kappa\) is just the Pigeonhole Principle

    Suppose that we have proved the theorem for \(n-1\). Let \(\lambda=\beth_n(\kappa)^+\), and
    let \(f:[\lambda]^{n+1}\to\kappa\). For \(\alpha<\lambda\), let \(f_\alpha:[\lambda\setminus\{\alpha\}]^n\to\kappa\) by \(f_\alpha(A)=f(A\cup\{\alpha\})\).

    We build \(X_0\subseteq X_1\subseteq\dots\subseteq X_\alpha\subseteq\dots\) for \(\alpha<\beth_{n-1}(\kappa)^+\) s.t. \(X_\alpha\subseteq\beth_n(\kappa)^+\) and each \(X_\alpha\) has
    cardinality at most \(\beth_n(\kappa)\). Let \(X_0=\beth_n(\kappa)\). If \alpha is a limit ordinal,
    then \(X_\alpha=\bigcup_{\beta<\alpha}X_\beta\)

    Suppose we have \(X_\alpha\) with \(\abs{X_\alpha}=\beth_n(\kappa)\). Because
    \begin{equation*}
    \beth_n(\kappa)^{\beth_{n-1}(\kappa)}=(2^{\beth_{n-1}(\kappa)})^{\beth_{n-1}(\kappa)}=2^{\beth_{n-1}(\kappa)}=\beth_n(\kappa)
    \end{equation*}
    there are \(\beth_n(\kappa)\) subsets of \(X_\alpha\) of cardinality \(\beth_{n-1}(\kappa)\). Also note that
    if \(Y\subset X_\alpha\) and \(\abs{Y}=\beth_{n-1}(\kappa)\), then there are \(\beth_n(\kappa)\) functions \(g:[Y]^n\to\kappa\)
    because
    \begin{equation*}
    \kappa^{\beth_{n-1}(\kappa)}=2^{\beth_{n-1}(\kappa)}=\beth_n(\kappa)
    \end{equation*}
    Thus we can find \(X_{\alpha+1}\subseteq X_\alpha\) s.t. \(\abs{X_{\alpha+1}}=\beth_n(\kappa)\) and if \(Y\subset X_\alpha\)
    with \(\abs{Y}=\beth_{n-1}(\kappa)\) and \(\beta\in\lambda\setminus Y\), then there is \(\gamma\in X_{\alpha+1}\setminus Y\) s.t.
    \(f_\beta|[Y]^n=f_\gamma|[Y]^n\) <<CANT UNDERSTAND>>
    #+END_proof
** Order Indiscernibles
    Let \(\calm\) be an \(\call\)-structure

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(I\) be an infinite set and suppose that \(X=\{x_i:i\in I\}\) is a set of distinct elements
    of \(\calm\). We say that \(X\) is an *indiscernible set* if whenever \(i_1,\dots,i_m\) and \(j_1,\dots,j_m\)
    are two sequences of \(m\) distinct elements of \(I\),
    then \(\calm\vDash\phi(x_{i_1},\dots,x_{i_m})\leftrightarrow \phi(x_{j_1},\dots,x_{j_m})\)
    #+END_definition

    For example, suppose that \(F\) is an algebraically closed field of infinite transcendence
    degree and \(x_1,x_2,\dots\) is an infinite algebraically independent set. For any two
    sequence \(i_1,\dots,i_m\) and \(j_1,\dots,j_m\), there is an automorphism \sigma of \(F\)
    with \(\sigma(x_{i_k})=x_{j_k}\) for \(k=1,\dots,m\). it follows that \(x_1,x_2,\dots\) is an infinite set of
    indiscernibles.

    If \((A,<)\) is an infinite linear order, then because we cannot have \(a<b\) and \(b<a\) there
    is no set of indiscernibles of size 2.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((I,<)\) be an ordered set, and let \((x_i:i\in I)\) be a sequence of distinct elements
    of \(M\), we say that \((x_i:i\in I)\) is a sequence of *order indiscernibles* if
    whenever \(i_1<i_2<\dots<i_m\) and \(j_1<\dots<j_m\) are two increasing sequences from \(I\),
    then \(\calm\vDash\phi(x_{i_1},\dots,x_{i_m})\leftrightarrow \phi(x_{j_1},\dots,x_{j_m})\)
    #+END_definition

    For example, in \((\Q,<)\), by quantifier elimination, if \(x_1<\dots<x_m\) and \(y_1<\dots<y_m\), then
    \(\Q\vDash\phi(\barx)\leftrightarrow\phi(\bary)\) for all \phi. Thus \(\Q\), itself, is a sequence of order indiscernibles

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(T\) be a theory with infinite models. For any infinite linear order \((I,<)\), there
    is \(\calm\vDash T\) containing \((x_i:i\in I)\), a sequence of order indiscernibles
    #+END_theorem

    #+BEGIN_proof
    Let \(\call^*=\call\cup\{c_i:i\in I\}\). Let \Gamma be the union of
    * \(T\)
    * \(c_i\neq c_j\) for \(i,j\in I\) with \(i\neq j\)
    * \(\phi(c_{i_1},\dots,c_{i_m})\to\phi(c_{j_1},\dots,c_{j_m})\) for all \(\call\)-formulas \(\phi(\barv)\),
      where \(i_1<\dots<i_m\) and \(j_1<\dots<j_m\) are increasing sequences from \(I\)


    If \(\calm\vDash\Gamma\), then \((c_i^{\calm}:i\in I)\) is an infinite sequence of order indiscernibles. It suffices
    to show that \Gamma is satisfiable. Suppose that \(\Delta\subset\Gamma\) is finite. Let \(I_0\) be the finite subset
    of \(I\) s.t. if \(c_i\) occurs in \Delta, then \(i\in I_0\). Let \(\phi_1,\dots,\phi_m\) be the formulas s.t.
    \Delta asserts indiscenibility w.r.t. the formula \(\phi_i\), \(i\le m\). Let \(v_1,\dots,v_n\) be the free
    variables from \(\phi_1,\dots,\phi_m\), \(i\le m\).

    Let \(\calm\) be an infinite model of \(T\). Fix < any linear order of \(\calm\). We will define a
    partition \(F:[M]^n\to\calp(\{1,\dots,m\})\). If \(A=\{a_1,\dots,a_n\}\) where \(a_1<\dots<a_n\), then
    \begin{equation*}
    F(A)=\{i:\calm\vDash\phi_i(a_1,\dots,a_n)\}
    \end{equation*}
    Because \(F\) partitions \([M]^n\) into at most \(2^m\) sets, we can find an
    infinite \(X\subseteq M\) homogeneous for \(F\). Let \(\eta\subseteq\{1,\dots,m\}\) s.t. \(F(A)=\eta\) for \(A\in[X]^n\).

    Suppose that \(I_0\) is a finite subset of \(I\). Choose \((x_i:i\in I_0)\) s.t. each \(x_i\in X\) and
    s.t. \(x_i<x_j\) if \(i<j\). If \(i_1<\dots<i_n\) and \(j_1<\dots<j_n\) then
    \begin{equation*}
    \calm\vDash\phi_k(x_{i_1},\dots,x_{i_n})\Longleftrightarrow k\in\eta\Longleftrightarrow\calm\vDash\phi_k(x_{j_1},\dots,x_{j_n})
    \end{equation*}
    If we interpret \(c_i\) as \(x_i\) for \(i\in I_0\), then we make \(\calm\) a model of \Delta. Note that
    here \(x_i\in M\) -.-
    #+END_proof

    if \((x_i:i\in I)\) is any sequence of order indiscernibles in \(M\), we can order \(X=\{x_i:i\in I\}\)
    by \(x_i<x_j\) if \(i<j\). In this way, we frequently identify \(X\) and \(I\)

    Suppose that \(\psi(x,y)\) is a formula in the language s.t. in some \(\calm\vDash T\), \psi linearly orders an
    infinite set \(Y\). When we did the construction above, we could add the condition
    that \(\psi(c_i,c_j)\) for \(i<j\). We would then restrict the partition to \([Y]^m\) and let the
    ordering < be the ordering determined by \psi. In this way, we would get an infinite sequence of
    indiscernibles \((x_i:i\in I)\) s.t. \(\psi(x_i,x_j)\) iff \(i<j\)
** Ehrenfeucht-Mostowski Models
    Suppose that our theory has built-in Skolem functions. Then when we have a model containing an
    infinite sequence of order indiscernibles, we can form the elementary submodel generated by the
    indiscernibles. <<Problem1>>


* Set Theory
** Cardinal Arithmetic
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:corA.15 
   1. If \(\abs{I}=\kappa\) and \(\abs{A_i}\le\kappa\) for all \(i\in I\), then 
      \(\abs{\bigcup A_i}\le\kappa\)
   2. If \kappa is regular, \(\abs{I}<\kappa\) and \(\abs{A_i}<\kappa\) for all 
      \(i\in I\), then \(\abs{\bigcup A_i}<\kappa\)
   3. Let \kappa be an infinite cardinal. Let $X$ be a set and \(\calf\) a set of
      functions \(f:X^{n_f}\to X\). Suppose that \(\abs{\calf}\le\kappa\) and
      \(A\subseteq X\) with \(\abs{A}\le\kappa\). Let \(\cl(A)\) be the smallest
      subset of $X$ containing $A$ closed under the functions in \(\calf\). Then 
      \(\abs{\cl(A)}\le\kappa\)
   #+END_corollary
** Finite Branching Trees
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *finite branching tree* is a partial order \((T,<)\) s.t.
    1. there is \(r\in T\) s.t. \(r\le x\) for all \(x\in T\)
    2. if \(x\in T\), then \(\{y:y<x\}\) is finite and linearly ordered by <
    3. if \(x\in T\), then there is a finite (possibly empty) set \(\{y_1,\dots,y_m\}\) of incomparable
       elements s.t. each \(y_i>x\) and if \(z>x\), then \(z\ge y_i\) for some \(i\)
    #+END_definition

    A *path* through \(T\) is a function \(f:\omega\to T\) s.t. \(f(n)<f(n+1)\) for all \(n\)

    #+ATTR_LATEX: :options [Kőnig's Lemma]
    #+BEGIN_lemma
    label:lemmaA.21
    If \(T\) is an infinite finite branching tree, then there is a path through \(T\)
    #+END_lemma

    #+BEGIN_proof
    Let \(S(x)=\{y:y\ge x\}\) for \(x\in T\). We inductively define \(f(n)\) s.t. \(S(f(n))\) is infinite
    for all \(n\). Let \(r\) be the minimal element of \(T\), then \(S(r)\) is infinite.
    Let \(f(0)=r\). Given \(f(n)\), let \(\{y_1,\dots,y_m\}\) be the immediate successors of \(f(n)\).
    Because \(S(f(n))=S(y_1)\cup\dots\cup S(y_n)\), \(S(y_i)\) is infinite for some \(i\). Let \(f(n+1)=y_i\).
    #+END_proof


* Reference
  bibliographystyle:alpha
  bibliography:/media/wu/file/stuuudy/notes/references.bib
* Index
  \renewcommand{\indexname}{}
  printindex:nil
  \appendix
[fn:stack]  [[https://math.stackexchange.com/questions/1170953/let-alpha-be-any-cardinal-there-are-at-most-2-alpha-cup-mathscrl][stackexchange]]
[fn:proofkappa] [[https://proofwiki.org/wiki/Field_of_Uncountable_Cardinality_K_has_Transcendence_Degree_K][proofwiki]]
* Problems :ignore:
    [[CANT UNDERSTAND]]
    [[Problem1]]
    [[Problem2]]
