#+title: Model Theory of Valued Field
#+AUTHOR: David Marker

#+EXPORT_FILE_NAME: ../latex/ModelTheoryOfValuedField/ModelTheoryOfValuedField/Model.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex


* Valued Fields - Definitions and Examples
** Valuations and Valuation Rings

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(A\) be an integral domain, \((\Gamma,+,0,<)\) be an ordered abelian group, a *valuation* is a
    map \(v:A^\times\to\Gamma\) s.t.
    1. \(v(ab)=v(a)+v(b)\)
    2. \(v(a+b)\ge\min(v(a),v(b))\)

    We refer to \((A,v)\) as a *valued ring*.

    A *valued field* \((K,v)\) is a field \(K\) with a valuation \(v\). The image of \(K\) under \(v\)
    is called the *value group* of \((K,v)\)
    #+END_definition

    Often we assume that the valuation \(v:K^\times\to\Gamma\) is surjective

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. Let \(K\) be a field and define \(v(x)=0\) for all \(x\in K^\times\). We call \(v\) the *trivial
       valuation* on \(K\)
    2. Let \(p\) be a prime number and define \(v_p\) on \(\Z\) by \(v_p(a)=m\)
       where \(a=p^mb\) where \(p\nmid b\). We call \(v_p\) the *\(p\)-adic valuation* on \(\Z\)
    3. Let \(F\) be a field and define \(v\) on \(F[X]\) s.t. \(v(f)=m\) where \(f=X^mg\)
       where \(g(0)\neq 0\). More generally, if \(p(X)\) is any irreducible polynomial we could
       define \(v_p(f)=m\) where \(f=p ^mg\) and \(p\nmid g\)
    4.

    #+END_examplle

    #+BEGIN_exercise
    1. If \(A\) is an domain, \(K\) is its field of fractions and \(v\) is a valuation on \(A\),
       show that we can extend \(v\) to \(K\) by \(v(a/.b)=v(a)-v(b)\)
    2. Show that this is the only way to extend \(v\) to a valuation on \(K\)
    #+END_exercise

    Thus we can extend the valuation \(v_p\) on \(\Z\) to \(v_p:\Q^\times\to\Z\)

    Let \(F\) be a field and let
    \begin{equation*}
    F\la T\ra=\bigcup_{n=1}^\infty F((F^{1/n}))
    \end{equation*}
    be the field  of *Puiseux series*. If \(f\in F\la T\ra\) is nonzero then for some \(m\in\Z\)
    and \(n\ge 1\), \(f=\sum_{i=m}^\infty a_iT^{i/n}\) and \(a_m\neq 0\). We let \(v(f)=m/n\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(v(1)=0\)
    2. \(v(-1)=0\)
    3. \(v(x)=v(-x)\)
    4. If \(K\) is a valued field and \(x\neq 0\), then \(v(1/x)=-v(x)\)
    5. if \(v(a)<v(b)\), then \(v(a+b)=v(a)\)
    #+END_lemma

    Suppose \((K,v)\) is a valued field. Let \(\calo=\{x\in K:v(x)\ge 0\}\), we call \(\calo\) the *valuation ring*
    of \(K\). Let \(U=\{x:v(x)=0\}\). If \(x\in U\), then \(1/x\in U\). Moreover, if \(v(x)>0\),
    then \(v(1/x)<0\). Thus \(U\) is the set of units of \(\calo\).
z
    Let \(\fm=\{x\in\calo:v(x)>0\}\). Then \(\fm\) is maximal ideal of \(\calo\) and \(\calo\) is local

    #+BEGIN_exercise
    Suppose \(A\) is a domain with fraction field \(K\) and \(\fp\subset A\) is a prime ideal. The
    *localization* of \(A\) at \(\fp\) is
    \begin{equation*}
    A_{\fp}=\{a/b\in K:a\in A\wedge b\notin\fp\}
    \end{equation*}
    Let
    \begin{equation*}
    A_{\fp}\fp=\{a_1p_1+\dots+a_mp_m:a_1,\dots,a_m\in A_{\fp},p_1,\dots,p_m\in\fp,m=1,2,\dots\}
    \end{equation*}
    Show that \(A_{\fp}\) is a local ring with maximal ideal \(A_{\fp}\fp\)
    #+END_exercise

    #+BEGIN_proof
    Prime ideals in \(A_{\fp}\) is in one-to-one correspondence with prime ideals in \(A\) contained
    in \(\fp\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    The ideals of \(\calo\) are linearly ordered by \(\subset\) with maximal element in \(\fm\)
    #+END_lemma

    #+BEGIN_proof
    Suppose \(\fp\) and \(\fq\) are prime ideals of \(\calo\), \(x\in\fp\setminus\fq\) and \(y\in\fq\setminus\fp\). W.L.O.G., we may
    assume \(v(x)\le v(y)\). Then \(v(y/x)=v(y)-v(x)\ge 0\) and therefore \(y/x\in\calo\). But
    then \(y=(y/x)x\in\fp\), a contradiction.
    #+END_proof

    Define \(\bk=\calo/\fm\), called the *residue field* of \((K,v)\) and let \(\res:\calo\to\bk\) be the residue
    map \(\res(x)=x/\fm\). Often we write \(\barx\) for \(\res(x)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. For the \(p\)-adic valuation on \(\Q\) the valuation ring is \(\Z_{(p)}=\{m/n:m,n\in\Z,p\nmid n\}\),
       the maximal ideal is \(p\Z_{(p)}\) and the residue field is \(\F_p\)
    2. Consider the field of formal Laurent series \(F((T))\) with valuation \(v(f)=m\)
       where \(f=\sum_{n=m}^\infty a_nT^n\) where \(a_m\neq 0\), then the valuation ring is \(F[[T]]\), the maximal
       ideal is all series \(\sum_{n=m}^\infty a_nT^n\) where \(m>0\) and the residue field is \(F\)
    #+END_examplle

    #+BEGIN_exercise
    1. Suppose \((K,v)\) is an algebraically closed valued field. Show that the value group is
       divisible and the residue field is algebraically closed
    #+END_exercise


    #+BEGIN_proof
    1. Given \(f=\sum a_ix^i\in\bk[x]\), \(a_i\neq 0\), take each \(a_i\)'s lifting \(b_i\) in \(\calo\) and we have
       \(g=\sum b_ix^i\in\calo[x]\)

       Claim: any solution of \(g\) is in \(\calo\)

       Note that each \(b_i\notin\bk\) and therefore \(v(b_i)=0\). Therefore \(v(x)=0\) and we are done
    #+END_proof

*** The valuation topology
    Let \(v:K^\times\to\Gamma\) be a valuation. Let \(a\in K\) and \(\gamma\in\Gamma\). Let
    \begin{equation*}
    B_\gamma(a)=\{x\in K:v(x-a)>\gamma\}
    \end{equation*}
    be the open ball centered at \(a\) of radius \gamma. The valuation topology on \(K\) is the weakest
    topology in which all \(B_\gamma(a)\) are open.

    Let
    \begin{equation*}
    \barB_\gamma(a)=\{x\in K:v(x-a)\ge\gamma\}
    \end{equation*}
    be the closed ball of radius \gamma centered at \(a\).

    If \(b\notin\barB_\gamma(a)\), then \(v(b-a)=\delta<\gamma\). If \(x\in B_\delta(b)\), then \(v(x-a)=v(x-b+a-b)\).
    Since \(v(x-b)>\delta\) and \(v(b-a)=\delta\), \(v(x-a)=\delta<\gamma\). Thus \(\barB_\gamma(a)\cap B_\delta(a)=\emptyset\) and closed
    balls are indeed closed in the valuation topology

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(b\in B_\gamma(a)\), then \(B_\gamma(a)=B_\gamma(b)\)
    #+END_lemma

    #+BEGIN_proof
    Let \(b\in B_\gamma(a)\). If \(v(x-a)>\gamma\), then
    \begin{equation*}
    v(x-b)=v(x-a+a-b)>\gamma
    \end{equation*}
    #+END_proof

    When we have a valuation \(v:K^\times\to\Z\), \(\barB_{n}(a)=B_{n+1}(a)\), thus the closed balls are
    also open. So there is a clopen basis for the topology

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Every closed ball is open
    #+END_lemma

    #+BEGIN_proof
    Let \(B=\barB_\gamma(a))\) be a closed ball. Consider the boundary
    \begin{equation*}
    \partial B=\{x:v(x-a)=\gamma\}
    \end{equation*}
    Suppose \(b\in\partial B\), if \(x\in B_\gamma(b)\), then
    \begin{equation*}
    v(x-a)=v(x-b+b-a)=\gamma
    \end{equation*}
    and \(B_\gamma(b)\) is contained in \(\partial B\). Thus
    \begin{equation*}
    B=B_\gamma(a)\cup\bigcup_{b\in\partial B}B_\gamma(b)
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that a domain \(A\) with fraction field \(K\) is a *valuation ring* if \(x\in A\)
    or \(x^{-1}\in A\) for all \(x\in K\)
    #+END_definition

    Let \(A\) be a valuation ring. Let \(U\) be the group of units of \(A\) and let \(\fm=A\setminus U\).  We
    claim that \(\fm\) is the unique maximal ideal of \(A\). If \(a\in\fm\) and \(b\in A\), then \(ab\notin U\)
    since otherwise \(1/a=b(1/ab)\in A\). If \(a,b\in\fm\), at least one of \(a/b\) or \(b/a\) belongs
    to \(A\). Suppose \(a/b\in A\), then \(a+b=b(a/b+1)\in\fm\), thus \(\fm\) is closed under addition so it
    is an ideal. If \(x\in A\setminus\fm\), then \(x\in U\), so no ideal of \(A\) contains \(x\). Thus \(\fm\) is
    the unique maximal ideal of \(A\). For \(x,y\in K^\times\) we say \(x\mid y\) if \(y/x\in A\)

    Let \(G=K^\times/U\), define a relation on \(G\) by \(x/U\le y/U\) iff \(x\mid y\). For \(u,v\in U\), we
    have \(x\mid y\) iff \(ux\mid vy\). Thus \(<\) is well-defined.  If \(x\mid y\) and \(y\mid x\),
    then \(x/y\in U\) and \(x/U=y/U\). If \(x/U\le y/U\) and \(y/U\le z/U\), then there is \(a,b\in A\)
    s.t. \(y=ax\) and \(z=by\). But then \(z=abx\) and \(x/U\le z/U\). Thus \(\le\) is a linear order of
    \Gamma. We write \(x/U<y/U\) if \(x\mid y\) and \(y\nmid x\)

    #+BEGIN_exercise
    Suppose \(x/U<y/U\) and \(z\in K^\times\). Show that \(x/U\cdot z/U<y/U\cdot z/U\)
    #+END_exercise

    Thus \((G,\cdot,<)\) is an ordered abelian group.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An ordered group \Gamma is *archimedean* if for all \(0<g<h\) there is \(n\in\N\) with \(ng>h\)
    #+END_definition

** Absolute Values
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *absolute value* on a ring \(A\) is a function \(\abs{\;}:A\to\R^{\ge 0}\) s.t.
    1. \(\abs{x}=0\Leftrightarrow \abs{x}=0\)
    2. \(\abs{xy}=\abs{x}\abs{y}\)
    3. \(\abs{x+y}\le\abs{x}+\abs{y}\)
    #+END_definition

    If \(v:A^\times\to\Gamma\) is a valuation where \(\Gamma\subseteq\R\) and \(0<\alpha<1\). Then we can construct an absolute
    value \(\abs{x}=\alpha^{v(x)}\). In this
    case \(\abs{x+y}=\alpha^{v(x+y)}\le\alpha^{\max(v(x),v(y))}=\max(\abs{x},\abs{y})\).

    Consider the field \(Q\). We have the usual absolute value on it which we will
    denote \(\abs{\cdot}_\infty\). For \(p\) a prime we have the absolute value \(\abs{x}_p=(1/p)^{v_p(a)}\).
    This choice of base is convenient as it gives the *product formula*
    \begin{equation*}
    \abs{x}_\infty\prod_{p\text{ prime}}\abs{x}_p=1
    \end{equation*}

*** Complete rings
    Suppose \((A,\abs{\cdot})\) is a domain with absolute value. We say that a
    sequence \((a_n:n=1,2,\dots)\) in \(A\) is *Cauchy* if for all \(\epsilon>0\) there is an \(n\) s.t.
    if \(i,j>n\) then \(\abs{a_i-a_j}<\epsilon\)

    We say that \(A\) is *complete* if every Cauchy sequence converges.

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Consider the ring of power series \(K((X))\) with the valuation \(v(f)=m\)
    where \(f=\sum_{n\ge m}a_nX^n\) where \(a_m\neq 0\) and the absolute value \(\abs{f}=\alpha^{v(f)}\)
    where \(0<\alpha<1\). Then \(K\) is complete
    #+END_lemma

    #+BEGIN_proof
    Suppose \(f_0,f_1,\dots\) is a Cauchy sequence. Suppose \(f_i=\sum_{n\in\N}a_{i,n}X^n\) where \(a_{i,n}=0\)
    for \(m>i\). Let \(\epsilon\le\alpha^{n}\). There is \(m_n\) s.t. if \(i,j>m_n\) then \(\abs{f_i-f_j}<\epsilon\).
    But then \(a_{i,k}=a_{j,k}\) for all \(k<n\). Let \(b_k\) be this common value. Let \(g=\sum_{k\in\N}b_kX^k\)
    #+END_proof

    #+BEGIN_exercise
    If \((A,\abs{\cdot})\)  is a complete domain, then the extension to the fraction field is also complete
    #+END_exercise

    If \(a\) is a domain with absolute value \(\abs{\cdot}\). We can follow the usual constructions from
    analysis to build a *completion* \(\hatA\) of \(A\). The elements of \(\hatA\) are equivalence
    classes of Cauchy sequences from \(A\) where \((a_n)\) and \((b_n)\) are equivalent iff for
    any \(\epsilon>0\) there is \(n\) s.t. \(\abs{a_i-b_j}<\epsilon\) for all \(i,j>n\). We can define an absolute
    value on \(\hatA\) \(\lim_{n\to\infty}\abs{a_n}\).

    #+BEGIN_exercise
    Complete the construction of \(\hatR\). Prove that it is a complete ring and that if \(L\supset K\) is
    any complete field with an absolute value extending the absolute value of \(K\), then there is
    an absolute value preserving embedding of \(\hatK\) into \(L\) fixing \(L\)
    #+END_exercise

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose \(A\) is a complete domain with nonarchimedean absolute value \(\abs{\cdot}\). If \((a_n)\)
    is a Cauchy sequence that does not converge to 0, then \(\abs{a_i}=\abs{a_j}\) for all
    sufficiently large \(i,j\). Thus when we pass to the completion \(\hatA\) we add no new absolute values
    #+END_lemma

    #+BEGIN_proof
    We can find an \(N\) and \epsilon s.t. \(\abs{a_n}>\epsilon\) and \(\abs{a_n-a_m}<\epsilon\) for all \(n,m>N\). But
    then since we have a nonarchimedean absolute value \(\abs{a_n}=\abs{a_m}\) for all \(n>N\)

    If \(\abs{a_m}>\abs{a_n}\), then \(\abs{a_m}\le\max(\abs{a_m-a_n},\abs{a_n})=\abs{a_n}\) leads to
    a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The ring of *\(p\)-adic integers* \(\Z_p\) is the completion of \(\Z\)  with the \(p\)-adic absolute
    value \(\abs{\cdot}_p\). Its fraction field is \(\Q_p\) the field of *\(p\)-adic numbers*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. Suppose \((a_n)\) is a sequence of integers, the series \(\sum_{i=0}^\infty a_ip^i\) converges in \(\Z_p\)
    2. The map \((a_n)\mapsto\Z_p\) is a bijection between \(\{0,\dots,p-1\}^\omega\) and \(\Z_p\)
    #+END_lemma

    #+BEGIN_proof
    1. If \(m<n\) then
       \begin{equation*}
       \abs{\sum_{i=0}^na_ip^i-\sum_{i=0}^ma_ip^i}<\frac{1}{p^m}
       \end{equation*}
       Thus the sequence of partial sums is Cauchy and hence convergent
    .2
    #+END_proof


*  Hensel's Lemma

** Hensel's Lemma, Equivalents and Applications
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that a local domain \(A\) with maximal ideal \(\fm\) is *henselian* if
    whenever \(f(x)\in A[X]\) and there is \(a\in A\) s.t. \(f(a)\in\fm\) and \(f'(a)\notin\fm\), then there
    is \(\alpha\in A\) s.t. \(f(\alpha)=0\) and \(\alpha-a\in\fm\)
    #+END_definition

    #+ATTR_LATEX: :options [Hensel's Lemma]
    #+BEGIN_theorem
    Suppose \(K\) is a complete field with nonarchimedean absolute value \(\abs{\cdot}\) and valuation
    ring \(\calo=\{x\in K:\abs{x}\le 1\}\). Then \(\calo\) is henselian
    #+END_theorem

    #+BEGIN_proof

    #+END_proof
