#+TITLE: Model Theory for Dummies: An Introduction
#+AUTHOR: David Marker


#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/ModelTheoryAnIntroduction/ModelTheoryAnIntroduction.tex
#+STARTUP: noindent
* Structures and Theories
** Languages and Structures
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A language $\call$ is given by specifying the following data
   1. A set of function symbols $\calf$ and positive integers $n_f$ for each
      $f\in\calf$
   2. a set of relation symbols $\calr$ and positive integers $n_R$ for each
      $R\in\calr$
   3. a set of constant symbols $\calc$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-structure $\calm$ is given by the following data
   1. a nonempty set $M$ called the *universe*, *domain* or *underlying set*
      of $\calm$
   2. a function $f^\calm:M^{n_f}\to M$ for each $f\in\calf$
   3. a set $R^\calm\subseteq M^{n_R}$ for each $R\in\calr$
   4. an element $c^\calm\in M$ for each $c\in\calc$
   #+END_definition

   We refer to $f^\calm,R^\calm,c^\calm$ as the *interpretations* of the
   symbols $f,R$ and $c$. We often write the structure as
   $\calm=(M,f^\calm,R^\calm,c^\calm:f\in\calf,R\in\calr,c\in\calc)$ 

   [[index:\(\call\)-embedding]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose that $\calm$ and $\caln$ are \(\call\)-structures with universes $M$
   and $N$ respectively. An *\(\call\)-embedding* $\eta:\calm\to\caln$ is a
   one-to-one map $\eta:M\to N$ that
   1. $\eta(f^\calm(a_1,\dots,a_{n_f}))=f^\caln(\eta(a_1),\dots,\eta(a_{n_f}))$
      for all $f\in\calf$ and $a_1,\dots,a_{n_f}\in M$
   2. $(a_1,\dots,a_{m_R})\in R^\calm$ if and only if
      $(\eta(a_1),\dots,\eta(a_{m_R}))\in R^\caln$ for all $R\in\calr$ and
      $a_1,\dots,a_{m_R}\in M$
   3. $\eta(c^\calm)=c^\caln$ for $c\in\calc$
   #+END_definition


   [[index:substructure]]
   A bijective \(\call\)-embedding is called an *\(\call\)-isomorphism*. If
   $M\subseteq N$ and the inclusion map is an \(\call\)-embedding, we say either
   $\calm$ is a *substrcture* of $\caln$ or that $\caln$ is an *extension*
   of $\calm$

   The *cardinality* of $\calm$ is $\abs{M}$, the cardinality of the universe of \(\calm\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The set of *\(\call\)-terms* is the smallest set $\calt$ s.t.
   1. $c\in\calt$ for each constant symbol $c\in\calc$
   2. each variable symbol $v_i\in\calt$ for $i=1,2,\dots$
   3. if $t_1,\dots,t_{n_f}\in\calt$ and $f\in\calf$ then
      $f(t_1,\dots,n_{n_f})\in\calt$ 
   #+END_definition


   Suppose that $\calm$ is an \(\call\)-structure and that $t$ is a term built
   using variables from $\bar{v}=(v_{i_1},\dots,v_{i_m})$. We want to interpret
   $t$ as a function $t^\calm:M^m\to M$. For $s$ a subterm of $t$ and
   $\bar{a}=(a_{i_1},\dots,a_{i_m})\in M$, we inductively define
   $s^\calm(\bar{a})$ as follows.
   1. If $s$ is a constant symbol $c$, then $s^\calm(\bar{a})=c^\calm$
   2. If $s$ is the variable $v_{i_j}$, then $s^\calm(\bar{a})=a_{i_j}$
   3. If $s$ is the term $f(t_1,\dots,t_{n_f})$, where $f$ is a function symbol
      of $\call$ and $t_1,\dots,t_{n_f}$ are terms, then 
      $s^\calm(\bar{a})=f^\calm(t^\calm_1(\bar{a}),\dots,t_{n_f}^\calm(\bar{a}))$

      
   The function $t^\calm$ is defined by $\bar{a}\mapsto t^\calm(\bar{a})$

   [[index:atomic formula]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \phi is an *atomic* *\(\call\)-formula* if \phi is either
   1. $t_1=t_2$ where $t_1$ and $t_2$ are terms
   2. $R(t_1,\dots,t_{n_R})$


   The set of *\(\call\)-formulas* is the smallest set $\calw$ containing the
   atomic formulas s.t.
   1. if $\phi\in\calw$, then $\neg\phi\in\calw$
   2. if $\phi,\psi\in\calw$, then $(\phi\wedge\psi),(\phi\vee\psi)\in\calw$
   3. if $\phi\in\calw$, then $\exists v_i\phi,\forall v_i\phi\in\calw$
   #+END_definition

   We say a variable $v$ *occurs freely* in a formula \phi if it is not
   inside a $\exists v$ or $\forall v$ quantifier; otherwise we say that it's
   *bound*. We call a formula a *sentence* if it has no free variables. We
   often write $\phi(v_1,\dots,v_n)$ to make explicit the free variables in \phi

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \phi be a formula with free variables from
   $\bar{v}=(v_{i_1,\dots,v_{i_m}})$ and let $\bar{a}=(a_{i_1},\dots,a_{i_m})\in
   M^m$. We inductively define $\calm\models\phi\bar{a}$ as follows
   1. If \phi is $t_1=t_2$, then $\calm\models\phi(\bar{a})$ if
      $t_1^\calm(\bar{a})=t_2^\calm(\bar{a})$ 
   2. If \phi is $R(t_1,\dots,t_{m_R})$ then $\calm\models\phi(\bar{a})$ if
      $(t_1^\calm(\bar{a}),\dots,t_{m_R}^\calm(\bar{a}))\in R^\calm$
   3. If \phi is $\neg\psi$ then $\calm\models\phi(\bar{a})$ if
      $\calm\not\models\psi(\bar{a})$
   4. If \phi is $(\psi\wedge\theta)$ then $\calm\models\phi(\bar{a})$ if
      $\calm\models\psi(\bar{a})$ and
      $\calm\models\theta(\bar{a})$
   5. If \phi is $(\psi\vee\theta)$ then $\calm\models\phi(\bar{a})$ if
      $\calm\models\psi(\bar{a})$ or
      $\calm\models\theta(\bar{a})$
   6. If \phi is $\exists v_j\psi(\bar{v},v_j)$ then $\calm\models\phi(\bar{a})$
      if there is $b\in M$ s.t. $\calm\models\psi(\bar{a},b)$
   7. If \phi is $\forall v_j\psi(\bar{v},v_j)$ then $\calm\models\phi(\bar{a})$
      if $\calm\models\psi(\bar{a},b)$ for all $b\in M$
   #+END_definition


   If $\calm\models\phi(\bar{a})$ we say that $\calm$ *satisfies*
   $\phi(\bar{a})$ or $\phi(\bar{a})$ is *true* in $\calm$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop1.1.8
   Suppose that $\calm$ is a substrcture of $\caln$, $\bar{a}\in M$ and
   $\phi(\bar{v})$ is a quantifier-free formula. Then
   $\calm\models\phi(\bar{a})$ if and only if $\caln\models\psi(\bar{a})$
   #+END_proposition

   #+BEGIN_proof
   *Claim* If $t(\bar{v})$ is a term and $\bar{b}\in M$ then
   $t^\calm(\bar{b})=t^\caln(\bar{b})$. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that two \(\call\)-strctures $\calm$ and $\caln$ are *elementarily*
   *equivalent* and write $\calm\equiv\caln$ if
   \begin{equation*}
    \calm\models\phi\text{ if and only if } \caln\models\phi
   \end{equation*}
   for all \(\call\)-sentences \phi
   #+END_definition

   [[index:full theory]]
   We let $\Th(\calm)$, the *full theory* of $\calm$ be the set of
   \(\call\)-sentences \phi s.t. $\calm\models\phi$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm1.1.10
   Suppose that $j:\calm\to\caln$ is an isomorphism. Then $\calm\equiv\caln$
   #+END_theorem

   #+BEGIN_proof
   Show by induction on formulas that $\calm\models\phi(a_1,\dots,a_n)$ if and
   only if $\caln\models\phi(j(a_1),\dots,j(a_n))$ for all formulas \phi
   #+END_proof
** Theories
   [[index:model]]
   [[index:satisfiable]]
   Let $\call$ be a language. An *\(\call\)-theory* $T$ is a set of
   \(\call\)-sentences. We say that $\calm$ is a *model* of $T$ and write
   $\calm\models T$ if $\calm\models\phi$ for all sentences $\phi\in T$. A
   theory is *satisfiable* if it has a model.

   [[index:elementary class]]
   A class of \(\call\)-structures $\calk$ is an *elementary class* if there
   is an \(\call\)-theory $T$ s.t. $\calk=\{\calm:\calm\models T\}$
   #+ATTR_LATEX: :options [Linear Orders]
   #+BEGIN_examplle
   Let \(\call=\{<\}\), where < is a binary relation symbol. The class of linear
   order is axiomatized by the \(\call\)-sentences
   \begin{align*}
   &\forall x\;\neg(x<x)\\
   &\forall x\forall y\forall z\;((x<y\wedge y<z)\to x<z)\\
   &\forall x\forall y\;(x<y\vee x=y\vee y<x)
   \end{align*}
   #+END_examplle

   #+ATTR_LATEX: :options [Groups]
   #+BEGIN_examplle
   Let $\call=\{\cdot,e\}$ where $\cdot$ is a binary function symbol and $e$ is a 
   constant symbol. The class of groups is axiomatized by
   \begin{align*}
   &\forall x\;e\cdot x=x\cdot e=x\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\exists y\;x\cdot y=y\cdot x= e
   \end{align*}
   #+END_examplle

   #+ATTR_LATEX: :options [Left \(R\)-modules]
   #+BEGIN_examplle
   Let $R$ be a ring with multiplicative identity 1. Let
   $\call=\{+,0\}\cup\{r:r\in R\}$ where $+$ is a binary function symbol, 0 is a
   constant, and $r$ is a unary function symbol for $r\in R$. In an
   \(R\)-module, we will interpret $r$ as scalar multiplication by $R$. The
   axioms for \(R\)-modules are
   \begin{align*}
   &\forall x\e r(x+y)=r(x)+r(y)\text{ for each }r\in R\\
   &\forall x\e (r+s)(x)=r(x)+s(x)\text{ for each }r,s\in R\\
   &\forall x\e r(s(x))=rs(x)\text{ for } r,s\in R\\
   &\forall x\e 1(x)=x
   \end{align*}
   #+END_examplle
   [[index:ACF]]
   #+ATTR_LATEX: :options [Rings and Fields]
   #+BEGIN_examplle
   Let $\call_r$ be the language of rings $\{+,-,\cdot,0,1\}$, where $+,-$ and $\cdot$
   are binary function symbols and $0$ and $1$ are constants. The axioms for rings are given 
   by
   \begin{align*}
   &\forall x\forall y\forall z\;(x-y=z\leftrightarrow x=y+z)\\
   &\forall x\;x\cdot 0=0\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\;x\cdot 1=1\cdot x=x\\
   &\forall x\forall y\forall z\;x\cdot(y+z)=(x\cdot y)+(x\cdot z)\\
   &\forall x\forall y\forall z\;(x+y)\cdot z=(x\cdot z)+(y\cdot z)
   \end{align*}
   We axiomatize the class of fields by adding
   \begin{align*}
   &\forall x\forall y\;x\cdot y=y\cdot x\\
   &\forall x\;(x\neq 0\to\exists y\;x\cdot y=1)
   \end{align*}
   We axiomatize the class of algebraically closed fields by adding to the field axioms the sentences
   \begin{equation*}
   \forall a_0\dots\forall a_{n-1}\exists x\;x^n+\displaystyle\sum_{i=1}^{n-1}
   a_ix^i=0
   \end{equation*}
   for $n=1,2,\dots$. Let \(\ACF\) be the axioms for algebraically closed fields.

   Let $\psi_p$ be the \(\call_r\)-sentence $\forall x\;
   \underbrace{x+\dots+x}_{p\text{-times}}=0$, which asserts that a field has characteristic
   $p$. For $p>0$ a prime, let $\ACF_p=\ACF\cup\{\psi_p\}$ and
   $\ACF_0=\ACF\cup\{\neg\psi_p:p>0\}$ be the theories of algebraically
   closed fields of characteristic $p$ and zero respectively
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence. We say that
   \phi is a *logical consequence* of $T$ and write $T\models\phi$ if
   $\calm\models\phi$ whenever $\calm\models T$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. Let $\call=\{+,<,0\}$ and let $T$ be the theory of ordered abelian groups.
      Then $\forall x(x\neq 0\to x+x\neq 0)$ is a logical consequence of $T$
   2. Let $T$ be the theory of groups where every element has order 2. Then\par
      $T\not\models\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proposition

   #+BEGIN_proof
   2. $\Z/2\Z\models T\wedge\neg\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proof
** Definable Sets and Interpretability
   [[index:definable]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\calm=(M,\dots)$ be an \(\call\)-structure. We say that $X\subseteq M^n$
   is *definable* if and only if there is an \(\call\)-formula 
   $\phi(v_1,\dots,v_n,w_1,\dots,w_m)$ and $\bar{b}\in M^b$ s.t. 
   $X=\{\bar{a}\in M^n:\calm\models\phi(\bar{a},\bar{b})\}$. We say that
   $\phi(\bar{v},\bar{b})$ *defines* $X$. We say that $X$ is
   *\(A\)-definable* or *definable over*  $A$ if there is a formula 
   $\psi(\bar{v},w_1,\dots,w_l)$ and $\bar{b}\in A^l$ s.t.
   $\psi(\bar{v},\bar{b})$ defines $X$
   #+END_definition

   A number of examples using $\call_r$, the language of rings
   * Let $\calm=(R,+,-,\cdot,0,1)$ be a ring. Let $p(X)\in R[X]$. Then 
     $Y=\{x\in R:p(x)=0\}$ is definable. Suppose that
     $p(X)=\displaystyle\sum_{i=0}^ma_iX^i$. Let $\phi(v,w_0,\dots,w_n)$ be the
     formula
     \begin{equation*}
     w_n\cdot\underbrace{v\cdots v}_{n\text{-times}}+\dots+w_1\cdot v+w_0=0
     \end{equation*}
     Then $\phi(v,a_0,\dots,a_n)$ defines $Y$. Indeed, $Y$ is \(A\)-definable
     for any $A\supseteq\{a_0,\dots,a_n\}$
   * Let $\calm=(\R,+,-,\cdot,0,1)$ be the field of real numbers. Let
     $\phi(x,y)$ be the formula 
     \begin{equation*}
     \exists z(z\neq 0\wedge y=x+z^2)
     \end{equation*}
     Because $a<b$ if and only if $\calm\models\phi(a,b)$, the ordering is
     \(\emptyset\)-definable 
   * Consider the natural numbers $\N$ as an $\call=\{+,\cdot,0,1\}$ structure.
     There is an \(\call\)-formula $T(e,x,s)$ s.t. $\N\models T(e,x,s)$ if and
     only if the Turing machine with program coded by $e$ halts on input $x$ in
     at most $s$ steops. Thus the Turing machine with program $e$ halts on input
     $x$ if and only if

 $\N\models\exists s\;T(e,x,s)$. So the halting
     computations is definable

     
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. Suppose that $D_n$ is a collection of
   subsets of $M^n$ for all $n\ge 1$ and $\cald=(D_n:n\ge 1)$ is the smallest
   collection s.t. 
   1. $M^n\in D_n$
   2. for all \(n\)-ary function symbols $f$ of $\call$, the graph of $f^\calm$
      is in $D_{n+1}$
   3. for all \(n\)-ary relation symbols $R$ of $\call$, $R^\calm\in D_n$
   4. for all $i,j\le n$, $\{(x_1,\dots,x_n)\in M^n:x_i=x_j\}\in D_n$
   5. if $X\in D_n$, then $M\times X\in D_{n+1}$
   6. each $D_n$ is cloed under complement, union and intersection
   7. if $X\in D_{n+1}$ and $\pi:M^{n+1}\to M^n$ is the projection 
      $(x_1,\dots,x_{n+1})\mapsto(x_1,\dots,x_n)$, then $\pi(X)\in D_n$
   8. if $X\in D_{n+m}$ and $b\in M^m$, then $\{a\in M^n:(a,b)\in X\}\in D_n$
      

   Thus $X\subseteq M^n$ is definable if and only if $X\in D_n$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. If $X\subset M^n$ is \(A\)-definable,
   then every \(\call\)-automorphism of $\calm$ that fixes $A$ pointwise fixes
   $X$ setwise(that is, if \sigma is an automorphism of $M$ and $\sigma(a)=a$
   for all $a\in A$, then $\sigma(X)=X$)
   #+END_proposition

   #+BEGIN_proof
   \begin{equation*}
   \calm\models\psi(\bar{v},\bar{a})\leftrightarrow
   \calm\models\psi(\sigma(\bar{v}),\sigma(\bar{a}))\leftrightarrow
   \calm\models\psi(\sigma(\bar{v}),\bar{a})
   \end{equation*}
   In other words, $\bar{b}\in X$ if and only if $\sigma(\bar{b})\in X$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
    A subset $S$ of a field $L$ is *algebraically independent* over a
    subfield $K$ if the elements of 
    $S$ do not satisfy any non-trivial polynomial equation with
    coefficients in $K$ 
   #+END_definition

   
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
    The set of real numbers is not definable in the field of complex numbers
   #+END_corollary

   #+BEGIN_proof
   If $\R$ where definable, then it would be definable over a finite
   $A\subset\C$. Let $r,s\in\C$ be algebraically independent over $A$ with
   $r\in\R$ and $s\not\in\R$. There is an automorphism \sigma of $\C$ s.t.
   $\sigma|A$ is the identity and $\sigma(r)=s$. Thus $\sigma(\R)\neq\R$ and
   $\R$ is not definable over $A$
   #+END_proof
   
   We say that an \(\call_0\)-structure $\caln$ is *definably interpreted* in
   an \(\call\)-structure $\calm$ if and only if we can find a definable
   $X\subseteq M^n$ for some $n$ and we can interpret the symbols of $\call_0$
   as definable subsets and functions on $X$ so that the resulting
   \(\call_0\)-structure is isomorphic to $\calm$


   For example, let $K$ be a field and $G$ be $\GL_2(K)$, the group of
   invertible $2\times 2$ matrices over $K$. Let $X=\{(a,b,c,d)\in K^4:ad-bc\neq
   0\}$. Let $f:X^2\to X$ by
   \begin{align*}
   f((a_1,b_1,&c_1,d_1),(a_2,b_2,c_2,d_2))=\\
   &(a_1a_2+b_1c_2,a_1b_2+b_1d_2,c_1a_2+d_1c_2,c_1b_2+d_1d_2)
   \end{align*}
   $X$ and $f$ are definable in $(K,+,\cdot)$, and the set $X$ with operation
   $f$ is isomorphic to $\GL_2(K)$, where the identity element of $X$ is
   $(1,0,0,1)$ 

   Clearly, $(\GL_n(K),\cdot,e)$ is definably interpreted in $(K,+,\cdot,0,1)$.
   A *linear algebraic group* over $K$ is a subgroup of $\GL_n(K)$ defined by
   polynomial equations over $K$. Any linear algebraic group over $K$ is
   definably interpreted in $K$

   Let $F$ be an infinite field and let $G$ be the group of matrices of the form 
   #+ATTR_LATEX: :mode math :environment pmatrix
   | a | b |
   | 0 | 1 |

   where $a,b\in F, a\neq 0$. This group is isomorphic to the group of affine
   transformations $x\mapsto ax+b$, where $a,b\in F$ and $a\neq 0$

   We will show that $F$ is definably interpreted in the group $G$. Let
   \begin{equation*}
    \alpha=\begin{pmatrix}
           1&1\\
           0&1\\
           \end{pmatrix}\text{ and }
   \beta=\begin{pmatrix}
   \tau&0\\
   0&1\\
         \end{pmatrix}
   \end{equation*}
   where $\tau\neq 0$. Let
   \begin{gather*}
   A=\{g\in G:g\alpha=\alpha g\}=\{\begin{pmatrix}
   1&x\\
   0&1\\
                                   \end{pmatrix}:x\in F\}\\
   B=\{g\in G:g\beta=\beta g\}=\{\begin{pmatrix}
   x&0\\
   0&1\\
                                   \end{pmatrix}:x\neq 0\}
   \end{gather*}
   Clearly $A,B$ are definable using parameters \alpha and \beta

   $B$ acts on $A$ by conjugation
   \begin{equation*}
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}^{-1}
   \begin{pmatrix}
   1&y\\
   0&1\\
   \end{pmatrix}
   \begin{pmatrix}
   x&0\\
   0&1\\
   \end{pmatrix}=
   \begin{pmatrix}
   1&\frac{y}{x}\\
   0&1
   \end{pmatrix}
   \end{equation*}
   We can define the map $i:A\backslash\{1\}\to B$ by $i(a)=b$ if and only if
   $b^{-1}ab=\alpha$, that is
   \begin{equation*}
   i \begin{pmatrix}
   1&x\\
   0&1
     \end{pmatrix}=
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}
   \end{equation*}
   Define an operation $*$ on $A$ by
   \begin{equation*}
   a*b=
   \begin{cases}
   i(b)a(i(b))^{-1}&\text{if } b\neq I\\
   1&\text{if } b=I
   \end{cases}
   \end{equation*}
   where $I$ is the identity matrix. Now $(F,+,\cdot,0,1)\cong (A,\cdot,*,1,\alpha)$


   Very complicated structures can often be interpreted in seemingly simpler
   ones. For example, any structure in a countable language can be interpreted
   in a graph. Let $(A,<)$ be a linear order. For each $a\in A$, $G_A$ will have
   vertices $a,x_1^a,x_2^a,x_3^a$ and contain the subgraph

   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \node[vertex,label=left:$x_2^a$] (2) at (0,0) {};
   \node[vertex,label=right:$x^a_3$] (3) at (2,0) {};
   \node[vertex,label=right:$x^a_1$] (1) at (1,-1) {};
   \node[vertex,label=right:$a$] (a) at (1,-2) {};
   \draw (2) -- (3) -- (1) -- (2);
   \draw (a) -- (1);
   \end{tikzpicture}
   \end{center}

   If $a<b$, then $G_A$ will have vertices $y_1^{a,b},y_2^{a,b},y_3^{a,b}$ and
   contain the subgraph
   
   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$y_2^{a,b}$] (2) at (2,2) {};
   \node[label=left:$y_1^{a,b}$,inner sep=0] (1) at (1,1) {};
   \node[vertex,label=right:$y_3^{a,b}$] (3) at (2,1) {};
   \node[vertex,label=left:$a$] (a) at (0,0) {};
   \node[vertex,label=right:$b$] (b) at (4,0) {};
   \draw (a) -- (2);
   \draw (1) -- (3);
   \draw (2) -- (b);
   \end{tikzpicture}
   \end{center}


   Let $V_A=A\cup\{x_1^a,x_2^a,x_3^a:a\in
   A\}\cup\{y_1^{a,b},y_2^{a,b},y_3^{a,b}:a,b\in A\text{ and }a<b\}$, and let
   $R_A$ be the smallest symmetric relation containing all edges drawn above.

   For example, if $A$ is the three-element linear order $a<b<c$, then $G_A$ is
   the graph

   \begin{center}
   \begin{tikzpicture}[scale=0.8,transform shape]
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$x_2^a$] (a2) at (0,0) {};
   \node[vertex,label=left:$x_2^b$] (b2) at (4,0) {};
   \node[vertex,label=left:$x_2^c$] (c2) at (8,0) {};
   \node[vertex,label=right:$x_1^c$] (c1) at (9,1) {};
   \node[vertex,label=right:$x_1^b$] (b1) at (5,1) {};
   \node[vertex,label=right:$x_1^a$] (a1) at (1,1) {};
   \node[vertex,label=right:$x_3^a$] (a3) at (2,0) {};
   \node[vertex,label=right:$x_3^b$] (b3) at (6,0) {};
   \node[vertex,label=right:$x_3^c$] (c3) at (10,0) {};
   \node[vertex,label=left:$a$] (a) at (1,2) {};
   \node[vertex,label=above:$b$] (b) at (5,2) {};
   \node[vertex,label=right:$c$] (c) at (9,2) {};
   \node[vertex,label=below:$y_1^{a,b}$] (ab1) at (2,2.5) {};
   \node[vertex,label=below:$y_1^{b,c}$] (bc1) at (6,2.5) {};
   \node[vertex,label=below:$y_3^{a,b}$] (ab3) at (3,2.5) {};
   \node[vertex,label=right:$y_2^{a,b}$] (ab2) at (3,3) {};
   \node[vertex,label=below:$y_3^{b,c}$] (bc3) at (7,2.5) {};
   \node[vertex,label=right:$y_2^{b,c}$] (bc2) at (7,3) {};
   \node[vertex,label=below:$y_3^{a,c}$] (ac3) at (5,4) {};
   \node[vertex,label=below:$y_2^{a,c}$] (ac2) at (5,6) {};
   \node[vertex,label=below:$y_1^{a,c}$] (ac1) at (3,4) {};
   \draw (a2) -- (a1) -- (a3) -- (a2);
   \draw (a1) -- (a);
   \draw (b2) -- (b1) -- (b3) -- (b2);
   \draw (b1) -- (b);
   \draw (c2) -- (c1) -- (c3) -- (c2);
   \draw (c1) -- (c);
   \draw (a) -- (ac2);
   \draw (ac2) -- (c);
   \draw (a) -- (ab2);
   \draw (ab1) -- (ab3);
   \draw (ac1) -- (ac3);
   \draw (bc1) -- (bc3);
   \draw (b) -- (bc2);
   \draw (b) -- (ab2);
   \draw (c) -- (bc2);
   \end{tikzpicture}
   \end{center}

   Let $\call=\{R\}$ where $R$ is a binary relation. Let $\phi(x,u,v,w)$ be the
   formula asserting that $x,u,v,w$ are distinct, there are edges
   $(x,u),(u,v),(v,w),(u,w)$ and these are the only edges involving $u,v,w$.
   $G_A\models\phi(a,x_1^a,x_2^a,x_3^a)$ for all $a\in A$.

   $\psi(x,y,u,v,w)$ asserts that $x,y,u,v,w$ are distinct. $(x,u),(u,v),(u,w),(v,y)$

   Define $\theta_i(z)$ as follows:
   \begin{align*}
   &\theta_0(z):=\exists u\exists v\exists w\;\phi(z,u,v,w)\\
   &\theta_1(z):=\exists x\exists v\exists w\;\phi(x,z,v,w)\\
   &\theta_2(z):=\exists u\exists u\exists w\;\phi(x,u,z,w)\\
   &\theta_3(z):=\exists x\exists y\exists v\exists w\;\psi(x,y,z,v,w)\\
   &\theta_4(z):=\exists x\exists y\exists u\exists w\;\psi(x,y,u,z,w)\\
   &\theta_5(z):=\exists x\exists y\exists u\exists v\;\psi(x,y,u,v,z)\\
   \end{align*}
   If $a,b\in A$ and $a<b$, then
   \begin{equation*}
   G_A\models\theta_0(a)\wedge\theta_1(x^a_1)\wedge\theta_2(x^a_2)\wedge
   \theta_2(x^a_3)
   \end{equation*}
   and 
   \begin{equation*}
   G_A\models\theta_3(y_1^{a,b})\wedge\theta_4(y_2^{a,b})\wedge\theta_5(
   y_3^{a,b})
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then for all vertices $x$ in $G$, there is a
   unique $i\le 5$ s.t. $G_A\models\theta_i(x)$
   #+END_lemma

   Let $T$ be the \(\call\)-theory with the following axioms
   1. $R$ is symmetric and irreflexive
   2. for all $x$, exactly one $\theta_i$ holds
   3. if $\theta_0(x)$ and $\theta_0(y)$ then $\neg R(x,y)$
   4. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)\\$ then
      $\forall u_1\forall v_1\forall w_1\neg\psi(y,x,u_1,v_1,w_1)$
   5. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ and 
      $\exists u\exists v\exists w\;\psi(y,z,u,v,w)$ then\par
      $\exists u\exists v\exists w\;\psi(x,z,u,v,w)$
   6. if $\theta_0(x)$ and $\theta_0(y)$, then either $x=y$ or 
      $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ or
      $\exists u\exists v\exists w\;\psi(y,x,u,v,w)$
   7. if $\phi(x,u,v,w)\wedge\phi(x,u',v',w')$, then
      $u=u',v=v',w=w'$
   8. if $\psi(x,y,u,v,w)\wedge\psi(x,y,u',v',w')$, then
      $u'=u,v=v',w=w'$


   If $(A,<)$ is a linear order, then $G_A\models T$

   Suppose $G\models T$. Let $X_G=\{x\in G:G\models\theta_0(x)\}$

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then $(X_{G_A},<_{G_A})\cong(A,<)$. Moreover,
   $G_{X_G}\cong G$ for all $G\models T$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call_0\)-structure $\caln$ is *interpretable* in an
   \(\call\)-structure $M$ if there is a definable $X\subseteq M^n$, a definable
   equivalence relation $E$ on $X$, and for each symbol of $\call_0$ we can find
   definable \(E\)-invariant sets on X s.t. $X/E$ with the induced structure is
   isomorphic to $\caln$
   #+END_definition
** Answers to Exercises
   #+BEGIN_exercise
   1. transform $\psi$ to CNF
   2. prenex normal form
   #+END_exercise
   #+BEGIN_exercise
   1. 
      \begin{tikzpicture}[scale=0.6]
      \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
      \node[vertex,label=above:$s$] (1) at (0,1) {};
      \node[vertex,label=above:$e$] (0) at (0,0) {};
      \node[vertex,label=above:$r$] (2) at (1,0) {};
      \node[vertex,label=above:$rs$] (3) at (1,1) {};
      \end{tikzpicture}
   2. enumerate $\calm$'s functions, relations and constants
   #+END_exercise
   #+BEGIN_exercise
   [fn:stack]
   Note that every \(\call\)-structure $\calm$ of size $\kappa$ is isomorphic to an
   \(\call\)-structure with domain $\kappa$. For each relation symbols, we have $2^\kappa$
   options. If the language has size $\lambda$, this is at most 
   $(2^\kappa)^\lambda=2^{\kappa\cdot\lambda}=2^{\max(\lambda,\kappa)}$
   #+END_exercise

   #+BEGIN_exercise
   \begin{align*}
   T\models\phi&\Leftrightarrow\forall \calm\;\calm\models T\to\calm\models\phi\\
   &\Leftrightarrow\forall \calm\;\calm\models T'\to\calm\models\phi\\
   &\Leftrightarrow T'\models\phi
   \end{align*}
   #+END_exercise
   #+BEGIN_exercise
   Follow the definition
   #+END_exercise

   #+BEGIN_exercise
   Since there is no model $\calm$ s.t. $\calm\models T$. It's true that 
   $T\models \phi$
   #+END_exercise

   #+BEGIN_exercise
   1. Suppose $\calm\models\phi$, then $E^\calm$ is an equivalent relation and
      each equivalence class's cardinality is 2
   2. follows from number theory
   3. cite:DBLP:journals/bsl/DurandJMM12
   #+END_exercise

   #+BEGIN_exercise
   TBD
   #+END_exercise

   #+BEGIN_exercise
   $G(f)=\{(\bar{x},\bar{y})\in M^{n+m}\mid\phi(\bar{x},\bar{y})\}$ and 
   $G(g)=\{(\bar{y},\bar{z})\in M^{m+l}\mid\psi(\bar{y},\bar{z})\}$. Hence
   $G(g\circ f)=\{(\bar{x},\bar{z})\in M^{n+l}\mid \phi(\bar{x},\bar{y})
   \wedge \psi(\bar{y},\bar{z})\}$
   #+END_exercise

   #+BEGIN_exercise
   $\phi(\bar{a},b)$ really defines a function and since 
   $\phi(\bar{a},y)\to y=b$
   #+END_exercise

* Basic Techniques
** The Compactness Theorem

   Some points of proofs
   * Proofs are finite
   * (Soundness) If \(T\vdash\phi\), then \(T\models\phi\)
   * If \(T\) is a finite set of sentences, then there is an algorithm that,
     when given a sequence of \(\call\)-formulas \sigma and an \(\call\)-sentence \phi,
     will decide whether \sigma is a proof of \phi from $T$

   [[index:recursive]]
   A language $\call$ is *recursive* if there is an algorithm that decides
   whether a sequence of symbols is an \(\call\)-formula. An \(\call\)-theory
   $T$ is *recursive* if there is an algorithm that when given an
   \(\call\)-sentence \phi as input, decides whether $\phi\in T$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.1.1
   If \(\call\) is a recursive language and $T$ is a recursive \(\call\)-theory,
   then $\{\phi:T\vdash\phi\}$ is recursively enumerable; that is, there is an
   algorithm that when given \phi as input will halt accepting if $T\vdash\phi$
   and not halt if $T\not\vdash\phi$
   #+END_proposition
   #+BEGIN_proof
   There is $\sigma_0,\sigma_1,\dots$ a computable listing of all finite
   sequence of \(\call\)-formulas. At stage $i$, we check to see whether
   $\sigma_i$ is a proof of \psi from $T$. If it is, then halt.
   #+END_proof

   #+ATTR_LATEX: :options [Gödel's Completeness Theorem]
   #+BEGIN_theorem
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence, then
   $T\models\phi$ if and only if $T\vdash \phi$
   #+END_theorem

   We say that an \(\call\)-theory $T$ is *inconsistent* if
   $T\vdash(\phi\wedge\neg\phi)$ for some sentence \phi.

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $T$ is consistent if and only if $T$ is satisfiable
   #+END_corollary

   #+BEGIN_proof
   Supose that $T$ is not satisfiable, then every model of $T$ is a model of
   $\phi\wedge\neg\phi$. Thus by the Completeness theorem
   $T\vdash(\phi\wedge\neg\phi)$ 
   #+END_proof


   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   $T$ is satisfiable if and only if every finite subset of $T$ is satisfiable
   #+END_theorem

   #+BEGIN_proof
   If $T$ is not satisfiable, then $T$ is inconsistent. Let \sigma be a proof of
   a contradiction from  $T$. Because \sigma is finite, only finitely many
   assumptions from $T$ are used in the proof. Thus there is a finite
   $T_0\subseteq T$ s.t. \sigma is a proof of a contradiction from $T_0$
   #+END_proof

*** Henkin Constructions
    [[index:finitely satisfiable]]
    A theory $T$ is *finitely satisfiable* if every finite subset of $T$ is
    satisfiable. We will show that every finitely satisfiable theory $T$ is
    satisfiable.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that an \(\call\)-theory $T$ has the *witness property* if whenever
    $\phi(v)$ is an \(\call\)-formula with one free variable $v$, then there is
    a constant symbol $c\in\call$ s.t. $T\vdash(\exists v\phi(v))\to\phi(c)\in T$

    An \(\call\)-theory $T$ is *maximal* if for all $\phi$ either $\phi\in T$ or
    $\neg\phi\in T$
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.6
    Suppose $T$ is a maximal and finitely satisfiable \(\call\)-theory. If
    $\Delta\subseteq T$ is finite and $\Delta\models\psi$, then $\psi\in T$
    #+END_lemma

    #+BEGIN_proof
    If $\psi\not\in T$, then $\neg\psi\in T$ but $\Delta\cup\{\psi\}$ is
    unsatisfiable 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.7
    Suppose that $T$ is a maximal and finitely satisfiable \(\call\)-theory with
    the witness property. Then $T$ has a model. In fact, if \kappa is a cardinal
    and \(\call\) has at most \kappa constant symbols, then there is
    $\calm\models T$ with $\abs{\calm}\le\kappa$
    #+END_lemma
    
    #+BEGIN_proof
    Let $\calc$ be the set of constant symbols of \(\call\). For $c,d\in\calc$,
    we say $c\sim d$ if $c=d\in T$

    *Claim 1* $\sim$ is an equivalence relation. 

    The universe of our model will be $M=\calc/\sim$. Clearly
    $\abs{M}\le\kappa$. We let $c^*$ denote the equivalence class of $c$ and
    interprete $c$ as its equivalence class, that is, $c^\calm=c^*$

    Suppose that $R$ is an \(n\)-ary relation symbol of \(\call\)

    *Claim 2* Suppose that $c_1,\dots,c_n,d_1,\dots,d_n\in\calc$ and $c_i\sim d_i$
    for $i=1,\dots,n$, then $R(\bar{c})$ if and only if $R(\bar{d})$

    By Lemma ref:lemma2.1.6, if one of \(R(\bar{c})\) and \(R(\bar{d})\) is
    in $T$, then both are in $T$

    
    \begin{equation*}
    R^\calm=\{(c_1^*,\dots,c_n^*):R(c_1,\dots,c_n)\in T\}
    \end{equation*}
    Suppose that $f$ is an \(n\)-ary function symbol of \(\call\) and
    $c_1,\dots,c_n\in\calc$. Because  $\underline{\emptyset\models\exists
    vf(c_1,\dots,c_n)=v}$, and $T$ has the witness property, then there is
    $c_{n+1}\in\calc$ s.t. $f(c_1,\dots,c_n)=c_{n+1}\in T$. As above, if
    $d_i\sim c_i$ for $i=1,\dots,n+1$, then $f(d_1,\dots,d_n)=d_{n+1}\in T$.
    Thus we get a well-defined function $f^\calm:M^n\to M$ by
    \begin{equation*}
    f^\calm(c_1^*,\dots,c_n^*)=d^*\text{ if and only if }f(c_1,\dots,c_n)=d\in T
    \end{equation*}

    *Claim 3* Suppose that $t$ is a term using free variables from
    $v_1,\dots,v_n$. If $c_1,\dots,c_n,d\in\calc$, then $t(c_1,\dots,c_n)=d\in
    T$ if and only if $t^\calm(c_1^*,\dots,c_n^*)=d^*$

    (\(\Rightarrow\)) If \(t\) is a constant symbol, then \(c=d\in T\) and
    \(c^\calm=c^*=d^*\)

    If \(t\) is the variable \(v_i\), then \(c_i=d\in T\) and 
    \(t^\calm(c_1^*,\dots,c_n^*)=c_i^*=d^*\)

    Suppose that the claim is true for \(t_1,\dots,t_m\) and \(t\) is
    \(f(t_1,\dots,t_m)\). Using the witness property and Lemma ref:lemma2.1.6,
    we can find \(d,d_1,\dots,d_n\in\calc\) s.t. \(t_i(c_1,\dots,c_n)=d_i\in T\)
    for \(i\le m\) and \(f(d_1,\dots,d_m)=d\in T\). By our induction hypothesis, 
    \(t_i^\calm(c_1^*,\dots,c_n^*)=d_i^*\) and
    \(f^\calm(d_1^*,\dots,d_m^*)=d^*\). Thus \(t^\calm(c_1^*,\dots,c_n^*)=d^*\)

    ($\Leftarrow$) Suppose $t^\calm(c_1^*,\dots,c_n^*)=d^*$. By the witness
    property, there is a $e\in\calc$ s.t. $t(c_1,\dots,c_n)=e\in T$. Using the
    $(\Rightarrow)$ direction of the proof, $t^\calm(c_1^*,\dots,c_n^*)=e^*$.
    Thus $e^*=d^*$ and $e=d\in T$


    *Claim 4* For all \(\call\)-formulas $\phi(v_1,\dots,v_n)$ and
    $c_1,\dots,c_n\in\calc$, $\calm\models\phi(\bar{c}^*)$ if and only if
    $\phi(\bar{c})\in T$

    Suppose that \(\phi\) is \(t_1=t_2\). By Lemma ref:lemma2.1.6 and the
    witness property, we can find \(d_1\) and \(d_2\) s.t. 
    \(t_1(\bar{c})=d_1,t_2(\bar{c})=d_2\in T\). By Claim 3,
    \(t_i^\calm(\bar{c}^*)=d_i^*\). Then
    \begin{align*}
    \calm\models\phi(\bar{c}^*)&\Leftrightarrow d_1^*=d_2^*\\
    &\Leftrightarrow d_1=d_2\in T\\
    &\Leftrightarrow t_1(\bar{c})=t_2(\bar{c})\in T
    \end{align*}

    Suppose that \phi is \(R(t_1,\dots,t_m)\). There are \(d_1,\dots,d_m\in\calc\)
    s.t. \(t_i(\bar{c})=d_i\in T\). Thus
    \begin{align*}
    \calm\models\phi(\bar{c}^*)&\Leftrightarrow \bar{d}^*\in R^\calm\\
    &\Leftrightarrow R(\bar{d})\in T\\
    &\Leftrightarrow\phi(\bar{c})\in T
    \end{align*}
    
    Suppose that the claim is true for \phi. If
    \(\calm\models\neg\phi(\bar{c}^*)\), then
    \(\calm\not\models\phi(\bar{c}^*)\). By the inductive hypothesis,
    \(\phi(\bar{c})\not\in T\). Thus by maximality, \(\neg\phi(\bar{c})\in T\). On
    the other hand, if \(\neg\phi(\bar{c})\in T\), then because $T$ is finitely
    satisfiable, \(\phi(\bar{c})\not\in T\). Thus, by induction,
    \(\calm\not\models\phi(\bar{c}^*)\).

    
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.8
    Let $T$ be a finitely satisfiable \(\call\)-theory. There is a language
    $\call^*\supseteq\call$ and $T^*\supseteq T$ a finitely satisfiable
    \(\call^*\)-theory s.t. any \(\call^*\)-theory extending $T^*$ has the
    witness property. We can choose $\call^*$ s.t.
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_lemma

    #+BEGIN_proof
    We first show that there is a language $\call_1\supseteq\call$ and a
    finitely satisfiable \(\call_1\)-theory $\call_1\supseteq T$ s.t. for any
    \(\call\)-formula $\phi(v)$ there is an \(\call_1\)-constant symbol $c$ s.t.
    $T_1\models(\exists v\phi(v))\to\phi(c)$. For each \(\call\)-formula
    $\phi(v)$, let $c_\phi$ be a new constant symbol and let
    $\call_1=\call\cup\{c_\phi:\phi(v)\text{ an }\call\text{-formula}\}$. For
    each \(\call\)-formula $\phi(v)$, let $\Theta_\phi$ be the
    \(\call_1\)-sentence
    $(\exists v\phi(v))\to\phi(c_\phi)$. Let
    $T_1=T\cup\{\Theta_\phi:\phi(v)\text{ an }\call\text{-formula}\}$

    *Claim* $T_1$ is finitely satisfiable

    Suppose that $\Delta$ is a finite subset of $T_1$. Then
    $\Delta=\Delta_0\cup\{\Theta_{\phi_1},\dots, \Theta_{\phi_n}\}$ where
    $\Delta_0$ is a finite subset of $T$ and there is $\calm\models\Delta_0$. We
    will make $\calm$ into an
    \(\call\cup\{c_{\phi_1},\dots,c_{\phi_n}\}\)-structure $\calm'$. If
    $\calm\models\exists v\phi(v)$, choose $a_i$ some element of $M$ s.t.
    $\calm\models\phi(a_i)$ and let $c_{\phi_i}^{\calm'}=a_i$. Otherwise, let
    $c_{\phi_i}^{\calm'}$ be any element of $\calm$. Clearly
    $\calm'\models\Theta_{\phi_i}$ for $i\le n$. Thus $T_1$ is finitely
    satisfiable.

    We now iterate the construction above to build a sequence of languages
    $\call\subseteq\call_1\subseteq\call_2\subseteq\dots$ and a sequence of
    finitely satisfiable \(\call_i\)-theories $T\subseteq T_1\subseteq
    T_2\subseteq\dots$ s.t. if $\phi(v)$ is an \(\call_i\)-formula then there is
    a constant symbol $c\in\call_{i+1}$ s.t. $T_{i+1}\models(\exists
    v\phi(v))\to\phi(c)$

    Let $\call^*=\bigcup\call_i$ and $T^*=\bigcup T_i$. 
    If \(\abs{\call_i}\) is the number of relation, function and constant
    symbols in \(\call_i\), then there are at most \(\abs{\call_i}+\aleph_0\)
    formulas in \(\call_i\).
    Thus by induction,
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:2.1.9
    Suppose that $T$ is a finitely satisfiable \(\call\)-theory and \phi is an
    \(\call\)-sentence, then either $T\cup\{\phi\}$ or $T\cup\{\neg\phi\}$ is
    finitely satisfiable
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor2.1.10
    If $T$ is a finitely satisfiable \(\call\)-theory, then there is a maximal
    finitely satisfiable \(\call\)-theory $T'\supseteq T$
    #+END_corollary
    #+BEGIN_proof
    Let $I$ be the set of all finitely satisfiable \(\call\)-theory containing
    $T$. We partially order $I$ by inclusion. If $C\subseteq I$ is a chain, let
    $T_C=\bigcup\{\Sigma:\Sigma\in C\}$. If $\Delta$ is a finite subset of
    $T_C$, then there is a $\Sigma\in C$ s.t. $\Delta\subseteq\Sigma$, so $T_C$
    is finitely satisfiable and $T_C\supseteq\Sigma$ for all $\Sigma\in C$. Thus
    every chain in $I$ has an upper bound, and we can apply Zorn's lemma to find
    a $T'\in I$ maximal w.r.t. the partial order.
    #+END_proof


    #+ATTR_LATEX: :options [strengthening of Compactness Theorem]
    #+BEGIN_theorem
    label:thm2.1.11
    If $T$ is a finitely satisfiable \(\call\)-theory and \kappa is an infinite
    cardinal with $\kappa\ge\abs{\call}$, then there is a model of $T$ of
    cardinality at most \kappa
    #+END_theorem

    #+BEGIN_proof
    By Lemma ref:lemma2.1.8, we can find \(\call^*\supseteq\call\) and 
    \(T^*\supseteq T\) a finitely satisfiable \(\call^*\)-theory s.t. any
    \(\call^*\)-theory extending \(T^*\) has the witness property and the
    cardinality of \(\call^*\) is at most \kappa. By Corollary ref:cor2.1.10, we can
    find a maximal finitely satisfiable \(\call^*\)-theory 
    \(T'\supseteq T^*\). Because \(T'\) has the witness property, Lemma
    ref:lemma2.1.7 ensures that there is \(\calm\models T\) with \(\abs{M}\le\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let $\call=\{\cdot,+,<,0,1\}$ and let $\Th(\N)$ be the full \(\call\)-theory
    of the natural numbers. There is $\calm\models\Th(\N)$ and $a\in M$ s.t. $a$
    is larger than every natural number
    #+END_proposition

    #+BEGIN_proof
    Let $\call^*=\call\cup\{c\}$ where $c$ is a new constant symbol and let
    \begin{equation*}
    T=\Th(\N)\cup\{\underbrace{1+1+\dots+1}_{n\text{-times}}<c:\text{for }n=1,2,\dots\} 
    \end{equation*}
    If $\Delta$ is a finite subset of $T$ we can make $\N$ a model of $\Delta$ by
    interpreting $c$ as a suitably large natural number. Thus $T$ is finitely
    satisfiable and there is $\calm\models T$.
    #+END_proof
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.14
    If $T\models\phi$, then $\Delta\models T$ for some finite $\Delta\subseteq T$
    #+END_lemma
    #+BEGIN_proof
    Suppose not. Let $\Delta\subseteq T$ be finite. Because
    $\Delta\not\models\phi$, $\Delta\cup\{\neg\phi\}$ is satisfiable. Thus
    $T\cup\{\neg\phi\}$ is finitely satisfiable and by the compactness theorem,
    $T\not\models\phi$ 
    #+END_proof


    
** Complete Theories
   [[index:complete]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-theory $T$ is called *complete* if for any \(\call\)-sentence \phi
   either $T\models\phi$ or $T\models\neg\phi$
   #+END_definition

   For $\calm$ an \(\call\)-structure, then the full theory
   \begin{equation*}
   \Th(\calm)=\{\phi:\phi\text{ is an }\call\text{-sentence and }
   \calm\models\phi\}
   \end{equation*}
   is a complete theory.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.2
   Let $T$ be an \(\call\)-theory with infinite models. If \kappa is an infinite
   cardinal and $\kappa\ge\abs{\call}$, then there is a model of $T$ of
   cardinality \kappa
   #+END_proposition

   #+BEGIN_proof
   Let $\call^*=\call\cup\{c_\alpha:\alpha<\kappa\}$, where each $c_\alpha$ is
   new constant symbol, and let $T^*$ be the \(\call^*\)-theory
   $T\cup\{c_\alpha\neq c_\beta:\alpha,\beta<\kappa,\alpha\neq\beta\}$. Clearly
   if $\calm\models T^*$, then $\calm$ is a model of $T$ of cardinality at least
   \kappa.
   Thus by Theorem ref:thm2.1.11, it suffices to show that $T^*$ is finitely
   satisfiable. But if $\Delta\subseteq T^*$ is finite, then $\Delta\subseteq
   T\cup\{c_\alpha\neq c_\beta:\alpha\neq\beta,\alpha,\beta\in I\}$, where $I$
   is a finite subset of \kappa. Let $\calm$ be an infinite model of $T$. We can
   interpret the symbols $\{c_\alpha:\alpha\in I\}$ as $\abs{I}$ distinct
   elements of $M$. Because $\calm\models\Delta$, $T^*$ is finitely satisfiable.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal and let $T$ be a theory with models of
   size \kappa. We say that $T$ is *\kappa-categorical* if any two models of
   $T$ of cardinality \kappa are isomorphic.
   #+END_definition

   Let $\call=\{+,0\}$ be the language of additive groups and let $T$ be the
   \(\call\)-theory of torsion-free divisible Abelian groups. The axioms of $T$
   are the axioms for Abelian groups together with the axioms
   \begin{gather*}
   \forall x(x\neq 0\to\underbrace{x+\dots+x}_{n\text{-times}}\neq 0)\\
   \forall y\exists x\underbrace{x+\dots+x}_{n\text{-times}}=y
   \end{gather*}
   for $n=1,2,\dots$

   
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The theory of torsion-free divisible Abelian groups is \kappa-categorical for
   all $\kappa>\aleph_0$
   #+END_proposition

   #+BEGIN_proof
   We first argue that models of $T$ are essentially vector spaces over the
   field of rational numbers $\Q$. If $V$ is any vector space over $\Q$, then
   the underlying additive group $V$ is a model of $T$. 
   Check [[https://math.stackexchange.com/questions/1550900/necessary-and-sufficient-conditions-for-an-abelian-group-to-be-a-vector-space-ov/1550954][StackExchange]].
   On the other hand, if
   \(G\models T\), \(g\in G\) and \(n\in\N\) with \(g>0\), we can find 
   \(h\in G\) s.t. \(nh=g\). If \(nk=g\), then \(n(h-k)=0\). Because $G$ is
   torsion-free there is a unique \(h\in G\) s.t. \(nh=g\). We call this element 
   \(g/n\). We can view $G$ as a \(\Q\)-vector space under the action
   \(\frac{m}{n}g=m(g/n)\)

   Two \(\Q\)-vector spaces are isomorphic if and only if they have the same
   dimension. Thus the model of $T$ are determined up to isomorphism by their
   dimension. If \(G\) has dimension \lambda, then \(\abs{G}=\lambda+\aleph_0\). If \kappa
   is uncountable and $G$ has cardinality \kappa, then $G$ has dimension \kappa. Thus for
   \(\kappa>\aleph_0\) any two models of $T$ of cardinality \kappa are isomorphic
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemmamy1
   Field of uncountable cardinality \kappa has transcendence degree \kappa
   [fn:proofkappa]
   #+END_lemma

   #+BEGIN_proof
   We prove the theorem for fields with characteristic \(p=0\). 

   Since each characteristic 0 field contains a copy of \(\Q\) as its prime
   field, we can view $F$ as a field extension over \(\Q\). We will show that
   $F$ has a subset of cardinality \kappa which is algebraically independent over
   \(\Q\).

   We build the claimed subset of $F$ by transfinite induction and implicit use
   of the axiom of choice.

   Let \(S_0=\emptyset\)

   Let \(S_1\) be a singleton containing some element of $F$ which is not
   algebraic over \(\Q\). This is possible since algebraic numbers are countable

   Define \(S_{\alpha+1}\) to be \(S_\alpha\) together with an element of $F$
   which is not a root of any non-trivial polynomial with coefficients in 
   \(\Q\cup S_\alpha\) since there are only 
   \(\abs{\Q\cup S_\alpha}=\aleph_0+\abs{\alpha}<\kappa\) polynomials

   Define \(S_\beta=\displaystyle\bigcup_{\alpha<\beta}S_\alpha\)
   
   Let \(P(x_1,\dots,x_n)\) be a non-trivial polynomial with coefficients in
   \(\Q\) and elements \(a_1,\dots,a_n\) in $F$. W.L.O.G., it is assumed that
   \(a_n\) was added at an ordinal \(\alpha+1\) later than the other elements.
   Then \(P(a_1,\dots,a_{n-1},x_n)\) is a polynomial with coefficients in 
   \(\Q\cup S_\alpha\). Hence \(P(a_1,\dots,a_n)\neq0\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.5
   \(\ACF_p\) is \kappa-categorical for all uncountable cardinals \kappa
   #+END_proposition

   #+BEGIN_proof
   Two algebraically closed fields are isomorphic if and only if they have the
   same characteristic and transcendence degree. See
   [[file:AdvancedModernAlgebra.org::Application of Zorn's Lemma]]. By Lemma
   ref:lemmamy1, an algebraically closed field of transcendence degree \lambda has
   cardinality \(\lambda+\aleph_0\).
   #+END_proof

   #+ATTR_LATEX: :options [Vaught's Test]
   #+BEGIN_theorem
   label:thm2.2.6
   Let $T$ be a satisfiable theory with no finite models that is
   \kappa-categorical for some infinite cardinal \(\kappa\ge\abs{\call}\). Then
   $T$ is complete
   #+END_theorem

   #+BEGIN_proof
   Suppose $T$ is not complete. Then there is a sentence \phi s.t. 
   \(T\not\models\phi\) and \(T\not\models\neg\phi\). Because
   \(T\not\models\psi\) if and only if \(T\cup\{\neg\psi\}\) is satisfiable, the
   theories \(T_0=T\cup\{\phi\}\) and \(T_1=T\cup\{\neg\phi\}\) are satisfiable.
   Because $T$ has no finite models, both \(T_0\) and \(T_1\) have infinite
   models. By Proposition ref:prop2.2.2 we can find \(\calm_0\) and
   \(\calm_1\) of cardinality \kappa with \(\calm_i\models T_i\). Because \(\calm_0\)
   and \(\calm_1\) disagree about \phi, they are not elementarily equivalent, and
   hence by Theorem ref:thm1.1.10, nonisomorphic. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that an \(\call\)-theory $T$ is *decidable* if there is an algorithm
   that when given an \(\call\)-sentence \phi as input decides whether \(T\models\phi\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $T$ be a recursive complete satisfiable theory in a recursive language
   \(\call\). Then $T$ is decidable
   #+END_lemma

   #+BEGIN_proof
   Because $T$ is satisfiable \(A=\{\phi:T\models\phi\}\) and
   \(B=\{\phi:T\models\neg\phi\}\) are disjoint. Because $T$ is consistent 
   \(A\cup B\) is the set of all \(\call\)-sentences. By the Completeness
   Theorem, \(A=\{\phi:T\vdash\phi\}\) and \(B=\{\phi:T\vdash\neg\phi\}\). By
   Proposition ref:prop2.1.1 $A$ and $B$ are recursively enumerable. But any
   recursively enumerable set with a recursively enumerable complement is
   recursive. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   For $p=0$ or $p$ prime, \(ACF_p\) is decidable. In particular, \(\Th(\C)\),
   the first-order theory  of the field of complex numbers, is decidable
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \phi be a sentence in the language of rings. The following are equivalent
   1. \phi is true in the complex number
   2. \phi is true in every algebraically closed field of characteristic zero
   3. \phi is true in some algebraically closed field of characteristic zero
   4. There are arbitrarily large primes $p$ s.t. \phi is true in some
      algebraically closed field of characteristic $p$
   5. There is an $m$ s.t. for all \(p>m\), \phi is true in all algebraically
      closed fields of characteristic $p$
   #+END_corollary

   #+BEGIN_proof
   By Proposition ref:prop2.2.5 and Vaught's Test, \(\ACF_p\) is complete.

   \((2)\to(5)\). Suppose that \(\ACF_0\models\phi\). By Lemma ref:lemma2.1.14,
   there is a finite \(\Delta\subseteq\ACF_0\) s.t. \(\Delta\models\phi\). Thus
   if we choose \(p\) large enough, then \(\ACF_p\models\Delta\).

   \((4)\to(2)\). Suppose \(\ACF_0\not\models\phi\). Because \(\ACF_0\) is
   complete, \(\ACF_0\models\neg\phi\).
   #+END_proof
   
** Up and Down

   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \(\calm\) and \(\caln\) are \(\call\)-structures, then an
   \(\call\)-embedding \(j:\calm\to\caln\) is called an *elementary embedding* if
   \begin{equation*}
   \calm\models\phi(a_1,\dots,a_n)\leftrightarrow\caln\models\phi(j(a_1),\dots,j(a_n))
   \end{equation*}
   for all \(\call\)-formulas \(\phi(v_1,\dots,v_n)\) and all \(a_1,\dots,a_n\in
   M\)

   If \(\calm\) is a substructure of \(\caln\), we say that it is an *elementary
   substructure* and write \(\calm\prec\caln\) if the inclusion map is elementary.
   \(\caln\) is an *elementary extension* of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \(\calm\) is an \(\call\)-structure. Let \(\call_M\) be the language where we
   add to \(\call\) constant symbols \(m\) for each element of $M$. The *atomic
   diagram* of \(\calm\) is \(\{\phi(m_1,\dots,m_n):\phi\text{ is either an atomic
   }\call\text{-formula or the negation of an atomic }\call\text{-formula and
   }\calm\models\phi(m_1,\dots.m_n)\}\).
   The *elementary diagram* of $\calm$ is 
   \begin{equation*}
   \{\phi(m_1,\dots,m_n):\calm\models\phi(m_1,\dots,m_n),\phi\text{ an 
   \(\call\)-formula}\}
   \end{equation*}

   We let \(\Diag(\calm)\) and \(\Diag_{\el}(\calm)\) denote the atomic and
   elementary diagrams of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.3.3
   1. Suppose that \(\caln\) is an \(\call_M\)-structure and
      \(\caln\models\Diag(\calm)\), then viewing \(\caln\) as an
      \(\call\)-structure, there is an \(\call\)-embedding of \(\calm\) into \(\caln\)
   2. If \(\caln\models\Diag_{\el}(\calm)\), then there is an elementary
      embedding of \(\calm\) into \(\caln\)
   #+END_lemma

   #+BEGIN_proof
   1. Let \(j:M\to N\) by \(j(m)=m^\caln\). If \(m_1\neq m_2\in\Diag(\calm)\);
      thus \(j(m_1)\neq j(m_2)\) so $j$ is an embedding. If \(f\) is a function
      symbols of \(\call\) and \(f^\calm(m_1,\dots,m_n)=m_{n+1}\), then
      \(f(m_1,\dots,m_n)=m_{n+1}\) is a formula in \(\Diag(\calm)\) and 
      \(f^\caln(j(m_1),\dots,j(m_n))=j(m_{n+1})\). If \(R\) is a relation symbol
      and \(\bar{m}\in R^\calm\), then \(R(m_1,\dots,m_n)\in\Diag(\calm)\) and 
      \((j(m_1),\dots,j(m_{n}))\in R^\caln\). Hence \(j\) is an
      \(\call\)-embedding
   2. $j$ is elementary.

   #+END_proof

   #+ATTR_LATEX: :options [Upward Löwenheim–Skolem Theorem]
   #+BEGIN_theorem
   Let \(\calm\) be an infinite \(\call\)-structure and \kappa be an infinite
   cardinal \(\kappa\ge\abs{\calm}+\abs{\call}\). Then, there is \(\caln\) an
   \(\call\)-structure of cardinality \kappa and \(j:\calm\to\caln\) is elementary
   #+END_theorem

   #+BEGIN_proof
   Because \(\calm\models\Diag_{\el}(\calm)\), \(\Diag_{\el}(\calm)\) is
   satisfiable. By Theorem ref:thm2.1.11, there is
   \(\caln\models\Diag_{\el}(\calm)\) of cardinality \kappa. By Lemma ref:lemma2.3.3,
   there is an elementary \(j:\calm\to\caln\)
   #+END_proof

   #+ATTR_LATEX: :options [Tarski-Vaught Test]
   #+BEGIN_proposition
   label:prop2.3.5
   Suppose that \(\calm\) is a substructure of \(\caln\). Then \(\calm\) is an
   elementary substructure if and only if, for any formula \(\phi(v,\bar{w})\) and 
   \(\bar{a}\in M\), if there is \(b\in N\) s.t.
   \(\caln\models\phi(b,\bar{a})\), then there is \(c\in M\) s.t.
   \(\caln\models\phi(c,\bar{a})\) 
   #+END_proposition

   #+BEGIN_proof
   We need to show that for all \(\bar{a}\in M\) and all \(\call\)-formulas
   \(\psi(\bar{v})\)
   \begin{equation*}
   \calm\models\psi(\bar{a})\Leftrightarrow\caln\models\psi(\bar{a})
   \end{equation*}

   In Proposition ref:prop1.1.8, we showed that if \(\phi(\bar{v})\) is quantifier
   free then \(\calm\models\phi(\bar{a})\) if and only if \(\phi(\bar{a})\)
   #+END_proof

   We say that an \(\call\)-theory $T$ has *built-in Skolem functions* if for all
   \(\call\)-formulas \(\phi(v,w_1,\dots,w_n)\) there is a function symbol $f$ s.t.\\
   \(T\models\forall\bar{w}((\exists
   v\phi(v,\bar{w}))\to\phi(f(\bar{w}),\bar{w}))\). In other words, there are
   enough function symbols in the language to witness all existential statements.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.3.6
   Let \(T\) be an \(\call\)-theory. There are \(\call^*\supseteq\call\) and 
   \(T^*\supseteq T\) an \(\call^*\)-theory s.t. \(T^*\) has built-in Skolem
   functions, and if \(\calm\models T\), then we can expand \(\calm\) to 
   \(\calm^*\models T^*\). We can choose \(\call^*\) s.t.
   \(\abs{\call^*}=\abs{\call}+\aleph_0\).

   We call \(T^*\) a *skolemization* of $T$
   #+END_lemma

   #+BEGIN_proof
   We build a sequence of languages
   \(\call=\call_0\subseteq\call_1\subseteq\dots\) and \(\call_i\)-theories
   \(T_i\) s.t. \(T=T_0\subseteq T_1\subseteq\dots\)

   Given \(\call_i\), let
   \(\call_{i+1}=\call\cup\{f_\phi:\phi(v,w_1,\dots,w_n)\text{ an
   }\call_i\text{-formula},n=1,2,\dots\}\), 
   where \(f_\phi\) is an \(n\)-ary function symbol. For \(\phi(v,\bar{w})\) an
   \(\call_i\)-formula, let \(\Psi_\phi\) be the sentence
   \begin{equation*}
   \forall\bar{w}((\exists v\phi(v,\bar{w}))\to\phi(f_\phi(\bar{w}),\bar{w}))
   \end{equation*}
   and let \(T_{i+1}=T_i\cup\{\Psi_\phi:\phi\text{ an
   }\call_i\text{-formula}\}\)

   *Claim* If \(\calm\models T_i\), then we can interpret the function symbols of
   \(\call_{i+1}\backslash\call_i\) so that \(\calm\models T_{i+1}\)

   Let \(c\) be some fixed element of $M$. If \(\phi(v,w_1,\dots,w_n)\) is an
   \(\call_i\)-formula, we find a function \(g:M^n\to M\) s.t. 
   \(\bar{a}\in M^n\) and \(X_{\bar{a}}=\{b\in M:\calm\models\phi(b,\bar{a})\}\)
   is nonempty, then \(g(\bar{a})\in X_{\bar{a}}\), and if
   \(X_{\bar{a}}=\emptyset\), then \(g(\bar{a})=c\). Thus if 
   \(\calm\models\exists v\phi(v,\bar{a})\), then
   \(\calm\models\phi(g(\bar{a}),\bar{a})\). If we interpret \(f_\phi\) as
   \(g\), then \(\calm\models\Psi_\phi\)

   Let \(\call^*=\bigcup\call_i\) and \(T^*=\bigcup T_i\). If \(\phi(v,\bar{w})\)
   is an \(\call^*\)-formula, then \(\phi\in\call_i\) for some $i$ and 
   \(\Psi_\phi\in T_{i+1}\subseteq T^*\), so \(T^*\) has built in Skolem
   functions. By iterating the claim, we see that for any \(\calm\models T\) we
   can interpret the symbols of \(\call^*\backslash\call\) to make
   \(\calm\models T^*\)

   \(\abs{\call_{i+1}}=\abs{\call_i}+\aleph_0\)

   #+END_proof

   #+ATTR_LATEX: :options [Löwenheim–Skolem Theorem]
   #+BEGIN_theorem
   Suppose that \(\calm\) is an \(\call\)-structure and \(X\subseteq M\), there
   is an elementary submodel \(\caln\) of \(\calm\) s.t. \(X\subseteq N\) and 
   \(\abs{\caln}\le\abs{X}+\abs{\call}+\aleph_0\)
   #+END_theorem

   #+BEGIN_proof
   By Lemma ref:lemma2.3.6, we may assume that \(\Th(\calm)\) has built in
   Skolem functions (otherwise we may extend \(\call\) to some \(\call^*\)). Let
   \(X_0=X\). Given \(X_i\), let \(X_{i+1}=X_i\cup\{f^\calm(\bar{a}):f\text{ an
   }n\text{-ary function symbol},\bar{a}\in X^n_i,n=1,2,\dots\}\). Let
   \(N=\bigcup X_i\), then \(\abs{N}\le\abs{X}+\abs{\call}+\aleph_0\)
   If \(f\) is an \(n\)-ary function symbol of \(\call\) and \(\bar{a}\in N^n\),
   then \(\bar{a}\in X^n_i\) for some $i$ and 
   \(f^\calm(\bar{a})\in X_{i+1}\subseteq N\). Thus \(f^\calm|N:N^n\to N\). Thus
   we can interpret \(f\) as \(f^\caln=f^\calm|N^n\). If $R$ is an \(n\)-ary
   relation symbol, let \(R^\caln=R^\calm\cap N^n\). If \(c\) is a constant
   symbol of \(\call\), there is a Skolem function \(f\in\call\) s.t. 
   \(f(x)=c^\calm\) for all \(x\in M\) (for example, \(f\) is the Skolem
   function for the formula \(v=c\)) . Thus \(c^\caln\in N\)

   If \(\phi(v,\bar{w})\) is any \(\call\)-formula, \(\bar{a},b\in M\) and
   \(\calm\models\phi(b,\bar{a})\), then
   \(\calm\models\phi(f(\bar{a}),\bar{a})\) for some function symbol \(f\) of
   \(\call\). By construction, \(f^\calm(\bar{a})\in N\). Thus by Proposition
   ref:prop2.3.5 \(\caln\prec\calm\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *universal sentence* is one of the form \(\forall\bar{v}\phi(\bar{v})\), where
   \phi is quantifier-free. We say that an \(\call\)-theory $T$ has a *universal
   axiomatization* if there is a set of universal \(\call\)-sentences \Gamma s.t. 
   \(\calm\models\Gamma\) if and only if \(\calm\models T\) for all
   \(\call\)-structures \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   An \(\call\)-theory $T$ has a universal axiomatization if and only if
   whenever \(\calm\models T\) and \(\caln\) is a substructure of \(\calm\),
   then \(\caln\models T\). In other words, a theory is preserved under
   substructure if and only if it has a universal axiomatization
   #+END_theorem

   #+BEGIN_proof
   Suppose that \(\caln\subseteq\calm\). By Proposition ref:prop1.1.8, if
   \(\phi(\bar{v})\) is a quantifier-free formula and \(\bar{a}\in N\), then
   \(\caln\models\phi(\bar{a})\) if and only if \(\phi(\bar{a})\). Thus if
   \(\calm\models\forall\bar{v}\phi(\bar{v})\), then so does \(\caln\)

   Suppose that \(T\) is preserved under substructures. Let
   \(\Gamma=\{\phi:\phi\text{ is universal and }T\models\phi\}\). Clearly, if
   \(\caln\models T\), then \(\caln\models\Gamma\). For the other direction,
   suppose that \(\caln\models\Gamma\). We claim that \(\caln\models T\)

   *Claim* \(T\cup\Diag(\caln)\) is satisfiable

   Suppose not. Then, by the Compactness Theorem, there is a finite
   \(\Delta\subseteq\Diag(\caln)\) s.t. \(T\cup\Delta\) is not satisfiable. Let
   \(\Delta=\{\psi_1,\dots,\psi_n\}\). Let \(\bar{c}\) be the new constant
   symbols from \(N\) used in \(\psi_1,\dots,\psi_n\) and say
   \(\psi_i=\phi_i(\bar{c})\), where \(\phi_i\) is a quantifier-free
   \(\call\)-formula. Because the constants in \(\bar{c}\) do not occur in $T$, if
   there is a model of \(T\cup\{\exists\bar{v}\bigwedge\phi_i(\bar{v})\}\), then
   by interpreting \(\bar{c}\) as witness to the existential formula,
   \(T\cup\Delta\) would be satisfiable. Thus
   \(T\models\forall\bar{v}\bigvee\neg\phi_i(\bar{v})\). As the latter formula
   is universal, \(\forall\bar{v}\bigvee\neg\phi_i(\bar{v})\in\Gamma\),
   contradicting \(\caln\models\Gamma.\)

   By Lemma ref:lemma2.3.3, there is \(\calm\models T\) with
   \(\calm\supseteq\caln\). Because $T$ is preserved under substructure,
   \(\caln\models T\) and \Gamma is a universal axiomatization
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose that \((I,<)\) is a linear order. Suppose that \(\calm_i\) is an
   \(\call\)-structure for \(i\in I\). We say that \((\calm_i:i\in I)\) is a
   chain of \(\call\)-strctures if \(\calm_i\subseteq\calm_j\) for \(i<j\). If
   \(\calm_i\prec\calm_j\) for \(i<j\), we call \((\calm_i:i\in I)\) an 
   *elementary chain*
   #+END_definition

   If \((\calm_i:i\in I)\) is a nonempty chain of structures, then we can define
   \(\calm=\bigcup_{i\in I}\calm_i\), the union of the chain, as follows. 
   \(M=\bigcup_{i\in I}M_i\). if \(c\) is a constant in the language, then
   \(c^{\calm_i}=c^{\calm_j}\) for all \(i,j\in I\). Let
   \(c^\calm=c^{\calm_i}\).

   Suppose that \(\bar{a}\in M\). Because $I$ is linearly ordered, we can find
   \(i\in I\) s.t. \(\bar{a}\in M_i\). If \(f\) is a function symbol of
   \(\call\) and \(i<j\), then \(f^{\calm_i}(\bar{a})=f^{\calm_j}(\bar{a})\).
   Thus \(f^\calm=\bigcup_{i\in I}f^{\calm_i}\) is a well-defined function.
   Similarly, \(R^\calm=\bigcup_{i\in I}R^{\calm_i}\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Suppose that \((I,<)\) is a linear order and \((\calm_i:i\in I)\) is an
   elementary chain. Then \(\calm=\bigcup_{i\in I}\calm_i\) is an elementary
   extension of each \(\calm_i\)
   #+END_proposition

   #+BEGIN_proof
   We prove by induction on formulas that 
   \begin{equation*}
   \calm\models\phi(\bar{a})\Leftrightarrow\calm_i\models\phi(\bar{a})
   \end{equation*}
   for all \(i\in I\), all formulas \(\phi(\bar{v})\), and all \(\bar{a}\in M_i^n\) 

   Because \(\calm_i\) is a substructure of \(\calm\), by Proposition
   ref:prop1.1.8 this is true for all atomic \phi. \(\neg\phi\) and
   \(\phi\vee\psi\) is easy.

   Suppose that \(\phi\) is \(\exists v\psi(v,\bar{w})\) and the chain holds for
   \psi. If \(\calm_i\models\psi(b,\bar{a})\), then so does \(\calm\). Thus if
   \(\calm_i\models\phi(\bar{a})\), then so does \(\calm\). On the other hand,
   if \(\calm\models\psi(b,\bar{a})\), there is \(j\ge i\) s.t. \(b\in M_j\). By
   induction, \(\calm_j\models\psi(b,\bar{a})\), so
   \(\calm_j\models\phi(\bar{a})\). Because \(\calm_i\prec\calm_j\), \(\calm_i\models\phi(\bar{a})\)
   #+END_proof


** Back and Forth   

*** Dense Linear Orders
    Let \(\call=\{<\}\) and let DLO be the theory of dense linear orders without
    endpoints. DLO is axiomatized by the axioms for linear orders plus the
    axioms
    \begin{align*}
    &\forall x\forall y\;(x<y\to \exists z\;x<z<y)\\
    &\forall x\exists y\exists z\; y<x<z
    \end{align*}
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm2.4.1
    The theory DLO is \(\aleph_0\)-categorical and complete
    #+END_theorem

    #+BEGIN_proof
    Let \((A,<)\) and \((B,<)\) be two countable models of DLO. Let
    \(a_0,a_1,a_2,\dots\) and \(b_0,b_1,b_2,\dots\) be one-to-one enumerations
    of \(A\) and \(B\). We will build a sequence of partial bijections
    \(f_i:A_i\to B_i\) where \(A_i\subset A\) and \(B_i\subset B\) are finite
    s.t. \(f_0\subseteq f_1\subseteq\dots\) and if \(x,y\in A_i\) and \(x<y\),
    then \(f_i(x)<f_i(y)\). We call \(f_i\) a *partial embedding*. We will build
    these sequences s.t. \(A=\bigcup A_i\) and \(B=\bigcup B_i\). In this case,
    \(f=\bigcup f_i\) is the desired isomorphism from \((A,<)\) to \((B,<)\)

    At odd stages of the construction we will ensure that \(\bigcup A_i=A\), and
    at even stages we will ensure that \(\bigcup B_i=B\)

    _stage 0_: Let \(A_0=B_0=f_0=\emptyset\)

    _stage \(n+1=2m+1\)_: We will ensure that \(a_m\in A_{n+1}\).

    If \(a_m\in A_n\), then let \(A_{n+1}=A_n\), \(B_{n+1}=B_n\) and
    \(f_{n+1}=f_n\). Suppose that \(a_m\not\in A_n\). To add \(a_m\) to the
    domain of our partial embedding, we must find \(b\in B\backslash B_n\) s.t.
    \begin{equation*}
    \alpha<a_m\Leftrightarrow f_n(\alpha)<b
    \end{equation*}
    for all \(\alpha\in A_n\). In other words, we must find \(b\in B\), which is
    the image under \(f_n\) of the cut of \(a_m\) in \(A_n\). Exactly one of the
    following holds:
    1. \(a_m\) is greater than every element of \(A_n\), or
    2. \(a_m\) is than than every element of \(A_n\), or
    3. there are \alpha and \(\beta\in A_n\) s.t. \(\alpha<\beta\),\(\gamma\le\alpha\) or
       \(\gamma\ge\beta\) for all \(\gamma\in A_n\) and \(\alpha<a_m<\beta\)


    In case 1 because \(B_n\) is finite and \(B\models\DLO\),we can find 
    \(b\in B\) greater than every element of \(B_n\). Similar for case 2. In
    case 3, because \(f_n\) is a partial embedding, \(f_n(\alpha)<f_n(\beta)\) and we can
    choose \(b\in B_n\) s.t. \(f_n(\alpha)<b<f_n(\beta)\). Note that 
    \begin{equation*}
    \alpha<a_m\Leftrightarrow f_n(\alpha)<b
    \end{equation*}
    for all \(\alpha\in A_n\)

    _stage \(n+1=2m+2\)_: We will ensure \(b_m\in B_{n+1}\)

    Again, if \(b_m\) is already in \(B_n\), then we make no changes. Otherwise,
    we must find \(a\in A\) s.t. the image of the cut of \(a\) in \(A_n\) is the
    cut of \(b_m\) in \(B_n\). This is done in odd case.

    Clearly, at odd stages we have ensured that \(\bigcup A_n=A\) and at even
    stages we have ensured that \(\bigcup B_n=B\). Because each \(f_n\) is a
    partial embedding, \(f=\bigcup f_n\) is an isomorphism from \(A\) onto \(B\)

    But there are no finite dense linear orders, Vaught's test implies that DLO
    is complete
    #+END_proof

*** The Random Graph
    Let \(\call=\{R\}\), where $R$ is a binary relation symbol. We will consider
    an \(\call\)-theory containing the graph axioms \(\forall x\;\neg R(x,x)\) and 
    \(\forall x\forall y\; R(x,y)\to R(y,x)\). Let \(\psi_n\) be the "extension
    axiom"
    \begin{equation*}
    \forall x_1\dots\forall x_n\forall y_1\dots\forall y_n\;
    \left(\displaystyle\bigwedge_{i=1}^n\bigwedge_{j=1}^nx_1\neq y_j\to
    \exists z\;\bigwedge_{i=1}^n(R(x_i,z)\wedge\neg R(y_i,z))
    \right)
    \end{equation*}
    We let $T$ be the theory of graphs where we add 
    \(\{\exists x\exists y\; x\neq y\}\cup\{\psi_n:n=1,2,\dots\}\) to the graph
    axioms. A model of $T$ is a graph where for any finite disjoint sets \(X\)
    and \(Y\) we can find a vertex with edges going to every vertex in $X$ and
    no vertex in \(Y\)
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    $T$ is satisfiable and \(\aleph_0\)-categorical. In particular, $T$ is
    complete and decidable
    #+END_theorem
    #+BEGIN_proof
    We first build a countable model of $T$. Let \(G_0\) be any countable graph

    *Claim* There is a graph \(G_1\supseteq G_0\) s.t. \(G_1\) is countable and if
    \(X\) and $Y$are disjoint finite subsets of \(G_0\) then there is 
    \(z\in G_1\) s.t. \(R(x,z)\) for \(x\in X\) and \(\neg R(y,z)\) for \(y\in
    Y\)

    Let the vertices of \(G_1\) be the vertices of \(G_0\) plus new vertices
    \(z_X\) for each \(X\subseteq G_0\). The edges of \(G_1\) are the edges of
    \(G\) together  with new edges between \(x\) and \(z_X\) whenever 
    \(X\subseteq G_0\) is finite and \(x\in X\).

    We iterate this construction to build a sequence of countable graphs 
    \(G_0\subset G_1\subset\dots\) s.t. if \(X\) and \(Y\) are disjoint finite
    subsets of \(G_i\), then there is \(z\in G_{i+1}\) s.t. \(R(x,z)\) for
    \(x\in X\) and \(\neg R(y,z)\) for \(y\in Y\). Thus \(G=\bigcup G_n\) is a
    countable model of \(T\)

    Next we show that \(T\) is \(\aleph_0\)-categorical. Let \(G_1\) and \(G_2\)
    be countable models of \(T\). Let \(a_0,a_1,\dots\) list \(G_1\), and let
    \(b_0,b_1,\dots\) list \(G_2\). We will build a sequence of finite partial
    one-to-one maps \(f_0\subseteq f_1\subseteq f_2\subseteq\dots\) s.t. for all
    \(x,y\) in the doamin of \(f_s\),
    \begin{equation*}
    G_1\models R(x,y)\Leftrightarrow G_2\models R(f_s(x),f_s(y))
    \end{equation*}
    Let \(f_0=\emptyset\)
    _stage \(s+1=2i+1\)_: We make sure that \(a_i\) is in the domain
    
    If \(a_i\) is in the domain of \(f_s\), let \(f_{s+1}=f_s\). If not, let
    \(\alpha_1,\dots,\alpha_m\) list the domain of \(f_s\) and let 
    \(X=\{j\le m:R(\alpha_j,a_i)\}\) and let \(Y=\{j\le m:\neg
    R(\alpha_j,a_i)\}\). Because 
    \(G_2\models T\), we can find \(b\in G_2\) s.t. \(G_2\models
    R(f_s(\alpha_j),b)\) for \(j\in X\) and 
    \(G_2\models\neg R(f_s(\alpha_j),b)\) for \(j\in Y\). Let
    \(f_{s+1}=f_s\cup\{(a_i,b)\}\). 
    
    _stage \(s+1=2i+2\)_: Similar
    #+END_proof

    Let \(\calg_N\) be the set of all graphs with vertices \(\{1,2,\dots,N\}\).
    We consider a probability measure on \(\calg_N\) where we make all graphs
    equally likely. This is the same as constructing a random graph where we
    independently decide whether there is an edge between \(i\) and \(j\) with
    probability \(\frac{1}{2}\). For any \(\call\)-sentence \phi,
    \begin{equation*}
    p_N(\phi)=\frac{\abs{\{G\in\calg_N:G\models\phi\}}}{\abs{\calg_N}}
    \end{equation*}
    is the probability that a random element of \(\calg_N\) satisfies \phi

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.4.3
    \(\lim_{N\to\infty}p_N(\psi_n)=1\)
    #+END_lemma

    #+BEGIN_proof
    Fix $n$. Let \(G\) be a random graph in \(\calg_N\) where \(N>2n\). Fix 
    \(x_1,\dots,x_n,y_1,\dots,y_n,z\in G\) distinct. Let \(q\) be the
    probability that 
    \begin{equation*}
    \neg\left(
    \displaystyle\bigwedge_{i=1}^n(R(x_i,z))\wedge\neg R(y_i,z)
    \right)
    \end{equation*}
    Then \(q=1-2^{-2n}\). Because these probabilities are independent, the
    probability that 
    \begin{equation*}
    G\models\neg\exists z\neg\left(
    \displaystyle\bigwedge_{i=1}^n(R(x_i,z))\wedge\neg R(y_i,z)
    \right)
    \end{equation*}
    is \(q^{N-2n}\). Let $M$ be the number of pairs of disjoint subsets of \(G\)
    of size $n$. Thus
    \begin{equation*}
    p_N(\neg\psi_n)\le Mq^{N-2n}<N^{2n}q^{N-2n}
    \end{equation*}
    Because \(q<1\)
    \begin{equation*}
    \lim_{N\to\infty}p_N(\neg\psi_n)=\lim_{N\to\infty}N^{2n}q^N=0
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options [Zero-One Law for Graphs]
    #+BEGIN_theorem
    label:thm2.4.4
    For any \(\call\)-sentence \phi either \(\lim_{N\to\infty}p_N(\phi)=0\) or 
    \(\lim_{N\to\infty}p_N(\phi)=1\). Moreover, \(T\) axiomatizes
    \(\{\phi:\lim_{N\to\infty}p_N(\phi)=1\}\), the *almost sure theory graphs*. The
    almost sure theory of graphs is decidable and complete
    #+END_theorem

    #+BEGIN_proof
    If \(T\models\phi\), then there is \(n\) s.t. if \(G\) is a graph and
    \(G\models\psi_n\), then \(G\models\phi\). Thus,
    \(p_N(\phi)\ge\phi_N(\psi_n)\) and by Lemma ref:lemma2.4.3, \(\lim_{N\to\infty}p_N(\phi)=1\).
    #+END_proof

*** Ehrenfeucht-Fraïssé Games
    Let \(\call\) be a language and \(\calm=(M,\dots)\) and \(\caln=(N,\dots)\)
    be two \(\call\)-structures with \(M\cap N=\emptyset\). If \(A\subseteq M\),
    \(B\subseteq N\) and \(f:A\to B\), we wsay that \(f\) is a *partial embedding*
    if \(f\cup\{(c^\calm,c^\caln):c\text{ a constant of }\call\}\)is a bijection
    preserving all relations and functions of \(\call\)

    We will define an infinite two-player game \(G_\omega(\calm,\caln)\). We
    will call the two players player \rom{1} and player \rom{2}; together they
    will build a partial embedding \(f\) from \(M\) to \(N\). A play of the game
    will consist of \omega stages. At the \(i\)th-stage, player \rom{1} moves first
    and either plays \(m_i\in M\), challenging player \rom{2} to put \(m_i\)
    into the domain of \(f\), or \(n_i\in N\), challenging player \rom{2} to put
    \(n_i\) into the range. If player \rom{1} plays \(m_i\in M\), then player
    \rom{2} must play \(n_i\in N\), whereas if player \rom{1} plays 
    \(n_i\in M\), then player \rom{2} must play \(m_i\in M\). Player \rom{2} wins the
    play of the game if \(f=\{(m_i,n_i):i=1,2,\dots\}\) is the graph of a
    partial embedding.

    A *strategy* for player \rom{2} in \(G_\omega(\calm,\caln)\) is a function \tau
    s.t. if player \rom{1}'s first \(n\) moves are \(c_1,\dots,c_n\) , then
    player \rom{2}'s \(n\)th move will be \(\tau(c_1,\dots,c_n)\). We say that
    player \rom{2} uses the strategy \tau in the play of the game if the play looks
    like
    #+ATTR_LATEX: :align cc
    | Player \rom{1} | Player \rom{2}     |
    | \(c_1\)        |                    |
    |                | \(\tau(c_1)\)         |
    | \(c_2\)        |                    |
    |                | \(\tau(c_1,c_2)\)     |
    | c_3            |                    |
    |                | \(\tau(c_1,c_2,c_3)\) |
    | \(\vdots\)     | \(\vdots\)         |


    We say that \tau is a *winning strategy* for player \rom{2}, if for any sequence
    of plays \(c_1,\dots\) player \rom{1} makes, player \rom{2} will win by
    following \tau. We define strategies for player \rom{1} analogously

    For example, suppose that \(\calm,\caln\models\DLO\). Then player \rom{2}
    has a winning strategy. Suppose that up to stage $n$ they have built a
    partial embedding \(g:A\to B\). If player \rom{1} plays \(a\in M\), then
    player \rom{2} plays \(b\in N\) s.t. the cub $b$ makes in \(B\) is the image
    of the cut of \(a\) in \(A\) under \(g\). Similar for player \rom{1}'s
    \(b\in N\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(\calm\) and \(\caln\) is countable, then the second player has a wining
    strategy in \(G_\omega\) if and only if \(\calm\cong\caln\)
    #+END_proposition

    #+BEGIN_proof
    If \(\calm\cong\caln\), player \rom{2} can win by playing according to the
    isomorphism

    Suppose that player \rom{2} has a winning strategy. Let \(m_0,m_1,\dots\)
    list \(M\) and \(n_0,n_1,\dots\) list $N$. Consider a play of the game where
    the second player uses the winning strategy and the first player plays 
    \(m_0,n_0,m_1,n_1,m_2,n_2,\dots\). If \(f\) is the partial embedding build
    during this play of the game then the domain of \(f\) is $M$ and the range
    of \(f\) is $N$. Thus \(f\) is an isomorphism
    #+END_proof

    [[index:Ehrenfeucht-Fraïssé Games]]

    _Fix \(\call\) a finite language with no function symbols_, and let \(\calm\)
    and \(\caln\) be \(\call\)-structures. We define a game \(G_n(\calm,\caln)\)
    for \(n=1,2,\dots\). The game will have \(n\) rounds similar to \omega rounds
    . Player \rom{2} wins if
    \(\{(a_i,b_i):i=1,\dots,n\}\) is the graph of a partial embedding from
    \(\calm\) into \(\caln\). We call \(G_n(\calm,\caln)\) an 
    *Ehrenfeucht-Fraïssé Games*
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(\call\) be a finite language without function symbols and let
    \(\calm\) and \(\caln\) be \(\call\)-structures. Then \(\calm\equiv\caln\)
    if and only if the second player has a wining strategy in
    \(G_n(\calm,\caln)\) for all \(n\)
    #+END_theorem

    We need several lemmas.

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    One of the players has a winning strategy in \(G_n(\calm,\caln)\)
    #+END_lemma

    #+BEGIN_proof
    Suppose that player \rom{2} does not have a winning strategy. Then there is
    some move player \rom{1} can make in round one so that player \rom{2} has no
    move available to force a win. Player \rom{1} makes that move. Now, whatever
    player \rom{2} does, there is still a move that if made by player \rom{1}
    means that player \rom{2} cannot force a win.
    #+END_proof

    We inductively define \(\text{depth}(\phi)\), the *quantifier depth* of an
    \(\call\)-formula \phi, as follows
    
    \(\text{depth}(\phi)=0\) if and only if \phi is quantifier-free

    \(\text{depth}(\neg\phi)=\text{depth}(\phi)\)
    
    \(\text{depth}(\phi\wedge\psi)=\text{depth}(\phi\vee\psi)=
    \max\{\text{depth}(\phi),\text{depth}(\psi)\}\)

    \(\text{depth}(\exists v\phi)=\text{depth}(\phi)+1\)

    We say that \(\calm\equiv_n\caln\) if
    \(\calm\models\phi\Leftrightarrow\caln\models\phi\) for all sentences of
    depth at most $n$. We will show player \rom{2} has a winning strategy in
    \(G_n(\calm,\caln)\) if and only if \(\calm\equiv_n\caln\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For each \(n\) and \(l\), there is a finite list of formulas
    \(\phi_1,\dots,\phi_k\) of depth at most \(n\) in free variables
    \(x_1,\dots,x_l\) s.t. every formula of depth at most $n$ in free variables
    \(x_1,\dots,x_l\) is equivalent to some \(\phi_i\)
    #+END_lemma

    #+BEGIN_proof
    We first prove this for quantifier-free formulas. Because \(\call\) is
    finite and has no function symbols, there are only finitely many atomic
    \(\call\)-formulas in free variables \(x_1,\dots,x_l\). Let
    \(\sigma_1,\dots,\sigma_s\) list all such formulas.

    If \phi is a Boolean combination of formulas \(\tau_1,\dots,\tau_s\), then
    there is \(S\) a collection of subsets of \(\{1,\dots,s\}\) s.t.
    \begin{equation*}
    \models\phi\leftrightarrow\displaystyle
    \bigvee_{X\in S}\left(\bigwedge_{i\in X}\tau_i\wedge
    \bigwedge_{i\not\in X}\neg\tau_i
    \right)
    \end{equation*}
    This gives a list of \(2^{2^s}\) formulas s.t. every Boolean combination of
    \(\tau_1,\dots,\tau_s\) is equivalent to a formula in this list. In
    particular, because quantifier free formulas are Boolean combinations of
    atomic formulas, there is a finite list of depth-zero formulas s.t. every
    depth-zero formula is equivalent to one in the list.

    Because formulas of depth \(n+1\) are Boolean combinations of 
    \(\exists v\phi\) and \(\forall v\phi\) where \phi has depth at most \(n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\call\) be a finite language without function symbols and \(\calm\)
    and \(\caln\) be \(\call\)-structures. The second player has a winning
    strategy in \(G_n(\calm,\caln)\) if and only if \(\calm\equiv_n\caln\)
    #+END_lemma

    #+BEGIN_proof
    Induction on \(n\)

    Suppose that \(\calm\equiv_n\caln\). Consider a play of the game where in
    round one player \rom{1} plays \(a\in M\). We claim that there is
    \(b\in\caln\) s.t. \(\calm\models\phi(a)\Leftrightarrow\caln\models\phi(b)\)
    whenever \(\depth(\phi)<n\). Let \(\phi_0(v),\dots,\phi_m(v)\) list, up to
    equivalance, all formulas of depth less than \(n\). Let 
    \(X=\{i\le m:\calm\models\phi_i(a)\}\), and let \(\Phi(v)\) be the formula
    \begin{equation*}
    \displaystyle\bigwedge_{i\in X}\phi_i(v)\wedge\bigwedge_{i\not\in X}
    \neg\phi_i(v)
    \end{equation*}
    Then, \(\depth(\exists v\Phi(v))\le n\) and \(\calm\models\Phi(a)\); thus
    there is \(b\in N\) s.t. \(\caln\models\Phi(b)\). Player \rom{2} plays \(b\)
    in round one

    If \(n=1\), the game has now concluded and \(a\mapsto b\) is a partial
    embedding so player \rom{2} wins. Suppose that \(n>1\)

    Let \(\call^*=\call\cup\{c\}\), where \(c\) is a new constant symbol. View
    \(\calm\) and \(\caln\) as \(\call^*\)-structures \((\calm,a)\) and
    \((\caln,b)\) where we interpret the new constant as \(a\) and \(b\)
    respectively. Because 
    \begin{equation*}
    \calm\models\phi(a)\Leftrightarrow\caln\models\phi(b)
    \end{equation*}
    for \(\phi(v)\) an \(\call\)-formula with \(\depth(\phi)<n\),
    \((\calm,a)\equiv_{n-1}(\caln,b)\). By induction, player \rom{2} has a
    winning strategy in \(G_{n-1}((\calm,a),(\caln,b))\). If player's second
    play is \(d\), player \rom{2} responds as if \(d\) was player \rom{1}'s
    first play in \(G_{n-1}((\calm,a),(\caln,b))\)' and continues playing using
    this strategy, that is, in round $i$ player \rom{1} has plays
    \(a,d_2,\dots,d_i\), then player \rom{2} plays \(\tau(d_2,\dots,d_i)\), where 
    \(\tau\) is his winning strategy in \(G((\calm,a),(\caln,b))\).
    #+END_proof

** Exercises
   #+BEGIN_exercise
   label:ex2.5.1
   We say that an ordered group \((G,+,<)\) is *Archimedean* if for all
   \(x,y\in G\) with \(x,y>0\) there is an integer \(m\) s.t.
   \(\abs{x}<m\abs{y}\). Show that there are non-Archimedean fields elementarily
   equivalent to the field of real numbers
   #+END_exercise

   #+BEGIN_exercise
   label:ex2.5.10
   Let \(T\) be an \(\call\)-theory and \(T_\forall\) be all of the universal
   sentences \phi s.t. \(T\models\phi\). Show that \(\cala\models T_\forall\) if and only
   if there is \(\calm\models T\) with \(\cala\subseteq\calm\)
   #+END_exercise

   #+BEGIN_proof
   Comes from [[http://www.math.uni-konstanz.de/~eleftheriou/teaching/Masterarbeit.pdf][Quantifier Elimination Tests and Examples]]
   
   Consider the theory \(T'=T\cup\Diag(\cala)\) in the language \(\call_A\). We
   will show by contradiction that \(T'\) is satisfiable.

   Suppose that \(T'\) is not satisfiable. Then by the Compactness Theorem,
   already some finite subset \(\Delta\subseteq T'\) is not satisfiable. By forming
   conjunctions we may assume that the part of \Delta coming from \(\Diag(\cala)\)
   consists only of one formula \(\phi(\bar{a})\) for some \(\bar{a}\in\ A\), where
   \(\phi(\bar{a})\) is a conjunction of atomic formulas and the negation of atomic
   formulas. Thus we will assume that \(T\cup\{\phi(\bar{a})\}\) is not satisfiable.

   On the other hand, viewing \(T\) as an \(\call_{\bar{a}}\)-theory, and because
   \(T\cup\{\phi(\bar{a})\}\) is not satisfiable, we obtain
   \(T\models\neg\phi(\bar{a})\). We will show that this implies
   \(T\models\forall\bar{v}\neg\phi(\bar{v})\): Let \(\calc\) be an
   \(\call\)-structure with \(\calc\models T\). Let \(n\) be the number of
   components in \(\bar{a}\) and \(c_1,\dots,c_n\in C\). Let \(C'\) be the
   \(\call_{\bar{a}}\)-structure which expands \(\calc\) by the constant symbols
   that we interpret as \(c_1,\dots,c_n\) respectively. Then \(\calc'\models T\) and
   hence \(\calc'\models\neg\phi(\bar{c})\). As this follows for any tuple in
   \(C\), we get \(\calc\models\forall\bar{v}\neg\phi(\bar{v})\)

   Since \(T_\forall\) consists exactly of the universal formulas which hold in all
   models of \(T\), we obtain \(T_\forall\models\forall x\neg\phi(x)\). Hence also
   \(\cala\models\forall x\neg\phi(x)\), a contradiction

   Therefore \(T'\) is indeed satisfiable
   #+END_proof

* Algebraic Examples

** Quantifier Elimination
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that a theory $T$ has *quantifier elimination* if for every formula \phi
   there is a quantifier-free formula \psi s.t.
   \begin{equation*}
   T\models\phi\leftrightarrow\psi
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \((A,<)\) and \((B,<)\) be countable dense linear orders,
   \(a_1,\dots,a_n\in A\), \(b_1,\dots,b_n\in B\), s.t. \(a_1<\dots<a_n\) and
   \(b_1,\dots<b_n\). Then there is an isomorphism \(f:A\to B\) s.t.
   \(f(a_i)=b_i\) for all \(i=1,\dots,n\)
   #+END_lemma
   
   #+BEGIN_proof
   Modify the proof of Theorem ref:thm2.4.1 starting with
   \(A_0=\{a_1,\dots,a_n\}\), \(B_0=\{b_1,\dots,b_n\}\), and the partial
   isomorphism \(f_0:A_0\to B_0\), where \(f_0(a_i)=b_i\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   DLO has quantifier elimination
   #+END_theorem
   #+BEGIN_proof
   First, suppose that \(\phi\) is a sentence. If \(\Q\models\phi\), then
   because DLO is complete, \(\DLO\models\phi\), and 
   \begin{equation*}
   \DLO\models\phi\leftrightarrow x_1=x_1
   \end{equation*}
   whereas if \(\Q\models\neg\phi\)
   \begin{equation*}
   \DLO\models\phi\leftrightarrow x_1\neq x_1
   \end{equation*}

   Now suppose that \phi is a formula with free variables \(x_1,\dots,x_n\) where
   \(n\ge1\). We will show that there is a quantifier-free formula \psi with free
   variables from among \(x_1,\dots,x_n\) s.t.
   \begin{equation*}
   \Q\models\forall\bar{x}(\phi(\bar{x})\leftrightarrow\psi(\bar{x}))
   \end{equation*}
   Because DLO is complete,
   \begin{equation*}
   \DLO\models\forall\bar{x}(\phi(\bar{x})\leftrightarrow\psi(\bar{x}))
   \end{equation*}
   so this will suffices.

   For \(\sigma:\{(i,j):1\le i<j\le n\}\to3\), let \(\chi_\sigma(x_1,\dots,x_n)\) be the formula
   \begin{equation*}
   \displaystyle\bigwedge_{\sigma(i,j)=0}x_i=x_j\wedge
   \bigwedge_{\sigma(i,j)=1}x_i<x_j\wedge
   \bigwedge_{\sigma(i,j)=2}x_i>x_j
   \end{equation*}
   We call \(\chi_\sigma\) a *sign condition*.

   Let \(\call\) be the language of linear orders and \phi be an
   \(\call\)-formula with \(n\ge1\) free variables. Let \(\Lambda_\phi\) be the
   set of sign conditions s.t. there is \(\bar{a}\in\Q\) s.t.
   \(\Q\models\chi_\sigma(\bar{a})\wedge\phi(\bar{a})\)

   
   _case 1:_ \(\Lambda_\phi=\emptyset\)

   Then \(\Q\models\forall\bar{x}\neg\phi(\bar{x})\) and
   \(\Q\models\phi(\bar{x})\leftrightarrow x_1\neq x_1\)

   _case 2:_ \(\Lambda_\phi\neq\emptyset\)

   Let
   \begin{equation*}
   \psi_\phi(\bar{x})=\displaystyle\bigwedge_{\sigma\in\Lambda_\phi}\chi_\sigma(\bar{x})
   \end{equation*}

   By choice of \(\Lambda_\phi\),
   \begin{equation*}
   \Q\models\phi(\bar{x})\to\psi_\phi(\bar{x})
   \end{equation*}

   On the other hand, suppose that \(\bar{b}\in\Q\) and
   \(\Q\models\psi_\phi(\bar{b})\). Let \(\sigma\in\Lambda_\phi\) s.t. \(\Q\models\chi_\sigma(\bar{b})\).
   There is \(\bar{a}\in\Q\) s.t. \(\Q\models\phi(\bar{a})\wedge\chi_\sigma(\bar{a})\). By Theorem
   ref:thm2.4.1, there is \(f\), an automorphism of \((\Q,<)\) s.t.
   \(f(\bar{a})=\bar{b}\). By Theorem ref:thm1.1.10, \(\Q\models\phi(\bar{b})\).
   Thus \(\phi(\bar{b})\leftrightarrow\psi_\phi(\bar{b})\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.1.4
   Suppose that \(\call\) contains a constant symbol \(c\), \(T\) is an
   \(\call\)-theory, and \(\phi(\bar{v})\) is an \(\call\)-formula. The following
   are equivalent:
   1. There is a quantifier-free \(\call\)-formula \(\psi(\bar{v})\) s.t.
      \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\)
   2. If \(\calm\) and \(\caln\) are models of \(T\), \(\cala\) is an
      \(\call\)-structure, \(\cala\subseteq\calm\), and \(\cala\subseteq\caln\),
      then \(\calm\models\phi(\bar{a})\) if and only if \(\caln\models\phi(\bar{a})\)
      for all \(\bar{a}\in\cala\)
   #+END_theorem

   #+BEGIN_proof
   \((1)\to(2)\). Suppose that \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\),
   where \psi is quantifier-free. Let \(\bar{a}\in\cala\), where \(\cala\) is a
   common substructure of \(\calm\) and \(\caln\) and the latter structures are
   models of \(T\). In Proposition ref:prop1.1.8, we saw that quantifer-free
   formulas are preserved under substructure and extension. Thus
   \begin{align*}
   \calm\models\phi(\bar{a})&\Leftrightarrow\calm\models\psi(\bar{a})\\
   &\Leftrightarrow\cala\models\psi(\bar{a})\\
   &\Leftrightarrow\caln\models\psi(\bar{a})\\
   &\Leftrightarrow\caln\models\phi(\bar{a})
   \end{align*}

   \((2)\to(1)\). First, if \(T\models\forall\bar{v}\phi(\bar{v})\), then
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow c=c)\).Second, if
   \(T\models\forall\bar{v}\neg\phi(\bar{v})\), then
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow c\neq c)\).

   Thus, we may assume that both \(T\cup\{\phi(\bar{v})\}\) and \(T\cup\{\neg\phi(\bar{v})\}\)
   are satisfiable

   Let \(\Gamma(\bar{v})=\{\psi(\bar{v}):\psi\text{ is quantifier free and
   }T\models\forall\bar{v}(\phi(\bar{v})\to\psi(\bar{v}))\}\). Let
   \(d_1,\dots,d_m\) be new constant symbols. We will show that
   \(T\cup\Gamma(\bar{d})\models\phi(\bar{d})\). Then, by compactness, there are
   \(\psi_1,\dots,\psi_n\in\Gamma\) s.t.
   \begin{equation*}
   T\models\forall\bar{v}\left(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\to\phi(\bar{v})
   \right)
   \end{equation*}
   Thus
   \begin{equation*}
   T\models\forall\bar{v}\left(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\leftrightarrow
   \phi(\bar{v})
   \right)
   \end{equation*}
   and \(\displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\) is quantifier-free

   *Claim* \(T\cup\Gamma(\bar{d})\models\phi(\bar{d})\)

   Suppose not. Let \(\calm\models T\cup\Gamma(\bar{d})\cup\{\neg\phi(\bar{d})\}\). Let \(\cala\)
   be the substructure of \(\calm\) generated by \(\bar{d}\)

   Let \(\Sigma=T\cup\Diag(\cala)\cup\phi(\bar{d})\). If \Sigma is unsatisfiable, then there are
   quantifier-free formulas \(\psi_1(\bar{d}),\dots,\psi_n(\bar{d})\in\Diag(\cala)\) s.t.
   \begin{equation*}
   T\models\forall\bar{v}\left(
   \displaystyle\bigwedge_{i=1}^n\psi_i(\bar{v})\to\neg\phi(\bar{v})
   \right)
   \end{equation*}
   But then
   \begin{equation*}
   T\models\forall\bar{v}\left(\phi(\bar{v})\to
   \displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{v})
   \right)
   \end{equation*}
   so \(\displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{v})\in\Gamma\) and
   \(\cala\models\displaystyle\bigvee_{i=1}^n\neg\psi_i(\bar{d})\), a
   contradiction. Thus, \Sigma is satisfiable

   Let \(\caln\models\Sigma\). Then \(\caln\models\phi(\bar{d})\). Because
   \(\Sigma\supseteq\Diag(\cala)\), \(\cala\subseteq\caln\), by Lemma ref:lemma2.3.3.
   But \(\calm\models\neg\phi(\bar{d})\); thus \(\caln\models\neg\phi(\bar{d})\), a contradiction
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.1.5
   Let \(T\) be an \(\call\)-theory. Suppose that for every quantifier-free
   \(\call\)-formula \(\theta(\bar{v},w)\) there is a quantifier-free formula
   \(\psi(\bar{v})\) s.t. \(T\models\exists w\theta(\bar{v},w)\leftrightarrow\psi(\bar{v})\). Then \(T\)
   has quantifier elimination
   #+END_lemma

   #+BEGIN_proof
   Let \(\phi(\bar{v})\) be an \(\call\)-formula. We wish to show to show that
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\) for some quantifier-free
   formula \(\psi(\bar{v})\)

   If \phi is quantifier-free, there is nothing to prove. Suppose that for
   \(i=0,1\), \(T\models\forall\bar{v}(\theta_i(\bar{v})\leftrightarrow\psi_i(\bar{v}))\), where
   \(\psi_{i}\) is quantifier-free.

   If \(\phi(\bar{v})=\neg\theta_0(\bar{v})\), then
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\neg\psi_0(\bar{v}))\)

   Suppose that \(T\models\forall\bar{v}(\theta(\bar{v},w)\leftrightarrow\psi_0(\bar{v},w))\), where
   \(\psi_0\) is quantifier-free and \(\phi(\bar{v})=\exists w\theta(\bar{v},w)\). Then
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\exists\psi_0(\bar{v},w))\). By our assumptions,
   there is a quantifier-free \(\psi(\bar{v})\) s.t.
   \(T\models\forall\bar{v}(\exists w\psi_0(\bar{v},w)\leftrightarrow\psi(\bar{v}))\). But then
   \(T\models\forall\bar{v}(\phi(\bar{v})\leftrightarrow\psi(\bar{v}))\)

   #+END_proof

   Combining Theorem ref:thm3.1.4 and Lemma ref:lemma3.1.5 gives us the
   following test for quantifier elimination
   #+ATTR_LATEX: :options [NEED TO RECONSIDER]
   #+BEGIN_corollary
   label:cor3.1.6
   Let \(T\) be an \(\call\)-theory. Suppose that for all quantifier-free
   formulas \(\phi(\bar{v},w)\), if \(\calm,\caln\models T\), \(\cala\) is a common
   substructure of \(\calm\) and \(\caln\), \(\bar{a}\in A\), and there is
   \(b\in M\) s.t. \(\calm\models\phi(\bar{a},b)\), then there is \(c\in N\) s.t.
   \(\caln\models\phi(\bar{a},c)\). Then $T$ has a quantifier elimination
   #+END_corollary

   #+BEGIN_proof
   Check this notes [[http://www.math.uni-konstanz.de/~eleftheriou/teaching/Masterarbeit.pdf][Quantifier Elimination Tests and Examples]]

   We need to show that \(T\models\forall\bar{v}(\exists w\phi(\bar{v},w)\leftrightarrow\psi(\bar{v}))\).
   Suppose that \(\calm\models\exists w\phi(\bar{v},w)\), then
   \(\caln\models\exists w\phi(\bar{v},w)\). Note that \(\calm\) and \(\caln\) are interchangeable.
   #+END_proof



*** Divisible Abelian Groups
    Work with the language \(\call=\{+,-,0\}\) because its convenient

    Let DAG be the \(\call\)-theory of nontrivial torsion-free divisible Abelian
    groups

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.1.7
    Suppose \(G\) and \(H\) are nontrivial torsion free divisible Abelian
    groups, \(G\subseteq H\), \(\psi(\bar{v},w)\) is quantifier-free,
    \(\bar{a}\in G\), \(b\in H\), and \(H\models\phi(\bar{a},b)\). Then there is
    \(c\in G\) s.t. \(G\models\phi(\bar{a},c)\)
    #+END_lemma

    #+BEGIN_proof
    We first note that \psi can be put in disjunctive normal form.

    Because \(H\models\psi(\bar{a},b)\),
    \(H\models\bigwedge_{j=1}^m\theta_{i,j}(\bar{a},b)\) for some \(i\). Thus, without
    loss of generality, we may assume that \psi is a conjunction of atomic and
    negated atomic formulas. If \(\theta(v_1,\dots,v_m,w)\) is an atomic formula,
    then for some integers \(n_1,\dots,n_m,m\), \(\theta(\bar{v},w)\) is
    \(\sum n_iv_i+mw=0\)

    Thus we may assume that
    \begin{equation*}
    \psi(\bar{a},w)=\displaystyle\bigwedge_{i=1}^s\sum_{j=1}^mn_{i,j}a_j+m_iw=0\wedge
    \bigwedge_{i=1}^s\sum_{j=1}^mn_{i,j}'a_j+m_i'w\neq0
    \end{equation*}
    Let \(g_i=\sum n_{i,j}a_j\) and \(h_i=\sum n_{i,j}'a_j'\). Then \(g_i,h_i\in G\) and
    \begin{equation*}
    \psi(\bar{a},w)\leftrightarrow\bigwedge g_i+m_iw=0\wedge\bigwedge h_i+m_i'w\neq0
    \end{equation*}

    If any \(m_i\neq0\), then \(b=-g_i/m_i\in G\) and \(G\models\theta(\bar{a},b)\),
    so suppose that \(\psi(\bar{a},w)=\bigwedge h_i+m_i'w\neq0\). Thus
    \(\psi(\bar{a},w)\) is satisfied by any element of \(H\) that is not equal to
    any one of \(\frac{-h_1}{m_1'},\dots,\frac{-h_s}{m_s'}\). Because \(G\) is
    infinite, there is an element  of \(G\) satisfying \(\psi(\bar{a},w)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.1.8
    Suppose that \(G\) is a torsion-free Abelian group. Then there is a
    torsion-free divisible Abelian group $H$, called the *divisible hull* of
    \(G\), and an embedding \(i:G\to H\) s.t. if \(j:G\to H'\) is an embedding of
    \(G\) into a torsion-free divisible Abelian group, then there is \(h:H\to H'\) s.t.
    \(j=h\circ i\)
    #+END_lemma

    #+BEGIN_proof
    If \(G\) is the trivial group, then we take \(H=\Q\) since every torsion
    free divisible Abelian group can be viewed as a vector space over \(\Q\). So
    suppose that \(G\) is non-trivial

    Let \(X=\{(g,n):g\in G,n\in\N,n>0\}\). We think of \((g,n)\) as \(g/n\)

    We define an equivalence relation \(\sim\) on \(X\) by \((g,n)\sim(h,m)\) if and
    only if \(mg=nh\). Let \(H=X/\sim\). For \((g,n)\in X\), let \([(g,n)]\) denote
    the \(\sim\)-class of \((g,n)\). We define \(+\) on \(H\) by
    \([(g,n)]+[(h,m)]=[(mg+nh,mn)]\). We must show that \(+\) is well defined

    Suppose that \((g_0,n_0)\sim(g,n)\). We claim that
    \((mg_0+n_0h,mn_0)\sim(mg+nh,mn)\).

    Similarly we can define \(-\) by \([(g,n)]-[(h,m)]=[(mg-nh,mn)]\). It is
    easy to show that \((H,+)\) is an Abelian group

    If \([(g,m)]\in H\) and \(n>0\), then \(n[(g,m)]=[(ng,m)]\). If
    \((ng,m)\sim(0,k)\), then \(kng=0\). Becasue \(k,n>0\) and \(G\) is torsion
    free, \(g=0\). Then \([(g,m)]=[(0,1)]\). Thus \(H\) is torsion free.

    Suppose that \([(g,m)]\in H\) and \(n>0\), then \(n[(g,mn)]=[(g,m)]\). Thus
    \(H\) is divisible.

    We can embed \(G\) into \(H\) by the map \(i(g)=[(g,1)]\)

    Suppose that \(H'\) is a divisible torsion-free Abelian group and
    \(j:G\to H'\) is an embedding. Let \(h:H\to H'\) by \(h([g,n])=j(g)/n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    DAG has quantifier elimination
    #+END_theorem
    #+BEGIN_proof
    Suppose that \(G_0\) and \(G_1\) are torsion-free divisible Abelian groups,
    \(G\) is a common subgroup of \(G_0\) and \(G_1\), \(\bar{g}\in G\),
    \(h\in G_0\) and \(G_0\models\phi(\bar{g},h)\), where \phi is quantifier-free.
    Let \(H\) be the divisible hull of \(G\). Because we can embed \(H\) into
    \(G_0\), by Lemma ref:lemma3.1.7, \(H\models\exists w\phi(\bar{g},w)\). Because
    we can embed \(H\) into \(G_1\), there is \(h'\in G_1\) s.t.
    \(G_1\models\phi(\bar{g},h')\). By Corollary ref:cor3.1.6, DAG has
    quantifier elimination
    #+END_proof

    Quantifier elimination gives us a good picture of the definable sets in
    a model of DAG. Suppose that \(\phi(v_1,\dots,v_n,w_1,\dots,w_m)\) is an atomic
    formula. Then there are integers \(k_1,\dots,k_n\) and \(l-1,\dots,l_m\) s.t.
    \(\phi(\bar{v},\bar{w})\leftrightarrow\sum k_ix_i+\sum l_iy_i=0\). If \(G\models\DAG\) and
    \(a_1,\dots,a_m\in G\), \(\phi(\bar{v},\bar{a})\) defines
    \(\{\bar{g}\in G^n:\sum k_ig_i+\sum l_ia_i=0\}\), a hyperplane in \(G^n\). Because
    any \(\call\)-formula \(\phi(\bar{v},\bar{w})\) is equivalent in DAG to a
    Boolean combination of atomic \(\call\)-formulas, every definable subset of
    \(G^n\) is a Boolean combination of hyperplanes

    In particular, suppose that \(\bar{a}\in G^m\) and \(\phi(v,\bar{a})\) defines a
    subset of \(G\). The "hyperplanes" in \(G\) are just single points. Thus,
    \(\{g\in G:G\models\phi(g,\bar{a})\}\) is either finite or cofinite. Thus
    every definable subset of \(G\) was definable already in the language of equality

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that an \(\call\)-theory $T$ is *strongly minimal* if for any
    \(\calm\models T\) every definable subset of \(M\) is either finite or cofinite
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    DAG is strongly minimal
    #+END_corollary


    If \(T\) is a theory then \(T_\forall\) is the set of all universal consequences
    of \(T\)

* Set Theory
** Cardinal Arithmetic
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   label:corA.15 
   1. If \(\abs{I}=\kappa\) and \(\abs{A_i}\le\kappa\) for all \(i\in I\), then 
      \(\abs{\bigcup A_i}\le\kappa\)
   2. If \kappa is regular, \(\abs{I}<\kappa\) and \(\abs{A_i}<\kappa\) for all 
      \(i\in I\), then \(\abs{\bigcup A_i}<\kappa\)
   3. Let \kappa be an infinite cardinal. Let $X$ be a set and \(\calf\) a set of
      functions \(f:X^{n_f}\to X\). Suppose that \(\abs{\calf}\le\kappa\) and
      \(A\subseteq X\) with \(\abs{A}\le\kappa\). Let \(\cl(A)\) be the smallest
      subset of $X$ containing $A$ closed under the functions in \(\calf\). Then 
      \(\abs{\cl(A)}\le\kappa\)
   #+END_corollary
* Algebra
  Comes from cite:lang2005algebra
** Real Fields
*** Ordered Fields
    Let \(K\) be a field. An *ordering* of \(K\) is a subset \(P\) of \(K\)
    having the following properties
    \bigskip
    \begin{itemize}[itemindent=3em]
    \item[\textbf{ORD 1.}] Given \(x\in K\), we have either \(x\in P\) ,or \(x=0\) or
    \(-x\in P\), and these three possibilities are mutually exclusive
    \item[\textbf{ORD 2.}] If \(x,y\in P\), then \(x+y,xy\in P\)
    \end{itemize}

    \(K\) is *ordered by* \(P\), and we call \(P\) the set of *positive
    elements*

    Suppose \(K\) is ordered by \(P\). Since \(1\neq0\) and \(1=1^2=(-1)^2\), we
    see that \(1\in P\). By *ORD 2*, it follows that \(1+\dots+1\in P\), whence \(K\)
    has characteristic 0. If \(x\in P\) and \(x\neq0\), then \(xx^{-1}=1\in P\) implies
    that \(x^{-1}\in P\)

    #+BEGIN_center
    /Let \(E\) be a field. Then a product of sums of squares in \(E\) is a sum
    of squares./

    /If \(a,b\in E\) are sum of squares and \(b\neq0\), then \(a/b\) is a sum of
    squares/
    #+END_center

    Consider complex number:)

    Let \(x,y\in K\). We define \(x<y\) to mean that \(y-x\in P\). If \(x<0\) we say
    that \(x\) is *negative*.

    If \(K\) is ordered and \(x\in K\), \(x\neq0\), then \(x^2\) is positive

    If \(E\) has characteristic \(\neq2\), and \(-1\) is a sum of squares in \(E\),
    then every element \(a\in E\) is a sum of squares, because
    \(4a=(1+a)^2-(1-a)^2\)

    If \(K\) is a field with an ordering \(P\), and \(F\) is a subfield, then
    obviously, \(P\cap F\) defines an ordering of \(F\), which is called the
    *induced* ordering

    Let \(K\) be an ordered field and let \(F\) be a subfield with the induced
    ordering. We put \(\abs{x}=x\) if \(x>0\) and \(\abs{x}=-x\) if \(x<0\). An
    element \(\alpha\in K\) is *infinitely large* over \(F\) if \(\abs{\alpha}\ge x\) for all
    \(x\in F\). It is *infinitely small* over \(F\) if \(0\le\abs{\alpha}\le\abs{x}\) for
    all \(x\in F\), \(x\neq0\). \alpha is infinitely large if and only if \(\alpha^{-1}\) is
    infinitely small. \(K\) is *archimedean* over \(F\) if \(K\) has no elements
    which are infinitely large over \(F\). An intermediate field \(F_1\),
    \(K\supset F_1\supset F\) is *maximal archimedean over* \(F\) in \(K\) if it is
    archimedean over \(F\) and no other intermediate field containing \(F_1\) is
    archimedean over \(F\). We say that \(F\) is *maximal archimedean in* \(K\)
    if it is maximal archimedean over itself in \(K\)

    Let \(K\) be an ordered field and \(F\) a subfield. Let \(K\) be an ordered
    field and \(F\) a subfield. Let \(\fo\) be the set of elements of \(K\)
    which are not infinitely large over \(F\). Then \(\fo\) is a ring and that
    for any \(\alpha\in K\), we have \(\alpha\) or \(\alpha^{-1}\in\fo\). Hence \(\fo\) is what is
    called a valuation ring, containing \(F\). Let \(\fm\) be the ideal of all
    \(\alpha\in K\) which are infinitely small over \(F\). Then \(\fm\) is the unique
    maximal ideal of \(\fo\), because any element in \(\fo\) which is not in
    \(\fm\) has an inverse in \(\fo\). We call \(\fo\) the
    *valuation ring determined by the ordering of* \(K/F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(K\) be an ordered field and \(F\) a subfield. Let \(\fo\) be the
    valuation ring determined by the ordering of \(K/F\), and let \(\fm\) be its
    maximal ideal. Then \(\fo/\fm\) is a real field.
    #+END_proposition

    #+BEGIN_proof
    Otherwise, we could write
    \begin{equation*}
    -1=\displaystyle\sum\alpha_i^2+a
    \end{equation*}
    with \(\alpha_i\in\fo\) and \(a\in\fm\). Since \(\sum\alpha_i^2\) is positive and \(a\) is
    infinitely small, such a relation is clearly impossible
    #+END_proof

* Reference
  bibliographystyle:alpha
  bibliography:/media/wu/file/stuuudy/notes/references.bib
* Index
  \renewcommand{\indexname}{}
  printindex:nil
  \appendix
[fn:stack]  [[https://math.stackexchange.com/questions/1170953/let-alpha-be-any-cardinal-there-are-at-most-2-alpha-cup-mathscrl][stackexchange]]
[fn:proofkappa] [[https://proofwiki.org/wiki/Field_of_Uncountable_Cardinality_K_has_Transcendence_Degree_K][proofwiki]]
