#+TITLE: Model Theory for Dummies: An Introduction
#+AUTHOR: David Marker


#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/ModelTheoryAnIntroduction/ModelTheoryAnIntroduction.tex
* Structures and Theories
** Languages and Structures
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A language $\call$ is given by specifying the following data
   1. A set of function symbols $\calf$ and positive integers $n_f$ for each
      $f\in\calf$
   2. a set of relation symbols $\calr$ and positive integers $n_R$ for each
      $R\in\calr$
   3. a set of constant symbols $\calc$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-structure $\calm$ is given by the following data
   1. a nonempty set $M$ called the *universe*, *domain* or *underlying set*
      of $\calm$
   2. a function $f^\calm:M^{n_f}\to M$ for each $f\in\calf$
   3. a set $R^\calm\subseteq M^{n_R}$ for each $R\in\calr$
   4. an element $c^\calm\in M$ for each $c\in\calc$
   #+END_definition

   We refer to $f^\calm,R^\calm,c^\calm$ as the *interpretations* of the
   symbols $f,R$ and $c$. We often write the structure as
   $\calm=(M,f^\calm,R^\calm,c^\calm:f\in\calf,R\in\calr,c\in\calc)$ 

   [[index:\(\call\)-embedding]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose that $\calm$ and $\caln$ are \(\call\)-structures with universes $M$
   and $N$ respectively. An *\(\call\)-embedding* $\eta:\calm\to\caln$ is a
   one-to-one map $\eta:M\to N$ that
   1. $\eta(f^\calm(a_1,\dots,a_{n_f}))=f^\caln(\eta(a_1),\dots,\eta(a_{n_f}))$
      for all $f\in\calf$ and $a_1,\dots,a_{n_f}\in M$
   2. $(a_1,\dots,a_{m_R})\in R^\calm$ if and only if
      $(\eta(a_1),\dots,\eta(a_{m_R}))\in R^\caln$ for all $R\in\calr$ and
      $a_1,\dots,a_{m_R}\in M$
   3. $\eta(c^\calm)=c^\caln$ for $c\in\calc$
   #+END_definition

   A bijective \(\call\)-embedding is called an *\(\call\)-isomorphism*. If
   $M\subseteq N$ and the inclusion map is an \(\call\)-embedding, we say either
   $\calm$ is a *substrcture* of $\caln$ or that $\caln$ is an *extension*
   of $\calm$

   The *cardinality* of $\calm$ is $\abs{M}$, the cardinality of the universe of \(\calm\)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   The set of *\(\call\)-terms* is the smallest set $\calt$ s.t.
   1. $c\in\calt$ for each constant symbol $c\in\calc$
   2. each variable symbol $v_i\in\calt$ for $i=1,2,\dots$
   3. if $t_1,\dots,t_{n_f}\in\calt$ and $f\in\calf$ then
      $f(t_1,\dots,n_{n_f})\in\calt$ 
   #+END_definition


   Suppose that $\calm$ is an \(\call\)-structure and that $t$ is a term built
   using variables from $\bar{v}=(v_{i_1},\dots,v_{i_m})$. We want to interpret
   $t$ as a function $t^\calm:M^m\to M$. For $s$ a subterm of $t$ and
   $\bar{a}=(a_{i_1},\dots,a_{i_m})\in M$, we inductively define
   $s^\calm(\bar{a})$ as follows.
   1. If $s$ is a constant symbol $c$, then $s^\calm(\bar{a})=c^\calm$
   2. If $s$ is the variable $v_{i_j}$, then $s^\calm(\bar{a})=a_{i_j}$
   3. If $s$ is the term $f(t_1,\dots,t_{n_f})$, where $f$ is a function symbol
      of $\call$ and $t_1,\dots,t_{n_f}$ are terms, then 
      $s^\calm(\bar{a})=f^\calm(t^\calm_1(\bar{a}),\dots,t_{n_f}^\calm(\bar{a}))$

      
   The function $t^\calm$ is defined by $\bar{a}\mapsto t^\calm(\bar{a})$

   [[index:atomic formula]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \phi is an *atomic* *\(\call\)-formula* if \phi is either
   1. $t_1=t_2$ where $t_1$ and $t_2$ are terms
   2. $R(t_1,\dots,t_{n_R})$


   The set of *\(\call\)-formulas* is the smallest set $\calw$ containing the
   atomic formulas s.t.
   1. if $\phi\in\calw$, then $\neg\phi\in\calw$
   2. if $\phi,\psi\in\calw$, then $(\phi\wedge\psi),(\phi\vee\psi)\in\calw$
   3. if $\phi\in\calw$, then $\exists v_i\phi,\forall v_i\phi\in\calw$
   #+END_definition

   We say a variable $v$ *occurs freely* in a formula \phi if it is not
   inside a $\exists v$ or $\forall v$ quantifier; otherwise we say that it's
   *bound*. We call a formula a *sentence* if it has no free variables. We
   often write $\phi(v_1,\dots,v_n)$ to make explicit the free variables in \phi

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \phi be a formula with free variables from
   $\bar{v}=(v_{i_1,\dots,v_{i_m}})$ and let $\bar{a}=(a_{i_1},\dots,a_{i_m})\in
   M^m$. We inductively define $\calm\models\phi\bar{a}$ as follows
   1. If \phi is $t_1=t_2$, then $\calm\models\phi(\bar{a})$ if
      $t_1^\calm(\bar{a})=t_2^\calm(\bar{a})$ 
   2. If \phi is $R(t_1,\dots,t_{m_R})$ then $\calm\models\phi(\bar{a})$ if
      $(t_1^\calm(\bar{a}),\dots,t_{m_R}^\calm(\bar{a}))\in R^\calm$
   3. If \phi is $\neg\psi$ then $\calm\models\phi(\bar{a})$ if
      $\calm\not\models\psi(\bar{a})$
   4. If \phi is $(\psi\wedge\theta)$ then $\calm\models\phi(\bar{a})$ if
      $\calm\models\psi(\bar{a})$ and
      $\calm\models\theta(\bar{a})$
   5. If \phi is $(\psi\vee\theta)$ then $\calm\models\phi(\bar{a})$ if
      $\calm\models\psi(\bar{a})$ or
      $\calm\models\theta(\bar{a})$
   6. If \phi is $\exists v_j\psi(\bar{v},v_j)$ then $\calm\models\phi(\bar{a})$
      if there is $b\in M$ s.t. $\calm\models\psi(\bar{a},b)$
   7. If \phi is $\forall v_j\psi(\bar{v},v_j)$ then $\calm\models\phi(\bar{a})$
      if $\calm\models\psi(\bar{a},b)$ for all $b\in M$
   #+END_definition


   If $\calm\models\phi(\bar{a})$ we say that $\calm$ *satisfies*
   $\phi(\bar{a})$ or $\phi(\bar{a})$ is *true* in $\calm$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop1.1.8
   Suppose that $\calm$ is a substrcture of $\caln$, $\bar{a}\in M$ and
   $\phi(\bar{v})$ is a quantifier-free formula. Then
   $\calm\models\phi(\bar{a})$ if and only if $\caln\models\psi(\bar{a})$
   #+END_proposition

   #+BEGIN_proof
   *Claim* If $t(\bar{v})$ is a term and $\bar{b}\in M$ then
   $t^\calm(\bar{b})=t^\caln(\bar{b})$. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that two \(\call\)-strctures $\calm$ and $\caln$ are *elementarily*
   *equivalent* and write $\calm\equiv\caln$ if
   \begin{equation*}
    \calm\models\phi\text{ if and only if } \caln\models\phi
   \end{equation*}
   for all \(\call\)-sentences \phi
   #+END_definition

   [[index:full theory]]
   We let $\Th(\calm)$, the *full theory* of $\calm$ be the set of
   \(\call\)-sentences \phi s.t. $\calm\models\phi$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm1.1.10
   Suppose that $j:\calm\to\caln$ is an isomorphism. Then $\calm\equiv\caln$
   #+END_theorem

   #+BEGIN_proof
   Show by induction on formulas that $\calm\models\phi(a_1,\dots,a_n)$ if and
   only if $\caln\models\phi(j(a_1),\dots,j(a_n))$ for all formulas \phi
   #+END_proof
** Theories
   [[index:model]]
   [[index:satisfiable]]
   Let $\call$ be a language. An *\(\call\)-theory* $T$ is a set of
   \(\call\)-sentences. We say that $\calm$ is a *model* of $T$ and write
   $\calm\models T$ if $\calm\models\phi$ for all sentences $\phi\in T$. A
   theory is *satisfiable* if it has a model.

   [[index:elementary class]]
   A class of \(\call\)-structures $\calk$ is an *elementary class* if there
   is an \(\call\)-theory $T$ s.t. $\calk=\{\calm:\calm\models T\}$
   #+ATTR_LATEX: :options [Groups]
   #+BEGIN_examplle
   Let $\call=\{\cdot,e\}$ where $\cdot$ is a binary function symbol and $e$ is a 
   constant symbol. The class of groups is axiomatized by
   \begin{align*}
   &\forall x\;e\cdot x=x\cdot e=x\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\exists y\;x\cdot y=y\cdot x= e
   \end{align*}
   #+END_examplle

   #+ATTR_LATEX: :options [Left \(R\)-modules]
   #+BEGIN_examplle
   Let $R$ be a ring with multiplicative identity 1. Let
   $\call=\{+,0\}\cup\{r:r\in R\}$ where $+$ is a binary function symbol, 0 is a
   constant, and $r$ is a unary function symbol for $r\in R$. In an
   \(R\)-module, we will interpret $r$ as scalar multiplication by $R$. The
   axioms for \(R\)-modules are
   \begin{align*}
   &\forall x\e r(x+y)=r(x)+r(y)\text{ for each }r\in R\\
   &\forall x\e (r+s)(x)=r(x)+s(x)\text{ for each }r,s\in R\\
   &\forall x\e r(s(x))=rs(x)\text{ for } r,s\in R\\
   &\forall x\e 1(x)=x
   \end{align*}
   #+END_examplle
   [[index:ACF]]
   #+ATTR_LATEX: :options [Rings and Fields]
   #+BEGIN_examplle
   Let $\call_r$ be the language of rings $\{+,-,\cdot,0,1\}$, where $+,-$ and $\cdot$
   are binary function symbols and $0$ and $1$ are constants. The axioms for rings are given 
   by
   \begin{align*}
   &\forall x\forall y\forall z\;(x-y=z\leftrightarrow x=y+z)\\
   &\forall x\;x\cdot 0=0\\
   &\forall x\forall y\forall z\;x\cdot(y\cdot z)=(x\cdot y)\cdot z\\
   &\forall x\;x\cdot 1=1\cdot x=x\\
   &\forall x\forall y\forall z\;x\cdot(y+z)=(x\cdot y)+(x\cdot z)\\
   &\forall x\forall y\forall z\;(x+y)\cdot z=(x\cdot z)+(y\cdot z)
   \end{align*}
   We axiomatize the class of fields by adding
   \begin{align*}
   &\forall x\forall y\;x\cdot y=y\cdot x\\
   &\forall x\;(x\neq 0\to\exists y\;x\cdot y=1)
   \end{align*}
   We axiomatize the class of algebraically closed fields by adding to the field axioms the sentences
   \begin{equation*}
   \forall a_0\dots\forall a_{n-1}\exists x\;x^n+\displaystyle\sum_{i=1}^{n-1}
   a_ix^i=0
   \end{equation*}
   for $n=1,2,\dots$. Let \(\ACF\) be the axioms for algebraically closed fields.

   Let $\psi_p$ be the \(\call_r\)-sentence $\forall x\;
   \underbrace{x+\dots+x}_{p\text{-times}}=0$, which asserts that a field has characteristic
   $p$. For $p>0$ a prime, let $\ACF_p=\ACF\cup\{\psi_p\}$ and
   $\ACF_0=\ACF\cup\{\neg\psi_p:p>0\}$ be the theories of algebraically
   closed fields of characteristic $p$ and zero respectively
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence. We say that
   \phi is a *logical consequence* of $T$ and write $T\models\phi$ if
   $\calm\models\phi$ whenever $\calm\models T$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   1. Let $\call=\{+,<,0\}$ and let $T$ be the theory of ordered abelian groups.
      Then $\forall x(x\neq 0\to x+x\neq 0)$ is a logical consequence of $T$
   2. Let $T$ be the theory of groups where every element has order 2. Then\par
      $T\not\models\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proposition

   #+BEGIN_proof
   2. $\Z/2\Z\models T\wedge\neg\exists x_1\exists x_2\exists x_3(x_1\neq x_2\wedge
      x_2\neq x_3\wedge x_1\neq x_3)$
   #+END_proof
** Definable Sets and Interpretability
   [[index:definable]]
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\calm=(M,\dots)$ be an \(\call\)-structure. We say that $X\subseteq M^n$
   is *definable* if and only if there is an \(\call\)-formula 
   $\phi(v_1,\dots,v_n,w_1,\dots,w_m)$ and $\bar{b}\in M^b$ s.t. 
   $X=\{\bar{a}\in M^n:\calm\models\phi(\bar{a},\bar{b})\}$. We say that
   $\phi(\bar{v},\bar{b})$ *defines* $X$. We say that $X$ is
   *\(A\)-definable* or *definable over*  $A$ if there is a formula 
   $\psi(\bar{v},w_1,\dots,w_l)$ and $\bar{b}\in A^l$ s.t.
   $\psi(\bar{v},\bar{b})$ defines $X$
   #+END_definition

   A number of examples using $\call_r$, the language of rings
   * Let $\calm=(R,+,-,\cdot,0,1)$ be a ring. Let $p(X)\in R[X]$. Then 
     $Y=\{x\in R:p(x)=0\}$ is definable. Suppose that
     $p(X)=\displaystyle\sum_{i=0}^ma_iX^i$. Let $\phi(v,w_0,\dots,w_n)$ be the
     formula
     \begin{equation*}
     w_n\cdot\underbrace{v\cdots v}_{n\text{-times}}+\dots+w_1\cdot v+w_0=0
     \end{equation*}
     Then $\phi(v,a_0,\dots,a_n)$ defines $Y$. Indeed, $Y$ is \(A\)-definable
     for any $A\supseteq\{a_0,\dots,a_n\}$
   * Let $\calm=(\R,+,-,\cdot,0,1)$ be the field of real numbers. Let
     $\phi(x,y)$ be the formula 
     \begin{equation*}
     \exists z(z\neq 0\wedge y=x+z^2)
     \end{equation*}
     Because $a<b$ if and only if $\calm\models\phi(a,b)$, the ordering is
     \(\emptyset\)-definable 
   * Consider the natural numbers $\N$ as an $\call=\{+,\cdot,0,1\}$ structure.
     There is an \(\call\)-formula $T(e,x,s)$ s.t. $\N\models T(e,x,s)$ if and
     only if the Turing machine with program coded by $e$ halts on input $x$ in
     at most $s$ steops. Thus the Turing machine with program $e$ halts on input
     $x$ if and only if

 $\N\models\exists s\;T(e,x,s)$. So the halting
     computations is definable

     
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. Suppose that $D_n$ is a collection of
   subsets of $M^n$ for all $n\ge 1$ and $\cald=(D_n:n\ge 1)$ is the smallest
   collection s.t. 
   1. $M^n\in D_n$
   2. for all \(n\)-ary function symbols $f$ of $\call$, the graph of $f^\calm$
      is in $D_{n+1}$
   3. for all \(n\)-ary relation symbols $R$ of $\call$, $R^\calm\in D_n$
   4. for all $i,j\le n$, $\{(x_1,\dots,x_n)\in M^n:x_i=x_j\}\in D_n$
   5. if $X\in D_n$, then $M\times X\in D_{n+1}$
   6. each $D_n$ is cloed under complement, union and intersection
   7. if $X\in D_{n+1}$ and $\pi:M^{n+1}\to M^n$ is the projection 
      $(x_1,\dots,x_{n+1})\mapsto(x_1,\dots,x_n)$, then $\pi(X)\in D_n$
   8. if $X\in D_{n+m}$ and $b\in M^m$, then $\{a\in M^n:(a,b)\in X\}\in D_n$
      

   Thus $X\subseteq M^n$ is definable if and only if $X\in D_n$
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let $\calm$ be an \(\call\)-structure. If $X\subset M^n$ is \(A\)-definable,
   then every \(\call\)-automorphism of $\calm$ that fixes $A$ pointwise fixes
   $X$ setwise(that is, if \sigma is an automorphism of $M$ and $\sigma(a)=a$
   for all $a\in A$, then $\sigma(X)=X$)
   #+END_proposition

   #+BEGIN_proof
   \begin{equation*}
   \calm\models\psi(\bar{v},\bar{a})\leftrightarrow
   \calm\models\psi(\sigma(\bar{v}),\sigma(\bar{a}))\leftrightarrow
   \calm\models\psi(\sigma(\bar{v}),\bar{a})
   \end{equation*}
   In other words, $\bar{b}\in X$ if and only if $\sigma(\bar{b})\in X$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
    A subset $S$ of a field $L$ is *algebraically independent* over a
    subfield $K$ if the elements of 
    $S$ do not satisfy any non-trivial polynomial equation with
    coefficients in $K$ 
   #+END_definition

   
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
    The set of real numbers is not definable in the field of complex numbers
   #+END_corollary

   #+BEGIN_proof
   If $\R$ where definable, then it would be definable over a finite
   $A\subset\C$. Let $r,s\in\C$ be algebraically independent over $A$ with
   $r\in\R$ and $s\not\in\R$. There is an automorphism \sigma of $\C$ s.t.
   $\sigma|A$ is the identity and $\sigma(r)=s$. Thus $\sigma(\R)\neq\R$ and
   $\R$ is not definable over $A$
   #+END_proof
   
   We say that an \(\call_0\)-structure $\caln$ is *definably interpreted* in
   an \(\call\)-structure $\calm$ if and only if we can find a definable
   $X\subseteq M^n$ for some $n$ and we can interpret the symbols of $\call_0$
   as definable subsets and functions on $X$ so that the resulting
   \(\call_0\)-structure is isomorphic to $\calm$


   For example, let $K$ be a field and $G$ be $\GL_2(K)$, the group of
   invertible $2\times 2$ matrices over $K$. Let $X=\{(a,b,c,d)\in K^4:ad-bc\neq
   0\}$. Let $f:X^2\to X$ by
   \begin{align*}
   f((a_1,b_1,&c_1,d_1),(a_2,b_2,c_2,d_2))=\\
   &(a_1a_2+b_1c_2,a_1b_2+b_1d_2,c_1a_2+d_1c_2,c_1b_2+d_1d_2)
   \end{align*}
   $X$ and $f$ are definable in $(K,+,\cdot)$, and the set $X$ with operation
   $f$ is isomorphic to $\GL_2(K)$, where the identity element of $X$ is
   $(1,0,0,1)$ 

   Clearly, $(\GL_n(K),\cdot,e)$ is definably interpreted in $(K,+,\cdot,0,1)$.
   A *linear algebraic group* over $K$ is a subgroup of $\GL_n(K)$ defined by
   polynomial equations over $K$. Any linear algebraic group over $K$ is
   definably interpreted in $K$

   Let $F$ be an infinite field and let $G$ be the group of matrices of the form 
   #+ATTR_LATEX: :mode math :environment pmatrix
   | a | b |
   | 0 | 1 |

   where $a,b\in F, a\neq 0$. This group is isomorphic to the group of affine
   transformations $x\mapsto ax+b$, where $a,b\in F$ and $a\neq 0$

   We will show that $F$ is definably interpreted in the group $G$. Let
   \begin{equation*}
    \alpha=\begin{pmatrix}
           1&1\\
           0&1\\
           \end{pmatrix}\text{ and }
   \beta=\begin{pmatrix}
   \tau&0\\
   0&1\\
         \end{pmatrix}
   \end{equation*}
   where $\tau\neq 0$. Let
   \begin{gather*}
   A=\{g\in G:g\alpha=\alpha g\}=\{\begin{pmatrix}
   1&x\\
   0&1\\
                                   \end{pmatrix}:x\in F\}\\
   B=\{g\in G:g\beta=\beta g\}=\{\begin{pmatrix}
   x&0\\
   0&1\\
                                   \end{pmatrix}:x\neq 0\}
   \end{gather*}
   Clearly $A,B$ are definable using parameters \alpha and \beta

   $B$ acts on $A$ by conjugation
   \begin{equation*}
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}^{-1}
   \begin{pmatrix}
   1&y\\
   0&1\\
   \end{pmatrix}
   \begin{pmatrix}
   x&0\\
   0&1\\
   \end{pmatrix}=
   \begin{pmatrix}
   1&\frac{y}{x}\\
   0&1
   \end{pmatrix}
   \end{equation*}
   We can define the map $i:A\backslash\{1\}\to B$ by $i(a)=b$ if and only if
   $b^{-1}ab=\alpha$, that is
   \begin{equation*}
   i \begin{pmatrix}
   1&x\\
   0&1
     \end{pmatrix}=
   \begin{pmatrix}
   x&0\\
   0&1
   \end{pmatrix}
   \end{equation*}
   Define an operation $*$ on $A$ by
   \begin{equation*}
   a*b=
   \begin{cases}
   i(b)a(i(b))^{-1}&\text{if } b\neq I\\
   1&\text{if } b=I
   \end{cases}
   \end{equation*}
   where $I$ is the identity matrix. Now $(F,+,\cdot,0,1)\cong (A,\cdot,*,1,\alpha)$


   Very complicated structures can often be interpreted in seemingly simpler
   ones. For example, any structure in a countable language can be interpreted
   in a graph. Let $(A,<)$ be a linear order. For each $a\in A$, $G_A$ will have
   vertices $a,x_1^a,x_2^a,x_3^a$ and contain the subgraph

   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \node[vertex,label=left:$x_2^a$] (2) at (0,0) {};
   \node[vertex,label=right:$x^a_3$] (3) at (2,0) {};
   \node[vertex,label=right:$x^a_1$] (1) at (1,-1) {};
   \node[vertex,label=right:$a$] (a) at (1,-2) {};
   \draw (2) -- (3) -- (1) -- (2);
   \draw (a) -- (1);
   \end{tikzpicture}
   \end{center}

   If $a<b$, then $G_A$ will have vertices $y_1^{a,b},y_2^{a,b},y_3^{a,b}$ and
   contain the subgraph
   
   \begin{center}
   \begin{tikzpicture}
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$y_2^{a,b}$] (2) at (2,2) {};
   \node[label=left:$y_1^{a,b}$,inner sep=0] (1) at (1,1) {};
   \node[vertex,label=right:$y_3^{a,b}$] (3) at (2,1) {};
   \node[vertex,label=left:$a$] (a) at (0,0) {};
   \node[vertex,label=right:$b$] (b) at (4,0) {};
   \draw (a) -- (2);
   \draw (1) -- (3);
   \draw (2) -- (b);
   \end{tikzpicture}
   \end{center}


   Let $V_A=A\cup\{x_1^a,x_2^a,x_3^a:a\in
   A\}\cup\{y_1^{a,b},y_2^{a,b},y_3^{a,b}:a,b\in A\text{ and }a<b\}$, and let
   $R_A$ be the smallest symmetric relation containing all edges drawn above.

   For example, if $A$ is the three-element linear order $a<b<c$, then $G_A$ is
   the graph

   \begin{center}
   \begin{tikzpicture}[scale=0.8,transform shape]
   \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
   \tikzstyle{empty}=[circle,fill=black,minimum size=1pt,inner sep=0]
   \node[vertex,label=left:$x_2^a$] (a2) at (0,0) {};
   \node[vertex,label=left:$x_2^b$] (b2) at (4,0) {};
   \node[vertex,label=left:$x_2^c$] (c2) at (8,0) {};
   \node[vertex,label=right:$x_1^c$] (c1) at (9,1) {};
   \node[vertex,label=right:$x_1^b$] (b1) at (5,1) {};
   \node[vertex,label=right:$x_1^a$] (a1) at (1,1) {};
   \node[vertex,label=right:$x_3^a$] (a3) at (2,0) {};
   \node[vertex,label=right:$x_3^b$] (b3) at (6,0) {};
   \node[vertex,label=right:$x_3^c$] (c3) at (10,0) {};
   \node[vertex,label=left:$a$] (a) at (1,2) {};
   \node[vertex,label=above:$b$] (b) at (5,2) {};
   \node[vertex,label=right:$c$] (c) at (9,2) {};
   \node[vertex,label=below:$y_1^{a,b}$] (ab1) at (2,2.5) {};
   \node[vertex,label=below:$y_1^{b,c}$] (bc1) at (6,2.5) {};
   \node[vertex,label=below:$y_3^{a,b}$] (ab3) at (3,2.5) {};
   \node[vertex,label=right:$y_2^{a,b}$] (ab2) at (3,3) {};
   \node[vertex,label=below:$y_3^{b,c}$] (bc3) at (7,2.5) {};
   \node[vertex,label=right:$y_2^{b,c}$] (bc2) at (7,3) {};
   \node[vertex,label=below:$y_3^{a,c}$] (ac3) at (5,4) {};
   \node[vertex,label=below:$y_2^{a,c}$] (ac2) at (5,6) {};
   \node[vertex,label=below:$y_1^{a,c}$] (ac1) at (3,4) {};
   \draw (a2) -- (a1) -- (a3) -- (a2);
   \draw (a1) -- (a);
   \draw (b2) -- (b1) -- (b3) -- (b2);
   \draw (b1) -- (b);
   \draw (c2) -- (c1) -- (c3) -- (c2);
   \draw (c1) -- (c);
   \draw (a) -- (ac2);
   \draw (ac2) -- (c);
   \draw (a) -- (ab2);
   \draw (ab1) -- (ab3);
   \draw (ac1) -- (ac3);
   \draw (bc1) -- (bc3);
   \draw (b) -- (bc2);
   \draw (b) -- (ab2);
   \draw (c) -- (bc2);
   \end{tikzpicture}
   \end{center}

   Let $\call=\{R\}$ where $R$ is a binary relation. Let $\phi(x,u,v,w)$ be the
   formula asserting that $x,u,v,w$ are distinct, there are edges
   $(x,u),(u,v),(v,w),(u,w)$ and these are the only edges involving $u,v,w$.
   $G_A\models\phi(a,x_1^a,x_2^a,x_3^a)$ for all $a\in A$.

   $\psi(x,y,u,v,w)$ asserts that $x,y,u,v,w$ are distinct. $(x,u),(u,v),(u,w),(v,y)$

   Define $\theta_i(z)$ as follows:
   \begin{align*}
   &\theta_0(z):=\exists u\exists v\exists w\;\phi(z,u,v,w)\\
   &\theta_1(z):=\exists x\exists v\exists w\;\phi(x,z,v,w)\\
   &\theta_2(z):=\exists u\exists u\exists w\;\phi(x,u,z,w)\\
   &\theta_3(z):=\exists x\exists y\exists v\exists w\;\psi(x,y,z,v,w)\\
   &\theta_4(z):=\exists x\exists y\exists u\exists w\;\psi(x,y,u,z,w)\\
   &\theta_5(z):=\exists x\exists y\exists u\exists v\;\psi(x,y,u,v,z)\\
   \end{align*}
   If $a,b\in A$ and $a<b$, then
   \begin{equation*}
   G_A\models\theta_0(a)\wedge\theta_1(x^a_1)\wedge\theta_2(x^a_2)\wedge
   \theta_2(x^a_3)
   \end{equation*}
   and 
   \begin{equation*}
   G_A\models\theta_3(y_1^{a,b})\wedge\theta_4(y_2^{a,b})\wedge\theta_5(
   y_3^{a,b})
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then for all vertices $x$ in $G$, there is a
   unique $i\le 5$ s.t. $G_A\models\theta_i(x)$
   #+END_lemma

   Let $T$ be the \(\call\)-theory with the following axioms
   1. $R$ is symmetric and irreflexive
   2. for all $x$, exactly one $\theta_i$ holds
   3. if $\theta_0(x)$ and $\theta_0(y)$ then $\neg R(x,y)$
   4. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)\\$ then
      $\forall u_1\forall v_1\forall w_1\neg\psi(y,x,u_1,v_1,w_1)$
   5. if $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ and 
      $\exists u\exists v\exists w\;\psi(y,z,u,v,w)$ then\par
      $\exists u\exists v\exists w\;\psi(x,z,u,v,w)$
   6. if $\theta_0(x)$ and $\theta_0(y)$, then either $x=y$ or 
      $\exists u\exists v\exists w\;\psi(x,y,u,v,w)$ or
      $\exists u\exists v\exists w\;\psi(y,x,u,v,w)$
   7. if $\phi(x,u,v,w)\wedge\phi(x,u',v',w')$, then
      $u=u',v=v',w=w'$
   8. if $\psi(x,y,u,v,w)\wedge\psi(x,y,u',v',w')$, then
      $u'=u,v=v',w=w'$


   If $(A,<)$ is a linear order, then $G_A\models T$

   Suppose $G\models T$. Let $X_G=\{x\in G:G\models\theta_0(x)\}$

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $(A,<)$ is a linear order, then $(X_{G_A},<_{G_A})\cong(A,<)$. Moreover,
   $G_{X_G}\cong G$ for all $G\models T$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call_0\)-structure $\caln$ is *interpretable* in an
   \(\call\)-structure $M$ if there is a definable $X\subseteq M^n$, a definable
   equivalence relation $E$ on $X$, and for each symbol of $\call_0$ we can find
   definable \(E\)-invariant sets on X s.t. $X/E$ with the induced structure is
   isomorphic to $\caln$
   #+END_definition
** Answers to Exercises
   #+BEGIN_exercise
   1. transform $\psi$ to CNF
   2. prenex normal form
   #+END_exercise
   #+BEGIN_exercise
   1. 
      \begin{tikzpicture}[scale=0.6]
      \tikzstyle{vertex}=[circle,fill=black,minimum size=1pt,inner sep=2pt]
      \node[vertex,label=above:$s$] (1) at (0,1) {};
      \node[vertex,label=above:$e$] (0) at (0,0) {};
      \node[vertex,label=above:$r$] (2) at (1,0) {};
      \node[vertex,label=above:$rs$] (3) at (1,1) {};
      \end{tikzpicture}
   2. enumerate $\calm$'s functions, relations and constants
   #+END_exercise
   #+BEGIN_exercise
   [fn:stack]
   Note that every \(\call\)-structure $\calm$ of size $\kappa$ is isomorphic to an
   \(\call\)-structure with domain $\kappa$. For each relation symbols, we have $2^\kappa$
   options. If the language has size $\lambda$, this is at most 
   $(2^\kappa)^\lambda=2^{\kappa\cdot\lambda}=2^{\max(\lambda,\kappa)}$
   #+END_exercise

   #+BEGIN_exercise
   \begin{align*}
   T\models\phi&\Leftrightarrow\forall \calm\;\calm\models T\to\calm\models\phi\\
   &\Leftrightarrow\forall \calm\;\calm\models T'\to\calm\models\phi\\
   &\Leftrightarrow T'\models\phi
   \end{align*}
   #+END_exercise
   #+BEGIN_exercise
   Follow the definition
   #+END_exercise

   #+BEGIN_exercise
   Since there is no model $\calm$ s.t. $\calm\models T$. It's true that 
   $T\models \phi$
   #+END_exercise

   #+BEGIN_exercise
   1. Suppose $\calm\models\phi$, then $E^\calm$ is an equivalent relation and
      each equivalence class's cardinality is 2
   2. follows from number theory
   3. cite:DBLP:journals/bsl/DurandJMM12
   #+END_exercise

   #+BEGIN_exercise
   TBD
   #+END_exercise

   #+BEGIN_exercise
   $G(f)=\{(\bar{x},\bar{y})\in M^{n+m}\mid\phi(\bar{x},\bar{y})\}$ and 
   $G(g)=\{(\bar{y},\bar{z})\in M^{m+l}\mid\psi(\bar{y},\bar{z})\}$. Hence
   $G(g\circ f)=\{(\bar{x},\bar{z})\in M^{n+l}\mid \phi(\bar{x},\bar{y})
   \wedge \psi(\bar{y},\bar{z})\}$
   #+END_exercise

   #+BEGIN_exercise
   $\phi(\bar{a},b)$ really defines a function and since 
   $\phi(\bar{a},y)\to y=b$
   #+END_exercise

* Basic Techniques
** The Compactness Theorem

   Some points of proofs
   * Proofs are finite
   * (Soundness) If \(T\vdash\phi\), then \(T\models\phi\)
   * If \(T\) is a finite set of sentences, then there is an algorithm that,
     when given a sequence of \(\call\)-formulas \sigma and an \(\call\)-sentence \phi,
     will decide whether \sigma is a proof of \phi from $T$

   [[index:recursive]]
   A language $\call$ is *recursive* if there is an algorithm that decides
   whether a sequence of symbols is an \(\call\)-formula. An \(\call\)-theory
   $T$ is *recursive* if there is an algorithm that when given an
   \(\call\)-sentence \phi as input, decides whether $\phi\in T$

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.1.1
   If \(\call\) is a recursive language and $T$ is a recursive \(\call\)-theory,
   then $\{\phi:T\vdash\phi\}$ is recursively enumerable; that is, there is an
   algorithm that when given \phi as input will halt accepting if $T\vdash\phi$
   and not halt if $T\not\vdash\phi$
   #+END_proposition
   #+BEGIN_proof
   There is $\sigma_0,\sigma_1,\dots$ a computable listing of all finite
   sequence of \(\call\)-formulas. At stage $i$, we check to see whether
   $\sigma_i$ is a proof of \psi from $T$. If it is, then halt.
   #+END_proof

   #+ATTR_LATEX: :options [Gödel's Completeness Theorem]
   #+BEGIN_theorem
   Let $T$ be an \(\call\)-theory and \phi an \(\call\)-sentence, then
   $T\models\phi$ if and only if $T\vdash \phi$
   #+END_theorem

   We say that an \(\call\)-theory $T$ is *inconsistent* if
   $T\vdash(\phi\wedge\neg\phi)$ for some sentence \phi.

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $T$ is consistent if and only if $T$ is satisfiable
   #+END_corollary

   #+BEGIN_proof
   Supose that $T$ is not satisfiable, then every model of $T$ is a model of
   $\phi\wedge\neg\phi$. Thus by the Completeness theorem
   $T\vdash(\phi\wedge\neg\phi)$ 
   #+END_proof


   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   $T$ is satisfiable if and only if every finite subset of $T$ is satisfiable
   #+END_theorem

   #+BEGIN_proof
   If $T$ is not satisfiable, then $T$ is inconsistent. Let \sigma be a proof of
   a contradiction from  $T$. Because \sigma is finite, only finitely many
   assumptions from $T$ are used in the proof. Thus there is a finite
   $T_0\subseteq T$ s.t. \sigma is a proof of a contradiction from $T_0$
   #+END_proof

*** Henkin Constructions
    [[index:finitely satisfiable]]
    A theory $T$ is *finitely satisfiable* if every finite subset of $T$ is
    satisfiable. We will show that every finitely satisfiable theory $T$ is
    satisfiable.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We say that an \(\call\)-theory $T$ has the *witness property* if whenever
    $\phi(v)$ is an \(\call\)-formula with one free variable $v$, then there is
    a constant symbol $c\in\call$ s.t. $T\vdash(\exists v\phi(v))\to\phi(c)\in T$

    An \(\call\)-theory $T$ is *maximal* if for all $\phi$ either $\phi\in T$ or
    $\neg\phi\in T$
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.6
    Suppose $T$ is a maximal and finitely satisfiable \(\call\)-theory. If
    $\Delta\subseteq T$ is finite and $\Delta\models\psi$, then $\psi\in T$
    #+END_lemma

    #+BEGIN_proof
    If $\psi\not\in T$, then $\neg\psi\in T$ but $\Delta\cup\{\psi\}$ is
    unsatisfiable 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.7
    Suppose that $T$ is a maximal and finitely satisfiable \(\call\)-theory with
    the witness property. Then $T$ has a model. In fact, if \kappa is a cardinal
    and \(\call\) has at most \kappa constant symbols, then there is
    $\calm\models T$ with $\abs{\calm}\le\kappa$
    #+END_lemma
    
    #+BEGIN_proof
    Let $\calc$ be the set of constant symbols of \(\call\). For $c,d\in\calc$,
    we say $c\sim d$ if $c=d\in T$

    *Claim 1* $\sim$ is an equivalence relation. 

    The universe of our model will be $M=\calc/\sim$. Clearly
    $\abs{M}\le\kappa$. We let $c^*$ denote the equivalence class of $c$ and
    interprete $c$ as its equivalence class, that is, $c^\calm=c^*$

    Suppose that $R$ is an \(n\)-ary relation symbol of \(\call\)

    *Claim 2* Suppose that $c_1,\dots,c_n,d_1,\dots,d_n\in\calc$ and $c_i\sim d_i$
    for $i=1,\dots,n$, then $R(\bar{c})$ if and only if $R(\bar{d})$

    By Lemma ref:lemma2.1.6, if one of \(R(\bar{c})\) and \(R(\bar{d})\) is
    in $T$, then both are in $T$

    
    \begin{equation*}
    R^\calm=\{(c_1^*,\dots,c_n^*):R(c_1,\dots,c_n)\in T\}
    \end{equation*}
    Suppose that $f$ is an \(n\)-ary function symbol of \(\call\) and
    $c_1,\dots,c_n\in\calc$. Because  $\underline{\emptyset\models\exists
    vf(c_1,\dots,c_n)=v}$, and $T$ has the witness property, then there is
    $c_{n+1}\in\calc$ s.t. $f(c_1,\dots,c_n)=c_{n+1}\in T$. As above, if
    $d_i\sim c_i$ for $i=1,\dots,n+1$, then $f(d_1,\dots,d_n)=d_{n+1}\in T$.
    Thus we get a well-defined function $f^\calm:M^n\to M$ by
    \begin{equation*}
    f^\calm(c_1^*,\dots,c_n^*)=d^*\text{ if and only if }f(c_1,\dots,c_n)=d\in T
    \end{equation*}

    *Claim 3* Suppose that $t$ is a term using free variables from
    $v_1,\dots,v_n$. If $c_1,\dots,c_n,d\in\calc$, then $t(c_1,\dots,c_n)=d\in
    T$ if and only if $t^\calm(c_1^*,\dots,c_n^*)=d^*$

    (\(\Rightarrow\)) If \(t\) is a constant symbol, then \(c=d\in T\) and
    \(c^\calm=c^*=d^*\)

    If \(t\) is the variable \(v_i\), then \(c_i=d\in T\) and 
    \(t^\calm(c_1^*,\dots,c_n^*)=c_i^*=d^*\)

    Suppose that the claim is true for \(t_1,\dots,t_m\) and \(t\) is
    \(f(t_1,\dots,t_m)\). Using the witness property and Lemma ref:lemma2.1.6,
    we can find \(d,d_1,\dots,d_n\in\calc\) s.t. \(t_i(c_1,\dots,c_n)=d_i\in T\)
    for \(i\le m\) and \(f(d_1,\dots,d_m)=d\in T\). By our induction hypothesis, 
    \(t_i^\calm(c_1^*,\dots,c_n^*)=d_i^*\) and
    \(f^\calm(d_1^*,\dots,d_m^*)=d^*\). Thus \(t^\calm(c_1^*,\dots,c_n^*)=d^*\)

    ($\Leftarrow$) Suppose $t^\calm(c_1^*,\dots,c_n^*)=d^*$. By the witness
    property, there is a $e\in\calc$ s.t. $t(c_1,\dots,c_n)=e\in T$. Using the
    $(\Rightarrow)$ direction of the proof, $t^\calm(c_1^*,\dots,c_n^*)=e^*$.
    Thus $e^*=d^*$ and $e=d\in T$


    *Claim 4* For all \(\call\)-formulas $\phi(v_1,\dots,v_n)$ and
    $c_1,\dots,c_n\in\calc$, $\calm\models\phi(\bar{c}^*)$ if and only if
    $\phi(\bar{c})\in T$

    Suppose that \(\phi\) is \(t_1=t_2\). By Lemma ref:lemma2.1.6 and the
    witness property, we can find \(d_1\) and \(d_2\) s.t. 
    \(t_1(\bar{c})=d_1,t_2(\bar{c})=d_2\in T\). By Claim 3,
    \(t_i^\calm(\bar{c}^*)=d_i^*\). Then
    \begin{align*}
    \calm\models\phi(\bar{c}^*)&\Leftrightarrow d_1^*=d_2^*\\
    &\Leftrightarrow d_1=d_2\in T\\
    &\Leftrightarrow t_1(\bar{c})=t_2(\bar{c})\in T
    \end{align*}

    Suppose that \phi is \(R(t_1,\dots,t_m)\). There are \(d_1,\dots,d_m\in\calc\)
    s.t. \(t_i(\bar{c})=d_i\in T\). Thus
    \begin{align*}
    \calm\models\phi(\bar{c}^*)&\Leftrightarrow \bar{d}^*\in R^\calm\\
    &\Leftrightarrow R(\bar{d})\in T\\
    &\Leftrightarrow\phi(\bar{c})\in T
    \end{align*}
    
    Suppose that the claim is true for \phi. If
    \(\calm\models\neg\phi(\bar{c}^*)\), then
    \(\calm\not\models\phi(\bar{c}^*)\). By the inductive hypothesis,
    \(\phi(\bar{c})\not\in T\). Thus by maximality, \(\neg\phi(\bar{c})\in T\). On
    the other hand, if \(\neg\phi(\bar{c})\in T\), then because $T$ is finitely
    satisfiable, \(\phi(\bar{c})\not\in T\). Thus, by induction,
    \(\calm\not\models\phi(\bar{c}^*)\).

    
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.8
    Let $T$ be a finitely satisfiable \(\call\)-theory. There is a language
    $\call^*\supseteq\call$ and $T^*\supseteq T$ a finitely satisfiable
    \(\call^*\)-theory s.t. any \(\call^*\)-theory extending $T^*$ has the
    witness property. We can choose $\call^*$ s.t.
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_lemma

    #+BEGIN_proof
    We first show that there is a language $\call_1\supseteq\call$ and a
    finitely satisfiable \(\call_1\)-theory $\call_1\supseteq T$ s.t. for any
    \(\call\)-formula $\phi(v)$ there is an \(\call_1\)-constant symbol $c$ s.t.
    $T_1\models(\exists v\phi(v))\to\phi(c)$. For each \(\call\)-formula
    $\phi(v)$, let $c_\phi$ be a new constant symbol and let
    $\call_1=\call\cup\{c_\phi:\phi(v)\text{ an }\call\text{-formula}\}$. For
    each \(\call\)-formula $\phi(v)$, let $\Theta_\phi$ be the
    \(\call_1\)-sentence
    $(\exists v\phi(v))\to\phi(c_\phi)$. Let
    $T_1=T\cup\{\Theta_\phi:\phi(v)\text{ an }\call\text{-formula}\}$

    *Claim* $T_1$ is finitely satisfiable

    Suppose that $\Delta$ is a finite subset of $T_1$. Then
    $\Delta=\Delta_0\cup\{\Theta_{\phi_1},\dots, \Theta_{\phi_n}\}$ where
    $\Delta_0$ is a finite subset of $T$ and there is $\calm\models\Delta_0$. We
    will make $\calm$ into an
    \(\call\cup\{c_{\phi_1},\dots,c_{\phi_n}\}\)-structure $\calm'$. If
    $\calm\models\exists v\phi(v)$, choose $a_i$ some element of $M$ s.t.
    $\calm\models\phi(a_i)$ and let $c_{\phi_i}^{\calm'}=a_i$. Otherwise, let
    $c_{\phi_i}^{\calm'}$ be any element of $\calm$. Clearly
    $\calm'\models\Theta_{\phi_i}$ for $i\le n$. Thus $T_1$ is finitely
    satisfiable.

    We now iterate the construction above to build a sequence of languages
    $\call\subseteq\call_1\subseteq\call_2\subseteq\dots$ and a sequence of
    finitely satisfiable \(\call_i\)-theories $T\subseteq T_1\subseteq
    T_2\subseteq\dots$ s.t. if $\phi(v)$ is an \(\call_i\)-formula then there is
    a constant symbol $c\in\call_{i+1}$ s.t. $T_{i+1}\models(\exists
    v\phi(v))\to\phi(c)$

    Let $\call^*=\bigcup\call_i$ and $T^*=\bigcup T_i$. 
    If \(\abs{\call_i}\) is the number of relation, function and constant
    symbols in \(\call_i\), then there are at most \(\abs{\call_i}+\aleph_0\)
    formulas in \(\call_i\).
    Thus by induction,
    $\abs{\call^*}=\abs{\call}+\aleph_0$ 
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:2.1.9
    Suppose that $T$ is a finitely satisfiable \(\call\)-theory and \phi is an
    \(\call\)-sentence, then either $T\cup\{\phi\}$ or $T\cup\{\neg\phi\}$ is
    finitely satisfiable
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:cor2.1.10
    If $T$ is a finitely satisfiable \(\call\)-theory, then there is a maximal
    finitely satisfiable \(\call\)-theory $T'\supseteq T$
    #+END_corollary
    #+BEGIN_proof
    Let $I$ be the set of all finitely satisfiable \(\call\)-theory containing
    $T$. We partially order $I$ by inclusion. If $C\subseteq I$ is a chain, let
    $T_C=\bigcup\{\Sigma:\Sigma\in C\}$. If $\Delta$ is a finite subset of
    $T_C$, then there is a $\Sigma\in C$ s.t. $\Delta\subseteq\Sigma$, so $T_C$
    is finitely satisfiable and $T_C\supseteq\Sigma$ for all $\Sigma\in C$. Thus
    every chain in $I$ has an upper bound, and we can apply Zorn's lemma to find
    a $T'\in I$ maximal w.r.t. the partial order.
    #+END_proof


    #+ATTR_LATEX: :options [strengthening of Compactness Theorem]
    #+BEGIN_theorem
    label:thm2.1.11
    If $T$ is a finitely satisfiable \(\call\)-theory and \kappa is an infinite
    cardinal with $\kappa\ge\abs{\call}$, then there is a model of $T$ of
    cardinality at most \kappa
    #+END_theorem

    #+BEGIN_proof
    By Lemma ref:lemma2.1.8, we can find \(\call^*\supseteq\call\) and 
    \(T^*\supseteq T\) a finitely satisfiable \(\call^*\)-theory s.t. any
    \(\call^*\)-theory extending \(T^*\) has the witness property and the
    cardinality of \(\call^*\) is at most \kappa. By Corollary ref:cor2.1.10, we can
    find a maximal finitely satisfiable \(\call^*\)-theory 
    \(T'\supseteq T^*\). Because \(T'\) has the witness property, Lemma
    ref:lemma2.1.7 ensures that there is \(\calm\models T\) with \(\abs{M}\le\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let $\call=\{\cdot,+,<,0,1\}$ and let $\Th(\N)$ be the full \(\call\)-theory
    of the natural numbers. There is $\calm\models\Th(\N)$ and $a\in M$ s.t. $a$
    is larger than every natural number
    #+END_proposition

    #+BEGIN_proof
    Let $\call^*=\call\cup\{c\}$ where $c$ is a new constant symbol and let
    \begin{equation*}
    T=\Th(\N)\cup\{\underbrace{1+1+\dots+1}_{n\text{-times}}<c:\text{for }n=1,2,\dots\} 
    \end{equation*}
    If $\Delta$ is a finite subset of $T$ we can make $\N$ a model of $\Delta$ by
    interpreting $c$ as a suitably large natural number. Thus $T$ is finitely
    satisfiable and there is $\calm\models T$.
    #+END_proof
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.1.14
    If $T\models\phi$, then $\Delta\models T$ for some finite $\Delta\subseteq T$
    #+END_lemma
    #+BEGIN_proof
    Suppose not. Let $\Delta\subseteq T$ be finite. Because
    $\Delta\not\models\phi$, $\Delta\cup\{\neg\phi\}$ is satisfiable. Thus
    $T\cup\{\neg\phi\}$ is finitely satisfiable and by the compactness theorem,
    $T\not\models\phi$ 
    #+END_proof


    
** Complete Theories
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An \(\call\)-theory $T$ is called *complete* if for any \(\call\)-sentence \phi
   either $T\models\phi$ or $T\models\neg\phi$
   #+END_definition

   For $\calm$ an \(\call\)-structure, then the full theory
   \begin{equation*}
   \Th(\calm)=\{\phi:\phi\text{ is an }\call\text{-sentence and }
   \calm\models\phi\}
   \end{equation*}
   is a complete theory.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.2
   Let $T$ be an \(\call\)-theory with infinite models. If \kappa is an infinite
   cardinal and $\kappa\ge\abs{\call}$, then there is a model of $T$ of
   cardinality \kappa
   #+END_proposition

   #+BEGIN_proof
   Let $\call^*=\call\cup\{c_\alpha:\alpha<\kappa\}$, where each $c_\alpha$ is
   new constant symbol, and let $T^*$ be the \(\call^*\)-theory
   $T\cup\{c_\alpha\neq c_\beta:\alpha,\beta<\kappa,\alpha\neq\beta\}$. Clearly
   if $\calm\models T^*$, then $\calm$ is a model of $T$ of cardinality at least
   \kappa.
   Thus by Theorem ref:thm2.1.11, it suffices to show that $T^*$ is finitely
   satisfiable. But if $\Delta\subseteq T^*$ is finite, then $\Delta\subseteq
   T\cup\{c_\alpha\neq c_\beta:\alpha\neq\beta,\alpha,\beta\in I\}$, where $I$
   is a finite subset of \kappa. Let $\calm$ be an infinite model of $T$. We can
   interpret the symbols $\{c_\alpha:\alpha\in I\}$ as $\abs{I}$ distinct
   elements of $M$. Because $\calm\models\Delta$, $T^*$ is finitely satisfiable.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \kappa be an infinite cardinal and let $T$ be a theory with models of
   size \kappa. We say that $T$ is *\kappa-categorical* if any two models of
   $T$ of cardinality \kappa are isomorphic.
   #+END_definition

   Let $\call=\{+,0\}$ be the language of additive groups and let $T$ be the
   \(\call\)-theory of torsion-free divisible Abelian groups. The axioms of $T$
   are the axioms for Abelian groups together with the axioms
   \begin{gather*}
   \forall x(x\neq 0\to\underbrace{x+\dots+x}_{n\text{-times}}\neq 0)\\
   \forall y\exists x\underbrace{x+\dots+x}_{n\text{-times}}=y
   \end{gather*}
   for $n=1,2,\dots$

   
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The theory of torsion-free divisible Abelian groups is \kappa-categorical for
   all $\kappa>\aleph_0$
   #+END_proposition

   #+BEGIN_proof
   We first argue that models of $T$ are essentially vector spaces over the
   field of rational numbers $\Q$. If $V$ is any vector space over $\Q$, then
   the underlying additive group $V$ is a model of $T$. 
   Check [[https://math.stackexchange.com/questions/1550900/necessary-and-sufficient-conditions-for-an-abelian-group-to-be-a-vector-space-ov/1550954][StackExchange]].
   On the other hand, if
   \(G\models T\), \(g\in G\) and \(n\in\N\) with \(g>0\), we can find 
   \(h\in G\) s.t. \(nh=g\). If \(nk=g\), then \(n(h-k)=0\). Because $G$ is
   torsion-free there is a unique \(h\in G\) s.t. \(nh=g\). We call this element 
   \(g/n\). We can view $G$ as a \(\Q\)-vector space under the action
   \(\frac{m}{n}g=m(g/n)\)

   Two \(\Q\)-vector spaces are isomorphic if and only if they have the same
   dimension. Thus the model of $T$ are determined up to isomorphism by their
   dimension. If \(G\) has dimension \lambda, then \(\abs{G}=\lambda+\aleph_0\). If \kappa
   is uncountable and $G$ has cardinality \kappa, then $G$ has dimension \kappa. Thus for
   \(\kappa>\aleph_0\) any two models of $T$ of cardinality \kappa are isomorphic
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemmamy1
   Field of uncountable cardinality \kappa has transcendence degree \kappa
   [fn:proofkappa]
   #+END_lemma

   #+BEGIN_proof
   We prove the theorem for fields with characteristic \(p=0\). 

   Since each characteristic 0 field contains a copy of \(\Q\) as its prime
   field, we can view $F$ as a field extension over \(\Q\). We will show that
   $F$ has a subset of cardinality \kappa which is algebraically independent over
   \(\Q\).

   We build the claimed subset of $F$ by transfinite induction and implicit use
   of the axiom of choice.

   Let \(S_0=\emptyset\)

   Let \(S_1\) be a singleton containing some element of $F$ which is not
   algebraic over \(\Q\). This is possible since algebraic numbers are countable

   Define \(S_{\alpha+1}\) to be \(S_\alpha\) together with an element of $F$
   which is not a root of any non-trivial polynomial with coefficients in 
   \(\Q\cup S_\alpha\) since there are only 
   \(\abs{\Q\cup S_\alpha}=\aleph_0+\abs{\alpha}<\kappa\) polynomials

   Define \(S_\beta=\displaystyle\bigcup_{\alpha<\beta}S_\alpha\)
   
   Let \(P(x_1,\dots,x_n)\) be a non-trivial polynomial with coefficients in
   \(\Q\) and elements \(a_1,\dots,a_n\) in $F$. W.L.O.G., it is assumed that
   \(a_n\) was added at an ordinal \(\alpha+1\) later than the other elements.
   Then \(P(a_1,\dots,a_{n-1},x_n)\) is a polynomial with coefficients in 
   \(\Q\cup S_\alpha\). Hence \(P(a_1,\dots,a_n)\neq0\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.2.5
   \(\ACF_p\) is \kappa-categorical for all uncountable cardinals \kappa
   #+END_proposition

   #+BEGIN_proof
   Two algebraically closed fields are isomorphic if and only if they have the
   same characteristic and transcendence degree. See
   [[file:AdvancedModernAlgebra.org::Application of Zorn's Lemma]]. By Lemma
   ref:lemmamy1, an algebraically closed field of transcendence degree \lambda has
   cardinality \(\lambda+\aleph_0\).
   #+END_proof

   #+ATTR_LATEX: :options [Vaught's Test]
   #+BEGIN_theorem
   label:thm2.2.6
   Let $T$ be a satisfiable theory with no finite models that is
   \kappa-categorical for some infinite cardinal \(\kappa\ge\abs{\call}\). Then
   $T$ is complete
   #+END_theorem

   #+BEGIN_proof
   Suppose $T$ is not complete. Then there is a sentence \phi s.t. 
   \(T\not\models\phi\) and \(T\not\models\neg\phi\). Because
   \(T\not\models\psi\) if and only if \(T\cup\{\neg\psi\}\) is satisfiable, the
   theories \(T_0=T\cup\{\phi\}\) and \(T_1=T\cup\{\neg\phi\}\) are satisfiable.
   Because $T$ has no finite models, both \(T_0\) and \(T_1\) have infinite
   models. By Proposition ref:prop2.2.2 we can find \(\calm_0\) and
   \(\calm_1\) of cardinality \kappa with \(\calm_i\models T_i\). Because \(\calm_0\)
   and \(\calm_1\) disagree about \phi, they are not elementarily equivalent, and
   hence by Theorem ref:thm1.1.10, nonisomorphic. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   We say that an \(\call\)-theory $T$ is *decidable* if there is an algorithm
   that when given an \(\call\)-sentence \phi as input decides whether \(T\models\phi\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $T$ be a recursive complete satisfiable theory in a recursive language
   \(\call\). Then $T$ is decidable
   #+END_lemma

   #+BEGIN_proof
   Because $T$ is satisfiable \(A=\{\phi:T\models\phi\}\) and
   \(B=\{\phi:T\models\neg\phi\}\) are disjoint. Because $T$ is consistent 
   \(A\cup B\) is the set of all \(\call\)-sentences. By the Completeness
   Theorem, \(A=\{\phi:T\vdash\phi\}\) and \(B=\{\phi:T\vdash\neg\phi\}\). By
   Proposition ref:prop2.1.1 $A$ and $B$ are recursively enumerable. But any
   recursively enumerable set with a recursively enumerable complement is
   recursive. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   For $p=0$ or $p$ prime, \(ACF_p\) is decidable. In particular, \(\Th(\C)\),
   the first-order theory  of the field of complex numbers, is decidable
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \phi be a sentence in the language of rings. The following are equivalent
   1. \phi is true in the complex number
   2. \phi is true in every algebraically closed field of characteristic zero
   3. \phi is true in some algebraically closed field of characteristic zero
   4. There are arbitrarily large primes $p$ s.t. \phi is true in some
      algebraically closed field of characteristic $p$
   5. There is an $m$ s.t. for all \(p>m\), \phi is true in all algebraically
      closed fields of characteristic $p$
   #+END_corollary

   #+BEGIN_proof
   By Lemma ref:2.2.5 and Vaught's Test, \(\ACF_p\) is complete.

   \((2)\to(5)\). Suppose that \(\ACF_0\models\phi\). By Lemma ref:lemma2.1.14,
   there is a finite \(\Delta\subseteq\ACF_0\) s.t. \(\Delta\models\phi\). Thus
   if we choose \(p\) large enough, then \(\ACF_p\models\Delta\).

   \((4)\to(2)\). Suppose \(\ACF_0\not\models\phi\). Because \(\ACF_0\) is
   complete, \(\ACF_0\models\neg\phi\).
   #+END_proof

** Up and Down
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If \(\calm\) and \(\caln\) are \(\call\)-structures, then an
   \(\call\)-embedding \(j:\calm\to\caln\) is called an *elementary embedding* if
   \begin{equation*}
   \calm\models\phi(a_1,\dots,a_n)\leftrightarrow\caln\models\phi(j(a_1),\dots,j(a_n))
   \end{equation*}
   for all \(\call\)-formulas \(\phi(v_1,\dots,v_n)\) and all \(a_1,\dots,a_n\in
   M\)

   If \(\calm\) is a substructure of \(\caln\), we say that it is an *elementary
   substructure* and write \(\calm\prec\caln\) if the inclusion map is elementary.
   \(\caln\) is an *elementary extension* of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \(\calm\) is an \(\call\)-structure. Let \(\call_M\) be the language where we
   add to \(\call\) constant symbols \(m\) for each element of $M$. The *atomic
   diagram* of \(\calm\) is \(\{\phi(m_1,\dots,m_n):\phi\text{ is either an atomic
   }\call\text{-formula or the negation of an atomic }\call\text{-formula and
   }\calm\models\phi(m_1,\dots.m_n)\}\).
   The *elementary diagram* of $\calm$ is 
   \begin{equation*}
   \{\phi(m_1,\dots,m_n):\calm\models\phi(m_1,\dots,m_n),\phi\text{ an 
   \(\call\)-formula}\}
   \end{equation*}

   We let \(\Diag(\calm)\) and \(\Diag_{\el}(\calm)\) denote the atomic and
   elementary diagrams of \(\calm\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.3.3
   1. Suppose that \(\caln\) is an \(\call_M\)-structure and
      \(\caln\models\Diag(\calm)\), then viewing \(\caln\) as an
      \(\call\)-structure, there is an \(\call\)-embedding of \(\calm\) into \(\caln\)
   2. If \(\caln\models\Diag_{\el}(\calm)\), then there is an elementary
      embedding of \(\calm\) into \(\caln\)
   #+END_lemma

   #+BEGIN_proof
   1. Let \(j:M\to N\) by \(j(m)=m^\caln\). If \(m_1\neq m_2\in\Diag(\calm)\);
      thus \(j(m_1)\neq j(m_2)\) so $j$ is an embedding. If \(f\) is a function
      symbols of \(\call\) and \(f^\calm(m_1,\dots,m_n)=m_{n+1}\), then
      \(f(m_1,\dots,m_n)=m_{n+1}\) is a formula in \(\Diag(\calm)\) and 
      \(f^\caln(j(m_1),\dots,j(m_n))=j(m_{n+1})\). If \(R\) is a relation symbol
      and \(\bar{m}\in R^\calm\), then \(R(m_1,\dots,m_n)\in\Diag(\calm)\) and 
      \((j(m_1),\dots,j(m_{n}))\in R^\caln\). Hence \(j\) is an
      \(\call\)-embedding
   2. $j$ is elementary.

   #+END_proof

   #+ATTR_LATEX: :options [Upward Löwenheim–Skolem Theorem]
   #+BEGIN_theorem
   Let \(\calm\) be an infinite \(\call\)-structure and \kappa be an infinite
   cardinal \(\kappa\ge\abs{\calm}+\abs{\call}\). Then, there is \(\caln\) an
   \(\call\)-structure of cardinality \kappa and \(j:\calm\to\caln\) is elementary
   #+END_theorem

   #+BEGIN_proof
   Because \(\calm\models\Diag_{\el}(\calm)\), \(\Diag_{\el}(\calm)\) is
   satisfiable. By Theorem ref:thm2.1.11, there is
   \(\caln\models\Diag_{\el}(\calm)\) of cardinality \kappa. By Lemma ref:lemma2.3.3,
   there is an elementary \(j:\calm\to\caln\)
   #+END_proof

   #+ATTR_LATEX: :options [Tarski-Vaught Test]
   #+BEGIN_proposition
   Suppose that \(\calm\) is a substructure of \(\caln\). Then \(\calm\) is an
   elementary substructure if and only if, for any formula \(\phi(v,\bar{w})\) and 
   \(\bar{a}\in M\), if there is \(b\in N\) s.t.
   \(\caln\models\phi(b,\bar{a})\), then there is \(c\in M\) s.t.
   \(\caln\models\phi(c,\bar{a})\) 
   #+END_proposition

   #+BEGIN_proof
   We need to show that for all \(\bar{a}\in M\) and all \(\call\)-formulas
   \(\psi(\bar{v})\)
   \begin{equation*}
   \calm\models\psi(\bar{a})\Leftrightarrow\caln\models\psi(\bar{a})
   \end{equation*}

   In Proposition ref:prop1.1.8, we showed that if \(\phi(\bar{v})\) is quantifier
   free then \(\calm\models\phi(\bar{a})\) if and only if \(\phi(\bar{a})\)
   #+END_proof

   We say that an \(\call\)-theory $T$ has *built-in Skolem functions* if for all
   \(\call\)-formulas \(\phi(v,w_1,\dots,w_n)\) there is a function symbol $f$ s.t.
   \(T\models\forall\bar{w}((\exists
   v\phi(v,\bar{w}))\to\phi(f(\bar{w}),\bar{w}))\). In other words, there are
   enough function symbols in the language to witness all existential statements.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(T\) be an \(\call\)-theory. There are \(\call^*\supseteq\call\) and 
   \(T^*\supseteq T\) an \(\call^*\)-theory s.t. \(T^*\) has built-in Skolem
   functions, and if \(\calm\models T\), then we can expand \(\calm\) to 
   \(\calm^*\models T^*\). We can choose \(\call^*\) s.t.
   \(\abs{\call^*}=\abs{\call}+\aleph_0\).

   We call \(T^*\) a *skolemization* of $T$
   #+END_lemma

   #+BEGIN_proof
   We build a sequence of languages
   \(\call=\call_0\subseteq\call_1\subseteq\dots\) and \(\call_i\)-theories
   \(T_i\) s.t. \(T=T_0\subseteq T_1\subseteq\dots\)

   Given \(\call_i\), let
   \(\call_{i+1}=\call\cup\{f_\phi:\phi(v,w_1,\dots,w_n)\text{ an
   }\call_i\text{-formula},n=1,2,\dots\}\), 
   where \(f_\phi\) is an \(n\)-ary function symbol. For \(\phi(v,\bar{w})\) an
   \(\call_i\)-formula, let \(\Psi_\phi\) be the sentence
   \begin{equation*}
   \forall\bar{w}((\exists v\phi(v,\bar{w}))\to\phi(f_\phi(\bar{w}),\bar{w}))
   \end{equation*}
   and let \(T_{i+1}=T_i\cup\{\Psi_\phi:\phi\text{ an
   }\call_i\text{-formula}\}\)

   *Claim* If \(\calm\models T_i\), then we can interpret the function symbols of
   \(\call_{i+1}\backslash\call_i\) so that \(\calm\models T_{i+1}\)

   Let \(c\) be some fixed element of $M$. If \(\phi(v,w_1,\dots,w_n)\) is an
   \(\call_i\)-formula, we find a function \(g:M^n\to M\) s.t. 
   \(\bar{a}\in M^n\) and \(X_{\bar{a}}=\{b\in M:\calm\models\phi(b,\bar{a})\}\)
   is nonempty, then \(g(\bar{a})\in X_{\bar{a}}\), and if
   \(X_{\bar{a}}=\emptyset\), then \(g(\bar{a})=c\). Thus if 
   \(\calm\models\exists v\phi(v,\bar{a})\), then
   \(\calm\models\phi(g(\bar{a}),\bar{a})\). If we interpret \(f_\phi\) as
   \(g\), then \(\calm\models\Psi_\phi\)

   Let \(\call^*=\bigcup\call_i\) and \(T^*=\bigcup T_i\)
   #+END_proof
* Reference
  bibliographystyle:alpha
  bibliography:/media/wu/file/stuuudy/notes/references.bib
* Index  
  \renewcommand{\indexname}{}
  printindex:nil

* Footnotes

[fn:stack]  [[https://math.stackexchange.com/questions/1170953/let-alpha-be-any-cardinal-there-are-at-most-2-alpha-cup-mathscrl][stackexchange]]
[fn:proofkappa] [[https://proofwiki.org/wiki/Field_of_Uncountable_Cardinality_K_has_Transcendence_Degree_K][proofwiki]]
