#+TITLE: Model Theory
#+AUTHOR: C. C. Chang & H. Jerome Keisler

#+EXPORT_FILE_NAME: ../latex/ModelTheory/ModelTheory.tex
#+LATEX_HEADER: \input{../preamble.tex}

* Models Constructed From Constants

** Completeness and Compactness
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(T\) be a set of sentences of \(\call\) and let \(C\) be a set of
   constant symbols of \(\call\). We say that \(C\) is a *set of witnesses* for
   \(T\) iff for every formula \varphi of \(\call\) with at most one free variable,
   say ,\(x\), there is a constant \(c\in C\) s.t.
   \begin{equation*}
   T\vdash(\exists x)\varphi \to\varphi(c)
   \end{equation*}
   We say that \(T\) *has witnesses* in \(\call\) iff \(T\) has some set \(C\) of
   witness in \(\call\)
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.1.1
   Let \(T\) be a consistent set of sentences of \(\call\). Let \(C\) be a set
   of new constant symbols of power \(\abs{C}=\norm{\call}\), and let
   \(\bbar{\call}=\call\cup C\) be the simple extension of \(\call\) formed by
   adding \(C\). Then \(T\) can be extended to a consistent set of sentences
   \(\bbar{T}\) in \(\bbar{\call}\) which has \(C\) as a set of witnesses in \(\bbar{\call}\)
   #+END_lemma

   #+BEGIN_proof
   Let \(\alpha=\norm{\call}\). For each \(\beta<\alpha\), let \(c_\beta\) be a
   constant symbol which does not occur in \(\call\) and s.t. \(\c_\beta\neq
   c_\gamma\) if \(\beta<\gamma<\alpha \). Let \(C=\{c_\beta:\beta<\alpha\}\),
   \(\bbar{\call}=\call\cup C\). Clearly \(\norm{\bbar{\call}}=\alpha\), so we
   may arrange all formulas of \(\bbar{\call}\) with at most one free variable
   in a sequence \(\varphi_\xi,\xi<\alpha\). We now define an increasing sequence
   of sets of sentences of \(\bbar{\call}\):
   \begin{equation*}
   T=T_0\subset T_1\subset\dots\subset T_\xi\subset\dots,\quad\xi<\alpha
   \end{equation*}
   and a sequence \(d_\xi,\xi<\alpha\) of constants from \(C\) s.t.
   1. each \(T_\xi\) is consistent in \(\bbar{\call}\)
   2. if \(\xi=\xi+1\), then \(T_\xi=T_\zeta\cup\{(\exists
      x_\zeta)\varphi_\zeta\to\varphi_\zeta(d_\zeta)\}\); \(\xi_\zeta\) is the
      free variable in \(\varphi_\zeta\) if it has one, otherwise \(x_\xi=v_0\)
   3.if \(\xi\) is a limit ordinal different from 0, then
   \(T_\xi=\bigcup_{\zeta<\xi}T_\zeta\)


   Let \(d_\zeta\) be the first element of \(C\) which has not yet occurred in
   \(T_\zeta\). We show that
   \begin{equation*}
   T_{\zeta+1}=T_\zeta\cup\{(\exists x_\zeta)\varphi_\zeta\to\varphi_\zeta(d_\zeta)\}
   \end{equation*}
   is consistent. If this were not the case, then
   \begin{equation*}
      T_\zeta\vdash\neg((\exists x_\zeta)\varphi_\zeta\to\varphi_\zeta(d_\zeta))
   \end{equation*}
   By propositional logic
   \begin{equation*}
   T_\zeta\vdash(\exists x_\zeta)\varphi_\zeta\wedge\neg\varphi_\zeta(d_\zeta)
   \end{equation*}
   As \(d_\zeta\) does not occur in \(T_\zeta\), we have by predicate logic
   \begin{gather*}
   T_\zeta\vdash(\forall x_\zeta)((\exists x_\zeta)\varphi_\zeta\wedge\neg\varphi_\zeta
   (x_\zeta))\\
   T_\zeta\vdash(\exists x_\zeta)\varphi_\zeta\wedge\neg(\exists x_\zeta)\varphi_\zeta
   \end{gather*}
   which contradicts the consistency of \(T_\zeta\). If \xi is a nonzero limit
   ordinal, and each member of the increasing chain \(T_\zeta,\zeta<\xi\) is
   consistent, then \(T_\xi\) is consistent.

   Now let \(\bbar{T}=\bigcup_{\xi<\alpha}T_\xi\). Suppose \varphi is a formula of
   \(\bbar{\call}\) with at most the variable \(x\) free. Then we may assume
   that \(\varphi=\varphi_xi\) and \(x=x_\xi\) for some \(\xi<\alpha\). Whence the
   sentence
   \begin{equation*}
   (\exists x_\xi)\varphi_xi\to\varphi_\xi(d_\xi)
   \end{equation*}
   belongs to \(T_{\xi+1}\) and so to \(\bbar{T}\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.1.2
   Let \(T\) be a consistent set of sentences and \(C\) be a set of witnesses
   for \(T\) in \(\call\). Then \(T\) has a model \(\fA\) s.t. every element of
   \(\fA\) is an interpretation of a constant \(c\in C\)
   #+END_lemma

   #+BEGIN_proof
   If a set of sentences \(T\) has a set \(C\) of witnesses in \(\call\), then
   \(C\) is also a set of witnesses for every extension of \(T\). Second, if an
   extension of \(T\) has a model \(\fA\), then \(fA\) is also a model of \(T\).
   So we may assume that \(T\) is maximal consistent in \(\call\)

   For two constants \(c,d\in C\), define
   \begin{equation*}
   c\sim d \quad\text{ iff }\quad
   c\equiv d\in T
   \end{equation*}
   Because \(T\) is maximal consistent, we see that \(\sim\) is an equivalence
   relation on \(C\). For each \(c\in C\), let
   \begin{equation*}
   \widetilde{c}=\{d\in C:d\sim c\}
   \end{equation*}
   be the equivalence class of \(c\). We propose to construct a model \(\fA\)
   whose set of elements \(A\) is the set of all these equivalence classes
   \(\widetilde{c}\), for \(c\in C\); so we define
   1. \(A=\{\widetilde{c}:c\in C\}\)



   2. [@2] For each \(n\)-placed relation symbol \(P\) in \(\call\), we define an
      \(n\)-placed relation \(R'\) on the set \(C\) by: for all \(c_1,\dots,c_n\in
      C\)

      \(R'(c_1,\dots, c_n)\) iff \(P(c_1,\dots,c_n)\in T\)

      By our axioms of identity, we have

      \begin{equation*}
      \vdash P(c_1,\dots,c_n)\wedge c_1\equiv d_1\wedge\dots\wedge c_n\equiv d_n\to
      P(d_1,\dots,d_n)
      \end{equation*}
      So \(\sim\) is what is called a *congruence relation*.
      \(R(\widetilde{c}_1,\dots,\widetilde{c}_n)\) iff
      \(P(c_1,\dots,c_n)\in T\)
   3. Now consider a constant symbol \(d\) of \(\call\). From predicate logic, we
     have
     \begin{equation*}
     \vdash(\exists v_0)(d\equiv v_0)
     \end{equation*}
     So \((\exists v_0)(d\equiv v_0)\in T\), and because \(T\) has witnesses,
     there is a constant \(c\in C\) s.t.
     \begin{equation*}
     (d\equiv c)\in T
     \end{equation*}

     the constant \(c\) may not be unique, but its equivalence class is unique
      because
      \begin{equation*}
      \vdash(d\equiv c\wedge d\equiv c'\to c\equiv c')
      \end{equation*}

   4.  Let \(F\) be any \(m\)-placed function symbol of \(\call\), and let
      \(c_1,\dots,c_m\in C\). We have
      \begin{equation*}
      (\exists v_0)(F(c_1,\dots,c_m)\equiv v_0)\in T
      \end{equation*}
      hence there is a constant \(c\in C\) s.t.
      \begin{equation*}
      (F(c_1,\dots ,c_m)\equiv c)\in T
      \end{equation*}
      We use our axioms of identity to obtain
      \begin{equation*}
      \vdash (F(c_1\dots c_m)\equiv c\wedge
      c_1\equiv d_1\wedge\dots\wedge c_m\equiv d_m\wedge c\equiv d)\to
      F(d_1\dots d_m)\equiv d
      \end{equation*}
      Hence we define

      \(G(\widetilde{c}_1\dots\widetilde{c}_m)\) iff
      \((F(c_1\dots c_m)\equiv c)\in T\)

      By induction
      \begin{equation*}
      \fA\models t\equiv c \quad\text{ iff }\quad
      (t\equiv c)\in T
      \end{equation*}
      Since \(C\) is a set of witness for \(T\), we have: for any terms
      \(t_1,t_2\) of \(\call\) with no free variables
      \begin{equation*}
      \fA\models t_1\equiv t_2 \quad\text{ iff }\quad
      (t_1\equiv t_2)\in T
      \end{equation*}

      for any atomic formula \(P(t_1\dots t_n)\) of \(\call\) containing no free
      variables
      \begin{equation*}
      \fA\models P(t_1\dots t_n) \quad\text{ iff }\quad
      P(t_1\dots t_n)\in T
      \end{equation*}

      Hence for any sentence \varphi of \(\call\)
      \begin{equation*}
      \fA\models\varphi \quad\text{ iff }\quad
      \varphi\in T
      \end{equation*}

      Suppose \(\varphi=(\exists x)\psi\). If \(fA\models\varphi\), then for
      some \(\widetilde{c}\in A,\fA\models\psi[\widetilde{c}]\). This means that
      \(\fA\models\psi(c)\). So \(\psi(c)\in T\) and because
      \begin{equation*}
      \vdash\psi(c)\to(\exists x)\psi
      \end{equation*}
      we have \(\varphi\in T\). On the other hand, if \(\varphi\in T\), then
      because \(T\) has witnesses, there exists a constant \(c\in C\) s.t.
      \(\psi(c)\in T\), so \(\fA\models\psi(c)\). This gives
      \(\fA\models\psi[\widetilde{c}]\) and \(\fA\models\varphi\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2.1.3
   Let \(C\) be a set of constant symbols of \(\call\), and let \(T\) be a
   set of sentences of \(\call\). If \(T\) has a model \(\fA\) s.t. every
   element of \(\fA\) is an interpretation of some constant \(c\in C\), then
   \(T\) can be extended to a consistent \(\bbar{T}\) in \(\call\) for which
   \(C\) is a set of witnesses
   #+END_lemma

   #+BEGIN_proof
   Let \(\bbar{T}\) be the sentences of \(\call\) true in \(\fA\)
   #+END_proof

   #+ATTR_LATEX: :options [Extended Completeness Theorem]
   #+BEGIN_theorem
      label:thm1.3.21 
   Let \Sigma be a set of sentences of \(\call\). Then \Sigma is consistent iff \Sigma has a model
   #+END_theorem

   #+BEGIN_proof
   Assume \Sigma is consistent.  By Lemma ref:lemma2.1.1 we consider extensions
   \(\bbar{\Sigma}\) of \Sigma and \(\bbar{\call}\) of \(\call\), so that \(\bbar{\Sigma}\) has
   witnesses in \(\bbar{\call}\). By Lemma ref:lemma2.1.2 let \(\fA\) be the
   model of \(\bbar{\Sigma}\). Let \(\fB\) be the model for \(\call\) which is the
   reduct of \(\fA\) to \(\call\).
   #+END_proof

   #+ATTR_LATEX: :options [Downward Löwenheim–Skolem Theorem]
   #+BEGIN_corollary

   Every consistent theory \(T\) in \(\call\) has a model of power at most \(\norm{\call}\)
   #+END_corollary

   #+BEGIN_proof
   Choose \(\fA\) so that every element is a constant.

   \(\abs{B}=\abs{A}\le\norm{\bbar{\call}}=\norm{\call}\)
   #+END_proof

   #+ATTR_LATEX: :options [Gödel's Completeness Theorem]
   #+BEGIN_theorem
   label:thm1.3.20
   A sentence of \(\call\) is a theorem of \(\call\) iff it is valid
   #+END_theorem

   #+BEGIN_proof
   If a sentence \sigma is not a theorem of \(\call\), then \(\{\neg\sigma\}\) is
   consistent in \(\call\). By Theorem ref:thm1.3.21, \(\{\neg\sigma\}\) will
   have a model where \sigma cannot hold. Hence \sigma is not valid
   #+END_proof

   #+ATTR_LATEX: :options [Compactness Theorem]
   #+BEGIN_theorem
   label:thm1.3.22
   A set of sentences \Sigma has a model iff every finite subset of \Sigma has a model
   #+END_theorem

   #+BEGIN_proof
   If every finite subset of \Sigma has a model, then every finite subset of \Sigma is
   consistent. So \Sigma is consistent and has a model by Theorem ref:thm1.3.21
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If a theory \(T\) has arbitrarily large finite models, then it has an
   infinite model
   #+END_corollary

   #+BEGIN_proof
   Consider the expansion \(\call'=\call\cup\{c_n:n\in\omega\}\)  where \(c_n\)
   is a list of distinct constant symbols not in \(\call\). Consider the set \Sigma
   of \(\call'\) defined by
   \begin{equation*}
   \Sigma=T\cup\{\neg(c_n\equiv c_m):n<m<\omega\}
   \end{equation*}
   Any finite subset \(\Sigma'\) of \Sigma will involve at most the constants
   \(c_0,\dots,c_m\) for some \(m\). Let \(\fA\) be  a model of \(T\) with at
   least \(m+1\) elements, and let \(a_0,\dots,a_m\) be a list of \(m+1\)
   distinct elements of \(\fA\). The model \((\fA,a_0,\dots,a_m)\) for the
   finite expansion \(\call''=\call\cup\{c_0,\dots,c_m\}\) of \(\call\) is a
   model of (\Sigma'). So by Theorem ref:thm1.3.22 \Sigma has a model.
   #+END_proof

   #+ATTR_LATEX: :options [Upward Löwenheim–Skolem-Tarski Theorem]
   #+BEGIN_corollary
   If \(T\) has infinite models, then it has infinite models of any given power \(\alpha\ge\norm{\call}\)
   #+END_corollary


   *Method of diagrams*. Let \(\fA\) be a model of \(\call\). We expand the
   language \(\call\) to a new language
   \begin{equation*}
   \call_A=\call\cup\{c_a:a\in A\}
   \end{equation*}
   by If \(a\neq b\) and \(c_a,c_b\) are different symbols, we may then expand
   \(\fA\) to the model
   \begin{equation*}
   \fA_A=(\fA,a)_{a\in A}
   \end{equation*}
   The *diagram of* \(\fA\), denote by \(\varlrtriangle_{\fA}\), is the set of all
   atomic sentences and negations of atomic sentences of \(\call_A\) which hold
   in the model \(\fA_A\)

   If \(X\) is a subset of \(A\), then we let \(\call_X=\call\cup\{c_a:a\in
   X\}\) and \(\fA_X=(\fA,a)_{a\in X}\). If \(f\) is a mapping from \(X\) into
   the set of elements \(B\) of a model \(\fB\) for \(\call\), then
   \((\fB,fa)_{a\in X}\) is the expansion of \(\fB\) to a model for \(\call_X\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop2.1.8
   Let \(\fA,\fB\) be models for \(\call\) and let \(f:A\to B\). Then the
   following are equivalent:
   1. \(f\) is an isomorphic embedding of \(\fA\) into \(\fB\)
   2. There is an extension \(\fC\supset\fA\) and an isomorphism
      \(g:\fC\cong\fB\) s.t. \(g\supset f\)
   3. \((\fB,fa)_{a\in A}\) is a model of the diagram of \(\fA\)
   #+END_proposition

   #+BEGIN_proof
   \(1\to2\). Extend the set \(A\) to a set \(C\) and extend the function \(f\)
   to a one-to-one function \(g\) from \(C\) onto \(B\). Then define the
   relations
   \begin{equation*}
   \fC\models R[c_1\dots c_n] \quad\text{ iff }\quad
   \fB\models R[gc_1\dots gc_n]
   \end{equation*}

   \(1\leftrightarrow2\). For each formula \(\varphi(x_1\dots x_n)\) and all
   \(a_1,\dots,a_n\in A\)
   \begin{equation*}
   \fA\models\varphi[a_1\dots a_n] \quad\text{ iff }\quad
   \fA_A\models\varphi(a_1\dots a_n)
   \end{equation*}
   and
   \begin{equation*}
   \fB\models\varphi[fa_1\dots fa_n] \quad\text{ iff }\quad
   (\fB,fa)_{a\in A}\models\varphi(a_1\dots a_n)
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Suppose that \(\call\) has no function or constant symbols. Let \(T\) be a
   theory in \(\call\) and \(\fA\) be a model for \(\call\). Then \(\fA\) is
   isomorphically embedded in some model of \(T\) iff every finite submodel of
   \(\fA\) is isomorphically embedded in some model of \(T\)
   #+END_corollary

   #+BEGIN_proof
   Suppose every finite submodel of \(\fA\) is isomorphically embedded in some
   model of \(T\). We show that the set \(\Sigma=T\cup\varlrtriangle_{\fA}\) is
   consistent. Every finite subset \(\Sigma'\) of \Sigma contains at most a finite
   number of the new constants, say \(c_{a_1},\dots,c_{a_m}\). Because the
   language \(\call\) has no function or constant symbols, the finite set
   \(A'=\{a_1,\dots,a_m\}\) generates a finite submodel \(\fA'\) of \(\fA\). Let
   \(\fB'\) be a model of \(T\) where \(\fA'\) is isomorphically embedded. Since
   \(\Sigma'\subset\Sigma\), by Proposition ref:prop2.1.8 \(\fB'\) can be
   extended to a model of \(\Sigma'\), and hence \(\Sigma'\) has a model. By
   campactness, \Sigma has a model \(\fB\). By Proposition ref:prop2.1.8 the reduct
   of \(\fB\) to \(\call\) gives a mode lof \(T\)
   #+END_proof

** Refinements of the method. Omitting types and interpolation theorems
   \begin{equation*}
   \fA\models\Sigma[a_1\dots a_n]
   \end{equation*}
   for every \(\sigma\in\Sigma,a_1,\dots,a_n\)satisfies \sigma in \(\fA\); in this
   case we say that \(a_1,\dots,a_n\) *satisfies*, or *realizes* \Sigma in \(\fA\).

   \(\fA\) *realizes* \Sigma iff some \(n\)-tuple of elements of \(A\) satisfies
   \Sigma in \(\fA\). \(\fA\) *omits* \Sigma iff \(\fA\) does not realize \Sigma.
   \Sigma is *satisfiable in \(\fA\)* iff \(\fA\) realizes \Sigma. \Sigma is *consistent* iff its satisfiable

   By a *type* \(\Gamma(x_1\dots x_n)\) in the variables \(x_1,\dots,x_n\) we mean a
   maximal consistent set of formulas of \(\call\) in these variables. Given any
   model \(\fA\) and \(n\)-tuple \(a_1,\dots,a_n\in A\), the set \(\Gamma(x_1\dots
   x_n)\) of all formulas \(\gamma(x_1\dots x_n)\) satisfied by \(a_1,\dots,a_n\) is
   a type and is the unique type realized by \(a_1,\dots,a_n\). It is called the
   *type of* \(a_1,\dots,a_n\) in \(\fA\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(T\) be a theory and let \(\Sigma=\Sigma(x_1\dots x_n)\). The following
   are equivalent
   1. \(T\) has a model which realizes \Sigma
   2. Every finite subset of \Sigma is realized in some model of \(T\)
   3. \(T\cup\{(\exists x_1\dots x_n)(\sigma_1\wedge\dots\wedge
      \sigma_m):m<\omega,\sigma_1,\dots,\sigma_m\in\Sigma\}\) is consistent
   #+END_proposition

   Let \(\Sigma=\Sigma(x_1\dots x_n)\) be a set of formulas of \(\call\). A
   theory \(T\) in \(\call\) is said to *locally realize* \Sigma iff there is a
   formula \(\varphi(x_1\dots x_n)\) in \(\call\) s.t.
   1. \varphi is consistent with \(T\)
   2. For all \(\sigma\in\Sigma,T\models\varphi\to\sigma\)


   That is, every \(n\)-tuple in a model of \(T\) which satisfies \varphi realizes \Sigma

   \(T\) *locally omits* \Sigma iff \(T\) does not locally realize \Sigma. Thus
   \(T\) locally omits \Sigma iff for every formula \(\varphi(x_1\dots x_n)\) which is
   consistent with \(T\), there exists \(\sigma\in\Sigma\) s.t.
   \(\varphi\wedge\neg\sigma\) is consistent with \(T\)

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(T\) be a complete theory in \(\call\), and let \(\Sigma=\Sigma(x_1\dots
   x_n)\) be a set of formulas of \(\call\). If \(T\) has a model which omits \Sigma,
   then \(T\) locally omits \Sigma
   #+END_proposition

   #+BEGIN_proof
   If \(T\) locally realizes \Sigma, then every model of \(T\) realizes \Sigma
   #+END_proof

   #+ATTR_LATEX: :options [Omitting Types Theorem]
   #+BEGIN_theorem
   Let \(T\) be a consistent theory in a countable language \(\call\), and let
   \(\Sigma(x_1\dots x_n)\) be a set of formulas. If \(T\) locally omits \Sigma, then
   \(T\) has a countable model which omits \Sigma
   #+END_theorem

   #+BEGIN_proof
   Suppose \(T\) locally omits \(\Sigma(x)\). Let \(C=\{c_0,c_1,\dots\}\) be a
   countable set of new constant symbols not already in \(\call\) and let
   \(\call'=\call\cup C\). Then \(\call'\) is countable. Arrange all the
   sentences of \(\call'\) in a list \(\varphi_0,\varphi_1,\dots\). We shall
   construct an increasing sequence of consistent theories
   \begin{equation*}
   T=T_0\subset T_0\subset\dots\subset T_m\subset\dots
   \end{equation*}
   s.t.
   1. Each \(T_m\) is a consistent theory of \(\call'\) which is a finite
      extension of \(T\)
   2. Either \(\varphi_m\in T_{m+1}\) or \((\neg\varphi_m)\in T_{m+1}\)
   3. If \(\varphi_m=(\exists x)\psi(x)\) and \(\varphi_m\in T_{m+1}\), then
      \(\psi(c_p)\in T_{m+1}\) where \(c_p\) is the first constant not occuring in
      \(T_m\) or \(\varphi_m\)
   4. There is a formula \(\sigma(x)\in\Sigma(x)\) s.t. \((\neg\sigma(c_m))\in
      T_{m+1}\)


   Assuming we already have the theory \(T_m\), we construct \(T_{m+1}\) as
   follows: Let \(T_m=T\cup\{\theta_1,\dots,\theta_r\},r>0\) and let
   \(\theta=\theta_1\wedge\dots\wedge\theta_r\) . Let \(c_0,\dots,c_n\) contain
   all the constants from \(C\) occuring in \theta. For the formula \(\theta(x_m)\) of
   \(\call\) by replacing each constant \(c_i\) by \(x_i\)(renaming bound
   variables if necessary) and prefixing by \(\exists x_i,i\not\equiv m\). Then
   \(\theta(x_m)\) is consistent with \(T\). Therefore for some \(\sigma(x)\in\Sigma(x)\),
   \(\theta(x_m)\wedge\neg\sigma(x_m)\) is consistent with \(T\). Put the sentence
   \(\neg\sigma(c_m)\) into \(T_{m+1}\). This makes (4) hold

   If \(\varphi_m\) is consistent with \(T_m\cup\{\neg\sigma(c_m)\}\), put
   \(\varphi_m\) into \(T_{m+1}\). Otherwise put \((\neg\varphi_m)\) into
   \(T_{m+1}\). This take care of (2). If \(\varphi_m=(\exists x)\psi(x)\) is
   consistent with \(T_m\cup\{\neg(\sigma(c_m))\}\), put \(\psi(c_p)\) into \(T_{m+1}\).
   This take care of (3). The theory \(T_{m+1}\) is a consistent finite
   extension of \(T_m\). Thus (1) - (4) hold for \(T_{m+1}\)

   Let \(T_\omega=\bigcup_{n<\omega}T_n\). From (1) and (2) we see that \(T_\omega\)
   is a maximal consistent theory in \(\call'\). Let
   \(\fB'=(\fB,b_0,b_1,\dots)\) be a countable model of \(T_\omega\), and let
   \(\fA'=(\fA,b_0,b_1,\dots)\) be the submodel of \(\fB'\) generated by the
   constants \(b_0,b_1,\dots\) We then see from (3) that
   \begin{equation*}
   A=\{b_0,b_1,\dots\}
   \end{equation*}
   Moreover, using (3) and the completeness of \(T_\omega\), we can show by
   induction on the complexity of a sentence \varphi in \(\call'\) that
   \begin{equation*}
   \fA'\models\varphi,\quad\fB'\models\varphi,\quad T_\omega\models\varphi
   \end{equation*}
   are all equivalent. Thus \(\fA'\) is a model of \(T_\omega\) and hence
   \(\fA\) is a model of \(T\). Finally condition (4) ensures that \(\fA\) omits \Sigma
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let \(\call\) be countable. A theory \(T\) has a (countable) model omitting
   \(\Sigma(x_1\dots x_n)\) iff some complete extension of \(T\) locally omits
   \(\Sigma(x_1\dots x_n)\)
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Consider the language \(\call=\{+,\cdot,S,0\}\). We abbreviate
   \(1=S0,2=SS0,3=SSS0,\dots\). By an *\(\omega\)-model* we mean a model \(\fA\)
   in which
   \begin{equation*}
   A=\{0,1,2,3,\dots\}
   \end{equation*}
   that is, \(\fA\) omits the set \(\{x\not\equiv0,x\not\equiv1,\dots\}\). A
   theory \(T\) in \(\call\) is said to be *\(\omega\)-consistent* iff there is no
   formula \(\varphi(x)\) of \(\call\) s.t.
   \begin{equation*}
   T\models\varphi(0),\quad T\models\varphi(1),\quad T\models\varphi(2),\dots
   \end{equation*}
   and
   \begin{equation*}
   T\models(\exists x)\neg\varphi(x)
   \end{equation*}
   \(T\) is said to be *\(\omega\)-complete* iff for every formula \(\varphi(x)\) of
   \(\call\) we have
   \begin{equation*}
   T\models\varphi(0),T\models\varphi(1),T\models\varphi(2),\dots\text{ implies }
   T\models\(\forall x\)\varphi(x)
   \end{equation*}
   #+END_examplle

   If follows from the omitting types theorem that
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(T\) be a consistent theory in \(\call\)
   1. If \(T\) is \(\omega\)-complete, then \(T\) has an \(\omega\)-model
   2. If \(T\) has an \(\omega\)-model, then \(T\) is \(\omega\)-consistent
   #+END_proposition

   #+BEGIN_proof
   1. We show that \(T\) locally omits the set
      \(\Sigma(x)=\{x\not\equiv0,x\not\equiv1,\dots\}\). Suppose \(\theta(x)\) is
      consistent with \(T\). Then \(T\models(\forall x)\neg\theta(x)\) fails. By
      \(\omega\)-completeness, there is a \(n\) s.t. not
      \(T\models\neg\theta(n)\). Hence \(\theta(n)\) is consistent with \(T\), so
      \(\theta(x)\wedge\neg x\not\equiv n\) is consistent with \(T\). Thus \(T\)
      locally omits \(\Sigma(x)\)
   #+END_proof

   The *\(\omega\)-rule* is the following infinite rule of proof: From
   \(\varphi(0),\varphi(1),\dots\) infer \((\forall x)\varphi(x)\), where \(\varphi(x)\) is any formula
   of \(\call\). *\(\omega\)-logic* is formed by adding the \(\omega\)-rule to the
   axioms and rules of inference of the first-order logic \(\call\) and allowing
   infinitely long proofs. We have the following completeness theorem for
   \(\omega\)-logic

   #+ATTR_LATEX: :options [$\omega$-Completeness Theorem]
   #+BEGIN_proposition
   A theory \(T\) in \(\call\) is consistent in \(\omega\)-logic iff \(T\) has
   an \(\omega\)-model
   #+END_proposition

   #+BEGIN_proof
   Let \(T'\) be the set of all sentences of \(\call\) provable from \(T\) in
   \(\omega\)-logic. Then \(T\) is consistent in \(\omega\)-logic iff \(T'\) is
   consistent in \(\call\). Moreover, \(T'\) is \(\omega\)-complete. Therefore
   \(T'\) has an \(\omega\)-model iff \(T'\) is consistent
   #+END_proof

   #+ATTR_LATEX: :options [Continue]
   #+BEGIN_examplle
   Let \(\call'\) be a countable language which has among its
   symbols a special unary relation symbol \(N\) and special constant symbols
   \(0,1,2,\dots\).
   By an *\(\omega\)-model* for \(\call'\) we mean a model \(\fA\) for \(\call'\)
   in which \(N\) is interpreted by the set \omega of natural numbers, and
   \(0,1,2,\dots\) are interpreted by themselves. In an \(\omega\)-model, \omega is a
   subset of the universe \(A\), but we allow \(A\) to contain elements outside
   of \omega or even to be uncountable

   Let \(T_N\) be the special set of sentences
   \begin{equation*}
   T_N=\{N(m):m<\omega\}\cup\{\neg m\equiv n:m<n<\omega\}
   \end{equation*}
   which state that the natural numbers are distinct and belong to \(N\).
   \(T_N\) holds in every \(\omega\)-model for \(\call'\). A theory \(T\) in
   \(\call'\) is said to be *\(\omega\)-consistent* iff there is no formula
   \(\varphi(x)\) of \(\call'\) s.t.
   \begin{equation*}
   T_N\cup T\models\varphi(0),T_N\cup T\models\varphi(1),
   T_N\cup T\models\varphi(2),\dots
   \end{equation*}
   and
   \begin{equation*}
   T_N\cup T\models(\exists x)(N(x)\wedge\neg\varphi(x))
   \end{equation*}
   \(T\) is said to be *\(\omega\)-complete* iff for every formula \(\varphi(x)\) of
   \(\call'\) we have
   \begin{equation*}
   T_N\cup T\models\varphi(0),T_N\cup T\models\varphi(1),T_N\cup T\models\varphi(2),\dots
   \end{equation*}
   implies
   \begin{equation*}
   T_N\cup T\models(\forall x)(N(x)\to\varphi(x))
   \end{equation*}
   The *\(\omega\)-rule* for \(\call'\) is the infinite rule: From
   \(\varphi(0),\varphi(1),\varphi(2),\dots\) infer \((\forall x)(N(x)\to\varphi(x))\). By
   *generalized \(\omega\)-logic* we mean first order logic for the language
   \(\call'\) with \(T_N\) added as an additional set of logical axioms and the
   \(\omega\)-rule added as an additional rule of proof
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Let \(T\) be a theory in \(\call'\) s.t. \(T_N\cup T\) is consistent
   1. If \(T\) is \(\omega\)-complete, then \(T\) has an \(\omega\)-model
   2. If \(T\) has an \(\omega\)-model, then \(T\) is \(\omega\)-consistent
   #+END_proposition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A theory \(T\) in \(\call'\) is consistent in generalized \(\omega\)-logic
   iff \(T\) has an \(\omega\)-model
   #+END_proposition

   #+ATTR_LATEX: :options [Extended Omitting Types Theorem]
   #+BEGIN_theorem
   Let \(T\) be a consistent theory in a countable language \(\call\), and for
   each \(r<\omega\) let \(\Sigma_r(x_1,\dots,x_{n_r})\) be a set of formulas in
   \(n_r\) variables. If \(T\) locally omits each \(\Sigma_r\), then \(T\) has a
   countable model which omits each \(\Sigma_r\)
   #+END_theorem

   Let's consider the theory ZF, Zermelo-Fraenkel set theory. A model \(\fB=\la
   B,F\ra\) of ZF is said to be an *end extension* of a model \(\fA=\la A,E\ra\)
   of ZF iff \(\fB\) is a proper extension of \(\fA\) and no member of \(A\)
   gets a new element, that is
   \begin{equation*}
   \text{if }\quad a\in A \quad\text{ and }\quad
   b\in B,\quad\text{then }\quad bFa\quad\text{implies}\quad b\in A
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Every countable model \(\fA=\la A,E\ra\) of ZF has an end elementary extension
   #+END_theorem

   #+BEGIN_proof
   Let \(\call\) be the language with the symbol \(\in\), a constant symbol
   \(\bbar{a}\) for each \(a\in A\), and a new constant symbol \(c\). Let
   \(T\) be the theory with the axioms
   \begin{gather*}
      \Th((\fA,a)_{a\in A})\\
      c\not\in\bbar{a}, \quad\text{where }a\in A
   \end{gather*}
   \(T\) is consistent because every finite subset of \(T\) has a model of the
   form \((\fA,a,c)_{a\in A}\). For each \(a\in A\), let \(\Sigma_a(x)\) be the
   set of formulas
   \begin{equation*}
   \Sigma_a(x)=\{x\in\bbar{a}\}\cup\{x\not\equiv\bbar{b}:bEa\}
   \end{equation*}
   It suffices to show that \(T\) locally omits each set \(\Sigma_a(x)\). For
   then \(T\) has a model \((\fB,a,c)_{a\in A}\) which omits each
   \(\Sigma_a(x)\). We may also assume that \(A\subset B\). \(\fB\) is an
   elementary extension of \(\fA\) because \(\Th((\fA,a)_{a\in A})\subset T\),
   whence \((\fA,a)_{a\in A}\equiv(\fB,a)_{a\in A}\). \(\fB\) is a proper
   extension because \(c\in B\setminus A\). Finally \(\fB\) is an end extension
   because it omits each \(\Sigma_a(x)\)

   A formula \(\varphi(x,c)\) of \(\call\) is consistent with \(T\) iff
   \begin{equation*}
   (\fA,a)_{a\in A}\models(\forall y)(\exists z)(\exists x)[z\not\in y\wedge\varphi(x,z)]
   \end{equation*}
   Suppose \(\varphi(x,c)\) is consistent with \(T\), but \(\varphi(x,c)\wedge\neg
   x\in\bbar{a}\) is not. Then \(\varphi(x,c)\wedge x\in\bbar{a}\) is  consistent with
   \(T\). Using the axiom of replacement in ZF, we see in turn that the
   following sentences hold in \((\fA,a)_{a\in A}\)
   \begin{gather*}
   (\forall y)(\exists z)(\exists x)[z\not\in y\wedge\varphi(x,z)\wedge x\in\bbar{a}]\\
   (\exists x)(\forall y)(\exists z)[z\not\in y\wedge\varphi(x,z)\wedge x\in\bbar{a}]
   \end{gather*}
   Then for some \(b\in A\), \(\varphi(\bbar{b},c)\wedge\bbar{b}\in\bbar{a}\) is
   consistent with \(T\), whence \(\varphi(x,c)\wedge x\equiv\bbar{b}\) is consistent
   with \(T\). Thus \(T\) locally omits \(\Sigma_a(x)\)
   #+END_proof

   The omitting types theorem is false for uncountable languages. For example,
   let \(T\) be the theory with the axioms
   \begin{equation*}
   c_\alpha\neq c_\beta,\alpha<\beta<\omega_1
   \end{equation*}
   in the language \(\call\) with constants
   \begin{equation*}
   \{c_\alpha:\alpha<\omega_1\}\cup\{d_n:n<\omega\}
   \end{equation*}
   Let \(\Gamma(x)\) be the set of formulas
   \begin{equation*}
   \Gamma(x)=\{x\not\equiv d_n:n<\omega\}
   \end{equation*}
   Then \(T\) locally omits \(\Gamma(x)\). However no model of \(T\) omits \(\Gamma(x)\)
   because every model of \(T\) is uncountable but each model which omits
   \(\Gamma(x)\) is countable

   Let \(T\) be a theory and \(\Sigma(x_1\dots x_n)\) a set of formulas in a language
   \(\call\) of power \alpha. We say that \(T\) *\(\alpha\)-realizes* \Sigma iff there
   is a set \(\Phi(x_1\dots x_n)\) of fewer than \alpha formulas of \(\call\) s.t.
   1. \Phi is consistent with \(T\)
   2. \(T\cup\Phi(x_1\dots x_n)\models\Sigma(x_1\dots x_n)\)


   that is, in any model \(\fA\) of \(T\), any \(n\)-tuple which realizes \Phi
   realizes \Sigma.
   Note that if \Sigma has power less than \alpha, then \(T\) \(\alpha\)-realizes \Sigma trivially.

   #+ATTR_LATEX: :options [$\alpha$-Omitting Types Theorem]
   #+BEGIN_theorem
   Let \(T\) be a consistent theory in a language \(\call\) of power \alpha and let
   \(\Sigma(x_1\dots x_n)\) be a set of formulas of \(\call\). If \(T\)
   \(\alpha\)-omits \Sigma, then \(T\) has a model of power \(\le\alpha\) which omits \Sigma
   #+END_theorem

   #+ATTR_LATEX: :options [Craig Interpolation Theorem]
   #+BEGIN_theorem
   Let \varphi,\psi be sentences s.t. \(\varphi\models\psi\). Then there exists a
   sentence \theta s.t.
   1. \(\varphi\models\theta\) and \(\theta\models\psi\)
   2. Every relation, function or constant symbol (excluding identity) which
      occurs in \theta also occurs in both \varphi and \psi
   #+END_theorem

   The sentence \theta will be called a *Craig interpolation* of \varphi, \psi.

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   In each of the following, \varphi and \psi are sentences s.t. the identity symbol
   occurs in at most one of them, and \(\varphi\models\psi\); however, \varphi, \psi have
   no Craig interpolation in which the identity symbol does not occur
   1. \(\varphi=(\exists x)(P(x)\wedge\neg P(x))\),\(\psi=(\exists x)Q(x)\)
   2. \(\varphi=(\exists x)Q(x)\),\(\psi=(\exists x)(P(x)\vee\neg P(x))\)
   3. \(\varphi=(\forall xy)(x\equiv y)\),\(\psi=(\forall
      xy)(P(x)\leftrightarrow P(y))\)
   #+END_examplle

   #+BEGIN_proof
   We assume that there is no Craig interpolant \theta of \varphi and \psi
   #+END_proof


* COMMENT wef
  definition

  corollary

  lemma

  proposition

  theorem
