#+TITLE: Non-standard Logics for Automated Reasoning
#+AUTHOR: Miaomiaomiao
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/Non-standardLogicForAutomatedReasoning/Belief.tex

* Belief functions
  :PROPERTIES:
  :AUTHOR:   Philippe Smets
  :END:
** Introduction
*** Possibility
    The information that "John's height is over 170cm" implies that, in
    describing John, any height $h$ over 170 is possible and any height equal to
    or below 170 is impossible. This can be represented by a possibility
    function on the height domain whose value is 0 for $h\le 170$ and 1 for
    $h>170$. *Ignorance* is due to the lack of precision of specificity of the
    information "over 170"
*** Probability
    When throwing a dice, the probability that the outcome is one is $1/6$.

    This model can be generalized by considering that the probability of each
    event is not known as a real value between 0 and 1, but as belonging to an
    interval. 
*** Credibility
    Belief functions aim to model and to quantify the subjective, personal
    credibility (called belief) induced in us by evidence. 
** The frame of discernment
*** open- and closed-world assumptions
    frame of discernment \delta (also called the Universe of discourse or the
    domain of reference) where evidence induces some belief.

    /UP/ as /unknown propositions/, /KP/ as /Known as Possible/, /KI/ as /Known as
    Impossible/.

    /closed-world assumption/ postulates an empty $UP$ set. The /open-world
    assumption/ admits the existentce of a non-empty $UP$ set.
*** Notation
    let \Omega be the boolean algebra of propositions derived from \Delta. Let 
    $\bl{1}_\Omega$ be the tautology relative to \Omega, i.e. $\bl{1}_\Omega$ is
    the disjunction of all elementary propositions of \Delta. Let
    $\bl{0}_\Omega$ be the contradiction relative to \Omega, i.e. none of the
    propositions of \Delta implies $\bl{0}_\Omega$. 

    The set $UP$ will be denoted by \Theta

    Any support given by some piece of evidence to some proposition $A$ of
    \Omega is in fact given to $A\vee \Theta$. $\bl{0}_\Omega$ is not the
    contradiction, as it corresponds to $\bl{0}_\Omega\vee\Theta$

    $A\in\Delta$ means that $A$ is an elementary proposition of \Delta

    $A\in\Omega$ means that $A$ is a proposition of \Omega
    
    for $B\in\Omega$, $A\in B$ means that $A$ is an elementary proposition
    implying $B$

    For any $A\in\Omega$, $\abs{A}$ is the number of elementary propositions
    $B\in\Delta$ s.t. $B\in A$

    $B\in\Omega$ is based on some elementary proposition $A$ of \Delta if $A\in
    B$
** Quantification of degree of belief
*** general model
    The total amount(mass) of belief is arbitrary. The non-negation mass $m(A)$
    allocated to the proposition $A\in\Omega$ that cannot be allocated to any
    proposition $A'$ s.t. $A'\to A,A'\neq A$ is called a /basic probability
    number/

    The function $m:\Omega\to[0,1]$ is called a basic probability assignment if
    \begin{equation*}
    \displaystyle\sum_{A\to\bl{1}_\Omega}m(A)=1
    \end{equation*}
    Any $A$ s.t. $m(A)>0$ is called a /focal/ proposition
*** Combination of evidence
    Dempster's rule of combination on the basic probability assignments

    $m_1(A)\times m_2(B)$ is allocated to the $A\wedge B$
    \begin{equation*}
      m_{12}(A)=\displaystyle
      \sum_{\substack{X\to\neg A\\X\to\neg A\\X\wedge Y=\bl{0}_\Omega}}
      m_1(A\vee X)m_2(A\vee Y)=
      \displaystyle\sum_{X\wedge Y=A}m_1(X)m_2(Y)
    \end{equation*}
