#+TITLE: \aunclfamily\Huge Probability Theory@@latex:\\@@ A @@latex:\\@@Comprehensive Course
#+AUTHOR: Achim Klenke
#+EXPORT_FILE_NAME: ../latex/ProbabilityTheoryAComprehensiveCourse/ProbabilityTheoryAComprehensiveCourse.tex
#+LATEX_HEADER: \input{preamble.tex}
* Basic Measure Theory
** Classes of Sets
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A class of sets $\cala$ is called
   * *\(\cap\)-closed* or a *\(\pi\)-system* if $A\cap B\in\cala$ whenever $A,B\in\cala$
   * *\(\sigma\text{-}\cap\)-closed* (closed under countable intersection)
   * *\(\cup\)-closed* (closed under unions)
   * *\(\sigma\text{-}\cup\)-closed*
   * *\textbackslash-closed*
   * closed under complements
   #+END_definition

   #+ATTR_LATEX: :options [$\sigma$-algebra]
   #+BEGIN_definition
   A class of sets $\cala\subset 2^{\Omega}$ is called a *\(\sigma\)-algebra* if it
   fullills the following three conditions
   1. $\Omega\in\cala$
   2. $\cala$ is closed under complements
   3. $\cala$ is closed under countable unions
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $\cala$ is closed under complements, then we have the equivalence
   \begin{align*}
   \cala\text{ is }\cap\text{-closed}\quad&\Longleftrightarrow\quad\cala\text{ is }
   \cup\text{-closed}\\
   \cala\text{ is }\sigma\text{-}\cap\text{-closed}\quad&\Longleftrightarrow\quad\cala\text{ is }
   \sigma\text{-}\cup\text{-closed}
   \end{align*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm1.4
   Assume that $\cala$ is \textbackslash-closed. Then the following statements hold:
   1. $\cala$ is \(\cup\)-closed
   2. If in addition $\cala$ is \(\sigma\text{-}\cup\)-closed, then $\cala$ is 
      \(\sigma\text{-}\cup\)-closed
   3. Any countable (repectively finite) union of sets in $\cala$ can be
      expressed as a countable (respectively finite) disjoint union of sets in $\cala$
   #+END_theorem

   #+BEGIN_proof
   3. [@3] Assume that $A_1,A_2,\dots\in\cala$
      \begin{equation*}
      \displaystyle\bigcup_{n=1}^\infty A_n=A_1\uplus(A_2\textbackslash
      A_1)\uplus((A_3\textbackslash
      A_2)\textbackslash A_1)\uplus\dots
      \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A class of sets $\cala\subset 2^\Omega$ is called an *algebra* if the
   following three conditions are fulfilled
   1. $\Omega\in\cala$
   2. $\cala$ is \textbackslash-closed
   3. $\cala$ is \(\cup\)-closed

   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   A class of sets $\cala\subset2^\Omega$ is an algebra if and only if the
   following  three properties hold
   1. $\Omega\in\cala$
   2. $\cala$ is closed under complements
   3. $\cala$ is closed under intersections
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A class of sets $\cala\subset2^\Omega$ is called a *ring* if the following
   conditions hold
   1. $\emptyset\in\cala$
   2. $\cala$ is \textbackslash-closed
   3. $\cala$ is \(\cup\)-closed
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A class of sets $\cala\subset2^\Omega$ is called a *semiring* if
   1. $\emptyset\in\cala$
   2. for any two sets $A,B\in\cala$ the difference set $B\textbackslash A$ is a
      finite union of mutually disjoint sets in $\cala$
   3. $\cala$ is \(\cap\)-closed
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A class of sets $\cala\subset2^\Omega$ is called a *\(\lambda\)-system* if
   1. $\Omega\in\cala$
   2. for any two sets $A,B\in\cala$ with $A\subset B$, \(B\textbackslash A\in\cala\)
   3. \(\biguplus_{n=1}^\infty A_n\in\cala\) for any choice of countably many
      pairwise disjoint sets $A_1,\dots\in\cala$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   1. Every \(\sigma\)-algebra also is a \(\lambda\)-system, an algebra and a
      \sigma-ring
   2. Every \sigma-ring is a ring, and every ring is a semiring
   3. Every algebra is a ring. An algebra on a finite set \Omega is a \sigma-algebra
   #+END_theorem

   #+ATTR_LATEX: :options [liminf and limsup]
   #+BEGIN_definition
   Let $A_1,A_2,\dots$ be a subset of \Omega. The sets
   \begin{equation*}
   \liminf_{n\to\infty}A_n:=\displaystyle\bigcup_{n=1}^\infty
   \bigcap_{m=n}^\infty A_m\hspace{1.5cm}
   \limsup_{n\to\infty}A_n:=\bigcap_{n=1}^\infty\bigcup_{m=n}^\infty
   A_m
   \end{equation*}
   are called *limes inferior* and *limes superior*, respectively, of the sequence
   \((A_n)_{n\in\N}\)
   #+END_definition

   #+BEGIN_remark
   1. lim\hspace{0.03cm}inf and lim\hspace{0.03cm}sup can be rewritten as
      \begin{align*}
      \liminf_{n\to\infty}A_n&=\{\omega\in\Omega:\#\{n\in\N:\omega\not\in A_n\}<\infty\}\\
      \limsup_{n\to\infty}A_n&=\{\omega\in\Omega:\#\{n\in\N:\omega\in A_n\}=\infty\}
      \end{align*}
      In other words, limes inferior is the event where *eventually all* of the
      $A_n$ occur. On the other hand, limes superior is the event where
      *infinitely many* of the $A_n$ occur. In particular,
      \(A_*:=\liminf_{n\to\infty}A_n\subset A^*:=\limsup_{n\to\infty}A_n\)
   2. We define the *indicator function* on the set $A$ by
      \begin{equation*}
      \mathbbm{1}_A(x):=
      \begin{cases}
      1,&x\in A\\
      0,&x\not\in A
      \end{cases}
      \end{equation*}
      With this notation 
      \begin{equation*}
      \mathbbm{1}_{A_*}=\liminf_{n\to\infty}\mathbbm{1}_{A_n}\quad\text{and}\quad
      \mathbbm{1}_{A^*}=\limsup_{n\to\infty}\mathbbm{1}_{A_n}
      \end{equation*}
   3. If $\cala\subset2^\Omega$ is a \sigma-algebra and if $A_n\in\cala$ for
      every $n\in\N$, then $A_*\in\cala$ and $A^*\in\cala$
   #+END_remark

   #+ATTR_LATEX: :options [Intersection of classes of sets]
   #+BEGIN_theorem
   Let $I$ be an arbitrary index set, and assume that $\cala_i$ is a
   \sigma-algebra for every $i\in I$. Hence the intersection
   \begin{equation*}
   \cala_I:=\{A\subset\Omega:A\in\cala_i\text{ for every }i\in I\}=
   \displaystyle\bigcap_{i\in I}\cala_i
   \end{equation*}
   is a \sigma-algebra. The analogous statement holds for rings, \sigma-rings,
   algebras and \lambda-systems. However, it fails for semirings
   #+END_theorem

   #+ATTR_LATEX: :options [Generated $\sigma$-algebra]
   #+BEGIN_theorem
   Let $\cale\subset2^\Omega$. Then there exists a smallest \sigma-algebra 
   $\sigma(\cale)$ with $\cale\subset\sigma(\cale)$
   \begin{equation*}
   \sigma(\cale):=\displaystyle\bigcap_{\substack{\cala\subset2^\Omega
   \text{ is a }\sigma\text{-algebra}\\\cala\supset\cale}}\cala
   \end{equation*}
   $\sigma(\cale)$ is called the \sigma-algebra generated by $\cale$. $\cale$ is
   called a generator of $\sigma(\cale)$. Similarly, we define $\delta(\cale)$
   as the \lambda-system generated by $\cale$
   #+END_theorem

   #+BEGIN_remark
   The following three statements hold 
   1. $\cale\subset\sigma(\cale)$
   2. If $\cale_1\subset\cale_2$, then $\sigma(\cale_1)\subset\sigma(\cale_2)$
   3. $\cala$ is a \sigma-algebra if and only if $\sigma(\cala)=\cala$
   #+END_remark

   #+ATTR_LATEX: :options [$\cap$-closed $\lambda$-system]
   #+BEGIN_theorem
   label:thm1.18
   Let $\cald\subset2^\Omega$ be a \(\lambda\)-system. Then 
   \begin{equation*}
   \cald\text{ is a }\pi\text{-system}\quad\Longleftrightarrow\quad
   \cald\text{ is a }\sigma\text{-algebra}
   \end{equation*}
   #+END_theorem

   #+BEGIN_proof
   "$\Longrightarrow$"
   3. [@3] Let $A,B\in\cald$. By assumption, $A\cap B\in\cald$ and trivially
      $A\cap B\subset A$. Thus \(A\textbackslash B=A\textbackslash(A\cap
      B)\in\cald\). This implies that $\cald$ is \textbackslash-closed. Thus by
      Theorem ref:thm1.4, works.
   #+END_proof
   

   #+ATTR_LATEX: :options [Dynkin's $\pi$-$\lambda$ theorem]
   #+BEGIN_theorem
   If $\cale\subset2^\Omega$ is a \(\pi\)-system, then
   \begin{equation*}
   \sigma(\cale)=\delta(\cale)
   \end{equation*}
   #+END_theorem

   #+BEGIN_proof
   1. $\supseteq$. \(A^c=\Omega\textbackslash A\).
   2. $\subseteq$. By Theorem ref:thm1.18, it is enough to show that
      $\delta(\cale)$ is a \(\pi\)-system. For any \(B\in\delta(\cale)\) define
      \begin{equation*}
      \cald_B:=\{A\in\delta(\cale):A\cap B\in\delta(\cale)\}
      \end{equation*}
      In order to show that \(\delta(\cale)\) is a \(\pi\) system, it is enough to
      show that 
      \begin{equation*}
      \delta(\cale)\subset\cald_B\quad\text{for any }B\in\delta(\cale)
      \end{equation*}

      \(\cald_E\) is a \(\lambda\)-system
      1. \(\Omega\cap E=E\in\delta(\cale)\). Hence \(\Omega\in\cald_E\)
      2. For any \(A,B\in\cald_E\) with $A\subset B$, we have 
         \((B\textbackslash A)\cap E=(B\cap E)\textbackslash(A\cap E)\in\delta(E)\)
      3. Assume that $A_1,\dots,\in\cald_E$ are mutually disjoint. Hence
         \begin{equation*}
         \left(\displaystyle\bigcup_{n=1}^\infty\right)\cap E=
         \biguplus_{n=1}^\infty(A_n\cap E)\in\delta(\cale)
         \end{equation*}

         
      By assumption, $A\cap E\in\cale$ if \(A,E\in\cale\); thus
      \(\cale\subset\cale_E\) if $E\in\cale$. Hence
      \(\delta(\cale)\subset\delta(\cald_E)=\cald_E\) for any $E\in\cale$. Hence we
      get that \(B\cap E\in\delta(\cale)\) for any \(B\in\delta(\cale)\) and
      \(E\in\cale\). This implies that $E\in\cale_B$ for any
      \(B\in\delta(\cale)\). Thus \(\cale\subset\cald_B\) for any
      \(B\in\delta(\cale)\). 
   
   #+END_proof

   
