#+TITLE: Proof Theory @@latex:\\@@ The First Step Into Impredicativity
#+AUTHOR: Wolfram Pohlers

#+EXPORT_FILE_NAME: ../latex/ProofTheoryTheFirstStepIntoImpredicativity/ProofTheoryTheFirstStepIntoImpredicativity.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \def \otyp {\text{otyp}}
* Primitive Recursive Functions and Relations
** Primitive Recursive Functions
** Primitive Recursive Relations
* Ordinals
** Some Basic Facts about Ordinals
   \begin{equation*}
   \alpha\in On\quad:\Leftrightarrow\quad Tran(\alpha)\wedge(\alpha,\in)\text{ is well-ordered}
   \end{equation*}
   where
   \begin{equation*}
   Tran(M)\quad:\Leftrightarrow\quad(\forall x\in M)(\forall y\in x)[y\in M]
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   \(\alpha\in On\Rightarrow Tran(\alpha)\wedge(\forall x\in\alpha)[Tran(x)]\)
   #+END_proposition

   #+BEGIN_proof
   If \(z\in y\in x\in \alpha\), then \(z\in x\) because \alpha is well-ordered by \(\in\).
   #+END_proof
   so we have
   \begin{equation*}
   \alpha\in On\wedge x\in\alpha\Rightarrow x\in On, \text{ i.e., }Tran(On)
   \end{equation*}
   and obtain
   \begin{equation*}
   \alpha\in On\Rightarrow\alpha=\{\beta\mid\beta<\alpha\}
   \end{equation*}

   We assume that an ordinal is a transitive set



   Assume the universe is well-founded w.r.t. the membership relation. This is expressed by the
   foundation schemes
   \begin{equation*}
   (\exists x)F(x)\to(\exists x)[F(x)\wedge(\forall y\in x)[\neg F(y)]]
   \end{equation*}

   \alpha is *hereditarily transitive* iff \(Tran(\alpha)\wedge(\forall x\in\alpha)[Tran(x)]\)
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Assume that the membership relation \(\in\) well-founded. Then \alpha is an ordinal iff \alpha is a
   hereditarily transitive set
   #+END_lemma

   #+BEGIN_proof
   Assume \alpha is hereditarily transitive. By the foundation scheme \(\in\) is irreflexive and
   well-founded on \alpha. Since \alpha is hereditarily transitive, it's also transitive. Assume \beta is also
   hereditarily transitive, we show

   #+BEGIN_quoting
   label:3.6
   if \beta is well-ordered by \(\in\) and \(\alpha\subseteq\beta\) then \(\alpha=\beta\vee\alpha\in\beta\)
   #+END_quoting
   Assume \(\alpha\neq\beta\) and let \xi be the \(\in\)-minimal element in \(\beta\setminus\alpha\). Then \(\xi\subseteq\alpha\). For \(\eta\in\alpha\) we
   get \(\xi\not\in\eta\) as well as \(\eta\neq\xi\) and thus \(\eta\in\xi\) because \beta is linearly ordered by \(\in\). Hence \(\alpha=\xi\in\beta\).

   Observe that the contraposition of the foundation scheme is the scheme of \(\in\)-induction
   \begin{equation*}
   (\forall x)[(\forall y\in x)F(y)\to F(x)]\to(\forall x)F(x)
   \end{equation*}
   we prove
   #+BEGIN_quoting
   If \alpha is hereditarily transitive then \alpha is linearly ordered by \(\in\)
   #+END_quoting
   by \(\in\)-induction. Let \(\xi,\eta\in\alpha\) s.t. \(\xi\neq\eta\). Then \(\gamma:=\xi\cap\eta\) is hereditarily transitive.
   If \(\gamma=\xi\neq\eta\) we get \(\xi=\gamma\in\eta\) by the induction hypothesis. If \(\gamma\neq\xi\) we get \(\gamma\in\xi\) by ref:3.6. In case
   of \(\gamma=\eta\) we are done and the remaining case \(\gamma\in\eta\) is excluded since this would
   entail \(\gamma\in\eta\cap\xi=\gamma\) which contradicts foundation.
   #+END_proof

   ref:3.6 gives
   \begin{equation*}
   \alpha\in On\wedge\beta\in On\Rightarrow(\alpha\subseteq\beta\Leftrightarrow\alpha\le\beta)
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Assume that \(\in\) is well-founded on a set \(a\). Then \(a\) is an ordinal iff \(a\) is
   hereditarily transitive
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The class \(On\) is well-ordered by \(\in\)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(M\subseteq On\) be transitive. Then \(M\in On\) or \(M=On\)
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(M\subseteq On\) be a set. Then
   \begin{equation*}
   \sup M:=\min\{\xi\in On\mid(\forall \alpha\in M)[\alpha\le\xi]\}
   \end{equation*}
   exists and
   \begin{equation*}
   \sup M=\bigcup M:=\{\xi\mid(\exists\alpha\in M)[\xi\in\alpha]\}
   \end{equation*}
   we call \(\sup M\) the *suprem um* of the set \(M\).
   #+END_lemma

   #+BEGIN_proof
   Let \(\beta:=\bigcup M\). Then \beta is hereditarily transitive subset of \(On\). Hence \(\beta\in On\). For \(\alpha\in M\)
   we have \(\alpha\subseteq\beta\), which implies \(\alpha\le\beta\) by equation ref:3.6. Hence \(\{\xi\mid(\forall \alpha\in M)[\alpha\le\xi]\}\neq\emptyset\).
   So \(\sup M\) exists and \(\sup M\le\beta\). For \(\xi<\beta\) there is an \(\eta\in M\) s.t. \(\xi<\eta\) that also
   proves \(\beta\le\sup M\).
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let
   \begin{equation*}
   \alpha':=\min\{\beta\mid\alpha<\beta\}
   \end{equation*}
   We call \(\alpha'\) the *successor* of \alpha. Also, \(\alpha'=\alpha\cup\{\alpha\}\). Let
   \begin{equation*}
   Lim:=\{\alpha\in On\mid\alpha\neq 0\wedge(\forall\beta<\alpha)[\beta'<\alpha]\}
   \end{equation*}
   denote the class of *limit ordinals* We define
   \begin{equation*}
   \omega:=\min Lim
   \end{equation*}
   and call an ordinal *finite* if it is less than \omega
   #+END_definition

   #+ATTR_LATEX: :options [Transfinite recursion on ordinals]
   #+BEGIN_theorem
   Let \(G\) be a function mapping sets to sets. Then there is a uniquely defined
   function \(F:On\to V\) s.t.
   \begin{equation*}
   F(\alpha)=G(F\restriction\alpha)
   \end{equation*}
   #+END_theorem

   We may reformulate the principle of transfinite recursion in the following form

   Let \(a\) be a set and \(S,L\) function which map sets to sets. Then there is a uniquely defined
   function \(F:On\to V\) satisfying
   \begin{align*}
   &F(0)=a\\
   &F(\alpha')=S(F(\alpha))\\
   &\lambda\in Lim\Rightarrow F(\lambda)=L(F\restriction\lambda)
   \end{align*}

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \((A,\prec)\) be a well-founded relation and \(G:V\to V\) a function. Then there is a uniquely
   determined function \(F\) satisfying
   \begin{equation*}
   (\forall x\in A)[F(x)=G(F\restriction\{y\in A\mid y\prec x\})]
   \end{equation*}
   #+END_theorem

   The field of a relation \(R\) is defined as
   \begin{equation*}
   field(R):=\{x\mid(\exists y)[(x,y)\in R\vee(y,x)\in R]\}
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For a well-founded binary relation \(\prec\) and \(s\in field(\prec)\) we define
   \begin{equation*}
   \otyp_\prec(s)=\sup\{\otyp_\prec(t)'\mid t\prec s\}
   \end{equation*}
   by transfinite recursion. It follows by induction on \(\prec\) that \(\otyp_\prec(s)\in On\)  for
   all \(s\in field(\prec)\). We call \(\otyp_\prec(s)\) the *order-type of \(s\) in \(\prec\)*. The order-type of
   the relation \(\prec\) is
   \begin{equation*}
   \otyp(\prec):=\sup\{\otyp_\prec(s)'\mid s\in field(\prec)\}
   \end{equation*}
   We define
   \begin{equation*}
   \omega_1^{CK}:=\sup\{\otyp(\prec)\mid\prec\subseteq\omega\times\omega\text{ is primitive recursive}\}
   \end{equation*}
   Also by transfinite recursion we define for a well-founded relation \(\prec\) the *Mostowski
   collapsing function*
   \begin{align*}
   &\pi_\prec:field(\prec)\to V\\
   &\pi_\prec(s):=\{\pi_\prec(t)\mid t\prec s\}
   \end{align*}
   The *Mostowski collapse* of \(\prec\)
   \begin{equation*}
   \pi_\prec[field(\prec)]:=\{\pi_\prec(s)\mid s\in field(\prec)\}
   \end{equation*}
   #+END_definition



** Fundatmentals of Ordinal Arithmetic
