#+TITLE: Real Analysis: Measure Theory, Integration, and Hilbert Spaces
#+AUTHOR: Elias M. Stein & Rami Shakarchi
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/RealAnalysis/RealAnalysis.tex
#+STARTUP: content hideblocks latexpreview

* Measure Theory
** Preliminaries
   The *norm* of $x$ is denoted by $\abs{x}$ and is defined to be the standard
   Euclidean norm given by
   \begin{equation*}
   \abs{x}=(x_1^2+\dots+x_d^2)^{1/2}
   \end{equation*}
   
   The *distance* between two points $x$ and $y$ is then simply $\abs{x-y}$

   The *distance* between two sets $E$ and $F$ is defined by
   \begin{equation*}
   d(E,F=\inf\abs{x-y})
   \end{equation*}
   where the infimum is taken over all $x\in E$ and $y\in F$

   The *open ball* in $\R^d$ centered at $x$ and of radius $r$ is defined by
   \begin{equation*}
   B_r(x)=\{y\in\R^d:\abs{y-x}<r\}
   \end{equation*}
   A subset $E\subset\R^d$ is *open* if for every $x\in E$, there exists $r>0$
   with $B_r(x)\subset E$. A set is *closed* if its complement is open.

   A set $E$ is *bounded* if it's contained in some ball of finite radius. A
   bounded set is *compact* if it's also closed. Compact sets enjoy the
   Heine-Borel covering property:
   * Assume $E$ is compact, $E\subset\bigcup_\alpha\calo_\alpha$, and each
     $\calo_\alpha$ is open. Then there are finitely many of the open sets
     $\calo_{\alpha_1},\dots,\calo_{\alpha_N}$ s.t.
     $E\subset\bigcup_{j=1}^N\calo_{\alpha_j}$ 

     
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.2
   If $R,R_1,\dots,R_N$ are rectangles, and $R\subset\bigcup_{k=1}^NR_k$, then
   \begin{equation*}
   \abs{R}\le \displaystyle\sum_{k=1}^N\abs{R_k}
   \end{equation*}
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Every open subset $\calo$ of $\R$ can be written uniquely as a countable
   union of disjoint open intervals
   #+END_theorem
   #+BEGIN_proof
   For every $x\in\calo$, let
   \begin{equation*}
   a_x=\inf\{a<x:(a,x)\subset\calo\}\quad b_x=\sup\{b>x:(x,b)\subset\calo\}
   \end{equation*}
   and $I_x=(a_x,b_x)$. Then $\calo=\bigcup_{x\in\calo}I_x$. Now suppose that
   two intervals $I_x$ and $I_y$ intersects. Then $(I_x\cup I_y)\subset I_x$ and
   $(I_x\cup I_y)\subset I_x$. This can happen only if $I_x=I_y$. Therefore any
   two disjoint intervals in the collection $\cali=\{I_x\}_{x\in\calo}$. Since
   every open interval $I_x$ contains a rational number.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm1.4
   Every open subset $\calo$ of $\R^d$, $d\ge 1$, can be written as a countable
   union of almost disjoint closed cubes.
   #+END_theorem
** The exterior measure
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $E$ is /any/ subset of $\R^d$, the *exterior measure* of $E$ is
   \begin{equation*}
   m_*(E)=\inf \displaystyle\sum_{j=1}^\infty\abs{Q_j}
   \end{equation*}
   where the infimum is taken over all countable coverings
   $E\subset\bigcup_{j=1}^\infty Q_j$ by closed cubes
.
   #+END_definition
   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The exterior measure of a point is zero. This is clear once we observe that a
   point is a cube with volume zero.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The exterior measure of a closed cube is equal to its volume. Indeed suppose
   $Q$ is a closed cube in $\R^d$. Since $Q$ covers itself, we must have
   $m_*(Q)\le\abs{Q}$. Therefore, it suffices to prove the reverse inequality.

   We consider an arbitrary covering $Q\subset\bigcup_{j=1}^\infty Q_j$ by
   cubes, and note that it suffices to prove that
   \begin{equation*}
   \abs{Q}\le \displaystyle\sum_{j=1}^\infty\abs{Q_j}
   \end{equation*}

   For a fixed $\epsilon>0$ we choose for each $j$ an open cube $S_j$ which
   contains $Q_j$ and s.t. $\abs{S_j}\le(1+\epsilon)\abs{Q_j}$. From the open
   covering $\bigcup_{j=1}^\infty S_j$ of the compact set $Q$, we may select a
   finite subcovering which, after possibly renumbering the rectangles, we may
   write as $Q\subset\bigcup_{j=1}^NS_j$. We may apply Lemma ref:lemma1.2 to
   conclude that $\abs{Q}\le\sum_{j=1}^N\abs{S_j}$. Consequently,
   \begin{equation*}
   \abs{Q}\le(1+\epsilon)\displaystyle\sum_{j=1}^N\abs{Q_j}\le(1+\epsilon)
   \displaystyle\sum_{j=1}^\infty\abs{Q_j}
   \end{equation*}
   Since \epsilon is arbitrary, the inequality holds; thus $\abs{Q}\le m_*(Q)$
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   If $Q$ is an open cube, the result $m_*(Q)=\abs{Q}$ still holds. Since $Q$ is
   covered by its closure $\overline{Q}$ and $\abs{\overline{Q}}=\abs{Q}$, we
   immediately see that $m_*(Q)\le\abs{Q}$. Note that if $Q_0$ is a closed cube
   contained in $Q$, then $m_*(Q_0)\le m_*(Q)$, since any covering of $Q$ by a
   countable number of closed cubes is also a covering of $Q_0$. Hence
   $\abs{Q_0}\le m_*(Q)$, and since we can choose $Q_0$ with a volume as close
   as we wich to $\abs{Q}$, we must have $\abs{Q}\le m_*(Q)$
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The exteriormeasure of a rectangle $R$ is equal to its volume. To obtain
   $\abs{R}\le m_*(R)$, consider a grid in $\R^d$ formed by cubes of side length
   $1/k$. Then if $\calq$ consists of the (finite) collection of all cubes entirely
   contained in $R$, and $\calq'$ the (fintie) collection of all cubes that
   intersect the complement of $R$, we first note that
   $R\subset\bigcup_{Q\in(\calq\cup\calq')}Q$. Also a simple argument yields
   \begin{equation*}
   \displaystyle\sum_{Q\in\calq}\abs{Q}\le\abs{R}
   \end{equation*}
   Moreover, there are $O(k^{d-1})$ cubes in $\calq'$ and these cubes have
   volume $k^{-d}$, so that $\sum_{Q\in\calq'}\abs{Q}=O(1/k)$. Hence
   \begin{equation*}
   \displaystyle\sum_{Q\in\calq\cup\calq'}\abs{Q}\le\abs{R}+O(1/k)
   \end{equation*}
   and letting $k$ tend to infinity yields $m_*(R)\le\abs{R}$
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The exterior measure of $\R^d$ is infinite. This follows from the fact that
   any covering of $\R^d$ is also a covering of any cube $Q\subset\R^d$ hence
   $\abs{Q}\le m_*(\R^d)$.
   #+END_examplle

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   The Cantor set $\calc$ has exterior measure 0. From the construction of
   $\calc$, we know that $\calc\subset C_k$, where each $C_k$ is a dijoint union
   of $2^k$ closed intervals, each of length $3^{-k}$. Consequently,
   $m_*(\calc)\le(2/3)^k$ for all $k$, hence $m_*(\calc)=0$
   #+END_examplle
   

   #+ATTR_LATEX: :options []
   
   #+BEGIN_proposition
   For every $\epsilon>0$, there exists a covering $E\subset\bigcup_{j=1}^\infty
   Q_j$ with
   \begin{equation*}
   \displaystyle\sum_{j=1}^\infty m_*(Q_j)\le m_*(E)+\epsilon
   \end{equation*}
   #+END_proposition

   #+ATTR_LATEX: :options [Monotonicity]
   #+BEGIN_proposition
   If $E_1\subset E_2$, then $m_*(E_1)\le m_*(E_2)$
   #+END_proposition

   #+ATTR_LATEX: :options [Countable sub-additivity]
   #+BEGIN_proposition
   label:ob2
   If $E=\bigcup_{j=1}^\infty E_j$, then $m_*(E)\le\sum_{j=1}^\infty m_*(E_j)$
   #+END_proposition
   #+BEGIN_proof
   First we may assume that each $m_*(E_j)<\infty$ for otherwise the inequality
   clearly holds. For any $\epsilon>0$ the definition of the exterior measure
   yields for each $j$ a covering $E_j\subset\bigcup_{k=1}^\infty Q_{k,j}$ by
   closed cubes with
   \begin{equation*}
   \displaystyle\sum_{k=1}^\infty\abs{Q_{k,j}}\le m_*(E_j)+\frac{\epsilon}{2^j}
   \end{equation*}
   Then, $E\subset\bigcup_{j,k=1}^\infty Q_{k,j}$ is a covering of $E$ by closed
   cubes and therefore
   \begin{align*}
   m_*(E)\le \displaystyle\sum_{j,k}\abs{Q_{k,j}}=&\displaystyle\sum_{j=1}^\infty
   \displaystyle\sum_{k=1}^\infty\abs{Q_{k,j}}\\
   &\le \displaystyle\sum_{j=1}^\infty(m_*(E_j)+\frac{\epsilon}{2^j})\\
   &=\displaystyle\sum_{j=1}^\infty m_*(E_j)+\epsilon
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:ob3
   If $E\subset\R^d$, then $m_*(E)=\inf m_*(\calo)$ where the infimum is taken
   over all open sets $\calo$ containing $E$
   #+END_proposition

   #+BEGIN_proof
   By monotonicity, it is clear that $m_*(E)\le\inf m_*(\calo)$ holds. For the
   reverse inequality, let $\epsilon>0$ and choose cubes $Q_j$ s.t.
   $E\subset\bigcup_{j=1}^\infty Q_j$ with
   \begin{equation*}
   \displaystyle\sum_{j=1}^\infty\abs{Q_j}\le m_*(E)+\frac{\epsilon}{2}
   \end{equation*}

   Let $Q_j^0$ denote an open cube containing $Q_j$, and s.t. 
   $\abs{Q_j^0}\le\abs{Q_j}+\frac{\epsilon}{2^{j+1}}$. Then 
   $\calo=\bigcup_{j=1}^\infty Q_j^0$ is open, and by Proposition ref:ob2
   \begin{align*}
   m_*(\calo)\le \displaystyle\sum_{j=1}^\infty m_*(Q_j^0)&=
   \displaystyle\sum_{j=1}^\infty\abs{Q_j^0}\\
   &\le \displaystyle\sum_{j=1}^\infty(\abs{Q_j}+\frac{\epsilon}{2^{j+1}})\\
   &\le \displaystyle\sum_{j=1}^\infty\abs{Q_j}+\frac{\epsilon}{2}\\
   &\le m_*(E)+\epsilon
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:ob4
   If $E=E_1\cup E_2$ and $d(E_1,E_2)>0$, then
   \begin{equation*}
   m_*(E)=m_*(E_1)+m_*(E_2)
   \end{equation*}
   #+END_proposition

   #+BEGIN_proof
   By Proposition ref:ob2, we already know that $m_*(E)\le m_*(E_1)+m_*(E_2)$.
   First select $d(E_1,E_2)>\delta>0$. Next we choose a covering
   $E\subset\bigcup_j=1^\infty Q_j$ by closed cubes with 
   $\sum_{j=1}^\infty\abs{Q_j}\le m_*(E)+\epsilon$. We may, after subdividing
   the cubes $Q_j$, assume that each $Q_j$ has a diameter less than \delta. In
   this case, each $Q_j$ can intersect at most one of the two sets $E_1$ or
   $E_2$. If we denote by $J_1$ and $J_2$ the sets of those indices $j$ for
   which $Q_j$ intersects $E_1$ and $E_2$, respectively, then $J_1\cap J_2$ is
   empty, and we have
   \begin{equation*}
   E_1\subset \displaystyle\bigcap_{j\in J_1}^\infty Q_j\quad
   \text{ as well as }\quad
   E_2\subset \displaystyle\bigcap_{j\in J_2}^\infty Q_j
   \end{equation*}
   Therefore, 
   \begin{align*}
   m_*(E_1)+m_*(E_2)&\le \displaystyle\sum_{j\in J_1}\abs{Q_j}+
   \displaystyle\sum_{j\in J_2}\abs{Q_j}\\
   &\le \displaystyle\sum_{j=1}^\infty\abs{Q_j}\\
   &\le m_*(E)+\epsilon
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If a set $E$ is the countable union of almost disjoint cubes
   $E=\bigcup_{j=1}^\infty Q_j$, then
   \begin{equation*}
   m_*(E)=\displaystyle\sum_{j=1}^\infty\abs{Q_j}
   \end{equation*}
   #+END_proposition

   #+BEGIN_proof
   Let $\tilde{Q}_j$ dentoe a cube strictly contained in $Q_j$ s.t.
   $\abs{Q_j}\le\abs{\tidle{Q}_j}+\epsilon/2^{j}$, where \epsilon is arbitrary
   but fixed. Then for every $N$, the cubes $\tilde{Q}_1,\dots,\tilde{Q}_N$ are
   disjoint, hence at a finite distance from one another, and repeated 
   applications of Proposition ref:ob4 imply
   \begin{equation*}
   m_*(\displaystyle\bigcup_{j=1}^N\tilde{Q}_j)=\displaystyle\sum_{j=1}^N
   \abs{\tilde{Q}_j}\ge \displaystyle\sum_{j=1}^N(\abs{Q_j}-\epsilon/2^j)
   \end{equation*}
   Since $\bigcup_{j=1}^N\tilde{Q}_j\subset E$, we conclude that for every
   integer $N$,
   \begin{equation*}
   m_*(E)\ge \displaystyle\sum_{j=1}^N\abs{Q_j}-\epsilon
   \end{equation*}
   In the limit as $N$ tends to infinity we deduce
   $\sum_{j=1}^\infty\abs{Q_j}\le m_*(E)+\epsilon$ for every $\epsilon>0$
   #+END_proof
** Measurable sets and the Lebesgue measure
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A subset $E$ of $\R^d$ is *Lebesgue measurable* or simply *measurable*, if for
   any $\epsilon>0$ there exists an open set $\calo$ with $E\subset\calo$ and
   \begin{equation*}
   m_*(\calo-E)\le\epsilon
   \end{equation*}
   
   If $E$ is measurable, we define its *Lebesgue measure* (or *measure*) $m(E)$ by
   \begin{equation*}
   m(E)=m_*(E)
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Every open set in $\R^d$ is measurable
   #+END_proposition
   #+BEGIN_proof
   $m_*(E-E)=0\le\epsilon$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   If $m_*(E)=0$, then $E$ is measurable. In particular, if $F$ is a subset of a
   set of exterior measure 0, then $F$ is measurable.
   #+END_proposition
   #+BEGIN_proof
   By proposition ref:ob3, for every $\epsilon>0$ there exists an open set
   $\calo$ with $E\subset\calo$ and $m_*(\calo)\le\epsilon$. Since
   $(\calo-E)\subset\calo$, monotonicity implies $m_*(\calo-E)\le\epsilon$
   #+END_proof

   As a consequence, the Cantor set $\calc$ is measurable.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop3
   A countable union of measurable sets is measurable
   #+END_proposition

   #+BEGIN_proof
   Suppose $E=\bigcup_{j=1}^\infty E_j$ where each $E_j$ is measurable. Given
   $\epsilon>0$, we may choose for each $j$ an open set $\calo_j$ with
   $E_j\subset\calo_j$ and $m_*(\calo_j-E_j)\le\epsilon/2^j$. Then the union 
   $\calo=\bigcup_{j=1}^\infty\calo_j$ is open, $E\subset\calo$ and 
   $\calo-E\subset\bigcup_{j=1}^\infty(\calo_j-E_j)$, so monotonicity and
   sub-additivity of the exterior measure imply
   \begin{equation*}
   m_*(\calo-E)\le \displaystyle\sum_{j=1}^\infty m_*(\calo_j-E_j)\le\epsilon
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Closed sets are measurable
   #+END_proposition
   #+BEGIN_proof
   First we observe that it suffices to prove that compact sets are measurable.
   Indeed any closed set $F$ can be written as the union of compact sets, say 
   $F=\bigcup_{k=1}^\infty F\cap B_k$, where $B_k$ denotes the closed ball of
   radius $k$ centered at the origin; then Proposition ref:prop3 applies.

   So suppose $F$ is compact (so that in particular $m_*(F)<\infty$), and let
   $\epsilon>0$. By Proposition ref:ob3 we can select an open set $\calo$ with
   $F\subset\calo$ and $m_*(\calo)\le m_*(F)+\epsilon$. Since $F$ is closed, the
   difference $\calo-F$ is open, and by Theorem ref:thm1.4 we may write this
   difference as countable union of almost disjoint cubes
   \begin{equation*}
   \calo-F=\displaystyle\bigcup_{j=1}^\infty Q_j
   \end{equation*}
   For a fixed $N$, the finite union $K=\bigcup_{j=1}^N Q_j$ is compact;
   therefore $d(K,F)>0$. Since $(K\cup F)\subset\calo$
   \begin{align*}
   m_*(\calo)&\ge m_*(F)+m_*(K)\\
   &=m_*(F)+\displaystyle\sum_{j=1}^Nm_*(Q_j)
   \end{align*}

   Hence $\sum_{j=1}^Nm_*(Q_j)\le m_*(\calo)-m_*(F)\le\epsilon$, and this also
   holds in the limit as $N$ tends to be infinite. Hence
   \begin{equation*}
   m_*(\calo-F)\le \displaystyle\sum_{j=1}^\infty m_*(Q_j)\le\epsilon
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $F$ is closed, $K$ is compact, and these sets are disjoint, then $d(F,K)>0$
   #+END_lemma
   #+BEGIN_proof
   Since $F$ is closed, for each point $x\in K$, there exists $\delta_x>0$ so
   that $d(x,F)>3\delta_x$. Since $\bigcup_{x\in K}B_{2\delta_x}(x)$ covers $K$,
   and $K$ is compact, we may find a subcover, which we denote by
   $\bigcup_{j=1}^NB_{2\delta_j}(x_j)$. If we let
   $\delta=\min(\delta_1,\dots,\delta_N)$, then we must have
   $d(K,F)\ge\delta>0$. Indeed, if $x\in K$ and $y\in F$, then for some $j$ we
   have $\abs{x_j-x}\le 2\delta_j$ and by construction
   $\abs{y-x_j}\ge3\delta_j$. Therefore
   \begin{equation*}
   \abs{y-x}\ge\abs{y-x_j}-\abs{x_j-x}\ge3\delta_j-2\delta_j\ge\delta
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   The complement of a measurable set is measurable
   #+END_proposition

   #+BEGIN_proof
   If $E$ is measurable, then for every positive integer $n$ we may choose an
   open set $\calo_n$ with $E\subset\calo_n$ and $m_*(\calo_n-E)\le1/n$. The
   complement $\calo_n^c$ is closed, hence measurable, which implies that the
   union $S=\bigcup_{n=1}^\infty\calo_n^c$ is also measurable. Now we simply
   note that $S\subset E^c$ and
   \begin{equation*}
   (E^c-S)\subset(\calo_n-E)
   \end{equation*}
   s.t. $m_*(E^c-S)\le1/n$ for all $n$. Therefore $m_*(E^c-S)=0$ and $E^c-S$ is
   measurable. Hence $E^c=S\cup(E^c-S)$ is measurable
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   A countable intersection of measurable sets is measurable
   #+END_proposition
   #+BEGIN_proof
   \begin{equation*}
   \displaystyle\bigcap_{j=1}^\infty E_j=(\displaystyle\bigcup_{j=1}^\infty E_j^c)^c
   \end{equation*}
   #+END_proof

   The operations of *uncountable* unions or intersections are not permissible
   when dealing with measurable sets.

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $E_1,\dots$ are disjoint measurable sets, and $E=\bigcup_{j=1}^\infty
   E_j$, then
   \begin{equation*}
   m(E)=\displaystyle\sum_{j=1}^\infty m(E_j)
   \end{equation*}
   #+END_theorem

