#+TITLE: Notes on Set Theory
#+AUTHOR: Qi'ao Chen

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/settheory/SetTheory.tex

* Foreword
  Notes for the entrance examination
* Models of Set - Sertraline
** Some mathematical logic
  #+ATTR_LATEX: :options [Gödel’s second incompleteness theorem]
  #+BEGIN_theorem
  If a consistent recursive axiom set $T$ contains $\zfc$, then
  \begin{equation*}
  T\not\vdash\con(t)
  \end{equation*}
  especially, $\zfc\not\vdash\con(\zfc)$
  #+END_theorem

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Suppose $(M,E_M)$ and $(N,E_N)$ are two models of set theory, then
  1. if for any formula \sigma, $M\models\sigma$ if and only if
     $N\models\sigma$, then $M$ and $N$ are \tf{elementary equivalent}, denoted
     by $M\equiv N$
  2. If bijection $f:M\to N$ satisfies: for any $a,b\in M$, $aE_Mb$ iff
     $f(a)E_Nf(b)$, then $f:M\cong N$ is an \tf{isomorphism}
  3. If $M\subseteq N$ and $E_M=E_N\restriction M$, then $M$ is $N$'s submodel
  4. If $M$ is isomorphic to a submodel of $N$ by injection $f$, and for any
     formula $\varphi(x_1,\dots,x_n)$, for any $a_1,\dots,a_n\in M$, 
     $M\models\varphi[a_1,\dots,a_n]$ iff
     $N\models\varphi[f(a_1),\dots,f(a_n)]$, then $f$ is called an
     \tf{elementary embedding} from $M$ to $N$, written as $f:M\prec N$
  5. If $M\subseteq N$ and $M\prec N$, then $M$ is a \tf{elementary submodel}
     of $N$
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  Suppose $N\models\zfc,M\subseteq N$, then $M\prec N$ iff
  $\forall\varphi(x,x_1,\dots,x_n)$, $\forall(a_1,\dots,a_n)\in M$, if 
  $\exists a\in N$ s.t. $N\models\varphi[a,a_1,\dots,a_n]$, then $\exists a\in
  M$ s.t. 
  $M\models\varphi[a,a_1,\dots,a_n]$
  #+END_lemma

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Suppose $(M,E)\models\zfc$
  1. $h_\varphi:M^n\to M$ is \varphi's \tf{Skolem function} if 
     $\forall a_1,\dots,a_n\in M$, if $\exists a\in M$ s.t.
     $M\models\varphi[a,a_1,\dots,a_n]$, then
     $M\models\varphi[h_\varphi(a_1,\dots,a_n),a_1,\dots,a_n]$ . requires \ac
  2. Let $\calh=\{h_\varphi\mid\varphi \text{is a formula on set theory}\}$. For
     any $S\subseteq M$, \tf{Skolem hull} $\calh(S)$ is the smallest set
     consisting of $S$ and closed under $\calh$
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  $N\models\zfc,S\subseteq N$, if $M=\calh(S)$, then $M\prec N$
  #+END_lemma

  #+ATTR_LATEX: :options [Löwenheim-Skolem theorem]
  #+BEGIN_theorem
  Suppose $N\models\zfc$ and is infinite, then there is a model $M$ s.t.
  $\abs{M}=\omega$ and $M\prec N$
  #+END_theorem
** Cumulative Hierarchy
   This section works in \zfm(a.k.a. $\zf-\text{axiom of foundation}$)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any \alpha, define sequence $V_\alpha$
   1. $V_0=\emptyset$
   2. $V_{\alpha+1}=\calp(V_\alpha)$
   3. For any limit ordinal \lambda, $V_\lambda=\bigcup_{\beta<\lambda}V_\beta$

      
   And $\wf=\displaystyle\bigcup_{\alpha\in\on}V_\alpha$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $V_\alpha$ is transitive
   2. if $\xi\le\alpha$, then $V_\xi\subseteq V_\alpha$
   3. if \kappa is inaccessible cardinal, then $\abs{V_\kappa}=\kappa$
   #+END_lemma

   #+BEGIN_proof
   3. Obviously $\kappa\le V_\kappa$. Since \kappa is inaccessible, then for any
      $\alpha<\kappa$, $\abs{V_\alpha}<\kappa$.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any set $x\in\wf$, 
   \begin{equation*}
   \rank(x)=\min\{\beta\mid x\in V_{\beta+1}\}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $V_\alpha=\{x\in\wf\mid\rank(x)<\alpha\}$
   2. \wf is transitive
   3. For any $x,y\in\wf$, if $x\in y$, then $\rank(x)<\rank(y)$
   4. for any $y\in\wf$, $\rank(y)=\sup\{\rank(x)+1\mid x\in y\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Supoose \alpha is an ordinal
   1. $\alpha\in\wf$ and $\rank(\alpha)=\alpha$
   2. $V_\alpha\cap\on=\alpha$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. If $x\in\wf$, then $\bigcup x,\calp(x),\{x\}\in\wf$, and their ranks are
      all less than $\rank(x)+\omega$
   2. If $x,y\in\wf$, then $x\times y,x\cup y,x\cap y,\{x,y\},(x,y),x^y\in\wf$,
      and their ranks are all less than $\rank(x)+\rank(y)+\omega$
   3. $\Z,\Q,\R\in V_{\omega+\omega}$
   4. for any set $x$, $x\in\wf$ iff $x\subset\wf$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose \ac
   1. for any group $G$, there exists group $G'\cong G$ in \wf
   2. for any topological space $T$, there exists $T'\cong T$ in \wf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Binary relation $<$ on set $A$ is \tf{well-founded} if for any nonempty
   $X\subseteq A$, $X$ has minimal element under $<$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $A\in\wf$, then $\in$ is a well-founded relation on $A$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If set $A$ is transitive and $\in$ is well-founded on $A$, then $A\in\wf$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any set $x$, there is a smallest transitive set $\trcl{x}$ s.t.
   $x\subseteq\trcl{x}$ 
   #+END_lemma

   #+BEGIN_proof
   \begin{align*}
   x_0&=x\\
   x_{n+1}&=\bigcup x_n\\
   \trcl{x}&=\displaystyle\bigcup_{n<\omega}x_n
   \end{align*}
   #+END_proof

   $\trcl{x}$ is called \tf{transitive closure} of $x$


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Without axiom of power set
   1. if $x$ is transitive, then $\trcl{x}=x$
   2. if $y\in x$, then $\trcl{y}\subseteq\trcl{x}$
   3. $\trcl{x}=x\cup\bigcup\{\trcl{y}\mid y\in x\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any set $X$, the following are equivalent
   1. $X\in\wf$
   2. $\trcl{X}\in\wf$
   3. $\in$ is a well-founded relation on $\trcl{X}$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following propositions are equivalent
   1. Axiom of foundation
   2. For any set $X$, $\in$ is a well-founded relation on $X$
   3. $\tf{V}=\wf$
   #+END_theorem
** Relativization
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \tf{M} be a class \varphi a formula, the \tf{relativization} of \varphi
   to \tf{M} is $\varphi^{\tf{M}}$ defined inductively
   \begin{align*}
   (x\in y)^{\cm}&\leftrightarrow x=y\\
   (x\in y)^{\cm}&\leftrightarrow x\in y\\
   (\varphi\to\psi)^{\cm}&\leftrightarrow \varphi^{\cm}\to\psi^\cm\\
   (\neg\varphi)^\cm&\leftrightarrow\neg\varphi^\cm\\
   (\forall x\varphi)^\cm&\leftrightarrow(\forall x\in\cm)\varphi^\cm
   \end{align*}
   #+END_definition

   Note $\varphi^\cv=\varphi$ and
   \begin{equation*}
   f^\cm=\{(x_1,\dots,x_n,x_{n+1})\in\cm\mid\varphi^\cm(x_1,\dots,x_n,x_{n+1})\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any theory $T$, any class $\cm$, $\cm\models T$ iff for any axiom
   $\varphi$ of $T$, $\varphi^\cm$ holds
   #+END_definition


   #+ATTR_LATEX: :options [\zfm]
   #+BEGIN_theorem
   $\wf\models\zf$
   #+END_theorem

   #+BEGIN_proof
   * \tf{Axiom of existence}

     $(\exists x(x=x))^\cm\leftrightarrow\exists x\in\cm(x=x)$, which is
     equivalent to \cm being nonempty
   * \tf{Axiom of extensionality}

     \begin{gather*}
     \forall X\forall Y\forall u((u\in X\leftrightarrow u\in Y)\to X=Y)^\cm
     \Leftrightarrow\\
     \forall X\in\cm\forall Y\in\cm\forall u\in\cm
     ((u\in X\leftrightarrow u\in Y)\to X=Y)
     \end{gather*}

     \begin{lemma}
     If $\cm$ is transitive, then axiom of extensionality holds in \cm
     \end{lemma}

   * \tf{Axiom schema of specification}

     \begin{equation*}
     \forall X\in\cm\exists Y\in\cm\forall u\in\cm(u\in Y\leftrightarrow
     u\in X\wedge\varphi^\cm(u))
     \end{equation*}

     Since for any $X\in\wf$, $\calp(X)\subseteq \wf$
   * \tf{Axiom of paring}
   * \tf{Axiom of union}
   * \tf{Axiom of power set}

     \begin{equation*}
     \forall X\in\cm\exists Y\in\cm\forall u\in\cm(u\in Y\leftrightarrow(u\subseteq X)^\cm)
     \end{equation*}
     and 
     \begin{equation*}
     (u\subseteq X)^\cm\leftrightarrow\forall x\in\cm(x\in u\to x\in X)
     \leftrightarrow u\cap\cm\subseteq X
     \end{equation*}
   * \tf{Axiom of foundation}
   * \tf{Axiom schema of replacement}
   #+END_proof 
** Absoluteness
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any formula $\psi(x_1,\dots,x_n)$ and any class \cm,\cn, 
   $\cm\subseteq \cn$, if
   \begin{equation*}
   \forall x_1\dots\forall x_n\in\cm(\psi^\cm(x_1,\dots,x_n)
   \leftrightarrow\psi^\cn(x_1,\dots,x_n))
   \end{equation*}
   then $\psi(x_1,\dots,x_n)$ is \tf{absolute} for \cm,cn. If $\cn=\cv$, then
   \psi is \tf{absolute} for \cm
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose $\cm\subseteq\cn$ and \varphi,\psi are formulas, then
   1. if \varphi,\psi are absolute for \cm,cn, then so are
      $\neg\varphi,\varphi\to\psi$ 
   2. if \varphi doesn't contain any quantifiers, then \varphi is absolute for
      any \cm
   3. if \cm,\cn  are transitive and \varphi is absolute for them, then so are
      $\forall x\in y\varphi$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\Delta_0$ formula
   1. $x=y,x\in y$ are $\Delta_0$ formulas
   2. if \varphi,\psi are $\Delta_0$, then so are $\neg\varphi,\varphi\to\psi$
   3. if $\varphi$ is $\Delta_0$, $y$ is any set, then $(\forall x\in y)\varphi$
      is $\Delta_0$
      

   If \varphi is $\Delta_0$, then $\exists x_1\dots\exists x_n\varphi$ is
   $\Sigma_1$ formula, $\forall x_1\dots\forall x_n\varphi$ is $\Pi_1$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\cm\subseteq\cn$ are both transitive, $\psi(x_0,\dots,x_n)$ is a formula,
   then
   1. if \psi is $\Delta_0$, then it's absolute for \cm,cn
   2. if \psi is $\Sigma_1$, then
      \begin{equation*}
      \forall x_1\dots x_n(\psi^\cm(x_1,\dots,x_n)\to\psi^\cn(x_1,\dots,x_n))
      \end{equation*}
   3. if \psi is $\Pi_1$, then
      \begin{equation*}
      \forall x_1\dots x_n(\psi^\cn(x_1,\dots,x_n)\to\psi^\cm(x_1,\dots,x_n))
      \end{equation*}
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\cm\subseteq\cn$, $\cm\models\Sigma,\cn\models\Sigma$ and
   \begin{equation*}
   \Sigma\vdash\forall x_1\dots\forall x_n(\varphi(x_1,\dots,x_n)\leftrightarrow
   \psi(x_1,\dots,x_n))
   \end{equation*}
   then \varphi is absolute for \cm,\cn if and only if \psi is absolute for \cm,\cn
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose $\cm\subseteq\cn$, $f(x_1,\dots,x_n)$ is a function. $f$ is
   \tf{absolute} for \cm and \cn if and only if $\varphi(x_1,\dots,x_n,x_{n+1})$
   defining $f$ is absolute.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Following relations and functions can be defined in
   $\zfmm-\text{Pow}-\text{Inf}$ and are equivalent to some $\Delta_0$ formulas.
   So they are absolute for any transitive model \cm on 
   $\zfmm-\text{Pow}-\text{Inf}$
   1. $x\in y$
   2. $x=y$
   3. $x\subset y$
   4. $\{x,y\}$
   5. $\{x\}$

   6. $(x,y)$
   7. $\emptyset$
   8. $x\cup y$
   9. $x-y$
   10. $x\cap y$
   11. $x^+$
   12. $x$ is a transitive set
   13. $\bigcup x$
   14. $\bigcap x$ ($\bigcap\emptyset=\emptyset$)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Absoluteness is closed under operation composition
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Following relations and functions are absolute for any transitive model \cm on 
   $\zfmm-\text{Pow}-\text{Inf}$
   1. $z$ is an ordered pair
   2. $A\times B$
   3. $R$ is a relation
   4. $\dom{R}$
   5. $\ran{R}$
   6. $f$ is a function
   7. $f(x)$
   8. $f$ is injective
   #+END_theorem
** Relative consistence of the axiom of foundation
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose transitive class $\cm\models\zfmm-\text{Pow}-\text{inf}$ and
   $\omega\in\cm$, then the axiom of infinity is true in \cm. Hence the axiom of
   infinity is true in \wf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:7.5.2
   Let $T$ be a theory of set theory language and \Sigma a set of sentences.
   Suppose \cm is a class and $T\vdash\cm\neq\emptyset$, then if
   $\cm\models_T\Sigma$, then
   1. for any sentences \varphi, if $\Sigma\vdash\varphi$, then
      $T\vdash\varphi^\cm$
   2. if $T$ is consistent, then so is $\text{Cn}(\Sigma)$
   #+END_theorem


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The axiom of foundation is consistent with \zfm.
   #+END_theorem

   #+BEGIN_proof
   By ref:7.5.2, let T be \zfm, \Sigma be \zf and \cm be \wf
   #+END_proof

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_lemma
   Suppose transitive model $\cmm\models\zfmm-\text{Pow}-\text{Inf}$. If
   $X,R\in\cm$ and $R$ is a well-order on $X$, then
   \begin{equation*}
   (R\text{ is a well-order on }X)^\cmm
   \end{equation*}
   #+END_lemma

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_theorem
   $V_\omega\models\zfc-\text{Inf}+\neg\text{Inf}$
   #+END_theorem
   #+BEGIN_proof
   For any $X\in V_\omega$, $X$ is finite hence there is a well-ordering on $X$
   #+END_proof

   \begin{corollary}
   $\con{\zfmm}\to\con{\zfc-\text{Inf}+\neg\text{Inf}}$
   \end{corollary}
** Induction and recursion based on well-order relation
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is a well-founded relation on $\bX$ if and only if
   \begin{equation*}
   \forall U\subset\bX(U\neq\emptyset\to\exists y\in U(\neg\exists z\in U(z\bR y)))
   \end{equation*}
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Relation $\bR$ is \tf{set-like} on $\bX$ iff for any $x\in\bX$,\par
   $\{y\in\bX\mid y\bR x\}$ is a set
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\bR$ is a set-like relation on $\bX$ and $x\in \bX$, define
   \begin{align*}
   \pred^0(\bX,x,\bR)&=\{y\in\bX\mid y\bR x\}\\
   \pred^{n+1}(\bX,x,bR)&=\bigcup\{\pred(\bX,y,\bR)\mid y\in\pred^n(\bX,x,\bR)\}\\
   \cl(\bX,x,\bR)&=\displaystyle\bigcup_{n\in\omega}\pred^n(\bX,x,\bR)
   \end{align*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\bR$ is a set-like relation on $\bX$, then for any $y\in\cl(\bX,x,\bR)$,
   $\pred(\bX,y,\bR)\subseteq\cl(\bX,x,\bR)$
   #+END_lemma

   #+ATTR_LATEX: :options [Induction on well-founded set-like relation]
   #+BEGIN_theorem
   If $\bR$ is a well-founded set-like relation on $\bX$, then every nonempty 
   $\bY\subseteq\bX$ has minimal element under $\bR$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose $\bR$ is a well-founded set-like relation on $\bX$. If 
   $\bF:\bX\times\bV\to\bV$, then there is a unique $\bG:\bX\to\bV$ s.t.
   \begin{equation*}
   \forall x\in\bX(\bG(x)=\bF(x,\bG\restriction\pred(\bX,x,\bR)))
   \end{equation*}
   #+END_theorem
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\bR$ is a set-like well-founded relation on $\bX$, define 
   \begin{equation*}
   \rank(x,\bX,\bR)=\sup\{\rank(y,\bX,\bR)+1\mid y\bR x\wedge y\in\bX\}
   \end{equation*}
   #+END_definition

   Note that
   \begin{equation*}
   \bF(x,h)=\sup\{\alpha+1\mid\alpha\in\ran{h}\}
   \end{equation*}

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_lemma
   If $\bX$ is transitive and $\in$ is well-founded on $\bX$, then
   $\bX\subseteq\wf$ and for any $x\in\bX$, $\rank(x,\bX,\in)=\rank(x)$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is a set-like well-founded relation on $\bX$, \tf{Mostowski function}
   $\bG$ on $(\bX,\bR)$ is 
   \begin{equation*}
   \bG(x)=\{\bG(y)\mid y\in\bX\wedge y\bR x\}
   \end{equation*}
   $\cmm=\ran{\bG}$ is called the \tf{Mostowski collapse} of $(\bX,\bR)$
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $\forall x,y\in\bX(x\bR y\to\bG(x)\in\bG(y))$
   2. \cm is transitive
   3. If the axiom of power set holds, $\cm\subseteq\wf$
   4. if the axiom of power set holds and $x\in\bX$, then\par
      $\rank(x,\bX,\bR)=\rank(\bG(x))$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is extensional on $\bX$ iff
   \begin{equation*}
   \forall x,y\in\bX(\forall z\in\bX(z\bR x\leftrightarrow z\bR y)\to x=y)
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\bX$ is transitive then $\in$ is extensional on $\bX$
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $\bR$ be a set-like well-founded relation on $\bX$, $\bG$ is a Mostowski
   function on it. If $\bR$ is extensional, then $\bG$ is an isomorphism
   #+END_lemma

   #+ATTR_LATEX: :options [Mostowski collapse theorem]
   #+BEGIN_theorem
   Suppose $\bR$ is set-like well-founded extensional on $\bX$, then there are
   unique transitive class \cm and bijection $\bG:\bX\to\cm$ s.t. 
   $\bG:(\bX,\bR)\cong(\cm,\in)$
   #+END_theorem
** Absoluteness under the axiom of foundation
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following relations and functions can be defined by formulas in
   $\zf-\text{Pow}$ and are equivalent to some $\Delta_0$ formulas
   1. $x$ is an ordinal
   2. $x$ is a limit ordinal
   3. $x$ is a successor ordinal
   4. \omega
   5. $x$ is a finite ordinal
   6. $0,1,2,\dots,20,\dots$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem

   If transitive model $\cm\models\zf-\text{Pow}$, then every finite subset of
   \cm belongs to \cm
   #+END_theorem

   #+BEGIN_proof
   prove 
   \begin{equation*}
   \forall x\subset\cm(\abs{x}=n\to x\in\cm)
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following concepts are absolute for any transitive model of
   $\zf-\text{Pow}$ 
   1. $x$ is finite
   2. $X^n$
   3. $X^{<\omega}$
   4. $R$ is a well-ordering on $X$
   5. $\text{type}(X,R)$
   6. $\alpha+1$
   7. $\alpha-1$
   8. $\alpha+\beta$
   9. $\alpha\cdot\beta$
   #+END_theorem


   Class $\bX$ is in fact a formula $\bX(x)$. It's absolute for \cm if and only
   if $\forall x\in\cm(\bX^\cm(x)\leftrightarrow\bX(x))$, which is equivalent to
   $\{x\in\cm\mid\bX(x)\}=\{x\in\cm\mid\bX^\cm(x)\}$. Hence $\bX$ is absolute
   for \cm if and only if $\bX^\cm=\cm\cap\bX$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose $\bR$ is a well-founded set-like relation on $\bX$,
   $\bF:\bX\times\bV\to\bV$,
   \begin{equation*}
   \forall x\in\bX(\bG(x)=\bF(x,\bG\restriction(\bX,x,\bR)))
   \end{equation*}
   transitive model $\cm\models\zf-\text{Pow}$ and
   1. $\bF$ is absolute for \cm
   2. $\bX,\bR$ are absolute for \cm, $(\bR\text{ is set-like on }\bX)^\cm$ and
      \begin{equation*}
      \forall x\in\cm(\pred(\bX,x,\bR)\subseteq\cm)
      \end{equation*}

      
   then $\bG$ is absolute for $\cm$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following concept is absolute for any transitive model of
   $\zf-\text{Pow}$
   1. $\alpha^\beta$
   2. $\rank(x)$
   3. $\trcl{x}$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   transitive $\cm\models\zf$
   1. if $x\in\cm$, then $\calp^\cm(x)=\calp(x)\cap\cm$
   2. if $\alpha\in\cm$, then $V_\alpha^\cm=V_\alpha\cap\cm$
   #+END_lemma
** Unaccessible cardinal and models of \zfc
   $\bZ=\zff-\text{Rep},\zfmm=\zfcm-\text{Rep}$
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $\gamma>\omega$ is a limit ordinal, then $V_\gamma\models_{\zff}\bZ$ and 
   $V_\gamma\models_{\zfcm}\zc$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $V_{\omega+\omega}$ doesn't satisfies the axiom of replacement
   #+END_corollary

   #+BEGIN_proof
   
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\zcm\not\vdash\exists x(x=V_\omega),\zcm\not\vdash\forall x\exists y(\trcl{x}=y)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is an inaccessible cardinal, then $V_\kappa\models_{\zfmm}\zff$,\par
   $V_\kappa\models_{\zfcc}\zfc$
   #+END_theorem

   #+BEGIN_proof
   Since \kappa is inaccessible, $\abs{V_\kappa}=\kappa$. For any $A\in
   V_\kappa$, $\abs{A}<\kappa$. Since \kappa is regular, any 
   $f:A\to V_\kappa$ is bounded. Hence there exists $\alpha<\kappa$ s.t. 
   $\ran{f}\subseteq V_\alpha$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   We cannot prove "there is some inaccessible cardinals" in \zfc
   #+END_corollary

   #+BEGIN_proof
   Suppose we could. Then we have $V_\kappa\models\zfc$, which contradicts
   Gödel’s second incompleteness theorem 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose \kappa is inaccessible. The following concepts are absolute for
   $V_\kappa$ 
   1. $x$ is a cardinal
   2. $x$ is a regular cardinal
   3. $x$ is an inaccessible cardinal
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\con(\zfcm)\to\con(\zfcm+\text{"there is no inaccessible cardinal"})$
   #+END_lemma

   #+BEGIN_proof
   If \kappa is the smallest inaccessible cardinal, then \par
   $V_\kappa\models\zfcm+\text{"there is no inaccessible cardinal"}$. Define
   \begin{equation*}
   \cm=\bigcap\{V_\kappa\mid\kappa\text{ is inaccessible}\}
   \end{equation*}
   #+END_proof
   If there are, then $\cm=V_\kappa$

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   \con(\zfcm)\not\to\con(\zfcm+\text{"there are some inaccessible cardinals"})
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any infinite cardinal \kappa, $H_\kappa=\{x\mid\abs{\trcl{x}}<\kappa\}$
   is the collection of sets which \tf{hereditarily have size less than } \kappa.
   Element of $H_\omega$ is called \tf{hereditarily finite set}. Element of
   $H_{\omega_1}$ is called \tf{hereditarily countable set}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any infinite cardinal \kappa, $H_\kappa\subseteq V_\kappa$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \kappa is regular, then $H_\kappa=V_\kappa$ if and only if \kappa is
   inaccessible
   #+END_lemma

   #+BEGIN_proof
   which implies $\abs{V_\kappa}=\kappa$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any infinite cardinal \kappa
   1. $H_\kappa$ is transitive
   2. $H_\kappa\cap\on=\kappa$
   3. If $x\in H_\kappa$, then $\bigcup x\in H_\kappa$
   4. If $x,y\in H_\kappa$, then $\{x,y\}\in H_\kappa$
   5. If $x\in H_\kappa,y\subseteq x$, then $y\in H_\kappa$
   6. if $\kappa$ is regular, then $\forall x(x\in H_\kappa\leftrightarrow
      x\subset H_\kappa\wedge\abs{x}<\kappa)$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is uncountable regular cardinal, then
   $H_\kappa\models_{\zfcm}\zfcm-\text{Pow}$ 
   #+END_theorem
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is uncountable regular cardianl, then the following propositions
   are equivalent
   1. $H_\kappa\models\zfcm$
   2. $H_\kappa=V_\kappa$
   3. $\kappa$ is inaccessible
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $\con(\zfcm)\to\con(\zfcm-\text{pow}+\forall x(x\text{ is countable}))$
   #+END_corollary
** Reflection theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\cm\subseteq\cn$ are classes. $\varphi_1,\dots,\varphi_n$ is a sequence
   closed under subformula, then the following propositions are equivalent
   1. $\varphi_1,\dots,\varphi_n$ are absolute for \cm and \cn
   2. if $\varphi_i=\exists\varphi_j(x,y_1,\dots,y_m)$, then
      \begin{equation*}
      \forall y_1,\dots,y_m\in\cm(\exists x\in\cn\varphi_j^\cn(x,y_1,\dots,y_m)
      \to\exists x\in\cm\varphi_j^\cm(x,y_1,\dots,y_m))
      \end{equation*}
   #+END_lemma
   
   #+ATTR_LATEX: :options [reflection theorem(\zff)]
   #+BEGIN_theorem
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any
   $V_\alpha$, there exists $V_\beta$ s.t. $V_\alpha\subseteq V_\beta$ and 
   $\varphi_1,\dots,\varphi_n$ are absolute for $V_\beta$
   #+END_theorem

   #+ATTR_LATEX: :options [\zff]
   #+BEGIN_corollary
   $F=\{\sigma_1,\dots,\sigma_n\}$ are finite subsets of \zf, then
   \begin{equation*}
   \forall\alpha\exists\beta>\alpha(\sigma_1^{V_\beta}\wedge\dots\wedge\sigma_n^{V_\beta})
   \end{equation*}
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $F=\{\sigma_1,\dots,\sigma_n\}$ is a finite subset of \zf. Unless \zf is
   unconsistent, $F$ cannot prove all axioms of \zf
   #+END_corollary

   #+ATTR_LATEX: :options [\zfcm]
   #+BEGIN_theorem
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any set
   $N$, there exists set $M$ s.t.
   1. $N\subseteq M$
   2. $\varphi_1,\dots,\varphi_n$ are absolute for $(M,\in)$
   3. $\abs{M}\le\abs{N}\cdot\omega$
   #+END_theorem

   #+ATTR_LATEX: :options [\zfcm]
   #+BEGIN_corollary
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any set
   $N$, there exists set $M$ s.t.
   1. $N\subseteq M$
   2. $\varphi_1,\dots,\varphi_n$ are absolute for $(M,\in)$
   3. $\abs{M}\le\abs{N}\cdot\omega$
   4. $M$ is transitive
   #+END_corollary
   \newpage
* Constructable Set - Venlafaxine
** Definablity and Gödel operation
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $M$ is a set, $\psi(x_1,\dots,x_n,y_1,\dots,y_m)$ is a formula, 
   $X\subseteq M^n$ is \tf{definable in $M$ from parameters from $\psi$} if and
   only if there are $y_1,\dots,y_m\in M$ s.t.
   \begin{equation*}
   X=\{(x_1,\dots,x_n)\mid(\psi^M(x_1,\dots,x_n,y_1,\dots,y_m))\}
   \end{equation*}
   \begin{equation*}
   \deff(M)=\{X\subseteq M\mid\exists\psi,X\text{ is definable in } 
   M \text{ from } \psi\} 
   \end{equation*}
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \tf{Gödel operation}
   1. $G_1(X,Y)=\{X,Y\}$
   2. $G_2(X,Y)=X\times Y$
   3. $G_3(X,Y)=\in\restriction X\times Y$
   4. $G_4(X,Y)=X-Y$
   5. $G_5(X,Y)=X\cap Y$
   6. $G_6(X,Y)=\bigcap X$
   7. $G_7(X,Y)=\dom{X}$
   8. $G_8(X,Y)=\{(x,y)\mid(y,x)\in X\}$
   9. $G_9(X,Y)=\{(x,y,z)\mid(x,z,y)\in X\}$
   10. $G_{10}(X,Y)=\{(x,y,z)\mid(y,z,x)\in X\}$

       
   Class $C$ is closed under Gödel operation if for any $X,Y$, X,Y\in C$ implies
   $G_i(X,Y)\in C$. For any set $M$, $\cl_G(M)$ is the 
   \tf{closure under Gödel operation}
 
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \psi is a \tf{normal form} if
   1. only $\neg,\wedge,\exists$ are logical symbol
   2. = doesn't appear
   3. if $x_i\in x_j$ then $i\neq j$
   4. $\exists$ only shown as: $\exists x_{m+1}\in
      x_i\varphi(x_1,\dots,x_{m+1})$, $1\le i\le m$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Any $\Delta_0$ formula can be transformed into normal form
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any $\Delta_0$ formula $\psi(x_1,\dots,x_n)$, there is Gödel operations'
   composition $G$ s.t. for any $X_1,\dots,X_n$
   \begin{align*}
   G(X_1,\dots,X_n)=&\{(x_1,\dots,x_n)\mid\\
   &x_1\in X_1\wedge\dots\wedge x_n\in X_n\wedge\psi(x_1,\dots,x_n)\}
   \end{align*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $M$ is transitive and $M=\cl_G(M)$, then for any $\Delta_0$ formula
   $\psi(x,y_1,\dots,y_m)$, any set $X\in M$, any $y_1,\dots,y_m\in M$ if
   \begin{equation*}
   Y=\{x\in X\mid\psi(x,y_1,\dots,y_m)\}
   \end{equation*}
   then $Y\in M$. Hence $\Delta_0$ schema of specification holds in $M$
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $G(X_1,\dots,X_n)$ is Gödel operations' composition, then
   $Z=G(X_1,\dots,X_n)$ is equivalent to a $\Delta_0$ formula
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any transitive set $M$, $\deff(M)=\cl_G(M\cup\{M\})\cap\calp(M)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If transitive $\cm\models\zff$, then for any transitive set $M\in\cm$,
   $\deff(M)$ is absolute for \cm
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any transitive set $M$
   1. $\deff(M)\subseteq\calp(M)$
   2. $M\subseteq \deff(M)$
   3. for any $X\subseteq M$, if $X$ is finite, then $X\in\deff(M)$
   4. assume $\ac$ and $\abs{M}\ge\omega$, then $\abs{\deff(M)}=\abs{M}$
   #+END_lemma
** Gödel's L
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   for any \alpha
   1. $L_0=\emptyset$
   2. $L_{\alpha+1}=\deff(L_\alpha)$
   3. For any limit \alpha, $L_\alpha=\bigcup_{\beta<\alpha}L_\beta$


   $\textbf{L}=\displaystyle\bigcup_{\alpha\in\on}L_\alpha$. Element of \gl is
   called constructible set
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $L_\alpha$ is transitive
   2. If $\alpha<\beta$, then $L_\alpha\subseteq L_\beta$
   3. $L_\alpha\subseteq V_\alpha$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $x\in\gll$
   \begin{equation*}
   \rank_\gll(x)=\min\{\beta\mid x\in\gll_{\beta+1}\}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any \alpha
   \begin{equation*}
   L_\alpha=\{x\in\gll\mid\rank_{\gll}(x)<\alpha\}
   \end{equation*}
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $L_\alpha\cap\on=\alpha$
   2. $\alpha\in\gll\cap\rank_{\gll}(\alpha)=\alpha$
   #+END_lemma

   #+BEGIN_proof
   since "\alpha is a cardinal" is absolute for any transitive set. 
   \begin{align*}
   \alpha&=L_\alpha\cap\on=\{\eta\in L_\alpha\mid\eta\text{ is a ordinal}\}\\
   &=\{\eta\in L_\alpha\mid(\eta\text{ is an ordinal}^{L_\alpha})\}\in\deff(L_\alpha)
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   for any ordinal \alpha
   1. $L_\alpha\in L_{\alpha+1}$
   2. any finite subset of $L_\alpha$ belongs to $L_{\alpha+1}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $\forall n\in\omega(L_n=V_n)$
   2. $L_\omega=V_\omega$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \ac, then for any $\alpha\ge\omega,\abs{L_\alpha}=\abs{\alpha}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\gll\models\zff$
   #+END_theorem

** Axiom of constructibility and relativization
   #+ATTR_LATEX: :options [Axiom of constructibility]
   #+BEGIN_theorem
   $\cvm=\gll$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:8.3.2
   function $\alpha\mapsto L_\alpha$ is absolute for any transitive model of \zf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\gll\models\zff+\cv=\gll$
   #+END_theorem

   #+BEGIN_proof
   $(\cv=\gll)^\gll$ is $\forall x\in\gll\exists\alpha\in\gll(x\in
   L_\alpha)^\gll$. 
   By ref:8.3.2, $(x\in L_\alpha)^\gll\Leftrightarrow x\in L_\alpha$. Hence
   $\gll\models\cv=\gll$

   #+END_proof
   Hence
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\con(\zff)\to\con(\zff+\cv=\gll)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose transitive proper class $\cmm\models\zff-\text{Pow}$, then\par
   $\gll=\gll^\cmm\subseteq\cmm$ 
   #+END_theorem

   #+BEGIN_proof
   For any ordinal \alpha, since \cm is proper, $\cmm\not\subseteq V_\alpha$.
   Hence there is $x\in\cmm$ s.t. $\rank(x)\ge\alpha$. Since rank is absolute,
   $\rank(x)\in\cmm$. And \cm is transitive, hence $\alpha\in\cmm$. By
   ref:8.3.2, $L_\alpha\in\cmm$
   \begin{align*}
    \gll^\cmm &=\{x\in\cmm\mid(\exists\alpha\in\on(x\in L_\alpha))^\cmm\}\\
    &=\{x\mid\exists\alpha\in\on\cap\cmm(x\in\ L_\alpha\cap\cmm)\}\\
    &=\{x\mid\exists\alpha\in\on(x\in L_\alpha)\}\\
    &=\gll
   \end{align*}
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If transitive model $\cm\models\zff$ contains all ordinals, then it's an
   \tf{inner model}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   there is a finite set of axioms $\{\psi_1,\dots,\psi_n\}$ of
   $\zff-\text{Pow}$ s.t. ordinals,rank and $L_\alpha$ are absolute for any
   model of $\{\psi_1,\dots,\psi_n\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If set $M$ is transitive, then $M\cap\on$ is a ordinall and is the least that
   doesn't belong to $M$, denoted by $\alpha^M$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   There is a finite subset $\{\psi_1,\dots,\psi_n\}$ of axioms of
   $\zff-\text{Pow}$ satisfying
   \begin{equation*}
   \forall M(M\text{ is transitive }\wedge\psi_1^M\wedge\dots\wedge\psi_n^m\to
   (L_{\alpha^M}=\gll^M\subseteq M))
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The is a finite subset $\{\psi_1,\dots,\psi_{n+1}\}$ of axioms of
   $\zff-\text{Pow}+\cvm=\gll$ satisfying
   1. If \cm is a transitive proper class and
      $\psi_1^\cm\wedge\dots\wedge\psi_{n+1}^\cm$, then $\cm=\gll$
   2. $\forall M(M\text{ is transitive
      }\wedge\psi_1^M\wedge\dots\wedge\psi_n^m\to (L_{\alpha^M}=M))$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   There is a well-ordering on \gll. Hence $\cvm=\gll\to\ac$
   #+END_theorem

   If $\cvm=\gll$, hence $\aleph_\alpha\subseteq L_{\aleph_{\alpha+1}}$. Because
   $\abs{L_{\alpha_{\alpha+1}}}=\aleph_{\alpha+1}$,
   $2^{\aleph_\alpha}\le\aleph_{\alpha+1}$ 
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $\cvm=\gll$, then for any infinite ordinal \alpha,
   $\calp(L_\alpha)\subseteq L_{\abs{\alpha}^+}$
   #+END_theorem

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_corollary
   $(\ac+\gchh)^\gll$
   #+END_corollary

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_theorem
   $\con(\zff)\to\con(\zfcm+\gchh)$
   #+END_theorem

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_theorem
   Suppose $S_0=\{\psi_1,\dots,\psi_n\}\subseteq\zff+\cvm=\gll$, then
   \begin{equation*}
   \zff\vdash\exists M(\abs{M}=\omega\wedge M\text{ is transitive}\wedge
   (\psi_1^M\wedge\dots\wedge\psi_n^M))
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose $\cvm=\gll$. For any uncountable regular cardinal \kappa,
   $L_\kappa=H_\kappa$ 
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If \kappa is a uncountable regular cardinal, then
   $\L_\kappa\models\zff-\text{Pow}+\cvm=\gll$. If \kappa is inaccessible, then 
   $L_\kappa\models\zff+\cvm=\gll$
   #+END_corollary

\newpage

* The end
  Learn and forget

   
