#+TITLE: Set Theory
#+AUTHOR: Thomas Jech

#+EXPORT_FILE_NAME: ../latex/SetTheory/SetTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex

* Ordinal Numbers

** Linear and Partial Ordering
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A binary relation < on a set \(P\) is a *partial ordering* of \(P\) if
    1. \(p\not<p\) for any \(p\in P\)
    2. if \(p<q\) and \(q<r\) then \(p<r\)


    \((P,<)\) is called a *partially ordered set*. A partial ordering < of \(P\) is a *linear ordering*
    if moreover
    3. [@3] \(p<q\) or \(p=q\) or \(q<p\) for all \(p,q\in P\)

       If < is a partial ordering, then \(\le\) is also a partial ordering
    #+END_definition

    if \((P,<)\) and \((Q,<)\) are partially ordered sets and \(f:P\to Q\), then \(f\) is
    *order-preserving* if \(x<y\) implies \(f(x)<f(y)\). If \(P\) and \(Q\) are linearly ordered, then
    an order-preserving function is also called *increasing*

** Well-Ordering
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A linear ordering < of a set \(P\) is a *well-ordering* if every nonempty subset of \(P\) has a
    least element
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.4
    If \((W,<)\) is a well-ordered set and \(f:W\to W\) is an increasing function, then \(f(x)\ge x\)
    for each \(x\in W\)
    #+END_lemma

    #+BEGIN_proof
    Assume that the set \(X=\{x\in W:f(x)<x\}\) is nonempty and let \(z\) be the least element of \(X\).
    If \(w=f(z)\), then \(f(w)<w\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The only automorphism of a well-ordered set is the identity
    #+END_corollary

    #+BEGIN_proof
    By Lemma ref:lemma2.4, \(f(x)\ge x\) for all \(x\), and \(f^{-1}(x)\ge x\) for all \(x\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If two well-ordered sets \(W_1,W_2\) are isomorphic, then the isomorphism of \(W_1\) onto \(W_2\) is unique
    #+END_corollary

    if \(W\) is a well-ordered set and \(u\in W\), then \(\{x\in W:x<u\}\) is an *initial segment* of \(W\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.7
    No well-ordered set is isomorphic to an initial segment of itself
    #+END_lemma

    #+BEGIN_proof
    If \(\ran(f)=\{x:x<u\}\), then \(f(u)<u\), contrary to Lemma ref:lemma2.4
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm2.8
    If \(W_1\) and \(W_2\) are well-ordered sets, then exactly one of the following three cases holds
    1. \(W_1\) is isomorphic to \(W_2\)
    2. \(W_1\) is isomorphic to an initial segment of \(W_2\)
    3. \(W_2\) is isomorphic to an initial segment of \(W_1\)
    #+END_theorem

    #+BEGIN_proof
    For \(u\in W_i\), (\(i=1,2\)), let \(W_i(u)\) denote the initial segment of \(W_i\) given by \(u\).
    Let
    \begin{equation*}
    f=\{(x,y)\in W_1\times W_2:W_1(x)\text{ is isomorphic to }W_2(y)\}
    \end{equation*}
    Using Lemma ref:lemma2.7, \(f\) is a injective: if \(f(x_1)=f(x_2)=y\),
    then \(W_1(x_1)\cong W_2(y)\cong W_1(x_2)\), and \(x_1<x_2\) or \(x_2<x_1\) fail. If \(h\) is an isomorphism
    between \(W_1(x)\) and \(W_2(y)\), and \(x'<x\), then \(W_1(x')\) and \(W_2(h(x'))\) are isomorphic.
    It follows that \(f\) is order-preserving

    If \(\dom(f)=W_1\) and \(\ran(f)=W_2\), then case 1 holds

    if \(y_1<y_2\) and \(y_2\in\ran(f)\), then \(y_1\in\ran(f)\). Thus if \(\ran(f)\neq W_2\) and \(y_0\) is the
    least element of \(W_2-\ran(f)\), we have \(\ran(f)=W_2(y_0)\). Necessarily, \(\dom(f)=W_1\), for
    otherwise we would have \((x_0,y_0)\in f\), where \(x_0\)=the least element of \(W_1-\dom(f)\)
    #+END_proof

    if \(W_1\) and \(W_2\) are isomorphic, we say that they have the same *order-type*.

** Ordinal Numbers
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(T\) is *transitive* if every element of \(T\) is a subset of \(T\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set is an *ordinal number* (an *ordinal*) if it is transitive and well-ordered by \(\in\)
    #+END_definition

    Define
    \begin{equation*}
    \alpha<\beta \quad\text{ iff }\quad \alpha\in\beta
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.11
    1. \(0=\emptyset\) is an ordinal
    2. if \alpha is an ordinal and \(\beta\in\alpha\), then \beta is an ordinal
    3. if \(\alpha\neq\beta\) are ordinals and \(\alpha\subset\beta\), then \(\alpha\in\beta\)
    4. if \alpha, \beta are ordinals, then either \(\alpha\subset\beta\) or \(\beta\subset\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1,2 by definition

    3. [@3] if \(\alpha\subset\beta\), let \gamma be the least element of the set \(\beta-\alpha\). Since \alpha is transitive, it
       follows that \alpha is the initial segment of \beta given by \gamma: for \(\eta\in\alpha\), \(\eta\neq\gamma\) and \(\gamma\not\in\eta\),
       hence \(\eta\in\gamma\) since ordinals are well-ordered by \(\in\). Thus \(\alpha=\{\xi\in\beta:\xi<\gamma\}=\gamma\), and
       so \(\alpha\in\beta\).
    4. \(\alpha\cap\beta\) is an ordinal, \(\alpha\cap\beta=\gamma\). We have \(\gamma=\alpha\) or \(\gamma=\beta\), for otherwise \(\gamma\in\alpha\)
       and \(\gamma\in\beta\), by 3. Then \(\gamma\in\gamma\), which contradicts the definition of an ordinal (namely
       that \(\in\) is a *strict* ordering of \alpha)
    #+END_proof

    Using Lemma ref:lemma2.11 one gets the followings
    1. < is a linear ordering of the class \(\Ord\)
    2. for each \alpha, \(\alpha=\{\beta:\beta<\alpha\}\) <<Question1>>
    3. if \(C\) is a nonempty class of ordinals, then \(\bigcap C\) is an ordinal, \(\bigcap C\in C\)
       and \(\bigcap C=\inf C\)
    4. if \(X\) is a nonempty set of ordinals, then \(\bigcup X\) is an ordinal, and \(\bigcup X=\sup X\)
    5. for every \alpha, \(\alpha\cup\{\alpha\}\) is an ordinal and \(\alpha\cup\{\alpha\}=\inf\{\beta:\beta>\alpha\}\)


    We thus define \(\alpha+1=\alpha\cup\{\alpha\}\). In view of 4, the class \(\Ord\) is a proper class; otherwise
    consider \(\sup\Ord+1\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Every well-ordered set is isomorphic to a unique ordinal number
    #+END_theorem

    #+BEGIN_proof
    The uniqueness follows from Lemma ref:lemma2.7: suppose \(\alpha\cong\beta\) and \(\alpha\neq\beta\). As \(\alpha\neq\beta\),
    either \(\alpha\in\beta\) or \(\beta\in\alpha\), thus \(\alpha\) is isomorphic to an initial segment of \beta or vice versa.
    But by Lemma ref:lemma2.7,  we get a contradiction.

    Given a well-ordered set \(W\),
    define \(F(x)=\alpha\) is \alpha is isomorphic to the initial segment of \(W\) given by \(x\). If such an
    \alpha exists, then it is unique. By the Replacement Axioms, \(F(W)\) is a set. For each \(x\in W\),
    such an \alpha exists (otherwise consider the least \(x\) for which such an \alpha does not exists). If
    \gamma is the least \(\gamma\not\in F(W)\), then \(F(W)=\gamma\) and we have an isomorphism of \(W\) onto \gamma
    #+END_proof

    0 is a limit ordinal and define \(\sup\emptyset=0\)

    #+ATTR_LATEX: :options [Natural Numbers]
    #+BEGIN_definition
    We denote the least nonzero limit ordinal \omega (or \(\N\)). The ordinals less than \omega are call
    *finite ordinals*, or *natural numbers*
    #+END_definition

** Induction and Recursion
    #+ATTR_LATEX: :options [Transfinite Induction]
    #+BEGIN_theorem
    Let \(C\) be a class of ordinals and assume that
    1. \(0\in C\)
    2. if \(\alpha\in C\), then \(\alpha+1\in C\)
    3. if \alpha is a nonzero limit ordinal and \(\beta\in C\) for all \(\beta<\alpha\), then \(\alpha\in C\)


    Then \(C\) is the class of all ordinals
    #+END_theorem

    #+BEGIN_proof
    Otherwise, let \alpha be the least \(\alpha\not\in C\) and apply 1,2 and 3.
    #+END_proof

    A function whose domain is the set \(\N\) is called an (*infinite*) *sequence* (A *sequence in* \(X\)
    is a function \(f:\N\to X\)). The standard notation for a sequence is
    \begin{equation*}
    \la a_n:n<\omega\ra
    \end{equation*}
    A *finite sequence* is a function \(s\) s.t. \(\dom(s)=\{i:i<n\}\) for some \(n\in\N\); then \(s\) is a
    *sequence  of length* \(n\)

    A *transfinite sequence* is a function whose domain is an ordinal
    \begin{equation*}
    \la a_\xi:\xi<\alpha\ra
    \end{equation*}
    It is also called an *\alpha-sequence* or a *sequence of length* \alpha. We also say that a
    sequence \(\la a_\xi:\xi<\alpha\ra\) is an *enumeration* of its range \(\{a_\xi:\xi<\alpha\}\). If \(s\) is a sequence of
    length \alpha, then \(s^\smallfrown x\) or simply \(sx\) denotes the sequence of length \(\alpha+1\) that
    extends \(s\) and whose \(\alpha\)th term is \(x\):
    \begin{equation*}
    s^\smallfrown x=sx=s\cup\{(\alpha,x)\}
    \end{equation*}
    Sometimes we call a "sequence"
    \begin{equation*}
    \la a_\alpha:\alpha\in\Ord\ra
    \end{equation*}
    a function (a proper class) on \(\Ord\)


    "Definition by transfinite recursion" usually takes the following form: Given a function \(G\)
    (on the class of transfinite sequence), then for every \theta there exists a unique \theta-sequence
    \begin{equation*}
    \la a_\alpha:\alpha<\theta\ra
    \end{equation*}
    s.t.
    \begin{equation*}
    a_\alpha=G(\la a_\xi:\xi<\alpha\ra)
    \end{equation*}
    for every \(\alpha<\theta\)

    #+ATTR_LATEX: :options [Transfinite Recursion]
    #+BEGIN_theorem
    Let \(G\) be a function (on \(V\)), then eqref:2.6 below defines a unique function \(F\)
    on \(\Ord\) s.t.
    \begin{equation*}
    F(\alpha)=G(F\restriction\alpha)
    \end{equation*}
    for each \alpha
    #+END_theorem

    In other words, if we let \(a_\alpha=F(\alpha)\), then for each \alpha
    \begin{equation*}
    a_\alpha=G(\la a_\xi:\xi<\alpha\ra)
    \end{equation*}
    (Note that we tacitly use Replacement: \(F\restriction\alpha\) is a set for each \alpha)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(X\) be a set and \theta an ordinal number. For every function \(G\) on the set of all
    transfinite sequences in \(X\) of length \(<\theta\) s.t. \(\ran(G)\subset X\) there exists a unique
    \theta-sequence \(\la a_\alpha:\alpha<\theta\ra\) in \(X\) s.t. \(a_\alpha=G(\la a_\xi:\xi<\alpha\ra)\) for every \(\alpha<\theta\)
    #+END_corollary

    #+BEGIN_proof
    Let
    \begin{align}
    \label{2.6}
    F(\alpha)=x\leftrightarrow&\text{ there is a sequence }\la a_\xi:\xi<\alpha\ra\text{ s.t.:}\\
    &1.\; (\forall\xi<\alpha)a_\xi=G(\la a_\eta:\eta<\xi\ra)\nonumber\\
    &2.\; x=G(\la a_\xi:\xi<\alpha\ra)\nonumber
    \end{align}
    For every \alpha, if there is an \alpha-sequence that satisfies 1, then such a sequence is unique:
    if \(\la a_\xi:\xi<\alpha\ra\) and \(\la b_\xi:\xi<\alpha\ra\) are two \alpha-sequences satisfying 1, one shows \(a_\xi=b_\xi\) by
    induction on \xi.Thus \(F(\alpha)\) is determined uniquely by 2, and therefore \(F\) is a function.

    it follows, again by induction, that for each \alpha there is an \alpha-sequence that satisfies 1 (at
    limit steps, we use Replacement to get the \alpha-sequence as the union of all the
    \xi-sequences, \(\xi<\alpha\)). Thus \(F\) is defined for all \(\alpha\in\Ord\). It obviously satisfies
    \begin{equation*}
    F(\alpha)=G(F\restriction\alpha)
    \end{equation*}

    If \(F'\) is any function on \(\Ord\) that satisfies
    \begin{equation*}
    F'(\alpha)=G(F'\restriction\alpha)
    \end{equation*}
    then it follows by induction that \(F'(\alpha)=F(\alpha)\) for all \alpha
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\alpha>0\) be a limit ordinal and let \(\la\gamma_\xi:\xi<\alpha\ra\) be a *nondecreasing* sequence of ordinals.
    We define the *limit* of the sequence by
    \begin{equation*}
    \lim_{\xi\to\alpha}\gamma_\xi=\sup\{\gamma_\xi:\xi<\alpha\}
    \end{equation*}

    A sequence of ordinals \(\la\gamma_\alpha:\alpha\in\Ord\ra\) is *normal* if it is increasing and *continuous*, i.e., for
    every limit \alpha,\(\gamma_\alpha=\lim_{\xi\to\alpha}\gamma_\xi\)
    #+END_definition

** Ordinal Arithmetic
    #+ATTR_LATEX: :options [Addition]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha+0=\alpha\)
    2. \(\alpha+(\beta+1)=(\alpha+\beta)+1\) for all \beta
    3. \(\alpha+\beta=\lim_{\xi\to\beta}(\alpha+\xi)\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options [Multiplication]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha\cdot 0=0\)
    2. \(\alpha\cdot(\beta+1)=\alpha\cdot\beta+\alpha\) for all \beta
    3. \(\alpha\cdot\beta=\lim_{\xi\to\beta}\alpha\cdot\xi\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options [Exponentiation]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha^0=1\)
    2. \(\alpha^{\beta+1}=\alpha^\beta\cdot\alpha\) for all \beta
    3. \(\alpha^\beta=\lim_{\xi\to\beta}\alpha^\xi\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For all ordinals \alpha, \beta and \gamma
    1. \(\alpha+(\beta+\gamma)=(\alpha+\beta)+\gamma\)
    2. \(\alpha\cdot(\beta\cdot\gamma)=(\alpha\cdot\beta)\cdot\gamma\)
    #+END_lemma

    #+BEGIN_proof
    Induction on \gamma
    #+END_proof

    Neither + nor \(\cdot\) are commutative:
    \begin{equation*}
    1+\omega=\omega\neq\omega+1,\quad 2\cdot\omega=\omega\neq\omega\cdot 2=\omega+\omega
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((A,<_A)\) and \((B,<_B)\) be disjoint linearly ordered sets. The *sum* of these linear
    orders is the set \(A\cup B\) with the ordering defined as follows: \(x<y\) iff
    1. \(x,y\in A\) and \(x<_Ay\), or
    2. \(x,y\in B\) and \(x<_By\), or
    3. \(x\in A\) and \(y\in B\)

    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((A,<)\) and \((B,<)\) be linearly ordered sets. The *product* of these linear orders is the
    set \(A\times B\) with the ordering defined by
    \begin{equation*}
    (a_1,b_1)<(a_2,b_2)\text{ iff either }b_1<b_2\text{ or }(b_1=b_2\text{ and }a_1<a_2)
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    <<Question2>>
    For all ordinals \alpha and \beta, \(\alpha+\beta\) and \(\alpha\cdot\beta\) are isomorphic to the sum and product of \alpha and \beta
    #+END_lemma

    #+BEGIN_proof
    We can define \(S(\alpha,\beta)=\{(0,a):a\in\alpha\}\cup\{(1,b)\in\beta\}\)

    if \(\beta=0\), then \(S(\alpha,\beta)=\alpha\)

    if \(\beta=\eta+1\), then \(S(\alpha,\beta)=S(\alpha,\eta)\cup\{(1,\eta)\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.25
    1. if \(\beta<\gamma\) then \(\alpha+\beta<\alpha+\gamma\)
    2. if \(\alpha<\beta\) then there exists a unique \delta s.t. \(\alpha+\delta=\beta\)
    3. if \(\beta<\gamma\) and \(\alpha>0\), then \(\alpha\cdot\beta<\alpha\cdot\gamma\)
    4. if \(\alpha>0\) and \gamma is arbitrary, then there exist a unique \beta and a unique \(\rho<\alpha\) s.t. \(\gamma=\alpha\cdot\beta+\rho\)
    5. if \(\beta<\gamma\) and \(\alpha>1\), then \(\alpha^\beta<\alpha^\gamma\)
    #+END_lemma

    #+BEGIN_proof
    1. induction on \gamma
    2. let \delta be the order-type of the set \(\{\xi:\alpha\le\xi<\beta\}\); \delta is unique by 1
    3. \gamma
    4. let \beta be the greatest ordinal s.t. \(\alpha\cdot\beta\le\gamma\)
    5. \gamma
    #+END_proof

    #+ATTR_LATEX: :options [Cantor's Normal Form Theorem]
    #+BEGIN_theorem
    Every ordinal \(\alpha>0\) can be represented uniquely in the form
    \begin{equation*}
    \alpha=\omega^{\beta_1}\cdot k_1+\dots+\omega^{\beta_n}\cdot k_n
    \end{equation*}
    where \(n\ge 1\), \(\alpha\ge\beta_1>\dots>\beta_n\), and \(k_1,\dots,k_n\) are nonzero natural numbers
    #+END_theorem

    #+BEGIN_proof
    By induction on \alpha. For \(\alpha=1\), we have \(1=\omega^0\cdot 1\); for arbitrary \(\alpha>0\), let \beta be the
    greatest ordinal s.t. \(\omega^\beta\le\alpha\). By Lemma ref:lemma2.25 (4) there exists a unique \delta and a
    unique \(\rho<\omega^\beta\) s.t. \(\alpha=\omega^\beta\cdot\delta+\rho\); this \delta must necessarily be finite
    #+END_proof


** Well-Founded Relations
    A binary relation \(E\) on a set \(P\) is *well-founded* if every nonempty \(X\subset P\) has an
    *\(E\)-minimal* element, that is \(a\in X\) s.t. there is no \(x\in X\) with \(xEa\)

    Given a well-founded relation \(E\) on a set \(P\), we can define the *height* of \(E\), and
    assign to each \(x\in P\) an ordinal number, the *rank* of \(x\) in \(E\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(E\) is a well-founded relation on \(P\), then there exists a unique function \rho from \(P\)
    into the ordinals s.t. for all \(x\in P\)
    \begin{equation*}
    \rho(x)=\sup\{\rho(y)+1:yEx\}
    \end{equation*}
    #+END_theorem

    The range of \rho is an initial segment of the ordinals, thus an ordinal number. This ordinal is
    called the *height* of \(E\)

    #+BEGIN_proof

    #+END_proof


* Question
    [[Question1]]
    [[Question2]]
