#+TITLE: Notes on Set Theory
#+AUTHOR: Thomas Jech

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/settheory/SetTheory.tex

* Ordinal
** Linear and partial ordering
   #+ATTR_LATEX:options []
   #+BEGIN_definition
   A binary relation $<$ on a set $P$ is a \tf{partial ordering} of $P$ if:
   1. $p\not< p$ for any $p\in P$
   2. if $p<q$ and $q<r$ then $p<r$

      $(P,<)$ is called a \tf{partial ordered set}. A partial ordering $<$ of
      $P$ is a \tf{linear ordering} if moreover
   3. $p<q$ or $q<p$ or $p=q$ for all $p,q\in P$
   #+END_definition


   If $(P,<)$ and $(Q,<)$ are poset and $f:P\to Q$, then $f$ is
   \tf{order-preserving} if $x<y$ implies $f(x)<f(y)$. If $P$ and $Q$ are
   linearly ordered, then $f$ is also called \tf{increasing}
** Well-Ordering
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A linear ordering $<$ of a set $P$ is a *well-ordering* if every nonempty
   subset of $P$ has a least element
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1
   If $(W,<)$ is a well-ordering set and $f:W\to W$ is an increasing function,
   then $f(x)\ge x$ for each $x\in W$
   #+END_lemma
   #+BEGIN_proof
   Assume that the set $X=\{x\in W\mid f(x)<x\}$ is nonempty and let $z$ be the
   least element of $X$. Hence $f(f(x))<f(x)$ and $f(x)\in X$, a contradiction.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   The only automorphism of a well-ordered set is the identity
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If two well-ordered sets $W_1,W_2$ are isomorphic, then the isomorphism of
   $W_1$ onto $W_2$ is unique
   #+END_corollary

   If $W$ is a well-ordered set and $u\in W$, then $\{x\in W:x<u\}$ is an
   \tf{initial segment} of $W$
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma2
   No well-ordered set is isomorphic to an initial segment of itself
   #+END_lemma
   #+BEGIN_proof
   If $\ran{f}=\{x:x<u\}$, then $f(u)<u$, contrary to lemma ref:lemma1
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $W_1$ and $W_2$ are well-ordered sets, then exactly one of the following
   three cases holds:
   1. $W_1\cong W_2$
   2. $W_1$ is isomorphic to an initial segment of $W_2$
   3. $W_2$ is isomorphic to an initial segment of $W_1$
   #+END_theorem
   #+BEGIN_proof
   For $u\in W_i,(i=1,2)$, let $W_i(u)$ denote the initial segment of $W_i$
   given by $u$. Let
   \begin{equation*}
   f=\{(x,y)\in W_1\times W_2\mid W_1(x)\cong W_2(y)\}
   \end{equation*}

   If $W_1(x)\cong W_w(y)$ and $W_1(x)\cong W_2(y')$, then $W_2(y)\cong
   W_1(y')$. According to lemma ref:lemma2, $y=y'$. Hence it's easy to see that
   $f$ is a one-to-one function.

   If $h$ is an isomorphism between $W_1(x)$ and $W_2(y)$ and $x'<x$, then
   $W_1(x')\cong W_2(h(x'))$. It follows that $f$ is order-preserving.

   If $\dom{f}=W_1$ and $\ran{f}=W_2$, then case 1 holds.

   If $y_1<y_2$ and $y_2\in \ran{f}$, then $y_1\in\ran{f}$. If there is some
   $y<y_2$ and $y\not\in\ran{f}$. Consider the least element $y'$ of $\{y\in
   W_2\mid y<y_2\wedge y\not\in\ran{f}\}$. Let $x'=\sup\{x\in W_1\mid\exists
   y\in W_2(W_1(x)\cong W_2(y)\wedge y<y')\}$, then $W_1(x')\cong W_2(y')$, a
   contradiction. 

   If $\ran{f}\neg W_2$ and $y_0$ is the least element of $W_2-\ran{f}$. We have
   $\ran{f}=W_2(x_0)$. Necessarily, $\dom{f}=W_1$, for otherwise we could have
   $(x_0,y_0)\in f$ where \(x_0=\)least element of $W_1-\dom{f}$. Thus case 2
   holds.

   Similarly, case 3 holds.
   #+END_proof

   If $W_1\cong W_2$, we say that they have the same \tf{order-type}


** Ordinal Numbers
   The idea is to define ordinal numbers so that
   \begin{equation*}
   \alpha<\beta\Leftrightarrow\alpha\in\beta\wedge\alpha=\{\beta:\beta<\alpha\}
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A set $T$ is \tf{transitive} if every element of $T$ is a subset of $T$
   #+END_definition
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A set is an \tf{ordinal number} (an \tf{ordinal}) if it's transitive and
   well-ordered by $\in$
   #+END_definition
   The class of all ordinals is denoted by $Ord$

   We define
   \begin{equation*}
   \alpha<\beta\Leftrightarrow\alpha\in\beta
   \end{equation*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3
   1. $0=\emptyset$ is an ordinal
   2. If $\alpha$ is an ordinal and $\beta\in\alpha$, then \beta is an ordinal
   3. If $\alpha\neq\beta$ are ordinals and $\alpha\subset\beta$, then
      $\alpha\in\beta$
   4. If \alpha,\beta are ordinals, then either $\alpha\subset\beta$ or
      $\beta\subset\alpha$
   #+END_lemma
   #+BEGIN_proof
   1. definition
   2. definition
   3. If $\alpha\subset\beta$, let \gamma be the least element of the set
      $\beta-\alpha$. Since \alpha is transitive, it follows that \alpha is the
      initial segment of \beta given by \gamma. Thus
      $\alpha=\{\xi\in\beta\mid\xi<\gamma\}=\gamma\in\beta$
   4. Clearly $\alpha\cap\beta$ is an ordinal \gamma. We have $\gamma=\alpha$ or
      $\gamma=\beta$, for otherwise $\gamma\in\alpha$ and $\gamma\in\beta$ by 3.
      Then $\gamma\in\gamma$ which contradicts the definition of an ordinal
   #+END_proof
   Using lemma ref:lemma3 one gets the following facts about ordinal numbers
   1. $<$ is a linear ordering of the class $Ord$
   2. For each \alpha, $\alpha=\{\beta:\beta<\alpha\}$
   3. If $C$ is a nonempty class of ordinals, then $\bigcap C$ is an ordinal,
      $\bigcap C\in C$ and $\bigcap C=\inf C$
   4. If $X$ is a nonempty set of ordinals, then $\bigcup X$ is an ordinal and
      $\bigcup X=\sup X$
   5. For every \alpha, $\alpha\cup\{\alpha\}$ is an ordinal and
      $\alpha\cup\{\alpha\}=\inf\{\beta:\beta>\alpha\}$


   We thus define $\alpha+1=\alpha\cup\{\alpha\}$(the \tf{succesor} of \alpha) 
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Every well-ordered set is isomorphic to a unique ordinal number
   #+END_theorem

   #+BEGIN_proof
   The uniqueness follows from lemma ref:lemma2. Given a well-ordered set $W$,
   we find an isomorphic ordinal as follows: Define $F(x)=\alpha$ if \alpha is
   isomorphic to the initial segment of $W$ given by $x$. If such an \alpha
   exists, then it's unique. By the replacement axiom, $F(W)$ is a set. For each
   $x\in W$, such an \alpha exists. Otherwise consider the least $x$ such that
   \alpha doesn't exist. Let $\alpha=\sup\{F(x')\mid x'\in W\wedge x' <x\}$ and
   $F(x)=\alpha$. If \gamma is the least $\gamma\not\in F(W)$, then
   $F(W)=\gamma$ and we have an isomorphism of $W$ onto \gamma
   #+END_proof

   If $\alpha=\beta+1$, then \alpha is a \tf{succesor ordinal}. If \alpha is not
   a succesor ordinal then $\alpha=\sup\{\beta:\beta<\alpha\}=\bigcup\alpha$ is
   called a \tf{limit ordinal}. We also consider 0 a limit ordinal and define
   $\sup\emptyset=0$.

** Induction and Recursion
   #+ATTR_LATEX: :options [Transfinite Induction]
   #+BEGIN_theorem
   Let $C$ be a class of ordinals and assume
   1. $0\in C$
   2. if $\alpha\in C$, then $\alpha+1\in C$
   3. if \alpha is a nonzero limit ordinal and $\beta\in C$ for all
      $\beta<\alpha$, then $\alpha\in C$

      
   Then $C$ is the class of all ordinals
   #+END_theorem

   #+BEGIN_proof
   Otherwise let \alpha be the least ordinal $\alpha\not\in C$ and apply 1, 2 or 3
   #+END_proof

   A function whose domain is the set $\N$ is called an *infinite*
   sequence} (A *sequence* in $X$ is a function $f:\N\to X$). The standard
   notation for a sequence is
   \begin{equation*}
   \la a_n:n<\omega\ra
   \end{equation*}
   A *finite sequence* is a function $s$ s.t. $\dom{s}=\{i:i<n\}$ for some
   $n\in\N$; then $s$ is a *sequence of length* $n$

   A *transfinite sequence* is a function whose domain is an ordinal
   \begin{equation*}
   \la a_\xi:\xi<\alpha\ra
   \end{equation*}
   It is also called an \alpha-*sequence* or a *sequence of length*
   \alpha. We also say that a sequence $\la a_\xi:\xi<\alpha\ra$ is an
   *enumeration* of its range $\{a_\xi:\xi<\alpha\}$. If $s$ is a sequence of
   length \alpha, then $s^\smallfrown x$ or simply $sx$ denotes the sequence of length
   $\alpha+1$ that extends $s$ and whose \(\alpha\)th term is $x$:
   \begin{equation*}
   s^\smallfrown x=sx=s\cap\{(\alpha,x)\}
   \end{equation*}

   #+ATTR_LATEX: :options [Transfinite Recursion]
   #+BEGIN_theorem
   Let $G$ be a function, then ref:align1 below defines a unique function $F$ on
   $Ord$ s.t.
   \begin{equation*}
   F(\alpha)=G(F\restriction\alpha)
   \end{equation*}
   for each \alpha
   #+END_theorem
   In other words, if we let $a_\alpha=F(\alpha)$, then for each \alpha
   \begin{equation*}
   a_\alpha=G(\la a_\xi:\xi<\alpha\ra)
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   Let $X$ be a set and \theta be an ordinal number. For every function $G$ on
   the set of all transfinite sequences in $X$ of length $<\theta$ s.t.
   $\ran{G}\subset X$ there exists a unique \theta-sequence in $X$ s.t. 
   $a_\alpha=G(\la a_\xi:\xi<\theta)$ for every $\alpha<\theta$
   #+END_corollary
   #+BEGIN_proof
   
   Let
   \begin{align}
   \label{align1}
   F(\alpha)=x\leftrightarrow&\text{ there is a sequence }
   \la a_\xi:\xi<\alpha\ra \text{ such that }\\
   &1.\;(\forall \xi<\alpha)a_\xi=G(\la a_n\eta:\eta<\xi\ra)\nonumber \\
   &2.\; x=G(\la a_\xi:\xi<\alpha\ra)\nonumber
   \end{align}

   For every \alpha, if there is an \alpha-sequence that satisfying 1, then such
   a sequence is unique. Thus $F(\alpha)$ is determined uniquely by 2 and
   therefore $F$ is a function. 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\alpha>0$ be a limit ordinal and let $\la\gamma_\xi:\xi<\alpha\ra$ be a
   \tf{nondecreasing} sequence of ordinals (i.e., $\xi<\eta$ implies
   $\gamma_\xi\le\gamma_eta$). We define the \tf{limit} of the sequence by
   \begin{equation*}
   \lim_{\xi\to\alpha}\gamma_\xi=\sup\{\gamma_\xi:\xi<\alpha\}
   \end{equation*}

   A sequence of ordinals $\la\gamma_\alpha:\alpha\in Ord\ra$ is *normal* if
   it's increasing and *continuous*, i.e., for every limit \alpha,
   $\gamma_\alpha=\lim_{\xi\to\alpha}\gamma_\xi$ 
   #+END_definition

   
** Ordinal Arithmetic
   #+ATTR_LATEX: :options [Addition]
   #+BEGIN_definition
   For all ordinal numbers \alpha
   1. $\alpha+0=\alpha$
   2. $\alpha+(\beta+1)=(\alpha+\beta)+1$, for all \beta
   3. $\alpha+\beta=\lim_{\xi\to\beta}(\alpha+\xi)$ for all limit $\beta>0$
   #+END_definition

   #+ATTR_LATEX: :options [Multiplication]
 
   #+BEGIN_definition
   For all ordinal numbers \alpha
   1. $\alpha\cdot 0=0$
   2. $\alpha\cdot(\beta+1)=(\alpha\cdot\beta)+\alpha$, for all \beta
   3. $\alpha\cdot\beta=\lim_{\xi\to\beta}(\alpha\cdot\xi)$ for all limit $\beta>0$
   #+END_definition

   #+ATTR_LATEX: :options [Exponentiation]
   #+BEGIN_definition
   For all ordinal numbers \alpha
   1. $\alpha^0=1$
   2. $\alpha^{\beta+1}=\alpha^\beta\cdot\alpha$, for all \beta
   3. $\alpha^\beta=\lim_{\xi\to\beta}\alpha^\xi$ for all limit $\beta>0$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For all ordinals \alpha, \beta and \gamma
   1. $\alpha+(\beta+\gamma)=(\alpha+\beta)+\gamma$
   2. $\alpha\cdot(\beta\cdot\gamma)=(\alpha\cdot\beta)\cdot\gamma$
   #+END_lemma
   Neither $+$ nor $\cdot$ are commutative
   \begin{equation*}
   1+\omega=\omega\neq \omega+1,\e 2\cdot\omega=\omega\neq\omega\cdot 2
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $(A,<_A)$ and $(B,<_B)$ be disjoint linearly ordered sets. The \tf{sum}
   of these linear orders is the set $A\cup B$ with the ordering defined as
   follows:
   $x<y$ if and only if
   1. $x,y\in A$ and $x<_A y$
   2. $x,y\in B$ and $x<_B y$
   3. $x\in A$ and $y\in B$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $(A,<)$ and $(B,<)$ be linearly ordered sets. The \tf{product} of these
   linear orders is the set $A\times B$ with the ordering defined by
   \begin{equation*}
   (a_1,b_1)<(a_2,b_2)\Leftrightarrow b_1<b_2\text{ or } (b_1=b_2\wedge a_1<a_2)
   \end{equation*}
   #+END_definition
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For all ordinals \alpha and \beta, $\alpha+\beta$ and $\alpha\cdot\beta$ are
   respectively isomorphic to the sum and to the product of \alpha and \beta
   #+END_lemma

   #+BEGIN_proof
   Suppose $(A,<_A)\cong\alpha$ and $(B,<_B)\cong\beta$. 
   1. if $\beta=0$, then $B=\emptyset, A\cup B=A$
   2. if $(A\cup B,<_{A\cup B})\cong \alpha+\beta$, let $B'\equal B\cup\{c\}$ s.t.
      $\{c\}\cap A=\{c\}\cap B=\emptyset$ all for all $b\in B$, $b<c$. Hence
      \begin{equation*}
      \alpha+(\beta+1)=(\alpha+\beta)+1\cong(A\cup B)\cup\{c\}=A\cup B'
      \end{equation*}
      
   3. if \beta is a limit ordinal and for all $\xi<\beta$ and $B_\xi\cong\xi$,\par
      $(A\cup B_\xi,<_{A\cup B_\xi})\cong\alpha+\xi$,
      \begin{equation*}
      A\cup B=A\cup\sup{B_\xi}=\sup(A\cup B_\xi)\cong\sup(\alpha+\xi)=\alpha+\beta
      \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. If $\beta<\gamma$ then $\alpha+\beta<\alpha+\gamma$
   2. If $\alpha<\beta$ then there exists a unique \delta s.t.
      $\alpha+\delta=\beta$
   3. If $\beta < \gamma$ and $\alpha>0$, then
      $\alpha\cdot\beta<\alpha\cdot\gamma$
   4. If $\alpha>0$ and \gamma is arbitrary, then there exist a unique \beta and
      a unique $\rho<\alpha$ s.t. $\gamma=\alpha\cdot\beta+\rho$
   5. If $\beta<\gamma$ and $\alpha>1$, then $\alpha^\beta<\alpha^\gamma$
   #+END_lemma
   #+BEGIN_proof
   2. [@2] Let \delta be the order-type of the set $\{\xi:\alpha\le\xi<\beta\}$
   4. [@4] Let \beta be the greatest ordinal s.t. $\alpha\cdot\beta\le\gamma$
   #+END_proof


   #+ATTR_LATEX: :options [Cantor's Normal Form Theorem]
   #+BEGIN_theorem
   Every ordinal $\alpha>0$ can be represented uniquely in the form
   \begin{equation*}
   \alpha=\omega^{\beta_1}\cdot k_1+\dots+\omega^{\beta_n}\cdot k_n
   \end{equation*}
   where $n\ge 1$, $\alpha\ge\beta_1>\dots>\beta_n$ and $k_1,\dots,k_n$ are
   nonzero natural numbers.
   #+END_theorem
   #+BEGIN_proof
   By induction on \alpha. For $\alpha=1$ we have $1=\omega^0+1$; for arbitrary
   $\alpha>0$, let $\beta$ be the greatest ordinal s.t. $\omega^\beta\le
   \alpha$.
   The uniqueness of the normal form is proved by induction
   #+END_proof

   
** Well-Founded Relations
   A binary relation $E$ on a set $P$ is *well-founded* if every nonempty
   $X\subset P$ has an \(E\)-*minimal* element.

   Given a well-founded relation $E$ on a set $P$, we can define the \tf{height}
   of $E$ and assign to each $x\in P$ and ordinal number, the \tf{rank} of $x$
   in $E$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $E$ is a well-founded relation on $P$, then there exists a unique function
   \rho from $P$ into the ordinals s.t. for all $x\in P$
   \begin{equation*}
   \rho(x)=\sup\{\rho(y)+1:yEx\}
   \end{equation*}
   #+END_theorem
   The range of \rho is an initial segment of the ordinals, thus an ordinal
   number. This ordinal is called the \tf{height} of $E$

   #+BEGIN_proof
   By induction, let
   \begin{align*}
   &P_0=\emptyset\\
   &P_{\alpha+1}=\{x\in P:\forall y(yEx\to y\in P_\alpha)\}\cup P_\alpha\\
   &P_\alpha=\displaystyle\bigcup_{\xi<\alpha}P_\xi \e\text{if } \alpha 
   \text{ is a limit ordinal}
   \end{align*}
   Let \theta be the least ordinal s.t. $P_{\theta+1}=P_\theta$. We claim that
   $P_\theta=P$ 
   #+END_proof

** Exercise
   #+BEGIN_exercise
   Every normal sequence $\la\gamma_\alpha:\alpha\in Ord\ra$ has arbitrarily
   large \tf{fixed points}, i.e., \alpha s.t. $\gamma_\alpha=\alpha$
   #+END_exercise
   

   #+BEGIN_proof
   From
   \href{https://math.stackexchange.com/questions/1808103/show-that-there-exists-a-fixed-point-for-this-set-theoretic-class-function}{StackExchange}.
      
   #+END_proof

   A limit ordinal $\gamma>0$ is called \tf{indecomposable} if there exist no
   $\alpha<\gamma$ and $\beta<\gamma$ s.t. $\alpha+\beta=\gamma$
   #+BEGIN_exercise
   A limit ordinal $\gamma>0$ is indecomposable if and only if
   $\alpha+\gamma=\gamma$ for all $\alpha<\gamma$ if and only if
   $\gamma=\omega^\alpha$ for some \alpha
   #+END_exercise
   
   #+BEGIN_proof
   1. (3)$\to$(1). Assume $\gamma_1,\gamma_2<\gamma=\omega^\alpha$. By
      Cantor's normal form theorem, there exist $\alpha'$ and $k$ s.t. 
      $\gamma_1,\gamma_2<\omega^{\alpha'}\cdot k$
   2. (2)$\to$(3). Assume that $\gamma$ can't be written as $\omega^\alpha$.
      Then by Cantor's theorem, $\gamma=\omega^{\beta_1}\cdot
      k_1+\dots+\omega^{\beta_n}\cdot k_n$. But then
      $\omega^{\beta_1}<\gamma$ and $\omega^{\beta_1}+\gamma>\gamma$
   #+END_proof

   #+BEGIN_exercise
   (Without the Axiom of Infinity). Let $\omega=$ least limit $\alpha\neq 0$ if
   it exists, $\omega=\ord$ otherwise. Prove that the following statements are
   equivalent
   1. There exists an inductive set
   2. There exists an infinite set
   3. \omega is a set
   #+END_exercise

   
* Cardinal Numbers
** Cardinality
   Two sets $X,Y$ have the same /cardinality/
   \begin{equation}
   \label{eq:3.1}
   \abs{X}=\abs{Y}
   \end{equation}
   if there exists a one-to-one mapping of $X$ onto $Y$.
  
   The relation ref:eq:3.1 is an equivalence relation. We assume that we can
   assign to each set $X$ its /cardinal number/ $\abs{X}$ so that two sets are
   assigned the same cardinal just in case they satisfy condition ref:eq:3.1. 
   /Cardinal numbers can be defined either using the Axiom of Regularity (via
   equivalence classes) or using/
   /the Axiom of Choice/

   \begin{equation*}
   \abs{X}\le\abs{Y}
   \end{equation*}
   if there exists a one-to-one mapping of $X$ into $Y$.

   #+ATTR_LATEX: :options [Cantor]
   #+BEGIN_theorem
   For every set $X$, $\abs{X}<\abs{P(X)}$
   #+END_theorem
   #+BEGIN_proof
   Let $f$ be a function from $X$ into $P(X)$. The set 
   \begin{equation*}
   Y=\{x\in X:x\not\in f(x)\}
   \end{equation*}
   is not in the range of $f$. Thus $f$ is not a function of $X$ onto $P(X)$
   #+END_proof
   #+ATTR_LATEX: :options [Cantor-Bernstein]
   #+BEGIN_theorem
   If $\abs{A}\le\abs{B}$ and $\abs{B}\le\abs{A}$, then $\abs{A}=\abs{B}$
   #+END_theorem
   #+BEGIN_proof
   If $f_1:A\to B$ and $f_2:B\to A$ are one-to-one, then if we let $B'=f_2(B)$
   and $A_1=f_2(f_1(A))$, we have $A_1\subset B'\subset A$ and
   $\abs{A_1}\equal\abs{A}$. Thus we may assume that $A_1\subset B\subset A$ and
   that $f$ is a one-to-one function of $A$ onto $A_1$; we will show that
   $\abs{A}=\abs{B}$

   We define for all $n\in\N$
   \begin{alignat*}{2}
   &A_0=A,\quad&&A_{n+1}=f(A_n)\\
   &B_0=B,&&B_{n+1}=f(B_n)
   \end{alignat*}
   Let $g$ be the function on $A$ defined as follows 
   \begin{equation*}
   g(x)=
   \begin{cases}
   f(x)&\text{if }x\in A_n-B_n\text{ for some }n\\
   x&\text{otherwise}
   \end{cases}
   \end{equation*}
   Then $g$ is a one-to-one mapping of $A$ onto $B$

   \href{https://math.stackexchange.com/questions/936467/problem-applying-the-cantor-bernstein-theorem-proof-technique-to-two-open-interv}{StackExchange}
   #+END_proof

   The arithmetic operations on cardinals are defined as follows:
   \begin{alignat*}{2}
   &\kappa+\lambda=\abs{A\cup B}\quad&&\text{where }\abs{A}=\kappa,\abs{B}=\lambda,A,B
   \text{ are disjoint} \\
   &\kappa\cdot\lambda=\abs{A\times B}&&\text{where }\abs{A}=\kappa,\abs{B}=\lambda\\
   &\kappa^\lambda=\abs{A^B}&&\text{where }\abs{A}=\kappa,\abs{B}=\lambda
   \end{alignat*}
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\abs{A}=\kappa$, then $\abs{P(A)}=2^\kappa$
   #+END_lemma
   #+BEGIN_proof
   For every $X\subset A$, let $\chi_X$ be the function
   \begin{equation*}
   \chi_X(x)=
   \begin{cases}
   1&\text{if }x\in X\\
   0&\text{if }x\in A-X\\
   \end{cases}
   \end{equation*}
   The mapping $f:X\to\chi_X$ is a one-to-one correspondence between $P(A)$ and
   $\{0,1\}^A$
   #+END_proof
  
   Facts about cardinal arithmetic
   1. $+$ and $\cdot$ are associative, commutative and distributive
   2. $(\kappa\cdot\lambda)^\mu=\kappa^\mu\cdot\lambda^\mu$
   3. $(\kappa^\lambda)^\mu==\kappa^{\lambda\cdot\mu}$
   4. $\kappa^{\lambda+\mu}=\kappa^\lambda\cdot\kappa^\mu$
   5. If $\kappa\le\lambda$, then $\kappa^\mu\le\lambda^\mu$
   6. If $0<\lambda\le\mu$, then $\kappa^\lambda\le\kappa^\mu$
   7. $\kappa^0=1;1^\kappa=1;0^\kappa=0$ if $\kappa>0$

** Alephs
   An ordinal \alpha is called  /cardinal number/ (a cardinal) if
   $\abs{\alpha}\neq\abs{\beta}$ for all $\beta<\alpha$

   If $W$ is a well-ordered set, then there exists an ordinal \alpha s.t.
   $\abs{W}=\abs{\alpha}$. Thus we let
   \begin{equation*}
   \abs{W}=\text{the least ordinal s.t. } \abs{W}=\abs{\alpha}
   \end{equation*}
   
   All infinite cardinals are limit ordinals. The infinite ordinal numbers that
   are cardinals are called /alephs/
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.4
   1. For every \alpha there is a cardinal number greater than \alpha
   2. If $X$ is a set of cardinals, then $\sup X$ is a cardinal


   For every \alpha, let $\alpha^+$ be the least cardinal number greater than
   \alpha, the /cardinal successor/ of \alpha
   #+END_lemma
   #+BEGIN_proof
   1. For any set $X$, let
      \begin{equation*}
      h(X)=\text{the least }\alpha\text{ s.t. there is no one-to-one function of }
      \alpha\to X
      \end{equation*}
      There is only a set of possible well-orderings of subsets of $X$. Hence
      there is only a set of ordinals for which a one-to-one function of \alpha
      into $X$ exists. Thus $h(X)$ exists.

      If \alpha is an ordinal, then $\abs{\alpha}<\abs{h(\alpha)}$
   2. Let $\alpha=\sup X$. If $f$ is a one-to-one mapping of \alpha onto some
      $\beta<\alpha$, let $\kappa\in X$ s.t. $\beta<\kappa\le\alpha$. Then
      $\abs{\kappa}=\abs{\{f(\xi):\xi<\kappa\}}\le\beta$, a contradiction
   #+END_proof
   Using Lemma ref:lemma3.4 we define the increasing enumeration of all alephs.
   \begin{align*}
   &\aleph_0=\omega_0=\omega,\e\e\aleph_{\alpha+1}=\omega_{\alpha+1}=\aleph_\alpha^+\\
   &\aleph_\alpha=\omega_\alpha=\sup\{\omega_\beta:\beta<\alpha\}\e
   \text{if }\alpha\text{ is a limit ordinal}
   \end{align*}
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thm3.5
   $\aleph_\alpha \cdot\aleph_\alpha=\aleph_\alpha$
   #+END_theorem

** The Canonical Well-Ordering of $\alpha\times\alpha$
   We define
   \begin{align*}
   (\alpha,\beta)<(\gamma,\delta)\leftrightarrow\e&\text{either }\max
   \{\alpha,\beta\}<\max\{\gamma,\delta\},\\
   &\text{or }\max\{\alpha,\beta\}=\max\{\gamma,\delta\}\text{ and }\alpha<\gamma,\\
   &\text{or }\max\{\alpha,\beta\}=\max\{\gamma,\delta\},\alpha=\gamma\text{ and }
   \beta<\delta
   \end{align*}
   This relation is a linear ordering of the class $\ord\times\ord$. Moreover if
   $X\subset\ord\times\ord$ is nonempty, then $X$ has a least element. Also, for
   each \alpha,$\alpha\times\alpha$ is the initial segment given by
   $(0,\alpha)$. If we let
   \begin{equation*}
   \Gamma(\alpha,\beta)=\text{the order-type of the set }
   \{(\xi,\eta):(\xi,\eta)<(\alpha,\beta)\}
   \end{equation*}
   then \Gamma is a one-to-one mapping of $\ord^2$ onto $\ord$ and
   \begin{equation*}
   (\alpha,\beta)<(\gamma,\delta)\e\text{ if and only if }\e
   \Gamma(\alpha,\beta)<\Gamma(\gamma,\delta)
   \end{equation*}
   Note that $\Gamma(\omega,\omega)=\omega$ and since
   $\gamma(\alpha)=\Gamma(\alpha,\alpha)$ is an increasing function of $\alpha$,
   we have $\gamma(\alpha)\ge\alpha$. However, $\gamma(\alpha)$ is also
   continuous and so $\Gamma(\alpha,\alpha)=\alpha$ for arbitrarily large \alpha

   \noindent /Proof of Theorem ref:thm3.5/. We shall show that
   $\gamma(\omega_\alpha)=\omega_\alpha$. This is true for $\alpha=0$. Thus let
   \alpha be the least ordinal s.t. $\gamma(\omega_\alpha)\neq\omega_\alpha$.
   Let $\beta,\gamma<\omega_\alpha$ be s.t.
   $\Gamma(\beta,\gamma)=\omega_\alpha$. Pick $\delta<\omega_\alpha$ s.t.
   $\delta>\beta$ and $\delta>\gamma$. Since $\delta\times\delta$ is an initial
   segment of $\ord\times\ord$ in the canonical well-ordering and contains
   $(\beta,\gamma)$, we have $\Gamma(\delta,\delta)\supset\omega_\alpha$ and so
   $\abs{\delta\times\delta}\ge\aleph_\alpha$. However
   $\abs{\delta\times\delta}=\abs{\delta}\cdot\abs{\delta}$, and by the
   minimality of \alpha,
   $\abs{\delta}\cdot\abs{\delta}=\abs{\delta}<\aleph_\alpha$. A contradiction

   As a corollary we have 
   \begin{equation*}
   \aleph_\alpha+\aleph_\beta=\aleph_\alpha\cdot\aleph_\beta=\max
   \{\aleph_\alpha,\aleph_\beta\}
   \end{equation*}

** Cofinality
   Let $\alpha>0$ be a limit ordinal. We say that an increasing \beta-sequence 
   $\la\alpha_\xi:\xi<\beta\ra$, \beta a limit ordinal, is /cofinal/ in \alpha if 
   $\lim_{\xi\to\beta}\alpha_\xi=\alpha$. $A\subset\alpha$ is /cofinal/ in \alpha
   if $\sup A=\alpha$. If \alpha is an infinite limit ordinal, the /cofinality/ of
   \alpha is 
   \begin{align*}
   \cf\alpha=&\text{the least limit ordinal }\beta\text{ s.t. there is 
   an increasing}\\
   &\beta\text{-sequence }\la\alpha_\xi:\xi<\beta\ra
   \text{ with }\lim_{\xi\to\beta}\alpha_\xi=\alpha
   \end{align*}
   Obviously $\cf\alpha$ is a limit ordinal and $\cf\alpha\le\alpha$. Examples:
   $\cf(\omega+\omega)=\cf\aleph_\omega=\omega$
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\cf(\cf\alpha)=\cf\alpha$
   #+END_lemma
   #+BEGIN_proof
   If $\la\alpha_\xi:\xi<\beta\ra$ is cofinal in \alpha and
   $\la\xi(\nu):\nu<\gamma\ra$ is cofinal in \beta, then
   $\la\alpha_{\xi(\nu)}:\nu<\gamma\ra$ is cofinal in \alpha
   #+END_proof
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma3.7
   Let $\alpha>0$ be a limit ordinal
   1. If $A\subset \alpha$ and $\sup A=\alpha$, then the order-type of $A$ is at
      least $\cf\alpha$
   2. If $\beta_0\le\beta_1\le\dots\le\beta_\xi\le\dots,\xi<\gamma$, is a
      nondecreasing \gamma-sequence of ordinals in \alpha and 
      $\lim_{\xi\to\gamma}\beta_\xi=\alpha$, then $\cf\gamma=\cf\alpha$
   #+END_lemma
   #+BEGIN_proof
   1. The order-type of $A$ is the length of the increasing enumeration of $A$
      which is an increasing sequence with limit \alpha
   2. If $\gamma=\lim_{\nu\to\cf\gamma}\xi(\nu)$, then
      $\alpha=\lim_{\nu\to\cf\gamma}\beta_{\xi(\nu)}$, and the nondecreasing
      sequence $\la\beta_{\xi(\nu):\nu<\cf\gamma\ra}$ has an increasing
      subsequence of length $\le\cf\gamma$ with the same limit. Thus
      $\cf\alpha\le\cf\gamma$ 

      Let $\alpha=\lim_{\nu\to\cf\alpha}\alpha_\nu$. For each $\nu<\cf\alpha$,
      let $\xi(\nu)$ be the least \xi greater than all $\xi(\iota),\iota<\nu$
      s.t. $\beta_\xi>\alpha_\nu$. Since
      $\lim_{\nu\to\cf\alpha}\beta_{\xi(\nu)}=\alpha$ it follows that
      $\lim_{\nu\to\cf\alpha}\xi(\nu)=\gamma$ and so $\cf\gamma\le\cf\alpha$
   #+END_proof

   An infinite cardinal $\aleph_\alpha$ is /regular/ if
   $\cf\omega_{\alpha}=\omega_\alpha$. It's /singular/ if
   $\cf\omega_\alpha<\omega_\alpha$

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For every limit ordinal \alpha,$\cf\alpha$ is a regular cardinal
   #+END_lemma
   #+BEGIN_proof
   If \alpha is not a cardinal, then using a mapping of $\abs{\alpha}$ onto
   \alpha, one can construct a cofinal sequence in \alpha of length
   $\le\abs{\alpha}$. Therefore $\cf\alpha<\alpha$

   Since $\cf(\cf\alpha)=\cf(\alpha)$, it follows that $\cf\alpha$ is a cardinal
   and is regular
   #+END_proof

   Let \kappa be a limit ordinal. A subset $X\subset\kappa$ is /bounded/ if $\sup
   X<\kappa$ and /unbounded/ if $\sup X=\kappa$ 

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \kappa be an aleph
   1. If $X\subset\kappa$ and $\abs{X}<\cf\kappa$ then $X$ is bounded
   2. If $\lambda<\cf\kappa$ and $f:\lambda\to\kappa$ then the range of $f$ is
      bounded
   #+END_lemma
   It follows from 1 that every unbounded subset of a regular cardinal has
   cardinality \kappa
   #+BEGIN_proof
   1. from Lemma ref:lemma3.7
   2. If $X=\ran{f}$ then $\abs{X}\le\lambda$
   #+END_proof

   [[index:singular]]
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   An infinite cardinal \kappa is singular if and only if there exists a
   cardinal $\lambda<\kappa$ and a family $\{S_\xi:\xi<\lambda\}$ of subsets of
   \kappa s.t. $\abs{S_\xi}<\kappa$ for each $\xi<\lambda$ and
   $\kappa=\bigcup_{\xi<\lambda}S_\xi$. The least cardinal \lambda that
   satisfies the condition is $\cf\kappa$
   #+END_lemma
   #+BEGIN_proof
   If \kappa is singular, then there is an increasing sequence
   $\la\alpha_\xi:\xi<\cf\kappa\ra$ with $\lim_\xi\alpha_\xi=\kappa$. Let
   $\lambda=\cf\kappa$ and $S_\xi=\alpha_\xi$ for all $\xi<\lambda$

   If the condition holds, let $\lambda<\kappa$ be the least cardinal for which
   there is a family $\{S_\xi:\xi<\lambda\}$ s.t.
   $\kappa=\bigcup_{\xi<\lambda}S_\xi$ and $\abs{S_\xi}<\kappa$ for each
   $\xi<\lambda$. For every $\xi<\lambda$, let $\beta_\xi$ be the order-type of
   $\bigcup_{\nu<\xi}S_\nu$. The sequence $\la\beta_\xi:\xi<\lambda\ra$ is
   nondecreasing and by the minimality of \lambda, $\beta_\xi<\kappa$ ofr all
   $\xi<\lambda$. We shall show that $\lim_\xi\beta_\xi=\kappa$, thus proving
   that $\cf\kappa\le\lambda$

   Let $\beta=\lim_{\xi\to\lambda}\beta_\xi$. There is a one-to-one mapping $f$
   of $\kappa=\bigcup_{\xi<\lambda}S_\xi$ into $\lambda\times\beta$: if
   $\alpha\in\kappa$, let $f(\alpha)=(\xi,\gamma)$ where \xi is the least \xi
   s.t. \alpha\in S_\xi and \gamma is the order-type of $S_\xi\cap\alpha$. Since
   $\lambda<\kappa$ and $\abs{\kappa\times\beta}=\lambda\cdot\abs{\beta}$, it
   follows that $\beta=\kappa$
   #+END_proof

   The only cardinal inequality we have proved so far is Cantor's Theorem
   $\kappa<2^\kappa$. It follows that $\kappa<\lambda^\kappa$ for every
   $\lambda>1$
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is an infinite cardinal, then $\kappa<\kappa^{\cf\kappa}$
   #+END_theorem
   #+BEGIN_proof
   Let $F$ be a collection of \kappa functions from $\cf\kappa$ to
   \kappa:$F=\{f_\alpha:\alpha<\kappa\}$. It's enough to find
   $f:\cf\kappa\to\kappa$ that is different from all the $f_\alpha$. Let
   $\kappa=\lim_{\xi\to\cf\kappa}\alpha_\xi$. For $\xi<\cf\alpha$, let
   \begin{equation*}
   f(\xi)=\text{least }\gamma\text{ s.t. }\gamma\neq f_\alpha(\xi)
   \text{ for all }\alpha<\alpha_\xi 
   \end{equation*}
   Such \gamma exists since
   $\abs{\{f_\alpha(\xi):\alpha<\alpha_\xi\}}\le\abs{\alpha_\xi}<\kappa$.
   Obviously $f\neq f_\alpha$ for all $\alpha<\kappa$
   #+END_proof

   An uncountable cardinal \kappa is /weakly inaccessible/ if it's a limit
   cardinal and is regular. The existence of (weakly) inaccessible cardinals is
   not provable in $\zfc$.

   Note that if $\aleph_\alpha>\aleph_0$ is limit and regular, then
   $\aleph_\alpha=\cf\aleph_\alpha=\cf\alpha\le\alpha$, and so
   $\aleph_\alpha=\alpha$

   The least fixed point $\aleph_\alpha=\alpha$ has cofinality \omega:
   \begin{align*}
   \kappa=&\lim\la\omega,\omega_\omega,\omega_{\omega_\omega},\dots\ra=\lim_{n\to\omega}\kappa_n\\
   &\text{where }\kappa_0=\omega,\kappa_{n+1}=\omega_{\kappa_n}
   \end{align*}

** Exercises
   #+BEGIN_exercise
   Show that $\Gamma(\alpha\times\alpha)\le\omega^\alpha$
   #+END_exercise
   #+BEGIN_proof
   Note that
   $\gamma_{\alpha+1}=\gamma_\alpha+\alpha+\alpha+1=\gamma_\alpha+\alpha\cdot
   2+1$. 
   \begin{center}
   \begin{tikzpicture}
   \draw[->] (0,0) -- (3.5,0);
   \draw[->] (0,0) -- (0,3.5);
   \draw (2,0) -- (2,2) -- (0,2);
   \draw (2.6,0) -- (2.6,2.6) -- (0,2.6);
   \draw (2,0) node [anchor=north] {$\alpha$};
   \draw (2.6,0) node [anchor=north] {$\alpha+1$};
   \fill[black!40!white] (2,0) -- (2.6,0) -- (2.6,2.6) -- (0,2.6) -- (0,2)
   -- (2,2);
   \end{tikzpicture}
   \end{center}

   If $\gamma_\alpha\le\omega^\alpha$, then
   \begin{equation*}
   \gamma_{\alpha+1}\le\omega^\alpha+\alpha\cdot 2+1
   \end{equation*}
   Since $\alpha\cdot\omega\le\omega^\alpha$, 
   \begin{equation*}
   \gamma_{\alpha+1}\le\omega^\alpha+\alpha\cdot 2+1\le\omega^\alpha+\alpha\cdot\omega\le
   \omega^\alpha\cdot 2\le\omega^{\alpha+1}
   \end{equation*}
   
   #+END_proof

   #+BEGIN_exercise
   There is a well-ordering of the class of all finite sequences of ordinals
   s.t. for each \alpha, the set of all finite sequences in $\omega_\alpha$ is
   an initial segment and its order-type is $\omega_\alpha$
   #+END_exercise

   #+BEGIN_proof
   We need to show that $\Gamma(\omega_\alpha^\omega)=\omega_\alpha$, which is
   to show $\Gamma(\omega_\alpha^n)=\omega_\alpha$ for any $n\in\omega$.
   #+END_proof

   We say that a set $B$ is a /projection/ of a set $A$ if there is a mapping of
   $A$ onto $B$. Note that $B$ is a projection of $A$ if and only if there is a
   partition $P$ of $A$ such that $\abs{P}=\abs{B}$. If $\abs{A}\ge\abs{B}>0$,
   then $B$ is a projection of $A$. Conversely using the Axiom of Choice, one
   shows that if $B$ is a projection of $A$, then $\abs{A}\ge\abs{B}$. This
   cannot be proved without the Axiom of Choice
   
   #+BEGIN_exercise
   The set of all finite subsets of $\omega_\alpha$ has cardinality $\aleph_\alpha$
   #+END_exercise

   #+BEGIN_exercise
   $\omega_{\alpha+1}$ is a projection of $P(\omega_\alpha)$
   #+END_exercise
   #+BEGIN_proof
   Consider $f:P(\omega_\alpha\times\omega_\alpha)\to\omega_{\alpha+1}$. If
   $R\subset\omega_\alpha\times\omega_\alpha$ is a well-ordering, let
   $f(R)=\type(R)$ and $f(\omega_\alpha\times\omega_\alpha)=\omega_\alpha$
   #+END_proof
   #+BEGIN_exercise
   $\aleph_{\alpha+1}<2^{2^{\aleph_\alpha}}$
   #+END_exercise
   #+BEGIN_proof
   $\aleph_{\alpha+1}$ is a projection of $P(\aleph_\alpha)$. Hence
   \begin{equation*}
   \aleph_{\alpha+1}<2^{\aleph_{\alpha+1}}\le 2^{2^{\aleph_\alpha}}
   \end{equation*}
   #+END_proof
   #+ATTR_LATEX: :options [$\zf$]
   #+BEGIN_exercise
   Show that $\omega_2$ is not a countable union of countable sets.
   #+END_exercise
   #+BEGIN_proof
   Assume that
   #+END_proof
* Real Numbers
  The set of all real numbers $\R$ (the /real line/ or the /continuum/) is the
  unique ordered field in which every nonempty bounded set has a least upper bound.
  #+ATTR_LATEX: :options [Cantor]
  #+BEGIN_theorem
  The set of all real numbers is uncountable
  #+END_theorem
  #+BEGIN_proof
  Let us assume that the set $\R$ of all reals is countable, and let
  $c_0,\dots,c_n,n\in\N$ be an enumeration of $\R$.

  Let $a_0=c_0$ and $b_0=c_{k_0}$ where $k_0$ is the least $k$ s.t. $a_0<c_k$.
  For each $n$, let $a_{n+1}=c_{i_n}$, where $i_n$ is the least $i$ s.t.
  $a_n<c_i<b_n$, and $b_{n+1}=c_{k_n}$ where $k_n$ is the least $k$ s.t.
  $a_{n+1}<c_k<b_n$. If we let $a=\sup\{a_n:n\in\N\}$, then $a\neq c_k$ for all $k$
  #+END_proof
  
** The Cardinality of the Continuum
   Let $\fc$ denote the cardinality of $\R$. As the set $\Q$ of all rational
   numbers is dense in $\R$, every real number $r$ is equal to
   $\sup\{q\in\Q:q<r\}$ and because $\Q$ is countable, it follows that
   $\fc\le\abs{P(\Q)}=2^{\aleph_0}$ 

   Let $\bC$ (the /Cantor Set/) be the set of all reals of the form 
   $\sum_{n=1}^\infty a_n/3^n$ where each $a_n=0$ or 2. $\bC$ is obtained by
   removing from the closed interval $[0,1]$. $\bC$ is in a one-to-one
   correspondence with the set all \omega-sequences of 0's and 2's and so
   $\abs{\bC}=2^{\aleph_0}$

   Therefore $\fc\ge 2^{\aleph_0}$ and so by the Cantor-Berstein Theorem we have
   \begin{equation*}
   \fc=2^{\aleph_0}
   \end{equation*}

   In $\zfc$ every infinite cardinal is an aleph and so
   $2^{\aleph_0}\ge\aleph_1$. Cantor's conjecture then becomes the statement 
   \begin{equation*}
   2^{\aleph_0}=\aleph_1
   \end{equation*}
   known as the /Continuum Hypothesis/ (CH).
** The Ordering of $\R$
   A linear ordering $(P,<)$ is /complete/ if every nonempty boudned subset of $P$
   has a least upper bound.
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A lienar ordering $(P,<)$ is /dense/ if for all $a<b$ there exists a $c$ s.t.
   $a<c<b$

   A set $D\subset P$ is a /dense subset/ if for all $a<b$ in $P$ there exists a
   $d\in D$ s.t. $a<d<b$.

   An ordered set is /unbounded/ if it has neither a least nor a greatest element
   #+END_definition

   #+ATTR_LATEX: :options [Cantor]
   #+BEGIN_theorem
   1. Any two countable unbounded dense linearly ordered sets are isomorphic
   2. $(\R,<)$ is the unique complete linear ordering that has a countable dense
      subset isomorphic to $(\Q,<)$
   #+END_theorem
   #+BEGIN_proof
   1. Let $P_1=\{a_n:n\in\N\}$ and $P_2=\{b_n:n\in\N\}$ be two such linearly ordered
      sets. We construct an isomorphism $f:P_1\to P_2$ in the following way: we
      first define $f(a_0)$, then $f^{-1}(b_0)$, then $f(a_1)$, then $f^{-1}(b_1)$,
      etc., so as to keep $f$ order-preserving. For example, to define $f(a_n)$, if
      it's not yet defined, we let $f(a_n)=b_k$ where $k$ is the least index s.t.
      $f$ remains order-preserving (such a $k$ always exists because $f$ has been
      defined for only finitely many $a\in P_1$) 
   2. To prove the uniqueness of $\R$, let $C$ and $C'$ be two complete dense
      unbounded linearly ordered sets, let $P$ and $P'$ be dense in $C$ and
      $C'$, respectively, and let $f$ be an isomorphism of $P$ onto $P'$. Then
      $f$ can be extended to an isomorphism $f^*$ of $C$ and $C'$: For $x\in C$
      let $f^*(C)=\sup\{f(p):p\in P\text{ and }p\le x\}$
   #+END_proof

   The existence of $(\R,<)$ is proved by means of *Dedekind cuts* in $(\Q,<)$.
   The following theorem is a general version of this construction:
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let $(P,<)$ be a dense unbounded linearly ordered set. Then there is a
   complete unbounded linearly ordered set $(C,\prec)$ s.t.
   1. $P\subset C$ and $<$ and $\prec$ agree on $P$
   2. $P$ is dense in $C$
   #+END_theorem
   #+BEGIN_proof
   A *Dedekind cut* in $P$ is a pair $(A,B)$ of disjoint nonempty subsets of $P$
   s.t.
   1. $A\cup B=P$
   2. $a<b$ for any $a\in A$ and $b\in B$
   3. $A$ does not have a greatest element 
     
      
   Let $C$ be the set of all Dedekind cuts in $P$ and let
   $(A_1,B_1)\preceq(A_2,B_2)$ if $A_1\subset A_2$. The set $C$ is complete: If
   $\{(A_i,B_i):i\in I\}$ is a nonempty bounded subset of $C$, then
   $(\bigcup_{i\in I}A_i,\bigcap_{i\in I}B_i)$ is its supremum.

   For $p\in P$, let
   \begin{equation*}
   A_p=\{x\in P:x<p\},\quad B_p=\{x\in P:x\ge P\}
   \end{equation*}
   Then $P'=\{(A_p,B_p):p\in P\}$ is isomorphic to $P$ and is dense in $C$
   #+END_proof
** Suslin's Problem
   The real line is, up to isomorphism, the unique linearly ordered set that is
   dense, unbounded, complete and contains a countable dense subset.

   Since $\Q$ is dense in $\R$, every nonempty open interval of $\bR$ contains
   a rational number. Hence if $S$ is a disjoint collection of open intervals,
   $S$ is at most countable. ($f:S\to\Q$ is injective)

   Let $P$ be a dense linearly ordered set. If every disjoint collection of open
   intervals in $P$ is at most countable, then we say that $P$ satisfies the
   *countable* *chain condition*

   /*Suslin's Problem*. Let $P$ be a complete dense unbounded linearly ordered/
   /set that satisfies the countable chain condition. Is $P$ isomorphic to the/
   /real line?/

   This question cannot be decided in $\zfc$
** The Topology of the Real Line
   The real line is a metric space with the metric $d(a,b)=\abs{a-b}$. Its
   metric topology coincides with the order topology of $(\R,<)$. Since $\Q$ is
   a dense set in $\R$ and since every Cauchy sequence of real numbers
   converges, $\R$ is a separable complete metric space. (A metric space is
   *separable* if it has a countable dense set; it is *complete* if every Cauchy
   sequence converges)

   Every open sets is the union of open intervals with rational endpoints.[fn:union] 
   
   Every open interval has cardinality $\fc$

   A nonempty closed set is *perfect* if it has no isolated points.
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Every perfect set has cardinality $\fc$
   #+END_theorem

   #+BEGIN_proof
   Given a perfect set $P$, we want to find a one-to-one function
   $F:\{0,1\}^\omega\hookrightarrow P$. Let $S$ be the set of all fintie
   sequences of 0's and 1's. By induction on the length of $s\in S$ one can
   fined closed intervals $I_s$ s.t. for each $n$ and all $s\in S$ of length of
   $n$,
   1. $I_s\cap P$
   2. the diameter of $I_s$ is $\le 1/n$
   3. $I_{s^\frown 0}\subset I_s,I_{s^\frown 1}\subset I_s$ and
      $I_{s^\frown 0}\cap I_{s^\frown 1}=\emptyset$



   For each $f\in\{0,1\}^\omega$, the set 
   $P\cap\bigcap_{n=0}^\infty I_{f\restriction n}$ has exactly one element
   #+END_proof
   
   #+ATTR_LATEX: :options [Cantor-Bendixson]
   #+BEGIN_theorem
   If $F$ is an uncountable closed set then $F=P\cup S$ where $P$ is perfect and
   $S$ is at most countable
   #+END_theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $F$ is a closed set, then either $\abs{F}\le\aleph_0$ or
   $\abs{F}=2^{\aleph_0}$
   #+END_corollary
   #+BEGIN_proof
   For every $A\subset\R$, let
   \begin{equation*}
   A'=\text{the set of all limit points of } A
   \end{equation*}
   $A'$ is closed, and if $A$ is closed then $A'\subset A$. Thus we let
   \begin{align*}
   &F_0=F,\quad F_{\alpha+1}=F_\alpha'\\
   &F_\alpha=\displaystyle\bigcap_{\gamma<\alpha}F_\gamma\text{ if }\alpha>0
   \text{ is a limit ordinal} 
   \end{align*}
   Since $F_0\supset F_1\supset\dots\supset F_\alpha\supset\dots$, there exists
   an ordinal \theta s.t. $F_\alpha=F_\theta$ for all $\alpha\ge\theta$. We let
   $P=F_\theta$ 

   If $P$ is nonempty, then $P'=P$ and so it's perfect. Thus the proof is
   completed by showing that $F-P$ is at most countable.

   Let $\la J_k:k\in\N\ra$ be an enumeration of rational intervals. We have
   $F-P=\bigcup_{\alpha<\theta}(F_\alpha-F_\alpha')$; hence if $a\in F-P$, then
   there is a unique \alpha s.t. $a$ is an isolated point of $F_\alpha$. We let
   $k(a)$ be the least $k$ s.t. $a$ is the only opoint of $F_\alpha$ in the
   interval $J_k$. Note that if $\alpha\le\beta$, $b\neq a$ and $b\in
   F_\beta-F_\beta'$, then $b\not\in J_{k(a)}$. Thus the correspondence
   $a\mapsto k(a)$ is one-to-one
   #+END_proof
   A set of reals is called *nowhere dense* if its closure has empty interior.

   #+ATTR_LATEX: :options [The Baire Category Theorem]
   #+BEGIN_theorem
   If $D_0,D_1,\dots,D_n,\dots,n\in\N$ are dense open sets of reals, then the
   intersection $D=\bigcap_{n=0}^\infty D_n$ is dense in $\R$
   #+END_theorem



[fn:union] Check [[https://math.stackexchange.com/questions/318299/any-open-subset-of-bbb-r-is-a-at-most-countable-union-of-disjoint-open-interv][StackExchange]]
** Borel Sets
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   An *algebra of sets* is a collection of $\cals$ of subsets of a given set $S$
   s.t.
   1. $S\in\cals$
   2. if $X\in\cals$ and $Y\in\cals$ then $X\cup Y\in\cals$
   3. if $X\in\cals$ then $S-X\in\cals$


   A *\sigma-algebra* is additionally closed under countable unions (and
   intersections)
   4. [@4] if $X_n\in\cals$ for all $n$, then $\bigcup_{n=0}^\infty X_n\in\cals$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A set of reals $B$ is *Borel* if it belongs to the smallest \sigma-algebra
   $\calb$ of sets of reals that contains all open sets.
   #+END_definition

* The Axiom of Choice and Cardinal Arithmetic
  #+ATTR_LATEX: :options [Zermelo's Well-Ordering Theorem]
  #+BEGIN_theorem
  label:thm5.1
  Every set can be well-ordered
  #+END_theorem

  #+BEGIN_proof
  Let $A$ be a set. To well order $A$, it suffices to construct a transfinite
  one-to-one sequence $\la a_\alpha:\alpha<\theta\ra$ that enumerates $A$. That we can
  do by induction, using a choice function $f$ for the family $S$ of all nonempty
  subsets of $A$. We let for every \alpha 
  \begin{equation*}
  a_\alpha=f(A-\{a_\xi:\xi<\alpha\})
  \end{equation*}
  if $A-\{a_\xi:\xi<\alpha\}$ is nonempty. Let \theta be the least ordinal s.t.
  $A=\{a_\xi:\xi<\theta\}$. Clearly $\la a_\alpha:\alpha<\theta\ra$ enumerates $A$
  #+END_proof

  In fact, Zermelo's Theorem ref:thm5.1 is equivalent to the Axiom of Choice. For
  any family $S$ of nonempty sets, well-order $\bigcup S$ and let $f(X)$ be the
  least element of $X$ for every $X\in S$

  Of particular importance is the fact that the set of all real numbers can be
  well-ordered. It follows that $2^{\aleph_0}$ is a cardinal and
  $2^{\aleph_0}\ge\aleph_1$ 

  If every set can be well-ordered, then every infinite set has a countable
  subset: Well-order the set and take the first \omega elements.

  Dealing with cardinalities of sets is much easier when we have $\AC$. In the
  first place, any two sets have comparable cardinals. Another consequence is
  \begin{equation*}
  \textif{if } f\textit{ maps }A\textit{ onto }B\textit{ then }\abs{B}\le\abs{A}
  \end{equation*}

  This is done by choosing one element from $f_{-1}(\{b\})$ for each $b\in B$

  Another consequence of the $\AC$ is 
  \begin{equation*}
  \textit{The union of a countable family of countable sets is countable}
  \end{equation*}
  Let $A_n$ be a countable set for each \(n\in\N\). For each $n$, let us /choose/
  an enumeration \(\la a_{n,k}:k\in\N\ra\) of $A_n$. This gives us a projection
  of \(\N\times\N\) onto \(\bigcup_{n=0}^{\infty}A_n\)

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  $\abs{\bigcup S}\le\abs{S}\cdot\sup\{\abs{X}:X\in S\}$
  #+END_lemma

  #+BEGIN_proof
  Let \(\kappa=\abs{S}\) and \(\lambda=\sup\{\abs{X}:X\in S\}\). We have
  \(S=\{X_\alpha:\alpha<\kappa\}\) and for each \(\alpha<\kappa\) we choose an enumeration
  \(X_\alpha=\{a_{\alpha,\beta}:\beta<\lambda_\alpha\}\) where \(\lambda_\alpha<\lambda\).
  Again we have a projection
  \begin{equation*}
  (\alpha,\beta)\mapsto a_{\alpha,\beta}
  \end{equation*}
  of \(\kappa\times\lambda\) onto \(\bigcup S\)
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  Every \(\aleph_{\alpha+1}\) is a regular cardinal
  #+END_corollary

  #+BEGIN_proof
  This is because otherwise \(\omega_{\alpha+1}\) would be the union of at most
  \(\aleph_\alpha\) sets of cardinality at most \(\aleph_{\alpha}\). 

  Suppose $\omega_{\alpha+1}$ is not regular and hence
  $\cf(\omega_{\alpha+1})\le\omega_{\alpha}$. Consider a cofinal increasing
  \(\omega_\alpha\)-sequence $\la\beta_\xi:\xi<\omega_\alpha\ra$ s.t. 
  \(\lim_{\xi\to\omega_\alpha}\beta_\xi=\omega_{\alpha+1}\).

  Note that \(\aleph_\alpha\cdot\aleph_\alpha=\aleph_\alpha\)
  #+END_proof

** Using the Axiom of Choice in Mathematics
   #+ATTR_LATEX: :options [Zorn's Lemma]
   #+BEGIN_theorem
   If \((P,<)\) is a nonempty partially ordered set s.t. every chain in $P$ has an
   upper bound, then $P$ has a maximal element
   #+END_theorem

   #+BEGIN_proof
   We let by induction
   \begin{equation*}
   a_\alpha=\text{ an element of }P\text{ s.t. }a_\alpha>a_\xi
   \text{ for every } \xi<\alpha\text{ if there is one}
   \end{equation*}
   If \(\alpha>0\) is a limit ordinal, then \(C_\alpha=\{a_\xi:\xi<\alpha\}\) is a
   chain in $P$ and \(a_\alpha\) exists by the assumption. Eventually, there is
   a \theta s.t. there is no \(a_{\theta+1}\in P,a_{\theta+1}>a_{\theta}\). Thus
   $a_\theta$ is a maximal element of $P$
   #+END_proof
   
** The Countable Axiom of Choice
   *The Countable Axiom of Choice*. /Every countable family of nonempty sets has a/
   /choice function/

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Countable \(\AC\) implies that the union of countably many
   countable sets is countable
   #+END_proposition
   #+BEGIN_proof
   Well order the countable sets.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Countable \(\AC\) implies \(\aleph_1\) is regular
   #+END_proposition


   *The Principle of Dependent Choices (DC)*. /If $E$ is a binary relation on a/
   /nonempty set $A$, and if for every \(a\in A\) there exists \(b\in A\) s.t./
   /\(bEa\), thenthere is a sequence \(a_0,\dots,a_n,\dots\) in $A$ s.t./
   \begin{equation*}
   a_{n+1}Ea_n\e\text{ for all }n\in\N
   \end{equation*}
   

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. A linear ordering $<$ of a set $P$ is a well-ordering of $P$ if and only
      if there is no infinite descending sequence 
      \begin{equation*}
      a_0>a_1>\dots>a_n>\dots
      \end{equation*}
      in $A$
   2. A relation $E$ on $P$ is well-founded if and only if there is no infinite
      sequence \(\la a_n:n\in\N\ra\) in $P$ s.t.
      \begin{equation*}
      a_{n+1}Ea_n\e\text{ for all }n\in\N
      \end{equation*}
   #+END_lemma

   #+BEGIN_proof
   1 is a special case of 2.
   #+END_proof

   
** Cardinal Arithmetic
   In the presence of the \(\AC\), every set can be well-ordered and so every
   infinite set has the cardinality of some \(\aleph_\alpha\).

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \(2\le\kappa\le\lambda\) and \(\lambda\) is infinite, then \(\kappa^\lambda=2^\lambda\)
   #+END_lemma
   #+BEGIN_proof
   \begin{equation*}
   2^\lambda\le\kappa^\lambda\le(2^\kappa)^\lambda=2^{\lambda\cdot\kappa}=2^\lambda
   \end{equation*}
   #+END_proof

   If \kappa and \lambda are infinite and \(\lambda<\kappa\), first if \(2^\lambda>\kappa\), then we
   have \(\kappa^\lambda=2^\lambda\) but if \(2^\lambda<\kappa\) (because
   \(\kappa^\lambda\le\kappa^\kappa=2^\kappa\)) we can only conclude
   \begin{equation*}
   \kappa\le\kappa^\lambda\le 2^\kappa
   \end{equation*}

   If \lambda is a cardinal and \(\abs{A}\ge\lambda\) let
   \begin{equation*}
   [A]^\lambda=\{X\subseteq A:\abs{X}=\lambda\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \(\abs{A}=\kappa\ge\lambda\), then the set \([A]^\lambda\) has
   cardinality $\kappa^\lambda$
   #+END_lemma

   #+BEGIN_proof
   On the one hand, every \(f:\lambda\to A\) is a subset of \(\lambda\times A\),
   and \(\abs{f}=\lambda\). Thus \(\kappa^\lambda\le\abs{[\lambda\times A]^\lambda}=\abs{[A]^\lambda}\).
   #+END_proof

** Infinite Sums and Products
   Let \(\kappa_i:i\in I\) be an indexed set of cardinal numbers. We define
   \begin{equation*}
   \displaystyle\sum_{i\in I}\kappa_i=\abs{\displaystyle\bigcup_{i\in I}X_i}
   \end{equation*}
   where \(\{X_i:i\in I\}\) is a disjoint family of sets s.t.
   \(\abs{X_i}=\kappa_i\) for each \(i\in I\)

   Note that if \kappa and \lambda are cardinals and \(\kappa_i=\kappa\) for each
   \(i<\lambda\), then
   \begin{equation*}
   \displaystyle\sum_{i<\lambda}\kappa_i=\lambda\cdot\kappa
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \lambda is an infinite cardinal and \(\kappa_i>0\) for each \(i<\lambda\), then
   \begin{equation*}
   \displaystyle\sum_{i<\lambda}\kappa_i=\lambda\cdot\sup_{i<\lambda}\kappa_i
   \end{equation*}
   #+END_lemma

   #+BEGIN_proof
   Let \(\kappa=\sup_{i<\lambda}\kappa_i\) and \(\sigma=\sum_{i<\lambda}\kappa_i\). On the
   one hand, since \(\kappa_i\le\kappa\) for all \(i\), we have
   \(\sum_{i<\lambda}\kappa\le\lambda\cdot\kappa\). On the other hand, since
   \(\kappa_i\ge1\) for all $i$, we have \(\lambda=\sum_{i<\lambda}1\le\sigma\) and
   since \(\sigma\ge\kappa_i\) for all $i$, we have
   \(\sigma\ge\sup_{i<\lambda}\kappa_i=\kappa\). Therefore \(\sigma\ge\lambda\cdot\kappa\)
   #+END_proof
   In particular, if $\lambda\le\sup_{i<\lambda}\kappa_i$, we have
   \begin{equation*}
   \displaystyle\sum_{i<\lambda}\kappa_i=\sup_{i<\lambda}\kappa_i
   \end{equation*}

   Thus we can characterize singular cardinals as follows: An infinite cardinal
   \kappa is singular just in case 
   \begin{equation*}
   \kappa=\displaystyle\sum_{i<\lambda}\kappa_i
   \end{equation*}
   where \(\lambda<\kappa\) and for each $i$, \(\kappa_i<\kappa\)

   An infinite product of cardinals is defined using infinite products of sets.
   If \(\{X_i:i\in I\}\) is a family of sets, then the *product* is defined as
   \begin{equation*}
   \displaystyle\prod_{i\in I}X_i=\{f:f\text{ is a function on }I\text{ and }
   f(i)\in X_i\text{ for each }i\in I\}
   \end{equation*}
   Note that if some \(X_i\) is empty, the product is empty. If
   \(\{\kappa_i:i\in I\}\) is a family of cardinal numbers, we define
   \begin{equation*}
   \displaystyle\prod_{i\in I}\kappa_i=\abs{\displaystyle\prod_{i\in I}X_i}
   \end{equation*}
   where \(\{X_i:i\in I\}\) is a family of sets s.t. \(\abs{X_i}=\kappa_i\) for
   each \(i\in I\)

   If \(\kappa_i=\kappa\) for each \(i\in I\), and \(\abs{I}=\lambda\), then
   \(\prod_{i\in I}\kappa_i=\kappa^\lambda\)
* COMMENT Models of Set - Sertraline
** Some mathematical logic
   #+ATTR_LATEX: :options [Gdels second incompleteness theorem]
   #+BEGIN_theorem
   If a consistent recursive axiom set $T$ contains $\zfc$, then
   \begin{equation*}
   T\not\vdash\con(t)
   \end{equation*}
   especially, $\zfc\not\vdash\con(\zfc)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose $(M,E_M)$ and $(N,E_N)$ are two models of set theory, then
   1. if for any formula \sigma, $M\models\sigma$ if and only if
      $N\models\sigma$, then $M$ and $N$ are \tf{elementary equivalent}, denoted
      by $M\equiv N$
   2. If bijection $f:M\to N$ satisfies: for any $a,b\in M$, $aE_Mb$ iff
      $f(a)E_Nf(b)$, then $f:M\cong N$ is an \tf{isomorphism}
   3. If $M\subseteq N$ and $E_M=E_N\restriction M$, then $M$ is $N$'s submodel
   4. If $M$ is isomorphic to a submodel of $N$ by injection $f$, and for any
      formula $\varphi(x_1,\dots,x_n)$, for any $a_1,\dots,a_n\in M$, 
      $M\models\varphi[a_1,\dots,a_n]$ iff
      $N\models\varphi[f(a_1),\dots,f(a_n)]$, then $f$ is called an
      \tf{elementary embedding} from $M$ to $N$, written as $f:M\prec N$
   5. If $M\subseteq N$ and $M\prec N$, then $M$ is a \tf{elementary submodel}
      of $N$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose $N\models\zfc,M\subseteq N$, then $M\prec N$ iff
   $\forall\varphi(x,x_1,\dots,x_n)$, $\forall(a_1,\dots,a_n)\in M$, if 
   $\exists a\in N$ s.t. $N\models\varphi[a,a_1,\dots,a_n]$, then $\exists a\in
   M$ s.t. 
   $M\models\varphi[a,a_1,\dots,a_n]$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose $(M,E)\models\zfc$
   1. $h_\varphi:M^n\to M$ is \varphi's \tf{Skolem function} if 
      $\forall a_1,\dots,a_n\in M$, if $\exists a\in M$ s.t.
      $M\models\varphi[a,a_1,\dots,a_n]$, then
      $M\models\varphi[h_\varphi(a_1,\dots,a_n),a_1,\dots,a_n]$ . requires \ac
   2. Let $\calh=\{h_\varphi\mid\varphi \text{is a formula on set theory}\}$. For
      any $S\subseteq M$, \tf{Skolem hull} $\calh(S)$ is the smallest set
      consisting of $S$ and closed under $\calh$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $N\models\zfc,S\subseteq N$, if $M=\calh(S)$, then $M\prec N$
   #+END_lemma

   #+ATTR_LATEX: :options [Lwenheim-Skolem theorem]
   #+BEGIN_theorem
   Suppose $N\models\zfc$ and is infinite, then there is a model $M$ s.t.
   $\abs{M}=\omega$ and $M\prec N$
   #+END_theorem
** Cumulative Hierarchy
   This section works in \zfm(a.k.a. $\zf-\text{axiom of foundation}$)

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any \alpha, define sequence $V_\alpha$
   1. $V_0=\emptyset$
   2. $V_{\alpha+1}=\calp(V_\alpha)$
   3. For any limit ordinal \lambda, $V_\lambda=\bigcup_{\beta<\lambda}V_\beta$

      
   And $\wf=\displaystyle\bigcup_{\alpha\in\on}V_\alpha$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $V_\alpha$ is transitive
   2. if $\xi\le\alpha$, then $V_\xi\subseteq V_\alpha$
   3. if \kappa is inaccessible cardinal, then $\abs{V_\kappa}=\kappa$
   #+END_lemma

   #+BEGIN_proof
   3. Obviously $\kappa\le V_\kappa$. Since \kappa is inaccessible, then for any
      $\alpha<\kappa$, $\abs{V_\alpha}<\kappa$.
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any set $x\in\wf$, 
   \begin{equation*}
   \rank(x)=\min\{\beta\mid x\in V_{\beta+1}\}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $V_\alpha=\{x\in\wf\mid\rank(x)<\alpha\}$
   2. \wf is transitive
   3. For any $x,y\in\wf$, if $x\in y$, then $\rank(x)<\rank(y)$
   4. for any $y\in\wf$, $\rank(y)=\sup\{\rank(x)+1\mid x\in y\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Supoose \alpha is an ordinal
   1. $\alpha\in\wf$ and $\rank(\alpha)=\alpha$
   2. $V_\alpha\cap\on=\alpha$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. If $x\in\wf$, then $\bigcup x,\calp(x),\{x\}\in\wf$, and their ranks are
      all less than $\rank(x)+\omega$
   2. If $x,y\in\wf$, then $x\times y,x\cup y,x\cap y,\{x,y\},(x,y),x^y\in\wf$,
      and their ranks are all less than $\rank(x)+\rank(y)+\omega$
   3. $\Z,\Q,\R\in V_{\omega+\omega}$
   4. for any set $x$, $x\in\wf$ iff $x\subset\wf$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose \ac
   1. for any group $G$, there exists group $G'\cong G$ in \wf
   2. for any topological space $T$, there exists $T'\cong T$ in \wf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Binary relation $<$ on set $A$ is \tf{well-founded} if for any nonempty
   $X\subseteq A$, $X$ has minimal element under $<$
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $A\in\wf$, then $\in$ is a well-founded relation on $A$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If set $A$ is transitive and $\in$ is well-founded on $A$, then $A\in\wf$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any set $x$, there is a smallest transitive set $\trcl{x}$ s.t.
   $x\subseteq\trcl{x}$ 
   #+END_lemma

   #+BEGIN_proof
   \begin{align*}
   x_0&=x\\
   x_{n+1}&=\bigcup x_n\\
   \trcl{x}&=\displaystyle\bigcup_{n<\omega}x_n
   \end{align*}
   #+END_proof

   $\trcl{x}$ is called \tf{transitive closure} of $x$


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Without axiom of power set
   1. if $x$ is transitive, then $\trcl{x}=x$
   2. if $y\in x$, then $\trcl{y}\subseteq\trcl{x}$
   3. $\trcl{x}=x\cup\bigcup\{\trcl{y}\mid y\in x\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any set $X$, the following are equivalent
   1. $X\in\wf$
   2. $\trcl{X}\in\wf$
   3. $\in$ is a well-founded relation on $\trcl{X}$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following propositions are equivalent
   1. Axiom of foundation
   2. For any set $X$, $\in$ is a well-founded relation on $X$
   3. $\tf{V}=\wf$
   #+END_theorem
** Relativization
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \tf{M} be a class \varphi a formula, the \tf{relativization} of \varphi
   to \tf{M} is $\varphi^{\tf{M}}$ defined inductively
   \begin{align*}
   (x\in y)^{\cm}&\leftrightarrow x=y\\
   (x\in y)^{\cm}&\leftrightarrow x\in y\\
   (\varphi\to\psi)^{\cm}&\leftrightarrow \varphi^{\cm}\to\psi^\cm\\
   (\neg\varphi)^\cm&\leftrightarrow\neg\varphi^\cm\\
   (\forall x\varphi)^\cm&\leftrightarrow(\forall x\in\cm)\varphi^\cm
   \end{align*}
   #+END_definition

   Note $\varphi^\cv=\varphi$ and
   \begin{equation*}
   f^\cm=\{(x_1,\dots,x_n,x_{n+1})\in\cm\mid\varphi^\cm(x_1,\dots,x_n,x_{n+1})\}
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any theory $T$, any class $\cm$, $\cm\models T$ iff for any axiom
   $\varphi$ of $T$, $\varphi^\cm$ holds
   #+END_definition


   #+ATTR_LATEX: :options [\zfm]
   #+BEGIN_theorem
   $\wf\models\zf$
   #+END_theorem

   #+BEGIN_proof
   * \tf{Axiom of existence}

     $(\exists x(x=x))^\cm\leftrightarrow\exists x\in\cm(x=x)$, which is
     equivalent to \cm being nonempty
   * \tf{Axiom of extensionality}

     \begin{gather*}
     \forall X\forall Y\forall u((u\in X\leftrightarrow u\in Y)\to X=Y)^\cm
     \Leftrightarrow\\
     \forall X\in\cm\forall Y\in\cm\forall u\in\cm
     ((u\in X\leftrightarrow u\in Y)\to X=Y)
     \end{gather*}

     \begin{lemma}
     If $\cm$ is transitive, then axiom of extensionality holds in \cm
     \end{lemma}

   * \tf{Axiom schema of specification}

     \begin{equation*}
     \forall X\in\cm\exists Y\in\cm\forall u\in\cm(u\in Y\leftrightarrow
     u\in X\wedge\varphi^\cm(u))
     \end{equation*}

     Since for any $X\in\wf$, $\calp(X)\subseteq \wf$
   * \tf{Axiom of paring}
   * \tf{Axiom of union}
   * \tf{Axiom of power set}

     \begin{equation*}
     \forall X\in\cm\exists Y\in\cm\forall u\in\cm(u\in Y\leftrightarrow(u\subseteq X)^\cm)
     \end{equation*}
     and 
     \begin{equation*}
     (u\subseteq X)^\cm\leftrightarrow\forall x\in\cm(x\in u\to x\in X)
     \leftrightarrow u\cap\cm\subseteq X
     \end{equation*}
   * \tf{Axiom of foundation}
   * \tf{Axiom schema of replacement}
   #+END_proof 
** Absoluteness
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any formula $\psi(x_1,\dots,x_n)$ and any class \cm,\cn, 
   $\cm\subseteq \cn$, if
   \begin{equation*}
   \forall x_1\dots\forall x_n\in\cm(\psi^\cm(x_1,\dots,x_n)
   \leftrightarrow\psi^\cn(x_1,\dots,x_n))
   \end{equation*}
   then $\psi(x_1,\dots,x_n)$ is \tf{absolute} for \cm,cn. If $\cn=\cv$, then
   \psi is \tf{absolute} for \cm
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose $\cm\subseteq\cn$ and \varphi,\psi are formulas, then
   1. if \varphi,\psi are absolute for \cm,cn, then so are
      $\neg\varphi,\varphi\to\psi$ 
   2. if \varphi doesn't contain any quantifiers, then \varphi is absolute for
      any \cm
   3. if \cm,\cn  are transitive and \varphi is absolute for them, then so are
      $\forall x\in y\varphi$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\Delta_0$ formula
   1. $x=y,x\in y$ are $\Delta_0$ formulas
   2. if \varphi,\psi are $\Delta_0$, then so are $\neg\varphi,\varphi\to\psi$
   3. if $\varphi$ is $\Delta_0$, $y$ is any set, then $(\forall x\in y)\varphi$
      is $\Delta_0$
      

   If \varphi is $\Delta_0$, then $\exists x_1\dots\exists x_n\varphi$ is
   $\Sigma_1$ formula, $\forall x_1\dots\forall x_n\varphi$ is $\Pi_1$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\cm\subseteq\cn$ are both transitive, $\psi(x_0,\dots,x_n)$ is a formula,
   then
   1. if \psi is $\Delta_0$, then it's absolute for \cm,cn
   2. if \psi is $\Sigma_1$, then
      \begin{equation*}
      \forall x_1\dots x_n(\psi^\cm(x_1,\dots,x_n)\to\psi^\cn(x_1,\dots,x_n))
      \end{equation*}
   3. if \psi is $\Pi_1$, then
      \begin{equation*}
      \forall x_1\dots x_n(\psi^\cn(x_1,\dots,x_n)\to\psi^\cm(x_1,\dots,x_n))
      \end{equation*}
   #+END_lemma
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\cm\subseteq\cn$, $\cm\models\Sigma,\cn\models\Sigma$ and
   \begin{equation*}
   \Sigma\vdash\forall x_1\dots\forall x_n(\varphi(x_1,\dots,x_n)\leftrightarrow
   \psi(x_1,\dots,x_n))
   \end{equation*}
   then \varphi is absolute for \cm,\cn if and only if \psi is absolute for \cm,\cn
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Suppose $\cm\subseteq\cn$, $f(x_1,\dots,x_n)$ is a function. $f$ is
   \tf{absolute} for \cm and \cn if and only if $\varphi(x_1,\dots,x_n,x_{n+1})$
   defining $f$ is absolute.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Following relations and functions can be defined in
   $\zfmm-\text{Pow}-\text{Inf}$ and are equivalent to some $\Delta_0$ formulas.
   So they are absolute for any transitive model \cm on 
   $\zfmm-\text{Pow}-\text{Inf}$
   1. $x\in y$
   2. $x=y$
   3. $x\subset y$
   4. $\{x,y\}$
   5. $\{x\}$

   6. $(x,y)$
   7. $\emptyset$
   8. $x\cup y$
   9. $x-y$
   10. $x\cap y$
   11. $x^+$
   12. $x$ is a transitive set
   13. $\bigcup x$
   14. $\bigcap x$ ($\bigcap\emptyset=\emptyset$)
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Absoluteness is closed under operation composition
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Following relations and functions are absolute for any transitive model \cm on 
   $\zfmm-\text{Pow}-\text{Inf}$
   1. $z$ is an ordered pair
   2. $A\times B$
   3. $R$ is a relation
   4. $\dom{R}$
   5. $\ran{R}$
   6. $f$ is a function
   7. $f(x)$
   8. $f$ is injective
   #+END_theorem
** Relative consistence of the axiom of foundation
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose transitive class $\cm\models\zfmm-\text{Pow}-\text{inf}$ and
   $\omega\in\cm$, then the axiom of infinity is true in \cm. Hence the axiom of
   infinity is true in \wf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:7.5.2
   Let $T$ be a theory of set theory language and \Sigma a set of sentences.
   Suppose \cm is a class and $T\vdash\cm\neq\emptyset$, then if
   $\cm\models_T\Sigma$, then
   1. for any sentences \varphi, if $\Sigma\vdash\varphi$, then
      $T\vdash\varphi^\cm$
   2. if $T$ is consistent, then so is $\text{Cn}(\Sigma)$
   #+END_theorem


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The axiom of foundation is consistent with \zfm.
   #+END_theorem

   #+BEGIN_proof
   By ref:7.5.2, let T be \zfm, \Sigma be \zf and \cm be \wf
   #+END_proof

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_lemma
   Suppose transitive model $\cmm\models\zfmm-\text{Pow}-\text{Inf}$. If
   $X,R\in\cm$ and $R$ is a well-order on $X$, then
   \begin{equation*}
   (R\text{ is a well-order on }X)^\cmm
   \end{equation*}
   #+END_lemma

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_theorem
   $V_\omega\models\zfc-\text{Inf}+\neg\text{Inf}$
   #+END_theorem
   #+BEGIN_proof
   For any $X\in V_\omega$, $X$ is finite hence there is a well-ordering on $X$
   #+END_proof

   \begin{corollary}
   $\con{\zfmm}\to\con{\zfc-\text{Inf}+\neg\text{Inf}}$
   \end{corollary}
** Induction and recursion based on well-order relation
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is a well-founded relation on $\bX$ if and only if
   \begin{equation*}
   \forall U\subset\bX(U\neq\emptyset\to\exists y\in U(\neg\exists z\in U(z\bR y)))
   \end{equation*}
   #+END_definition


   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Relation $\bR$ is \tf{set-like} on $\bX$ iff for any $x\in\bX$,\par
   $\{y\in\bX\mid y\bR x\}$ is a set
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\bR$ is a set-like relation on $\bX$ and $x\in \bX$, define
   \begin{align*}
   \pred^0(\bX,x,\bR)&=\{y\in\bX\mid y\bR x\}\\
   \pred^{n+1}(\bX,x,bR)&=\bigcup\{\pred(\bX,y,\bR)\mid y\in\pred^n(\bX,x,\bR)\}\\
   \cl(\bX,x,\bR)&=\displaystyle\bigcup_{n\in\omega}\pred^n(\bX,x,\bR)
   \end{align*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\bR$ is a set-like relation on $\bX$, then for any $y\in\cl(\bX,x,\bR)$,
   $\pred(\bX,y,\bR)\subseteq\cl(\bX,x,\bR)$
   #+END_lemma

   #+ATTR_LATEX: :options [Induction on well-founded set-like relation]
   #+BEGIN_theorem
   If $\bR$ is a well-founded set-like relation on $\bX$, then every nonempty 
   $\bY\subseteq\bX$ has minimal element under $\bR$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose $\bR$ is a well-founded set-like relation on $\bX$. If 
   $\bF:\bX\times\bV\to\bV$, then there is a unique $\bG:\bX\to\bV$ s.t.
   \begin{equation*}
   \forall x\in\bX(\bG(x)=\bF(x,\bG\restriction\pred(\bX,x,\bR)))
   \end{equation*}
   #+END_theorem
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If $\bR$ is a set-like well-founded relation on $\bX$, define 
   \begin{equation*}
   \rank(x,\bX,\bR)=\sup\{\rank(y,\bX,\bR)+1\mid y\bR x\wedge y\in\bX\}
   \end{equation*}
   #+END_definition

   Note that
   \begin{equation*}
   \bF(x,h)=\sup\{\alpha+1\mid\alpha\in\ran{h}\}
   \end{equation*}

   #+ATTR_LATEX: :options [$\zfmm$]
   #+BEGIN_lemma
   If $\bX$ is transitive and $\in$ is well-founded on $\bX$, then
   $\bX\subseteq\wf$ and for any $x\in\bX$, $\rank(x,\bX,\in)=\rank(x)$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is a set-like well-founded relation on $\bX$, \tf{Mostowski function}
   $\bG$ on $(\bX,\bR)$ is 
   \begin{equation*}
   \bG(x)=\{\bG(y)\mid y\in\bX\wedge y\bR x\}
   \end{equation*}
   $\cmm=\ran{\bG}$ is called the \tf{Mostowski collapse} of $(\bX,\bR)$
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $\forall x,y\in\bX(x\bR y\to\bG(x)\in\bG(y))$
   2. \cm is transitive
   3. If the axiom of power set holds, $\cm\subseteq\wf$
   4. if the axiom of power set holds and $x\in\bX$, then\par
      $\rank(x,\bX,\bR)=\rank(\bG(x))$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $\bR$ is extensional on $\bX$ iff
   \begin{equation*}
   \forall x,y\in\bX(\forall z\in\bX(z\bR x\leftrightarrow z\bR y)\to x=y)
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $\bX$ is transitive then $\in$ is extensional on $\bX$
   #+END_lemma


   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let $\bR$ be a set-like well-founded relation on $\bX$, $\bG$ is a Mostowski
   function on it. If $\bR$ is extensional, then $\bG$ is an isomorphism
   #+END_lemma

   #+ATTR_LATEX: :options [Mostowski collapse theorem]
   #+BEGIN_theorem
   Suppose $\bR$ is set-like well-founded extensional on $\bX$, then there are
   unique transitive class \cm and bijection $\bG:\bX\to\cm$ s.t. 
   $\bG:(\bX,\bR)\cong(\cm,\in)$
   #+END_theorem
** Absoluteness under the axiom of foundation
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following relations and functions can be defined by formulas in
   $\zf-\text{Pow}$ and are equivalent to some $\Delta_0$ formulas
   1. $x$ is an ordinal
   2. $x$ is a limit ordinal
   3. $x$ is a successor ordinal
   4. \omega
   5. $x$ is a finite ordinal
   6. $0,1,2,\dots,20,\dots$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem

If transitive model $\cm\models\zf-\text{Pow}$, then every finite subset of
\cm belongs to \cm
   #+END_theorem

   #+BEGIN_proof
   prove 
   \begin{equation*}
   \forall x\subset\cm(\abs{x}=n\to x\in\cm)
   \end{equation*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following concepts are absolute for any transitive model of
   $\zf-\text{Pow}$ 
   1. $x$ is finite
   2. $X^n$
   3. $X^{<\omega}$
   4. $R$ is a well-ordering on $X$
   5. $\text{type}(X,R)$
   6. $\alpha+1$
   7. $\alpha-1$
   8. $\alpha+\beta$
   9. $\alpha\cdot\beta$
   #+END_theorem


   Class $\bX$ is in fact a formula $\bX(x)$. It's absolute for \cm if and only
   if $\forall x\in\cm(\bX^\cm(x)\leftrightarrow\bX(x))$, which is equivalent to
   $\{x\in\cm\mid\bX(x)\}=\{x\in\cm\mid\bX^\cm(x)\}$. Hence $\bX$ is absolute
   for \cm if and only if $\bX^\cm=\cm\cap\bX$

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose $\bR$ is a well-founded set-like relation on $\bX$,
   $\bF:\bX\times\bV\to\bV$,
   \begin{equation*}
   \forall x\in\bX(\bG(x)=\bF(x,\bG\restriction(\bX,x,\bR)))
   \end{equation*}
   transitive model $\cm\models\zf-\text{Pow}$ and
   1. $\bF$ is absolute for \cm
   2. $\bX,\bR$ are absolute for \cm, $(\bR\text{ is set-like on }\bX)^\cm$ and
      \begin{equation*}
      \forall x\in\cm(\pred(\bX,x,\bR)\subseteq\cm)
      \end{equation*}

      
   then $\bG$ is absolute for $\cm$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The following concept is absolute for any transitive model of
   $\zf-\text{Pow}$
   1. $\alpha^\beta$
   2. $\rank(x)$
   3. $\trcl{x}$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   transitive $\cm\models\zf$
   1. if $x\in\cm$, then $\calp^\cm(x)=\calp(x)\cap\cm$
   2. if $\alpha\in\cm$, then $V_\alpha^\cm=V_\alpha\cap\cm$
   #+END_lemma
** Unaccessible cardinal and models of \zfc
   $\bZ=\zff-\text{Rep},\zfmm=\zfcm-\text{Rep}$
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $\gamma>\omega$ is a limit ordinal, then $V_\gamma\models_{\zff}\bZ$ and 
   $V_\gamma\models_{\zfcm}\zc$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $V_{\omega+\omega}$ doesn't satisfies the axiom of replacement
   #+END_corollary

   #+BEGIN_proof
   
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\zcm\not\vdash\exists x(x=V_\omega),\zcm\not\vdash\forall x\exists y(\trcl{x}=y)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is an inaccessible cardinal, then $V_\kappa\models_{\zfmm}\zff$,\par
   $V_\kappa\models_{\zfcc}\zfc$
   #+END_theorem

   #+BEGIN_proof
   Since \kappa is inaccessible, $\abs{V_\kappa}=\kappa$. For any $A\in
   V_\kappa$, $\abs{A}<\kappa$. Since \kappa is regular, any 
   $f:A\to V_\kappa$ is bounded. Hence there exists $\alpha<\kappa$ s.t. 
   $\ran{f}\subseteq V_\alpha$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   We cannot prove "there is some inaccessible cardinals" in \zfc
   #+END_corollary

   #+BEGIN_proof
   Suppose we could. Then we have $V_\kappa\models\zfc$, which contradicts
   Gdels second incompleteness theorem 
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose \kappa is inaccessible. The following concepts are absolute for
   $V_\kappa$ 
   1. $x$ is a cardinal
   2. $x$ is a regular cardinal
   3. $x$ is an inaccessible cardinal
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\con(\zfcm)\to\con(\zfcm+\text{"there is no inaccessible cardinal"})$
   #+END_lemma

   #+BEGIN_proof
   If \kappa is the smallest inaccessible cardinal, then \par
   $V_\kappa\models\zfcm+\text{"there is no inaccessible cardinal"}$. Define
   \begin{equation*}
   \cm=\bigcap\{V_\kappa\mid\kappa\text{ is inaccessible}\}
   \end{equation*}
   #+END_proof
   If there are, then $\cm=V_\kappa$

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   \con(\zfcm)\not\to\con(\zfcm+\text{"there are some inaccessible cardinals"})
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   For any infinite cardinal \kappa, $H_\kappa=\{x\mid\abs{\trcl{x}}<\kappa\}$
   is the collection of sets which \tf{hereditarily have size less than } \kappa.
   Element of $H_\omega$ is called \tf{hereditarily finite set}. Element of
   $H_{\omega_1}$ is called \tf{hereditarily countable set}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any infinite cardinal \kappa, $H_\kappa\subseteq V_\kappa$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \kappa is regular, then $H_\kappa=V_\kappa$ if and only if \kappa is
   inaccessible
   #+END_lemma

   #+BEGIN_proof
   which implies $\abs{V_\kappa}=\kappa$
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any infinite cardinal \kappa
   1. $H_\kappa$ is transitive
   2. $H_\kappa\cap\on=\kappa$
   3. If $x\in H_\kappa$, then $\bigcup x\in H_\kappa$
   4. If $x,y\in H_\kappa$, then $\{x,y\}\in H_\kappa$
   5. If $x\in H_\kappa,y\subseteq x$, then $y\in H_\kappa$
   6. if $\kappa$ is regular, then $\forall x(x\in H_\kappa\leftrightarrow
      x\subset H_\kappa\wedge\abs{x}<\kappa)$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is uncountable regular cardinal, then
   $H_\kappa\models_{\zfcm}\zfcm-\text{Pow}$ 
   #+END_theorem
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If \kappa is uncountable regular cardianl, then the following propositions
   are equivalent
   1. $H_\kappa\models\zfcm$
   2. $H_\kappa=V_\kappa$
   3. $\kappa$ is inaccessible
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $\con(\zfcm)\to\con(\zfcm-\text{pow}+\forall x(x\text{ is countable}))$
   #+END_corollary
** Reflection theorem
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   $\cm\subseteq\cn$ are classes. $\varphi_1,\dots,\varphi_n$ is a sequence
   closed under subformula, then the following propositions are equivalent
   1. $\varphi_1,\dots,\varphi_n$ are absolute for \cm and \cn
   2. if $\varphi_i=\exists\varphi_j(x,y_1,\dots,y_m)$, then
      \begin{equation*}
      \forall y_1,\dots,y_m\in\cm(\exists x\in\cn\varphi_j^\cn(x,y_1,\dots,y_m)
      \to\exists x\in\cm\varphi_j^\cm(x,y_1,\dots,y_m))
      \end{equation*}
   #+END_lemma
   
   #+ATTR_LATEX: :options [reflection theorem(\zff)]
   #+BEGIN_theorem
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any
   $V_\alpha$, there exists $V_\beta$ s.t. $V_\alpha\subseteq V_\beta$ and 
   $\varphi_1,\dots,\varphi_n$ are absolute for $V_\beta$
   #+END_theorem

   #+ATTR_LATEX: :options [\zff]
   #+BEGIN_corollary
   $F=\{\sigma_1,\dots,\sigma_n\}$ are finite subsets of \zf, then
   \begin{equation*}
   \forall\alpha\exists\beta>\alpha(\sigma_1^{V_\beta}\wedge\dots\wedge\sigma_n^{V_\beta})
   \end{equation*}
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   $F=\{\sigma_1,\dots,\sigma_n\}$ is a finite subset of \zf. Unless \zf is
   unconsistent, $F$ cannot prove all axioms of \zf
   #+END_corollary

   #+ATTR_LATEX: :options [\zfcm]
   #+BEGIN_theorem
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any set
   $N$, there exists set $M$ s.t.
   1. $N\subseteq M$
   2. $\varphi_1,\dots,\varphi_n$ are absolute for $(M,\in)$
   3. $\abs{M}\le\abs{N}\cdot\omega$
   #+END_theorem

   #+ATTR_LATEX: :options [\zfcm]
   #+BEGIN_corollary
   For any finite formula set $F=\{\varphi_1,\dots,\varphi_n\}$, for any set
   $N$, there exists set $M$ s.t.
   1. $N\subseteq M$
   2. $\varphi_1,\dots,\varphi_n$ are absolute for $(M,\in)$
   3. $\abs{M}\le\abs{N}\cdot\omega$
   4. $M$ is transitive
   #+END_corollary
   \newpage
* COMMENT Con
  structable Set - Venlafaxine
** Definablity and Gdel operation
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $M$ is a set, $\psi(x_1,\dots,x_n,y_1,\dots,y_m)$ is a formula, 
   $X\subseteq M^n$ is \tf{definable in $M$ from parameters from $\psi$} if and
   only if there are $y_1,\dots,y_m\in M$ s.t.
   \begin{equation*}
   X=\{(x_1,\dots,x_n)\mid(\psi^M(x_1,\dots,x_n,y_1,\dots,y_m))\}
   \end{equation*}
   \begin{equation*}
   \deff(M)=\{X\subseteq M\mid\exists\psi,X\text{ is definable in } 
   M \text{ from } \psi\} 
   \end{equation*}
   #+END_definition
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \tf{Gdel operation}
   1. $G_1(X,Y)=\{X,Y\}$
   2. $G_2(X,Y)=X\times Y$
   3. $G_3(X,Y)=\in\restriction X\times Y$
   4. $G_4(X,Y)=X-Y$
   5. $G_5(X,Y)=X\cap Y$
   6. $G_6(X,Y)=\bigcap X$
   7. $G_7(X,Y)=\dom{X}$
   8. $G_8(X,Y)=\{(x,y)\mid(y,x)\in X\}$
   9. $G_9(X,Y)=\{(x,y,z)\mid(x,z,y)\in X\}$
   10. $G_{10}(X,Y)=\{(x,y,z)\mid(y,z,x)\in X\}$

       
   Class $C$ is closed under Gdel operation if for any $X,Y$, X,Y\in C$ implies
   $G_i(X,Y)\in C$. For any set $M$, $\cl_G(M)$ is the 
   \tf{closure under Gdel operation}
 
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   \psi is a \tf{normal form} if
   1. only $\neg,\wedge,\exists$ are logical symbol
   2. = doesn't appear
   3. if $x_i\in x_j$ then $i\neq j$
   4. $\exists$ only shown as: $\exists x_{m+1}\in
      x_i\varphi(x_1,\dots,x_{m+1})$, $1\le i\le m$
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Any $\Delta_0$ formula can be transformed into normal form
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any $\Delta_0$ formula $\psi(x_1,\dots,x_n)$, there is Gdel operations'
   composition $G$ s.t. for any $X_1,\dots,X_n$
   \begin{align*}
   G(X_1,\dots,X_n)=&\{(x_1,\dots,x_n)\mid\\
   &x_1\in X_1\wedge\dots\wedge x_n\in X_n\wedge\psi(x_1,\dots,x_n)\}
   \end{align*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If $M$ is transitive and $M=\cl_G(M)$, then for any $\Delta_0$ formula
   $\psi(x,y_1,\dots,y_m)$, any set $X\in M$, any $y_1,\dots,y_m\in M$ if
   \begin{equation*}
   Y=\{x\in X\mid\psi(x,y_1,\dots,y_m)\}
   \end{equation*}
   then $Y\in M$. Hence $\Delta_0$ schema of specification holds in $M$
   #+END_corollary

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If $G(X_1,\dots,X_n)$ is Gdel operations' composition, then
   $Z=G(X_1,\dots,X_n)$ is equivalent to a $\Delta_0$ formula
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   For any transitive set $M$, $\deff(M)=\cl_G(M\cup\{M\})\cap\calp(M)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If transitive $\cm\models\zff$, then for any transitive set $M\in\cm$,
   $\deff(M)$ is absolute for \cm
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any transitive set $M$
   1. $\deff(M)\subseteq\calp(M)$
   2. $M\subseteq \deff(M)$
   3. for any $X\subseteq M$, if $X$ is finite, then $X\in\deff(M)$
   4. assume $\ac$ and $\abs{M}\ge\omega$, then $\abs{\deff(M)}=\abs{M}$
   #+END_lemma
** Gdel's L
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   for any \alpha
   1. $L_0=\emptyset$
   2. $L_{\alpha+1}=\deff(L_\alpha)$
   3. For any limit \alpha, $L_\alpha=\bigcup_{\beta<\alpha}L_\beta$


   $\textbf{L}=\displaystyle\bigcup_{\alpha\in\on}L_\alpha$. Element of \gl is
   called constructible set
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $L_\alpha$ is transitive
   2. If $\alpha<\beta$, then $L_\alpha\subseteq L_\beta$
   3. $L_\alpha\subseteq V_\alpha$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   $x\in\gll$
   \begin{equation*}
   \rank_\gll(x)=\min\{\beta\mid x\in\gll_{\beta+1}\}
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any \alpha
   \begin{equation*}
   L_\alpha=\{x\in\gll\mid\rank_{\gll}(x)<\alpha\}
   \end{equation*}
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   For any ordinal \alpha
   1. $L_\alpha\cap\on=\alpha$
   2. $\alpha\in\gll\cap\rank_{\gll}(\alpha)=\alpha$
   #+END_lemma

   #+BEGIN_proof
   since "\alpha is a cardinal" is absolute for any transitive set. 
   \begin{align*}
   \alpha&=L_\alpha\cap\on=\{\eta\in L_\alpha\mid\eta\text{ is a ordinal}\}\\
   &=\{\eta\in L_\alpha\mid(\eta\text{ is an ordinal}^{L_\alpha})\}\in\deff(L_\alpha)
   \end{align*}
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   for any ordinal \alpha
   1. $L_\alpha\in L_{\alpha+1}$
   2. any finite subset of $L_\alpha$ belongs to $L_{\alpha+1}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. $\forall n\in\omega(L_n=V_n)$
   2. $L_\omega=V_\omega$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If \ac, then for any $\alpha\ge\omega,\abs{L_\alpha}=\abs{\alpha}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\gll\models\zff$
   #+END_theorem

** Axiom of constructibility and relativization
   #+ATTR_LATEX: :options [Axiom of constructibility]
   #+BEGIN_theorem
   $\cvm=\gll$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:8.3.2
   function $\alpha\mapsto L_\alpha$ is absolute for any transitive model of \zf
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\gll\models\zff+\cv=\gll$
   #+END_theorem

   #+BEGIN_proof
   $(\cv=\gll)^\gll$ is $\forall x\in\gll\exists\alpha\in\gll(x\in
   L_\alpha)^\gll$. 
   By ref:8.3.2, $(x\in L_\alpha)^\gll\Leftrightarrow x\in L_\alpha$. Hence
   $\gll\models\cv=\gll$

   #+END_proof
   Hence
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   $\con(\zff)\to\con(\zff+\cv=\gll)$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Suppose transitive proper class $\cmm\models\zff-\text{Pow}$, then\par
   $\gll=\gll^\cmm\subseteq\cmm$ 
   #+END_theorem

   #+BEGIN_proof
   For any ordinal \alpha, since \cm is proper, $\cmm\not\subseteq V_\alpha$.
   Hence there is $x\in\cmm$ s.t. $\rank(x)\ge\alpha$. Since rank is absolute,
   $\rank(x)\in\cmm$. And \cm is transitive, hence $\alpha\in\cmm$. By
   ref:8.3.2, $L_\alpha\in\cmm$
   \begin{align*}
    \gll^\cmm &=\{x\in\cmm\mid(\exists\alpha\in\on(x\in L_\alpha))^\cmm\}\\
    &=\{x\mid\exists\alpha\in\on\cap\cmm(x\in\ L_\alpha\cap\cmm)\}\\
    &=\{x\mid\exists\alpha\in\on(x\in L_\alpha)\}\\
    &=\gll
   \end{align*}
   #+END_proof
   
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   If transitive model $\cm\models\zff$ contains all ordinals, then it's an
   \tf{inner model}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   there is a finite set of axioms $\{\psi_1,\dots,\psi_n\}$ of
   $\zff-\text{Pow}$ s.t. ordinals,rank and $L_\alpha$ are absolute for any
   model of $\{\psi_1,\dots,\psi_n\}$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If set $M$ is transitive, then $M\cap\on$ is a ordinall and is the least that
   doesn't belong to $M$, denoted by $\alpha^M$
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   There is a finite subset $\{\psi_1,\dots,\psi_n\}$ of axioms of
   $\zff-\text{Pow}$ satisfying
   \begin{equation*}
   \forall M(M\text{ is transitive }\wedge\psi_1^M\wedge\dots\wedge\psi_n^m\to
   (L_{\alpha^M}=\gll^M\subseteq M))
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The is a finite subset $\{\psi_1,\dots,\psi_{n+1}\}$ of axioms of
   $\zff-\text{Pow}+\cvm=\gll$ satisfying
   1. If \cm is a transitive proper class and
      $\psi_1^\cm\wedge\dots\wedge\psi_{n+1}^\cm$, then $\cm=\gll$
   2. $\forall M(M\text{ is transitive
      }\wedge\psi_1^M\wedge\dots\wedge\psi_n^m\to (L_{\alpha^M}=M))$
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   There is a well-ordering on \gll. Hence $\cvm=\gll\to\ac$
   #+END_theorem

   If $\cvm=\gll$, hence $\aleph_\alpha\subseteq L_{\aleph_{\alpha+1}}$. Because
   $\abs{L_{\alpha_{\alpha+1}}}=\aleph_{\alpha+1}$,
   $2^{\aleph_\alpha}\le\aleph_{\alpha+1}$ 
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   If $\cvm=\gll$, then for any infinite ordinal \alpha,
   $\calp(L_\alpha)\subseteq L_{\abs{\alpha}^+}$
   #+END_theorem

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_corollary
   $(\ac+\gchh)^\gll$
   #+END_corollary

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_theorem
   $\con(\zff)\to\con(\zfcm+\gchh)$
   #+END_theorem

   #+ATTR_LATEX: :options [$\zff$]
   #+BEGIN_theorem
   Suppose $S_0=\{\psi_1,\dots,\psi_n\}\subseteq\zff+\cvm=\gll$, then
   \begin{equation*}
   \zff\vdash\exists M(\abs{M}=\omega\wedge M\text{ is transitive}\wedge
   (\psi_1^M\wedge\dots\wedge\psi_n^M))
   \end{equation*}
   #+END_theorem

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Suppose $\cvm=\gll$. For any uncountable regular cardinal \kappa,
   $L_\kappa=H_\kappa$ 
   #+END_lemma

   #+ATTR_LATEX: :options []
   #+BEGIN_corollary
   If \kappa is a uncountable regular cardinal, then
   $\L_\kappa\models\zff-\text{Pow}+\cvm=\gll$. If \kappa is inaccessible, then 
   $L_\kappa\models\zff+\cvm=\gll$
   #+END_corollary

   \newpage

* COMMENT The end
  Learn and forget

   








