#+TITLE: Set Theory
#+AUTHOR: Thomas Jech

#+EXPORT_FILE_NAME: ../latex/SetTheory/SetTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex

* Ordinal Numbers

** Linear and Partial Ordering
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A binary relation < on a set \(P\) is a *partial ordering* of \(P\) if
    1. \(p\not<p\) for any \(p\in P\)
    2. if \(p<q\) and \(q<r\) then \(p<r\)


    \((P,<)\) is called a *partially ordered set*. A partial ordering < of \(P\) is a *linear ordering*
    if moreover
    3. [@3] \(p<q\) or \(p=q\) or \(q<p\) for all \(p,q\in P\)

       If < is a partial ordering, then \(\le\) is also a partial ordering
    #+END_definition

    if \((P,<)\) and \((Q,<)\) are partially ordered sets and \(f:P\to Q\), then \(f\) is
    *order-preserving* if \(x<y\) implies \(f(x)<f(y)\). If \(P\) and \(Q\) are linearly ordered, then
    an order-preserving function is also called *increasing*

** Well-Ordering
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A linear ordering < of a set \(P\) is a *well-ordering* if every nonempty subset of \(P\) has a
    least element
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.4
    If \((W,<)\) is a well-ordered set and \(f:W\to W\) is an increasing function, then \(f(x)\ge x\)
    for each \(x\in W\)
    #+END_lemma

    #+BEGIN_proof
    Assume that the set \(X=\{x\in W:f(x)<x\}\) is nonempty and let \(z\) be the least element of \(X\).
    If \(w=f(z)\), then \(f(w)<w\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The only automorphism of a well-ordered set is the identity
    #+END_corollary

    #+BEGIN_proof
    By Lemma ref:lemma2.4, \(f(x)\ge x\) for all \(x\), and \(f^{-1}(x)\ge x\) for all \(x\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If two well-ordered sets \(W_1,W_2\) are isomorphic, then the isomorphism of \(W_1\) onto \(W_2\) is unique
    #+END_corollary

    if \(W\) is a well-ordered set and \(u\in W\), then \(\{x\in W:x<u\}\) is an *initial segment* of \(W\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.7
    No well-ordered set is isomorphic to an initial segment of itself
    #+END_lemma

    #+BEGIN_proof
    If \(\ran(f)=\{x:x<u\}\), then \(f(u)<u\), contrary to Lemma ref:lemma2.4
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm2.8
    If \(W_1\) and \(W_2\) are well-ordered sets, then exactly one of the following three cases holds
    1. \(W_1\) is isomorphic to \(W_2\)
    2. \(W_1\) is isomorphic to an initial segment of \(W_2\)
    3. \(W_2\) is isomorphic to an initial segment of \(W_1\)
    #+END_theorem

    #+BEGIN_proof
    For \(u\in W_i\), (\(i=1,2\)), let \(W_i(u)\) denote the initial segment of \(W_i\) given by \(u\).
    Let
    \begin{equation*}
    f=\{(x,y)\in W_1\times W_2:W_1(x)\text{ is isomorphic to }W_2(y)\}
    \end{equation*}
    Using Lemma ref:lemma2.7, \(f\) is a injective: if \(f(x_1)=f(x_2)=y\),
    then \(W_1(x_1)\cong W_2(y)\cong W_1(x_2)\), and \(x_1<x_2\) or \(x_2<x_1\) fail. If \(h\) is an isomorphism
    between \(W_1(x)\) and \(W_2(y)\), and \(x'<x\), then \(W_1(x')\) and \(W_2(h(x'))\) are isomorphic.
    It follows that \(f\) is order-preserving

    If \(\dom(f)=W_1\) and \(\ran(f)=W_2\), then case 1 holds

    if \(y_1<y_2\) and \(y_2\in\ran(f)\), then \(y_1\in\ran(f)\). Thus if \(\ran(f)\neq W_2\) and \(y_0\) is the
    least element of \(W_2-\ran(f)\), we have \(\ran(f)=W_2(y_0)\). Necessarily, \(\dom(f)=W_1\), for
    otherwise we would have \((x_0,y_0)\in f\), where \(x_0\)=the least element of \(W_1-\dom(f)\)
    #+END_proof

    if \(W_1\) and \(W_2\) are isomorphic, we say that they have the same *order-type*.

** Ordinal Numbers
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(T\) is *transitive* if every element of \(T\) is a subset of \(T\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set is an *ordinal number* (an *ordinal*) if it is transitive and well-ordered by \(\in\)
    #+END_definition

    Define
    \begin{equation*}
    \alpha<\beta \quad\text{ iff }\quad \alpha\in\beta
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.11
    1. \(0=\emptyset\) is an ordinal
    2. if \alpha is an ordinal and \(\beta\in\alpha\), then \beta is an ordinal
    3. if \(\alpha\neq\beta\) are ordinals and \(\alpha\subset\beta\), then \(\alpha\in\beta\)
    4. if \alpha, \beta are ordinals, then either \(\alpha\subset\beta\) or \(\beta\subset\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1,2 by definition

    3. [@3] if \(\alpha\subset\beta\), let \gamma be the least element of the set \(\beta-\alpha\). Since \alpha is transitive, it
       follows that \alpha is the initial segment of \beta given by \gamma: for \(\eta\in\alpha\), \(\eta\neq\gamma\) and \(\gamma\not\in\eta\),
       hence \(\eta\in\gamma\) since ordinals are well-ordered by \(\in\). Thus \(\alpha=\{\xi\in\beta:\xi<\gamma\}=\gamma\), and
       so \(\alpha\in\beta\).
    4. \(\alpha\cap\beta\) is an ordinal, \(\alpha\cap\beta=\gamma\). We have \(\gamma=\alpha\) or \(\gamma=\beta\), for otherwise \(\gamma\in\alpha\)
       and \(\gamma\in\beta\), by 3. Then \(\gamma\in\gamma\), which contradicts the definition of an ordinal (namely
       that \(\in\) is a *strict* ordering of \alpha)
    #+END_proof

    Using Lemma ref:lemma2.11 one gets the followings
    1. < is a linear ordering of the class \(\Ord\)
    2. for each \alpha, \(\alpha=\{\beta:\beta<\alpha\}\) <<Question1>>
    3. if \(C\) is a nonempty class of ordinals, then \(\bigcap C\) is an ordinal, \(\bigcap C\in C\)
       and \(\bigcap C=\inf C\)
    4. if \(X\) is a nonempty set of ordinals, then \(\bigcup X\) is an ordinal, and \(\bigcup X=\sup X\)
    5. for every \alpha, \(\alpha\cup\{\alpha\}\) is an ordinal and \(\alpha\cup\{\alpha\}=\inf\{\beta:\beta>\alpha\}\)


    We thus define \(\alpha+1=\alpha\cup\{\alpha\}\). In view of 4, the class \(\Ord\) is a proper class; otherwise
    consider \(\sup\Ord+1\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Every well-ordered set is isomorphic to a unique ordinal number
    #+END_theorem

    #+BEGIN_proof
    The uniqueness follows from Lemma ref:lemma2.7: suppose \(\alpha\cong\beta\) and \(\alpha\neq\beta\). As \(\alpha\neq\beta\),
    either \(\alpha\in\beta\) or \(\beta\in\alpha\), thus \(\alpha\) is isomorphic to an initial segment of \beta or vice versa.
    But by Lemma ref:lemma2.7,  we get a contradiction.

    Given a well-ordered set \(W\),
    define \(F(x)=\alpha\) is \alpha is isomorphic to the initial segment of \(W\) given by \(x\). If such an
    \alpha exists, then it is unique. By the Replacement Axioms, \(F(W)\) is a set. For each \(x\in W\),
    such an \alpha exists (otherwise consider the least \(x\) for which such an \alpha does not exists). If
    \gamma is the least \(\gamma\not\in F(W)\), then \(F(W)=\gamma\) and we have an isomorphism of \(W\) onto \gamma
    #+END_proof

    0 is a limit ordinal and define \(\sup\emptyset=0\)

    #+ATTR_LATEX: :options [Natural Numbers]
    #+BEGIN_definition
    We denote the least nonzero limit ordinal \omega (or \(\N\)). The ordinals less than \omega are call
    *finite ordinals*, or *natural numbers*
    #+END_definition

** Induction and Recursion
    #+ATTR_LATEX: :options [Transfinite Induction]
    #+BEGIN_theorem
    Let \(C\) be a class of ordinals and assume that
    1. \(0\in C\)
    2. if \(\alpha\in C\), then \(\alpha+1\in C\)
    3. if \alpha is a nonzero limit ordinal and \(\beta\in C\) for all \(\beta<\alpha\), then \(\alpha\in C\)


    Then \(C\) is the class of all ordinals
    #+END_theorem

    #+BEGIN_proof
    Otherwise, let \alpha be the least \(\alpha\not\in C\) and apply 1,2 and 3.
    #+END_proof

    A function whose domain is the set \(\N\) is called an (*infinite*) *sequence* (A *sequence in* \(X\)
    is a function \(f:\N\to X\)). The standard notation for a sequence is
    \begin{equation*}
    \la a_n:n<\omega\ra
    \end{equation*}
    A *finite sequence* is a function \(s\) s.t. \(\dom(s)=\{i:i<n\}\) for some \(n\in\N\); then \(s\) is a
    *sequence  of length* \(n\)

    A *transfinite sequence* is a function whose domain is an ordinal
    \begin{equation*}
    \la a_\xi:\xi<\alpha\ra
    \end{equation*}
    It is also called an *\alpha-sequence* or a *sequence of length* \alpha. We also say that a
    sequence \(\la a_\xi:\xi<\alpha\ra\) is an *enumeration* of its range \(\{a_\xi:\xi<\alpha\}\). If \(s\) is a sequence of
    length \alpha, then \(s^\smallfrown x\) or simply \(sx\) denotes the sequence of length \(\alpha+1\) that
    extends \(s\) and whose \(\alpha\)th term is \(x\):
    \begin{equation*}
    s^\smallfrown x=sx=s\cup\{(\alpha,x)\}
    \end{equation*}
    Sometimes we call a "sequence"
    \begin{equation*}
    \la a_\alpha:\alpha\in\Ord\ra
    \end{equation*}
    a function (a proper class) on \(\Ord\)


    "Definition by transfinite recursion" usually takes the following form: Given a function \(G\)
    (on the class of transfinite sequence), then for every \theta there exists a unique \theta-sequence
    \begin{equation*}
    \la a_\alpha:\alpha<\theta\ra
    \end{equation*}
    s.t.
    \begin{equation*}
    a_\alpha=G(\la a_\xi:\xi<\alpha\ra)
    \end{equation*}
    for every \(\alpha<\theta\)

    #+ATTR_LATEX: :options [Transfinite Recursion]
    #+BEGIN_theorem
    Let \(G\) be a function (on \(V\)), then eqref:2.6 below defines a unique function \(F\)
    on \(\Ord\) s.t.
    \begin{equation*}
    F(\alpha)=G(F\restriction\alpha)
    \end{equation*}
    for each \alpha
    #+END_theorem

    In other words, if we let \(a_\alpha=F(\alpha)\), then for each \alpha
    \begin{equation*}
    a_\alpha=G(\la a_\xi:\xi<\alpha\ra)
    \end{equation*}
    (Note that we tacitly use Replacement: \(F\restriction\alpha\) is a set for each \alpha)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(X\) be a set and \theta an ordinal number. For every function \(G\) on the set of all
    transfinite sequences in \(X\) of length \(<\theta\) s.t. \(\ran(G)\subset X\) there exists a unique
    \theta-sequence \(\la a_\alpha:\alpha<\theta\ra\) in \(X\) s.t. \(a_\alpha=G(\la a_\xi:\xi<\alpha\ra)\) for every \(\alpha<\theta\)
    #+END_corollary

    #+BEGIN_proof
    Let
    \begin{align}
    \label{2.6}
    F(\alpha)=x\leftrightarrow&\text{ there is a sequence }\la a_\xi:\xi<\alpha\ra\text{ s.t.:}\\
    &1.\; (\forall\xi<\alpha)a_\xi=G(\la a_\eta:\eta<\xi\ra)\nonumber\\
    &2.\; x=G(\la a_\xi:\xi<\alpha\ra)\nonumber
    \end{align}
    For every \alpha, if there is an \alpha-sequence that satisfies 1, then such a sequence is unique:
    if \(\la a_\xi:\xi<\alpha\ra\) and \(\la b_\xi:\xi<\alpha\ra\) are two \alpha-sequences satisfying 1, one shows \(a_\xi=b_\xi\) by
    induction on \xi.Thus \(F(\alpha)\) is determined uniquely by 2, and therefore \(F\) is a function.

    it follows, again by induction, that for each \alpha there is an \alpha-sequence that satisfies 1 (at
    limit steps, we use Replacement to get the \alpha-sequence as the union of all the
    \xi-sequences, \(\xi<\alpha\)). Thus \(F\) is defined for all \(\alpha\in\Ord\). It obviously satisfies
    \begin{equation*}
    F(\alpha)=G(F\restriction\alpha)
    \end{equation*}

    If \(F'\) is any function on \(\Ord\) that satisfies
    \begin{equation*}
    F'(\alpha)=G(F'\restriction\alpha)
    \end{equation*}
    then it follows by induction that \(F'(\alpha)=F(\alpha)\) for all \alpha
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\alpha>0\) be a limit ordinal and let \(\la\gamma_\xi:\xi<\alpha\ra\) be a *nondecreasing* sequence of ordinals.
    We define the *limit* of the sequence by
    \begin{equation*}
    \lim_{\xi\to\alpha}\gamma_\xi=\sup\{\gamma_\xi:\xi<\alpha\}
    \end{equation*}

    A sequence of ordinals \(\la\gamma_\alpha:\alpha\in\Ord\ra\) is *normal* if it is increasing and *continuous*, i.e., for
    every limit \alpha,\(\gamma_\alpha=\lim_{\xi\to\alpha}\gamma_\xi\)
    #+END_definition

** Ordinal Arithmetic
    #+ATTR_LATEX: :options [Addition]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha+0=\alpha\)
    2. \(\alpha+(\beta+1)=(\alpha+\beta)+1\) for all \beta
    3. \(\alpha+\beta=\lim_{\xi\to\beta}(\alpha+\xi)\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options [Multiplication]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha\cdot 0=0\)
    2. \(\alpha\cdot(\beta+1)=\alpha\cdot\beta+\alpha\) for all \beta
    3. \(\alpha\cdot\beta=\lim_{\xi\to\beta}\alpha\cdot\xi\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options [Exponentiation]
    #+BEGIN_definition
    For all ordinal numbers \alpha
    1. \(\alpha^0=1\)
    2. \(\alpha^{\beta+1}=\alpha^\beta\cdot\alpha\) for all \beta
    3. \(\alpha^\beta=\lim_{\xi\to\beta}\alpha^\xi\) for all limit \(\beta>0\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For all ordinals \alpha, \beta and \gamma
    1. \(\alpha+(\beta+\gamma)=(\alpha+\beta)+\gamma\)
    2. \(\alpha\cdot(\beta\cdot\gamma)=(\alpha\cdot\beta)\cdot\gamma\)
    #+END_lemma

    #+BEGIN_proof
    Induction on \gamma
    #+END_proof

    Neither + nor \(\cdot\) are commutative:
    \begin{equation*}
    1+\omega=\omega\neq\omega+1,\quad 2\cdot\omega=\omega\neq\omega\cdot 2=\omega+\omega
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((A,<_A)\) and \((B,<_B)\) be disjoint linearly ordered sets. The *sum* of these linear
    orders is the set \(A\cup B\) with the ordering defined as follows: \(x<y\) iff
    1. \(x,y\in A\) and \(x<_Ay\), or
    2. \(x,y\in B\) and \(x<_By\), or
    3. \(x\in A\) and \(y\in B\)

    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((A,<)\) and \((B,<)\) be linearly ordered sets. The *product* of these linear orders is the
    set \(A\times B\) with the ordering defined by
    \begin{equation*}
    (a_1,b_1)<(a_2,b_2)\text{ iff either }b_1<b_2\text{ or }(b_1=b_2\text{ and }a_1<a_2)
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    <<Question2>>
    For all ordinals \alpha and \beta, \(\alpha+\beta\) and \(\alpha\cdot\beta\) are isomorphic to the sum and product of \alpha and \beta
    #+END_lemma

    #+BEGIN_proof
    We can define \(S(\alpha,\beta)=\{(0,a):a\in\alpha\}\cup\{(1,b)\in\beta\}\)

    if \(\beta=0\), then \(S(\alpha,\beta)=\alpha\)

    if \(\beta=\eta+1\), then \(S(\alpha,\beta)=S(\alpha,\eta)\cup\{(1,\eta)\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma2.25
    1. if \(\beta<\gamma\) then \(\alpha+\beta<\alpha+\gamma\)
    2. if \(\alpha<\beta\) then there exists a unique \delta s.t. \(\alpha+\delta=\beta\)
    3. if \(\beta<\gamma\) and \(\alpha>0\), then \(\alpha\cdot\beta<\alpha\cdot\gamma\)
    4. if \(\alpha>0\) and \gamma is arbitrary, then there exist a unique \beta and a unique \(\rho<\alpha\) s.t. \(\gamma=\alpha\cdot\beta+\rho\)
    5. if \(\beta<\gamma\) and \(\alpha>1\), then \(\alpha^\beta<\alpha^\gamma\)
    #+END_lemma

    #+BEGIN_proof
    1. induction on \gamma
    2. let \delta be the order-type of the set \(\{\xi:\alpha\le\xi<\beta\}\); \delta is unique by 1
    3. \gamma
    4. let \beta be the greatest ordinal s.t. \(\alpha\cdot\beta\le\gamma\)
    5. \gamma
    #+END_proof

    #+ATTR_LATEX: :options [Cantor's Normal Form Theorem]
    #+BEGIN_theorem
    Every ordinal \(\alpha>0\) can be represented uniquely in the form
    \begin{equation*}
    \alpha=\omega^{\beta_1}\cdot k_1+\dots+\omega^{\beta_n}\cdot k_n
    \end{equation*}
    where \(n\ge 1\), \(\alpha\ge\beta_1>\dots>\beta_n\), and \(k_1,\dots,k_n\) are nonzero natural numbers
    #+END_theorem

    #+BEGIN_proof
    By induction on \alpha. For \(\alpha=1\), we have \(1=\omega^0\cdot 1\); for arbitrary \(\alpha>0\), let \beta be the
    greatest ordinal s.t. \(\omega^\beta\le\alpha\). By Lemma ref:lemma2.25 (4) there exists a unique \delta and a
    unique \(\rho<\omega^\beta\) s.t. \(\alpha=\omega^\beta\cdot\delta+\rho\); this \delta must necessarily be finite
    #+END_proof


** Well-Founded Relations
    A binary relation \(E\) on a set \(P\) is *well-founded* if every nonempty \(X\subset P\) has an
    *\(E\)-minimal* element, that is \(a\in X\) s.t. there is no \(x\in X\) with \(xEa\)

    Given a well-founded relation \(E\) on a set \(P\), we can define the *height* of \(E\), and
    assign to each \(x\in P\) an ordinal number, the *rank* of \(x\) in \(E\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(E\) is a well-founded relation on \(P\), then there exists a unique function \rho from \(P\)
    into the ordinals s.t. for all \(x\in P\)
    \begin{equation*}
    \rho(x)=\sup\{\rho(y)+1:yEx\}
    \end{equation*}
    #+END_theorem

    The range of \rho is an initial segment of the ordinals, thus an ordinal number. This ordinal is
    called the *height* of \(E\)

    #+BEGIN_proof
    By induction, let
    \begin{align*}
    &P_0=\emptyset\\
    &P_{\alpha+1}=\{x\in P:\forall y(yEx\to y\in P_\alpha)\}\\
    &P_\alpha=\bigcup_{\xi<\alpha}P_\xi\quad\text{ if $\alpha$ is a limit ordinal}
    \end{align*}
    Let \theta be the least ordinal s.t. \(P_{\theta+1}=P_\theta\) (such \theta exists by Replacement, \theta is at least
    \alpha i guess).
    First \(P_\alpha\subset P_{\alpha+1}\) for each \alpha. Thus \(P_0\subset P_1\subset\dots\subset P_\theta\). We claim that \(P_\theta=P\). Otherwise,
    let \(a\) be an \(E\)-minimal element of \(P-P_\theta\). It follows that each \(xEa\) is an \(P_\theta\),
    and so \(a\in P_{\theta+1}\), a contradiction. Now we define \(\rho(x)\) as the least \alpha
    s.t. \(x\in P_{\alpha+1}\). The ordinal \theta is the height of \(E\).

    Uniqueness: let \(\rho'\) be another function and consider an \(E\)-minimal element of the
    set \(\{x\in P:\rho(x)\neq\rho'(x)\}\).
    #+END_proof

* Cardinal Numbers

** Cardinality
    Two sets \(X,Y\) have the same *cardinality*
    \begin{equation*}
    \abs{X}=\abs{Y}
    \end{equation*}
    if there exists a one-to-one mapping of \(X\) onto \(Y\)

    \begin{equation*}
    \abs{X}\le\abs{Y}
    \end{equation*}
    if there exists a one-to-one mapping of \(X\) into \(Y\).

    #+ATTR_LATEX: :options [Cantor]
    #+BEGIN_theorem
    label:thm3.1
    For every set \(X\), \(\abs{X}<\abs{P(X)}\)
    #+END_theorem

    #+BEGIN_proof
    Let \(f\) be a function from \(X\) into \(P(X)\). The set
    \begin{equation*}
    Y=\{x\in X:x\not\in f(x)\}
    \end{equation*}
    is not in the range of \(f\): If \(z\in X\) were such that \(f(z)=Y\), then \(z\in Y\)
    iff \(z\not\in Y\). Thus \(f\) is not a function of \(X\) onto \(P(X)\).
    Hence \(\abs{P(X)}\neq\abs{X}\)

    The function \(f(x)=\{x\}\) is the required one
    #+END_proof

    #+ATTR_LATEX: :options [Cantor-Bernstein]
    #+BEGIN_theorem
    label:thm3.2
    If \(\abs{A}\le\abs{B}\) and \(\abs{B}\le\abs{A}\), then \(\abs{A}=\abs{B}\)
    #+END_theorem

    #+BEGIN_proof
    From a nice [[https://web.williams.edu/Mathematics/lg5/CanBer.pdf][note]]

    We will write \(X\sim Y\) to denote the existence of a bijection from \(X\) to \(Y\).

    Given injections \(f:A\to B\) and \(g:B\to A\). Let
    \begin{alignat*}{2}
    &A_0=A\hspace{2cm}&&B_0=B\\
    &A_1=g(B_0)&&B_1=f(A_0)\\
    &A_2=g(B_1)&&B_2=f(A_1)\\
    &\vdots&&\vdots\\
    &A_n=g(B_{n-1})&&B_n=f(A_{n-1})\\
    &\vdots&&\vdots
    \end{alignat*}
    Then
    \begin{align*}
    &A=A_0\sim B_1\sim A_2\sim B_3\sim A_4\cdots\\
    &B=B_0\sim A_1\sim B_2\sim A_3\sim B_4\sim\cdots
    \end{align*}
    and
    \begin{align*}
    &A_0\supseteq A_1\supseteq A_2\supseteq\cdots\\
    &B_0\supseteq B_1\supseteq B_2\supseteq\cdots
    \end{align*}
    If \(A_n=A_{n+1}\), then \(A\sim B\), hence we assume \(A_n\supsetneq A_{n+1}\)

    Problem here now is that \(X_1\sim Y_1\) and \(X_2\sim Y_2\) do *not* imply \(X_1\cup X_2\sim Y_1\cup Y_2\) and
    therefore \(A\cup A_1\sim B_1\cup B\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose we have sets \(\{X_i\}\) and \(\{Y_i\}\) satisfying \(X_i\sim Y_i\) for all \(i\). If all
    the \(X_i\) are pairwise disjoint, and all the \(Y_i\) are pairwise disjoint, then
    \begin{equation*}
    \bigcup_iX_i\sim\bigcup_iY_i
    \end{equation*}
    #+END_lemma

    #+ATTR_LATEX: :options [Continuation of proof \ref{thm3.2}]
    #+BEGIN_proof
    Hence for each \(n\), set \(A_n^*=A_n-A_{n+1}\). By our assumption, all \(A_n^*\) are nonempty,
    moreover they are pairwise disjoint. Also we get

\begin{align*}
    &A^*=A^*_0\sim B^*_1\sim A^*_2\sim B^*_3\sim A^*_4\cdots\\
    &B^*=B^*_0\sim A^*_1\sim B^*_2\sim A^*_3\sim B^*_4\sim\cdots
    \end{align*}
    Hence we get
    \begin{equation*}
    \tilde{A}:=\bigcup_{n\ge 0}A_n^*\sim\tilde{B}:=\bigcup_{n\ge 0}B_n^*
    \end{equation*}
    Let \(\barA=\bigcap_{n\ge 0}A_n\) and \(\barb=\bigcap_{n\ge 0}B_n\)

    *Claim* \(A=\barA\cup\tilde{A}\) is a partition of \(A\), and \(B=\barB\cup\tilde{B}\) is a partition
    of \(B\)

    Now it remains to show that \(\barA\sim\barB\), which is immediate as \(f(\barA)=\barB\) and \(g(\barB)=\barA\)
    #+END_proof

    The arithmetic operations on cardinals are defined as follows
    \begin{alignat*}{2}
    &\kappa+\lambda=\abs{A\cup B}\quad&&\text{ where }\abs{A}=\kappa,\abs{B}=\lambda,\text{ and }A,B\text{ are disjoint}\\
    &\kappa\cdot\lambda=\abs{A\times B}&&\text{ where }\abs{A}=\kappa,\abs{B}=\lambda\\
    &\kappa^\lambda=\abs{A^B}&&\text{ where }\abs{A}=\kappa,\abs{B}=\lambda
    \end{alignat*}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    if \(\abs{A}=\kappa\), then \(\abs{P(A)}=2^\kappa\)
    #+END_lemma

    #+BEGIN_proof
    For every \(X\subset A\), let \(\chi_X\) be the function
    \begin{equation*}
    \chi_X(x)=
    \begin{cases}
    1&\text{ if }x\in X\\
    0&\text{ if }x\in A-X
    \end{cases}
    \end{equation*}
    The mapping \(f:X\to\chi_X\) is.a one-to-one correspondence between \(P(A)\) and \(\{0,1\}^A\)
    #+END_proof

    Thus Cantor's Theorem ref:thm3.1 can be formulated as
    #+BEGIN_quoting
    \(\kappa<2^\kappa\) for every cardinal \kappa
    #+END_quoting

    Very useful [[https://math.stackexchange.com/questions/131212/overview-of-basic-results-on-cardinal-arithmetic][link]]

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. + and \(\cdot\) is associative, commutative and distributive
    2. \((\kappa\cdot\lambda)^\mu=\kappa^\mu\cdot\lambda^\mu\)
    3. \(\kappa^{\lambda+\mu}=\kappa^\lambda\cdot\kappa^\mu\)
    4. \((\kappa^\lambda)^\mu=\kappa^{\lambda\cdot\mu}\)
    5. if \(\kappa\le\lambda\), then \(\kappa^\mu\le\lambda^\mu\)
    6. if \(0<\lambda\le\mu\), then \(\kappa^\lambda\le\kappa^\mu\)
    7. \(\kappa^0=1\); \(1^\kappa=1\); \(0^\kappa=0\) if \(\kappa>0\)
    #+END_proposition

    #+BEGIN_proof
    1. commutativity of + follows from \(A\cup B=B\cup A\), and so is the commutativity of \(\cdot\). Similar
       for associativity
    3. [@3] Given \(f:A\cup B\to C\), we get \(f\restriction A\) and \(f\restriction B\). Therefore we
       have a map \(f\mapsto(f\restriction A,f\restriction B)\)
    6. [@6] let \(\abs{A}=\kappa\), \(\abs{B}=\lambda\), \(\abs{C}=\mu\). Given injection \(f:B\to C\), for
       each \(h:B\to A\) we associate a \(g(y):C\to A\) by \(g(f(x))=h(x)\) if \(y\in f(B)\),
       otherwise \(g(y)\) can be anything.

    #+END_proof

** Alephs
    An ordinal \alpha is called a *cardinal number* if \(\abs{\alpha}\neq\abs{\beta}\) for all \(\beta<\alpha\).

    If \(W\)is a well-ordered set, then there exists an ordinal \alpha s.t. \(\abs{W}=\abs{\alpha}\). Thus we
    let
    \begin{equation*}
    \abs{W}=\text{ the least ordinal s.t. }\abs{W}=\abs{\alpha}
    \end{equation*}

    Every natural number is a cardinal

    The infinite ordinal numbers that are cardinals are called *alephs*

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.4
    1. For every \alpha there is a cardinal number greater than \alpha
    2. if \(X\) is a set of cardinals, then \(\sup X\) is a cardinal
    #+END_lemma

    for every \alpha, let \(\alpha^+\) be the least cardinal number greater than \alpha, the *cardinal successor* of
    \alpha

    #+BEGIN_proof
    1. for any set \(X\), let \(h(X)\)=the least \alpha s.t. there is no one-to-one function of \alpha
       into \(X\). There is only a set of possible well-orderings of subsets of \(X\).
       (But the collection of ordinals is a class)
       Hence there is only a set of ordinals for which a one-to-one function of \alpha into \(X\) exists.
       Thus \(h(X)\) exists.

       if \alpha is an ordinal, then \(\abs{\alpha}<\abs{h(\alpha)}\)

    2. let \(\alpha=\sup X\). if \(f\) is a one-to-one mapping of \alpha onto some \(\beta<\alpha\), let \(\kappa\in X\) be
       s.t. \(\beta<\kappa\le\alpha\). Then \(\abs{\kappa}=\abs{\{f(\xi):\xi<\kappa\}}\le\beta\), a contradiction. Thus \alpha is a cardinal
    #+END_proof

    Use Lemma ref:lemma3.4 we define the increasing enumeration of all alephs. We usually
    use \(\aleph_\alpha\) when referring to the cardinal number, and \(\omega_\alpha\) to denote the order-type
    \begin{align*}
    &\aleph_0=\omega_0=\omega\\
    &\aleph_{\alpha+1}=\omega_{\alpha+1}=\aleph_\alpha^+\\
    &\aleph_\alpha=\omega_\alpha=\sup\{\omega_\beta:\beta<\alpha\}\quad\text{ if \(\alpha\) is a limit ordinal}
    \end{align*}
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm3.5
    \(\aleph_\alpha\cdot\aleph_\alpha=\aleph_\alpha\)
    #+END_theorem
** The Canonical Well-Ordering of \texorpdfstring{\(\alpha\times\alpha\)}{α×α}
    relevant [[https://planetmath.org/canonicalorderingonpairsofordinals][reading]]

    We define a well-ordering of the class \(\Ord\times\Ord\) of ordinal pairs. Under this well-ordering,
    each \(\alpha\times\alpha\) is an initial segment of \(\Ord^2\); the induced well-ordering of \(\alpha^2\) is called
    the *canonical well-ordering* of \(\alpha^2\). Moreover, the well-ordered class \(\Ord^2\) is isomorphic
    to the class \(\Ord\)

    We define
    \begin{align*}
    (\alpha,\beta)<(\gamma,\delta)\leftrightarrow\;&\text{either }\max\{\alpha,\beta\}<\max\{\gamma,\delta\}\\
    &\text{or }\max\{\alpha,\beta\}=\max\{\gamma,\delta\}\text{ and }\alpha<\gamma\\
    &\text{or }\max\{\alpha,\beta\}=\max\{\gamma,\delta\},\alpha=\gamma\text{ and }\beta<\delta
    \end{align*}
    If \(X\subset\Ord\times\Ord\) is nonempty, then \(X\) has a least element. For each \alpha, \(\alpha\times\alpha\) is the
    initial segment given by \((0,\alpha)\). If we let
    \begin{equation*}
    \Gamma(\alpha,\beta)=\text{ the order-type of the set }\{(\xi,\eta):(\xi,\eta)<(\alpha,\beta)\}
    \end{equation*}
    then \Gamma is a one-to-one mapping of \(\Ord^2\) onto \(\Ord\), and
    \begin{equation*}
    (\alpha,\beta)<(\gamma,\delta) \quad\text{ iff }\quad \Gamma(\alpha,\beta)<\Gamma(\gamma,\delta)
    \end{equation*}
    Note that \(\Gamma(\omega\times\omega)=\omega\) and since \(\gamma(\alpha)=\Gamma(\alpha\times\alpha)\) is an increasing function of \alpha, we
    have \(\gamma(\alpha)\ge\alpha\) for every \alpha. However, \(\gamma(\alpha)\) is also continuous, and so \(\Gamma(\alpha\times\alpha)=\alpha\) for
    arbitrary large \alpha. <<Question3>>

    #+ATTR_LATEX: :options [Proof of Theorem \ref{thm3.5}]
    #+BEGIN_proof
    We will show that \(\Gamma(\omega_\alpha\times\omega_\alpha)=\omega_\alpha\). This is true for \(\alpha=0\). Thus let \alpha be the least ordinal
    s.t. \(\Gamma(\omega_\alpha\times\omega_\alpha)\neq\omega_\alpha\). Let \(\beta,\gamma<\omega_\alpha\) be s.t. \(\Gamma(\beta,\gamma)=\omega_\alpha\). Pick \(\delta<\omega_\alpha\) s.t. \(\delta>\beta\)
    and \(\delta>\gamma\). Since \(\delta\times\delta\) is an initial segment of \(\Ord\times\Ord\) in the canonical well-ordering
    and contains \((\beta,\gamma)\), we have \(\Gamma(\delta\times\delta)\supset\omega_\alpha\), and so \(\abs{\delta\times\delta}\ge\aleph_\alpha\).
    However \(\abs{\delta\times\delta}=\abs{\delta}\cdot\abs{\delta}\), and by the minimality of \alpha, \(\abs{\delta}\cdot\abs{\delta}=\abs{\delta}<\aleph_\alpha\).
    #+END_proof

    As a corollary we have
    \begin{equation*}
    \aleph_\alpha+\aleph_\beta=\aleph_\alpha\cdot\aleph_\beta=\max\{\aleph_\alpha,\aleph_\beta\}
    \end{equation*}
** Cofinality
    Let \(\alpha>0\) be a limit ordinal. We say that an increasing \beta-sequence \(\la\alpha_\xi:\xi<\beta\ra\), \beta a limit
    ordinal, is *cofinal* in \alpha if \(\lim_{\xi\to\beta}\alpha_\xi=\alpha\). Similarly, \(A\subset\alpha\) is *cofinal* in \alpha
    if \(\sup A=\alpha\). If \alpha is an infinite limit ordinal, the *cofinality* of \alpha is
    \begin{align*}
    \cf\alpha=\;&\text{the least limit ordinal $\beta$ s.t. there is an increasing}\\
    &\beta\text{-sequence }\la\alpha_\xi:\xi<\beta\ra\text{ with }\lim_{\xi\to\beta}\alpha_\xi=\alpha
    \end{align*}

    #+ATTR_LATEX:: options []
    #+BEGIN_lemma
    \(\cf(\cf\alpha)=\cf\alpha\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:lemma3.7
    Let \(\alpha>0\) be a limit ordinal
    1. if \(A\subset\alpha\) and \(\sup A=\alpha\), then the order-type of \(A\) is at least \(\cf\alpha\)
    2. if \(\beta_0\le\beta_1\le\dots\le\beta_\xi\le\dots\), \(\xi<\gamma\), is a nondecreasing \gamma-sequence of ordinals in \alpha
       and \(\lim_{\xi\to\gamma}\beta_\xi=\alpha\), then \(\cf\gamma=\cf\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1. the order-type of \(A\) is the length of the increasing enumeration of \(A\) which is an
       increasing sequence with limit \alpha
    2. if \(\gamma=\lim_{\nu\to\cf\gamma}\xi(\nu)\), then \(\alpha=\lim_{\nu\to\cf\gamma}\beta_{\xi(\nu)}\), and the nondecreasing sequence
       \(\la\beta_{\xi(\nu)}:\nu<\cf\gamma\ra\) has an increasing subsequence of length \(\le\cf\gamma\), with the same limit.
       Thus \(\cf\alpha\le\cf\gamma\)

       To show that \(\cf\gamma\le\cf\alpha\), let \(\alpha=\lim_{\nu\to\cf\alpha}\alpha_\nu\). For each \(\nu<\cf\alpha\), let \(\xi(\nu)\) be
       the least \xi greater than all \(\xi(\iota)\), \(\iota<\nu\), s.t. \(\beta_\xi>\alpha_\nu\).
       Since \(\lim_{\nu\to\cf\alpha}\beta_{\xi(\nu)}=\alpha\), it follows that \(\lim_{\nu\to\cf\alpha}\xi(\nu)=\gamma\), and so \(\cf\gamma\le\cf\alpha\).
    #+END_proof

    An infinite cardinal \(\aleph_\alpha\) is *regular* if \(\cf\omega_\alpha=\omega_\alpha\). It is *singular* if \(\cf\omega_\alpha<\omega_\alpha\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For every limit ordinal \alpha, \(\cf\alpha\) is a regular cardinal
    #+END_lemma

    #+BEGIN_proof
    if \alpha is not a cardinal, then by an bijection \(f:\abs{\alpha}\sim\alpha\), we get a cofinal sequence in
    \alpha of length \(\le\abs{\alpha}\), therefore \(\cf\alpha<\alpha\)

    if \alpha is a cardinal, \(\cf\alpha=\alpha\) by Lemma ref:lemma3.7
    #+END_proof

    [[index:unbounded]]
    Let \kappa be a limit ordinal. A subset \(X\subset\kappa\) is *bounded* if \(\sup X<\kappa\), and *unbounded*
    if \(\sup X=\kappa\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \kappa be an aleph
    1. If \(X\subset\kappa\) and \(\abs{X}<\cf\kappa\) then \(X\) is bounded
    2. If \(\lambda<\cf\kappa\) and \(f:\lambda\to\kappa\) then the range of \(f\) is bounded
    #+END_lemma

    it follows from 1 that every unbounded subset of a regular cardinal has cardinality \kappa

    #+BEGIN_proof
    1. Lemma ref:lemma3.7
    2. if \(X=\ran f\), then \(\abs{X}\le\lambda\), then use 1.
    #+END_proof

    There are arbitrary large singular cardinals. For each \alpha, \(\aleph_{\alpha+\omega}\) is a singular cardinal of
    cofinality \omega

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    An infinite cardinal \kappa is singular iff there exists a cardinal \(\lambda<\kappa\) and a
    family \(\{S_\xi:\xi<\lambda\}\) of subsets of \kappa s.t. \(\abs{S_\xi}<\kappa\) for each \(\xi<\lambda\),
    and \(\kappa=\bigcup_{\xi<\lambda}S_\xi\). The least cardinal \lambda satisfies the condition is \(\cf\kappa\).
    #+END_lemma

    #+BEGIN_proof
    If \kappa is singular, then there is an increasing sequence \(\la\alpha_\xi:\xi<\cf\kappa\ra\) with \(\lim_\xi\alpha_\xi=\kappa\).
    Let \(\lambda=\cf\kappa\), and \(S_\xi=\alpha_\xi\) for all \(\xi<\lambda\).

    If the condition holds, let \(\lambda<\kappa\) be the least cardinal for which there is a
    family \(\{S_\xi:\xi<\lambda\}\) s.t. \(\kappa=\bigcup_{\xi<\lambda}S_\xi\) and \(\abs{S_\xi}<\kappa\) for each \(\xi<\lambda\). For
    every \(\xi<\lambda\), let \(\beta_\xi\) be the order-type of \(\bigcup_{\nu<\xi}S_\nu\). The sequence \(\la\beta_\xi:\xi<\lambda\ra\) is
    nondecreasing, and by the minimality of \lambda, \(\beta_\xi<\kappa\) for all \(\xi<\lambda\). If not, then \(\beta_\xi=\kappa\)
    and \(\bigcup_{\nu<\xi}S_\nu=\kappa\). We shall show
    that \(\lim_\xi\beta_\xi=\kappa\), thus proving that \(\cf\kappa\le\lambda\).

    Let \(\beta=\lim_{\xi\to\lambda}\beta_\xi\). There is a one-to-one mapping \(f\) of \(\kappa=\bigcup_{\xi<\lambda}S_\xi\) into \(\lambda\times\beta\):
    if \(\alpha\in\kappa\), let \(f(\alpha)=(\xi,\gamma)\), where \xi is the least \xi s.t. \(\alpha\in S_\xi\) and \gamma is the order type
    of \(S_\xi\cap\alpha\). Since \(\lambda<\kappa\) and \(\abs{\lambda\times\beta}=\lambda\cdot\abs{\beta}\), it follows that \(\beta=\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \kappa is an infinite cardinal, then \(\kappa<\kappa^{\cf\kappa}\)
    #+END_theorem

    #+BEGIN_proof
    Let \(F\) be a collection of \kappa functions from \(\cf\kappa\) to \(\kappa\): \(F=\{f_\alpha:\alpha<\kappa\}\). It is enough
    to find \(f:\cf\kappa\to\kappa\) that is different from all the \(f_\alpha\). Let \(\kappa=\lim_{\xi\to\cf\kappa}\alpha_\xi\).
    For \(\xi<\cf\kappa\), let
    \begin{equation*}
    f(\xi)=\text{ least $\gamma$ s.t. }\gamma\neq f_\alpha(\xi)\text{ for all }\alpha<\alpha_\xi
    \end{equation*}
    Such \gamma exists since \(\abs{\{f_\alpha(\xi):\alpha<\alpha_\xi\}}\le\abs{\alpha_\xi}<\kappa\). Obviously, \(f\neq f_\alpha\) for all \(\alpha<\kappa\)
    #+END_proof

    Consequently \(\kappa^\lambda>\kappa\) whenever \(\lambda\ge\cf\kappa\).

* Real Numbers
    #+ATTR_LATEX: :options [Cantor]
    #+BEGIN_theorem
    label:thm4.1
    The set of all real numbers is uncountable
    #+END_theorem

    #+BEGIN_proof
    Suppose not, let \(c_0,c_1,\dots\) be an enumeration of \(\R\)

    Let \(a_0=c_0\) and \(b_0=c_{k_0}\), where \(k_0\) is the least \(k\) s.t. \(a_0<c_k\). For
    each \(n\), let \(a_{n+1}=c_{i_n}\) where \(i_n\) is the least \(i\) s.t. \(a_n<c_i<b_n\)
    and \(b_{n+1}=c_{k_n}\) where \(k_n\) is the least \(k\) s.t. \(a_{n+1}<c_k<b_n\). If we
    let \(a=\sup\{a_n:n\in\N\}\), then \(a\neq c_k\) for all \(k\).
    #+END_proof

** The Cardinality of the Continuum
    Let \(\fc\) denote the cardinality of \(\R\). As the set \(\Q\) of all rational numbers is dense
    in \(\R\), every real number \(r\) is equal to \(\sup\{q\in\Q:q<r\}\) and because \(\Q\) is countable,
    it follows that \(\fc\le\abs{P(\Q)}=2^{\aleph_0}\)

    Let \(\bC\) (the *Cantor set*) be the set of all reals of the form \(\sum_{n=1}^\infty a_n/3^n\) where
    each \(a_n=0\) or 2. \(\bC\) is obtained by removing from the closed interval \([0,1]\), the open
    intervals
    \((\frac{1}{3},\frac{2}{3})\), \((\frac{1}{9},\frac{2}{9})\),\((\frac{7}{9},\frac{8}{9})\),
    etc. \(\bC\) is in a one-to-one correspondence with the set of all \omega-sequence of 0's and 2's and
    so \(\abs{\bC}=2^{\aleph_0}\)

    Therefore \(\fc\ge 2^{\aleph_0}\), and so by the Cantor-Bernstein Theorem we have
    \begin{equation*}
    \fc=2^{\aleph_0}
    \end{equation*}
    By Cantor's Theorem ref:thm4.1 \(\fc>\aleph_0\). In ZFC, every infinite cardinal is an aleph, and
    so \(2^{\aleph_0}\ge\aleph_1\). Cantor's conjecture then become the statement
    \begin{equation*}
    2^{\aleph_0}=\aleph_1
    \end{equation*}
    known as the *Continuum Hypothesis* (CH)

** The Ordering of \(\R\)
    A linear ordering \((P,<)\) is *complete* if every nonempty bounded subset of \(P\) has a least
    upper bound.

    An ordered set is *unbounded* if it has neither a least nor a greatest element

    #+ATTR_LATEX: :options [Cantor]
    #+BEGIN_theorem
    1. Any two countable unbounded dense linearly ordered sets are isomorphic
    2. \((\R,<)\) is the unique complete linear ordering that has a countable dense subset isomorphic
       to \((\Q,<)\)
    #+END_theorem

    #+BEGIN_proof
    1. Let \(P_1=\{a_n:n\in\N\}\) and let \(P_2=\{b_n:n\in\N\}\) be two such linearly ordered sets. We construct
       an isomorphism \(f:P_1\to P_2\) in the following way: we first define \(f(a_0)\),
       then \(f^{-1}(b_0)\), then \(f(a_1)\), then \(f^{-1}(b_1)\), etc., so as to keep \(f\)
       order-preserving. For example, to define \(f(a_n)\), if it is not yet defined, we let \(f(a_n)=b_k\)
       where \(k\) is the least index such that \(f\) remains order-preserving (such a \(k\) always exists
       because \(f\) has been defined for only finitely many \(a\in P_1\), and because \(P_2\) is dense and
       unbounded)
    #+END_proof

* Question
    [[Question1]]
    [[Question2]]
    [[Question3]]
