#+TITLE: \aunclfamily\Huge Sheaves in Geometry and Logic
#+AUTHOR: Sanders Mac Lane & Leke Moerdijk

#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/SheavesInGeometryAndLogic/SheavesInGeometryAndLogic.org

* Categorical Preliminaries
  A *category* \(\bC\) consists of a collection of *objects*, a collection of
  *morphisms* and four operations; two of these operations associate with each
  morphism \(f\) of \(\bC\) its *domain* \(\dom(f)\) or \(\textd_0(f)\) and its
  *codomain* \(\cod(f)\) or \(\textd_1(f)\), respectively, both of which are objects of
  \(\bC\). The other two operations are operation which associates with each
  object $C$ of \(\bC\) a morphism \(1_C\) (or \(\id_C\)) of \(\bC\) called the
  *identity morphism* of $C$ and an operation of \(\bC\) s.t.
  \(\textd_0(f)=\textd_1(g)\) another morphism \(f\circ g\). These operations
  are required to satisfy the following axioms
  1. \(\textd_0(1_C)=C=\textd_1(1_C)\)
  2. \(\td_0(f\circ g)=\td_0(g),\td_1(f\circ g)=\td_1(f)\)
  3. \(1_D\circ f=f,f\circ 1_C=f\)
  4. \((f\circ g)\circ h=f\circ(g\circ h)\)

     
  In an arbitrary category \(\bC\), a morphism \(f:C\to D\) in \(\bC\) is called
  an *isomorphism* if there exists a morphism \(g:D\to C\) s.t. \(f\circ g=1_D\)
  and \(g\circ f=1_C\). If such a morphism $f$ exists, one says that $C$ is
  isomorphic to $D$ and one writes \(f:C\xrightarrow{\sim}D\) and \(C\cong D\)


  [[index:subobject]] [[index:equivalent]]
  A morphism \(f:C\to D\) is called an *epi(morphism)* if for any object $E$ and
  any two parallel morphisms \(g,h:D\rightrightarrows E\) in \(\bC\), \(gf=hf\)
  implies \(g=h\); one writes \(f:C\twoheadrightarrow D\) to indicate that $f$
  is an epimorphism. Dually, $f:C\to D$ is called a *mono(morphism)* if for any
  object $B$ and any two parallel morphisms \(g,h:B\rrarrow C\) in \(\bC\),
  \(fg=fh\) implies \(g=h\); in this case, one writes \(f:C\monoarrow D\). Two
  monomorphisms \(f:A\monoarrow D\) and \(g:B\monoarrow D\) with a common
  codomain $D$ are called *equivalent* if there exists an isomorphism
  \(h:A\xrightarrow{\sim}B\) with \(gh=f\). A *subobject* of $D$ is an equivalence
  class of monomorphisms into $D$. The collection \(\Sub_{\bC}(D)\) of
  subobjects of $D$ carries a natural partial order defined by \([f]\le[g]\) iff
  there is an \(h:A\to B\) s.t. \(f=gh\), where \([f]\) and \([g]\) are the
  classes of \(f:A\monoarrow D\) and \(g:B\monoarrow D\)

  \begin{center}
  \begin{tikzcd}
  A \arrow[r,rightarrowtail,"f"] \arrow[d,"h"] & D\\
  B \arrow[ur,rightarrowtail,"g"']
  \end{tikzcd}
  \end{center}

  If \(\bC\) is a category, we sometimes write \(\bC_0\) for its collection of
  objects and \(\bC_1\) for its collection of mophisms. For two objects $C$ and
  $D$, the collection of morphisms with domain $C$ and codomain $D$ is denoted
  by one of the following three symbols

  \begin{equation*}
  \Hom_{\bC}(C,D),\quad\Hom(C,D),\quad\bC(C,D)
  \end{equation*}

  [[index:locally small]]
  We shall tacitly assume we are working in some fixed universe $U$ of sets.
  Members of $U$ are then called *small* sets, whereas a collection of members of
  $U$ which doesnot itself belong to $U$ will sometimes be referred to as a *large* set.
  Given such an ambient universe $U$, a category \(\bC\) is *locally small* if for
  any two objects $C$ and $D$ of \(\bC\) the hom-set \(\Hom_{\bC}(C,D)\) is a
  small set, while \(\bC\) is called *small* if both \(\bC_0\) and \(\bC_1\) are
  small sets.

  Given a category \(\bC\), one can form a new category \(\bC^{\op}\), called
  the *opposite* or *dual* category of \(\bC\), by taking the same objects but
  reversing the direction of all the morphisms and the order of all
  compositions.

  Given a category \(\bC\) and an object $C$ of \(\bC\), one can construct the
  *comma category* or the *slice category* \(\bC/C\) (read: \(\bC\) over $C$):
  object of \(\bC/C\) are morphisms of \(\bC\) with codomain $C$, and morphisms
  in \(\bC/C\) from one such object $f:D\to C$ to another \(g:E\to C\) are
  commutative triangles in \(\bC\)

  \begin{center}
  \begin{tikzcd}
  D \arrow[dr,"f"'] \arrow[rr,"h"]& & E \arrow[dl,"g"]\\
  &C
  \end{tikzcd}
  \end{center}

  Given two categories \(\bC\) and \(\bD\), a *functor* from \(\bC\) to \(\bD\) is
  an operation $F$ which assigns to each objects $C$ of $\bC$ an object $F(C)$
  of $\bD$ and to each morphism $f$ of \(\bC\) a morphism $F(f)$ of $\bD$ in
  such a way that $F$ respects the domain and codomain as well as the identities
  and compositions.

  For a category $\bC$ there is an *identity functor* $\id_{\bC}:\bC\to\bC$, and
  for two functors $F:\bC\to\bD$ and $G:\bD\to\bE$ one can form a new functor
  $G\circ F:\bC\to\bE$ by *composition*

  [[index:natural transformation]]
  Let $F$ and $G$ be two functors from a category $\bC$ to a category $\bD$. A
  *natural transformation* \alpha from $F$ to $G$, written \(\alpha:F\to G\), is
  an operation associating with each object $C$ of $\bC$ a morphism
  $\alpha_C:FC\to GC$ of \(\bD\) in such a way that for any morphism 
  $f:C'\to C$ in $\bC$, the diagram

  \begin{center}
  \begin{tikzcd}
  FC' \arrow[r,"\alpha_{C'}"] \arrow[d,"F(f)"'] & GC' \arrow[d,"G(f)"]\\
  FC \arrow[r,"\alpha_C"] & GC
  \end{tikzcd}
  \end{center}

  commutes. The morphism $\alpha_C$ is called the *component* of \alpha at $C$. If
  every component of \alpha is an isomorphism, \alpha is said to be a *natural isomorphism*.
  If $\alpha:F\to G$ and \(\beta:G\to H\) are two natural transformation between
  functors \(\bC\to\bD\), one can define composite natural transformation
  $\beta\circ\alpha$ by setting 
  \begin{equation*}
  (\beta\circ\alpha)_C=\beta_{G(C)}\circ\alpha_C
  \end{equation*}

  By fixed categories $\bC$ and $\bD$ this yields a new category $\bD^{\bC}$:
  the objects of $\bD^{\bC}$ are functors from $\bC$ to $\bD$ while the
  morphisms of $\bD^{\bC}$ are natural transformations between such functors.
  Categories so constructed are called *functor categories*

  For categories $\bC$ and $\bD$, a functor $F:\bC^{\op}\to\bD$ is also called a
  *contravariant functor* from $\bC$ to $\bD$. In contrast, ordinary functors from
  $\bC$ to $\bD$ are sometimes called *covariant. Thus
  $C'\mapsto\Hom_{\bC}(C',C)$ for fixed $C$ yields a contravariant functor from
  $\bC$ to $\Sets$, while $C\mapsto\Hom_{\bC}(C',C)$ for fixed $C'$ is the
  covariant Hom-functor.
  \begin{center}
  \begin{tikzcd}
  C'\arrow[r]\arrow[d]&\Hom_{\bC}(C',C)
  \arrow[d]\\
  C''\arrow[r]&\Hom_{\bC}(C'',C)
  \end{tikzcd}
  \end{center}

  [[index:full functor]] [[index:faithful functor]]
  A functor $F:\bC\to\bD$ is called *full* (respectively *faithful*) if for any two
  objects $C$ and $C'$ of $\bC$, the operation
  \begin{equation*}
  \Hom_{\bC}(C',C)\to\Hom_{\bD}(FC',FC);\quad f\mapsto F(f)
  \end{equation*}
  induced by $F$ is surjective (respectively injective). A functor
  $F:\bC\to\bD$ is called an *equivalence of categories* if $F$ is full and
  faithful and if any object of $\bD$ is isomorphic to an object in the image of
  $F$. For example, if $F:\bC\to\bD$ is a functor s.t. there exists a functor
  $G:\bD\to\bC$ and natural isomorphism $\alpha:F\circ
  G\xrightarrow{\sim}\id_{\bD}$ and \(\beta:G\circ F\xrightarrow{\sim}\id_{\bC}\),
  then $F$ is an equivalence (and $G$ is sometimes called a *quasi-inverse* for
  $F$).

  We say that an object $X$ equipped with morphsims $\pi_1:X\to A$ and
  $\pi_2:X\to B$ is a *product* of $A$ and $B$ if for any other object $Y$ and any
  two maps $f:Y\to A$ and $g:Y\to B$ there is a *unique* map $h:Y\to X$ s.t.
  $\pi_1\circ h=f$ and $\pi_2\circ h=g$ [this unique is denoted by 
  $(f,g):Y\to X$ or sometimes $\la f,g\ra$]

  \begin{center}
  \begin{tikzcd}
  & Y \arrow[d,dashed,"!","{\la f, g\ra}"'] \arrow[dl,"f"'] \arrow[dr,"g"]\\
  A&X\arrow[l,"\pi_1"'] \arrow[r,"\pi_2"]&B
  \end{tikzcd}
  \end{center}
  

  A product of an \(I\)-indexed family \(A_i\) is written \(\prod_iA_i\). For a
  poset $(P,\le)$ viewed as a category in the way explained above, the product
  of two objects $p$ and $q$ is their infimum, which may or may not exist.

  The singleton set \(\{*\}\) is the set $S$, unique up to isomorphism, for
  which there is exactly one morphism $A\to S$ from any other set $A$ into $S$.
  In an arbitrary category \(\bC\), an object $C$ with the property that for any
  other object $D$ of $\bC$ there is one and only one morphism from $D$ to $C$
  is called a *terminal object* of $C$. It's often denoted by 1 or by $1_{\bC}$

  [[index:pullback]]
  Given two functions $f:B\to A$ and $g:C\to A$ between sets, one may construct
  their *fibered product* (or *pullback*) as the set
  \begin{equation*}
  B\times_A C=\{(b,c)\in B\times C\mid f(b)=g(c)\}
  \end{equation*}
  Thus $B\times_{A}C$ is a subset of the product, and therefore comes equipped
  with two *projections* $\pi_1:B\times_A C\to B$ and $\pi_2:B\times_AC\to C$
  which fit into a commutative diagram 
  \begin{center}
  \begin{tikzcd}
  B\times_AC\arrow[r,"\pi_2"]\arrow[d,"\pi_1"']&C\arrow[d,"g"]\\
  B\arrow[r,"f"']&A
  \end{tikzcd}
  \end{center}
  This diagram has the property that given any other set $X$ and functions
  $\beta:X\to B$ and $\gamma:X\to C$ s.t. $f\beta=g\gamma$, there is a unique
  function $\delta:X\to B\times_A C$ with $\pi_1\delta=\beta$ and
  $\pi_2\delta=\gamma$ [namely $\delta(x)=(\beta(x),\gamma(x))$]

  In a general category $\bC$, one says that a commutative square

  \begin{center}
  \begin{tikzcd}
  P\arrow[r,"q"]\arrow[d,"p"']&C\arrow[d,"g"]\\
  B\arrow[r,"f"]&A
  \end{tikzcd}
  \end{center}

  is a *pullback* (*square*) or a *fibered product* if it has the property just
  described for sets: given any object $X$ of $\bC$ and morphisms $\beta:X\to B$
  and $\gamma:X\to C$ with $f\beta=g\gamma$, there is a unique $\delta:X\to P$
  s.t. $p\delta=\beta$ and $q\delta=\gamma$

  \begin{center}
  \begin{tikzcd}
  X\arrow[ddr,"\beta"',bend right]\arrow[dr,dashrightarrow,"!\delta"]
  \arrow[drr,"\gamma",bend left]\\
  &P\arrow[r,"q"]\arrow[d,"p"']&C\arrow[d,"g"]\\
  &B\arrow[r,"f"']&A\\
  \end{tikzcd}
  \end{center}

  This unique map \delta is usually denoted by $(\beta,\gamma)$. Given $f:B\to A$ and $g:C\to
  A$, the pullback $P$ with its projections $P$ and $q$ is uniquely determined
  up to isomorphism and one usually writes $B\times_A C$ for this pullback. We
  also says that the arrow $p$ is the pullback of $g$ *along* $f$. Notice that $p$
  is a monomorphism if $g$ is. A morphism $f:B\to A$ in a category $\bC$ is a
  monomorphism iff the pullback of $f$ along itself is an isomorphism, iff the
  square
  \begin{center}
  \begin{tikzcd}
  B\arrow[r,"1"]\arrow[d,"1"']&B\arrow[d,"f"]\\
  B\arrow[r,"f"']&A
  \end{tikzcd}
  \end{center}
  is a pullback
  #+BEGIN_proof
  $1\to2$. Consider

  \begin{center}
  \begin{tikzcd}
  B\arrow[drr,"1",bend left]\arrow[dr,dashrightarrow,"g'"]
  \arrow[ddr,"1",bend right]\\
  &C\arrow[r,"g"]\arrow[d,"g"]&B\arrow[d,"f"]\\
  &B\arrow[r,"f"]&A\\
  \end{tikzcd}
  \begin{tikzcd}
  C\arrow[drr,"g",bend left]\arrow[dr,dashrightarrow,"1"]
  \arrow[ddr,"g",bend right]\\
  &C\arrow[r,"g"]\arrow[d,"g"]&B\arrow[d,"f"]\\
  &B\arrow[r,"f"]&A\\
  \end{tikzcd}
  \end{center}
  We have $g(g'g)=gg'g=(gg')g=g$, hence $g'g=1$

  $2\to3$. \lambda has inverse $g$
  \begin{center}
  \begin{tikzcd}
  B\arrow[drr,"1",bend left]\arrow[ddr,bend right]
  \arrow[dr,"\lambda",dashrightarrow]\\
  &C\arrow[r,"g","\cong"']\arrow[d]&B\arrow[d,"f"]\\
  &B\arrow[r]&A
  \end{tikzcd}
  \end{center}
  $3\to 1$. 
  #+END_proof

  There is an important "pasting-lemma" for pullback squares. Given a
  commutative diagram of the form
  \begin{center}
  \begin{tikzcd}
  Q\arrow[d]\arrow[r]&P\arrow[d]\arrow[r]&D\arrow[d]\\
  C\arrow[r]&B\arrow[r]&A
  \end{tikzcd}
  \end{center}
  the outer rectangle is a pullback if both inner squares are pullbacks; and
  conversely, if the outer rectangle as well as the right-hand square pullbacks,
  then so is the left-hand square

  [[index:equalizer]]
  For two parallel arrows $f:A\to B$ and $g:A\to B$ in a category $\bC$, the
  *equalizer* of $f$ and $g$ is a morphism $e:E\to A$ s.t. $fe=ge$ and which is
  universal with this property; that is, given any other morphism $u:X\to A$ in
  $\bC$ s.t. $fu=gu$, there is a unique $v:X\to E$ s.t. $ev=u$
  \begin{center}
  \begin{tikzcd}
  E\arrow[r,"e"]&A\arrow[r,shift right,"f"']\arrow[r,shift left,"g"]&B\\
  X\arrow[u,dashrightarrow,"v"]\arrow[ur,"u"']
  \end{tikzcd}
  \end{center}

  Equalizer need not always exists. However, in the category of sets the equalizer
  of any pair of functions $f,g\rrarrow B$ exists, and can be constructed be the
  set 
  \begin{equation*}
  E=\{a\in A\mid f(a)=g(a)\}
  \end{equation*}
  where $e$ is set inclusion

  Consider two categories $\bA$ and $\bX$ and two functors between them in
  opposite directions, say
  \begin{equation*}
  F:\bX\to\bA\quad G:\bA\to\bX
  \end{equation*}
  One says that $G$ is *right adjoint* to $F$ (and that $F$ is *left adjoint* to
  $G$, notation $F\dashv G$) when for any two objects $X$ from $\bX$ and $A$
  from $\bA$ there is a natural bijection between morphisms
  \begin{equation}
  \frac{X\xrightarrow{f}GA}{FX\xrightarrow{h}A}\label{eq-6}
  \end{equation}
  in the sense that each morphism $f$ uniquely determines a morphism $h$, and
  conversely. This bijection is to be natural in the following sense: given any
  morphisms $\alpha:A\to A'$ in $\bA$ and $\xi:X'\to X$ in $\bX$, and
  corresponding arrows $f$ and $h$ composites also correspond
  \begin{equation*}
  \frac{X'\xrightarrow{\xi}X\xrightarrow{f}GA\xrightarrow{G\alpha}GA'}
  {FX'\xrightarrow{F\xi}FX\xrightarrow{h}A\xrightarrow{\alpha}A'}
  \end{equation*}
  If we write this bijective correspondence as
  \begin{equation}
  \theta:\Hom_{\bX}(X,GA)\xrightarrow{\sim}\Hom_{\bA}(FX,A)\label{eq-8}
  \end{equation}
  then this naturality condition can be expressed by the equation
  \begin{equation*}
  \theta(G(\alpha)\circ f\circ\xi)=\alpha\circ\theta(f)\circ F(\xi)
  \end{equation*}
  Given \theta as in eqref:eq-8, and an object $X$ in $\bX$, setting $A=FX$ gives a
  unique map 
  \begin{equation*}
  \eta=\eta_X:X\to GFX
  \end{equation*}
  s.t. $\theta(\eta_X)=1_{F(X)}$. This map $\eta_X$ is called the *unit* of the
  adjunction (at $X$). If one takes \(\xi=1_X,A=FX,f=\eta,\alpha=1_A\) and $A'=A$,
  then
  \begin{equation*}
  \frac{X\xrightarrow{1_X}X\xrightarrow{\eta}GFX\xrightarrow{Gh}GA}
  {FX\xrightarrow{F1_X}FX\xrightarrow{h}A\xrightarrow{1_A}A}
  \end{equation*}

  In short, \eta determined the adjunction, since $h$ corresponds to
  $G(h)\circ\eta_X$ under the correspondence eqref:eq-6. This means that each
  $f$ determines uniquely an $h$ which makes the following triangle commutes.

  \begin{center}
  \begin{tikzcd}
  X\arrow[r,"\eta"]\arrow[dr,"f"']&GFX\arrow[d,dashrightarrow,"Gh"]\\
  &GA
  \end{tikzcd}
  \begin{tikzcd}
  FX\arrow[d,dashrightarrow,"h"]\\A
  \end{tikzcd}
  \end{center}
  
  One expresses this by saying that $\eta=\eta_X$ is *universal* among arrows from
  $X$ to an object of the form $GA$. This also implies that when the functor $G$
  is given, the object $FX$ is uniquely determined up to isomorphism. In other
  words, given a functor $G$, its left adjoint $F$ is unique up to isomorphism.

* Index
  # This eliminates the duplicate Index section name
  \renewcommand{\indexname}{}
  [[printindex:nil]]
