#+TITLE: Simple Theories and Hyper Imaginaries
#+AUTHOR: Enrique Casanovas
#+EXPORT_FILE_NAME: ../latex/SimpleTheoriesAndHyperImaginaries/SimpleTheoriesAndHyperImaginaries.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    \(T\) is a complete theory of language \(L\) with infinite models and \(\fC\) is its monster
    model. \(a,b,c\) are tuples of elements of \(\fC\).

    For any subclass \(A\) of \(\fC\), \(\tp(a/A)\) is the class of all formulas with parameters
    in \(A\) realized by \(a\) in \(\fC\), and \(\Aut(\fC/A)\) is the group of all automorphisms
    of \(\fC\) which fix \(A\) pointwise

    If \(A\) is a set, then \(\tp(a/A)=\tp(b/A)\) iff \(f(a)=f(b)\) for
    some \(f\in\Aut(\fC/A)\). \(a\in A\) means that all the elements in the tuple \(a\) belong to \(A\).

    A tuple is a sequence, not necessarily finite. A class \(A\) of tuples is *bounded* if its small
    compared with the monster model, hence if it is a set.

    Or we can assume the monster model is a saturated model of inaccessible cardinality \kappa; in this
    case we can replace the words *proper class* and *set* by *of cardinality* \kappa and *of
    cardinality* \(<\kappa\) respectively

    Sometimes it is convenient to add an end point \(\infty\) to \(On\), hence \(\infty=\sup_{\alpha\in On}\alpha\). The
    set of all mappings from \(I\) into \(J\) is denoted by \(J^I\). Hence \(\kappa^\lambda\) has two meanings:
    cardinal exponentiation and set of functions.

    For a sequence \((a_i:i<\alpha)\) and any \(j\le\alpha\) we use \(a_{< j}\) for \((a_i:i<j)\). The union of
    two sets \(A,B\) is sometimes denoted by \(AB\)

    A *finitary type* is a type in finitely many variables. For a formula \(\varphi(x)\) we write \(\vDash\varphi(a)\)
    or \(a\vDash\varphi(x)\) to mean \(\fC\vDash\varphi(a)\), and similarly for a type.

    We write \(a\equiv_Ab\) to express equality of types over \(A\): \(\tp(a/A)=\tp(b/A)\). For
    sets \(A,B\) we some times use notations like \(\tp(A/C)\) and \(A\equiv_CB\). An implicit
    enumeration of \(A\) should be assumed. Hence \(A\equiv_CB\) means that \(a\equiv_Cb\) for some
    tuples \(a\) and \(b\) enumerating \(A\) and \(B\) respectively

    If \(\pi(x)\) is a partial type, \(\pi(\fC)\) is the class of tuples (of the length of \(x\)) that
    satisfy \pi, and more generally, \(\pi(A)\) is the set of all tuples \(a\in A\) s.t. \(\vDash\pi(a)\).
    Equivalence of partial types \(\Sigma(x)\) and \(\pi(x)\) (perhaps over different sets)
    means \(\Sigma(\fC)=\pi(\fC)\). We write \(\Sigma(x)\equiv\pi(x)\) for it.

    A model \(M\) is always an elementary submodel of the monster model \(\fC\). In fact, \(\fC\) is the
    union \(\bigcup_{i\in On}M_i\) of an elementary chain \((M_i:i\in On)\) of models, where each \(M_i\)
    is \(\abs{i}\)-saturated

    If \(\Sigma(x)\) is over \(A\), then we mean relative to the theory \(T(A)\) of the monster model
    expanded by constants for the elements of \(A\). This amounts to being the same for \Sigma as being
    finitely satisfiable in the monster model (expanded by the parameters in \(A\))

    It is convenient to work with complete types over the monster model. We call them *global types*.
    It makes sense to consider the space of types \(S(\fC)\) although every global type \(\fp\in S(\fC)\) is
    in fact a proper class.

    The group \(\Aut(\fC/A)\) acts naturally on \(\fC\) but also on the space of types \(S(\fC)\). The
    image of an object by some \(f\in\Aut(\fC/A)\) is often called an *\(A\)-conjugate* of the object
    by \(f\). If \(\varphi(x,y)\in L\), the \(A\)-conjugate of \(\varphi(x,a)\) by \(f\in\Aut(\fC/A)\) is the
    formula \(\varphi(x,a)^f=\varphi(x,f(a))\). Similarly for types. If \(\fp\in S(\fC)\), the \(A\)-conjugate of \(\fp\)
    by \(f\in\Aut(\fC/A)\) is the global type \(\fp^f\in S(\fC)\) all whose formulas are conjugate by \(f\) of
    formulas in \(\fp\). Hence \(\fp^f=\{\varphi(x)^f:\varphi(x)\in\fp\}\).

    An element \(a\in\fC\) is *definable over* the set \(A\) if its orbit under \(\Aut(\fC/A)\) is a
    singleton and it is *algebraic over* \(A\) if the orbit is finite. For any set \(A\), the set of
    all elements definable over \(A\) is the *definable closure* of \(A\), denoted \(\dcl(A)\), and
    the set of all elements algebraic over \(A\) is the *algebraic closure* of \(A\), denoted
    by \(\acl(A)\). These definitions can be extended to the case of an arbitrary class \(A\subseteq\fC\) by
    letting \(\dcl(A)\)be the union of all \(\dcl(B)\) where \(B\) ranges over subsets of \(A\), and
    similarly for \(\acl(A)\). Note that \(\dcl\) and \(\acl\) are finitary closure operators on
    subclasses of the monster model, i.e., they are operators \(\cl\) s.t.
    1. \(A\subseteq\cl(A)\)
    2. If \(A\subseteq B\), then \(\cl(A)\subseteq\cl(B)\)
    3. \(\cl(\cl(A))\subseteq\cl(A)\)
    4. If \(a\in\cl(A)\), then \(a\in\cl(A_0)\) for some finite \(A_0\subseteq A\)


    A partial type \(\pi(x)\) over \(A\) is called *algebraic* (over \(A\)) if all realizations of \pi
    belong to \(\acl(A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A relation \(R\) (a subclass of \(\fC^I\) for some index set \(I\)) is *\(A\)-invariant* if it is
    preserved under automorphisms of \(\fC\) fixing \(A\) pointwise, that is,
    \begin{equation*}
    R(a)\Rightarrow R(f(a))
    \end{equation*}
    for all \(a\), for all \(f\in\Aut(\fC/A)\). This clearly implies \(R(a)\Leftrightarrow R(f(a))\)

    #+END_definition

    #+BEGIN_remark
    For every set \(A\), every \(A\)-invariant relation \(R\) is definable by a disjunction of types
    over \(A\), namely: \(R(a)\Leftrightarrow a\vDash\bigvee_{R(b)}\bigwedge\tp(b/A)\)
    #+END_remark
