#+TITLE: Stability in Model Theory
#+AUTHOR: Daniel Lascar
#+EXPORT_FILE_NAME: ../latex/StabilityInModelTheory/StabilityInModelTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    The problem that we are going to treat is of this kind: we shall try to classify the models of a
    theory \(T\)

    First we can freely make a certain number of assumptions about \(T\). We can start to classify
    its models by using their elementary theory. This amounts to supposing \(T\) to be complete.
    Then again, if we are sure that a theory \(T'\) in a language \(L'\) has exactly the same models
    as \(T\) - i.e., that there is a natural bijection between the models of \(T\) and those
    of \(T'\) - and that \(T'\) is easier to handle, we may as well work with \(T'\) as with \(T\).
    Hence we may assume that \(T\) admits the elimination of quantifiers: for each
    formula \(\varphi(v_1,\dots,v_n)\) we adjoin a new \(n\)-ary predicate \(R_{\varphi}(v_1,\dots,v_n)\) and consider the
    theory \(T'\) obtained by adding to \(T\) the axioms
    \begin{equation*}
    \forall v_1,\dots,v_n[\varphi(v_1,\dots,v_n)\leftrightarrow R_\varphi(v_1,\dots,v_n)]
    \end{equation*}
    Then \(T'\) admits the elimination of quantifiers and has the same models as \(T\)

    The gain is that every monomorphism becomes elementary. We denote by \(\bC(T)\) the category whose
    objects are the models of \(T\) and whose arrows are the elementary mappings

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. Consider the theory of an equivalence relation with an infinite number of classes each having
        infinitely many elements. Then, to have the isomorphism type of model, we first need the number
        of classes, which is a cardinal \lambda, and secondly the cardinality of each of the classes; in other
        words, we need a set of \lambda cardinals
    2. We can complicate the preceding example. Take two equivalence relations, \(E_1\) and \(E_2\),
       where \(E_2\) is finer than \(E_1\) and \(E_1\) has infinitely many classes. Each \(E_1\)-class
       contains infinitely many \(E_2\)-classes and each \(E_2\)-class is infinite. If we try to give
       the invariants that fix the isomorphism type of a model we are faces with a tree of dimensions
    #+END_examplle

    denote by \(I(\lambda,T)\) the number of models, up to isomorphism, of cardinality \lambda. The search for
    the function \(\lambda\to I(\lambda,T)\) is interesting from several points of view
    1. Except when \(I(\lambda,T)\) has its greatest a priori value, namely \(2^\lambda\), it is hard to see how
       to calculate \(I(\lambda,T)\) without classifying the models of \(T\). It allows us to replace a
       vague problem (classify the models) with a precise one (calculate \(I(\lambda,T)\))
    2. In the tiresome case \(I(\lambda,T)=2^\lambda\) it is legitimate to decide that we had better give up
    3. Finally, the growth of the function \(I(\lambda,T)\) will give us a hierarchy for theories


    This granted, the problem presents itself as follows: we first define a set of theories, the
    stable theories; these are the theories of which no model contains a set totally ordered by a
    formula. We can then dismiss the unstable theories, for which \(I(\lambda,T)=2^\lambda\) for
    all \(\lambda>\abs{T}\)

    If we now re-examine the examples of \(\aleph_1\)-categorical theories we find that we have cracked
    the problem, for we have at our disposal:
    1. a concept of independence
    2. from which flows a concept of basis and dimension
    3. a concept of models generated by ...


    It is accordingly a matter of generalizing these three points
    a. For the first we need the assumption of stability: this is the concept of forking
    b. For the second we need a stronger assumption: superstability. But it matters little because
       we show again that if \(T\) is non-superstable then \(I(\lambda,T)=2^\lambda\) for all \(\lambda\ge\abs{T}\)
    c. For the third point we have the concept of prime model: a model is prime over one of its
       substructure \(A\) if it can be embedded elementary in every model that contains \(A\).
       When \(T\) is an \omega-stable theory we prove the existence and uniqueness of a prime model over
       an arbitrary set of parameters


    Unfortunately the hypothesis of \omega-stability does not come free: there are superstable theories
    that are not \omega-stable. However, if we confine ourselves to the category of models that have
    certain saturation properties (\(\aleph_1\)-saturated models for countable stable theories and a
    slightly weaker condition called \(\aleph_\epsilon\)-saturation for superstable theories), then we can prove
    the existence and uniqueness of the prime model


    In all that follows, \(L\) will be a countable language and \(T\) a complete theory in \(L\)
    admitting the elimination of quantifiers.

    When \(A\subset M\), we write \(T(A)\) for the set of those formulas with parameters in \(A\) that are
    true in \(M\). By convention, \(T(A)\) does not depend on \(M\), which is to say that we rule
    out consideration of the situation where \(A\) is a subset of \(M\) and of \(M'\), with formulas
    in parameters in \(A\) that are true in \(M\) but not in \(M'\). This convention allows us the
    abuse of using the same letter for a model and its underlying set

* Types
** Types
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.1
    Let \(\bara\in M^n\) and \(\barb\in M'^n\). TFAE
    1. \(\tp^M(\bara)=\tp^{M'}(\barb)\)
    2. There exists a model \(N\) and elementary mappings \(f\) and \(g\) from \(M\) and \(M'\)
       respectively into \(N\) s.t. \(f(\bara)=g(\barb)\)
    3. There exist a model \(N\succ M\) and an elementary mapping \(g\) from \(M'\) into \(N\) s.t. \(g(\barb)=\bara\)
    #+END_proposition

    #+BEGIN_proof
    \(3\to 2\). trivial

    \(2\to 3\). By coping \(N\)  we can find \(N'\succ M\) and an isomorphism \(f':N'\cong N\)

    \(2\to 1\) obvious

    \(1\to 2\) we need the following lemma (Proposition 3.1.4 of C&K)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Two structures are elementarily equivalent iff they can be embedded elementarily in the same
    third structure
    #+END_lemma

    #+BEGIN_proof
    \(\Leftarrow\) trivial

    \(\Rightarrow\). Suppose two structures is \(M\) and \(N\), Then prove \(T(M)\cup T(N)\) is finitely
    satisfiable.
    #+END_proof

    #+ATTR_LATEX: :options [Continued]
    #+BEGIN_proof
    Condition 1 means precisely that \((M,\bara)\equiv(N,\barb)\). Hence there exists a
    structure \((N,\barc)\) and elementary embeddings \(f\) and \(g\) of \((M,\bara)\)
    and \((M',\barb)\) respectively in \((N,\barc)\). We then have \(f(\bara)=g(\barb)=\barc\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\bara,\barb\in M^n\). TFAE
    1. \(\tp(\bara)=\tp(\barb)\)
    2. There exist \(N\succ M\) and an automorphism \(f\) of \(N\) s.t. \(f(\bara)=\barb\)
    #+END_proposition

    #+BEGIN_proof
    \(1\to 2\). By ref:1.1, there is \(M_1\succ M\) and an elementary mapping \(f_1:M\to M_1\)
    s.t. \(f_1(\bara)=\barb\). Then the structure \((M_1,c)_{c\in M}\) is elementarily equivalent
    to \((M_1,f_1(c))_{c\in M}\), and we can find an elementary extension \((M_2,f_1(c))_{M}\)
    of \((M_1,f_1(c))_{c\in M}\) and an elementary mapping \(f_2\) from \((M_1,c)_{c\in M}\)
    into \((M_2,f_1(c))_{c\in M}\); \(f_2\) is then an elementary mapping from \(M_1\) to \(M_2\)
    extending \(f_1\). In this way we construct inductively an elementary chain \((M_n)_{n\in\omega}\) and
    mappings \(f_n\) from \(M_{n-1}\) to \(M_n\), with \(f_n\) extending \(f_{n-1}\). Then \(f\),
    the union of the mappings \(f_n\) is an automorphism of \(N=\bigcup_{n\in\omega}M_n\) and \(f(\bara)=\barb\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(A\subset M\) and \(n\in\omega\). An \(n\)-type on \(A\) is a complete theory in \(L(A\cup\{x_1,\dots,x_n\})\)
    containing \(T(A)\), where the \(x_i\) are new individual constants
    #+END_definition

    Because of the elimination of quantifiers, we do not need to mention \(M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(p\in S_n(A)\). Then there exist \(M\supset A\) and \(\bara\in M^n\) s.t. \(\tp(\bara/A)=p\)
    #+END_proposition

    #+BEGIN_proof
    A model of \(p\) is a structure \((M,a_1,\dots,a_n)\), where \(M\) is a model of \(T(A)\) - or, up to
    isomorphism and an abuse of language, a model of \(T\) containing \(A\) - and \(a_1,\dots,a_n\) are
    interpretations of the \(x_i\)
    #+END_proof

    If \(t\) is a theory in \(L(A\cup\{\barx_n\})\), then \(\{p\in S_n(A):t\subset p\}=\bigcap_{\varphi\in t}[\varphi]\) is a closed
    set of \(S_n(A)\). Conversely, every closed set \(X\) of \(S_n(A)\) is of this
    form \(\{p\in S_n(A):t\subset p\}\):
    consider \(t\in\bigcap_{p\in X}p\). If \(p\in X\) then \(t\subset p\); now if \(t\subset p\) and \(\varphi\in p\),
    then \(\neg\varphi\notin t\), and consequently \(X\) contains a type \(p_1\) s.t. \(\varphi\in p_1\) and \(p_1\in[\varphi]\).
    This shows that \(p\) is in the closure of \(X\).
    #+LATEX: \wu{
    For any neighborhood \(p\in[\varphi]\), as \(t\subset p\), \(\neg\varphi\notin t\) implies there is other set containing
    both \(t\) and \varphi
    #+LATEX: }

    If \(p\in S_n(B)\), given an elementary map \(f:A\to B\), we can derive a mapping \(\barf:S_n(B)\to S_n(A)\)
    \begin{equation*}
    \barf_n(p)=\{\varphi(\bara,\barx_n):\varphi(\barv_k,\barx_n)\in L(\barx_n),\bara\in A^k,\varphi(f(\bara),\barx_n)\in p\}
    \end{equation*}
    Then:
    * \(\barf_n(p)\) is a type
    * \(\barf_n\) is continuous: \(\barf_n^{-1}([\varphi(\bara,\barx_n)])=[\varphi(f(\bara),\barx_n)]\)
    * \(\barf_n\) is surjective
    * If \(f:A\to B\) and \(g:B\to C\) are elementary, then \((\bbar{g\circ f})_n=\barf_n\circ\barg_n\)
    * If \(A\subseteq B\) and \(f\) is the inclusion, then \(\barf_n(p)=p\cap L(A\cup\{\barx_n\})\). We shall denote
      this type by \(p\upharpoonright A\). If \(\tp(\bara/B)=p\), then \(p\upharpoonright A=\tp(\bara/A)\)
    * If \(f\) is an isomorphism, then \(\barf_n\) is a homeomorphism



    If \(I\) is any set, an *\(I\)-type* on \(A\) is a complete theory in \(L(A\cup\{x_i:i\in I\})\)
    containing \(T(A)\)

    \(p\in S_n(A)\) is *isolated* if \(\{p\}\) is a closed open set of \(S_n(A)\). Then there is a
    formula \(\varphi\in L(L\cup\{\barx_n\})\) s.t. \([\varphi]=\{p\}\). This amounts to saying that \(p\) is a logical
    consequence of \varphi
** The omitting types theorem
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(E\) be a topological space and let \(A\subset E\)

    We say that \(A\) is *nowhere dense* if it contains no non-empty open set

    \(A\) is *meagre* if it is contained in a countable union of nowhere dense closed sets
    #+END_definition

    #+ATTR_LATEX: :options [Baire]
    #+BEGIN_theorem
    If \(E\) is a compact space and \(A\) is a meagre subset of \(E\), then \(A\neq E\)
    #+END_theorem

    Let \(X\) be a closed set in \(S_n(\emptyset)\). We have seen that there is a set \(t\) of formulas
    in \(L(\barx_n)\) s.t. \(X=\{p\in S_n(\emptyset):t\subset p\}\). How do we express the fact that \(X\) is nowhere
    dense? For every formula \(\varphi(\barv_n)\), if \(T\vdash\exists\barv_n\varphi(\barv_n)\), then it is not true
    that \(\varphi(\barx_n)\vdash t\)
    #+LATEX: \wu{
    \(T\vdash\exists\barv\varphi(\barv)\) means \(\varphi\) is consistent and \([\varphi]\neq\emptyset\). Then by the definition of
    meagre, \([\varphi]\not\subseteq X\) and hence there is \(p\in[\varphi]\setminus X\). \(p\) is realised in some model \(M\)
    of \(T\) but \(M\not\vdash t\) as \(t\not\subset p\) and \(p\) is complete.
    Thus \(\varphi(\barx)\not\vdash t\)
    #+LATEX: }

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For each \(n\in\omega\) let \(X_n\) be a meagre set in \(S_n(\emptyset)\). Then there is a model of \(T\) that
    omits every element of \(\bigcup_{n\in\omega}X_n\)
    #+END_theorem

    #+BEGIN_proof
    We work in the space of \omega-types. For each \(n\in\omega\) and each function \(\alpha:n\to\omega\) we consider the
    functions \(\tilalpha(p)=\{\varphi(x_1,\dots,x_n):\varphi(x_{\alpha(1)},\dots,x_{\alpha(n)})\in p\}\)

    In other words, if \((a_i:i\in\omega)\) realizes \(p\), then \((a_{\alpha(1)},\dots,a_{\alpha(n)})\)
    realizes \(\tilalpha(p)\)

    *Claim* The function \(\tilalpha\) is continuous and open

    Let \(\varphi(\barx)\in L(x_i:i\in\omega)\); we have to evaluate \(\tilalpha([\varphi(\barx)])\). While possibly
    including some \(x\) that serve no purpose, we may write \(\varphi(\barx)\) in the
    form \(\varphi(x_{\alpha(1)},\dots,x_{\alpha(n)},\barx')\), where \(\barx'\) is a sequence of \(x_i\) whose indices
    do not appear in the image of \alpha. We show that
    \begin{equation*}
    \tilalpha([\varphi(\barx)])=[\exists\barv\varphi(\barx_n,\barv)]\cap[\bigwedge x_i=x_j:i,j\le n,\alpha(i)=\alpha(j)]
    \end{equation*}
    Indeed, if \(\varphi(x)\in p\) then \(\exists\barv\varphi(x_{\alpha(1)},\dots,x_{\alpha(n)},\barv)\in p\) and, by definition
    of \(\tilalpha\), \(\exists\barv\varphi(\barx_n,\barv)\in\tilalpha(p)\); in the same
    way \((x_i=x_j)\in\tilalpha(p)\) whenever \(\alpha(i)=\alpha(j)\)

    Conversely, suppose that
    \begin{equation*}
    \exists\barv\varphi(\barx_n,\barv)\wedge\bigwedge\{x_i=x_j:i,j\le n,\alpha(i)=\alpha(j)\in q\in S_n(\emptyset)\}
    \end{equation*}
    Then \(q'=\{\psi(x_{\alpha(1)},\dots,x_{\alpha(n)}):\psi(\barx_n)\in q\}\) is a complete theory
    in \(L(x_{\alpha(i)}:1\le i\le n)\) that contains \(T\) and \(\exists\barv\varphi(x_{\alpha(1)},\dots,x_{\alpha(n)},\barv)\).
    Let \(\barx'\) be a sequence of \(x_i\) whose indices do not belong to the image of \alpha and whose
    length is that of \(\barv\); then \(q'\cup\{\varphi(x_{\alpha(1)},\dots,x_{\alpha(n)},\barx')\}\) is consistent and can
    be extended to a type \(p\in S_\omega(\emptyset)\). We then obviously have \(\tilalpha(p)=q\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(X\) and \(Y\) be topological spaces and let function \(f:X\to Y\) be continuous and open.
    Then the inverse image under \(f\) of a meagre set is meagre
    #+END_lemma

    #+ATTR_LATEX: :options [Continued]
    1#+BEGIN_proof
    From the two lemmas above we deduct that the set \(E=\bigcup_{n\in\omega}\bigcup_{\alpha:n\to\omega}\tilalpha^{-1}(X_n)\)
    in \(S_\omega(\emptyset)\) is meagre. The construction of \(E\) ensures us that if \(\bara=(a_i:i\in\omega)\)
    realizes a point of \(S_n(\emptyset)-E\) and if \(\barb\) is a subsequence of \(\bara\) of length \(n\),
    then \(t(\barb)\notin X_n\). In other words we omit in \(\{a_i:i\in\omega\}\) all the wanted types. In remains
    to arrange that this set is a model

    Let \(\varphi(\barx,\barv_0)\) be a formula in one free variable in \(L(x_i:i\in\omega)\).
    Put \(0_\varphi=\bigcup_{i\in\omega}[\exists\barv_0\varphi(\barx,v_0)\to\varphi(\barx,x_i)]\) . Then \(0_\varphi\) is open and and its
    complement is nowhere dense: we must show that \(0_\varphi\) meets every non-empty open set: indeed it
    is easily seen that if \(\psi(\barx')\in L(x_i:i\in\omega)\) is consistent with \(T\), and if \(x_i\) appears
    neither in \(\barx\) nor in \(\barx'\), then the formula
    \begin{equation*}
    (\exists v_0\varphi(\barx,v_0)\to\varphi(\barx,x_i))\wedge\psi(\barx')
    \end{equation*}
    is consistent with \(T\)

    We then see, by Baire's theorem, that \(\bigcap_\varphi 0_\varphi\cap(S_\omega(\emptyset)-E)\) is non-empty. If \((a_i:i<\omega)\) is a
    sequence in a model \(M\) that realizes a type of this set, then it is an elementary
    substructure of \(M\) by the Tarski-Vaught test, and we have seen that it omits every element
    of \(\bigcup_{n\in\omega}X_n\)
    #+END_proof
* Types over models
    In this chapter we begin to define a notion of independence. For \(A\subset M\) and \(\bara,\barb\in M\)
    we want to give meaning to the expression \(\bara\) and \(\barb\) are independent over \(A\). We
    begin by dealing with the particular case where \(A\) is an elementary submodel of \(M\). The
    idea is to consider \(\tp(\bara/A)\) and to distinguish certain types among its possible
    extensions to \(A\cup\{b\}\)
** The fundamental ordering
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(p\in S_n(M)\). The *class* of \(p\), denoted by \(\cl(p)\), is the
    set \(\{\varphi(\barx_n,\barv):\varphi(\barx_n,\barv)\in L(\barx_n)\wedge\exists\bara\in M(\varphi(\barx_n,\bara)\in p)\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *fundamental ordering* for \(n\)-types is the set
    \begin{equation*}
    O_n(T)=\{\cl(p):M\vDash T,p\in S_n(M)\}
    \end{equation*}
    ordered by inverse inclusion: we say that \(p\ge q\) if \(\cl(p)\subseteq\cl(q)\)
    #+END_definition

    If \(A\subset M\) and \(p\in S_n(M)\) we can define the class of \(p\) over \(A\):
    \begin{equation*}
    \cl(p/A)=\{\varphi(\barx_n,\barv)\in L(A\cup\barx_n):\exists\bara\in M(\varphi(\barx_n,\bara)\in p)\}
    \end{equation*}

    Then the set of all classes over \(A\) for all models containing \(A\) is \(O_n(A)\)

    It is clear that if \(\cl(p)\) and \(\cl(q)\) are  comparable,
    then \(p\upharpoonright\emptyset=q\upharpoonright\emptyset\). On the other hand, if \(M\prec N\), if \(p\in S_n(M)\)
    and if \(q\) is an extension of \(p\) to \(N\), then \(\cl(p)\subseteq\cl(q)\) and
    even \(\cl(p/M)\subseteq\cl(q/M)\)

    The minimal types for the fundamental ordering are exactly those that are realised, that is to
    say those whose classes contains \(\barx_n=\barv_n\). If \(p\) and \(q\) are such types,
    then \(\cl(p)=\cl(q)\) iff \(p\uhr\emptyset=q\uhr\emptyset\)



    For \(\DLO\), a type \(p\in S_1(M)\) is determined by the following sets
    \begin{align*}
    &X_p=\{a\in M:(x=a)\in p\}\\
    &Y_p=\{a\in M:(x<a)\in p\}
    \end{align*}
    We can distinguish several kind of type
    1. If \(X_p\neq\emptyset\), then \(p\) is realised in \(M\)
    2. If \(X_p=\emptyset\) and \(Y_p=\emptyset\), a realisation of \(p\) is larger than every element of \(M\). We
       call this type \(+\infty\)
    3. If \(X_p=\emptyset\) and \(Y_p=M\) we call the type \(-\infty\)
    4. If \(X_p=\emptyset\) and \(Y_p=\{a\in M:a>a_0\}\) for some \(a_0\in M\), we call the type \(a_0^+\)
    5. If \(X_p=\emptyset\) and \(Y_p=\{a\in M:a\ge a_0\}\) for some element \(a_0\in M\), we call the type \(a_0^-\)
    6. Finally the types that do not belong to any of the five preceding families are called
       *irrational*


    The types in families 4 and 5 are called *rational*

    It can be verified that there are four classes of types: \(+\infty\) and \(-\infty\) are maximal and
    incomparable; then follow the rational and irrational types in the same class; realized types
    are in the same minimal class

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\calu\) be a ultrafilter on a set \(I\) and, for each \(i\in I\), let \(p_i\in S_n(M_i)\). The
    ultraproduct of the \(p_i\), denoted by \((p_i)/\calu\), is the type on the ultraproduct of
    the \((M_i)/\calu\), defined by:

    If \(\varphi(\barx_n,\barv_k)\in L(\barx_n)\), and if \(\bara=(\bara(i))_{i\in\calu}\) is a sequence of
    length \(k\) in \((M_i)/\calu\), then \(\varphi(\barx_n,\bara)\in(p_i)/\calu\)
    iff \(\{i:\varphi(\barx_n,\bara(i))\in p_i\}\in\calu\)

    If all the \(M_i\) are equal to the same model \(M\) and if \(p_i\in S_n(M)\), write \(p^{\calu}\)
    for \((p_i)/\calu\)

    #+END_definition

    Note that if, for all \(i\), \(N_i\succ M_i\) and \(c_i\in N_i\) realizes \(p_i\), then \((p_i)/\calu\) is
    precisely realised by the element \((c_i)/\calu\) of \((N_i)/\calu\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\calu\) be a ultrafilter on \(I\) and let \(p_i\in S_n(M_i)\) for all \(i\in I\).
    If \(\varphi(\barx_n,\barv)\in L(\barx_n)\), then
    \begin{equation*}
    \varphi\in\cl((p_i)/\calu) \quad\text{ iff }\quad\{i:\varphi\in\cl(p_i)\}\in\calu
    \end{equation*}
    If \(p\in S_n(M)\) then \(\cl(p^{\calu})=\cl(p)\) and even \(\cl(p^{\calu}/M)=\cl(p/M)\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(p\in S_n(M)\) and \(q\in S_n(N)\). TFAE
    1. \(\cl(p)\subseteq\cl(q)\)
    2. There exist an ultrafilter \(\calu\), \(N'\prec N^{\calu}\) and an isomorphism \(f\) from \(M\)
       onto \(N'\) s.t. \(\barf(q^{\calu}\uhr N')=p\)
    #+END_proposition
