#+title: Stable Groups

#+AUTHOR: Bruno Poizat

#+EXPORT_FILE_NAME: ../latex/StableGroups/StableGroups.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Chain
** Stable groups; examples
    A stable group is a group which is definable in a stable structure.

    By Parameter separation theorem, if \(G\) is definable in \(M\), every subset of \(G^n\) which is
    definable with parameters in \(M\) can be defined by using only the parameters \(\bara\) which
    serve to define \(G\) together with other parameters which are all in \(G\). Therefore, if \(G\)
    is equipped with all relations definable in \(M\), with \(\bara\) as parameters, we can forget
    that structure \(M\) from which \(G\) came: The stability of \(M\) confers on \(G\) a whole
    model-theoretic autonomy

    Consider an infinite group \(G\) of exponent 2, that is to say, an infinite-dimensional vector
    space over the 2-element field, with a unary predicate \(A\) defining an infinite subset \(G\)
    of linearly independent elements. Let \(A_n\) denote the set of elements of \(G\) which are sums
    of \(n\) distinct elements of \(A=A_1\); by convention, \(A_0\) consists only of the
    identity. \(G\) admits quantifier elimination when the \(A_n\) are added to the language, and
    also the relations among elements of \(A_{n_1},\dots,A_{n_m}\) specifying the equality of different
    coordinates. \(G\) is a structure of Morley rank \omega; here is the description of the types
    over \(G\):
    * there is one and only one type, which we call generic, which omits all the
      formulas \(A_n(x-y)\): for every \(a\in G\), \(x-a\) is outside of \(A_n\)
** The order property
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    A nonempty stable associative monoid with left and right cancellation, or with left
    cancellation and right identity, is a group
    #+END_lemma

    #+BEGIN_proof
    Let \(a\) be in our monoid \(M\); if \(n<m\), the pair \((a^n,a^m)\) satisfies the
    formula \((Ez)xz=y\); this formula must therefore also be satisfied by at least one
    pair \((a^n,a^m)\) with \(n>m\), and we get an equation \(a^n=a^{n+p}b\). Let \(e=a^pb\) and
    let \(c\) be an arbitrary element of \(M\); then \(a^nc=a^nec\), so by cancellation \(c=ec\)
    and \(e\) is a left identity
    #+END_proof
