#+TITLE: Stability

#+AUTHOR: Qi'ao Chen
#+EXPORT_FILE_NAME: ../latex/Stability/Stability.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preface
    A combination of various notes from [[cite:&PillayNoteStability]] [[cite:&ChernNoteStability]]
    [[cite:&tent2012course]] [[cite:&DriesNoteStability]]

    A monster model \(\fC\)

    [[cite:&PillayNoteStability]] has many typos\emoji{😅}
* Preliminaries
** Indiscernibles
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(I\) be a linear order and \(\fA\) an \(L\)-structure. A family \((a_i)_{i\in I}\) of elements
    of \(A\) is called a *sequence of indiscernibles*  if for all \(L\)-formulas \(\varphi(x_1,\dots,x_n)\) and
    all \(i_1<\dots<i_n\) and \(j_1<\dots<j_n\) from \(I\)
    \begin{equation*}
    \fA\vDash\varphi(a_{i_1},\dots,a_{i_n})\leftrightarrow\varphi(a_{j_1},\dots,a_{j_n})
    \end{equation*}
    or
    \begin{equation*}
    \tp(a_{i_1},\dots,a_{i_n})=\tp(a_{j_1},\dots,a_{j_n})
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Compactness let us "stretch" indiscernibles. Let \((a_i:i\in\omega)\) be indiscernibles in \(\fC\),
    and \((I,<)\) an ordering. Then there exists an indiscernible \((b_i:i\in I)\) in \(\fC\)
    s.t. \(\forall i_1<\dots<i_n\in I\)
    \begin{equation*}
    \tp(a_1,\dots,a_n)=\tp(b_{i_1},\dots,b_{i_n})
    \end{equation*}
    #+END_theorem

    Indiscernible sequence are a fundamental tool of model theory, and there are many ways to obtain
    them.

    #+ATTR_LATEX: :options [Ramsey, extended]
    #+BEGIN_theorem
    Let \(n_1,\dots,n_r<\omega\). For each \(i=1,\dots,r\), let \(X_{i,1}\), \(X_{i,2}\) be a partition
    of \([\omega]^{n_i}\). Then there is an infinite subset \(Y\subseteq\omega\) which is homogeneous,
    i.e., \(\forall i=1,\dots,r\), either \([Y]^{n_i}\subseteq X_{i,1}\) or \([Y]^{n_i}\subseteq Y_{i,2}\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For each \(n\in\omega\), let \(\Sigma_n(x_1,\dots,x_n)\) be a collection of \(L\)-formulas in
    variables \(x_1,\dots,x_n\). Suppose that there are \(a_1,a_2,\dots\in\fC\) s.t.
    \begin{equation*}
    \vDash\Sigma_n(a_{i_1},\dots,a_{i_n}),\quad\forall i_1<\dots<i_n<\omega
    \end{equation*}
    Then there is an indiscernible \((b_i:i\in\omega)\) in \(\fC\) s.t.
    \begin{equation*}
    \vDash\Sigma_n(b_{i_1},\dots,b_{i_n}),\quad\forall i_1<\dots<i_n<\omega
    \end{equation*}
    #+END_proposition

    #+LATEX: \wu{
    we can expand \(\bigcup_{n\in\omega}\Sigma_n\) and obtain the Ehrenfeucht-Mostowski type \(\EM((a_i)_{i\in\omega})\).
    This is just the Standard Lemma in Tent
    #+LATEX: }

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Suppose \(\Sigma_2=\{x_1\neq x_2\}\). Then the proposition yields the existence of infinite indiscernible sequences
    #+END_examplle

    #+BEGIN_proof
    Consider
    \begin{align*}
    \Gamma(x_1,x_2,\dots)&=\{\varphi(x_{i_1},\dots,x_{i_n})\leftrightarrow\varphi(x_{j_1},\dots,x_{j_n}):\\
    &\quad i_1<\dots<i_n,j_1<\dots<j_n\in\omega,\varphi\in L\}\\
    &\cup\bigcup_n\Sigma(x_1,\dots,x_n)
    \end{align*}
    Let \(\Gamma'(x_1,\dots,x_n)\subseteq_f\Gamma\). Let \(\varphi_1,\dots,\varphi_r\) be the \(L\)-formulas appearing in \(\Gamma'\).
    For \(i=1,\dots,r\), let
    \begin{align*}
    &X_{i,1}=\{(j_1,\dots,j_n):j_1<\dots<j_n\in\omega,\vDash\varphi_i(a_{j_1},\dots,a_{j_n})\}\\
    &X_{i,2}=\{(j_1,\dots,j_n):j_1<\dots<j_n\in\omega,\vDash\neg\varphi_i(a_{j_1},\dots,a_{j_n})\}
    \end{align*}
    By Ramsey's theorem, there exists an infinite \(Y\subseteq\N\) s.t. \(\forall i=1,\dots,r\), \([Y]^{n_i}\) is either
    contained in \(X_{i,1}\) or in \(X_{i,2}\). Write \(Y=\{k_1<k_2<\dots\}\). Interpret each \(x_i\)
    as \(a_{k_i}\) to satisfy \(\Gamma'\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(M\prec N\prec\fC\) be models, and \(p(\barx)\in S_{\barx}(N)\). We say \(p\) is finitely satisfiable
    in \(M\), or \(p(\barx)\) is a *coheir* of \(p\uhr M\in S_{\barx}(M)\), if
    every \(\varphi(\barx)\in p(\barx)\) is satisfied by some \(\bara\in M\)
    #+END_definition

    #+BEGIN_remark
    \(p(\barx)\in S_n(N)\) is finitely satisfiable (f.s.) in \(M\) iff \(p(\barx)\) is in the
    topological closure of \(\{\tp(\bara/N):\bara\in M\}\subseteq S_n(N)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:P2.8
    Suppose \(p(\barx)\in S_{\barx}(M)\) and \(M\prec N\), then there is \(p'(\barx)\in S_{\barx}(N)\)
    s.t. \(p\subseteq p'\) and \(p'\) is f.s. in \(M\)
    #+END_lemma

    #+BEGIN_proof
    Consider \(\Gamma(\barx)=p(\barx)\cup\{\neg\varphi(\barx):\varphi(\barx)\in L_N\text{ and not realized in }M\}\). Let
    \(\Gamma\supseteq_f\Gamma'=\{\Psi(\barx),\neg\varphi_1(\barx),\dots,\neg\varphi_r(\barx)\}\in p\). Then any solution \(\bara\) of \(\Psi\) in \(M\)
    satisfies \(\Gamma'\) as \(M\vDash\forall\barx(\neg\varphi_i(\barx))\)
    #+END_proof

    #+BEGIN_remark
    Let \(i_M:M^{\barx}\to S_{\barx}(M)\) s.t. \(m\mapsto\tp(m/M)\). Define \(i_N:M^{\barx}\to S_{\barx}(N)\)
    similarly. Let \(r:S_{\barx}(N)\to S_{\barx}(M)\). Note that \(r\circ i_N=i_M\) and the set of types
    in \(S_{\barx}(N)\) that are f.s. in \(M\) is exactly the closure of \(i_N(M^{\barx})\)
    in \(S_{\barx}(N)\). Hence its image under \(r\) is closed. However the image must
    contain \(i_M(M^{\barx})\) which is dense in \(S_{\barx}(M)\). Therefore it must be onto, which
    proves the desired result

    #+LATEX: \wu{
    \(r\) is continuous and \(r(\bbar{i_N(M^n)})\supseteq i_M(M^n)\) is closed. \(\bbar{i_M(M^n)}=S_n(M)\).
    Then \(r\) is onto? Then its preimage of \(p\) is what we want <<Problem2>>
    #+LATEX: }
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(p(\barx)\in S_{\barx}(M)\), \(N\succ M\) be \(\abs{M}^+\)-saturated,
    and \(p'(\barx)\in S_{\barx}(N)\) a coheir of \(p\). Let \(\bara_1,\bara_2,\dots\in N\) be defined as
    follows
    \begin{align*}
    &\bara_1\text{ realises }p(\barx)\\
    &\bara_2\text{ realises }p'(\barx)\uhr(M,\bara_1)\\
    &\bara_3\text{ realises }p'(\barx)\uhr(M,\bara_1,\bara_2)\\
    &\cdots
    \end{align*}
    Then \((\bara_i:i\in\omega)\) is indiscernible over \(M\)
    #+END_proposition

    #+BEGIN_proof
    We prove by induction on \(k\) that for any \(n\le k\) and \(i_1<\cdots<i_n\le k\) and \(j_1<\cdots<j_n\le k\), we
    have
    \begin{equation*}
    \tp_M(\bara_{i_1},\dots,\bara_{i_n}/M)=\tp_M(\bara_{j_1},\dots,\bara_{j_n}/M)
    \end{equation*}
    Assume this is true for \(k\) and consider \(k+1\). Let \(i_1<\cdots<i_n\le k\), \(j_1<\cdots<j_n\le k\). We
    need to show that
    \begin{equation*}
    \tp_M(\bara_{i_1},\dots,\bara_{i_n},\bara_{k+1}/M)=\tp_M(\bara_{j_1},\dots,\bara_{j_n},\bara_{k+1}/M)
    \end{equation*}
    Consider a formula \(\varphi(\barx_1,\dots,\barx_n,\barx_{n+1})\in L_M\). Assume by contradiction that
    \begin{equation*}
    M\vDash\varphi(\bara_{i_1},\cdots,\bara_{i_{n}},\bara_{k+1})\wedge\neg\varphi(\bara_{j_1},\cdots,\bara_{j_{n}},\bara_{k+1})
    \end{equation*}
    But \(\tp(\bara_{k+1}/M,\bara_1,\dots,\bara_k)\) is f.s. in \(M\), so there is \(\bara'\in M\) s.t.
    \begin{equation*}
    M\vDash\varphi(\bara_{i_1},\cdots,\bara_{i_{n}},\bara')\wedge\neg\varphi(\bara_{j_1},\cdots,\bara_{j_{n}},\bara')
    \end{equation*}
    contradicting IH
    #+END_proof

** Definability and Generalizations
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\subseteq\fC^n\) is *definable almost over* \(A\) if there is an \(A\)-definable equivalence
    relation \(E\) on \(\fC^n\) with finitely many classes and \(X\) is a union of some \(E\)-classes
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:P2.11
    Let \(\D\) be a definable class and \(A\) a set of parameters. T.F.A.E.
    1. \(\D\) is definable over \(A\)
    2. \(\D\) is invariant under all automorphisms of \(\fC\) which fix \(A\) pointwise
    #+END_lemma

    \(S\subseteq K^{\alg}\Rightarrow M\setminus S\subseteq K^{\alg}\)

    #+BEGIN_proof
    \(\Rightarrow\) is easy as for any \(F\in\Aut(\fC/A)\) and \(\D=\varphi(\fC,\bara)\), \(\fC\vDash\varphi(\bars,\bara)\)
    iff \(\fC\vDash\varphi(F(\bars),\bara)\). [[https://math.stackexchange.com/questions/3361635/when-are-automorphism-invariant-subsets-definable][StackExchange]]

    \(x\in\D\Leftrightarrow\vDash\varphi(x,\bara)\Leftrightarrow\varphi(F(x),F(\bara))\leftrightarrow\varphi(F(x),\bara)\Leftrightarrow F(x)\in\D\)

    \(\Leftarrow\). Another proof from Chernikov. Assume that \(\D=\varphi(\fC,b)\) where \(b\in\fC\), and
    let \(p(y)=\tp(b/A)\)

    *Claim 1*. \(p(y)\vdash\forall x(\varphi(x,y)\leftrightarrow\varphi(x,b))\), which says that for any realisations \(b'\), \(\varphi(\fC,b)=\varphi(\fC,b')\)

    Indeed, let \(b'\vDash p(y)\) be arbitrary. Then \(\tp(b/A)=\tp(b'/A)\) so there is
    some \(\sigma\in\Aut(\fC/A)\) with \(\sigma(b)=b'\). Then \(\sigma(X)=\varphi(\fC,b')\) and by assumption \(\sigma(X)=X\),
    thus \(\varphi(\fC,b)=X=\varphi(\fC,b')\).

    There is some \(\psi(y)\in p\) (there is a finite subset of \(p(y)\) that does the job and we take
    the conjunction) s.t.
    \begin{equation*}
    \psi(y)\vDash\forall x(\varphi(x,y)\leftrightarrow\varphi(x,b))
    \end{equation*}
    Let \(\theta(x)\) be the formula \(\exists y(\psi(y)\wedge\varphi(x,y))\). Note that \(\theta(x)\) is an \(L(A)\)-formula,
    as \(\psi(y)\) is

    *Claim 2*. \(X=\theta(\fC)\)

    If \(a\in X\), then \(\vDash\varphi(a,b)\), and as \(\psi(y)\in\tp(b/A)\) we have \(\vDash\theta(a)\). Conversely,
    if \(\vDash\theta(a)\), let \(b'\) be s.t. \(\vDash\psi(b')\wedge\varphi(a,b')\). But by the choice of \psi this implies that \(\vDash\varphi(a,b)\)

    \(\Leftarrow\) Let \(\D\) be defined by \varphi, defined over \(B\supset A\). Consider the maps
    \begin{equation*}
    \fC\xrightarrow{\tau}S(B)\xrightarrow{\pi}S(A)
    \end{equation*}
    where \(\tau(c)=\tp(c/B)\) and \pi is the restriction map. Let \(Y\) be the image of \(\D\)
    in \(S(A)\). Since \(Y=\pi[\varphi]\). \(Y\) is closed.
    #+LATEX: \wu{
    Note that \(\tau(\D)=[\varphi]\). \(\tau(\D)=\{\tp(c/B):\fC\vDash\varphi(c)\}\subseteq[\varphi]\). For any \(q(x)\in[\varphi]\), as \(\fC\) is
    saturated, \(\fC\vDash q(d)\) and \(d\in\D\). Thus \(q\in\tau(\D)\). \pi is continuous
    #+LATEX: }


    Assume that \(\D\) is invariant under all automorphisms of \(\fC\) which fix \(A\) pointwise. Since
    elements which have the same type over \(A\) are conjugate by an automorphism of \(\fC\), this
    means that \(\D\)-membership depends only on the type over \(A\), i.e., \(\D=(\pi\tau)^{-1}(Y)\).
    #+LATEX: \wu{
    For any \(\tp(c/A)=\tp(d/A)\) and \(c\in\D\), as \(c\) and \(d\) are conjugate, \(d\in\D\).

    For any \(c\notin\D\), \(\pi\tau(c)\in Y\) iff \(\tp(c/A)\in\pi[\varphi]\) iff there is \(d\in\D\)
    s.t. \(\tp(c/A)=\tp(d/A)\) but then \(c\in\D\).
    #+LATEX: }

    This implies that \([\varphi]=\pi^{-1}(Y)\)
    #+LATEX: \wu{
    \(\tau(\D)=[\varphi]=\tau(\tau^{-1}\pi^{-1})(Y)=\pi^{-1}(Y)\)
    #+LATEX: }
    , or \(S(A)\setminus Y=\pi[\neg\varphi]\); hence \(S(A)\setminus Y\) is also closed and
    we conclude that \(Y\) is clopen. By Lemma ref:lemma4.2.3 \(Y=[\psi]\) for some \(L(A)\)-formula \psi.
    This \psi defines \(\D\).
    #+LATEX: \wu{
    For any \(d\in\fC\)
    \begin{equation*}
    \vDash\psi(d)\Leftrightarrow\tp(d/A)\Leftrightarrow d\in\D
    \end{equation*}
    #+LATEX: }
    #+END_proof


    A slight generalization of the previous lemma
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:P2.13
    Let \(X\subseteq\fC^n\) be definable. TFAE
    1. \(X\) is almost \(A\)-definable, i.e., there is an \(A\)-definable equivalence relation \(E\)
       on \(\fC^n\) with finitely many classes, s.t. \(X\) is a union of \(E\)-classes
    2. The set \(\{\sigma(X):\sigma\in\Aut(\fC/A)\}\) is finite
    3. The set \(\{\sigma(X):\sigma\in\Aut(\fC/A)\}\) is small
    #+END_lemma

    #+BEGIN_proof
    \(1\to 2\). Let \(\varphi(x_1,x_2)\in L(A)\) be the \(A\)-definable equivalence relation \(E\), and
    let \(b_1,\dots,b_n\in M\) be representatives in each equivalence class so that each class can be
    written as \([b_i]=\varphi(\fC,b_i)\). Given \(\sigma\in\Aut(\fC/A)\), since \(\varphi(x_1,x_2)\leftrightarrow\varphi(\sigma(x_1),\sigma(x_2))\), the image
    of each \([b_i]\) under \sigma will be
    \begin{equation*}
    \sigma([b_i])=\{\sigma(x):\varphi(x,b_i)\}=\{x':\varphi(x',\sigma(b_i))\}=\{x:\varphi(x,b_{j_i})\}=[b_{j_1}]
    \end{equation*}
    for some \(j_i\le n\). Now \(X\) is a disjoint union of some \([b_i]\)'s, so \(\sigma(X)\) is a disjoint
    union of some \([b_j]\)'s. Since there are only finitely many equivalence classes, there can
    only be finitely many possibilities for disjoint unions of these classes

    \(2\to 1\). Let \(X=\varphi(\fC,b)\) and \(p(y)=\tp(b/A)\). Given \(\sigma\in\Aut(\fC/A)\), we
    have \(\sigma(X)=\varphi(\fC,\sigma(b))\). Then from assumption, there must be distinct \(b_1,\dots,b_n\) s.t.
    \begin{equation*}
    \{\sigma(X):\sigma\in\Aut(\fC/A)\}=\{\varphi(\fC,b_i):i\le n\}
    \end{equation*}
    Now if \(\tp(b'/A)=\tp(b/A)\), then strong homogeneity yields some \(\sigma\in\Aut(\fC/A)\)
    s.t. \(\sigma(b)=b'\). Then the above argument again shows that \(\varphi(x,b')\) defines \(\sigma(X)\) for
    some \(\sigma\in\Aut(\fC/A)\). Thus \(\sigma(X)=\varphi(\fC,b')=\varphi(\fC,b_i)\) for some \(i\le k\). Therefore
    \(p(y)\vdash\bigvee_{i\le k}\forall x(\phi(x,y)\leftrightarrow\phi(x,b_i))\). By compactness there is
    some \(\psi(y)\in p\) s.t. \(\psi(y)\vdash\bigvee_{i\le k}\forall x(\phi(x,y)\leftrightarrow\phi(x,b_i))\). Now define \(E(x_1,x_2)\) as
    \begin{equation*}
    \forall y(\psi(y)\to(\phi(x_1,y)\leftrightarrow\phi(x_2,y)))
    \end{equation*}
    so it is \(A\)-definable. It is easy to check that \(E\) is an equivalence relation with
    finitely many classes, and that \(X\) is a union of \(E\)-classes (\(a_1Ea_2\) iff they agree on
    \(\phi(x,b_i)\) for all \(i\le k\), and so \(X=\phi(\fC,b_0)\) is given by the union of all possible
    combinations intersected with it)

    \(3\to 1\) Assume for contradiction that
    \begin{equation*}
    \abs{\{\sigma(X):\sigma\in\Aut(\fC/A)\}}=\lambda\ge\omega
    \end{equation*}
    we can find \lambda-many elements \((b_i:i<\lambda)\subset\fC\) to represent the distinct images under automorphisms.
    Then the set
    \begin{equation*}
    q(y)=p(y)\cup\{\neg\forall x(\varphi(x,y)\leftrightarrow\varphi(x,b_i)):i<\lambda\}
    \end{equation*}
    will be finitely satisfiable. Thus \(q(y)\) is realised by some \(b'\). But such \(b'\) has the
    same type as \(b\) over \(A\) and so strong homogeneity yields some \(\sigma\in\Aut(\fC/A)\)
    s.t. \(\sigma(b)=b'\). Applying such \sigma on \(X\) gives the image \(\varphi(\fC,b')=\varphi(\fC,b_i)\) for some \(i<\lambda\),
    a contradiction

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    We can identify definable sets with continuous functions in a certain settings
    1. Formulas \(\varphi(\barx),\psi(\barx)\in L_A\) are equivalent iff \([\varphi(\barx)]=[\psi(\barx)]\)
    2. The clopen subsets of \(S_{\barx}(A)\) are precisely the basic clopen sets
    3. [@3] Clopen subsets \(X\) of \(S_{\barx}(A)\) correspond exactly to continuous
       functions \(f:S_{\barx}(A)\to 2\) (with discrete topology) where \(f(p(\barx))=1\) if \(p(\barx)\in X\) and 0 otherwise
    4. The definable subsets of \(\fC^c\) are in one-to-one correspondence with continuous functions
       from \(S_{\barx}(A)\) to 2
    #+END_proposition

    #+BEGIN_proof
    3. [@3] If \(X\) is clopen, then \(f^{-1}(2)=S_{\barx}(A)\), \(f^{-1}(0)=\emptyset\), \(f^{-1}(\{1\})=X\), \(f^{-1}(\{0\})=X^c\)
    4. By 1, definable sets are in one-to-one correspondence with basic clopen subsets. By 2, basic
       clopen sets are exactly all of the clopen subsets, so definable sets are in one-to-one
       correspondence with clopen sets. By 3, clopen sets are in one-to-one correspondence with
       continuous functions \(f:S_{\barx}(A)\to 2\)
    #+END_proof


** Imaginaries and @@latex:\texorpdfstring{\(T^{\eq}\)}{Teq}@@

    A *multi-sorted* structure is a family of sets \((M_s)_{s\in S}\) equipped with relations
    \begin{equation*}
    R\subseteq M_{s_1}\times\cdots\times M_{s_m},\quad(s_1,\dots,s_m\in S)
    \end{equation*}
    A multi-sorted language \(L\) is a  triple \((S,L^r,L^f)\) and \(S\) are the sorts of \(L\)

    \(M_s\) is the underlying set of sort \(s\). Elements of \(M_s\) are also called "elements
    of \(\calm\)" of sort \(s\) Given any tuple \(\bars=(s_i)_{i\in I}\) of sorts in \(S\), we
    let \(M_{\bars}=\prod_{i\in I}M_{s_i}\)

    Given a variable \(x=(x_i)_{i\in I}\) of \(L\), with \(x_i\) of sorts \(s_i\) for \(i\in I\), we define
    the *\(x\)-set of* \(\calm\) to be the product set
    \begin{equation*}
    M_x:=M_{\bars}=\prod_iM_{s_i},\quad \bars=(s_i)_{i\in I}
    \end{equation*}
    \(x=(x_i)_{i\in I}\) and \(y=(y_j)_{j\in J}\) is *disjoint* if \(x_i\neq y_j\) for all \(i\in I\)
    and \(j\in J\), and in that case we put \(M_{x,y}=M_x\times M_y\). If in addition \(I=J\) and \(x_i\)
    and \(y_i\) have the same sort for \(i\in I\) (so that \(M_x=M_y\)), we call \(x\) and \(y\)
    *disjoint and similar*

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *definable closure* \(\dcl(A)\) of \(A\) is the set of elements \(c\) for which there is
    an \(L(A)\)-formula \(\varphi(x)\) s.t. \(c\) is the unique element satisfying \varphi. Elements or
    tuples \(a\) and \(b\) are said to be *interdefinable* if \(a\in\dcl(b)\) and \(b\in\dcl(a)\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume \(A\subseteq\fC\) and \(\barb\in\fC\)
    1. \(\barb\in\acl(A)\) iff \(\{f(\barb):f\in\Aut(\fC/A)\}\) is finite
    2. \(\barb\in\dcl(A)\) iff \(f(\barb)=\barb\) for all \(f\in\Aut(\fC/A)\)
    #+END_lemma

    #+BEGIN_proof
    1. Suppose \(\barb\in\acl(A)\) with witness \(\exists^{\le k}\varphi(\barx)\). Then \(\varphi(\fC)\) is \(A\)-definable
       and hence is \(\Aut(\fC/A)\)-invariant by Lemma ref:P2.11

       Suppose the finiteness. Since the composition of automorphisms is an automorphism, this set
       is \(\Aut(\fC/A)\)-invariant and therefore \(A\)-definable by some \(\varphi(\barx)\).

    2. \(\{\barb\}\) is \(\Aut(\fC/A)\)-invariant
    #+END_proof

    The first motivation to develop \(T^{\eq}\) is dealing with quotient objects, without leaving
    the context of first order logic. That is, if \(E\) is some definable equivalence relation on
    some definable set \(X\), we want to view \(X/E\) as a definable set

    We work in the setting of multi-sorted languages. Let \(L\) be a 1-sorted language and let \(T\)
    be a (complete) \(L\)-theory. We shall build a many-sorted
    language \(L^{\eq}\)-theory \(T^{\eq}\). We will ensure that in natural sense, \(L^{\eq}\)
    contains \(L\) and \(T^{\eq}\) contains \(T\)

    First we define \(L^{\eq}\). Consider the set \(L\)-formula \(\varphi(x,y)\), up to equivalence, such
    that \(T\) models that \varphi is an equivalence relation. For each \varphi, define \(s_\varphi\) to be a new sort
    in \(L^{\eq}\). Of particular importance is \(s_=\), the sort given by the formula "\(x=y\)".
    #+LATEX: \wu{
    = is an equivalence relation
    #+LATEX: }
    This sort \(s_=\) will yield, in each model of \(T^{\eq}\), a model of \(T\)

    Also define \(f_\varphi\) to be a function symbol with domain sort \(s^n_=\) (where \varphi has \(n\) free
    variables) and codomain sort \(s_\varphi\)

    For each \(m\)-place relation symbol \(R\in L\), make \(R^{\eq}\) an \(m\)-place relation symbol
    in \(L^{\eq}\) on \(s_=^m\). Likewise for all constant and function symbols in \(L\). Finally, for
    the sake of formality, we put a unique equality symbol \(=_\varphi\) on each sort

    #+BEGIN_remark
    Let \(N\) be an \(L^{\eq}\) structure. Then \(N\) has interpretations \(s_\varphi(N)\) of each
    sort \(s_\varphi\) and \(f_\varphi(N):s_=(N)^{n_{f_\varphi}}\to s_\varphi(N)\) of each function symbol \(f_\varphi\).
    Additionally, \(N\) will contain an \(L\)-structure consisting of \(s_=\) and interpretations of
    the symbols of \(L\) inside of \(s_=\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(T^{\eq}\) is the \(L^{\eq}\)-theory which is axiomatised by the following
    1. \(T\), where the quantifiers in the formulas of \(T\) now range over the sort \(s_=\)
    2. For each suitable \(L\)-formula \(\varphi(x,y)\), the axiom \(\forall_{s_=}\barx\forall_{s_=}\bary(\varphi(x,y)\leftrightarrow f_\varphi(\barx)=f_\varphi(\bary))\)
    3. For each \(L\)-formula \varphi, the axiom \(\forall_{s_\varphi}y\exists_{s_=}\barx(f_\varphi(\barx)=y)\)
    #+END_definition

    Axioms 2 and 3 simply state that \(f_\varphi\) is the quotient function for the equivalence relation
    given by \varphi

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(M\vDash T\). Then \(M^{\eq}\) is the \(L^{\eq}\) structure s.t. \(s_=(M^{\eq})=M\) and for each
    suitable \(L\)-formula \(\varphi(x,y)\) of \(n\) variables, the sort \(s_\varphi(M^{\eq})\) is equal
    to \(M^{n_{f_\varphi}}/E\) where \(E\) is the equivalence relation defined by \(\varphi(x,y)\) and \(f_\varphi(M^{\eq})(b)=b/E\)
    #+END_definition

    #+ATTR_LATEX: :options [Projective planes]
    #+BEGIN_examplle
    From Hodges.

    Suppose \(A\) is a three-dimensional vector space over a finite field, and let \(L\) be the
    first-order language of \(A\). Then we can write a formula \(\theta(x,y)\) of \(L\) which expresses
    'vectors \(x\) and \(y\) are non-zero and are linearly dependent on each other'. The formula
    \theta is an equivalence formula of \(A\), and the sort \(s_\theta\) is the set of points of the
    projective plane \(P\) associated with \(A\)
    #+END_examplle

    Now \(M^{\eq}\vDash T^{\eq}\). Moreover, passing from \(T\) to \(T^{\eq}\) is a canonical operation,
    in the following sense
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. For any \(N\vDash T^{\eq}\), there is an \(M\vDash T\) s.t. \(N\cong M^{\eq}\)
    2. Suppose \(M,N\vDash T\) are isomorphic, and let \(h:M\cong N\). Then \(h\) extends uniquely
       to \(h^{\eq}:M^{\eq}\cong N^{\eq}\)
    3. \(T^{\eq}\) is a complete \(L^{\eq}\)-theory
    4. Suppose \(M,N\vDash T\) and let \(\bara\in M\), \(\barb\in N\) with \(\tp_M(\bara)=\tp_N(\barb)\).
       Then \(\tp_{M^{\eq}}(\bara)=\tp_{N^{\eq}}(\barb)\)
    #+END_lemma

    #+BEGIN_proof
    1. Take \(M=s_=(N)\)
    2. Let \(h^{\eq}:M^{\eq}\to N^{\eq}\) be defined
       as \(h^{\eq}(f_\varphi(M^{\eq})(b))=f_\varphi(N^{\eq})(h(b))\) for each \(\varphi\in L\). This defines a function
       on \(M^{\eq}\), because \(f_\varphi(M^{\eq})\) is surjective by the \(T^{\eq}\) axioms.
       Moreover \(h^{\eq}\) is well-defined. Suppose \(f_\varphi(M^{\eq})(b)=f_\varphi(M^{\eq})(b')\),
       then \(\varphi(b,b')\) and hence \(\varphi(h(b),h(b'))\),
       therefore \(f_\varphi(N^{\eq})(h(b))=f_\varphi(N^{\eq})(h(b'))\). Injectivity is the same
       since \(\varphi(b,b')\leftrightarrow\varphi(h(b),h(b'))\).
       \begin{align*}
       f_\varphi(N^{\eq})(h(b))=f_\varphi(N^{\eq})(h(b'))&\Leftrightarrow h(b)/E_\varphi=h(b')/E_\varphi\\
       &\Leftrightarrow\varphi(h(b),h(b'))\\
       &\Leftrightarrow\varphi(b,b')\\
       &\Leftrightarrow f_\varphi(M^{\eq})(b)=f_\varphi(M^{\eq})(b')
       \end{align*}
    3. Let \(M,N\vDash T^{\eq}\), we want to show that they are elementary equivalent. Assume the
       generalized continuum hypothesis. By GCH, there are \(M',N'\vDash T^{\eq}\) which are \lambda saturated
       of size \lambda, for some large \lambda (strongly inaccessible), which \(M\preceq M'\) and \(N\preceq N'\). Since we
       want to show elementary equivalence, we can replace \(M,N\) with \(M'\) and \(N'\). By 1, we
       have \(M=M_0^{\eq}\), \(N=N_0^{\eq}\) for some \(M_0,N_0\vDash T\). Furthermore, \(M_0,N_0\)
       are \lambda-saturated of size \lambda. By assumption, \(T\) is complete, so \(M_0\equiv N_0\), and
       therefore \(M_0\cong N_0\). By 2, \(M\cong N\), and therefore \(M\equiv N\)

       We could simply prove that there is a back and forth system between \(M\) and \(N\), using
       such a system between \(M\supset M_0\vDash T\) and \(N\supset N_0\vDash T\)
       <<Problem13>>
       #+LATEX: \wu{
       \(M_0\equiv N_0\) iff \(M_0\sim_\omega N_0\). We want to show that \(M\sim_\omega N\). For any \(p\in\omega\),
       * given \(a\in s_=(M)\), choose according to \(M\)

       * given \(a\in s_\varphi(M)\), then there is \(\barb\barc\in s_=(M)\)
         s.t. \(f_\varphi(M^{\eq})(\barb\barc)=a\) and \(\varphi(\barb,\barc)\). If \(\barb\in s_=(M^{\eq})^n\),
         then there is a local isomorphism \(\barb\mapsto\bard\) as \(M\sim_\omega N\). Take \(b=\bard/E_\varphi\).
       #+LATEX: }
    4. Let \(M,N\vDash T\), they are elementary submodels of \(\fC\). Since \(\tp_M(\bara)=\tp_N(\barb)\), there
       exists an \(\sigma\in\Aut(\fC/A)\) with \(\sigma(\bara)=\barb\). By 2, this automorphism extends to \(\sigma^{\eq}:\fC^{\eq}\to\fC^{\eq}\)
       with \(\sigma^{\eq}(a)=b\), hence \(\tp_{M^{\eq}}(a)=\tp_{\fC^{\eq}}(a)=\tp_{\fC^{\eq}}(b)=\tp_{N^{\eq}}(b)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Consider the Strong space \(S_{(s_=)^n}(T^{\eq})\). The forgetful
    map \(\pi:S_{(s_=)^n}(T^{\eq})\to S_n(T)\) is a homeomorphism
    #+END_corollary

    #+BEGIN_proof
    Observe that it is continuous and surjective. By 4 of the previous lemma it is injective. Any
    continuous bijection from a compact space to a Hausdorff space is a homeomorphism
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:P2.28
    Let \(\varphi(x_1,\dots,x_k)\) be an \(L^{\eq}\) formula, where \(x_i\) is of sort \(S_{E_i}\). There is
    an \(L\)-formula \(\psi(\bary_1,\dots,\bary_k)\) s.t.
    \begin{equation*}
    T^{\eq}\vDash\forall \bary_1,\dots,\bary_k(\psi(\bary_1,\dots,\bary_k)\leftrightarrow\varphi(f_{E_1}(\bary_1),\dots,f_{E_k}(\bary_k)))
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    Let \(n\) be the length of \(\bary_1,\dots,\bary_k\). Consider the
    set \(\pi[\varphi(f_{E_1}(\bary_1),\dots,f_{E_k}(\bary_k))]\), it is a clopen subset of \(S_n(T)\) by the
    previous lemma, hence equal to \(\psi(\bary_1,\dots,\bary_k)\) for some formula \psi.

    #+LATEX: \wu{
    Guess the intuition is \([\varphi]=[\psi]\) iff \(\vDash\varphi\leftrightarrow\psi\).
    Consider \(\pi[\psi(\bary_1,\dots,\bary_k)]=\pi[\varphi(f_{E_1}(\bary_1),\dots,f_{E_k}(\bary_k))]\) and as \pi is
    homeomorphism, \([\psi(\bary_1,\dots,\bary_k)]=[\varphi(f_{E_1}(\bary_1),\dots,f_{E_k}(\bary_k))]\)
    #+LATEX: }
    #+END_proof

    #+LATEX: \wu{
    This proposition also shows that \(T^{\eq}\) is complete since \(f_{E_i}\) is surjective

    Also, for any \(\barc\in\fC\), \(\barc\in\dcl^{\eq}(\emptyset)\Leftrightarrow\barc\in\dcl(\emptyset)\) , \(\barc\in\acl^{\eq}(\emptyset)\Leftrightarrow\barc\in\acl(\emptyset)\)
    #+LATEX: }

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    1. Let \(M,N\vDash T\), and let \(h:M\to N\) be an elementary embedding.
       Then \(h^{\eq}:M^{\eq}\to N^{\eq}\) is also an elementary embedding
    2. \(\fC^{\eq}\) is also \kappa-saturated
    #+END_corollary

    #+BEGIN_proof
    1. \(h:M\to\im(h)\) is an isomorphism and can extend to \(h^{\eq}:M^{\eq}\to(\im(h))^{\eq}\),
       and \((\im(h))^{\eq}\subseteq N^{\eq}\)
    2. By Proposition ref:P2.28
    #+END_proof

    #+BEGIN_remark
    For \(M\vDash T\), a definable set \(X\subseteq M^n\) can be viewed as an element of \(M^{\eq}\).
    Suppose \(X\) is defined in \(M\) by \(\varphi(\barx,\bara)\) where \(\bara\in M\). Consider the
    equivalence relation \(E_\psi\) defined
    by \(\psi(\bary_1,\bary_2)=\forall\barx(\varphi(\barx,\bary_1)\leftrightarrow\varphi(\barx,\bary_2))\)
    #+LATEX: \wu{
    \(\bary_1\sim\bary_2\) iff this \(\varphi(M,\bary_1)=\varphi(M,\bary_2)\),
    #+LATEX: }
    and consider \(c=\bara/E_\psi=f_\psi(\bara)\in M^{\eq}\). Then \(X\) is defined in \(M^{\eq}\)
    by \(\chi(\barx,c)=\exists\bary(\varphi(\barx,\bary)\wedge f_\psi(\bary)=c)\). Moreover, if \(c'\in S_\psi(M^{\eq})\)
    and \(\forall\barx(\chi(\barx,c)\leftrightarrow\chi(\barx,c'))\), then \(c=c'\). To see this, let \(c'=f_{\psi}(\bara')\),
    and let \(X'\) be defined in \(M\) by \(\varphi(\barx,\bara')\). Then \(X'\) is defined in \(M^{\eq}\)
    by \(\chi(\barx,c')\), so we have that \(X=X'\) (in \(M^{\eq}\)). And then \(X=X'\) (in \(M\))
    so \(c=f_{\psi}(\bara)=f_{\psi'}(\bara')=c'\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    With the above considerations in mind, given \(M\vDash T\) and a definable set \(X\subseteq M^n\), we call
    such a \(c\in M^{\eq}\) a *code* for \(X\)
    #+END_definition

    #+BEGIN_remark
    Any automorphism of \(\fC^{\eq}\) fixes a definable set \(X\) set-wise iff it fixes a code
    for \(X\). However, the choice of a code for \(X\) will depend on the formula \varphi used to define
    it
    \begin{align*}
    \sigma(X)=X&\Leftrightarrow\sigma(X)=\{\sigma(x):\varphi(x,b)\}=\{x:\varphi(x,\sigma(b))\}=\{x:\varphi(x,b)\}=X\\
    &\Leftrightarrow\forall x(\varphi(x,b)\leftrightarrow\varphi(x,\sigma(b)))\\
    &\Leftrightarrow\psi(b,\sigma(b))\Leftrightarrow f_\psi(b)=f_\psi(\sigma(b))
    \end{align*}

    We can think of \(\fC^{\eq}\) as adjoining codes for all definable equivalence relations
    (as \(c/E'\) codes \(E'(x,c)\) for an arbitrary equivalence relation \(E\))
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(A\subseteq M\vDash T\). Then \(\acl^{\eq}(A)=\{c\in M^{\eq}:c\in\acl_{M^{\eq}}(A)\}\) and \(\dcl^{\eq}(A)\)
    is defined similarly
    #+END_definition

    #+BEGIN_remark
    Suppose \(A\subseteq M\prec N\), then \(\acl_{N^{\eq}}(A),\dcl_{N^{\eq}}(A)\subseteq M^{\eq}\), so this notation is unambiguous
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:P2.35
    Let \(M\vDash T\), a definable subset \(X\) of \(M^n\), and \(A\subseteq M\). Then \(X\) is
    almost \(A\)-definable iff \(X\) is definable in \(M^{\eq}\) by a formula with parameters in \(\acl^{\eq}(A)\)
    #+END_lemma

    #+BEGIN_proof
    We can work in \(\fC\), since \(M\prec\fC\). Let \(c\) be a code for \(X\). From ref:P2.13 \(X\) is
    almost \(A\)-definable iff \(\abs{\{\sigma(X):\sigma\in\Aut(\fC/A)\}}<\omega\) iff \(\abs{\{\sigma(c):\sigma\in\Aut(\fC^{\eq}/A)\}}<\omega\)
    (note that \sigma extends uniquely in \(\fC^{\eq}\)),
    that is, \(c\in\acl^{\eq}(A)\).

    \begin{align*}
    \sigma(b)/E=\sigma'(b)/E&\Leftrightarrow\forall x(\varphi(x,\sigma(b))\leftrightarrow\varphi(x,\sigma'(b)))\\
    &\Leftrightarrow\sigma(X)=\sigma'(X)
    \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\bara,\barb\in\fC\) have length \(n\). Let \(\bara,\barb\) have the same strong type
    over \(A\) (written as \(\stp_{\fC}(\bara/A)=\stp_{\fC}(\bara/A)\)) if \(E(\bara,\barb)\) for any
    finite equivalence relation (finitely many classes) defined over \(A\)
    #+END_definition

    #+BEGIN_remark
    If \(\varphi(\barx)\) is a formula over \(A\), then it defines an equivalence with two
    classes \(E(\barx_1,\barx_2)\) iff \((\varphi(\barx_1)\wedge\varphi(\barx_2))\vee(\neg\varphi(\barx_1)\wedge\neg\varphi(\barx_2))\). Hence strong
    types are a refinement of types

    Hence for any formula if \(\stp(\bara/A)=\stp(\barb/B)\), at least we have \(\varphi(\bara)\leftrightarrow\varphi(\barb)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(A=M\prec\fC\), then \(\tp_{\fC}(a/M)\vDash\stp_{\fC}(a/M)\)
    #+END_lemma

    #+LATEX: \wu{
    \(\tp_{\fC}(a/M)=\tp_{\fC}(b/M)\Rightarrow\stp_{\fC}(a/M)=\stp_{\fC}(b/M)\)
    #+LATEX: }

    #+BEGIN_proof
    Let \(E\) be an equivalence relation with finitely many classes, defined over \(M\),
    and \(\barb\) another realization of \(\tp_{\fC}(\bara/M)\), we want to show \(E(a,b)\).
    Since \(E\) has only finitely many classes, and \(M\) is a model, there are
    representants \(e_1,\dots,e_n\) of each \(E\)-class in \(M\). Hence we must have \(E(a,e_i)\) for
    some \(i\), and therefore \(E(b,e_i)\), which yields \(E(a,b)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A\subseteq M\vDash T\), and let \(\bara,\barb\in M\). TFAE
    1. \(\stp(\bara/A)=\stp(\barb/A)\)
    2. \(\bara,\barb\) satisfy the same formulas almost \(A\)-definable
    3. \(\tp_{\fC}(\bara/\acl^{\eq}(A))=\tp_{\fC}(\barb/\acl^{\eq}(A))\)
    #+END_lemma

    #+BEGIN_proof
    <<Problem3>>

    \(3\to 2\). ref:P2.35. Suppose \(X=\varphi(\fC,\bard)\) is almost \(A\)-definable,
    then \(\bara,\barb\in\varphi(\fC,\bard)\) iff \(\bara,\barb\in\theta(\fC):=\exists\bary(\varphi(\fC,\bary)\wedge\bary/E_\psi=\barc)\)
    where \(\barc=\bard/E_\psi\in\acl^{\eq}(A)\).

    \(2\to 3\)

    \(1\to 2\). Let \(X\) be almost definable over \(A\). We want to show that \(\bara\in X\)
    iff \(\barb\in X\).

    Since \(X\) is almost definable over \(A\), there is an \(A\)-definable equivalence
    relation \(E\) with finitely many classes, and \(\barc_1,\dots,\barc_n\) s.t. for all \(\barx\in M\),
    we have \(\barx\in X\) iff \(M\vDash E(\barx,\barc_1)\vee\cdots\vee E(\barx,\barc_n)\). Hence \(E(\bara,\barc_i)\)
    for some \(i\), so by assumption \(E(\barb,\barc_i)\).

    \(2\to 1\). Let \(E\) be an \(A\)-definable equivalence relation with finitely many classes, we
    want to show that \(E(\bara,\barb)\). The set \(X=\{\barx\in M:E(\barx,\bara)\}\) is definable
    almost over \(A\). But \(\bara\in X\), so \(\barb\in X\), hence \(E(\bara,\barb)\)
    #+END_proof


    Here is a note from [[https://math.berkeley.edu/~scanlon/225af13lectures/20131810Lec15.pdf][scanlon]]
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *imaginary element* of \(\fA\) is a class \(a/E\) where \(a\in A^n\) and \(E\) is a definable
    equivalence relation on \(A^n\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\fA\) *eliminates imaginaries* if, for every definable equivalence relation \(E\) on \(A^n\) there
    exists definable function \(f:A^n\to A^m\) s.t. for \(x,y\in A^n\) we have
    \begin{equation*}
    xEy\Leftrightarrow f(x)=f(y)
    \end{equation*}
    #+END_definition

    #+BEGIN_remark
    The definition give above is what Hodges calls *uniform elimination of imaginaries*
    #+END_remark

    #+BEGIN_remark
    If \(\fA\) eliminates imaginaries, then for any definable set \(X\) and definable equivalence
    relation \(E\) on \(X\), there is a definable set \(Y\) and a definable bijection \(f:X/E\to Y\).
    Of course this is not literally true, we should rather say that there is a definable
    map \(f':X\to Y\) s.t. \(f'\) is invariant on the equivalence classes defined by \(E\)
    #+END_remark

    So elimination of imaginaries is saying that quotients exists in the category of definable sets

    #+BEGIN_remark
    If \(\fA\) eliminates imaginaries then for any imaginaries element \(a/E=\tila\) there is some
    tuple \(\hata\in A^m\) s.t. \(\tila\) and \(\hata\) are *interdefinable*, i.e. there is a
    formula \(\varphi(x,y)\) s.t.
    * \(\fA\vDash\varphi(a,\tila)\)
    * If \(a'Ea\) then \(\fA\vDash\varphi(a',\hata)\)
    * If \(\varphi(b,\hata)\) then \(bEa\)
    * If \(\varphi(a,c)\) then \(c=\hata\)


    To get the formula \varphi we use the function \(f\) given by the definition of elimination of
    imaginaries and let \(\varphi(x,y):=f(x)=y\)
    #+END_remark

    Almost conversely, if for every \(\fA'\equiv\fA\) every imaginary in \(\fA'\) is interdefinable with a *real*
    (non-imaginary) tuple then \(\fA\) eliminates imaginaries
    \begin{equation*}
    \{\forall xy(xEy\leftrightarrow f_E(x)=f_E(y))\mid \forall E\}
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    For any structure \(\fA\), every imaginary in \(\fA_A\) is interdefinable with a sequence of real elements
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(\fA=(\N,<,\equiv\mod 2)\). Then \(\fA\) eliminates imaginaries. For example, to eliminate the
    "odd/even" equivalence relation, \(E\), we can define \(f:\N\to\N\) by
    \begin{equation*}
    f(x)=y\Leftrightarrow xEy\wedge\forall z[xEz\to y<z\vee y=z]
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\fA\) has *definable choice functions* if for any formula \(\theta(\barx,\bary)\) there is a definable
    function \(f(\bary)\) s.t.
    \begin{equation*}
    \forall\bary\exists\barx[\theta(\barx,\bary)\leftrightarrow\theta(f(\bary),\bary)]
    \end{equation*}
    (i.e., \(f\) is a skolem function for \theta) and s.t.
    \begin{equation*}
    \forall\bary\forall\barz[\forall\barx(\theta(\barx,\bary)\leftrightarrow\theta(\barx,\barz))\to f(\bary)=f(\barz)]
    \end{equation*}
    #+END_definition

    #+BEGIN_proof
    If \(\fA\) has definable choice functions then \(\fA\) eliminates imaginaries
    #+END_proof

    #+BEGIN_proof
    Given a definable equivalence relation \(E\) on \(A^n\) let \(f\) be a definable choice function
    for \(E(\barx,\bary)\). Since \(E\) is an equivalence relation we have \(\forall\bary E(f(\bary),\bary)\) and
    \begin{equation*}
    \forall\bary\barz[\bary/E=\barz/E\to f(\bary)=f(\barz)]
    \end{equation*}
    Thus \(f(\bary)=f(\barz)\Leftrightarrow\bary E\barz\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    We now see that \(\fA=(\N,<,\equiv\mod 2)\)  eliminates imaginaries. Basically since \(\fA\) is well
    ordered, we can find a least element to witness membership of definable sets, hence we have
    definable functions
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\fA=(\N,\equiv\mod 2)\) does not eliminate imaginaries

    First note that the only definable subsets of \(\N\) are \(\emptyset,\N,2\N,(2n+1)\N\). This is
    because \(\fA\) has an automorphisms which switches \((2n+1)\N\) and \(2\N\)

    Now suppose \(f:\N\to\N^m\)  eliminates the equivalence relation \(\equiv\mod 2\), i.e.,
    \begin{equation*}
    f(x)=f(y)\Leftrightarrow y\equiv 2\mod 2
    \end{equation*}
    The \(\im(f)\) is definable and has cardinality \(2\). Since there are no definable subsets
    of \(\N\) of cardinality 2, we must have \(m>1\). Now let \(\pi:\N^m\to\N\) be a projection.
    Then \(\pi(\im(f))\) is a finite nonempty definable subset of \(\N\). But no such set exists
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(\fA\) eliminates imaginaries, then \(\fA_A\) eliminates imaginaries
    #+END_proposition

    #+BEGIN_proof
    The idea is that an equivalence relation with parameters can be obtained as a fiber of an
    equivalence relation in more variables. Let \(E\subseteq A^n\) be an equivalence relation definable
    in \(\fA_A\). Let \(\varphi(x,y;z)\in L\) and \(a\in A^l\) be s.t.
    \begin{equation*}
    xEy\Leftrightarrow\fA\vDash\varphi(x,y;a)
    \end{equation*}
    We now define
    \begin{equation*}
    \psi(x,u,y,v)=
    \begin{cases}
    u=v\wedge"\varphi\text{ defines an equivalence relation}"&\text{or}\\
    u\neq v&\text{or}\\
    "\varphi(x,y,v)\text{ does not define an equivalence relation}"
    \end{cases}
    \end{equation*}
    Now \psi defines an equivalence relation on \(A^{n+l}\). Let \(f:A^{n+l}\to A^m\) eliminate \psi,
    then \(f(-,a)\) eliminates \(E\)
    #+END_proof

    Back to [[cite:&PillayNoteStability]]

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. \(T\) has elimination of imaginaries (EI) if for any model \(M\vDash T\) and \(e\in M^{\eq}\), there
       is a \(\barc\in M\) s.t. \(e\in\dcl_{M^{\eq}}(\barc)\) and \(\barc\in\dcl_{M^{\eq}}(e)\)
    2. \(T\) has weak elimination of imaginaries if, as above, except \(\barc\in\acl_{M^{\eq}}(e)\)
       (that is, \(e\in\dcl_{M^{\eq}}(\barc)\) and \(\barc\in\acl_{M^{\eq}}(e)\))
    3. \(T\) has geometric elimination of imaginaries if, as above,
       except \(e\in\acl_{M^{\eq}(\barc)}\) and \(\barc\in\acl_{M^{\eq}}(e)\)
    #+END_definition

    Note that in particular, elimination of imaginaries imply the existence of codes for definable sets

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:P2.41
    TFAE
    1. \(T\) has EI
    2. For some model \(M\vDash T\), we have that for any \(\emptyset\)-definable equivalence relation \(E\),
       there is a partition of \(M^n\) into \(\emptyset\)-definable sets \(Y_1,\dots,Y_r\) and for each \(i=1,\dots,r\)
       a \(\emptyset\)-definable \(f_i:Y_i\to M^{k_i}\) where \(k_i\ge 1\) s.t. for each \(i=1,\dots,r\), for
       all \(\barb_1,\barb_2\in Y_i\), we have \(E(\barb_1,\barb_2)\) iff \(f_i(\barb_1)=f_i(\barb_2)\)
    3. For any model \(M\vDash T\), we have that for any \(\emptyset\)-definable equivalence relation \(E\),
       there is a partition of \(M^n\) into \(\emptyset\)-definable sets \(Y_1,\dots,Y_r\) and for each \(i=1,\dots,r\)
       a \(\emptyset\)-definable \(f_i:Y_i\to M^{k_i}\) where \(k_i\ge 1\) s.t. for each \(i=1,\dots,r\), for
       all \(\barb_1,\barb_2\in Y_i\), we have \(E(\barb_1,\barb_2)\) iff \(f_i(\barb_1)=f_i(\barb_2)\)
    4. For any model \(M\vDash T\), and any definable \(X\subseteq M^n\) there is
       an \(L\)-formula \(\varphi(\barx,\bary)\) and \(\barb\in M\) s.t. \(X\) is defined by \(\varphi(\barx,\barb)\)
       and for all \(\barb'\in M\) if \(X\) is defined by \(\varphi(\barx,\barb')\) then \(\barb=\barb'\).
       We call such a \(\barb\) a code for \(X\).
    #+END_proposition

    #+LATEX: \wu{
    most typos i've ever seen in a proof
    #+LATEX: }

    #+BEGIN_proof
    \(2\Leftrightarrow 3\). Since we concern only \(\emptyset\)-definable relations and functions, if it is true in some
    model, then it is true in any model

    \(1\to 2\). Let \(\pi_E:S_=^n\to S_E\) the canonical definable quotient map. Let \(e\in S_E\). By
    assumption, there is \(k\in\N\) and \(\barc\in\fC^k\) s.t. \(e\) and \(\barc\) are interdefinable. In
    other words, there is a formula \(\varphi_e(x,\bary)\) over \(\emptyset\) s.t. \(\varphi_e(e,\barc)\).
    Moreover, \(\abs{\varphi_e(\fC,\barc)}=\abs{\varphi_e(e,\fC)}=1\)

    Let
    \begin{align*}
    X_e=\{&\barx\in\fC,\vDash\exists!\bary\varphi_e(\pi_E(\barx),\bary)\\&\wedge\forall z(E(\barx,\barz)\leftrightarrow\\&\quad(\forall y(\varphi_e(\pi_E(\barx),\bary)\leftrightarrow\varphi_e(\pi_E(\barz),\bary)))\}
    \end{align*}
    This means that \(\varphi_e\) defines a function on \(X_e\), and that this function
    separates \(E\)-classes.

    Then \(\pi^{-1}(\{e\})\subset X_e\).

    Since each \(X_e\) contains \(\pi^{-1}(\{e\})\), we get \(\fC^n=\bigcup_{e\in\pi_E(\fC^n)}X_e\), and by compactness,
    there are \(e_1,\dots,e_l\) s.t. \(\fC^n=\bigcup_{i=1}^lX_{e_i}\).
    #+LATEX: \wu{
    As each \(X_e\) is \(\emptyset\)-definable. Let \(\barx\in X_e\Leftrightarrow\theta_e(\barx)\). Suppose there is no such \(l\),
    then \(\{x=x\}\cup\{\neg\theta_e(x)\}\) is satisfiable and realised since \(\fC\) is saturated
    #+LATEX: }
    Naively, we can pick \(f_i=\varphi_{e_i}\circ\pi_E\), but \(X_{e_i}\) are not disjoint

    However we can consider \(Y_1,\dots,Y_r\) to be the atoms of the boolean algebra generated by the \(X_i\).
    These are disjoint, and we can pick, for each \(Y_j\), appropriate \(f_i\), to get the result

    \(3\to 4\). Let \(X=\varphi(\fC,\bara)\). Consider the \(\emptyset\)-definable equivalence
    relation \(E(\bary,\barz)\Leftrightarrow\forall x(\varphi(\barx,\bary)\leftrightarrow\varphi(\barx,\barz))\). Let \(Y_i\) and \(f_i\) be as in 3
    and say \(\bara\in Y_1\), and let \(\barb=f_1(\bara)\).
    Then \(\exists\bary(f_1(\bary)=\barb\wedge\varphi(\barx,\bary))\) defines \(X\), call this formula \(\psi\)

    We have to show that \(\barb\) is unique. Let \(\barb'\) be
    s.t. \(\exists\bary(f_1(\bary)=\barb'\wedge\varphi(\barx,\bary))\) also defines \(X\), and let \(\bara_0\) be as
    the \(\bary\) in the formula. Then \(\varphi(x,\bara_0)\) defines \(X\), hence \(\bara_0E\bara\),
    which implies \(\barb'=f_1(\bara_0)=f_1(\bara)=\barb\)

    \(4\to 1\). Let \(e\in \fC^{\eq}\), then \(e=\pi_E(\bara)\) for some \(\bara\in \fC^n\) and
    some \(\emptyset\)-definable equivalence relation \(E\)

    The set \(X=\{\barx\in\fC^n\mid\vDash E(\barx,\bara)\}\) has a code \(\barb\in\fC^k\), so
    that \(X=\psi(\fC^n,\barb)\). We are going to prove interdefinability of \(e\) and \(\barb\) using
    automorphisms of \(\fC\)

    First suppose that \(\sigma\in\Aut(\fC)\), and fixes \(e\). We
    have \(\fC^{\eq}\vDash\forall\barx(\pi_E(\barx)=\pi_E(\bara)\leftrightarrow\psi(\barx,\barb))\). Applying \sigma, we
    get \(\fC^{\eq}\vDash\forall\barx(\pi_E(\barx)=\pi_E(\bara)\leftrightarrow\psi(\barx,\sigma(\barb)))\). But \(\barb\) is a code
    for \(X\), hence \(\barb=\sigma(\barb)\). This implies \(\barb\in\dcl(e)\)

    Now suppose \(\sigma\in\Aut(\fC)\) and fixes \(\barb\).
    Again \(\fC^{\eq}\vDash\forall\barx(\pi_E(\barx)=\pi_E(\bara)\leftrightarrow\psi(\barx,\barb))\)
    and \(\fC^{\eq}\vDash\forall\barx(\pi_E(\barx)=\pi_E(\sigma(\bara))\leftrightarrow\psi(\barx,\barb))\).
    But \(\psi(\bara,\barb)\), \(e=\pi_E(\bara)=\pi_E(\sigma(\bara))=\sigma(e)\). Hence \(e\in\dcl(\barb)\)

    #+END_proof

    Note that condition 2 is somewhat unsatisfying, as we would like to have a quotient function
    for \(E\), that is, \(r=1\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Suppose \(T\) eliminates imaginaries. We get \(r=1\) in condition 2 iff \(\dcl(\emptyset)\) has at least
    two elements
    #+END_proposition

    #+BEGIN_proof
    First, suppose that \(r=1\). Consider the equivalence on \(\fC^2\) given by \(E((x,y),(x',y'))\)
    iff \(x=y\leftrightarrow x'=y'\). In other words, the \(E\) classes are the diagonal and its complement (only
    two). Then \(\pi_E(\fC^2)\) has two elements, and they belong to \(\dcl^{\eq}(\emptyset)\). But because \(T\)
    eliminates imaginaries, this implies that there is also two elements in \(\dcl(\emptyset)\) by
    Proposition ref:P2.28

    Second, suppose that \(\dcl(\emptyset)\) contains two constants \(a\) and \(b\). Let \(Y_i,f_i\) be as in
    condition 2. Using \(a\) and \(b\),we can find some number \(k\) and functions \(g_i:\fC^{k_i}\to\fC^k\)
    s.t. \(g_i(\fC^{k_i})\) are pairwise disjoint. We can check that the \(\emptyset\)-definable
    function \(f:\fC^n\to\fC^k\) sending \(y\in Y_i\) to \(g_i(f_i(y))\) has all the required properties

    #+END_proof

    #+BEGIN_remark
    Elimination of imaginaries also makes sense for many sorted theories
    #+END_remark

    #+ATTR_LATEX: :options [Assume \(T\) 1-sorted]
    #+BEGIN_proposition
    \(T^{\eq}\) has elimination of imaginaries
    #+END_proposition

    #+BEGIN_proof
    Prove a strong version of 2 in Proposition ref:P2.41
    #+LATEX: \wu{
    that is, we don't need to distinguish \(Y_1,\dots,Y_r\) and \(f_1,\dots,f_r\).
    #+LATEX: }
    Let \(E'\) be a \(\emptyset\)-definable
    equivalence relation on a sort \(s_E\) in some model \(M^{\eq}\) of \(T^{\eq}\). By Proposition
    ref:P2.28 there is an \(L\)-formula \(\psi(\bary_1,\bary_2)\) (\(\bary_i\) the appropriate length)
    s.t. for all \(\bara_1,\bara_2\in M\), \(M\vDash\psi(\bara_1,\bara_2)\)
    iff \(M^{\eq}\vDash E'(f_E(\bara_1),f_E(\bara_2))\). So \(\psi(\bary_1,\bary_2)\) is an \(L\)-formula
    defining an equivalence relation on \(M^k\) for the suitable length \(k\). Consider the
    map \(h\), taking \(e\in S_E\) to \(f_\psi(\bara)\) for any \(\bara\in M^k\) s.t. \(f_E(\bara)=e\) for
    any \(\bara\in M^k\) s.t. \(f_E(\bara)=e\). Suppose \(f_E(\bara)=e=f_E(\bara')\), we easily see
    that \(f_\psi(\bara)=f_\psi(\bara')\), hence the map \(h\) is well-defined, and satisfies 2 of ref:P2.41
    #+END_proof

** Examples and counterexamples
    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The theory of an infinite set has weak elimination of imaginaries but not full elimination of imaginaries
    #+END_examplle

    #+BEGIN_proof
    <<Problem4>>
    First, we show that \(T\) has weak elimination of imaginaries. Let \(M\) be an infinite set and
    let \(e\in M^{\eq}\) be an imaginary element. Suppose that. Let \(A\subset M\) be a finite set over
    which \(X\) is definable ??. Consider the set
    \begin{equation*}
    \hatA:=\bigcap_{\substack{\sigma\in\Aut(M)\\\sigma(X)=X}}\sigma(A)
    \end{equation*}
    Since \(A\) is finite, there are \(\sigma_1,\dots,\sigma_n\) s.t. \(\hatA=\bigcap_i\sigma_i(A)\)

    To see that \(T\) does not have full elimination of imaginaries, observe that there is never a
    code for any finite set. Indeed, if \(M\) is an infinite set, \(X\subset_fM\), and \(\bara\in M\), we
    can find a permutation of \(M\) which fixes \(X\) as a set but does not fix \(\bara\),
    meaning \(\bara\) could not be a code for \(X\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(T=\Th(M,<,\dots)\) where < is a total well-ordering. Then \(T\) has elimination of imaginaries
    #+END_examplle

    #+BEGIN_proof
    Every definable set has a least element. We verify (2) in ref:P2.41. Let \(E\) be
    a \(\emptyset\)-definable equivalence relation on \(M^n\). Let \(f:M^n\to M^n\) s.t. for
    any \(\bara\), \(f(\bara)\) is the least element of the \(E\)-class of \(\bara\). Notice
    that \(f\) is \(\emptyset\)-definable, and for all \(\bara,\barb\), \(f(\bara)=f(\barb)\)
    iff \(E(\bara,\barb)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:P2.49
    Let \(T\) be strongly minimal and \(\acl(\emptyset)\) be infinite (in some, any model). Then \(T\) has
    weak elimination of imaginaries
    #+END_lemma

    #+BEGIN_proof
    Fix a model \(M\). Let \(e\in M^{\eq}\)
    #+LATEX: \wu{
    Ok, now i think the convention for pillay is that \(e\in M^{\eq}\) is automatically imaginary,
    #+LATEX: }
    so \(e=\bara/E\) for some \(\bara\) and \(E\) some \(\emptyset\)-definable equivalence relation.
    Let \(A=\acl_{M^{\eq}}(e)\cap M\). \(A\) is infinite as it contains \(\acl(\emptyset)\). \(A\) is infinite
    as it contains \(\acl(\emptyset)\).

    We first prove that there exists some \(\barb\subset A\) s.t. \(E(\bara,\barb)\).
    Let \(X_1=\{y_1\in M:M\vDash\exists y_2\dots y_n(\bary E\bara)\}\). It is definable over \(e\). If \(X_1\) is finite,
    any \(b_1\in X_1\) then belongs to \(A\). Otherwise, \(X_1\) is cofinite, hence meets the infinite
    set \(A\). Either way, \(X_1\cap A\neq\emptyset\) and we have \(b_1\in X_1\cap A\)

    Now let \(X_2=\{y_2\in M:M\vDash\exists y_3\dots y_n(b_1\bary E\bara)\}\). We remark \(X_2\neq\emptyset\) since \(b_1\in X_1\).
    Now \(X_2\) is either finite or cofinite since \(T\) is strongly minimal. By the same argument
    above, we may find \(b_2\in X_2\cap A\). Then repeating this process, we may find \(\barb\subset A\).
    Therefore \(\barb\in\acl_{M^{\eq}}(e)\).

    Finally notice that \(e\in\dcl_{M^{\eq}}(\barb)\) since \(\bara/E=\barb/E=e\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The theory \(\ACF_p\) has elimination of imaginaries, for any \(p\)
    #+END_examplle

    #+BEGIN_proof
    By Lemma ref:P2.49, \(\ACF_p\) has weak elimination of imaginaries. Therefore it suffices to
    show that every finite set can be coded. Let \(K\) be an algebraically closed field and
    let \(X=\{c_1,\dots,c_n\}\subseteq K\). Consider the polynomial
    \begin{align*}
    P(x)&=\prod_{i=1}^n(x-c_i)\\
    &=x^n+e_{n-1}x^{n-1}+\dots+e_1x+e_0
    \end{align*}
    Then we may take the tuple \(\bare=(e_n,\dots,e_0)\) to be our code for \(X\).
    #+END_proof

* Stability
** Historic remarks and motivations
    Thoughout this chapter we will fix a complete theory \(T\) in some language \(L\). Moreover, we
    will have no problem in working in \(T^{\eq}\) (that is to say, to assume \(T=T^{\eq}\))

    For a given theory \(T\), the spectrum functions is given as
    \begin{gather*}
    I(T,-):Card\to Card\\
    I(T,\lambda)=\#\text{ of models of \(T\) or cardinality $\lambda$ (up to isomorphism)}
    \end{gather*}
    #+ATTR_LATEX: :options [Morley]
    #+BEGIN_conjecture
    Let \(T\) be countable, then function \(I_T(\kappa)\) is non-decreasing on uncountable cardinals
    #+END_conjecture

    One of such dividing lines is stability
** Counting types and stability
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For a complete first order theory \(T\), let \(f_T:Card\to Card\) be defined
    by \(f_T(\kappa)=\sup\{\abs{S_1(M)}:M\vDash T,\abs{M}=\kappa\}\), for \kappa an infinite cardinal
    #+END_definition

    #+BEGIN_exercise
    Show that
    \begin{equation*}
    f_T(\kappa)=\sup\{\abs{S_n(M)}:M\vDash T,\abs{M}=\kappa,n\in\omega\}
    \end{equation*}
    gives an equivalent definition
    #+END_exercise

    It is easy to see that \(\kappa\le f_T(\kappa)\le 2^{\kappa+\abs{T}}\)

    #+ATTR_LATEX: :options [Keisler, Shelah \cite{keisler1976six}]
    #+BEGIN_fact
    Let \(T\) be an arbitrary complete theory in a countable language. Then \(f_T(\kappa)\) is one of the
    following functions (and all of these options occur for some \(T\)):
    \begin{equation*}
    \kappa,\kappa+2^{\aleph_0},\kappa^{\aleph_0},\ded\kappa,(\ded\kappa)^{\aleph_0},2^\kappa
    \end{equation*}
    Here, \(\ded\kappa=\sup\{\abs{I}:I\text{ is a linear order with a dense subset of size }\kappa\}\),
    equivalently \(\sup\{\lambda:\text{ there is a linear order of size $\kappa$ with $\lambda$ cuts}\}\)
    #+END_fact

    \(\ded\) is called the *Dedekind function*

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\kappa<\ded\kappa\le 2^\kappa\)
    #+END_lemma

    #+BEGIN_proof
        Let \mu be minimal s.t. \(2^\mu>\kappa\), and consider the tree \(2^{<\mu}\). Take the lexicographic
        ordering \(I\) on it, then \(\abs{I}\le\kappa\) by the minimality of \mu, but there are at
        least \(2^\mu>\kappa\) cuts

        Every cut is *uniquely* determined by the subset of elements in its lower half
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(M\vDash T\)
    1. A formula \(\phi(x,y)\) with its variables partitioned into two groups \(x,y\), has the
       *\(k\)-order property*, \(k\in\omega\), if there are some \(a_i\in M_x\), \(b_i\in M_y\) for \(i<k\)
       s.t. \(M\vDash\phi(a_i,b_j)\Leftrightarrow i<j\)
    2. \(\phi(x,y)\) has the *order property* if it has the \(k\)-order property for all \(k\in\omega\)
    3. A formula \(\phi(x,y)\) is *stable* if there is some \(k\in\omega\) s.t. it does not have the \(k\)-order property
    4. A theory is *stable* if it implies that all formulas are stable
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:C2.2.8
    Assume that \(T\) is unstable, then \(f_T(\kappa)\ge\ded\kappa\) for all cardinals \(\kappa\ge\abs{T}\)
    #+END_proposition

    #+BEGIN_proof
    Fix a cardinal \kappa. Let \(\phi(x,y)\in L\) be a formula that has the \(k\)-order property for
    all \(k\in\omega\). Then by compactness we have:

    *Cliam*. Let \(I\) be an arbitrary linear order. Then we can find some \(\calm\vDash T\) and \(a_ib_i:i\in I\)
     from \(M\) s.t. \(\calm\vDash\phi(a_i,b_j)\Leftrightarrow i<j\), for all \(i,j\in I\)

     #+LATEX: \wu{
     Consider
     \begin{equation*}
    T'=T\cup\{\phi(a_i,b_j):i<j\}\cup\{\neg\phi(a_i,b_j):i\\ge j\}
     \end{equation*}
     #+LATEX: }

     Let \(I\) be an arbitrary dense linear order of size \kappa, and let \((a_ib_i:i\in I)\) in \(\calm\) be as
     given by the claim. By Löwenheim–Skolem Theorem, we can assume that \(\abs{\calm}=\kappa\)

     Given a cut \(C=(A,B)\) in \(I\), consider the set of \(L(M)\)-formulas
     \begin{equation*}
    \Phi_C=\{\phi(x,b_j):j\in B\}\cup\{\neg\phi(x,b_j):j\in A\}
     \end{equation*}
     Note that by compactness it is a partial type, let \(p_C\in S_x(M)\) be a complete type over \(M\)
     extending \(\Phi_C(x)\). Given two cuts \(C_1,C_2\), we have \(p_{C_1}\neq p_{C_2}\). As \(I\) was
     arbitrary, this shows that \(\sup\{\abs{S_x(M)}:M\vDash T,\abs{M}=\kappa\}\ge\ded\kappa\). Note that we may
     have \(\abs{x}>1\), however using Exercise ref:C2.2.2 we get \(f_T(\kappa)\ge\ded\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options [Ramsey]
    #+BEGIN_fact
    \(\aleph_0\to(\aleph_0)^n_k\) holds for all \(n,k\in\omega\) (i.e., for any coloring of subsets of \(\N\) of size
    \(n\) in \(k\) colors, there is some infinite subset \(I\) of \(\N\) s.t. all \(n\)-element
    subsets of \(I\) have the same color)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\phi(x,y)\), \(\psi(x,z)\) be stable formulas (where \(y,z\) are not necessarily disjoint tuples
    of variables). Then
    1. \(\neg\phi(x,y)\) is stable
    2. Let \(\phi^*(y,x):=\phi(x,y)\), i.e., we switch the roles of the variables. Then \(\phi^*(y,x)\) is
       stable
    3. \(\theta(x,yz):=\phi(x,y)\wedge\psi(x,z)\) and \(\theta'(x,yz):=\phi(x,y)\vee\psi(x,z)\) are stable
    4. If \(y=uv\) and \(c\in M_v\), then \(\theta(x,u):=\phi(x,uc)\) is stable
    5. If \(T\) is stable, then every \(L^{\eq}\)-formula is stable as well
    6. The formula \(\varphi(x,y)\) is stable for \(T\) iff there is \(n<\omega\) s.t. \(\varphi(x,y)\)
       is \(n\)-stable: it is not the case that there are \(a_i,b_i\) (in \(\fC\), or in
       some/any \(M\vDash T\)), \(i< n\), s.t. \(\vDash\varphi(a_i,b_i)\) iff \(i< j\) for all \(i,j< n\)
    7. There are \(T\), \(M\vDash T\) and \(\varphi(x,y)\) s.t. \(\varphi(x,y)\) is stable in \(M\) but it is not
       stable for \(T\)
    #+END_lemma

    #+BEGIN_proof
    1. Suppose \(\neg\phi(x,y)\) is unstable, then there is \(I=(a_i,b_i)_{i\in\omega}\)
       s.t. \(\vDash\neg\varphi(a_i,b_i)\Leftrightarrow i<j\), equivalently, \(\vDash\varphi(a_i,b_i)\Leftrightarrow i\ge j\).
       Then add constants \((a_i,b_i)_{i\in\omega}\) and consider
       \begin{equation*}
       \Gamma=T\cup\{\varphi(a_i,b_i):i<j\}\cup\{\neg\varphi(a_i,b_i):i\ge j\}
       \end{equation*}
       For any finite subset \(\Gamma'\subset_f\Gamma\), we can reverse the order of \(I\): suppose \(n\) is the
       maximum index and then let \(i'=n-i\), \(j'=n+1-j\). Then \(i'<j'\Leftrightarrow n-i<n+1-j\Leftrightarrow i\ge j\).
       Hence \(I\) satisfies this, and hence \(\varphi(x,y)\) is unstable
    2. Suppose \(\varphi^*(y,x)\) is not stable, then \(\neg\varphi^*(y,x)\) is also unstable. Let \(a_i,b_i\) be
       witnesses in \(\fC\) of the latter. Then \(a'_i=b_i\) and \(b_i'=a_{i+1}\), \(i<\omega\), witness the
       instability of \(\varphi(x,y)\) as \(j+1>i\)
    3. Suppose that \(\theta'(x,yz)\) is unstable, i.e., there are \((a_i,b_ib_i':i\in\N)\)
      s.t. \(\vDash\phi(a_i,b_j)\vee\psi(a_i,b_j')\Leftrightarrow i<j\) for all \(i,j\in\N\).
      Let
      \begin{equation*}
      P:=\{(i,j)\in\N^2:i<j,\vDash\phi(a_i,b_j)\},Q:=\{(i,j)\in\N^2:i<j,\vDash\psi(a_i,b_j')\}
      \end{equation*}
      then \(P\cup Q=\{(i,j)\in\N^2:i<j\}\). By Ramsey there is an infinite \(I\subseteq\N\) s.t. either all
      increasing pairs from \(I\) belong to \(P\), or all increasing pairs from \(I\) belong
      to \(Q\)
    4. [@7] Consider the graph \(G\), disjoint union of all finite graphs. Then the edge
       relation \(E\) is stable in \(G\). Indeed, if it wasn't, we would have a vertex \(x_0\) and
       infinitely many vertices \(\{y_i:i\in\N\}\) s.t. \(E(x_0,y_i)\) for all \(i\), which is impossible

       But by 6, edge relation is not stable in \(\Th(G)\)

    #+END_proof

    #+ATTR_LATEX: :options [Erdős-Makkai]
    #+BEGIN_theorem
    Let \(B\) be an infinite set and \(\calf\subseteq\calp(B)\) a collection of subsets of \(B\)
    with \(\abs{B}<\abs{\calf}\). Then there are sequences \((b_i:i<\omega)\) of elements of \(B\)
    and \((S_i:i<\omega)\) of elements of \(\calf\) s.t. one of the following holds
    1. \(b_i\in S_j\Leftrightarrow\forall i,j\in\omega(j<i)\)
    2. \(b_i\in S_j\Leftrightarrow\forall i,j\in\omega(i<j)\)
    #+END_theorem

    1#+BEGIN_proof
    Choose \(\calf'\subseteq\calf\) with \(\abs{\calf'}=\abs{B}\), s.t. any two finite subsets \(B_0,B_1\) of \(B\),
    if \(\exists S\in\calf\) with \(B_0\subseteq S\), \(B_1\subseteq B\setminus S\), then there is some \(S'\in\calf'\)
    with \(B_0\subseteq S'\), \(B_1\subseteq B\setminus S'\) (possible as there are at most \(\abs{B}\)-many pairs of finite
    subsets of \(B\))

    By assumption there is some \(S^*\in\calf\) which is not a Boolean combination of elements of \(\calf'\)
    (again there are at most \(\abs{B}\)-many different Boolean combinations of sets from \(\calf'\))

    We choose by induction sequences \((b_i':i<\omega)\) in \(S^*\), \(b_i'':i<\omega\) in \(B\setminus S^*\)
    and \((S_i:i<\omega)\) in \(\calf'\) s.t.
    * \(\{b_0',\dots,b_n'\}\subseteq S_n\) and \(\{b_0'',\dots,b_n''\}\subseteq B\setminus S_n\)
    * \(\forall i<n(b_n'\in S_i\Leftrightarrow b_n''\in S_i)\)


    Assume \((b_i':i<n)\), \((b_i'':i<n)\) and \((S_i:i<n)\) have already been constructed.
    Since \(S^*\) is not a Boolean combination of \(S_0,\dots,S_{n-1}\), there
    are \(b_n'\in S^*\), \(b_n''\in B\setminus S^*\) s.t. for all \(i<n\)
    \begin{equation*}
    b_n'\in S_i\Leftrightarrow b_n''\in S_i
    \end{equation*}
    #+LATEX: \wu{
    1. \(S^*\subset\bigcup S_i\) or \(B\setminus S^*\subset\bigcup S_i\). If \(S_1,\dots,S_n,S^*\) is "Boolean combination independent",
       then for any \(i\), \(S_i-S^*\cup\bigcup_{j\neq i}S_i\) and \(S^*\cap S_i-\bigcup_{j\neq i}S_i\) is both nonempty
    2. \(b_n'\in S^*-\bigcup S_i\wedge b_n''\in B\setminus S^*-\bigcup S_i\neq\emptyset\)
    #+LATEX: }

    By the choice of \(\calf'\), there is some \(S_n\in\calf'\) with \(\{b_0',\dots,b_n'\}\subseteq S_n\)
    and \(\{b_0'',\dots,b_n''\}\subseteq B\setminus S_n\).

    Now by Ramsey theorem we may assume that either \(b_n'\in S_i\) for all \(i<n<\omega\) or \(b_n'\notin S_i\)
    for all \(i<n<\omega\) (color the set of pairs \((i,n)\) for \(i<n\) with two colors according to
    whether \(b_n'\in S_i\) or \(b_n'\notin S_i\))
    Then there is an infinite set \(I\subseteq\N\times\N\) s.t. for all \((i,n)\in I\) s.t. \(i<n\), \(b_n'\in S_i\).
    We can reorder the elements of \(I\) and ignore those outside of \(I\)
    In the first case we set \(b_i=b_i''\) and get 1, in the
    second case we set \(b_i=b_{i+1}'\) and get 2.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Fix \(\varphi(x,y)\in L\). By a *complete \varphi-type over* \(A\subseteq M_y\), we mean a maximal consistent collection
    of formulas of the form \(\varphi(x,b)\), \(\neg\varphi(x,b)\) where \(b\) ranges over \(A\). Let \(S_\varphi(A)\) be
    the space of all complete \varphi-types over \(A\)
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:C2.2.13
    Assume that \(\abs{S_\varphi(B)}>\abs{B}\) for some infinite set of parameters \(B\). Then \(\varphi(x,y)\)
    is unstable
    #+END_proposition

    #+BEGIN_proof
    For any \(a\in M_x\), \(\tp_\varphi(a/B)\) is given by \(S_a=\{b\in B:\vDash\varphi(a,b)\}\subseteq B\)

    Applying the Erdős-Makkai theorem to \(B\) and \(\calf=\{S_a:a\in M_x\}\) we obtain a
    sequence \((b_i:i<\omega)\) of elements of \(B\) and a sequence \((a_i:i<\omega)\) of elements of \(M_x\)
    s.t. either \(b_i\in S_{a_j}\Leftrightarrow j<i\) or \(b_i\in S_{a_j}\Leftrightarrow i<j\) for all \(i,j\in\omega\).
    #+END_proof

    #+BEGIN_remark
    1. By a *\varphi-formula over \(M\)* we mean a Boolean combination of instances (over \(M\)) of
       \varphi and \(\neg\varphi\). For example, \((\varphi(x,c)\wedge\varphi(x,b))\vee\neg\varphi(x,d)\) is a \varphi-formula
    2. Any type \(p(x)\in S_\varphi(M)\) decides any \varphi-formula \(\psi(x)\) over \(M\), that is to
       say \(p(x)\vDash\psi(x)\) or \(p(x)\vDash\neg\psi(x)\), so in fact \(p(x)\) extends to a unique maximal
       consistent set of \varphi-formulas over \(M\)
    3. By defining the basic open sets of \(S_\varphi(M)\) to be \(\{p(x)\in S_\varphi(M):\psi(x)\in p\}\) for \psi a
       \varphi-formula, \(S_\varphi(M)\) becomes a compact totally disconnected space, where in addition the
       clopen sets are precisely given by \varphi-formulas, i.e., they are the basic clopen sets
    4. Any \(p(x)\in S_\varphi(M)\) extends to some \(q(x)\in S_x(M)\) s.t. \(p=q\uhr\varphi\), where \(q\uhr\varphi\) is
       the set of \varphi-formulas in \(q(x)\) (or instances of \varphi, \(\neg\varphi\) in \(q(x)\))
    #+END_remark


** Local ranks and definability of types
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We define *Shelah's local 2-rank* taking values in \(\{-\infty\}\cup\omega\cup\{+\infty\}\) by induction on \(n\in\omega\). Let
    \Delta be a set of \(L\)-formulas, and \(\theta(x)\) a partial type over \(\fC\)
    * \(R_\Delta(\theta(x))\ge 0\) iff \(\theta(x)\) is consistent (\(-\infty\) otherwise)
    * \(R_\Delta(\theta(x))\ge n+1\) if for some \(\phi(x,y)\in\Delta\) and \(a\in\fC_y\) we have both \(R_\Delta(\theta(x)\wedge\phi(x,a))\ge n\)
      and \(R_\Delta(\theta(x)\wedge\neg\phi(x,a))\ge n\)
    * \(R_\Delta(\theta(x))=n\) if \(R_\Delta(\theta(x))\ge n\) and \(R_\Delta(\theta(x))\not\ge n+1\), and \(R_\Delta(\theta(x))=\infty\) if
      for \(n\in\omega\), \(R_\Delta(\theta(x))\ge n\)


    If \(\phi(x,y)\) is a formula, we write \(R_\phi\) instead of \(R_{\{\phi\}}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:C2.3.2
    \(\phi(x,y)\) is stable iff \(R_\phi(x=x)\) is finite (and so also \(R_\phi(\theta(x))\) is finite for any
    partial type \theta). Here \(x=(x_i:i\in I)\) is a tuple of variables and \(x=x\) is an abuse of
    notation for \(\bigwedge_{i\in I}x_i=x_i\)
    #+END_proposition

    #+BEGIN_proof
    If \(\phi(x,y)\) is unstable, i.e., it has the \(k\)-order property for all \(k\in\omega\), by
    compactness, we find \((a_ib_i:i\in[0,1])\) s.t. \(\vDash\phi(a_i,b_j)\Leftrightarrow i<j\). We know both \(\phi(x,b_{1/2})\)
    and \(\neg\phi(x,b_{1/2})\) contain dense subsequences of \(a_i\)'s. Each of these sets can be split
    again

    Conversely, suppose the rank is infinite, then we can find an infinite tree of
    parameters \(B=(B_\eta:\eta\in 2^{<\omega})\) s.t. for every \(\eta\in 2^\omega\) there set of
    formulas \(\{\phi^{\eta(i)}(x,b_{\eta\mid i}):i<\omega\}\) is consistent (rank being \(\ge k\) guarantees that we can
    find such a tree of height \(k\), and then use compactness to find one of infinite height). This
    gives us that \(\abs{S_\phi(B)}>\abs{B}\), which by Proposition ref:C2.2.13 implies that \(\phi(x,y)\)
    is unstable
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. Let \(\phi(x,y)\in L\) be given. A type \(p(x)\in S_\phi(A)\) is *definable over* \(B\) if there is
       some \(L(B)\)-formula \(\psi(y)\) s.t. \(\forall a\in A\)
       \begin{equation*}
       \phi(x,a)\in p\Leftrightarrow\;\vDash\psi(a)
       \end{equation*}
    2. A type \(p\in S_x(A)\) is definable over \(B\) if \(p\mid\phi\) is definable over \(B\) for
       all \(\phi(x,y)\in L\)
    3. A type is *definable* if it is definable over its domain
    4. types in \(T\) are *uniformly definable* if for every \(\phi(x,y)\) there is some \(\psi(y,z)\) s.t.
       every type can be defined by an instance of \(\psi(y,z)\), i.e., for any \(A\) and \(p\in S_\phi(A)\)
       there is some \(b\in A\) s.t. \(\phi(x,a)\in p\Leftrightarrow\;\vDash\psi(a,b)\) for all \(a\in A\)
    #+END_definition

    #+BEGIN_remark
    Another way to think about it:

    Given a set \(A\subseteq\fC_x\), \(B\subseteq A\) is *externally definable* (as a subset of \(A\)) if there is some
    definable (over \(\fC\)) set \(X\) s.t. \(B=X\cap A\)

    Assume moreover that we have \(X=\phi(c,\fC)\) above. Then \(\tp_\phi(c/A)\) is definable iff \(B\) is
    internally definable, i.e., \(B=A\cap Y\) for some \(A\)-definable \(Y\). A set is called *stably
    embedded* if every externally definable subset of it is internally definable.
    #+LATEX: \wu{
    \(\phi(x,a)\in\tp_\phi(c/A)\Leftrightarrow\vDash\phi(c,a)\Leftrightarrow a\in X\Leftrightarrow\vDash\psi(a)\). Thus \(X=\phi(c,\fC)=\psi(\fC)\)
    #+LATEX: }
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:C2.3.7
    1. The set \(\{e:R_\phi(\theta(x,e))\ge n\}\) is definable, for all \(n\in\omega\)
    2. If \(R_\phi(\theta(x))=n\), then for any \(a\in M_y\), at most one of \(\theta(x)\wedge\phi(x,a)\), \(\theta(x)\wedge\neg\phi(x,a)\)
       has \(R_\phi\)-rank \(n\)
    #+END_lemma

    #+BEGIN_proof
    1. Let \(S_n(\theta)=\{e:R_\phi(\theta(x,e))\ge n\}\) and suppose it is defined by \(\psi_{n,\theta}(x)\). Induction on \(n\)
       to show that \(S_n(\theta)\) is definable for any \theta.
       For \(n=0\), consider \(\psi_{0,\theta}(x):=\exists y(\theta(y,x))\). Then \(e\in R_0(\theta)\) iff \(\theta(x,e)\) is consistent
       iff \(\vDash\exists x(\theta(x,e))\) iff \(e\in\psi_{0,\theta}(\fC)\).

       Now for \(n\), \(e\in S_n(\theta)\) iff \(\exists a(R_\phi(\theta(x,e)\wedge\phi(x,a))\ge n-1\wedge R_\phi(\theta(x,e)\wedge\neg\phi(x,a))\ge n-1)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:C.2.3.8
    Let \(\phi(x,y)\) be a stable formula. Then all \phi-types are uniformly definable
    #+END_proposition

    #+BEGIN_proof
    <<Problem1>>
    Given \(p\in S_\phi(A)\), call a subtype \(p_i\subseteq p\) one-element minimal if \(R_\phi(q)=R_\phi(p_i)\) for
    all \(p_i\subseteq q\subseteq p\) with \(\abs{\dom(q)\setminus\dom(p_i)}=1\).
    #+LATEX: \wu{
    Take \(a\in A\), \(p'=p\uhr A\setminus\{a\}\),
    #+LATEX: }

    *Claim* For any \(p\in S_\phi(A)\) there is a one-element minimal \(p_i\subseteq p\) with \(\abs{p_i}\le R_\phi(x=x)\)

    Let \(p_0=\emptyset\), and given \(p_i\) let \(p_{i+1}\subseteq p\) be any one-element extension of \(p_i\) of
    smaller \(R_\phi\)-rank, if one exists
    #+END_proof

    Summary
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    TFAE
    1. \(\phi(x,y)\) is stable
    2. \(R_\phi(x=x)<\omega\)
    3. All \phi-types are uniformly definable
    4. All \phi-types over models are definable
    5. \(\abs{S_\phi(M)}\le\kappa\) for all \(\kappa\ge\abs{L}\) and \(M\vDash T\) with \(\abs{M}=\kappa\)
    6. There is some \kappa s.t. \(\abs{S_\phi(M)}<\ded\kappa\) for all \(M\vDash T\) with \(\abs{M}=\kappa\)
    #+END_theorem

    #+BEGIN_proof
    \(1\leftrightarrow 2\) ref:C2.3.2. \(1\to 3\) ref:C2.3.7. \(3\to 4\) obvious.

    \(4\to 5\). There are \(\abs{L}+\kappa=\kappa\) possible formulas defining \(S_\phi(M)\) over \(M\)

    \(6\to 1\) ref:C2.2.8
    #+END_proof

    For complete theory, this translates to
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(T\) be a complete first-order theory. TFAE
    1. \(T\) is stable
    2. There is no sequence of tuples \((a_i:i\in\omega)\) from
    #+END_theorem



    As we will see later, a theory \(T\) iff all types over *all* models of \(T\) are definable.

    Note that there are unstable theories for which all the types over a certain models are
    definable. For instance, in the case of dense linear orders, all types over \(\R\) are definable

    Indeed, by quantifier elimination, any non-realised 1-type over any model of \(\DLO\)
    corresponds to a cut in its order. But in the case of \(\R\), the order is complete, so for any
    cut, there will in fact exist a real number \(r\) s.t. the cut is of the
    form \((\{l\in\R,l<r\},\{d\in\R,d>r\})\). Using this real number \(r\), one can easily show definability
    of 1-types over \(\R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Fix a model \(M\vDash T\) and an \(L\)-formula \(\varphi(x,y)\). TFAE
    1. \(\varphi(x,y)\) is stable in \(M\)
    2. Whenever \(M^*\succ M\) is \(\abs{M}^+\)-saturated and \(\tp(a^*/M^*)\) is finitely satisfiable
       in \(M\), then \(\tp_\varphi(a^*/M^*)\) is definable over \(M\) and, moreover, it is defined by
       some \(\varphi\)-formula \(\varphi^*\), i.e., a Boolean combination of \(\varphi(a,y)\)'s, \(a\in M\)
    #+END_proposition

    1#+BEGIN_proof
    \(1\to 2\). Fix some \(p^*(x)=\tp_\varphi(a^*/M^*)\) finitely satisfiable in \(M\). We want to
    prove \(\tp_\varphi(a^*/M^*)\) is definable over \(M\) by a \(\varphi^*\)-formula. Note first that,
    as \(p^*\) is finitely satisfiable in \(M\), whether or not some \(\varphi(x,b)\), \(b\in M^*\), is
    in \(p^*\) depends only on \(\tp(b/M)\); in fact, even only
    on \(\tp_{\varphi^*}(b/M)=q(y)\in S_{\varphi^*}(M)\)

    Suppose we had \(b'\in M^*\) s.t. \(\tp_{\varphi^*}(b'/M)=\tp_{\varphi^*}(b/M)\), but \(\varphi(x,b)\in p^*\)
    and \(\neg\varphi(x,b')\in p^*\). Then we would have \(\vDash\)
    #+END_proof
** Cantor-Bendixson Rank
    #+ATTR_LATEX: :options [Cantor-Bendixson Rank]
    #+BEGIN_definition
    Let \(X\) be a topological space. The *Cantor-Bendixson rank* is a function \(CB_X:X\to On\cup\{\infty\}\).
    Let \(p\in X\), then:
    1. \(CB_X(p)\ge 0\)
    2. \(CB_X(p)=\alpha\) if \(CB_X(p)\ge\alpha\) and \(p\) is isolated in the (closed)
       subspace \(\{q\in X:CB_X(q)\ge\alpha\}\)
    3. \(CB_X(p)=\infty\) if \(CB_X(p)>\alpha\) for every ordinal \alpha
    #+END_definition

    For example, \(CB_X(p)=0\) if \(p\) is isolated, equivalently if \(\{p\}\) is open. \(CB_X(p)\ge 1\)
    otherwise

    Note that 2 claims that the subspace \(\{q\in X:CB_X(q)\ge\alpha\}\) is closed for all \alpha. This is a
    consequence of the fact that the set of isolated points of any topological space form an open
    set, as a union of open sets


    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:P3.11
    <<Problem5>>
    Suppose \(X\) is compact and \(CB_X(p)<\infty\) for every \(p\) in \(X\). Then there exists a maximal
    element \alpha of \(\{CB_X(p):p\in X\}\) and \(\{p\in X:CB_X(p)=\alpha\}\) is finite and non empty
    #+END_proposition

    #+BEGIN_proof
    Assume there is no maximal element. Then, for each ordinal \alpha there exists some \(p_\alpha\) in \(X\)
    s.t. \(CB_X(p_\alpha)>\alpha\). The set \(\{p_\alpha:\alpha\in On\}\) must have a limit point \(p\) in the
    compact set \(X\), which cannot be isolated in any of the \(\{q\in X:CB_X(q)\ge\alpha\}\).
    Hence \(CB_X(p)=\infty\), a contradiction

    Let \(\alpha=\sup\{CB_X(p):p\in X\}\). We want to show that \(X_\alpha=\{p\in X:CB_X(p)=\alpha\}\) is non-empty. We
    only need to consider the limit case. Assume it is empty and for each \(\beta<\alpha\), \(X_{<\beta}=\{p\in X:CB_X(p)<\beta\}\).
    Since \(\calc=\{X_\beta:\beta<\alpha\}\) is an open cover of \(X\) which clearly has no finite subcover as \alpha is a
    limit ordinal, a contradiction

    \(\{p\in X:CB_X(p)\}\ge\alpha\) is closed, so compact. Since \alpha is maximal, all points
    in \(\{p\in X:CB_X(p)\ge\alpha\}\) are isolated. Therefore \(\{p\in X:CB_X(p)\ge\alpha\}\) is finite
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose \(\varphi(x,y)\) is stable in \(T\). Let \(M\vDash T\), \(X=S_\varphi(M)\). Then \(CB_X(p)<\infty\) for
    each \(p\in X\)
    #+END_lemma

    #+BEGIN_proof
    \(X_\alpha=\{p\in X:CB_X(p)\ge\alpha\}\). If \(\exists q\in X\) s.t. \(CB_X(q)=\infty\), then for some \alpha, \(X_\alpha\neq\emptyset\) and has
    no isolated points. If not, then each \(X_\alpha\) has at least one isolation point and we could
    conclude that \(CB_X(p)\le\abs{X}\) for any \(p\in X\)

    Now fix an \alpha. Since there are no isolated points in \(X_\alpha\), we can find \(p_0,p_1\in X_\alpha\)
    where \(p_0\neq p_1\). Since \(S_\varphi(M)\) is Hausdorff, we can find \(\psi_0(x)\) s.t. \(\psi_0(x)\in p_0\)
    and \(\neg\psi_0(x)\in p_1\). Notice that \(\{p:p\in X_\alpha\}\cap[\psi_0(x)]\) and \(\{p:p\in X_\alpha\}\cap[\psi_1(x)]\) have no
    isolated points. Thus we could build a tree and \(\abs{S_\varphi(M')}\ge 2^{\aleph_0}\) for some countable
    model \(M'\) by Löwenheim–Skolem Theorem since there is only countable many parameters
    #+END_proof

** Local Stability
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. Let \(M\vDash T\). We say \(\varphi(\barx,\bary)\) is *stable in \(M\)* if it is *not* the case that there
       are \(\bara_i,\barb_i\in M\), for \(i<\omega\), s.t. *either* for all \(i,j<\omega\), \(M\vDash\varphi(\bara_i,\barb_j)\)
       iff \(i\le j\), *or*, for all \(i,j<\omega\), \(M\vDash\neg\varphi(\bara_i,\barb_j)\) iff \(i\le j\)

    2. \(\varphi(\barx,\bary)\) is *stable* (for \(T\)) if it is stable in \(M\) for all \(M\vDash T\)
    3. \(T\) is *stable* if every \(L\)-formula \(\varphi(\barx,\bary)\) is stable (for \(T\))
    #+END_definition

    #+BEGIN_remark
    A formula \(\varphi(\barx,\bary)\) is stable for \(T\) iff it is not the case that there
    are \(\bara_i,\barb_i\in\fC\), for \(i<\omega\), s.t. \(\fC\vDash\varphi(\bara_i,\barb_i)\) iff \(i\le j\) for all \(i,j<\omega\)
    #+END_remark

    For simplicity, from now on we will write tuples simply as \(x\) and \(a\).

** Indiscernible sequences and stability
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Given a linear order \(I\), a sequence of tuples \((a_i:i\in I)\) with \(a_i\in\fC_x\) is *indiscernible*
    over a set of parameters \(A\) if \(a_{i_0}\dots a_{i_n}\equiv_A a_{j_0}\dots a_{j_n}\) for all \(i_0<\cdots<i_n\)
    and \(j_0<\cdots< j_n\) from \(I\) and all \(n\in\omega\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(I\) be an infinite linear order and \(\cali=(a_i)_{i\in I}\) a sequence of \(k\)-tuples
    in \(\fM\), \(A\subseteq M\). The *Ehrenfeucht-Mostowski type* \(\EM(\cali/A)\) of \(\cali\) over \(A\) is the set
    of \(L(A)\)-formulas \(\varphi(x_1,\dots,x_n)\) with \(\fM\vDash\varphi(a_{i_1},\dots,a_{i_n})\) for all \(i_1<\dots<i_n\in I\), \(n<\omega\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:C2.4.4
    Let \(\bara=(a_i:i\in J)\) be an arbitrary sequence in \(\fC\), where \(J\) is an arbitrary linear
    order and \(A\) is a small set of parameters. Then for any small linear order \(I\) we can find
    an \(A\)-indiscernible sequence \((b_i:i\in I)\) based on \(\bara\), i.e., s.t.:

    for any \(i_0<\dots<i_n\) in \(I\) and a finite set of formulas \(\Delta\subseteq L(A)\) there are
    some \(j_0<\dots<j_n\) in \omega s.t. \(\vDash\phi(b_{i_0},\dots,b_{i_n})\Leftrightarrow\;\vDash\phi(a_{j_0},\dots,a_{j_n})\) for all \(\phi\in\Delta\)

    Thus \((b_i:i\in I)\) realises \(\EM(\bara/A)\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \((a_i:i\in I)\) is an \(A\)-indiscernible sequence and \(J\supseteq I\) is an arbitrary linear order,
    then there is an \(A\)-indiscernible sequence \((b_j:j\in J)\) s.t. \(b_j=a_j\) for all \(j\in I\)
    (everything involved is small)
    #+END_corollary

    #+BEGIN_proof
    Let \((b_j:j\in J)\) be an arbitrary \(A\)-indiscernible sequence in \(\fC\) based on \(I\),
    obtained by ref:C2.4.4. In particular
    \begin{equation*}
    (b_j:j\in I)\equiv_A(a_j:i\in I)
    \end{equation*}
    which by strong homogeneity of \(\fC\) implies that there is some \(\sigma\in\Aut(\fC/A)\)
    s.t. \(\sigma(b_j)=a_j\). Then define \(b_j'=\sigma(b_j)\) for all \(j\in J\)
    #+END_proof

    #+BEGIN_proof
    First
    #+END_proof



* TODO Problems
    | [[Problem1]] | [[Problem2]] | [[Problem3]] | [[Problem4]] | [[Problem5]] |
    |          |          |          |          |          |

* Index

This is a functional link that will open a buffer of clickable index entries:
# This eliminates the duplicate Index section name
@@latex:\renewcommand{\indexname}{}@@
[[printindex:]]

* References

<<bibliographystyle link>>
bibliographystyle:unsrtnat

<<bibliography link>>
bibliography:/Users/wu/notes/references.bib
