#+TITLE: Stability in Model Theory
#+AUTHOR: Daniel Lascar
#+EXPORT_FILE_NAME: ../latex/StabilityInModelTheory/StabilityInModelTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    The problem that we are going to treat is of this kind: we shall try to classify the models of a
    theory \(T\)

    First we can freely make a certain number of assumptions about \(T\). We can start to classify
    its models by using their elementary theory. This amounts to supposing \(T\) to be complete.
    Then again, if we are sure that a theory \(T'\) in a language \(L'\) has exactly the same models
    as \(T\) - i.e., that there is a natural bijection between the models of \(T\) and those
    of \(T'\) - and that \(T'\) is easier to handle, we may as well work with \(T'\) as with \(T\).
    Hence we may assume that \(T\) admits the elimination of quantifiers: for each
    formula \(\varphi(v_1,\dots,v_n)\) we adjoin a new \(n\)-ary predicate \(R_{\varphi}(v_1,\dots,v_n)\) and consider the
    theory \(T'\) obtained by adding to \(T\) the axioms
    \begin{equation*}
    \forall v_1,\dots,v_n[\varphi(v_1,\dots,v_n)\leftrightarrow R_\varphi(v_1,\dots,v_n)]
    \end{equation*}
    Then \(T'\) admits the elimination of quantifiers and has the same models as \(T\)

    The gain is that every monomorphism becomes elementary. We denote by \(\bC(T)\) the category whose
    objects are the models of \(T\) and whose arrows are the elementary mappings

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    1. Consider the theory of an equivalence relation with an infinite number of classes each having
        infinitely many elements. Then, to have the isomorphism type of model, we first need the number
        of classes, which is a cardinal \lambda, and secondly the cardinality of each of the classes; in other
        words, we need a set of \lambda cardinals
    2. We can complicate the preceding example. Take two equivalence relations, \(E_1\) and \(E_2\),
       where \(E_2\) is finer than \(E_1\) and \(E_1\) has infinitely many classes. Each \(E_1\)-class
       contains infinitely many \(E_2\)-classes and each \(E_2\)-class is infinite. If we try to give
       the invariants that fix the isomorphism type of a model we are faces with a tree of dimensions
    #+END_examplle

    denote by \(I(\lambda,T)\) the number of models, up to isomorphism, of cardinality \lambda. The search for
    the function \(\lambda\to I(\lambda,T)\) is interesting from several points of view
    1. Except when \(I(\lambda,T)\) has its greatest a priori value, namely \(2^\lambda\), it is hard to see how
       to calculate \(I(\lambda,T)\) without classifying the models of \(T\). It allows us to replace a
       vague problem (classify the models) with a precise one (calculate \(I(\lambda,T)\))
    2. In the tiresome case \(I(\lambda,T)=2^\lambda\) it is legitimate to decide that we had better give up
    3. Finally, the growth of the function \(I(\lambda,T)\) will give us a hierarchy for theories


    This granted, the problem presents itself as follows: we first define a set of theories, the
    stable theories; these are the theories of which no model contains a set totally ordered by a
    formula. We can then dismiss the unstable theories, for which \(I(\lambda,T)=2^\lambda\) for
    all \(\lambda>\abs{T}\)

    If we now re-examine the examples of \(\aleph_1\)-categorical theories we find that we have cracked
    the problem, for we have at our disposal:
    1. a concept of independence
    2. from which flows a concept of basis and dimension
    3. a concept of models generated by ...


    It is accordingly a matter of generalizing these three points
    a. For the first we need the assumption of stability: this is the concept of forking
    b. For the second we need a stronger assumption: superstability. But it matters little because
       we show again that if \(T\) is non-superstable then \(I(\lambda,T)=2^\lambda\) for all \(\lambda\ge\abs{T}\)
    c. For the third point we have the concept of prime model: a model is prime over one of its
       substructure \(A\) if it can be embedded elementary in every model that contains \(A\).
       When \(T\) is an \omega-stable theory we prove the existence and uniqueness of a prime model over
       an arbitrary set of parameters


    Unfortunately the hypothesis of \omega-stability does not come free: there are superstable theories
    that are not \omega-stable. However, if we confine ourselves to the category of models that have
    certain saturation properties (\(\aleph_1\)-saturated models for countable stable theories and a
    slightly weaker condition called \(\aleph_\epsilon\)-saturation for superstable theories), then we can prove
    the existence and uniqueness of the prime model


    In all that follows, \(L\) will be a countable language and \(T\) a complete theory in \(L\)
    admitting the elimination of quantifiers.

    When \(A\subset M\), we write \(T(A)\) for the set of those formulas with parameters in \(A\) that are
    true in \(M\). By convention, \(T(A)\) does not depend on \(M\), which is to say that we rule
    out consideration of the situation where \(A\) is a subset of \(M\) and of \(M'\), with formulas
    in parameters in \(A\) that are true in \(M\) but not in \(M'\). This convention allows us the
    abuse of using the same letter for a model and its underlying set

* Types
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.1
    Let \(\bara\in M^n\) and \(\barb\in M'^n\). TFAE
    1. \(\tp^M(\bara)=\tp^{M'}(\barb)\)
    2. There exists a model \(N\) and elementary mappings \(f\) and \(g\) from \(M\) and \(M'\)
       respectively into \(N\) s.t. \(f(\bara)=g(\barb)\)
    3. There exist a model \(N\succ M\) and an elementary mapping \(g\) from \(M'\) into \(N\) s.t. \(g(\barb)=\bara\)
    #+END_proposition

    #+BEGIN_proof
    \(3\to 2\). trivial

    \(2\to 3\). By coping \(N\)  we can find \(N'\succ M\) and an isomorphism \(f':N'\cong N\)

    \(2\to 1\) obvious

    \(1\to 2\) we need the following lemma (Proposition 3.1.4 of C&K)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Two structures are elementarily equivalent iff they can be embedded elementarily in the same
    third structure
    #+END_lemma

    #+BEGIN_proof
    \(\Leftarrow\) trivial

    \(\Rightarrow\). Suppose two structures is \(M\) and \(N\), Then prove \(T(M)\cup T(N)\) is finitely
    satisfiable.
    #+END_proof

    #+ATTR_LATEX: :options [Continued]
    #+BEGIN_proof
    Condition 1 means precisely that \((M,\bara)\equiv(N,\barb)\). Hence there exists a
    structure \((N,\barc)\) and elementary embeddings \(f\) and \(g\) of \((M,\bara)\)
    and \((M',\barb)\) respectively in \((N,\barc)\). We then have \(f(\bara)=g(\barb)=\barc\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\bara,\barb\in M^n\). TFAE
    1. \(\tp(\bara)=\tp(\barb)\)
    2. There exist \(N\succ M\) and an automorphism \(f\) of \(N\) s.t. \(f(\bara)=\barb\)
    #+END_proposition

    #+BEGIN_proof
    \(1\to 2\). By ref:1.1, there is \(M_1\succ M\) and an elementary mapping \(f_1:M\to M_1\)
    s.t. \(f_1(\bara)=\barb\). Then the structure \((M_1,c)_{c\in M}\) is elementarily equivalent
    to \((M_1,f_1(c))_{c\in M}\), and we can find an elementary extension \((M_2,f_1(c))_{M}\)
    of \((M_1,f_1(c))_{c\in M}\) and an elementary mapping \(f_2\) from \((M_1,c)_{c\in M}\)
    into \((M_2,f_1(c))_{c\in M}\); \(f_2\) is then an elementary mapping from \(M_1\) to \(M_2\)
    extending \(f_1\). In this way we construct inductively an elementary chain \((M_n)_{n\in\omega}\) and
    mappings \(f_n\) from \(M_{n-1}\) to \(M_n\), with \(f_n\) extending \(f_{n-1}\). Then \(f\),
    the union of the mappings \(f_n\) is an automorphism of \(N=\bigcup_{n\in\omega}M_n\) and \(f(\bara)=\barb\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(A\subset M\) and \(n\in\omega\). An \(n\)-type on \(A\) is a complete theory in \(L(A\cup\{x_1,\dots,x_n\})\)
    containing \(T(A)\), where the \(x_i\) are new individual constants
    #+END_definition

    Because of the elimination of quantifiers, we do not need to mention \(M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(p\in S_n(A)\). Then there exist \(M\supset A\) and \(\bara\in M^n\) s.t. \(\tp(\bara/A)=p\)
    #+END_proposition

    #+BEGIN_proof
    A model of \(p\) is a structure \((M,a_1,\dots,a_n)\), where \(M\) is a model of \(T(A)\) - or, up to
    isomorphism and an abuse of language, a model of \(T\) containing \(A\) - and \(a_1,\dots,a_n\) are
    interpretations of the \(x_i\)
    #+END_proof

    If \(t\) is a theory in \(L(A\cup\{\barx_n\})\), then \(\{p\in S_n(A):t\subset p\}=\bigcap_{\varphi\in t}[\varphi]\) is a closed
    set of \(S_n(A)\).
