#+TITLE: Stone Spaces
#+AUTHOR: Peter T. Johnstone

#+EXPORT_FILE_NAME: ../latex/StoneSpaces/StoneSpaces.tex
#+LATEX_HEADER: \input{preamble.tex}

* Preliminaries

** Lattices
   Let \(A\) be a poset in which every finite subset has a join. Then the binary
   operation \(\vee\) and the element 0 defiend above satisfy the equations
   1. \(a\vee a=a\)
   2. \(a\vee b=b\vee a\)
   3. \(a\vee(b\vee c)=(a\vee b)\vee c\)
   4. \(a\vee0=a\)


   for all \(a,b,c\). We can say that \((A,\vee,0)\) is a commutative monoid
   where every element is idempotent. Conversely we have
   
   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   Let \((A,\vee,0)\) be a commutative monoid in which every element is
   idempotent. Then there exists a unique partial order on \(A\) s.t.
   \(a\vee b\) is the join of \(a\) and \(b\), and 0 is the least element
   #+END_theorem

   #+BEGIN_proof
   If such a partial order exists, we must have \(a\le b\) iff \(a\vee b=b\).
   Take this as a definition of \(\le\). Suppose \(a\le b\) and \(b\le c\). Then
   \begin{align*}
   a\vee c&=a\vee(b\vee c)\\
   &=(a\vee b)\vee c\\
   &=b\vee c=c
   \end{align*}
   so \(a\le c\).

   Now let \(a,b\) be any two elements of \(A\). Then
   \(a\vee(a\vee b)=(a\vee a)\vee b=a\vee b\), so \(a\le a\vee b\) and similarly
   \(b\le a\vee b\). But if \(a\le c\) and \(b\le c\), then \((a\vee b)\vee
   c=a\vee(b\vee c)=a\vee c=c\), so \(a\vee b\le c\); i.e. \(a\vee b\) is the
   join of \(a\) and \(b\).
   #+END_proof

   A set with the structure described in the theorem is called a *semilattice*. A
   semilattice homomorphism \(f:A\to B\) (i.e. a map preserving the
   distinguished element 0 and the operation \(\vee\)) is necessarily an
   order-preserving map.

   A *lattice* is a poset \(A\) in which every finite subset has both a join and a
   meet.

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   Suppose \((A,\vee,0)\) and \((A,\wedge,1)\) are semilattices. Then
   \((A,\vee,\wedge,0,1)\) is a lattice iff the *absorptive laws*
   \begin{equation*}
   a\wedge(a\vee b)=a,\quad a\vee(a\wedge b)=a
   \end{equation*}
   are satisfied for all \(a,b\in A\)
   #+END_proposition

   #+BEGIN_proof
   If \(a\vee b=b\), then \(a\wedge b=a\wedge(a\vee b)=a\). So the two partial
   orders on \(A\) agree.
   #+END_proof

   *distributive law*
   \begin{equation*}
   a\wedge(b\vee c)=(a\wedge b)\vee(a\wedge c)
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   If the distributive law holds in a lattice, then so does its dual, i.e. the
   identity
   \begin{equation*}
   a\vee(b\wedge c)=(a\vee b)\wedge(a\vee c)
   \end{equation*}
   #+END_lemma

   #+BEGIN_proof
   \begin{align*}
   (a\vee b)\wedge(a\vee c)&=
   ((a\vee b)\wedge a)\vee((a\vee b)\wedge c)\\
   &=a\vee((a\wedge c)\vee(b\wedge c))\\
   &=a\vee(b\wedge c)
   \end{align*}
   #+END_proof

   with distributive law we can deduce either absorptive law from the other

   #+ATTR_LATEX: :options []
   #+BEGIN_proposition
   label:prop1.6
   Let \(a,b,c\) be three elements of a distributive lattice \(A\). Then there
   exists at most one \(x\in A\) satisfying \(x\wedge a=b\) and \(x\vee a=c\)
   #+END_proposition

   #+BEGIN_proof
   Suppose \(x,y\) both satisfy the conditions. Then
   \begin{align*}
   x&=x\wedge(x\vee a)=x\wedge c=x\wedge(y\vee a)\\
   &=(x\wedge y)\vee(x\wedge a)\\
   &=(x\wedge y)\vee b=x\wedge y
   \end{align*}
   since \(b=x\wedge a=y\wedge a\) is a lower bound for \(\{x,y\}\). Similarly
   we have \(y=x\wedge y\); so \(x=y\)
   #+END_proof

   an element \(x\) satisfying \(x\wedge a=0\) and \(x\vee a=1\) is called a
   *complement* of \(a\). The proposition tells us that in a distributive lattice
   complements are unique when they exist. A *boolean algebra* is a distributive
   lattice equipped with an additional unary operation \(\neg:A\to A\) s.t.
   \(\neg a\) is a complement of \(a\). Since \(\neg\) is uniquely determined by
   the other data in the definition, it follows that any lattice homomorphism
   \(f:A\to B\) between Boolean algebras is actually a Boolean algebra homomorphism

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(G\) be a group. The set of subgroups of \(G\), ordered by inclusion, is
   a lattice in which meet is again interpreted as intersection, but the join of
   two subgroups is the subgroup generated by their union.
   #+END_examplle

   In any Boolean algebra \(A\), we define the *symmetric difference* operation +
   by
   \begin{equation*}
   a+b=(a\wedge\neg b)\vee(b\wedge\neg a)
   \end{equation*}

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemma1.8
   The distributive law \(a\wedge(b+c)=(a\wedge b)+(a\wedge c)\) holds
   #+END_lemma

   #+BEGIN_proof
   First note that since \(\neg\) is an order-preserving bijection of \(A\) onto
   itself, it carries jions into meets and vice versa; that is, the De Morgan
   laws
   \begin{equation*}
   \neg(a\wedge b)=\neg a\vee\neg b \quad\text{ and }\quad
   \neg(a\vee b)=\neg a\wedge\neg b
   \end{equation*}
   Now we have
   \begin{align*}
   (a\wedge b)+(a\wedge c)&=
   (a\wedge b\wedge\neg(a\wedge c))\vee(a\wedge c\wedge\neg(a\wedge b))\\
   &=(a\wedge b\wedge(\neg a\vee\neg c))\vee(a\wedge c\wedge(\neg a\vee\neg b))\\
   &=a\wedge(b+c)
   \end{align*}
   #+END_proof

   Also we have associative law
   \begin{equation*}
   a+(b+c)=(a+b)+c
   \end{equation*}
   Now for any \(a\), we have
   \begin{align*}
   &a+a=(a\wedge\neg a)\vee(a\wedge\neg a)=0\\
   &a+0=a
   \end{align*}
   So \((A,+,0)\) is a group and \((A,+,\wedge,0,1)\) is a commutative ring with
   1


   Conversely, let \(A\) be a ring with 1 in which every element satisfies
   \(a^2=a\) (We call \(A\) a *Boolean ring*). Then
   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. \(A\) is commutative
   2. Every \(a\in A\) satisfies \(a+a=0\)
   #+END_lemma

   #+BEGIN_proof
   \begin{align*}
   a+b&=(a+b)^2=a^2+ab+ba+b^2=a+b+ab+ba
   \end{align*}
   So \(ab+ba=0\). Putting \(a=b\) we get \(a+a=0\). Hence \(ab=ba\)
   #+END_proof

   So the multiplicative structure \((A,\cdot,1)\) is a semilattice, with
   partial order defined by \(a\le b\) iff \(ab=a\)

   Now consider \(a+b+ab\). We have
   \begin{equation*}
   a(a+b+ab)=a+ab+ab=a\quad b(a+b+ab)=ba+b+ab=b
   \end{equation*}
   so \(a+b+ab\) is an upper bound for \(\{a,b\}\). But if \(c\) is an upper
   bound for \(\{a,b\}\), then
   \begin{equation*}
   (a+b+ab)c=ac+bc+abc=a+b+ab
   \end{equation*}
   so \(a+b+ab\) is the least upper bound. Denoting \(a+b+ab\) by \(a\vee b\),
   we thus have a lattice structure \((A,\vee,\cdot,0,1)\). Its easy to verify
   that \(\cdot\) is distributive over \(\vee\), and \(1+a\) is a complement for
   \(a\). So \(A\) is a Boolean algebra

   What is the symmetric difference operation in this Boolean algebra? we have
   \begin{align*}
   (a\wedge\neg b)\vee(b\wedge\neg a)&=(a(1+b))\vee(b(1+a))\\
   &=a+b+6ab=a+b
   \end{align*}

   Thus if we start from a Boolean ring and turn it into a Boolean algebra, then
   back into a Boolean ring, we recover the original ring.


   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   The category of Boolean algebras is isomorphic to the category of Boolean rings
   #+END_theorem

   Let \(a\) and \(b\) be elements of a Boolean algebra, and consider the
   element \(\neg a\vee b\). We have
   \begin{align*}
   c\le\neg a\vee b\Rightarrow c\wedge a&\le a\wedge(\neg a\vee b)\\
   &=(a\wedge\neg a)\vee(a\wedge b)\\
   &=0\vee(a\wedge b)=a\wedge b\\
   &\le b
   \end{align*}
   and conversely
   \begin{align*}
   c\wedge a\le b\Rightarrow\neg a\vee b&\ge\neg a\vee(c\wedge a)\\
   &=(\neg a\vee c)\wedge(\neg a\vee a)\\
   &=(\neg a\vee c)\wedge 1\\
   &\ge c
   \end{align*}

   Thus \(\neg a\vee b\) is the unique largest element \(c\) satisfying
   \(c\wedge a\le b\). A lattice \(A\) is said to be a *Heyting algebra* if, for
   each pair of elements \((a,b)\), there exists an element \((a\to b)\) s.t.
   \(c\le(a\to b)\) iff \(c\wedge a\le b\)

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   Let \(A\) be a lattice, \(\to\) a binary operation on \(A\). Then \(\to\)
   makes \(A\) into a Heyting algebra iff the equations
   1. \(a\to a=1\)
   2. \(a\wedge(a\to b)=a\wedge b\)
   3. \(b\wedge(a\to b)=b\)
   4. \(a\to(b\wedge c)=(a\to b)\wedge(a\to c)\)


   hold for all \(a,b,c\) in \(A\)
   #+END_lemma

   #+BEGIN_proof
   Suppose the equations hold. Then if \(c\le(a\to b)\), we have
   \begin{equation*}
   c\wedge a\le a\wedge(a\to b)=a\wedge b\le b
   \end{equation*}
   Conversely, if \(c\wedge a\le b\), then
   \begin{align*}
   c&=c\wedge(a\to c)\\
   &\le(a\to a)\wedge(a\to c) \quad \text{by }1\\
   &=a\to(a\wedge c)\\
   &\le a\to b
   \end{align*}
   since 4 implies thatthe map \(a\to(-)\) is order-preserving


   Now suppose \(A\) is a Heyting algebra. Since we always have
   \(a\wedge c\le a\), it is clear that \(a\to a=1\). And since
   \(b\wedge a\le b\), we have \(b\le a\to b\), i.e. \(b\wedge(a\to b)=b\).
   Now \(a\wedge(a\to b)\le b\) by definition since \(a\to b\le a\to b\). And
   \(a\wedge(a\to b)\le a\), so \(a\wedge(a\to b)\le a\wedge b\). But
   \((a\wedge b)\wedge a\le b\), so \(a\wedge b\le a\to b\), and \(a\wedge b\le
   a\), so \(a\wedge b\le a\wedge(a\to b)\). Finally it is clear that
   \(a\to(-)\) is order-preserving, so \(a\to(b\wedge c)\le(a\to b)\wedge(a\to
   c)\). But
   \begin{align*}
   (a\to b)\wedge(a\to c)\wedge a&=
   (a\wedge(a\to b))\wedge(a\wedge(a\to c))\\
   &\le b\wedge c
   \end{align*}
   so \((a\to b)\wedge(a\to c)\le a\to(b\wedge c)\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   1. A Heyting algebra is distributive
   2. A Heyting algebra \(A\) is a Boolean algebra iff \(\neg\neg a=a\) for all
      \(a\in A\)
   #+END_lemma

   #+BEGIN_proof
   1. Since \(a\wedge(-)\) is order-preserving, we have
      \((a\wedge b)\vee(a\wedge c)\le a\wedge(b\vee c)\). But
      \begin{align*}
      a\to((a\wedge b)\vee(a\wedge c))&\ge(a\to(a\wedge b))\vee(a\to(a\wedge c))\\
      &\ge a\to(b\vee c)
      \end{align*}
      so that \((a\wedge b)\vee(a\wedge c)\ge a\wedge(b\vee c)\)
   2. If \(A\) is a Boolean algebra,then the identity \(\neg\neg a=a\) is clear
      from uniqueness of complement (Proposition ref:prop1.6)

      Conversely, suppose \(\neg\neg a=a\) holds in a Heyting algebra \(A\);
      since we know \(A\) is distributive, we need only verify the identity
      \(a\vee\neg a=1\). But the given condition implies that \(\neg\) is a
      bijection \(A\to A\), and its clearly order-reversing, so the De Morgan
      laws hold. Thus on negating the equation \(a\wedge\neg a=0\) we obtain
      \(\neg a\vee\neg\neg a=\neg a\vee a=1\)
   #+END_proof

   #+BEGIN_exercise
   1. show that the law \(\neg(a\vee b)=\neg a\wedge\neg b\) holds in any
      Heyting algebra, though its dual may fail
   #+END_exercise

   #+BEGIN_proof
   1. 
   #+END_proof
