#+title: Tame Topology And O-minimal Structures

#+AUTHOR: Lou van den Dries

#+EXPORT_FILE_NAME: ../latex/TameTopologyAndOminimalStructures/TameTopologyAndOminimalStructures.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\tint}{\text{int}}
* Some Elementary Results
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *structure* on a nonempty set \(R\) is a sequence \(\cals=(\cals_m)_{m\in\N}\) s.t. for each \(m\ge 0\)
    1. \(\cals_m\) is a boolean algebra of subsets of \(R^m\)
    2. if \(A\in\cals_m\), then \(R\times A\) and \(A\times R\) belong to \(\cals_{m+1}\)
    3. \(\{(x_1,\dots,x_m)\in R^m:x_1=x_m\}\in\cals_m\)
    4. if \(A\in S_{m+1}\), then \(\pi(A)\in\cals_m\) where \(\pi:R^{m+1}\to R^m\) is the projection map on the
       first \(m\) coordinates
    #+END_definition


    Given functions \(f,g:X\to R_\infty\) on a set \(X\subseteq R^m\) we put
    \begin{align*}
    (f,g)&:=\{(x,r)\in X\times R:f(x)<r<g(x)\}\\
    [f,g]&:=\{(x,r)\in X\times R_\infty:f(x)\le r\le g(x)\}
    \end{align*}
    We consider \((f,g)\) as a subset of \(R^{m+1}\); also \([f,g]\subseteq R^{m+1}\) if \(f\) and \(g\) are \(R\)-valued

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints. An *o-minimal structure*
    on \((R,<)\) is by definition a structure \(\cals\) on \(R\) s.t.
    1. \(\{(x,y)\in R^2:x<y\}\in\cals_2\)
    2. the sets in \(\cals_1\) are exactly the finite unions of intervals and points
    #+END_definition

    Fix an o-minimal structure \(\cals\) on \((R,<)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A\subseteq R\) be definable. Then
    1. \(\inf(A)\) and \(\sup(A)\) exist in \(R_\infty\) (dedekind completeness for definable sets)
    2. the
       boundary \(bd(A):=\{x\in R:\text{ each interval containing $x$ intersects both $A$ and $R-A$}\}\)
       is finite, and if \(a_1<\dots<a_k\) are the points of \(bd(A)\) in order, then each
       interval \((a_i,a_{i+1})\), where \(a_0=-\infty\) and \(a_{k+1}=+\infty\) is either part of \(A\) or
       disjoint from \(A\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(A\subseteq R^m\) is definable, so are \(\cl(A)\) and \(\tint(A)\)
    2. If \(A\subseteq B\subseteq R^m\) are definable sets, and \(A\) is open in \(B\), then there is a definable
       open \(U\subseteq R^m\) with \(U\cap B=A\)
    #+END_lemma

    #+BEGIN_proof
    \begin{gather*}
    (x_1,\dots,x_m)\in\cl(A)\\
    \Leftrightarrow\\
    (\forall y_1,\dots,y_m\forall z_1,\dots,z_m[y_1<x<z_1\wedge\dots\wedge y_m<x_m<z_m)\to\\
    \exists a_1,\dots,a_m(y_1<a<z_1)\wedge\dots\wedge y_m<a_m<z_m\wedge(a_1,\dots,a_m)\in A]
    \end{gather*}

    take \(U\) is as the union of all boxes in \(R^m\)  whose intersection with \(B\) is contained in \(A\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq R^m\) is *definably connected* if \(X\) is definable and \(X\) is not the union of two
    disjoint nonempty definable open subsets of \(X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.3.6
    1. the definably connected subsets of \(R\) are the following: the empty set, the intervals, the
       sets \([a,b)\) with \(-\infty<a<b\le+\infty\), the sets \((a,b]\) with \(-\infty\le a<b<+\infty\) and the sets
       \([a,b)\) with \(-\infty<a\le b<+\infty\), and the sets \([a,b]\) with \(-\infty<a\le b<+\infty\)
    2. the image of a definably connected set \(X\subseteq R^m\) under a definable continuous map \(f:X\to R^n\)
       is definably connected
    3. if \(X\) and \(Y\) are definable subsets of \(R^m\), \(X\subseteq Y\subseteq\cl(X)\), and \(X\) is definably
       connected, then \(Y\) is definably connected
    4. if \(X\) and \(Y\) are definably connected subsets of \(R^m\) and \(X\cap Y\neq\emptyset\) , then \(X\cup Y\)
       is definably connected
    #+END_lemma

    #+BEGIN_proof
    3. [@3] suppose \(Y=U_1\cup U_2\) where \(U_1,U_2\) are definably open, then \(X\subseteq U_1\) or \(X\subseteq U_2\)
    #+END_proof

    note the following special case of (2):
    #+BEGIN_center
    If the function \(f:[a,b]\to R\) is definable and continuous, then \(f\) assumes all values
    between \(f(a)\) and \(f(b)\)
    #+END_center
** O-minimal ordered groups and rings
    *Order group* is a group equipped with a linear order that is invariant under left and right
     multiplication:
     \begin{equation*}
    x<y\Rightarrow zx<zy\wedge xz<yz
     \end{equation*}

     #+ATTR_LATEX: :options []
     #+BEGIN_lemma
     The only definable subsets of \(R\) that are also subgroups are \(\{1\}\) and \(R\)
     #+END_lemma

     #+BEGIN_proof
     Given a definable subgroup \(G\) we first show that \(G\) is convex: if not, then there
     are \(g\in G\), \(r\in R-G\) with \(1<r<g\). This gives a sequence
     \begin{equation*}
    1<r<g<rg<g^2<rg^2<g^3<\dots
     \end{equation*}
     whose terms alternate in being in and out of the definable set \(G\).

     So \(G\) is convex, hence assuming \(G\neq\{1\}\) we have \(s:=\sup(G)>1\) with \((1,s)\subseteq G\).
     If \(G=+\infty\), then clearly \(R=G\). If \(s<+\infty\), then we take any \(g\in(1,s)\) and
     obtain \(s=gg^{-1}s\in G\), since \(g^{-1}s\in(1,s)\) hence \(s<gs\in G\)
     #+END_proof

     #+ATTR_LATEX: :options []
     #+BEGIN_proposition
     Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains a binary operation \(\cdot\)
     on \(R\), s.t. \((R,<,\cdot)\) is an ordered group. Then the group \((R,\cdot)\) is abelian, divisible
     and torsion-free
     #+END_proposition

     #+BEGIN_proof
     for each \(r\in R\) the centralizer \(C_r:=\{x\in R:rx=xr\}\) is a definable subgroup
     containing \(r\), so \(C_r=R\)  by the lemma. Hence \(R\) is abelian. For each \(n>0\) the
     subgroup \(\{x^n:x\in R\}\) is definable, hence equal to \(R\). Every ordered group is torsion free
     #+END_proof

     #+BEGIN_remark
     Let \((R,<,+)\) be an ordered abelian group, \(R\neq\{0\}\), so \((R,<)\) has no endpoints. Assume
     also that the linearly ordered set \((R,<)\) is dense. Then the addition operation \(+:R^2\to R\)
     and the additive inverse operation \(-:R\to R\) are continuous w.r.t. the interval topology, that
     is, \((R,+)\) is a topological group w.r.t. the interval topology
     #+END_remark

     An *ordered ring* is a ring (associative with 1) equipped with a linear order < s.t.
     1. \(0<1\)
     2. < is translation invariant
     3. < is invariant under multiplication by positive elements

    Note that then the additive group of the ring is an ordered group, that the ring has no zero
    divisors, that \(x^2\ge 0\) for all \(x\), and that \(k\mapsto k\cdot 1:\Z\to\text{ring}\) is a strictly
    increasing ring embedding

    suppose our ordered ring is moreover a *division ring*: for each \(x\neq 0\) there is \(y\)
    with \(x\cdot y=1\). It is easy to check that such a \(y\) is unique, and satisfies \(y\cdot x=1\) and
    that \(x>0\) implies \(y>0\). It is easy to see that the additive group is divisible, the
    underlying ordered set is dense without endpoints, and the maps \((x,y)\to xy\) and \(x\mapsto x^{-1}\)
    are continuous w.r.t. the interval topology

    An *ordered field* is an ordered division ring with commutative multiplication. Examples: field of
    reals, field of rational numbers. Define *real closed field* to be an ordered field s.t.
    if \(f(X)\) is a one-variable polynomial with coefficients in the field and \(a<b\) are elements
    in the field with \(f(a)<0<f(b)\), then there is \(c\in(a,b)\) in the field with \(f(c)=0\)


    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains binary operations \(+:R^2\to R\)
    and \(\cdot:R^2\to R\) s.t. \((R,<,​+,\cdot)\). Then \((R,<, ​+,\cdot)\) is a real closed field
    #+END_proposition

    #+BEGIN_proof
    For each \(r\in R\) we have a definable additive subgroup \(rR\) of \((R,+)\), hence \(rR=R\)
    if \(r\neq 0\). This shows that \((R,<,+,\cdot)\) is an ordered division ring.
    Let \(Pos(R)=\{r\in R:r>0\}\). Clearly \(Pos(R)\) is an ordered multiplicative group. By
    restricting \(\cals\) to \(Pos(R)\) it follows from the previous proposition that multiplication is
    commutative on \(Pos(R)\), hence on all of \(R\). So \((R,<,+,\cdot)\) is an ordered field. Each
    one-variable polynomial \(f(X)\in R[X]\) gives rise to a definable continuous
    function \(x\mapsto f(x):R\to R\). Now apply ref:1.3.6
    #+END_proof
** Model-theoretic structures
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A model-theoretic structure \(\calr=(R,<,\dots)\) where < is a dense linear order without endpoints
    on \(R\), is called *o-minimal* if \(\Def(\calr_R)\) is an o-minimal structure on \((R,<)\)
    #+END_definition
** The simplest o-minimal structures
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints

    We prove below that the model theoretic structure \((R,<)\) is o-minimal

    Let \(1\le i\le m\). The function \((x_1,\dots,x_m)\mapsto x_i:R^m\to R\) will be denoted by \(x_i\). The *simple*
    functions on \(R^m\) are by definition these coordinate functions \(x_1,\dots,x_m\) and the constant
    functions \(R^m\to R\)

    Let \(f_1,\dots,f_N\) be simple functions on \(R^m\), and let \(\epsilon:\{1,\dots,N\}^2\to\{-1,0,1\}\) be given. Then
    we put
    \begin{align*}
    \epsilon(f_1,\dots,f_N):=\{x\in R^m:&\forall(i,j)\in\{1,\dots,N\}^2\\
    &f_i(x)<f_j(x)\text{ if }\epsilon(i,j)=-1\\
    &f_i(x)=f_j(x)\text{ if }\epsilon(i,j)=0\\
    &f_i(x)>f_j(x)\text{ if }\epsilon(i,j)=1\}
    \end{align*}
    If \xi and \eta are the restrictions of \(f_i\) and \(f_j\) to \(\epsilon(f_1,\dots,f_N)\), then either \(\xi<\eta\)
    or \(\xi=\eta\) or \(\xi>\eta\). Let \(\xi_1<\dots<\xi_k\) be the restrictions of \(f_1,\dots,f_N\) to \(\epsilon(f_1,\dots,f_N)\)
    arranged in increasing order. One checks easily that the sets \(\Gamma(\xi_j)\) \((1\le j\le k)\) and the sets
