#+title: Tame Topology And O-minimal Structures

#+AUTHOR: Lou van den Dries

#+EXPORT_FILE_NAME: ../latex/TameTopologyAndOminimalStructures/TameTopologyAndOminimalStructures.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\tint}{\text{int}}
* Some Elementary Results
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *structure* on a nonempty set \(R\) is a sequence \(\cals=(\cals_m)_{m\in\N}\) s.t. for each \(m\ge 0\)
    1. \(\cals_m\) is a boolean algebra of subsets of \(R^m\)
    2. if \(A\in\cals_m\), then \(R\times A\) and \(A\times R\) belong to \(\cals_{m+1}\) (\(\forall\))
    3. \(\{(x_1,\dots,x_m)\in R^m:x_1=x_m\}\in\cals_m\)
    4. if \(A\in S_{m+1}\), then \(\pi(A)\in\cals_m\) where \(\pi:R^{m+1}\to R^m\) is the projection map on the
       first \(m\) coordinates \((\exists)\)
    5. \(\{a\}\in\cals_1\) for \(a\in R\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \((R,\dots)\) is a model-theoretic structure and \(\cals_n=\{D\subseteq R^n:D\text{ is definable}\}\),
    then \(\{\cals_n\}_{n\in\N}\) is a structure on \(R\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\subseteq\C^n\) is *constructible* if \(X=\bigcup_{i=1}^mY_i\) where each \(Y_i\) has the form
    \begin{equation*}
    \{\barx\in\C^n:P_1(\barx)=0,\dots,P_n(\barx)=0, Q_1(\barx)\neq 0,\dots,Q_n(\barx)\neq 0\}
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(S_m=\{D\subseteq\C^m:D\text{ constructible}\}\), then \(\{\cals_n\}_{n\in\N}\) is a structure on \(\C\)
    #+END_fact

    #+ATTR_LATEX: :options [Chevalley's Theorem, Quantifier elimination in \(\C\)]
    #+BEGIN_theorem
    Projections works
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\subseteq\R^n\) is *semialgebraic* if \(X\) is a finite union of sets of the form
    \begin{equation*}
    \{\barx\in\R^n:P_1(\barx)=0,\dots,P_n(\barx)=0,Q_1(\barx)> 0,\dots,Q_m(\barx)>0\}
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options [Tarski-Seidenberg]
    #+BEGIN_fact
    Semialgebraic sets are a structure on \(\R\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(f:X\to Y\) is definable
    1. if \(f^{-1}\) exists then \(f^{-1}\) is definable
    2. if \(g:Y\to Z\) is definable, then \(g\circ f\) is definable
    3. if \(A\subseteq X\) is definable, then \(f(A)\) is definable
    4. if \(A\subseteq Y\) is definable, then \(f^{-1}(A)\) is definable
    5. If \(A\subseteq X\) is definable, then so is \(f\uhr A\)
    #+END_fact

    Given functions \(f,g:X\to R_\infty\) on a set \(X\subseteq R^m\) we put
    \begin{align*}
    (f,g)&:=\{(x,r)\in X\times R:f(x)<r<g(x)\}\\
    [f,g]&:=\{(x,r)\in X\times R_\infty:f(x)\le r\le g(x)\}
    \end{align*}
    We consider \((f,g)\) as a subset of \(R^{m+1}\); also \([f,g]\subseteq R^{m+1}\) if \(f\) and \(g\) are \(R\)-valued

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints. An *o-minimal structure*
    on \((R,<)\) is by definition a structure \(\cals\) on \(R\) s.t.
    1. \(\{(x,y)\in R^2:x<y\}\in\cals_2\)
    2. the sets in \(\cals_1\) are exactly the finite unions of intervals and points
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Semialgebraic sets are an o-minimal structure on \(\R\)
    #+END_fact

    Fix an o-minimal structure \(\cals\) on \((R,<)\)

    Why o-minimality?
    1. results results for definable sets
    2. a bunch of o-minimal structures exist

    #+ATTR_LATEX: :options [Wilkie]
    #+BEGIN_fact
    There is an o-minimal structure on \(\R\) where \(\exp(-)\), \(\log(-)\) are definable
    #+END_fact

    \(\sin(x)\) cannot be definable in o-minimal structure on \(\R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A\subseteq R\) be definable. Then
    1. \(\inf(A)\) and \(\sup(A)\) exist in \(R_\infty\) (dedekind completeness for definable sets)
    2. the
       boundary \(bd(A):=\{x\in R:\text{ each interval containing $x$ intersects both $A$ and $R-A$}\}\)
       is finite, and if \(a_1<\dots<a_k\) are the points of \(bd(A)\) in order, then each
       interval \((a_i,a_{i+1})\), where \(a_0=-\infty\) and \(a_{k+1}=+\infty\) is either part of \(A\) or
       disjoint from \(A\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(A\subseteq R^m\) is definable, so are \(\cl(A)\) and \(\tint(A)\)
    2. If \(A\subseteq B\subseteq R^m\) are definable sets, and \(A\) is open in \(B\), then there is a definable
       open \(U\subseteq R^m\) with \(U\cap B=A\)
    #+END_lemma

    #+BEGIN_proof
    \begin{gather*}
    (x_1,\dots,x_m)\in\cl(A)\\
    \Leftrightarrow\\
    (\forall y_1,\dots,y_m\forall z_1,\dots,z_m[y_1<x<z_1\wedge\dots\wedge y_m<x_m<z_m)\to\\
    \exists a_1,\dots,a_m(y_1<a<z_1)\wedge\dots\wedge y_m<a_m<z_m\wedge(a_1,\dots,a_m)\in A]
    \end{gather*}

    take \(U\) is as the union of all boxes in \(R^m\)  whose intersection with \(B\) is contained in \(A\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq R^m\) is *definably connected* if \(X\) is definable and \(X\) is not the union of two
    disjoint nonempty definable open subsets of \(X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.3.6
    1. the definably connected subsets of \(R\) are the following: the empty set, the intervals, the
       sets \([a,b)\) with \(-\infty<a<b\le+\infty\), the sets \((a,b]\) with \(-\infty\le a<b<+\infty\) and the sets
       \([a,b)\) with \(-\infty<a\le b<+\infty\), and the sets \([a,b]\) with \(-\infty<a\le b<+\infty\)
    2. the image of a definably connected set \(X\subseteq R^m\) under a definable continuous map \(f:X\to R^n\)
       is definably connected
    3. if \(X\) and \(Y\) are definable subsets of \(R^m\), \(X\subseteq Y\subseteq\cl(X)\), and \(X\) is definably
       connected, then \(Y\) is definably connected
    4. if \(X\) and \(Y\) are definably connected subsets of \(R^m\) and \(X\cap Y\neq\emptyset\) , then \(X\cup Y\)
       is definably connected
    #+END_lemma

    #+BEGIN_proof
    3. [@3] suppose \(Y=U_1\cup U_2\) where \(U_1,U_2\) are definably open, then \(X\subseteq U_1\) or \(X\subseteq U_2\)
    #+END_proof

    note the following special case of (2):
    #+BEGIN_center
    If the function \(f:[a,b]\to R\) is definable and continuous, then \(f\) assumes all values
    between \(f(a)\) and \(f(b)\)
    #+END_center
** O-minimal ordered groups and rings
    *Order group* is a group equipped with a linear order that is invariant under left and right
     multiplication:
     \begin{equation*}
    x<y\Rightarrow zx<zy\wedge xz<yz
     \end{equation*}

     #+ATTR_LATEX: :options []
     #+BEGIN_lemma
     The only definable subsets of \(R\) that are also subgroups are \(\{1\}\) and \(R\)
     #+END_lemma

     #+BEGIN_proof
     Given a definable subgroup \(G\) we first show that \(G\) is convex: if not, then there
     are \(g\in G\), \(r\in R-G\) with \(1<r<g\). This gives a sequence
     \begin{equation*}
    1<r<g<rg<g^2<rg^2<g^3<\dots
     \end{equation*}
     whose terms alternate in being in and out of the definable set \(G\).

     So \(G\) is convex, hence assuming \(G\neq\{1\}\) we have \(s:=\sup(G)>1\) with \((1,s)\subseteq G\).
     If \(G=+\infty\), then clearly \(R=G\). If \(s<+\infty\), then we take any \(g\in(1,s)\) and
     obtain \(s=gg^{-1}s\in G\), since \(g^{-1}s\in(1,s)\) hence \(s<gs\in G\)
     #+END_proof

     #+ATTR_LATEX: :options []
     #+BEGIN_proposition
     Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains a binary operation \(\cdot\)
     on \(R\), s.t. \((R,<,\cdot)\) is an ordered group. Then the group \((R,\cdot)\) is abelian, divisible
     and torsion-free
     #+END_proposition

     #+BEGIN_proof
     for each \(r\in R\) the centralizer \(C_r:=\{x\in R:rx=xr\}\) is a definable subgroup
     containing \(r\), so \(C_r=R\)  by the lemma. Hence \(R\) is abelian. For each \(n>0\) the
     subgroup \(\{x^n:x\in R\}\) is definable, hence equal to \(R\). Every ordered group is torsion free
     #+END_proof

     #+BEGIN_remark
     Let \((R,<,+)\) be an ordered abelian group, \(R\neq\{0\}\), so \((R,<)\) has no endpoints. Assume
     also that the linearly ordered set \((R,<)\) is dense. Then the addition operation \(+:R^2\to R\)
     and the additive inverse operation \(-:R\to R\) are continuous w.r.t. the interval topology, that
     is, \((R,+)\) is a topological group w.r.t. the interval topology
     #+END_remark

     An *ordered ring* is a ring (associative with 1) equipped with a linear order < s.t.
     1. \(0<1\)
     2. < is translation invariant
     3. < is invariant under multiplication by positive elements

    Note that then the additive group of the ring is an ordered group, that the ring has no zero
    divisors, that \(x^2\ge 0\) for all \(x\), and that \(k\mapsto k\cdot 1:\Z\to\text{ring}\) is a strictly
    increasing ring embedding

    suppose our ordered ring is moreover a *division ring*: for each \(x\neq 0\) there is \(y\)
    with \(x\cdot y=1\). It is easy to check that such a \(y\) is unique, and satisfies \(y\cdot x=1\) and
    that \(x>0\) implies \(y>0\). It is easy to see that the additive group is divisible, the
    underlying ordered set is dense without endpoints, and the maps \((x,y)\to xy\) and \(x\mapsto x^{-1}\)
    are continuous w.r.t. the interval topology

    An *ordered field* is an ordered division ring with commutative multiplication. Examples: field of
    reals, field of rational numbers. Define *real closed field* to be an ordered field s.t.
    if \(f(X)\) is a one-variable polynomial with coefficients in the field and \(a<b\) are elements
    in the field with \(f(a)<0<f(b)\), then there is \(c\in(a,b)\) in the field with \(f(c)=0\)


    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains binary operations \(+:R^2\to R\)
    and \(\cdot:R^2\to R\) s.t. \((R,<,​+,\cdot)\). Then \((R,<, ​+,\cdot)\) is a real closed field
    #+END_proposition

    #+BEGIN_proof
    For each \(r\in R\) we have a definable additive subgroup \(rR\) of \((R,+)\), hence \(rR=R\)
    if \(r\neq 0\). This shows that \((R,<,+,\cdot)\) is an ordered division ring.
    Let \(Pos(R)=\{r\in R:r>0\}\). Clearly \(Pos(R)\) is an ordered multiplicative group. By
    restricting \(\cals\) to \(Pos(R)\) it follows from the previous proposition that multiplication is
    commutative on \(Pos(R)\), hence on all of \(R\). So \((R,<,+,\cdot)\) is an ordered field. Each
    one-variable polynomial \(f(X)\in R[X]\) gives rise to a definable continuous
    function \(x\mapsto f(x):R\to R\). Now apply ref:1.3.6
    #+END_proof
** Model-theoretic structures
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A model-theoretic structure \(\calr=(R,<,\dots)\) where < is a dense linear order without endpoints
    on \(R\), is called *o-minimal* if \(\Def(\calr_R)\) is an o-minimal structure on \((R,<)\), in other
    words, every set \(S\subseteq R\) that is definable in \(\calr\) using constants is a union of finitely many
    intervals and points
    #+END_definition
** The simplest o-minimal structures
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints

    We prove below that the model theoretic structure \((R,<)\) is o-minimal

    Let \(1\le i\le m\). The function \((x_1,\dots,x_m)\mapsto x_i:R^m\to R\) will be denoted by \(x_i\). The *simple*
    functions on \(R^m\) are by definition these coordinate functions \(x_1,\dots,x_m\) and the constant
    functions \(R^m\to R\)

    Let \(f_1,\dots,f_N\) be simple functions on \(R^m\), and let \(\epsilon:\{1,\dots,N\}^2\to\{-1,0,1\}\) be given. Then
    we put
    \begin{align*}
    \epsilon(f_1,\dots,f_N):=\{x\in R^m:&\forall(i,j)\in\{1,\dots,N\}^2\\
    &f_i(x)<f_j(x)\text{ if }\epsilon(i,j)=-1\\
    &f_i(x)=f_j(x)\text{ if }\epsilon(i,j)=0\\
    &f_i(x)>f_j(x)\text{ if }\epsilon(i,j)=1\}
    \end{align*}
    If \xi and \eta are the restrictions of \(f_i\) and \(f_j\) to \(\epsilon(f_1,\dots,f_N)\), then either \(\xi<\eta\)
    or \(\xi=\eta\) or \(\xi>\eta\). Let \(\xi_1<\dots<\xi_k\) be the restrictions of \(f_1,\dots,f_N\) to \(\epsilon(f_1,\dots,f_N)\)
    arranged in increasing order. One checks easily that the sets \(\Gamma(\xi_j)\) \((1\le j\le k)\) and the
    sets \((\xi_j,\xi_{j+1})\) (\(0\le j\le k\), where \(\xi_0=-\infty\) and \(\xi_{k+1}=+\infty\) by convention) are
    exactly the nonempty subsets of \(R^{m+1}\) of the form \(\epsilon'(f_1,\dots,f_N,x_{m+1})\) where
    \begin{equation*}
    \epsilon':\{1,\dots,N,N+1\}^2\to\{-1,0,1\}
    \end{equation*}
    is an extension of \epsilon.
    #+LATEX: \wu{
    suppose \(x_{m+1}(x)=y\), we only need to know the relation among \(f_1(x),\dots,f_N(x),y\). And
    \(\bigcup\Gamma(\xi_j)\cup\bigcup(\xi_j,\xi_{j+1})=\epsilon(f_1,\dots,f_N)\times R\)
    #+LATEX: }

    Define a *simple set* in \(R^m\) to be the subset of \(R^m\) of the
    form \(\epsilon(f_1,\dots,f_N)\) with \(f_1,\dots,f_N\) simple functions on \(R^m\) and \(\epsilon:\{1,\dots,N\}^2\to\{-1,0,1\}\).
    We have just proved that if \(S\subseteq R^{m+1}\) is simple, then its image under the projection map
    \begin{equation*}
(x_1,\dots,x_m,x_{m+1})\mapsto(x_1,\dots,x_m):R^{m+1}\to R^m
    \end{equation*}
    is simple in \(R^m\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The subsets of \(R^m\) that are definable in \((R,<)\) using constants are exactly the finite
    unions of simple sets in \(R^m\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\cals_m\) be the collection of finite unions of simple sets in \(R^m\). Clearly \(\cals_m\) is a
    boolean algebra of subsets of \(R^m\), and each set in \(\cals_m\) is definable in \((R,<)\) using
    constants. Texts above show that \(\cals:=(\cals_m)_{m\in\N}\) is a structure on the set \(R\), hence the
    sets in \(\cals_m\) are exactly the subsets of \(R^m\) definable in \((R,<)\) using constants
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The model-theoretic structure \((R,<)\) is o-minimal
    #+END_corollary
** Semilinear sets
    In this section we show that the sets definable using constants in an ordered vector space over
    an ordered field are exactly the semilinear sets.

    definition
* Semialgebriac sets
** Thom's lemma and continuity of roots
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\alpha\in\C\) be a zero of the monic polynomial
    \begin{equation*}
    a_0+a_1T+\dots+a_{d-1}T^{d-1}+T^d\in\C[T],d\ge 1
    \end{equation*}
    Then \(\abs{\alpha}\le 1+\max\{\abs{a_i}:i=0,\dots,d-1\}\)
    #+END_lemma

    #+BEGIN_proof
    Put \(M:=\max\{\abs{a_i}:i=0,\dots,d-1\}\) and suppose \(\alpha>1+M\). Then
    \(\abs{a_0+a_1\alpha+\dots+a^{d-1}\alpha^{d-1}}\le M(1+abs{\alpha}+\dots+\abs{\alpha}^{d-1})=M(\abs{\alpha}^d-1)/(\abs{\alpha}-1)<\abs{\alpha}^d\),
    contradicting \(0=\abs{f(\alpha)}\)
    #+END_proof

    #+ATTR_LATEX: :options [Thom]
    #+BEGIN_lemma
    Let \(f_1,\dots,f_k\in\R[T]\) be nonzero polynomials s.t. if \(f_i'\neq 0\), then \(f_i'\in\{f_1,\dots,f_k\}\).
    Let \(\epsilon:\{1,\dots,k\}\to\{-1,0,1\}\), and put
    \begin{equation*}
    A_\epsilon:=\{t\in\R:\sgn(f_i(t))=\epsilon(i),i=1,\dots,k\}\subseteq\R
    \end{equation*}
    Then \(A_\epsilon\) is empty, a point, or an interval. If \(A_\epsilon\neq\emptyset\), then its closure is given by
    \begin{equation*}
    \cl(A_\epsilon)=\{t\in\R:\sgn(f_i(t))\in\{\epsilon(i),0\},i=1,\dots,k\}
    \end{equation*}
    If \(A_\epsilon=\emptyset\), then \(\{t\in\R:\sgn(f_i(t))\in\{\epsilon(i),0\},i=1,\dots,k\}\) is empty or a point
    #+END_lemma

    We call \epsilon a *sign condition* for \(f_1,\dots,f_k\). The \(3^k\) possible sign conditions \epsilon
    determine \(3^K\) disjoint sets \(A_\epsilon\), which together cover the real line \(\R\). The second
    statement of the lemma says that for nonempty \(A_\epsilon\) its closure can be obtained by relaxing
    all strict inequalities to weak inequalities

    #+BEGIN_proof
    By induction on \(k\). The lemma holds trivially for \(k=0\). Let \(f_1,\dots,f_k,f_{k+1}\in\R[T]-\{0\}\)
    be polynomials s.t. if \(f_i'\neq 0\), then \(f_i'\in\{f_1,\dots,f_{k+1}\}\). We may assume
    that \(\deg(f_{k+1})=\max\{\deg(f_i):1\le i\le k+1\}\). Let \(\epsilon':\{1,\dots,k+1\}\to\{-1,0,1\}\), and let \epsilon be the
    restriction of \(\epsilon'\) to \(\{1,\dots,k\}\). By the inductive hypothesis, \(A_\epsilon\) is empty, a point or
    an interval. It \(A_\epsilon\) is empty or a point, so
    is \(A_{\epsilon'}=A_\epsilon\cap\{t\in\R:\sgn(f_{k+1}(t))=\epsilon'(k+1)\}\), and the other properties to be checked in this
    case follow easily from the inductive hypothesis on \(A_\epsilon\)

    Suppose \(A_\epsilon\) is an interval. Since \(f_{k+1}'\) has a constant sign on \(A_\epsilon\), the
    function \(f_{k+1}\) is either strictly monotone on \(A_\epsilon\), or constant. In both cases, it is
    routine to check that \(A_{\epsilon'}=A_\epsilon\cap\{t\in\R:\sgn(f_{k+1}(t))=\epsilon'(k+1)\}\) has the required properties
    #+END_proof

    #+ATTR_LATEX: :options [Continuity of roots]
    #+BEGIN_lemma
    Let \(f(T)=a_0+a_1+\dots+a_dT^d\in\C[T]\) be a polynomial that has no zero on the boundary
    circle \(\abs{z-c}=r\) of a given open disc \(\abs{z-c}<r\) in the complex plane \((c\in\C,r>0)\).
    Then there is \(\epsilon>0\) s.t. if \(\abs{a_i-b_i}\le\epsilon\) for \(i=0,\dots,d\)
    then \(g(T):=b_0+b_1T+\dots+b_dT_d\in\C[T]\) also has no zero on the circle, and \(f\) and \(g\) have
    the same number of zeros in the disc
    #+END_lemma
* Cell Decomposition
    Fix an arbitrary o-minimal structure \((R,<,\cals)\). Instead of saying that a set \(A\subseteq R^m\) belongs
    to \(\cals\), we say that \(A\) is definable
** The monotonicity theorem and the finiteness lemma
    #+ATTR_LATEX: :options [Monotonicity theorem]
    #+BEGIN_theorem
    Let \(f:(a,b)\to R\) be a definable function on the interval \((a,b)\). Then there are
    points \(a_1<\dots<a_k\) in \((a,b)\) s.t. on each subinterval \((a_j,a_{j+1})\)
    with \(a_0=a\), \(a_{k+1}=b\), the function is either constant, or strictly monotone and continuous
    #+END_theorem


    We derive this from the threes below. In these lemmas we consider a definable
    function \(f:I\to R\) on an interval \(I\)
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.1
    There is a subinterval of \(I\) on which \(f\) is constant or injective
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.2
    If \(f\) is injective, then \(f\) is strictly monotone on a subinterval of \(I\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.3
    If \(f\) is strictly monotone, then \(f\) is continuous on a subinterval of \(I\)
    #+END_lemma

    These lemmas imply the monotonicity theorem as follows:

    Let
    \begin{align*}
    X:=\{x\in(a,b):&\text{on some subinterval of $(a,b)$ containing $x$ the function $f$}\\
    &\text{is either constant, or strictly monotonicity and continuous}\}
    \end{align*}
    Now \((a,b)-X\) must be finite, since otherwise it would contain an interval \(I\); applying
    successively lemmas ref:3.1.1, ref:3.1.2, ref:3.1.3 we can make \(I\) so small that \(f\) is
    either constant, or strictly monotone and continuous on \(I\). But then \(I\subseteq X\), a
    contradiction <<Problem1>>

    Since \((a,b)-X\) is finite, we can reduce the proof of the theorem to the case
    that \((a,b)=X\), by replacing \((a,b)\) by each of the finitely many intervals of which the
    open set \(X\) consists. In particular, we may assume that \(f\) is continuous. By splitting
    up \((a,b)\) further we can reduce to one of the following three cases

    Case 1. For all \(x\in(a,b)\), \(f\) is constant on some neighborhood of \(x\)

    Case 2. For all \(x\in(a,b)\), \(f\) is strictly increasing on some neighborhood of \(x\)

    Case 3. For all \(x\in(a,b)\), \(f\) is strictly decreasing on some neighborhood of \(x\)

    Case 1. Take \(x_0\in(a,b)\) and put
    \begin{equation*}
    s:=\sup\{x:x_0<x<b,f\text{ is constant on }[x_0,x)\}
    \end{equation*}
    Then \(s=b\), since \(s<b\) implies that \(f\) is constant on some neighborhood of \(s\),
    contradiction. From \(s=b\) it follows that \(f\) is constant on \([x_0,b)\). Similarly we prove
    that \(f\) is constant on \((a,x_0]\), therefore \(f\) is constant on \((a,b)\)

    Case 2. Take \(x_0\in(a,b)\) and put
    \begin{equation*}
    s:=\sup\{x:x_0<x<b,f\text{ is strictly increasing on }[x_0,x)\}
    \end{equation*}
    Then \(s=b\), since \(s<b\) leads to a contradiction

    We now prove the lemmas

    #+ATTR_LATEX: :options [Proof of Lemma \ref{3.1.1}]
    #+BEGIN_proof
    If some \(y\in R\) had infinite preimage \(f^{-1}(y)\), then this preimage would contain a
    subinterval of \(I\)<<Problem2>> and \(f\) would take the constant value \(y\) on that subinterval. So we
    may assume that each \(y\in R\) has finite preimage. Then \(f(I)\) is infinite, and so contains an
    interval \(J\). Define an "inverse" \(g:J\to I\) by
    \begin{equation*}
    g(y):=\min\{x\in I:f(x)=y\}
    \end{equation*}
    Since \(g\) is injective by definition, \(g(J)\) is infinite, and hence \(g(J)\) contains a
    subinterval of \(I\), and \(f\) is necessarily injective on this subinterval
    #+END_proof
** The cell decomposition theorem
    for each definable set \(X\) in \(R^m\) we put
    \begin{align*}
    C(X)&:=\{f:X\to R:f\text{ definable and continuous}\}\\
    C_\infty(X)&:=C(X)\cup\{-\infty,+\infty\}
    \end{align*}
    where we regard \(-\infty\) and \(+\infty\) as constant functions on \(X\)

    For \(f,g\in C_\infty(X)\) we write \(f<g\) if \(f(x)<g(x)\) for all \(x\in X\), and in this case we put
    \begin{equation*}
    (f,g)_X:=\{(x,r)\in X\times R:f(x)<r<g(x)\}
    \end{equation*}
    So \((f,g)_X\) is a definable subset of \(R^{m+1}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((i_1,\dots,i_m)\) be a sequence of zeros and ones of length \(m\). An *\((i_1,\dots,i_m)\)-cell* is a
    definable subset of \(R^m\) obtained by induction on \(m\) as follows:
    1. a \((0)\)-cell is a one-element set \(\{r\}\subseteq R\), a \((1)\)-cell is an
       interval \((a,b)\subseteq R\)
    2. suppose \((i_1,\dots,i_m)\)-cells are already defined, then an \((i_1,\dots,i_m,0)\)-cell is the
       graph \(\Gamma(f)\) of a function \(f\in C(X)\), where \(X\) is an \((i_1,\dots,i_m)\)-cell; further,
       an \((i_1,\dots,i_m,1)\)-cell is a set \((f,g)_X\) where \(X\) is an \((i_1,\dots,i_m)\)-cell
       and \(f,g\in C_\infty(X)\), \(f<g\)
    #+END_definition

    So a \((0,0)\)-cell is a "point" \(\{(r,s)\}\subseteq R^2\), a \((0,1)\)-cell is an "interval" on a
    vertical line \(\{a\}\times R\), and a \((1,0)\)-cell is the graph of a continuous definable function
    defined on an interval.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *cell in* \(R^m\) is an \((i_1,\dots,i_m)\)-cell for some (necessarily unique)
    sequence \((i_1,\dots,i_m)\). Since the \((1,\dots,1)\)-cells are exactly the cells which are open in
    their ambient space \(R^m\), we call these *open cells*
    #+END_definition

    The non-open cells are "thin":

    The union of finitely many non-open cells in \(R^m\) has empty interior

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Each cell is locally closed, i.e., open in its closure
    #+END_proposition

    #+BEGIN_proof
    Let \(C\subseteq R^{m+1}\) be a cell
    #+END_proof
