#+title: Tame Topology And O-minimal Structures

#+AUTHOR: Lou van den Dries

#+EXPORT_FILE_NAME: ../latex/TameTopologyAndOminimalStructures/TameTopologyAndOminimalStructures.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\tint}{\text{int}}

* Some Elementary Results
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *structure* on a nonempty set \(R\) is a sequence \(\cals=(\cals_m)_{m\in\N}\) s.t. for each \(m\ge 0\)
    1. \(\cals_m\) is a boolean algebra of subsets of \(R^m\)
    2. if \(A\in\cals_m\), then \(R\times A\) and \(A\times R\) belong to \(\cals_{m+1}\) (\(\forall\))
    3. \(\{(x_1,\dots,x_m)\in R^m:x_1=x_m\}\in\cals_m\)
    4. if \(A\in S_{m+1}\), then \(\pi(A)\in\cals_m\) where \(\pi:R^{m+1}\to R^m\) is the projection map on the
       first \(m\) coordinates \((\exists)\)
    5. \(\{a\}\in\cals_1\) for \(a\in R\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \((R,\dots)\) is a model-theoretic structure and \(\cals_n=\{D\subseteq R^n:D\text{ is definable}\}\),
    then \(\{\cals_n\}_{n\in\N}\) is a structure on \(R\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\subseteq\C^n\) is *constructible* if \(X=\bigcup_{i=1}^mY_i\) where each \(Y_i\) has the form
    \begin{equation*}
    \{\barx\in\C^n:P_1(\barx)=0,\dots,P_n(\barx)=0, Q_1(\barx)\neq 0,\dots,Q_n(\barx)\neq 0\}
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(S_m=\{D\subseteq\C^m:D\text{ constructible}\}\), then \(\{\cals_n\}_{n\in\N}\) is a structure on \(\C\)
    #+END_fact

    #+ATTR_LATEX: :options [Chevalley's Theorem, Quantifier elimination in \(\C\)]
    #+BEGIN_theorem
    Projections works
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(X\subseteq\R^n\) is *semialgebraic* if \(X\) is a finite union of sets of the form
    \begin{equation*}
    \{\barx\in\R^n:P_1(\barx)=0,\dots,P_n(\barx)=0,Q_1(\barx)> 0,\dots,Q_m(\barx)>0\}
    \end{equation*}
    #+END_definition

    Semialgebraic sets are closed under intersection, union, complement, cartesian product, projection

    #+ATTR_LATEX: :options [Tarski-Seidenberg]
    #+BEGIN_fact
    Semialgebraic sets are a structure on \(\R\) (projection)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(f:X\to Y\) is definable
    1. if \(f^{-1}\) exists then \(f^{-1}\) is definable
    2. if \(g:Y\to Z\) is definable, then \(g\circ f\) is definable
    3. if \(A\subseteq X\) is definable, then \(f(A)\) is definable
    4. if \(A\subseteq Y\) is definable, then \(f^{-1}(A)\) is definable
    5. If \(A\subseteq X\) is definable, then so is \(f\uhr A\)
    #+END_fact

    Given functions \(f,g:X\to R_\infty\) on a set \(X\subseteq R^m\) we put
    \begin{align*}
    (f,g)&:=\{(x,r)\in X\times R:f(x)<r<g(x)\}\\
    [f,g]&:=\{(x,r)\in X\times R_\infty:f(x)\le r\le g(x)\}
    \end{align*}
    We consider \((f,g)\) as a subset of \(R^{m+1}\); also \([f,g]\subseteq R^{m+1}\) if \(f\) and \(g\) are \(R\)-valued

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints. An *o-minimal structure*
    on \((R,<)\) is by definition a structure \(\cals\) on \(R\) s.t.
    1. \(\{(x,y)\in R^2:x<y\}\in\cals_2\)
    2. the sets in \(\cals_1\) are exactly the finite unions of intervals and points
    #+END_definition

    In \(\R\), "definable" = "semialgebraic", in \(\Q\), "definable" = "semilinear"

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Semialgebraic sets are an o-minimal structure on \(\R\)
    #+END_fact

    context
    - \((R,\le)\) dense linear order with no endpoints
    - for each \(n\), there's \(\cals_n\)

    Fix an o-minimal structure \(\cals\) on \((R,<)\)

    Why o-minimality?
    1. results results for definable sets
    2. a bunch of o-minimal structures exist

    #+ATTR_LATEX: :options [Wilkie]
    #+BEGIN_fact
    There is an o-minimal structure on \(\R\) where \(\exp(-)\), \(\log(-)\) are definable
    #+END_fact

    \(\sin(x)\) cannot be definable in o-minimal structure on \(\R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A\subseteq R\) be definable. Then
    1. \(\inf(A)\) and \(\sup(A)\) exist in \(R_\infty\) (dedekind completeness for definable sets)
    2. the
       boundary \(bd(A):=\{x\in R:\text{ each interval containing $x$ intersects both $A$ and $R-A$}\}\)
       is finite, and if \(a_1<\dots<a_k\) are the points of \(bd(A)\) in order, then each
       interval \((a_i,a_{i+1})\), where \(a_0=-\infty\) and \(a_{k+1}=+\infty\) is either part of \(A\) or
       disjoint from \(A\)
    3. If \(\abs{X}=\infty\) then \(X\supseteq I\) for some \(I\)
    4. If \(X\) is dense in \(I\), then \(\abs{X}=\infty\), \(X\supseteq J\) (not true in \(\Q\)/\(\R\)) (\(X\subseteq I\) is
       *dense* in \(I\)if \(\forall J\subseteq I(J\cap X\neq\emptyset)\))
    5. If \(p\in R\), then \(\exists b>a\) s.t. \((a,b)\subseteq X\) or \((a,b)\cap X=\emptyset\). Locally,
    #+END_lemma

    #+BEGIN_proof
    2. [@2] \(bd(X\cup Y)\subseteq bd(X)\cup bd(Y)\)
    3. \(X\) is a union of interval and points
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(A\subseteq R^m\) is definable, so are \(\cl(A)\) and \(\tint(A)\)
    2. If \(A\subseteq B\subseteq R^m\) are definable sets, and \(A\) is open in \(B\), then there is a definable
       open \(U\subseteq R^m\) with \(U\cap B=A\)
    #+END_lemma

    #+BEGIN_proof
    \begin{gather*}
    (x_1,\dots,x_m)\in\cl(A)\\
    \Leftrightarrow\\
    (\forall y_1,\dots,y_m\forall z_1,\dots,z_m[y_1<x<z_1\wedge\dots\wedge y_m<x_m<z_m)\to\\
    \exists a_1,\dots,a_m(y_1<a<z_1)\wedge\dots\wedge y_m<a_m<z_m\wedge(a_1,\dots,a_m)\in A]
    \end{gather*}

    take \(U\) is as the union of all boxes in \(R^m\)  whose intersection with \(B\) is contained in \(A\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq R^m\) is *definably connected* if \(X\) is definable and \(X\) is not the union of two
    disjoint nonempty definable open subsets of \(X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.3.6
    1. the definably connected subsets of \(R\) are the following: the empty set, the intervals, the
       sets \([a,b)\) with \(-\infty<a<b\le+\infty\), the sets \((a,b]\) with \(-\infty\le a<b<+\infty\) and the sets
       \([a,b)\) with \(-\infty<a\le b<+\infty\), and the sets \([a,b]\) with \(-\infty<a\le b<+\infty\)
    2. the image of a definably connected set \(X\subseteq R^m\) under a definable continuous map \(f:X\to R^n\)
       is definably connected
    3. if \(X\) and \(Y\) are definable subsets of \(R^m\), \(X\subseteq Y\subseteq\cl(X)\), and \(X\) is definably
       connected, then \(Y\) is definably connected
    4. if \(X\) and \(Y\) are definably connected subsets of \(R^m\) and \(X\cap Y\neq\emptyset\) , then \(X\cup Y\)
       is definably connected
    #+END_lemma

    #+BEGIN_proof
    3. [@3] suppose \(Y=U_1\cup U_2\) where \(U_1,U_2\) are definably open, then \(X\subseteq U_1\) or \(X\subseteq U_2\)
    #+END_proof

    note the following special case of (2):
    #+BEGIN_center
    If the function \(f:[a,b]\to R\) is definable and continuous, then \(f\) assumes all values
    between \(f(a)\) and \(f(b)\)
    #+END_center

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(I,J\subseteq R\) intervals, \(X\subseteq R\) definable, \(I<J\), \(\abs{I\setminus X}=\infty=\abs{J\cap X}\), then there
    is \(a\) s.t. \(I<a<J\), and there is \(c<a<b\) s.t. \((c,a)\cap X=\emptyset\), \((a,b)\subseteq X\)
    #+END_lemma

    #+BEGIN_proof
    take \(a=\inf X\setminus bd(X)\)
    #+END_proof
** O-minimal ordered groups and rings
    *Order group* is a group equipped with a linear order that is invariant under left and right
     multiplication:
     \begin{equation*}
    x<y\Rightarrow zx<zy\wedge xz<yz
     \end{equation*}

     #+ATTR_LATEX: :options []
     #+BEGIN_lemma
     The only definable subsets of \(R\) that are also subgroups are \(\{1\}\) and \(R\)
     #+END_lemma

     #+BEGIN_proof
     Given a definable subgroup \(G\) we first show that \(G\) is convex: if not, then there
     are \(g\in G\), \(r\in R-G\) with \(1<r<g\). This gives a sequence
     \begin{equation*}
    1<r<g<rg<g^2<rg^2<g^3<\dots
     \end{equation*}
     whose terms alternate in being in and out of the definable set \(G\).

     So \(G\) is convex, hence assuming \(G\neq\{1\}\) we have \(s:=\sup(G)>1\) with \((1,s)\subseteq G\).
     If \(G=+\infty\), then clearly \(R=G\). If \(s<+\infty\), then we take any \(g\in(1,s)\) and
     obtain \(s=gg^{-1}s\in G\), since \(g^{-1}s\in(1,s)\) hence \(s<gs\in G\)
     #+END_proof

     #+ATTR_LATEX: :options []
     #+BEGIN_proposition
     Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains a binary operation \(\cdot\)
     on \(R\), s.t. \((R,<,\cdot)\) is an ordered group. Then the group \((R,\cdot)\) is abelian, divisible
     and torsion-free
     #+END_proposition

     #+BEGIN_proof
     for each \(r\in R\) the centralizer \(C_r:=\{x\in R:rx=xr\}\) is a definable subgroup
     containing \(r\), so \(C_r=R\)  by the lemma. Hence \(R\) is abelian. For each \(n>0\) the
     subgroup \(\{x^n:x\in R\}\) is definable, hence equal to \(R\). Every ordered group is torsion free
     #+END_proof

     #+BEGIN_remark
     Let \((R,<,+)\) be an ordered abelian group, \(R\neq\{0\}\), so \((R,<)\) has no endpoints. Assume
     also that the linearly ordered set \((R,<)\) is dense. Then the addition operation \(+:R^2\to R\)
     and the additive inverse operation \(-:R\to R\) are continuous w.r.t. the interval topology, that
     is, \((R,+)\) is a topological group w.r.t. the interval topology
     #+END_remark

     An *ordered ring* is a ring (associative with 1) equipped with a linear order < s.t.
     1. \(0<1\)
     2. < is translation invariant
     3. < is invariant under multiplication by positive elements

    Note that then the additive group of the ring is an ordered group, that the ring has no zero
    divisors, that \(x^2\ge 0\) for all \(x\), and that \(k\mapsto k\cdot 1:\Z\to\text{ring}\) is a strictly
    increasing ring embedding

    suppose our ordered ring is moreover a *division ring*: for each \(x\neq 0\) there is \(y\)
    with \(x\cdot y=1\). It is easy to check that such a \(y\) is unique, and satisfies \(y\cdot x=1\) and
    that \(x>0\) implies \(y>0\). It is easy to see that the additive group is divisible, the
    underlying ordered set is dense without endpoints, and the maps \((x,y)\to xy\) and \(x\mapsto x^{-1}\)
    are continuous w.r.t. the interval topology

    An *ordered field* is an ordered division ring with commutative multiplication. Examples: field of
    reals, field of rational numbers. Define *real closed field* to be an ordered field s.t.
    if \(f(X)\) is a one-variable polynomial with coefficients in the field and \(a<b\) are elements
    in the field with \(f(a)<0<f(b)\), then there is \(c\in(a,b)\) in the field with \(f(c)=0\)


    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Suppose \((R,<,\cals)\) is an o-minimal structure and \(\cals\) contains binary operations \(+:R^2\to R\)
    and \(\cdot:R^2\to R\) s.t. \((R,<,​+,\cdot)\). Then \((R,<, ​+,\cdot)\) is a real closed field
    #+END_proposition

    #+BEGIN_proof
    For each \(r\in R\) we have a definable additive subgroup \(rR\) of \((R,+)\), hence \(rR=R\)
    if \(r\neq 0\). This shows that \((R,<,+,\cdot)\) is an ordered division ring.
    Let \(Pos(R)=\{r\in R:r>0\}\). Clearly \(Pos(R)\) is an ordered multiplicative group. By
    restricting \(\cals\) to \(Pos(R)\) it follows from the previous proposition that multiplication is
    commutative on \(Pos(R)\), hence on all of \(R\). So \((R,<,+,\cdot)\) is an ordered field. Each
    one-variable polynomial \(f(X)\in R[X]\) gives rise to a definable continuous
    function \(x\mapsto f(x):R\to R\). Now apply ref:1.3.6
    #+END_proof
** Model-theoretic structures
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A model-theoretic structure \(\calr=(R,<,\dots)\) where < is a dense linear order without endpoints
    on \(R\), is called *o-minimal* if \(\Def(\calr_R)\) is an o-minimal structure on \((R,<)\), in other
    words, every set \(S\subseteq R\) that is definable in \(\calr\) using constants is a union of finitely many
    intervals and points
    #+END_definition

    \((\R,+,\cdot,\le)\), \((\R,+,\le)\), \((\Q,+,\le)\), \((\R,\le)\), \((\Q,\le)\)

    Wilkie's theorem: \((\R,+,\cdot,\le,\exp)\),
** The simplest o-minimal structures
    Let \((R,<)\) be a dense linearly ordered nonempty set without endpoints

    We prove below that the model theoretic structure \((R,<)\) is o-minimal

    Let \(1\le i\le m\). The function \((x_1,\dots,x_m)\mapsto x_i:R^m\to R\) will be denoted by \(x_i\). The *simple*
    functions on \(R^m\) are by definition these coordinate functions \(x_1,\dots,x_m\) and the constant
    functions \(R^m\to R\)

    Let \(f_1,\dots,f_N\) be simple functions on \(R^m\), and let \(\epsilon:\{1,\dots,N\}^2\to\{-1,0,1\}\) be given. Then
    we put
    \begin{align*}
    \epsilon(f_1,\dots,f_N):=\{x\in R^m:&\forall(i,j)\in\{1,\dots,N\}^2\\
    &f_i(x)<f_j(x)\text{ if }\epsilon(i,j)=-1\\
    &f_i(x)=f_j(x)\text{ if }\epsilon(i,j)=0\\
    &f_i(x)>f_j(x)\text{ if }\epsilon(i,j)=1\}
    \end{align*}
    If \xi and \eta are the restrictions of \(f_i\) and \(f_j\) to \(\epsilon(f_1,\dots,f_N)\), then either \(\xi<\eta\)
    or \(\xi=\eta\) or \(\xi>\eta\). Let \(\xi_1<\dots<\xi_k\) be the restrictions of \(f_1,\dots,f_N\) to \(\epsilon(f_1,\dots,f_N)\)
    arranged in increasing order. One checks easily that the sets \(\Gamma(\xi_j)\) \((1\le j\le k)\) and the
    sets \((\xi_j,\xi_{j+1})\) (\(0\le j\le k\), where \(\xi_0=-\infty\) and \(\xi_{k+1}=+\infty\) by convention) are
    exactly the nonempty subsets of \(R^{m+1}\) of the form \(\epsilon'(f_1,\dots,f_N,x_{m+1})\) where
    \begin{equation*}
    \epsilon':\{1,\dots,N,N+1\}^2\to\{-1,0,1\}
    \end{equation*}
    is an extension of \epsilon.
    #+LATEX: \wu{
    suppose \(x_{m+1}(x)=y\), we only need to know the relation among \(f_1(x),\dots,f_N(x),y\). And
    \(\bigcup\Gamma(\xi_j)\cup\bigcup(\xi_j,\xi_{j+1})=\epsilon(f_1,\dots,f_N)\times R\)
    #+LATEX: }

    Define a *simple set* in \(R^m\) to be the subset of \(R^m\) of the
    form \(\epsilon(f_1,\dots,f_N)\) with \(f_1,\dots,f_N\) simple functions on \(R^m\) and \(\epsilon:\{1,\dots,N\}^2\to\{-1,0,1\}\).
    We have just proved that if \(S\subseteq R^{m+1}\) is simple, then its image under the projection map
    \begin{equation*}
(x_1,\dots,x_m,x_{m+1})\mapsto(x_1,\dots,x_m):R^{m+1}\to R^m
    \end{equation*}
    is simple in \(R^m\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The subsets of \(R^m\) that are definable in \((R,<)\) using constants are exactly the finite
    unions of simple sets in \(R^m\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\cals_m\) be the collection of finite unions of simple sets in \(R^m\). Clearly \(\cals_m\) is a
    boolean algebra of subsets of \(R^m\), and each set in \(\cals_m\) is definable in \((R,<)\) using
    constants. Texts above show that \(\cals:=(\cals_m)_{m\in\N}\) is a structure on the set \(R\), hence the
    sets in \(\cals_m\) are exactly the subsets of \(R^m\) definable in \((R,<)\) using constants
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The model-theoretic structure \((R,<)\) is o-minimal
    #+END_corollary
** Semilinear sets
    In this section we show that the sets definable using constants in an ordered vector space over
    an ordered field are exactly the semilinear sets.

    definition
* Semialgebriac sets
** Thom's lemma and continuity of roots
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\alpha\in\C\) be a zero of the monic polynomial
    \begin{equation*}
    a_0+a_1T+\dots+a_{d-1}T^{d-1}+T^d\in\C[T],d\ge 1
    \end{equation*}
    Then \(\abs{\alpha}\le 1+\max\{\abs{a_i}:i=0,\dots,d-1\}\)
    #+END_lemma

    #+BEGIN_proof
    Put \(M:=\max\{\abs{a_i}:i=0,\dots,d-1\}\) and suppose \(\alpha>1+M\). Then
    \(\abs{a_0+a_1\alpha+\dots+a^{d-1}\alpha^{d-1}}\le M(1+abs{\alpha}+\dots+\abs{\alpha}^{d-1})=M(\abs{\alpha}^d-1)/(\abs{\alpha}-1)<\abs{\alpha}^d\),
    contradicting \(0=\abs{f(\alpha)}\)
    #+END_proof

    #+ATTR_LATEX: :options [Thom]
    #+BEGIN_lemma
    Let \(f_1,\dots,f_k\in\R[T]\) be nonzero polynomials s.t. if \(f_i'\neq 0\), then \(f_i'\in\{f_1,\dots,f_k\}\).
    Let \(\epsilon:\{1,\dots,k\}\to\{-1,0,1\}\), and put
    \begin{equation*}
    A_\epsilon:=\{t\in\R:\sgn(f_i(t))=\epsilon(i),i=1,\dots,k\}\subseteq\R
    \end{equation*}
    Then \(A_\epsilon\) is empty, a point, or an interval. If \(A_\epsilon\neq\emptyset\), then its closure is given by
    \begin{equation*}
    \cl(A_\epsilon)=\{t\in\R:\sgn(f_i(t))\in\{\epsilon(i),0\},i=1,\dots,k\}
    \end{equation*}
    If \(A_\epsilon=\emptyset\), then \(\{t\in\R:\sgn(f_i(t))\in\{\epsilon(i),0\},i=1,\dots,k\}\) is empty or a point
    #+END_lemma

    We call \epsilon a *sign condition* for \(f_1,\dots,f_k\). The \(3^k\) possible sign conditions \epsilon
    determine \(3^K\) disjoint sets \(A_\epsilon\), which together cover the real line \(\R\). The second
    statement of the lemma says that for nonempty \(A_\epsilon\) its closure can be obtained by relaxing
    all strict inequalities to weak inequalities

    #+BEGIN_proof
    By induction on \(k\). The lemma holds trivially for \(k=0\). Let \(f_1,\dots,f_k,f_{k+1}\in\R[T]-\{0\}\)
    be polynomials s.t. if \(f_i'\neq 0\), then \(f_i'\in\{f_1,\dots,f_{k+1}\}\). We may assume
    that \(\deg(f_{k+1})=\max\{\deg(f_i):1\le i\le k+1\}\). Let \(\epsilon':\{1,\dots,k+1\}\to\{-1,0,1\}\), and let \epsilon be the
    restriction of \(\epsilon'\) to \(\{1,\dots,k\}\). By the inductive hypothesis, \(A_\epsilon\) is empty, a point or
    an interval. It \(A_\epsilon\) is empty or a point, so
    is \(A_{\epsilon'}=A_\epsilon\cap\{t\in\R:\sgn(f_{k+1}(t))=\epsilon'(k+1)\}\), and the other properties to be checked in this
    case follow easily from the inductive hypothesis on \(A_\epsilon\)

    Suppose \(A_\epsilon\) is an interval. Since \(f_{k+1}'\) has a constant sign on \(A_\epsilon\), the
    function \(f_{k+1}\) is either strictly monotone on \(A_\epsilon\), or constant. In both cases, it is
    routine to check that \(A_{\epsilon'}=A_\epsilon\cap\{t\in\R:\sgn(f_{k+1}(t))=\epsilon'(k+1)\}\) has the required properties
    #+END_proof

    #+ATTR_LATEX: :options [Continuity of roots]
    #+BEGIN_lemma
    Let \(f(T)=a_0+a_1+\dots+a_dT^d\in\C[T]\) be a polynomial that has no zero on the boundary
    circle \(\abs{z-c}=r\) of a given open disc \(\abs{z-c}<r\) in the complex plane \((c\in\C,r>0)\).
    Then there is \(\epsilon>0\) s.t. if \(\abs{a_i-b_i}\le\epsilon\) for \(i=0,\dots,d\)
    then \(g(T):=b_0+b_1T+\dots+b_dT_d\in\C[T]\) also has no zero on the circle, and \(f\) and \(g\) have
    the same number of zeros in the disc
    #+END_lemma
* Cell Decomposition
    Fix an arbitrary o-minimal structure \((R,<,\cals)\). Instead of saying that a set \(A\subseteq R^m\) belongs
    to \(\cals\), we say that \(A\) is definable
** The monotonicity theorem and the finiteness lemma
    #+ATTR_LATEX: :options [Monotonicity theorem]
    #+BEGIN_theorem
    Let \(f:(a,b)\to R\) be a definable function on the interval \((a,b)\). Then there are
    points \(a_1<\dots<a_k\) in \((a,b)\) s.t. on each subinterval \((a_j,a_{j+1})\)
    with \(a_0=a\), \(a_{k+1}=b\), the function is either constant, or strictly monotone and continuous
    #+END_theorem


    We derive this from the threes below. In these lemmas we consider a definable
    function \(f:I\to R\) on an interval \(I\)
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.1
    There is a subinterval of \(I\) on which \(f\) is constant or injective
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.2
    If \(f\) is injective, then \(f\) is strictly monotone on a subinterval of \(I\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.1.3
    If \(f\) is strictly monotone, then \(f\) is continuous on a subinterval of \(I\)
    #+END_lemma

    These lemmas imply the monotonicity theorem as follows:

    Let
    \begin{align*}
    X:=\{x\in(a,b):&\text{on some subinterval of $(a,b)$ containing $x$ the function $f$}\\
    &\text{is either constant, or strictly monotonicity and continuous}\}
    \end{align*}
    Now \((a,b)-X\) must be finite, since otherwise it would contain an interval \(I\); applying
    successively lemmas ref:3.1.1, ref:3.1.2, ref:3.1.3 we can make \(I\) so small that \(f\) is
    either constant, or strictly monotone and continuous on \(I\). But then \(I\subseteq X\), a
    contradiction <<Problem1>>

    Since \((a,b)-X\) is finite, we can reduce the proof of the theorem to the case
    that \((a,b)=X\), by replacing \((a,b)\) by each of the finitely many intervals of which the
    open set \(X\) consists. In particular, we may assume that \(f\) is continuous. By splitting
    up \((a,b)\) further we can reduce to one of the following three cases

    Case 1. For all \(x\in(a,b)\), \(f\) is constant on some neighborhood of \(x\)

    Case 2. For all \(x\in(a,b)\), \(f\) is strictly increasing on some neighborhood of \(x\)

    Case 3. For all \(x\in(a,b)\), \(f\) is strictly decreasing on some neighborhood of \(x\)

    Case 1. Take \(x_0\in(a,b)\) and put
    \begin{equation*}
    s:=\sup\{x:x_0<x<b,f\text{ is constant on }[x_0,x)\}
    \end{equation*}
    Then \(s=b\), since \(s<b\) implies that \(f\) is constant on some neighborhood of \(s\),
    contradiction. From \(s=b\) it follows that \(f\) is constant on \([x_0,b)\). Similarly we prove
    that \(f\) is constant on \((a,x_0]\), therefore \(f\) is constant on \((a,b)\)

    Case 2. Take \(x_0\in(a,b)\) and put
    \begin{equation*}
    s:=\sup\{x:x_0<x<b,f\text{ is strictly increasing on }[x_0,x)\}
    \end{equation*}
    Then \(s=b\), since \(s<b\) leads to a contradiction

    We now prove the lemmas

    #+ATTR_LATEX: :options [Proof of Lemma \ref{3.1.1}]
    #+BEGIN_proof
    If some \(y\in R\) had infinite preimage \(f^{-1}(y)\), then this preimage would contain a
    subinterval of \(I\) and \(f\) would take the constant value \(y\) on that subinterval. So we
    may assume that each \(y\in R\) has finite preimage. Then \(f(I)\) is infinite, and so contains an
    interval \(J\). Define an "inverse" \(g:J\to I\) by
    \begin{equation*}
    g(y):=\min\{x\in I:f(x)=y\}
    \end{equation*}
    Since \(g\) is injective by definition, \(g(J)\) is infinite, and hence \(g(J)\) contains a
    subinterval of \(I\), and \(f\) is necessarily injective on this subinterval

    If \(x_1,x_2\in J'\subseteq g(J)\), \(x_i=g(y_i)\), \(f(x_1)=f(x_2)\Rightarrow y_1=y_2\Rightarrow x_1=x_2\) and \(f\) is injective
    #+END_proof
    Fix \(f:I\to R\), \(a\in I\),  \(\Phi_{-+}(a)\) means \(\exists\epsilon\) s.t. if \(x\in(a-\epsilon,a)\) then \(f(x)<f(a)\),
    and if \(x\in(a,a+\epsilon)\) then \(f(x)>f(a)\). "locally increasing"

    \(\Phi_{+-}(a)\), \(\Phi_{++}(a)\), \(\Phi_{--}\) is similar

    \(\Phi_{00}(a)\), \(\exists\epsilon\), \(x\in(a-\epsilon,a+\epsilon)\Rightarrow f\) is increasing

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(a\in slbd(D)\) if \((a-\epsilon,a)\cap D=\emptyset\), \((a,a+\epsilon)\subseteq D\), strong left boundary
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(X,Y\subseteq R\), \(\abs{X}=\abs{Y}=\infty\), \(X<Y\), if \(D\subseteq R\), \(X\cap D=\emptyset\), \(Y\subseteq D\)
    then \(\exists a\in slbd(D)\), \(X\le a\le Y\)
    #+END_fact


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(\Phi_{-+}(a)\), \(\forall a\in I\), then \(f\) is increasing
    #+END_lemma

    #+BEGIN_proof
    suppose \(a,b\in I\), \(a<b\), \(f(a)\ge f(b)\). there is \epsilon s.t.
    if \(x\in(a,a+\epsilon)\) then \(f(x)>f(a)\), and if \(x\in(b-\epsilon,b)\), \(f(x)<f(b)\le f(a)\).

    \(D=\{x:f(x)\le f(a)\}\), \((a,a+\epsilon)\cap D=\emptyset\), \((b-\epsilon,b)\subseteq D\), then \(\exists c\in slbd(D)\), \(c-\delta,c\cap D=\emptyset\)
    and \((c,c+\delta)\subseteq D\), so \(\Phi_{-+}(c)\) is false
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(\forall a\in I\), \(\Phi_{+-}(a)\), then \(f\) is decreasing
    2. If \(\forall a\in I\),  \(\Phi_{00}(a)\), then \(f\) is constant
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(f:I\to R\) injective, \(a\in I\), then \(\Phi_{++}(a)\) or \(\Phi_{+-}(a)\) or \(\Phi_{-+}(a)\) or \(\Phi_{--}(a)\)
    #+END_lemma

    if \(f\) is not injective, then there may be 9 cases

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(D\subseteq R\) definable, \(a\in R\), then there is \epsilon s.t. \((a,a+\epsilon)\subseteq D\) or \((a,a+\epsilon)\cap D=\emptyset\) and
    \((a-\epsilon,a)\subseteq D\) or \((a-\epsilon,a)\cap D=\emptyset\)
    #+END_fact

    #+BEGIN_proof
    Let \(D=\{x\in I:f(x)>f(a)\}\), then the fact gives 4 cases
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:w3.4
    If \(f:I\to R\) is definable
    1. It can't be that: \(\forall a\in I\), \(\Phi_{++}(a)\)
    2. It can't be that: \(\forall a\in I\), \(\Phi_{--}(a)\)
    #+END_lemma

    #+BEGIN_proof
    1. Assume \(\forall x\Phi_{++}(x)\)

       \(\Psi_{+-}(a)\Leftrightarrow\exists y,\epsilon\), if \(x\in(a-\epsilon,a)\), then \(f(x)>y\), \(x\in (a,a+\epsilon), f(x)<y\)

        Let \(I=(a,b)\), \(S=\{x\in I\mid \exists x'\in I, x'>x,f(x')<f(x)\}\)

        *Case 1*: \((\exists \epsilon)(b-\epsilon,b)\cap S=\emptyset\). Then on the interval \((b-\epsilon,b)\), \(f\) is
        increasing, \(\Phi_{++}(x)\) doesn't hold

        *Case 2*: \((\exists\epsilon)(b-\epsilon,b)\subseteq S\)

        Take \(x_0\in(b-\epsilon,b)\), \(x_0\in S\), and we could get a decreasing sequence

        Let \(D=\{x\in I:f(x)>f(x_0)\}\). So there are infinitely many points \(<x_0\) in \(D\), and
       infinitely many points \(>x_0\) not in \(D\)

       \(\exists c\) s.t. \((c-\epsilon,c)\subseteq D\), \((c,c+\epsilon)\cap D=\emptyset\). So \(\Psi_{+-}(c)\) is true
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\exists J\subseteq I\), \(\forall x\in J\), \(\Psi_{+-}(x)\),
    #+END_lemma

    #+BEGIN_proof
    \(S=\{x\in I:\Psi_{+-}(x)\}\). If \(S\) is finite, replace \(I\) with \(I'\subseteq I\setminus S\), replace \(f\)
    with \(f|_{I'}\), apply previous lemma, get \(c\in I'\), \(\Psi_{+-}(c)\), a contradiction
    #+END_proof

    Similarly,     \(\exists J\subseteq I\), \(\forall x\in J\), \(\Psi_{-+}(x)\)

    Combine these, get \(I\supseteq I'\supseteq I''\), \(\forall x\in I'\), \(\Psi_{+-}(x)\), and \(\forall x\in I''\), \(\Psi_{+-}(x)\), a contradiction

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:w3.5
    If \(f:I\to R\), \(\exists a\in I\), \(\Phi_{-+}(a)\) or \(\Phi_{+-}(a)\) or \(\Phi_{00}(a)\)
    #+END_lemma

    #+BEGIN_proof
    By Lemma ref:3.1.1, there is \(J\subseteq I\), if \(f|_J\) is constant, then we are done.

    If \(f|_J\) is injective, let \(S_{+-}=\{a\in J,\Phi_{+-}(a)\}\) and other sets
    similarly. \(J=S_{+-}\cup S_{++}\cup S_{-+}\cup S_{--}\). If \(\abs{S_{++}}=\infty\), there
    is \(I'\subseteq S_{++}\), a contradiction. Therefore \(S_{--}\) and \(S_{++}\) are finite. But \(\abs{J}\)
    is infinite, so \(S_{+-}\) or \(S_{-+}\) is nonempty
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:w3.6
    \(f:I\to R\), \(\exists c_0<c_1<\dots<c_n\), \(I=(c_0,c_n)\), \(f|_{(c_i,c_{i+1})}\) is constant or decreasing
    or increasing
    #+END_lemma

    #+BEGIN_proof
    Let \(E=I\setminus(S_{+-}\cup S_{-+}\cup S_{00})\). If \(\abs{E}=\infty\), then \(J\subseteq E\)
    and \(f|_E\) contradicts ref:w3.5.
    Take \(\{c_0,\dots,c_n\}\supseteq E\cup bd(I)\cup bd(S_{+-})\cup bd(S_{-+})\cup bd(S_{00})\).

    So all the sets respect the partition
    \begin{equation*}
    (c_0,c_1),\{c_1\},(c_1,c_2),\dots,(c_{n-1},c_n)
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:w3.7
    If \(f:I\to R\) definable and \(S=\{x\in I:f\text{ is not continuous at }x\}\), then \(S\) is finite
    #+END_lemma

    #+BEGIN_proof
    \(S\) is definable. If \(\abs{S}=\infty\), take \(J\subseteq S\), replace \(f\) with \(f|_J\), we may
    assume \(f\) is nowhere continuous. By Lemma ref:w3.6, there is \(J\subseteq I\), \(f|_J\) is constant
    or monotone. Replace \(f\) with \(f|_J\), now \(f\) is monotone (constant is continuous).
    Assume \(f\) is increasing, then \(f\) is injective, \(\abs{f(I)}=\infty\),
    take \(J\subseteq f(I)\), \([c,d]\subseteq f(I)\), \(c=f(a)\), \(d=f(b)\), \(x\in(a,b)\Rightarrow f(x)\in(c,d)\). \(f\) is
    strictly increasing. if \(y\in(c,d)\subseteq f(I)\), so \(\exists x\in I\), \(y=f(x)\), therefore \(f\) is
    surjective. Also \(f\) is order-preserving, thus \(f\) is continuous on \((a,b)\) (since we are
    using order to define the topology). But \(f\) is continuous at nowhere, so a contradiction
    #+END_proof

    Then the monotonicity theorem follows from the proof of Lemma ref:w3.6 (modify the boundary to
    include the discontinuous points)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(f:(a,b)\to R\) definable, \(\lim_{x\to a^+}f(x)\) exists in \(R_{\infty}\)
    #+END_corollary

    #+BEGIN_proof
    1. Take \epsilon, \(f|_{a,a+\epsilon}\) is continuous and monotone. Then \(\lim_{x\to a^+}f(x)\)
       is \(\sup\{f(x):x\in(a,a+\epsilon)\}\) or \(\inf\{f(x):x\in(a,a+\epsilon)\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(f:[a,b]\to R\) is definable and continuous, then \(\max_{x\in[a,b]f(x)}\)
    and \(\min_{x\in[a,b]}f(x)\) exist
    #+END_corollary

    #+BEGIN_proof
    Take maximum for each piece and combine
    #+END_proof

    *Uniform Finiteness*

    Suppose \(D\subseteq R^n\times R\), for \(\bara\in R^n\), \(D_{\bara}=\{y\in R:(a,y\}\in D\)

    #+ATTR_LATEX: :options [Uniform Finitness]
    #+BEGIN_theorem
    Suppose \(\forall\bara\), \(\abs{D_{\bara}<\infty}\). Then \(\exists N<\infty\forall\bara\abs{D_{\bara}}<N\)
    #+END_theorem

    For now, consider \(n=1\).

    Fix \(D\subseteq R^2\) definable, \(\abs{D_a}<\infty\) for all \(a\in R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((a,b)\subseteq R\times R_{\infty}\) is *normal* if either
    * \((a,b)\notin\cl(D)\), \((\exists \epsilon)(a-\epsilon,a+\epsilon)\times(b-\epsilon,b+\epsilon)\cap D=\emptyset\)
    * \((a,b)\in D\) and \((\exists\epsilon,\delta)D\cap(a-\epsilon,a+\epsilon)\times(b-\delta,b+\delta)\) is \(\Gamma(f)\) for some continuous
      function \(f\)

    Otherwise \((a,b)\) is abnormal
    #+END_definition

    #+BEGIN_remark
    \(\{(x,y)\text{ normal}\}\) is open, \(\{(x,y)\text{ abnormal}\}\) is closed.
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(a\in R\) is *good* if \(\forall b\in R_\infty\), \((a,b)\) is normal, is *bad* if \(\exists b\in R_\infty\), \((a,b)\) is abnormal
    #+END_definition

    This is a definable definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\{x\in R:x\text{ is bad}\}\) is finite
    #+END_lemma

    #+BEGIN_proof
    Otherwise, take \(I\subseteq B\), \(\forall x\in I\), \(\{y\in R_\infty:(x,y)\text{ abnormal}\}\) is closed, nonempty.

    Let \(f(x)=\min\{y\in R_\infty:(x,y)\text{ abnormal}\}\), \(f:I\to R_\infty\) definable.

    \(\forall x\), break into cases based on these questions
    - \(f(x)=-\infty\) vs \(f(x)\in R\) vs \(f(x)=+\infty\)
    - \((x,f(x))\in D\) vs not
    - whether \(\exists y>f(x)\), \((x,y)\in D\)
    - whether \(\exists y<f(x)\), \((x,y)\in D\)

    So 24 pieces

    Shrink \(I\) to make all the answers constant

    Assume \(\forall x\in I\), \(f(x)\in R\), \((x,f(x))\in D\), \((\exists y<f(x))(x,y)\in D\), \((\exists z>f(x))(x,z)\in D\)

    Let \(g(x)=\max\{y:y<f(x), (x,y)\in D\}\), \(h(x)=\min\{y:y>f(x),(x,y)\in D\}\)

    \(D_x\) is finite and we can take the min and max

    For each \(x\in I\), \((x,f(x))\in D\), \((x,f(x))\) is abnormal, if \(f(x)<y<h(x)\),
    then \((x,y)\notin D\)

    Idea: apply monotonicity theorem, get \(f,g,h\) continuous, then \((x,f(x))\) is normal

    Use monotonicity theorem to get \(J\subseteq I\), \(f|_J,g|_J,h|_J\) are continuous

    Take \(a\in J\), \((a,f(a))\in D\), \((a,f(a))\) is normal. Take \epsilon
    s.t. \(g(a)+\epsilon<f(a)-\epsilon\), \(f(a)+\epsilon<h(a)-\epsilon\). Take \delta s.t. if \(\abs{x-a}<\delta\)
    then \(\abs{f(x)-f(a)}<\epsilon\), same for \(g,h\)

    If \(x\in(a-\epsilon,a+\epsilon)\), then \((x,f(x))\in D\), \((a-\delta,a+\delta)\times(f(a)-\epsilon,f(a)+\epsilon)\cap D\)
    is \(\Gamma(f|_{(a-\delta,a+\delta)})\)

    if \((x,y)\in D\) and \(x\in(a-\delta,a+\delta)\), \(y\in(f(a)-\epsilon,f(a)+\epsilon)\) then \(y=f(x)\) or else \(y\neq f(x)\),
    then \(y\in D_x\), so either \(y\ge h(x)\) or \(y\le g(x)\). But \(\abs{x-a}<\delta\), \(\abs{h(x)-h(a)}<\epsilon\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(I\subseteq R\) and \(\forall x\in I\), \(x\) is good, then \(\exists n<\infty\), \(\forall a\in I\), \(\abs{D_a}=n\)
    #+END_lemma

    #+BEGIN_proof
    Take \(a_0\in I\), let \(n=\abs{D_{a_0}}<\infty\).

    Let \(S=\{a\in I:\abs{D_a}=n\}\).

    Goal: \(S\) and \(I\setminus S\) are open.

    This is sufficient because o-minimality shows intervals are definably connected. \(I\neq X\cup Y\)
    where \(X,Y\) are disjoint, nonempty, definable and open. So if \(I=X\cup Y\), \(X\cap Y=\emptyset\), \(X,Y\)
    definable open, then one of them is empty

    Let \(S_n=\{a\in I:\abs{D_a}\}=n\), \(S=S_n\)

    Goal: each \(S_n\) is open. Then \(I\setminus S_n\) and \(S_n\) are open

    Idea: \(I\to\N\), \(a\mapsto\abs{D_a}\) is locally constant

    Fix \(a\in I\), let \(n=\abs{D_a}\), \(D_a=\{b_1,\dots,b_n\}\), \(b_1<\dots<b_n\). Since \(a\) is good,
    so \((a,b_i)\) is normal. Take \epsilon, \delta small enough, then \((a-\delta,a+\delta)\times(b_i-\epsilon,b_i+\epsilon)\cap D\) is a graph of
    a continuous function \(f_i:(a-\delta,a+\delta)\to R\). Take \epsilon small enough s.t. \(b_i+\epsilon<b_{i+1}-\epsilon\).
    If \(x\in(a-\delta,a+\delta)\), then \((f_1(a),\dots,f_n(a))\subseteq D_x\), then \(\abs{D_x}\ge n\).

    Suppose \(\abs{D_x}\ge n\), if \((a-\delta,a+\delta)\subseteq S_n\), then we are done. Otherwise, by
    o-minimality, \((a,a+\delta')\cap S_n=\empty\) or \((a-\delta',a)\cap S_n=\emptyset\).

    Shrinking \(\delta',\delta\) we can assume \(\delta=\delta'\). WLOG, \(a<x<a+\delta\), \(x\notin S_n\).

    Let \(g(x)=\min D_x\setminus\{f_1(x),\dots,f_n(x)\}\). By monotonicity theorem, \(\lim_{x\to a^+}g(x)=:c\in R_\infty\)

    \((a,c)\) is normal because \(a\) is good.

    \((a,c)=\lim_{x\to a^+}(x,g(\abs{x}))\) , so \((a,c)\in\cl(D)\). Because \((a,c)\) is
    normal, \((a,c)\in D\) and \(D\) looks like \(\Gamma(h)\) around \((a,c)\).
    #+END_proof

    #+ATTR_LATEX: :options [Proof of uniform boundedness]
    #+BEGIN_proof
    Let \(b_1,\dots,b_n\) be the bad points.
    \begin{equation*}
    (-\infty,b_1),(b_1,b_2),\dots,(b_{n-1},b_n),(b_n,+\infty)
    \end{equation*}
    and \(\abs{D_a}\) is constant on each intervals
    #+END_proof





** The cell decomposition theorem
    for each definable set \(X\) in \(R^m\) we put
    \begin{align*}
    C(X)&:=\{f:X\to R:f\text{ definable and continuous}\}\\
    C_\infty(X)&:=C(X)\cup\{-\infty,+\infty\}
    \end{align*}
    where we regard \(-\infty\) and \(+\infty\) as constant functions on \(X\)

    For \(f,g\in C_\infty(X)\) we write \(f<g\) if \(f(x)<g(x)\) for all \(x\in X\), and in this case we put
    \begin{equation*}
    (f,g)_X:=\{(x,r)\in X\times R:f(x)<r<g(x)\}
    \end{equation*}
    So \((f,g)_X\) is a definable subset of \(R^{m+1}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((i_1,\dots,i_m)\) be a sequence of zeros and ones of length \(m\). An *\((i_1,\dots,i_m)\)-cell* is a
    definable subset of \(R^m\) obtained by induction on \(m\) as follows:
    1. a \((0)\)-cell is a one-element set \(\{r\}\subseteq R\), a \((1)\)-cell is an
       interval \((a,b)\subseteq R\)
    2. suppose \((i_1,\dots,i_m)\)-cells are already defined, then an \((i_1,\dots,i_m,0)\)-cell is the
       graph \(\Gamma(f)\) of a function \(f\in C(X)\), where \(X\) is an \((i_1,\dots,i_m)\)-cell; further,
       an \((i_1,\dots,i_m,1)\)-cell is a set \((f,g)_X\) where \(X\) is an \((i_1,\dots,i_m)\)-cell
       and \(f,g\in C_\infty(X)\), \(f<g\)
    #+END_definition

    So a \((0,0)\)-cell is a "point" \(\{(r,s)\}\subseteq R^2\), a \((0,1)\)-cell is an "interval" on a
    vertical line \(\{a\}\times R\), and a \((1,0)\)-cell is the graph of a continuous definable function
    defined on an interval.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *cell in* \(R^m\) is an \((i_1,\dots,i_m)\)-cell for some (necessarily unique)
    sequence \((i_1,\dots,i_m)\). Since the \((1,\dots,1)\)-cells are exactly the cells which are open in
    their ambient space \(R^m\), we call these *open cells*
    #+END_definition

    The non-open cells are "thin":

    The union of finitely many non-open cells in \(R^m\) has empty interior

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Each cell is locally closed, i.e., open in its closure
    #+END_proposition

    #+BEGIN_proof
    Let \(C\subseteq R^{m+1}\) be a cell. Put \(B:=\pi(C)\subseteq R^m\) and assume inductively that the cell \(B\) is
    open in its closure \(\cl(B)\), so that \(\cl(B)-B\) is a closed set. If \(C=\Gamma(f)\)
    with \(f:B\to R\) a definable continuous function, then \(\cl(C)-C\) is contained
    in \((\cl(B)-B)\times R\), hence \(C\) is open in the closed set \(C\cup((\cl(B)- B)\times R)\)  <<Problem1>>

    If \(C=(f,g)\) with \(f,g:B\to R\) definable continuous functions on \(B\), \(f<g\), then one
    verifies that \(\cl(C)-C\subseteq\Gamma(f)\cup\Gamma(g)\cup((\cl(B)-B)\times R)\) and that \(C\) is open in the closed set
    \(C\cup\Gamma(f)\cup\Gamma(g)\cup((\cl(B)-B)\times R)\)
    #+END_proof

    we consider the point-space \(R^0\) as a cell, or ()-cell, where () is the sequence of length 0

    Each cell is homeomorphic under a coordinate projection to an open cell. We now make this
    explicit. Let \(i=(i_1,\dots,i_m)\) be a sequence of zeros and ones

    Define \(p_i:R^m\to R^k\) as follows: let \(\lambda(1)<\dots<\lambda(k)\) be the indices \(\lambda\in\{1,\dots,m\}\) for
    which \(i_\lambda=1\), so that \(k=i_1+\dots+i_m\); then
    \begin{equation*}
    p_i(x_1,\dots,x_m):=(x_{\lambda(1),\dots,x_{\lambda(k)}})
    \end{equation*}
    It is easy to show by induction on \(m\) that \(p_i\) maps each \(i\)-cell \(A\) homeomorphically
    onto an open cell \(p_i(A)\) in \(R^k\). We denote \(p_i(A)\) also by \(p(A)\) and the
    homeomorphism \(p_i|A:A\to p(A)\) by \(p_A\). Clearly \(p_A=\id_A\) if \(A\) is an open cell

    If \(A\) is a cell in \(R^{m+1}\) then \(\pi(A)\) is a cell in \(R^m\), where \(\pi:R^{m+1}\to R^m\) is
    the projection on the first \(m\) coordinates. Here is a simple application of this fact

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Each cell is definably connected
    #+END_proposition

    #+BEGIN_proof
    For intervals and points this is stated in ref:1.3.6

    If \(A\) is a cell in \(R^{m+1}\), then we assume inductively that the cell \(\pi(A)\) in \(R^m\)
    is definably connected and use the fact that each fiber \(\pi^{-1}(x)\cap A\) is definably connected
    #+END_proof

    #+ATTR_LATEX: :options [Cell decomposition]
    #+BEGIN_theorem
    If \(X\subseteq R^m\) is definable, then \(\exists C_1,\dots,C_n\) cells, \(X=\bigcup_{i=1}^nC_i\), \(C_i\cap C_j=\emptyset\)
    for \(i\neq j\).
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    In \((\R,+,0,\le,0,1)\), \(X=\{(x,y):x^2+y^2\le 1\}\) is a \((1,1)\)-cell
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any \(m\in\N\),
    1. (\(Cell_m\)): any definable \(A\subseteq R^m\) has a cell decomposition. \(A=\bigcup_{i=1}^nC_i\)
    2. (\(Con_m\)): if \(f:A\to R\) definable, then \(\exists\) cell decomposition \(A=\bigcup_{i=1}^nC_i\)
       s.t. \(f|_{C_i}\) is continuous for all \(i\)
    3. (\(Fin_m\)): if \(A\subseteq R^m\times R\) definable, and if \(A_{\barx}=\{y\in R:(\barx,y)\in A\}\) is finite
       \(\forall\barx\in R^m\), then \(\exists N\in\N\), \(\forall\barx\in R^m\), \(\abs{A_{\barx}}\le N\).
    #+END_theorem

    Proof stragegy: Cell\textsubscript{1}, Con\textsubscript{1}, Fin\textsubscript{1},
    Cell\textsubscript{2}, Con\textsubscript{2}, Fin\textsubscript{2}, and so on.

    (Cell\textsubscript{1}) is the definition of o-minimality.

    (Con\textsubscript{1}) is the monotonicity theorem.

    (Fin\textsubscript{1}) is the uniform finiteness part 1.

    Suppose \(m>1\), take \(m=2\) for simplicity.

    If \(D\subseteq R\) definable, and \(\tbd(D)=\{x_1,\dots,x_n\}\), \(x_1<\dots<x_n\), then \(D\) is the union of some
    of
    \begin{equation*}
    c_0:=(-\infty,x_1),c_1:=\{x_1\},c_2:=(x_1,x_2),\dots,c_{2n-1}:=\{x_n\},c_{2n}:=(x_n,+\infty)
    \end{equation*}
    The "shape" of \(D\) is the string \((j_0,\dots,j_{2n})\) where \(j_i=1\) if \(C_i\subseteq D\) and 0
    if \(C_i\cap D=\emptyset\)

    (Cell\textsubscript{2}): Fix definable \(A\subseteq R^2\), \(A_x=\{y\in R:(x,y)\in A\}\), \(\tbd(A_x)\) is finite
    for all \(x\in R\). By (Fin\textsubscript{1}), \(\exists N\in\N\) s.t. \(\forall x\), \(\abs{\tbd(A_x)}\le N\),
    then \(\{shape(A_x):x\in R\}\) is finite.
    \(\{x\in R:shape(A_x)=0011001\}\) is definable.

    By (Cell\textsubscript{1}), can partition \(R\) into cells \(C_1,\dots,C_n\) s.t. \(shape(A_x)\) is a
    constant for \(x\in C_i\).

    Let \(f_i(x)\) be the \(i\)th smallest element of \(\tbd(A_x)\), then \(f\) is definable. We can
    further partition and WMA \(f_1,\dots,f_N\) is continuous on \(C_1,\dots,C_n\) using
    (Con\textsubscript{1}).

    (Con\textsubscript{2}):
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(B\subseteq R^2\) is a box and \(f:B\to R\) is continuous in each variable separately and monotone in
    each variable separately, then \(f\) is continuous.
    #+END_lemma

    #+BEGIN_proof
    WLOG, \(f\) is increasing in each variable.

    Fix \((x,y)\in B\), \(\epsilon>0\), \(\exists\delta_1>0\) s.t. \(f(x+\delta_1,y)<f(x,y)+\epsilon\). \(\exists\delta_2>0\)
    s.t. \(f(x,y+\delta_2)<f(x,y)+\epsilon\).

    \(\exists\delta_3,\delta_4>0\), \(f(x-\delta_3,y-\delta_4)>f(x,y)-\epsilon\).

    If \(x'\in(x-\delta_3,x+\delta_4)\) and \(y'\in(y-\delta_4,y+\delta_2)\), then
    \begin{equation*}
    f(x,y)-\epsilon<\dots<f(x',y')<f(x+\delta_1,y+\delta_2)<f(x,y)+\epsilon
    \end{equation*}
    #+END_proof

    For \(x\in A\) ask questions:
    - is \(f\) continuous at \(x\)
    - is \(f\) continuous in first variable at \(x\)
    - is \(f\) continuous in second variable at \(x\)
    - is \(f\) increasing in first variable
    - is \(f\) decreasing in first variable
    - increasing in second
    - decreasing in second
    By (Cell\textsubscript{2}), \(A=\bigcup_{i=1}^nC_i\), answers are constant on each \(C_i\). Fix \(C=C_i\)
    - if \(f\) is continuous \(\forall x\in C\), then \(f|_C\) is continuous
    - if \(C\) is not a \((1,1)\)-cell, then there is a coordinate projection \(\pi:R^2\to R\)
      s.t. \(C\to\pi(C)\) is a bijection, \(\pi(C)\) is a cell. \(C\to\pi(C)\) is a homeomorphism, subcells
      of \(C\) corresponds to subcells of \(\pi(C)\)

      (Con\textsubscript{1}) on \(\pi(C)\) implies (Con\textsubscript{2}) on \(C\) by homeomorphism.
    - \(C\) is a \((1,1)\)-cell, \(f\) is continuous nowhere on \(C\). Take \((a,b)\in C\), look
      at \(f(x,b)\) for \(x\in(a-\epsilon,a+\epsilon)\). Apply monotonicity theorem, get \(a'\) s.t. \(f\)
      at \((a',b)\) is continuous and monotone in \(x\), then \(f\) is continuous and monotone in
      1st coordinate everywhere in \(C\). Similary, \(f\) is cts & monotone in 2nd coordinate. By
      the lemma, \(f\) is continuous,

    Fix \(A\subseteq R^2\times R\), \(\abs{A_{(x,y)}<\infty}\) for any \(x,y\in R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((x,y,z)\in R^2\times R_{\infty}\) is *normal* if
    - locally, \(A\) is \(\emptyset\), \((x,y,z)\notin\cl(A)\), or
    - locally, \(A\) is \(\Gamma(f)\), \(f\) is continuous

    abnormal otherwise

    \((x,y)\) is *good* if \(\forall z\in R_{\infty}\), \((x,y,z)\) is normal. Bad otherwise
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(B\subseteq R^2\) is a box, then there is \((x,y)\in B\) s.t. \((x,y)\) is good.
    #+END_lemma

    #+BEGIN_proof
    Similar, use Con\textsubscript{2}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:ww2
    If \(B\subseteq R^2\) is a box and \(\forall(x,y)\in B\), \((x,y)\) is good, then \(\abs{A_{(x,y)}}\) is constant
    for \((x,y)\in B\)
    #+END_lemma

    #+BEGIN_proof
    Suppose \(B=I\times J\), fix \(a_0\in I\),
    let \(A'=\{(y,z):(a_0,y,z)\in A\}\), \(A'_y=A_{(a_0,y)}\). \(A'_y\) is finite for each \(y\).

    Check \(A'\) is good on \(J\). Every \(y\in J\) is good w.r.t. \(A'\).

    By the \(m=1\) version of lemma, \(\abs{A'_y}\) is constant for \(y\in J\)

    \(f(x,y)=\abs{A_{(x,y)}}\) doesn't depend on 2nd coordinate.

    Similary, \(f(x,y)\) is constant on 1st coordinate

    So \(f\) is constant on \(B\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(C\) is an open cell, \((1,1)\)-cell, and \(\forall(x,y)\in C\) is good, then \(\abs{A_{(x,y)}}\) is
    constant for \((x,y)\in C\)
    #+END_lemma

    #+BEGIN_proof
    Take \((x_0,y_0)\in C\), let \(n=\abs{A_{(x_0,y_0)}}\), let \(D=\{(x,y)\in C:\abs{A_{(x,y)}=n}\}\).
    Using ref:ww2, can show that \(D\) is open, \(C\setminus D\) open

    But \(C\) is definably connected

    \begin{equation*}
    \chi_D(x)
    \begin{cases}
    1&x\in D\\
    0&x\notin D
    \end{cases}
    \end{equation*}
    want \(\chi_D\) constant in the cell.
    1. \(\chi_D(x,y)\) doesn't depend on \(y\), so \(\chi_D(x,y)=f(x)\)
    2. \(f(x)\) doesn't depend on \(x\)
    #+END_proof

    Proof of Fin\textsubscript{2}: Use (Cell\textsubscript{2}) to split \(R^2\)
    into \(R^2=\bigcup_{i=1}^nC_i\), where for \(i\), (normal is definable)
    1. \(\forall(x,y)\in C_i\), \((x,y)\) is good
    2. \(C_i\) is bad.
    We only need uniform finiteness above each \(C_i\)

    Fix \(C_i\)

    Case 1: \(C_i\) is a \((1,1)\)-cell, all the points in \(C_i\) is good.

    Case 2: \(C_i\) is not a \((1,1)\)-cell. Take a projection \(\pi\) s.t. \(\pi(C_i)\) is an cell.
    Uniform finiteness holds over \(\pi(C_i)\), then uniform finiteness holds over \(C_i\), transfering
    the definable bijection \(\pi\)

    \(R\) is o-minimal.
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(\varphi(\barx,y)\) is a formula and \(\abs{\varphi(\bara,M)}<\infty\) for all \(\bara\in R^m\), then \(\exists N<\infty\)
    s.t. \(\forall\bara\in R^m\), \(\abs{\varphi(\bara,M)}<N\)
    #+END_lemma

    #+BEGIN_remark
    If \(\varphi(\barx,y)\) a formula and we let \(\varphi'(\barx,y)\) be
    \begin{equation*}
    \forall z,w[z<y<w\to(\exists s:z<s<w\wedge\varphi(\barx,s))\wedge(\exists s:z<s<w\wedge\neg\varphi(\barx,s))]
    \end{equation*}
    Then \(\varphi'(\bara,R)\) is \(\tbd(\varphi(\bara,R))\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(R\equiv R'\) and \(R\) is o-minimal, then \(R'\) is o-minimal
    #+END_theorem

    #+BEGIN_proof
    If \(D\subseteq R'\) definable, (want \(D\) be the union of finite intervals)

    \(D=\varphi(\bara,R')\) for some \(\bara\in R'\). Let \(\varphi'(\barx,y)\) be the formula from the remark.

    \(\varphi'(\barb,R')=\tbd(\varphi(\barb,R'))\) for \(\barb\in(R')^m\), so
    \(\varphi'(\barb,R)=\tbd(\varphi(\barb,R))\) for all \(\barb\in R^m\).

    O-minimality \(\Rightarrow\) \(\abs{\varphi'(\barb,R)}<\infty\) for all \(\barb\in R^m\). Uniform finiteness gives \(N\)
    s.t. \(\forall \barb\in R^m\), \(\abs{\varphi'(\barb,R)}<N\), therefore \(\varphi'(\barb,R')\) is finite for
    all \(\barb\in(R')^m\). Take \(\barb=\bara\), therefore \(\tbd(D)\) is finite.

    *Claim*: In \(R'\), If \(y<z\) and \([y,z]\cap\tbd(D)\), then \(y\in D\Leftrightarrow z\in D\)

    /Proof/: True in \(R\) by o-minimality.
    \begin{equation*}
    R\vDash\forall\barx,y,z(y<z\wedge\neg\exists w(y\le w\le z\wedge\varphi'(\barx,w))\to[\varphi(\barx,y)\leftrightarrow\varphi(\barx,z)])
    \end{equation*}

    If \(\tbd(D)=\{c_1,\dots,c_m\}\), \(c_1<\dots<c_m\), the claim shows that \(D\) respects the partition
    of \(R'\).

    So \(D\) is a union of some points and intervals
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(T\) is o-minimal is every model of \(T\) is o-minimal
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\DLO\), \(\RCF\), \(\ODAG\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(\calm\) is o-minimal, then \(\Th(\calm)\) is o-minimal
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\calm\) is minimal if \(\forall\) definable \(D\subseteq M\), \(D\) is either finite or cofinite.
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\calm\) is strongly minimal if
    1. \(\calm\vDash T\) where \(T\) is strongly minimal, or
    2. \(\forall\caln\equiv\calm\), \(\caln\) is minimal.
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    \((\C,+,\cdot)\) is strongly minimal, \((\N,\le)\) is minimal but not strongly minimal
    #+END_fact

    Idea: strong o-minimality = o-minimality


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *decomposition* of \(R^m\) is a special kind of partition of \(R^m\) into finitely many cells. The
    definition is by induction on \(m\)
    1. a decomposition of \(R^1=R\) is a collection
       \begin{equation*}
       \{(-\infty,a_1),(a_1,a_2),\dots,(a_k,+\infty),\{a_1\},\dots,\{a_k\}\}
       \end{equation*}
       where \(a_1<\dots<a_k\) are points
    2. a decomposition of \(R^{m+1}\) is a finite partition of \(R^{m+1}\) into cells \(A\) s.t. the
       set of projections \(\pi(A)\) is a decomposition of \(R^m\)
    #+END_definition

    Let \(\cald=\{A(1),\dots,A(k)\}\) be a decomposition of \(R^m\), \(A(i)\neq A(j)\) if \(i\neq j\), and let for
    each \(i\in\{1,\dots,k\}\) functions \(f_{i1}<\dots<f_{in(i)}\) in \(C(A_i)\) be given

    Then
    \begin{equation*}
    \cald_i:=\{(-\infty,f_{i1}),(f_{i1},f_{i2}),\dots,(f_{in(i)},+\infty),\Gamma(f_{i1}),\dots,\Gamma(f_{in(i)})\}
    \end{equation*}
    is a partition of \(A(i)\times R\) and one easily checks that \(\cald^*:=\cald_1\cup\dots\cup\cald_k\) is a decomposition
    of \(R^{m+1}\), and that every decomposition of \(R^{m+1}\) arises in this way from a
    decomposition \(\cald\) of \(R^m\). We write \(\cald=\pi(\cald^*)\)

    A decomposition \(\cald\) of \(R^m\) is said to be *partition* a set \(S\subseteq R^m\) if each cell in \(\cald\) is
    either part of \(S\) or disjoint from \(S\), in other words, if \(S\) is a union of cells
    in \(\cald\).

    #+ATTR_LATEX: :options [Cell Decomposition Theorem]
    #+BEGIN_theorem
    1. \((\text{\rom{1}}_m)\)Given any definable sets \(A_1,\dots,A_k\subseteq R^m\) there is a decomposition of \(R^m\) partitioning
       each of \(A_1,\dots,A_k\)
    2. (\(\text{\rom{2}}_m\))For each definable function \(f:A\to R\), \(A\subseteq R^m\), there is a decomposition \(\cald\) of \(R^m\)
       partitioning \(A\) s.t. the restriction \(f|B:B\to R\) to each cell \(B\in\cald\) with \(B\subseteq A\) is continuous
    #+END_theorem

    \((\text{\rom{1}}_1)\) holds by o-minimality, and that \((\text{\rom{2}}_1)\) follows from the monotonicity
    theorem

    We now assume that \(\text{\rom{1}}_1,\dots,\text{\rom{1}}_m\)
    and \(\text{\rom{2}}_1,\dots,\text{\rom{2}}_m\) hold

    The proof is lengthy. The first step is to generalize the finiteness lemma of the previous
    section. Call a set \(Y\subseteq R^{m+1}\) *finite over* \(R^m\) if for each \(x\in R^m\) the
    fiber \(Y_x:=\{r\in R:(x,r\}\in Y\) is finite; call \(Y\) *uniformly finite over* \(R^m\) if there
    is \(N\in\N\) s.t. \(\abs{Y_x}\le N\) for all \(x\in R^m\)

    #+ATTR_LATEX: :options [Uniform Finitness Property]
    #+BEGIN_lemma
    Suppose the definable subset \(Y\) of \(R^{m+1}\) is finite over \(R^m\), then \(Y\) is uniformly
    finite over \(R^m\)
    #+END_lemma

    #+BEGIN_proof

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(X\) be a topological space, \((R_1,<)\), \((R_2,<)\) dense linear orderings without
    endpoints and \(f:X\times R_1\to R_2\) a function s.t. for each \((x,r)\in X\times R_1\)
    1. \(f(x,\cdot):R_1\to R_2\) is continuous
    2. \(f(\cdot,r):X\to R_2\) is continuous
    Then \(f\) is continuous
    #+END_lemma

    #+BEGIN_proof
    Let \((x,r)\in X\times R_1\) and \(f(x,r)\in J\), where \(J\) is an interval in \(R_2\). We shall find a
    neighborhood \(U\) of \(x\) and an interval \(I\) around \(r\) s.t. \(f(U\times I)\subseteq J\). By (1) there
    are \(r_-,r_+\) in \(R_1\) s.t. \(r_-<r<r_+\) and \(f(x,r_-),f(x,r_+)\in J\). Now use (2) to get a
    neighborhood \(U\) of \(x\) s.t. \(f(U\times\{r_-\})\subseteq J\) and \(f(U\times\{r_+\})\subseteq J\). We claim that
    then \(f(U\times I)\subseteq J\) for \(I=(r_-,r_+)\)

    Let \(x'\in U\) and \(r_-<r'<r_+\). Assume \(f(x',\cdot)\) is increasing,
    then \(f(x',r_-)\le f(x',r')\le f(x',r_+)\) and \(f(x',r_-)\), \(f(x',r_+)\) are both in \(J\),
    hence \(f(x',r')\) is in \(J\)
    #+END_proof

    A *definably connected component* of a nonempty definable set \(X\subseteq R^m\) is by definition a maximal
    definably connected subset of \(X\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(X\subseteq R^m\) be a nonempty definable set. Then \(X\) has only finitely many definably connected
    components. They are open and closed in \(X\) and form a finite partition of \(X\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\{C_1,\dots,C_k\}\) be a partition of \(X\) into \(k\) disjoint cells. For each nonempty set of
    indices \(I\subseteq\{1,\dots,k\}\), put \(C_I:=\bigcup_{i\in I}C_i\). Among the \(2^k-1\) sets \(C_I\), let \(C'\) be
    maximal w.r.t. being definably connected.

    Claim: If a set \(Y\subseteq X\) is definably connected and \(C'\cap Y\neq\emptyset\), then \(Y\subseteq C'\)

    Put \(C_Y:=\bigcup\{C_i:C_i\cap Y\neq\emptyset\}\). Since the \(C_i\)'s cover \(X\) we have \(Y\subseteq C_Y\), so \(C_Y\)
    is the union of \(Y\) with certain cells that intersect \(Y\). Hence \(C_Y\) is definably
    connected <<Problem2>>. By maximality of \(C'\) it follows that \(C'\cup C_Y=C'\).
    Hence \(Y\subseteq C_Y\subseteq C'\), which proves the claim.

    It follows in particular that \(C'\) is a definably connected component of \(X\). Further the
    claim shows that the sets \(C'\) are the only definable connected components of \(X\). Note that
    because the closure in \(X\) of a definably connected subset of \(X\) is also definably
    connected, the definably connected components of \(X\) are closed in \(X\). Hence they are open
    in \(X\)
    #+END_proof

** Definable families
    Let \(S\subseteq R^{m+n}=R^m\times R^n\) be definable. For each \(a\in R^m\) we put
    \begin{equation*}
    S_a:=\{x\in R^n:(a,x)\in S\}\subset R^n
    \end{equation*}
    We view \(S\) as describing the family of sets \((S_a)_{a\in R^m}\). Such a family is called a
    *definable family* (of subsets of \(R^n\), with parameter space \(R^m\)). The sets \(S_a\) are also
    called the *fibers* of the family

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(\calr:=(\R,<,+,\cdot)\) and consider the formula
    \begin{equation*}
    ax^2+bxy+cy^2+dx+ey+f=0
    \end{equation*}
    This defines a relation \(S\subseteq\R^6\times\R^2\). For each point \((a,b,c,d,e,f)\in\R^6\) the
    subset \(S_{(a,b,c,d,e,f)}\in\R^2\) consists of the points \((x,y)\) satisfying the equation
    #+END_examplle

    In the following \(\pi:R^{m+n}\to R^m\) denotes the projection on the first \(m\) coordinates

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. Let \(C\) be a cell in \(R^{m+n}\) and \(a\in\pi(C)\). Then \(C_a\) is a cell in \(R^n\)
    2. Let \(\cald\) be a decomposition of \(R^{m+n}\) and \(a\in R^m\). Then the collection
       \begin{equation*}
       \cald_a:=\{C_a:C\in\cald,a\in\pi(C)\}
       \end{equation*}
       is a decomposition of \(R^n\)
    #+END_proposition

    #+BEGIN_proof
    For \(n=1\) this is immediate from the definitions

    Suppose the proposition holds for a certain \(n\), and let \(C\) be a cell in \(R^{m+(n+1)}\).
    Let \(\pi_1:R^{m+(n+1)}\to R^{m+n}\) be the obvious projection map, so that \(\pi\circ\pi_1:R^{m+(n+1)}\to R^m\)
    is the projection on the first \(m\) coordinates

    If \(C=\Gamma(f)\), then \(C_a=\Gamma(f_a)\), where \(f_a:(\pi_1C)\to R\) is defined by \(f_a(x)=f(a,x)\)

    If \(C=(f,g)_D\) with \(D=\pi_1C\), then \(C_a=(f_a,g_a)_E\) where \(E=D_a\)

    In both cases \(C_a\) is a cell in \(R^{n+1}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(S\subseteq R^m\times R^n\) be definable. Then there is a number \(M_S\in\N\) s.t. for each \(a\in R^m\) the
    set \(S_a\subseteq R^n\) has a partition into at most \(M_S\) cells. In particular, each fiber \(S_a\) has
    at most \(M_S\) definably connected components
    #+END_corollary

    #+BEGIN_proof
    Take a decomposition \(\cald\) of \(R^{m+n}\) partitioning \(S\). Then for each \(a\in R^m\) the
    decomposition \(\cald_a=\{C_a:C\in\cald,a\in\pi C\}\) of \(R^m\) consists of at most \(\abs{\cald}\) cells and
    partitions \(S_a\). So we can take \(M_S=\abs{\cald}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(S\subseteq R^m\times R^n\) be definable. Then there is a natural number \(M_S\) s.t. for each \(a\in R^m\)
    the set \(S_a\subseteq R^n\) has at most \(M_S\) isolated points. In particular, each finite fiber \(S_a\)
    has cardinality at most \(M_S\)
    #+END_corollary

* Definable invariants: dimension and euler characteristic

** Dimension
    We define the *dimension* of a nonempty definable set \(X\subseteq R^m\) by
    \begin{equation*}
    \dim(X):=\max\{i_1+\dots+i_m:X\text{ contains an }(i_1,\dots,i_m)\text{-cell}\}
    \end{equation*}
    To the empty set we assign the dimension \(-\infty\)

    Goal:
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    1. well-defined
    2. if \(f:A\to B\) is a definable bijection
    3. \(\dim(A)>0\Leftrightarrow\abs{A}=\infty\)
    4. \(\dim(A\times B)=\dim(A)+\dim(B)\)
    5. \(\dim(R^n)=n\)
    6. If \(f:A\to B\) is a definable surjection, if \(\dim(f^{-1}(b))=k\) for all \(b\in B\),
       then \(\dim(A)=k+\dim(B)\)
    7. If \(\varphi(\barx,\bary)\) is a formula, then
       \begin{equation*}
       S(k)=\{\barb\in R^m:\dim(\varphi(R^n,\barb))=k\}
       \end{equation*}
       is definable.
    8. \(\dim(\cl(A))=\dim(A)\), \(\partial A:=\cl(A)\setminus A\), \(\dim(\partial A)<\dim(A)\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(A=\sqcup_{i=1}^nC_i\), \(\chi(A)=\sum_{i=1}^n(-1)^{\dim(C_i)}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    - well-defined
    - \(\chi(A\times B)=\chi(A)\cdot\chi(B)\)
    - \(\chi(A\cup B)=\chi(A)\cdot\chi(B)-\chi(A\cap B)\)
    - If \(\abs{A}<\infty\), \(\chi(A)=\abs{A}\)
    - (7) in above and replace \(\dim\) with \(\chi\)
    - If \(f:A\to B\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(f:A_1\to A_2\) a definable injection, then \(m\le\dim(A_1)\Rightarrow m\le\dim(A_2)\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    1. If \(f:A_1\to A_2\) is a definable injection, then \(\dim(A_1)\le\dim(A_2)\).
    2. If \(f:A_1\to A_2\) is a definable bijection, then \(\dim(A_1)=\dim(A_2)\).
    3. If \(A_1\subseteq A_2\), then \(\dim(A_1)\le\dim(A_2)\)
    #+END_theorem

    \(D\subseteq R^n\) definable, \(a\in\tint(D)\Leftrightarrow\exists\text{Box } B\ni a, B\subseteq D\).

    \(\tint(D)\neq\emptyset\Leftrightarrow\exists\text{Box }B, B\subseteq D\)

    #+BEGIN_remark
    If \(C\subseteq R^n\) is an \((i_1,\dots,i_n)\)-cell, then
    - if \(i_1=i_2=\dots=i_n=1\), then \(C\) is open
    - otherwise, \(\tint(C)=\emptyset\) and \(C\) is nowhere dense.
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(D\) is *nowhere dense* if \(\forall\) box \(B\), \(\exists\) box \(B'\subseteq B\), \(B'\cap D=\emptyset\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(D_1,D_2\) are nowhere dense, then \(D_1\cup D_2\) is nowhere dense.
    #+END_lemma

    #+BEGIN_proof
    Given a box \(B_1\), \(\exists B_2\subseteq B_1\), \(B_2\cap D_1=\emptyset\), \(\exists B_3\subseteq B_2\), \(B_3\cap D_2=\emptyset\), \(B_3\cap(D_1\cup D_2)=\emptyset\).
    #+END_proof

    If \(A\subseteq R^m\) definable, \(A=\bigcup_{i=1}^nC_i\), \(C_i\) are cells, then either
    - some \(C_i\) is open, then \(\tint(A)\neq\emptyset\), or
    - all \(C_i\) are nowhere dense, so \(A\) is nowhere

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(D_1,\dots,D_n\subseteq R^m\) are definable and \(\tint(D_i)=\emptyset\), then \(\tint(\bigcup_{i=1}^mD_i)=\emptyset\).
    #+END_corollary

    \(\R=\Q\cup(\R\setminus\Q)\), \(\tint(\Q)=\tint(\R\setminus\Q)=\emptyset\), \(\tint(\R)=\R\)

    #+BEGIN_proof
    \(\tint(D_i)=\emptyset\Rightarrow\) \(D_i\) is nowhere dense.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(D_1,D_2\subseteq R^n\) definable, then \(\dim(D_1\cup D_2)=\max(\dim(D_1),\dim(D_2))\)
    #+END_theorem

    #+BEGIN_proof
    \(\max(\dim(D_1),\dim(D_2))\le\dim(D_1\cup D_2)\).

    *Claim*: If \(m\le\dim(D_1\cup D_2)\), then \(m\le\max(\dim(D_1),\dim(D_2))\)

    Take \(B\subseteq R^m\), definable injection \(f:B\hookrightarrow D_1\cup D_2\). If \(x\in B\), \(f(x)\in D_1\) or \(f(x)\in D_2\).
    So \(B=f^{-1}(D_1)\cup f^{-1}(D_2)\). \(\tint(B)=B\neq\emptyset\), so \(\tint(f^{-1}(D_1))\neq\emptyset\)
    or \(\tint(f^{-1}(D_2))\neq\emptyset\).

    \(\exists\) box \(B'\subseteq f^{-1}(D_1)\) and \(f|_{B'}:B'\hookrightarrow D_1\), so \(m\le\dim(D_i)\le\max(\dim(D_1),\dim(D_2))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(D\subseteq R^n\) definable and \(\tint(D)\neq\emptyset\)
    1. (\(\rom{1}_n\)): \(\not\exists\) definable injection \(f:D\to R^{n-1}\)
    2. (\(\rom{2}_n\)): If \(f:D\to R^n\) a definable injection, then \(\tint(f(D))\neq\emptyset\).
    #+END_theorem

    #+BEGIN_proof
    \(n=1\), \(\rom{2}_1\), \(\abs{D}=\infty\), \(\abs{f(D)}=\infty\), then o-minimality says \(f(D)\) contains
    an interval

    \(\rom{1}_n\): By Cell decomposition, can shrink \(B\), get \(f|_B\) continuous. And at least
    one of cell is open, take box \(B\) from it.

    \(B=B_0\times(a,b)\), \(B_0\subseteq R^{n-1}\), take \(c\in(a,b)\), let \(g:B_0\to R^{n-1}\), \(g(x)=f(x,c)\).
    By \(\rom{2}_{n-1}\), \(g(B_0)\) has interior, take \(p=g(x_0)\in\tint(g(B_0))\), \(f\) is
    continuous, \(\exists c'\in(a,b)\)
    s.t. \(c'\neq c\), \(f(x_0,c')\in\tint(g(B_0))\), \(f(x_0,c')=g(x_1)=f(x_1,c)\) for some \(x_1\in B_0\),
    but \(f\) is injective.

    \(\rom{2}_n\): \(f:D\to R^n\) injection, \(\tint(D)\neq\emptyset\). Assume \(\tint(f(D))=\emptyset\).

    \(f(D)=\sqcup_{i=1}^nC_i\) cells, no \(C_i\) is open. \(D=\bigcup_{i=1}^nf^{-1}(C_i)\), \(\tint(D)\neq\emptyset\). There
    is \(i\) s.t. \(\tint(f^{-1}(C_i))\neq\emptyset\), there is box \(B\subseteq f^{-1}(C_i)\), therefore there is
    definable injection \(B\to C_i\to\pi(C_i)\subseteq R^{n-1}\), contradicts \(\rom{1}_n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\dim(R^n)=n\)

    If \(D\subseteq R^n\), \(\tint(D)\neq\emptyset\), then \(\dim(D)=n\)

    \(\tint(D)\neq\emptyset\Leftrightarrow\dim(D)=n\)
    #+END_corollary

    dimension theory rules out things like space-filling curves. No definable surjection
    \begin{equation*}
    [0,1]\to[0,1]^2
    \end{equation*}
    No Hilbert curves,


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:4.1.2
    If \(A\subseteq R^m\) is an open cell and \(f:A\to R^m\) an injective definable map, then \(f(A)\) contains
    an open cell
    #+END_lemma

    #+BEGIN_proof
    Clearly for \(m=1\). Let \(m>1\) and assume inductively the lemma holds for lower values
    of \(m\). Taking a decomposition of \(R^m\) that partitions \(f(A)\) we have
    \begin{equation*}
    f(A)=C_1\cup\dots\cup C_k\text{ for cells $C_i$ in }R^m
    \end{equation*}
    Then
    \begin{equation*}
    A=f^{-1}(C_1)\cup\dots\cup f^{-1}(C_k)
    \end{equation*}
    so at least one of the \(f^{-1}(C_i)\), say \(f^{-1}(C_1)\), contains a box \(B\) , and by
    taking \(B\) suitably small we may assume that \(f|B\) is continuous. We now claim that \(C_1\)
    is open.

    If not, then by composing \(f|B:B\to C_1\) with a definable homeomorphism of \(C_1\) with a
    cell in \(R^{m-1}\) we obtain a definable continuous injective map \(g:B\to R^{m-1}\).
    Write \(B=B'\times(a,b)\)

    Take \(c\) with \(a<c<b\) and consider the map \(h:B'\to R^{m-1}\) given by \(h(x)=f(x,c)\). By
    the inductive assumption applied to \(h\) we get \(h(B')\supseteq D\) for some box \(D\) in \(R^{m-1}\).
    Let \(y\) be a point in \(D\) and take \(x\) in \(B'\) with \(h(x)=y\)

    If \(c'\neq c\) is sufficiently close to \(c\), then \(g(x,c')\) will be in \(D\),
    so \(g(x,c')=h(x')=g(x',c)\) for some \(x'\in B'\). This contradicts the injectivity of \(g\)
    #+END_proof

    Box is a cell

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. If \(X\subseteq Y\subseteq R^m\) and \(X,Y\) are definable, then \(\dim X\le\dim Y\le m\)
    2. If \(X\subseteq R^m\) and \(Y\subseteq R^n\) are definable and there is a definable bijection between \(X\)
       and \(Y\), then \(\dim X=\dim Y\)
    3. If \(X,Y\subseteq R^m\) are definable, then \(\dim(X\cup Y)=\max\{\dim X,\dim Y\}\)
    #+END_proposition

    #+BEGIN_proof
    2. [@2] Let \(f:X\to Y\) be a definable bijection and \(d=\dim X\), \(e=\dim Y\). It is enough to
       show \(d\le e\).

       Let \(A\) be an \((i_1,\dots,i_m)\)-cell contained in \(X\), with \(d=i_1+\dots+i_m\).
       Then \(f\circ(p_A^{-1}):p(A)\to Y\) is an injective map and \(p(A)\) an open cell.
       Replacing \(X\) by \(p(A)\), \(Y\) by \(f(A)\) and \(f\) by \(f\circ(p_A^{-1})\) we may as well
       assume that \(d=m\) and that \(X\) is an open cell in \(R^d\). Let \(Y=C_1\cup\dots\cup C_k\) be a
       partition of \(Y=f(X)\) into cells. Then \(X=f^{-1}(C_1)\cup\dots\cup f^{-1}(C_k)\), so by the cell
       decomposition theorem  \(f^{-1}(C_i)\) contains an open cell \(B\) since \(X\) is open, for
       some \(i\). Fix such \(i\) and \(B\)

       Let \(C_i=C\subseteq R^n\) be a \((j_1,\dots,j_n)\)-cell. We shall prove that \(d\le j_1+\dots+j_n\).

       Suppose \(d>j_1+\dots+j_n\), the composition
       \begin{equation*}
       B\xrightarrow{f|B}C\xrightarrow{p_C}p(C)\subseteq R^{j_1+\dots+j_n}
       \end{equation*}
       is an injective map. Identify \(R^{j_1+\dots+j_n}\) with a non-open cell \((R^{j_1+\dots+j_n})\times\{p\}\)
       in \(R^d\), where \(p\in R^{d-(j_1+\dots+j_n)}\), we obtain a contradiction with lemma ref:3.1.2
    3. Let \(d=\dim(X\cup Y)\), and let \(A\) be an \((i_1,\dots,i_m)\)-cell contained in \(X\cup Y\)
       with \(d=i_1+\dots+i_m\). The open cell \(pA\subseteq R^d\) is the union of \(p_A(A\cap X)\)
       and \(p_A(A\cap Y)\), so by the cell decomposition theorem, one of these sets,
       say \(p_A(A\cap X)\), contains a box \(B\) in \(R^d\). Then \(p_A^{-1}(B)\) is
       an \((i_1,\dots,i_m)\)-cell contained in \(X\), so that
       \begin{equation*}
       \dim X\ge d\ge \dim X
       \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(C\) is an \((i_1,\dots,i_n)\)-cell, then \(\dim(C)=\sum_{j=1}^ni_j\).
    #+END_theorem

    #+BEGIN_proof
    there is \(\pi:R^n\to R^m\) s.t. \(C\to\pi(C)\) is a homeomorphism, \(\pi(C)\) is open.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(C\subseteq R^n\) is an \((i_1,\dots,i_n)\)-cell, \(C'\subseteq R^m\) is a \((j_1,\dots,j_m)\)-cell, then
    \(C\times C'\) is an \((i_1,\dots,i_n,j_1,\dots,j_m)\)-cell
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\subseteq R^n\), \(B\subseteq R^m\) definable, then
    \begin{equation*}
    \dim(A\times B)=\dim(A)+\dim(B)
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    Do cell decomposition on each one
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\subseteq R^{n+m}\), if \(A_x=\{y\in R^m:(x,y\}\in A\) for all \(x\in R^n\), if
    \(S(k)=\{x:\dim(A_x)=k\}\), then \(S(k)\) is definable and
    \(\dim(A)=\max_k(k+\dim(S(k)))\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(D\subseteq R^n\times R^m\), if \(\pi(\barx,\bary)=\barx\), \(\dim(D)\ge\dim(\pi(D))\)
    #+END_lemma

    #+BEGIN_proof
    If \(C\subseteq R^{n+m}\) is a cell, then \(\pi(C)\) is an cell
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(f:A\to B\) is a definable surjection, then \(\dim(A)\ge\dim(B)\)
    #+END_theorem

    #+BEGIN_proof

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(D\subseteq R^n\), \(m\le n\), then \(\dim(D)\ge m\) iff there is some coordinate projection \(\pi:R^n\to R^m\)
    s.t. \(\tint(\pi(D))\neq\emptyset\).
    #+END_theorem

    #+BEGIN_proof
    If \(\exists\pi:R^n\to R^m\) and \(\tint(\pi(D))\neq\emptyset\), then \(\dim(D)\ge\dim(\pi(D))=m\)

    If \(\dim(D)\ge m\), then \(\exists\) cell \(C\subseteq D\) s.t. \(C\) is an \((i_1,\dots,i_n)\)-cell
    and \(l=i_1+\dots+i_n\ge m\).

    There is \(\pi_0:R^n\to R^l\) s.t. \(\pi_0(C)\) is an open cell.

    Then take \(\pi_1:R^l\to R^m\)
    #+END_proof

    \(\partial D=\cl(D)\setminus D\)


    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\subseteq R^n\) definable, \(A\neq\emptyset\), then
    \(\dim(\partial A)<\dim(A)\)
    #+END_theorem





    The next result says among other things that the dimension of a set from a definable family
    depends "definably" on its parameters

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(S\subseteq R^m\times R^n\) be definable. For \(d\in\{-\infty,0,1,\dots,n\}\) put
    \begin{equation*}
    S(d):=\{a\in R^m:\dim S_a=d\}
    \end{equation*}
    Then \(S(d)\) is definable and the part of \(S\) above \(S(d)\) has dimension given by
    \begin{equation*}
    \dim\left( \bigcup_{a\in S(d)}\{a\}\times S_a \right)=\dim(S(d))+d
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    Let \(\cald\) be a decomposition of \(R^{m+n}\) partitioning \(S\)
    #+END_proof



* Problems

    | [[Problem1]]|[[Problem2]]|     |
