#+TITLE: The Rising Sea@@latex:\\@@Foundations of Algebraic Geometry
#+AUTHOR: Ravi Vakil
#+EXPORT_FILE_NAME: ../latex/TheRisingSea/TheRisingSea.tex
#+LATEX_HEADER: \input{../preamble.tex}

#+LATEX_HEADER: \DeclareMathOperator{\opp}{opp}

* Some category theory

** Categories and functors
   #+BEGIN_exercise
   label:ex1.2.B
   If \(A\) is an object in a category \(\calc\), show that the invertible
   elements of \(\Mor(A,A)\) form a group (called the *automorphism group of*
   \(A\), denoted \(\Aut(A)\)). Show that two isomorphic objects have isomorphic
   automorphism group.
   #+END_exercise

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *subcategory* \(\cala\) of a category \(\calb\) has as its objects some of
   the objects of \(\calb\), and some of the morphisms, s.t. the morphisms of
   \(\cala\) include the identity morphisms of the objects of \(\cala\), and are
   closed under composition.
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *covariant functor* \(F\) from a category \(\cala\) to a category \(\calb\),
   denoted \(F:\cala\to\calb\), is the following data. It is a map of objects
   \(F:\obj(\cala)\to\obj(\calb)\), and for each \(A_1,A_2\in\cala\), and
   morphism \(m:A_1\to A_2\), a morphism \(F(m):F(A_1)\to F(A_2)\) in \(\calb\).
   We require that \(F\) preserves identity morphisms and that \(F\) preserves composition.
   #+END_definition

   A covariant functor \(F:\cala\to\calb\) is *faithful* if for all
   \(A,A'\in\cala\), the map \(\Mor_{\cala}(A,A')\to\Mor_{\calb}(F(A),F(A'))\) is
   injective, and *full* if it's surjective. A functor that is full and faithful
   is *fully faithful*. A subcategory \(i:\cala\to\calb\) is a *full subcategory* if
   \(i\) is full.

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A *contravariant functor* is defined in the same way as a covariant functor,
   except the arrows switch directions: in the above language, \(F(A_1\to A_2)\)
   is now an arrow from \(F(A_2)\) to \(F(A_1)\)

   \(\calc^{\opp}\) is said to be the *opposite category* to \(\calc\)
   #+END_definition
