#+TITLE: Uncertainty and vagueness in knowledge based systems
#+AUTHOR: R. Kruse E.Schewecke J.Heinsohn
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/UncertaintyandVagueness/UncertaintyandVagueness.tex
* General Considerations of uncertainty and vagueness
** Modeling ignorance
   Ignorance arises from a restricted reliability of technical devices, from
   partial knowledge, from insufficiencies of observations or from other causes. 

   In the sequel we distinguish between two different types of ignorance:
   *uncertainty* and *vagueness*.  

   Vagueness arises whenever a datum, although its meaning is not in doubt,
   lacks the desired precision. 

   Uncertainty, on the other hand, corresponds to a
   human being's valuation of some datum, reflecting his or her faith or doubt
   in its source. This concept covers those cases in which the actual state of
   affairs or process is not completely determined but where we have to rely on
   some human expert's subjective preferences among the different possibilities. 

   the basic intention of any model is to reflect properties of the real world,
   i.e. to enable the prediction of a system's behavior in the real world. 

   a model can never be verified, and the only reasonable argument for its
   validity is that all efforts to falsify it have failed.
* Introduction
** Basic notations
   \Omega /universe of discourse/ or /frame of discernment/.
   $\what{\emptyset}$
   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   A set \Omega' is called a /refinement/ of \Omega if there is a mapping 
   $\what{\Pi}:2^\Omega\to 2^{\Omega'}$ s.t.
   1. $\what{\Pi}(\lb\omega\rb)\neq\emptyset$ for all $\omega\in\Omega$
   2. $\what{\Pi}(\lb\omega\rb)\cap\what{\Pi}(\lb\omega'\rb)=\emptyset$, if
      $\omega\neq\omega'$ 
   3. $\bigcup\lb\what{\Pi}(\lb\omega\rb)|\omega\in\Omega\rb=\Omega'$
   4. $\what{\Pi}(A)=\bigcup\lb\what{\Pi}(\lb\omega\rb)|\omega\in A\rb$
   #+END_definition
   $\what{\Pi}$ is called a /refinement mapping/. If such a mapping exists, then
   the sets \Omega and \Omega' are compatible, and the refined space \Omega' is
   able to carry more information than \Omega. \Omega is a /coarsening/ of \Omega'

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \Omega' be a refinement of \Omega where $\what{\Pi}:2^\Omega\to
   2^{\Omega'}$ is the corresponding refinement mapping. The mapping
   \begin{equation*}
   \Pi:2^{\Omega'}\to 2^\Omega,\quad\Pi(A')\stackrel{d}{=}\lb
   \omega\in\Omega\mid\what{\Pi}(\lb\omega\rb)\cap A\neq\emptyset\rb
   \end{equation*}
   is called the /outer reduction/ induced by $\what{\Pi}$
   #+END_definition

   Consider a frame of discernment $\Omega=\lb\text{not\_at\_sea,at\_sea}\rb$.
   The granularity of this set is coarse and we might switch to a refined set
   $\Omega'=\lb\text{open\_sea, 12-mile-zone, 3-mile-zone, canal, refueling\_dock,
   loading\_dock}\rb$. We obtain the refinement mapping
   \begin{align*}
   \what{\Pi}(\lb\text{at\_sea}\rb)&=\lb\text{open\_sea, 12-mile-zone, 3-mile-zone}
   \rb\\
   \what{\Pi}(\lb\text{not\_at\_sea}\rb)&=\lb
   \text{canal, refueling\_dock, loading\_dock}\rb
   \end{align*}
   and 
   \begin{align*}
   \Pi(\lb\text{open\_sea}\rb)&=\lb\text{at\_sea}\rb\\
   \Pi(\lb\text{canal}\rb)&=\lb\text{not\_at\_sea}\rb\\
   \end{align*}

   A family $\calu$ of set $\Omega^{(i)}$ is a /universe/.

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\calu$ be a universe with index set $M$. If $S,T,C$ are index subsets of
   $M$ s.t. $T=S\cup C,S\cap C=\emptyset$, then we define the pointwise
   projection by setting
   1. $\pi_S^T:\Omega^T\to\Omega^S,\pi^T_S(\omega^T)\triangleq y^S$, where 
      $y^{(i)}=\omega^{(i)}$ for all $i\in S,S\neq\emptyset$ and
   2. $\pi^T_\emptyset:\Omega^T\to\Omega^{\emptyset},\pi^T_\emptyset=\epsilon$

      
   $\omega^T=(\omega^S,\omega^C)$ if 
   \begin{equation*}
   \pi^T_S(\omega^T)=\omega^S\;\text{ and }\; \pi^T_C(\omega^T)=\omega^C
   \end{equation*}
   #+END_definition

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let $\calu$ be a universe with index set $M$. $S,T,C\subseteq M$ s.t.
   $T=S\cup C,S\cap C=\emptyset$, then
   1. the mapping
      \begin{align*}
      &\Pi^T_S:2^{(\Omega^T)}\to 2^{(\Omega^S)}\\
      &\Pi^T_S(A)\triangleq\lb\omega^T\in\Omega^S\mid\exists\omega^T\in A:
      \pi^T_S(\omega^T)=\omega^S\rb
      \end{align*}
   #+END_definition

