#+TITLE: Exercise

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}

#+BEGIN_exercise
Suppose \(G\) is infinite planar
#+END_exercise

#+BEGIN_proof
Let \(\call=\{E,R,W,B,Y\}\),
\begin{align*}
\sigma=\forall x(&(R(x)\wedge\neg W(x)\wedge\neg B(x)\wedge\neg Y(x))\vee\\
&(\neg R(x)\wedge W(x)\wedge\neg B(x)\wedge\neg Y(x))\vee\\
&(\neg R(x)\wedge\neg W(x)\wedge B(x)\wedge\neg Y(x))\vee\\
&\neg (R(x)\wedge\neg W(x)\wedge\neg B(x)\wedge Y(x)))
\end{align*}
\(\sigma_R:\forall x,y(E(x,y)\to\neg (R(x)\wedge R(y)))\) and \(\sigma_W,\sigma_B,\sigma_Y\) similarly.

\(\Diag_{\el}(G)=\{\phi(a_1,\dots,a_n)\mid G\vDash\phi(a_1,\dots,a_n),a_i\in V,\phi\in L\}\)

Let \(L_V=L\cup V\)

Let \(\Sigma=\Diag(G)\cup\{\sigma,\sigma_R,\sigma_W,\sigma_B,\sigma_Y\}\). \Sigma is finitely satisfiable. For any finite \(\Delta\subset\Diag(G)\),
assume \(a_1,\dots,a_m\) occurs in \(\Delta\), then the subgraph \(T\) of \(G\) with vertices \(a_1,\dots,a_m\) is a
model of \Delta. As we can color \(T\) in 4 colors, \(\Delta\) is satisfiable and thus \(\Sigma\) is satisfiable.

Thus \Sigma has a model \(G'\) with \(f:G\xrightarrow{\prec}G'\) an elementary map. Prove

Let \(f(a)=a^{G'}\). For any \(a_1,a_2\in G\)
1. If \(a_1,a_2\) are distinct elements of \(G\), then \(a_1\neq a_2\in\Diag_{\el}(G)\). Hence \(f(a_1)\neq f(a_2)\)
2. For any relation \(R\), if \(\bara\in R^G\), then \(R(\bara)\in\Diag_{\el}(G)\),
   hence \(f(\bara)\in R^{G'}\)

   If \(\bara\notin R^G\), then \(\neg R(\bara)\in\Diag_{\el}(G)\), hence \(f(\bara)\notin R^{G'}\)

As \(G'\) has 4 color, so does \(G\).
#+END_proof
