#+TITLE: Homework10

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Work in a stable theory. Suppose the sequence \((a_1,\dots,a_n)\) is independent over \(\emptyset\). Suppose the
sequence \((b_1,\dots,b_m)\) is independent over \(\emptyset\). Suppose
\begin{equation*}
\{a_1,\dots,a_n\}\ind_\emptyset\{b_1,\dots,b_m\}
\end{equation*}
Show that \((a_1,\dots,a_n,b_1,\dots,b_m)\) is independent over \(\emptyset\)
#+END_exercise

#+BEGIN_proof
Let \(\bara=(a_1,\dots,a_n)\), \(\barb=(b_1,\dots,b_m)\), for any \(1\le i\le n\), since \(\bara\) is independent
over \(\emptyset\), \(a_i\ind_\emptyset a_{\neq i}\).
Also as \(\bara\ind_\emptyset\barb\), we have \(a_ia_{\neq i}\ind_\emptyset\barb\), by base
monotonicity, \(a_i\ind_{a_{\neq i}}\barb\). Then with \(a_i\ind_\emptyset a_{\neq i}\), monotonicity
gives \(a_i\ind_{\emptyset}a_{\neq i}\barb\). Similarly we can prove \(b_i\ind_{\emptyset}b_{\neq i}\bara\).
Therefore \(\bara\barb\) is independent over \(\emptyset\)
#+END_proof

#+BEGIN_exercise
If \(T=\Th(\R,\le)\) and \(A=\R\) and \(n=1\), show that \(R(\R)\ge 3\), i.e., \(R(S_1(\R))\ge 3\)
#+END_exercise

#+BEGIN_proof
First we prove that \(R(U)\ge\alpha\) for any open interval \(U=(a,b)\subseteq\R\) and any ordinal \alpha by induction.

1. Apparently for any open interval \(U\), \(U\neq\emptyset\) and therefore \(R(U)\ge 0\).
2. For any open interval \(U=(a,b)\subseteq\R\), we can take \(U_i=(a+\frac{b-a}{i+2},a+\frac{b-a}{i+1})\) for
   all \(i\in\omega\), then \(U_0,U_1,\dots\) are pairwise disjoint \(\R\)-definable subsets of \(U\) and
   \(R(U_i)\ge\alpha\) for each \alpha, therefore \(R(U)\ge\alpha+1\)
3. Limit ordinal case is obvious.


\(R(\R)\ge 3\) if and only if there are pairwise disjoint \(\R\)-definable subseteq \(D_1,D_2,\dots\subseteq\R\) such
that \(R(D_i)\ge 2\), and we can take \(D_i=(i,i+1)\) for \(i=1,2,3,\dots\). For each \(D_i\), \(R(D_i)\ge 2\),
therefore \(R(\R)\ge 3\)
#+END_proof

#+BEGIN_exercise
If \(T=\Th(\Z,+)\) and \(A=\emptyset\) and \(n=1\), show that the definable set \(\Z\) has Cantor-Bendixon
rank \(\infty\).
#+END_exercise

#+BEGIN_proof

#+END_proof

#+BEGIN_exercise
If \(T=\ACF_0=\Th(\C,+,\cdot)\) and \(A=\C\) and \(n=3\). Show that the definable set
\begin{equation*}
D=\{(x,y,z)\in\C^3:x+y+z=0\}
\end{equation*}
has Cantor-Bendixon rank at least 2
#+END_exercise

#+BEGIN_proof
For any \(i\in\omega\), let \(D_{i}=\{(x,y,z)\in\C^3:x+y=i\}\), then \(D_0,D_1,D_2,\dots\) are disjoint \(\C\)-definable
subsets of \(D\). Now for any \(i\in\omega\), for any \(j\in\omega\), let \(D_{ij}=\{(x,y,z)\in\C^3:x+y=i\wedge y=j\}\). When
fixing \(i\), each \(D_{ij}\) is disjoint nonempty set, therefore \(R(D_{ij})\ge 0\) and \(R(D_i)\ge 1\).
Thus \(R(D)\ge 2\).
#+END_proof

#+BEGIN_exercise
Let \((M,\approx)\) be a set \(M\) with an equivalence relation \(\approx\), s.t. each equivalence class is
infinite and there are infinite many equivalence classes. Show that \(S_1(M)\) has Cantor-Bendixson
rank at least 2
#+END_exercise

#+BEGIN_proof
As there are infinitely many equivalence class, we can take \(a_1,a_2,\dots\) such that their equivalence
class is different. Then \([x\approx a_1],[x\approx a_2],\dots\) are disjoint clopen subsets of \(S_1(M)\). Since each
equivalence class is infinite, in \([a_i]\),we can take infinitely many
different \(a_{i1},a_{i2},\dots\in [a_i]\). Thus for each \([x\approx a_i]\), there are pairwise
disjoint \(M\)-definable subsets \([x=a_{i1}],[x=a_{i2}],\dots\) of it and therefore \(R([x\approx a_i])\ge 1\)
and so \(R(S_1(M))\ge 2\)
#+END_proof
