#+TITLE: Homework2

#+AUTHOR: Qi'ao Chen @@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Given two chains \((C,\le)\) and \((D,\le)\), define the lexicographic product of \(C\) and \(D\) to be
the chain defined on the Cartesian product of their universes s.t. \((a,b)<(c,d)\) in the sense
of \(C\times D\) if \(b<d\) in the sense of \(D\), or \(b=d\)and \(a<c\) in the sense of \(C\)
1. Show that a discrete chains without endpoints are those that be written in the form \(\Z\times C\),
   where \(C\) is a linear order
2. Show that if \(C\sim_\omega C'\) and \(D\sim_\omega D'\) then so is \(C\times D\sim_\omega C'\times D'\)
#+END_exercise

#+BEGIN_proof
1. Given a discrete chains without endpoints \((D,<)\), for any \(a,b\in D\), let \(a\sim b\)
   if \(d(a,b)\neq\infty\). Suppose \(a< b\) and \(d(a,b)=\infty\), then for
   any  \(a'\in[a]\), as \(d(a,a')\) is
   finite, \(d(a',b)=\infty\) . Hence \(a'<b\). Similarly, for any \(b'\in[b]\), \(a<b'\). Thus we
   define \([a]\prec[b]\) if \(a<b\). As \(<\) is a strict linear order, \(\prec\) is also a strict linear
   order. We choose an element from each equivalence class, denoted by \(b_i\) for \(i\in I\). For
   each \(a\in[b_i]\), define \(f:D\to\Z\) as
   \begin{equation*}
   f(a)=
   \begin{cases}
   d(a,b_i)&\text{if }b_i<a\\
   -d(a,b_i)&\text{otherwise}
   \end{cases}
   \end{equation*}
   and we have an isomorphism \(f:[a]\cong\Z\) for any \(a\in D\). Then we define the
   \(\phi:D\to\Z\times D/\sim\) with \(a\mapsto(f(a),[a])\). \phi is an isomorphism as \(f\) is an isomorphism
   and \(-/\sim:D\to D/\sim\) is surjective.

   Given a lexicographic product \((\Z\times C,<)\) where \(C\) is a linear order, for
   any \((n,c)\in\Z\times C\), we have \((n-1,c)\) and \((n+1,c)\) such that \((n-1,c)<(n,c)<(n+1,c)\). Also
   there is no \((m,c)\in\Z\times C\) such that \((n-1,c)<(m,c)<(n,c)\) or \((n,c)<(m,c)<(n+1,c)\). Hence
   \((\Z\times C,<)\) is a discrete order.

2. If \(C\sim_\omega C'\) and \(D\sim_\omega D'\), then \((C',\le)\) and \((D',\le)\) are also chains (here we abuse the
   symbols of relations on \(C'\) and \(D'\)).

   We prove \(C\times D\sim_\omega C'\times D'\) by induction on \(p\) to show \(S_p(C\times D,C'\times D')\) is not empty.

   For \(p=0\), \(S_0(C\times D,C'\times D')\neq\emptyset\) as \(\emptyset\in S_0(C\times D,C'\times D')\).

   For \(p=n+1\), as \(S_n(C\times D,C'\times D')\neq\emptyset\), we can build a local
   isomorphism \(s=\{((c_i,d_i),(c_i',d_i'))|0< i\le n\}\) where \(i\) respect the order of \(C\times D\).

   Now for any \((c,d)\in C\times D\)
   * if \((c,d)>(c_n,d_n)\), then either \(d>d_n\) or \(d=d_n\) and \(c>c_n\). In both cases,
     as \(C\sim_\omega C'\) and \(D\sim_\omega D'\), we can find \((c',d')\in C'\times D'\) such that either \(d'>d_n'\)
     or \(d'=d_n'\) and \(c'>c_n'\). Hence \((c',d')>(c_n',d_n')\)
   * if \((c_i,d_i)<(c,d)<(c_{i+1},d_{i+1})\), similarly we can find \((c',d')\in C'\times D'\) such that
     \((c_i',d_i')<(c',d')<(c_{i+1},d_{i+1})\)
   * if \((c,d)<(c_1,d_1)\), similarly we can find \((c',d')\in C'\times D'\) with \((c',d')<(c_1',d_1')\)


   Hence \(t=s\cup\{((c,d),(c',d'))\}\) is a local isomorphism. Backward condition is similar and thus
   \(\emptyset\in S_n(C\times D,C'\times D')\).

   Consequently, \(C\times D\sim_\omega C'\times D'\)
#+END_proof

#+BEGIN_exercise
Given two chains \((C,\le)\) and \((D,\le)\), by \(C+D\) we mean the chain
\begin{equation*}
C\times\{0\}\cup D\times\{1\}
\end{equation*}
s.t. \(C\times\{0\}\) is a copy of \(C\), \(D\times\{1\}\) is a copy of \(D\), and each element of \(C\times\{0\}\) is
smaller than each element of \(D\times\{1\}\)
1. Show that the linear orders \(\R\) and \(\R+\Q\) are not isomorphic
2. Construct two discrete linear orders such that they are \(\infty\)-equivalent but not isomorphic
#+END_exercise

#+BEGIN_proof
1. Suppose there is an isomorphism \(f:\R\to\R+\Q\). Then
   \begin{equation*}
    \R\cong[(f^{-1}(0,1),0),(f^{-1}(1,1),0)]\cong[(0,1),(1,1)]\cong\Q
   \end{equation*}
   that is impossible.
2. \(\R\) and \(\R+\Q\) are \(\infty\)-equivalent. We prove \(\R\sim_\infty\R+\Q\) by induction on \alpha.

    Clearly \(\R\sim_0\R +\Q\).

    If \(\alpha=\beta+1\) and \(\R\sim_\beta\R +\Q\), then \(\emptyset\in S_\beta(\R,\R +\Q)\) and we get a local
   isomorphism \(s=\{(a_i,b_i)_{0\le i<\beta}\}\) and for each ordinal \(\gamma<\lambda<\beta\), \(a_\gamma<a_\lambda\) and \(b_\gamma<b_\lambda\).
   * if \(a<a_0\), then we choose \(b=(\inf(\dom s)-1,0)\)
   * if \(a_{\gamma}<a<a_{\lambda}\) and there is no \(a_i\) such that \(a_\gamma<a_i<a_\lambda\) for all \(0\le i<\beta\), then we
     choose a \(b\) such that \(b_\gamma<b<b_\lambda\) as \(\R\) and \(\Q\) are both dense
   * if \(a>\sup(\dom s)\), then we choose \(b=(\sup(\im s)+1,1)\)


    Let \(t=s\cup\{(a,b)\}\) and we get a new local isomorphism preserving all order relations. And the
    backward case is similar.
    Hence \(\R\sim_{\alpha}\R+\Q\)

    If \alpha is a limit ordinal, then clearly \(\R\sim_\alpha\R+\Q\).

    Hence \(\R\sim_\infty\R+\Q\).
#+END_proof

#+BEGIN_exercise
1. Show that \(\Z+\Z\) and \(\Z\) are \(\omega+1\)-equivalent but not \(\omega+2\)-equivalent
2. Construct two discrete linear orders such that they are \(\omega+n\)-equivalent but
   not \(\omega+n+1\)-equivalent for each \(n\in\N\)
#+END_exercise

#+BEGIN_proof
1. We first prove that \(\Z+\Z\sim_{\omega+1}\Z\)

    For any \(a\in\Z\), we choose \((a,0)\in\Z+\Z\). Now we prove that \(s=\{(a,(a,0))\}\) is an
   \omega-isomorphism, that is, for any \(p\in\omega\), \(s\) is a \(p\)-isomorphism. But by Theorem 1.8, \(s\)
   is indeed a \(p\)-isomorphism. Hence \(s\) is an \omega-isomorphism and forward condition is
   satisfied.

   Then backward is similar and \(\Z+\Z\sim_{\omega+1}\Z\).

   But for \(\omega+2\), if we choose \(a,b\in\Z+\Z\) as \(d(a,b)=\infty\), and suppose \(s=\{(a,c),(b,d)\}\). To
   show \(s\) is an \omega-isomorphism, by
   Theorem 1.8, for any \(p\in\omega\), \(d(c,d)\) should be greater than or equal to \(2^p-1\), which is
   impossible in \(\Z\). Thus \(\Z+\Z\not\sim_{\omega+2}\Z\)

2.


#+END_proof
