#+TITLE: Homework7

#+AUTHOR: 陈淇奥@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(-0=1\)
    2. \(-1=0\)
    3. \(a\cdot 1=a\)
    4. \(a+0=a\)
    5. \(a+a=a\)
    6. \(a\cdot a=a\)
    7. \(1+a=1\)
    8. \(0\cdot a=0\)
    9. \(a+b=1\wedge a\cdot b=0\Rightarrow b=-a\)
    10. \(-(a\cdot b)=(-a)+(-b)\)
    #+END_lemma

    #+BEGIN_proof
    1. \(1=0+(-0)=(0\cdot(-0))+(-0)=-0\)
    2. \(0=1\cdot(-1)=(1+(-1))\cdot(-1)=-1\)
    3. \(a\cdot 1=a\cdot(a+(-a))=a\)
    5. [@5] \(a+a=a+(a\cdot 1)=a\)
    7. [@7] \(1+a=(a+1)\cdot 1=(a+1)\cdot(a+-a)=a\cdot a+0+a+-a=a+-a=1\)
    8. \(0\cdot a=(a\cdot (-a))\cdot a=a\cdot a\cdot (-a)=a\cdot (-a)=0\)
    9. [@9] \(-a=(-a)\cdot 1=(-a)\cdot(a+b)=(-a)\cdot a+(-a)\cdot b=(-a)\cdot b\).

       \(ab+(-a)b=-a\). \(b(a+(-a))=b=-a\)
    10. \(ab+(-a)+(-b)=ab+(-a)+(-b)\cdot 1=ab+(-a)+(-b)a+(-b)(-a)=a(b+(-b))+(-a)+(-b)(-a)=1+(-b)(-a)=1\)
    #+END_proof

#+ATTR_LATEX: :options []
#+BEGIN_exercise
证明不存在基数为3的布尔代数
#+END_exercise

#+BEGIN_proof
若存在基数为3的布尔代数\(\calb\)，则令\(B=\{0,1,a\}\)。

如果 \(-a=0\),那么 \(a+(-a)=a+0=a+(a\cdot(-a))=a\neq 1\)，矛盾。
如果\(-a=1\)，那么\(a\cdot(-a)=a\cdot 1=a\cdot(a+(-a))=a\neq 0\)，矛盾。
如果\(-a=a\)，那么\(a=a\cdot 1=a\cdot(a+a)=a\cdot a+a\cdot a=0+0=0\)，矛盾。

因此不存在基数为3的布尔代数。
#+END_proof

#+ATTR_LATEX: :options [3.1.10]
#+BEGIN_exercise
令\(\calb\)为任意布尔代数
1. 证明任意布尔代数\(\calb\)在关系\(\le\)下是偏序
4. [@4] 对任意\(a,b\in\calb\)，\(a\cdot(-b)=0\)当且仅当\(a\le b\)
#+END_exercise

#+BEGIN_proof
1. 因为\(x=x\)，因此\(x=x\)

   若\(x\le y\wedge y\le x\)则存在\(c,d\)使得\(c\neq 0\wedge d\neq 0\wedge x+c=y\wedge y+d=x\)，于
   是\(x=y+d=y+y+d=x+y=x+x+c=x+c=y\)。


   若\(x\le y\wedge y\le z\)，则存在\(c,d\)使得\(c\neq 0\wedge d\neq 0\wedge x+c=y\wedge y+d=z\)，因此\(x+c+d=z\)。

4. [@4]  \(a\cdot(-b)=0\Rightarrow a=ab\Rightarrow b=(a+1)b=a+b\)

    若存在\(c\neq 0\wedge a+c=b\)，则\(a+b=a+a+c=a+c=b\)，
    因此\(a(-b)=a(-b)+0=b(-b)=0\)。若\(a=b\)，则\(a\cdot(-b)=0\)。
#+END_proof

#+ATTR_LATEX: :options [3.1.13]
#+BEGIN_exercise
任意有穷的布尔代数都是原子化的
#+END_exercise

#+BEGIN_proof
给定一个有限布尔代数\(\calb\)，对任意\(b\in\calb\)，任选一条\(b\)的最长下降链\(C=\{c_0,c_1,\dots,c_n\}\)使
得\(0=c_0<c_1<\dots<c_n=b\)，若\(c_1\)不是原子，则存在\(0<c'<c_1\)，于是\(C\)不是最长的，矛盾。因
此\(c_1\le b\)是原子
#+END_proof

#+ATTR_LATEX: :options [3.1.16]
#+BEGIN_exercise
证明\(f\)是同态映射
#+END_exercise

#+BEGIN_proof
因为0不是原子，于是\(f(0)=\emptyset\)。有因为所有原子都小于等于1，因此\(f(1)=A\)。

对于任意\(b_1,b_2\in B\)，因为\(b_1\le b_1+b_2\)且\(b_2\le b_1+b_2\)，因此\(f(b_1+b_2)\supseteq f(b_1)\)
且\(f(b_1+b_2)\supseteq f(b_2)\)，于是\(f(b_1+b_2)\supseteq f(b_1)\cup f(b_2)\)。对于任意原子\(a\le b_1+b_2\)，由引理3.1.14，
\(a\le b_1\)或\(a\le b_2\)，于是\(a\in f(b_1)\cup f(b_2)\)。因此\(f(b_1+b_2)=f(b_1)\cup f(b_2)\)。

对于任意\(b_1,b_2\in B\)，有\(b_1b_2\le b_1\wedge b_1b_2\le b_2\)，因此\(f(b_1b_2)\subseteq f(b_1)\cap f(b_2)\)。对于任意原
子\(a\in f(b_1)\cap f(b_2)\)，则\(a\le b_1\wedge a\le b_2\)，若\(a\le-(b_1b_2)=(-b_1)+(-b_2)\)，则\(a\le -b_1\)或\(a\le -b_2\)，矛
盾。因此\(a\le b_1b_2\)，于是\(a\in f(b_1b_2)\)

对于任意\(b\in B\)，\(x\in f(-b)\Leftrightarrow x\le -b\Leftrightarrow x\not\le b\Leftrightarrow x\notin f(b)\Leftrightarrow x\in \calp(A)-f(b)\)。
#+END_proof

#+ATTR_LATEX: :options [3.1.22]
#+BEGIN_exercise
若\(\calb\)完全且是原子化的，\(A\)是\(\calb\)中所有原子的集合，则\(f:B\to\calp(A)\)是一个同构
#+END_exercise

#+BEGIN_proof
对于任意\(Y\subseteq A\)，若\(a\in Y\)，则\(a\le\sum Y\)。若\(a\le\sum Y\)，
#+END_proof
