#+title: Cloud Control with Distributed Rate Limiting
#+AUTHOR:
#+LATEX_HEADER: \input{/Users/wu/notes/preamble.tex}
#+EXPORT_FILE_NAME: ../../latex/papers/engineering/cloud_control_with_distributed_rate_limiting.tex
#+LATEX_HEADER: \graphicspath{{../../../paper/engineering/}}
#+OPTIONS: toc:nil
#+STARTUP: shrink


* Introduction
        In this paper, we focus on a specific instance of this problem: controlling the aggregate network
        bandwidth used by a cloud-based service, or distributed rate limiting (DRL).

        Our goal is to allow a set of distributed traffic rate limiters to collaborate to subject a class of
        network traffic (for example, the traffic of a particular cloud-based service) to a single, aggregate
        global limit.


* Limiter Design
        We aim to approximate a centralized token-bucket traffic-policing mechanism.

        We use a peer-to-peer limiter architecture: each limiter is functionally identical and operates
        independently. The task of a limiter can be split into three separate subtasks: estimation,
        communication, and allocation.
        * Every limiter collects periodic measurements of the local traffic arrival rate and disseminates them
          to the other limiters.
        * Upon receipt of updates from other limiters, each limiter computes its own estimate of the global
          aggregate arrival rate that it uses to determine how to best service its local demand to enforce the
          global rate limit.


** Estimation and communication
        We measure traffic demand in terms of bytes per unit time. Each limiter maintains an estimate of both
        local and global demand.

* Problems


* References
<<bibliographystyle link>>
bibliographystyle:alpha

<<bibliography link>>
bibliography:/Users/wu/notes/references.bib
