#+title:Scott拓扑与\(D_\infty\)

#+AUTHOR: 陈淇奥
#+LATEX_HEADER: \input{../../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \DeclareMathOperator{\CPO}{\textbf{CPO}}

* Scott拓扑
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定偏序集\(\la D,\sqsubseteq\ra\)以及集合\(X\subseteq D\)，
    1. 用\(\bot\)表示\(D\)的 *最小元* ；
    2. 用\(\bigsqcup X\)表示\(X\)的最小上界；
    3. 若\(X\)非空且对任意\(a,b\in X\)都存在\(c\in X\)使得\(a\sqsubseteq c\)且\(b\sqsubseteq c\)，则称\(X\)是 *有向集* ；
    4. 若\(D\)满足
       1. \(D\)有最小元；
       2. 每一个\(D\)的有向子集\(X\)都有最小上界。
       则称\(D\)是 *完全偏序* ，记作c.p.o.。
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定任意\(\bot\notin\N\)，定义\(\N^+=\N\cup\{\bot\}\)，并且对任意\(a,b\in\N^+\)，定义
    \begin{equation*}
    a\sqsubseteq b\Leftrightarrow(a=\bot\wedge b\in\N)\vee a=b
    \end{equation*}
    我们用\(\N^+\)表示\(\la\N^+,\sqsubseteq\ra\)。
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\N^+\)是完全偏序。
    #+END_lemma

    #+BEGIN_proof
    注意到\(\N^+\)的有向子集只包括单点集与\(\{\bot,n\}\)，其中\(n\in\N\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定完全偏序\(D,D'\)，令\(\phi\)是从\(D\)到\(D'\)的函数，定义\(\phi\)是 *单调的* 当且仅当
    \begin{equation*}
    a\sqsubseteq b\Rightarrow \phi(a)\sqsubseteq'\phi(b)
    \end{equation*}
    \(\phi\)是 *连续的* 当且仅当对于任意有向集\(X\subseteq D\)，
    \begin{equation*}
    \phi(\bigsqcup X)=\bigsqcup(\phi(X))
    \end{equation*}
    其中\(\phi(X)=\{\phi(x):x\in X\}\)，
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定完全偏序\(\la D,\sqsubseteq\ra\)，定义\(D\)上的 *Scott拓扑* ：\(O\subseteq D\)是开集当且仅当
    1. \(x\in O\wedge x\sqsubseteq y\Rightarrow y\in O\);
    2. 若\(X\subseteq D\)有向且\(\bigsqcup X\in O\)，则\(X\cap O\neq\emptyset\)。
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(U_x=\{z\in D\mid z\not\sqsubseteq x\}\)，则\(U_x\)是开集
    #+END_lemma

    #+BEGIN_proof
    1. 若\(y\in U_x\)且\(y\sqsubseteq z\)，若\(z\sqsubseteq x\)，则\(y\sqsubseteq x\)矛盾。
    2. 若\(X\subseteq D\)有向且\(\bigsqcup X\in U_x\)，若\(X\cap U_x=\emptyset\)，则\(\bigsqcup X\sqsubseteq x\)，矛盾。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(D\)是\(T_0\)空间
    #+END_corollary

    #+BEGIN_proof
    令\(x,y\in D\)且\(x\neq y\)，则\(x\in U_y\)且\(y\notin U_y\)。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    考虑函数\(f:D\to D'\)，则
    #+BEGIN_center
    \(f\)连续当且仅当对任意有向集\(X\subseteq D\)，\(f(\bigsqcup X)=\bigsqcup f(X)\)
    #+END_center
    其中\(f(X)=\{f(x)\mid x\in X\}\)。
    #+END_proposition

    #+BEGIN_proof
    \(\Rightarrow\)：若\(f\)连续，假设\(x\sqsubseteq y\)且\(f(x)\not\sqsubseteq' f(y)\)，则\(f(x)\in U_{f(y)}\)，
    \(x\in f^{-1}(U_{f(y)})\)，由于\(f^{-1}(U_{f(y)})\)是开集，\(y\in f^{-1}(U_{f(y)})\)，
    \(f(y)\in U_{f(y)}\)，矛盾。因此对于任意\(x\in X\)，\(f(\bigsqcup X)\sqsupseteq f(x)\)，\(f(\bigsqcup X)\sqsupseteq\bigsqcup f(X)\)。
    若\(f(\bigsqcup X)\not\sqsubseteq\bigsqcup f(X)\)，则\(f(\bigsqcup X)\in U_{\bigsqcup f(X)}\)，\(\bigsqcup X\in f^{-1}(U_{\bigsqcup f(X)})\)，由定义，存
    在\(a\in X\)使得\(a\in X\cap f^{-1}(U_{\bigsqcup f(X)})\)，因此\(f(a)\in U_{\bigsqcup f(X)}\)，\(f(a)\not\sqsubseteq\bigcup f(X)\)，矛盾。

    \(\Leftarrow\)：若\(x\sqsubseteq y\)，则\(y=x\sqcup y\)，\(f(y)=f(x)\sqcup f(y)\)，因此\(f(x)\sqsubseteq f(y)\)。因此若\(O\subseteq D'\)是开集，
    对于任意有向\(X\subseteq D\)且\(\bigsqcup X\in f^{-1}(O)\)，有\(f(\bigsqcup X)=\bigsqcup f(X)\in O\)，而\(f(X)\)是有向，于
    是\(f(X)\cap O\neq\emptyset\)，因此\(X\cap f^{-1}(O)\neq\emptyset\)。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    给定完全偏序\(D,D'\)，定义\(D\times D'\)上的偏序为
    \begin{equation*}
    (x,x')\sqsubseteq(y,y')\Leftrightarrow x\sqsubseteq y\wedge x'\sqsubseteq y'
    \end{equation*}
    则\(D\times D'\)是完全偏序，给定任意有向集\(X\subseteq D\times D'\)，它的最小上界是
    \begin{equation*}
    \bigsqcup X=(\bigsqcup X_0,\bigsqcup X_1)
    \end{equation*}
    其中
    \begin{align*}
    X_0&=\{x\in D\mid\exists x'\in  D'(x,x')\in X\}\\
    X_1&=\{x'\in D'\mid\exists x\in D(x,x')\in X\}
    \end{align*}
    #+END_proposition

    #+BEGIN_proof
    首先\((\bot,\bot')\)是\(D\times D'\)的最小元。对于任意有向集合\(X\subseteq D\times D'\)，\(X_0,X_1\)也是有向集合，因
    此\(\bigsqcup X_0,\bigsqcup X_1\)存在，于是对于任意\(X\)的上界\((A,B)\)，\(A\)是\(X_0\)的上界，\(B\)是\(X_1\)的上
    界，因此\((\bigsqcup X_0,\bigsqcup X_1)\sqsubseteq(A,B)\)，因此\(\bigsqcup X=(\bigsqcup X_0,\bigsqcup X_1)\)。
    #+END_proof


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定完全偏序\(D,D'\)，定义
    \begin{equation*}
    [D\to D']=\{f:D\to D'\mid f\text{连续}\}
    \end{equation*}
    并且定义\([D\to D']\)上的偏序为
    \begin{equation*}
    f\sqsubseteq g\Leftrightarrow\forall x\in D(f(x)\sqsubseteq'g(x))
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.2.10
    令\(\{f_i\}_i\subseteq[D\to D']\)为有向的函数集合，定义
    \begin{equation*}
    f(x)=\bigsqcup_if_i(x)
    \end{equation*}
    则\(f\)是良定义的并且是连续的。
    #+END_lemma

    #+BEGIN_proof
    应为\(\{f_i\}_i\)有向，因此对于任意\(x\in D\)，\(\{f_i(x)\}_i\)有向，因此\(f\)存在且\(f(x)\)唯一。对于任意
    有向集合\(X\subseteq D\)，
    \begin{equation*}
    f(\bigsqcup X)=\bigsqcup_i\bigsqcup_{x\in X}f_i(x)=\bigsqcup_{x\in X}\bigsqcup_if_i(x)=\bigsqcup f(X)
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.2.11
    \([D\to D']\)是完全偏序，并且对于任意有向\(F\subseteq[D\to D']\)，它的最小上界为
    \begin{equation*}
    (\bigsqcup F)(x)=\bigsqcup\{f(x)\mid f\in F\}
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    \(\metalambda x.\bot'\)是\([D\to D']\)的最小元，由引理ref:1.2.10 ，\(\metalambda x.\bigsqcup\{f(x)\mid f\in F\}\)是
    连续的，因此属于\([D\to D']\)，显然它是最小上界。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    给定完全偏序\(D,D',D''\)，若\(f\in[D\to D']\)，\(g\in[D'\to D'']\)，定义\(g\circ f\)为对任意\(d\in D\)，
    \((g\circ f)(d)=g(f(d))\)，则\(g\circ f\in[D\to D'']\)。
    #+END_proposition

    #+BEGIN_proof
    任给有向集合\(X\subseteq D\)，\(f\in[D\to D']\)，\(g\in[D'\to D'']\)，则
    \begin{align*}
    g\circ f(\bigsqcup X)&=g(f(\bigsqcup X))=g(\bigsqcup_{x\in X} f(x))=\bigsqcup_{x\in X}g(f(x))=\bigsqcup_{x\in X} g\circ f(x)
    \end{align*}
    #+END_proof


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.2.12
    令\(f:D\times D'\to D''\)，则\(f\)连续当且仅当它在\(D\)跟\(D'\)上连续，即对于任意\(x_0\in D,x_0'\in D'\)，
    \(\metalambda x.f(x,x_0')\)和\(\metalambda x.f(x_0,x)\)连续。
    #+END_lemma

    #+BEGIN_proof
    \(\Rightarrow\)：令\(g=\metalambda x.f(x,x_0')\)，则对于有向集合\(X\subseteq D\)
    \begin{align*}
    g(\bigsqcup X)&=f(\bigsqcup X,x_0')=f(\bigsqcup\{(x,x_0')\mid x\in X\})\\
    &=\bigsqcup\{f(x,x_0')\mid x\in X\}\\
    &=\bigsqcup g(X)
    \end{align*}
    同理，\(\metalambda x.f(x_0,x)\)连续。

    \(\Leftarrow\)：给定有向集合\(X\subseteq D\times D'\)，
    \begin{align*}
    f(\bigsqcup X)&=f(\bigsqcup X_0,\bigsqcup X_1)\\
    &=\bigsqcup_{x\in X_0}f(x,\bigsqcup X_1)=\bigsqcup_{x\in X_0}\bigsqcup_{x'\in X_0'}f(x,x')\\
    &=\bigsqcup_{(x,x')\in X}f(x,x')\\
    &=\bigsqcup f(X)
    \end{align*}
    因此\(f\)连续。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.2.13
    定义
    \begin{equation*}
    app:[D\to D']\times D\to D'
    \end{equation*}
    为\(app(f,x)=f(x)\)，则\(app\)连续。
    #+END_proposition

    #+BEGIN_proof
    给定有向集合\(F\subseteq[D\to D']\)，令\(h=\metalambda f.f(x)\)，则
    \begin{align*}
    h(\bigsqcup F)&=(\bigsqcup F)(x)=\bigsqcup\{f(x)\mid f\in F\}\\
    &=\bigsqcup\{h(f)\mid f\in F\}=\bigsqcup h(F)
    \end{align*}
    因此\(h\)连续，同时因为\(\metalambda x.f(x)=f\)连续，由命题ref:1.2.11 \(app\)连续
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:1.2.14
    给定\(f\in[D\times D'\to D'']\)，定义\(\hatf(x)=\metalambda y\in D'(f(x,y))\)，则
    1. \(\hatf\)连续；
    2. \(\metalambda f.\hatf:[D\times D'\to D'']\to[D\to[D'\to D'']]\)连续。
    #+END_proposition

    #+BEGIN_proof
    1. 对于任意有向集\(X\subseteq D\)，
       \begin{align*}
       \hatf(\bigsqcup X)&=\metalambda y.f(\bigsqcup X,y)=\metalambda y.\bigsqcup_{x\in X}f(x,y)\\
       &=\bigsqcup_{x\in X}(\metalambda y.f(x,y))\\
       &=\bigsqcup\hatf(X)
       \end{align*}
    2. 令\(L=\metalambda f.\hatf\)，对于任意有向集\(F\subseteq[D\times D'\to D'']\)，
       \begin{align*}
       L(\bigsqcup F)&=\metalambda x.\metalambda y.(\bigsqcup F)(x,y)=\metalambda x\metalambda y.\bigsqcup_{f\in F}f(x,y)\\
       &=\bigsqcup_{f\in F}\metalambda x.\metalambda y.f(x,y)=\bigsqcup L(F)
       \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\CPO\)是以完全偏序为元素连续映射为态射的范畴。
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \(\CPO\)是笛卡儿闭范畴。
    #+END_theorem

    #+BEGIN_proof
    \(D\times D'\)是\(\CPO\)中的乘积，同时单元素完全偏序是终对象，而
    对于任意\(f:D\times D'\to D''\)，由命题ref:1.2.13 和ref:1.2.14 ，都存在
    唯一的\(\hatf:D\to[D'\to D'']\)使得
    \begin{center}\begin{tikzcd}
    D\times D'\ar[r,"f"]\ar[d,dashed,"\hatf\times\id_{D'}"']&D\\
    \left[D'\to D''\right]\times D'\ar[ur,"app"]
    \end{tikzcd}\end{center}
    交换。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    令\(D_0,D_1,\dots\)是可数的完全偏序序列，令\(f_i\in[D_{i+1}\to D_i]\)，
    1. 序列\((D_i,f_i)\)称为完全偏序的 *逆向系统* (inverse system)。
    2. 系统\((D_i,f_i)\)的 *逆向极限* (inverse limit) \(\varprojlim(D_i,f_i)\)（或记作\(\varprojlim D_i\)）是偏序集\((D_\infty,\sqsubseteq_\infty)\)，其中
       \begin{align*}
       D_\infty=\{(x_0,x_1,\dots)\mid\forall i\in\N(x_i\in D_i\wedge\psi_i(x_{i+1})=x_i)\}
       \end{align*}
       并且
       \begin{equation*}
       (x_0,x_1,\dots)\sqsubseteq_\infty(y_0,y_1,\dots)\Leftrightarrow\forall i\in\N(x_i\sqsubseteq y_i)
       \end{equation*}

    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    给定逆向系统\((D_i,f_i)\)，则\(\varprojlim(D_i,f_j)\)是完全偏序且对任意有向\(X\subseteq\varprojlim D_i\)，
    \begin{equation*}
    \bigsqcup X=\metalambda i.\bigsqcup\{x(i)\mid x\in X\}
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    对于任意有向\(X\subseteq D_\infty\)，则对任意\(i\in\N\)，\(\{x(i)\mid x\in X\}\)有向，令
    \begin{equation*}
    y_i=\bigsqcup\{x(i)\mid x\in X\}
    \end{equation*}
    则由\(\psi_i\)的连续性，
    \begin{equation*}
    \psi_i(y_{i+1})=\bigsqcup f_i(\{x(i+1)\mid x\in X\})=\bigsqcup\{x(i)\mid x\in X\}=y_i
    \end{equation*}
    因此\((y_0,y_1,\dots)\in \varprojlim D_i\)。
    #+END_proof

    因此在\(\CPO\)中，逆向极限存在。

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. \(x\in D\)是 *紧致* (compact)的如果对每个有向集\(X\subseteq D\)都有
       \begin{equation*}
       x\sqsubseteq\bigsqcup X\Rightarrow \exists x\in X(x\sqsubseteq x_0)
       \end{equation*}
    2.\(D\)是 *代数* 完全偏序（algebraic cpo）如果对于所有\(x\in D\)集合\(\{y\sqsubseteq x\mid y\text{紧致}\}\)是有向的并
    且
    \begin{equation*}
    y=\bigsqcup\{y\sqsubseteq x\mid y\text{紧致}\}
    \end{equation*}
    #+END_definition

* \texorpdfstring{\(D_\infty\)}{D}
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定完全偏序\(D\)和\(D'\)，\(D\)与\(D'\) *同构* 当且仅当存在\(\phi\in[D\to D']\)与\(\psi\in[D'\to D]\)使得
    \begin{equation*}
    \psi\circ\phi=\id_D,\quad\phi\circ\psi=\id_{D'}
    \end{equation*}
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定完全偏序\(D\)和\(D'\)。函数的二元组\(\la\varphi,\psi\ra\)是从\(D'\)到\(D\)的 *投射* 如果
    1. \(\varphi\in[D\to D']\), \(\psi\in[D'\to D]\)
    2. \(\psi\circ\varphi=\id_D\)
    3. \(\varphi\circ\psi\sqsubseteq\id_{D'}\)
    #+END_definition

    注意到\(D\)与\(\varphi\psi(D)\)同构，因此在同构的意义下\(D\subseteq D'\)。

    接下来构造\(\lambda\)演算的模型\(D_\infty\)。

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    定义\(D_0=\N^+\)，\(D_{n+1}=[D_n\to D_n]\)，记\(D_n\)的最小元为\(\bot_n\)
    #+END_definition

    由ref:1.2.11 ，对任意\(n\in\N\)，\(D_n\)是完全偏序。

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    给定\(D'\)到\(D\)的投射\((\varphi,\psi)\)，存在从\([D'\to D']\)到\([D\to D]\)的投射\((\varphi^*,\psi^*)\)满足：对于任
    意\(f\in[D\to D]\)，\(g\in[D'\to D']\)有
    \begin{equation*}
    \varphi^*(f)=\varphi\circ f\circ\psi,\quad\psi^*(g)=\psi\circ g\circ\varphi
    \end{equation*}

    \begin{center}\begin{tikzcd}
    D\ar[d,"f"']&D'\ar[l,"\psi"']\ar[d,dashed,"\varphi^*(f)"]\\
    D\ar[r,"\varphi"']&D'
    \end{tikzcd}\quad\begin{tikzcd}
    D\ar[r,"\varphi"]\ar[d,dashed,"\psi^*(g)"']&D'\ar[d,"g"]\\
    D&D'\ar[l,"\psi"]
    \end{tikzcd}\end{center}

    #+END_lemma

    #+BEGIN_proof
    注意到
    \begin{align*}
    \varphi^*(f)&=\metalambda x'\in D'.\varphi(f(\psi(x)))\\
    &=\metalambda x'\in D'.\varphi(app(f,\psi(x)))
    \end{align*}
    于是\(\varphi^*\)是连续的，类似的\(\psi^*\)是连续的。同时
    \begin{gather*}
    \psi^*(\varphi^*(f))=\psi\circ\varphi\circ f\circ\psi\circ\varphi=f\\
    \varphi^*(\psi^*(f))=\varphi\circ\psi\circ f\circ\varphi\circ\psi\sqsubseteq f
    \end{gather*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    给定完全偏序\(D\)，定义\(\varphi_0:D\to[D\to D]\)，\(\psi_0:[D\to D]\to D\)为
    \begin{align*}
    &\varphi_0(x)=\metalambda y\in D.x\\
    &\psi_0(f)=f(\bot)
    \end{align*}
    则\((\varphi_0,\psi_0)\)是从\([D\to D]\)到\(D\)的投射。
    #+END_lemma

    #+BEGIN_proof
    首先证明\(\varphi_0\)连续，给定有向集\(X\subseteq D\)，
    \begin{align*}
    \varphi_0(\bigsqcup X)&=\metalambda y\in D.\bigsqcup X=\bigsqcup_{x\in X}\metalambda y\in D.x\\
    &=\bigsqcup\varphi_0(X)
    \end{align*}
    同理，\(\psi_0\)连续。同时
    \begin{align*}
    \varphi_0(\psi_0(f))&=\varphi_0(f(\bot))=\metalambda x.f(\bot)\\
    &\sqsubseteq\metalambda x.f(x)=f\\
    \psi_0\circ\varphi_0(f)&=\varphi_0(f)(\bot)=f
    \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options [构造\(D_\infty\)]
    #+BEGIN_definition
    给定完全偏序\(D\)与\((\varphi_0,\psi_0)\)如上，定义
    \begin{align*}
    &D_0=D\\
    &D_{n+1}=[D_n\to D_n]\\
    &(\varphi_{n+1},\psi_{n+1})=(\varphi_n^*,\psi_n^*)
    \end{align*}
    令\(D_\infty=\varprojlim(D_n,\psi_n)\)。
    #+END_definition


    记\(x\in D_\infty\)为\((x_0,x_1,\dots)\)。

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. 对于\(n,m\in\N\)，定义\(\Phi_{nm}:D_n\to D_m\)为：

       若\(n\le m\), \(m=n+k\)，则递归定义\(\Phi_{nm}\)为
       \begin{align*}
       &\Phi_{nn}=\lambda x\in D_n.x\\
       &\Phi_{n(m+1)}=\varphi_m\circ\Phi_{nm}
       \end{align*}
       若\(m\le n\)，\(n=m+k\)，递归定义\(\Phi_{nm}\)为
       \begin{equation*}
       \Phi_{(n+1)m}=\Phi_{nm}\circ\psi_n
       \end{equation*}
    2. 定义\(\Phi_{\infty n}:D_\infty\to D_n\)为\(\Phi_{\infty n}(x)=x_n\)。
    3. 定义\(\Phi_{n\infty}:D_n\to D_\infty\)为\(\Phi_{n\infty}(x)=(\Phi_{ni}(x))_{i\in\N}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. 对于\(0\le n\le m\le\infty\)，\((\Phi_{nm},\Phi_{mn})\)是从\(D_m\)到\(D_n\)的投射
    2. 对于\(0\le n\le m\le l\le\infty\)，\(\Phi_{ml}\circ\Phi_{nm}=\Phi_{nl}\)
    #+END_lemma

    #+BEGIN_proof
    1. 若\(n<m<\infty\)，对于任意\(x\in D_m\)，
       \begin{align*}
       \Phi_{nm}\circ\Phi_{mn}&=(\varphi_{m-1}\circ\dots\circ\varphi_n\circ\id_{D_n})\circ(\id_{D_n}\circ\psi_n\circ\dots\circ\psi_{m-1})\\
       &\sqsubseteq\id_{D_m}\\
       \Phi_{mn}\circ\Phi_{nm}&=(\id_{D_n}\circ\psi_1\circ\dots\circ\psi_{m-1})\circ(\varphi_{m-1}\circ\dots\circ\varphi_1\circ\id_{D_n})\\
       &=\id_{D_n}
       \end{align*}
       \(n<m=\infty\)和\(n=m=\infty\)的情况类似。
    2. 根据定义类似可得。
    #+END_proof

    注意到在同构的意义下，
    \begin{equation*}
    D_0\subseteq D_1\subseteq\dots\subseteq D_\infty
    \end{equation*}
    又有一个事实是在\(\CPO\)中，\(D_\infty\)不仅是逆向极限，也是正向极限
    \begin{equation*}
    D_\infty\cong\varinjlim(D_n,\varphi_n)
    \end{equation*}
    因此每个元素\(x\in D_n\)也可被\(\Phi_{n\infty}(x)\in D_\infty\)刻画。

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. 如果\(x\in D_n\)，则\((\Phi_{n\infty}(x))n=x\)。
    2. 如果\(x\in D_n\)，则\(\varphi_n(x)=x\)。
    3. 如果\(x\in D_{n+1}\)，则\(\psi_n(x)\sqsubseteq x\)。
    #+END_lemma

    #+BEGIN_proof
    1. 在\(D_\infty\)中，\(x\)为\(\Phi_{n\infty}(x)\)，因此\(x_n=x\)。
    2. \(\varphi_n(x)\)在\(D_\infty\)中为\((\dots,\psi_n(\varphi_n(x)),\varphi_n(x),\varphi_{n+1}\varphi_n(x),\dots)\)，因
       为\(\psi_n(\varphi_n(x))=x\)，因此\(\varphi_n(x)=x\)。
    3. 类似。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    在\(D_\infty\)中，若\(x\in D_\infty\)，则
    1. \((x_n)_m=x_{\min(n,m)}\)
    2. \(n\le m\Rightarrow x_n\sqsubseteq x_m\sqsubseteq x\)
    3. \(x=\bigsqcup_{n\in\N}x_n\)
    4. \(\bot_n\)是\(D_n\)的最小元素
    5. \(\bot_n=\bot\)
    #+END_lemma

    #+BEGIN_proof
    1. 若\(n<m\)，则
       \begin{equation*}
       (x_n)_m=\Phi_{nm}x_n=
       \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若\(x,y\in D_\infty\)，则对所有\(n,k\in\N\)，\(n\le k\)，则
    1. \(x_{n+1}(y_n)\sqsubseteq x_{k+1}(y_k)\)
    2. \((x_{n+1})_{k+1}(y_k)=x_{n+1}(y_n)\)
    3. \((x_{k+1}(y_n)_k)_n=x_{n+1}(y_n)\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    对于任意\(x\in D_\infty\)，任意\(n,r\ge 0\)，
    1. \(\Phi_{(n+r)n}(x_{n+r})=x_n\)
    2. \(\Phi_{n\infty}(x_n)\sqsubseteq\Phi_{(n+1)\infty}(x_{n+1})\)
    3. \(x=\bigsqcup_{n\ge 0}\Phi_{n\infty}(x_n)=\bigsqcup_{n\ge r}\Phi_{n\infty}(x_n)\)
    #+END_lemma

    #+BEGIN_proof
    1. 根据定义。
    2. ​
       \begin{align*}
       \Phi_{n\infty}(a_n)&=\Phi_{n\infty}(\psi_n(a_{n+1}))=\Phi_{(n+1)\infty}(\phi_n(\psi_n(a_{n+1})))\\
       &\sqsubseteq\Phi_{(n+1)\infty}(a_{n+1})
       \end{align*}
    3. 令\(X=\{\phi_{n,\infty}(a_n):n\ge 0\}\)，则由2，\(X\)是一个递增的序列，因此是有向的，因此\(\bigsqcup X\)存在，同
       时对于任意\(r\ge 0\)，都有\(\bigsqcup X=\bigsqcup_{n\ge r}\Phi_{n\infty}(a_n)\)。同时，
       \begin{align*}
       (\bigsqcup X)_p&=(\bigsqcup_{n\ge p}\Phi_{n\infty}(a_n))_p=\bigsqcup_{n\ge p}(\Phi_{n\infty}(a))_p\\
       &=\bigsqcup_{n\ge p}\Phi_{n,p}(a_n)=\bigsqcup\{a_p\}\\
       &=a_p
       \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:16.42
    对于任意\(x,y\in D_\infty\)，
    \begin{equation*}
    \Phi_{n\infty}(x_{n+1}(y_n))\sqsubseteq\Phi_{(n+1)\infty}(x_{n+2}(y_{n+1}))
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    首先
    \begin{align*}
    \phi_n(x_{n+1}(y_n))&=\phi_n(\psi_{n+1}(x_{n+2})(\psi_{n}(y_{n+1})))\\
    &=\phi_n(\psi_n(x_{n+2}(\phi_n(\psi_n(y_{n+1})))))\\
    &\sqsubseteq\phi_n(\psi_n(x_{n+2}(y_{n+1})))\\
    &\sqsubseteq x_{n+2}(y_{n+1})
    \end{align*}
    于是
    \begin{align*}
    \Phi_{(n+1)\infty}(\phi_n(x_{n+1}(y_n)))\sqsubseteq\Phi_{(n+1)\infty}(x_{n+2}(y_{n+1}))
    \end{align*}
    注意到\(\Phi_{(n+1)\infty}\phi_n=\Phi_{(n+1)\infty}\Phi_{n(n+1)}=\Phi_{n\infty}\)，因此
    \begin{equation*}
    \Phi_{n\infty}(x_{n+1}(y_n))\sqsubseteq\Phi_{(n+1)\infty}(x_{n+2}(y_{n+1}))
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    给定\(x,y\in D_\infty\)，于是由引理ref:16.42 ，\(\{\Phi_{n\infty}(x_{n+1}(y_n)):n\ge 0\}\)是一个递增序列，因此有最
    小上界，定义
    \begin{equation*}
    a\cdot b=\bigsqcup_{n\ge 0}\Phi_{n\infty}(a_{n+1}(b_n))
    \end{equation*}
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    对于任意\(x,y\in D_\infty\)以及所有\(r\ge 0\)
    1. \(x\cdot y=\bigsqcup_{n\ge r}\Phi_{n\infty}(x_{n+1}(y_n))\)；
    2. \((x\cdot y)_r=\bigsqcup_{n\ge r}\Phi_{nr}(x_{n+1}(y_n))\)；
    3. \((x\cdot y)_r\sqsupseteq x_{r+1}(y_r)\)
    #+END_corollary

    #+BEGIN_proof
    1. 因为\(\{\Phi_{n\infty}(x_{n+1}y_n): n\ge 0\}\)是递增序列。
    2.
       \begin{align*}
       (x\cdot y)_r&=\left( \bigsqcup_{n\ge r}\Phi_{n\infty}(x_{n+1}(y_n)) \right)_r\\
       &=\bigsqcup_{n\ge r}(\Phi_{n\infty}(x_{n+1}(y_n)))_r\\
       &=\bigsqcup_{n\ge r}\Phi_{nr}(x_{n+1}(y_n))
       \end{align*}
    #+END_proof
*
