#+TITLE: Homework8

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Let \(M\) be a substructure of \(N\). Let \(\bara\in M^n\) be a tuple and \(\varphi(x_1,\dots,x_n)\) be a
quantifier-free formula. Show that \(M\vDash\varphi(\bara)\Leftrightarrow N\vDash\varphi(\bara)\)
#+END_exercise

#+BEGIN_proof
\(M\) is a substructure of \(N\), then the inclusion map \(i:M\to N\) is an embedding.

First we prove that for any term \(t(\barx)\), \(t^M(\bara)=t^N(\bara)\) by induction on the
complexity of term \(t\).

If \(t\) is a constant \(c\), then \(c^N=i(c^M)=c^M\).

If \(t\) is a variable \(v_i\), then \(t^M(\bara)=a_i=t^N(\bara)\).

If \(t\) is of the form \(f(t_1(\barx),\dots,t_n(\barx))\), then, for
all \(i=1,\dots,n\), \(t_i^M(\bara)=t_i^N(\bara)\) by induction. Because
\(i\) is an embedding, then \(f^M(b_1,\dots,b_n)=i(f^M(b_1,\dots,b_n))=f^N(i(b_1),\dots,i(b_n))=f^N(b_1,\dots,b_n)\).
Hence \(f^M=f^N\mid M^n\)
\begin{align*}
t^M(\bara)&=f^M(t_1^M(\bara),\dots,t_n^M(\bara))\\
&=f^N(t_1^N(\bara),\dots,t_n^N(\bara))\\
&=t^N(\bara)
\end{align*}

Then we prove the exercise by induction on the complexity of \(\varphi(\barx)\).

If \varphi is of the form \(t_1(\barx)=t_2(\barx)\). Then
\begin{align*}
M\vDash t_1(\bara)=t_2(\bara)&\Leftrightarrow t_1^M(\bara)=t_2^M(\bara)\\
&\Leftrightarrow t_1^N(\bara)=t_2^N(\bara)\\
&\Leftrightarrow N\vDash t_1(\bara)=t_2(\bara)
\end{align*}

If \varphi is of the form \(R(t_1(\barx),\dots,t_m(\barx))\), then
\begin{align*}
M\vDash R(t_1(\bara),\dots,t_m(\bara))&\Leftrightarrow (t_1^M(\bara),\dots,t_m(\bara))\in R^M\\
&\Leftrightarrow(i(t_1^M(\bara)),\dots,i(t_m^N(\bara)))\in R^N\\
&\Leftrightarrow(t_1^M(\bara),\dots,t_m^N(\bara))\in R^N\\
&\Leftrightarrow(t_1^N(\bara),\dots,t_n^N(\bara))\in R^N\\
&\Leftrightarrow N\vDash R(t_1(\bara),\dots,t_m(\bara))
\end{align*}

If \varphi is of the form \(\neg\psi\), then
\begin{align*}
M\vDash\varphi(\bara)\Leftrightarrow M\not\vDash\psi(\bara)\Leftrightarrow N\not\vDash\psi(\bara)\Leftrightarrow N\vDash\varphi(\bara)
\end{align*}

If \varphi is of the form \(\psi_1\wedge\psi_2\), then
\begin{align*}
M\vDash\varphi(\bara)\Leftrightarrow M\vDash\psi_1(\bara)\text{ and }M\vDash\psi_2(\bara)\\
&N\vDash\psi_1(\bara)\text{ and }N\vDash\psi_2(\bara)\\
&N\vDash\varphi(\bara)
\end{align*}
#+END_proof

#+BEGIN_exercise
Let \(M\) be an \omega-saturated elementary extensions of \((\R,+,\cdot,-,0,1,\le)\). Suppose that \(a\in M\).
Show that there is \(b\in M\) s.t. \(b>a^n\) for all positive integers \(n\).
#+END_exercise

#+BEGIN_proof
Let \(\varphi_n(x,y)\) be
\begin{equation*}
\neg y=x\wedge\underbrace{x\cdot x\cdot\cdots\cdot x}_{n\text{ times}}\le y
\end{equation*}

Let \(\Sigma(x)=\{\varphi_n(a,x)\mid n\in \N_+\}\). For any finite \(\Sigma_0(x)\subseteq\Sigma(x)\), it's equivalent to \(\varphi_N(a,x)\) for
some sufficient large \(N\). But since \(\R\vDash\forall x\exists y\varphi_n(x,y)\) and \(M\) is an elementary extension
of \(\R\), \(M\vDash\forall x\exists y\varphi_n(x,y)\) and hence there is a \(b_a\in M\) such that \(M\vDash\varphi_N(a,b)\).

Hence \(\Sigma(x)\) is finitely satisfiable and there is \(p\in S_n(a)\) with \(p\supseteq\Sigma\). Then \(M\) being
\omega-saturated implies that \(p(x)\) is realised by \(b\in M\) and therefore \(M\vDash\Sigma(b)\). So for any
positive \(n\), \(b>a^n\).
#+END_proof

#+BEGIN_exercise
Let \(K\) be a field and \(x,y\in K\) be elements. Show that \(xy=0\Leftrightarrow(x=0\vee y=0)\)
#+END_exercise

#+BEGIN_proof
\(\Rightarrow\). If both \(x\) and \(y\) are nonzero. Then as \(xy=0\), \(1=y^{-1}x^{-1}xy=0\), which violates
the axiom of field.

\(\Leftarrow\). For any \(a\in K\),
\begin{align*}
0=0\cdot a+(-0\cdot a)&=(0+0)\cdot a+(-0\cdot a)=0\cdot a+0\cdot a+(-0\cdot a)=0\cdot a
\end{align*}
and similarly \(a\cdot 0=0\).
#+END_proof

#+BEGIN_exercise
Let \(a,b\) be positive integers. Let \(g\) be the greatest common divisor of \(a\) and \(b\). Show
that \(g=ax+by\) for some \(x,y\in\Z\).
#+END_exercise

#+BEGIN_proof
Let \(I=\{ax+by:x,y\in\Z\}\). For
any \(ax+by,ax'+by'\in I\), \(ax+by+ax'+by'=a(x+x')+b(y+y')\in I\).
\((ax+by)(ax'+by')=a(axx'+bxy'+aby)+by'\in I\).
\(0=a\cdot 0+b\cdot 0\in I\). Hence \(I\) is an ideal.

Then \(I=n\Z\) for some \(n\ge 0\) by Theorem 15. Then \(n=ax_n+by_n\) for some \(x_n,y_n\in\Z\) which
implies \(g\mid n\). But as \(a,b\in n\Z\), we have \(n\mid a\) and \(n\mid b\), and so \(n\le g\). Thus \(n=g\)
and \(I=g\Z\). Therefore \(g=ax+by\) for some \(x,y\in\Z\)
#+END_proof

#+BEGIN_exercise
If \(x,y,n\in\Z\) and \(n>0\), then \(x\equiv y\mod n\) means \(x-y\in n\Z\). Show that \(\equiv\) is an equivalence relation
#+END_exercise

#+BEGIN_proof
\(x-x=0\in n\Z\), therefore \(x\equiv x\).

If \(x\equiv y\), then \(x-y\in n\Z\) and hence \(y-x=(-1)(x-y)\in n\Z\).

If \(x\equiv y\) and \(y\equiv z\), then \(x-y,y-z\in n\Z\). There is \(a,b\in \Z\) such that \(x-y=na\)
and \(y-z=nb\). Since \(x-z=(x-y)+(y-z)=n(a+b)\in n\Z\), \(x\equiv z\)
#+END_proof

#+BEGIN_exercise
Suppose that \(x\equiv x'\mod n\) and \(y\equiv y'\mod n\). Show that \(xy\equiv x'y'\mod n\)
#+END_exercise

#+BEGIN_proof
There is \(a,b\in\Z\) such that \(x-x'=an\) and \(y-y'=bn\). We have \(x'=x-an\), \(y'=y-bn\)
and \(x'y'=xy+n(abn-bx-ay)\). Hence \(x'y'-xy\in n\Z\)
#+END_proof

#+BEGIN_exercise
Suppose that \(p\) is a prime and \(x\not\equiv 0\mod p\). Show that there is \(y\) s.t. \(xy\equiv 1\mod p\)
#+END_exercise

#+BEGIN_proof
Since \(x\not\equiv 0\mod p\), \(p\nmid x\) and so \(x\) and \(p\) is coprime and there is \(m,n\in\Z\) such
that \(mx+pn=1\). Thus \(mx-1\in p\Z\) and so \(mx\equiv 1\mod p\)
#+END_proof
