#+TITLE: Homework4

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}
#+LATEX_HEADER: \def \EF {\text{EF}}

#+BEGIN_exercise
Let \(\call=\{P\}\), a language with only one unary relation symbol. Classify complete theories
with \(\call\), i.e. determine all complete theories with only one unary symbol
#+END_exercise

#+BEGIN_proof
Suppose \(\fM=(M,R)\) and \(\fN=(N,S)\).

1. If the universe of \(\fM\) is finite. Then \(\abs{\fM}=a\) and \(\abs{P(\fM)}=b\) for some \(a,b\in\N\)
   and \(b\le a\).

   For \(n\in\N\), let
   \begin{align*}
   &\varphi_n=\exists x_1\dots x_n(\bigwedge_{1\le i<j\le n}x_i\neq x_j\wedge\forall x(\bigwedge_{i=1}^nx=x_i))\\
   &\varphi_{n,P}=\exists x_1\dots x_n(\bigwedge_{1\le i<j\le n}x_i\neq x_j\wedge\forall x(\bigwedge_{i=1}^nx=x_i)\wedge\bigwedge_{i=1}^nP(x_i))\\
   \end{align*}
   Then \(\varphi_n\) says there are exactly \(n\) elements and \(\varphi_{n,P}\) says there are exactly \(n\)
   elements satisfying \(P\). Let \(\theta_{a,b}=\varphi_a\wedge\varphi_{b,P}\), then \(\fM\vDash\theta_{a,b}\).

   *Claim* \(\fM\cong\fN\Leftrightarrow \fM\vDash\theta_{a,b}\text{ and }\fN\vDash\theta_{a,b}\)

   Left to right is obvious. Now suppose both \(\fM\) and \(\fN\) both satisfy \(\theta_{a,b}\). Then they
   have same number of elements and have same number of elements satisfying \(P\).
   Let \(f:P(\fM)\to P(\fN)\) be a bijection as they have same cardinality and let \(f':\fM\to\fN\) be the
   bijection such that \(f'\supseteq f\). Thus for any \(a\in M\), \(Ra\Leftrightarrow Sf'(a)\) and \(f'\) is an isomorphism.

   Thus \(\fM\equiv\fN\) and any complete theory consisting of \(\theta_{a,b}\) is unique.

2. If the universe of \(\fM\) is infinite.

   For each \(n\in\N\), let
   \begin{equation*}
   \psi_n=\exists x_1\dots x_n(\bigwedge_{1\le i<j\le n}x_i\neq x_j)
   \end{equation*}
   and \(S=\{\psi_i:i\in\N\}\).
   1. If \(\abs{P(\fM)}=a\).

      Let \(\Gamma_a=S\cup\{\varphi_{a,P}\}\). For any \(p\in\N\), we show that Duplicator wins \(\EF_p(R,S)\): if
      Spoiler chooses an element from \(M\setminus P(\fM)\)(\(N\setminus P(\fN)\)), then Duplicator chooses a new element
      from \(N\setminus P(\fN)\) (\(M\setminus P(\fM)\)); if Spoiler chooses an element from \(P(\fM)\) (\(P(\fN)\)), then
      Duplicator chooses a element from \(P(\fN)\) (\(P(\fM)\)). Then we get a map \(s\)
      and \(Ra\Leftrightarrow Ss(a)\) for \(a\in\dom(s)\). Thus \(s\) is a local isomorphism and \(\fM\equiv\fN\). Hence any
      complete theory that contains \(\Gamma_a\) is unique
   2. if \(\abs{P(\fM)}\) is infinite.

      Let \(\Gamma_\omega=S\cup\{\varphi_{n,P}:n\in\N\}\). Similarly we can that prove any complete theory containing \(\Gamma_\omega\) is
      unique


   Thus we prove that there is three kinds of complete theory
   1. For each \(n\in\omega\) and \(m\le n\), there is a unique complete theory containing \(\theta_{m,n}\)
   2. For each \(n\in\omega\) there is a unique complete theory containing \(\Gamma_n\)
   3. Unique complete theory containing \(\Gamma_\omega\)
#+END_proof

#+BEGIN_exercise
Show that there is a structure \((M,+,\cdot,<,0,1)\) elementarily equivalent to \((\R,+,\cdot,<,0,1)\) s.t.
the order on \(M\) is not complete: there is a bounded set with no supremum
#+END_exercise

#+BEGIN_proof
Take \(\Q\subseteq\R\), then by Löwenheim's theorem, we can find an elementarily restriction \(\fQ\)
of \((\R,+,\cdot,<,0,1)\) whose domain \(Q\) contains \(\Q\) and \(\abs{\fQ}=\aleph_0\). Thus by Theorem 1.7 \(\fQ\) is
also a dense linear order. As every countable dense linear set is isomorphic to \(\Q\), \(\fQ\cong\Q\).
Since \(\Q\) is not complete, \(\fQ\) is also not complete.
#+END_proof

#+BEGIN_exercise
Show that the open interval \(((0,1)<))\) is an elementary substructure of \((\R,<)\)
#+END_exercise

#+BEGIN_proof
First \((\R,<)\cong((0,1),<)\) as we have the isomorphic function \(f(x)=\arctan(x)\).

We first show that \(((0,1),<)\sim_\omega(\R,<)\). For any \(p\in\N\) and game \(\EF_p(((0,1),<),(\R,<))\)
 * If Spoiler chooses \(x\in\R\), then Duplicator chooses \(y=f(x)\in(0,1)\)
 * If Spoiler chooses \(y\in(0,1)\), then Duplicator chooses \(x=f^{-1}(y)\)
The induced map \(s\) is a local isomorphism as \(s\subset f\). Thus Duplicator wins.

Thus \(((0,1),<)\) is an elementary substructure of \((\R,<)\)
#+END_proof

#+BEGIN_exercise
Show that every formula is equivalent to a "nice" formula.
#+END_exercise

#+BEGIN_proof
We prove this by induction on the complexity of \varphi
1. If \varphi is atomic formula
   1. If \varphi is of the form \(t_1(\barx)=t_2(\barx)\)

      If both of \(t_1\) and \(t_2\) are not good, then we replace \varphi
      with \(\exists y(t_1(\barx)=y\wedge t_2(\barx)=y)\).
      Obviously \(\vDash \varphi(\barx)\leftrightarrow\exists y(t_1(\barx)=y\wedge t_2(\barx)=y)\)
   2. If \varphi is of the form \(R(t_1(\barx),\dots,t_m(\barx))\)

      If among \(t_1(\barx),\dots,t_m(\barx)\), \(t_{r_1},\dots,t_{r_n}\) where \(n\le m\) are not good. Then we
      replace \varphi with
      \begin{equation*}
      \psi=\exists y_1\dots y_{n}\left( \left(R(t_1(\barx),\dots,t_m(\barx))\right)^{t_{r_1}(\barx),\dots,t_{r_n}(\barx)}_{y_1,\dots,y_n}\wedge
      \bigwedge_{i=1}^nt_{r_i}(\barx)=y_i\right)
      \end{equation*}
      and we have \(\vDash\varphi(\barx)\leftrightarrow\psi(\barx)\)
2. If \varphi is of the form \(\neg\psi\), \(\psi\wedge\theta\), \(\psi\vee\theta\) or \(\exists x\psi\). As we can transform \psi and \theta into nice
   formulas, \varphi is equivalent to a "nice" formula
#+END_proof

#+BEGIN_exercise
Let \(T\) be the set of \(\call_{\text{ring}}\)-sentences true in \((\R,+,\cdot,0,1)\). Show that \(T\) is
finitely satisfiable and complete, but does not have the witness property
#+END_exercise

#+BEGIN_proof
Let \(\fM=(\R,+,\cdot,0,1)\). Then \(T=\Th(\fM)\). As for every \(\call_{\text{ring}}\)-sentence \varphi,
either \(\fM\vDash\varphi\) or \(\fM\vDash\neg\varphi\), thus either \(\varphi\in T\) or \(\neg\varphi\in T\). Hence \(T\) is complete.

For every finite subset \(S\) of \(\Th(\fM)\), we can enumerate them as \(\varphi_1,\dots,\varphi_n\). Let \(\psi=\bigwedge_{i=1}^n\varphi_i\).
As \(\fM\vDash\psi\), \(S\) is satisfiable and thus \(\Th(\fM)\) is finitely satisfiable.

Sentence \(\varphi=\exists x(x\cdot x=1+1)\) doesn't have the witness property.
#+END_proof
