#+TITLE: Homework1

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025


#+LATEX_HEADER: \input{../../../../preamble-lite.tex}
#+LATEX_HEADER: \makeindex
#+OPTIONS: toc:nil

#+ATTR_LATEX: :options [0]
#+BEGIN_exercise
Show that \([a]_\sim=[b]_\sim\) if and only if \(a\sim b\), and that \([a]_\sim\cap[b]_\sim=\emptyset\) if \(a\not\sim b\)
#+END_exercise

#+BEGIN_proof
If \([a]_\sim=[b]_\sim\), then for all \(x\in[a]_\sim\), \(x\in[b]_\sim\). As \(a\in[a]_\sim\), \(a\in[b]_\sim\), that
is, \(a\sim b\).

If \(a\sim b\), then for all \(x\in[a]_\sim\), as \(x\sim a\) and \(a\sim b\), then \(x\sim b\) and
hence \(x\in[b]_\sim\). Thus \([a]_\sim\subset[b]_\sim\). Similarly, \([b]_\sim\subset[a]_\sim\). Hence \([a]_\sim=[b]_\sim\)

If \([a]_\sim\cap[b]_\sim=\emptyset\) and suppose \(a\sim b\). Then \([a]_\sim=[b]_\sim\). As \(a\in[a]_\sim\), \([a]_\sim\) is not
empty and hence \([a]_\sim\cap[b]_\sim\neq\emptyset\), a contradiction.

If \(a\not\sim b\) and suppose \([a]_\sim\cap[b]_\sim\neq\emptyset\), let \(x\in[a]_\sim\cap[b]_\sim\). Then \(x\sim a\) and \(x\sim b\),
and so \(a\sim b\), a contradiction
#+END_proof

#+BEGIN_exercise
label:ex1
Suppose a binary relation \((E',\approx)\) is elementary equivalent to an equivalence relation \((E,\sim)\).
Show that \(\approx\) is an equivalence relation
#+END_exercise

#+BEGIN_proof
\(S_\omega(E',E)\neq\emptyset\).
1. \(\approx\) is reflexive. For any \(x'\in E'\), as \(\emptyset\in S_\omega(E',E)\), there is a \(x\in E\) such
   that \(\{(x',x)\}\) is a local isomorphism from \(E'\) to \(E\), which means that \(x'\approx x'\) if and
   only if \(x\sim x\). Since \(\sim\) is an equivalence relation, \(x\sim x\), hence \(x'\approx x'\)
2. \(\approx\) is symmetric. For any \(x',y'\in E'\) and \(x'\approx y'\), as \(\emptyset\in S_\omega(E',E)\subset S_2(E',E)\), we have
   a local isomorphism \(\{(x',x),(y',y)\}\) from \(E'\) onto \(E\). Then \(x\sim y\) and hence \(y\sim x\)
   as \(\sim\) is symmetric. Consequently \(y'\approx x'\)
3. \(\approx\) is transitive. For any \(x',y',z'\in E'\), \(x'\approx y'\) and \(y'\approx z'\).
   As \(\emptyset\in S_\omega(E',E)\subset S_3(E',E)\), we have a local isomorphism \(\{(x',x),(y',y),(z',z)\}\) from \(E'\)
   onto \(E\). Then \(x\sim y\) and \(y\sim z\) and hence \(x\sim z\). Thus we have \(x'\approx z'\)
#+END_proof

#+BEGIN_exercise
Show that \(\calk\) is non-empty
#+END_exercise

#+BEGIN_proof
Take a injective function \(f:\omega\to E\), and we define \(S_n\) for all nonzero \(n\in\omega\)
as
\begin{equation*}
S_n=\left\{f(i)\mid i\in\omega\wedge\frac{n(n-1)}{2}\le i<\frac{n(n+1)}{2}\right\}
\end{equation*}
and \(S_\omega=E\setminus f(\omega)\). Then
\begin{equation*}
S=\{S_\omega\}\cup\bigcup_{n\in\omega}\{S_n\}
\end{equation*}
forms a partition of \(E\). And for each nonzero \(n\in\omega\), \(\abs{S_n}=n\).

Let \(\sim_S=\{(x,y)\in E^2\mid \exists \alpha\in\omega+1(x\in S_\alpha\wedge y\in S_\alpha)\}\) defined by \(S\). Then
\(\sim_S\in\calk\) and hence \(\calk\) is non-empty.
#+END_proof

#+BEGIN_exercise
Suppose that \((E,\sim)\in\calk\) and \((E',\approx)\) is elementarily equivalent to \((E,\sim)\). Show
that \((E',\approx)\in\calk\).
#+END_exercise

#+BEGIN_proof
From Exercise ref:ex1 we know that \(\approx\) is an equivalence relation on \(E'\). For each
nonzero \(n\in\omega\), \((E,\sim)\) has exactly one equivalence class of size \(n\), denoted by \(S_n=\{e_1,\dots,e_n\}\).
As \(\emptyset\in S_\omega(E,E')\subset S_{n+1}(E,E')\), we have a local isomorphism \(s\in S_1(E,E')\) such
that \(s(e_i)=e_i'\) for all \(i=1,2,\dots,n\) and \(e_i'\in E'\). Let \(S_n'=\{e_1',\dots,e_n'\}\), then each pair
of elements in \(S_n'\) is equivalent in the sense of \(\approx\). If there is \(e'\in E'\setminus S_n'\) such
that \(e'\approx e_1'\), then as \(s\) is an 1-isomorphism, there should be some other element \(e\)
in \(E\) such that \(e\sim e_1\), which is impossible. Hence \(S_n'\) is an equivalence class in \(E'\)
of size \(n\).

If there is another equivalence class \(S_n''\) of size \(n\) in \(E'\).
As \(\emptyset\in S_\omega(E',E)\subset S_{2n+1}(E',E)\), we can construct a 1-isomorphism \(r\)
with \(\dom(r)=S_n'\cup S_n''\). As \(S_n'\) and \(S_n''\) are two distinct equivalence
class, \(\im(r)\) is also a union of two distinct equivalence class of size \(n\). But \((E,\sim)\)
only has exactly one equivalence class of size \(n\), we get a contradiction. Thus
for \(n=1,2,3,\dots\), \((E',\approx)\) has exactly one equivalence class of size \(n\). Thus \((E',\approx)\in\calk\)
#+END_proof

#+BEGIN_exercise
label:ex5
Suppose that \((E,\sim)\)and \((E',\approx)\) are both in \(\calk\). Let \(s\) be a local isomorphism
from \((E,\sim)\) to \((E',\approx)\), and let \(p\ge 0\). Suppose that for every \(a\in\dom(s)\),
the \(\sim\)-equivalence class of \(a\) has the same size as the \(\approx\)-equivalence class of \(s(a)\),
or both equivalence classes have size greater than \(p\). Then \(s\) is a \(p\)-isomorphism
from \((E,\sim)\) to \((E',\cong)\)
#+END_exercise

#+BEGIN_proof

We prove this by induction on \(p\).

If \(p=0\), then \(s\) is a 0-isomorphism by definition

If \(p=n+1\). We now prove that \(s\) is a \(n+1\)-isomorphism.

For every \(e\in E\setminus\dom(s)\), we choose \(e'\in E'\) for different cases:
1. if there is a \(x\in E\) such that \(e\sim x\), then as \(\abs{[x]_\sim}=\abs{[s(x)]_\approx}\) or
   both \(\abs{[x]_\sim}\) and \(\abs{[s(x)]_\approx}\) are greater than \(n+1\), we are able to choose
   a \(e'\in E'\setminus\im(s)\) with \(e'\sim s(x)\).

2. If there is no \(x\in E\) with \(e\sim x\) and \(\abs{[e]_\sim}=m\le n\). If there is \(y\in\im(s)\)
    with \(\abs{[y]_\approx}=\abs{[e]_\sim}\), then there will be a \(n-m+1\)-isomorphism \(u\supset s\)
    maps a subset of \([s^{-1}(y)]_\sim\) onto \([y]_\approx\), otherwise there will be a contradiction
    if \(u\) is not onto. Also
    as \(n-m+1\ge 1\), \([s^{-1}(y)]_\sim=[y]_\approx\),
    which leads to another contradiction. Hence there is no \(y\in\im(s)\) with \(\abs{[y]_\approx}\). Then we pick
    an \(e'\) from the equivalence class of size \(m\) from \(E'\).

3. If there is no \(x\in E\) with \(e\sim x\) and \(\abs{[e]_\sim}>n\), then choose a element \(e'\) from a
    equivalence class \(S'_{>n}\) of size greater than \(n\)
    from \(E'\) with \(S_{>n}'\cap\im(s)=\emptyset\).

Let \(t=s\cup\{(e,e')\}\). Then \(t\) is a local isomorphism by our construction and the conditions in
exercise are satisfied. Hence \(t\) is an \(n\)-isomorphism by induction. Thus forth condition is satisfied.

The back condition is similar.

Hence \(s\) is an \(n+1\)-isomorphism
#+END_proof

#+BEGIN_exercise
Suppose that \((E,\sim)\) and \((E',\approx)\) are both in \(\calk\). Show that \((E,\sim)\) is elementarily
equivalent to \((E',\approx)\)
#+END_exercise

#+BEGIN_proof
We need to prove that for every \(p\in\omega\), \(S_p(E,E')\) is not empty. But for local
isomorphism \(\emptyset\), the condition in Exercise ref:ex5 are always satisfied and \(\emptyset\in S_p(E,E')\).
Hence \(S_p(E,E')\) are not empty for all \(p\in\omega\).

Thus \((E,\sim)\) is elementarily equivalent to \((E',\approx)\).
#+END_proof

#+BEGIN_exercise
Construct two equivalence relations \((E,\sim)\) and \((E',\approx)\) s.t. \((E,\sim)\sim_\omega(E',\approx)\) ,
but \((E,\sim)\not\sim_\infty(E',\approx)\).
#+END_exercise

#+BEGIN_proof
Let \(E=\Q,E'= \R\), and \(\sim=\{(x,y)\mid x-y\in\Z\}\).
#+END_proof
