#+TITLE: Week4
#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Find a set \(A\) and a relation \(R\subseteq A\times A\) s.t.
\begin{gather*}
\exists^\infty x\in A\exists^\infty y\in A:(x,y)\in R\\
\neg\exists^\infty y\in A\exists^\infty x\in A:(x,y)\in R\\
\end{gather*}
#+END_exercise

#+BEGIN_proof
Let \(A=\N\) and \(R\) be \(<\) on \(\N\). Then there is infinitely many \(r\in\N\) with infinitely many
elements of \(\N\) greater than it. But there is only finitely many elements which is smaller than it.
#+END_proof

#+BEGIN_exercise
Consider the structure \((\R,+,-,\cdot,0,1,\le)\). Let \(\varphi(x,y)\) be the formula \(y-1\le x\wedge x\le y+1\). Show
that \(\varphi(x,y)\) has the order property (in a monster model \(\M\succeq\R\))
#+END_exercise

#+BEGIN_proof
Let \(b_0=2\), \(b_i=\frac{1}{i}\) for \(i=1,2,\dots\). Let \(a_0=0\), \(a_i=\frac{1}{i+1}-1\)
for \(i=1,2,\dots\). Then \(a_i+1=b_{i+1}\) and hence \(b_j\in[a_i-1,a_i+1]\) for any \(i<j\). And
for \(i\ge j\), \(b_j>a_i+1\).
#+END_proof

#+BEGIN_exercise
Let \(\M\) be a monster model of \(\DLO\). Let \(\tau\in S_1(\M)\) be the type at \(+\infty\). Consider the
Morley product \(\tau\otimes\tau(x,y)\in S_2(\M)\). Show that \((\tau\otimes\tau)(x,y)\) is the unique completion of \(\tau(x)\cup\tau(y)\cup\{x<y\}\)
#+END_exercise

#+BEGIN_proof
Let \(\Sigma(x,y):=\tau(x)\cup\tau(y)\cup\{x<y\}\). First we show that \Sigma has unique extension. Otherwise, take
two \(p_1,p_2\in S_2(\M)\) containing \Sigma and suppose \(p_1,p_2\) is realized by \(x_1y_1, x_2y_2\) in \(\N\succeq\M\) respectively.
Then we have \(\M<x_1<y_1\) and \(\M<x_2<y_2\). Let \(f=\id_{\M}\cup\{(x_1,x_2),(y_1,y_2)\}\). Then \(f\) is an
order-preserving bijection from \(\M\cup\{x_1,y_1\}\) to \(\M\cup\{x_2,y_2\}\). By quantifier elimination
of \(\DLO\), \(f\) is a partial elementary map and hence \(p_1=\tp(x_1y_1/\M)=\tp(x_2y_2/\M)=p_2\), a
contradiction.

Then we show that \(\tau\otimes\tau(x,y)\supseteq\Sigma(x,y)\).

First we prove that \(\tau(x)\) is \(\emptyset\)-invariant. Let \(\Gamma(x)=\{x>a:a\in\M\}\), then for
any \(\sigma\in\Aut(\M)\), \(\sigma(\Gamma(x))=\Gamma(x)\). Then \(\sigma(\tau)\supseteq\sigma(\Gamma)=\Gamma\) and by previous exercise, \(\tau=\sigma(\tau)\).
Then we show that \(\tau\otimes\tau(x,y)\) is consistent with \(\tau(x)\cup\tau(y)\cup\{x<y\}\). For any finite parameter
set \(A\subseteq\M\), \(a,b\vDash\tau\otimes\tau(x,y)\uhr_A\) iff \(a\vDash\tau(x)\uhr_A\) and \(b\vDash\tau(y)\uhr_{Aa}\) iff \(a,b\vDash(\tau(x)\cup\tau(y)\cup\{x<y\})\uhr_A\).
Thus \(\tau\otimes\tau(x,y)\cup\tau(x)\cup\tau(y)\cup\{x<y\}\) is consistent and hence
 \(\tau\otimes\tau(x,y)\vdash\tau(x)\cup\tau(y)\cup\{x<y\}\) since \(\tau\otimes\tau(x,y)\) is complete
#+END_proof

#+BEGIN_exercise
Let \(\M\) be a monster model of a complete theory \(T\). Suppose \(\M\) is an expansion of a linear
order. Let \(p\in S_1(\M)\) be a global \(A\)-invariant 1-type. Suppose that \(p\) commutes with itself.
Show that \(p=\tp(c/\M)\) for some \(c\in\M\)
#+END_exercise

#+BEGIN_proof
For any \(a,b\vDash (p\otimes p(x,y))\uhr_A\), \(a\vDash p\uhr_A\) and \(b\vDash p\uhr_{Aa}\). Since \(p\) commutes with
itself, \(a\vDash p\uhr Ab\). Since \((\M,\le)\) is a linear order, \(x<m\vee x=m\vee x>m\in p(x)\) for any \(m\in\M\).
If \(a=b\), then \(x=a\in p(x)\) and \(p\) is realized by \(a\). Otherwise, if \(a<b\),
then \(a<x\in p(x)\) as \(b\vDash p\uhr_{Aa}\) and \(x<b\) as \(a\vDash p\uhr_{Ab}\). Hence either \(a<x\wedge x<b\in p(x)\)
or \(b<x\wedge x<a\in p(x)\).


I don't know how to continue:(
#+END_proof
