#+TITLE: 数学与当今时代

* 摘要

* 数学与科学技术的关系
    为什么是数学？

    当今社会，

    举一例：数学与计算机的关系

    为什么我要选择数学，数学与科学技术是什么关系呢？我认为，科学技术是数学的某种外化形式。计算机是离
    我们最近的科学技术之一，在这里我想论述一下计算机的一些方面与数学的关系。

    我们可以考虑一下，计算机是如何影响我们这个时代的？我们普通人使用计算机或是手机时（计算机与手机本质
    上没有什么区别，因此之后我们只会使用计算机来称呼这一系列类似的机器），我们有两个目的：
    生产与娱乐。借助处理器庞大的计算能力以及构筑在其上的各类生产力软件（比如word，photoshop），我们
    得以完成一些任务；而我们的娱乐活动，则依赖于视频、音乐与文字，但依赖于计算机，我们才能较方便地获
    取这些东西。

    归根结底，我们在利用他人写好的程序来达成我们的目的，而程序，则由各式各样的算法组成。算法是什么？
    算法就是给定一些输入，程序在接受
    这些输入这些输入后，返回一些输出。例如对于无处不在的推荐算法来说，它的输入就是某个特定用户在平时
    使用计算机或手机时的一些特征，在经过一系列运算后，返回这个用户可能感兴趣的一些结果。更抽象地说，
    我们几乎可以认为一个具体的算法就是一个“可计算”[fn:1]的函数，它的参数是我们的输入，它的值就是我们
    的输出。再进一步，我们要如何来判断什么样的结果是好的，什么样的结果是坏的？也就是说，我们需要一个
    参数来刻画我们的结果，并且我们就需要证明，我们的结果对应的参数在某个好的区间上。

    因此，事实上我们是依赖于不同的数学命题与数学定理来刻画我们的算法，进而输出我们想要的结果。所以本
    质上，算法是数学的。计算机只是科学技术的一个例子，但也是离我们的生活最近的一个例子，


    总结：因此可以说，
* 数学与社会的关系
    数学问题、数学定理会影响我们的社会吗？

    它能改变我们对世界的认知。

    我想举的第一个例子是有名的连续统假设，它是希尔伯特第一问题，说的是：

    不存在一个基数绝对大于可数集而绝对小于实数集的集合。

    抛开内容不谈，对于我们普通人来说，给我们一个问题，我们总是会认为，这要么是正确，要么是错误的，虽
    然我们证明不出来，但总会有人能将它证明出来。正如希尔伯特所言：“我们必须知道，我们终将知道”。
    但哥德尔跟科恩证明了，连续统假设独立于ZFC[fn:2]，也
    就是说，我们既不能证明它正确，也不能证明它错误，于是我们证明了它的真假与否并不可知。

    因此，不可证明

    这说明

    它的一个意义是，我们

    另一个例子与我们的生活更相近的例子是P对NP问题，它是克雷数学研究所高额悬赏的七个千禧年难题之一。
    在算法理论的发展过程中，我们会倾向于认为能够在多项式时间内能够被解决的问题是快的，记作P，而那些
    我们能够在多项式时间内验证答案的问题是慢，记作NP，这两个概念是如此广泛以致于很多基本的问题都与它
    们有关，例如以下的NP完全问题：
    * 找到一个最符合一系列DNA片段的DNA序列[[cite:&coulson1998algorithms]]。
    * 在一些特定环境中找到纳什均衡 [[cite:&conitzer2008new]]
    * 判断一个数学陈述是否短的证明[[cite:&cook1971complexity]]

    显然P是属于NP的，那么一个自然的问题是，NP是否
    属于P，也就是说P是否等于NP。计算机科学家与数学家倾向于认为它们不相等，因为目前种种迹象表明它们不
    相等，只是我们还缺乏相应的技术去证明，但这要求我们去承认有一些问题是本质上困难的，我们并不能有效
    地解决它们。而如果它们相等，用Fortnow的话说，“互联网将会变成历史的脚注”，首先与我们息息相关的公
    钥加密手段不再安全，但同时，我们能够快速地解决大多数的运筹学问题，举例来说，我们可以以最优的方式
    安排各种运输手段（飞机，火车..），同时制造业也能够通过新的算法提高它们的工作效率，减少浪费。

    以上的两个例子说明，虽然数学定理或是数学命题看起来与我们的生活很远，却能够确确实实地改变我们的观
    念，改变我们的思想。
* 通过数学而进步
    数学可以引领社会的发展吗？答案是肯定的，或者说是毋庸置疑的。总的来说

* Footnotes
[fn:2] ZFC是大多数人所使用的公理集合论。

[fn:1] 通俗的说就是一台计算机可以计算的函数，但是在数学中我们有更严谨的定义来刻画什么是可计算的，什
么是不可计算的。

* References

<<bibliographystyle link>>
bibliographystyle:unsrtnat

<<bibliography link>>
bibliography:~/notes/references.bib
