#+TITLE: Homework10

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Let \(M\) be a \kappa-saturated structure for some \(\kappa>\aleph_0\). Let \(X_i\)  be a definable subset of \(M^n\)
for \(i=1,2,\dots\). Suppose that \(X_0\subseteq\bigcup_{i=1}^\infty X_i\). Show that there is an \(n\) s.t. \(X_0\subseteq\bigcup_{i=0}^nX_i\)
#+END_exercise

#+BEGIN_proof
Suppose for each \(X_i\) , \(X_i=\varphi_i(M^n)\).

Suppose there is no such \(n\), then for any \(n\in\N\), there is \(c_n\in M\)
s.t. \(\varphi_0(c_n)\wedge\neg\bigvee_{i=1}^n\varphi_i(c_n)\). Hence consider
\begin{equation*}
\Gamma(x)=\{\varphi_0(x)\}\cup\{\neg\varphi_i(x)\mid i=1,2,\dots\}
\end{equation*}
This is finitely satisfiable by our discussion and hence realised by \(a\in M\) since \(M\) is
\kappa-saturated. Thus \(X_0\not\subseteq\bigcup_{i=1}^\infty X_i\), a contradiction
#+END_proof

#+BEGIN_exercise
Consider the structure \((\C,+,\cdot)\). Let \(\calf\) be a family of definable subsets of \(\C^1\).
Suppose \(\calf\) has the finite intersection property. If \(\abs{\calf}<\abs{\C}\), show that \(\bigcap\calf\neq\emptyset\)
#+END_exercise

#+BEGIN_proof
Suppose \(\abs{\calf}=\lambda\), then \(\calf=\{\varphi_\alpha(\C)\mid\alpha<\lambda\}\).

If all of \(\abs{\varphi_\alpha(\C)}\) are cofinite, then each \(\varphi_\alpha(x)\leftrightarrow\bigwedge_{i=1}^{n_\alpha}x\neq c_{\alpha,i}\)
where \(\abs{\neg\varphi_\alpha(\C)}=n_\alpha\) and \(\C\vDash\neg\varphi(c_{\alpha,i})\). But as \(\omega\cdot\lambda=\max\{\omega,\lambda\}<\abs{\C}\), there is \(c\in\bigcap\calf\).

Otherwise, since \(\calf\) has the finite intersection property,
\(F=\{\varphi_\alpha(x)\mid\alpha<\lambda\}\) is finitely satisfiable. Add a new constant distinct constant \(c\)
to \(L(\C)\) and then
\begin{equation*}
\Gamma=\Diag_{\el}(\C)\cup\{\varphi_\alpha(c)\mid\alpha<\lambda\}
\end{equation*}
is satisfiable and let \(\fM\vDash\Gamma\). Note that \(\abs{\varphi_\alpha(\fM)}=\abs{\varphi_\alpha(\C)}\) for all \(\alpha<\lambda\) by the fact
as \(\abs{\varphi(\C)}=n\) is definable. By the assumption, there is \(\alpha<\lambda\) s.t. \(\abs{\varphi_\alpha(\C)}=n<\omega\), then \(\fM\vDash\bigvee_{i=1}^nc=c_i\)
where \(c_i\neq c_j\) for \(i\neq j\) and \(c_i,c_j\in\varphi_\alpha(\C)\). Hence \(c\in\C\).
#+END_proof

#+BEGIN_exercise
Show that \(\C\) is \(\abs{\C}\)-saturated
#+END_exercise

#+BEGIN_proof
For any \(A\subseteq\C\) with \(\abs{A}<\abs{\C}\) and \(p\in S_n(A)\).
Then \(\abs{p}=\max\{\abs{A},\aleph_0\}<\abs{\C}\). Let \(\calf=\{\varphi(\C)\mid\varphi\in p\}\). Then \(\calf\) has the finite
intersection property since \(p\) is finitely satisfiable. Then \(\bigcap\calf\neq\empty\)  and hence \(p\) is
realised by \(c\in\bigcap\calf\). Thus \(\C\) is \(\abs{\C}\)-saturated
#+END_proof

#+BEGIN_exercise
Show that \(\R\) is not \(\abs{\R}\)-saturated
#+END_exercise

#+BEGIN_proof
Consider
\begin{equation*}
\Gamma(x)=\{x>q:q\in\Q\}
\end{equation*}
then \(\Gamma(x)\) is finitely satisfiable but it is not realised in \(\R\) since there is no such element
in \(\R\). Thus \(\R\) is not \(\aleph_1\)-saturated
#+END_proof

#+BEGIN_exercise
Let \(f:\C\to\C\) be the complex conjugation map
\begin{equation*}
f(x+iy)=x-iy\text{ for }x,y\in\R
\end{equation*}
Show that the structure \((\C,+,\cdot,f)\) is not \(\abs{\C}\)-saturated
#+END_exercise

#+BEGIN_proof
\((\R,+,\cdot,f)\) is a substructure of \((\C,+,\cdot,f)\). Suppose \(\C\) is \(\abs{\C}\)-saturated, then for
any \(p\in S_n(A)\) where \(A\subseteq\R\) and \(\abs{A}<\abs{\R}=\abs{\C}\), \(p\) is realised in \(A\) by some \(c\).
#+END_proof

#+BEGIN_exercise
Let \(M\) be an infinite structure. Show that \(M\) is not \(\abs{M}^+\)-saturated.
#+END_exercise

#+BEGIN_proof
Consider
\begin{equation*}
\Gamma(x)=\{x\neq a:a\in M\}
\end{equation*}
we can extend it to \(p(x)\in S(M)\), which is obviously not realised in \(M\). Thus \(M\) is not \(\abs{M}^+\)-saturated
#+END_proof
