#+title: Erion

* Miscellaneous
** Fish
        Magnus says to you, 'While your line is in the water, typing 'fish state' will give you clues as to
what the fish are doing and how far away they are. Responding properly to the clues will improve 
your chances of catching a fish.'


Magnus says to you, 'When the fish are swimming far out, it'll do you no good to jiggle the line.
First, you'll need to 'toss chum' to entice them to come closer. They might nibble up all of the 
chum before noticing the bait, so you may need to toss chum more than once.'


Magnus says to you, 'Once a fish is circling your bait, jiggle the line by typing 'jiggle', to
entice them to start nibbling.'


Magnus says to you, 'Once the fish are nibbling, a little patience is required, though luck will
help your chances of getting the fish to bite.'


Magnus says to you, 'When you feel the line snap taut, TUG to set the hook, and then reel them in!
But remember, you are not a skilled fisherman yet, so you may lose the catch or need to repeat 
certain steps.'
           
