#+title: Real Closed Field
#+EXPORT_FILE_NAME: ../latex/rcf/rcf.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Real Closed Field
    From [[http://homepages.math.uic.edu/~marker/orsay/orsay3.pdf][marker]] and [[cite:&bochnak2013real]]

    \(\call_r=\{+,1,\cdot,0\}\), \(\call_{or}=\{+,-,\dots,<,0,1\}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *ordering* of a field \(F\) is a total order relation \(\le\) satisfying
    1. \(x\le y\Rightarrow x+z\le y+z\)
    2. \(0\le x,0\le y\Rightarrow 0\le xy\)
    An *ordered field* \((F,\le)\) is a field equipped with an ordering \(\le\)
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A field \(F\) is *orderable* if there is a linear order < of \(F\) making \((F,<)\) an ordered field
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(F\) is *formally real* if -1 is not a sum of squares
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:7.3
    If \(F\) is a formally real field, then \(F\) is orderable. Indeed, if \(a\in F\) and \(-a\) is
    not a sum of squares of elements of \(F\), then there is an ordering of \(F\) where \(a\) is positive
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A field \(F\) is *real closed* if it is formally real with no proper formally real algebraic extensions
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(F\) be a formally real field. TFAE
    1. \(F\) is real closed
    2. \(F(i)\) is algebraically closed (where \(i^2=-1\))
    3. \(\forall a\in F\), either \(a\) or \(-a\) is a square and every polynomial of odd degree has a root
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The class of real closed fields is an elementary class of \(\call_r\)-structures
    #+END_corollary

    #+BEGIN_proof
    We can axiomatize real closed fields by
    1. axioms for fields
    2. for each \(n\ge 1\), the axiom
       \begin{equation*}
       \forall x_1\dots\forall x_n\;x_1^2+\dots+x_n^2+1\neq 0
       \end{equation*}
    3. \(\forall x\exists y(y^2=x\vee y^2+x=0)\)
    4. for each \(n\ge 0\), the axiom
       \begin{equation*}
       \forall x_0\dots\forall x_{2n}\exists y\;y^{2n+1}+\sum_{i=0}^{2n}x_iy^i=0
       \end{equation*}
    #+END_proof

    If \(F\) is a real closed field and \(0\neq a\in F\), then exactly one of \(a\) and \(-a\) is a
    square. This allows us to order \(F\) by
    #+BEGIN_center
    \(x<y\) iff \(y-x\) is a nonzero square
    #+END_center

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We let \(\RCF\) be the \(\call_{or}\)-theory axiomatized by the axioms above for real closed fields
    and the axioms for ordered fields
    #+END_definition

    The models of \(\RCF\) are exactly real closed fields with their canonical ordering. Because the
    ordering is defined by the \(\call_r\)-formula
    \begin{equation*}
    \exists z(z\neq 0\wedge x+z^2=y)
    \end{equation*}
    we have
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(F\) is a real closed field and \(X\subseteq F^n\) is definable by an \(\call_{or}\)-formula, then \(X\)
    is definable by an \(\call_r\)-formula
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    An ordered field \(F\) is real closed iff whenever \(p(X)\in F[X]\), \(a,b\in X\), \(a<b\)
    and \(p(a)p(b)<0\), there is \(c\in F\) s.t. \(a<c<b\) and \(p(c)=0\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(F\) is a formally real field, a *real closure* of \(F\) is a real closed algebraic extension
    of \(F\)
    #+END_definition

    By Zorn's Lemma, every formally real field \(F\) has a maximal formal real algebraic extension.
    This maximal extension is a real closure of \(F\)

    The real closure of a formally real field may not be unique.
    Let \(F=\Q(X)\), \(F_0=F(\sqrt{X})\), \(F_1=F(\sqrt{-X})\). By Theorem ref:7.3, \(F_0\)
    and \(F_1\)are formally real. Let \(R_i\) be a real closure of \(F_i\). There is no isomorphism
    between \(R_0\) and \(R_1\) fixing \(F\) because \(X\) is a square in \(R_0\) but not in \(R_1\).
    Thus, some work needs to be done to show that any ordered field \((F,<)\) has a real closure
    where the canonical order extends the ordering of \(F\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:7.11
    If \((F,<)\) is an ordered field, \(0<x\in F\) and \(x\) is not a square in \(F\), then we can
    extend the ordering of \(F\) to \(F(\sqrt{x})\)
    #+END_lemma

    #+BEGIN_proof
    We can extend the ordering to \(F(\sqrt{x})\) by \(0<a+b\sqrt{x}\) iff
    1. \(b=0\) and \(a>0\) or
    2. \(b>0\) and (\(a>0\) or \(x>\frac{a^2}{b^2}\)) or
    3. \(b<0\) and (\(a>0\) and \(x<\frac{a^2}{b^2}\))
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \((F,<)\) is an ordered field, there is a real closure \(R\) of \(F\) s.t. the canonical
    ordering of \(R\) extends the ordering on \(F\)
    #+END_corollary

    #+BEGIN_proof
    By successive applications of Lemma ref:7.11, we can find an ordered field \((L,<)\)
    extending \((F,<)\) s.t. every positive element of \(F\) has a square root in \(L\). We now
    apply Zorn's Lemma to find a maximal formally real algebraic extension \(R\) of \(L\). Because
    every positive element of \(F\) is a square in \(R\), the canonical ordering of \(R\) extends
    the ordering of \(F\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \((F,<)\) is an ordered field, and \(R_1\) and \(R_2\) are real closures of \(F\) where the
    canonical ordering extends the ordering of \(F\), then there is a unique field
    isomorphism \(\phi:R_1\to R_2\) that is the identity on \(F\)
    #+END_theorem

    Note that because the ordering of a real closed field is definable in \(\call_r\), \phi also preserves
    the ordering. We often say that any ordered field \((F,<)\) has a unique real closure. By this
    we mean that there is a unique real closure that extends the given ordering
* Quantifier elimination for Real Closed Fields
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    The theory \(\RCF\) admits quantifier elimination in \(\call_{or}\)
    #+END_theorem

    #+BEGIN_proof
    Suppose \(R,L\vDash\RCF\) and \(A\) is a common substructure. Then \(A\) is an ordered integral
    domain. We extend the ordering on \(A\) to its fraction field to obtain an ordered
    subfield \(F_0\subseteq K\cap L\). Let \(F\) be the real closure of \(F_0\). By uniqueness of real
    closures, \(F\) is isomorphic, as an ordered field, to the algebraic closure of \(F_0\)
    inside \(K\) and \(L\). W.L.O.G., we may assume \(F\subseteq K\cap L\)

    It suffices then to show that if \(\phi(v,w)\) is a quantifier-free formula, \(a\in F\), \(b\in K\),
    and \(K\vDash\phi(b,a)\), then there is \(b'\in F\) s.t. \(F\vDash\phi(b',a)\)

    Note that
    \begin{equation*}
    p(X)\neq 0\leftrightarrow(p(X)>0\vee-p(X)>0)
    \end{equation*}
    and
    \begin{equation*}
    p(X)\not>0\leftrightarrow(p(X)=0\vee -p(X)>0)
    \end{equation*}
    We may assume that \phi is a disjunction of conjunctions of formulas of the form \(p(v,w)=0\)
    or \(p(v,w)>0\). We may assume that there are polynomials \(p_1,\dots,p_n,q_1,\dots,q_m\in F[X]\) s.t.
    \begin{equation*}
    \phi(v,\bara)\leftrightarrow\bigwedge_{i=1}^np_i(v)=0\wedge\bigwedge_{i=1}^mq_i(v)>0
    \end{equation*}
    If any of the polynomials \(p_i(X)\) is nonzero, then \(b\) is algebraic over \(F\).
    Because \(F\) has no proper formally real algebraic extensions, in this case \(b\in F\). Thus we
    may assume that
    \begin{equation*}
    \phi(v,a)\leftrightarrow\bigwedge_{i=1}^mq_i(v)>0
    \end{equation*}
    The polynomial \(q_i(X)\) can only change signs at zeros of \(q_i\) and all zeros of \(q_i\) are
    in \(F\). Thus we can find \(c_i,d_i\in F\) s.t. \(c_i<b<d_i\) and \(q_i(x)>0\) for all \(x\in(c_i,d_i)\).
    Let \(c=\max(c_1,\dots,c_n)\) and \(d=\min(d_1,\dots,d_m)\). Then \(c<d\) and \(\bigwedge_{i=1}^mq_i(x)>0\) whenever \(c<x<d\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\RCF\) is complete, model complete and decidable. Thus \(\RCF\) is the theory of \((\R,+,\cdot,<)\).
    #+END_corollary

    #+BEGIN_proof
    By quantifier elimination, \(\RCF\) is model complete.

    Every real closed field has characteristic 0, thus the rational numbers are embedded in every
    real closed field. Therefore \(\R_{alg}\), the field of real algebraic numbers (i.e., the real
    closure of the rational numbers) is a subfield of any real closed field. Thus, for any real
    closed field \(R\), \(\R_{\alg}\prec R\), so \(R\equiv\R_{\alg}\)

    In particular, \(R\equiv\R_{\alg}\equiv\R\)
    #+END_proof
* Semialgebraic Sets
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(F\) be an ordered field. \(X\subseteq F^n\)  is *semialgebraic* if it is a Boolean combination of
    sets of the form \(\{x:p(x)>0\}\) where \(p(X)\in F[X_1,\dots,X_n]\)
    #+END_definition

    By quantifier elimination, the semialgebraic sets are exactly the definable sets.

    #+ATTR_LATEX: :options [Tarski-Seidenberg Theorem]
    #+BEGIN_corollary
    The semialgebraic sets are closed under projection
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(F\vDash\RCF\) and \(A\subseteq F^n\) is semialgebraic, then the closure (in the euclidean topology)
    of \(A\) is semialgebraic.
    #+END_corollary

    #+BEGIN_proof
    Let \(d\) be the definable function
    \begin{equation*}
    d(x_1,\dots,x_n,y_1,\dots,y_n)=z \quad\text{ iff }\quad z\ge 0\wedge z^2=\sum_{i=0}^n(x_i-y_i)^2
    \end{equation*}
    The closure of \(A\) is
    \begin{equation*}
    \{x:\forall\epsilon>0\exists y\in A\;d(x,y)<\epsilon\}
    \end{equation*}
    This set is definable, and therefore semialgebraic
    #+END_proof

    We say that a function is semialgebraic if its graph is semialgebraic.

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(F\) be a real closed field. If \(X\subseteq F^n\) semialgebraic, closed and bounded, and \(f\) is
    continuous semialgebraic function, then \(f(X)\) is closed and bounded
    #+END_corollary

    #+BEGIN_proof
    If \(F=\R\), then \(X\) is closed and bounded iff \(X\) is compact. Because the continuous image
    of a compact set is compact, the continuous image of a closed and bounded set is closed and
    bounded

    In general, there are \(a,b\in F\) and formulas \phi and \psi s.t. \(\phi(x,a)\) defines \(X\)
    and \(\psi(x,y,b)\) defines \(f(x)=y\). There is a sentence \Phi asserting:

    \(\forall v,w\)[if \(\psi(x,y,w)\) defines a continuous function with domains \(\phi(x,u)\) and \(\phi(x,u)\)
    is a closed and bounded set, then the range of the function is closed and bounded]

    As \(\R\vDash\Phi\), by the completeness of \(\RCF\), \(F\vDash\Phi\) and the range of \(f\) is closed and bounded
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(F\) be a real closed field and \(f(X)\in F(X_1,\dots,X_n)\) be a rational function. We say
    that \(f\) is *positive semidefinite* if \(f(a)\ge 0\) for all \(a\in F^n\)
    #+END_definition

    #+ATTR_LATEX: :options [Hilbert's 17th Problem]
    #+BEGIN_theorem
    If \(f\) is a positive semidefinite rational function over a real closed field \(F\), then \(f\)
    is a sum of squares of rational functions
    #+END_theorem

    #+BEGIN_proof
    Suppose that \(f(X_1,\dots,X_n)\) is a positive semidefinite rational function over \(F\) that is not
    a sum of squares. By Theorem ref:7.3, there is an ordering of \(F(X)\) so that \(f\) is
    negative. Let \(R\) be the real closure of \(F(X)\) extending the order. Then
    \begin{equation*}
    R\vDash\exists v\;f(v)<0
    \end{equation*}
    By model-completeness
    \begin{equation*}
    F\vDash\exists v\;f(v)<0
    \end{equation*}
    contradicting the fact that \(f\) is positive semidefinite
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\call\supseteq\{<\}\). Let \(T\) be an \(\call\)-theory extending the theory of linear orders. We say
    that \(T\) is *o-minimal* if for all \(\calm\vDash T\) if \(X\subseteq M\) is definable, then \(X\) is a finite
    union of points and intervals with endpoints in \(M\cup\{\pm\infty\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:7.23
    \(\RCF\) is o-minimal
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(f:\R\to\R\) is semialgebraic, then for any open interval \(U\subseteq\R\) there is a point \(x\in U\)
    s.t. \(f\) is continuous at \(x\)
    #+END_lemma

    #+BEGIN_proof
    _cast 1_: There is an open set \(V\subseteq U\) s.t. \(f\) has finite range on \(V\)

    Pick an element \(b\) in the range of \(f\) s.t. \(\{x\in V:f(x)=b\}\) is infinite. By o-minimality,
    there is an open set \(V_0\subseteq V\) s.t. \(f\) is constantly \(b\) on \(V\)

    _case 2_: Otherwise.

    We build a chain \(U=V_0\supset V_1\supset V_2\dots\) of open subsets of \(U\) s.t. the
    closure \(\barVV_{n+1}\subseteq V_n\). Given \(V_n\), let \(X\) be the range of \(f\) on \(V_n\).
    Because \(X\) is infinite, by o-minimality, \(X\) contains an interval \((a,b)\) of length at
    most \(\frac{1}{n}\). The set \(Y=\{x\in V_n:f(x)\in(a,b)\}\) contains a suitable open
    interval \(V_{n+1}\). Because \(\R\) is locally compact,
    \begin{equation*}
    \bigcap_{I=1}^\infty V_i=\bigcap_{i=1}^\infty\barVV_i\neq\emptyset
    \end{equation*}
    If \(x\in\bigcap_{i=1}^\infty V_i\), then \(f\) is continuous at \(x\)
    #+END_proof

    The proof above makes essential use of the completeness of the ordering of the reals. However,
    because the statement is first order, it is true for all real closed fields, by the completeness
    of \(\RCF\)

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(F\) be a real closed field and \(f:F\to F\) is a semialgebraic function. Then, we can
    partition \(F\) into \(I_1\cup\dots\cup I_m\cup X\) where \(X\) is finite and the \(I_j\) are pairwise
    disjoint open intervals with endpoints in \(F\cup\{\pm\infty\}\) s.t. \(f\) is continuous on each \(I_j\)
    #+END_corollary

    #+BEGIN_proof
    Let
    \begin{equation*}
    D=\{x:F\vDash\exists\epsilon>0\forall\delta>0\exists y\;\abs{x-y}<\delta\wedge\abs{f(x)-f(y)}>\epsilon\}
    \end{equation*}
    be the set of points where \(f\) is discontinuous. Because \(D\) is definable, by
    o-minimality \(D\) is either finite or has a nonempty interior. By Corollary ref:7.23 \(D\) must
    be finite.
    #+END_proof
* O-minimal expansions of \texorpdfstring{\(\R\)}{R}
    Let \(\calr=(\R,+,\cdot,<,\dots)\) be an o-minimal expansion of the reals, i.e., a structure obtained by
    adding extra structure to the reals s.t. \(\Th(\calr)\) is o-minimal. Below by definable we mean
    definable in \(\calr\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Assume \(\calr\) is an o-minimal expansion of \(\R\)
    1. Every definable subset of \(\R^n\) is a finite union of cells
    2. If \(f:X\to\R^n\) is definable, there is a finite partition of \(X\) into cells \(X_1\cup\dots\cup X_n\)
       s..t \(f|X_i\) is continuous for each \(i\). I
    #+END_theorem
