* EqMobs
        | Name        | Area          | Size | Drops |
        | Frost devil | saurus        | 8m   | trash |
        | Kz          | spider forest | 20m  | axe of thunder |
* Soloable Sets
** Spr
        | head   |                                        |   |   |
        | neck   | The necklace of the moon               |   |   |
        | cloak  | Dragon's wings                         |   |   |
        | amulet | The ancient amulet of the moon         |   |   |
        | torso  | A white robe with gold linings         |   |   |
        | arms   | ---                                    |   |   |
        | hands  | Red gloves with golden decorations     |   |   |
        | finger | Silver ring with a heartshaped diamond |   |   |
        | finger |                                        |   |   |
        | held   | Old elven staff                        |   |   |
        | belt   | Three clear flaoting orbs              |   |   |
        | legs   | ---                                    |   |   |
        | feet   | White boots with golden decorations    |   |   |
        | wield  | staff of law                           |   |   |
** Fig
* Areas
** Terray
        Try find a person called dubbit or find a man Klpsys and ask questions. A few hints are to take some
        shamen out and find a floating tower.
        
        You say 'mushrooms'
Dubbit says 'Someone came here last night and stole my mushrooms and
              I cannot even find my dog anywhere.'

You say 'daughter'

Klypsys says 'My daughter, Cheila, left a day ago to the
              near plains for collecting mushrooms. I haven't
              seen her since that. I wish someone could go and
              look for her. My bones are too old for that.'

The fortress is in the form of a square, shaped from the black
vulcanic rock in the ages past. Smooth rock faces are imbued
with subtle magic to slow its weathering. Three pairs of heavy
wheels are set on the four sides of the Fortress, buttressing its
great mass. The way how the wheels are moved is unknown and
little is know of the inhabitants of the Fortress.              
** Temple of teros
        A simple looking wooden cane
** Village
        Since the papers are all so old and delicate you can only read
through the paper that's on top of the pile. Written in shaky
writing it seems as someone has written down a desperate cry
for help;

 'It is with great despair I have decided to put down what I
believe to be my final thoughts on paper. The events of the
past few days have taxed my previously strong will, rendering
my abilities to reason near the point of a child's..'

You say 'togak'
Elene says 'Togak has disappeared. Noone has seen him ever since he left
 our house at early morning four days ago. The little dwarf guarding the
 western entrance to the village said he saw Togak leave the village early
 that morning, heading for the forest to gather some wood. But he never
 returned.. Please help me to find him.'
say husband
You say 'husband'
Elene says 'Togak and I have been married for two years now, and this is
 the first time he has ever been away for such a long time as this. This is
 not like him. No definately not like him.. Something has happened to him,
 I can feel that. Other people have mysteriously disappeared as well, and
 they never returned. Oh my..'

 You say 'help'
You sizzle with magical energy.
The barkeep whispers 'Prove that I can trust you and I am sure we will
 have something to discuss.'

        search rug -> spring

        smith drop key, 8m mob
        
