* EqMobs
        | Name        | Area          | Size | Drops |
        | Frost devil | saurus        | 8m   | trash |
        | Kz          | spider forest | 20m  | axe of thunder |
* Soloable Sets
** Pref weapon
        | Psi    | psisword             |
        | acid   | Coroding scourager   |
        | fire   |                      |
        | magic  | hand of life?        |
        | poison | Venomtongue?         |
        | elec   | sword/axe of thunder |
        | asph   |                      |
        | cold   |                      |
** Spr
|--------+----------------------------------------------------+---+---|
| head   | The black crown of spiders                         |   |   |
| neck   | A ruby necklace with a blue crystal embedded in it |   |   |
| cloak  | The cloak of the hell                              |   |   |
| amulet | The ancient amulet of the moon                     |   |   |
| torso  | The Runed Robes of the Sun                         |   |   |
| arms   | Cat fur sleeves                                    |   |   |
| hands  | Red gloves with golden decorations                 |   |   |
| finger | Silver ring with a heartshaped diamond             |   |   |
| finger |                                                    |   |   |
| held   | Old elven staff                                    |   |   |
| belt   | Three clear flaoting orbs                          |   |   |
| legs   | Spider leggings                                    |   |   |
| feet   | White boots with golden decorations                |   |   |
| wield  | --                                                 |   |   |
|--------+----------------------------------------------------+---+---|

** Fig
** Need to find where
        | legs  | The mithril leggings of Essence | -7str -3con +4dex +10int +5wis, +5-6hpr +13-14spr |
        | torso | A set of worm-eaten robes       | -3str -6con +3int +7wis, +13-14spr                |
        | torso | Dark shadowed breastplate       | -5str +5int, +17-18spr                            |
        |       |                                 |                                                   |
        | belt  | Silken cinch cord                          | +14int, +17-18spr, 5-9%channel power              |
        | belt  | A leather belt with a solid mythril buckle | -3con +7int +5wis, +15-16spr, 5-9%power blast     |
* Guilds
** Necro
         Leveless tells you '500kg for torso 150kg for head and 100kg for each limb and 25kg for each glue'
** DK
         Zorky tells you 'warden is stygian fire + dkmist (works with
necro) + deadslam + fell gravesite + call for power'
20:56:44 Zorky tells you 'power of the dead'
    6:58 Ratitsumy [party]: WIMPY
20:57:08 Zorky tells you 'use like 6 corpses, make fell gravesite,
then cast power of the dead and eat it for a nice stat boost in all
your stats for like 2-5 mins'
* Areas
** Stonemen
The elder states 'The entrance is well hidden, some lower class
                  people 'know' where it is though.'
** Eldoria
        touch tablet

    As your fingers brush the smooth surface of the stone tablet, the chamber around you fades into darkness,
and a vision unfolds before your eyes. Standing amidst a realm that shimmers with arcane energy, an ancient
mage appears before you, his presence commanding yet ethereal. Clad in regal garb that radiates power and
wisdom, a crown resting upon his brow signifies his sovereignty over the arcane mysteries. His eyes, ancient
and knowing, meet yours across the veil of time, a silent communication that transcends words. In a voice that
resonates with the very essence of magic, deep and imbued with authority, he utters a single word that seems
to echo through the ages: "Aethernis." The sound of it vibrates through your being, a call that awakens a
response deep within your soul, leaving an indelible mark upon your memory.
** Terray
        Try find a person called dubbit or find a man Klpsys and ask questions. A few hints are to take some
        shamen out and find a floating tower.
        
        You say 'mushrooms'
Dubbit says 'Someone came here last night and stole my mushrooms and
              I cannot even find my dog anywhere.'

You say 'daughter'

Klypsys says 'My daughter, Cheila, left a day ago to the
              near plains for collecting mushrooms. I haven't
              seen her since that. I wish someone could go and
              look for her. My bones are too old for that.'

The fortress is in the form of a square, shaped from the black
vulcanic rock in the ages past. Smooth rock faces are imbued
with subtle magic to slow its weathering. Three pairs of heavy
wheels are set on the four sides of the Fortress, buttressing its
great mass. The way how the wheels are moved is unknown and
little is know of the inhabitants of the Fortress.              
** Temple of teros
        A simple looking wooden cane

        * ~get bowl~ in package room
        * ~give bowl to elder~
          #+begin_quote
Exhaton burbles: 'You know, I have not always looked like this. I was
a young man once, not this old fragile shell I have become. I lead this
priesthood once in place of Zomm. I had the darkest robe and the favour of
Teros. Oh the things I did for him, horrible things. I gave my life for
serving of him and where has that lead, look at me! Laying crippled in my
own piss in a little bed!'

Exhaton burbles: 'I should have recognized his ambition. The fire in his
saucer eyes. I never saw it coming. The overtaking, but then it is the way
of our Lord. The weak shall perish from the way of the strong. Zomm was
the one who crippled me. He and that abomination at his side, Aesynica..'

Exhaton burbles: 'You cannot know how it feels when your ability to walk is
taken away from you. It is not the pain you experience when your feet are
crushed, it is knowing you will never walk again which hurts the most. He
keeps me alive in here. He even comes to see me occasionally. I'm living
proof of his victory, his fucking trophy. I know what he thinks behind that
blindfold and how his eyes shines with satisfaction when he sees me. He wants
the rest of temple to believe he is blind, but I know him. I trained him.
He is cunning, always has and always will be.'

Exhaton ponders: 'You looks like a well built adventurer, I have a suggestion
for you. Sit here next to me so that I may whisper it to you.'
          #+end_quote
        * ~sit listen exhaton~: nothing?
        * kill aesynica and ~search desk~, get a paper
          #+begin_quote
Our numbers are growing. Each day brings new willing followers.
Lambs to the slaughter.. These fools have no idea how far I am willing to
go for personal gain. Puppets, mere puppets, that is what they are to me.
Immortality will be mine and they will be the means in gaining of it.

The surgical procedure was taxing and I've felt myself weaker during the
last few weeks than ever before. The bleeding wont stop, but the faith
in our lord keeps me on my feet. The pact has been made and the ritual
has been completed, just as it was described in the scrolls. I could try
the spell right away but I am not ready yet. I must meditate and gather
my strength and consecrate my body through meditation.
          #+end_quote
          where is scrolls

** Village/Isthmas
        * Elene room
          #+begin_quote
Elene asks 'Have you seen my husband?'

You say 'husband'
Elene says 'Togak and I have been married for two years now, and this is
the first time he has ever been away for such a long time as this. This is
not like him. No definately not like him.. Something has happened to him,
I can feel that. Other people have mysteriously disappeared as well, and
they never returned. Oh my..'

You say 'togak'
Elene says 'Togak has disappeared. Noone has seen him ever since he left
our house at early morning four days ago. The little dwarf guarding the
western entrance to the village said he saw Togak leave the village early
that morning, heading for the forest to gather some wood. But he never
returned.. Please help me to find him.'
          #+end_quote
        Since the papers are all so old and delicate you can only read
through the paper that's on top of the pile. Written in shaky
writing it seems as someone has written down a desperate cry
for help;

 'It is with great despair I have decided to put down what I
believe to be my final thoughts on paper. The events of the
past few days have taxed my previously strong will, rendering
my abilities to reason near the point of a child's..'


 You say 'help'
You sizzle with magical energy.
The barkeep whispers 'Prove that I can trust you and I am sure we will
 have something to discuss.'

        search rug -> spring

        smith drop key, 8m mob
        



        Ragagrok:
        Amulet: Amulet of the dying winds.
        Hands: Black deerhide gloves.
        Belt: Ancient wyvernscale belt.
** Xytherix
        #+begin_quote
> press first knothole
You press the first knothole. You hear the wonderful sound of joyous laughter of a Forest Nymph.

> press second knothole
You press the second knothole. You hear the melodic trilling of a Nightingale.

> press third knothole
    You press the third knothole. You hear the rustling of Ancient Leaves throughout the forest, whispering
secrets.

> press fifth knothole
    You press the fifth knothole. You hear the sound of a herd of Deer as their hoof-falls thump throughout
the forest.

> press fourth knothole
You press the fourth knothole. You are disturbed by the sounds of clacking from a Terracarapid's pincers.
        #+end_quote




        In statue
        #+begin_quote
search statue
Near the base of the statue you see a complex, intricately carved rune.

You push the rune, and it activates, glowing vibrantly.
The rune slowly loses its glow.

You touch the rune, and it activates, glowing vibrantly.
The rune slowly loses its glow.
        #+end_quote
** Eldoria
        #+begin_quote
    With a wild cackle, Elara exclaims, 'The frogs have whispered their secrets today! But they wear tiny
hats, you know.'
say frogs
You say 'frogs'
    Elara suddenly looks concerned, whispering, 'The potion! It needs... more laughter! Yes, that will fix
everything!'
say potion
You say 'potion'
    With a gleeful spin, she proclaims, 'I've found the solution! But now, where did I put that pesky
problem...?'
say laughter
You say 'laughter'
The mental strain of controlling a servant drains your magical reserves.
Elara peers at you intently, muttering, 'Your aura is quite loud today. Did you remember to silence it?'
You sizzle with magical energy.
say problem
You say 'problem'
    Elara suddenly looks concerned, whispering, 'The potion! It needs... more laughter! Yes, that will fix
everything!'
        #+end_quote

        
        push eldryth,voranol,thalasir,mirendel,kynareth,halcyrix,grendor,feynora,bryaxis,dorinth

        push eldryth,voranol,thalasir,mirendel,kynareth,halcyrix,grendor,bryaxis,dorinth,feynora
