* EqMobs
        | Name        | Area          | Size | Drops |
        | Frost devil | saurus        | 8m   | trash |
        | Kz          | spider forest | 20m  | axe of thunder |
* Soloable Sets
** Pref weapon
        | Psi    | psisword             |
        | acid   | Coroding scourager   |
        | fire   |                      |
        | magic  | hand of life?        |
        | poison | Venomtongue?         |
        | elec   | sword/axe of thunder |
        | asph   |                      |
        | cold   |                      |
** Spr
|--------+----------------------------------------------------+---+---|
| head   | The black crown of spiders                         |   |   |
| neck   | A ruby necklace with a blue crystal embedded in it |   |   |
| cloak  | The cloak of the hell                              |   |   |
| amulet | The ancient amulet of the moon                     |   |   |
| torso  | The Runed Robes of the Sun                         |   |   |
| arms   | Cat fur sleeves                                    |   |   |
| hands  | Red gloves with golden decorations                 |   |   |
| finger | Silver ring with a heartshaped diamond             |   |   |
| finger |                                                    |   |   |
| held   | Old elven staff                                    |   |   |
| belt   | Three clear flaoting orbs                          |   |   |
| legs   | Spider leggings                                    |   |   |
| feet   | White boots with golden decorations                |   |   |
| wield  | --                                                 |   |   |
|--------+----------------------------------------------------+---+---|

** Fig
** Need to find where
        | legs  | The mithril leggings of Essence | -7str -3con +4dex +10int +5wis, +5-6hpr +13-14spr |
        | torso | A set of worm-eaten robes       | -3str -6con +3int +7wis, +13-14spr                |
        | torso | Dark shadowed breastplate       | -5str +5int, +17-18spr                            |
        |       |                                 |                                                   |
        | belt  | Silken cinch cord                          | +14int, +17-18spr, 5-9%channel power              |
        | belt  | A leather belt with a solid mythril buckle | -3con +7int +5wis, +15-16spr, 5-9%power blast     |
* Guilds
** Necro
         Leveless tells you '500kg for torso 150kg for head and 100kg for each limb and 25kg for each glue'
** DK
         Zorky tells you 'warden is stygian fire + dkmist (works with
necro) + deadslam + fell gravesite + call for power'
20:56:44 Zorky tells you 'power of the dead'
    6:58 Ratitsumy [party]: WIMPY
20:57:08 Zorky tells you 'use like 6 corpses, make fell gravesite,
then cast power of the dead and eat it for a nice stat boost in all
your stats for like 2-5 mins'
* Areas
** Stonemen
The elder states 'The entrance is well hidden, some lower class
                  people 'know' where it is though.'
** Eldoria
        touch tablet

    As your fingers brush the smooth surface of the stone tablet, the chamber around you fades into darkness,
and a vision unfolds before your eyes. Standing amidst a realm that shimmers with arcane energy, an ancient
mage appears before you, his presence commanding yet ethereal. Clad in regal garb that radiates power and
wisdom, a crown resting upon his brow signifies his sovereignty over the arcane mysteries. His eyes, ancient
and knowing, meet yours across the veil of time, a silent communication that transcends words. In a voice that
resonates with the very essence of magic, deep and imbued with authority, he utters a single word that seems
to echo through the ages: "Aethernis." The sound of it vibrates through your being, a call that awakens a
response deep within your soul, leaving an indelible mark upon your memory.
** Terray
        Try find a person called dubbit or find a man Klpsys and ask questions. A few hints are to take some
        shamen out and find a floating tower.
        
        You say 'mushrooms'
Dubbit says 'Someone came here last night and stole my mushrooms and
              I cannot even find my dog anywhere.'

You say 'daughter'

Klypsys says 'My daughter, Cheila, left a day ago to the
              near plains for collecting mushrooms. I haven't
              seen her since that. I wish someone could go and
              look for her. My bones are too old for that.'

The fortress is in the form of a square, shaped from the black
vulcanic rock in the ages past. Smooth rock faces are imbued
with subtle magic to slow its weathering. Three pairs of heavy
wheels are set on the four sides of the Fortress, buttressing its
great mass. The way how the wheels are moved is unknown and
little is know of the inhabitants of the Fortress.              
** Temple of teros
        A simple looking wooden cane

        * ~get bowl~ in package room
        * ~give bowl to elder~
          #+begin_quote
Exhaton burbles: 'You know, I have not always looked like this. I was
a young man once, not this old fragile shell I have become. I lead this
priesthood once in place of Zomm. I had the darkest robe and the favour of
Teros. Oh the things I did for him, horrible things. I gave my life for
serving of him and where has that lead, look at me! Laying crippled in my
own piss in a little bed!'

Exhaton burbles: 'I should have recognized his ambition. The fire in his
saucer eyes. I never saw it coming. The overtaking, but then it is the way
of our Lord. The weak shall perish from the way of the strong. Zomm was
the one who crippled me. He and that abomination at his side, Aesynica..'

Exhaton burbles: 'You cannot know how it feels when your ability to walk is
taken away from you. It is not the pain you experience when your feet are
crushed, it is knowing you will never walk again which hurts the most. He
keeps me alive in here. He even comes to see me occasionally. I'm living
proof of his victory, his fucking trophy. I know what he thinks behind that
blindfold and how his eyes shines with satisfaction when he sees me. He wants
the rest of temple to believe he is blind, but I know him. I trained him.
He is cunning, always has and always will be.'

Exhaton ponders: 'You looks like a well built adventurer, I have a suggestion
for you. Sit here next to me so that I may whisper it to you.'
          #+end_quote
        * ~sit listen exhaton~: nothing?
        * kill aesynica and ~search desk~, get a paper
          #+begin_quote
Our numbers are growing. Each day brings new willing followers.
Lambs to the slaughter.. These fools have no idea how far I am willing to
go for personal gain. Puppets, mere puppets, that is what they are to me.
Immortality will be mine and they will be the means in gaining of it.

The surgical procedure was taxing and I've felt myself weaker during the
last few weeks than ever before. The bleeding wont stop, but the faith
in our lord keeps me on my feet. The pact has been made and the ritual
has been completed, just as it was described in the scrolls. I could try
the spell right away but I am not ready yet. I must meditate and gather
my strength and consecrate my body through meditation.
          #+end_quote
          where is scrolls

** Village/Isthmas
        * Elene room
          #+begin_quote
Elene asks 'Have you seen my husband?'

You say 'husband'
Elene says 'Togak and I have been married for two years now, and this is
the first time he has ever been away for such a long time as this. This is
not like him. No definately not like him.. Something has happened to him,
I can feel that. Other people have mysteriously disappeared as well, and
they never returned. Oh my..'

You say 'togak'
Elene says 'Togak has disappeared. Noone has seen him ever since he left
our house at early morning four days ago. The little dwarf guarding the
western entrance to the village said he saw Togak leave the village early
that morning, heading for the forest to gather some wood. But he never
returned.. Please help me to find him.'
          #+end_quote
        Since the papers are all so old and delicate you can only read
through the paper that's on top of the pile. Written in shaky
writing it seems as someone has written down a desperate cry
for help;

 'It is with great despair I have decided to put down what I
believe to be my final thoughts on paper. The events of the
past few days have taxed my previously strong will, rendering
my abilities to reason near the point of a child's..'


 You say 'help'
You sizzle with magical energy.
The barkeep whispers 'Prove that I can trust you and I am sure we will
 have something to discuss.'

        search rug -> spring

        smith drop key, 8m mob
        



        Ragagrok:
        Amulet: Amulet of the dying winds.
        Hands: Black deerhide gloves.
        Belt: Ancient wyvernscale belt.
** Xytherix
        #+begin_quote
> press first knothole
You press the first knothole. You hear the wonderful sound of joyous laughter of a Forest Nymph.

> press second knothole
You press the second knothole. You hear the melodic trilling of a Nightingale.

> press third knothole
    You press the third knothole. You hear the rustling of Ancient Leaves throughout the forest, whispering
secrets.

> press fifth knothole
    You press the fifth knothole. You hear the sound of a herd of Deer as their hoof-falls thump throughout
the forest.

> press fourth knothole
You press the fourth knothole. You are disturbed by the sounds of clacking from a Terracarapid's pincers.
        #+end_quote




        In statue
        #+begin_quote
search statue
Near the base of the statue you see a complex, intricately carved rune.

You push the rune, and it activates, glowing vibrantly.
The rune slowly loses its glow.

You touch the rune, and it activates, glowing vibrantly.
The rune slowly loses its glow.
        #+end_quote
** Eldoria
        #+begin_quote
    With a wild cackle, Elara exclaims, 'The frogs have whispered their secrets today! But they wear tiny
hats, you know.'
say frogs
You say 'frogs'
    Elara suddenly looks concerned, whispering, 'The potion! It needs... more laughter! Yes, that will fix
everything!'
say potion
You say 'potion'
    With a gleeful spin, she proclaims, 'I've found the solution! But now, where did I put that pesky
problem...?'
say laughter
You say 'laughter'
The mental strain of controlling a servant drains your magical reserves.
Elara peers at you intently, muttering, 'Your aura is quite loud today. Did you remember to silence it?'
You sizzle with magical energy.
say problem
You say 'problem'
    Elara suddenly looks concerned, whispering, 'The potion! It needs... more laughter! Yes, that will fix
everything!'
        #+end_quote

        
        push eldryth,voranol,thalasir,mirendel,kynareth,halcyrix,grendor,feynora,bryaxis,dorinth

        push eldryth,voranol,thalasir,mirendel,kynareth,halcyrix,grendor,bryaxis,dorinth,feynora
* Eq mobs
Mounted head of Breastesses (deceased)
Mounted head of Santa Claus is here wishing you Merry Christmas (deceased)
Mounted head of A sleek, dark brown squirrel (deceased)
Mounted head of A furious elven druid (deceased)
Mounted head of A Spectral Aspect of A Tyranid Hive Tyrant (undead) (deceased)
Mounted head of A headless horseman riding a fiery nightmare steed (deceased)
Mounted head of Umbaghtor, the guardian of the jell-o (deceased)
Mounted head of Mandok, the leader of the black brotherhood (deceased)
Mounted head of A Guild-sworn toadman bodyguard (deceased)
Mounted head of Jander Sunstar the gold elf (undead) (deceased)
Mounted head of Hastur, the King in Yellow (deceased)
Mounted head of A huge storm cloud (deceased)
Mounted head of King Overen Dowd, Noble Monarch (deceased)
Mounted head of A Spectral Aspect of Yaga S'laad the Djinni (undead) (deceased)
Mounted head of Nasty parasite looking like a worm (deceased)
Mounted head of Glaun the Listener (deceased)
Mounted head of Niklomdeziu the Leprachaun King wearing a red hat (deceased)
Mounted head of A Singing Simulacrum of Shu (deceased)
Mounted head of A massive black Tarantula (deceased)
Mounted head of A Malformed Effigy of A Vorlon Miner (deceased)
Mounted head of The Master of Espionage (deceased)
2 times Mounted head of Deco'ryah the exiled (undead) (deceased)
4 times Mounted head of A part of a gargantuan jell-o slashing its tentacles (deceased)
Mounted head of Lucifer's druggist stands here getting high on opium. (deceased)
Mounted head of Tereluo, the merfolk chronicler (enraged) (deceased)
Mounted head of A Spectral Aspect of Benard, the Dwarven King (undead) (deceased)
Mounted head of Claudia Venicus, The commander of the united forces of Towanda (deceased)
Mounted head of Commander Drayl Grathar the Skeleton (undead) (deceased)
Mounted head of Rob, the wandering white zombie (undead) (deceased)
Mounted head of The Guildmaster of the Mage Hobgoblins (deceased)
Mounted head of The king maple stands here. (deceased)
Mounted head of A spellcasting elf (deceased)
2 times Mounted head of Gaug, Tyrant of the Swamps (putrid white aura) (deceased)
Mounted head of Pendrath, King of Dragons (deceased)
4 times Mounted head of The Statue of Ffor (deceased)
Mounted head of A huge snake-like Lavaworm (deceased)
Mounted head of Devourer, huge spider with human head (enraged) (deceased)
Mounted head of Ashara Tazerak, Lady of the Grave (deceased)
2 times Mounted head of Balizaar the Sorcerer Highlord (deceased)
Mounted head of Kz the God of Thunder (deceased)
Mounted head of Ioree the Listener (enraged) (deceased)
Mounted head of A Guild-sworn toadman guard (deceased)
Mounted head of A large purple worm (deceased)
Mounted head of Modran the Mystic Sorcerer Toadman (deceased)
2 times Mounted head of Tohaphme, Elemental Fiend of the Void (deceased)
Mounted head of Tythus the necromancer, destroyer of worlds (glowing magneta) (enraged) (deceased)
2 times Mounted head of Gahren the dragonslayer (deceased)
2 times Mounted head of Devourer, huge spider with human head (deceased)
Mounted head of Azmog, the master disciplinarian (deceased)
Mounted head of Tra'Xiah the Slimy, gatekeeper of the misty swamps (deceased)
Mounted head of Graks the cross-eyed cyclops hunter is hunting a wabbit here (deceased)
Mounted head of A Spectral Aspect of Grim Reaper the Hobbit (undead) (deceased)
Mounted head of A part of a gargantuan jell-o covered with dozens of mouths (deceased)
Mounted head of The fabled unicorn is 1 feet deep in mud (deceased)
2 times Mounted head of Zotha, the lesser god of cold (enraged) (deceased)
3 times Mounted head of 0 (deceased)
Mounted head of A Guardian of Lucifer standing here attacking you. (undead) (deceased)
Mounted head of A tsarist soldier (deceased)
Mounted head of Morkeveilian Maguis the Dark Mage. (deceased)
2 times Mounted head of A part of a gargantuan jell-o riddled with eyeballs (deceased)
Mounted head of Qen Tie the Kungfu Master (deceased)
Mounted head of A Weakened Aspect of A Tyranid Hive Tyrant (undead) (deceased)
Mounted head of Niklomdeziu the Leprechaun King wearing a yellow hat (deceased)
Mounted head of A Spectral Aspect of A Vorlon Miner (undead) (deceased)
Mounted head of Remmoraz, the Elemental Prince of Fire (deceased)
2 times Mounted head of Strange twisting portal constantly changing shape (deceased)
Mounted head of A Pedlar for Lucifer stands here designing shoes. (deceased)
Mounted head of Niklomdeziu the Leprechaun King wearing a green hat (deceased)
Mounted head of A Soothing Simulacrum of Earendil (deceased)
Mounted head of A Spectral Aspect of Elrond, the King of Rivendell (undead) (deceased)
Mounted head of Gyaratkh, the vile Dweller from the Beyond (deceased)
Mounted head of Epimetreus, High Sorcerer-Mage of Aquilonia (deceased)
Mounted head of Tythus the necromancer, destroyer of worlds (glowing orange) (deceased)
4 times Mounted head of A titanic sandworm (deceased)
Mounted head of A massive greyish beast gathering speed (deceased)
Mounted head of Yeao the Holy Paladin (deceased)
Mounted head of A zombie servant of Maeve, formerly known as Earendil (undead) (deceased)
Mounted head of Jarenz the Listener (enraged) (deceased)
Mounted head of A charnel carrion moth (enraged) (deceased)
Mounted head of Wexan the Listener (deceased)
Mounted head of The King of Ringwraiths (undead) (deceased)
Mounted head of Grytha, the troll chieftain (deceased)
3 times Mounted head of Amon Algaab, The Duke of Decay (undead) (deceased)
Mounted head of Laraf, leader of the illusionists (deceased)
Mounted head of Captain Rennil, knight captain of the guard (deceased)
Mounted head of Tang Tu, the Master of Monks (deceased)
Mounted head of Tolso the Listener (enraged) (deceased)
Mounted head of Niklomdeziu the Leprachaun King wearing a black hat (deceased)
Mounted head of A horrifying skeleton knight (undead) (deceased)
2 times Mounted head of Deschoga the Djinni, Unholy Master of the Assassins (deceased)
Mounted head of The ancient lich Syphus is here cackling madly (undead) (deceased)
Mounted head of A golem shaped out of magical lava (deceased)
Mounted head of A Lawyer for Lucifer stands here writing laws. (deceased)
Mounted head of A Spectral Aspect of Bubba the Shop Owner (undead) (deceased)
2 times Mounted head of Lady Kirvana, Elemental Goddess of Fire and Destruction (deceased)
Mounted head of Hurthang the Cold, high priest of Belinik (deceased)
Mounted head of King Cleaving Tooth (deceased)
Mounted head of A Weakened Aspect of Ralgar Shaddles the Dwarf (undead) (deceased)
Mounted head of Gaug, Tyrant of the Swamps (nauseating blue aura) (deceased)
Mounted head of Pipra the Listener (deceased)
Mounted head of A Spectral Aspect of Durandal Dunderdeed the Thrikhren (undead) (deceased)
Mounted head of Samas, the Grand Fathomer (deceased)
Mounted head of Kaira, The Evil Penguin of Underworld (deceased)
Mounted head of Blazing fire shade (deceased)
Mounted head of A Guardian of Lucifer standing here attacking you. (deceased)
2 times Mounted head of Count Strahd von Zarovich the lord of Barovia (undead) (deceased)
Mounted head of Maeve, former healer of the fortress (undead) (deceased)
Mounted head of Ec'lor, the master of stone and time (deceased)
Mounted head of The sexy whore of Lucifer stands here trying to torture you. (deceased)
Mounted head of A 15 headed hideous monster (deceased)
Mounted head of Orcus, The Prince of the undead (death black aura) (deceased)
Mounted head of A Spectral Aspect of Troops Olympic the Treant (undead) (deceased)
2 times Mounted head of Ashathetron the golden dragon (deceased)
Mounted head of Bituliini the wild cat (following furry) (deceased)
Mounted head of Gaug, Tyrant of the Swamps (diseased yellow aura) (deceased)
Mounted head of Tereluo, the merfolk chronicler (deceased)
2 times Mounted head of The Guardian of Thunderdome (deceased)
Mounted head of Nyak the Listener (deceased)
Mounted head of The sinister Lady Ulrika, a widowed Necromancer seeking revenge (undead) (deceased)
Mounted head of Grimoan the gremlin master (deceased)
2 times Mounted head of Jadrele the former sorceress of the fortress (undead) (deceased)
Mounted head of Sylrith, Dragon Queen (deceased)
2 times Mounted head of Yith'Sehta, the Greater Medusa (deceased)
2 times Mounted head of Tiamat the celestial dragon of evil <sparkling dark aura> (deceased)
Mounted head of Niklomdeziu the Leprachaun King wearing a grey hat (deceased)
Mounted head of Shogun Naganoro, ruler of the Melarni (deceased)
Mounted head of Poor citizen stands here grinning. (deceased)
Mounted head of Ignatzz, High Mage of Cleaving Tooth (deceased)
Mounted head of A gigantic kraken (deceased)
Mounted head of The village elder is here staring at the crystal (deceased)
2 times Mounted head of Ragagrok the fearsome tribe leader (furious) (deceased)
Mounted head of Dehrait Sarak, the ancient lich mage (undead) (deceased)
Mounted head of Bertti the large bear (following earendil) (deceased)
2 times Mounted head of A pair of crude stone hands, which try to get you (deceased)
Mounted head of Amon Algaab, The Duke of Decay (undead) (enraged) (deceased)
Mounted head of A Spectral Aspect of Ralgar Shaddles the Dwarf (undead) (deceased)
2 times Mounted head of Malec-Keth, Fire Giant warrior (deceased)
Mounted head of Hfran the alchemist (deceased)
Mounted head of Gelka, the king of the thieves (deceased)
Mounted head of Lyazar, the silent watcher (undead) (enraged) (deceased)
Mounted head of Henri Morgan the Pirate King (deceased)
Mounted head of Yeao the Evil Lord, Emperor of the Underworld (undead) (deceased)
Mounted head of Kharam-naokh the unholy, evil necromancer (deceased)
Mounted head of A Spellweaving Simulacrum of Steele (deceased)
3 times Mounted head of Zi'taq the Lich Lord (undead) (deceased)
Mounted head of Sucky abjurer (deceased)
Mounted head of Melkyn the Ancient Lorekeeper (enraged) (deceased)
Mounted head of Demon Hunter summoned by Priest (deceased)
Mounted head of Slime leader is here oozing in the pool. (deceased)
Mounted head of The Guildmaster of the Cleric Goblins (deceased)
