#+TITLE: week 1
#+AUTHOR: 陈淇奥@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}

#+ATTR_LATEX: :options [1.1.5]
#+BEGIN_exercise
令\(T\)为命题逻辑中的理论
1. 请验证\(\calb(T)=(B,+,\cdot,-,0,1)\)是一个布尔代数
2. \(T\)是一致的当且仅当\(\calb(T)\)是非平反的
#+END_exercise

#+BEGIN_proof
1. 下面验证\(\calb(T)\)满足布尔代数公理。对于任意公式\([\alpha],[\beta],[\gamma]\in B\)
   1. ​
       \begin{align*}
       [\alpha]+([\beta]+[\gamma])&=[\alpha]+[\beta\vee\gamma]=[\alpha\vee(\beta\vee\gamma)]\\
       &=[(\alpha\vee\beta)\vee\gamma]=[\alpha\vee\beta]+[\gamma]=([\alpha]+[\beta])+[\gamma]\\
       [\alpha]\cdot([\beta]\cdot[\gamma])&=[\alpha]\cdot[\beta\wedge\gamma]=[\alpha\wedge(\beta\wedge\gamma)]\\
       &=[(\alpha\wedge\beta)\wedge\gamma]=[\alpha\wedge\beta]\cdot[\gamma]=([\alpha]\cdot[\beta])\cdot[\gamma]
       \end{align*}
   2. ​
       \begin{align*}
       [\alpha]+[\beta]&=[\alpha\vee\beta]=[\beta\vee\alpha]=[\beta]+[\alpha]\\
       [\alpha]\cdot[\beta]&=[\alpha\wedge\beta]=[\beta\wedge\alpha]=[\beta]\cdot[\alpha]
       \end{align*}
   3. ​
        \begin{align*}
        [\alpha]+([\alpha]\cdot[\beta])&=[\alpha]+[\alpha\wedge\beta]=[\alpha\vee(\alpha\wedge\beta)]=[\alpha]\\
        [\alpha]\cdot([\alpha]+[\beta])&=[\alpha]\cdot[\alpha\vee\beta]=[\alpha\wedge(\alpha\vee\beta)]=[\alpha]
        \end{align*}
   4. ​
       \begin{align*}
        [\alpha]\cdot([\beta]+[\gamma])&=[\alpha]\cdot[\beta\vee\gamma]=[\alpha\wedge(\beta\vee\gamma)]\\
        &=[(\alpha\wedge\beta)\vee(\alpha\wedge\gamma)]=([\alpha]\cdot[\beta])+([\alpha]\cdot[\gamma])\\
        [\alpha]+([\beta]\cdot[\gamma])&=[\alpha\vee(\beta\wedge\gamma)]=[(\alpha\vee\beta)\wedge(\alpha\vee\gamma)]\\
        &=([\alpha]+[\beta])\cdot([\alpha]+[\gamma])
       \end{align*}
   5. ​
       \begin{align*}
       [\alpha]+(-[\alpha])&=[\alpha]+[\neg\alpha]=[\alpha\vee\neg\alpha]=1\\
       [\alpha]\cdot(-[\alpha])&=[\alpha]\cdot[\neg\alpha]=[\alpha\wedge\neg\alpha]=0
       \end{align*}
2. 若\(T\)不一致，则对于任意公式\(\alpha,\beta\)，总有\(T\vdash\alpha\leftrightarrow\beta\)，因此\(\abs{B}=1\)，\(\calb(T)\)平凡

   若\(\calb(T)\)是平凡的，于是对于任意公式\(\alpha\)与公式\(\beta\in T\)，有\(T\vdash\beta\leftrightarrow\alpha\)，于是\(T\vdash\alpha\)。因此\(T\)不一
   致
#+END_proof

#+ATTR_LATEX: :options [1.1.8]
#+BEGIN_exercise
令\(B=\{Y\subseteq X\mid Y\text{是有穷的或余有穷的}\}\)，则\(X,\emptyset\in B\)。证明\(B\)对\(\cap,\cup,-\)封闭，所以\(\calb\)是一个
布尔代数，是一个集合代数
#+END_exercise

#+BEGIN_proof
对于任意\(X,Y\in B\)，
1. 若\(X,Y\)有穷，则\(X\cap Y\)有穷，\(X\cup Y\)有穷，\(-X\)余有穷
2. 若\(X\)有穷，\(Y\)余有穷，则\(X\cap Y\)余有穷，\(X\cup Y\)余有穷
3. 若\(X\)余有穷，\(Y\)有穷，则\(X\cap Y，X\cup Y\)余有穷，\(-X\)有穷
4. 若\(X,Y\)余有穷，则\(X\cap Y,X\cup Y\)余有穷
#+END_proof

#+ATTR_LATEX: :options [1.1.9]
#+BEGIN_exercise
证明不存在基数为3的布尔代数。一个有穷的布尔代数，其基数需要满足什么条件？
#+END_exercise

#+BEGIN_proof
若存在基数为3的布尔代数\(\calb\)，则令\(B=\{0,1,a\}\)。

如果 \(-a=0\),那么 \(a+(-a)=a+0=a+(a\cdot(-a))=a\neq 1\)，矛盾。
如果\(-a=1\)，那么\(a\cdot(-a)=a\cdot 1=a\cdot(a+(-a))=a\neq 0\)，矛盾。
如果\(-a=a\)，那么\(a=a\cdot 1=a\cdot(a+a)=a\cdot a+a\cdot a=0+0=0\)，矛盾。

因此不存在基数为3的布尔代数。

\(\abs{\calb}=2^n\) for some \(n\)
#+END_proof

#+ATTR_LATEX: :options []
#+BEGIN_lemma
给定布尔代数\(\calb\)，对于任意\(a,b,c\in B\)
1. \(a+0=a\)
2. \(a\cdot 1=a\)
3. 若\(a+b=1\)且\(a\cdot b=0\)，则\(b=-a\)
4. \(-(a\cdot b)=(-a)+(-b)\)。\(-(a+b)=(-a)\cdot(-b)\)
5. \(--a=a\)
#+END_lemma

#+BEGIN_proof
1. \(a+0=a+(a\cdot(-a))=a\)
2. \(a\cdot 1=a\cdot(a+(-a))=a\)
3. \(b=b+0=b+a\cdot(-a)=(a+b)\cdot(b+(-a))=1\cdot(b+(-a))=(a+(-a))\cdot(b+(-a))=(-a)+(a\cdot b)=-a\)
4. \((-a)+(-b)+(a\cdot b)=ab+(-a)+(-b)\cdot(a+-a)=a(b+-b)+(-a)(1+-b)=a+(-a)=1\).

   \((a\cdot b)\cdot(-a+-b)=ab(-a)+ab(-b)=0+0=0\).

   同理可得\(-(a+b)=(-a)\cdot(-b)\)
5. 由3可知
#+END_proof

#+ATTR_LATEX: :options [1.1.10]
#+BEGIN_exercise
\(1\to 2\): 定义

\(2\to 3\): 对任意\(a,b\in A\),  \(f(a\cdot b)=f(--(a\cdot b))=-f((-a)+(-b))=-(-f(a)+-f(b))=f(a)\cdot f(b)\)

\(3\to 2\): 对任意\(a,b\in A\)，\(f(a+b)=f(--(a+b))=-f((-a)\cdot(-b))=f(a)+f(b)\)

\(2\to 4\): 对任意\(a,b\in A\), \(f(1)=f(a+(-a))=f(a)+-f(a)=1\), \(f(0)=f(-1)=-f(1)=1\)。若\(a\cdot b=0\)，
则\(f(a\cdot b)=f(0)=0\)

\(4\to 2\): 对任意\(a\in A\) \(f(-a)\cdot f(a)=f(-a\cdot a)=0\)， \(f(-a)+f(a)=f(-a+a)=f(1)=1\)，因
此\(f(-a)=-f(a)\)

因此\(4\leftrightarrow 3\leftrightarrow 2\)，而\(4\wedge 3\wedge 2\to 1\)，因此\(2\to 1\)
#+END_exercise
