#+title: Basic Valuation Theory

#+AUTHOR: Chen Qi'ao

#+EXPORT_FILE_NAME: ../..//latex/ModelTheoryReadingGroup/BasicValuationTheory.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../../preamble.tex}
#+LATEX_HEADER: \makeindex
#+OPTIONS: toc:nil
* COMMENT CheckBox [12/12]
    * [X] absolute value
    * [X] \(p\)-adic numbers and formal series
    * [X] topology
    * [X] completion
    * [X] completions satisfy Hensel's Lemma
    * [X] absolute values are either archimedean or non-archimedean
    * [X] archimedean absolute values are boring
    * [X] valuations are a generalization of non-archimedean absolute values
    * [X] valuations can be understood in terms of valuation rings
    * [X] henselianity
    * [X] henselianity can be characterized in terms of extending valuations
    * [X] henselianity can be characterized in terms of Hensel's Lemma. It's a first-order property
        henselian ring is a first order property


* Absolute Values
** Absolute Values - Completions
    Let \(K\) be a field. An *absolute value* on \(K\) is a map
    \begin{equation*}
    \abs{\;}:K\to\R
    \end{equation*}
    satisfying the following axioms for all \(x,y\in K\)
    1. \(\abs{x}>0\) for all \(x\neq 0\), and \(\abs{0}=0\)
    2. \(\abs{xy}=\abs{x}\abs{y}\)
    3. \(\abs{x+y}\le\abs{x}+\abs{y}\)

    The absolute value sending all \(x\neq 0\) to 1 is called the *trivial* absolute value on \(K\).

    Observation: \(\abs{1}^2=\abs{1^2}=\abs{1}\), \(\abs{1}=1=\abs{-1}\), \(\abs{x}=\abs{-x}\) for all
    \(x\in K\), \(\abs{x^{-1}}=\abs{x}^{-1}\) for \(x\neq 0\).

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The set \(\{\abs{n\cdot 1}\mid n\in\Z\}\) is bounded iff \(\abs{\;}\) satisfies the "ultrametric" inequality
    \begin{equation}
    \label{1.2}
    \abs{x+y}\le\max\{\abs{x},\abs{y}\}
    \end{equation}
    for all \(x,y\in K\)
    #+END_proposition

    #+BEGIN_proof
    \(\Leftarrow\): Easy, bounded by 1

    \(\Rightarrow\): let \(\abs{n\cdot 1}\le C\), then
    \begin{equation*}
    \abs{x+y}^n=\abs{(x+y)^n}\le\sum_\nu\abs{\binom{n}{\nu}x^\nu y^{n-\nu}}\le(n+1)C\max(\abs{x},\abs{y})^n
    \end{equation*}
    #+END_proof

    If an absolute value satisfies eqref:1.2, it is called *non-archimedean*; otherwise it is called
    *archimedean*. Clearly, if \(\tchar K\neq 0\), \(K\) cannot carry any archimedean absolute value.

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let
    \begin{equation*}
    \abs{x}_0=
    \begin{cases}
    x&x\ge 0\\
    -x&x\le 0
    \end{cases}
    \end{equation*}
    for all \(x\in\R\); we call \(\abs{\;}_0\) the *usual* absolute value on \(\R\). This is an
    archimedean absolute value.
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    For every prime \(p\), the *\(p\)-adic* absolute value \(\abs{\;}_p\) on \(\Q\) is defined by
    \(\abs{0}_p=0\) and
    \begin{equation*}
    \abs{p^\nu\frac{m}{n}}_p=\frac{1}{e^\nu}
    \end{equation*}
    where \(\nu\in\Z\), and \(n,m\in\Z\setminus\{0\}\) are not divisible
    by \(p\). In this case
    \begin{equation*}
    \{\abs{n\cdot 1}_p\mid n\in\Z\}=\{e^{-\nu}\mid\nu\in\N\}
    \end{equation*}
    is bounded in \(\R\).
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(F\) be a field and let \(F[[T]]=\{\sum_{i=0}^\infty a_iT^i\mid a_i\in F\}\), which is called
    the *formal power series over \(F\)*. We can define the absolute value \(\abs{\;}\) as
    \begin{equation*}
    \abs{f}=e^{-m}
    \end{equation*}
    when \(f=\sum_{i=m}^\infty a_iT^i\) where \(a_m\neq 0\) .
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    label:e1.1.4
    We define for every irreducible polynomial \(p\in k[X]\), \(k\) a field, the following absolute
    value \(\abs{\;}_p\) on the rational function field \(K=k(X)\):
    Let \(\abs{0}_p=0\) and
    \begin{equation*}
    \abs{p^\nu\frac{f}{g}}_p=\frac{1}{e^\nu}
    \end{equation*}
    where \(\nu\in\Z\) and \(f,g\in k[X]\setminus\{0\}\) are not divisible by \(p\). Hence the
    set \(\{\abs{n\cdot 1}_p\mid n\in\Z\}\) is bounded in \(\R\).
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(A\) is a domain, \(K\) is the fraction field of \(A\) and \(\abs{\;}\) is an absolute
    value, then we can uniquely extend \(\abs{\;}\) to \(K\)
    #+END_proposition

    #+BEGIN_proof
    For any \(a,b\in A\) and \(b\neq 0\),
    \begin{equation*}
    \abs{a}=\abs{b\cdot\frac{a}{b}}=\abs{b}\abs{\frac{a}{b}}
    \end{equation*}
    #+END_proof

    An absolute value \(\abs{\;}\) on \(K\) defines a metric by taking \(\abs{x-y}\) as distance,
    for \(x,y\in K\). In particular, \(\abs{\;}\) induces a topology on \(K\) by taking basic open
    balls \(B_\epsilon(a)=\{x:\abs{x-a}<\epsilon\}\).

    Since a non-trivial absolute value \(\abs{\;}\) defines a metric on \(K\), we may consider the
    completion of \(K\) w.r.t. \(\abs{\;}\). Fix a \(\abs{\;}\).

    A sequence \((x_n)_{n\in\N}\) of elements of \(k\) is called a *Cauchy sequence* if for every \(\epsilon>0\)
    there exists \(N\in\N\) s.t. for all \(n,m>N\) we have
    \begin{equation*}
    \abs{x_n-x_m}<\epsilon
    \end{equation*}
    We say a sequence \((x_n)_{n\in\N}\) *converges* to \(x\in K\)  and write \(\lim_{n\to\infty}x_n=x\) if for
    every \(\epsilon>0\) there is an \(N\in\N\) s.t. for all \(n>N\) we have
    \begin{equation*}
    \abs{x_n-x}<\epsilon
    \end{equation*}
    \(K\) is *complete* if every Cauchy sequence from \(K\) converges to some element of \(K\).

    The next theorem will show that every field \(K\) with a non-trivial absolute value can be densely
    embedded into a field complete with respect to an ab- solute value extending the given one
    on \(K\).

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:1.1.4
    There exists a field \(\hatK\), complete under an absolute value \(\abs{\hat{\;}}\), and an
    embedding \(\iota:K\to\hatK\), s.t. \(\abs{x}=\abs{\hat{\iota{x}}}\) for all \(x\in K\). The image \(\iota(K)\)
    is dense in \(\hatK\). If \((\hatK',\iota')\) is another such pair, then there exists a unique
    continuous isomorphism \(\varphi:\hatK\to\hatK'\) preserving the absolute value and making  the diagram
    \begin{center}\begin{tikzcd}
    \hatK\ar[rr,"\varphi"]&&\hatK'\\
    &K\ar[ul,"\iota"]\ar[ur,"\iota'"']
    \end{tikzcd}\end{center}
    Such a pair is called a *completion* of the valued field \(K,\abs{\;}\)
    #+END_theorem

    #+BEGIN_proof
    /Sketch of completion/:

    Let \(\calc\) be the set of all Cauchy sequences \((x_n)_{n\in\N}\) of elements of \(K\). \(\calc\) is a
    ring with componentwise addition and multiplication. \(\caln=\{(x_n)_{n\in\N}\mid\lim_{n\to\infty}x_n=0\}\) is
    an ideal of \(\calc\).

    Each \((a_n)_{n\in\N}\in\calc\setminus\caln\) has a positive lower bound, and therefore there is \(M\in\N\) and \(\eta>0\)
    s.t. \(\abs{a_n}>\eta\) for every \(n>M\).

    Setting \(c_n=1\) for every \(n=1,\dots,M\) and \(c_n=a_n^{-1}\) for every \(n>M\).
    Then \((c_n)_{n\in\N}\) is a Cauchy sequence, and \((a_n)_{n\in\N}(c_n)_{n\in\N}-(1)_{n\in\N}\in\caln\). Thus the
    ideal \(\caln\) is a maximal ideal of \(\calc\), and the quotient ring \(\hatK\) is a field.

    The map \(\iota:K\to\hatK\) defined by \(\iota(x)=(x_n)_{n\in\N}+\caln\), where \(x_n=x\) for every \(n\),
    embeds \(K\) in \(\hatK\).

    For \((a_n)_{n\in\N}\in\calc\) the sequence \((\abs{a_n})_{n\in\N}\) is a Cauchy sequence of real numbers,
    since \(\abs{\abs{a_p}-\abs{a_q}}_0\le\abs{a_p-a_q}\) for all \(p,q\). Moreover, for every
    sequence \((a_n)_{n\in\N}\in\caln\) the sequence of real numbers \((\abs{a_n})_{n\in\N}\) has limit 0.
    Consequently for \(\xi=(a_n)_{n\in\N}+\caln\) the value
    \begin{equation*}
    \abs{\hat{\xi}}=\lim_{n\to\infty}\abs{a_n}
    \end{equation*}
    does not depend on the representative \((b_n)_{n\in\N}\) of \xi.And it's an absolute value
    of \(\hatK\) that induces \(\abs{\;}\) on \(K\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(\Q_p\) be the completion of \(\Q\) w.r.t. the \(p\)-adic absolute value \(\abs{\;}_p\),
    called *\(p\)-adic numbers*. The ring of *\(p\)-adic integers* is \(\Z_p=\{x\in\Q_p\mid\abs{x}_p\le 1\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    1. \(\Z_p\) is the completion of \(\Z\) w.r.t. the \(p\)-adic absolute value.
    2. \(\Q_p=\Z_p[1/p]\).
    3. Every \(x\in\Z_p\) can be written in the form
       \begin{equation*}
       x=b_0+b_1p+b_2p^2+\dots+b_np^n+\dots
       \end{equation*}
       where \(0\le b_i\le p-1\), and this representation is unique.
    4. Every \(x\in\Q_p\) can be written in the form
       \begin{equation*}
       x=\sum_{n\ge-n_0}b_np^n
       \end{equation*}
       where \(0\le b_n\le p-1\) and \(\abs{x}_p=e^{n_0}\). This representation is unique.
    #+END_fact

** Archimedean Complete Fields
    Let \(K\) be a field complete w.r.t. an archimedean absolute value \(\abs{\;}\). Since the
    set \(\{\abs{n\cdot 1}\mid n\in\Z\}\) is not bounded, \(\tchar K=0\). Thus \(K\) contains the field \(\Q\) of
    rationals.

    \(\abs{\;}\) restricted to \(\Q\) induces the same topology as the usual absolute value of \(\Q\). Thus the
    complete field \(K\) contains the completion of \(\Q\) w.r.t. the ordinary absolute value,
    i.e., \(K\) contains \(\R\) as a closed subfield.

    Then \(K\) must be equal to \(\R\) or to \(\C\). Consequently, every field \(K\) admitting an
    archimedean absolute value may be considered as a subfield of \(\C\) or even \(\R\) with the
    absolute value dependent on the induced one from \(\C\) (or from \(\R\))

** Non-Archimedean Complete Fields
    Assume \(\abs{\;}\) is a non-trivial, non-archimedean absolute value on the field \(K\), we can
    define an "additive" presentation of the absolute value \(\abs{\;}\):
    \begin{equation*}
    v(x):=-\ln\abs{x}
    \end{equation*}
    In the case of the \(p\)-adic absolute value \(\abs{\;}_q\) on \(\Q\), we obtain
    \begin{equation*}
    v_p(p^\nu\frac{m}{n})=\nu
    \end{equation*}
    \(v_p\) is called the *\(p\)-adic valuation* on \(\Q\).

    Using the additive notion, the axioms of a non-archimedean absolute value
    \begin{equation*}
    v:K\to\R\cup\{\infty\}
    \end{equation*}
    now reads for all \(x,y\in K\)
    1. \(v(x)\in\R\) for \(x\neq 0\), \(v(0)=\infty\)
    2. \(v(xy)=v(x)+v(y)\)
    3. \(v(x+y)\ge\min\{v(x),v(y)\}\)

    First we note that only the additive structure of \(\R\) together with the ordering on \(\R\) is
    used, we will generalize this later. Secondly, \(\infty\) is a symbol that satisfies, for
    all \(\gamma\in\R\), the following axiom:
    \begin{equation*}
    \infty=\infty+\infty=\gamma+\infty=\infty+\gamma
    \end{equation*}

    By an *ordered abelian group* we mean an abelian group \((\Gamma,+,0)\) together with a binary
    relation \(\le\) on \Gamma, where \(\le\) is a linear order on \Gamma and for any \(\gamma,\delta,\lambda\in\Gamma\),
    \begin{equation*}
    \gamma\le\delta\Rightarrow\gamma+\lambda\le\delta+\lambda
    \end{equation*}

    Let \Gamma be an ordered abelian group, and \infty a symbol satisfying for all \(\gamma\in\Gamma\),
    \begin{equation*}
    \infty=\infty+\infty=\gamma+\infty=\infty+\gamma.
    \end{equation*}
    We then define a *valuation* \(v\) on a field \(K\) to be a surjective map
    \begin{equation*}
    v:K\twoheadrightarrow\Gamma\cup\{\infty\}
    \end{equation*}
    satisfying the following axioms: for all \(x,y\in K\),
    1. \(v(x)=\infty\Rightarrow x=0\)
    2. \(v(xy)=v(x)+v(y)\)
    3. \(v(x+y)\ge\min\{v(x),v(y)\}\)

    If \(\Gamma=\{0\}\), we call \(v\) the *trivial valuation*; for all \(x,y\in K\):
    \begin{gather*}
    v(1)=0,\hspace{1cm}v(x^{-1})=-v(x),\hspace{1cm}(-x)=v(x),\\
    v(x)<v(y)\Rightarrow v(x+y)=v(x)
    \end{gather*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(v:K^\times\to\Gamma\) be a valuation on a field. We set
    1. \(\calo_v:=\{x\in K:v(x)\ge 0\}\)
    2. \(\fm_v:=\{x\in K:v(x)>0\}\)
    3. \(\bk_v:=\calo_v/\fm_v\).
    #+END_definition

    For all \(x,y\in\calo_v\) we have
    \begin{gather*}
    v(x\pm y)\ge\min\{v(x),v(\pm y)\}\ge 0\\
    v(xy)=v(x)+v(y)\ge 0
    \end{gather*}
    Hence \(x\pm y,xy\in\calo\). From \(v(x^{-1})=-v(x)\), we deduce that \(x\) is a unit in \(\calo_v\) iff \(v(x)=0\) and for
    every \(x\in K\), either \(x\) or \(x^{-1}\) or both lie in \(\calo_v\). A subring \(\calo\) of \(K\)
    satisfying
    \begin{equation*}
    x\in\calo \quad\text{ or }\quad x^{-1}\in\calo
    \end{equation*}
    for all \(x\in K^\times\) is called a *valuation ring* of \(K\). Thus \(\calo_v\)  is a valuation ring.
    Moreover, \(\fm_v\) is an ideal of \(\calo_v\).
    Since \(\fm_v\) consists exactly of the non-units of \(\calo_v\), \(\fm_v\) is a
    maximal ideal, and in fact the only maximal ideal of \(\calo_v\). Thus \(\calo_v\) is a local ring(ring
    with only one maximal ideal) and \(\bk_v\) is a field, called the *residue class field* of \(v\). The
    residue class of \(a\in\calo_v\) is denoted
    by \(\bara\). Note that \(v\) is trivial iff \(\calo_v=K\) iff \(\bk_v=K\). The group \(v(K^\times)\)
    will be called the *value group* of \(v\).

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(\calo\subseteq K\) be a valuation ring of \(K\). Then there exists a valuation \(v\) on \(K\) s.t. \(\calo=\calo_v\).
    #+END_proposition

    #+BEGIN_proof
    Denote by \(\calo^\times\) the group of units of \(\calo\). The group \(\Gamma=K^\times/\calo^\times\) is an abelian group and
    we can define a binary relation on \Gamma by
    \begin{equation*}
    x\calo^\times\le y\calo^\times\Leftrightarrow\frac{y}{x}\in\calo
    \end{equation*}
    We can check that \Gamma is an ordered abelian group. The valuation is defined by
    \begin{equation*}
    v(x)=x\calo^\times\in\Gamma
    \end{equation*}
    for \(x\in K^\times\), and \(v(0)=\infty\). If \(v(x)\le v(y)\), then \(y/x\in\calo\). Therefore \((x+y)/x=1+y/x\in\calo\)
    and \(v(x+y)\ge v(x)=\min\{v(x),v(y)\}\). Now
    \begin{equation*}
    \calo_v=\{x\in K\mid v(x)\ge 0\}=\{x\in K\mid x\in\calo\}=\calo
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Consider \(K=\Q\), \(v=v_p\), then
    \begin{align*}
    \calo_{v_p}&=\{\frac{a}{b}\mid a,b\in\Z,b\text{ is not divisible by }p\}\\
    \fm_{v_p}&=\{\frac{pa}{b}\mid a,b\in\Z,b\text{ is not divisible by }p\}
    \end{align*}
    \(\calo_{v_p}\) is the localization \(\Z_{(p)}=(\Z-(p))^{-1}\Z)\) of the ring \(\Z\) at the prime ideal \((p)=p\Z\),
    and \(\fm_{v_p}\) is \(p\Z_{(p)}\). Thus the residue class field \(\bk_{v_p}\) is isomorphic to
    the finite field \(\F_p\).
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Consider \(K=F((T))=\{\sum_{n=m}^\infty a_nT^n\mid m\in\Z,a_n\in F\}\), field of formal Laurent series with
    valuation \(v(f)=m\) where \(f=\sum_{n=m}^\infty a_nT^n\) and \(a_m\neq 0\), then \(\calo_{v}=F[[T]]\), \(\fm_v\) is all
    series \(\sum_{n=m}^\infty a_nT^n\) where \(m>0\) and the residue field \(\bk_v\) is \(F\).
    #+END_examplle

* Hensel's Lemma
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A local domain \(A\) with maximal ideal \(\fm\) is *henselian* if whenever \(f(x)\in A[X]\) and there
    is \(a\in A\) s.t. \(f(a)\in\fm\) and \(f'(a)\notin\fm\), then there is \(\alpha\in A\) s.t. \(f(\alpha)=0\)
    and \(\alpha-a\in\fm\).

    A *valued field* is a pair \((K,\calo)\) where \(K\) is a field and \(A\) is a valuation ring. A
    valued field is *henselian* if its valuation ring is henselian.
    #+END_definition

    #+BEGIN_remark
    A ring is local iff all non-units form an ideal, therefore henselianity is a first-order property.
    #+END_remark

    #+ATTR_LATEX: :options [Hensel's Lemma]
    #+BEGIN_theorem
    Suppose \(K\) is a complete field with non-archimedean absolute value \(\abs{\;}\) and valuation
    ring \(\calo=\{x\in K:\abs{x}\le 1\}\). Then \(\calo\) is henselian
    #+END_theorem

    #+BEGIN_proof
    Suppose \(a\in\calo_v\), \(\abs{f(a)}=\epsilon<1\) and \(\abs{f'(a)}=1\). We think of \(a\) as our first
    approximation to a zero of \(f\) and use Newton's method to find a better approximation.

    Let \(\delta=\frac{-f(a)}{f'(a)}\). Note that \(\abs{\delta}=\abs{\frac{f(a)}{f'(a)}}=\epsilon\). Consider the
    Taylor expansion
    \begin{equation*}
    f(a+x)=f(a)+f'(a)x+\text{terms of degree at least 2 in \(x\)}
    \end{equation*}
    Thus
    \begin{equation*}
    f(a+\delta)=f(a)+f'(a)\frac{-f(a)}{f'(a)}+\text{terms of degree at least 2 in \(\delta\)}
    \end{equation*}
    Thus \(\abs{f(a+\delta)}\le\epsilon^2\). Similarly
    \begin{equation*}
    f'(a+\delta)=f'(a)+\text{terms of degree at least 2 in \(\delta\)}
    \end{equation*}
    and \(\abs{f'(a+\delta)}=\abs{f'(a)}=1\).

    Thus starting with an approximation where \(\abs{f(a)}=\epsilon<1\) and \(\abs{f'(a)}=1\), we get a
    better approximation \(b\) where \(\abs{f(b)}\le\epsilon^2\) and \(\abs{f'(b)}=1\). We now iterate this
    procedure to build \(a=a_0,a_1,a_2,\dots\) where
    \begin{equation*}
    a_{n+1}=a_n-\frac{a_n}{f'(a_n)}
    \end{equation*}
    It follows, by induction, that for all \(n\):
    1. \(\abs{a_{n+1}-a_n}\le\epsilon^{2^{n+1}}\)
    2. \(\abs{f(a_n)}\le\epsilon^{2^n}\)
    3. \(\abs{f'(a_n)}=1\)
    Thus \((a_n)_{n\in\N}\) is a Cauchy sequence and converges to \alpha, \(\abs{\alpha-a}\le\epsilon\), and \(f(\alpha)=\lim_{n\to\infty}f(a_n)=0\)
    #+END_proof

    Therefore we have henselian field \((\Q_p,\Z_p)\) and \((F((T)),F[[T]])\).

    #+ATTR_LATEX: :options [Chevalley]
    #+BEGIN_fact
    For a field \(K\), let \(A\subseteq K\) be a subring and let \(P\subseteq A\) be a prime ideal of \(A\). Then
    there exists a valuation ring \(\calo\) of \(K\) s.t.
    \begin{equation*}
    R\subseteq\calo \quad\text{ and }\quad M\cap R=P
    \end{equation*}
    where \(M\) is the maximal ideal of \(\calo\).
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(K_2/K_1\) be a field extension and let \(\calo_1\subseteq K_1\) be a valuation ring. Then there is a
    valuation ring \(\calo_2\subseteq K_2\) with \(\calo_2\cap K_1=\calo_1\).
    #+END_lemma

    #+BEGIN_proof
    Since \(\calo_1\) is a subring of \(K_2\), according to Chevalley's Theorem there exists a valuation
    ring \(\calo_2\) of \(K_2\) with \(\calo_1\subseteq\calo_2\) and \(\fm_2\cap\calo_1=\fm_1\) for maximal ideals. Since \(\calo_2\cap K_1\)
    and \(\calo_1\) are valuation rings with the same maximal ideal they must coincide.
    #+END_proof


    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \((K,\calo)\) be a valued field. T.F.A.E.:
    1. \((K,\calo)\) is henselian.
    2. For any separable extension \(L/K\) there is a unique extension of \(\calo\) to a
       valuation ring of \(L\).
    3. For any algebraic extension \(L/K\) there is a unique extension of \(\calo\) to a valuation ring
       of \(L\).
    #+END_fact

* Hahn Series
    For each group \Gamma and field \(k\), there is a field \(K=k((t^\Gamma))\) with valuation \(v\) having
    \Gamma as the value group and \(k\) as the residue field.
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A,B\subseteq\Gamma\) be well-ordered (by the ordering of \Gamma). Then \(A\cup B\) is well-ordered, the
    set \(A+B:=\{\alpha+\beta:\alpha\in A,\beta\in B\}\) is well-ordered, and for each \(\gamma\in\Gamma\) there are only finitely
    many \((\alpha,\beta)\in A\times B\)  s.t. \(\alpha+\beta=\gamma\).
    #+END_lemma

    #+BEGIN_proof
    Suppose \((a_0,b_0),(a_1,b_1),\dots\) are distinct s.t. \(a_i+b_i>a_j+b_j\) for \(i<j\). Then we can
    find a strictly monotone subsequence of the \(a_i\). Since \(A\) is well-ordered, the sequence
    cannot be decreasing. But then there is a strictly decreasing subsequence of \(b_i\).
    #+END_proof

    #+ATTR_LATEX: :options [Neumann's Lemma]
    #+BEGIN_lemma
    Let \(A\subseteq\Gamma^{>0}\) be well-ordered. Then
    \begin{equation*}
    [A]:=\{\alpha_1+\dots+\alpha_n:\alpha_1,\dots,\alpha_n\in A\}\hspace{2cm}(\text{allowing }n=0)
    \end{equation*}
    is also well-ordered, and for each \(\gamma\in[A]\) there are only finitely many
    tuples \((n,\alpha_1,\dots,\alpha_n)\) with \(\alpha_1,\dots,\alpha_n\in A\) s.t. \(\gamma=\alpha_1+\dots+\alpha_n\)
    #+END_lemma

    Define \(K=k((t^\Gamma))\) to be the set of all formal series \(f(t)=\sum_{\gamma\in\Gamma}a_\gamma t^\gamma\) with
    coefficients \(a_\gamma\in k\), s.t. the support of \(f\),
    \begin{equation*}
    \supp(f)    :=\{\gamma\in\Gamma:a_\gamma\neq 0\}
    \end{equation*}
    is a well-ordered subset of \Gamma.By the first lemma, we can define binary operations of addition
    and multiplication on \(k((t^\Gamma))\) as
    \begin{gather*}
    \sum a_\gamma t^\gamma+\sum b_\gamma t^\gamma=\sum(a_\gamma+b_\gamma)t^\gamma\\
    \left( \sum a_\gamma t^\gamma \right)\left( \sum b_\gamma t^\gamma \right)=
    \sum_\gamma\left( \sum_{\alpha+\beta=\gamma}a_\alpha b_\beta \right)t^\gamma
    \end{gather*}
    Define \(v:K\setminus\{0\}\to\Gamma\) by
    \begin{equation*}
    v(\sum a_\gamma t^\gamma):=\min\{\gamma:a_\gamma\neq 0\}
    \end{equation*}
    Then \(v\) is a valuation on \(K\). If \(v(f)>0\), then by the second lemma \(\sum_{n=0}^\infty f^n\)
    makes sense as an element of \(K\): for any \(\gamma\in\Gamma\) there are only finitely many \(n\) s.t. the
    coefficients of \(t^\gamma\) in \(f^n\) is not zero. Then
    \begin{equation*}
    (1-f)\sum_{n=0}^\infty f^n=1
    \end{equation*}
    Now for any \(g\in K\setminus\{0\}\), \(g=ct^\gamma(1-f)\), with \(c\in k^\times\) and \(v(f)>0\).
    Then \(g^{-1}=c^{-1}t^{-\gamma}\sum_nf^n\).

    For \(f=\sum a_\gamma t^\gamma\in K\), call \(a_0\) the constant term of \(f\). The map sending sending \(f\) to
    its constant term sends \(\calo_v\) onto \(k\), and this is a ring homomorphism. Its kernel
    is \(\fm_v\). Therefore \(\calo_v/\fm_v\cong k\).

    We call \(K\) the *Hahn field*.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(K\) be a valued field. We say that \(K\) is *spherically complete* if whenever \((I,<)\) is
    a linear order and \((B_i:i\in I)\) is a family of open balls s.t. \(B_i\supset B_j\) for all \(i<j\),
    then \(\bigcap_{i\in I}B_i\neq\emptyset\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \((K,v)\) is a valuation field extending \(L\) as a subfield, then \(K\) is an *immediate
    extension* if \(v(K)=v(L)\) and \(\bk_K=\bk_L\).
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    1. Hahn field is henselian.
    1. Hahn field is spherically complete.
    2. Hahn field has no proper immediate extensions.
    #+END_fact
