#+TITLE: Homework4
#+AUTHOR: 陈淇奥@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../preamble-lite.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}

#+ATTR_LATEX: :options [2.1.3]
#+BEGIN_exercise
对任意集合\(X,Y\)，定义\(X\sim Y\)当且仅当\(\abs{X}=\abs{Y}\)。证明\(\sim\)是一个等价关系
#+END_exercise

#+BEGIN_proof
对于任意集合\(X\)，定义\(id:X\to X\)为对任意\(x\in X\)，\(id(x)=x\)，则\(id\)是一个双射，于是\(X\sim X\)

对任意集合\(X,Y\)，若\(X\sim Y\)，则存在双射\(f:X\to Y\)，因为双射的逆是双射，有双射\(f^{-1}:Y\to X\)，于是\(Y\sim X\)

对任意集合\(X,Y,Z\)，若\(X\sim Y\)与\(Y\sim Z\)，则有双射\(f:X\to Y\)与\(g:Y\to Z\)，则\(g\circ f\)是双射：对任
意\(z_1,z_2\in Z\)，如果\(g\circ f(z_1)=g\circ f(z_2)\)，因为\(g,f\)是双射，于是\(f(z_1)=f(z_2)\)，\(z_1=z_2\)；对于任
意\(z\in Z\)，都有\(f^{-1}\circ g^{-1}(z)\in X\)使得\(gf(f^{-1}g^{-1}(z))=z\)。因此\(X\sim Z\)。

因此\(\sim\)是一个等价关系。
#+END_proof

#+ATTR_LATEX: :options [2.1.8]
#+BEGIN_exercise
如果\(X\)是有穷的，则不存在\(X\)到它的真子集\(Y\subsetneq X\)上的双射。
#+END_exercise

#+BEGIN_proof
对\(X\)的元素个数\(n\)做归纳。

若\(n=0\)，命题成立。

若\(n=k\)命题成立，当\(n=k+1\)时，假设存在\(X\)到它的真子集\(Y\)的双射\(f\)，选择\(a\in X\)
与\(f(a)\in Y\)，则\(Y\setminus\{f(a)\}\)
是\(X\setminus\{a\}\)的真子集，且\(f\upharpoonright X\setminus\{a\}\)是双射，这与归纳假设矛盾。

因此不存在\(X\)到它的真子集\(Y\subsetneq X\)上的双射。
#+END_proof

#+ATTR_LATEX: :options [2.1.16]
#+BEGIN_exercise
证明：如果\(X\)是无穷序数的集合，则\(\abs{X}\le\abs{\sup X}\)
#+END_exercise

#+BEGIN_proof
因为\(\sup X=\inf\{a\in\O:\forall\beta\in X(\beta<\alpha)\}\)，对任意\(\beta\in X\)，都有\(\beta\in\sup X\)。于是定义\(f:X\to\sup X\)
为\(f(\beta)=\beta\)。\(f\)是单射，因此\(\abs{X}\le\abs{\sup X}\)
#+END_proof

#+ATTR_LATEX: :options [2.1.24]
#+BEGIN_exercise
对任意序数 \lambda ， \lambda 是冯\(\cdot\)诺伊曼基数当且仅当\(\lambda=Card(\lambda)\)
#+END_exercise

#+BEGIN_proof
若\(\lambda\)是冯\(\cdot\)诺伊曼基数，则存在良序集\(X\)且\(\lambda=Card(X)\)，
即\(\lambda=\inf\{\alpha\in\O:\abs{\alpha}=\abs{X}=\abs{\lambda}\}\)，因此\(\lambda=Card(\lambda)\)

若\(\lambda=Card(\lambda)\)，因为\(\lambda\)是良序集，因此\(\lambda\)是冯\(\cdot\)诺伊曼基数。
#+END_proof

#+ATTR_LATEX: :options [2.1.25]
#+BEGIN_exercise
每个自然数\(n\)都是冯\(\cdot\)诺伊曼基数；\(\omega\)是冯\(\cdot\)诺伊曼基数
#+END_exercise

#+BEGIN_proof
对于自然数\(n,m\)，若\(m<n\)则\(\abs{m}<\abs{n}\)，因此\(Card(n)=\inf\{m\in\O:\abs{m}=\abs{n}\}=n\)，因
此\(n\)是冯\(\cdot\)诺伊曼基数

\(Card(\omega)=\inf\{\lambda\in\O:\abs{\lambda}=\abs{\omega}\}\)，因为\(\omega\)是最小的极限序数，而对于所有\(n\in\omega\)，
\(\abs{n}<\abs{n+1}\le\abs{\omega}\)。因此\(Card(\omega)=\omega\)，\(\omega\)是冯\(\cdot\)诺伊曼基数
#+END_proof
