#+TITLE: Some Notes
#+AUTHOR: wu

#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{preamble.tex}


* Preaservation Theorems

  #+ATTR_LATEX: :options [Lemma 3.1.2]
  #+BEGIN_lemma
  label:lemma3.1.2
  Here we actually use the corollary from original Lemma 3.1.2

  \(\fA\Rightarrow_\Delta\fB\) iff there exists a map \(f\) and a structure \(\fB'\equiv\fB\) s.t. \(f:\fA\to_\Delta\fB'\)
  #+END_lemma

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemma1
  If \(f:\fA_1\to_\exists\fA_2\) or \(f:\fA_1\to_\forall\fA_2\), then \(f\) is an embedding
  #+END_lemma

  #+BEGIN_proof
  \(\fA_2\vDash\Diag(\fA_1)\), hence \(f\) is an embedding
  #+END_proof

  #+ATTR_LATEX: :options [Theorem 3.1.3]
  #+BEGIN_theorem
  Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
  1. There is a universal sentence which separates \(T_1\) from \(T_2\)
  2. No model of \(T_2\) is a substructure of a model of \(T_1\)
  #+END_theorem

  #+BEGIN_proof
  Here we add some details for the proof \(2\to 1\). If \(T_1\) and \(T_2\) cannot be separated by a
  universal sentence, then they have models \(\fA_1\) and \(\fA_2\)  which cannot be separated by a
  universal sentence. That is, for all universal sentence \varphi, if \(\fA_1\vDash\varphi\) then \(\fA_2\vDash\varphi\).
  Thus \(\fA_1\Rightarrow_\forall\fA_2\), here \(\Rightarrow_\forall\) means for all the sentences of the form \(\forall x_1\dots x_n\psi\) where \psi
  is quantifier-free..

  Now note that
  \begin{equation*}
  \fA_1\vDash\varphi\to\fA_2\vDash\varphi\quad\Leftrightarrow\quad\fA_2\vDash\neg\varphi\to\fA_1\vDash\neg\varphi
  \end{equation*}
  and \(\neg\varphi\) is an existential sentence. Hence we have
  \begin{equation*}
  \fA_2\Rightarrow_{\exists}\fA_1
  \end{equation*}

  Now by Lemma ref:lemma3.1.2 we
  have \(\fA_1'\equiv\fA_1\) and a map \(f:\fA_2\to_\exists\fA_1'\).
  Then \(\fA_1'\) is an extension of \(\fA_2\)
  #+END_proof



  #+ATTR_LATEX: :options [Theorem 3.1.8]
  #+BEGIN_theorem
  Let \(T_1\) and \(T_2\) be two theories. Then the following are equivalent
  1. there is an \(\forall\exists\)-sentence which separates \(T_1\) from \(T_2\)
  2. No model of \(T_2\) is the union of a chain (or of a directed family) of models of \(T_1\)
  #+end_theorem

  #+BEGIN_proof
  \(2\to 1\). Suppose \(\fA\vDash T_1\) and \(\fB^0\vDash T_2\). Then
  \begin{equation*}
  \fA\Rightarrow_{\forall\exists}\fB^0
  \end{equation*}
  Again we have
  \begin{equation*}
  \fB^0\Rightarrow_{\exists\forall}\fA
  \end{equation*}
  we have a map
  \begin{equation*}
  f':\fB^0\to_{\exists\forall}\fA^0
  \end{equation*}
  where \(\fA^0\equiv\fA\). Since \(\forall\)-sentences are also \(\exists\forall\)-sentences, we thus have a map \(f:\fB^0\to_{\forall}\fA^0\).

  Here we need to prove that \(\fB^0\) is isomorphic to a substructure of \(\fA^0\), which is Lemma
  ref:lemma1. Then
  we can assume that \(\fB^0\subseteq\fA^0\) and \(f\) is the inclusion map. Then
  \begin{equation*}
  \fA_B^0\Rightarrow_\exists\fB_B^0
  \end{equation*}
  since we are consider elements in \(B\). And the original proof is natural
  #+END_proof
