#+TITLE: Commutative Algebra
#+AUTHOR: Richard E. Borcherds

#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex

* Introduction

* Rings, Ideals and Modules
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(R\) is a *ring* if it's an abelian group under + and
    \begin{align*}
    &(ab)c=a(bc)\\
    &(a+b)c=ac+bc\\
    &a(b+c)=ab+ac
    \end{align*}
    with identity
    #+END_definition

    Rings of diffrerential operators:
    \begin{equation*}
    \sum a_{ij}x^i\left( \frac{d}{dx} \right)^j\quad a_{ij}\in\R
    \end{equation*}

    Assume commutative and identity.
    ideal of \(R\) is the kernel of a hom \(R\to S\).

    \(I\): \(a,b\in I\), \(a\pm b\in I\), \(ar\in I\) for \(a\in I\), \(r\in R\)

    ideals are examples of "rings without 1".

    \((x^2+1)\) all elements of \(r(x^2+1)\) with \(r\in R\).

    \(\R[x]/(x^2+1)=\C\).

    modules: over ring is like a vector space over a field.

    \(M\) module over \(R\)
    \begin{equation*}
    R\times M\to M
    \end{equation*}
    \begin{align*}
    &(r_1r_2)m=r_1(r_2m)\\
    &(r_1+r_2)m=r_1m+r_2m\\
    &r(m_1+m_2)=rm_1+rm_2\\
    &1m=m
    \end{align*}

    Special modules:

    \(\Z\)-modules: abelian groups

    \(k\)-modules (\(k\) a field): vector space

    \(k[x]\)-modules: Linear transformations

    submodule of \(R\): ideal \(I\)

    \(R/I\): quotient ring (still module over \(R\)).


    Suppose \(N\subseteq M\) modules, \(N/M\) is still a module.
    But for ideals \(I\subseteq J\), \(J/I\) is not an ideal

    | Groups                | Rings               |
    | Action Set \(S\)      | Action module \(M\) |
    | \(G/N\)               | \(R/I\)             |
    | \(N\) normal subgroup | \(I\) ideal         |
    | \(G\)                 | \(\Z[G]\)            |
    | \(S\)                 | \(M\), basis of \(S\) as \(\Z\)-module |

* What is a syzygy
    Aim: Hilbert's theorem

    Example 1: rotation of \(\R^3\), the \(O_3(\R)\).

    Wiki: The orthogonal group \(O(n)\) is the subgroup of the general linear group \(\GL(n,\R)\), consisting
    of all endomorphisms that preserve the Euclidean norm, that is endomorphisms \(g\) such that
    \(\norm{g(x)}=\norm{x}\)

    Preserve LENGTH, that is, \(x^2+y^2+z^2\), a polynomial on \(\R^3\), remains the same, and it's an invariant of \(O_3(\R)\)
    action on \(\R^3\)

    How does \(G\) act on polynomials
