#+TITLE: Continuous First Order Logic
#+AUTHOR: Shichang Song
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \def \diam {\text{diam}}
#+LATEX_HEADER: \def \Card {\text{Card}}
#+LATEX_HEADER: \def \density {\text{density}}
#+LATEX_HEADER: \def \dist {\text{dist}}
#+EXPORT_FILE_NAME: ../latex/ContinuousFirstOrderLogic/ContinuousFirstOrderLogic.tex
* Day 1
  Continuou first order logic a.k.a. continuous logic, continuous model theory, model theory for
  metric structures

  | Logic                                 | Mathematics                                   |
  | 1930s: Compactness thm                | 1960s: diaphantine problems over local fields |
  | ultraproducts, saturation             | nonstandard analysis                          |
  | 1970s: shelah: classification theorem | 1996: mordell-lang conjecture                 |
  | stability theory                      |                                               |
  | 1980s: o-minimal theory               | 2011: pila André-oort conjecture              |

  background:

  1960s: Applications of ultraproducts to Banach spaces. Krivine

  1976: Ward Henson nonstandard hulls of Banach spaces: "Henson's logic" positive bounded formulas
  with an approximate semantics

  Later, 2002 with Iovino. Ultraproducts in analysis

  2003, Ben Yaacov, compact abstract theories, Positive model theory and compact abstract theories

  2005 model theory for metric structures

  many valued logic: Łukasiewicz, Chang-Keisler.

  | Truth values | \([0,1]\)     |
  | quantifiers  | \(\inf,\sup\) |
  | equality     | metric \(d(\cdot,\cdot)\) |

  Analogy betweeen CFO and FOL

  Let \((M,d)\) be a complete, bounded metric space

  \(d:M\times M\to\R^{\ge0}\) is a *metric* on \(M\)
  1. \(d(x,y)\ge0\), \(d(x,y)=0\) iff \(x=y\)
  2. \(d(x,y)=d(y,x)\)
  3. \(d(x,y)\le d(x,z)+d(z,y)\)


\((M,d)\) is *bounded* if \(\exists k>0,\forall x,y\in M\), \(d(x,y)<k\) or
\(\diam(M,d):=\sup_{x,y\in M}d(x,y)<k\)

\((M,d)\) is *complete* if every cauchy sequence convergencs




  A *predicate* on \(M\) is a *uniformly continuous* function:
  \(M^n\to[a,b]\subseteq\R\) for some \(n\ge1\)

  \(P:M^n\to(0,1)\) is *uniformly continuous* if \(\forall \epsilon>0\exists\delta>0\forall x,y\in M^n\)
  \(d(x,y)<\delta\to\abs{p(x)-p(y)}<\epsilon\)

  A function on \(M\) is a uniformly continuous function: \(M^n\to M\) fro some \(n\ge1\).

  For simplicity, \((M,d)\) is bounded by 1, predicates have values on \([0,1]\). 0 is true and 1 is
  false.

  #+BEGIN_remark
  In FOL, predicates: \(M^n\to\{0,1\}\)

  In CFO, predicates: \(M^n\to[0,1]\)
  #+END_remark

  A *metric structure* \(\calm\) based on \((M,d)\) consists of a family \((R_i\mid i\in I)\) of
  predicates on \(M\), a family \((F_j\mid j\in J)\) of functions on \(M\) and a
  family \((a_k\mid k\in K)\) of distinguished elements of \(M\)

  We denote a metric structure as
  \begin{equation*}
    \calm=(M,R_i,F_j,a_k\mid i\in I,j\in J,k\in K)
  \end{equation*}
  _Key restrictions_:
  1. complete bounded
  2. bounded interval (\(R_i\))
  3. uniformly continuous \((R_i,F_j)\)


  #+ATTR_LATEX: :options []
  #+BEGIN_examplle
  1. A complete bounded metric space \((M,d)\) with no additional structure
  2. Given a first-order structure \(\calm\), define a discrete metric on it.
     \begin{equation*}
     d(a,b)=
     \begin{cases}
     1&\text{if }a\neq b\\
     0
     \end{cases}
     \end{equation*}
     predicates taking values in \(\{0,1\}\). Then \((\calm,d)\)  is a metric structure. Thus CFO is
     a generalization of FOL
  3. Probability algebras are boolean algebras of events in probabilities space.
  #+END_examplle

  For each metric structure \(\calm=(M,R_i,F_j,a_k\mid i\in I,j\in J,k\in K)\), we
  associate a *signature*
   \begin{equation*}
    L=\{p_i,f_i,c_k\mid i\in I,j\in J,k\in K\}
   \end{equation*}
   where each \(p_i\) is a *predicate symbol* corresponding to predicate \(R_i\) on \(\calm\),
   each \(f_j\) is a *function symbol* corresponding to predicate \(F_j\) on \(\calm\) ,
   and each \(c_k\) is a *constant symbol* corresponding to predicate \(a_k\) on \(\calm\).

   We associate to each symbol its arity like in FOL.

   Moreover, in CFO, we associate to each predicate symbol \(p\) a closed bounded interval \(I_p\)
   (usually \(I_p=[0,1]\)) and a *modulus of uniform continuity* \(\Delta_p\), i.e., a
   function \(\Delta_p:(0,1]\to(0,1])\) satisfify \(\forall \epsilon>0\forall x,y\in M^n\),
   if \(d(x,y)<\Delta_p(\epsilon)\) (defines a \delta by \(\Delta_p\)) then
   \begin{equation*}
    \abs{p^{\calm}(x)-p^{\calm}(y)}<\epsilon
   \end{equation*}
   This \(\Delta_p\) does *not* depend on \(\calm\)

   We associate to each function a modulus of uniformly continuity \(\Delta_f\), i.e. a
   function \(\Delta_f:(0,1]\to(0,1]\) satisfying  \(\forall \epsilon>0\forall x,y\in M^n\),
   if \(d(x,y)<\Delta_f(\epsilon)\) then
   \begin{equation*}
    d(f^{\calm}(x,f^{\calm}(y)))<\epsilon
   \end{equation*}

   Finally, \(L\) provides \(D_L\) which is a bound on the diameter of \((M,d)\). For
   simplicity, \(D_L=1\) and \(I_p=[0,1]\).

   We say \(\calm\) an \(L\)-structure

   Suppose \(\calm\) and \(\caln\) are \(L\)-structures. An *embedding* from \(\calm\) to \(\caln\) is
   a metric space *isometry* \(T:(\calm,d^{\calm})\to(N,d^{\caln})\) s.t.
   1. \(\forall x,y\in M\), \(d^{\caln}(T(x),T(y))=d^{\calm}(x,y)\)
   2. for each \(n\)-ary predicate symbol \(p\) of \(L\)
      \begin{equation*}
      \forall a_1,\dots,a_n\in M,p^{\caln}(T(a_1),\dots,T(a_n))=p^{\calm}(a_1,\dots,a_n)
      \end{equation*}
   3. for each \(n\)-ary function symbol \(f\) of  \(L\)
      \begin{equation*}
      \forall a_1,\dots,a_n\in M,f^{\caln}(T(a_1),\dots,T(a_n))=T(f^{\calm}(a_1,\dots,a_n))
      \end{equation*}
   4. for each constant symbol \(c\) of \(L\)
      \begin{equation*}
      c^{\caln}=T(c^{\calm})
      \end{equation*}


   An *isomorphism* is a surjective embedding. We say that \(\calm\) and \(\caln\) are isomorphic and
   write \(\calm\cong\caln\) if there exists an isomorphism between \(\calm\) and \(\caln\)

   If \(M\subseteq N\) and the inclusion map is an embedding of \(\calm\) into \(\caln\), then we
   say \(\calm\) is a *substructure* of \(\caln\) and write \(\calm\subseteq\caln\)

   More on modulus of uniform continuity. See [BBHU] appendix to section 2 on pages 322-327

   Fix a signature \(L\) for metric structure

   Symbols of \(L\)
   * nonlogical symbols: predicates, functions, constants
   * logical symbols: \(d\)-binary predicate (=), \(V_L\) - an infinite set of
     variables, \(u:[0,1]^n\to[0,1]\) continuous connectives (since continus \(\Rightarrow\)
     uniformly continuous), \(\sup,\inf\) (quantifiers)


   The *cardinality* of \(L\), denoted by \(\Card(L)\) is the smallest infinite cardinal
   \(\ge\#\{\text{nonlogical symbols}\}\)

   *terms* of \(L\)
   1. variables and constant symbols
   2. \(f(t_1,\dots,t_n)\)


   *Atomic formulas* of \(L\)
   1. \(P(t_1,\dots,t_n)\) wher e\(P\) is an \(n\)-ary predicate symbol
   2. \(d(t_1,t_2)\) like "=" in FOL


   *Formulas* of \(L\)
   1. atomic formulas
   2. if \(u:[0,1]^n\to[0,1]\) is continuous and \(\varphi_1,\dots,\varphi_n\) are \(L\)-formulas,
      then \(u(\varphi_1,\dots,\varphi_n)\) is an \(L\)-formula
   3. if \varphi is an \(L\)-formula and \(x\) is a variable, then \(\sup_x\varphi\) and \(\inf_x\varphi\)
      are \(L\)-formulas


   This definition is not a  good one
   1. too general, uncountably continuous functions. we only need to concern a dense subset of it
   2. too restrict, in order to develop a good nition of "definability", need formulas closed under
      certain kinds of limits


   We write \(t(x_1,\dots,x_n)\) or \(\varphi(x_1,\dots,x_n)\) to indicate is free variables are
   among \(x_1,\dots,x_n\)

   #+ATTR_LATEX: :options []
   #+BEGIN_examplle
   Let \(D_0\) denote the set of repeating decimals. Then \((D_0,d_0)\) (\(d_0\) is subtraction) is
   a *pseudometric* space. Because \(d_0(0.\dot{9},1)=0\) but \(0.\dot{9}\neq1\). Consider its
   quotient \((D,d)=(D_0,d_0)/\sim\) where \(x\sim y\) if \(d_0(x,y)=0\). Then \((D,d)\) is a metric
   space, but it is not complete. Actually \((D,d)=(\Q,d)\). Take its completion, we
   get \((\barD,\bard)=(\R,d)\).

   pseudometric space -> metric space -> complete metric space
   #+END_examplle

   Fix a signature \(L\). Let \((M_0,d_0)\) be a pseudometric space
   satisfying \(\diam(M_0,d_0)\le D_L\). An *\(L\)-prestructure* \(\calm_0\) based on \((M_0,d_0)\) is a
   structure satisfying
   1. for each predicate symbol \(p\) of \(L\) \(p^{\calm_0}:M_0^n\to I_p\) has \(\Delta_p\) as a
      modulus of uniform continuity
   2. for each function symbol \(f\) of \(L\), \(f^{\calm_0}:M_0^n\to M_0\) has \(\Delta_f\) as a modulus
      of uniform continuity
   3. for each constant symbol \(c\) of  \(L\), \(c^{\calm_0}\in M_0\)


   Given \(L\)-prestructure \(\calm_0\), we define its *quotient* prestructure as follows:

   Let \((M,d)=(M_0,d_0)/\sim\), where \(x\sim y\) iff \(d_0(x,y)=0\). Let \(\pi:M_0\to M\) be the
   quotient map. Then
   1. for each predicate symbol \(p\) of \(L\), define \(p^{\calm}:M^n\to I_p\) by
      \begin{equation*}
    p^{\calm}(\pi(x_1),\dots,\pi(x_n))=p^{\calm_0}(x_1,\dots,x_n)
      \end{equation*}
   2. for each function symbol \(f\) of \(L\), define \(f^{\calm}:M^n\to M\) by
      \begin{equation*}
    f^{\calm}(\pi(x_1),\dots,\pi(x_n))=\pi(f^{\calm_0}(x_1,\dots,x_n))
      \end{equation*}
   3. for each constant symbol \(c\) of \(L\), define \(c^{\calm}=\pi(c^{\calm_0})\)


   Clearly,
   1. \(\diam(M,d)=\diam(M_0,d)\)
   2. \(p^{\calm}\) is well-defined and has \(\Delta_p\) as its modulus of uniform continuity
   3. \(f^{\calm}\) is well-defined and has \(\Delta_f\) as its modulus of uniform continuity (these
      2 proofs are in the appendix)


   Thus \((M,d)\) is an \(L\)-prestructure based on a possibly incomplete metric space.

   Finally we take a *completion* of \(\calm\), denoted by \(L\)-structure \(\caln\)
   1. for each predicate symbol \(p\). define \(p^{\caln}:N^n\to I_p\) as the unique extension
      of \(p^{\calm}\) with the same \(\Delta_p\) (Check!)
   2. for each \(f\), \(f^{\caln}:N^n\to N\) is the unique extension of \(f^{\calm}\) with the same \(\Delta_f\)
   3. for each constant \(c\), \(c^{\caln}=c^{\calm}\)


   Let \(\calm\) be an \(L\)-prestructure and let \(A\subset M\). We extend \(L\) to a
   signature \(L(A)\) by adding a new constant symbol \(c(a)\) to \(L\) for
   each \(a\in A\). \((c(a))^{\calm=a}\). We call \(c(a)\) the *name* of \(a\) in \(L(A)\).
   Consider \(L(M)\)-terms \(t(x_1,\dots,x_n)\), define exactly as in FOL
   \begin{equation*}
    t^{\calm}:M^n\to M
   \end{equation*}
   The interpretation of \(t\) in \(\calm\)

   _Key definitions of semantics in CFO_
   1. \((d(t_1,t_2))^{\calm}=d^{\calm}(t_1^{\calm},t_2^{\calm})\) for all \(t_1,t_2\)
   2. \((p(t_1,\dots,t_n))^{\calm}=p^{\calm}(t_1^{\calm},\dots,t_n^{\calm})\) for all \(n\)-ary
      predicate symbol \(p\) and all \(t_1,\dots,t_n\)
   3. for all \(L(M)\)-sentences \(\sigma_1,\dots,\sigma_n\) and all continuous
      function \(\mu:[0,1]^n\to[0,1]\)
      \begin{equation*}
    (\mu[\sigma_1,\dots,\sigma_n])^{\calm}=\mu(\sigma_1^{\calm},\dots,\sigma_n^{\calm})
      \end{equation*}
   4. for all \(L(M)\)-formulas \(\varphi(x)\)
      \begin{align*}
    (\sup_x(\varphi(x)))^{\calm}=\sup_{a\in M}(\varphi(a))^{\calm}\in[0,1]
      \end{align*}


   Given \(L(M)\)-formula \(\varphi(x_1,\dots,x_n)\), we let \(\varphi^{\calm}\) denote the function
   \(M^n\to[0,1]\) defined by
   \begin{equation*}
    \varphi^{\calm}(a_1,\dots,a_n)=(\varphi(a_1,\dots,a_n))^{\calm}
   \end{equation*}

   Fact: \(\varphi^{\calm}\) is a uniformly continuous function

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thmA.1
   Let \(t(x_1,\dots,x_m)\) be an \(L\)-term and \(\varphi(x_1,\dots,x_n)\) an \(L\)-formula. Then there
   exists functions \(\Delta_t\) and \(\Delta_{\varphi}\)\(:(0,1]\to(0,1]\) s.t.
   for every \(L\)-prestructure \(\calm\), \(\Delta_t\) is a modulus of uniform continuity for the
   function \(t^{\calm}:M^n\to M\) and \(\Delta_\varphi\) is a modulus of uniform continuity for the
   predicate \(\varphi^{\calm}:M^n\to[0,1]\)
   #+END_theorem

   #+BEGIN_proof
   Induction
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_theorem
   label:thmA.2
   pseudometric space \((M_0,d_0)\) \(\to\) quotient \((M,d)\) \(\to\) completion \((N,d)\)

   Let \(t(x_1,\dots,x_n)\) be an \(L\)-term and \(\varphi(x_1,\dots,x_n)\) be an \(L\)-formula. Then
   1. \(t^{\calm}(\pi(a_1),\dots,\pi(a_n))=t^{\calm_0}(a_1,\dots,a_n)\)
   2. \(t^{\caln}(b_1,\dots,b_n)=t^{\calm}(b_1,\dots,b_n)\)
   3. \(\varphi^{\calm}(\pi(a_1),\dots,\pi(a_n))=\varphi^{\calm_0}(a_1,\dots,a_n)\)
   4. \(\varphi^{\caln}(b_1,\dots,b_n)=\varphi^{\calm}(b_1,\dots,b_n)\)
   #+END_theorem

   #+BEGIN_proof
   in 3. key step is that \pi is surjective

   in 4, key step is that \(\varphi^{\caln}\) is continuous and \(M\) is dense in \(N\)
   #+END_proof


   Two \(L\)-formulas \(\varphi(x_1,\dots,x_n)\) and \(\psi(x_1,\dots,x_n)\) are *logically equivalent* if
   \begin{equation*}
    \varphi^{\calm}(a_1,\dots,a_n)=\psi^{\calm}(a_1,\dots,a_n)
   \end{equation*}
   for every \(L\)-structure \(\calm\)

   The *logical distance* \(d_L\) between \varphi and \psi is
   \begin{equation*}
    d_L(\varphi,\psi)=\sup_{\calm}\sup_{a_1,\dots,a_n\in M}\abs{\varphi^{\calm}(a_1,\dots,a_n)-\varphi^{\calm}(a_1,\dots,a_n)}
   \end{equation*}


   #+BEGIN_remark
   1. This defines a pseudometric
   2. \(d_L(\varphi,\psi)=0\) iff \(\varphi\sim_L\psi\)
   #+END_remark

   The space of \(L\)-formulas is too big. *density character* is the smallest dense subset w.r.t.
   logical distance.

   By Weierstrass theorem, there is a countable set of functions that is dense in the set of all
   continuous functions w.r.t \(\sup\)-distance. We may use this countable set of functions to build
   connectives. Then
   1. the total number of constructed formulas is \(\Card(L)\)
   2. every \(L\)-formulas can be approximated arbitrarily closely in logical distance by a formula
      constructed using restricted connectives
* Day 2
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  An *\(L\)-condition* \(E\) is of the form \(\varphi=0\), where \varphi is an \(L\)-formula. We call \(E\)
  *closed* if \varphi is closed, i.e., \varphi is an \(L\)-sentence

  If \(E\) is the \(L(M)\)-condition \(\varphi(x_1,\dots,x_n)=0\) and \(a_1,\dots,a_n\in M\), we say \(E\)
  is *true of \(a_1,\dots,a_n\)* in \(\calm\) and we write \(\calm\vDash E[a_1,\dots,a_n]\) if
  \(\varphi^{\calm}(a_1,\dots,a_n)=0\)

  Let \(E_i\) be the \(L\)-condition \(\varphi_i(x_1,\dots,x_n)=0\). We say \(E_1\) and \(E_2\) are
  *logically equivalent* if for every \(L\)-structure \(\calm\) and every \(a_1,\dots,a_n\) we have
  \begin{equation*}
    \calm\vDash E_1[a_1,\dots,a_n] \quad\text{ iff }\quad
    \calm\vDash E_2[a_1,\dots,a_n]
  \end{equation*}

  \(\varphi=\psi\) is an abbreviation for the condition \(\abs{\varphi-\psi}=0\), where
  \(\abs{\cdot}:[0,1]^2\to[0,1]\), \((t_1,t_2)\mapsto\abs{t_1-t-2}\) is a connective.

  \(\varphi\le\psi\) iff \(\varphi\dot-\psi=0\)
  #+END_definition

  In \([0,1]\)-valued logic, \(\varphi\le\psi\) is like \(\varphi\to\psi\) in FOL. Since
  from \(\psi\le r\) we have \(\varphi\le r\) for all \(r\in[0,1]\)

  Fix a signature \(L\) for metric structure.

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A *theory* \(T\) is a set of closed \(L\)-conditions. We say \(\calm\) is a model of \(T\) and
  write \(\calm\vDash T\)  if \(\calm\vDash E\) for every condition \(E\in T\).

  Let \(\Mod_L(T)\) be the collection of all models of \(T\)

  The *theory of \(\calm\)*, denoted by \(\Th(\calm)\), is the set of closed \(L\)-conditions that are
  true in \(\calm\).

  If \(T\) is a theory of this form, then \(T\) is *complete*.

  We say \(E\) is a *logical consequence* of \(T\) and write \(T\vDash E\) if \(\calm\vDash E\) holds
  for every model \(\calm\) of \(T\).
  #+END_definition

  #+BEGIN_remark
  1. models are complete metric spaces.
  2. Let \(\calm_0\) be an \(L\)-prestructure s.t. \(\varphi^{\calm_0}=0\) for every
     condition \(\varphi=0\) in \(T\). Then by Theorem ref:thmA.2, the completion of the canonical
     quotient of \(\calm_0\) is a model of \(T\). (\(\calm_0\) is a *premodel*)
  #+END_remark

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  1. We say \(\calm\) and \(\caln\) are *elementary equivalent* and write \(\calm\equiv\caln\)
     if \(\sigma^{\calm}=\sigma^{\caln}\) for all \(L\)-sentences \sigma
  2. If \(\calm\subseteq\caln\), we say that \(\calm\) is an *elementary substructure* of \(\caln\)
     and write \(\calm\preceq\caln\)
     if whenever \(\varphi(x_1,\dots,x_n)\) is an \(L\)-formula and \(a_1,\dots,a_n\in M\) we have
     \begin{equation*}
    \varphi^{\calm}(a_1,\dots,a_n)=\varphi^{\caln}(a_1,\dots,a_n)
     \end{equation*}
     We also say \(\caln\) is an *elementary extension* of \(\calm\)
  3. \(F:A\subseteq M\to N\) is an *elementary map* if whenever \(\varphi(x_1,\dots,x_n)\) is
     an \(L\)-formula and \(a_1,\dots,a_n\in\dom(F)\) we have
     \begin{equation*}
    \varphi^{\calm}(a_1,\dots,a_n)=\varphi^{\caln}(F(a_1),\dots,F(a_n))
     \end{equation*}
  4. An *elementary embedding* of \(\calm\) into \(\caln\) is a function \(M\to N\) that is an
     elementary map from \(\calm\) into \(\caln\)
  #+END_definition

  #+BEGIN_remark
  1. elementary map is distance preserving, and thus is an embedding
  2. \(\calm\cong\caln\Rightarrow\calm\equiv\caln\)
  #+END_remark

  We say \(S\) of \(L\)-formulas is *dense w.r.t. logical distance* if for
  every \(L\)-formula \(\varphi(x_1,\dots,x_n)\) and every \(\epsilon>0\) there is \(\psi(x_1,\dots,x_n)\) in \(S\)
  s.t. for every \(L\)-structure \(\calm\) and all \(a_1,\dots,a_n\in M\) we have
  \begin{equation*}
    \abs{\varphi^{\calm}(a_1,\dots,a_n)-\psi^{\calm}(a_1,\dots,a_n)}\le\epsilon
  \end{equation*}

  #+ATTR_LATEX: :options [Tarski-Vaught Test for $\preceq$]
  #+BEGIN_proposition
  label:propB.1
  Let \(S\) be dense w.r.t. logical distance. Suppose \(\calm\) and \(\caln\) are \(L\)-structures
  with \(\calm\subseteq\caln\). Then the following are equivalent
  1. \(\calm\preceq\caln\)
  2. For every \(L\)-formula e\(\varphi(x_1,\dots,x_n,y)\) in \(S\) and all \(a\in M^n\)
     \begin{equation}
     \inf\{\varphi^{\caln}(a,b)\mid b\in N\}=\inf\{\varphi^{\caln}(a,c)\mid c\in M\}\tag{$\star$}
     \end{equation}
  #+END_proposition

  #+BEGIN_proof
  \(1\to 2\). By 1, we have
  \begin{align*}
    \inf\{\varphi^{\caln}(a_1,\dots,a_n,b)\mid b\in N\}&=
    \left(\inf_y\varphi(a_1,\dots,a_n,y)\right)^{\caln}\\
    &=\left((\inf_y\varphi(a_1,\dots,a_n,y))\right)^{\calm}\\
    &=\inf\{\varphi^{\calm}(a_1,\dots,a_n,c)\mid c\in M\}\\
    &=\inf\{\varphi^{\caln}(a_1,\dots,a_n,c)\mid c\in M\}
  \end{align*}

  \(2\to1\). First we show \(\star\) holds for all \(L\)-formulas \(\varphi(x_1,\dots,x_n,y)\).
  \(\forall\epsilon>0\), take \(\varphi(x_1,\dots,x_n,y)\in S\) s.t.
  \begin{equation*}
    \sup_{\calm}\sup_{a_1,\dots,a_n\in M}
    \abs{\varphi^{\calm}(a_1,\dots,a_n,b)-\psi^{\calm}(a_1,\dots,a_n,b)}\le\epsilon
  \end{equation*}
  Let \(a_1,\dots,a_n\in M\) then we have
  \begin{align*}
    \inf\{\varphi^{\caln}(a_1,\dots,a_n,b)\mid b\in M\}&\le
    \inf\{\psi^{\caln}(a_1,\dots,a_n,b)\mid b\in M\}+\epsilon\\
    &=\inf\{\psi^{\caln}(a_1,\dots,a_n,c)\mid c\in N\}+\epsilon\\
    &\le\inf\{\varphi^{\caln}(a_1,\dots,a_n,c)\mid c\in N\}+2\epsilon
  \end{align*}
  Let \(\epsilon\to0\), then
  \begin{equation*}
    \inf\{\varphi^{\caln}(a_1,\dots,a_n,b)\mid b\in M\}\le
    \inf\{\varphi^{\caln}(a_1,\dots,a_n,c)\mid c\in N\}
  \end{equation*}
  Hence \(\star\) holds for all \(L\)-formulas \varphi.

  Then by incution on the complexities of \varphi and \(\star\) we have
  \(\varphi^{\calm}(a_1,\dots,a_n)=\varphi^{\caln}(a_1,\dots,a_n)\) for all \(a_1,\dots,a_n\in M\)
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(I\) be a nonempty set. A *filter* on \(I\) is a collection \(F\) of subsets of \(I\) satisfies
  1. \(\emptyset\not\in F\) and \(I\in F\)
  2. for all \(A,B\in F\), \(A\cap B\in F\)
  3. for all \(A\in F\), if \(A\subseteq B\subseteq I\) then \(B\in F\)


  A filter \(F\) is an *ultrafilter* if it is maximal under \(\subseteq\) among filters on \(I\)

  \(F\) is *principal* if there is a subset \(A\subseteq I\) s.t. \(F\) is exactly the collection of
  all sets \(B\) that satisfy \(A\subseteq B\subseteq I\).

  non-principal is also called as *free*
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  \(S\) is a collection of \(I\). We say that \(S\) has *finite intersection property* (FIP)
  if \(\forall n\in\N\), \(\forall\) finite subset collection \(\{A_1,\dots,A_n\}\)
  of \(S\), \(A_1\cap\dots\cap A_n\neq\emptyset\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaB.2
  Let \(I\) be a nonempty set and let \(S\) be a collection of subsets of \(I\). There exists a
  filter \(F\) on \(I\) which contains \(S\) iff \(S\) has the FIP
  #+END_lemma

  #+BEGIN_remark
  The smallest filter on \(I\) containing \(S\) is called the *filter generated by \(S\)*
  #+END_remark

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaB.3
  Let \(F\) be a filter on a nonempty set \(I\). Then \(F\) is an ultrafilter iff \(\forall A\subset I\),
  either \(A\in F\) or \(A^c\in F\).
  #+END_lemma

  #+BEGIN_remark
    principal ultrafilters are trivial
  #+END_remark

  #+ATTR_LATEX: :options []
  #+BEGIN_theorem
  label:thmB.4
  Let \(I\) be a nonempty set. Then every filter on \(I\) is contained in an ultrafilter on \(I\).
  #+END_theorem

  #+BEGIN_proof
  Zorn's lemma
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  label:corB.5
  Let \(I\) be a nonempty set and let \(S\) be a collection of subset of \(I\). If \(S\) has the
  FIP, then there is an ultrafilter on \(I\) that contains \(S\).
  #+END_corollary

  Fix a first order signature \(L\). Let \(I\) be a nonempty set and let \(U\) be a fixed
  ultrafilter on \(I\). Consider an \(I\)-indexed family of \(L\)-structures \(\cala_i\).
  Let \(A=\prod_{i\in I}A_i\) be the Cartesian product of the sets \(A_i\). Let \(f,g\in A\). We
  define a relation on \(A\)
  \begin{equation*}
    f\sim g \quad\text{ iff }\quad
    \{i\mid f(i)=g(i)\}\in U
  \end{equation*}
  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaB.6
  The relation \(\sim\) is an equivalence relation on \(A\)
  #+END_lemma

  Then \(A/\sim\) is the ultraproduct of the set \(A_i\) w.r.t. the ultrafilter \(U\) on \(I\)

  We let \(\prod_UA_i\) denote \(A/\sim\), the collection of all equivalence classes
  \(\{[f]\mid f\in\prod_{i\in I}A_i\}\)

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  The *ultraproduct* \(\prod_{U}\cala_i\) is defined to be the \(L\)-structure
  1. the universe of \(\prod_{U}\cala_i\) is \(\prod_UA_i\)
  2. for each constant \(c\) in \(L\), define \(f\in A\) by \(f(i)=c^{\cala_i}\)
     \begin{equation*}
    c^{\prod_U\cala_i}=f/\sim
     \end{equation*}
  3. for each predicate \(P\) in \(L\)
     \begin{equation*}
    P^{\prod_U\cala_i}(f_1/\sim,\dots,f_n/\sim)\quad\text{ iff }\quad
    \{i\in I\mid P^{\cala_i}(f_1(i),\dots,f_n(i))\}\in U
     \end{equation*}
  4. for each function \(F\) in \(L\)
     \begin{equation*}
    F^{\prod_U\cala_i}(f_1/\sim,\dots,f_n/\sim)=f/\sim
     \end{equation*}
     where \(f\in A\) is defined by \(f(i)=F^{\cala_i}(f_1(i),\dots,f_n(i))\)


  Need to check they are well-defined

  An *ultrapower* of \(\cala\) is an ultraproduct \(\prod_U\cala_i\) with \(\cala_i=\cala\) for
  all \(i\in I\)
  #+END_definition

  #+ATTR_LATEX: :options [Łoś's theorem (fundamental theorem for ultraproducts)]
  #+BEGIN_theorem
  label:thmB.7
  For every \(L\)-formula \(\varphi(x_1,\dots,x_n)\) and every \(f/\sim=(f_1/\sim,\dots,f_n/\sim)\), we
  have
  \begin{equation*}
    \prod_U\cala_i\vDash\varphi[f/\sim] \quad\text{ iff }\quad
    \{i\in I\mid\cala_i\vDash\varphi[f_1(i),\dots,f_n(i)]\}\in U
  \end{equation*}
  #+END_theorem

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  label:corB.8
  if \sigma is an \(L\)-sentence, then \(\prod_U\cala_i\vDash\sigma\) iff
  \(\{i\in I\mid\cala_i\vDash\sigma\}\in U\)
  #+END_corollary

  Let \(X\) be a topological space and let \((x_i)_{i\in I}\) be a family of elements of \(X\).
  If \(D\) is an ultrafilter on \(I\) and \(x\in X\), we write \(\lim_{i,D}x_i=x\) (ultra limit) and
  say \(x\) is the *\(D\)-limit of \((x_i)_{i\in I}\)* if \(\forall \)
  open \(U\ni x\), \(\{i\in I\mid x_i\in U\}\in D\)

  *Fact*: \(X\) is a compact Hausdorff space (e.g. \(X=[0,1]\)) iff for every family \((x_i)_{i\in I}\) in \(X\) and
   every ultrafilter \(D\) on \(I\) the \(D\)-limit of \((x_i)_{i\in I}\) exists and is unique.

   #+ATTR_LATEX: :options []
   #+BEGIN_lemma
   label:lemmaB.9
   Suppose \(X,X'\) are topological spaces and \(F:X\to X'\) is continuous. For every
   family \((x_i)_{i\in I}\) from \(X\) and every ultrafilter \(D\) on \(I\), we have
   \begin{equation*}
    \lim_{i, D}x_i=x\Rightarrow\lim_{i,D}F(x_i)=F(x)
   \end{equation*}
   where the ultralimits are taken in \(X\) and \(X'\) respectively
   #+END_lemma

   #+BEGIN_proof
   Take open \(U\ni F(x)\) in \(X'\). Since \(F\) is continuous, \(F^{-1}(U)\) is open in \(X\).
   And \(F^{-1}(U)\ni x\). If \(x\) is the \(D\)-limit of \((x_i)_{i\in I}\) there is \(A\in D\)
   s.t. \(x_i\in F^{-1}(U)\) for all \(i\in A\) and thus \(F(x_i)\in U\)
   #+END_proof

   #+ATTR_LATEX: :options []
   #+BEGIN_definition
   Let \(((M_i,d_i)\mid i\in I)\) be a family of bounded metric spaces with diameter \(\le k\).
   Let \(D\) be an ultrafilter on \(I\). Define \(d\) on \(\prod_{i\in I}M_i\)
   by \(d(x,y)=\lim_{i,D}d_i(x_i,y_i)\), when \(x=(x_i)_{i\in I}\) and \(y=(y_i)_{i\in I}\).

   Check: \(d\) is a pseudometric on \(\prod_{i\in I}M_i\)

   For \(x,y\in\prod_{i\in I}M_i\), define \(x\sim_Dy\) iff \(d(x,y)=0\)

   Then \(\sim_D\) is an equivalence relation, so we may define
   \begin{equation*}
    \left(\prod_{i\in I}M_i\right)_D=\left(\prod_{i\in I}M_i\right)/\sim_D
   \end{equation*}
   Later we will see its complete

   The pseudometric \(d\) on \(\prod_{i\in I}M_i\) induces a metric \(d\)
   on \((\prod_{i\in I}M_i)_D\)

   The space \(((\prod_{i\in I}M_i)_D,d)\) is the *\(D\)-ultraproduct* of \(((M_i,d_i)\mid i\in I)\).

   We denote \((x_i)_{i\in I}/\sim_D\) by \(((x_i)_{i\in I})_D\)

   If \((M_i,d_i)=(M,d)\) \(\forall i\in I\). The space \((\prod_{i\in I}M_i)_D\) is called the
   *\(D\)-ultrapower* of \(M\) and denoted by \((M)_D\)

   \(T:M\to(M)_D\), \(x\mapsto((x_i)_{i\in I})_D\), where \(\forall i\in I\), \(x_i=x\) is a *diagonal
   embedding*. its an isometric embedding
   #+END_definition

   If \((M,d)\) is compact, then it is easy to show \(((x_i)_{i\in I})_D=T(x)\), i.e., the diagonal
   embedding is surjective.

   *Fact*: every ultrapower of a closed bounded interval may be canonically identified wiht the
    interval itself. e.g. \(([0,1])_D=[0,1]\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:propB.10
    Let \(((M_i,d_i)\mid i\in I)\) be a family of complete, uniformly bounded metric space.
    Let \(D\) be an ultrafilter on \(I\) and let \((M,d)\) be the \(D\)-ultraproduct
    of \(((M_i,d_i)\mid i\in I)\). The metric space \((M,d)\) is complete
    #+END_proposition

    #+BEGIN_proof
    let \((x^k)_{k\ge1}\)  be a Cauchy sequence in \((M,d)\). WLOG, we assume that
    \(d(x^k,x^{k+1})<\frac{1}{2^k}\) holds for all \(k\ge1\). We want to show it has a limit.

    For each \(k\ge1\) let \(x^k\) be represente by the family \((x_i^k)_{i\in I}\). For
    each \(m\ge1\), let \(A_m=\{i\in I\mid d_i(x_i^k,x_i^{k+1})<\frac{1}{2k}\forall k\le m\}\).
    Note \(A_1\supseteq A_2\supseteq\dots A_n\neq\emptyset\supseteq\dots\) and each \(A_i\in D\).

    We define a family \((y_i)_{i\in I}\) as follows. If \(i\not\in A_1\) then we take \(y_i\)
    arbitrarily. If \(i\in A_m\setminus A_{m+1}\) for some \(m\ge1\), then we set \(y_i=x_i^{m+1}\).
    If \(\forall m\ge1\), \(i\in A_m\), then \((x_i^m)_{m\ge1}\) is a Cauchy sequence, we take \(y_i\) to
    be its limit.

    Then for each \(m\ge1\) each \(i\in A_m\) we have \(d_i(x_i^m,y_i)\le 2^{-m+1}\). It follows that
    \(((y_i)_{i\in I})_{D}\) is the limit of \((x^k)_{k\ge1}\) in \((M,d)\)
    #+END_proof

    Suppose \(((M_i,d_i)\mid i\in I)\) and \(((M_i',d_i')\mid i\in I)\) are families of metric
    spaces with diameter \(\le k\). Fix \(n\ge1\) and suppose \(f_i:M_i^n\to M_i'\) is uniformly
    continuous for each \(i\). Moreover, there is a function \(\Delta:(0,1]\to(0,1]\) is a modulus of
    uniform continuity for all \(f_i\).

    Given an ultrafilter \(D\) on \(I\) we define
    \begin{equation*}
    \left(\prod_{i\in I}f_i\right)_D\cdot\left(\prod_{i\in I}M_i\right)_D\to
    \left(\prod_{i\in I}M_i'\right)_D
    \end{equation*}
    as follows
    \begin{equation*}
    \left(\prod_{i\in I}f_i\right)_D\left(
    ((x_i^1)_{i\in I})_D,\dots,((x_i^n)_{i\in I})_D
    \right)=\left((f_i(x_i^1,\dots,x_i^n))_{i\in I}\right)_D
    \end{equation*}
    where \((x_i^k)_{i\in I\in\prod_{i\in I}M_i}\)

    *Claim*. \((\prod_{i\in I}f_i)_D\) is a uniformly continuous function that also has \Delta as its
    modulus of uniform continuity

    Suppose \(n=1\), \(\forall \epsilon>0\), \(d(((x_i)_{i\in I})_D,((y_i)_{i\in I})_D)\le \Delta(\epsilon)\).
    Then \(\exists A\in D\) s.t. \(\forall i\in A\), \(d_i(x_i,y_i)<\Delta(\epsilon)\). Since \Delta is a modulus of u.c. for
    all \(f_i\). Then \(d_i'(f_i(x_i),f_i(y_i))\le\epsilon\) for all \(i\in A\).
    Hence \(d'(((f(x_i)_{i\in I})_D,((f(y_i)_{i\in I})_D)\le\epsilon\). This shows that
    \((\prod_{i\in I}f_i)_D\) is well-defined and has \Delta as a modulus of u.c.

    Let \((\calm_i\mid i\in I)\) be a family of \(L\)-structures and \(D\) be an ultrafilter on \(I\).
    We define the *\(D\)-ultraproduct of the family \((\calm_i\mid i\in I)\) of \(L\)-structures* to
    be the \(L\)-structure \(\calm\) that is specified as follows
    1. the universe of \(\calm\) is \(M=(\prod_{i\in I}M_i)_D\)
    2. for each predicate \(P\) of \(L\)
       \begin{equation*}
       P^{\calm}=(\prod_{i\in I}P^{\calm_i})_D:M^n\to[0,1]
       \end{equation*}
       since \(([0,1])_D=[0,1]\)
    3. for each function \(f\) of \(L\)
       \begin{equation*}
       f^{\calm}=(\prod_{i\in I}f^{\calm_i})_D:M^n\to M
       \end{equation*}
    4. for each constant \(c\) of \(L\)
       \begin{equation*}
       c^{\calm}=((c^{\calm_i})_{i\in I})_D
       \end{equation*}


    We call \(\calm\) the *\(D\)-ultraproduct of the family* \((\calm_i\mid i\in I)\) and denoted by
    \begin{equation*}
    \calm=(\prod_{i\in I}\calm_i)_D
    \end{equation*}
    \(D\)-ultrapower as \((\calm)_D\)

    #+ATTR_LATEX: :options [Łoś theorem]
    #+BEGIN_theorem
    label:htmB.11
    let \(\varphi(x_1,\dots,x_n)\) be an \(L\)-formula. If \(a_k=((a_i^k)_{i\in I})_D\) are elements
    of \(\calm\) for \(k=1,\dots,n\), then
    \begin{equation*}
    \varphi^{\calm}(a_1,\dots,a_n)=\lim_{i,D}\varphi^{\calm_i}(a^1_i,\dots,a^n_i)
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    Induction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:corB.12
    If \(\calm\) is an \(L\)-structure and \(T:M\to(M)_D\) is the diagonal embedding, then \(T\) is
    an elementary embedding of \(\calm\) into \((\calm)_D\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:corB.13
    If \(\calm\) and \(\caln\) are \(L\)-structures and they have isomorphic ultrapower then
    \begin{equation*}
    \calm\equiv\caln
    \end{equation*}
    #+END_corollary

    #+ATTR_LATEX: :options [Keisler-Shelah]
    #+BEGIN_theorem
    label:thmB.14
    If \(\calm\) and \(\caln\) are \(L\)-structures and \(\calm\equiv\caln\) then there is an
    ultrafilter \(D\) s.t. \((\calm)_D\cong(\caln)_D\)
    #+END_theorem

    #+ATTR_LATEX: :options [Compactness Theorem]
    #+BEGIN_theorem
    label:thmB.15
    Let \(T\) be an \(L\)-theory and \(\calc\) a class of \(L\)-structures. Assume that \(T\) is
    finitely satisfiable in \(\calc\), then there is an ultraporduct of structure from \(\calc\)
    that it is a model of \(T\)
    #+END_theorem

    #+BEGIN_proof
    Let \Lambda be the set of finite subsets of \(T\). Let \(\lambda\in\Lambda\) and
    write \(\lambda =\{E_1,\dots,E_n\}\). by assumption \(\exists M_\lambda\in\calc\)
    s.t. \(\calm_\lambda\vDash\lambda\). For each \(E\in T\), let \(S(E)\) be the set of
    all \(\lambda\in\Lambda\) s.t. \(E\in\lambda\). note that the collection of sets
    \(\{S(E)\mid E\in T\}\) has the FIP (Check!).

    Hence there is a ultrafilter \(D\) on \Lambda that contains \(S(E)\).

    Let \(\calm=(\prod_{\lambda\in\Lambda}M_\lambda)_D\). Note that if \(\lambda\in S(E)\)
    then \(\calm_\lambda\vDash E\). By Łoś theorem, \(\calm\vDash E\) for every \(E\in T\),
    i.e. \(\calm\vDash T\).
    #+END_proof
* Day 3
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  \Sigma is a set of \(L\)-conditions. \(\Sigma^+=\{\varphi\le\frac{1}{n}\mid\varphi=0\in\Sigma,n\in\N\}\), \(\Sigma\neq\Sigma^+\)
  #+END_definition

  *Fact*: \(\Mod_L(\Sigma)=\Mod_L(\Sigma^+)\).

  #+ATTR_LATEX: :options [Approximation version of compactness theorem]
  #+BEGIN_corollary
  Assume that \(T^+\) is finitely satisfiable in \(\calc\). Then there is an ultraproduct of structures
  from \(\calc\) that is a model of \(T\)
  #+END_corollary

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A class \(\calc\) of \(L\)-structures is *axiomatizable* if there is a set \(T\) of
  closed \(L\)-conditions s.t. \(\calc=\Mod_L(T)\). We say that \(T\) a set of *axioms* of \(\calc\) in \(L\).
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.3
  Suppose that \(\calc\) is class of \(L\)-structures. TFAE (the following are equivalent)
  1. \(\calc\) is axiomatizable in \(L\)
  2. \(\calc\) is closed under isomorphisms and ultraprodcuts, and its complement
     \(\{\calm\mid\calm\text{ is not $L$-structure not in }\calc\}\) is closed under ultrapowers.
  #+END_proposition

  #+BEGIN_proof
  \(1\to 2\). Łoś theorem
  \(2\to 1\). Let \(T=\Th(\calc)\) . We will show that \(T\) axiomatizes \(\calc\). Let \(\calm\vDash T\). We will
  show \(\calm\in\calc\).

  _Claim_: \(\Th(\calm)^+\) is finitely satisfiable in \(\calc\).

  Suppose not. There are \(L\)-sentences \(\sigma_1,\dots,\sigma_n\) and \(\epsilon>0\) s.t. \(\sigma_j^{\calm}=0\) for each \(j\).
  But for every \(\caln\in\calc\), \(\sigma_j^{\caln}>\epsilon\) for some \(j\). Then \(\max\{\sigma_1,\dots,\sigma_n\}\ge\epsilon\in T\). But its not
  satisfied in \(\calm\). Contradiction

  Then by the compactness theorem, this yields an ultraproduct \(\calm'\) of structures from \(\calc\)
  s.t. \(\calm'\vDash\Th(M)^+\). Then \(\calm'\equiv\calm\).

  By Keisler-Shelah, \(\exists\) ultrafilter \(D\) s.t. \((\calm')_D\cong(M)_D\). Then by 2, \(\calm\in\calc\)
  thus \(\Mod_L(T)=\calc\)
  #+END_proof


  Consider all continuous \(u:[0,1]^n\to[0,1]\) as connectives is too general. Actually every formula
  can be "uniformly approximated" by a formula from a smaller set

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A system of connectives is a family \(\calf=(F_n\mid n\ge 1)\) where each \(F_n\) is a set of connectives:
  \(f:[0,1]^n\to[0,1]\). We say that \(\calf\) is *closed* if
  1. for each \(n\), \(F_n\) contains the projection \(\pi_j^n:[0,1]^n\to[0,1]\) onto the \(j\)-th
     coordinate. for each \(j\)
  2. for each \(n,m\), if \(u\in F_n\) and \(v_1,\dots,v_n\in F_m\) then \(w:[0,1]^m\to[0,1]\) defined by
     \(w(t)=u(v_1(t),\dots,v_n(t))\) is in \(F_m\), where \(t\in[0,1]^m\)
  #+END_definition

  *Note*: every system \(\calf\) of connectives generates a smallest closed system of
  connectives \(\ove{\calf}\)

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  We say that \(\calf\) is *full* if \(\ove{\calf}\) is uniformly dense in the system of all connectives,
  i.e., \(\forall \epsilon>0\) and \(\forall\) connectives \(f(t_1,\dots,t_n)\), \(\exists g\in\ove{F}_n\) s.t.
  \begin{equation*}
    \abs{f(t_1,\dots,t_n)-g(t_1,\dots,t_n)}<\epsilon
  \end{equation*}
  for all \(t_1,\dots,t_n\in[0,1]\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Given a system \(\calf\) of connectives, we define the collection of *\(\calf\)-restricted formulas* by
  induction
  1. atomic formulas are \(\calf\)-restricted formulas
  2. if \(u\in F_n\) and \(\varphi_1,\dots,\varphi_n\) are \(\calf\)-restricted formulas then
     \(u(\varphi_1,\dots,\varphi_n)\) is an \(\calf\)-restricted formula
  3. if \varphi is an \(\calf\)-restricted formula, so are \(\sup_x\varphi\) and \(\inf_x\varphi\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_theorem
  label:thmC.4
  Assume. that \(\calf\) is a full system of connectives. Then for every \(\epsilon>0\) and
  every \(L\)-formula \(\varphi(x_1,\dots,x_n)\) there is an \(\calf\)-restricted \(L\)-formula \(\psi(x_1,\dots,x_n)\)
  s.t. for all \(L\)-structures \(\calm\) one has
  \begin{equation*}
    \abs{\varphi^{\calm}(a_1,\dots,a_n)-\psi^{\calm}(a_1,\dots,a_n)}\le\epsilon
  \end{equation*}
  for all \(a_1,\dots,a_n\in\calm\)
  #+END_theorem

  Now we look for a simple but full system of connectives.

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(\calf_0=(F_n\mid n\ge 1)\), where \(F_1=\{0,1,\frac{x}{2}\}\), \(F_2=\{\dot-\}\), others are \(\emptyset\).
  #+END_definition

  In \(\ove{F_0}\) we have
  \begin{align*}
    &\min(t_1,t_2)=t_1\dot-(t_1\dot-t_2)\\
    &\max(t_1,t_2)=1\dot-(\min(1\dot-t_1,1\dot-t_2))\\
    &\abs{t_1\dot-t_2}=\max(t_1\dot-t_2,t_2\dot-t_1)\\
    &t_1\dot-(mt_2)=((\dots(t_1\dot-t_2)\dot-\dots)\dot-t_2)
  \end{align*}
  Every dyadic fraction \(\frac{m}{2^n}\in[0,1]\) is in \(\ove{F_1}\)

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.5
  \(\calf_0\) is full
  #+END_proposition

  #+BEGIN_proof
  lattice version of Stone-Weierstrass theorem on \([0,1]^n\).

  Suppose \(X\) is a compact Hausdorff space with \(\ge 2\) points and \(L\) is a lattice
  in \(C(X,\R)\) (all continuous function) with the separative property that
  \(\forall x\neq y\in X\forall a,b\in \R\exists f\in L\) s.t. \(f(x)=a\) and \(f(y)=b\). Then \(L\) is dense in \(C(X,\R)\)
  #+END_proof

  When we say a *restricted formula* we mean an \(\calf_0\)-restricted formula.

  A formula is in *prenex form* if it is of the form \(Q^1x_1Q^2x_2\dots Q^nx_n\psi\) where \psi is a quantifier free
  formula and each \(Q^i\) is either \(\sup\) and \(\inf\)

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.6
  Every restricted formula is equivalent to a restricted formula in prenex form
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \Lambda be a linearly ordered set. A *\(\Lambda\)-chain* of \(L\)-structures is a family
  of \(L\)-structures \((\calm_\lambda\mid \lambda\in\Lambda)\) s.t. \(\calm_\lambda\subseteq \calm_\eta\) for \(\lambda<\eta\). The union
  \(\bigcup_{\lambda\in\Lambda}\calm_\lambda\) is a metric space but not always complete. So we can only get
  an \(L\)-prestructure.  After taking completion, we get an \(L\)-structure. We call it the *union*
  of the chains, denoted by \(\bigcup_{\lambda\in\Lambda}\calm_\lambda\)

  A chain of structures \((\calm_\lambda\mid\lambda\in\Lambda)\) is called an *elementary chain* if \(\calm_\lambda\preceq\calm_\eta\) for all \(\lambda<\eta\).
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.7
  If \((\calm_\lambda\mid\lambda\in\Lambda)\) is an elementary chain and \(\lambda\in\Lambda\) then
  \begin{equation*}
    \calm_\lambda\preceq\bigcup_{\lambda\in\Lambda}\calm_\lambda
  \end{equation*}
  #+END_proposition

  #+BEGIN_proof
  Tarski-Vaught test
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  The *density character* of a topological space \(A\) is the smallest cardinality of a dense subset
  of \(A\), denoted by \(\density(A)\) or \(\norm{A}\)
  #+END_definition

  e.g. a space is separable iff its density character is \(\le\aleph_0\)


  #+ATTR_LATEX: :options [Upward Löwenheim-Skolem Theorem]
  #+BEGIN_proposition
  label:propC.9
  Let \(\calm\) be a non-compact \(L\)-structure. Then for every cardinal \(\kappa\ge\card(L)\), there is an
  elementary extension \(\caln\succeq\calm\) with \(\density(N)\ge\kappa\)
  #+END_proposition

  #+ATTR_LATEX: :options [Downward Löwenheim-Skolem Theorem]
  #+BEGIN_proposition
  Let \kappa be an infinite cardinal and assume \(\card(L)\le\kappa\). Let \(\calm\) be an \(L\)-structure and
  suppose \(A\subseteq M\) has \(\density(A)\le\kappa\). Then there exists a substructure \(\caln\) of \(\calm\) s.t.
  1. \(\caln\preceq\calm\)
  2. \(A\subseteq N\subseteq M\)
  3. \(\density(N)\le\kappa\)
  #+END_proposition

  #+BEGIN_proof
  Let \(A_0\subseteq A\) dense with \(\card(A)\le\kappa\). Since \(\card(L)\le\kappa\), we may enlarge \(A_0\) to get a
  prestructure \(\caln_0\) s.t. \(A_0\subseteq N_0\subseteq M\) and \(\card(N_0)\le\kappa\) and satisfies the following
  property

  (*)  for every restricted \(L\)-formula \(\varphi(x_1,\dots,x_n,x_{n+1})\) and every rational \(\epsilon>0\),
  if \(\varphi^{\calm}(a_1,\dots,a_n,c)\le\epsilon\) with \(a_k\in N_0\) for each \(k\) and \(c\in M\) then \(\exists b\in N_0\) s.t.
  \(\varphi^{\calm}(a_1,\dots,a_n,b)\le\epsilon\)

  Since \(L\) has at most \kappa many restrict formulas, it's possible to get \(N_0\)
  with \(\card(N_0)\le\kappa\). Let \(N=\ove{N_0}\subseteq M\). By considering atmoic formulas in (*) based
  on \(N\), there is \(\caln\subseteq\calm\). Then using Tarski-Vaught test to show \(\caln\preceq\calm\)

  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(\Gamma(x_1,\dots,x_n)\) be a set of \(L\)-conditions and let \(\calm\) be an \(L\)-structure. We say
  that \(\Gamma(x_1,\dots,x_n)\) is *satisfiable* in \(\calm\) if there are \(a_1,\dots,a_n\in M\) s.t. \(\calm\vDash\Gamma(a_1,\dots,a_n)\).
  We also write
  \begin{equation*}
    (a_1,\dots,a_n)\vDash\Gamma(x_1,\dots,x_n)
  \end{equation*}
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
    We say that \(\calm\) is *\(\kappa\)-saturated* if whenever \(A\subseteq M\) has
    cardinality \(\le\kappa\) and \(\Gamma(x_1,\dots,x_n)\) is a set of \(L(A)\)-conditions if every finite subset of
    \Gamma is satisfiable, then \Gamma is satisfiable in \((\calm,a)_{a\in A}\)

    An ultrafilter \(D\) is *countably incomplete* if \(D\) is not closed under countable intersection
    \(\Leftrightarrow\) \(\exists\{J_n\}_{n\in\N}\subseteq D\) s.t. \(\bigcap_{n\in\N}J_n=\emptyset\)
  #+END_definition

  *Fact*: every non-principal ultrafilter on a countable set is countably incomplete

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.10
  Let \(L\) be a countable signature and let \(D\) be a countably incomplete ultrafilter on a set \Lambda.
  Then for every family \((\calm_\lambda\mid\lambda\in\Lambda)\) of \(L\)-structures, \((\prod_{\lambda\in\Lambda}\calm_\lambda)_D\) is \(\omega_1\)-saturated
  #+END_proposition

  In saturated structures, the meaning of \(L\)-conditions can be analyzed using the usual
  quantifiers \(\forall\) and \(\exists\).

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.11
  Suppose \(E(x_1,\dots,x_n)\) is the \(L\)-condition
  \begin{equation*}
    (Q_{y_1}^1\dots Q_{y_n}^n\varphi(x_1,\dots,x_m,y_1,\dots,y_n))=0
  \end{equation*}
  where each \(Q^i\) is either \(\inf\) or \(\sup\) and \varphi is quantifier free.

  Let \(\Epsilon(x_1,\dots,x_n)\) be the mathematical statement
  \begin{equation*}
    \tilde{Q}^1_{y_1}\dots\tilde{Q}^n_{y_n}(\varphi(x_1,\dots,x_m,y_1,\dots,y_n)=0)
  \end{equation*}
  where each \(\tilde{Q}_{y_i}^i\) is \(\exists y_i\) if \(Q_{y_i}^i\) is \(\inf y_i\) and is \(\forall y_i\) otherwise

  If \(\calm\) is \(\omega\)-saturated, then for all \(a_1,\dots,a_m\in M\),
  \(\calm\vDash E[a_1,\dots,a_m]\)  iff \(\Epsilon(a_1,\dots,a_m)\) is true in \(\calm\)
  #+END_proposition

  #+BEGIN_proof
  Induction on \(n\). For the induction step. Suppose \(E\) is
  \((\inf_y\psi(x_1,\dots,x_m,y))=0\) and \(\calm\) is \(\omega\)-saturated. Then
  \((\inf_y\psi(a_1,\dots,a_m,y))=0\) holds in \(\calm\) iff
  \(\exists b\in M\) s.t. \(\psi(a_1,\dots,a_m,b)=0\) holds in \(\calm\)

  \(\Rightarrow\). Consider \(L\)-condition \(\{\psi(a_1,\dots,a_n,y)\le\frac{1}{n}\}_{n\in\N}\). Take \(b\in M\) to satisfy
  them since \(\calm\) is \(\omega\)-saturated.
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.12
  Let \(\calm\) be an \(L\)-structure and let \kappa be an infinite cardinal. Then \(\calm\) has a \kappa-saturated
  elementary extension
  #+END_proposition

  #+BEGIN_proof
  Need enlargement and more
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  We say that \(\calm\) is *strongly \kappa-homogeneous* if whenever \(L(C)\) is an extension of \(L\) by
  constants with \(\card(C)<\kappa\) and \(f,g\) are functions from \(C\) to \(M\)
  s.t. \((\calm,f(c))_{c\in C}\equiv(\calm,g(c))_{c\in C}\) one has \((\calm,f(c))_{c\in C}\cong(\calm,g(c))_{c\in C}\).
  #+END_definition

  *Note*: an isomorphism from  \((\calm,f(c))_{c\in C}\) onto \((\calm,g(c))_{c\in C}\) is an automorphism
  of \(\calm\) that takes \(f(c)\) to \(g(c)\) for each \(c\in C\)

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.12
  \(\calm\) has a \kappa-saturated elementary extension \(\caln\) s.t. each reduct of \(\caln\) to a subsignature
  of \(L\) is strongly \kappa-homogeneous
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(T\) be a complete theory and let \kappa be an infinite cardinal. A *\kappa-universal domain*
  for \(T\) is \kappa-saturated, strongly \kappa-homogeneous model of \(T\).
  #+END_definition

  By Proposition ref:propC.12, every complete theory has a \kappa-universal domain for every infinite
  cardinal \kappa.

  Continuou logic is a "positive" logic
  1. in a saturated model (its from compactness)
  2. in all models of \(T\) (compactness)



  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.13
  Let \(\calm\) be an \(\omega\)-saturated model of \(T\). TFAE
  1. For all \(a\in M^n\), if \(\varphi^{\calm}(a)=0\) then \(\psi^{\calm}(a)=0\)
  2. \(\forall\epsilon>0\exists\delta>0\forall a\in M^n(\varphi^{\calm}(a)<\delta\Rightarrow\psi^{\calm}(a)\le\epsilon)\)
  3. There is an increasing continuous function \(\alpha:[0,1]\to[0,1]\) with \(\alpha(0)=0\) s.t.
     \(\psi^{\calm}(a)\le\alpha(\varphi^{\calm}(a))\) for all \(a\in M^n\), i.e.
     \begin{equation*}
     \sup_x(\psi(x)\dot-\alpha(\varphi(x)))=0
     \end{equation*}
  #+END_proposition

  #+BEGIN_proof
  \(1\to 2\). Suppose not. then \(\exists\epsilon>0\), \(\{\psi(s)\ge\epsilon,\varphi(x)\le\frac{1}{n}\mid n\ge 1\}\) is finitely satisfiable
  in \(\calm\). Then there is \(a\in M^n\) s.t. \(\psi^{\calm}(a)\ge\epsilon\) while \(\varphi^{\calm}(a)\le\frac{1}{n}\) for
  all \(n\ge 1\), contradicting 1
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.14
  TFAE
  1. For all \(\calm\vDash T\) and all \(a\in M^n\), if \(\varphi^{\calm}(a)=0\) then \(\psi^{\calm}(a)=0\)
  2. For all \(\epsilon>0\) there exists \(\delta>0\) s.t.
     \begin{equation*}
     T\vDash\sup_x\min(\delta\dot-\varphi(x),\psi(x)\dot-\epsilon)=0
     \end{equation*}
  #+END_proposition

  #+BEGIN_proof
  \(2\to 1\) is obvious

  \(1\to 2\). Suppose not \(\exists\epsilon>0\), \(\{\psi(x)\ge\epsilon,\varphi(x)\le\frac{1}{n}\mid n\ge1\}\) is finitely satisfiable. by
  compactness, there is \(\calm\vDash T\) and \(a\in M^n\) s.t. \(\psi^{\calm}(a)\ge\epsilon\) while \(\varphi^{\calm}(a)\le\frac{1}{n}\)
  for all \(n\ge 1\)
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Suppose \(\calm\vDash T\), \(A\subseteq M\). Denote \(L(A)\)-structure \((\calm,a)_{a\in A}\)
  by \(\calm_A\). \(T_A=\Th_{L(A)}(\calm_A)\)

  A set \(p\) of \(L(A)\)-conditions with \(n\) free variables \(x_1,\dots,x_n\) is called an *\(n\)-type
  over \(A\)* if there exists a model \((\calm,a)_{a\in A}\) of \(T_A\) and \(e_1,\dots,e_n\in M\) s.t. \(p\) is
  the set of all \(L(A)\)-conditions \(E(x_1,\dots,x_n)\) for which \(\calm_A\vDash E[e_1,\dots,e_n]\)

  We denote \(p\) by \(\tp_{\calm}(e_1,\dots,e_n/A)\) and we say *\((e_1,\dots,e_n)\) realizes \(p\) in \(\calm\)*

  The collection of all such \(n\)-types over \(A\) is denoted by \(S_n(T_A)\) or simply \(S_n(A)\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(\varphi(x_1,\dots,x_n)\) be an \(L(A)\)-formula, and \(\epsilon>0\).
  \begin{equation*}
    [\varphi<\epsilon]=\{q\in S_n(T_A)\mid\text{for some }0\le\delta<\epsilon\text{ the condition }(\varphi\le\delta)\in q\}
  \end{equation*}

  The *logic topology* on \(S_n(T_A)\) is defined as follows. If \(p\in S_n(T_A)\) then basic open
  neighborhoods of \(p\) are the sets of the form \([\varphi<\epsilon]\) for which the condition \(\varphi=0\) is
  in \(p\) and \(\epsilon>0\).
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  The logic topology is Hausdorff
  #+END_proposition

  #+BEGIN_proof
  \(\forall p\neq q\in S_n(T_A)\). Then there exists an \(L(A)\)-formula \(\varphi(x_1,\dots,x_n)\) s.t. \(\varphi=0\) is in
  exactly \(p\) or \(q\). Then there is \(r>0\) s.t. \(\varphi=r\) is in the another.
  Take \(\epsilon=\frac{r}{2}>0\), then \([\varphi<\frac{r}{2}]\) and \([(r\dot-\varphi)<\epsilon]\) are disjoint for the
  logic topology
  #+END_proof

  \([\varphi\le\epsilon]=\{q\in S_n(T_n)\mid (\varphi\le\epsilon)\in q\}\). Note that \([\varphi\le\epsilon]\) is closed in logic topology

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaC.15
  The closed subset of \(S_n(T_A)\) for the logic topolgy are exactly the sets of the form
  \(C_\Gamma=\{p\in S_n(T_A)\mid \Gamma(x_1,\dots,x_n)\subseteq p\}\) where \(\Gamma(x_1,\dots,x_n)\) is a set of \(L(A)\)-conditions
  #+END_lemma

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.16
  For each \(n\ge1\), \(S_n(T_A)\) is compact w.r.t. logic topology
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(\calm_A=(\calm,a)_{a\in A}\) be a model of \(T_A\) in which each type in \(S_n(T_A)\) is realized.
  For \(p,q\in S_n(T_A)\) we define \(d(p,q)\) to be
  \begin{equation*}
    \inf\{\max_{1\le j\le n}d(b_j,c_j)\mid \calm_A\vDash p[b_1,\dots,b_n],\calm_A\vDash q[c_1,\dots,c_n]\}
  \end{equation*}
  Check: the definition \(d(p,q)\) doesn't depend on \(\calm_A\)

  \((S_n(T_A),d)\) is a metric space. This is called the *\(d\)-metric topology*
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.17 the \(d\)-metric topolgy is finer than the logic topolgy
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propC.18
  The metric space \((S_n(T_A),d)\) is complete
  #+END_proposition

  #+BEGIN_proof
  Let \((p_k)_{k\ge1}\) be a Cauchy sequence in \((S_n(T_A),d)\). WLOG,
  WMA, \(d(p_k,p_{k+1})\le 2^{-k}\) for all \(k\).

  Let \(\caln\) be an \(\omega\)-saturated and strongly \omega-homogeneous model of \(T_A\). We assume \(\caln=\calm_A\)
  for some \(\calm\vDash T\). By saturation and homogeneity, for every \(a\in M^n\) realizing \(p_k\), there
  is \(b\in M^n\) realizing \(p_{k+1}\) s.t. \(d(a,b)=d(p_k,p_{k+1})\). Inductively, we can generate a
  sequence \((b_k)_{k\ge1}\) s.t. \(b_k\vDash p_k\) and \(d(b_k,b_{k+1})=d(p_k,p_{k+1})\le 2^{-k}\) for all \(k\)
  #+END_proof
* Day 4
  1. Why we consider uniform continuous functions with the same \(\Delta_f\)

     \(\Delta_f\) is preserved under ultraproduct
     1. What if \(\{f_n\}\) are not continuous

        \(f_n:[0,1]\to[0,1]\), \(f_n(x)=0\) if \(0\le x<\frac{1}{n}\), \(f_n=1\)
        if \(\frac{1}{n}\le x\le 1\). \(D\) is an ultrafilter on \(\N\).
        \(\prod_Df_n:\prod_D[0,1]\to[0,1]\). Note that
        \((0,\dots,0,\dots)\sim(0,1,\frac{1}{2},\dots,\frac{1}{n},\dots)\).
        \(\prod_Df_n((0,\dots,0,\dots))=0\), \(\prod_Df_n((0,1,\frac{1}{2},\dots,\frac{1}{n},\dots))=1\). So
        \(\prod_Df_n\) is not well-defined

     2. Even \(f_n:[0,1]\to[0,1]\) are uniformly continuous but \(\Delta_{f_n}\) are different. Still
        \(\prod_Df_n((0,\dots,0,\dots))=0\),\(\prod_Df_n((0,1,\dots,\frac{1}{n},\dots))=1\)

  2. Consider the theory of \(L^p\) Banach lattices.

  3. FOL \(\calm\) \(\to\) considered as a metric structure with discrete metric
  , then \(\sup=\forall\),\(\inf=\exists\)


  Let \(\calm_A=(\calm,a)_{a\in A}\) be a model of \(T_A\) in which each type in \(S_n(T_A)\) is realized for
  each \(n\ge1\). Let \(\varphi(x_1,\dots,x_n)\) be an \(L(A)\)-formula

  For each type \(p\in S_n(T_A)\), \(\tilde{\varphi}(p)=r\) where \(r\) is the unique real number
  s.t. \(\varphi=r\in p\). Equivalently, \(\tilde{\varphi}(p)=\varphi^{\calm}(b)\) where \(b\vDash p\)

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaD.1
  Let \(\varphi(x_1,\dots,x_n)\) be an \(L(A)\)-formula. Then \(\tilde{\varphi}:S_n(T_A)\to[0,1]\) is continuous for
  the logic topology and uniformly continuous for the \(d\)-metric distance on \(S_n(T_A)\)
  #+END_lemma

  #+BEGIN_proof
  1. \(\tilde{\varphi}^{-1}(r-\epsilon,r+\epsilon)=\abs{\abs{\varphi\dot-r}<\epsilon}\)
  2. \(\Delta_\varphi\) for \(\varphi^{\calm}\) is also a modulus of u.c. for \(\tilde{\varphi}\)
  #+END_proof

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propD.2
  Let \(\Phi:S_n(T_A)\to[0,1]\). TFAE
  1. \Phi is continuous for the logic topology on \(S_n(T_A)\)
  2. There is a sequence \((\varphi_k(x_1,\dots,x_n)\mid k\ge 1)\) of \(L(A)\)-formulas s.t.
     \((\tilde{\varphi}_k\mid k\ge 1)\) uniformly converges to \Phi on \(S_n(T_A)\)
  3. \Phi is continuous for the logic topology and uniformly continuous for the \(d\)-metric on \(S_n(T_A)\)
  #+END_proposition

  definable predicates \(\leadsto\) definable sets \(\leadsto\) definable functions
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A predicate \(P:M^n\to[0,1]\) is *definable* in \(\calm\) over \(A\) if there is a sequence
  \((\varphi_k(x)\mid k\ge1)\) of \(L(A)\)-formulas s.t. \(\varphi_k^{\calm}(x)\rightrightarrows p(x)\) on \(M^n\)
  (uniformly converge),
  i.e., \(\forall \epsilon>0\exists N\forall k\ge N\forall x\in M^n\), \(\abs{\varphi_k^{\calm}(x)-p(x)}\le\epsilon\)
  #+END_definition

  We enlarge our connectives to include all continuous \(u:[0,1]^{\N}\to[0,1]\)

  Define \(\rho:[0,1]^{\N}\times[0,1]^{\N}\to[0,1]\), \((a_k),(b_k)\mapsto\sum_{k=0}^n2^{-k}\abs{a_k-b_k}\)

  \(([0,1]^{\N},\rho)\) is a compact metric space

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propD.3
  Let \(\calm\) be an \(L\)-structure with \(A\subseteq M\) and suppose \(P:M^n\to[0,1]\) is a predicate. Then
  \(P\) is definable in \(\calm\) over \(A\) iff there is a continuous function \(u:[0,1]^{\N}\to[0,1]\)
  and \(L(A)\)-formulas sequence \((\varphi_k\mid k\ge 1)\) s.t.
  \(\forall x\in M^n\) \(P(x)=u(\varphi_k^{\calm}(x)\mid k\in\N)\)
  #+END_proposition

  #+BEGIN_remark
  \(u\) is completely independent of \(P\)
  #+END_remark

  #+ATTR_LATEX: :options []
  #+BEGIN_lemma
  label:lemmaD.4
  Suppose \(P:M^n\to[0,1]\) is definable in \(\calm\) over \(A\) and consider \(\caln\preceq\calm\) with \(A\subseteq N\).
  Then \(\inf_xP(x)\) and \(\sup_xP(x)\) have the same value in \(\caln\) as in \(\calm\)
  #+END_lemma

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propD.5
  Let \(P_i:M^n\to[0,1]\) be definable in \(\calm\) over \(A\) for \(i=1,\dots,m\) and consider \(\caln\preceq\calm\).
  Let \(Q_i\) be \(P_i\mid N^n\) for each \(i\). Then \((\caln,Q_1,\dots,Q_m)\preceq(\calm,P_1,\dots,P_m)\)
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propD.6
  Let \(P:M^n\to[0,1]\) be definable in \(\calm\) over \(A\) and consider an elementary extension \(\caln\)
  of \(\calm\). There is a unique predicate \(Q:N^n\to[0,1]\) s.t. \(Q\) is definable in \(\caln\) over \(A\)
  and \(P\)  is the restriction of \(Q\) to \(M^n\). This predicate satisfies
  \begin{equation*}
    (\calm,P)\preceq(\caln,Q)
  \end{equation*}
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_theorem
  label:thmD.7
  Let \(P:M^n\to[0,1]\) be a function. Then \(P\) is a predicate definable in \(\calm\) over \(A\) iff
  there is \(\Phi:S_n(T_A)\to[0,1]\) that is continuous w.r.t. the logic topology on \(S_n(T_A)\)
  s.t. \(P(a)=\Phi(\tp_{\calm}(a/A))\) for all \(a\in M^n\)

  #+END_theorem

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A subset \(S\subseteq M^n\) is *type-definable* in \(\calm\) over \(A\) if there is a set \(\Sigma(x_1,\dots,x_n)\)
  of \(L(A)\)-formulas s.t. for every \(a\in M^n\) we have \(a\in S\) iff \(\varphi^{\calm}(a)=0\) for
  every \(\varphi\in\Sigma\). We say that \(S\) is *type-defined by* \Sigma

  #+END_definition

  In saturated models, definable predicates have a new characterization

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  label:corD.8
  Let \(\calm\) be a \kappa-saturated \(L\)-structure and \(A\subseteq M\) with \(\card(A)\le\kappa\); let \(P:M^n\to[0,1]\) be
  a function. Then we have: \(P\) is a predicate definable in \(\calm\) over \(A\) iff the sets of
  \(\{a\in M^n\}\mid P(a)\le r\) and \(\{a\in M^n\mid P(a)\ge r\}\) are type-definable in \(\calm\) over \(A\) for every \(r\in[0,1]\)
  #+END_corollary

  Let \(D\subseteq M^n\). Define \(\dist(x,D)=\inf\{d(x,y)\mid y\in D\}\). It's a map \(M^n\to[0,1]\).
  \(\forall x=(x_1,\dots,x_n),y=(y_1,\dots,y_n)\in M^n\),
  \begin{equation*}
    d(x,y)=\max(d(x_1,y_1),\dots,d(x_n,y_n))
  \end{equation*}
  \(\dist(x,D)\) can be characterized by axioms in CFO

  Consider a predicate \(P:M^n\to[0,1]\)

  | E1 | \(\sup_x\inf_y\max(P(y),\abs{P(x)-d(x,y)})=0\) |
  | E2 | \(\sup_x\abs{P(x)-\inf_y\min(P(y)+d(x,y),1))}=0\)     |

  Observation: \(\forall \emptyset\neq D\subseteq M^n\), \(P(x)=\dist(x,D)\) satisfies E1 and E2

  #+ATTR_LATEX: :options []
  #+BEGIN_theorem
  label:thmD.9
  let \((\calm,F)\) be a \(L\)-structure satisfy E1 and E2. Let \(D=\{x\in M^n\mid F(x)\}\) be the zero set
  of \(F\). Then \(F(x)=\dist(x,D)\)  for all \(x\in M^n\)
  #+END_theorem

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Let \(D\subseteq M^n\). We say that \(D\) is a *zeroset* in \(\calm\) over \(A\) if there is a
  predicate \(P:M^n\to[0,1]\) definable in \(\calm\) over \(A\) s.t. \(D=\{x\in M^n\mid P(x)=0\}\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  TFAE
  1. \(D\) is a zeroset in \(\calm\)
  2. there is a sequence \((\varphi_m\mid m\ge1)\) or \(L\)-formulas s.t.
     \begin{align*}
     D&=\{x\in M^n\mid\varphi_m^{\calm}=0\forall m\in\N\}\\
     &=\bigcap_{m=1}^\infty\text{zeroset of }\varphi_m^{\calm}
     \end{align*}
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_corollary
  The collection of zerosets in \(\calm\) over \(A\) is closed under countable intersection
  #+END_corollary

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  A closed set \(D\subset M^n\) is *definable* in \(\calm\) over \(A\) if the distance predicate \(\dist(X,D)\)
  is definable in \(\calm\) over \(A\)
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_theorem
  label:thmD.12
  Let \(D\subseteq M^n\) be a closed set. TFAE
  1. \(D\) is definable in \(\calm\) over \(A\)
  2. For every predicate \(P:M^m\times M^n\to[0,1]\) that is definable in \(\calm\) over \(A\), the predicate
     \(Q:M^m\to[0,1]\) defined by \(Q(x)=\inf\{P(x,y)\mid y\in D\}\) is definable in \(\calm\) over \(A\)
  #+END_theorem

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  label:propD.13
  Let \(\caln\preceq\calm\) be a \(L\)-structure and let \(D\subseteq M^n\) be definable in \(\calm\) over \(A\)
  where \(A\subseteq N\)
  #+END_proposition
