#+TITLE: Introduction To Model Theory

#+AUTHOR: Will Johnson
#+EXPORT_FILE_NAME: ../latex/IntroductionToModelTheory/IntroductionToModelTheory.tex
#+STARTUP: overview
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \def \EF {\text{EF}}
#+LATEX_HEADER: \def \tint {\text{int}}

* Back-and-forth Equivalence \rom{1}
    Convention: Relations and functions are sets of pairs \((x,y)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *binary relation* is a pair \((E,R)\) where \(E\) is a set and \(R\subseteq E^2\). We call \(E\) the
    *universe* of the relation. For \(a,b\in E\), write \(aEb\) if \((a,b)\in R\)
    #+END_definition

    We abbreviate \((E,R)\) as \(R\) or \(E\), if \(E\) or \(R\) is clear

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \((\R,<)\), \((\R,=)\), \((\R,\ge)\),\((\Z,<)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A binary relation \(R\) is said to be
    - *reflexive* if \(aRa\) (\(\forall a\in E\))
    - *symmetric* if \(aRb\Rightarrow bRa\) (\(\forall a,b\in E\))
    - *transitive* if \(aRb\wedge bRc\Rightarrow aRc\) (\(\forall a,b,c\in E\))
    - *antisymmetric* if \(aRb\wedge bRa\Rightarrow a=b\) (\(\forall a,b\in E\))
    - *total* if \(aRb\vee bRa\) (\(\forall a,b\in E\))
    - an *equivalence relation* if it's reflexive, symmetric and transitive
    - a *partial order* if it's reflexive, antisymmetric and transitive
    - a *linear order*  if it's a total partial order
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(=\) is an equivalence relation

    \(\subseteq\) is a partial order

    \(\le\) is a linear order
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *isomorphism* from \((E,R)\) to \((E',R')\) is a bijection \(f:E\to E'\) s.t. for any \(a,b\in E\),
    \(aRb\Leftrightarrow f(a)R'f(b)\). Two binary relations \((E,R)\) and \((E',R')\) are *isomorphic* (\(\cong\)) if
    there is an isomorphism between them
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(f:(\Z,<)\to(2\Z,>)\) and \(f(x)=-2x\) is an isomorphism. \(x<y\Leftrightarrow -2x>-2y\)
    #+END_examplle

    \(\cong\) is an equivalence relation

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *local isomorphism* from \(R\) to \(R'\) is an isomorphism from a finite restriction of \(R\) to
    a finite restriction of \(R'\). The set of local isomorphisms from \(R\) to \(R'\) is
    denoted \(S_0(R,R')\). For \(f\in S_0(R,R')\), \(\dom(f)\) and \(\im(f)\) denote the domain and
    range of \(f\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
     \((\Z,<)\) is a restriction of \((\R,<)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Suppose \(R=R'=(\Z,<)\), there is \(f\in S_0(R,R')\) given by \(\dom(f)​=\{1,2,3\}\)
    and \(\im(f)​=\{10,20,30\}\) and \(f(1)=10\),\(f(2)=20\), \(f(3)=30\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(f,g\) be local isomorphisms from \(R\) to \(R'\). Then \(f\) is a *restriction* of \(g\)
    if \(f\subseteq g\) and \(f\) is an *extension* of \(g\) if \(f\supseteq g\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(g:\{0,1,2,3\}\to\{5,10,20,30\}\), \(g\) extends \(f\) in the previous example
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(R,R'\) be binary relations with universe \(E,E'\). A *Karpian family* for \((R,R')\) is a
    set \(K\subseteq S_0(R,R')\) satisfying the following two conditions for any \(f\in K\)
    1. (*forth*) if \(a\in E\) then there is \(g\in K\) with \(g\supseteq f\) and \(a\in\dom(g)\)
    2. (*back*) if \(b\in E'\) then there is \(g\in K\) with \(g\supseteq f\) and \(b\in\im(g)\)


    \(R\) and \(R'\) are *\(\infty\)-equivalent*, write \(R\sim_\infty R'\), if there is a non-empty
    Karpian family
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f:(E,R)\to(E',R')\) an isomorphism and \(K=\{g\subseteq f:g\text{ is finite}\}\), then \(K\) is Karpian
    and \(R\sim_\infty R'\)
    #+END_proposition

    #+BEGIN_proof
    Suppose \(g\in K\)
    * (forth) Suppose \(a\in E\), take \(b=f(a)\) and let \(h=g\cup\{(a,b)\}\). Then \(h\subseteq f\),
      so \(h\in K\), \(h\supseteq g\), \(a\in\dom(h)\)
    * (back) similarly
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \((E,R)\) and \((E',R')\) are countable and \(R\sim_\infty R'\), then \(R\cong R'\)
    #+END_proposition

    #+BEGIN_proof
    Let \(K\subseteq S_0(R,R')\) be Karpian, \(K\neq\emptyset\), \(E=\{e_1,e_2,e_3,\dots\}\), \(E'=\{e_1',e_2',e_3',\dots\}\)

    Recursively build \(f_1\subseteq f_2\subseteq\cdots\), \(f_i\in K\)

    Let \(f_1\) be anything in \(K\) as \(K\) is non-empty.

    \(f_{2i}\) some extension of \(f_{2i-1}\) with \(e_i\in\dom(f_{2i})\)

    \(f_{2i+1}\) some extension of \(f_{2i}\) with \(e_i'\in\im(f_{2i+1})\)

    Now let \(g=\bigcup_{i=1}^\infty f_i\), then \(g\) is an isomorphism
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *dense linear order without endpoints* (DLO) is a linear order \((C,\le)\) satisfying
    1. \(C\neq\emptyset\)
    2. \(\forall x,y\in C\), \(x<y\Rightarrow\exists z\in C\; x<z<y\)
    3. \(\forall x\in C\), \(\exists y,z\in C\;y<x<z\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \((\Q,\le)\), \((\R,\le)\)

    non-example: \((\Z,\le)\), \(([0,1],\le)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \((C,\le)\) and \((C',\le)\) be DLO's. Then \(S_0(C,C')\) is Karpian. So \(C\sim_\infty C'\)
    #+END_proposition

    #+BEGIN_proof
    Let \(f\in S_0(C,C')\), \(\dom(f)=\{a_1,\dots,a_n\}\), \(a_1<\dots<a_n\)
    and \(\im(f)=b_1,\dots,b_n\), \(b_1<\dots<b_n\). Since \(f\) is a local isomorphism, \(f(a_i)=b_i\)
    * (forth) Suppose \(a\in C\). We want \(b\in C'\) s.t. \(f\cup\{(a,b)\}\in S_0(C,C')\).
      + if \(a_i<a<a_{i+1}\). We take \(b\in C'\) s.t. \(b_i<b<b_{i+1}\) since dense
      + if \(a<a_1\). We take \(b\in C'\) s.t. \(b<b_1\) since no endpoints
      + if \(a>a_n\), take \(b\in C'\) s.t. \(b>b_n\)
      + if \(a=a_i\), take \(b=b_i\)
    * (back) similar
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \((C,\le)\) and \((C',\le)\) are countable DLOs, then \(C\sim_\infty C'\), so \(C\cong C'\)
    #+END_proposition
    Hence
    \begin{align*}
    (\Q,\le)&\cong(\Q\setminus\{0\},\le)\\
    &\cong(\Q\cup\{\sqrt{2}\},\le)\\
    &\cong(\Q\cap(0,1),\le)
    \end{align*}
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(R,R'\) be binary relations with universe \(E,E'\)
    * A *0-isomorphism* from \(R\) to \(R'\) is a local isomorphism from \(R\) to \(R'\)
    * For \(p>0\), a *\(p\)-isomorphism* from \(R\) to \(R'\) is a local isomorphism \(f\) from \(R\)
      to \(R'\) satisfying the following two conditions
      1. (*forth*) For any \(a\in E\), there is a \((p-1)\)-isomorphism \(g\supseteq f\) with \(a\in\dom(g)\)
      2. (*back*) For any \(b\in E'\), there is a \((p-1)\)-isomorphism \(g\supseteq f\) with \(b\in\im(g)\)
    * An *\omega-isomorphism* from \(R\) to \(R'\) is a local isomorphism \(f\) from \(R\) to \(R'\)
      s.t. \(f\) is a \(p\)-isomorphism for all \(p<\omega\)


    The set of \(p\)-isomorphisms from \(R\) to \(R'\) is denoted \(S_p(R,R')\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Suppose \(R=R'=(\Z,<)\), \(f:\{2,4\}\to\{1,2\}\) is a local isomorphism with \(f(2)=1\) and \(f(4)=2\).
    Then \(f\notin S_1(\Z,\Z)\) (forth) fails. For \(a=3\), there is no \(b\) s.t. \(1<b<2\)

    \(g:\{2,4\}\to\{1,5\}\) is a 1-isomorphism but not a 2-isomorphism
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f\in S_p(R,R')\) and \(g\subseteq f\), then \(g\in S_p(R,R')\)
    #+END_proposition

    #+BEGIN_proof
    if \(p=0\) easy

    if \(p>0\) (forward), \(\forall a\in E\), \(\exists h\in S_{p-1}(R,R')\) has \(a\in\dom(h)\) and \(h\supseteq f\supseteq g\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(S_p(R,R')\neq\emptyset\) iff \(\emptyset\in S_p(R,R')\)
    #+END_proposition

    #+BEGIN_proof
    \(\Leftarrow\) immediate

    \(\Rightarrow\). Suppose \(f\in S_p(R,R')\). Then \(\emptyset\subseteq f\). Hence \(\emptyset\in S_p(R,R')\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(R\) and \(R'\) are *\(p\)-equivalent*, written \(R\sim_p R'\), if there is a \(p\)-isomorphism
    from \(R\to R'\)
    #+END_definition

    \(R\) and \(R'\) are *\omega-equivalent* or *elementarily equivalent*, written \(R\sim_\omega R'\)
    or \(R\equiv R'\), if there is an \omega-isomorphism from \(R\) to \(R'\)

    Note: \(R\sim_\omega R'\) iff \(S_\omega(R,R')\neq\emptyset\) iff \(\emptyset\in S_\omega(R,R')\) iff \(\forall p\;\emptyset\in S_p(R,R')\)
    iff \(\forall p\; R\sim_pR'\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(R,R'\) be binary relations with universe \(E,E'\). The Ehfrenfeucht-Fraïssé game of
    length \(n\), denoted \(\EF_n(R,R')\) is played as follows
    * There are two players, the Duplicator and Spoiler
    * There are \(n\) rounds
    * In the \(i\)th round, the Spoiler chooses either an \(a_i\in E\) or a \(b_i\in E'\)
    * The Duplicator responds with a \(b_i\in E'\) or an \(a_i\in E\) respectively
    * At the ends of the game, the Duplicator wins
      \begin{equation*}
      \{(a_i,b_i),\dots,(a_n,b_n)\}
      \end{equation*}
      is a local isomorphism from \(R\) to \(R'\)
    * Otherwise, the Spoiler wins
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    For \(\EF_3(\Q,\R)\)
    | \(\Q\)        | \(\R\)             |
    |--------------+-------------------|
    | S:\(a_1=7\)   | D:\(b_1=7\)        |
    | D:\(a_2=1.4\) | S:\(b_2=\sqrt{2}\) |
    | D:\(a_3=-10\) | S:\(b_3=1.41\)     |

    So \(D\) wins
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\EF_3(\R,\Z)\)

    | \(\R\)         | \(\Z\)      |
    | D:\(a_1=1\)    | S:\(b_1=1\) |
    | D:\(a_2=1.1\)  | S:\(b_2=2\) |
    | S:\(a_3=1.01\) |              |
    D fails
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(\EF_n(R,R')\) is a win for Duplicator iff \(R\sim_nR'\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    In \(\EF_n(R,R')\) if moves so far are \(a_1,b_1,\dots,a_i,b_i\), \(p=n-1\), \(f=\{(a_1,b_1),\dots,(a_i,b_i)\}\).
    Then Duplicator wins iff \(f\in S_p(R,R')\)
    #+END_proposition
* Back-and-forth Equivalence \rom{2}
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((M,R)\), \((M',R')\) be binary relations.. The Ehfrenfeucht-Fraïssé game of
    length \(n\), denoted \(\EF_n(M,M')\) is played as follows
    * There are two players, the Duplicator and Spoiler
    * There are \(n\) rounds
    * In the \(i\)th round, the Spoiler chooses either an \(a_i\in M\) or a \(b_i\in M'\)
    * The Duplicator responds with a \(b_i\in M'\) or an \(a_i\in M\) respectively
    * At the ends of the game, the Duplicator wins
      \begin{equation*}
      \{(a_i,b_i),\dots,(a_n,b_n)\}
      \end{equation*}
      is a local isomorphism from \(R\) to \(R'\)
    * Otherwise, the Spoiler wins
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose we are playing \(\EF_n(M,M')\) and there have been \(q\) rounds so far, with \(p=n-q\)
    rounds remaining. Suppose the moves so far are \((a_1,b_1),\dots,(a_n,b_n)\).
    Let \(f=\{(a_1,b_1),\dots,(a_q,b_q)\}\). Then the following are equivalent
    * Duplicator has a winning strategy
    * \(f\) is a \(p\)-isomorphism
    #+END_lemma

    #+BEGIN_proof
    By induction on \(p\).

    if \(p=0\), then the game is over, so Duplicator wins iff \(f\in S_0(M,M')\)

    \(p>0\). If \(f\) isn't a local isomorphism, then Duplicator will definitely lose, and \(f\)
    isn't a \(p\)-isomorphism. So we may assume \(f\in S_0(M,M')\). Then the following are equivalent
    * Duplicator wins
    * For any \(a_{q+1}\in M\), there is a \(b_{q+1}\in M'\) s.t. Duplicator wins in the
      position \((a_1,b_1,\dots,a_{q+1},b_{q+1})\),  AND for any \(b_{q+1}\in M'\), there is a \(a_{q+1}\in M\) s.t. Duplicator wins in the
      position \((a_1,b_1,\dots,a_{q+1},b_{q+1})\),
    * For any \(a_{q+1}\in M\) there is a \(b_{q+1}\in M'\)
      s.t. \(f\cup\{(a_{q+1},b_{q+1})\}\in S_{p-1}(M,M')\) (by induction) , AND ...
    * For any \(a_{q+1}\in M\), there is \(g\in S_{p-1}(M,M')\) s.t. \(g\supseteq f\) and \(a_{q+1}\in\dom(g)\),
      AND ....
    * \(f\in S_p(M,M')\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(M\) is \(p\)-equivalent to \(M'\), then \(\EF_p(M,M')\) is a win for the Duplicator.
    Otherwise it is a win for the Spoiler
    #+END_theorem

    #+BEGIN_proof
    We need to prove \(\emptyset\in\EF_p(M,M')\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Every \((p+1)\)-isomorphism is a \(p\)-isomorphism
    #+END_theorem

    #+BEGIN_proof
    By induction on \(p\).

    \(p=0\): every 1-isomorphism is a 0-isomorphism.
    #+END_proof

    So \(S_0(M,M')\supseteq S_1(M,M')\supseteq S_2(M,M')\supseteq\cdots\) In terms of the Ehfrenfeucht-Fraïssé game

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Suppose \(s\in S_p(M,M')\) and \(t\in S_p(M',M'')\) and \(\dom(t)=\im(s)\). Then \(u:=t\circ s\in S_p(M,M'')\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(M\sim_pM'\) and \(M'\sim_pM''\), then \(M\sim_pM''\)
    #+END_corollary

    #+BEGIN_proof
    \(\emptyset\in S_p(M,M')\) and \(\emptyset\in S_p(M',M'')\), hence \(\emptyset\in S_p(M,M'')\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Suppose \(s\in S_p(M,M')\). Then \(s^{-1}\in S_p(M,M')\)
    #+END_theorem

    #+BEGIN_proof
    Since \(s\in S_p(M,M')\), \(s\) is a local isomorphism from \(M\) onto \(M'\). As \(s\) is an
    bijection, \(s^{-1}\) is also a bijection.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(M\sim_pM'\), then \(M'\sim_pM\)
    #+END_corollary

    \(\sim_p\) is an equivalence relation

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(K\) be a Karpian family for \((M,R)\) and \((M',R')\). Then \(K\subseteq S_p(M,M')\) for
    all \(p\). (also for all \alpha)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(M,M'\) are DLOs, then \(S_0(M,M')=S_p(M,M')\) for all \(p\). \(M\sim_\omega M'\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(A\cong B\)\(\Longrightarrow\)\(A\sim_\infty B\Longrightarrow A\sim_\omega B\Rightarrow A\sim_pB\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\sim_p\) and \(\sim_\omega\) are equivalence relations
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Suppose \((\Q,\le)\sim_\omega(C,R)\). Then \((C,R)\) is a DLO
    #+END_theorem

    #+BEGIN_proof
    Suppose \((C,R)\) is not a DLO and break into cases
    * \(R\) is not reflexive. As \(\emptyset\in S_1(\Q,C)\). Spoiler chooses \(b_1\in C\) s.t. \((b_1,b_1)\notin R\). Then duplicator must
      choose \(a_1\in\Q\) s.t. \(a_1\not\le a_1\), impossible
    * \(R\) is antisymmetric. \(\emptyset\in S_2(\Q,C)\). Let \(b_1,b_2\in C\) s.t. \(b_1Rb_2\) and \(b_2Rb_1\). We want
      to show that \(b_1=b_2\). Since \(\emptyset\in S_2(\Q,C)\), we have a local
      isomorphism \(\{(a_1,b_1),(a_2,b_2)\}\in S_0(\Q,C)\). Hence \(a_1\le a_2\) and \(a_2\le a_1\). As so \(a_1=a_2\).
      As this is a bijection, \(b_1=b_2\).
    * \(R\) is transitive. \(\emptyset\in S_3(\Q,C)\). Let \(b_1,b_2,b_3\in C\) s.t. \(b_1Rb_2\) and \(b_2Rb_3\).  因此存
      在\(a_1,a_2,a_3\in\Q\) s.t. \(\{(a_1,b_1),(a_2,b_2),(a_3,b_3)\}\in S_0(\Q,C)\).
    * \(R\) is total. 依靠、\(S_2(\Q,C)\).
    * \((C,R)\) has no maximum. \(\forall b_1\in C\)
    * \((C,R)\) has no minimum
    * \((C,R)\) is dense. For any \(b_1\neq b_2\in C\) s.t. \(b_1Rb_2\). \(S_3(\Q,C)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    The class of DLOs is the \(\sim_\omega\)-equivalence class of \((\Q,\le)\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A linear order \((C,\le)\) is *discrete* without endpoints if \(C\neq\emptyset\) and
    \begin{align*}
    &\forall a\exists b:a\lhd b\\
    &\forall b\exists a:a\lhd b
    \end{align*}
    where \(a\lhd b\) means \(a<b\)  and not \(\exists c:a<c<b\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \((\Z,\le)\). So is \((C,\le)\), where
    \begin{align*}
    C=&\{\dots,-3,-2,-1\}\cup\\
    &\{-1/2,-1/3,-1/4,-1/5,\dots\}\cup\\
    &\{\dots,1/5,1/4,1/3,1/2\}\cup\\
    &\{1,2,3,\dots\}
    \end{align*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((C,<)\) be discrete. If \(a\le b\in C\), then \(d(a,b)\) is the size
    of \([a,b)=\{x\in C:a\le x<b\}\) or \(\infty\) if infinite. If \(a>b\), then \(d(a,b)=d(b,a)\) (definition)
    #+END_definition

    \(d(a,b)=0\Leftrightarrow a=b\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \((C,<)\) and \((C',<)\) be discrete linear orders without endpoints. Suppose \(a_1<\dots<a_n\)
    in \(C\) and \(b_1<\dots<b_n\) in \(C'\). Let \(f\) be the local isomorphism \(f(a_i)=b_i\). Suppose
    that for every \(1\le i<n\), we have
    \begin{equation*}
    d(a_i,a_{i+1})=d(b_i,b_{i+1})\text{ or }d(a_i,a_{i+1})\ge 2^p\le d(b_i,b_{i+1})
    \end{equation*}
    Then \(f\) is a \(p\)-isomorphism
    #+END_lemma

    IDEA: a 0-isomorphism needs to respect the order. A 1-isomorphism needs to respect the order
    plus the relation \(d(x,y)=1\) (to make sure we can find the point). A 2-isomorphism needs to
    respect the order plus the
    relation \(d(x,y)=i\) for \(i=1,2,3\). A 3-isomorphism needs to respect the order plus the
    relations \(d(x,y)=i\) for \(i=1,2,3,\dots,7\)

    this is like binary search algorithm:D

    #+BEGIN_proof
    - \(a_i<a<a_{i+1}\)
      * if \(d(a_i,a_{i+1}=d(b_i,b_{i+1}))\)

        which means they are finite
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \((C,\le)\) and \((C',\le')\) be discrete linear orders without points. Then \(\emptyset\)is
    a \(p\)-equivalence from \((C,\le)\) to \((C',\le)\) for all \(p\). Therefore \((C,\le)\sim\omega(C',\le)\).
    #+END_theorem

    #+BEGIN_remark
    If \((\Z,\le)\sim_\omega(C,R)\), then \((C,R)\) is a dense linear order
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((M,R)\), \((M',R')\) be binary relations.. The *infinite Ehfrenfeucht-Fraïssé game*,
    denoted \(\EF_\infty(M,M')\) is played as follows
    * There are two players, the Duplicator and Spoiler
    * There are infinitely many rounds (indexed by \omega)
    * In the \(i\)th round, the Spoiler chooses either an \(a_i\in M\) or a \(b_i\in M'\)
    * The Duplicator responds with a \(b_i\in M'\) or an \(a_i\in M\) respectively
    * if \(\{(a_1,b_1),\dots,(a_n,b_n)\}\) is not a local isomorphism, then the Spoiler immediately wins
    * The Duplicator wins if the Spoiler has not won by the end of the game
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    TFAE
    1. \(R\sim_\infty R'\), i.e., there is a non-empty Karpian family \(K\)
    2. Duplicator has a winning strategy for \(\EF_\infty(M,M')\)
    3. Spoiler does not have a winning strategy for \(\EF_\infty(M,M')\)
    #+END_theorem

    #+BEGIN_proof
    \(1\to 2\). Karpian family is the winning strategy
    #+END_proof




* Connections to Back-and-Forth Technique
    #+ATTR_LATEX: :options [Fraïssé’s Theorem]
    #+BEGIN_theorem
    Let \((M,R)\) and \((N,S)\) be \(m\)-ary relations, let \(\bara\in M^n\) and \(\barb\in N^n\).
    Then \(\bara\) and \(\barb\) are \(p\)-equivalent iff
    \begin{equation*}
    (M,R)\vDash f(\bara)\Longleftrightarrow(N,S)\vDash f(\barb)
    \end{equation*}
    for any formula \(f(\barx)\) with quantifier rank at most \(p\)
    #+END_theorem

    #+BEGIN_proof
    \(\Rightarrow\). Induction on \(p\). If \(\bara\sim_0\barb\), then by definition, they satisfy the same
    atomic formulas. Therefore they satisfy the same quantifier-free formulas.

    Suppose that \(\bara\sim_{p+1}\barb\). The formula \(f:=(\exists y)g(\barx,y)\) has quantifier rank at
    most \(p+1\). So \(g(\barx,y)\) is a formula of quantifier rank at
    most \(p\). \((M,R)\vDash f(\bara)\) iff there is a \(c\in M\) s.t. \((M,R)\vDash g(\bara,c)\). Then there
    is a \(d\in N\) s.t. \(\bara c\sim_p\barb d\). By IH, \((N,S)\vDash g(\barb,d)\) and
    thus \((N,S)\vDash(\exists y)g(\barb,y)\). Another direction is similar

    #+END_proof

    To prove the converse we need the following lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If the arity \(m\) of a relation, and the integers \(n\) and \(p\) are fixed, there is only
    finite number \(C(n,p)\) of \(p\)-equivalence classes of \(n\)-tuples
    #+END_lemma

    \((M,R_1,\bara_1),\dots,(M,R_n,\bara_n)\). For any \((M,R)\) and \(\bara\in M\), \(\exists 1\le i\le n\) s.t. \(\bara\sim_p\bara_i\)

    #+BEGIN_proof
    Induction on \(p\). If \(p=0\), then consider a set of symbols \(X=\{x_1,\dots,x_n\}\). There are at
    most finitely many \(m\)-ary relations defined on \(X\). Also there are at most finitely many
    ways to interpret the relation "=" on \(X\). Let \((M,R)\) and \((N,S)\) be \(m\)-ary
    relations, \(\bara\in M^n\) and \(\barb\in N^n\). Let \(A =\{a_1,\dots,a_n\}\) and \(B =\{b_1,\dots,b_n\}\).
    Let \(R_A =R\cap A^m\) and \(S_B =S\cap B^m\). If \(p=0\), \(\bara\sim_0\barb\) iff \(R_A\) is isomorphic
    to \(R_B\) via \(a_i\mapsto b_i\), \(i=1,\dots,n\). So there are at most finitely many 0-equivalence classes
    of \(n\)-tuples

    By IH, there exists relations \(\{(M_k,R_k)\mid k\le C(n+1,p)\}\)
    and \(\{\bard_k\in M_k^{n+1}\mid k\le C(n+1,p)\}\) s.t. each \(n+1\)-tuple is \(p\)-equivalent to
    some \(\bard_k\). Now consider an arbitrary relation \((M,R)\) and an \(n\)-tuple \(\bara\), we
    define \([\bara]=\{k\mid\exists c\in M(\bara c\sim_p\bard_k)\}\). For any relation \((N,S)\)
    and \(\barb\in N^n\), \(\bara\sim_{p+1}\barb\Leftrightarrow[\bara]=[\barb]\)
    #+END_proof

    #+ATTR_LATEX: :options [Proof (continued)]
    #+BEGIN_proof
    We now show that if \(\bara\) and \(\barb\) satisfy the same formulas of QR at most \(p\),
    then \(\bara\sim_p\barb\).

    Claim: For each \(p\)-equivalence class \(C\), there is a formula \(f_C\) of QR \(p\) s.t. the
    tuples in \(C\) are exactly those satisfy \(f_C\). \((M,R,\bara)\in C\Leftrightarrow R\vDash f_C(\bara)\).

    Induction on \(p\). If \(p=0\), given an \(n\)-tuple \(\bara\), there are finitely many atomic
    formulas with variables \(x_1,\dots,x_n\). \(n^2+n^m\). \(\{x_i=x_j\mid i,j\le n\}\)
    and \(\{r(x_{i_1},\dots,x_{i_m})\mid i_j\le n\}\).

    Let \(f_C\) be the conjunction of those satisfied
    by \(\bara\) and negation of the others. Then \(f_C\) characterizes the 0-equivalence class
    of \(\bara\). (characterizes \(\restr{R}{\{a_1,\dots,a_n\}}\))

    Now prove \(p+1\). Let \(\bara\) be an \(n\)-tuple of \((M,R)\).
    Let \(f_1(\barx,y),\dots,f_k(\barx,y)\) characterize all the \(p\)-equivalence classes \(C_1,\dots,C_k\)
    on \(n+1\)-tuples. Let \(\la\bara\ra=\{i\le k\mid(M,R)\vDash(\exists y)f_i(\bara,y)\}\). \(\la\bara\ra=[\bara]\)

    Let
    \(f_C(\barx)=\bigwedge_{i\in\la\bara\ra}(\exists y)f_i(\barx,y)\wedge\bigwedge_{i\notin\la\bara\ra}\neg(\exists y)f_i(\barx,y)\).
    \(\barb\sim_{p+1}\bara\) iff \([\bara]=[\barb]\) iff \(\la\bara\ra=\la\barb\ra\) iff \(f_C(\barb)\) holds
    #+END_proof

    bracket system
* Compactness
** Ultraproducts
    If \(I\) is a nonempty set, a *filter* is a set \(F\) of subsets of \(I\) s.t.
    * \(I\in F\), \(\emptyset\in F\)
    * if \(X,Y\in F\), then \(X\cap Y\in F\)
    * if \(X\in F\) and \(X\subset Y\), then \(Y\in F\)


    A *filter prebase* \(B\) is a set of subsets of \(I\) contained in a filter; this means that the
    intersection of a finite number of elements of \(B\) is never empty. The filter \(F_B\)
    consisting of subsets of \(I\) containing a finite intersection of elements of \(B\) is the
    smallest filter containing \(B\); we call it the filter *generated* by \(B\). If, in addition, the
    intersection of two elements of \(B\) is always in \(B\), we call \(B\) a *filter base*

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(J\) be a set and \(I\) the set of finite subsets of \(J\); for every \(i\in I\),
    let \(I_i=\{j:j\in I,j\supset i\}\), and let \(B\) be the set of all the \(I_i\).
    Then \(I_i\cap I_j=I_{i\cup J}\); \(B\) is closed under finite intersections and does contain \(\emptyset\); It
    is therefore a filter base.
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    A filter \(F\) of subsets of \(I\) is an ultrafilter iff for every subset \(A\) of \(I\),
    either \(A\) or its complement \(I-A\) is in \(F\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(U\) be an ultrafilter of subsets of \(I\). If \(I\) is covered by finitely many
    subsets \(A_1,\dots,A_n\), then one of the \(A_i\) is in \(U\); moreover, if the \(A_i\) are pairwise
    disjoint, exactly one of the \(A_i\) is in \(U\)
    #+END_theorem

    [[https://u.cs.biu.ac.il/~tsaban/RT/Book/Chapter2.pdf][Ultrafilter and Compactness]]

    A topological space X is compact if and only if every ultrafilter in \(X\) is convergent
** Applications of Compactness
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(M\) and \(N\) are elementarily equivalent structures, then \(M\) can be embedded into an
    ultraproduct of \(N\)
    #+END_lemma

    #+BEGIN_proof
    Let \(I\) be the set of injections from finite subset of \(M\) to \(N\). If \(f(\bara)\) is a
    formula with parameters \(\bara\) in \(M\), \(M\vDash f(\bara)\), let \(I_{f(\bara)}\) denote the set
    of such injections \(s\) whose universe contains \(\bara\) and s.t. \(N\vDash f(s(\bara))\). The
    set \(I_{f(\bara)}\) is never empty, as \(M\vDash f(\bara)\), so \(M\vDash\exists\barx(f(\barx)\wedge D(\barx))\),
    where \(D\) is the conjunction of the formulas \(x_i=x_j\) if \(a_i=a_j\), and \(x_i\neq x_j\)
    otherwise, and \(N\) also satisfies this formula. On the other
    hand, \(I_{f(\bara)}\cap I_{g(\barb)}=I_{f(\bara)\wedge g(\barb)}\), so the \(I_{f(\bara)}\) form a
    filter base, which can be extended to an ultrafilter

    Define a function \(S\) from \(M\) to \(N^U\) as follows: If \(a\in M\), the \(i\)th coordinate
    of \(Sa\) is \(ia\) if \(i\) is defined at \(a\), and any element of \(N\) otherwise (We are
    excluding the case of empty universes, which is trivial.) Note
    that \(\{i:i\text{ is defined at }a\}=I_{a=a}\), and that changing the coordinates outside
    of \(I_{a=a}\) will not change \(Sa\) modulo \(U\), so \(S\) is well-defined.
    #+LATEX: \wu{
    If \(a=b\), then \(S(a)=S(b)\) iff \(\{i:N\vDash i(a)=i(b)\}=I_{a=b}\in U\). If \(a\neq b\) ,
    then \(I_{a\neq b}\in U\), hence \(S\) is an injection.
    #+LATEX: }

    \(N^U\vDash\phi(S(\bara))\) iff \(\{i:N\vDash\phi(i(\bara))\}\in U\). If \(M\vDash\phi(\bara)\), then \(\{i:N\vDash\phi(i(\bara))\}=I_{\phi(\bara)}\).
    #+END_proof

* Quantifier elimination
    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If two structures \(M\) and \(N\) are elementarily equivalent and \omega-saturated, they
    are \(\infty\)-equivalent: More precisely, two tuples of the same type (over \(\emptyset\)), one in \(M\) and
    the other in \(N\), can be matched up by an infinite back-and-forth construction
    #+END_theorem

    If \(M\) is \omega-saturated, then for every \(\bara\) of \(M\) and every \(p\)
    of \(S_n(\bara)\), \(p\) is realised in \(M\)

    An \omega-saturated model therefore realises all absolute \(n\)-types for all \(n\). This condition,
    however, is not sufficient for a model to be \omega-saturated. Example: let \(T\) be the theory of
    discrete order without endpoints; \(M\) is \omega-saturated iff it has the form \(\Z\times\C\) where \(\C\)
    is a dense chain without endpoints, while it realizes all pure \(n\)-types iff it has the
    form \(\Z\times\C\) where \(\C\) is an infinite chain
    <<Problem1>>

    If \(T\) is a complete theory and \(M\) is an \omega-saturated model of \(T\), then every denumerable
    model \(N\) of \(T\) can be elementarily embedded in \(M\). In fact, if \(N=\{a_0,a_1,\dots,a_n,\dots\}\),
    we can successively realize, in \(M\), the type of \(a_0\), then the type of \(a_1\)
    over \(a_0\), \dots, the type of \(a_{n+1}\) over \((a_0,\dots,a_n)\), \(\dots\)

    As two denumerable, elementarily equivalent, \omega-saturated structures are isomorphic. Under what
    conditions does a complete theory \(T\) have a (unique) \omega-saturated denumerable model? That
    happens iff for every \(n\), \(S_n(T)\) is (finite or) denumerable. (Here, we do not assume that
    \(T\) is denumerable)

    In fact, this condition further implies that for every \(\bara\in M\), \(S_1(\bara)\) is
    denumerable (because to say that \(b\) and \(c\) have the same type over \(\bara\) is to say
    that \(\bara b\) and \(\bara c\) have the same type over \(\emptyset\)) . It is clearly necessary,
    because a denumerable model can realize only denumerable many \(n\)-types. To see that it is
    sufficient: Let \(A_1\) be a denumerable subset of \(M\) that realizes all 1-types over \(\emptyset\);
    then let \(A_2\) be a denumerable subset of \(M\) that realises all 1-types over finite subsets
    of \(A_1\); etc. Let \(A=\bigcup A_n\). \(A\) satisfies Tarski's test so it is an elementary submodel
    of \(M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:thm5.3
    Let \(T\) be a theory, not necessarily complete, and let \(F\) be a nonempty set of
    formulas \(f(\barx)\) in the language \(L\) of \(T\), having for free variables
    only \(\barx=(x_1,\dots,x_n)\), s.t. two \(n\)-tuples from models of \(T\) have the same type
    whenever they satisfy the same formulas of \(F\). Then for every formula \(g(\barx)\) of \(L\)
    in these variables, there is some \(f(\barx)\) that is a Boolean combination of elements
    of \(F\) s.t. \(T\vDash\forall\barx(f(\barx)\leftrightarrow g(\barx))\)
    #+END_theorem

    #+BEGIN_proof
    Consider the clopen set \([g(\barx)]\) in \(S_n(T)\). If \([g]=\emptyset\), then \([g]=[f\wedge\neg f]\), and
    if \([g]=S_n(T)\), then \([g]=[f\vee\neg f]\), where \(f\) is an arbitrary element of \(F\), which is
    nonempty. Consider \(p\in[g]\) and \(q\notin[g]\). There is \(f_{p,q}\in F\) s.t. \(p\vDash f_{p,q}(\barx)\)
    and \(q\vDash\neg f_{p,q}(\barx)\)
    #+LATEX: \wu{
    If \(p\) and \(q\) are different, then they are realised by two tuples satisfying different
    formulas of \(F\). Here we consider the model amalgamated by the model realising \(p\) and the
    model realising \(q\). Thus such \(f_{p,q}\) exists
    #+LATEX: }

    Keeping \(p\) fixed and varying \(q\), all the \([f_{p,q}]\) and \(\neg[g]\) form a family of
    closed sets whose intersection is empty;
    #+LATEX: \wu{
    \(\bigcup[\neg f_{p,q}]\supset[\neg g]\).
    #+LATEX: }
    by compactness, one of its finite subfamilies must have
    empty intersection, meaning that for some \(h_p=f_{p,q}\wedge\dots\wedge f_{p,q_n}\in[h_p]\subset[g]\)

    Now when we vary \(p\), \([g]\) is a compact set that is covered by the open sets \([h_p]\), so
    a finite number of them are enough to cover it; the disjunction of these \(h_p\), module \(T\),
    is equivalent to \(g\)
    #+END_proof

    Note that if we want that every sentence be equivalent module \(T\) to a quantifier-free
    sentence; that requires, naturally, that the set of sentences without quantifiers be nonempty,
    meaning that the language *involves* constant symbols, or else nullary relation symbols.

    A theory \(T\) is *model complete* if it has the following property: If \(M,N\vDash T\) and
    if \(N\subseteq M\), then \(N\preceq M\)

    Two theories \(T_1\) and \(T_2\) in the same language \(L\), are *companions* if every model of one
    can be embedded into a model of the other

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Two theories are companions of each other iff they have the same universal consequences (a
    sentence being called *universal* if it is of the form \(\forall x_1,\dots,x_n\;f(x_1,\dots,x_n)\) with \(f\)
    quantifier-free)
    #+END_theorem

    #+BEGIN_proof
    A universal sentence \(f\) that is true in a structure is always true in its substructure;
    if \(T_1\vDash f\) and if there is a model of \(T_2\) that doesn't satisfy \(f\), it cannot be extended
    to a model of \(T_1\)

    Conversely, suppose that \(T_1\) and \(T_2\) have the same universal consequences, and
    let \(M_1\vDash T_1\). We name each element of \(M_1\) by a new constant, and let \(D(M_1)\) be the set
    of all /quantifier-free/ sentences in the new language that are true in \(M_1\).
    If \(D(M_1)\vDash f(a_1,\dots,a_n)\), then \(M\vDash\exists\barx\;f(\barx)\), so \(\forall\barx\neg f(\barx)\) is not a
    consequence of \(T_1\), and therefore not of \(T_2\). There is therefore some model \(M_2\vDash T_2\)
    with \(\barb\in M_2\) s.t. \(M_2\vDash f(\barb)\). By compactness, this means that \(D(M_1)\cup T_2\) is
    consistent, in other words, that \(M_1\) embeds into a model of \(T_2\)
    #+END_proof

    A theory \(T\) therefore has a minimal companion, which we shall denote by \(T_\forall\), which is
    axiomatized by the universal consequences of \(T\).

    A theory \(T'\) is a *model companion* of \(T\) if it is a companion of \(T\) that is model complete

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    A theory has at most one model companion
    #+END_theorem

    #+BEGIN_proof
    Let \(T_1\) and \(T_2\) be model companions of \(T\). Therefore \(T_1\) and \(T_2\) are companions.
    Let \(M_1\vDash T_1\); it embeds into a \(N_1\vDash T_2\), which embeds into a \(M_2\vDash T_1\). We get a chain
    \(M_1\subset N_1\subset M_2\subset N_2\subset\cdots\subset M_n\subset N_n\subset\cdots\), whose limit we call \(P\). As \(T_1\) is model complete, the
    chain of \(M_n\) is elementary, and \(P\) is an elementary extension of \(M_1\);
    similarly \(N_1\preceq P\). Therefore \(M_1\)is also a model of \(T_2\); by symmetry \(T_1\) and \(T_2\)
    have the same models, meaning \(T_1=T_2\)
    #+END_proof

    We say that \(T'\) is a *model completion* of \(T\) if it is a model companion of \(T\) and also
    the following condition is satisfied: if \(M\vDash T\), embeds into a model \(M_1\vDash T'\) and into a
    model \(M_2\vDash T'\), then a tuple \(\bara\) of \(M\) satisfies the same formulas in \(M_1\) and in \(M_2\)

    Naturally a model complete theory is its own model completion, and it is clear that a theory
    that admits quantifier elimination is the model completion of every one of its companions. A
    theory is the model completion of every one of its companions iff it is the model completion of
    the weakest of them all, \(T_\forall\)

    In the particular case where for every \(n>0\) we can take for \(F\) the quantifier-free
    formulas, we say that the theory \(T\) *eliminates quantifiers* or *admits quantifier elimination*.

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    The model completion of a universal theory (i.e., one that is axiomatized by universal
    sentences) admits quantifier elimination
    #+END_theorem

    #+BEGIN_proof
    Let \(\bara\) and \(\barb\) satisfying the same quantifier-free formulas, be in two
    models \(M_1\) and \(M_2\) of this theory \(T'\), and let \(N_1\subseteq M_1\), \(N_2\subseteq M_2\) generated
    by \(\bara\) and \(\barb\) respectively.
    #+END_proof



    \(\DLO\) has quantifier elimination

    Facts. In \(\DLO\), any 0-isomorphism is an \omega-isomorphism.

    Suppose \(\qftp(\bara)=\qftp(\barb)\), want \(\tp(\bara)=\tp(\barb)\)

    \(\exists f:\la\bara\ra_{\fM}\to\la\barb\ra_{\fN}\) an isomorphism by Theorem 6, \(f\in S_0(\fM,\fN)=S_\omega(\fM,\fN)\). Then by Fraïssé's
    theorem, \(\tp(\bara)=\tp(\barb)\)

    \(M\equiv N\Leftrightarrow\la\emptyset\ra_M\cong\la\emptyset\ra_N\Leftrightarrow char(M)=char(N)\)

    same characteristic determine same minimal subring

    \(M^n/\Aut(M/A)\cong S_n(A)\)

    Algebraically closed fields are axiomatized by the field axioms plus the axiom schema
    \begin{equation*}
    \forall y_0,\dots,y_n\left( y_n\neq 0\to\exists x\sum_{i=0}^ny_ix^i=0 \right)
    \end{equation*}
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(K\vDash\ACF\), then \(K\) is infinite
    #+END_lemma

    #+BEGIN_proof
    If \(K=\{a_1,\dots,a_n\}\), then \(P(x)=1+\prod_{i=1}^n(x-a_i)\) has no root in \(K\)
    #+END_proof

    If \(M\vDash\ACF\) and \(K\) is a subfield, then \(K^{\alg}\) denotes the set of \(a\in M\) algebraic
    over \(K\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:24
    Given uncountable \(M,N\vDash\ACF\), suppose \(\bara\in M^n\) and \(\barb\in N^n\)
    and \(\qftp^M(\bara)=\qftp^N(\barb)\). Suppose \(\alpha\in M\). Then there is \(\beta\in N\) s.t. \(\qftp^M(\bara,\alpha)=\qftp^N(\barb,\beta)\)
    #+END_lemma

    #+BEGIN_proof
    Let \(A=\la\bara\ra_M\) and \(B=\la\barb\ra_N\). There is an isomorphism \(f:A\to B\) and we can
    extend \(f\) to an isomorphism \(f:\Frac(A)\to\Frac(B)\) (Note that \(A\) and \(B\) are subrings
    since they are only closed under multiplication and addition). Moving \(N\) by an isomorphism we may
    assume \(\Frac(A)=\Frac(B)\) and \(f=id_{\Frac(A)}\). (In particular, \(\bara=\barb\)).
    let \(K=\Frac(A)\). Let \(K=\Frac(A)\)

    *Claim*. There is \(\beta\in N\) with \(I(\alpha)=I(\beta)\) in \(K\)

    Suppose \alpha is algebraic over \(K\) with minimal polynomial \(P(x)\). Take \(\beta\in N\)
    with \(P(\beta)=0\). Let \(Q(x)\) be the minimal polynomial over \beta over \(K\).
    Then \(P(x)\in Q(x)\cdot K[x]\). But \(P(x)\) is irreducible, so \(P(x)=Q(x)\). Then \(I(\alpha)=I(\beta)\)

    suppose \alpha is transcendental, since there are only countable many solutions, there is
    transcendental \(\beta\in N\). Then \(I(\alpha)=I(\beta)=0\)

    Take such \beta, let \(I=I(\alpha)=I(\beta)\)
    * If \(P(x)\in K[x]\), \(P(\alpha)=0\Leftrightarrow P(x)\in I\Leftrightarrow P(\beta)=0\)
    * If \(P(x),Q(x)\in K[x]\), then \(P(\alpha)=Q(\alpha)\Leftrightarrow(P-Q)(\alpha)=0\Leftrightarrow(P-Q)(\beta)=0\Leftrightarrow P(\beta)=Q(\beta)\)
    * Hence if \(\varphi(x)\) is an atomic \(\call(K)\)-formula, then \(M\vDash\varphi(\alpha)\Leftrightarrow N\vDash\varphi(\beta)\)
    * so is quantifier-free \(\varphi(x)\in\call(K)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Lemma ref:24 holds if we replace "uncountable" with "\omega-saturated"
    #+END_lemma

    #+BEGIN_proof
    Take uncountable \(M'\succeq M\) and \(N'\succeq N\), this is possible since models of \(\ACF\) are
    infinite. By Lemma ref:24, there is \(\beta_0\in N'\) s.t. \(\qftp(\bara,\alpha)=\qftp(\barb,\beta_0)\). By
    \omega-saturation, we can find \(\beta\in N\) s.t. \(\tp(\beta/\barb)=\tp(\beta_0/\barb)\). Then \(\tp(\barb,\beta)=\tp(\barb,\beta_0)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \(\ACF\) has quantifier elimination
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Suppose \(M,N\vDash\ACF\), then \(M\equiv N\Leftrightarrow\tchar(M)=\tchar(N)\)
    #+END_theorem

    #+BEGIN_proof
    TFAE
    * \(M\equiv N\)
    * for every sentence \varphi, \(M\vDash\varphi\Leftrightarrow N\vDash\varphi\)
    * for every quantifier-free sentence \varphi, \(M\vDash\varphi\Leftrightarrow N\vDash\varphi\)
    * for every atomic sentence \varphi, \(M\vDash\varphi\Leftrightarrow N\vDash\varphi\)
    * for any terms \(t_1,t_2\), \(M\vDash t_1=t_2\Leftrightarrow N\vDash t_1=t_2\)
    * for any term \(t\), \(M\vDash t=0\Leftrightarrow N\vDash t=0\)
    * for any \(n\in\Z\), \(M\vDash n=0\Leftrightarrow N\vDash n=0\)
    * \(\{n\in\Z:n^M=0\}=\{n\in\Z:n^N=0\}\)
    * \(\tchar(M)=\tchar(N)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\ACF_p\) is complete for each \(p\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\C\) is completely axiomatized by \(\ACF_0\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(M\) be algebraically closed. Let \(K\) be a field. Let \(\varphi(x)\) be an \(\call(K)\)-formula in
    one variable. Let \(D=\varphi(M)\). Then there is a finite subset \(S\subseteq K^{\alg}\) s.t. \(D=S\)
    or \(D=M\setminus S\), that is, either \(D\subseteq K^{\alg}\) or \(M\setminus K\subseteq K^{\alg}\)
    #+END_lemma

    #+BEGIN_proof
    By Q.E., we may assume \varphi is quantifier-free. Then \varphi is a boolean combination of atomic formulas

    Let \(\calf=\{S:S\subseteq_fK^{\alg}\}\cup\{M\setminus S:S\subseteq_fK^{\alg}\}\). Note that \(\calf\) is closed under boolean
    combinations. So we may assume \varphi is an atomic formula

    Then \(\varphi(x)\) is \((P(x)=0)\) for some \(P(x)\in K[x]\). If \(P(x)\equiv 0\), then \(\varphi(M)=M\in\calf\).
    Otherwise \(\varphi(M)\subseteq_fK^{\alg}\), so \(\varphi(M)\in\calf\)
    #+End_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose \(M\preceq N\vDash\ACF\) and \(K\) is a subfield of \(M\). Suppose \(c\in N\) is algebraic
    over \(K\). Then \(c\in M\)
    #+END_lemma

    #+BEGIN_proof
    Let \(P(x)\) be the minimal polynomial of \(c\) over \(K\). Let \(b_1,\dots,b_n\) be the roots
    of \(P(x)\) in \(M\). Then
    \begin{equation*}
    M\vDash\forall x\left( P(x)=0\to\bigvee_{i=1}^nx=b_i \right)
    \end{equation*}
    so the same holds in \(N\). Then \(P(c)=0\Rightarrow c\in\{b_1,\dots,b_n\}\subseteq M\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(M\vDash\ACF\) and \(K\) is a subfield, then \(K^{\alg}\) is a subfield of \(M\) and \((K^{\alg})^{\alg}=K^{\alg}\)
    #+END_theorem

    #+BEGIN_proof
    Suppose \(a,b\in K^{\alg}\). We claim \(a+b\in K^{\alg}\). Let \(P(x)\) and \(Q(y)\) be the minimal
    polynomials of \(a,b\) over \(K\). Let \(\varphi(z)\) be the \(\call(K)\)-formula
    \begin{equation*}
    \exists x,y(P(x)=0\wedge Q(y)=0\wedge x+y=z)
    \end{equation*}
    Then \(M\vDash\varphi(a+b)\) and \(\varphi(M)=\{x+y:P(x)=0=Q(y)\}\) is finite. Thus \(a+b\in\varphi(M)\subseteq K^{\alg}\)

    A similar argument shows \(K^{\alg}\) is closed under the field operations, so \(K^{\alg}\) is a
    subfield of \(M\)


    #+END_proof


* Appendices                  :ignore:
  #+LATEX: \appendix
** Metric Spaces
    \(\R_{\ge 0}\) denotes \([0,+\infty]=\{x\in\R:x\ge 0\}\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *metric* on a set \(M\) is a function \(d:M\times M\to\R_{\ge 0}\) satisfying the following properties
    1. \(d(x,y)=0\Leftrightarrow x=y\)
    2. \(d(x,y)=d(y,x)\)
    3. \(d(x,z)\le d(x,y)+d(y,z)\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(M=\R^2\), \(d(x,y)=\)(the distance from \(x\) to \(y\))
    \begin{equation*}
      d(x_1,x_2;y_1,y_2)=\sqrt{(x_1-y_1)^2+(x_2-y_2)^2}
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The *Manhattan metric* on \(\R^2\) is given by
    \begin{equation*}
      d(x_1,x_2;y_1,y_2)=\abs{x_1-y_1}+\abs{x_2-y_2}
    \end{equation*}

    measure distances in a city grid
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(M\) be the set of strings. The *edit distance* from \(x\) to \(y\) is the minimum number of
    intersections, deletions, and substitutions to go from \(x\) to \(y\)
    \begin{gather*}
      d(drip,rope)=3\\
      drip\mapsto drop\mapsto rop\mapsto rope
    \end{gather*}
    Edit distance is a metric on \(M\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *metric space* is a pair \((M,d)\) where \(M\) is a set and \(d\) is a metric space
    #+END_definition

    * \((\R^n,d_{Euclidean})\) where \(d_{Euclidean}\) is the usual Euclidean distance
    * \((\R^2,d_{Manhattan})\) where \(d_{Manhattan}\) is the Manhattan distance


    Often we abbreviate \((M,d)\) as \(M\), when \(d\) is clear

    Fix a metric space \((M,d)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    If \(p\in M\) and \(\epsilon>0\), then
    \begin{align*}
    &B_\epsilon(p)=\{x\in M:d(x,p)<\epsilon\}\\
    &\barB_\epsilon(p)=\{x\in M:d(x,p)\le\epsilon\}\\
    \end{align*}
    \(B_\epsilon(p)\) and \(\barB_\epsilon(p)\) are called the *open* and *closed* balls of radius \epsilon around \(p\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    In \(\R^2\) with the Euclidean metric, the open ball of radius 2 around \((0,0)\) the open disk
    \begin{equation*}
    \{(x,y)\in\R^2:x^2+y^2<2^2\}
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    In \(\R^2\) with the Manhattan metric, the open ball of radius 1 around \((0,0)\) the open disk
    \begin{equation*}
    \{(x,y)\in\R^2:\abs{x}+\abs{y}\le 1\}
    \end{equation*}
    #+END_examplle

    Suppose \(p\in M\) and \(X\subseteq M\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(p\) is an *interior point* of \(X\) if \(X\) contains an open ball of positive radius around \(p\)
    #+END_definition

    In particular, \(p\) must be an element of \(X\)


    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \(X=[-1,1]\times[-1,1]\), then \((0,0)\) is an interior point of \(X\), but \((1,0)\)
    and \((0,2)\) are not
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *interior* \(\tint(X)\) is the set of interior points
    #+END_definition

    Warning: There are metric spaces where the interior of \(\barB_\epsilon(p)\) isn't \(B_\epsilon(p)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq M\) is *open* if \(X=\tint(X)\), i.e., every point of \(X\) is an interior point of \(X\)
    #+END_definition

    #+ATTR_LATEX: :options [in \(\R\)]
    #+BEGIN_examplle
    The set \((-1,2)\) is open. The sets \([-1,2]\) and \([-1,2)\) are not; they have interior \((-1,2)\)
    #+END_examplle

    Fact: the interior \(\tint(X)\) is the unique largest open set contained in \(X\)

    Let \(a_1,a_2,\dots\) be a sequence in a metric space \((M,d)\) and let \(p\) be a point
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    "\(\lim_{i\to\infty}a_i=p\)" if for every \(\epsilon>0\), there is \(n\) s.t.
    \begin{equation*}
    \{a_n,a_{n+1},a_{n+2},\dots\}\subseteq B_\epsilon(p)
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Work in \(\R\) with the usual distance. Let \(a_n=1/n\). Then \(\lim_{n\to\infty}a_n=0\)
    but \(\lim_{n\to\infty}a_n\neq 1\)
    #+END_examplle

    Fact: For any sequence \(a_1,a_2,a_3,\cdots\) in \((M,d)\), there is at most one point \(p\)
    s.t. \(\lim_{i\to\infty}a_i=p\)

    If such a \(p\) exists, it is called the *limit*, and written \(\lim_{i\to\infty}a_i\)

    let \(X\) be a set and \(p\) be a point in a metric space \((M,d)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(p\) is an *accumulation point* of \(X\) if \(p=\lim_{n\to\infty}a_n\) for some sequence \(a_n\) in \(X\)
    #+END_definition

    Equivalently
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(p\) is an accumulation point of \(X\) if for every \(\epsilon>0\), we have \(B_\epsilon(p)\cap X\neq\emptyset\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *closure* of \(X\), written \(\cl(X)\) or \(\barX\), is the set of accumulation points
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq M\) is *closed* if \(X=\cl(X)\)
    #+END_definition


    Fact: The closure \(\cl(X)\) is the unique smallest closed set containing \(X\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Work in \(\R\) with the distance \(d(x,y)=\abs{x-y}\)

    \(\Q\) is neither closed nor open

    \(\R\) is both closed and open, so is \(emptyset\)
    #+END_examplle

    Let \(X^c\) denote the completement \(M\setminus X\)

    Fact: \(X\) is closed iff \(X^c\) is open

    Fact: \(\tint(X)=\cl(X^c)^c\) and \(\cl(X)=\tint(X^c)^c\)

    Let \((M,d)\) and \((M',d)\) be metric spaces. Let \(f:M\to M'\) be a function
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(f\) is *continuous* if
    \begin{equation*}
    \lim_{n\to\infty}a_n=p\Rightarrow\lim_{n\to\infty}f(a_n)=f(p)
    \end{equation*}
    for \(a_1,a_2,a_3,\dots,p\in M\)
    #+END_definition

    idea: \(f\) is continuous iff \(f\) preserves limits

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    Let \(f:\R\to\R\) be given by
    \begin{equation*}
    f(x)=
    \begin{cases}
    1&\text{if }x>0\\
    -1&\text{if }x\le 0
    \end{cases}
    \end{equation*}
    Then \(\lim_{n\to\infty}1/n=0\), but
    \begin{equation*}
    \lim_{n\to\infty}f(1/n)=\lim_{n\to\infty}1=1\neq-1=f(0)
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Fix \(f:(M,d)\to(M',d)\). The following are equivalent
    1. \(f\) is continuous
    2. For every open set \(U\subseteq M'\), the preimage \(f^{-1}(U)\) is open
    3. For every \(p\in M\), for every \(\epsilon>0\), there is \(\delta>0\) s.t. for every \(x\in M\),
       \begin{equation*}
      d(x,p)<\delta\Rightarrow d(f(x),f(p))<\epsilon
       \end{equation*}
    #+END_proposition

    Fact: The functions \(\sin\), \(\cos\), \(\exp\), \(\sqrt[3]{-}\) and polynomials are continuous

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f,g:\R\to\R\) are continuous, then \(f+g,f\cdot g,f-g,f\circ g\) are continuous
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f:\R\to\R\) is continuous and \(f(x)\neq 0\) for all \(x\), then \(1/f(x)\) is continuous.
    If \(f(x)\ge 0\) for all \(x\), then \(\sqrt{f(x)}\) is continuous
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    This function is continuous
    \begin{equation*}
    h(x)=\exp\left( \frac{1}{1+x^2} \right)-\frac{1}{17+\sin(\sqrt[3]{x})}
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A function \(f:M\to M'\) is *Lipschitz continuous* if there is \(c\in\R\) s.t. for any \(x,y\in M\)
    \begin{equation*}
    d(f(x),f(y))\le c\cdot d(x,y)
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options [In \(\R\)]
    #+BEGIN_examplle
    The function \(f(x)=\abs{x}+\abs{x-1}\) is Lipschitz continuous with \(c=2\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(f\) is Lipschitz continuous, then \(f\) is continuous
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The function \(f(x)=x^2\) is continuous but not Lipschitz continuous
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \((M,d)\)be a metric space and \(S\subseteq M\) be a set. Then \((S,d')\) is a metric space,
    where \(d'(x,y)=d(x,y)\) for \(x,y\in S\)
    * \(d'\) is the restriction of \(d\) to \(S\times S\)
    * We say that \((S,d')\) is a *subspace* of \((M,d)\)
    #+END_definition

    Let \((M,d)\), \((M',d)\) be metric spaces, \(S\subseteq M\) and \(f:S\to M'\) be a function

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(f\)  is *continuous* if \(f\) is continuous as a map from the subspace \((S,d')\) to \((M',d)\)
    #+END_definition

    #+ATTR_LATEX: :options [in \(\R\)]
    #+BEGIN_examplle
    Let \(f:(-\infty,0)\cup(0,\infty)\to\R\)  be given by \(f(x)=1/x\). Then \(f\) is continuous
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *isometry* or *isomorphism* from \((M,d)\) to \((M',d')\) is a bijection \(f:M\to M'\) s.t. for
    any \(x,y\in M\)
    \begin{equation*}
    d(x,y)=d'(f(x),f(y))
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options [in \(\R^2\)]
    #+BEGIN_examplle
    The map \((x,y)\mapsto(x+1,y-7)\) is an isometry

    So is the map \((x,y)\mapsto(3/5x+4/5y,-4/5x+3/5y)\)

    These two metric spaces are isometric via the isometry \(x\mapsto(x,0)\)
    * \(\R\) with the usual distance
    * The subspace \(\R\times\{0\}\) inside \(\R^2\) with the usual distance
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The isometries of \(\R^2\) are exactly the rotations, translations, reflections and glide reflections
    #+END_proposition

    Let \(X\) be a non-empty set in a metric space

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *diameter* of \(X\), written \(\diam(X)\), is
    \begin{equation*}
    \sup\{d(p,q):p,q\in X\}
    \end{equation*}
    (Possibly \(\diam(X)=+\infty\))
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    In \(\R^2\) with the usual metric, the diameter of \(B_r(p)\) is \(2r\)
    #+END_examplle

    Work in a metric space \(M\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *Cauchy sequence* is a sequence \(a_1,a_2,a_3,\dots\) s.t.
    \begin{equation*}
    \lim_{n\to\infty}\diam(\{a_n,a_{n+1},a_{n+2},\dots\})=0
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Every sequence which converges to a point in \(M\) is a Cauchy sequence
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(a_1,a_2,a_3,\dots\) be a sequence in a metric space \((M,d)\). The following are equivalent
    * The sequence is a Cauchy sequence
    * There is some metric space \(M'\) s.t. \(M\) is a subspace of \(M'\), and \(\lim_{n\to\infty}a_n\)
      converges in \(M'\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    In \(\R\), every Cauchy sequence converges
    #+END_proposition

    This fails in the subspace \(\Q\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A metric space \((M,d)\) is *complete* if every Cauchy sequence in \(M\) converges (to a point in \(M\))
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\R\) is complete. The subspace \(\Q\) and \((-1,1)\) are not complete
    #+END_examplle

    Let \((M,d)\) be a metric space

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    The *completion* of \(M\) is a new metric space \(\barM\). Objects of \(\barM\) are equivalence
    classes of Cauchy sequences in \(M\). Two Cauchy sequences \((a_i)_{i\in\N}\) and \((b_i)_{i\in\N}\) are
    equivalent if \(\lim_{i\to\infty}d(a_i,b_i)=0\). The distance in \(\barM\) between two Cauchy
    sequences \((a_i)_{i\in\N}\) and \((b_i)_{i\in\N}\) is \(\lim_{i\to\infty}d(a_i,b_i)\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    This is well-defined, and \(\barM\) is complete
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If we identify \(c\in M\)with the constant sequence \(c,c,c,c,\dots\) then \(M\) is a dense subspace
    of \(\barM\). If \(M\) is complete, then \(\barM=M\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\R\) is the completion of \(\Q\) w.r.t. its usual metric
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The *\(p\)-adic norm* on \(\Q\) is defined by
    \begin{gather*}
    \abs{0}_p=0\\
    \abs{p^ka/b}_p=p^{-k}\text{ if }a,b\text{ are integers not divisible by }p
    \end{gather*}
    For example, \(\abs{1.3}_5=\abs{5^{-1}\cdot 13/2}_5=5^1\)

    The *\(p\)-adic metric* on \(\Q\) is given by \(d(x,y)=\abs{x-y}_p\). This is an incomplete metric.
    The completion is called \(\Q_p\), the set of *\(p\)-adic numbers*
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(C([0,1])\) is the space of continuous functions \(f:[0,1]\to\R\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    There is a metric on \(C([0,1])\) where \(d(f,g)=\max\{\abs{f(x)-g(x)}:x\in[0,1]\}\). This
    makes \(C([0,1])\) into a complete metric space.
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A metric space \((M,d)\) is *connected* if the only clopen sets are \(M\) and \(\emptyset\).
    Otherwise \(M\) is disconnected
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq M\) is *connected* (resp. *disconnected*) if the subspace \((X,d)\)is connected or
    disconnected as a metric space.
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(X\) is disconnected iff there is a non-constant continuous function \(f:X\to\{0,1\}\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The set \([-10,-1]\cup[1,10]\) is disconnected, as witnessed by
    \begin{equation*}
    f(x)=
    \begin{cases}
    0&x<0\\
    1&x>0
    \end{cases}
    \end{equation*}
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The set \([-10,10]\setminus\{0\}\) is disconnected
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    The set \(\Q\) is disconnected, witnessed by
    \begin{equation*}
    f(x)=
    \begin{cases}
    0&x<\sqrt{2}\\
    1&x>\sqrt{2}
    \end{cases}
    \end{equation*}
    The set \(\R\setminus\Q\) is disconnected by a similar argument
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(X\subseteq\R\) is non-empty, then the following are equivalent
    * \(X\) is connected
    * \(X\) is convex: if \(a,b\in X\), then \([a,b]\subseteq X\)
    * \(X\) is an interval, a set of the form
      \begin{gather*}
      [a,b],(a,b),(a,b],[a,b)\\
      (-\infty,a),(-\infty,a],[a,+\infty),(a,+\infty),(-\infty,\infty)
      \end{gather*}
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Let \(f:M\to M'\) be continuous. If \(X\subseteq M\) is connected, then \(f(X)\subseteq M'\) is connected
    #+END_proposition

    #+ATTR_LATEX: :options [Intermediate Value Theorem]
    #+BEGIN_corollary
    If \(f:[a,b]\to\R\) is continuous and \(f(a)<y<f(b)\), then there is \(x\in[a,b]\) with \(f(x)=y\)
    #+END_corollary

    #+BEGIN_proof
    \(f([a,b])\) is connected, hence convex, so it contains \(y\in[f(a),f(b)]\). Therefore there
    is \(x\in[a,b]\) with \(f(x)=y\)
    #+END_proof

    There are discontinuous functions \(f:\R\to\R\) satisfying the IVT

    classify infinite set with only 1 unary predicate

* Problems want to ask
    [[Problem1]]
