#+TITLE: Measure Theory
#+AUTHOR: Claudio Landim
#+LATEX_HEADER: \input{preamble.tex}
#+EXPORT_FILE_NAME: ../latex/MeasureTheory/MeasureTheory.tex

* Introduction: a non-measurable set
  Suppose we want a measure that satisfies:
  0. [@0] $\lambda:\calp(\R)\to\R_+\cup\{+\infty\}$
  1. $\lambda((a,b])=b-a$
  2. $A\subseteq\R,A+x=\{x+y:y\in A\}$
     \begin{equation*}
     \forall A\subseteq\R\forall x\in\R,\lambda(A+x)=\lambda(A)
     \end{equation*}
  3. $A=\bigcup_{j\ge 1}A_j,A_j\cap A_k=\emptyset$
     \begin{equation*}
     \lambda(A)=\displaystyle\sum_{k\ge1}\lambda(A_k)
     \end{equation*}

     

  Define $x\sim y$ for $x,y\in\R$ if $y-x\in\Q$. $\Lambda=\R/\sim$ and
  $\alpha,\beta\in\Lambda$. $\Gamma$ is uncountable since each equivalent class
  is countable.

  By the *Axiom of Choice*, we have a $\Omega\subseteq\R$ s.t. for each
  $[x]\in\R/\sim$, there is a $x\in[x]$ s.t. $x\in\Omega$. Hence we can assume
  $\Omega\subseteq(0,1)$. 

  #+BEGIN_claim
  For $p,q\in\Q$, either $\Omega+p=\Omega+q$ or
  $\Omega+p\cap\Omega+q=\emptyset$.
  #+END_claim

  #+BEGIN_proof
  Assume $(\Omega+p)\cap(\Omega+q)\neq\emptyset$, $x=\alpha+p=\beta+q$. Hence
  $\alpha-\beta=q-p\in\Q$, which implies $\alpha=\beta$.
  #+END_proof

  #+BEGIN_claim
  $\Omega+q\subseteq(-1,2)$ since $-1<q<1$.
  #+END_claim

  In particular,
  \begin{equation*}
  \displaystyle\bigcup_{\substack{q\in\Q\\-1<q<1}}(\Omega+q)\subseteq(-1,2)
  \end{equation*}

  #+BEGIN_claim
  If $E\subseteq F$, then $\lambda(E)\le\lambda(F)$
  #+END_claim

  #+BEGIN_proof
  $\lambda(F)=\lambda(E\cup(F-E))=\lambda(E)+\lambda(F-E)$
  #+END_proof

  If $q\neq p$,
  \begin{equation*}
  \lambda(\displaystyle\bigcup_{\substack{q\in\Q\\-1<q<1}}(\Omega+q))
  =\displaystyle\sum_{\substack{q\in\Q\\-1<q<1}}\lambda(\Omega+q)
  =\displaystyle\sum_{\substack{q\in\Q\\-1<q<1}}\lambda(\Omega)
  \le\lambda((-1,2))
  =3
  \end{equation*}
  
  Hence $\lambda(\Omega)=0$

  #+BEGIN_claim
  $(0,1)\subseteq\sum_{q\in\Q,-1<q<1}(\Omega+q)$
  #+END_claim

  #+BEGIN_proof
  Fix $x\in[0,1]$, $\exists\alpha\in[x]\cap\Omega$ and $\alpha\in(0,1)$. Hence
  $\alpha-x=q\in\Q$. Then $x\in\Omega+q$
  #+END_proof
  
  Hence we have a contradiction and there is no such \lambda function.

* Classes of subsets
  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  For $\cals\subseteq\calp(\Omega)$, $\cals$ is a *semi-algebra* if
  1. $\Omega\in\cals$
  2. If $A,B\in\cals$, then $A\cap B\in\cals$
  3. For all $A\in\cals$, there are $E_1,\dots,E_n\in\cals$ s.t. $A^c=\sqcup E_j$
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_examplle
  If $\Omega=\R$ and 
  \begin{align*}
  \cals&=\R\cup\{(a,b]:a<b,a,b\in\R\}\\
  &\cup\{(-\infty,b]:b\in\R\}\\
  &\cup\{(a,\infty):a\in\R\}\\
  &\cup\emptyset
  \end{align*}
  then $\cals$ is a semi-algebra
  #+END_examplle

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Take $\cala\subseteq\calp(\Omega)$, $\cala$ is an *algebra* if
  1. $\Omega\in\cala$
  2. If $A,B\in\cala$, then $A\cap B\in\cala$
  3. If $A\in\cala$, then $A^c\in\cala$
  #+END_definition

  If $\cala$ is an algebra, then it is also semi-algebra.

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  $\calf\subseteq\calp(\Omega)$ is a *\sigma-algebra* if
  1. $\Omega\in\calf$
  2. If $A_j\in\calf$ for $j\ge 1$, then $\bigcap_{j\ge1}A_j\in\calf$
  3. If $A\in\calf$, then $A^c\in\calf$
  #+END_definition

  #+ATTR_LATEX: :options []
  #+BEGIN_proposition
  Suppose $\cala_\alpha\subseteq\calp(\Omega)$, $\cala_\alpha$ is an (\sigma-)algebra, 
  $\alpha\in I$. Then $\cala=\bigcap_{\alpha\in I}\cala_\alpha$ is an (\sigma-)algebra
  #+END_proposition

  #+ATTR_LATEX: :options []
  #+BEGIN_definition
  Suppose class $\calc\subseteq\calp(\Omega)$. An (\sigma-)algebra $\cala(\calc)$ *generated*
  *by* $\calc$ is the smallest (\sigma-)algebra s.t. for any (\sigma-)algebra $\calb\supseteq\calc$
  and $\calb$ is an (\sigma-)algebra, then $\calb\supseteq \cala$. Hence
  $\cala(\calc)=\bigcap_\alpha \cala_\alpha$
  #+END_definition


#+ATTR_LATEX: :options []
#+BEGIN_lemma
Let $\cals$ be a semi-algebra and $\cals\subseteq\calp(\Omega)$.
$A\in\cala(\cals)$ 
iff there exists $1\le j\le n,E_j\in\cals$ s.t.
\begin{equation*}
A=\displaystyle\sum_{j=1}^nE_j
\end{equation*}
#+END_lemma

#+BEGIN_proof
Suppose $A=\sum_{j=1}^nE_j,E_j\in\cals\subseteq \cala(\cals)$
- If $E,F\in\cala$ then $E\cup F\in\cala$ since $E\cup F=(E^c\cap F^c)^c$

   
Suppose $A\in \cala(\cals)$, let
$\calb=\{\sum_{j=1}^nF_j:F_j\in\cals\}\subseteq\calp(\Omega)$ 
- $\calb$ is an algebra
- $\calb\supseteq\cals$
#+END_proof

#+ATTR_LATEX: :options []
#+BEGIN_definition
$\calc\subseteq\calp(\Omega),\emptyset\in\calc$ and
$\mu:\calc\to\R_+\cup\{+\infty\}$, \mu is *additive* if
1. $\mu(\emptyset)=0$
2. $E_1,\dots,E_n\in\calc,E=\sum_{j=1}^nE_j\in\calc$, then
   $\mu(E)=\sum_{j=1}^n\mu(E_j)$
#+END_definition

#+BEGIN_remark
1. Assume there is a set $A\in\calc,\mu(A)<\infty$, then $A=A\cup\emptyset$ and
   $\mu(\emptyset)=0$
2. If $E\subseteq F$ and $F-E\in\calc$, if $\mu(E)=+\infty$, $F=E\cup(F-E)$,
   hence $\mu(F)=\mu(E)+\mu(F-E)=+\infty$. If $\mu(E)<\infty$, 
   $\mu(F-E)=\mu(F)-\mu(E)$. We can conclude $\mu(E)\le\mu(F)$
#+END_remark

#+ATTR_LATEX: :options []
#+BEGIN_examplle
Discrete measure. Suppose we have $\{X_j:j\ge 1\},\{P_j:j\ge 1\}$
and $\mu(A)=\sum_{j}P_j1\{X_j\in A\}$ (indicator function), then $\mu$ is
additive 
#+END_examplle

#+ATTR_LATEX: :options []
#+BEGIN_definition
$\emptyset\in\calc\subseteq\calp(\Omega),\mu:\calc\to\R_+\cup\{+\infty\}$. \mu is
*\sigma-additive* if
1. $\mu(\emptyset)=0$
2. $E=\sum_{j\ge 1}E_j\in\calc,\mu(E)=\sum_{j\ge 1}\mu(E_j)$
#+END_definition

#+ATTR_LATEX: :options []
#+BEGIN_examplle
$\Omega=(0,1),\calc=\{(a,b]:0\le a<b<1\}$
\begin{equation*}
\mu((a,b])=
\begin{cases}
+\infty&a=0\\
b-a&b>a
\end{cases}
\end{equation*}
$(a,b]=\sum_{j=1}^n(a_j,b_j]$. \mu is additive but not sigma-additive. If $x_j$
converges to 0, $x_0=1/2$, then $\mu((0,1/2])=+\infty,\mu(\sum_{j\ge1}(x_{j+1},x_j])=1/2$
#+END_examplle

* Set functions
#+ATTR_LATEX: :options []
#+BEGIN_definition
1. \mu is *continuous from below* at $E$ if for all $(E_n)_{n\ge1}$,
   $E_n\in\calc,E_n\subseteq E_{n+1},\bigcup_{n\ge1}E_n=E$,
   $\lim_{n\to\infty}\mu(E_n)=\mu(E)$ 
2. \mu is *continuous from above* at $E$ if $E_n\supseteq
   E_{n+1},\bigcap_{n\ge1}E_n=E,\exists n\;\mu(E_{n_0})<\infty$, then
   $\lim_{n\to\infty}\mu(E_n)=\mu(E)$ 
#+END_definition

#+ATTR_LATEX: :options []
#+BEGIN_lemma
Algebra $\cala\subseteq\calp(\Omega),\mu:\cala\to\R_+\cup\{+\infty\}$ additive,
then
1. If \mu is \sigma-additive, then \mu is continuous at $E$ for all $E\in\cala$
2. If \mu is continuous from below, then \mu is \sigma-additive
3. If \mu is continuous from above at $\emptyset$ and \mu is finite, then \mu is
   \sigma-additive 
#+END_lemma

#+BEGIN_proof
1. Suppose $E_n\uparrow E$, define $F_1=E_1,F_2=E_2-E_1,\dots,F_n=E_n-E_{n-1}$,
   then $\bigcup E_n=\sum
   F_n=E$,$\mu(E)=\sum\mu(F_k)=\lim_{n\to\infty}\sum_{k=1}^n\mu(F_k)=\lim\mu(\sum
   F_k)=\lim\mu(E_n)$ 

   Suppose $E,E_n\in\cala,E_n\downarrow E,\mu(E_{n_0})<\infty$. Define
   $G_1=E_{n_0}-E_{n_0+1}, G_2=E_{n_0}}-E_{n_0+2},\dots,G_k=E_{n_0}-E_{n_0+k}$,
   we know $G_k\uparrow E_{n_0}-E$. By the first part,
   $\mu(G_k)\uparrow\mu(E_{n_0}-E)$.
   $\mu(E_{n_0}-E)=\mu(E_{n_0})-\mu(E)=\lim_k\mu(E_{n_0}-E_{n_0+k})=\lim_k(\mu(E_{n_0})-\mu(E_{n_0+k}))$
2. $\displaystyle\sum_{k=1}^nE_k\subseteq E$, $\mu(\sum E_k)\le\mu(E)$,
   $\sum(\mu(E_k))\le\mu(E)$, hence $\sum\mu(E_k)\le\mu(E)$. Let
   $F_n=\displaystyle\sum_{k=1}^nE_k\in\cala$, $F_n\uparrow E$.
   \sigma-additivity follows.
3. $F_n=\sum_{k\ge n}E_k$. $\mu(E)=\mu(\displaystyle\sum_{k=1}^nE_k\cup
   \displaystyle\sum_{k>n}E_k)=\displaystyle\sum_{k=1}^n\mu(E_k)+\mu(F_{n+1})$
   converges to $\displaystyle\sum_{k\ge1}\mu(E_k)$
#+END_proof

#+ATTR_LATEX: :options []
#+BEGIN_examplle
$(a,b],0\le a<b<1$,
\begin{equation*}
\mu((a,b])=\begin{cases}
          b-a&a>0\\
          +\infty&a=0
         \end{cases}
\end{equation*}
Take $E_n\downarrow\emptyset$, \mu won't be finite in some cases
#+END_examplle

#+ATTR_LATEX: :options []
#+BEGIN_theorem
Suppose we have a semi-algebra $\cals\subseteq\calp(\Omega)$, \mu is additive,
there is a 
\nu s.t. $\nu:\cala(\cals)\to\R_+\cup\{+\infty\}$ 
1. \nu is additive
2. \nu(A)=\mu(A) for all $A\in\cals$
3. If $\mu_1,\mu_2:\cala(\cals)\to\R_+\cup\{+\infty\}$,$\forall
   A\in\cals,\mu_1(A)=\mu_2(A)$, then $\forall
   E\in\cala(\cals),\mu_1(E)=\mu_2(E)$
4. \nu is \sigma-additive
#+END_theorem

#+BEGIN_proof
If $A\in\cala(\cals)$, then $A=\displaystyle\sum_{j=1}^nE_j,E_j\in\cals$.
$\nu(A)=\displaystyle\sum_{j=1}^n\nu(E_j)=\displaystyle\sum_{j=1}^n\mu(E_j)$ 
1. \nu is well-defined

   If $A=\displaystyle\sum_{k=1}^mF_k,F_k\in\cals$, $E_j=E_j\cap
   \displaystyle\sum_{k=1}^mF_k=\displaystyle\sum_{k=1}^m E_j\cap F_k$ and
   $\mu(E_j)=\displaystyle\sum_{k=1}^m \mu(E_j\cap F_k)$. Hence
   $\nu(A)=\displaystyle\sum_{j=1}^n \displaystyle\sum_{k=1}^m\mu(E_j\cap F_k)$
2. \nu is additive
3. unique
4. $A=\displaystyle\sum_{j\ge 1}A_j,A,A_j\in\cala(\cals)$,
   $A=\displaystyle\sum_{j=1}^nE_j,E_j\in\cals$, 
   $A_k=\displaystyle\sum_{l=1}^{m_k}E_{k,l}\in\cals$. 
   \begin{align*}
   E_j&=E_j\cap A
   =E_j\cap(\displaystyle\sum_{k\ge 1}A_k)\\
   &=E_j\cap
   (\displaystyle\sum_{k\ge 1}\displaystyle\sum_{l=1}^{m_k}E_{k,l})
   =\displaystyle\sum_{k\ge 1}\displaystyle\sum_{l=1}^{m_k}E_j\cap E_{k,l}
   \end{align*}
   $\mu(E_j)=\displaystyle\sum_{k\ge1}\displaystyle\sum_{l=1}^{m_k}\mu(E_j\cap
   E_{k,l})$ and $\nu(A)=\displaystyle\sum_{j=1}^n\mu(E_j)=
   \displaystyle\sum_{j=1}^n
   \displaystyle\sum_{k\ge 1}\displaystyle\sum_{l=1}^{m_k}\mu(E_j\cap E_{k,l})$.
   \begin{align*}
   E_{k,l}&=E_{k,l}\cap A=\displaystyle\sum_{j=1}^nE_{k,l}\cap E_j
   \end{align*}
   $\mu(E_{k,l})=\displaystyle\sum_{j=1}^n\mu(E_{k,l}\cap E_j)$. Finish.
#+END_proof
