#+TITLE: Set Theory
#+AUTHOR: 郝兆宽
#+EXPORT_FILE_NAME: ../latex/SetTheoryHao/SetTheoryHao.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
* Intro
    习题 40%

    考试 闭卷

    期中 8周

    集合 \(\{x,y,z,\dots\}\) 外延 \(\{x\mid x\text{ is ...}\}\) 内涵

    #+ATTR_LATEX: :options [Cantor-Bendixen]
    #+BEGIN_theorem
    闭集\(X\subseteq\R\) uncountable, then \(X=Y_1\cup Y_2\), where \(Y_1\) is countable and \(Y_2\) is perfect
    #+END_theorem

    if \(Y_2\) is perfect, then \(\abs{Y_2}=\abs{\R}\).

    Hence CH is true for close set

    Suppose \(X\) is a set and \(Y=\{x\mid x\in X\wedge x\not\in x\}\) is a set

    \(Y\in Y\) => \(Y\in X\) and \(Y\not\in Y\), a contradiction. Hence \(Y\not\in Y\).

    \(Y\not\in Y\) => \(Y\not\in X\) or \(Y\in Y\) => \(Y\not\in X\)

    Thus we have
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. For any set \(X\), there exists a set \(Y\) s.t. \(Y\not\in X\).
    2. collection of all sets is not a set
    #+END_proposition

    Notation: we call \(\{x\mid\varphi(x)\}\) a class

    \(V=\{x\mid x=x\}\), \(\{x\mid x\not\in x\}\) is not a set

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(\{x\mid x\neq x\}\) is a set
    #+END_proposition

    #+BEGIN_proof
    From Existential Axiom, there is a set \(X_0\).

    Claim: \(\{x\mid x\neq x\}=\{x\mid x\in X_0\wedge x\neq x\}\)

    for any \(z\), \(z\neq z\), we need to prove \(z\in X_0\). But \(z\neq z\) is always false.
    #+END_proof

    We write \(\emptyset=\{x\mid x\neq x\}\)

    For any set \(X\neq\emptyset\), its arbitrary intersection
    \begin{equation*}
    \bigcap X=\{u\mid\forall Y(Y\in X\to u\in Y)\}
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((x,y)=\{\{x\},\{x,y\}\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \((x,y)=(x',y')\Leftrightarrow x=x'\wedge y=y'\)
    #+END_proposition

    #+BEGIN_proof
    作业
    #+END_proof


    _partial ordering + well-founded => linear ordering_

    since for arbitrary \(\{x,y\}\), it has a minimal element

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any set \alpha, if \(\in\) is a well-ordering on \alpha, then \alpha is an *ordinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    *successor* of \(x\) is \(S(x)=x\cup\{x\}\), or \(x^+\)
    #+END_definition

    ordinal that is not 0 and successor is a limit ordinal

    极限是否存在

    let \(\omega=\{n\mid n=0\vee n\text{ is successor and }\forall m<n(m\text{ is successor})\}\)

    Then we need to show that \omega is a set. So we need new axiom

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(X\) 是归纳集，则\(\omega\subseteq X\)
    #+END_proposition

    #+BEGIN_proof
    Otherwise we have least \(n\in\omega\) and \(n\not\in X\). Let \(n=S(m)\), then \(m\in X\). Hence we get a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any \(X\subset\omega\), if \(X\) is inductive, then \(X=\omega\)
    #+END_theorem

    \([\varphi(0)\wedge\varphi(n)\to\varphi(n+1)]\Rightarrow\forall n\varphi(n)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \omega is a ordinal and is a limit ordinal
    #+END_theorem

    #+BEGIN_proof
    \(\in\) is a well-ordering on \omega, then we need show
    1. \(\in\) is a partial ordering
       1. transitive. let \(\varphi(x)\): if \(m<n\), then for any \(x\), \(n<x\to m<x\)

          \(x=0\)

          \(x=k+1\), \(n<k+1\), \(n\in k\cup\{k\}\). then \(n=k\) or \(n\in k\)
    2. \(\in\) is well-founded

       \(X\subseteq\omega\), \(X\neq\emptyset\), then \(\exists x_0\in X\). consider \(\omega-X\). Suppose \(X\) has no minimum element
       1. \(0\not\in X\Rightarrow 0\in\omega\)

       2. if \(n\in\omega-X\), then \(S(n)\in\omega-X\). Suppose \(n\not\in X\) and \(S(n)\in X\). Then \(S(n)\) is minimum

       then \(\omega-X\) is inductive



    for any \(\alpha<\omega\), \(S(\alpha)\neq\omega\), hence \omega is limit
    #+END_proof
* 序数
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    一个集合\(X\)成为 *传递* 的，如果对任意\(x\in X\)，都有\(x\subseteq X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    假设\(X\)是传递集。如果\(X\)的所有元素也是传递集，则\(\in\)在\(X\)上是一个传递关系。反之亦然。
    #+END_proposition

    #+BEGIN_proof
    注意在证明反方向时，\(\in\)是\(X\)上的传递关系，如果\(x\in b\), \(b\in a\)，我们先说明\(x,b,a\in X\)，然
    后因为\(\in\)是传递关系，于是\(x\in a\)
    #+END_proof

    #+BEGIN_exercise
    如果\((\calt,\in)\)是传递集，则外延公理在\(\calt\)中成立，即：对任意\(X,Y\in\calt\)，\(X=Y\)当且仅当对任
    意\(a\in\calt\),\(a\in X\)当且仅当\(a\in Y\)。即\(X\cap\calt=Y\cap\calt\)
    #+END_exercise

    如果\(\calt\)不传递，存在\(X\in\calt\)，有\(X\not\subseteq\calt\)，有\(a\in X\)且\(a\notin\calt\)，假设\(X\)与\(Y\)仅有\(a\)差别，
    但是\(\calt\)分辨不出

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    对任意集合\alpha，如果\(\in\)是\alpha上的良序，就称\alpha是 *序数*
    #+END_definition

    \(\{\omega,\omega+1,\omega+2,\dots\}\)是集合吗？这需要替换公理

    考虑\(V_{\omega+\omega}\)，我们定义集合是它的元素，替换公理在这里不对，\(f(\omega)\notin V_{\omega+\omega}\)不是集合。因此我们
    需要替换公理来保证它是集合
* 基数与选择公理
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    TFAE
    1. set \(X\) is finite
    2. there is a linear order \(\le\) on \(X\) satisfying for any nonempty subset there is a maximum
       and a minimum
    3. \(\forall Y\subseteq\calp(X)\) and \(Y\neq\emptyset\), it has a maximal under \(\subseteq\)
    #+END_proposition

    #+BEGIN_proof
    \(2\to 1\). Let \(x_0=\inf(X)\). For any \(k\in\N\), let \(x_{k+1}=\inf(X-\{x_0,\dots,x_k\})\)
    if \(x_k\neq\sup(X)\).

    \(1\to 3\). Find a maximum cardinality

    \(3\to 1\). If \(X\) is infinite. \(Y=\{Z\subseteq X\mid Z\text{ is finite}\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    一个序数是\(\alpha\)是至多可数的，当且仅当存在\(\R\)的子集\(A\)，\(ot(A)=\alpha\)
    #+END_theorem

    #+BEGIN_proof
    首先假设\(A\subseteq\R\)并且\(ot(A)=\alpha\)，即\(A=\{a_\beta\mid\beta<\alpha\}\)，并且\(a_\beta<a_\gamma\)当且仅当\(\beta<\gamma\)。对任意\(\beta<\alpha\)，
    令\(I_\beta=(a_\beta,a_{\beta+1})\)为实数的区间。如果\(\alpha=\eta+1\)是后继序数，则令\(I_\eta=(a_\eta,a_\eta+1)\)。这样的区间
    只有可数多
    #+LATEX: \wu{
    因为每个区间都有有理数，但是有理数只有可数多
    #+LATEX: }
    #+END_proof

    #+ATTR_LATEX: :options [2.2.15]
    #+BEGIN_proposition
    对任意无穷基数\(\kappa,\lambda\)
    1. \(\kappa^{<\lambda}=\sup\{\kappa^\eta\mid\eta\text{是基数并且}\eta<\lambda\}\)
    #+END_proposition

    #+BEGIN_proof
    1. TTT
       \begin{align*}
       \kappa^{<\lambda}&=\abs{\bigcup\{X^\beta\mid\beta<\lambda\}}\\
       &=\{\bigcup_{\beta<\lambda}\kappa^\beta\}=\bigoplus_{\beta<\lambda}\abs{\kappa^\beta}\\
       &=\sup\{\abs{\kappa^\beta}\mid\beta<\lambda\}\\
       &=\sup\{\kappa^{\abs{\beta}}\mid\beta<\lambda\}
       \end{align*}
    2. 对于\(f\in\kappa^\lambda\)，\(f\)都是\(\lambda\otimes\kappa\)的子集且 \(f\in\{X\subseteq\lambda\otimes\kappa\mid\abs{X}=\lambda\}\)
    #+END_proof

    #+BEGIN_exercise
    若\(\kappa\)是不可达的，则\(V_\kappa\vDash ZF\)。
    #+END_exercise

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(ZF\not\vDash\exists\kappa(\kappa\text{是inaccessible})\)
    #+END_corollary

    #+BEGIN_proof
    由 Gödel 第二不完全性定理，如果存在了，就能证明有模型了，就证明一致了
    #+END_proof

    大基数：\(\kappa\)是基数且\(ZF\not\vDash\exists\kappa\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \kappa 不可达，\(\abs{V_\kappa}=\kappa\).
    #+END_proposition

    #+BEGIN_proof
    \(\kappa\le\abs{V_\kappa}\)

    证明对任意\(\alpha<\kappa\), \(\abs{V_\alpha}<\kappa\),

    根据\(2^\alpha<\kappa\)
    #+END_proof

    证明\(f:\abs{X}=\alpha\to V_\kappa\)有界

    若\(\beta<\alpha\cdot\omega\),\(\beta=\alpha\cdot\xi+\eta\)，其中\(\xi\)有穷

    \(\beta>\alpha\), \(\beta=\alpha\cdot\xi+\eta\). \(\alpha+\beta=\alpha+\alpha\cdot\xi+\eta=\alpha\cdot\xi+\eta\).  \(\alpha+\alpha\cdot\xi=\alpha\cdot\xi\).
    只要证明\(\alpha\cdot(\xi+1)=\alpha+\alpha\cdot\xi\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\abs{\bigcup_{\gamma<\omega_\alpha}V_\gamma}=2^{\aleph_\beta}\)
    #+END_lemma

    #+BEGIN_proof
    \(2^{\aleph_\beta}=\sup\{2^{\aleph_\gamma}\mid\gamma<\beta\}\). Thus \(2^{\aleph_\beta}\le\abs{\bigcup_{\gamma<\omega_\alpha}V_\gamma}\)
    #+END_proof

    \(\abs{V_{\omega+1}}=2^{\aleph_0},\abs{V_{\omega+2}}=2^{\abs{2^{\aleph_0}}}>2^{\aleph_0}\)

    \(\abs{V_{\omega_1}}\ge\abs{V_{\omega+2}}>2^{\aleph_0}=\beth(1)\)

    \(\abs{V_{\omega_1}}=\beth_{\omega_1}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(\kappa\)不可达，\(X\in V_\kappa\),\(f:X\to V_\kappa\)，则\(f[X]\in V_\kappa\)
    #+END_proposition

    #+BEGIN_proof
    \(\abs{X}<\kappa\)，对不可达基数\(\abs{V_\kappa}=\kappa\)

    因此\(\abs{f(X)}<\kappa\)

    已知\(f[X]\subseteq V_\kappa\)。令\(\lambda=\sup\{\rank(y)\mid y\in f[X]\}\),因为\(y\in V_\kappa\)而\(\kappa\)是极限序数，因此存
    在\(\alpha<\kappa\)使得\(y\in V_\alpha\)，于是\(\rank(y)<\alpha+1<\kappa\),因此\(\lambda\)是\(<\kappa\)个小于\(\kappa\)的上界，又因为\(\kappa\)
    是正则的，\(\lambda<\kappa\)，于是\(f[X]\subseteq V_\lambda\)，于是\(f[X]\in V_{\lambda+1}\subseteq V_\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    令\(\beta\)为任意序数，\(\alpha\)为任意极限序数，证明：如果\(\alpha+\beta=\beta\)，则\(\beta\ge\alpha\cdot\omega\)
    #+END_proposition

    #+BEGIN_proof
    \(\alpha+\beta=\beta\Rightarrow\alpha\le\beta\Rightarrow\exists\delta,\gamma(\beta=\alpha\cdot\delta+\gamma\wedge\gamma<\alpha)\)

    若\(\delta\ge\omega\)就对了

    若\(\delta<\omega\)，\(\alpha+\beta=\alpha+(\alpha\cdot\delta)+\gamma=\alpha(1+\delta)+\delta>\alpha\)
    #+END_proof

    \(\aleph_1\le 2^{\aleph_0}\)，因此\(\aleph_1^{\aleph_0}\le 2^{\aleph_0\cdot\aleph_0}=2^{\aleph_0}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    令\(X=\{f:\omega\to\omega_1\mid f\text{ 1-1}\}\)，证明\(\abs{X}=2^\omega\)
    #+END_proposition

    #+BEGIN_proof
    \(Y=\{F\mid F:\aleph_0\to\aleph_0\times\aleph_1, \text{1-1}\}\)

    \(G=\aleph_1^{\aleph_0}\to Y\) s.t. \(G(f)=F\in Y\) s.t. \(F(n)=(n,f(n))\), then \(G\) is 1-1

    Hence \(\aleph_1^{\aleph_0}\le\abs{Y}=(\aleph_0\times\aleph_1)^{\aleph_0}=\aleph_1^{\aleph_0}\)
    #+END_proof

    #+BEGIN_proof

    #+END_proof



* 滤、理想与无界闭集
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(-0=1\)
    2. \(-1=0\)
    3. \(a\cdot 1=a\)
    4. \(a+0=a\)
    5. \(a+a=a\)
    6. \(a\cdot a=a\)
    7. \(1+a=1\)
    8. \(0\cdot a=0\)
    9. \(a+b=1\wedge a\cdot b=0\Rightarrow b=-a\)
    10. \(-(a\cdot b)=(-a)+(-b)\)
    11. \(-(a+b)=(-a)\cdot(-b)\)
    #+END_proposition

    #+BEGIN_proof
    1. \(1=0+(-0)=(0\cdot(-0))+(-0)=-0\)
    2. \(0=1\cdot(-1)=(1+(-1))\cdot(-1)=-1\)
    3. \(a\cdot 1=a\cdot(a+(-a))=a\)
    5. [@5] \(a+a=a+(a\cdot 1)=a\)
    7. [@7] \(1+a=(a+1)\cdot 1=(a+1)\cdot(a+-a)=a\cdot a+0+a+-a=a+-a=1\)
    8. \(0\cdot a=(a\cdot (-a))\cdot a=a\cdot a\cdot (-a)=a\cdot (-a)=0\)
    9. [@9] \(-a=(-a)\cdot 1=(-a)\cdot(a+b)=(-a)\cdot a+(-a)\cdot b=(-a)\cdot b\).

       \(ab+(-a)b=-a\). \(b(a+(-a))=b=-a\)
    10. \(ab+(-a)+(-b)=ab+(-a)+(-b)\cdot 1=ab+(-a)+(-b)a+(-b)(-a)=a(b+(-b))+(-a)+(-b)(-a)=1+(-b)(-a)=1\)
    #+END_proof

    \(G\)有有穷交性质
    \(F=\{b\in B\mid\exists g\in G(g\le b)\}\)

    若\(a,b\in F\)，则\(g_1\le a,g_2\le b\)

    Rasiowa-Sikorski [mathematics for metamathematics] 是为了证明一阶完全性，\(\sum D\)等价于\(\exists x\)

    令\(\phi(x,\bary)\), \(M_\phi=\{[\varphi(t,\bary)]\mid t\text{ a term}\}\subset B\)

    *Claim* \(\sum M_\phi=[\exists x\varphi(x,\bary)]\)

    那么如果\(U\)是完全的，那么\(\sum M_\phi\in U\)，于是\(\exists t[\phi(t,\bary)]\in U\)。类似于极大一致Henkin集

    under CH \(\abs{A}<2^{\aleph_0}=\aleph_1\) iff \(\abs{A}\le\aleph_0\)

    cichon diagram
* 复习
    没有良序集同构于真前段

    递归定理
