#+title: Set Theory3
#+AUTHOR: Ralf Schindler
#+EXPORT_FILE_NAME: ../latex/SetTheory3/SetTheory3.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
* Naive Set Theory
    #+ATTR_LATEX: :options [Cantor]
    #+BEGIN_theorem
    \(\N<\R\)
    #+END_theorem

    #+BEGIN_proof
    Assume that there is an injection from \(\R\) to \(\N\), so that there is then also a
    surjection \(f:\N\to\R\). Write \(x_n\) for \(f(n)\). In particular, \(\R=\{x_n:n\in\N\}\)

    Define \([a_n,b_n]=\{x:a_n\le x\le b_n\}\) as follows. Put \([a_0,b_0]=[0,1]\). Suppose \([a_n,b_n]\)
    has been defined. Pick \([a_{n+1},b_{n+1}]\) so
    that \(a_n\le a_{n+1}<b_{n+1}\le b_n\), \(b_{n+1}-a_{n+1}\le\frac{1}{n+1}\)
    and \(x_n\notin[a_{n+1},b_{n+1}]\).

    Now \(\bigcap_{n\in\N}[a_n,b_n]=\{x\}\) for some \(x\in\R\) by the Nested Interval Principle.
    Obviously \(x\neq x_n\) for all \(n\)
    #+END_proof

    #+ATTR_LATEX: :options [Cantor-Schroder-Bernstein]
    #+BEGIN_theorem
    Let \(X\) and \(Y\) be arbitrary. If \(X\le Y\) and \(Y\le X\), then \(X\sim Y\)
    #+END_theorem

    #+BEGIN_proof
    Suppose we have injections \(f:X\to Y\) and \(g:Y\to X\)

    Let \(X_0=X\), \(X_{n+1}=g''f''X\), \(Y_0=g''Y\), \(Y_{n+1}=g''f''Y_n\)

    \(f:X_0\setminus Y_0\xrightarrow{\sim}f''X_0\setminus f''Y_0\), \(g:f''X_0\setminus f''Y_0\xrightarrow{\sim}Y_1\setminus X_1\)

    \(g\circ f:X_0-Y_0\xrightarrow{\sim}X_1-Y_1\)

    generally, \(gf:X_n-Y_n\xrightarrow{\sim}X_{n+1}-Y_{n+1}\)

    define \(h:X_0\to Y_0\)
    \begin{equation*}
    h(x)=
    \begin{cases}
    gf(x)&\exists n.x\in X_n-Y_n\\
    x
    \end{cases}
    \end{equation*}
    Only need to prove \(h\) is a bijection

    *Claim*: \(h\) is

    \(X=X_0\cup X_1\), \(X_0=\{x\mid \exists n(x\in X_n-Y_n)\}\), \(X_1=X\setminus X_0\)

    \(Y_0=(X_0\cap Y_0)\cup (Y_0\setminus X_0)\)

    // Schindler
    Fix \(f,g\),  \(\forall x\in X\), \(X\)-orbit of \(x\) is a finite or infinite sequence of the form
    \begin{equation*}
    g^{-1}(x),f^{-1}g^{-1}(x), g^{-1}f^{-1}g^{-1}(x),\dots
    \end{equation*}
    let \(n(x)\in\N\cup\{\infty\}\) be the size of \(X\)-orbit.
    Define \(X_0=\{x\in X:n(x)=\infty\}\), \(X_1=\{x\in X:n(x)\text{ even}\}\), \(X_2=\{x\in X:n(x)\text{ odd}\}\)

    \(Y\)-orbit
    \begin{equation*}
    f^{-1}(y),g^{-1}f^{-1}(y),f^{-1}g^{-1}f^{-1}(y),\dots
    \end{equation*}
    \(Y_0=\{y\in Y:n(y)=\infty\}\), \(Y_1=\{y\in Y:n(y)\text{ odd}\}\), \(Y_2=\{y\in Y:n(y)\text{ even}\}\)

    Define \(h:X\to Y\) by
    \begin{equation*}
    h(x)=
    \begin{cases}
    f(x)&x\in X_0\cup X_1\\
    g^{-1}(x)&x\in X_2
    \end{cases}
    \end{equation*}

    Injection: suppose \(x_1\in X_0\cup X_1\), \(x_2\in X_2\), then \(f(x_1)\in Y_0\cup Y_1\), \(f(x_2)\in Y_2\)

    surjection: let \(y\in Y_0\cup Y_1\), then \(f(x)=y\) for some \(x\in X_0\cup X_1\); but then \(y=h(x)\).
    Let \(y\in Y_2\). Then \(g(y)\in X_2\), so blablabla
    #+END_proof

    Let \(A\subset\R\), \(A\) is called *open* iff for every \(a\in A\), there are \(c<a\) and \(b>a\)
    with \((c,b)=\{x:c<x<b\}\subset A\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(A\subset\R\). TFAE
    1. \(A\) is closed
    2. \(\forall x\in\R\), if \(a<x<b\) always implies \((a,b)\cap A\neq\emptyset\), then \(x\in A\)
    #+END_lemma

    \(x\) is *accumulation point* of \(A\) iff for all \(a<x<b\), \((a,b)\cap(A\setminus\{x\})\neq\emptyset\). The set of all
    accumulation points of \(A\) is called the *(first) derivative* of \(A\) and is abbreviated
    by \(A'\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(A\subset\R\), TFAE
    1. \(A\) is closed
    2. \(A'\subset A\)
    #+END_lemma

    Let \(A\subset\R\), a set \(B\subset A\) is *dense in \(A\)* if for all \(a,b\in\R\) with \(a<b\)
    and \([a,b]\cap A\neq\emptyset\), \([a,b]\cap B\neq\emptyset\). \(A\) is *dense* if \(A\) is dense in \(\R\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(A\subset\R\) is called *perfect* iff \(A\neq\emptyset\) and \(A'=A\)
    #+END_definition

    perfect set is a subset of close set. Consider \(\{a\}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(2^{\N}\sim\R\)
    #+END_lemma

    #+BEGIN_proof
    Since \(\R\subseteq\calp(\Q)\), \(\abs{\R}\le\abs{\calp(\Q)}=\abs{2^{\N}}\)

    use cantor set to prove \(2^{\N}\le[0,1]\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(A\subset\R\) be perfect, then \(A\sim\R\)
    #+END_theorem

    #+BEGIN_proof
    Let \(A\) be a perfect set, then \(A\neq\emptyset\). Then we can pick two different elements \(x_0,x_1\),
    then use the methods similar to cantor set
    #+END_proof

    #+ATTR_LATEX: :options [Cantor-Bendixson]
    #+BEGIN_theorem
    Let \(A\subset\R\) be closed. Then there are sets \(A_0\cup\R\) and \(P\cup\R\) so that
    1. \(A\) is the disjoint union of \(A_0\) and \(P\)
    2. \(A_0\) is at most countable
    3. \(P\) is perfect, unless \(P=\emptyset\)
    #+END_theorem

    #+BEGIN_proof
    \(x\in X\) is a *condensation point* of \(A\) iff \((a,b)\cap A\) is uncountable for all \(a<x<b\)

    Let \(P\) be the set of all condensation points of \(A\) and let \(A_0=A\setminus P\). As \(A\) is
    closed, \(P\subset A'\subset A\).

    Let \(x\in A_0\), then there are \(a_x<x<b_x\) with \(a_x,b_x\in\Q\) and s.t. \((a_x,b_x)\cap A\) is at most
    countable. Therefore
    \begin{equation*}
    A_0\subset\bigcup_{x\in A_0}(a_x,b_x)\cap A
    \end{equation*}
    As \(\Q\sim\N\), there are at most countably many sets of the form \((a_x,b_x)\cap A\), and each of them
    is at most countable. Hence \(A_0\) is at most countable

    Suppose that \(P\neq\emptyset\). We first show that \(P\subset P'\). Let \(x\in P\). Let \(a<x<b\). We have
    that \((a,b)\cap A\) uncountable. Suppose \((a,b)\cap(P\setminus\{x\})=\emptyset\). For each \(y\in((a,b)\setminus\{x\})\cap A\) there
    are then \(a_y<y<b_y\) with \(a_y,b_y\in\Q\) so that \((a_y,b_y)\cap A\) is at most countable. But
    then we have
    \begin{equation*}
    (a,b)\cap A\subset\{x\}\cup\bigcup_{y\in(a,b)\setminus\{x\}}(a_y,b_y)\cap A
    \end{equation*}
    at most countable

    Let \(x\in P'\). Then \((a,b)\cap(P\setminus\{x\})\neq\emptyset\) for all \(a<x<b\). Let \(y\in(a,b)\cap(P\setminus\{x\})\),
    where \(a<x<b\). Then \((a,b)\cap A\) is uncountable. Hence \(x\in P\)
    #+END_proof



    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Let \(A\subset\R\) be closed. Then \(A\le\N\) or \(A\sim\R\)
    #+END_corollary
* Axiomatic Set Theory
** Gödel-Bernays Class Theory
    Has variables \(X,Y,Z,\dots,A,B,\dots\) ranging over /classes/

    The axioms of the *Bernays-Gödel class theory* are Ext, Fund, Pair, Union, Pow, Inf exactly as
    before together with the following ones
    \begin{gather*}
    \forall X\forall Y\forall x((x\in X\leftrightarrow x\in Y)\to X=Y)\\
    \forall x\exists X\;x=X\\
    \forall X(\exists Y\;X\in Y\leftrightarrow\exists x\;x=X)\\
    \end{gather*}
    and (Rep*): if \(F\) is a (class) function, then \(F''a\) is a set for each set \(a\). For all
    \varphi s.t. \varphi is a formula of the language of \(\BG\), which contains exactly \(x, X_1,\dots,X_k\)  as its
    free variables and which does not have quantifiers ranging over classes, then
    \begin{equation*}
    \forall X_1\dots X_k\exists Y\forall x(x\in Y\leftrightarrow\varphi)\tag{Comp\(_\varphi\)}
    \end{equation*}
    , which is called the *comprehension axiom* for \varphi, and the collection of all (\(\text{Comp}_\varphi\))
    is called the *comprehension schema*. The *Bernays-Gödel class theory with choice*, \(\BGC\), is the
    theory \(\BG\) plus the following version of the axiom of choice:
    #+BEGIN_center
    There is a (class) function \(F\) s.t. \(\forall x(x\neq\emptyset\to F(x)\in x)\)\tag{AC}
    #+END_center
* Ordinals
