#+TITLE: Set Theory2

#+AUTHOR: Yao

#+EXPORT_FILE_NAME: ../latex/SetTheory2/SetTheory2.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \def \FORM {\text{FORM}}
#+LATEX_HEADER: \def \PROOF {\text{PROOF}}
* 集合的宇宙
** 数理逻辑
    在\(\ZFC\)下证明\(\ZFC\vdash\CH\)，希望将"\(\ZFC\vdash\CH\)"表述为一阶句子

    一般而言，给定一个\(\call\)-理论\(T\)和一个\(\call\)-句子\(\delta\)，"\(T\vdash\sigma\)"不能用一个\(\call\)-句子表示，只能
    用元语言表述

    我们需要在\(\ZFC\)中编码“元语言”

    在\(\ZFC\)中可以定义\(\caln=(\N,+,\times,0,1)\)

    即存在集合论语言\(\call=\{\in\}\)中的 *公式* ，在\(\ZFC\)的任意模型中可以定义 \(\N,+,\times,0,1\)，以上公式与模
    型无关

    用\(\ucorner{0}\)，\(\ucorner{1}\)，\(\ucorner{2}\)... 表示\(\ZFC\)中的“自然数”，以区别元语言中
    的自然数

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(R\subseteq\N^n\)是一个递归关系。\(T\subseteq\Th(\caln)\)是包含数论的适当丰富的理论，则存在公式\(\varphi(x_1,\dots,x_n)\)使
    得对任意自然数\(m_1,\dots,m_n\)有
    \begin{align*}
    &\text{如果}(m_1,\dots,m_n)\in R\text{则}T\vdash\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\\
    &\text{如果}(m_1,\dots,m_n)\notin R\text{则}T\vdash\neg\varphi(\ucorner{m_1},\dots,\ucorner{m_n})
    \end{align*}
    #+END_theorem

    #+BEGIN_remark
    1. \(T\subseteq\Th(\caln)\subseteq\ZFC\)
    2. \(\varphi\)是语言\(\{+,\times,0,1\}\)上的公式
    3. \(\varphi\)可以还原为一个\(\{\in\}\)上的公式
    4. \(\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\)是一个闭语句
    #+END_remark

    *编码*

    编码函数\(f:X\to\N\)

    存在解码函数\(g,h\)，对\(a=a_0,\dots,a_n\in X\), \(h(f(a))=n+1\), \(g(f(a),k)=a_k\) (分量)

    性质：以上三种函数\(f,g,h\)均是递归函数\(\Rightarrow\)都是可表示的

    性质：“公式集”的编码集是递归的

    性质：如果\(T\subseteq\ZFC\)是可公理化的，则\(T\)的证明集的编码集是递归的

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    存在一个公式 \(\psi\) 和\(\theta\)使得
    \begin{align*}
    \ZFC\vdash\psi(n)&\Leftrightarrow n\text{ is a formula}\\
    \ZFC\vdash\neg\psi(n)&\Leftrightarrow n\text{ is not a formula}\\
    \ZFC\vdash\theta(n)&\Leftrightarrow n\text{ is a proof in }\ZFC\\
    \ZFC\vdash\neg\theta(n)&\Leftrightarrow n\text{ is not a proof in }\ZFC\\
    \end{align*}
    称\(\psi\)定义了公式集，\(\theta\)定义了证明集
    #+END_corollary

    \(\FORM=\{\ucorner{\varphi}\mid\varphi\text{ formula}\}\subseteq\N\)

    如果\(T\subseteq\ZFC\)是可公理化的，则“\(T\)是一致的”是一个一阶表述式
    “不存在一个有穷的证明序列\(D=(\varphi_1,\dots,\varphi_n)\)使得\(\varphi_n\)形如\(\varphi\wedge\neg\varphi\)
，记作\(\Con(T)\)

    #+ATTR_LATEX: :options [第二不完全]
    #+BEGIN_theorem
    如果\(T\)是包含\(\ZFC\)的一个递归公理集，且\(T\)一致，则
    \begin{equation*}
    T\not\vdash\Con(T)
    \end{equation*}
    特别地，\(\ZFC\not\vdash\Con(\ZFC)\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    对任意可公理化的理论\(T\)，\(\ZFC\vdash\Con(T)\)当且仅当存在\(M\vDash T\)
    #+END_theorem

    即不能在\(\ZFC\)里证明\(\ZFC\)有一个模型

    需要可公理化来写出\(\Con(T)\)，因此因为\(\ZFC\not\vDash\Con(T)\)，我们只能假设这么一个模型

    集合论的模型跟集合论没什么关系，就是一个集合带一个二元关系，是关于集合论语言的结构

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\((M,E)\)是集合论模型
    1. 对任意公式\(\varphi(\barx,y)\)，定义\(M^n\)上的函数
       \begin{equation*}
       h_\varphi:M^n\to M
       \end{equation*}
       满足条件
       \begin{equation*}
       M\vDash\exists y\varphi(\bara,y)\Rightarrow M\vDash\varphi(\bara,h_\varphi(\bara))
       \end{equation*}
       称\(h_\varphi\)为\(\varphi\)的Skolem函数（依赖于选择公理，不同的变量选择有不同的函数）
    2. 令\(\calh=\{h_\varphi\mid\varphi\text{ formula}\}\)为Skolem函数集合，设\(S\)是\(M\)的任意子集，则\(\calh(S)\)表示包
       含\(S\)且对\(\calh\)封闭的最小集合，称之为\(S\)的Skolem壳
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(N\)是集合论模型，\(S\subseteq N\)，如果\(M=\calh(S)\)，则\(M\prec N\)
    #+END_lemma

    #+BEGIN_proof
    Induction

    对任意\(\bara\in M^n\)，有\(M\vDash\varphi(\bara)\Leftrightarrow N\vDash\varphi(\bara)\)
    1. 不含量词，显然成立
    2. \(\varphi\)形如\(\exists y\psi(\barx,y)\), \(N\vDash\exists y\psi(\bara,y)\Rightarrow N\vDash\psi(\bara,h_\psi(\bara))\)，by
       IH, \(M\vDash\psi(\bara,h_\psi(\bara))\Rightarrow M\vDash\exists y\psi(\bara,y)\)
    #+END_proof

    #+ATTR_LATEX: :options [Löwenheim–Skolem Theorem]
    #+BEGIN_theorem

    #+END_theorem
** 层垒的谱系
    工作于\(\ZF^-\)：\(\ZF-\)基础公理

    \(\alpha\mapsto V_\alpha\)是\(\On\)到\(\WF\)的1-1映射，而\(\On\)是真类

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any ordinal \alpha
    1. \(V_\alpha\) is transitive
    2. \(\xi\le\alpha\Rightarrow V_\xi\subseteq V_\alpha\)
    3. if \kappa is inaccessible, then \(\abs{V_\kappa}=\kappa\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any \(x\in\WF\), *rank* of \(x\) is
    \begin{equation*}
    \rank(x)=\min\{\beta\mid x\in V_{\beta+1}\}
    \end{equation*}
    #+END_definition

    \(\rank(x)=\alpha\Rightarrow x\in V_{\alpha+1}\wedge x\notin V_\alpha\)

    - \(x\in V_{\alpha+1}\Leftrightarrow\rank(x)\le\alpha\)
    - \(x\subseteq V_\alpha\Leftrightarrow\rank(x)\le\alpha\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_lemma

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof

    * \(\WF\)中的集合按照秩分层
    * 在\(\WF\)中基础公理是成立的：\(\forall y(y\neq\emptyset\to\exists x\in y(x\cap y=\emptyset))\)，因为任何序数集都有最小元，挑一个有最
      小rank的就好了
    * \(\WF\)类的构造没有用到选择公理
    * \(\On\subseteq\WF\)


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    for any ordinal \alpha
    1. \(\alpha\in\WF\) and \(\rank(\alpha)=\alpha\)
    2. \(V_\alpha\cap\On=\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1. \(0\in V_1\setminus V_0\subset\WF\), \(\rank(0)=0\)

       If \(\alpha\in\WF\)
       and
       \(\rank(\alpha)=\alpha\).
       \(\alpha\in V_{\alpha+1}\setminus V_\alpha\), \(\alpha\subseteq V_{\alpha+1}\). \(\alpha+1=\alpha\cup\{\alpha\}\subseteq V_{\alpha+1}\), \(\alpha+1\in V_{\alpha+2}\subset\WF\).
       If \(\alpha+1\in V_{\alpha+1}\), then \(\rank(\alpha+1)\le\alpha\), but \(\alpha\in\alpha+1\Rightarrow\rank(\alpha)=\alpha<\rank(\alpha+1)\). A
       contradiction

       suppose \gamma is a limit ordinal and for any \(\alpha<\gamma\), \(\alpha\in V_{\alpha+1}\setminus V_\alpha\).
       \(\gamma=\bigcup_{\alpha<\gamma}\alpha\subseteq\bigcup_{\alpha<\gamma}V_\alpha=V_\gamma\). Thus \(\gamma\in V_{\gamma+1}\), \(\rank(\gamma)\le\gamma\) and \(\rank(\gamma)\not<\gamma\).
    2. suppose \(\beta\in V_\alpha\cap\On\), then \(\beta=\rank(\beta)<\alpha\). If \(\beta\in\alpha\) and \(\rank(\beta)<\alpha\), \(\beta\in V_\alpha\cap\On\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(x\in\WF\), then \(\bigcup x,\calp(x),\{x\}\in\WF\), and their rank \(<\rank(x)+\omega\)
    2. If \(x,y\in\WF\), then \(x\times y,x\cup y,x\cap y,\{x,y\},(x,y),x^y\in\WF\), and their
       rank \(<\rank(x)+\rank(y)+\omega\)
    3. \(\Z,\Q,\R\in V_{\omega+\omega}\)
    4. for any set \(x\), \(x\in\WF\Leftrightarrow x\subset\WF\)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \(\rank(x)=\alpha\). \(x\in V_{\alpha+1}\setminus V_\alpha\) and \(x\subseteq V_\alpha\).

       by transitivity, \(\bigcup x\subseteq V_\alpha\Rightarrow \bigcup x\in V_{\alpha+1}\subset\WF\). \(\rank(\bigcup x)\le\alpha\)

       suppose
       \(y\in\calp(x)\),
       \(y\subseteq x\Rightarrow y\subseteq V_\alpha\Rightarrow y\in V_{\alpha+1}\). \(\calp(x)\subseteq V_{\alpha+1}\), \(\calp(x)\in V_{\alpha+2}\), \(\rank(\calp(x))\le\alpha+1\).

       \(\{x\}\in\calp(x)\in V_{\alpha+2}\).

    2. Suppose \(\rank(x)=\alpha,\rank(y)=\beta\), \(x\subset V_\alpha\), \(y\subset V_\beta\)

       \(x\cup y\subset V_\alpha\cup V_\beta=V_{\max(\alpha,\beta)}\), \(\rank(x\cup y)\le\max(\alpha,\beta)\)

       \(x\cap y\subset V_{\min(\alpha,\beta)}\)

       \(\{x,y\}\subseteq V_{\alpha+1}\cup V_{\beta+1}=V_{\max(\alpha,\beta)+1}\), \(\rank(\{x,y\})=\max(\alpha,\beta)+1\)

       \((x,y)=\{\{x\},\{x,y\}\}\subset V_{\max(\alpha,\beta)+2}\). \(\rank((x,y))=\max(\alpha,\beta)+2\)

       \(x\times y=\{(a,b)\mid a\in x,b\in y\}\).
       \(a\in x\Rightarrow\rank(a)<\alpha\), \(b\in y\Rightarrow\rank(b)<\beta\), \(\rank(a,b)<\max(\alpha,\beta)+2\),
       \((a,b)\in V_{\max(\alpha,\beta)+2}\). \(x\times y\subseteq V_{\max(\alpha,\beta)+2}\), \(\rank(x\times y)\le\max(\alpha,\beta)+2\).

       \(x^y\subseteq\calp(x\times y)\subseteq V_{\max(\alpha,\beta)+3}\).

    3. \(\N=\omega\in V_{\omega+1}\)

       \(\Z\): let \(\sim\) be an equivalence relation on \(\omega\times\omega\), \((a,b)\sim(c,d)\Leftrightarrow a+d=b+c\),
       then \(\Z=(\omega\times\omega)/\sim\). Hence \(\Z\) is a partition of \(\omega\times\omega\) and
       hence \(\Z\subseteq\calp(\omega\times\omega)\). \(\Z\in V_{\omega+3}\)

       \(\Q\): let \(\sim\) be an equivalence
       on \(\Z\times\Z^+\), \((a,b)\sim(c,d)\Leftrightarrow ad=bc\). \(\Q\subseteq\calp(\Z\times\Z^+)\), \(\Q\in V_{\omega+6}\)

       \(\R\): set of dedekind cut on \(\Q\), \(\R\subset\calp(\Q)\), \(\R\in V_{\omega+8}\)

    4. \(\Rightarrow\): \(\WF\) is transitive

       \(\Leftarrow\): \(x\) is a set and \(x\subset\bigcup_{\alpha\in\On}V_\alpha\).

       *Claim*: there is an ordinal \alpha s.t. \(x\subset V_\alpha\)

       Otherwise, let \(f:\On\to\calp(x)\) s.t. \(f(\alpha)=x\setminus V_\alpha\). Then for any \(y\in\calp(x)\), \(f^{-1}(y)\) is
       a set. \(\On=\bigcup_{y\in x}f^{-1}(y)\) and is thus a set, a contradiction
    #+END_proof

    AC => Any set has cardinality
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume AC (\(V\vDash\ZFC\))
    1. for any group \(G\), there is a group \(G'\) in \(\WF\) s.t. \(G\cong G'\)
    2. for any topological space \(T\), there is a topological space \(T'\) in \(\WF\)
       s.t. \(T\cong T'\) (homeomorphic)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \((G,*_G)\) is a group, \(G,*_G\in V\). By AC, there is a cardinal \alpha
       s.t. \(\abs{G}=\alpha\), that is, there is a bijection \(f:\alpha\to G\). Define \(*\): for
       any \(x,y,z\in\alpha\), \(x*y=z\Leftrightarrow f(x)*_Gf(y)=f(z)\). Then \((\alpha,​*)\cong(G,​*_G)\), \(​*\subseteq\alpha\times\alpha\)
    #+END_proof

    \(V\)中的任何结构都可以在\(\WF\)中找到同构象（同构是在\(V\)里看到的）

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    任意集合\(A\)上的二元关系<是 *良基* 的，当且仅当对\(A\)的任意非空子集\(X\)，\(X\)有<下的极小元
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\in\WF\), then \(\in\) is a well-founded relation on \(A\)
    #+END_theorem

    #+BEGIN_proof
    suppose \(X\subseteq A\), \(X\neq\emptyset\), \(X\subseteq\WF\), then elements of \(X\) has ranks
    and \(x\in y\Rightarrow\rank(x)<\rank(y)\). Let \(x\) having least rank in \(X\), then \(x\) is
    the \(\in\)-minimal element in \(X\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(A\) is a transitive set and \(\in\) is a well-founded relation on \(A\), then \(A\in\WF\)
    #+END_lemma

    #+BEGIN_proof
    Just need to prove \(A\subset\WF\). If \(A\not\subset\WF\), \(X=A\setminus\WF\neq\emptyset\). Then \(X\) has a \(\in\)-minimal
    element \(x\). Then \(x\neq\emptyset\in\WF\). For any \(y\in x\), \(y\in A\). By the minimality
    of \(x\), \(y\in\WF\). Then \(x\subset\WF\), \(x\in\WF\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any set \(x\), there is a minimal transitive set \(\trcl(x)\) s.t. \(x\subseteq\trcl(x)\)
    #+END_lemma

    #+BEGIN_proof
    For any \(n\in\omega\) define \(x_n\)
    \begin{align*}
    x_0&=x\\
    x_{n+1}&=\bigcup x_n
    \end{align*}
    let \(\trcl(x)=\bigcup_{n\in\omega}x_n\).
    1. \(\trcl(x)\)is transitive

       \(a\in\trcl(x)\Rightarrow a\in x_n\Rightarrow a\subseteq x_{n+1}\subseteq\trcl(x)\)
    2. \(\trcl(x)\) is minimal

       If \(y\supseteq x\) is transitive, recursively prove for any \(n<\omega\), \(x_n\subseteq y\).
    #+END_proof

    \(\trcl(x)\) is the *transitive closure* of \(x\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    We can prove the following without axiom of power set
    1. if \(x\) is transitive, \(\trcl(x)=x\)
    2. \(y\in x\Rightarrow\trcl(y)\subseteq\trcl(x)\)
    3. \(\trcl(x)=x\cup\bigcup\{\trcl(y)\mid y\in x\}\)
    #+END_lemma

    #+BEGIN_proof
    2. [@2] \(y\in x\subset\trcl(x)\). \(y\in\trcl(x)\). \(\trcl(y)\subseteq\trcl(x)\).
    3. \(x\cup\bigcup\{\trcl(y)\mid y\in x\}\subseteq\trcl(x)\) by (2)

       \(\bigcup\{\trcl(y)\mid y\in x\}\) is transitive. For \(y\in x\), \(y\subseteq\trcl(y)\). Thus rhs is transitive
    #+END_proof


    #+ATTR_LATEX: :options [In \(\ZFm\)]
    #+BEGIN_theorem
    For any set \(X\), TFAE
    1. \(X\in\WF\)
    2. \(\trcl(X)\in\WF\)
    3. \(\in\) is a well-founded relation on \(\trcl(X)\)
    #+END_theorem

    #+BEGIN_proof
    \(1\to 2\): \(\WF\) is closed under union
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    In \(\ZFm\), TFAE
    1. axiom of foundation
    2. for any set \(X\), \(\in\) is a well-founded relation on \(X\)
    3. \(V=\WF\)
    #+END_theorem

    \(V\vDash\ZF\Rightarrow V=\WF(\WF\vDash\ZF)\)

    Goal: \(\ZFm\vdash(\WF\vDash\ZF)\)




** Exercise
    #+BEGIN_exercise
    label:ex7.10.3
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_exercise

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof
