#+TITLE: Set Theory2

#+AUTHOR: Yao

#+EXPORT_FILE_NAME: ../latex/SetTheory2/SetTheory2.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \def \FORM {\text{FORM}}
#+LATEX_HEADER: \def \Rep {\text{Rep}}
#+LATEX_HEADER: \def \ZC {\text{ZC}}
#+LATEX_HEADER: \def \PROOF {\text{PROOF}}
* 集合的宇宙
** 数理逻辑
    在\(\ZFC\)下证明\(\ZFC\vdash\CH\)，希望将"\(\ZFC\vdash\CH\)"表述为一阶句子

    一般而言，给定一个\(\call\)-理论\(T\)和一个\(\call\)-句子\(\delta\)，"\(T\vdash\sigma\)"不能用一个\(\call\)-句子表示，只能
    用元语言表述

    我们需要在\(\ZFC\)中编码“元语言”

    在\(\ZFC\)中可以定义\(\caln=(\N,+,\times,0,1)\)

    即存在集合论语言\(\call=\{\in\}\)中的 *公式* ，在\(\ZFC\)的任意模型中可以定义 \(\N,+,\times,0,1\)，以上公式与模
    型无关

    用\(\ucorner{0}\)，\(\ucorner{1}\)，\(\ucorner{2}\)... 表示\(\ZFC\)中的“自然数”，以区别元语言中
    的自然数

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(R\subseteq\N^n\)是一个递归关系。\(T\subseteq\Th(\caln)\)是包含数论的适当丰富的理论，则存在公式\(\varphi(x_1,\dots,x_n)\)使
    得对任意自然数\(m_1,\dots,m_n\)有
    \begin{align*}
    &\text{如果}(m_1,\dots,m_n)\in R\text{则}T\vdash\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\\
    &\text{如果}(m_1,\dots,m_n)\notin R\text{则}T\vdash\neg\varphi(\ucorner{m_1},\dots,\ucorner{m_n})
    \end{align*}
    #+END_theorem

    #+BEGIN_remark
    1. \(T\subseteq\Th(\caln)\subseteq\ZFC\)
    2. \(\varphi\)是语言\(\{+,\times,0,1\}\)上的公式
    3. \(\varphi\)可以还原为一个\(\{\in\}\)上的公式
    4. \(\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\)是一个闭语句
    #+END_remark

    *编码*

    编码函数\(f:X\to\N\)

    存在解码函数\(g,h\)，对\(a=a_0,\dots,a_n\in X\), \(h(f(a))=n+1\), \(g(f(a),k)=a_k\) (分量)

    性质：以上三种函数\(f,g,h\)均是递归函数\(\Rightarrow\)都是可表示的

    性质：“公式集”的编码集是递归的

    性质：如果\(T\subseteq\ZFC\)是可公理化的，则\(T\)的证明集的编码集是递归的

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    存在一个公式 \(\psi\) 和\(\theta\)使得
    \begin{align*}
    \ZFC\vdash\psi(n)&\Leftrightarrow n\text{ is a formula}\\
    \ZFC\vdash\neg\psi(n)&\Leftrightarrow n\text{ is not a formula}\\
    \ZFC\vdash\theta(n)&\Leftrightarrow n\text{ is a proof in }\ZFC\\
    \ZFC\vdash\neg\theta(n)&\Leftrightarrow n\text{ is not a proof in }\ZFC\\
    \end{align*}
    称\(\psi\)定义了公式集，\(\theta\)定义了证明集
    #+END_corollary

    \(\FORM=\{\ucorner{\varphi}\mid\varphi\text{ formula}\}\subseteq\N\)

    如果\(T\subseteq\ZFC\)是可公理化的，则“\(T\)是一致的”是一个一阶表述式
    “不存在一个有穷的证明序列\(D=(\varphi_1,\dots,\varphi_n)\)使得\(\varphi_n\)形如\(\varphi\wedge\neg\varphi\)
，记作\(\Con(T)\)

    #+ATTR_LATEX: :options [第二不完全]
    #+BEGIN_theorem
    如果\(T\)是包含\(\ZFC\)的一个递归公理集，且\(T\)一致，则
    \begin{equation*}
    T\not\vdash\Con(T)
    \end{equation*}
    特别地，\(\ZFC\not\vdash\Con(\ZFC)\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    对任意可公理化的理论\(T\)，\(\ZFC\vdash\Con(T)\)当且仅当存在\(M\vDash T\)
    #+END_theorem

    即不能在\(\ZFC\)里证明\(\ZFC\)有一个模型

    需要可公理化来写出\(\Con(T)\)，因此因为\(\ZFC\not\vDash\Con(T)\)，我们只能假设这么一个模型

    集合论的模型跟集合论没什么关系，就是一个集合带一个二元关系，是关于集合论语言的结构

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\((M,E)\)是集合论模型
    1. 对任意公式\(\varphi(\barx,y)\)，定义\(M^n\)上的函数
       \begin{equation*}
       h_\varphi:M^n\to M
       \end{equation*}
       满足条件
       \begin{equation*}
       M\vDash\exists y\varphi(\bara,y)\Rightarrow M\vDash\varphi(\bara,h_\varphi(\bara))
       \end{equation*}
       称\(h_\varphi\)为\(\varphi\)的Skolem函数（依赖于选择公理，不同的变量选择有不同的函数）
    2. 令\(\calh=\{h_\varphi\mid\varphi\text{ formula}\}\)为Skolem函数集合，设\(S\)是\(M\)的任意子集，则\(\calh(S)\)表示包
       含\(S\)且对\(\calh\)封闭的最小集合，称之为\(S\)的Skolem壳
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(N\)是集合论模型，\(S\subseteq N\)，如果\(M=\calh(S)\)，则\(M\prec N\)
    #+END_lemma

    #+BEGIN_proof
    Induction

    对任意\(\bara\in M^n\)，有\(M\vDash\varphi(\bara)\Leftrightarrow N\vDash\varphi(\bara)\)
    1. 不含量词，显然成立
    2. \(\varphi\)形如\(\exists y\psi(\barx,y)\), \(N\vDash\exists y\psi(\bara,y)\Rightarrow N\vDash\psi(\bara,h_\psi(\bara))\)，by
       IH, \(M\vDash\psi(\bara,h_\psi(\bara))\Rightarrow M\vDash\exists y\psi(\bara,y)\)
    #+END_proof

    #+ATTR_LATEX: :options [Löwenheim–Skolem Theorem]
    #+BEGIN_theorem

    #+END_theorem
** 层垒的谱系
    工作于\(\ZF^-\)：\(\ZF-\)基础公理

    \(\alpha\mapsto V_\alpha\)是\(\On\)到\(\WF\)的1-1映射，而\(\On\)是真类

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any ordinal \alpha
    1. \(V_\alpha\) is transitive
    2. \(\xi\le\alpha\Rightarrow V_\xi\subseteq V_\alpha\)
    3. if \kappa is inaccessible, then \(\abs{V_\kappa}=\kappa\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any \(x\in\WF\), *rank* of \(x\) is
    \begin{equation*}
    \rank(x)=\min\{\beta\mid x\in V_{\beta+1}\}
    \end{equation*}
    #+END_definition

    \(\rank(x)=\alpha\Rightarrow x\in V_{\alpha+1}\wedge x\notin V_\alpha\)

    - \(x\in V_{\alpha+1}\Leftrightarrow\rank(x)\le\alpha\)
    - \(x\subseteq V_\alpha\Leftrightarrow\rank(x)\le\alpha\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_lemma

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof

    * \(\WF\)中的集合按照秩分层
    * 在\(\WF\)中基础公理是成立的：\(\forall y(y\neq\emptyset\to\exists x\in y(x\cap y=\emptyset))\)，因为任何序数集都有最小元，挑一个有最
      小rank的就好了
    * \(\WF\)类的构造没有用到选择公理
    * \(\On\subseteq\WF\)


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    for any ordinal \alpha
    1. \(\alpha\in\WF\) and \(\rank(\alpha)=\alpha\)
    2. \(V_\alpha\cap\On=\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1. \(0\in V_1\setminus V_0\subset\WF\), \(\rank(0)=0\)

       If \(\alpha\in\WF\)
       and
       \(\rank(\alpha)=\alpha\).
       \(\alpha\in V_{\alpha+1}\setminus V_\alpha\), \(\alpha\subseteq V_{\alpha+1}\). \(\alpha+1=\alpha\cup\{\alpha\}\subseteq V_{\alpha+1}\), \(\alpha+1\in V_{\alpha+2}\subset\WF\).
       If \(\alpha+1\in V_{\alpha+1}\), then \(\rank(\alpha+1)\le\alpha\), but \(\alpha\in\alpha+1\Rightarrow\rank(\alpha)=\alpha<\rank(\alpha+1)\). A
       contradiction

       suppose \gamma is a limit ordinal and for any \(\alpha<\gamma\), \(\alpha\in V_{\alpha+1}\setminus V_\alpha\).
       \(\gamma=\bigcup_{\alpha<\gamma}\alpha\subseteq\bigcup_{\alpha<\gamma}V_\alpha=V_\gamma\). Thus \(\gamma\in V_{\gamma+1}\), \(\rank(\gamma)\le\gamma\) and \(\rank(\gamma)\not<\gamma\).
    2. suppose \(\beta\in V_\alpha\cap\On\), then \(\beta=\rank(\beta)<\alpha\). If \(\beta\in\alpha\) and \(\rank(\beta)<\alpha\), \(\beta\in V_\alpha\cap\On\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(x\in\WF\), then \(\bigcup x,\calp(x),\{x\}\in\WF\), and their rank \(<\rank(x)+\omega\)
    2. If \(x,y\in\WF\), then \(x\times y,x\cup y,x\cap y,\{x,y\},(x,y),x^y\in\WF\), and their
       rank \(<\rank(x)+\rank(y)+\omega\)
    3. \(\Z,\Q,\R\in V_{\omega+\omega}\)
    4. for any set \(x\), \(x\in\WF\Leftrightarrow x\subset\WF\)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \(\rank(x)=\alpha\). \(x\in V_{\alpha+1}\setminus V_\alpha\) and \(x\subseteq V_\alpha\).

       by transitivity, \(\bigcup x\subseteq V_\alpha\Rightarrow \bigcup x\in V_{\alpha+1}\subset\WF\). \(\rank(\bigcup x)\le\alpha\)

       suppose
       \(y\in\calp(x)\),
       \(y\subseteq x\Rightarrow y\subseteq V_\alpha\Rightarrow y\in V_{\alpha+1}\). \(\calp(x)\subseteq V_{\alpha+1}\), \(\calp(x)\in V_{\alpha+2}\), \(\rank(\calp(x))\le\alpha+1\).

       \(\{x\}\in\calp(x)\in V_{\alpha+2}\).

    2. Suppose \(\rank(x)=\alpha,\rank(y)=\beta\), \(x\subset V_\alpha\), \(y\subset V_\beta\)

       \(x\cup y\subset V_\alpha\cup V_\beta=V_{\max(\alpha,\beta)}\), \(\rank(x\cup y)\le\max(\alpha,\beta)\)

       \(x\cap y\subset V_{\min(\alpha,\beta)}\)

       \(\{x,y\}\subseteq V_{\alpha+1}\cup V_{\beta+1}=V_{\max(\alpha,\beta)+1}\), \(\rank(\{x,y\})=\max(\alpha,\beta)+1\)

       \((x,y)=\{\{x\},\{x,y\}\}\subset V_{\max(\alpha,\beta)+2}\). \(\rank((x,y))=\max(\alpha,\beta)+2\)

       \(x\times y=\{(a,b)\mid a\in x,b\in y\}\).
       \(a\in x\Rightarrow\rank(a)<\alpha\), \(b\in y\Rightarrow\rank(b)<\beta\), \(\rank(a,b)<\max(\alpha,\beta)+2\),
       \((a,b)\in V_{\max(\alpha,\beta)+2}\). \(x\times y\subseteq V_{\max(\alpha,\beta)+2}\), \(\rank(x\times y)\le\max(\alpha,\beta)+2\).

       \(x^y\subseteq\calp(x\times y)\subseteq V_{\max(\alpha,\beta)+3}\).

    3. \(\N=\omega\in V_{\omega+1}\)

       \(\Z\): let \(\sim\) be an equivalence relation on \(\omega\times\omega\), \((a,b)\sim(c,d)\Leftrightarrow a+d=b+c\),
       then \(\Z=(\omega\times\omega)/\sim\). Hence \(\Z\) is a partition of \(\omega\times\omega\) and
       hence \(\Z\subseteq\calp(\omega\times\omega)\). \(\Z\in V_{\omega+3}\)

       \(\Q\): let \(\sim\) be an equivalence
       on \(\Z\times\Z^+\), \((a,b)\sim(c,d)\Leftrightarrow ad=bc\). \(\Q\subseteq\calp(\Z\times\Z^+)\), \(\Q\in V_{\omega+6}\)

       \(\R\): set of dedekind cut on \(\Q\), \(\R\subset\calp(\Q)\), \(\R\in V_{\omega+8}\)

    4. \(\Rightarrow\): \(\WF\) is transitive

       \(\Leftarrow\): \(x\) is a set and \(x\subset\bigcup_{\alpha\in\On}V_\alpha\).

       *Claim*: there is an ordinal \alpha s.t. \(x\subset V_\alpha\)

       Otherwise, let \(f:\On\to\calp(x)\) s.t. \(f(\alpha)=x\setminus V_\alpha\). Then for any \(y\in\calp(x)\), \(f^{-1}(y)\) is
       a set. \(\On=\bigcup_{y\in x}f^{-1}(y)\) and is thus a set, a contradiction
    #+END_proof

    AC => Any set has cardinality
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume AC (\(V\vDash\ZFC\))
    1. for any group \(G\), there is a group \(G'\) in \(\WF\) s.t. \(G\cong G'\)
    2. for any topological space \(T\), there is a topological space \(T'\) in \(\WF\)
       s.t. \(T\cong T'\) (homeomorphic)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \((G,*_G)\) is a group, \(G,*_G\in V\). By AC, there is a cardinal \alpha
       s.t. \(\abs{G}=\alpha\), that is, there is a bijection \(f:\alpha\to G\). Define \(*\): for
       any \(x,y,z\in\alpha\), \(x*y=z\Leftrightarrow f(x)*_Gf(y)=f(z)\). Then \((\alpha,​*)\cong(G,​*_G)\), \(​*\subseteq\alpha\times\alpha\)
    #+END_proof

    \(V\)中的任何结构都可以在\(\WF\)中找到同构象（同构是在\(V\)里看到的）

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    任意集合\(A\)上的二元关系<是 *良基* 的，当且仅当对\(A\)的任意非空子集\(X\)，\(X\)有<下的极小元
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\in\WF\), then \(\in\) is a well-founded relation on \(A\)
    #+END_theorem

    #+BEGIN_proof
    suppose \(X\subseteq A\), \(X\neq\emptyset\), \(X\subseteq\WF\), then elements of \(X\) has ranks
    and \(x\in y\Rightarrow\rank(x)<\rank(y)\). Let \(x\) having least rank in \(X\), then \(x\) is
    the \(\in\)-minimal element in \(X\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(A\) is a transitive set and \(\in\) is a well-founded relation on \(A\), then \(A\in\WF\)
    #+END_lemma

    #+BEGIN_proof
    Just need to prove \(A\subset\WF\). If \(A\not\subset\WF\), \(X=A\setminus\WF\neq\emptyset\). Then \(X\) has a \(\in\)-minimal
    element \(x\). Then \(x\neq\emptyset\in\WF\). For any \(y\in x\), \(y\in A\). By the minimality
    of \(x\), \(y\in\WF\). Then \(x\subset\WF\), \(x\in\WF\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any set \(x\), there is a minimal transitive set \(\trcl(x)\) s.t. \(x\subseteq\trcl(x)\)
    #+END_lemma

    #+BEGIN_proof
    For any \(n\in\omega\) define \(x_n\)
    \begin{align*}
    x_0&=x\\
    x_{n+1}&=\bigcup x_n
    \end{align*}
    let \(\trcl(x)=\bigcup_{n\in\omega}x_n\).
    1. \(\trcl(x)\)is transitive

       \(a\in\trcl(x)\Rightarrow a\in x_n\Rightarrow a\subseteq x_{n+1}\subseteq\trcl(x)\)
    2. \(\trcl(x)\) is minimal

       If \(y\supseteq x\) is transitive, recursively prove for any \(n<\omega\), \(x_n\subseteq y\).
    #+END_proof

    \(\trcl(x)\) is the *transitive closure* of \(x\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    We can prove the following without axiom of power set
    1. if \(x\) is transitive, \(\trcl(x)=x\)
    2. \(y\in x\Rightarrow\trcl(y)\subseteq\trcl(x)\)
    3. \(\trcl(x)=x\cup\bigcup\{\trcl(y)\mid y\in x\}\)
    #+END_lemma

    #+BEGIN_proof
    2. [@2] \(y\in x\subset\trcl(x)\). \(y\in\trcl(x)\). \(\trcl(y)\subseteq\trcl(x)\).
    3. \(x\cup\bigcup\{\trcl(y)\mid y\in x\}\subseteq\trcl(x)\) by (2)

       \(\bigcup\{\trcl(y)\mid y\in x\}\) is transitive. For \(y\in x\), \(y\subseteq\trcl(y)\). Thus rhs is transitive
    #+END_proof


    #+ATTR_LATEX: :options [In \(\ZFm\)]
    #+BEGIN_theorem
    For any set \(X\), TFAE
    1. \(X\in\WF\)
    2. \(\trcl(X)\in\WF\)
    3. \(\in\) is a well-founded relation on \(\trcl(X)\)
    #+END_theorem

    #+BEGIN_proof
    \(1\to 2\): \(\WF\) is closed under union
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(V\vDash\ZFm\), TFAE
    1. axiom of foundation (\(V\vDash\)) axiom of foundation
    2. for any set \(X\), \(\in\) is a well-founded relation on \(X\)
    3. \(V=\WF\)
    #+END_theorem

    \(V\vDash\ZF\Rightarrow V=\WF(\WF\vDash\ZF)\)

    Goal:  \(V\vDash\ZFm\Rightarrow\WF\vDash\ZFm\)
    但是\(\WF\)是一个类，我们并没有定义

    我们可以用相对化编码\(\WF\vDash\ZFm\)
** 相对化 relativization
    工作在\(\ZFm\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(M\) class, \(\varphi\) formula, \(\varphi\)对\(M\)的 *相对化* \(\varphi^{M}\)
    1. \((x=y)^{M}:=x=y\)
    2. \((x\in y)^{M}:=x\in y\)
    3. \((\varphi\to\psi)^{M}:=\varphi^{M}\to\psi^{M}\)
    4. \((\neg\varphi)^{M}:=\neg\varphi^{M}\)
    5. \((\forall x\varphi)^{M}:=(\forall x\in M)\varphi^{M}\)
    #+END_definition
    \(\varphi^{M}\)读作“\(\varphi\)在\(M\)中为真”，表示为\((M,\in)\subseteq(V,\in)\)有\(M\vDash\varphi\)，即如果\(V\vDash\varphi^{M}\)，那
    么\(M\vDash\varphi\)，而\(V\)知道得更多一点

    重新定义了满足

    若\(M\)被公式\(M(u)\)定义，\((\forall x\varphi)^{M}\)是公式\(\forall x(M(x)\to\varphi^{M}(x))\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(M=\On\)，\(\On\vDash\forall x\forall y(x\in y\vee y\in x\vee x= y)\)
    #+END_examplle

    "\(M\vDash\varphi\)"可以形式化为\(V\vDash\varphi^M\)，而\(M\)对应于\(M(u)\)，即等价于\(T\vdash\varphi^M\)，如果我们工作在某个\(T\)
    上

    若函数\(f\)被公式\(\varphi(\barx,y)\)定义，则\(V\vDash\forall\barx\exists!y\varphi(\barx,y)\)，但相对化后不一定对，因此
    \(f^M=\{(\barx,y)\in M:\varphi^M(\barx,y)\}\)不一定是\(M\)上的函数

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    for any theory \(T\), any class \(M\), \(M\) is a *model* of \(T\), \(M\vDash T\), iff for any axiom
    \varphi of \(T\), \(\varphi^M\) holds, i.e., \(V\vDash\varphi^M\)
    #+END_definition

    \(V\)中定义出语义

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \(V\vDash\ZFm\Rightarrow\WF\vDash\ZF-\Inf\)，

    \(V\vDash(\ZF-\Inf)^{\WF}\)
    等价的
    \(\ZFm\vdash(\ZF-\Inf)^{\WF}\)
    #+END_theorem

    * *存在公理* ：\(\exists x\in M(x=x)\)
    * *外延公理* ：\(\Ext^M\)
      \begin{equation*}
      \forall x\in M\forall y\in M\forall u\in M((u\in X\leftrightarrow u\in Y)\to X=Y)
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) is transitive, then \(\Ext^M\) holds
      #+END_lemma

      #+BEGIN_proof
      suppose \(X,Y\in M\), if \(X\neq Y\), then there is \(u\in X\triangle Y\) (by \(\Ext\) in \(V\)), by
      transitivity, \(u\in M\)
      #+END_proof
    * 分离公理模式：for any \(M\), any formula \varphi, \(S(\varphi)^M\)
      \begin{equation*}
      \forall x\in M\exists Y\in M\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))
      \end{equation*}
      Therefore, if for any \(X\in M\), \(\{u\in X\mid\varphi^M(x)\}\in M\), then 分离公理模式在\(M\)中为真
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) satisfies \(x\in M\Leftrightarrow x\subset M\), then \(S(\varphi)^M\) holds for any \(M\)
      #+END_lemma

      #+BEGIN_proof
      Suppose \(X\in M\), suffices to find corresponding \(Y\in M\) s.t. \(\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\)

      根据\(V\)中的分离公理, \(Y=\{x\in X\mid\varphi^M(u)\}\in V\) and \(Y\subseteq X\subset M\), thus \(Y\in M\) and
      \(\forall u(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\). But \(x\in Y\Rightarrow x\in M\), thus this is equivalent to
      \(\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\)
      #+END_proof
    * *axiom of pairing* Pair
      \begin{equation*}
      \forall x\in M\forall y\in M\exists z\in M\forall u\in M(u\in z\leftrightarrow u= x\vee u=y)
      \end{equation*}
      只要\(M\)对对集函数\(x,y\mapsto\{x,y\}\)封闭，则\(Pair^M\)成立
    * 幂集公理 \(Pow\)
      \begin{equation*}
      \forall X\in M\exists Y\in M\forall u\in M(u\in Y\leftrightarrow\forall a\in M(a\in u\to a\in X))
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) satisfies \(x\in M\Leftrightarrow x\subset M\), then \(Pow^M\) holds
      #+END_lemma

      #+BEGIN_proof
      for any \(X\in M\), \(\calp(X)\in M\). and we prove \(\calp(X)\) is the \(Y\), for any \(u\in M\)
      #+END_proof
    * *axiom of infinity* \(Inf\)
      \begin{equation*}
      \exists X\in M(\emptyset\in X\wedge\forall y\in M(y\in X\to y^+\in X))
      \end{equation*}
      \(\emptyset:\psi(x):=\forall u(u\in x\to u\neq u)\), \(x=\emptyset\Leftrightarrow\psi(x)\)

      \(y^+:\varphi(y,z):\forall u\in z(u=y\vee u\in y)\wedge y\subseteq z\wedge y\in z\)
      函数相对化后不一定是函数，所以放到下一节
    * *axiom of foundation* Fod
      \begin{equation*}
      \forall x\in M(\exists u\in M(u\in x)\to\exists y\in M(y\in x\wedge\neg\exists u\in M(u\in x\wedge u\in y)))
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) is transitive and elements of \(M\) is well-founded under \(\in\), then \(Fod^M\) holds
      #+END_lemma

      #+BEGIN_proof
      suppose \(x_0\in M\) and there is

      \(\psi:=\exists u(u\in x)\) and \(\varphi\) is the latter part

      \(\psi^M(x_0)\leftrightarrow\exists u(u\in x_0)\) since \(M\) is transitive, \(\varphi^M(x_0)\leftrightarrow\exists y(y\in x_0\wedge\neg\exists u\in M(u\in x\wedge u\in y))\)

      在\(V\)中,\(x_0\neq\emptyset\)，由条件可知\((x_0,\in)\)是良基的，于是\(\varphi\)在\(V\)中对，那么当然在\(M\)中对
      #+END_proof
    * *替换公理模式* \(Rep(\varphi)\)
      \begin{equation*}
      \forall A\in M\forall x\in A\cap M\exists !y\in M\varphi^M(x,y)\to\exists B\in M\forall x\in A\exists y\in B\varphi^M(x,y)
      \end{equation*}
      \(\exists!y\theta(y):\exists y(\theta(y)\wedge\forall y'(\theta(y')\to y=y'))\)
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      if \(M\) satisfied \(x\in M\Leftrightarrow x\subset M\), then \(Rep(\varphi)^M\) holds for any \varphi
      #+END_lemma

      #+BEGIN_proof
      for any \(A_0\in M\), then \(A_0\cap M=A_0\), thus we have
      \(\forall x\in A_0\exists!y(\varphi^M(x,y)\wedge M(y))\).

      by \(Rep(\varphi^M(x,y)\wedge M(y))\),
      \(\exists B'\forall x\in A_0\exists y\in B'\varphi^M(x,y)\wedge M(y)\)

      Let \(B=B'\cap M\), which is what we want
      #+END_proof

      Thus in \(\ZFm\), we can prove \(\WF\vDash\ZF-\inf\)
** 绝对性
    \((V,\in)\supseteq(M,\in)\)

    对于哪些\(\varphi\)，有\(V\vDash\varphi\Leftrightarrow M\vDash\varphi\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    公式\(\psi(\barx)\)，对任意类\(M\subseteq N\)，如果
    \begin{equation*}
    \forall\barx\in M(\psi^M(\barx)\leftrightarrow\psi^N(\barx))
    \end{equation*}
    就称\(\psi(\barx)\)对于\(M,N\)是 *绝对的* ，如果\(N=V\)，则称\(\psi(\barx)\)对于\(M\)是 *绝对的*
    #+END_definition

    \(\bara\in M\), \((M,\in)\vDash\psi(\bara)\Leftrightarrow V\vDash\psi^M(\bara)\)

    \(\psi\)相对于\(M,N\)绝对：\(\forall\bara\in M\),有\(M\vDash\psi(\bara)\Leftrightarrow N\vDash\psi(\bara)\)

    if \(\forall\varphi(\barx)\in L\)，均有\(\varphi\)相对于\(M,N\)绝对的，则\(M\preceq N\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    suppose \(M\subseteq N\), \(\varphi,\psi\) formula
    1. 如果\(\varphi,\psi\)相对于\(M,N\)绝对， so are \(\neg\varphi,\varphi\to\psi\)
    2. if \varphi is q.f., then \(\varphi\)对任意\(M\)绝对
    3. if \(M\) are transitive, and \(\varphi\)相对于它们绝对， so is \(\forall x\in y\varphi\)
    #+END_lemma

    #+BEGIN_proof
    3. [@3] \(\forall x\in y\varphi:=\forall x(x\in y\to\varphi(x,y,\barz))\)，故\((\forall x\in y\varphi)^M=\forall x\in M(x\in y\to\varphi^M(x,y,\barz))\)，任取
       \(y_0,\barz_0\in M\),则由\(M\)的传递性，都有\(x\in y_0\Rightarrow x\in M\)

       目标：\(\forall x\in M(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)当且仅当\(\forall x\in N(x\in y_0\to\varphi^N(x,y_0,\barz_0))\)

       由\(\varphi\)的绝对性，对每个\(x_0\in M\)，有
       \begin{equation*}
       \varphi^M(x_0,y_0,\barz_0)\leftrightarrow\varphi^N(x_0,y_0,\barz_0)
       \end{equation*}
       故\(V\vDash\forall x\in M(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)，当且仅当
       \(V\vDash\forall x(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)当且仅当
       \(V\vDash\forall x\in N(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(M\subseteq N\)且\(M\)传递，\(\psi(\barx)\)是一个公式，则
    1. 如果\(\psi\)是\(\Delta_0\)公式，则他它对\(M,N\)是绝对的
    2. 如果\(\psi\)是\(\Sigma_1\)公式，则
       \begin{equation*}
       \forall\barx\in M(\psi^M(\barx)\to\psi^N(\barx))
       \end{equation*}
    3. 如果\(\psi\)是\(\Pi_1\)公式，则
       \begin{equation*}
       \forall\barx\in M^n(\psi^N(\barx)\to\psi^M(\barx))
       \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    1. 对公式的长度进行归纳证明
    2. 例子：令\(M=\On\),\(N=\WF\)，令\(\psi(y):=\forall x\in y\forall u,v\in x(u\in v\vee v\in u\vee u=v)\)，则\(\psi\)是\(\Delta_0\)的，
       则
       \begin{align*}
       &\psi^M(y)=\forall x\in M(x\in y\to\forall u,v\in M(u,v\in x\to(u\in v\vee v\in u\vee u=v)))\\
       &\psi^N(y)=\forall x\in N(x\in y\to\forall u,v\in N(u,v\in x\to(u\in v\vee v\in u\vee u=v)))
       \end{align*}
       任取\(x_0\in\WF\setminus\On\)使得\((x_0,\in)\)不是线序，令\(y_0=\{x_0\}\)，则\(\psi^M(y_0)\)的前件假，
       \(\psi^M(y_0)\)是真的，\(\psi^N(y_0)\)为假，因此
       \begin{equation*}
       \forall\barx(\psi^M(\barx)\to\psi^N(\barx))
       \end{equation*}
       错误

       令\(x=\barx,y=\bary\)

       设\(\psi:=\exists\varphi(x,y)\)，\(\varphi(x,y)\in\Delta_0\), \(\psi^M:=\exists y\in M(\varphi^M(x,y))\), \(\psi^N:=\exists y\in N(\varphi^N(x,y))\)，任取
       \(a\in M^m\)，目标\(\psi^M(a)\to\psi^N(a)\)

       若\(\psi^M(a)\)成立，则有\(b\in M^n\)使得\(\psi^M(a,b)\)，由\(\Delta_0\)的绝对性，\(\psi^N(a,b)\)，因此\(\exists y\psi^N(a,y)\)
    3. 设\(\psi:=\forall y\varphi(x,y)\)其中\(\varphi\in\Delta_0\)，则\(\psi^M:=\forall y\in M\varphi^M(x,y)\)，\(\psi^N:=\forall y\in N\varphi^N(x,y)\)，设\(a\in M\)使
       得\(\psi^N(a)\)成立，目标\(\psi^M(a)\)成立。

       \(\psi^N(a)\Rightarrow\)对所有的\(b\in N\)均有\(\varphi^N(a,b)\)成立，故对一切\(b\in M\)有\(\varphi^N(a,b)\)成立，由\(\varphi\)的绝
       对性，\(\forall y\in M\varphi^M(a,y)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(M\subseteq N\)，均是句子集\(\Sigma\)的模型，而\(\Sigma\vdash\forall\barx(\varphi(\barx)\leftrightarrow\psi(\barx))\)，则\(\varphi\)对\(M\)与\(N\)绝对
    当且仅当\(\psi\)也是
    #+END_lemma

    #+BEGIN_proof
    \(M,N\vDash\forall\barx(\varphi(\barx)\leftrightarrow\psi(\barx))\)

    \(\forall\barx\in M^n(\varphi^M(\barx)\leftrightarrow\psi^M(\barx))\)，\(\forall\barx\in N^n(\varphi^N(\barx)\leftrightarrow\psi^N(\barx))\)

    若\(\varphi\)是绝对的,\(\forall\barx\in M^n(\varphi^M(\barx)\leftrightarrow\varphi^N(\barx))\)

    因此\(\forall\barx\in M^n(\psi^M(\barx)\leftrightarrow\psi^N(\barx))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    假设\(M\subseteq N\)，\(f(x_1,\dots,x_n)\)是函数（类），设\(f(x_1,\dots,x_n)\)被公式\(\varphi(x_1,\dots,x_n,y)\)定义，称\(f\)相对
    于\(M,N\)是绝对的，是指
    1. \(\varphi(x_1,\dots,x_n,y)\)相对于\(M,N\)绝对
    2. \(\forall\barx\in M^n\exists!y\in M(\varphi^N(\barx,y))\)
    #+END_definition

    由上一引理，\(f\)的绝对性与定义\(f\)的公式无关

    \(f^M=\{(x_1,\dots,x_n,y)\in M^{n+1}\mid\varphi^M(\barx,y)\}\),\(f\uhr M=\{(x_1,\dots,x_n,y)\in M^{n+1}\mid\varphi(\barx,y)\}\)

    \(f\)是绝对的当且仅当\(\forall\barx M\forall y\in M(\varphi(\barx,y)\leftrightarrow\varphi^M(\barx,y))\)当且仅当\(\varphi(M^n,M)=\varphi^M(M^n,M)\)，
    即\(f\uhr M=f^M\)

    即对任意\(\bara\in M^n\)，有\(f\uhr M(\bara)=f^M(\bara)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下关系和函数可以在\(\ZFm-\Pow-\Inf\)中用公式定义，且在\(\ZFm-\Pow-\Inf\)下等价于一
    个\(\Delta_0\)-formula
    1. \(x\in y\)
    2. \(x=y\)
    3. \(x\subset y\)
    4. \(\{x,y\}\)
    5. \(\{x\}\)
    6. \((x,y)\)
    7. \(\emptyset\)
    8. \(x\cup y\)
    9. \(x\cap y\)
    10. \(x-y\)
    11. \(x^+=x\cup\{x\}\)
    12. \(x\)传递
    13. \(\bigcup x\)
    14. \(\bigcap x\)，且\(\bigcap\emptyset=\emptyset\)

    #+END_theorem

    #+BEGIN_proof
    4. [@4] 函数\(z=\{x,y\}\)被公式\(\forall u\in z(u=x\vee u=y)\wedge(x\in z\wedge y\in z)\)
    5. \(y=\{x\}\)被公式\(\forall u\in y(u=x)\wedge (x\in y)\)
    6. 函数\(z=(x,y)\)被公式\(\forall u\in z(u=x\vee x=\{x,y\})\wedge x\in z\wedge \exists  u\in z(u=\{x,y\})\)
    7. \(\forall y\in x(y\neq y)\)
    8. 函数\(z=x\cup y\)被公式\(\forall x\subset z\wedge y\subset z\wedge\forall u\in z(u\in x\vee u\in y)\)
    9. 函数\(z=x\cap y\)被公式\(z\subset x\wedge z\subset y\wedge\forall u\in x(u\in y\to u\in z)\)
    10. 函数\(z=x-y\) \(\forall u\in z(u\in x\wedge u\notin y)\wedge \forall u\in x(u\notin y\to u\in z)\)
    11. 函数\(z=x^+\) \(\forall u\in z(u\in x\vee u=x)\wedge x\in z\wedge x\subset z\)
    12. \(\forall y\in x(y\subset x)\)
    13. 函数\(z=\bigcup x\), \(\forall u\in z\exists y\in x(u\in y)\wedge\forall u\in x(u\subset z)\)
    14. 函数\(z=\bigcap x\), \(x=\emptyset\to z=\emptyset\wedge\forall u\in z\forall y\in x(u\in y)\wedge\exists y\in x\forall u\in z(\forall w\in x(u\in w)\to u\in z)\)

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(M\)是一个传递类，\(f\)是一个被\(\Delta_0\)公式定义的函数，如果\(f\)在\(M\)上封闭，
    即\(f(M^n)\subseteq M\),则\(f\)相对于\(M\)绝对
    #+END_lemma

    #+BEGIN_proof
    设\(f\)被\(\varphi(\barx,y)\)定义，\(\forall\barx,y\in M(\varphi(\barx,y)\leftrightarrow\varphi^M(\barx,y))\),\(\forall\barx\in M\exists!y\in M(\varphi(\barx,y))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    之前的函数均在\(\ZFm-\Pow-\Inf\)的传递模型\(M\)中绝对的

    \(\ZFm-\Pow-\Inf\)能够保证函数封闭，传递性保证定义它们的公式的绝对性
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    绝对性对复合运算封闭，即假设\(M\subseteq N\),公式\(\varphi(x_1,\dots,x_n)\)函
    数\(f(x_1,\dots,x_n)\), \(g_i(y_1,\dots,y_m)\),\(1\le i\le n\)都相对于\(M,N\)绝对，则
    \(\varphi(g_1(y_1,\dots,y_m),\dots,g_n(y_1,\dots,y_m))\)与\(f(g_1(y_1,\dots,y_m),\dots,g_n(y_1,\dots,y_m))\)也相对于\(M,N\)绝对
    #+END_lemma

    #+BEGIN_proof
    不妨设\(m=n=1\)

    设\(g(y)=z\)被\(\theta(y,z)\)定义，\(\varphi(g(y)):=\exists z(\theta(y,z)\wedge\varphi(z))\)

    \(\varphi^M(g(y)):=\exists z\in M(\theta^M(y,z)\wedge\varphi^M(z))\),\(\varphi^N(g(y)):=\exists z\in N(\theta^M(y,z)\wedge\varphi^M(z))\)

    由绝对性
    \(\forall z\in M\forall y\in M(\theta^M(y,z)\wedge\varphi^M(z)\leftrightarrow\theta^N(y,z)\wedge\varphi^N(z))\)

    任取\(y_0\in M\)，设\(\exists z\in N(\theta^N(y_0,z)\wedge\varphi^N(z))\)，由函数\(g(y)=z\)的绝对性，
    \(\forall y\in M\exists! z\in M(\theta^N(y,z))\)，存在唯一的\(z_0\in M\)使得
    \(\theta^N(y_0,z_0)\wedge\varphi^N(z_0)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下关系和函数对任意\(\ZFm-\Pow\Inf\)的传递模型\(M\)都是绝对的
    1. \(z\)是有序对
    2. \(A\times B\)
    3. \(R\)是关系
    4. \(\dom(R)\)
    5. \(\ran(R)\)
    6. \(f\)是函数
    7. \(f(x)\)
    8. \(f\)是一一函数
    #+END_theorem

    #+BEGIN_proof
    1. "\(z\)是有序对"：\(\exists u,v(z=(u,v))\)，但是这不是\(\Delta_0\)，因此考虑
       \(\exists u\in\bigcup z\exists v\in\bigcup z(z=(u,v))\)，注意这里不是平常的受囿量词，但是
       令\(g_1(z)=\bigcup z\), \(g_2(z)=\bigcup z\), \(g_3(z)=z\), \(\varphi(x_1,x_2,x_3):=\exists u\in x_1\exists v\in x_2(x_3=(u,v))\)，则
       \(g_1,g_2,g_3,\varphi\)绝对，故\(\varphi(g_1(z),g_2(z),g_3(z))\)绝对
    2. 函数\(z=x\times y\): \(\forall u\in z\exists s\in x\exists t\in y(u=(s,t))\wedge\forall s\in x\forall t\in y\exists u\in z(u=(s,t))\)
    3. \(R\)是关系\(\Leftrightarrow\)\(\forall u\in R(u\text{是有序对})\)
    4. 函数，\(D=\dom(R)\): \(\forall x\in D\exists z\in R\exists u\in z\exists y\in u(z=(x,y))\)且
       \(\forall z\in R\forall u\in z\forall x\in u\forall y\in u(z=(x,y)\to x\in D)\)
    5. 同理
    6. \(f\text{是关系}\wedge\forall x\in\dom(f)\exists!y\in\ran(f)\exists u\in f(u=(x,y))\)
    7. \(\varphi(f(x))\)表示\(f\)是函数且\(x\in\dom(f)\),则"\(y=f(x)\)"定义为
       \(\varphi(f,x)\to\exists u\in f(u=x,y)\vee(\neg\varphi(f,x)\to y\neq\emptyset)\)
    8. "\(f\)是函数"且\(\forall s\in\dom(f)\forall t\in\dom(f)(f(s)=f(t)\to s=t)\)
    #+END_proof
** 基础公理的相对一致性
    如果\(\ZFm\)一致，则\(\ZF\)一致

    目标：\(V\vDash\ZFm\)，证明\(\WF\vDash\ZF\)，等价于\(\ZFm\vdash(\ZF)^{\WF}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若传递类\(M\)是\(\ZFm-\Pow-\Inf\)的模型，且\(\omega\in M\)，则无穷公理在\(M\)中为真，因此无穷公理
    在\(\WF\)中为真（\(\ZFm\vdash(\Inf)^{\WF}\)）
    #+END_lemma

    #+BEGIN_proof
    - 由于\(\emptyset\)与\(x^+\)都被\(\Delta_0\)公式定义
    - 若\(M\vDash\ZFm-\Pow-\Inf\)，则\(x^+\)在\(M\)中封闭，且\(\emptyset\in M\)
    - \(\emptyset^M=\emptyset\), \((x^+)^M=x^+\)
    - 无穷公理的相对化为\(\exists x\in M(\emptyset\in x\wedge\forall y\in x(y^+\in x))\)
    - 即\(\exists x\in M(\emptyset\in M\wedge\forall y\in x(y^+\in x))\)
    - 由于\(\omega\in M\)，令\(x=\omega\)
    #+END_proof

    结论： \(\WF\vDash\ZF\)


    目标：\(Con(\ZFm)\vdash Con(ZF)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    设\(T\) (\(\ZFm\))是集合论的的理论，\(\Sigma\) (\(\ZF\))是一个句子集， 设\(M\)是一个类且非空，如
    果\(T\vdash(M\vDash\Sigma)\)，即\(T\vdash\Sigma^M\)或者“若\(V\vDash T\)，则\(V\vDash\Sigma^M\)”，则
    1. 对集合论语言的任何语句\(\varphi\)，如果\(\Sigma\vdash\varphi\)，则\(T\vdash\varphi^M\)
    2. 如果\(T\)一致，则以\(\Sigma\)为公理的理论也一致
    #+END_theorem

    #+BEGIN_proof
    1. 设\(\varphi_1,\dots,\varphi_n=\varphi\)是\(\Sigma\)的一个证明，对\(k\le n\)，归纳证明\(T\vdash\varphi_k^M\)
       - 若\(\varphi_i\in\Sigma\cup Ax\),\(Ax\)一阶逻辑的公理，\(T\vdash\varphi_i^M\)
       - 若\(i,j<k\)使得\(\varphi_j=\varphi_k\to\varphi_k\)，由归纳假设\(T\vdash\varphi_i^M\), \(T\vdash\varphi_i^M\to\varphi_k^M\),因此\(T\vdash\varphi_k^M\)
    2. 若\(\Sigma\)不一致，则存在\(\varphi\)使得\(\Sigma\vdash\varphi\wedge\neg\varphi\)，从而\(T\vdash(\varphi\wedge\neg\varphi)^M\)，故\(T\)不一致
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    基础公理相对于\(\ZFm\)一致，即如果\(\ZFm\)一致，则\(\ZF\)一致
    #+END_theorem

    #+BEGIN_proof
    - \(\ZFm\vdash(\ZF)^{\WF}\)
    - 故\(\ZFm\)一致能推出\(\ZF\)一致
    #+END_proof

    选择公理：任何非空集合都可被良序化
    \(\forall X\exists R(R\text{是$X$上的良序})\)
    1. \(R\subseteq X\times X\)
    2. \(R\)是线序
    3. \(\forall Y\subseteq X\), \(Y\neq\emptyset\Rightarrow \)Y存在\(R\)-极小元


    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_lemma
    设\(M\)是\(\ZFm-\Pow-\Inf\)的传递模型，如果\(X,R\in M\)并且\(R\)是\(X\)上的一个良序，
    则\((R\text{是$X$的良序})^M\)
    #+END_lemma

    #+BEGIN_proof
    “\(R\)是\(X\)上的线序”被公式\(\varphi(X,R)\)表达
    - \(R\)是关系
    - \(\forall x\in X(\neg R(x,x))\)
    - \(\forall x,y,z\in X(R(x,y)\wedge R(y,z))\to R(x,z)\)
    - \(\forall x,y\in X(R(x,y)\vee R(y,x)\vee x=y)\)

      \(R(x,y)\)表示\((x,y)\in R\),\(\exists z\in R(z=(x,y))\)


    因此\(\varphi(X,R)\)是\(\Delta_0\)-公式

    令公式\(\psi(X,Y,R)\)为\(Y\subseteq X\wedge Y\neq\emptyset\to\exists y\in Y\forall x\in Y(\neg R(x,y))\)，则\(\psi(X,Y,R)\)是\(\Delta_0\)-公式，
    “\(R\)是\(X\)上的良序”可以表达为\(\theta(X,Y)=\varphi(X,R)\wedge\forall Y\psi(X,Y,R)\)

    则\(\theta\)是一个\(\Pi_1\)-公式

    \(\forall X\in  M\forall R\in M(\theta(X,R)\to\theta^M(X,R))\)，任取\(X_0,R_0\in M\)使得\(R_0\)是\(X_0\)上的良序，
    则\(\theta(X_0,R_0)\)，故\(\theta^M(X_0,R_0)\)也成立，即
    #+END_proof

    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_theorem
    \(V_\omega\)是\(\ZFC-\Inf+\neg\Inf\)的模型
    #+END_theorem

    #+BEGIN_proof
    与\(\WF\)类似，\(V_\omega\)是传递的，且关于\(\{x,y\}\),\(\bigcup x\),\(\calp(x)\)封闭，故而是\(\ZF-\Inf\)的模型
    （练习）

    \(\neg\Inf\): \(\forall x\neg(\emptyset\in X)\wedge\forall y\in x(y^+\in x)\)

    \(\neg\Inf^M\): \(\forall x\in M(\emptyset^M\in X\wedge\forall y\in x((y^+)^M\in x))\)

    由于\(M=V_\omega\)传递，故\((\neg\Inf)^M\): \(\forall x\in M(\emptyset\in X\wedge\forall y\in x(y^+\in x))\)

    由于\(V_\omega\)中没有无穷集，故\((\neg\Inf)^M\)在\(V\)中成立

    \(AC^M\):任取\(X\in V_\omega\),若\(X\neq\emptyset\)，存在\(R\in V_\omega\)使得\(R\)是\(X\)上的良序

    \(\rank(\calp(x\times y))<\max(\rank(x),\rank(y))\)，故
    \(\calp(x\times x)\in V_\omega\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(Con(\ZFm)\vdash Con(\ZFC-\Inf+\neg\Inf)\)
    #+END_corollary
** 基于良基关系的归纳与递归
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    类\(R\)（\(\varphi(x,y)\)）是类\(X\)（\(\psi(x)\)）上的良基关系当且仅当
    \begin{equation*}
    \forall U\subset X(U\neq\emptyset\to\exists y\in U(\neg\exists z\in U(zRy)))
    \end{equation*}
    \(U\)是集合
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\in\)是\(\On\)上的良基关系

    如果\(Fud\)成立，则\(\in\)是\(V\)上的良基关系
    #+END_examplle

    #+ATTR_LATEX: :options [超穷归纳原理]
    #+BEGIN_theorem
    设\(\varphi(x)\)是一个公式，若\(\forall\alpha\in On\)有\(\forall\beta(\beta<\alpha\to\varphi(\beta))\to\varphi(\alpha)\)，则\(\forall\alpha\in\On(\varphi(\alpha))\)
    #+END_theorem

    #+ATTR_LATEX: :options [超穷递归定理]
    #+BEGIN_theorem
    设\(G:V\to V\)的函数，则存在唯一的函数\(F:\On\to V\)使得
    \begin{equation*}
    F(\alpha)=G(F\uhr\alpha)
    \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    类\(X\)上的关系，类\(R\)是 *似集合* 的当且仅当对任意\(x\in X\)，有\(\{y\in X\mid yRx\}\)是一个集合
    #+END_definition

    类的元素一定是集合，因为类是集合宇宙的一个子区域

    一般称\(\{y\in X\mid yRx\}\)中的元素为\(x\)的前驱，\(\in\)是任何类\(X\)上的似集合关系

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    如果\(R\)是\(X\)上的似集合关系，且\(x\in X\)，则递归定义
    - \(\pred^0(X,x,R)=\{y\in X\mid yRx\}\)
    - \(\pred^{n+1}(X,x,R)=\bigcup\{\pred(X,y,R)\mid y\in\pred^n(X,x,R)\}\)
    - \(\cl(X,x,R)=\bigcup_{n\in\omega}\pred^n(X,x,R)\)
    #+END_definition

    对每个\(n\),\(\pred^n(X,x,R)\)是集合

    故\(\cl(X,x,R)\)是集合

    若\(R\)是\(\in\)，且\(X\)是传递的，则\(\cl(X,x,R)=x\)


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(R\)是\(X\)上的似集合关系，则对任意\(y\in\cl(X,x,R)\)，都有\(\pred(X,y,R)\subseteq\cl(X,x,R)\)
    #+END_lemma

    #+BEGIN_proof
    设\(y\in\cl(X,x,R)\)，则存在\(n\in\omega\)使得\(y\in\pred^n(X,x,R)\)，故\(\pred(X,y,R)\subseteq\pred^{n+1}(X,x,R)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(R\)是\(X\)上的良基关系， 且是似集合的，则\(X\)的每个非空子类\(Y\)都有\(R\)-极小元
    #+END_theorem

    #+BEGIN_proof
    任取\(x\in Y\)，若\(x\)不是\(Y\)的\(R\)-极小元，则\(\pred(X,x,R)\cap Y\)非空，于是\(Y\cap\cl(X,x,R)\)非
    空，令\(x_0\in Y\cap\cl(X,x,R)\)为极小元，则\(x_0\)是\(Y\)的极小元，否则\(\pred(X,x_0,R)\cap Y=\emptyset\)，任
    取\(z_0\in\pred(X,x_0,R)\cap Y\)，则\(z_0\in Y\), \(z_0\in\cl(X,x,R)\)，于是\(z_0\in Y\cap\cl(X,x,R)\)
    且\(z_0Rx_0\)，与\(x_0\)的极小性矛盾
    #+END_proof

    #+BEGIN_remark
    假设基础公理，则\(\in\)是\(V\)上的良基关系，若\(V\neq\WF\)，则\(V\setminus\WF\)有极小元\(x_0\)非空，但
    是\(\forall y\in x_0(y\in\WF)\)，于是\(x_0\subset\WF\)，矛盾，因此\(V=\WF\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    设\(R\)是\(X\)上的似集合的良基关系，如果\(F:X\times V\to V\)是“函数”，则存在唯一的“函数”\(G:X\to V\)使得
    \(\forall x\in X(G(x)=F(x, G\uhr\pred(X,x,R)))\)
    #+END_theorem

    练习
    #+BEGIN_proof
    1. 存在性

       令公式\(\theta(x,t)\)表示
       - \(t\)是一个函数（集合）
       - \(\dom(t)=\{x\}\cup\pred(X,x,R)\)
       - \(\forall y\in\dom(t)(t(y)=F(y,t\uhr\pred(X,y,R)))\)
       - \(\forall y\notin\dom(t)(t=\emptyset\)
       令\(G=\{(x,y)\mid\theta(x,y)\}\)，证明\(G\)是函数：


    2. 唯一性

       若不唯一，则存在最小的\(x\in X\)使得\(G(x)\neq G(x')\). 但是\(G(x)=F(x,G\uhr(X,x,R))=F(x,G'\uhr(X,x,R))=G'(x)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    如果\(R\)是\(X\)上的似集合关系，设\(x\in X\)，则定义
    \begin{equation*}
    \rank(x,X,R)=\sup\{\rank(y,X,R)+1\mid yRx\wedge y\in X\}
    \end{equation*}
    (来自超穷递归)
    #+END_definition

    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_definition
    如果类\(X\)传递，且\(\in\)是\(X\)上的良基关系，则\(X\subseteq\WF\)且对任意\(x\in X\)有\(\rank(x,X,\in)=\rank(x)\)
    #+END_definition

    #+BEGIN_proof
    若\(X\not\subseteq\WF\), 取极小元\(x_0\in X\setminus\WF\)，显然\(x_0\neq\emptyset\)。任取\(z\in x_0\)，由传递性，有\(z\in X\cap\WF\)，
    于是\(x_0\subseteq\WF\)，于是\(X\subseteq\WF\)

    令\(Y=\{x\in X\mid\rank(x,X,\in)\neq\rank(x)\}\)，如果\(Y\)非空，令\(x_0\)为\(Y\)的极小元，根据传递
    性,\(x_0\subseteq X\)，且\(\forall z\in x_0\),\(\rank(z,X,\in)=\rank(z)\)

    \(\rank(x_0,X,\in)=\sup\{\rank(z,X,\in)+1\mid z\in x_0\}\)

    \(\rank(x_0)=\sup\{\rank(z)+1\mid z\in x_0\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    令类\(R\)是\(X\)上似集合的良基关系，则\((X,R)\)上的 *mostowski函数* \(G\)定义为
    \begin{equation*}
    G(x)=\{G(y)\mid y\in X\wedge yRx\}
    \end{equation*}

    \(G\)的值域记作\(M\)，称之为\((X,R)\)的 *Mostowski坍塌*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(R\)是\(X\)上的一个似集合的良基关系，\(G\)是其上的Mostowski函数，\(M\)为其Mostowski坍塌，则
    1. \(\forall x,y\in X(xRy\to G(x)\in G(y))\), \(G:(X,R)\to(V,\in)\)同态
    2. \(M\)是传递集
    3. 如果幂集公理成立，则\(M\subseteq\WF\) (\(\ZFm-\Pow-\Inf\))
    4. 如果幂集公理成立，且\(x\in X\)，则\(\rank(x,X,R)=\rank(G(x))\)
    #+END_lemma

    #+BEGIN_proof
    3. [@3] 断言：\((M,\in)\)是良基的

       任取\(Y\subseteq M\)非空，则\(G^{-1}(Y)\subseteq X\)非空，有极小元\(x_0\)，若\(G(x_0)\)不是\(Y\)的极小元，
       则\(G(x_0)\cap Y\neq\emptyset\)。令\(z\in G(x_0)\cap Y\)，则存在\(y\in G^{-1}(Y)\)使得\(G(y)=z\)且\(yRx_0\)，
       与\(x_0\)极小矛盾
    4. 设\(x\in X\), \(\rank(G(x))=\sup\{\rank(v)+1\mid v\in G(x)\}=\sup\{\rank(G(y))+1\mid y\in X\wedge yRx\}\)

       设\(x_0\)是使得等式不成立的极小元，则对任意\(y\in X\), \(yRx_0\to\rank(y,X,R)=\rank(G(y))\)

       \(\rank(x,X,R)=\sup\{\rank(y,X,R)+1\mid yRx\wedge y\in X\}=\sup\{\rank(G(y))+1\mid yRx\wedge y\in X\}=\rank(G(x))\)
    #+END_proof

    那么\(G\)在什么条件下是个同构

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(R\)是\(X\)上的 *外延* 的关系当且仅当
    \begin{equation*}
    \forall x,y\in X(\forall z\in X(zRx\leftrightarrow zRy)\to x=y)
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(X\)是传递的，则\(\in\)在\(X\)上是外延的
    #+END_lemma

    #+BEGIN_proof
    \(\pred(X,x,\in)=x\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(R\)是\(X\)上的似集合良基关系，如果\(R\)在\(X\)上是外延的，则\(G\)是同构
    #+END_lemma

    #+BEGIN_proof
    若\(G\)不是单射，即\(Y=\{x\in X\mid\exists y\in X(x\neq y\wedge G(x)=G(y))\}\)非空，则有极小元\(x_0\)，取极小
    的\(y_0\in Y\)使得\(x_0\neq y_0\)且\(G(x_0)=G(y_0)\)，存在\(z_0\in X\)使得\(\neg(z_0Rx_0\leftrightarrow z_0Ry_0)\)

    若\(z_0Rx_0\)，\(\neg z_0Ry_0\)，则\(G(z_0)\in G(x_0)\), \(G(z_0)\notin G(y_0)\)
    #+END_proof

    #+ATTR_LATEX: :options [莫斯托夫斯基坍塌定理]
    #+BEGIN_theorem
    令\(R\)是\(X\)上的似集合良基关系，并且在\(X\)上是外延的，则存在传递类\(M\)和双射\(G\)满
    足\(G:X\to M\)满足：\(G\)是\((X,R)\)与\((M,\in)\)之间的同构。另外\(M\)和\(G\)唯一
    #+END_theorem

** 基础公理的绝对性
    已知\(\ZFm\)一致\(\Rightarrow\)\(\ZF\)一致

    本节工作于\(\ZF\)中

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下关系和函数可以在\(\ZF-\Pow\)中用公式定义，且\(\ZF-\Pow\)可以证明这些公式等价于\(\Delta_0\)公式，
    所以它们对任意\(\ZF-\Pow\)的传递模型绝对
    1. \(x\)是序数
    2. \(x\)是极限序数
    3. \(x\)是后继序数
    4. \(\omega\)
    5. \(x\)是有穷序数
    6. \(0,1,2,\dots,20,\dots\)
    #+END_theorem

    #+BEGIN_proof
    1. \(\in\)良基

       \(x\)是序数\(\Leftrightarrow\)\(x\)是传递集且\(\in\)是\(x\)上的线序

       即\(\forall y\in x(y\subset x)\wedge\forall y,z\in x(y\in z\vee y=z\vee z\in y)\)

    2. 令\(\psi(x)\)为“\(x\)是序数”且\(\forall y\in x\exists z\in x(y\in z)\)

    4. [@4] 令\(\psi(x)\)为“\(x\)是极限序数”且\(\emptyset\in x\)且\(\forall y\in x(y\text{ is limit}\to y=\emptyset)\)

    5. 令\(\psi(x)\)为 “\(x\)是序数”且\(x\neq\omega\)且\(\forall y\in x(y\neq\omega)\)

    6. 归纳证明：\(\emptyset\): \(\forall y\in x(y\neq y)\) \(\psi_0(x)\)

       假设\(n\)被\(\psi_n(x)\)定义，则\(\psi_{n+1}(x):\exists y\in x(\psi_n(y)\wedge x=y^+)\)
    #+END_proof

    #+BEGIN_remark
    令\(\psi_{limit}(x)\)定义极限序数，即使\(V\vDash\neg\Inf\)，\(\psi_{limit}(x)\)相对于\(\ZF-\Pow+\neg\Inf\)的传递
    模型\(M\)仍然是绝对的，此时，\(V\vDash\forall x(\psi_{limit}(x)\to x=\emptyset)\)

    同理定义\(\omega\)的\(\psi_\omega(x)\)也是绝对的，此时
    \(V\vDash\neg\exists(\psi_\omega(x))\)

    若\(V\)和\(M\)均满足\(\Inf\)，则\(\omega\in M\)且\(\psi_\omega(\omega)\leftrightarrow\psi_\omega^M(\omega)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(M\)是\(\ZFm-\Pow\)的传递模型，则\(M\)的所有有穷子集都是\(M\)的元素
    #+END_lemma

    #+BEGIN_proof
    令\(\sigma_n\)为
    \begin{equation*}
    \forall x\subset M(\abs{x}=n\to x\in M)
    \end{equation*}
    \(V\)看到的
    1. \(\sigma_0\),\(V\vDash(\ZF-\Pow)^{M}\)，由于\(\ZF-\Pow\vdash\exists x(x=\emptyset)\)，故\(V\vDash\exists x\in M(x=\emptyset^M)\)，而空集是一个绝对
       概念，因此\(V\vDash\exists x\in M(x=\emptyset)\)
    2. 假设\(\sigma_n\)成立，任取\(x\subset M\) s.t. \(\abs{x}=n+1\),任取\(y\in x\)，则\(y\in M\)，
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下概念对\(\ZF-\Pow\)的任何传递模型都是绝对的
    1. \(x\)是有穷的
    2. \(X^n\)
    3. \(X^{<\omega}\)即\(X\)上所有有穷序列的集合
    #+END_theorem

    #+BEGIN_proof
    1. 令\(\psi(x,f)\)表示“\(f\)是函数”且\(\dom(f)=x\)且\(\ran(f)\in\omega\)且"\(f\)是一一的"

       显然\(\psi(x,f)\)是绝对的，\(x\)有穷\(\Leftrightarrow\)\(\exists f\psi(x,f)\)

       目标：\(\forall x\in M(x\text{ finite}\leftrightarrow(x\text{ finite})^M)\)，即
       \(\forall x\in M(\exists f\psi(x,f)\leftrightarrow\exists f\in M\psi(x,f))\)

       任取\(x_0\in M\)，若存在\(f_0\in M\)使得\(\psi^M(x_0,f_0)\)成立，则\(\psi(x_0,f_0)\)成立，

       若存在\(f\)使得\(\psi(x_0,f)\)成立，下面证明\(f_0\in M\)。存在\(n\in\omega\)使得\(f_0:x\to n\)是一一的函数，
       \(f_0\subseteq x_0\times n\)是有穷集

       \(n\)与\(x_0\)均属于\(M\),故\(x_0\times n\in M\)，故\(x_0\times\subset M\),故\(f_0\subseteq M\)是有穷子集，

    2. \(X^n\)是\(n\)到\(X\)的所有函数的集合

       令\(f:n\to X\)表示“\(f\)是函数”且\(\dom(f)=n\)且\(\ran(f)\subseteq X\)

       \(f\)是绝对的，于是\(\forall f,n,X\in M((f:n\to X)\leftrightarrow(f:n\to X)^M)\)

       定义函数
       \begin{equation*}
       F(X,n)=
       \begin{cases}
       0&n\notin\omega\\
       \{f\mid f:n\to x\}&n\in\omega
       \end{cases}
       \end{equation*}
       \(Z=F(X,n)\)被公式\(\psi(X,n,z)\)表示：\((n\notin\omega\to z=0)\wedge(n\in\omega\to z=\{f\mid f:n\to x\})\)

       下面证明\(\psi\)的绝对性，只需证明\(\forall n\in\omega\)以及\(X_0,Z_0\in M\)，有
       \begin{equation*}
       \forall y\in Z_0(y:n\to X_0)\wedge\forall f((f:n\to X_0)\to f\in Z_0)
       \end{equation*}
       唯一的障碍是\(\forall f\)，但是因为当\(n,X_0\in M\)且\(f:n\to X_0\)，则\(f\)是\(M\)的有穷子集

       故\(\psi(X,n,Z)\)是绝对的

       下面验证, \(X^n\subseteq\calp(n\times X)\in M\)
       \begin{equation*}
       V\vDash\forall X\in M\forall n\in M\exists!Z\in M\psi(X,n,Z)
       \end{equation*}
       任取\(X\in M\)，若\(n\notin\omega\)，则\(F(X,n)=\emptyset\in M\)，若\(n\in\omega\)，定义
       \(\theta_n(x,y)\)为
       \begin{equation*}
       \exists a_0\dots a_{n-1}(x=(a_0,\dots,a_{n-1})\wedge y=\{(0,a_0),\dots,(n-1,a_{n-1})\})
       \end{equation*}
       令\([X^n]\)表示\(n\)次笛卡儿积，显然\([X^n]\in M\)

       \(\forall x\in[X^n]\exists!y\in M\theta_n^M(x,y)\)

       由于\(M\)满足替换公理，故存在\(z\in M, X^n\subseteq z\)

       根据分离公理
       \begin{equation*}
       V\vDash\exists u\in M\forall f\in M(f\in u\leftrightarrow f\in z\wedge(f:n\to x))
       \end{equation*}
       故\(u=X^n\in M\)

    3. 先证明封闭，再证明绝对

       首先证明函数\(Z=X^{<\omega}\)是绝对的

       令\(F(x,n)=X^n\)，则\(Z=\bigcup\{F(x,0),F(x,1),\dots\}=\bigcup\ran(F(x,-))\uhr\omega\)

       由于\(\omega\in M\)，于是\(\ran(F(x,-)\uhr\omega)\in M\)，由并集公理,\(\bigcup\ran(F(x,-)\uhr\omega)\in M\)

       即\(x\in M\Rightarrow X^{<\omega}\in M\)

       \(Z=X^{<\omega}\)被公式\(\varphi(x,z)\)定义：\(\forall f(f\in z\leftrightarrow\exists n(n\text{ fintie ordinal}\wedge f\in X^n))\)

       验证：\(\forall x\in M\forall z\in M(\varphi(x,z)\leftrightarrow\varphi^M(x,z))\)

       \(V\)看到所有有穷序数都在\(M\)中

       于是\(\varphi\)绝对，\(\forall x\in M\exists!z\in M\varphi(x,z)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下概念对\(\ZFm-\Pow\)的任何传递模型都是绝对的
    1. \(R\)是\(X\)上的良序（集合）
    2. \(\type(x,R)\)
    #+END_theorem

    #+BEGIN_proof
    1. 已证明：\(\forall R\in M\forall x\in M(R\text{是$X$的良序}\to(\text{$R$是$X$的良序})^M)\)

       另一方面，\(\ZF-\Pow\vdash\forall R\forall X[R\text{是$X$的良序}\to\exists\alpha\exists f(\alpha\text{ ordinal}\wedge f:(\alpha,\in)\cong(X,R)]\)

       后面的部分是绝对的

       同时这个也有\(M\)的相对化
       \((\ZF-\Pow)^M\vdash\forall R\in M\forall X\in M[(R\text{是$X$的良序})^M\to\exists\alpha\in M\exists f\in M(\alpha\text{ ordinal}\wedge f:(\alpha,\in)\cong(X,R)]\)

       若\(R_0,X_0\in M\)且\((R_0\text{是$X_0$的良序})^M\)，则存在\(\alpha\in M\), \(f\in M\),\(f:(\alpha,\in)\cong(X_0,R_0)\)，
       因此\(V\vDash R_0\text{是$X_0$的良序}\)
    2. 令\(W(X,R)\)表示\(R\)是\(X\)的良序，令\(\chi(X,R,Z)\)表示\(Z\)是序数且\(W(X,R)\)
       且\(\exists f:(Z,\in)\cong(X,R)\)

       则\(Z=\type(X,R)\Leftrightarrow\chi(X,R,Z)\)，而\(\chi\)是绝对（这里的问题是\(\exists f\)，要证明\(f\)一定在\(M\)中，参
       考良序绝对性的证明）的
       且\(\forall X,R\in M\exists!Z\in M\chi(X,R,Z)\) (练习)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下概念对\(\ZF-\Pow\)的任何传递模型都是绝对的
    1. \(\alpha+1\)
    2. \(\alpha-1\)
    3. \(\alpha+\beta\)
    4. \(\alpha\cdot\beta\)
    #+END_theorem

    #+BEGIN_proof
    2. [@2] \(x=\alpha-1\)被
       \begin{equation*}
       \alpha\neq 0\wedge((\alpha\text{后继}\wedge\alpha=x+1)\vee(\alpha\text{极限}\wedge\alpha=x))
       \end{equation*}
    3. 没有递归定义的绝对性

       \(\alpha+\beta\)的定义为\(\type(\alpha\oplus\beta)\)

       由于\(\type(-,-)\)是绝对的，只需证明\(\alpha\oplus\beta\)是绝对的

       令\(F(\alpha\oplus\beta)=W\)，其中\(W=\{\alpha\times\{0\}\cup\beta\times\{1\}\}\)，再令\(G(\alpha\oplus\beta)=R\)，其中\(R\subseteq W^2\)且满足
       \(\forall x\in\alpha\times\{0\}\forall y\in\beta\times\{1\}(xRy)\)且\(\forall x,y\in\alpha((x,0)R(y,0)\leftrightarrow x\in y)\)
       且\(\forall x,y\in\beta((x,1)R(y,1)\leftrightarrow x\in y)\)

       显然\(R\)是\(W\)的良序集

       \(F\)是绝对的

       令\(\psi(\alpha,\beta,R)\)为
       \begin{align*}
       \forall x\in R[&\exists a\in\alpha\exists b\in\alpha(a\in b\wedge x=((a,0),(b,0)))\\
       &\vee\exists a\in\beta\exists b\in\beta(a\in b\wedge x=((a,1),(b,1)))\\
       &\vee\exists a\in\alpha\exists b\in\beta(x=((a,0),(b,1)))]\\
       \wedge\forall a,b\in\alpha&\exists x\in R(x=((a,0),(b,0)))\\
       \wedge\forall a,b\in\beta&\exists x\in R(x=((a,1),(b,1)))\\
       \wedge\forall a\in\alpha&\forall b\in\beta\exists x\in R(x=((a,0),(b,1)))
       \end{align*}
       用\(\theta(\alpha,\beta,x)\)表示方括号，则\(V\vDash\forall z(z\in R\leftrightarrow\theta(\alpha,\beta,z))\)

       于是\(G(\alpha,\beta)=R\Leftrightarrow\psi(\alpha,\beta,R)\)

       \(\psi,\theta\)是绝对的

       若\(\alpha,\beta\in M\)，则\(\{x\mid\theta(\alpha,\beta,x)\}=\{x\in M\mid\theta(\alpha,\beta,x)\}=\{x\in M\mid\theta^M(\alpha,\beta,x)\}\subseteq M\),
       \(R=\{x\in W^2\mid\theta^M(\alpha,\beta,x)\}\)，由分离公理，\(R\in M\)

       故\(G(\alpha,\beta)=R\)是绝对的，

       \(\alpha+\beta=\type(F(\alpha,\beta),G(\alpha,\beta))\)是绝对的
    4. 同理：\(\alpha\cdot\beta=\type(\alpha\otimes\beta)\)是绝对的
    #+END_proof

    设\(X\)是一个类，被公式\(X(x)\)定义，称\(X\)绝对是指\(\forall x\in M(X(x)\leftrightarrow X^M(x))\)

    令\(X^M\)表示\(\{x\in M\mid x^M(x)\}\)，\(X\)对于\(M\)绝对\(\Leftrightarrow\) \(X^M=X\cap M\)

    若\(M\)是\(ZF-\Pow\)的传递模型，则\(\On^M=M\cap\On\)

    作为函数的类，\(G:X\to Y\)其中\(X,Y\)是类，是一个公式\(G(x,y)\)满足函数的条件

    称\(G\)相对于类\(M\)是绝对的是指
    1. \(\forall x\in X^M\exists!y\in Y^MG^M(x,y)\)，即\(G^M:X^M\to Y^M\)
    2. \(\forall x\in M\forall y\in M(G^M(x,y)\leftrightarrow G(x,y))\)


    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    设\(R\)是\(X\)的似集合的良基关系，\(F:X\times V\to V\)，令\(G:X\to V\)如递归定理所定义的：
    \begin{equation*}
    \forall x\in X(G(x)=F(x,G\uhr\pred(X,x,R)))
    \end{equation*}
    令\(M\)是\(ZF-\Pow\)的传递模型，且假设
    1. \(F\)相对于\(M\)绝对的
    2. \(X,R\)相对于\(M\)是绝对的
    3. \((R\text{在$X$上是似集合的})^M\)
    4. \(\forall x\in M(\pred(X,x,R)\subseteq M)\)
    则\(G\)对\(M\)是绝对的
    #+END_theorem

    #+BEGIN_proof
    阅读书中证明

    \(V\vDash(X^M=X\cap M)\)

    \(V\vDash(R^M=R\cap(M\times M))\)

    \(V\vDash R^M=(X^M)^2\cap R\)

    \(V\vDash(X^M,R^M)\)是良基的


    \(R\)在\(X\)上是似集合的，\(\forall x\in X\exists z\forall y\in X(y\in z\leftrightarrow yRx)\)，它的相对化就是
    \(\forall x\in X^M\exists z\in M\forall y\in X^M(y\in z\leftrightarrow yR^Mx)\)

    故\((X^M,R^M)\)是似集合的且\(\forall x\in M(\pred(X^M,x,R^M)\in M)\)

    由\(X\)与\(R\)的绝对性，\(\pred(X^M,x,R^M)=\pred(X,x,R)\cap M\)

    由于\(\forall x\in M(\pred(X,x,R))\subseteq M\)，故\(\forall x\in M(\pred(X^M,x,R^M)=\pred(X,x,R))\)

    *断言1* ：函数\(y=\pred(X,x,R)\)是绝对的

    \(y=\pred(X,x,R)\)被公式\(\psi(x,y)\)表示：
    \begin{equation*}
    \forall z(z\in y\leftrightarrow z\in X\wedge zRx)
    \end{equation*}
    则\(\psi^M(x,y)\)为
    \begin{equation*}
    \forall z\in M(z\in y\leftrightarrow z\in X^M\wedge zR^Mx)
    \end{equation*}
    若\(x_0,y_n\in M\)，有\(z\in y_0\to z\in M\), \(zRx_0\to z\in M\)

    故\(\psi\)绝对，由以上分析，若\(x\in M\)，则\(\pred(X,x,R)\in M\)。故\(y=\pred(X,x,R)\)是作为函数是绝对的

    对任意的\(x\in M\)，有\((\pred(X,x,R))^M=\pred(X,x,R)=\pred(X^m,x,R^M)\)

    先在\((X^M,R^M)\)是似集合的的良基关系，由绝对性，\(F^M:X^M\times M\to M\)，这些都是\(V\)看到的，那么由递归
    定理，存在函数\(g:X^M\to V\)满足
    \begin{equation*}
    \forall x\in X^M(g(x)=F^M(x,g\uhr\pred(X^M,x,R^M)))
    \end{equation*}
    目标：证明\(g=G^M\)（书本）

    问题：递归定理中的"\(G\)"只刻画了\(G\)的性质并非定义（元语言）

    回亿：\(G(x)\)的定义
    令公式\(\theta(x,t)\)表示
    - \(t\)是一个函数（集合）
    - \(x\in X\)
    - \(\dom(t)=\{x\}\cup\pred(X,x,R)\)
    - \(\forall y\in\dom(t)(t(y)=F(y,t\uhr\pred(X,y,R)))\)
    - \(\forall y\notin\dom(t)(t=\emptyset)\)
    则\(G(x)=y\Leftrightarrow\)\(\exists t(\theta(x,t)\wedge y=t(x))\)

    下面证明\(\exists t(\theta(x,t)\wedge y=t(x))\)的绝对性

    *断言2* ：\(\theta(x,t)\)是绝对的

    只需证明\(t\uhr\pred(X,y,R)\)是绝对的，即若\(x_0\in X^M,y_0\in\pred(X,x_0,R)\)，\(t_0\in M\)，则
    \(t_0\uhr\pred(X,y_0,R)=(t_0\uhr\pred(X,y_0,R))^M\)

    函数\(s=t\uhr\pred(X,y,R)\)被公式
    \begin{equation*}
    \eta(y,t,s):=\forall x\in s\exists u\exists v(uRy\wedge v=t(u)\wedge x=(u,v))\wedge
    \forall u\forall v(uRy\wedge v=t(u)\to (u,v)\in s)
    \end{equation*}
    验证：\(\eta\)是绝对的（练习），但是\(uRy\)，因此\(u\in M\),

    故\(\theta(x,t)\)是绝对的

    *断言3* ：\(\theta(x,t)\)定义了一个类函数，即\(V\vDash\forall x\in X\exists!t\theta(x,t)\)
    练习（对\(x\in X\)归纳证明）

    下面证明\(\theta\)作为函数是绝对的
    *断言4* ：若\(x\in M\)，则\(\forall t(\theta(x,t)\to t\in M)\)

    否则，存在一个极小的\(x_0\in M\),\(t_0\)使得\(\theta(x_0,t_0)\)且\(t_0\notin M\)

    若\(\pred(X,x_0,R)=\emptyset\)，则由\(\theta\)的定义，\(t_0=\{(x_0,F(x_0,\emptyset))\}\in M\)，矛盾

    若\(\pred(X,x_0,R)\neq\emptyset\)，令\(t^*=\{y\mid\exists x\in\pred(X,x_0,R)\wedge\theta(x,y)\}\)，由极小性，\(t^*\subseteq M\)

    \(t^*=\ran(\theta\uhr\pred(X,x_0,R))\)

    由归纳假设，\(\forall x\in\pred(X,x_0,R)\exists!y\in M(\theta(x,y))\)

    于是\(\forall x\in\pred(X,x_0,R)\exists!y\in M(\theta^M(x,y))\)

    因此\(t^*=\ran(\theta^M\uhr\pred(X,x_0,R))\)

    由替换公理，\(t^*\in M\)，由绝对性
    \begin{equation*}
    t_0=(\bigcup t^*)\cup\{(x_0,F^M(x_0,\bigcup t^*))\}\in M
    \end{equation*}
    矛盾

    故\(\forall x\in M\exists! t\in M\theta(x,t)\)，即\(\theta(x,t)\)作为函数绝对

    记\(\phi(x,y):=\exists t(\theta(x,t)\wedge y=t(x))\)，则
    \begin{equation*}
    \phi^M(x,y)=\exists t\in M(\theta(x,t)\wedge y=t(x))
    \end{equation*}
    但是\(\forall x\in M\forall y\in M\)
    \begin{equation*}
    (\exists t(\theta(x,t)\wedge y=t(x)))\leftrightarrow\exists t\in M(\theta(x,t)\wedge y=t(x))
    \end{equation*}

    下面证明\(G(x)\)作为函数绝对，即\(G(x)\)封闭

    回亿：\(g:X^M\to M\)满足
    \begin{equation*}
    \forall x\in X^M(g(x)=F^M(x,g\uhr\pred(X^M,x,R^M)))
    \end{equation*}

    *断言5* ：\(\forall x\in X^M(G(x)=g(x))\)

    否则，存在“极小”的\(x_0\in X^M=X\cap M\)使得\(G(x_0)\neq g(x_0)\)

    显然\(\pred(X,x_0,R)=\pred(X^M,x_0,R^M)\neq\emptyset\)，否
    则\(g(x_0)=F^M(\emptyset,g\uhr\emptyset)=F^M(\emptyset,\emptyset)=F(\emptyset,g\uhr\emptyset)=G(x_0)\)

    假设\(\pred(X,x_0,R)=\pred(X^M,x_0,R^M)\neq\emptyset\)，由\(x_0\)的极小性，
    有\(\forall x\in\pred(X,x_0,R)\cap\pred(X^M,x_0,R^M)\)时，有\(G(x)=g(x)\)

    因此\(G\uhr\pred(X,x_0,R)=g\uhr\pred(X^M,x_0,R^M)\)

    \(g(x_0)=F^M(x_0,g\uhr\pred(X^M,x_0,R^M))=G(x_0)\)，矛盾
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    一下概念对\(\ZF-\Pow\)的传递模型都是绝对的
    1. \(\alpha^\beta\) (序数)
    2. \(\rank(x)\)
    3. \(\trcl(x)\)
    #+END_theorem

    #+BEGIN_proof
    1. 若\(\alpha=0\)，则\(\alpha^\beta=0\)

       它是递归定义的，因此是绝对的

       规定\(\On\times\On\)上的关系\(R\)为
       \begin{equation*}
       R=\{((\alpha,\beta_1),(\alpha,\beta_2))\mid\beta_1\in\beta_2\}\subseteq\On^2
       \end{equation*}
       显然\(R\)是良基关系，\(R\)是似集合的，\(\pred(\On^2,(\alpha,\beta),R)=\{\alpha\}\times\beta\)

       定义\(F:\On^2\times V\to V\)为
       \begin{equation*}
       F(\alpha,\beta,x)=
       \begin{cases}
       0&\alpha=0\vee x\notin\On^3\\
       1&\beta=0\wedge\alpha\neq 0\\
       \left( \bigcup_{y\in x}\pi_3(y) \right)\cdot\alpha&\text{otherwise},x\in\On^3
       \end{cases}
       \end{equation*}
       有\(M\)的传递性，\(x=(x_1,x_2,x_3)\in M\Rightarrow x_1,x_2,x_3\in M\)

       由\((x_1,x_2,x_3)\)的绝对性，\(y=\pi_3(x)\)是绝对的，因为\(y=\pi_3(x)\)为
       \begin{equation*}
       \exists x_1\exists x_2\exists x_3(x=(x_1,x_2,x_3)\wedge y=x_3)
       \end{equation*}

       验证\(G(\alpha,\beta)=\alpha^\beta\)是基于\(F\)递归定义的，因此\(G\)是绝对的

    2. \(\rank(x)\)，即\(\rank(V,x,\in)\)

       \(\rank(x)=\sup\{\rank(y)+1\mid y\in x\}\)，找\(F\)，并证明绝对性，练习

    3. \(\trcl(x)=x\cup\bigcup\{\trcl(y)\mid y\in x\}\)练习
    #+END_proof

    #+BEGIN_remark
    \(\alpha+\beta\)也是递归定义的
    #+END_remark

    #+BEGIN_remark
    - \(\rank(x)\)的定义用到\(V_\alpha\)
    - 当\(M\not\vDash\Pow\)，\(V_\alpha^M\)没有意义
    - \(\rank(x)\)仍可递归定义为\(\sup\{\rank(y)+1\mid y\in x\}\)
    - 当\(M\vDash\Pow\)，则两种定义等价
    #+END_remark

    定义公式\(\varphi(x,y)\)为
    \begin{equation*}
    \forall z(z\in y\leftrightarrow z\subseteq x)
    \end{equation*}
    当\(V\vDash\Pow\)，则\(V\vDash\forall x\exists!y\varphi(x,y)\)，即\(\varphi(x,y)\)定义了一个函数，记作\(\calp(x)=y\)

    若\(M\vDash\Pow\)，则
    \begin{equation*}
    V\vDash\forall x\in M\exists!y\in M\varphi^M(x,y)
    \end{equation*}
    当\(M\)传递时，\(\subseteq^M\Leftrightarrow\subseteq\)，若\(M\vDash\Pow\)，则
    \begin{equation*}
    V\vDash(\varphi^M\text{定义了$M$到$M$的函数})
    \end{equation*}
    记该函数为\(\calp^M(x)\)，即\(\calp^M(x)=\{z\in M\mid z\subseteq^Mx\}\)
    当\(M\)传递时，\(\calp^M(x)=\{z\in M\mid z\subseteq x\}=\calp(x)\cap M\)

    同理\(V_\alpha^M=\{x\in M\mid(\rank(x)<\alpha)^M\}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若\(M\)是\(\ZF\)的传递模型，则
    1. 若\(x\in M\)，则\(\calp^M(x)=\calp(x)\cap M\)

       只需\(\Pow\)加传递
    2. 如果\(\alpha\in M\)，则\(V_\alpha^M=V_\alpha\cap M\)

       只需\(\ZF-\Pow\)，若有\(\Pow\)，则\(V_\alpha^M\)是由\(\calp^M\)得到的
    #+END_lemma

    #+BEGIN_remark
    \(\calp\)与\(V_\alpha\)作为函数不是绝对的

    固定\(x\in M\)，则\(\calp(x)\)可以是带参数\(x\)的公式
    \begin{equation*}
    \calp(x)(y):\forall z(z\in y\leftrightarrow z\in x)
    \end{equation*}
    此时谓词\(\calp(x)\)是绝对的，\((\calp(x))^M=\calp(x)\cap M\)

    固定\(\alpha\in M\cap\On\)，则\(V_\alpha\)可以看成带参数\(\alpha\)的谓词，此时\((V_\alpha)^M=V_\alpha\cap M\)是绝对的
    #+END_remark
** 不可达基数与ZFC的模型

    一般来讲，\(V_\alpha\)不是\(\ZF\)的模型，比如\(\ZFm\vdash(V_\omega\vDash\ZFC-\Inf)\)

    令\(Z\)表示\(\ZF-\)替换公理模式（Rep）

    \(ZC\)表示\(\ZFC-\Rep\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(\gamma>\omega\)是无穷极限序数，则\(\ZF\vdash(V_\gamma\vDash Z)\)，\(\ZFC\vdash(V_\gamma\vDash\ZC)\)
    #+END_theorem

    #+BEGIN_proof
    假设\(V\vDash\ZF\)
    - 存在公理：
    - 外延公理：\(\forall x\in V_\gamma\forall y\in V_\gamma\forall u\in V_\gamma((u\in x\leftrightarrow u\in y)\to x=y)\)，\(V_\gamma\)传递
    - 分离公理模式：假设\(x\in V_\gamma\)，则存在\(\beta<\gamma\)使得\(x\in V_\beta\)，故\(x\subseteq V_\beta\)，
      \(\calp(x)\subseteq\calp(V_\beta)=V_{\beta+1}\subseteq V_\gamma\)，则若\(x\in V_\gamma\)，则\(X\)的子集均属于\(V_\gamma\)

      分离公理
      \begin{equation*}
      \forall x\in V_\gamma\exists Y\in V_\gamma\forall u\in V_\gamma(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))
      \end{equation*}
      在\(V\)里面可以看到这些是\(X\)的子集，且能看到\(X\)的所有子集在\(V_\gamma\)里
    - 对集公理，\(\forall x\forall y\exists z\forall u(u\in z\leftrightarrow u=x\vee u=y)\)

      设\(x,y\in V_\gamma\subseteq\WF=V\)，有\(\rank(\{x,y\})<\max\{\rank(x),\rank(y)\}+\omega\)，故\(\{x,y\}\in V_\gamma\)
    - 并集公理，类似
    - 幂集公理，类似
    - 无穷公理

      对于\(\ZFm-\Pow-\Rep\)的传递模型，\(\emptyset\)与后继运算是绝对的

      \(\omega\in V_\gamma\)，故无穷公理的相对化成立
    - 基础公理

      \(\forall x\in V_\gamma((x\neq\emptyset)^{V_\gamma}\to\exists y\in V_\gamma(y\in x\wedge(y\cap x=\emptyset)^{V_\gamma}))\)

      对于\(\ZFm-\Pow-\Rep\)的传递模型，\(\emptyset\)与\(\cap\)是绝对的

      而\(V_\gamma\subseteq\WF=V\)，故Fon成立



    若\(V\vDash\ZFC\)，设\(x\in V_\gamma\)，则\(V\vDash\exists R(R\text{是$X$的良序})\)。\(R\subseteq X\times X\Rightarrow R\in V_\gamma\)，对
    于\(\ZFm-\Pow-\Inf-\Rep\)的传递模型\(V_\gamma\)有
    \begin{equation*}
    V\vDash(R\text{是$X$的良序})^{V_\gamma}
    \end{equation*}

    #+END_proof

    #+BEGIN_exercise
    证明\(V_{\omega+\omega}\)不满足Rep
    #+END_exercise

    #+BEGIN_proof
    \(f:n\to\omega+n\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    工作在\(\ZFC\)
    * \(\ZF\)不能证明“\(V_\omega\)存在”
    * \(\ZF\)不能证明“对任意\(x\)，\(\trcl(x)\)存在”
    #+END_proposition

    #+BEGIN_proof
    构造模型否定这两个命题

    令\(V\vDash\ZFC\)，令\(X_0=\omega\), \(X_{\alpha+1}=\calp(X_\alpha)\), \(X_\gamma=\bigcup_{\beta<\gamma}X_\beta\)（\(\gamma\)极限序数）

    显然\(\barX=\bigcup_{\alpha\in\On}X_\alpha=\WF=V\) （练习）

    容易验证以下事实：\(X_\alpha\)传递，设\(f(x,y)\)表
    示\(\{x,y\}\),\((x-y)\),\(x\times y\),\(\bigcup x\),\(\cap x\),\(\calp(x)\),\(\dots\)

    若\(x\in X_\alpha\),\(y\in X_\beta\)，则\(f(x,y)\in X_{\max\{\alpha,\beta\}+\omega}\)

    类似可证\(X_\omega\)是\(\ZC-\Inf\)的传递模型

    由于\(\omega\in X_\omega\)，故\(X_\omega\vDash\Inf\)，即\(X_\omega\vDash\ZC\)

    显然\(V_\omega\not\subseteq\omega=X_0\)，于是存在\(V_n\not\subseteq X_0\)，故\(\calp(V_n)\not\subseteq\calp(X_0)\)，即\(\forall k<\omega\)，
    \(V_{n+k}\not\subseteq X_k\)，故\(\forall n<\omega\)，都有\(V_\omega\not\subseteq X_n\)，故\(V_\omega\notin X_\omega\)

    但要严格地说的话得找到一个东西定义\(V_\omega\)然后证明它的相对化在\(X_\omega\)不满足

    另一方面，\(V_0\subseteq X_0\Rightarrow V_n\subseteq X_n\)，于是\(V_\omega\subseteq X_\omega\)

    令\(G:\omega\to\WF\)为\(G(n)=V_\alpha\)

    验证\(G\)相对于\(X_\omega\)是绝对的，\(G\)的任何一个片段都是有穷的，因此片段的值域都在\(X_\omega\)中，因
    为\(X_\omega\)对于任何有穷集合封闭

    注：当\(M\vDash\ZF-\Pow\)，我们知道递归函数\(G\)的绝对性，此时\(X_\omega\not\vDash\Rep\)，然而\(X_\omega\)的任何有穷
    子集都属于\(X_\omega\)，故而对任何\(f:\omega\to X_\omega\)，有\(f(\{0,\dots,n\})\in X_\omega\)，可以证明\(G\)的绝对性（练习）

    \(V_\omega\)被公式\(\eta(x):\exists n\in\omega(x\in G(n))\)

    (\(V_\omega\)被“\(\alpha\in V_\omega\)”定义，但是\(X_\omega\)不一定认为\(V_\omega\)是集合，必需用\(X_\omega\)认可的方式定义)

    \(V_\omega\)存在指的是
    \begin{equation*}
    \exists y\forall x(x\in y\leftrightarrow\eta(x))
    \end{equation*}
    由于\(G\)是绝对的，\(\eta(x)\)绝对，因此\(X_\omega\)认为“\(V_\omega\)存在”当且仅
    当\(\exists y\in X_\omega\forall x\in X_\omega(x\in y\leftrightarrow\eta(x))\)

    由于\(V_\omega\subseteq X_\omega\)且\(X_\omega\)是传递的，以上的公式等价于
    \begin{equation*}
    \exists y\in X_\omega\forall x(x\in y\leftrightarrow\eta(x))
    \end{equation*}
    而这样的\(y\)只能是\(V_\omega\)，而\(V_\omega\notin X_\omega\)，因此以上句子不成立

    即\(\ZFC\vdash"X_\omega\vDash\ZC+V_\omega\text{不存在}"\)

    证明“\(x\)存在且\(\trcl(x)\)不存在”，假设\(V\vDash\ZFC\)，令\(t(u)=\{u\}\)，\(x_n=t^n(n)\)，
    \(\rank(x_n)=2n\)，\(x=\{x_n\mid n<\omega\}\)，
    令\(X_0=x\),\(X_1=\bigcup X_0\),\(\dots\),\(X_{n+1}=\bigcup X_n\)，则\(\trcl(x)=\bigcup_{n<\omega}X_n\)

    令\(Y_0=\omega\cup X_0\)，\(Y_{n+1}=\calp(Y_n)\cup Y_n\cup X_n\)，验证\(Y_\omega=\bigcup_{n<\omega}Y_n\)是传递的，验证\(Y_\omega\vDash\ZC\)，
    验证\(x\in Y_1\subseteq Y\)，验证\(\trcl(x)=\bigcup_{n<\omega}X_n\notin Y\)，即验证\(\forall n\exists m(X_m\not\subseteq Y_n)\)

    后面类似，证明\(Y_\omega\vDash"\trcl(x)\text{不存在}"\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(\kappa\)是不可达基数，则在\(\ZFm\)中可以证明\(V_\kappa\vDash\ZF\)，在\(\ZFCm\)中可以证明\(V_\kappa\vDash\ZFC\)
    #+END_theorem

    #+BEGIN_proof
    已知\(\ZFm\vDash(V_\kappa\vDash Z)\),\(\ZFCm\vDash(V_\kappa\vDash\ZC)\)，下面验证替换公理模式
    \begin{equation*}
    \forall A(\forall x\in A\exists!y\psi(x,y)\to\exists B\forall x\in A\exists y\in B\psi(x,y))
    \end{equation*}
    相对化
    \begin{equation*}
    \forall A\in M(\forall x\in A\exists!y\in M\psi^M(x,y)\to\exists B\in M\forall x\in A\exists y\in B\psi(x,y))
    \end{equation*}
    假设\(A\in V_\kappa\)且\(\forall x\in A\exists!y\in V_\kappa\psi^M(x,y)\)

    由于\(\kappa\)是极限序数，故\(A\in V_\kappa\Rightarrow\exists\alpha<\kappa(A\in V_\alpha)\)，因此\(A\subseteq V_\alpha\)，而\(V\vDash(\psi^M:A\to V_\kappa)\)，于
    是\(V\vDash\abs{A}\le\abs{V_\alpha}<\kappa\), \(V\vDash\abs{f(A)}<\kappa\),\(V\vDash f(A)\subseteq V_\kappa\)，由\(\kappa\)的正则性，所以存
    在\(\beta<\kappa\)，\(f(A)\subseteq V_\beta\)，于是\(f(A)\in V_{\beta+1}\subseteq V_\kappa\)，即\(B=f(A)\)即可
    #+END_proof

    注：\(V_\kappa\)的基数小于\(\kappa\)的子集都是\(V_\kappa\)的元素

    若\(M\)的有穷子集都是\(M\)的元素，则\(M\vDash\)有穷Rep

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\ZFC\)中不能证明“存在不可达基数”
    #+END_corollary

    #+BEGIN_proof
    若\(\ZFC\vdash\)“存在不可达基数”，则\(\ZFC\vdash"V_\kappa\vDash\ZFC"\)，即\(\ZFC\vdash\exists X(\ZFC)^X\)，因为\(V_\kappa\)是个集合，
    因此\(\ZFC\vdash\Con(\ZFC)\)

    若只能找到一个真类，我们不能得到能证明一致性
    #+END_proof

    若\(T\)是可公理化的，则
    \begin{equation*}
    \ZFC\vdash\Con(T)\leftrightarrow\exists M(T)^M
    \end{equation*}
    （粗略的完全性定理）
    取一个适当大的子集\(P\subseteq\ZFC\)，有
    \begin{equation*}
    P\vdash\Con(T)\leftrightarrow\exists M(T)^M
    \end{equation*}

    已知若\(V\vDash\ZFm\)，则\(\WF\vDash\ZF\),\(\ZFm\vdash(\ZF)^{\WF}\)\(\not\Rightarrow\) \(\ZFm\vDash Con(\ZF)\)，因为\(\WF\)不
    是集合

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(\kappa\)是不可达基数（极限序数），则以下概念对\(V_\kappa\)都是绝对的
    1. \(x\)是一个基数
    2. \(x\)是正则基数
    3. \(x\)是一个不可达基数
    #+END_lemma

    #+BEGIN_proof
    1. \(x\)是基数被公式\(\varphi(x)\)表示：
       “\(x\)是序数”\(\wedge\forall f\forall y\in x((f:y\to x)\to\ran(f)\neq x)\)

       三个子公式对\(\ZF-\Pow-\Inf-\Rep\)的传递模型都是绝对的

       若\(\kappa\)是极限序数，则
       \begin{equation*}
       V_\kappa\vDash\ZF-\Pow-\Inf-\Rep
       \end{equation*}

       由于\(\varphi(x)\)是一个\(\Pi_1\)公式，故
       \begin{equation*}
       \forall x\in V_\kappa(\varphi(x)\to\varphi^{V_\kappa}(x))
       \end{equation*}
       另一方面，要证明\(\forall x\in V_\kappa(\varphi^{V_\kappa}(x)\to\varphi(x))\)，只需证明若\(x,y\in V_\kappa\)且\(f:y\to x\)，
       则\(f\in V_\kappa\)

       显然若\(f:y\to x\)，则\(f\in x^y\)，而\(x,y\in V_\alpha\)，\(x^y\in V_{\alpha+\omega}\)，故\(f\in V_\kappa\)，
       \(\rank(f)\le\max\{\rank(x),\rank(y)\}+2\)
    2. \(x\)是正则基数被公式\(\varphi(x)\)表示：
       “\(x\)是基数”\(\wedge\forall f\forall y\in x[(f:y\to x)\to\exists z\in x(\ran(f)\subseteq z)]\)

       与1类似
    3. \(x\)是不可达基数被公式\(\varphi(x)\)表示：
       “\(x\)是正则基数”\(\wedge\forall f\forall y\in x((f:2^y\to x)\to\ran(f)\neq x)\)

       \(2^y\)是\(y\)到2的全体函数为绝对概念
    #+END_proof

    用“\(I\)”表示“存在不可达基数”

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(\ZFC\)一致，则\(\ZFC+\neg I\)也是一致的，即
    \begin{equation*}
    \ZFC\vdash\Con(\ZFC)\to\Con(\ZFC+\neg I)
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    设\(V\vDash\ZFC+\Con(\ZFC)\)，\(V\vDash\exists M(ZFC)^M\)

    先在\(M\vDash\ZFC\)，视\(M\)为集合宇宙，若\(\kappa\)是\(M\)中最小的不可达基数，则\(V_\kappa\vDash\ZFC+\neg I\)，
    即\(M\vDash(\ZFC+\neg I)^{V_\kappa}\)

    存在\(M\)中的元素\(X\)使得\(M\vDash"(X,\in)\vDash\ZFC+\neg I"\)，即\(M\vDash(\ZFC+\neg I)^X\)，则
    \(V\vDash((\ZFC+\neg I)^X)^M\)，即\(\forall y\rightsquigarrow\forall y\in X\rightsquigarrow\forall y\in X\cap M\)，因此
    \(V\vDash(\ZFC+\neg I)^{X\cap M}\) （验证：归纳）

    注：\(M\)看到\((X,\in)\)恰好是\(V\)看到的\((X\cap M,\in)\)

    因此\(V\vDash\Con(\ZFC+\neg I)\)

    若\(M\)中不存在不可达基数，则\(M\vDash\ZFC+\neg I\)，因此\(V\vDash(\ZFC+\neg I)^M\)

    事实上
    \((\N,+,\times,0,1)+AC+\Con(\ZFC)\vdash\Con(\ZFC+\neg I)\)
    （完全性要AC）
    #+END_proof

    以上引理表明：\(\ZFC\not\vdash I\)

    以上证明没有使用哥德尔不完全定理

    最好的情况是，“\(\ZFC+I\)”一致，即我们希望\(\ZFC\)下构造“\(\ZFC+I\)”的模型

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    在\(\ZFC\)中不能生成“\(ZFC+I\)”的模型，即
    \begin{equation*}
    \ZFC+\Con(\ZFC)\not\vdash\Con(\ZFC+I)
    \end{equation*}
    #+END_corollary

    #+BEGIN_proof
    否则，假设\(\ZFC\)一致，则\(\ZFC+I\)一致，目标\(\ZFC+I\vdash\Con(\ZFC+I)\)

    任取\(V\vDash\ZFC+I\)，则\(V\vDash(\ZFC)^{V_\kappa}\)，由完全性，\(V\vDash\Con(\ZFC)\)，因此有了矛盾
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    对任意的无穷基数\(\kappa\)
    \begin{equation*}
    H_\kappa=\{x\mid\abs{\trcl(x)}<\kappa\}
    \end{equation*}
    称\(H_\kappa\)的元素为 *遗传基数\(<\kappa\)的基数*

    称\(x\in H_\omega\)为 *遗传有穷集*
    #+END_definition

    #+ATTR_LATEX: :options [\(V\vDash\ZFC\)]
    #+BEGIN_lemma
    对任意的无穷基数\(\kappa\)有
    \begin{equation*}
    H_\kappa\subseteq V_\kappa
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    \(V=\WF\)，只需验证\(\forall x\in H_\kappa\)，有\(\rank(x)<\kappa\)

    设\(x\in H_\kappa\)，令\(t=\trcl(x)\)，令\(s=\{\rank(y)\mid y\in t\}\subseteq\On\)，验证\(s\)是序数

    假设\(\alpha\)是最小的不属于\(s\)的序数，\(\alpha\subseteq s\)，若\(\alpha\neq s\)，令\(\beta=\min(s\setminus\alpha)\)，因此\(\beta>\alpha\)，
    令\(y\in t\)使得\(\beta=\rank(y)\)，\(\forall z\in y\)，\(z\in t\)且\(\rank(z)<\rank(y)\)，由\(\beta\)的极小性，
    \(\forall z\in y(\rank(z)<\alpha)\)，\(\beta=\rank(y)=\sup\{\rank(z)+1\mid z\in y\}\)，因此\(\beta\le\alpha\)，矛盾

    故\(s=\alpha\)，且\(\abs{s}\le\abs{t}=\abs{\trcl(x)}<\kappa\)，所以\(\alpha<\kappa\)，\(x\subseteq\trcl(x)\subseteq V_s\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(\kappa\)是正则基数，则\(H_\kappa=V_\kappa\)当且仅当\(\kappa\)是不可达基数
    #+END_lemma

    #+BEGIN_proof
    设\(\kappa\)不可达，只需证明\(V_\kappa\subseteq H_\kappa\)

    对\(\alpha<\kappa\)进行归纳证明：\(\abs{V_\alpha}<\kappa\) (练习)

    设\(x\in V_\kappa\)，则存在\(\alpha<\kappa\)使得\(x\in V_\alpha\)，\(\trcl(x)\subseteq V_\alpha\)，因此\(\abs{\trcl(x)}<\kappa\)

    假设\(\kappa\)不是不可达基数，则存在\(\lambda<\kappa\)，\(2^\lambda\ge\kappa\)，
    \(\calp(\lambda)\in V_{\lambda+\omega}\subseteq V_\kappa\),\(\abs{\trcl(P(\lambda))}\ge 2^\lambda\ge\kappa\)，因此\(P(\lambda)\in V_\kappa\setminus H_\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    对于任意无穷基数\(\kappa\)
    1. \(H_\kappa\)传递
    2. \(H_\kappa\cap\On=\kappa\)
    3. \(x\in H_\kappa\Rightarrow\bigcup x\in H_\kappa\)
    4. \(x,y\in H_\kappa\Rightarrow\{x,y\}\in H_\kappa\)
    5. \(x\in H_\kappa\)且\(y\subseteq x\)，则\(y\in H_\kappa\)
    6. 如果\(\kappa\)正则，则
       \begin{equation*}
       \forall x(x\in H_\kappa\leftrightarrow x\subset H_\kappa\wedge\abs{x}<\kappa)
       \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    1. 设\(x\in y\in H_\kappa\)，则\(\abs{\trcl(y)}<\kappa\)，而\(\trcl(x)\subset\trcl(y)\)，因此\(x\in H_\kappa\)
    2. 若\(\alpha<\kappa\)，则\(\alpha=\trcl(\alpha)\)，因此\(\alpha\in H_\kappa\)

       若\(\alpha\in H_\kappa\)，则\(\abs{\alpha}<\kappa\)，因此\(\alpha<\kappa\)
    3. \(\bigcup x\subseteq\trcl(x)\Rightarrow\trcl(\bigcup x)\subseteq\trcl(x)\)，故\(x\in H_\kappa\Rightarrow\bigcup x\in H_\kappa\)
    4. \(\trcl(\{x,y\})=\{x,y\}\cup\trcl(x)\cup\trcl(y)\)
    5. \(\trcl(y)\subseteq\trcl(x)\)
    6. 若\(x\in H_\kappa\)，由传递性，\(x\subset H_\kappa\)，\(\abs{x}\le\abs{\trcl(x)}<\kappa\)

       若\(x\subset H_\kappa\),\(\abs{x}<\kappa\),设\(x=\{x_i\mid i<\lambda\}\)，则\(\trcl(x)=x\cup\bigcup_{i<\lambda}\trcl(x_i)\)，
       若\(\abs{\trcl(x)}\ge\kappa\)，则\(\forall\alpha<\kappa\)，存在\(i<\lambda\)使得\(\abs{\trcl(x_i)}>\alpha\)，故\(\lambda\)与\(\kappa\)共尾
    #+END_proof

    #+ATTR_LATEX: :options [ZFC]
    #+BEGIN_theorem
    若\(\kappa\)是不可数正则基数，则\(H_\kappa\vDash\ZFC-\Pow\)
    #+END_theorem

    #+BEGIN_proof
    \(H_\kappa\)传递\(\Rightarrow\)外延公理

    \(H_\kappa\)非空\(\Rightarrow\)存在公理

    由于\(x\in H_\kappa\leftrightarrow x\subset H_\kappa\wedge\abs{x}<\kappa\)，故分离公理+替换公理成立

    \(H_\kappa\)对\(\bigcup x\)与\(\{x,y\}\)封闭，故对集公理+并集公理成立

    \(H_\kappa\)满足以上公理\(\Rightarrow\)\(\emptyset,\omega,x^+,x\cap y\)的绝对性

    由于\(\omega\in H_\kappa\), \(H_\kappa\vDash\Inf\)

    \(\emptyset,x\cap y\)的绝对性，\(H_\kappa\vDash Fud\)

    选择公理：\(\forall x\in H_k\exists R\in H_\kappa(R\text{是$X$的良序})^{H_\kappa}\)

    已知，若\(x,R\in H_\kappa\)，则\(R\)是\(x\)的良序当且仅当\((R\text{是$X$的良序})^{H_\kappa}\) (\(\ZF-\Pow\))

    只需验证：如果\(X\in H_\kappa\)，则\(\forall R\subseteq X\times X\)，有\(R\in H_\kappa\)

    显然\(\abs{X}<\kappa\)，因此\(\abs{X\times X}<\kappa\)，若\(a,b\in X\)，
    则\(\abs{\trcl((a,b))}<\abs{\trcl(x)}+\aleph_0\)，因此\((a,b)\in H_\kappa\)，因此\(R\subset H_\kappa\)，根据(6)，
    有\(R\in H_\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options [ZFC]
    #+BEGIN_theorem
    如果\(\kappa\)是不可数正则基数，TFAE
    1. \(H_\kappa\vDash\ZFC\)
    2. \(H_\kappa=V_\kappa\)
    3. \(\kappa\)不可达
    #+END_theorem

    #+BEGIN_proof
    已知\(2\leftrightarrow 3\)

    \(1\to 2+3\):若\(\kappa\)不是不可达基数，则存在\(\lambda<\kappa\)使得\(2^\lambda\ge\kappa\)，\(\lambda\in H_\kappa\)且\(\calp(\lambda)\notin H_\kappa\)，于
    是\(H_\kappa\not\vDash\Pow\)

    \(V\vDash\forall z\in H_\kappa\forall x\in H_\kappa(x\in z\leftrightarrow x\subseteq\lambda)\)

    \(2\to 1\)显然
    #+END_proof

    以上引理表明，若\(\kappa\)正则且不是不可达的，则
    \begin{equation*}
    \ZFC\vdash(\ZFC-\Pow+\neg\Pow)^{H_\kappa}
    \end{equation*}
    故\(\Con(\ZFC)\to\Con(\ZFC-\Pow+\neg\Pow)\)，即\(\Pow\)不能由\(\ZFC\)中的其它公理推出

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(\Con(\ZFC)\to\Con(\ZFC-\Pow+\forall(x\text{ countable}))\)
    #+END_corollary

    #+BEGIN_proof
    \(H_{\omega_1}\vDash\ZFC-\Pow\)

    \(x\)可数：存在\(f\)，\((f:x\to\omega)\)是双射，只需要这个\(f\)是属于\(H_{\omega_1}\)就行了，但这是显然的
    \(\forall x,y\in H_\kappa\), \(x^y\in H_\kappa\)用性质6

    这个可数我们得在\(H_{\omega_1}\)里看到
    #+END_proof
** 反映定理
    已知\(V\vDash\ZF\Rightarrow V_\alpha\vDash Z\) \(\alpha>\omega\)

    \(V\vDash\ZFC\Rightarrow V_\alpha\vDash\ZC\) (\(\alpha>\omega\))

    \(V_\omega\vDash\ZFC-\Inf\)

    \(V_\alpha\)不能“反映”\(V\)的全貌，除非\(\alpha\)是不可达基数

    对不可达基数\(\kappa\)，\(V_\kappa\)能“反映”\(V\)的全貌（不全对）

    \(H_\kappa\)也类似，


    本节讨论另一个方向：对给定的句子\(\varphi\)，若\(\varphi\)在\(V\)中成立，则能否找到\(\alpha\)使得\(V_\alpha\vDash\varphi\)

    问：是否存在\(\varphi\)，它在\(V\)中成立，但是\(\forall \alpha(V_\alpha\not\vDash\varphi)\) (因为\(\ZC\)少了无穷条Rep)

    #+ATTR_LATEX: :options [反映定理]
    #+BEGIN_theorem
    对于任意有穷\(\varphi_1,\dots,\varphi_n\)，存在\(\alpha\)使得
    \begin{equation*}
    V\vDash\varphi_i\Leftrightarrow V_\alpha\vDash\varphi_i(i=1,\dots,n)
    \end{equation*}
    即
    \begin{equation*}
    V\vDash\varphi_i\leftrightarrow\varphi_i^{V_\alpha}
    \end{equation*}
    #+END_theorem

    设\(F\)是一个集合论语言的公式集，如果对每个\(\varphi(x_1,\dots,x_n)\in F\)，对每个\(a_1,\dots,a_n\in M\)，
    有\(M\vDash\varphi[a_1,\dots,a_n]\Leftrightarrow N\vDash\varphi[a_1,\dots,a_n]\)，则称\(M\)是\(N\)的相对于\(F\)的初等子模型，记作\(M\prec_FN\)

    反映定理是 Löwenheim–Skolem Theorem的有穷“版本”，等价地说\(F\)中的公式相对于\(V_\alpha\)绝对

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(M\subseteq N\)都是类，\(\varphi_1,\dots,\varphi_n\)是对子公式封闭的公式集，则以下命题等价
    1. \(\varphi_1,\dots,\varphi_n\)相对于\(M\)和\(N\)绝对
    2. 如果\(\varphi_i\)是形如\(\exists x\varphi_j(x,y_1,\dots,y_m)\)的公式，则
       \begin{equation*}
       \forall\bary\in M(\exists x\in N\varphi_j^N(x,\bary)\to\exists x\in M\varphi_j^N(x,\bary))
       \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    \(1\to 2\): 设\(\varphi_i\)形如这样的形式，由绝对性
    \begin{equation*}
    \forall\bary\in M(\varphi_i^N(\bary)\leftrightarrow\varphi_i^M(\bary))
    \end{equation*}
    载有\(\varphi_j\)的绝对性,\(\forall\bary(\exists x\in M\varphi_j^M(x,\bary)\leftrightarrow\exists x\in M\varphi_j^N(x,\bary))\)

    \(2\to 1\): 对\(\varphi_i\)的长度归纳证明：
    若\(\abs{\varphi_i}\)最小，则\(\varphi_i\)无量词，因此绝对

    若长度小于\(\abs{\varphi_i}\)的公式都是绝对的，则\(\varphi_i\)的所有子公式都绝对，而\(\varphi_i\)的形式有以下形式
    1. \(\varphi_j\to\varphi_k\)
    2. \(\neg\varphi_j\)
    3. \(\exists x\varphi_j(x,\bary)\)


    只需验证情形3:任取\(\bary\in M\)，由题设条件，
    \begin{equation*}
    \exists x\in N\varphi_j^N(x,\bary)\to\exists x\in M\varphi_j^N(x,\bary)
    \end{equation*}
    由\(\varphi_j\)的绝对性，有
    \begin{equation*}
    \exists x\in N\varphi_j^N(x,\bary)\to\exists x\in M\varphi_j^M(x,\bary)
    \end{equation*}
    而显然
    \begin{equation*}
    \exists x\in M\varphi_j^N(x,\bary)\to\exists x\in N\varphi_j^N(x,\bary)
    \end{equation*}
    #+END_proof

    这个证明没有用到有穷性，因此无穷情况也成立

    #+ATTR_LATEX: :options [反映定理，ZF]
    #+BEGIN_theorem
    对于任意有穷公式集\(F=\{\varphi_1,\dots,\varphi_n\}\)，对任意\(\alpha\in\On\)，存在\(\beta\ge\alpha\)使得
    \(F\)对\(V_\beta\)绝对
    #+END_theorem

    在\(\ZF\)中，\(\WF=V\)

    #+BEGIN_proof
    由于没有选择公理，无法“构造”\(\calh(V_\alpha)\)，\(V_\alpha\)的Skolem hull

    本质上，我们只需要找到一个\(V_\beta\)使得每个形如\(\exists x\varphi(x,\bary)\)的公式以及每一组参数\(\barb\in V_\beta\)
    有\(V\vDash\exists x\varphi_j(x,\barb)\Leftrightarrow V_\beta\vDash\exists x\varphi_j(x,\barb)\)，即系数来自\(V_\beta\)的方程若有解，则有一个解\(\in V_\beta\)

    设\(\varphi_i\in F\)且形如\(\exists y\varphi_j(\barx,y)\)，定义函数\(h_i\)如下：
    * 任取\(\barx\in V\)，令\(U=\{y\mid\varphi_j(\barx,y)\}\)
    * 若\(U=\emptyset\)，则\(h_i(\barx)=0\)
    * 若\(U\neq\emptyset\)，则存在最小的\(\xi\)使得\(U\cap V_\xi\neq\emptyset\)，此时令\(h_i(\barx)=V_\xi\)（用了序数的良序性）
    * 函数\(h_i\)满足
      \begin{equation*}
      \forall\barx(\exists y\varphi_j(\barx,y)\to\exists y\in h_i(\barx))\varphi_j(\barx,y)
      \end{equation*}

    定义\(h_F\)为：
    \begin{equation*}
    h_F(x_1,\dots,x_m)=\bigcup\{h_i(x_1,\dots,x_m):i=1,\dots,n\}
    \end{equation*}
    这里必需要求只能有穷多个，因为\(h_i\)是类

    则\(h_F\)满足：对每个形如\(\exists y\varphi_j(\barx,y)\)的公式，有
    \begin{equation*}
    \forall\barx(\exists y\varphi_j(\barx,y)\to\exists y\in h_F(\barx)\varphi_j(\barx,y))
    \end{equation*}
    任取\(\alpha\)，递归定义\(V_\alpha^i\)，\(i\in\omega\)如下：
    - \(V_\alpha^0=V_\alpha\)
    - \(V_\alpha^{i+1}=V_\alpha^i\cup\bigcup\{h_F(\bary)\mid\bary\in V_\alpha^i\}\)


    令\(V_\beta=\bigcup V_\alpha^i\)，相当于\(V_\alpha\)的\(F\)-Skolem hull，若\(\varphi_i\in F\)形如\(\exists y\varphi_j(\barx,y)\)

    任取\(\barx\in V_\beta\)，则存在\(k<\omega\)使得\(\barx\in V_\alpha^k\)，若\(\exists y\varphi_j(\barx,y)\)，则
    \begin{equation*}
    \exists y\in h_F(\barx)\varphi_j(\barx,y)
    \end{equation*}

    #+END_proof

    #+ATTR_LATEX: :options [ZF]
    #+BEGIN_corollary
    令\(F=\{\sigma_1,\dots,\sigma_n\}\)为\(ZF\)的有穷子集，则
    \begin{equation*}
    \forall\alpha\exists\beta\ge\alpha(\sigma_1^{V_\beta}\wedge\dots\wedge\sigma_n^{V_\beta})
    \end{equation*}
    #+END_corollary

    #+BEGIN_proof
    将\(F\)扩张为\(F'\)，有穷且对子公式封闭，于是\(\forall\alpha\exists\beta\ge\alpha\)使得\(F'\)相对于\(V_\beta\)绝对

    对于\(F'\)中的句子，有
    \begin{equation*}
    \ZF\vdash\sigma\leftrightarrow\sigma^{V_\beta}
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    设\(F=\{\sigma_1,\dots,\sigma_n\}\subseteq\ZF\)，除非\(\ZF\)不一致，否则"\(F\not\vdash\ZF\)"
    #+END_corollary

    #+BEGIN_proof
    存在\(V_\beta\)使得\(\ZF\vdash(F)^{V_\beta}\)，若\(F\vdash\ZF\Rightarrow\ZF\vdash(\ZF)^{V_\beta}\)，故\(\ZF\vdash(\ZF)^{V_\beta}\to\Con(\ZF)\) (无需
    AC，反过来要)，因此\(\ZF\vdash\Con(\ZF)\)
    #+END_proof

    #+BEGIN_remark
    以上推论对\(\ZF\)的任意扩张成立

    若\(AC\)成立，则反映定理可以改进为
    存在可数\((M,\in)\)使得\(M\prec_FV\) （绝对性强于\(\prec_F\)）
    * 若\(F\)含有无穷公理，则\(M\neq V_\omega\)
    * 若\(F\)含有幂集公理，若\(M\)传递，则没有绝对性
      * 令\(\psi(x,y)\)表示\(\forall u(u\in y\leftrightarrow u\subseteq x)\)，令\(\Pow:\forall x\exists y\psi(x,y)\)，则\(\psi\)与\(\Pow\)不能同时绝对

        \(M\)传递时，\(\subseteq\leftrightarrow\subseteq^{\eq}\)，若\(\psi\)绝对，则\(V\)看到的幂集跟\(M\)看到的幂集，而\(M\)是可数的

    * 若\(F\subseteq_f\ZFC\)，由Mostowski collapsing定理，存在传递模型使得\((M,\in)\cong(N,\in)\)

      \(F\)相对于\(N\)绝对，但是\(F\)的子公式不一定绝对（比如\(\psi\)与\(\Pow\)）
    #+END_remark

    #+ATTR_LATEX: :options [ZFC]
    #+BEGIN_theorem
    对任意有穷公式集\(F\)，对任意集合\(N\)，存在集合\(M\)使得
    1. \(N\subseteq M\)
    2. \(\varphi_1,\dots,\varphi_n\)相对于\((M,\in)\)绝对
    3. \(\abs{M}\le\abs{N}+\aleph_0\)
    4. 若\(N\)至多可数，则\(M\)可数
    #+END_theorem

    #+BEGIN_proof
    不妨设\(F\)对于子公式封闭，令\(\calh_F\)为\(F\)对应的Skolem函数集，令\(M=\calh_F(N)\) （练习）
    #+END_proof

    #+ATTR_LATEX: :options [ZFC]
    #+BEGIN_corollary
    对任意有穷句子集\(F=\{\varphi_1,\dots,\varphi_n\}\)，对任意的传递集\(N\)，存在\(M\)满足
    1. \(N\subseteq M\)
    2. \(F\)相对于\((M,\in)\)是绝对的
    3. \(\abs{M}\le\abs{N}+\aleph_0\)
    4. \(M\)传递
    #+END_corollary

    #+BEGIN_proof
    不妨设外延公理\(\in F\)，则存在\((M',\in)\)满足\(1-3\)

    \((M',\in)\)良基似集合且满足外延公理

    故\(G:M'\to V\), \(x\mapsto\{G(y)\mid y\in M'\wedge y\in x\}\)是\(M'\)到\(M=G(M')\)的同构，\(M\)传递，由
    \(M'\)的绝对性, \(V\vDash\varphi_i\leftrightarrow\varphi_i^{M'}\)

    由同构
    \begin{equation*}
    \varphi_i^{M'}\Leftrightarrow M'\vDash\varphi_i\Leftrightarrow M\vDash\varphi_i\Leftrightarrow\varphi_i^M
    \end{equation*}
    故\(F\)相对于\(M\)绝对

    设\(N\subseteq M'\)传递，对\(N\)中元素的\(\rank\)归纳证明：\(\forall x\in N(G(x)=x)\)，即\(G(N)=N\subseteq M\)
    #+END_proof

    句子集的绝对性被同构保持，而公式不是这样（例子是幂集公理）

    #+BEGIN_remark
    若\(\varphi(x_1,\dots,x_n)\)是一个公式，且\((M,\in)\cong(M',\in)\)则\(\varphi\)相对于
    #+END_remark


** Exercise
    #+BEGIN_exercise
    label:ex7.10.3
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_exercise

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof

    #+BEGIN_exercise
    \(R\)是似集合的，则
    \(R\)是外延的当且仅当对任意\(x,y\in X\)
    \begin{equation*}
    x\neq y\to\pred(X,x,R)\neq\pred(X,y,R)
    \end{equation*}
    #+END_exercise

    #+ATTR_LATEX: :options [7.10.7]
    #+BEGIN_exercise
    证明莫斯托夫斯基定理中的\(\bM\)和\(\bG\)唯一
    #+END_exercise

    #+BEGIN_proof
    假设\(M,N\)是传递类且\(f:(M,\in)\cong(N,\in)\)，\(S=\{x\in M\mid f(x)\neq x\}\)。
    因为\(M\neq N\)，因此\(S\)非空，取\(S\)的极小元\(x_0\)，则对于任意\(y\in x_0\)，\(y=f(y)\in f(x_0)\)，
    于是\(x_0\subset f(x_0)\)，又因为\(f\)是双射，同理有\(f(x_0)\subset x_0\)，于是\(f(x_0)=x_0\)，矛盾。因此\(M=N\)。

    若\(f_1:(X,R)\cong(M,\in)\)，\(f_2:(X,R)\cong(N,\in)\)，则 \(M=N\)，于是\(f_1f_2=f_2f_1=\id\)，因此\(f_1=f_2\)
    #+END_proof

    #+ATTR_LATEX: :options [7.10.8]
    #+BEGIN_exercise
    证明以下概念对任意\(\ZF-\Pow\)的传递模型绝对
    1. \(X^{<\omega}\)
    #+END_exercise

    #+BEGIN_proof
    1. \(f\in X^{<\omega}\)当且仅当存在有穷序数\(n\)使得\(f\in X^n\)

    而任意这样的模型都有有穷序数
    #+END_proof

    #+ATTR_LATEX: :options [7.10.9]
    #+BEGIN_exercise
    \(V_\omega\vDash\ZF-\Inf+\neg\Inf\)
    #+END_exercise

    #+BEGIN_proof

    #+END_proof
