#+TITLE: Set Theory

#+EXPORT_FILE_NAME: ../latex/SetTheoryHao/SetTheoryHao.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
* Intro
    习题 40%

    考试 闭卷

    期中 8周

    集合 \(\{x,y,z,\dots\}\) 外延 \(\{x\mid x\text{ is ...}\}\) 内涵

    #+ATTR_LATEX: :options [Cantor-Bendixen]
    #+BEGIN_theorem
    闭集\(X\subseteq\R\) uncountable, then \(X=Y_1\cup Y_2\), where \(Y_1\) is countable and \(Y_2\) is perfect
    #+END_theorem

    if \(Y_2\) is perfect, then \(\abs{Y_2}=\abs{\R}\).

    Hence CH is true for close set

    Suppose \(X\) is a set and \(Y=\{x\mid x\in X\wedge x\not\in x\}\) is a set

    \(Y\in Y\) => \(Y\in X\) and \(Y\not\in Y\), a contradiction. Hence \(Y\not\in Y\).

    \(Y\not\in Y\) => \(Y\not\in X\) or \(Y\in Y\) => \(Y\not\in X\)

    Thus we have
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. For any set \(X\), there exists a set \(Y\) s.t. \(Y\not\in X\).
    2. collection of all sets is not a set
    #+END_proposition

    Notation: we call \(\{x\mid\varphi(x)\}\) a class

    \(V=\{x\mid x=x\}\), \(\{x\mid x\not\in x\}\) is not a set

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(\{x\mid x\neq x\}\) is a set
    #+END_proposition

    #+BEGIN_proof
    From Existential Axiom, there is a set \(X_0\).

    Claim: \(\{x\mid x\neq x\}=\{x\mid x\in X_0\wedge x\neq x\}\)

    for any \(z\), \(z\neq z\), we need to prove \(z\in X_0\). But \(z\neq z\) is always false.
    #+END_proof

    We write \(\emptyset=\{x\mid x\neq x\}\)

    For any set \(X\neq\emptyset\), its arbitrary intersection
    \begin{equation*}
    \bigcap X=\{u\mid\forall Y(Y\in X\to u\in Y)\}
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((x,y)=\{\{x\},\{x,y\}\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \((x,y)=(x',y')\Leftrightarrow x=x'\wedge y=y'\)
    #+END_proposition

    #+BEGIN_proof
    作业
    #+END_proof


    _partial ordering + well-founded => linear ordering_

    since for arbitrary \(\{x,y\}\), it has a minimal element

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any set \alpha, if \(\in\) is a well-ordering on \alpha, then \alpha is an *ordinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    successor of \(x\) is \(S(x)=x\cup\{x\}\)
    #+END_definition

    ordinal that is not 0 and successor is a limit ordinal

    极限是否存在

    let \(\omega=\{n\mid n=0\vee n\text{ is successor and }\forall m<n(m\text{ is successor})\}\)

    Then we need to show that \omega is a set. So we need new axiom

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(X\) 是归纳集，则\(\omega\subseteq X\)
    #+END_proposition

    #+BEGIN_proof
    Otherwise we have least \(n\in\omega\) and \(n\not\in X\). Let \(n=S(m)\), then \(m\in X\). Hence we get a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any \(X\subset\omega\), if \(X\) is inductive, then \(X=\omega\)
    #+END_theorem

    \([\varphi(0)\wedge\varphi(n)\to\varphi(n+1)]\Rightarrow\forall n\varphi(n)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \omega is a ordinal and is a limit ordinal
    #+END_theorem

    #+BEGIN_proof
    \(\in\) is a well-ordering on \omega, then we need show
    1. \(\in\) is a partial ordering
       1. transitive. let \(\varphi(x)\): if \(m<n\), then for any \(x\), \(n<x\to m<x\)

          \(x=0\)

          \(x=k+1\), \(n<k+1\), \(n\in k\cup\{k\}\). then \(n=k\) or \(n\in k\)
    2. \(\in\) is well-founded

       \(X\subseteq\omega\), \(X\neq\emptyset\), then \(\exists x_0\in X\). consider \(\omega-X\). Suppose \(X\) has no minimum element
       1. \(0\not\in X\Rightarrow 0\in\omega\)

       2. if \(n\in\omega-X\), then \(S(n)\in\omega-X\). Suppose \(n\not\in X\) and \(S(n)\in X\). Then \(S(n)\) is minimum

       then \(\omega-X\) is inductive



    for any \(\alpha<\omega\), \(S(\alpha)\neq\omega\), hence \omega is limit
    #+END_proof
