#+TITLE: Set Theory2

#+AUTHOR: Yao

#+EXPORT_FILE_NAME: ../latex/SetTheory2/SetTheory2.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \def \FORM {\text{FORM}}
#+LATEX_HEADER: \def \PROOF {\text{PROOF}}
* 集合的宇宙
** 数理逻辑
    在\(\ZFC\)下证明\(\ZFC\vdash\CH\)，希望将"\(\ZFC\vdash\CH\)"表述为一阶句子

    一般而言，给定一个\(\call\)-理论\(T\)和一个\(\call\)-句子\(\delta\)，"\(T\vdash\sigma\)"不能用一个\(\call\)-句子表示，只能
    用元语言表述

    我们需要在\(\ZFC\)中编码“元语言”

    在\(\ZFC\)中可以定义\(\caln=(\N,+,\times,0,1)\)

    即存在集合论语言\(\call=\{\in\}\)中的 *公式* ，在\(\ZFC\)的任意模型中可以定义 \(\N,+,\times,0,1\)，以上公式与模
    型无关

    用\(\ucorner{0}\)，\(\ucorner{1}\)，\(\ucorner{2}\)... 表示\(\ZFC\)中的“自然数”，以区别元语言中
    的自然数

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(R\subseteq\N^n\)是一个递归关系。\(T\subseteq\Th(\caln)\)是包含数论的适当丰富的理论，则存在公式\(\varphi(x_1,\dots,x_n)\)使
    得对任意自然数\(m_1,\dots,m_n\)有
    \begin{align*}
    &\text{如果}(m_1,\dots,m_n)\in R\text{则}T\vdash\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\\
    &\text{如果}(m_1,\dots,m_n)\notin R\text{则}T\vdash\neg\varphi(\ucorner{m_1},\dots,\ucorner{m_n})
    \end{align*}
    #+END_theorem

    #+BEGIN_remark
    1. \(T\subseteq\Th(\caln)\subseteq\ZFC\)
    2. \(\varphi\)是语言\(\{+,\times,0,1\}\)上的公式
    3. \(\varphi\)可以还原为一个\(\{\in\}\)上的公式
    4. \(\varphi(\ucorner{m_1},\dots,\ucorner{m_n})\)是一个闭语句
    #+END_remark

    *编码*

    编码函数\(f:X\to\N\)

    存在解码函数\(g,h\)，对\(a=a_0,\dots,a_n\in X\), \(h(f(a))=n+1\), \(g(f(a),k)=a_k\) (分量)

    性质：以上三种函数\(f,g,h\)均是递归函数\(\Rightarrow\)都是可表示的

    性质：“公式集”的编码集是递归的

    性质：如果\(T\subseteq\ZFC\)是可公理化的，则\(T\)的证明集的编码集是递归的

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    存在一个公式 \(\psi\) 和\(\theta\)使得
    \begin{align*}
    \ZFC\vdash\psi(n)&\Leftrightarrow n\text{ is a formula}\\
    \ZFC\vdash\neg\psi(n)&\Leftrightarrow n\text{ is not a formula}\\
    \ZFC\vdash\theta(n)&\Leftrightarrow n\text{ is a proof in }\ZFC\\
    \ZFC\vdash\neg\theta(n)&\Leftrightarrow n\text{ is not a proof in }\ZFC\\
    \end{align*}
    称\(\psi\)定义了公式集，\(\theta\)定义了证明集
    #+END_corollary

    \(\FORM=\{\ucorner{\varphi}\mid\varphi\text{ formula}\}\subseteq\N\)

    如果\(T\subseteq\ZFC\)是可公理化的，则“\(T\)是一致的”是一个一阶表述式
    “不存在一个有穷的证明序列\(D=(\varphi_1,\dots,\varphi_n)\)使得\(\varphi_n\)形如\(\varphi\wedge\neg\varphi\)
，记作\(\Con(T)\)

    #+ATTR_LATEX: :options [第二不完全]
    #+BEGIN_theorem
    如果\(T\)是包含\(\ZFC\)的一个递归公理集，且\(T\)一致，则
    \begin{equation*}
    T\not\vdash\Con(T)
    \end{equation*}
    特别地，\(\ZFC\not\vdash\Con(\ZFC)\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    对任意可公理化的理论\(T\)，\(\ZFC\vdash\Con(T)\)当且仅当存在\(M\vDash T\)
    #+END_theorem

    即不能在\(\ZFC\)里证明\(\ZFC\)有一个模型

    需要可公理化来写出\(\Con(T)\)，因此因为\(\ZFC\not\vDash\Con(T)\)，我们只能假设这么一个模型

    集合论的模型跟集合论没什么关系，就是一个集合带一个二元关系，是关于集合论语言的结构

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\((M,E)\)是集合论模型
    1. 对任意公式\(\varphi(\barx,y)\)，定义\(M^n\)上的函数
       \begin{equation*}
       h_\varphi:M^n\to M
       \end{equation*}
       满足条件
       \begin{equation*}
       M\vDash\exists y\varphi(\bara,y)\Rightarrow M\vDash\varphi(\bara,h_\varphi(\bara))
       \end{equation*}
       称\(h_\varphi\)为\(\varphi\)的Skolem函数（依赖于选择公理，不同的变量选择有不同的函数）
    2. 令\(\calh=\{h_\varphi\mid\varphi\text{ formula}\}\)为Skolem函数集合，设\(S\)是\(M\)的任意子集，则\(\calh(S)\)表示包
       含\(S\)且对\(\calh\)封闭的最小集合，称之为\(S\)的Skolem壳
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(N\)是集合论模型，\(S\subseteq N\)，如果\(M=\calh(S)\)，则\(M\prec N\)
    #+END_lemma

    #+BEGIN_proof
    Induction

    对任意\(\bara\in M^n\)，有\(M\vDash\varphi(\bara)\Leftrightarrow N\vDash\varphi(\bara)\)
    1. 不含量词，显然成立
    2. \(\varphi\)形如\(\exists y\psi(\barx,y)\), \(N\vDash\exists y\psi(\bara,y)\Rightarrow N\vDash\psi(\bara,h_\psi(\bara))\)，by
       IH, \(M\vDash\psi(\bara,h_\psi(\bara))\Rightarrow M\vDash\exists y\psi(\bara,y)\)
    #+END_proof

    #+ATTR_LATEX: :options [Löwenheim–Skolem Theorem]
    #+BEGIN_theorem

    #+END_theorem
** 层垒的谱系
    工作于\(\ZF^-\)：\(\ZF-\)基础公理

    \(\alpha\mapsto V_\alpha\)是\(\On\)到\(\WF\)的1-1映射，而\(\On\)是真类

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any ordinal \alpha
    1. \(V_\alpha\) is transitive
    2. \(\xi\le\alpha\Rightarrow V_\xi\subseteq V_\alpha\)
    3. if \kappa is inaccessible, then \(\abs{V_\kappa}=\kappa\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any \(x\in\WF\), *rank* of \(x\) is
    \begin{equation*}
    \rank(x)=\min\{\beta\mid x\in V_{\beta+1}\}
    \end{equation*}
    #+END_definition

    \(\rank(x)=\alpha\Rightarrow x\in V_{\alpha+1}\wedge x\notin V_\alpha\)

    - \(x\in V_{\alpha+1}\Leftrightarrow\rank(x)\le\alpha\)
    - \(x\subseteq V_\alpha\Leftrightarrow\rank(x)\le\alpha\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_lemma

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof

    * \(\WF\)中的集合按照秩分层
    * 在\(\WF\)中基础公理是成立的：\(\forall y(y\neq\emptyset\to\exists x\in y(x\cap y=\emptyset))\)，因为任何序数集都有最小元，挑一个有最
      小rank的就好了
    * \(\WF\)类的构造没有用到选择公理
    * \(\On\subseteq\WF\)


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    for any ordinal \alpha
    1. \(\alpha\in\WF\) and \(\rank(\alpha)=\alpha\)
    2. \(V_\alpha\cap\On=\alpha\)
    #+END_lemma

    #+BEGIN_proof
    1. \(0\in V_1\setminus V_0\subset\WF\), \(\rank(0)=0\)

       If \(\alpha\in\WF\)
       and
       \(\rank(\alpha)=\alpha\).
       \(\alpha\in V_{\alpha+1}\setminus V_\alpha\), \(\alpha\subseteq V_{\alpha+1}\). \(\alpha+1=\alpha\cup\{\alpha\}\subseteq V_{\alpha+1}\), \(\alpha+1\in V_{\alpha+2}\subset\WF\).
       If \(\alpha+1\in V_{\alpha+1}\), then \(\rank(\alpha+1)\le\alpha\), but \(\alpha\in\alpha+1\Rightarrow\rank(\alpha)=\alpha<\rank(\alpha+1)\). A
       contradiction

       suppose \gamma is a limit ordinal and for any \(\alpha<\gamma\), \(\alpha\in V_{\alpha+1}\setminus V_\alpha\).
       \(\gamma=\bigcup_{\alpha<\gamma}\alpha\subseteq\bigcup_{\alpha<\gamma}V_\alpha=V_\gamma\). Thus \(\gamma\in V_{\gamma+1}\), \(\rank(\gamma)\le\gamma\) and \(\rank(\gamma)\not<\gamma\).
    2. suppose \(\beta\in V_\alpha\cap\On\), then \(\beta=\rank(\beta)<\alpha\). If \(\beta\in\alpha\) and \(\rank(\beta)<\alpha\), \(\beta\in V_\alpha\cap\On\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    1. If \(x\in\WF\), then \(\bigcup x,\calp(x),\{x\}\in\WF\), and their rank \(<\rank(x)+\omega\)
    2. If \(x,y\in\WF\), then \(x\times y,x\cup y,x\cap y,\{x,y\},(x,y),x^y\in\WF\), and their
       rank \(<\rank(x)+\rank(y)+\omega\)
    3. \(\Z,\Q,\R\in V_{\omega+\omega}\)
    4. for any set \(x\), \(x\in\WF\Leftrightarrow x\subset\WF\)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \(\rank(x)=\alpha\). \(x\in V_{\alpha+1}\setminus V_\alpha\) and \(x\subseteq V_\alpha\).

       by transitivity, \(\bigcup x\subseteq V_\alpha\Rightarrow \bigcup x\in V_{\alpha+1}\subset\WF\). \(\rank(\bigcup x)\le\alpha\)

       suppose
       \(y\in\calp(x)\),
       \(y\subseteq x\Rightarrow y\subseteq V_\alpha\Rightarrow y\in V_{\alpha+1}\). \(\calp(x)\subseteq V_{\alpha+1}\), \(\calp(x)\in V_{\alpha+2}\), \(\rank(\calp(x))\le\alpha+1\).

       \(\{x\}\in\calp(x)\in V_{\alpha+2}\).

    2. Suppose \(\rank(x)=\alpha,\rank(y)=\beta\), \(x\subset V_\alpha\), \(y\subset V_\beta\)

       \(x\cup y\subset V_\alpha\cup V_\beta=V_{\max(\alpha,\beta)}\), \(\rank(x\cup y)\le\max(\alpha,\beta)\)

       \(x\cap y\subset V_{\min(\alpha,\beta)}\)

       \(\{x,y\}\subseteq V_{\alpha+1}\cup V_{\beta+1}=V_{\max(\alpha,\beta)+1}\), \(\rank(\{x,y\})=\max(\alpha,\beta)+1\)

       \((x,y)=\{\{x\},\{x,y\}\}\subset V_{\max(\alpha,\beta)+2}\). \(\rank((x,y))=\max(\alpha,\beta)+2\)

       \(x\times y=\{(a,b)\mid a\in x,b\in y\}\).
       \(a\in x\Rightarrow\rank(a)<\alpha\), \(b\in y\Rightarrow\rank(b)<\beta\), \(\rank(a,b)<\max(\alpha,\beta)+2\),
       \((a,b)\in V_{\max(\alpha,\beta)+2}\). \(x\times y\subseteq V_{\max(\alpha,\beta)+2}\), \(\rank(x\times y)\le\max(\alpha,\beta)+2\).

       \(x^y\subseteq\calp(x\times y)\subseteq V_{\max(\alpha,\beta)+3}\).

    3. \(\N=\omega\in V_{\omega+1}\)

       \(\Z\): let \(\sim\) be an equivalence relation on \(\omega\times\omega\), \((a,b)\sim(c,d)\Leftrightarrow a+d=b+c\),
       then \(\Z=(\omega\times\omega)/\sim\). Hence \(\Z\) is a partition of \(\omega\times\omega\) and
       hence \(\Z\subseteq\calp(\omega\times\omega)\). \(\Z\in V_{\omega+3}\)

       \(\Q\): let \(\sim\) be an equivalence
       on \(\Z\times\Z^+\), \((a,b)\sim(c,d)\Leftrightarrow ad=bc\). \(\Q\subseteq\calp(\Z\times\Z^+)\), \(\Q\in V_{\omega+6}\)

       \(\R\): set of dedekind cut on \(\Q\), \(\R\subset\calp(\Q)\), \(\R\in V_{\omega+8}\)

    4. \(\Rightarrow\): \(\WF\) is transitive

       \(\Leftarrow\): \(x\) is a set and \(x\subset\bigcup_{\alpha\in\On}V_\alpha\).

       *Claim*: there is an ordinal \alpha s.t. \(x\subset V_\alpha\)

       Otherwise, let \(f:\On\to\calp(x)\) s.t. \(f(\alpha)=x\setminus V_\alpha\). Then for any \(y\in\calp(x)\), \(f^{-1}(y)\) is
       a set. \(\On=\bigcup_{y\in x}f^{-1}(y)\) and is thus a set, a contradiction
    #+END_proof

    AC => Any set has cardinality
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume AC (\(V\vDash\ZFC\))
    1. for any group \(G\), there is a group \(G'\) in \(\WF\) s.t. \(G\cong G'\)
    2. for any topological space \(T\), there is a topological space \(T'\) in \(\WF\)
       s.t. \(T\cong T'\) (homeomorphic)
    #+END_lemma

    #+BEGIN_proof
    1. suppose \((G,*_G)\) is a group, \(G,*_G\in V\). By AC, there is a cardinal \alpha
       s.t. \(\abs{G}=\alpha\), that is, there is a bijection \(f:\alpha\to G\). Define \(*\): for
       any \(x,y,z\in\alpha\), \(x*y=z\Leftrightarrow f(x)*_Gf(y)=f(z)\). Then \((\alpha,​*)\cong(G,​*_G)\), \(​*\subseteq\alpha\times\alpha\)
    #+END_proof

    \(V\)中的任何结构都可以在\(\WF\)中找到同构象（同构是在\(V\)里看到的）

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    任意集合\(A\)上的二元关系<是 *良基* 的，当且仅当对\(A\)的任意非空子集\(X\)，\(X\)有<下的极小元
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(A\in\WF\), then \(\in\) is a well-founded relation on \(A\)
    #+END_theorem

    #+BEGIN_proof
    suppose \(X\subseteq A\), \(X\neq\emptyset\), \(X\subseteq\WF\), then elements of \(X\) has ranks
    and \(x\in y\Rightarrow\rank(x)<\rank(y)\). Let \(x\) having least rank in \(X\), then \(x\) is
    the \(\in\)-minimal element in \(X\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \(A\) is a transitive set and \(\in\) is a well-founded relation on \(A\), then \(A\in\WF\)
    #+END_lemma

    #+BEGIN_proof
    Just need to prove \(A\subset\WF\). If \(A\not\subset\WF\), \(X=A\setminus\WF\neq\emptyset\). Then \(X\) has a \(\in\)-minimal
    element \(x\). Then \(x\neq\emptyset\in\WF\). For any \(y\in x\), \(y\in A\). By the minimality
    of \(x\), \(y\in\WF\). Then \(x\subset\WF\), \(x\in\WF\), a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any set \(x\), there is a minimal transitive set \(\trcl(x)\) s.t. \(x\subseteq\trcl(x)\)
    #+END_lemma

    #+BEGIN_proof
    For any \(n\in\omega\) define \(x_n\)
    \begin{align*}
    x_0&=x\\
    x_{n+1}&=\bigcup x_n
    \end{align*}
    let \(\trcl(x)=\bigcup_{n\in\omega}x_n\).
    1. \(\trcl(x)\)is transitive

       \(a\in\trcl(x)\Rightarrow a\in x_n\Rightarrow a\subseteq x_{n+1}\subseteq\trcl(x)\)
    2. \(\trcl(x)\) is minimal

       If \(y\supseteq x\) is transitive, recursively prove for any \(n<\omega\), \(x_n\subseteq y\).
    #+END_proof

    \(\trcl(x)\) is the *transitive closure* of \(x\).

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    We can prove the following without axiom of power set
    1. if \(x\) is transitive, \(\trcl(x)=x\)
    2. \(y\in x\Rightarrow\trcl(y)\subseteq\trcl(x)\)
    3. \(\trcl(x)=x\cup\bigcup\{\trcl(y)\mid y\in x\}\)
    #+END_lemma

    #+BEGIN_proof
    2. [@2] \(y\in x\subset\trcl(x)\). \(y\in\trcl(x)\). \(\trcl(y)\subseteq\trcl(x)\).
    3. \(x\cup\bigcup\{\trcl(y)\mid y\in x\}\subseteq\trcl(x)\) by (2)

       \(\bigcup\{\trcl(y)\mid y\in x\}\) is transitive. For \(y\in x\), \(y\subseteq\trcl(y)\). Thus rhs is transitive
    #+END_proof


    #+ATTR_LATEX: :options [In \(\ZFm\)]
    #+BEGIN_theorem
    For any set \(X\), TFAE
    1. \(X\in\WF\)
    2. \(\trcl(X)\in\WF\)
    3. \(\in\) is a well-founded relation on \(\trcl(X)\)
    #+END_theorem

    #+BEGIN_proof
    \(1\to 2\): \(\WF\) is closed under union
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    If \(V\vDash\ZFm\), TFAE
    1. axiom of foundation (\(V\vDash\)) axiom of foundation
    2. for any set \(X\), \(\in\) is a well-founded relation on \(X\)
    3. \(V=\WF\)
    #+END_theorem

    \(V\vDash\ZF\Rightarrow V=\WF(\WF\vDash\ZF)\)

    Goal:  \(V\vDash\ZFm\Rightarrow\WF\vDash\ZFm\)
    但是\(\WF\)是一个类，我们并没有定义

    我们可以用相对化编码\(\WF\vDash\ZFm\)
** 相对化 relativization
    工作在\(\ZFm\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(M\) class, \(\varphi\) formula, \(\varphi\)对\(M\)的 *相对化* \(\varphi^{M}\)
    1. \((x=y)^{M}:=x=y\)
    2. \((x\in y)^{M}:=x\in y\)
    3. \((\varphi\to\psi)^{M}:=\varphi^{M}\to\psi^{M}\)
    4. \((\neg\varphi)^{M}:=\neg\varphi^{M}\)
    5. \((\forall x\varphi)^{M}:=(\forall x\in M)\varphi^{M}\)
    #+END_definition
    \(\varphi^{M}\)读作“\(\varphi\)在\(M\)中为真”，表示为\((M,\in)\subseteq(V,\in)\)有\(M\vDash\varphi\)，即如果\(V\vDash\varphi^{M}\)，那
    么\(M\vDash\varphi\)，而\(V\)知道得更多一点

    重新定义了满足

    若\(M\)被公式\(M(u)\)定义，\((\forall x\varphi)^{M}\)是公式\(\forall x(M(x)\to\varphi^{M}(x))\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(M=\On\)，\(\On\vDash\forall x\forall y(x\in y\vee y\in x\vee x= y)\)
    #+END_examplle

    "\(M\vDash\varphi\)"可以形式化为\(V\vDash\varphi^M\)，而\(M\)对应于\(M(u)\)，即等价于\(T\vdash\varphi^M\)，如果我们工作在某个\(T\)
    上

    若函数\(f\)被公式\(\varphi(\barx,y)\)定义，则\(V\vDash\forall\barx\exists!y\varphi(\barx,y)\)，但相对化后不一定对，因此
    \(f^M=\{(\barx,y)\in M:\varphi^M(\barx,y)\}\)不一定是\(M\)上的函数

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    for any theory \(T\), any class \(M\), \(M\) is a *model* of \(T\), \(M\vDash T\), iff for any axiom
    \varphi of \(T\), \(\varphi^M\) holds, i.e., \(V\vDash\varphi^M\)
    #+END_definition

    \(V\)中定义出语义

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \(V\vDash\ZFm\Rightarrow\WF\vDash\ZF-\Inf\)，

    \(V\vDash(\ZF-\Inf)^{\WF}\)
    等价的
    \(\ZFm\vdash(\ZF-\Inf)^{\WF}\)
    #+END_theorem

    * *存在公理* ：\(\exists x\in M(x=x)\)
    * *外延公理* ：\(\Ext^M\)
      \begin{equation*}
      \forall x\in M\forall y\in M\forall u\in M((u\in X\leftrightarrow u\in Y)\to X=Y)
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) is transitive, then \(\Ext^M\) holds
      #+END_lemma

      #+BEGIN_proof
      suppose \(X,Y\in M\), if \(X\neq Y\), then there is \(u\in X\triangle Y\) (by \(\Ext\) in \(V\)), by
      transitivity, \(u\in M\)
      #+END_proof
    * 分离公理模式：for any \(M\), any formula \varphi, \(S(\varphi)^M\)
      \begin{equation*}
      \forall x\in M\exists Y\in M\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))
      \end{equation*}
      Therefore, if for any \(X\in M\), \(\{u\in X\mid\varphi^M(x)\}\in M\), then 分离公理模式在\(M\)中为真
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) satisfies \(x\in M\Leftrightarrow x\subset M\), then \(S(\varphi)^M\) holds for any \(M\)
      #+END_lemma

      #+BEGIN_proof
      Suppose \(X\in M\), suffices to find corresponding \(Y\in M\) s.t. \(\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\)

      根据\(V\)中的分离公理, \(Y=\{x\in X\mid\varphi^M(u)\}\in V\) and \(Y\subseteq X\subset M\), thus \(Y\in M\) and
      \(\forall u(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\). But \(x\in Y\Rightarrow x\in M\), thus this is equivalent to
      \(\forall u\in M(u\in Y\leftrightarrow u\in X\wedge\varphi^M(u))\)
      #+END_proof
    * *axiom of pairing* Pair
      \begin{equation*}
      \forall x\in M\forall y\in M\exists z\in M\forall u\in M(u\in z\leftrightarrow u= x\vee u=y)
      \end{equation*}
      只要\(M\)对对集函数\(x,y\mapsto\{x,y\}\)封闭，则\(Pair^M\)成立
    * 幂集公理 \(Pow\)
      \begin{equation*}
      \forall X\in M\exists Y\in M\forall u\in M(u\in Y\leftrightarrow\forall a\in M(a\in u\to a\in X))
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) satisfies \(x\in M\Leftrightarrow x\subset M\), then \(Pow^M\) holds
      #+END_lemma

      #+BEGIN_proof
      for any \(X\in M\), \(\calp(X)\in M\). and we prove \(\calp(X)\) is the \(Y\), for any \(u\in M\)
      #+END_proof
    * *axiom of infinity* \(Inf\)
      \begin{equation*}
      \exists X\in M(\emptyset\in X\wedge\forall y\in M(y\in X\to y^+\in X))
      \end{equation*}
      \(\emptyset:\psi(x):=\forall u(u\in x\to u\neq u)\), \(x=\emptyset\Leftrightarrow\psi(x)\)

      \(y^+:\varphi(y,z):\forall u\in z(u=y\vee u\in y)\wedge y\subseteq z\wedge y\in z\)
      函数相对化后不一定是函数，所以放到下一节
    * *axiom of foundation* Fod
      \begin{equation*}
      \forall x\in M(\exists u\in M(u\in x)\to\exists y\in M(y\in x\wedge\neg\exists u\in M(u\in x\wedge u\in y)))
      \end{equation*}
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      If \(M\) is transitive and elements of \(M\) is well-founded under \(\in\), then \(Fod^M\) holds
      #+END_lemma

      #+BEGIN_proof
      suppose \(x_0\in M\) and there is

      \(\psi:=\exists u(u\in x)\) and \(\varphi\) is the latter part

      \(\psi^M(x_0)\leftrightarrow\exists u(u\in x_0)\) since \(M\) is transitive, \(\varphi^M(x_0)\leftrightarrow\exists y(y\in x_0\wedge\neg\exists u\in M(u\in x\wedge u\in y))\)

      在\(V\)中,\(x_0\neq\emptyset\)，由条件可知\((x_0,\in)\)是良基的，于是\(\varphi\)在\(V\)中对，那么当然在\(M\)中对
      #+END_proof
    * *替换公理模式* \(Rep(\varphi)\)
      \begin{equation*}
      \forall A\in M\forall x\in A\cap M\exists !y\in M\varphi^M(x,y)\to\exists B\in M\forall x\in A\exists y\in B\varphi^M(x,y)
      \end{equation*}
      \(\exists!y\theta(y):\exists y(\theta(y)\wedge\forall y'(\theta(y')\to y=y'))\)
      #+ATTR_LATEX: :options []
      #+BEGIN_lemma
      if \(M\) satisfied \(x\in M\Leftrightarrow x\subset M\), then \(Rep(\varphi)^M\) holds for any \varphi
      #+END_lemma

      #+BEGIN_proof
      for any \(A_0\in M\), then \(A_0\cap M=A_0\), thus we have
      \(\forall x\in A_0\exists!y(\varphi^M(x,y)\wedge M(y))\).

      by \(Rep(\varphi^M(x,y)\wedge M(y))\),
      \(\exists B'\forall x\in A_0\exists y\in B'\varphi^M(x,y)\wedge M(y)\)

      Let \(B=B'\cap M\), which is what we want
      #+END_proof

      Thus in \(\ZFm\), we can prove \(\WF\vDash\ZF-\inf\)
** 绝对性
    \((V,\in)\supseteq(M,\in)\)

    对于哪些\(\varphi\)，有\(V\vDash\varphi\Leftrightarrow M\vDash\varphi\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    公式\(\psi(\barx)\)，对任意类\(M\subseteq N\)，如果
    \begin{equation*}
    \forall\barx\in M(\psi^M(\barx)\leftrightarrow\psi^N(\barx))
    \end{equation*}
    就称\(\psi(\barx)\)对于\(M,N\)是 *绝对的* ，如果\(N=V\)，则称\(\psi(\barx)\)对于\(M\)是 *绝对的*
    #+END_definition

    \(\bara\in M\), \((M,\in)\vDash\psi(\bara)\Leftrightarrow V\vDash\psi^M(\bara)\)

    \(\psi\)相对于\(M,N\)绝对：\(\forall\bara\in M\),有\(M\vDash\psi(\bara)\Leftrightarrow N\vDash\psi(\bara)\)

    if \(\forall\varphi(\barx)\in L\)，均有\(\varphi\)相对于\(M,N\)绝对的，则\(M\preceq N\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    suppose \(M\subseteq N\), \(\varphi,\psi\) formula
    1. 如果\(\varphi,\psi\)相对于\(M,N\)绝对， so are \(\neg\varphi,\varphi\to\psi\)
    2. if \varphi is q.f., then \(\varphi\)对任意\(M\)绝对
    3. if \(M\) are transitive, and \(\varphi\)相对于它们绝对， so is \(\forall x\in y\varphi\)
    #+END_lemma

    #+BEGIN_proof
    3. [@3] \(\forall x\in y\varphi:=\forall x(x\in y\to\varphi(x,y,\barz))\)，故\((\forall x\in y\varphi)^M=\forall x\in M(x\in y\to\varphi^M(x,y,\barz))\)，任取
       \(y_0,\barz_0\in M\),则由\(M\)的传递性，都有\(x\in y_0\Rightarrow x\in M\)

       目标：\(\forall x\in M(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)当且仅当\(\forall x\in N(x\in y_0\to\varphi^N(x,y_0,\barz_0))\)

       由\(\varphi\)的绝对性，对每个\(x_0\in M\)，有
       \begin{equation*}
       \varphi^M(x_0,y_0,\barz_0)\leftrightarrow\varphi^N(x_0,y_0,\barz_0)
       \end{equation*}
       故\(V\vDash\forall x\in M(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)，当且仅当
       \(V\vDash\forall x(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)当且仅当
       \(V\vDash\forall x\in N(x\in y_0\to\varphi^M(x,y_0,\barz_0))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    令\(M\subseteq N\)且\(M\)传递，\(\psi(\barx)\)是一个公式，则
    1. 如果\(\psi\)是\(\Delta_0\)公式，则他它对\(M,N\)是绝对的
    2. 如果\(\psi\)是\(\Sigma_1\)公式，则
       \begin{equation*}
       \forall\barx\in M(\psi^M(\barx)\to\psi^N(\barx))
       \end{equation*}
    3. 如果\(\psi\)是\(\Pi_1\)公式，则
       \begin{equation*}
       \forall\barx\in M^n(\psi^N(\barx)\to\psi^M(\barx))
       \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    1. 对公式的长度进行归纳证明
    2. 例子：令\(M=\On\),\(N=\WF\)，令\(\psi(y):=\forall x\in y\forall u,v\in x(u\in v\vee v\in u\vee u=v)\)，则\(\psi\)是\(\Delta_0\)的，
       则
       \begin{align*}
       &\psi^M(y)=\forall x\in M(x\in y\to\forall u,v\in M(u,v\in x\to(u\in v\vee v\in u\vee u=v)))\\
       &\psi^N(y)=\forall x\in N(x\in y\to\forall u,v\in N(u,v\in x\to(u\in v\vee v\in u\vee u=v)))
       \end{align*}
       任取\(x_0\in\WF\setminus\On\)使得\((x_0,\in)\)不是线序，令\(y_0=\{x_0\}\)，则\(\psi^M(y_0)\)的前件假，
       \(\psi^M(y_0)\)是真的，\(\psi^N(y_0)\)为假，因此
       \begin{equation*}
       \forall\barx(\psi^M(\barx)\to\psi^N(\barx))
       \end{equation*}
       错误

       令\(x=\barx,y=\bary\)

       设\(\psi:=\exists\varphi(x,y)\)，\(\varphi(x,y)\in\Delta_0\), \(\psi^M:=\exists y\in M(\varphi^M(x,y))\), \(\psi^N:=\exists y\in N(\varphi^N(x,y))\)，任取
       \(a\in M^m\)，目标\(\psi^M(a)\to\psi^N(a)\)

       若\(\psi^M(a)\)成立，则有\(b\in M^n\)使得\(\psi^M(a,b)\)，由\(\Delta_0\)的绝对性，\(\psi^N(a,b)\)，因此\(\exists y\psi^N(a,y)\)
    3. 设\(\psi:=\forall y\varphi(x,y)\)其中\(\varphi\in\Delta_0\)，则\(\psi^M:=\forall y\in M\varphi^M(x,y)\)，\(\psi^N:=\forall y\in N\varphi^N(x,y)\)，设\(a\in M\)使
       得\(\psi^N(a)\)成立，目标\(\psi^M(a)\)成立。

       \(\psi^N(a)\Rightarrow\)对所有的\(b\in N\)均有\(\varphi^N(a,b)\)成立，故对一切\(b\in M\)有\(\varphi^N(a,b)\)成立，由\(\varphi\)的绝
       对性，\(\forall y\in M\varphi^M(a,y)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(M\subseteq N\)，均是句子集\(\Sigma\)的模型，而\(\Sigma\vdash\forall\barx(\varphi(\barx)\leftrightarrow\psi(\barx))\)，则\(\varphi\)对\(M\)与\(N\)绝对
    当且仅当\(\psi\)也是
    #+END_lemma

    #+BEGIN_proof
    \(M,N\vDash\forall\barx(\varphi(\barx)\leftrightarrow\psi(\barx))\)

    \(\forall\barx\in M^n(\varphi^M(\barx)\leftrightarrow\psi^M(\barx))\)，\(\forall\barx\in N^n(\varphi^N(\barx)\leftrightarrow\psi^N(\barx))\)

    若\(\varphi\)是绝对的,\(\forall\barx\in M^n(\varphi^M(\barx)\leftrightarrow\varphi^N(\barx))\)

    因此\(\forall\barx\in M^n(\psi^M(\barx)\leftrightarrow\psi^N(\barx))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    假设\(M\subseteq N\)，\(f(x_1,\dots,x_n)\)是函数（类），设\(f(x_1,\dots,x_n)\)被公式\(\varphi(x_1,\dots,x_n,y)\)定义，称\(f\)相对
    于\(M,N\)是绝对的，是指
    1. \(\varphi(x_1,\dots,x_n,y)\)相对于\(M,N\)绝对
    2. \(\forall\barx\in M^n\exists!y\in M(\varphi^N(\barx,y))\)
    #+END_definition

    由上一引理，\(f\)的绝对性与定义\(f\)的公式无关

    \(f^M=\{(x_1,\dots,x_n,y)\in M^{n+1}\mid\varphi^M(\barx,y)\}\),\(f\uhr M=\{(x_1,\dots,x_n,y)\in M^{n+1}\mid\varphi(\barx,y)\}\)

    \(f\)是绝对的当且仅当\(\forall\barx M\forall y\in M(\varphi(\barx,y)\leftrightarrow\varphi^M(\barx,y))\)当且仅当\(\varphi(M^n,M)=\varphi^M(M^n,M)\)，
    即\(f\uhr M=f^M\)

    即对任意\(\bara\in M^n\)，有\(f\uhr M(\bara)=f^M(\bara)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下关系和函数可以在\(\ZFm-\Pow-\Inf\)中用公式定义，且在\(\ZFm-\Pow-\Inf\)下等价于一
    个\(\Delta_0\)-formula
    1. \(x\in y\)
    2. \(x=y\)
    3. \(x\subset y\)
    4. \(\{x,y\}\)
    5. \(\{x\}\)
    6. \((x,y)\)
    7. \(\emptyset\)
    8. \(x\cup y\)
    9. \(x\cap y\)
    10. \(x-y\)
    11. \(x^+=x\cup\{x\}\)
    12. \(x\)传递
    13. \(\bigcup x\)
    14. \(\bigcap x\)，且\(\bigcap\emptyset=\emptyset\)

    #+END_theorem

    #+BEGIN_proof
    4. [@4] 函数\(z=\{x,y\}\)被公式\(\forall u\in z(u=x\vee u=y)\wedge(x\in z\wedge y\in z)\)
    5. \(y=\{x\}\)被公式\(\forall u\in y(u=x)\wedge (x\in y)\)
    6. 函数\(z=(x,y)\)被公式\(\forall u\in z(u=x\vee x=\{x,y\})\wedge x\in z\wedge \exists  u\in z(u=\{x,y\})\)
    7. \(\forall y\in x(y\neq y)\)
    8. 函数\(z=x\cup y\)被公式\(\forall x\subset z\wedge y\subset z\wedge\forall u\in z(u\in x\vee u\in y)\)
    9. 函数\(z=x\cap y\)被公式\(z\subset x\wedge z\subset y\wedge\forall u\in x(u\in y\to u\in z)\)
    10. 函数\(z=x-y\) \(\forall u\in z(u\in x\wedge u\notin y)\wedge \forall u\in x(u\notin y\to u\in z)\)
    11. 函数\(z=x^+\) \(\forall u\in z(u\in x\vee u=x)\wedge x\in z\wedge x\subset z\)
    12. \(\forall y\in x(y\subset x)\)
    13. 函数\(z=\bigcup x\), \(\forall u\in z\exists y\in x(u\in y)\wedge\forall u\in x(u\subset z)\)
    14. 函数\(z=\bigcap x\), \(x=\emptyset\to z=\emptyset\wedge\forall u\in z\forall y\in x(u\in y)\wedge\exists y\in x\forall u\in z(\forall w\in x(u\in w)\to u\in z)\)

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(M\)是一个传递类，\(f\)是一个被\(\Delta_0\)公式定义的函数，如果\(f\)在\(M\)上封闭，
    即\(f(M^n)\subseteq M\),则\(f\)相对于\(M\)绝对
    #+END_lemma

    #+BEGIN_proof
    设\(f\)被\(\varphi(\barx,y)\)定义，\(\forall\barx,y\in M(\varphi(\barx,y)\leftrightarrow\varphi^M(\barx,y))\),\(\forall\barx\in M\exists!y\in M(\varphi(\barx,y))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    之前的函数均在\(\ZFm-\Pow-\Inf\)的传递模型\(M\)中绝对的

    \(\ZFm-\Pow-\Inf\)能够保证函数封闭，传递性保证定义它们的公式的绝对性
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    绝对性对复合运算封闭，即假设\(M\subseteq N\),公式\(\varphi(x_1,\dots,x_n)\)函
    数\(f(x_1,\dots,x_n)\), \(g_i(y_1,\dots,y_m)\),\(1\le i\le n\)都相对于\(M,N\)绝对，则
    \(\varphi(g_1(y_1,\dots,y_m),\dots,g_n(y_1,\dots,y_m))\)与\(f(g_1(y_1,\dots,y_m),\dots,g_n(y_1,\dots,y_m))\)也相对于\(M,N\)绝对
    #+END_lemma

    #+BEGIN_proof
    不妨设\(m=n=1\)

    设\(g(y)=z\)被\(\theta(y,z)\)定义，\(\varphi(g(y)):=\exists z(\theta(y,z)\wedge\varphi(z))\)

    \(\varphi^M(g(y)):=\exists z\in M(\theta^M(y,z)\wedge\varphi^M(z))\),\(\varphi^N(g(y)):=\exists z\in N(\theta^M(y,z)\wedge\varphi^M(z))\)

    由绝对性
    \(\forall z\in M\forall y\in M(\theta^M(y,z)\wedge\varphi^M(z)\leftrightarrow\theta^N(y,z)\wedge\varphi^N(z))\)

    任取\(y_0\in M\)，设\(\exists z\in N(\theta^N(y_0,z)\wedge\varphi^N(z))\)，由函数\(g(y)=z\)的绝对性，
    \(\forall y\in M\exists! z\in M(\theta^N(y,z))\)，存在唯一的\(z_0\in M\)使得
    \(\theta^N(y_0,z_0)\wedge\varphi^N(z_0)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    以下关系和函数对任意\(\ZFm-\Pow\Inf\)的传递模型\(M\)都是绝对的
    1. \(z\)是有序对
    2. \(A\times B\)
    3. \(R\)是关系
    4. \(\dom(R)\)
    5. \(\ran(R)\)
    6. \(f\)是函数
    7. \(f(x)\)
    8. \(f\)是一一函数
    #+END_theorem

    #+BEGIN_proof
    1. "\(z\)是有序对"：\(\exists u,v(z=(u,v))\)，但是这不是\(\Delta_0\)，因此考虑
       \(\exists u\in\bigcup z\exists v\in\bigcup z(z=(u,v))\)，注意这里不是平常的受囿量词，但是
       令\(g_1(z)=\bigcup z\), \(g_2(z)=\bigcup z\), \(g_3(z)=z\), \(\varphi(x_1,x_2,x_3):=\exists u\in x_1\exists v\in x_2(x_3=(u,v))\)，则
       \(g_1,g_2,g_3,\varphi\)绝对，故\(\varphi(g_1(z),g_2(z),g_3(z))\)绝对
    2. 函数\(z=x\times y\): \(\forall u\in z\exists s\in x\exists t\in y(u=(s,t))\wedge\forall s\in x\forall t\in y\exists u\in z(u=(s,t))\)
    3. \(R\)是关系\(\Leftrightarrow\)\(\forall u\in R(u\text{是有序对})\)
    4. 函数，\(D=\dom(R)\): \(\forall x\in D\exists z\in R\exists u\in z\exists y\in u(z=(x,y))\)且
       \(\forall z\in R\forall u\in z\forall x\in u\forall y\in u(z=(x,y)\to x\in D)\)
    5. 同理
    6. \(f\text{是关系}\wedge\forall x\in\dom(f)\exists!y\in\ran(f)\exists u\in f(u=(x,y))\)
    7. \(\varphi(f(x))\)表示\(f\)是函数且\(x\in\dom(f)\),则"\(y=f(x)\)"定义为
       \(\varphi(f,x)\to\exists u\in f(u=x,y)\vee(\neg\varphi(f,x)\to y\neq\emptyset)\)
    8. "\(f\)是函数"且\(\forall s\in\dom(f)\forall t\in\dom(f)(f(s)=f(t)\to s=t)\)
    #+END_proof
** 基础公理的相对一致性
    如果\(\ZFm\)一致，则\(\ZF\)一致

    目标：\(V\vDash\ZFm\)，证明\(\WF\vDash\ZF\)，等价于\(\ZFm\vdash(\ZF)^{\WF}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若传递类\(M\)是\(\ZFm-\Pow-\Inf\)的模型，且\(\omega\in M\)，则无穷公理在\(M\)中为真，因此无穷公理
    在\(\WF\)中为真（\(\ZFm\vdash(\Inf)^{\WF}\)）
    #+END_lemma

    #+BEGIN_proof
    - 由于\(\emptyset\)与\(x^+\)都被\(\Delta_0\)公式定义
    - 若\(M\vDash\ZFm-\Pow-\Inf\)，则\(x^+\)在\(M\)中封闭，且\(\emptyset\in M\)
    - \(\emptyset^M=\emptyset\), \((x^+)^M=x^+\)
    - 无穷公理的相对化为\(\exists x\in M(\emptyset\in x\wedge\forall y\in x(y^+\in x))\)
    - 即\(\exists x\in M(\emptyset\in M\wedge\forall y\in x(y^+\in x))\)
    - 由于\(\omega\in M\)，令\(x=\omega\)
    #+END_proof

    结论： \(\WF\vDash\ZF\)


    目标：\(Con(\ZFm)\vdash Con(ZF)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    设\(T\) (\(\ZFm\))是集合论的的理论，\(\Sigma\) (\(\ZF\))是一个句子集， 设\(M\)是一个类且非空，如
    果\(T\vdash(M\vDash\Sigma)\)，即\(T\vdash\Sigma^M\)或者“若\(V\vDash T\)，则\(V\vDash\Sigma^M\)”，则
    1. 对集合论语言的任何语句\(\varphi\)，如果\(\Sigma\vdash\varphi\)，则\(T\vdash\varphi^M\)
    2. 如果\(T\)一致，则以\(\Sigma\)为公理的理论也一致
    #+END_theorem

    #+BEGIN_proof
    1. 设\(\varphi_1,\dots,\varphi_n=\varphi\)是\(\Sigma\)的一个证明，对\(k\le n\)，归纳证明\(T\vdash\varphi_k^M\)
       - 若\(\varphi_i\in\Sigma\cup Ax\),\(Ax\)一阶逻辑的公理，\(T\vdash\varphi_i^M\)
       - 若\(i,j<k\)使得\(\varphi_j=\varphi_k\to\varphi_k\)，由归纳假设\(T\vdash\varphi_i^M\), \(T\vdash\varphi_i^M\to\varphi_k^M\),因此\(T\vdash\varphi_k^M\)
    2. 若\(\Sigma\)不一致，则存在\(\varphi\)使得\(\Sigma\vdash\varphi\wedge\neg\varphi\)，从而\(T\vdash(\varphi\wedge\neg\varphi)^M\)，故\(T\)不一致
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    基础公理相对于\(\ZFm\)一致，即如果\(\ZFm\)一致，则\(\ZF\)一致
    #+END_theorem

    #+BEGIN_proof
    - \(\ZFm\vdash(\ZF)^{\WF}\)
    - 故\(\ZFm\)一致能推出\(\ZF\)一致
    #+END_proof

    选择公理：任何非空集合都可被良序化
    \(\forall X\exists R(R\text{是$X$上的良序})\)
    1. \(R\subseteq X\times X\)
    2. \(R\)是线序
    3. \(\forall Y\subseteq X\), \(Y\neq\emptyset\Rightarrow \)Y存在\(R\)-极小元


    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_lemma
    设\(M\)是\(\ZFm-\Pow-\Inf\)的传递模型，如果\(X,R\in M\)并且\(R\)是\(X\)上的一个良序，
    则\((R\text{是$X$的良序})^M\)
    #+END_lemma

    #+BEGIN_proof
    “\(R\)是\(X\)上的线序”被公式\(\varphi(X,R)\)表达
    - \(R\)是关系
    - \(\forall x\in X(\neg R(x,x))\)
    - \(\forall x,y,z\in X(R(x,y)\wedge R(y,z))\to R(x,z)\)
    - \(\forall x,y\in X(R(x,y)\vee R(y,x)\vee x=y)\)

      \(R(x,y)\)表示\((x,y)\in R\),\(\exists z\in R(z=(x,y))\)


    因此\(\varphi(X,R)\)是\(\Delta_0\)-公式

    令公式\(\psi(X,Y,R)\)为\(Y\subseteq X\wedge Y\neq\emptyset\to\exists y\in Y\forall x\in Y(\neg R(x,y))\)，则\(\psi(X,Y,R)\)是\(\Delta_0\)-公式，
    “\(R\)是\(X\)上的良序”可以表达为\(\theta(X,Y)=\varphi(X,R)\wedge\forall Y\psi(X,Y,R)\)

    则\(\theta\)是一个\(\Pi_1\)-公式

    \(\forall X\in  M\forall R\in M(\theta(X,R)\to\theta^M(X,R))\)，任取\(X_0,R_0\in M\)使得\(R_0\)是\(X_0\)上的良序，
    则\(\theta(X_0,R_0)\)，故\(\theta^M(X_0,R_0)\)也成立，即
    #+END_proof

    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_theorem
    \(V_\omega\)是\(\ZFC-\Inf+\neg\Inf\)的模型
    #+END_theorem

    #+BEGIN_proof
    与\(\WF\)类似，\(V_\omega\)是传递的，且关于\(\{x,y\}\),\(\bigcup x\),\(\calp(x)\)封闭，故而是\(\ZF-\Inf\)的模型
    （练习）

    \(\neg\Inf\): \(\forall x\neg(\emptyset\in X)\wedge\forall y\in x(y^+\in x)\)

    \(\neg\Inf^M\): \(\forall x\in M(\emptyset^M\in X\wedge\forall y\in x((y^+)^M\in x))\)

    由于\(M=V_\omega\)传递，故\((\neg\Inf)^M\): \(\forall x\in M(\emptyset\in X\wedge\forall y\in x(y^+\in x))\)

    由于\(V_\omega\)中没有无穷集，故\((\neg\Inf)^M\)在\(V\)中成立

    \(AC^M\):任取\(X\in V_\omega\),若\(X\neq\emptyset\)，存在\(R\in V_\omega\)使得\(R\)是\(X\)上的良序

    \(\rank(\calp(x\times y))<\max(\rank(x),\rank(y))\)，故
    \(\calp(x\times x)\in V_\omega\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(Con(\ZFm)\vdash Con(\ZFC-\Inf+\neg\Inf)\)
    #+END_corollary
** 基于良基关系的归纳与递归
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    类\(R\)（\(\varphi(x,y)\)）是类\(X\)（\(\psi(x)\)）上的良基关系当且仅当
    \begin{equation*}
    \forall U\subset X(U\neq\emptyset\to\exists y\in U(\neg\exists z\in U(zRy)))
    \end{equation*}
    \(U\)是集合
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\in\)是\(\On\)上的良基关系

    如果\(Fud\)成立，则\(\in\)是\(V\)上的良基关系
    #+END_examplle

    #+ATTR_LATEX: :options [超穷归纳原理]
    #+BEGIN_theorem
    设\(\varphi(x)\)是一个公式，若\(\forall\alpha\in On\)有\(\forall\beta(\beta<\alpha\to\varphi(\beta))\to\varphi(\alpha)\)，则\(\forall\alpha\in\On(\varphi(\alpha))\)
    #+END_theorem

    #+ATTR_LATEX: :options [超穷递归定理]
    #+BEGIN_theorem
    设\(G:V\to V\)的函数，则存在唯一的函数\(F:\On\to V\)使得
    \begin{equation*}
    F(\alpha)=G(F\uhr\alpha)
    \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    类\(X\)上的关系，类\(R\)是 *似集合* 的当且仅当对任意\(x\in X\)，有\(\{y\in X\mid yRx\}\)是一个集合
    #+END_definition

    类的元素一定是集合，因为类是集合宇宙的一个子区域

    一般称\(\{y\in X\mid yRx\}\)中的元素为\(x\)的前驱，\(\in\)是任何类\(X\)上的似集合关系

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    如果\(R\)是\(X\)上的似集合关系，且\(x\in X\)，则递归定义
    - \(\pred^0(X,x,R)=\{y\in X\mid yRx\}\)
    - \(\pred^{n+1}(X,x,R)=\bigcup\{\pred(X,y,R)\mid y\in\pred^n(X,x,R)\}\)
    - \(\cl(X,x,R)=\bigcup_{n\in\omega}\pred^n(X,x,R)\)
    #+END_definition

    对每个\(n\),\(\pred^n(X,x,R)\)是集合

    故\(\cl(X,x,R)\)是集合

    若\(R\)是\(\in\)，且\(X\)是传递的，则\(\cl(X,x,R)=x\)


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    如果\(R\)是\(X\)上的似集合关系，则对任意\(y\in\cl(X,x,R)\)，都有\(\pred(X,y,R)\subseteq\cl(X,x,R)\)
    #+END_lemma

    #+BEGIN_proof
    设\(y\in\cl(X,x,R)\)，则存在\(n\in\omega\)使得\(y\in\pred^n(X,x,R)\)，故\(\pred(X,y,R)\subseteq\pred^{n+1}(X,x,R)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    如果\(R\)是\(X\)上的良基关系， 且是似集合的，则\(X\)的每个非空子类\(Y\)都有\(R\)-极小元
    #+END_theorem

    #+BEGIN_proof
    任取\(x\in Y\)，若\(x\)不是\(Y\)的\(R\)-极小元，则\(\pred(X,x,R)\cap Y\)非空，于是\(Y\cap\cl(X,x,R)\)非
    空，令\(x_0\in Y\cap\cl(X,x,R)\)为极小元，则\(x_0\)是\(Y\)的极小元，否则\(\pred(X,x_0,R)\cap Y=\emptyset\)，任
    取\(z_0\in\pred(X,x_0,R)\cap Y\)，则\(z_0\in Y\), \(z_0\in\cl(X,x,R)\)，于是\(z_0\in Y\cap\cl(X,x,R)\)
    且\(z_0Rx_0\)，与\(x_0\)的极小性矛盾
    #+END_proof

    #+BEGIN_remark
    假设基础公理，则\(\in\)是\(V\)上的良基关系，若\(V\neq\WF\)，则\(V\setminus\WF\)有极小元\(x_0\)非空，但
    是\(\forall y\in x_0(y\in\WF)\)，于是\(x_0\subset\WF\)，矛盾，因此\(V=\WF\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    设\(R\)是\(X\)上的似集合的良基关系，如果\(F:X\times V\to V\)是“函数”，则存在唯一的“函数”\(G:X\to V\)使得
    \(\forall x\in X(G(x)=F(x, G\uhr\pred(X,x,R)))\)
    #+END_theorem

    练习
    #+BEGIN_proof
    1. 存在性

       令公式\(\theta(x,t)\)表示
       - \(t\)是一个函数（集合）
       - \(\dom(t)=\{x\}\cup\pred(X,x,R)\)
       - \(\forall y\in\dom(t)(t(y)=F(y,t\uhr\pred(X,y,R)))\)
       - \(\forall y\notin\dom(t)(t=\emptyset\)
       令\(G=\{(x,y)\mid\theta(x,y)\}\)，证明\(G\)是函数：


    2. 唯一性

       若不唯一，则存在最小的\(x\in X\)使得\(G(x)\neq G(x')\). 但是\(G(x)=F(x,G\uhr(X,x,R))=F(x,G'\uhr(X,x,R))=G'(x)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    如果\(R\)是\(X\)上的似集合关系，设\(x\in X\)，则定义
    \begin{equation*}
    \rank(x,X,R)=\sup\{\rank(y,X,R)+1\mid yRx\wedge y\in X\}
    \end{equation*}
    (来自超穷递归)
    #+END_definition

    #+ATTR_LATEX: :options [\(\ZFm\)]
    #+BEGIN_definition
    如果类\(X\)传递，且\(\in\)是\(X\)上的良基关系，则\(X\subseteq\WF\)且对任意\(x\in X\)有\(\rank(x,X,\in)=\rank(x)\)
    #+END_definition

    #+BEGIN_proof
    若\(X\not\subseteq\WF\), 取极小元\(x_0\in X\setminus\WF\)，显然\(x_0\neq\emptyset\)。任取\(z\in x_0\)，由传递性，有\(z\in X\cap\WF\)，
    于是\(x_0\subseteq\WF\)，于是\(X\subseteq\WF\)

    令\(Y=\{x\in X\mid\rank(x,X,\in)\neq\rank(x)\}\)，如果\(Y\)非空，令\(x_0\)为\(Y\)的极小元，根据传递
    性,\(x_0\subseteq X\)，且\(\forall z\in x_0\),\(\rank(z,X,\in)=\rank(z)\)

    \(\rank(x_0,X,\in)=\sup\{\rank(z,X,\in)+1\mid z\in x_0\}\)

    \(\rank(x_0)=\sup\{\rank(z)+1\mid z\in x_0\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    令类\(R\)是\(X\)上似集合的良基关系，则\((X,R)\)上的 *mostowski函数* \(G\)定义为
    \begin{equation*}
    G(x)=\{G(y)\mid y\in X\wedge yRx\}
    \end{equation*}

    \(G\)的值域记作\(M\)，称之为\((X,R)\)的 *Mostowski坍塌*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(R\)是\(X\)上的一个似集合的良基关系，\(G\)是其上的Mostowski函数，\(M\)为其Mostowski坍塌，则
    1. \(\forall x,y\in X(xRy\to G(x)\in G(y))\), \(G:(X,R)\to(V,\in)\)同态
    2. \(M\)是传递集
    3. 如果幂集公理成立，则\(M\subseteq\WF\) (\(\ZFm-\Pow-\Inf\))
    4. 如果幂集公理成立，且\(x\in X\)，则\(\rank(x,X,R)=\rank(G(x))\)
    #+END_lemma

    #+BEGIN_proof
    3. [@3] 断言：\((M,\in)\)是良基的

       任取\(Y\subseteq M\)非空，则\(G^{-1}(Y)\subseteq X\)非空，有极小元\(x_0\)，若\(G(x_0)\)不是\(Y\)的极小元，
       则\(G(x_0)\cap Y\neq\emptyset\)。令\(z\in G(x_0)\cap Y\)，则存在\(y\in G^{-1}(Y)\)使得\(G(y)=z\)且\(yRx_0\)，
       与\(x_0\)极小矛盾


    #+END_proof





** Exercise
    #+BEGIN_exercise
    label:ex7.10.3
    1. \(V_\alpha=\{x\in\WF\mid\rank(x)<\alpha\}\)
    2. \(\WF\) is transitive
    3. \(\forall x,y\in\WF\), \(x\in y\Rightarrow\rank(x)<\rank(y)\)
    4. \(\forall y\in\WF\), \(\rank(y)=\sup\{\rank(x)+1\mid x\in y\}\)
    #+END_exercise

    #+BEGIN_proof
    1. by definition, \(x\in V_{\rank(x)+1}\setminus V_{\rank(x)}\), \(\rank(x)<\alpha\Rightarrow x\in V_{\rank(x)+1}\subseteq V_\alpha\)

       \(\rank(x)\ge\alpha\Rightarrow x\notin V_\alpha\)

    2. \(\WF\) is the "union" of transitive sets

    3. \(y\in V_{\rank(y)+1}\setminus V_{\rank(y)}\), \(y\subseteq V_{\rank(y)}\), \(x\in y\Rightarrow x\in V_{\rank(y)}\Rightarrow\rank(x)<\rank(y)\)

    4. by 3, \(\sup\{\rank(x)+1\mid x\in y\}\le\rank(y)\).

       induction on \(\rank(y)\le\sup\{\rank(x)+1\mid x\in y\}\)
       * \(\rank(y)=0\)
       * \(\rank(y)=\beta+1\), \(y\in V_{\beta+2}\setminus V_{\beta+1}\)

         \(y\in V_{\beta+2}\Rightarrow y\subseteq V_{\beta+1}\). \(y\notin V_{\beta+1}\Rightarrow y\not\subseteq V_{\beta}\Rightarrow y\setminus V_\beta\) nonempty.
         Let \(x\in y\setminus V_\beta\), \(\rank(x)\ge\beta\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\beta+1=\rank(y)\)
       * \(\rank(y)=\gamma\) for some limit, then \(y\subseteq V_\gamma\) and for any \(\xi<\gamma\), \(y\not\subseteq V_\xi\),
         let \(X_\xi\in y\setminus V_\xi\), then \(\rank(X_\xi)\ge\xi\), \(\sup\{\rank(x)+1\mid x\in y\}\ge\sup\{\xi+1\mid\xi<\rank(y)\}\ge\rank(y)\)
    #+END_proof
