#+TITLE: Set Theory
#+AUTHOR: 郝兆宽
#+EXPORT_FILE_NAME: ../latex/SetTheoryHao/SetTheoryHao.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \def \btu {\bigtriangleup}
#+LATEX_HEADER: \def \btd {\bigtriangledown}
#+LATEX_HEADER: \DeclareMathOperator{\Pred}{Pred}
#+LATEX_HEADER: \DeclareMathOperator{\ot}{ot}
* Intro
    习题 40%

    考试 闭卷

    期中 8周

    集合 \(\{x,y,z,\dots\}\) 外延 \(\{x\mid x\text{ is ...}\}\) 内涵

    #+ATTR_LATEX: :options [Cantor-Bendixen]
    #+BEGIN_theorem
    闭集\(X\subseteq\R\) uncountable, then \(X=Y_1\cup Y_2\), where \(Y_1\) is countable and \(Y_2\) is perfect
    #+END_theorem

    if \(Y_2\) is perfect, then \(\abs{Y_2}=\abs{\R}\).

    Hence CH is true for close set

    Suppose \(X\) is a set and \(Y=\{x\mid x\in X\wedge x\not\in x\}\) is a set

    \(Y\in Y\) => \(Y\in X\) and \(Y\not\in Y\), a contradiction. Hence \(Y\not\in Y\).

    \(Y\not\in Y\) => \(Y\not\in X\) or \(Y\in Y\) => \(Y\not\in X\)

    Thus we have
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. For any set \(X\), there exists a set \(Y\) s.t. \(Y\not\in X\).
    2. collection of all sets is not a set
    #+END_proposition

    Notation: we call \(\{x\mid\varphi(x)\}\) a class

    \(V=\{x\mid x=x\}\), \(\{x\mid x\not\in x\}\) is not a set

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(\{x\mid x\neq x\}\) is a set
    #+END_proposition

    #+BEGIN_proof
    From Existential Axiom, there is a set \(X_0\).

    Claim: \(\{x\mid x\neq x\}=\{x\mid x\in X_0\wedge x\neq x\}\)

    for any \(z\), \(z\neq z\), we need to prove \(z\in X_0\). But \(z\neq z\) is always false.
    #+END_proof

    We write \(\emptyset=\{x\mid x\neq x\}\)

    For any set \(X\neq\emptyset\), its arbitrary intersection
    \begin{equation*}
    \bigcap X=\{u\mid\forall Y(Y\in X\to u\in Y)\}
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((x,y)=\{\{x\},\{x,y\}\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \((x,y)=(x',y')\Leftrightarrow x=x'\wedge y=y'\)
    #+END_proposition

    #+BEGIN_proof
    作业
    #+END_proof


    _partial ordering + well-founded => linear ordering_

    since for arbitrary \(\{x,y\}\), it has a minimal element

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any set \alpha, if \(\in\) is a well-ordering on \alpha, then \alpha is an *ordinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    *successor* of \(x\) is \(S(x)=x\cup\{x\}\), or \(x^+\)
    #+END_definition

    ordinal that is not 0 and successor is a limit ordinal

    极限是否存在

    let \(\omega=\{n\mid n=0\vee n\text{ is successor and }\forall m<n(m\text{ is successor})\}\)

    Then we need to show that \omega is a set. So we need new axiom

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(X\) 是归纳集，则\(\omega\subseteq X\)
    #+END_proposition

    #+BEGIN_proof
    Otherwise we have least \(n\in\omega\) and \(n\not\in X\). Let \(n=S(m)\), then \(m\in X\). Hence we get a contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    For any \(X\subset\omega\), if \(X\) is inductive, then \(X=\omega\)
    #+END_theorem

    \([\varphi(0)\wedge\varphi(n)\to\varphi(n+1)]\Rightarrow\forall n\varphi(n)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \omega is a ordinal and is a limit ordinal
    #+END_theorem

    #+BEGIN_proof
    \(\in\) is a well-ordering on \omega, then we need show
    1. \(\in\) is a partial ordering
       1. transitive. let \(\varphi(x)\): if \(m<n\), then for any \(x\), \(n<x\to m<x\)

          \(x=0\)

          \(x=k+1\), \(n<k+1\), \(n\in k\cup\{k\}\). then \(n=k\) or \(n\in k\)
    2. \(\in\) is well-founded

       \(X\subseteq\omega\), \(X\neq\emptyset\), then \(\exists x_0\in X\). consider \(\omega-X\). Suppose \(X\) has no minimum element
       1. \(0\not\in X\Rightarrow 0\in\omega\)

       2. if \(n\in\omega-X\), then \(S(n)\in\omega-X\). Suppose \(n\not\in X\) and \(S(n)\in X\). Then \(S(n)\) is minimum

       then \(\omega-X\) is inductive



    for any \(\alpha<\omega\), \(S(\alpha)\neq\omega\), hence \omega is limit
    #+END_proof
* 序数
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    一个集合\(X\)成为 *传递* 的，如果对任意\(x\in X\)，都有\(x\subseteq X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    假设\(X\)是传递集。如果\(X\)的所有元素也是传递集，则\(\in\)在\(X\)上是一个传递关系。反之亦然。
    #+END_proposition

    #+BEGIN_proof
    注意在证明反方向时，\(\in\)是\(X\)上的传递关系，如果\(x\in b\), \(b\in a\)，我们先说明\(x,b,a\in X\)，然
    后因为\(\in\)是传递关系，于是\(x\in a\)
    #+END_proof

    #+BEGIN_exercise
    如果\((\calt,\in)\)是传递集，则外延公理在\(\calt\)中成立，即：对任意\(X,Y\in\calt\)，\(X=Y\)当且仅当对任
    意\(a\in\calt\),\(a\in X\)当且仅当\(a\in Y\)。即\(X\cap\calt=Y\cap\calt\)
    #+END_exercise

    如果\(\calt\)不传递，存在\(X\in\calt\)，有\(X\not\subseteq\calt\)，有\(a\in X\)且\(a\notin\calt\)，假设\(X\)与\(Y\)仅有\(a\)差别，
    但是\(\calt\)分辨不出

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    对任意集合\alpha，如果\(\in\)是\(\alpha\)上的良序，就称\(\alpha\)是 *序数*
    #+END_definition

    \(\{\omega,\omega+1,\omega+2,\dots\}\)是集合吗？这需要替换公理

    考虑\(V_{\omega+\omega}\)，我们定义集合是它的元素，替换公理在这里不对，\(f(\omega)\notin V_{\omega+\omega}\)不是集合。因此我们
    需要替换公理来保证它是集合
* 基数与选择公理
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    TFAE
    1. set \(X\) is finite
    2. there is a linear order \(\le\) on \(X\) satisfying for any nonempty subset there is a maximum
       and a minimum
    3. \(\forall Y\subseteq\calp(X)\) and \(Y\neq\emptyset\), it has a maximal under \(\subseteq\)
    #+END_proposition

    #+BEGIN_proof
    \(2\to 1\). Let \(x_0=\inf(X)\). For any \(k\in\N\), let \(x_{k+1}=\inf(X-\{x_0,\dots,x_k\})\)
    if \(x_k\neq\sup(X)\).

    \(1\to 3\). Find a maximum cardinality

    \(3\to 1\). If \(X\) is infinite. \(Y=\{Z\subseteq X\mid Z\text{ is finite}\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    一个序数是\(\alpha\)是至多可数的，当且仅当存在\(\R\)的子集\(A\)，\(ot(A)=\alpha\)
    #+END_theorem

    #+BEGIN_proof
    首先假设\(A\subseteq\R\)并且\(ot(A)=\alpha\)，即\(A=\{a_\beta\mid\beta<\alpha\}\)，并且\(a_\beta<a_\gamma\)当且仅当\(\beta<\gamma\)。对任意\(\beta<\alpha\)，
    令\(I_\beta=(a_\beta,a_{\beta+1})\)为实数的区间。如果\(\alpha=\eta+1\)是后继序数，则令\(I_\eta=(a_\eta,a_\eta+1)\)。这样的区间
    只有可数多
    #+LATEX: \wu{
    因为每个区间都有有理数，但是有理数只有可数多
    #+LATEX: }
    #+END_proof

    #+ATTR_LATEX: :options [2.2.15]
    #+BEGIN_proposition
    对任意无穷基数\(\kappa,\lambda\)
    1. \(\kappa^{<\lambda}=\sup\{\kappa^\eta\mid\eta\text{是基数并且}\eta<\lambda\}\)
    #+END_proposition

    #+BEGIN_proof
    1. TTT
       \begin{align*}
       \kappa^{<\lambda}&=\abs{\bigcup\{X^\beta\mid\beta<\lambda\}}\\
       &=\{\bigcup_{\beta<\lambda}\kappa^\beta\}=\bigoplus_{\beta<\lambda}\abs{\kappa^\beta}\\
       &=\sup\{\abs{\kappa^\beta}\mid\beta<\lambda\}\\
       &=\sup\{\kappa^{\abs{\beta}}\mid\beta<\lambda\}
       \end{align*}
    2. 对于\(f\in\kappa^\lambda\)，\(f\)都是\(\lambda\otimes\kappa\)的子集且 \(f\in\{X\subseteq\lambda\otimes\kappa\mid\abs{X}=\lambda\}\)
    #+END_proof

    #+BEGIN_exercise
    若\(\kappa\)是不可达的，则\(V_\kappa\vDash ZF\)。
    #+END_exercise

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(ZF\not\vDash\exists\kappa(\kappa\text{是inaccessible})\)
    #+END_corollary

    #+BEGIN_proof
    由 Gödel 第二不完全性定理，如果存在了，就能证明有模型了，就证明一致了
    #+END_proof

    大基数：\(\kappa\)是基数且\(ZF\not\vDash\exists\kappa\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \kappa 不可达，\(\abs{V_\kappa}=\kappa\).
    #+END_proposition

    #+BEGIN_proof
    \(\kappa\le\abs{V_\kappa}\)

    证明对任意\(\alpha<\kappa\), \(\abs{V_\alpha}<\kappa\),

    根据\(2^\alpha<\kappa\)
    #+END_proof

    证明\(f:\abs{X}=\alpha\to V_\kappa\)有界

    若\(\beta<\alpha\cdot\omega\),\(\beta=\alpha\cdot\xi+\eta\)，其中\(\xi\)有穷

    \(\beta>\alpha\), \(\beta=\alpha\cdot\xi+\eta\). \(\alpha+\beta=\alpha+\alpha\cdot\xi+\eta=\alpha\cdot\xi+\eta\).  \(\alpha+\alpha\cdot\xi=\alpha\cdot\xi\).
    只要证明\(\alpha\cdot(\xi+1)=\alpha+\alpha\cdot\xi\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\abs{\bigcup_{\gamma<\omega_\alpha}V_\gamma}=2^{\aleph_\beta}\)
    #+END_lemma

    #+BEGIN_proof
    \(2^{\aleph_\beta}=\sup\{2^{\aleph_\gamma}\mid\gamma<\beta\}\). Thus \(2^{\aleph_\beta}\le\abs{\bigcup_{\gamma<\omega_\alpha}V_\gamma}\)
    #+END_proof

    \(\abs{V_{\omega+1}}=2^{\aleph_0},\abs{V_{\omega+2}}=2^{\abs{2^{\aleph_0}}}>2^{\aleph_0}\)

    \(\abs{V_{\omega_1}}\ge\abs{V_{\omega+2}}>2^{\aleph_0}=\beth(1)\)

    \(\abs{V_{\omega_1}}=\beth_{\omega_1}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(\kappa\)不可达，\(X\in V_\kappa\),\(f:X\to V_\kappa\)，则\(f[X]\in V_\kappa\)
    #+END_proposition

    #+BEGIN_proof
    \(\abs{X}<\kappa\)，对不可达基数\(\abs{V_\kappa}=\kappa\)

    因此\(\abs{f(X)}<\kappa\)

    已知\(f[X]\subseteq V_\kappa\)。令\(\lambda=\sup\{\rank(y)\mid y\in f[X]\}\),因为\(y\in V_\kappa\)而\(\kappa\)是极限序数，因此存
    在\(\alpha<\kappa\)使得\(y\in V_\alpha\)，于是\(\rank(y)<\alpha+1<\kappa\),因此\(\lambda\)是\(<\kappa\)个小于\(\kappa\)的上界，又因为\(\kappa\)
    是正则的，\(\lambda<\kappa\)，于是\(f[X]\subseteq V_\lambda\)，于是\(f[X]\in V_{\lambda+1}\subseteq V_\kappa\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    令\(\beta\)为任意序数，\(\alpha\)为任意极限序数，证明：如果\(\alpha+\beta=\beta\)，则\(\beta\ge\alpha\cdot\omega\)
    #+END_proposition

    #+BEGIN_proof
    \(\alpha+\beta=\beta\Rightarrow\alpha\le\beta\Rightarrow\exists\delta,\gamma(\beta=\alpha\cdot\delta+\gamma\wedge\gamma<\alpha)\)

    若\(\delta\ge\omega\)就对了

    若\(\delta<\omega\)，\(\alpha+\beta=\alpha+(\alpha\cdot\delta)+\gamma=\alpha(1+\delta)+\delta>\alpha\)
    #+END_proof

    \(\aleph_1\le 2^{\aleph_0}\)，因此\(\aleph_1^{\aleph_0}\le 2^{\aleph_0\cdot\aleph_0}=2^{\aleph_0}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    令\(X=\{f:\omega\to\omega_1\mid f\text{ 1-1}\}\)，证明\(\abs{X}=2^\omega\)
    #+END_proposition

    #+BEGIN_proof
    \(Y=\{F\mid F:\aleph_0\to\aleph_0\times\aleph_1, \text{1-1}\}\)

    \(G=\aleph_1^{\aleph_0}\to Y\) s.t. \(G(f)=F\in Y\) s.t. \(F(n)=(n,f(n))\), then \(G\) is 1-1

    Hence \(\aleph_1^{\aleph_0}\le\abs{Y}=(\aleph_0\times\aleph_1)^{\aleph_0}=\aleph_1^{\aleph_0}\)
    #+END_proof

    #+BEGIN_proof

    #+END_proof



* 滤、理想与无界闭集
** 滤
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(-0=1\)
    2. \(-1=0\)
    3. \(a\cdot 1=a\)
    4. \(a+0=a\)
    5. \(a+a=a\)
    6. \(a\cdot a=a\)
    7. \(1+a=1\)
    8. \(0\cdot a=0\)
    9. \(a+b=1\wedge a\cdot b=0\Rightarrow b=-a\)
    10. \(-(a\cdot b)=(-a)+(-b)\)
    11. \(-(a+b)=(-a)\cdot(-b)\)
    #+END_proposition

    #+BEGIN_proof
    1. \(1=0+(-0)=(0\cdot(-0))+(-0)=-0\)
    2. \(0=1\cdot(-1)=(1+(-1))\cdot(-1)=-1\)
    3. \(a\cdot 1=a\cdot(a+(-a))=a\)
    5. [@5] \(a+a=a+(a\cdot 1)=a\)
    7. [@7] \(1+a=(a+1)\cdot 1=(a+1)\cdot(a+-a)=a\cdot a+0+a+-a=a+-a=1\)
    8. \(0\cdot a=(a\cdot (-a))\cdot a=a\cdot a\cdot (-a)=a\cdot (-a)=0\)
    9. [@9] \(-a=(-a)\cdot 1=(-a)\cdot(a+b)=(-a)\cdot a+(-a)\cdot b=(-a)\cdot b\).

       \(ab+(-a)b=-a\). \(b(a+(-a))=b=-a\)
    10. \(ab+(-a)+(-b)=ab+(-a)+(-b)\cdot 1=ab+(-a)+(-b)a+(-b)(-a)=a(b+(-b))+(-a)+(-b)(-a)=1+(-b)(-a)=1\)
    #+END_proof

    \(G\)有有穷交性质
    \(F=\{b\in B\mid\exists g\in G(g\le b)\}\)

    若\(a,b\in F\)，则\(g_1\le a,g_2\le b\)

    Rasiowa-Sikorski [mathematics for metamathematics] 是为了证明一阶完全性，\(\sum D\)等价于\(\exists x\)

    令\(\phi(x,\bary)\), \(M_\phi=\{[\varphi(t,\bary)]\mid t\text{ a term}\}\subset B\)

    *Claim* \(\sum M_\phi=[\exists x\varphi(x,\bary)]\)

    那么如果\(U\)是完全的，那么\(\sum M_\phi\in U\)，于是\(\exists t[\phi(t,\bary)]\in U\)。类似于极大一致Henkin集

    under CH \(\abs{A}<2^{\aleph_0}=\aleph_1\) iff \(\abs{A}\le\aleph_0\)

    cichon diagram

    \(f:M\to N\), \(f\upharpoonright A:A\to N\), \(\forall a\in A, f\upharpoonright A(a)=f(a)\)
** Clut set
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \alpha limit, \(C\subseteq\alpha\) is a *club set* in \alpha if
    1. unbounded  \(\sup C=\alpha\), that is, for any \(\beta<\alpha\), there is \(\gamma\in C\) s.t. \(\beta<\gamma\)
    2. closed: for any limit \(\gamma<\alpha\), \(\sup(C\cap\gamma)=\gamma\Rightarrow\gamma\in C\)
    #+END_definition

    If \(A\subseteq C\subseteq\alpha\) and \(\sup C=\gamma<\alpha\), then \gamma is the *limit point* of \(C\). \(C\) is closed in \alpha iff
    all limit point of \(C\) belong to \(C\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.3.4
    \alpha limit and \(\cf(\alpha)>\omega\), then
    1. \alpha is a club set of itself
    2. \(\forall\beta<\alpha\), \(\{\beta<\alpha\mid\delta>\beta\}\) is a club set in \alpha
    3. \(X=\{\beta<\alpha\mid\beta\text{ limit}\}\) is a club set in \alpha
    4. If \(X\) is unbounded in \alpha, then \(X'=\{\gamma\in X\mid\gamma<\alpha\wedge\gamma\text{ is a limit point of }X\}\) is a club
       set in \alpha
    #+END_lemma

    #+BEGIN_proof
    3. [@3] \(X\) is closed. For any \(\xi\in\alpha\), define
       \begin{equation*}
       \xi=\xi_0,\xi_1,\cdots,\xi_n,\cdots\quad(n\in\omega)
       \end{equation*}
       s.t. \(\xi_{n+1}=\min\{\alpha-\xi_n\}\). Let \(\eta=\sup\xi_i\). Then \(\xi<\eta\in X\). \(\eta<\alpha\) since \(\cf(\alpha)>\omega\)
    4. Like 3, for any \(\xi\in\alpha\), define \(\xi_{n+1}=\min\{\xi'>\xi:X-\{\xi_1,\dots,\xi_n\}\}\), this works
       since \(X\) is unbounded.

       For any limit point \(\eta<\alpha\) of \(X'\), that is, \(\sup(X'\cap\eta)=\eta\), then for any \(\sigma<\eta\), there
       is limit point \(\xi<\eta\) of \(X\) s.t. \(\sigma+1<\xi\). By definition of limit point, \(\exists\mu\in X\cap\xi\)
       s.t. \(\sigma<\mu\), so \(\sup(X\cap\eta)=\eta\) and \(\eta\) is a limit point of \(X\), thus \(\eta\in X'\)

       Limit of limits of \(X\) is still a limit of \(X\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.3.5
    if \alpha is limit and \(\cf(\alpha)>\omega\), and \(f:\alpha\to\alpha\) is strictly increasing and continuous, that is,
    for any limit \(\beta<\alpha\), \(f(\beta)=\bigcup_{\gamma<\beta}f(\gamma)\), then
    1. \(\im(f)\) is a club set in \alpha
    2. if \alpha is regular, then every club set \(C\) in \alpha is the image of such a function
    #+END_lemma

    #+BEGIN_proof
    2. [@2] suppose \(ot(C)=\tau\). \(f:(\tau,<)\cong(C,<)\), then \(f\) is strictly increasing and
       continuous. Since \(C\) is unbounded and \alpha is regular, \(\tau\ge\cf(\alpha)=\alpha\). \(\forall\eta<\tau\), \(\eta\le f(\eta)\),
       so \(\tau\le\sup f(\eta)=\alpha\), thus \(\tau=\alpha\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:3.3.7
    Suppose \alpha is a limit ordinal and \(\cf(\alpha)>\omega\), then for any \(\gamma<\cf(\alpha)\), if \((C_\xi)_{\xi<\gamma}\) is
    a sequence of club sets in \alpha, then \(\bigcap_{\xi<\gamma}C_\xi\) is a club set in \alpha
    #+END_proposition

    #+BEGIN_proof
    Suppose \(\gamma=2\). Intersection of closed sets is still closed. We prove that \(C_1\cap C_2\) is
    unbounded in \alpha. \(\forall\delta<\kappa\), \(\exists\xi\in C_1,\eta\in C_2\) s.t. \(\delta<\xi<\eta\), let
    \begin{equation*}
    \xi_0<\eta_0<\xi_1<\eta_1<\dots
    \end{equation*}
    where \(\xi_0=\xi,\eta_0=\eta\) and for any \(n\in\omega\), \(\xi_n\in C_1\), \(\eta_n\in C_2\). Let \mu be the limit of this
    sequence, then \(\sup(C_1\cap\mu)=\mu\) and \(\sup(C_2\cap \mu)=\mu\), hence \(\mu\in C_1\cap C_2\).

    Suppose \(\gamma\) is a successor ordinal

    Suppose \gamma is a limit ordinal, let \(D=\bigcap_{\xi<\gamma}C_\xi\), we prove it is unbounded. For any \(\eta<\gamma\),
    if \(D_\eta=\bigcap\{C_\xi\mid\xi<\eta\}\), then \(\eta_n\) is a club set and \(D=\bigcap_{\eta<\gamma}D_\eta\) and \(\eta<\eta'<\gamma\)
    implies \(D_\eta\supset D_{\eta'}\). For any \(\mu<\alpha\), let
    \begin{equation*}
    \xi_0<\xi_1<\cdots<\xi_\eta<\cdots
    \end{equation*}
    where \(\xi_0>\mu\), and for any \(\eta<\gamma\), \(\xi_\eta\in D_\eta\) is the minimum element larger
    than \(\sup\{\xi_\alpha\mid\alpha<\eta\}\). Since \(\cf(\alpha)>\gamma\), \(\xi=\sup\{\xi_n\mid\eta<\gamma\}<\alpha\). for any \(\eta<\lambda\), \(\xi\in D_\eta\),
    thus \(\xi\in D\) and \(\mu<\xi\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any limit \(\cf(\alpha)>\omega\)
    \begin{equation*}
    F_{CB}(\alpha)=\{X\subseteq\alpha\mid\exists C(C\text{ is a club set in }\alpha\wedge C\subseteq X)\}
    \end{equation*}
    is a filter, called *club filter* in \alpha
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:3.3.9
    If \kappa is uncountable regular cardinal, then club filter in \kappa is \kappa-complete
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    for any ordinal \alpha, \((X_\xi\mid\xi<\alpha)\) is a sequence of subsets of \alpha
    1. *diagonal intersection* of \(X_\xi\)
       \begin{equation*}
       \bigtriangleup_{\xi<\alpha}X_\xi=\{\eta<\alpha\mid\eta\in\bigcap_{\xi<\eta}X_\xi\}
       \end{equation*}
    2. *diagonal union* of \(X_\xi\)
       \begin{equation*}
       \bigtriangledown_{\xi<\alpha}X_\xi=\{\eta<\alpha\mid\eta\in\bigcup_{\xi<\eta}X_\xi\}
       \end{equation*}
    #+END_definition

    #+BEGIN_remark
    Let \(Y_\xi=\{\eta\in X_\xi\mid\eta>\xi\}\), then \(\bigtriangleup_{\xi<\alpha}X_\xi=\bigtriangleup_{\xi<\alpha}Y_\xi\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    for any uncountable regular \kappa, and a sequence of club sets \((X_\gamma\mid\gamma<\kappa)\) in \kappa, \(\bigtriangleup_{\gamma<\kappa}X_\gamma\) is a
    club set in \kappa.
    #+END_proposition

    #+BEGIN_proof
    Let \(C_\gamma=\bigcap_{\xi<\gamma}X_\xi\), then \(\bigtriangleup X_\gamma=\bigtriangleup C_\gamma\)
    #+LATEX: \wu{
    \begin{align*}
    \eta\in\btu C_\gamma&\Leftrightarrow\forall\xi<\eta,\eta\in C_\xi=\bigcap_{\zeta<\xi}X_\zeta\\
    &\Leftrightarrow\forall\zeta<\xi<\eta,\eta\in X_\zeta
    \end{align*}
    guess should be \(C_\gamma=\bigcap_{\xi\le\gamma}X_\xi\)
    #+LATEX: }


    let
    \begin{equation*}
    C_0\supset C_1\supset\cdots\supset C_\gamma\supset\cdots\quad(\gamma<\kappa)
    \end{equation*}
    Define \(C=\btu C_\gamma\). To prove \(C\) is closed, let \eta be the limit point of \(C\). We need to
    prove \(\eta\in C\), that is, \(\forall\xi<\eta\), \(\eta\in C_\xi\). For any \(\xi<\eta\), define \(X=\{\nu\in C\mid\xi<\nu<\eta\}\), then \(X\subset C_\xi\); by
    Theorem ref:3.3.9, \(C_\xi\) is a club in \kappa, therefore \(\eta=\sup X\in C_\xi\), hence \(\eta\in C\)

    Unboundedness: for any \(\mu<\kappa\), define \((\beta_n\mid n\in\omega)\): let \(\mu<\beta_0\in C_0\),
    and \(\beta_n<\beta_{n+1}\in C_{\beta_n}\). Since \(C_{\beta_n}\) is unbounded, such \(\beta_{n+1}\) can always be
    found. Also
    \begin{equation*}
    C_{\beta_0}\supset C_{\beta_1}\supset C_{\beta_2}\supset\cdots
    \end{equation*}
    thus for any \(m>n\), \(\beta_m\in C_{\beta_{m+1}}\subset C_{\beta_n}\). Now we prove \(\beta=\sup\{\beta_n\mid n\in\omega\}\in C\), which
    is suffice to show that for any \(\xi<\beta\), \(\beta\in C_\xi\). But if \(\xi<\beta\), there is \(n\) s.t. \(\xi<\beta_n\) and
    for any \(m>n\), \(\beta_m\in C_{\beta_n}\subset C_\xi\). Since \(C_\xi\) is closed, \(\beta\in C_\xi\). Thus \(\beta\in C\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    For any uncountable regular cardinal \kappa, if \(f:\kappa\to\kappa\) is a function ,then
    \begin{equation*}
    D=\{\alpha<\kappa\mid\forall\beta<\alpha(f(\beta)<\alpha)\}
    \end{equation*}
    is a club set
    #+END_corollary

    #+BEGIN_proof
    For any \(\alpha<\kappa\), let \(C_\alpha=\{\beta<\kappa\mid f(\alpha)<\beta\}\), which is a club set. Then \(D=\btu C_\alpha\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \alpha limit and \(\cf(\alpha)>\omega)\)
    1. If \(S\subseteq\alpha\) and for any club set \(C\) in \alpha \(S\cap C\neq\emptyset\), then \(S\) is called *stationary set* in \alpha
    2. \(I_{NS}(\alpha)=\{X\subseteq\alpha\mid\exists C(C\text{ is a club set in $\alpha$}\wedge X\cap C=\emptyset)\}\) is called a *non-stationary
       ideal* in \alpha
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    limit ordinal \alpha with \(\cf(\alpha)>\omega\)
    1. club set in \alpha is stationary. if \(S\) is stationary and \(S\subseteq T\subseteq\alpha\), then \(T\) is stationary
    2. stationary set in \alpha is unbounded
    3. there is unbounded \(T\subseteq\alpha\) that is not stationary
    #+END_proposition

    #+BEGIN_proof
    1. ref:3.3.7
    2. If \(S\) is stationary, for any \(\beta<\alpha\), \(\{\gamma<\alpha\mid\beta<\gamma\}\) is a club set in \alpha and the elements of
       the intersection of it with \(S\) is larger than \(\beta\)
    3. \(T=\{\alpha+1\mid\alpha<\kappa\}\) is unbounded but not stationary, since the club set of all limit ordinal
       doesn't intersect with it
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    limit ordinal \alpha with \(\cf(\alpha)>\omega\) and \(\lambda<\cf(\alpha)\) is regular, then
    \begin{equation*}
    E_\lambda^\alpha=\{\beta<\alpha\mid\cf(\beta)=\lambda\}
    \end{equation*}
    is stationary in \alpha
    #+END_proposition

    #+BEGIN_proof
    For any club set \(C\) in \alpha, define a strictly increasing sequence of \(C\):
    \begin{equation*}
    \alpha_0<\alpha_1<\cdots<\alpha_\xi<\cdots\quad (\xi<\lambda)
    \end{equation*}
    such sequence exists since \lambda is regular, \(\lambda<\cf(\alpha)\) and \(C\) is unbounded. suppose \delta is the
    supremem of the sequence. Since \(C\) is closed, \(\delta\in C\), Since \(\cf(\delta)=\lambda\), \(\delta\in E_\lambda^\alpha\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    for any uncountable regular cardinal \kappa, if \((X_\xi\mid\xi<\kappa)\) is a sequence of non-stationary sets,
    then \(\btd_{\xi<\kappa}X_\xi\) is non-stationary. That is, \(I_{NS}(\kappa)\) is closed under diagonal intersection
    #+END_proposition

    #+BEGIN_proof
    For any \(X_\xi\), there is \(C_\xi\) s.t. \(X_\xi\cap C_\xi=\emptyset\). Let \(C=\btu C_\xi\), then \(C\) is a club
    set. Let \(X=\btd X_\xi\), then \(X\cap C=\emptyset\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For a ordinal set \(S\) and \(\dom(f)=S\), if for any \(0\neq\alpha\in S\), \(f(\alpha)<\alpha\), then \(f\) is *regressive*
    #+END_definition

    #+ATTR_LATEX: :options [Fodor]
    #+BEGIN_theorem
    For any uncountable regular cardinal \kappa, stationary \(S\subseteq\kappa\), if \(\dom(f)=S\) is regressive, then
    there is a stationary \(T\subseteq S\) and ordinal \(\gamma<\kappa\) s.t. for any \(\alpha\in T\), \(f(\alpha)=\gamma\)
    #+END_theorem

    #+BEGIN_proof
    If for any \(\gamma<\kappa\), \(A_\gamma=\{\alpha\in S\mid f(\alpha)=\gamma\}\) is non-stationary, and there is a club set \(C_\gamma\)
    s.t. \(A_\gamma\cap C_\gamma=\emptyset\), that is, for any \(\alpha\in S\cap C_\gamma\), \(f(\alpha)\neq\gamma\). Let \(C=\btu_{\gamma<\kappa}C_\gamma\).
    Then \(\alpha\in C\) iff \(\forall\gamma<\alpha\), \(\alpha\in C_\gamma\) iff \(\forall\gamma<\alpha\), \(f(\alpha)\neq\gamma\). Hence for
    any \(\alpha\in C\), \(f(\alpha)\ge\alpha\). Since \(C\) is a club set, \(S\cap C\neq\emptyset\), but for any \(\alpha\in S\), \(f(\alpha)<\alpha\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.3.24
    uncountable regular cardinal \kappa, \(S\subseteq\kappa\) stationary, \(f\) is a regressive function on \(S\). If
    for any \(\eta<\kappa\),
    \begin{equation*}
    X_\eta=\{\alpha\in S\mid f(\alpha)\ge\eta\}
    \end{equation*}
    is stationary, then \(S\) can be partitioned into \kappa disjoint stationary sets
    #+END_lemma

    #+BEGIN_proof
    For any \(\eta<\kappa\), \(f\uhr X_\eta\) is a regressive function on \(X_\eta\). By Fodor's, there
    is \(\eta<\gamma_\eta<\kappa\) s.t. \(S_{\gamma_n}=\{\alpha\in S\mid f(\alpha)=\gamma_n\}\) is stationary

    Define \(g:\kappa\to\kappa\): \(g(0)=0\), \(g(\eta)=\sup\{\gamma_{g(\xi)}+1\mid\xi<\eta\}\). If \(\xi<\eta<\kappa\),
    then \(\gamma_{g(\xi)}<g(\eta)\le\gamma_{g(\eta)}\), hence \(\eta\mapsto\gamma_{g(\eta)}\) is a increasing cofinal function from
    \kappa to \kappa. Thus \(\{S_{\gamma_{g(\eta)}}\mid\eta<\kappa\}\) has cardinality \kappa and is pairwise disjoint
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    uncountable regular \kappa, \(\lambda<\kappa\) is regular, any stationary subset of
    \begin{equation*}
    E_\lambda^\kappa=\{\alpha<\kappa\mid\cf(\alpha)=\lambda\}
    \end{equation*}
    can be partitioned into \kappa disjoint stationary subsets
    #+END_lemma

    #+BEGIN_proof
    Stationary \(S\subseteq E^\kappa_\lambda\), \(\forall\alpha\in S\), choose a strictly increasing cofinal
    function \(f_\alpha:\lambda\to\alpha\). \(\forall\xi<\lambda\), define \(g_\xi:\kappa\to\kappa\):
    \begin{equation*}
    g_\xi(\alpha)=
    \begin{cases}
    0&\alpha\notin S\\
    f_\alpha(\xi)&\alpha\in S
    \end{cases}
    \end{equation*}
    \(g_\xi\uhr S\) is regressive

    \(\forall\eta<\kappa\forall\xi<\lambda\), let
    \begin{equation*}
    X_\xi^\eta=\{\alpha\in S\mid g_\xi(\alpha)\ge\eta\}
    \end{equation*}
    We prove: \(\exists\xi<\lambda\forall\eta<\kappa\), \(X_\xi^\eta\) is stationary. Otherwise, \(\forall\xi<\lambda\), there is a club \(C_\xi\)
    and a ordinal \(\eta_\xi<\kappa\) s.t. \(C_\xi\cap X_\xi^{\eta_\xi}=\emptyset\). Let \(C=\bigcap_{\xi<\lambda}C_\xi\), \(\eta=\sup\{\eta_\xi\mid\xi<\lambda\}\),
    then \(C\) is a club. But for any \(\alpha\in C\cap S\), \(\forall\xi<\lambda\), \(g_\xi(\alpha)<\eta\) since \(C\cap X_\xi^\eta=\emptyset\), therefore \(C\cap S\subseteq\eta\), a
    contradiction since \(C\) is a club

    Fix a \(\xi<\lambda\) s.t. for any \(\eta<\kappa\), \(X_\xi^\eta\) is stationary. By ref:3.3.24, \(S\) can be
    partitioned into \kappa disjoint stationary sets
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:3.3.26
    uncountable regular \kappa, \(X=\{\alpha<\kappa\mid\cf(\alpha)<\alpha\}\). If \(S\subseteq X\) is stationary, then \(S\) can be
    partitioned into \kappa disjoint stationary sets
    #+END_corollary

    #+BEGIN_proof
    Let \(f:\kappa\to\kappa\) be \(f(\alpha)=\cf(\alpha)\). Then \(f\uhr S\) is regressive. By Fodor's lemma, there
    is \(\lambda<\kappa\), \(S_\lambda=\{\alpha\in S\mid f(\alpha)=\lambda\}\) is stationary. Note that \(S_\lambda\subseteq E_\lambda^\kappa\), hence \(S_\lambda\) can be
    partitioned into \kappa disjoint stationary sets
    #+END_proof

    #+ATTR_LATEX: :options [skip]
    #+BEGIN_lemma
    uncountable regular \kappa, \(S\subseteq\kappa\) stationary, \(f:S\to\kappa\) regressive. for any \(\beta<\kappa\), define
    \begin{equation*}
    S_\beta=\{\alpha\in S\mid f(\alpha)=\beta\}
    \end{equation*}
    Let \(I=\{S_\beta\mid S_\beta\text{ stationary}\}\), then exactly one of below is true
    1. \(\abs{I}=\kappa\)
    2. \(\abs{I}<\kappa\) and there is a club \(C\), \(\im(f\uhr C\cap S)\) is bounded in \kappa
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    uncountable regular \kappa, \(R=\{\omega<\gamma<\kappa\mid\cf(\gamma)=\gamma\}\), define
    \begin{equation*}
    D=\{\gamma\in R\mid R\cap\gamma\in I_{NS}(\gamma)\}
    \end{equation*}
    If \(R\) is stationary in \kappa, then so is \(D\)
    #+END_lemma

    #+BEGIN_proof
    If \(D\) is not stationary, there is club \(C\) s.t. \(C\cap D=\emptyset\). Let \(C'\) be the set of limit
    points of \(C\). Let \(\gamma=\min(C'\cap R)\), \(\gamma\in R-D\), thus \(R\cap\gamma\) is stationary in \gamma

    Now consider \(C\cap\gamma\), since \(\gamma\) is a limit point of \(C\), this set is unbounded in \gamma. By
    ref:3.3.4 (4), \(C'\cap\gamma\) is a club set in \gamma, thus \(R\cap C'\cap\gamma\neq\emptyset\), which contradicts the minimality
    of \gamma in \(R\cap C'\)
    #+END_proof

    #+ATTR_LATEX: :options [Soloway]
    #+BEGIN_theorem
    Any stationary set in uncountable regular cardinal \kappa can be partitioned into \kappa disjoint
    stationary sets
    #+END_theorem

    #+BEGIN_proof
    stationary \(S\subseteq\kappa\), let
    \begin{align*}
    &S_0=\{\alpha<\kappa\mid\cf(\alpha)<\alpha\}\\
    &S_1=\{\alpha<\kappa\mid\cf(\alpha)=\alpha\}
    \end{align*}
    Then \(S=S_0\cup S_1\), hence either \(S_0\) or \(S_1\) is stationary ?

    If \(S_0\) is stationary, by ref:3.3.26, \(S_0\) can be partitioned into \kappa disjoint stationary
    sets

    Now suppose \(S_1\) is stationary, let \(D=\{\alpha\in S_1\mid S_1\cap\alpha\in I_{NS}(\alpha)\}\)
    #+END_proof






** Ultrafilter and large cardinal
*** Normal ultrafilter
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    limit ordinal \alpha, \(\cf(\alpha)>\omega\), \(F\) is a filter on \alpha. If \(F\) is closed under diagonal
    intersection, then \(F\) is *normal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    For any limit ordinal \alpha with \(\cf(\alpha)>\omega\), \(F_{CB}(\alpha)\) is normal
    #+END_examplle

    Let elements in \(F\) have measure 1, otherwise has measure 0
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    limit ordinal \alpha, \(\cf(\alpha)>\omega\), \(F\) is a filter on \alpha, if \(\forall X\in F\), \(Y\cap X\neq\emptyset\), then \(Y\subseteq\alpha\)
    has *positive measure*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    uncountable normal cardinal \kappa, \(F\) is a filter on \kappa. \(F\) is normal \(\Leftrightarrow\) for
    any \(f:\kappa\to\kappa\), if there is a \(X\) with positive measure s.t. \(f\uhr X\) is regressive, then
    there exists \(\gamma<\kappa\) s.t. \(X_\gamma=\{\alpha\in X\mid f(\alpha)=\gamma\}\) has positive measure
    #+END_lemma

    #+BEGIN_proof
    \(\Rightarrow\). \(f:\kappa\to\kappa\), \(Y\) has positive measure and \(f\uhr Y\) is regressive. If for
    all \(\gamma<\kappa\), \(Y_\gamma=\{\alpha\in Y\mid f(\alpha)=\gamma\}\) doesn't have positive measure, then there is \(X_\gamma\in F\)
    s.t. \(Y_\gamma\cap X_\gamma=\emptyset\). Let \(X=\btu X_\gamma\in F\) since \(F\) is normal. Since \(Y\) has positive
    measure, \(X\cap Y\neq\emptyset\). For any \(\gamma\in X\cap Y\), since \(\gamma\in X\), then for any \(\beta<\gamma\), \(f(\gamma)\neq\beta\),
    therefore \(f(\gamma)\ge\gamma\), contradicting the fact that \(f\) is regressive on \(Y\).

    \(\Leftarrow\). Suppose for any \(\beta<\kappa\), \(X_\beta\in F\) and \(X=\btu X_\beta\notin F\), then
    \begin{equation*}
    Y=\kappa-X=\{\alpha<\kappa\mid\exists\beta<\alpha(\alpha\notin X_\beta)\}
    \end{equation*}
    has positive measure. Define \(f:\kappa\to\kappa\):
    \begin{equation*}
    f(\alpha)=
    \begin{cases}
    \min\{\beta\mid\beta<\alpha\wedge\alpha\notin X_\beta\}&\alpha\in Y\\
    0
    \end{cases}
    \end{equation*}
    that is, if \(\alpha\notin X\), there is \(\beta<\alpha\) s.t. \(\alpha\notin X_\beta\)

    Then \(f\uhr Y\) is regressive, hence there is \(0<\gamma<\kappa\), \(Y_\gamma=\{\alpha\in Y\mid f(\alpha)=\gamma\}\) has positive
    measure. But \(\alpha\in Y_\gamma\Rightarrow\alpha\notin X_\gamma\), hence \(X_\gamma\cap Y_\gamma=\emptyset\), a contradiction
    #+END_proof
*** Measurable cardinal
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.4.7
    there is no \(\aleph_1\)-complete non-principal ultrafilter on \(2^\omega=\{f\mid f:\omega\to\{0,1\}\}\)
    #+END_lemma

    #+BEGIN_proof
    If \(U\) is a \(\aleph_1\)-complete non-principal ultrafilter on \(2^\omega\).
    Let \(L=\{f\in 2^\omega\mid f(0)=0\}\), \(R=\{f\in 2^\omega\mid f(0)=1\}\), then \(2^\omega=L\cup R\), and only one of them
    belongs to \(U\). Define \(h\) and a sequence \((X_n)_{n\in\omega}\) of subsets of \(2^\omega\) as follows:
    1. If \(L\in U\), then \(h(0)=0\), \(X_0=R\). If \(R\in U\), then let \(h(0)=1\), \(X_0=L\)
    2. Let \(h(n)\) and \(X_n\) is defined, then
       \begin{equation*}
       Y=\{f\in 2^\omega\mid\forall i\le n(f(i)=h(i))\}\in U
       \end{equation*}
       Let \(Y^L=\{f\in Y\mid f(n+1)=0\}\), \(Y^R=\{f\in Y\mid f(n+1)=1\}\), then only one of them belongs to \(U\).
       If \(Y^L\in U\), let \(h(n+1)=0\), \(X_{n+1}=Y^R\); otherwise, \(h(n+1)=1\), \(X_{n+1}=Y_L\)


    For any \(f\in 2^\omega\), if \(f\neq h\), then there is a smallest \(i\in\omega\) s.t. \(f(i)\neq h(i)\), which
    implies \(f\in X_i\), thus
    \begin{equation*}
    \{h\}\cup\bigcup_{n\in\omega}X_n=2^\omega\in U
    \end{equation*}
    But \(\forall n\in\omega\), \(X_n\notin U\), \(U\) is \(\aleph_1\)-complete implying \(\bigcup_{n\in\omega}X_n\notin U\).
    #+LATEX: \wu{
    \(\bigcup_{n\in\omega}X_n\notin U\Leftrightarrow\ove{\bigcup_{n\in\omega}X_n}\in U\Leftrightarrow\bigcap_{n\in\omega}\ove{X_n}\in U\Leftarrow\forall n\in\omega(\ove{X_n}\in U)\)
    #+LATEX: }
    And \(U\) is not principal, thus \(\{h\}\notin U\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \kappa be the minimum cardinal with a \(\aleph_1\)-complete non-principal ultrafilter on it, then
    1. any \(\aleph_1\)-complete non-principal ultrafilter on \kappa is \(\kappa\)-complete
    2. \kappa is uncountable and regular
    #+END_lemma

    #+BEGIN_proof
    1. \(U\) is an \(\aleph_1\)-complete non-principal ultrafilter on \kappa. If \(U\) is not \kappa-complete, then
       there is \(\gamma<\kappa\), \((X_\beta)_{\beta<\gamma}\) a sequence of pairwise disjoint subsets of \kappa
       s.t. \(\bigcup_{\beta<\gamma}X_\beta\in U\) and \(\forall\beta<\gamma(X_\beta\notin U)\)

       Now we define a filter on \gamma. First, for any \(Y\subseteq\gamma\), let
       \begin{equation*}
       X_Y=\{\delta<\kappa\mid\exists\beta\in Y(\delta\in X_\beta)\}
       \end{equation*}
       that is, \(X_Y=\bigcup_{\beta\in Y}X_\beta\). Let \(F=\{Y\subseteq\gamma\mid X_Y\in U\}\), we prove that \(F\) is
       an \(\aleph_1\)-complete non-principal ultrafilter on \gamma, contradicting the minimality of \kappa

       Since \(X_\beta\notin U\), thus \(Y=\{\beta\}\notin F\), thus \(F\) is non-principal. \(F\) is \(\aleph_1\)-complete
       since \(U\) is \(\aleph_1\)-complete. \(\gamma\in F\Leftarrow X_\gamma\in U\Leftarrow\bigcup_{\beta\in\gamma}X_\beta\in U\)

    2. Let \((X_\beta)_{\beta<\gamma}\) be a sequence of subsets of \kappa, \(\gamma<\kappa\) and for
       any \(\beta<\gamma\), \(\abs{X_\beta}<\kappa\), now we prove \(\abs{\bigcup_{\beta<\gamma}X_\beta}\neq\kappa\)

       By 1, let \(U\) be a \kappa-complete non-principal ultrafilter on \kappa. For any \(\beta<\kappa\),
       since \(\abs{X_\beta}<\kappa\), \(X_\beta\notin U\). But \(U\) is \kappa-complete, so \(\bigcup_{\beta<\gamma}X_\beta\notin U\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
        uncountable regular cardinal \kappa, if there is a \kappa-complete non-principal ultrafilter on \kappa,
        then \kappa is a *measurable cardinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \kappa is measurable, then it is inaccessible
    #+END_proposition

    #+BEGIN_proof
    We only need to show \kappa is strongly limit

    If there is \(\lambda<\kappa\) s.t. \(2^\lambda\ge\kappa\). Let \(g:\kappa\to 2^\lambda\) be a injection. If \(U\) is a \kappa-complete
    non-principal ultrafilter on \kappa, then \(F=\{X\subseteq 2^\lambda\mid g^{-1}[X]\in U\}\) is a \kappa-complete non-principal
    filter on \(2^\lambda\)

    Now we prove there is no \kappa-complete non-principal ultrafilter on \(2^\lambda\) similar to ref:3.4.7.
    Suppose there is such ultrafilter \(F\), define \(h:\lambda\to\{0,1\}\) s.t. for
    any \(\beta<\kappa\), \(Y_\beta=\{f\in 2^\lambda\mid\forall\delta<\beta(f(\delta)=h(\delta))\}\in F\)

    Suppose for any \(\delta<\beta\), \(f(\delta)\) is defined, let
    \begin{align*}
    &Y^L=\{f\in 2^\lambda\mid\forall\delta<\beta(f(\delta)=h(\delta))\wedge f(\beta=0)\}=\{f\in Y_\beta\mid f(\beta)=0\}\\
    &Y^R=\{f\in 2^\lambda\mid\forall\delta<\beta(f(\delta)=h(\delta))\wedge f(\beta=1)\}=\{f\in Y_\beta\mid f(\beta)=1\}\\
    \end{align*}
    If \(Y^L\in F\), \(h(\beta)=0\), otherwise \(h(\beta)=1\), and let \(Y_{\beta+1}=\{f\in 2^\lambda\mid\forall\delta\le\beta(f(\delta)=h(\delta))\}\),
    obviously \(Y_{\beta+1}\in F\)

    For limit \(\eta<\lambda\), \(h(\eta)=\sup_{\delta<\eta}f(\delta)\) and \(Y_\eta=\bigcap_{\delta<\eta}Y_\delta\). Since \(F\) is
    \kappa-complete, \(Y_\eta\in F\).

    Then \(\{h\}=Y=\bigcap_{\beta<\lambda}Y_\beta\in F\), a contradiction
    #+END_proof
*** Mahlo cardinal

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any limit ordinal \alpha, ordinal \delta, \(f:\delta\to\alpha\), if
    1. \(\eta<\beta<\delta\Rightarrow f(\eta)<f(\beta)\)
    2. \(\forall\xi<\delta\), \(f(\xi)=\bigcup\{f(\beta)\mid\beta<\xi\}\)


    Then \(f\) is *continuous*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.4.12
    For any limit ordinal \alpha, TFAE
    1. \alpha is regular and \(\alpha>\omega\)
    2. any continuous cofinal \(f:\delta\to\alpha\) has fixed point
    #+END_lemma

    #+BEGIN_proof
    \(\Rightarrow\). If \(f:\delta\to\alpha\) is continuous cofinal, then \(\delta=\alpha\). For
    any \(\beta<\alpha\), \(\epsilon_0=f(\beta)\), \(\epsilon_{n+1}=f(\epsilon_n)\), \(\epsilon=\bigcup_{n\in\omega}\epsilon_n\). Since \(\alpha>\omega\) is
    regular, \(\epsilon\in\alpha\). Since \(f\) is continuous, \(f(\epsilon)=\bigcup_{n\in\omega}f(\epsilon_{n+1})=\epsilon\)

    \(\Leftarrow\). If \(\cf(\alpha)=\delta<\alpha\), cofinal \(f:\delta\to\alpha\). Let \(g:\delta\to\alpha\) be \(\beta\mapsto \delta+f(\beta)\). \(g\) is a
    continuous cofinal function, for any \(\beta<\delta\), \(\beta<g(\beta)\), hence it doesn't have fixed point
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    limit ordinal \kappa
    1. if any continuous cofinal function \(f:\kappa\to\kappa\) has a regular fixed point \epsilon, then \kappa is a *weakly
       Mahlo cardinal*
    2. if any continuous cofinal function \(f:\kappa\to\kappa\) has a inaccessible fixed point \epsilon, then \kappa is a
       *Mahlo cardinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any \kappa, if \kappa is weakly Mahlo, then \kappa is weakly inaccessible; if \kappa is Mahlo, then it is inaccessible
    #+END_lemma

    #+BEGIN_proof
    By ref:3.4.12, \kappa is regular
    1. if \(\kappa=\lambda^+\), let \(f:\kappa\to\kappa\) be \(f(\alpha)=\lambda+\alpha\). This is continuous, if \(f(\epsilon)=\epsilon\),
       then \(\epsilon=\lambda+\epsilon\), and thus \(\epsilon\) is not regular, since there is no cardinal between \lambda and \kappa
    2. if \(\lambda<\kappa\) and \(2^\lambda\ge\kappa\), let \(f:\kappa\to\kappa\) be \(f(\alpha)=\lambda+\alpha\). If \(f(\epsilon)=\epsilon\), then \(\lambda<\epsilon<2^\lambda\),
       thus is not strongly limit
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If there is a \kappa-complete regular non-principal ultrafilter \(U\) on \kappa, then \kappa is Mahlo
    #+END_lemma

    #+BEGIN_proof
    \kappa is measurable, so it is inaccessible. We need to prove that the set of all inaccessible
    cardinals that are less than \kappa is stationary, that is
    1. strongly limit cardinals less than \kappa is a club
    2. regular cardinal less than \kappa is stationary


    For 1, \(f(\lambda)=2^\lambda\) is a continuous cofinal function on \kappa, its fixed point is a club in \kappa and is
    strongly inaccessible

    For 2, we only need to prove that all regular cardinals less than \kappa belong to \(U\).
    Otherwise, \(\{\alpha<\kappa\mid\cf(\alpha)<\alpha\}\in U\). Since \(U\) is regular, there
    is \(\lambda<\kappa\), \(E=\{\alpha<\kappa\mid\cf(\alpha)=\lambda\}\in U\). For any \(\alpha\in E\), define a increasing cofinal
    sequence \(\{\alpha_\eta\mid\eta<\lambda\}\), for any \(\eta<\lambda\), there is \(\gamma_\eta\), \(X_\eta=\{\alpha\in E\mid\alpha_\eta=\gamma_\eta\}\in U\).
    Hence \(X=\bigcap_{\eta<\lambda}X_\eta\in U\). But \(X=\sup\{\gamma_n\mid\eta<\lambda\}\) is a singleton, a contradiction
    #+END_proof
** Tree and weakly compact cardinal
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Poset \((T,<)\), if for any \(x\in T\), \(\Pred(x)=\{y\mid y<x\}\) is a well-ordering in \(<\),
    then \(T\) is a *tree*
    #+END_definition

    root is the smallest

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    tree \((T,<)\)
    1. \(\forall x\in T\), \(h_T(x)=\ot(\Pred(x))\), *height* of \(x\) in \(T\)
    2. \(\tau=\bigcup\{h_T(x)+1\mid x\in T\}\) *height of the tree \(T\)*, denoted by \(h_T\)
    3. \(\forall\beta<h_T\), \(\{x\in T\mid h_T(x)=\beta\}\) is the  \(\beta\)-th level of \(T\)
    4. If every pair of elements of \(A\subseteq T\), then \(A\) is the *antichain* of \(T\)
    5. any linear ordering subset of \(T\)  is a *chain* of \(T\)
    6. If chain \(B\) of \(T\) is 向下封闭, that is, \(\forall x\in B(y<x\to y\in B)\), then \(B\) is a *branch*
       of \(T\)
    #+END_definition

    #+ATTR_LATEX: :options [Kőnig]
    #+BEGIN_lemma
    If \(T\) is a tree of height \omega, and every level of \(T\) is finite, then \(T\) has an infinite branch
    #+END_lemma

    #+BEGIN_proof
    Take \(x_0\) of 0-th level, and \(\{y\in T\mid x_0<y\}\) is infinite. Such \(x_0\) exists since \(T\)'s
    height is infinite. Suppose \(x_n\) is chosen of \(n\)-th level, take \(x_{n+1}\) of \(n+1\)-th
    level s.t. \(x_n<x_{n+1}\) and \(\{y\in T\mid x_{n+1}<y\}\) is infinite.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(T\) tree of height \kappa, if each level of \(T\) has cardinality less than \kappa, then \(T\) is a *\kappa-tree*
    #+END_definition

    #+ATTR_LATEX: :options [Aronszajn]
    #+BEGIN_theorem
    There is a \(\omega_1\)-tree \(T\) with no branch of order type \(\omega_1\)
    #+END_theorem

    1#+BEGIN_proof
    Let \(T\) be the subtree of \(\omega^{<\omega_1}\) consisting of all 1-1 functions. So \(\call_\alpha(T)\), for a
    countable ordinal \alpha, is the set of all \(s:\alpha\xrightarrow{1-1}\omega\). If \(C\) is a path through \(T\)
    then \(\bigcup C:\omega_1\xrightarrow{1-1}\omega\), which is impossible. But, \(T\) is not Aronszajn
    because \(\abs{\call_\alpha(T)}\) is not less than \(\omega_1\), but rather \(\fc\) for infinite \alpha.

    First, by recursion on \(\alpha<\omega_1\) choose \(s_\alpha\in\call_\alpha(T)\) so that
    1. \(\omega-\ran(s_\alpha)\) is infinite
    2. \(\xi<\alpha\to s_\alpha\uhr\xi=^*s_\xi\)


    Here, for \(x,y\in\omega^\xi\), \(x=^*y\) iff \(\{\mu:x(\mu)\neq y(\mu)\}\) is finite. Assuming that this can be
    done, let \(S=\bigcup_{\alpha<\omega_1}\{t\in\call_\alpha(T):t=^*s_\alpha\}\). Then \(S\) is a subtree of \(T\) (using 2), and
    all levels of \(S\) are countable, so \(S\) is an Aronszajn tree

    To choose the \(s_\alpha\): for \(j\in\omega\), let \(s_j\) be the identity function.  Given \(s_\alpha\),
    let \(s_{\alpha+1}=s_\alpha\cup(\alpha,n)\) for some \(n\in\omega\setminus\ran(s_\alpha)\) (using 1).

    Now let \(\gamma<\omega_1\) be a limit, and
    assume that we have \(s_\alpha\) for \(\alpha<\gamma\). Choose \(\alpha_0<\alpha_1<\cdots\) s.t. \(\sup\{\alpha_l:l<\omega\}=\gamma\). Then,
    using 2, choose \(t_l\in\call_{a_l}(T)\) so that \(t_0=s_{\alpha_0}\) and \(t_{l+1}=^*s_{\alpha_{l+1}}\) and
    \(t_{l+1}\uhr\alpha_l=t_l\).
    #+LATEX: \wu{
    Since \(s_{\alpha_{l+1}}\uhr\alpha_l=^*s_{\alpha_l}=^* t_l\). By reversing the difference, we can get such \(s_{\alpha_{l+1}}\).
    #+LATEX: }
    Let \(t=\bigcup_lt_l\). Then \(t:\gamma\xrightarrow{1-1}\omega\), so \(t\in\call_\gamma(T)\) and setting \(s_\gamma=t\) would preserve 2
    but might violate 1. So we remove \(\aleph_0\) elements from \(\ran(t)\).
    Define \(s_\gamma(\alpha_l)=t(\alpha_{2l})\) and \(s_\gamma(\zeta)=t(\zeta)\) for \(\zeta\in\gamma\setminus\{\alpha_l:l\in\omega\}\).
    Then \(\omega\setminus\ran(s_\gamma)\supseteq\{t(\alpha_{2l+1}):l<\omega\}\), so that 1 holds

    Consider \(T=\{f\in\aleph_0^{<\aleph_1}\mid f\text{ injective}\}\) (ordinal exponential), then \((T,\subset)\) is a tree
    of height \(\omega_1\). \(T\) doesn't have a \(\omega_1\)-branch: if \(\ot(B)=\omega_1\), then \(\bigcup B\) is a
    injection from \(\omega_1\) to \omega, which is impossible

    For any \(f,g\in T\), define \(f\sim_Fg\) iff \(\dom(f)=\dom(g)\) and \(\abs{\{\alpha\in\omega_1\mid f(\alpha)\neq g(\alpha)\}}<\omega\)

    *Claim* \(\sim_F\) is an equivalence relation and for any \(f\in T\), \([f]_{\sim_F}\) is countable
    since \([\omega]^{<\omega}=\omega\)

    Define a sequence \(\la f_\alpha\ra_{\alpha<\omega_1}\) of elements of \(T\) satisfying
    1. for any \alpha, \(\abs{\omega-\ran(f_\alpha)}=\omega\)
    2. for any \(\beta<\alpha\), \(f_\alpha\uhr\beta\sim_Ff_\beta\)


    Suppose for any \(\beta<\alpha\), \(f_\beta\) is defined. If \(\alpha=\beta+1\),
    then \(f_\alpha=f_\beta\cup\{(\alpha,n)\}\), \(n\notin\ran(f_\beta)\)

    If \alpha is limit, since \(\alpha<\omega_1\) is countable, take a strictly increasing cofinal \(\la\alpha_n\in\alpha:n<\omega\ra\)
    of \alpha and define \(\{(g_n,h_n,x_n)\mid n\in\omega\}\) satisfying
    1. \(g_n,h_n\in T\), \(g_n\subseteq h_n\subseteq g_{n+1}\)
    2. \(x_n\subseteq\omega\wedge\abs{x_n}<\omega\)
    3. \(\ran(h_n)\cap x_n=\emptyset\)
    4. \(g_n\sim_Fh_n\sim_Ff_{\alpha_n}\)


    Let \(g_0=h_0=f_{\alpha_0}\), \(x_0=\emptyset\),
    \begin{equation*}
    g_{n+1}=h_n\cup f_{\alpha_{n+1}}\uhr\{\beta\in[\alpha_n,\alpha_{n+1}):f_{\alpha_{n+1}}(\beta\notin\ran(h_n)\cup x_n\}
    \end{equation*}
    #+END_proof


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    For any cardinal \kappa, if any \kappa-tree has a branch with order type \kappa, then \kappa has *tree property*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    if an inaccessible cardinal \kappa has tree property, then \kappa is called *weakly compact cardinal*
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \kappa is weakly compact cardinal, then \kappa is inaccessible and Mahlo
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    If \kappa is measurable, then \kappa is weakly compact
    #+END_lemma

    #+BEGIN_proof
    That is, we prove \kappa has tree property
    #+END_proof







* 复习
    没有良序集同构于真前段

    递归定理
