#+title: Valuation Field
#+EXPORT_FILE_NAME: ../latex/ValuationField/ValuationField.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \DeclareMathOperator{\Char}{Char}
#+LATEX_HEADER: \makeindex
* 环与理想
** 介绍
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    称\(A\)为 *局部环* ，如果\(A\)只有一个极大理想 \(I\)，称\(k=A/I\)为\(A\)的 *剩余域* （residue field）
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. 设\(A\)为环，\(I\subsetneq A\)为理想，若每个\(x\in A\setminus I\)均是单位元则\(A\)是局部环，\(I\)是极大
       理想
    2. 若\(A\)为环，\(I\subseteq A\)为极大理想，若\(\forall a\in I\)，有\(1+a\)均是单位元，则\(A\)是局部环
    #+END_proposition


** 分式化
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(A\)是一个整环，令\(A^\times=A\setminus\{0\}\)，在\(A\times A^\times\)上定义关系\(\sim\)为
    \begin{equation*}
    (a,s)\sim(b,t)\Leftrightarrow at-bs=0
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    称\(S\subseteq A\)为 *乘法子集* ，如果\(1\in S\)且\(a,b\in S\Rightarrow ab\in S\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(S\subseteq A\)是乘法子集，定义\(A\times S\)上的等价关系\(\sim\)为
    \begin{equation*}
    (a,s)\sim(b,t)\Leftrightarrow\exists u\in S(u(at-bs)=0)
    \end{equation*}
    将\((a,s)\)的等价类记作\(\frac{a}{s}\)，定义
    \begin{equation*}
    \frac{a}{s}+\frac{b}{t}=\frac{at+bs}{st},\quad\frac{a}{s}\frac{b}{t}=\frac{ab}{st}
    \end{equation*}
    则\(A\times S/\sim\)是一个环，记作\(S^{-1}A\)
    #+END_definition

    #+BEGIN_remark
    * \(\forall x\in A\)，\(\frac{xa}{xs}=\frac{a}{s}\)
    * 若\(S\)有零因子，则\(S^{-1}A=0\)平凡
    * \(A\to S^{-1}A\), \(a\mapsto\frac{a}{1}\)是同态
    * 若\(A\)是整环，\(S=A^\times\)，则\(S^{-1}=\Frac(A)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    若\(\fp\)是素理想，\(S=A\setminus \fp\)是乘法子集
    * 令\(A_{\fp}=S^{-1}A\)
    * 令\(\fm=\{\frac{a}{s}\mid a\in\fp,s\notin\fp\}=pA_{\fp}=\fp S^{-1}\)，则\(A_{\fp}\)是局部环，\(\fm\)是\(A_{\fp}\)的极大理想
    #+END_examplle



** 多项式环
    设\(A\)是一个环，则多项式环\(A[X]\)的元素都形如
    \begin{equation*}
    \sum_{i=0}^na_ix^i,\quad a_i\in A,i\in\N
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(A\)是环，\(a\in A\) *不可约* 如果\(a\neq 0\)不是单位元且\(\forall b,c\in A(a=bc\Rightarrow)\)\(b\)或\(c\)为单位元

    一个整环\(A\)是 *唯一因子分解环* ，如果\(\forall a\in A\)，存在不可约元\(b_1,\dots,b_n\in A\)使得\(a=b_1\dotsb_n\)
    并且若存在不可约元\(c_1,\dots,c_m\)使得\(a=c_1\dots c_m\)则\(m=n\)，则\(\forall i<n\exists j<n(b_i=u_{ij}c_j)\)，其
    中\(u_{ij}\)是单位元
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(A\)是唯一因子分解环，则\(A[X]\)也是
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(k\)是域，则\(k[X_1,\dots,X_n]\)是唯一因子分解环
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(k\)是域，\(f\in k[X_1,\dots,X_n]\)，则\((f)\)是素理想\(\Leftrightarrow\)\(f\)不可约
    #+END_corollary

    #+BEGIN_proof
    \(\Rightarrow\)：\(k[X_1,\dots,X_n]/(f)\)是整环，如果\(f\)可约，则\(f=gh\)，其中\(g,h\in k[X_1,\dots,X_n]\)且不是单位
    元，于是\(g+(f),h+(f)\)非零，而\((g+(f))(h+(f))=0+(f)\)，矛盾

    \(\Leftarrow\)：对于任意\(g,h,p\in k[X_1,\dots,X_n]\)，若\(gh=fp\)，因为\(k[X_1,\dots,X_n]\)是唯一因子分解环，
    于是\(f\)整除\(g\)或者\(f\)整除\(h\)
    #+END_proof
* 局部环
    一个环是局部环当且仅当所有非单位元构成一个理想。等价地，一个环是局部环当且仅当所有非单位元构成一个理想。

    在环的语言\(\call_{ring}=\{+,\times,0,1\}\)中局部环可以公理为
    1. \(R\)是环。
    2. 所有的非单位元构成一个集合\(\fm\)是理想，即\(\fm\)关于"+"封闭，关于"\(\times\)"吸收。


    但是非单位元关于"\(\times\)"总是吸收的，故而（2）可以改为
    2. [@2] 所有非单位元关于“+”封闭，即\(\fm\)是一个群。

    #+BEGIN_remark
    * \(0\in\R\)出解析函数的函数芽的环\(A\)是局部环
    * 一个函数\(f\)在\(0\in\R\)处解析\(\Leftrightarrow\)存在开邻域\(U\ni 0\)使得\(f\)在\(U\)上是个幂级数，即
      \(f\uhr_U=\sum_{n=0}^\infty a_nx^n\)，其中\(a_n\in\R\)。
    * 显然，\(\sum a_nx^n\sim\sum b_nx^n\Leftrightarrow\forall n(a_n=b_n)\)，故而
      \begin{equation*}
      A=\{f\mid f\text{是幂级数且收敛半径}>0\}
      \end{equation*}
    * \(\fm=x A=\{xf\mid f\in A\}\)是唯一的极大理想，其中极大是因为\(A/\fm\cong\R\)。
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    设\(R\)是一个环，称\(\sum_{n=0}^\infty r_nx^n\) (\(r_n\in R\))的元素为\(R\)上的形式幂级数，令\(R[[x]]\)为\(R\)
    上所有形式幂级数构成的集合，定义
    1. \(\sum r_nx^n+\sum s_nx^n=\sum(r_n+s_n)x^n\)
    2. \(\sum r_nx^n\sum s_nx^n=\sum_n(\sum_{i+j=n}r_is_j)x^n\)


    则\((R[[x]],+,\times,0_R,1_R)\)是一个环。
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(R\)是一个环，称\(R[[x]]\)为\(R\)的 *形式幂级数环* ，若\(g=\sum r_nx^n\in R[[x]]\)，则\(g\)的 *度数* 记
    作\(\deg(g)\)，定义为
    \begin{equation*}
    \deg(g)=\min(n\in\N\mid r_n\neq 0)
    \end{equation*}
    定义\(\deg(0)=\infty\)。（因此\(\deg(g)\ge 0\)）
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    假设\(R是整环\)
    1. 若\(f\in R[[x]]\)，且\(\deg(f)=n\)，则
       \begin{equation*}
       f=x^n(\sum r_kx^k)
       \end{equation*}
       其中\(r_0\neq 0\)，即\(f=x^ng\)其中\(\deg(g)=0\)
    2. 若\(f,g\in R[[x]]\)，则\(\deg(fg)=\deg(f)+\deg(g)\)
    3. 若\(f=\sum r_nx^n\), \(g=\sum s_nx^n\)，则\(fg=1\Rightarrow r_0s_0=1\)
    4. 若\(f=\sum r_nx^n\)，则\(f\)是单位\(\Rightarrow\) \(r_0\)是单位(\(r_0\neq 0\))
    #+END_lemma

    #+BEGIN_proof
    1. 由定义，若\(f=\sum s_kx^k\)且\(\deg(f)=n\)，则\(s_0=\dots=s_{n-1}=0\)且\(s_n\neq 0\)，因此
       \(f=x^n(\sum_{k=n}^\infty s_kx^k)\)，对任意\(i\in\N\)，令\(r_i=s_{i+n}\)，则\(f=x^n(\sum r_kx^k)\)，其
       中\(r_0\neq 0\)。
    2. 假设\(\deg(f)=n\)，\(\deg(g)=m\)，则由（1），\(f=x^n(\sum r_kx^k)\)，\(g=x^m(\sum s_kx^k)\)，其
       中\(r_0,s_0\neq 0\)，因此\(fg=x^{n+m}\sum_{n=0}^\infty(\sum_{i+j=n}r_is_j)x^n\)，因为\(r_0,s_0\neq 0\)，\(R\)是
       整环，因此\(r_0s_0\neq 0\)，因此\(\deg(fg)=n+m=\deg(f)+\deg(g)\)。
    3. 由定义，\(fg=\sum_{n=0}^\infty(\sum_{i+j=n}r_is_j)x^n=1\)，因此\(r_0s_0=1\)
    4. 如果\(f\)是单位，则存在\(g\in R[[x]]\)使得\(fg=1\)，由（3），\(r_0\)是单位。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(R\)是局部环，则\(R[[x]]\)也是局部环。
    #+END_proposition

    #+BEGIN_proof
    * 只需验证非单位元关于加法封闭。
    * 设\(f\in R[[x]]\)是单位元，则\(f=r_0+g\)，其中\(r_0\)是\(R\)的单位，\(\deg(g)\ge 1\)。
    * 令一方面，若\(f=r_0+g\)且\(r_0\in R\)是单位，\(\deg(g)\ge 1\)，取\(s_0\in R\)使得\(s_0r_0=1_R\)，则
        \(s_0f=1+s_0g\)，令\(h=-s_0g\)。
    #+BEGIN_claim
    \(h+h^2+h^3+\dots\in R[[x]]\)
    #+END_claim

    \begin{proof}
    设\(h=\sum s_kx^k\)，其中\(s_0=0\)，令\(g=\sum_{n=1}^\infty h^n=\sum r_kx^k\)，于是\(r_0\in R\)，若\(r_0,\dots,r_n\in R\)，
    则\(r_{n+1}=s_{n+1}+\sum_{i=1}^{n-1}s_ir_{n-i}\in R\)，因此对于任意\(k\in\N\)，\(r_k\in R\)，因此\(g\in R[[x]]\)。
    \end{proof}
    * 考虑等式\((1-h)(1+h+h^2+\dots)=1\)，则\(s_0f(1+h+h^2+\dots)=1\)，故\(f\)是单位，因此
    * \(f\in R[[x]]\)是单位\(\Leftrightarrow\)\(f=r_0+g\)，其中\(r_0\)是单位且\(\deg(g)\ge 1\)。
    * \(f\in R[[x]]\)不是单位\(\Leftrightarrow\)\(\deg(f)\ge 1\)或\(f=r+g\)，其中\(r\)不是单位且\(\deg(g)\ge 1\)。
    * \(f\)不是单位\(\Leftrightarrow\)\(f\in \fm_0+xR[[x]]=\{r+g\mid r\in\fm_0,g\in xR[x]\}\)，其中\(\fm_0\)是\(R\)的极大理想。
    * 显然\(\fm_0+xR[[x]]\)是“+”封闭的，故\(R[[x]]\)是局部环。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(R\)是局部环，\(\fm_0\)为\(R\)的极大理想，则
    1. \(R[[x]]\)是局部环，其极大理想为
       \begin{equation*}
       \fm_0+(x)
       \end{equation*}
    3. 若\(k\)是域，则\(k[[x]]\)中的理想排成一个降链
       \begin{equation*}
       I_0=\fm_0+(x)\supseteq I_1=(x)\supseteq\dots\supseteq I_n=(x^n)\supseteq\dots
       \end{equation*}
    #+END_corollary

    #+BEGIN_proof
    1. 已证。
    2. 设\(J\)是\(k[[x]]\)的理想，令\(n=\min\{\deg(f)\mid f\in J\}\)，若\(n=\infty\)，则\(J=(0)\)。

       若\(n<\infty\)且\(f=x^ng\in J\)其中\(\deg(g)=0\)，由于\(g\)的首项是单位，因此\(g\)是单位，令\(h\in R[[x]]\)
       使得\(hg=1\)，则\(x^n=hf=hgx^n\in J\)，因此\((x^n)\subseteq J\)，又由\(n\)的定义，\(J\subseteq(x^n)\)，所以\(J=(x^n)\)。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(k\)是域，则\(k[[x]]\)是局部环，其极大理想为\((x)=xk[[x]]\)，剩余域为\(k\)。
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    定义\(k[[X_1,\dots,X_{n+1}]]=k[[X_1,\dots,X_n]][[X_{n+1}]]\)，则\(k[[X_1,\dots,X_{n+1}]]\)为局部环，其极大理
    想\(\fm\)为\((X_1,\dots,X_{n+1})\)，剩余域为\(k\)。
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    令\(p\in\Z\)是一个素数，
    1. \(\Z/p\Z\)是一个域，这是因为若\(0<r<p\)，则\((r,p)=1\)，故存在\(m,n\)使得
       \begin{equation*}
       mr+np=1\Rightarrow mr\equiv_p1
       \end{equation*}
        故\(\Z/p\Z\)是一个局部环
    2. 对每个\(n\in\N^+\)，\(\Z/p^n\Z\)是局部环
       * \(\Z\)中包含\((p^n)\)的理想与\(\Z/p^n\Z\)中的理想一一对应
       * \(\Z\)中的理想均形如\((k)\)
       * \((p^n)\subseteq(k)\Leftrightarrow k\mid p^n\Rightarrow k=p^m\)，其中\(m\le n\)
       * 故\(\Z/p^n\Z\)中的理想为
         \begin{equation*}
         p^n\Z/p^n\Z=(0)\subseteq p^{n-1}\Z/p^n\Z\subseteq\dots\subseteq p\Z/p^n\Z
         \end{equation*}
       * 故\(p\Z/p^n\Z\)为\(\Z/p^n\Z\)的唯一极大理想，显然\(\Z/p^n\Z\)中有\(p^n\)个元素。

       *  \(\Z/p^n\Z\)的元素可唯一表示为
       \begin{equation*}
       a_0+a_1p+\dots+a_{n-1}p^{n-1}
       \end{equation*}
            其中 \(a_i\in\{0,\dots,p-1\}\)。
    3. 若\(m>n\)，则\(\Z\to\Z/p^m\Z\)和\(\Z\to\Z/p^n\Z\)诱导了
       \begin{center}\begin{tikzcd}
       \Z\ar[r]\ar[d]&\Z/p^m\Z\ar[dl]\\
       \Z/p^n\Z
       \end{tikzcd}\end{center}
       * \(\forall m>n\)，令\(\pi_{mn}\)为\(\Z/(p^m)\)到\(\Z/(p^n)\)的自然同态，即
       \begin{equation*}
       \pi_{mn}(a_0+a_1p+\dots+a_{m-1}p^{m-1})=a_0+\dots+a_{n-1}p^{n-1}
       \end{equation*}
       * 令\(\Z^*=\prod_{n=1}^\infty\Z/(p^n)=\{(x_1,x_2,\dots)\mid x_n\in\Z/(p^n)\}\)，
       * 将\(x_n\)看作\(a_0+\dots+a_{n-1}p^{n-1}\)或序列\((a_0,\dots,a_{n-1})\)
       * 定义\(\Z_p\subseteq\Z^*\)为
       \begin{equation*}
       \{(x_1,x_2,\dots,)\mid\pi_{mn}(x_m)=x_n,m>n\}
       \end{equation*}
       * 将\((x_1,x_2,\dots)\)中的每个\(x_n\)看作\(a_0+\dots+a_{n-1}p^{n-1}\)，则\((x_1,x_2,\dots)\in \Z_p\Leftrightarrow\forall m>n\), \(x_m\)是\(x_n\)的延长

       * 故而\((x_1,x_2,\dots)\in\Z_p\)唯一对应一个幂级数\(a_0+a_1p+a_2p^2+\dots\)

       * 定义\(\Z^*\)中的+为
       \begin{equation*}
       (x_1,x_2,\dots)+(y_1,y_2,\dots)=(x_1+y_1,x_2+y_2,\dots)
       \end{equation*}
       * 定义\(\Z^*\)中的"\(\times\)"为
       \begin{equation*}
       (x_1,x_2,\dots)\cdot(y_1,y_2,\dots)=(x_1y_1,x_2y_2,\dots)
       \end{equation*}
       * 定义零为\((0,0,\dots,)\)，幺为\((1,1,\dots)\)，则\(\Z^*\)为环。

       * 由于每个\(\pi_{mn}\)是同态，故\(\Z_p\)对“+”与“\(\times\)”封闭：对任意\((x_1,x_2,\dots),(y_1,y_2,\dots)\in\Z_p\)，
         对任意\(m>n\)，因为\(\pi_{mn}\)是同态，有\(\pi_{mn}(x_m+y_m)=\pi_{mn}(x_m)+\pi_{mn}(y_m)=x_n+y_n\)，
         \(\pi_{mn}(x_m\cdot y_m)=\pi_{mn}(x_m)\cdot\pi_{mn}(y_m)=x_n\cdot y_n\)，故\((x_1,x_2,\dots)+(y_1,y_2,\dots),(x_1,x_2,\dots)\cdot(y_1,y_2,\dots)\in\Z_p\)。
       * 故\(\Z_p\)是一个环，称其为 *\(p\)-进整数环* 。
       *  \(\Z_p\)也称为\(\Z/(p^n)\)的逆极限，即\(\Z_p=\varprojlim\Z/(p^n)\)
    #+END_examplle

    #+BEGIN_remark
    设\(x=(x_1,x_2,\dots)\in\Z_p\)，则\(x\)可以记作\(a_0+a_1p+a_2p^2+\dots\)，其中每个\(a_i\in\{0,\dots,p-1\}\)，因此
    \(x_1=a_0\), \(x_2=a_0+a_1p\)，\(\dots\)，\(x_n=\sum_{k=0}^{n-1}a_kp^k\)。

    设\(y=(y_1,y_2,\dots)\in\Z_p\)，设它可写作\(b_0+b_1p+\dots\)，令\(z=x+y=(x_1+y_1,x_2+y_2,\dots)\)，
    将\(z\)写作\(\sum_{k=0}^\infty c_kp^k\)，则
    \begin{equation*}
    z_n=x_n+y_n=(\sum_{k=0}^{n-1}a_kp^k+\sum_{k=0}^{n-1}b_kp^k)(\mod p^k)
    \end{equation*}
    即\(z_n\)是\(x_n+y_n\)的\(p\)-进制展开的前\(n\)项。

    同理若\(z=xy\)，则\(z_n\)是\(x_ny_n\)的\(p\)-进制展开的前\(n\)项。

    故\(\Z_p\)中的运算是“\(p\)-进制”运算。
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:6
    若\(A,B\)是局部环，则\(f:A\to B\)是满同态，则\(a\in A\)是单位\(\Leftrightarrow\)\(f(a)\in B\)是单位
    #+END_lemma

    #+BEGIN_proof
    * 令\(\fm\)是\(B\)的极大理想，
    * 则\(\barf:A/f^{-1}(\fm)\to B/\fm\)是同构，
    * 而\(B/\fm\)是域，故\(A/f^{-1}(\fm)\)是域，故\(f^{-1}(\fm)\)是极大理想，
    * 故\(a\in A\)是单位\(\Leftrightarrow\)\(a\notin f^{-1}(\fm)\)\(\Leftrightarrow\) \(f(a)\notin\fm\)是\(B\)的单位。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(\Z_p\)是局部环
    2. \(\Z_p\)的理想排成降链
       \begin{equation*}
       p\Z_p\supseteq p^2\Z_p\supseteq\dots
       \end{equation*}
    3. \(\Z_p/p^n\Z_p\cong\Z/p^n\Z\)
    #+END_proposition

    #+BEGIN_proof
    1. 设\(x=(x_1,x_2,\dots)=a_0+a_1p+\dots\in\Z_p\)，即\(x_1=a_0\)，\(x_2=a_0+a_1p\)，\(\dots\)。

       #+BEGIN_claim
       \(x\)是单位\(\Leftrightarrow\) \(a_0\neq 0\)
       #+END_claim

       \begin{proof}
       \(\Leftarrow\)：
       \begin{itemize}
       \item 若\(a_0\neq 0\)，则\(a_0\in\Z/p\Z\)是单位，
       \item 故存在\(b_0\in\Z/p\Z\)使得\(a_0b_0\equiv 1\mod p\)。
       \item 由于 \(\pi_{21}\)是同态，而\(a_0=\pi_{21}(a_0+a_1p)\)是单位，由引理\ref{6}，\(a_0+a_1p\in\Z/p^2\Z\)也是单位，
       \item 同理，\(\forall b_1\in\{0,\dots,p-1\}\)，\(b_0+b_1p\in\Z/p^2\Z\)是单位，
       \item 令\(c_0+c_1p\in\Z/p^2\Z\)使得
       \begin{equation*}
       (a_0+a_1p)(c_0+c_1p)=1\in\Z/p^2\Z
       \end{equation*}
       \item 则\(\pi_{21}((a_0+a_1p)(c_0+c_1p))=a_0c_0=1=a_0b_0\)。
       \item 故\(a_0c_0-a_0b_0\equiv 0\mod p\)，因此\(c_0\equiv b_0\mod p\)，所以\(c_0=b_0\)。
       \item 一般地，设\(b_0+b_1x+\dots+b_{n-1}x^{n-1}\in\Z/(p^n)\)使得
       \((a_0+\dots+a_{n-1}x^{n-1})(b_0+\dots+b_{n-1}x^{n-1})=1\in\Z/p^n\Z\)，
       \item 则存在\(b_n\in\{0,\dots,p-1\}\)使得在\(\Z/(p^{n+1})\)中有
       \((a_0+\dots+a_nx^n)(b_0+\dots+b_nx^n)=1\)。
       \item 令\(y=b_0+b_1+\dots=(y_1,y_2,\dots)\)，则\(xy=1\)，故\(x\)是单位。
       \end{itemize}

       \(\Rightarrow\)：若\(a_0=0\)，则\(x=(0,x_2,\dots)\)显然不是单位。
       \end{proof}

       以上断言表明，所有非单位元形如\(x=(0,x_2,x_3,\dots)\)是一个加法群，故而是极大理想，恰好是\(p\Z_p\)

    2. 设\(J\subseteq\Z_p\)是一个非平凡理想
       * 令\(k=\min\{n\in\N\mid p^n\in J\}\)，显然\(k>0\)，\(p^k\Z_p\subseteq J\)
       * 断言\(p^k\Z_p=J\)。
       * 设\(x=a_0+a_1p+\dots\in J\)，令\(a_m\)是第一个非零系数
       * 则\(x=p^m(a_m+a_{m+1}p+\dots)\)，
       * 因为\(a_m\neq 0\)，\(a_m+a_{m+1}p+\dots\)是单位，故存在\(y\in\Z_p\)使得\(xy=p^m\in J\)
       * 由定义，\(k\le m\Rightarrow p^m\in p^k\Z_p\Rightarrow x\in p^k\Z_p\)，
       * 即\(\Z_p\)的每个非平反理想都形如\(p^k\Z_p\)。
    3. 投射函数诱导了一个同态
       \begin{center}\begin{tikzcd}
       \Z^*\ar[r,"\pi_n"]&\Z/(p^n)\\
       \Z_p\ar[u]\ar[ur,"\pi_n"']
       \end{tikzcd}\end{center}
       其中 \(\pi_n:\Z_p\to\Z/(p^n)\)，\(x=(x_1,\dots,x_n,\dots)\mapsto x_n\)，于是
       \begin{align*}
       x\in\ker(\pi_n)&\Leftrightarrow x_n=0\\
       &\Leftrightarrow x=(0,\dots,0,x_{n+1},\dots)\\
       &\Leftrightarrow x=a_{n}p^n+a_{n+1}p^{n+1}\dots\\
       &\Leftrightarrow x\in p^n\Z_p
       \end{align*}

    #+END_proof

    #+BEGIN_remark
    证明\(\Z_p\)是局部环的关键是验证
    \begin{equation*}
    x=a_0+a_1p+\dots\text{是单位}\Leftrightarrow a_0\neq 0
    \end{equation*}
    #+END_remark

    以下证明更简洁：
    * 设\(x=(x_1,x_2,\dots)\in\Z_p\subseteq\prod\Z/(p^n)\)，\(x_1=a_0,\dots,x_n=a_0+a_1p+\dots+a_{n-1}p^{n-1},\dots\)
    * 由于每个\(\Z/(p^n)\)都是局部环且\(p\Z/(p^n)\)是其极大理想，
    * 故每个\(x_n\)在\(\Z/(p^n)\)中可逆，令\(y_n\)是\(x_n\)在\(\Z/(p^n)\)的逆
    * \(\pi_{mn}(x_my_m)=\pi_{mn}(x_m)\pi_{mn}(y_m)=x_n\pi_{mn}(y_m)=1\)，
    * 故\(\forall n<m\)，\(\pi_{mn}(y_m)\)都是\(x_n\)的逆
    * 断言：\(\pi_{mn}(y_m)=y_n\)
    * \(x_n(y_n-\pi_{mn}(y_m))=0\Rightarrow y_nx_n(y_n-\pi_{mn}(y_m))=0\)，
    * 故\(y=(y_1,y_2,\dots)\)是\(x\)的逆

    更加简洁的方法：
    * 取\(b\in\{0,\dots,p-1\}\)使得\(a_0\cdot b\equiv 1\mod p\)，
    * 则\(bx=1+p(b_0+b_1p+\dots)=1-py\)，
    * 令\(c=1+py+p^2y^2+\dots\in\Z_p\)，
    * 则\(bxc=(1-py)(1+py+(py)^2+\dots)=1\)

    #+BEGIN_remark
    * \(\Z\mapsto\Z_p\), \(x\mapsto x\)的\(p\)-进制展开是一个单同态。
    * \(\Z\)中不能被\(p\)整除的元素都是\(\Z_p\)的单位。
    * 令\(S=\Z-(p)\)，则\(S\)是乘法集，\(\Z\)关于\((p)\)的局部化\(\Z_{(p)}=S^{-1}\Z\subseteq\Q\)是局部环，
      且\(pS^{-1}\Z\)是极大理想
    * \(\Z_{(p)}=\{\frac{a}{b}:a,b\in\Z,b\nmid b\}\subseteq\Q\)
    * \(\Z\)到\(\Z_p\)的嵌入自然地扩张为\(\Z_{(p)}\)到\(\Z_p\)的嵌入
      \begin{center}\begin{tikzcd}
      f:\Z\to\Z_p\ar[d]\\
      \parbox{3cm}{\centering \(\tilde{f}:S^{-1}\Z\to\Z_p\) \(\frac{a}{b}\mapsto(f(b))^{-1}a\)}
      \end{tikzcd}\end{center}
    * \(\Z_p\cap\Q=\Z_{(p)}\)
    * 在形式上，\(\Z_p\)与\(\F_p[[X]]\)有相似之处，然而\(\Char(\Z_p)=0\)，而\(\Char(\F_p[[X]])=p\)
    #+END_remark
