#+title: Valuation Field
#+EXPORT_FILE_NAME: ../latex/ValuationField/ValuationField.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{/Users/wu/notes/preamble.tex}
#+LATEX_HEADER: \usepackage[UTF8]{ctex}
#+LATEX_HEADER: \DeclareMathOperator{\Char}{Char}
#+LATEX_HEADER: \makeindex
* 环与理想
** 介绍
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    称\(A\)为 *局部环* ，如果\(A\)只有一个极大理想 \(I\)，称\(k=A/I\)为\(A\)的 *剩余域* （residue field）
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. 设\(A\)为环，\(I\subsetneq A\)为理想，若每个\(x\in A\setminus I\)均是单位元则\(A\)是局部环，\(I\)是极大
       理想
    2. 若\(A\)为环，\(I\subseteq A\)为极大理想，若\(\forall a\in I\)，有\(1+a\)均是单位元，则\(A\)是局部环
    #+END_proposition


** 分式化
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(A\)是一个整环，令\(A^\times=A\setminus\{0\}\)，在\(A\times A^\times\)上定义关系\(\sim\)为
    \begin{equation*}
    (a,s)\sim(b,t)\Leftrightarrow at-bs=0
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    称\(S\subseteq A\)为 *乘法子集* ，如果\(1\in S\)且\(a,b\in S\Rightarrow ab\in S\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(S\subseteq A\)是乘法子集，定义\(A\times S\)上的等价关系\(\sim\)为
    \begin{equation*}
    (a,s)\sim(b,t)\Leftrightarrow\exists u\in S(u(at-bs)=0)
    \end{equation*}
    将\((a,s)\)的等价类记作\(\frac{a}{s}\)，定义
    \begin{equation*}
    \frac{a}{s}+\frac{b}{t}=\frac{at+bs}{st},\quad\frac{a}{s}\frac{b}{t}=\frac{ab}{st}
    \end{equation*}
    则\(A\times S/\sim\)是一个环，记作\(S^{-1}A\)
    #+END_definition

    #+BEGIN_remark
    * \(\forall x\in A\)，\(\frac{xa}{xs}=\frac{a}{s}\)
    * 若\(S\)有零因子，则\(S^{-1}A=0\)平凡
    * \(A\to S^{-1}A\), \(a\mapsto\frac{a}{1}\)是同态
    * 若\(A\)是整环，\(S=A^\times\)，则\(S^{-1}=\Frac(A)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    若\(\fp\)是素理想，\(S=A\setminus \fp\)是乘法子集
    * 令\(A_{\fp}=S^{-1}A\)
    * 令\(\fm=\{\frac{a}{s}\mid a\in\fp,s\notin\fp\}=pA_{\fp}=\fp S^{-1}\)，则\(A_{\fp}\)是局部环，\(\fm\)是\(A_{\fp}\)的极大理想
    #+END_examplle



** 多项式环
    设\(A\)是一个环，则多项式环\(A[X]\)的元素都形如
    \begin{equation*}
    \sum_{i=0}^na_ix^i,\quad a_i\in A,i\in\N
    \end{equation*}

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(A\)是环，\(a\in A\) *不可约* 如果\(a\neq 0\)不是单位元且\(\forall b,c\in A(a=bc\Rightarrow)\)\(b\)或\(c\)为单位元

    一个整环\(A\)是 *唯一因子分解环* ，如果\(\forall a\in A\)，存在不可约元\(b_1,\dots,b_n\in A\)使得\(a=b_1\dotsb_n\)
    并且若存在不可约元\(c_1,\dots,c_m\)使得\(a=c_1\dots c_m\)则\(m=n\)，则\(\forall i<n\exists j<n(b_i=u_{ij}c_j)\)，其
    中\(u_{ij}\)是单位元
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(A\)是唯一因子分解环，则\(A[X]\)也是
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(k\)是域，则\(k[X_1,\dots,X_n]\)是唯一因子分解环
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(k\)是域，\(f\in k[X_1,\dots,X_n]\)，则\((f)\)是素理想\(\Leftrightarrow\)\(f\)不可约
    #+END_corollary

    #+BEGIN_proof
    \(\Rightarrow\)：\(k[X_1,\dots,X_n]/(f)\)是整环，如果\(f\)可约，则\(f=gh\)，其中\(g,h\in k[X_1,\dots,X_n]\)且不是单位
    元，于是\(g+(f),h+(f)\)非零，而\((g+(f))(h+(f))=0+(f)\)，矛盾

    \(\Leftarrow\)：对于任意\(g,h,p\in k[X_1,\dots,X_n]\)，若\(gh=fp\)，因为\(k[X_1,\dots,X_n]\)是唯一因子分解环，
    于是\(f\)整除\(g\)或者\(f\)整除\(h\)
    #+END_proof
* 局部环
    一个环是局部环当且仅当所有非单位元构成一个理想。等价地，一个环是局部环当且仅当所有非单位元构成一个理想。

    在环的语言\(\call_{ring}=\{+,\times,0,1\}\)中局部环可以公理为
    1. \(R\)是环。
    2. 所有的非单位元构成一个集合\(\fm\)是理想，即\(\fm\)关于"+"封闭，关于"\(\times\)"吸收。


    但是非单位元关于"\(\times\)"总是吸收的，故而（2）可以改为
    2. [@2] 所有非单位元关于“+”封闭，即\(\fm\)是一个群。

    #+BEGIN_remark
    * \(0\in\R\)出解析函数的函数芽的环\(A\)是局部环
    * 一个函数\(f\)在\(0\in\R\)处解析\(\Leftrightarrow\)存在开邻域\(U\ni 0\)使得\(f\)在\(U\)上是个幂级数，即
      \(f\uhr_U=\sum_{n=0}^\infty a_nx^n\)，其中\(a_n\in\R\)。
    * 显然，\(\sum a_nx^n\sim\sum b_nx^n\Leftrightarrow\forall n(a_n=b_n)\)，故而
      \begin{equation*}
      A=\{f\mid f\text{是幂级数且收敛半径}>0\}
      \end{equation*}
    * \(\fm=x A=\{xf\mid f\in A\}\)是唯一的极大理想，其中极大是因为\(A/\fm\cong\R\)。
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    设\(R\)是一个环，称\(\sum_{n=0}^\infty r_nx^n\) (\(r_n\in R\))的元素为\(R\)上的形式幂级数，令\(R[[x]]\)为\(R\)
    上所有形式幂级数构成的集合，定义
    1. \(\sum r_nx^n+\sum s_nx^n=\sum(r_n+s_n)x^n\)
    2. \(\sum r_nx^n\sum s_nx^n=\sum_n(\sum_{i+j=n}r_is_j)x^n\)


    则\((R[[x]],+,\times,0_R,1_R)\)是一个环。
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(R\)是一个环，称\(R[[x]]\)为\(R\)的 *形式幂级数环* ，若\(g=\sum r_nx^n\in R[[x]]\)，则\(g\)的 *度数* 记
    作\(\deg(g)\)，定义为
    \begin{equation*}
    \deg(g)=\min(n\in\N\mid r_n\neq 0)
    \end{equation*}
    定义\(\deg(0)=\infty\)。（因此\(\deg(g)\ge 0\)）
    #+END_definition


    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    假设\(R是整环\)
    1. 若\(f\in R[[x]]\)，且\(\deg(f)=n\)，则
       \begin{equation*}
       f=x^n(\sum r_kx^k)
       \end{equation*}
       其中\(r_0\neq 0\)，即\(f=x^ng\)其中\(\deg(g)=0\)
    2. 若\(f,g\in R[[x]]\)，则\(\deg(fg)=\deg(f)+\deg(g)\)
    3. 若\(f=\sum r_nx^n\), \(g=\sum s_nx^n\)，则\(fg=1\Rightarrow r_0s_0=1\)
    4. 若\(f=\sum r_nx^n\)，则\(f\)是单位\(\Rightarrow\) \(r_0\)是单位(\(r_0\neq 0\))
    #+END_lemma

    #+BEGIN_proof
    1. 由定义，若\(f=\sum s_kx^k\)且\(\deg(f)=n\)，则\(s_0=\dots=s_{n-1}=0\)且\(s_n\neq 0\)，因此
       \(f=x^n(\sum_{k=n}^\infty s_kx^k)\)，对任意\(i\in\N\)，令\(r_i=s_{i+n}\)，则\(f=x^n(\sum r_kx^k)\)，其
       中\(r_0\neq 0\)。
    2. 假设\(\deg(f)=n\)，\(\deg(g)=m\)，则由（1），\(f=x^n(\sum r_kx^k)\)，\(g=x^m(\sum s_kx^k)\)，其
       中\(r_0,s_0\neq 0\)，因此\(fg=x^{n+m}\sum_{n=0}^\infty(\sum_{i+j=n}r_is_j)x^n\)，因为\(r_0,s_0\neq 0\)，\(R\)是
       整环，因此\(r_0s_0\neq 0\)，因此\(\deg(fg)=n+m=\deg(f)+\deg(g)\)。
    3. 由定义，\(fg=\sum_{n=0}^\infty(\sum_{i+j=n}r_is_j)x^n=1\)，因此\(r_0s_0=1\)
    4. 如果\(f\)是单位，则存在\(g\in R[[x]]\)使得\(fg=1\)，由（3），\(r_0\)是单位。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(R\)是局部环，则\(R[[x]]\)也是局部环。
    #+END_proposition

    #+BEGIN_proof
    * 只需验证非单位元关于加法封闭。
    * 设\(f\in R[[x]]\)是单位元，则\(f=r_0+g\)，其中\(r_0\)是\(R\)的单位，\(\deg(g)\ge 1\)。
    * 令一方面，若\(f=r_0+g\)且\(r_0\in R\)是单位，\(\deg(g)\ge 1\)，取\(s_0\in R\)使得\(s_0r_0=1_R\)，则
        \(s_0f=1+s_0g\)，令\(h=-s_0g\)。
    #+BEGIN_claim
    \(h+h^2+h^3+\dots\in R[[x]]\)
    #+END_claim

    \begin{proof}
    设\(h=\sum s_kx^k\)，其中\(s_0=0\)，令\(g=\sum_{n=1}^\infty h^n=\sum r_kx^k\)，于是\(r_0\in R\)，若\(r_0,\dots,r_n\in R\)，
    则\(r_{n+1}=s_{n+1}+\sum_{i=1}^{n-1}s_ir_{n-i}\in R\)，因此对于任意\(k\in\N\)，\(r_k\in R\)，因此\(g\in R[[x]]\)。
    \end{proof}
    * 考虑等式\((1-h)(1+h+h^2+\dots)=1\)，则\(s_0f(1+h+h^2+\dots)=1\)，故\(f\)是单位，因此
    * \(f\in R[[x]]\)是单位\(\Leftrightarrow\)\(f=r_0+g\)，其中\(r_0\)是单位且\(\deg(g)\ge 1\)。
    * \(f\in R[[x]]\)不是单位\(\Leftrightarrow\)\(\deg(f)\ge 1\)或\(f=r+g\)，其中\(r\)不是单位且\(\deg(g)\ge 1\)。
    * \(f\)不是单位\(\Leftrightarrow\)\(f\in \fm_0+xR[[x]]=\{r+g\mid r\in\fm_0,g\in xR[x]\}\)，其中\(\fm_0\)是\(R\)的极大理想。
    * 显然\(\fm_0+xR[[x]]\)是“+”封闭的，故\(R[[x]]\)是局部环。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(R\)是局部环，\(\fm_0\)为\(R\)的极大理想，则
    1. \(R[[x]]\)是局部环，其极大理想为
       \begin{equation*}
       \fm_0+(x)
       \end{equation*}
    3. 若\(k\)是域，则\(k[[x]]\)中的理想排成一个降链
       \begin{equation*}
       I_0=\fm_0+(x)\supseteq I_1=(x)\supseteq\dots\supseteq I_n=(x^n)\supseteq\dots
       \end{equation*}
    #+END_corollary

    #+BEGIN_proof
    1. 已证。
    2. 设\(J\)是\(k[[x]]\)的理想，令\(n=\min\{\deg(f)\mid f\in J\}\)，若\(n=\infty\)，则\(J=(0)\)。

       若\(n<\infty\)且\(f=x^ng\in J\)其中\(\deg(g)=0\)，由于\(g\)的首项是单位，因此\(g\)是单位，令\(h\in R[[x]]\)
       使得\(hg=1\)，则\(x^n=hf=hgx^n\in J\)，因此\((x^n)\subseteq J\)，又由\(n\)的定义，\(J\subseteq(x^n)\)，所以\(J=(x^n)\)。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    若\(k\)是域，则\(k[[x]]\)是局部环，其极大理想为\((x)=xk[[x]]\)，剩余域为\(k\)。
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    定义\(k[[X_1,\dots,X_{n+1}]]=k[[X_1,\dots,X_n]][[X_{n+1}]]\)，则\(k[[X_1,\dots,X_{n+1}]]\)为局部环，其极大理
    想\(\fm\)为\((X_1,\dots,X_{n+1})\)，剩余域为\(k\)。
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    令\(p\in\Z\)是一个素数，
    1. \(\Z/p\Z\)是一个域，这是因为若\(0<r<p\)，则\((r,p)=1\)，故存在\(m,n\)使得
       \begin{equation*}
       mr+np=1\Rightarrow mr\equiv_p1
       \end{equation*}
        故\(\Z/p\Z\)是一个局部环
    2. 对每个\(n\in\N^+\)，\(\Z/p^n\Z\)是局部环
       * \(\Z\)中包含\((p^n)\)的理想与\(\Z/p^n\Z\)中的理想一一对应
       * \(\Z\)中的理想均形如\((k)\)
       * \((p^n)\subseteq(k)\Leftrightarrow k\mid p^n\Rightarrow k=p^m\)，其中\(m\le n\)
       * 故\(\Z/p^n\Z\)中的理想为
         \begin{equation*}
         p^n\Z/p^n\Z=(0)\subseteq p^{n-1}\Z/p^n\Z\subseteq\dots\subseteq p\Z/p^n\Z
         \end{equation*}
       * 故\(p\Z/p^n\Z\)为\(\Z/p^n\Z\)的唯一极大理想，显然\(\Z/p^n\Z\)中有\(p^n\)个元素。

       *  \(\Z/p^n\Z\)的元素可唯一表示为
       \begin{equation*}
       a_0+a_1p+\dots+a_{n-1}p^{n-1}
       \end{equation*}
            其中 \(a_i\in\{0,\dots,p-1\}\)。
    3. 若\(m>n\)，则\(\Z\to\Z/p^m\Z\)和\(\Z\to\Z/p^n\Z\)诱导了
       \begin{center}\begin{tikzcd}
       \Z\ar[r]\ar[d]&\Z/p^m\Z\ar[dl]\\
       \Z/p^n\Z
       \end{tikzcd}\end{center}
       * \(\forall m>n\)，令\(\pi_{mn}\)为\(\Z/(p^m)\)到\(\Z/(p^n)\)的自然同态，即
       \begin{equation*}
       \pi_{mn}(a_0+a_1p+\dots+a_{m-1}p^{m-1})=a_0+\dots+a_{n-1}p^{n-1}
       \end{equation*}
       * 令\(\Z^*=\prod_{n=1}^\infty\Z/(p^n)=\{(x_1,x_2,\dots)\mid x_n\in\Z/(p^n)\}\)，
       * 将\(x_n\)看作\(a_0+\dots+a_{n-1}p^{n-1}\)或序列\((a_0,\dots,a_{n-1})\)
       * 定义\(\Z_p\subseteq\Z^*\)为
       \begin{equation*}
       \{(x_1,x_2,\dots,)\mid\pi_{mn}(x_m)=x_n,m>n\}
       \end{equation*}
       * 将\((x_1,x_2,\dots)\)中的每个\(x_n\)看作\(a_0+\dots+a_{n-1}p^{n-1}\)，则\((x_1,x_2,\dots)\in \Z_p\Leftrightarrow\forall m>n\), \(x_m\)是\(x_n\)的延长

       * 故而\((x_1,x_2,\dots)\in\Z_p\)唯一对应一个幂级数\(a_0+a_1p+a_2p^2+\dots\)

       * 定义\(\Z^*\)中的+为
       \begin{equation*}
       (x_1,x_2,\dots)+(y_1,y_2,\dots)=(x_1+y_1,x_2+y_2,\dots)
       \end{equation*}
       * 定义\(\Z^*\)中的"\(\times\)"为
       \begin{equation*}
       (x_1,x_2,\dots)\cdot(y_1,y_2,\dots)=(x_1y_1,x_2y_2,\dots)
       \end{equation*}
       * 定义零为\((0,0,\dots,)\)，幺为\((1,1,\dots)\)，则\(\Z^*\)为环。

       * 由于每个\(\pi_{mn}\)是同态，故\(\Z_p\)对“+”与“\(\times\)”封闭：对任意\((x_1,x_2,\dots),(y_1,y_2,\dots)\in\Z_p\)，
         对任意\(m>n\)，因为\(\pi_{mn}\)是同态，有\(\pi_{mn}(x_m+y_m)=\pi_{mn}(x_m)+\pi_{mn}(y_m)=x_n+y_n\)，
         \(\pi_{mn}(x_m\cdot y_m)=\pi_{mn}(x_m)\cdot\pi_{mn}(y_m)=x_n\cdot y_n\)，故\((x_1,x_2,\dots)+(y_1,y_2,\dots),(x_1,x_2,\dots)\cdot(y_1,y_2,\dots)\in\Z_p\)。
       * 故\(\Z_p\)是一个环，称其为 *\(p\)-进整数环* 。
       *  \(\Z_p\)也称为\(\Z/(p^n)\)的逆极限，即\(\Z_p=\varprojlim\Z/(p^n)\)
    #+END_examplle

    #+BEGIN_remark
    设\(x=(x_1,x_2,\dots)\in\Z_p\)，则\(x\)可以记作\(a_0+a_1p+a_2p^2+\dots\)，其中每个\(a_i\in\{0,\dots,p-1\}\)，因此
    \(x_1=a_0\), \(x_2=a_0+a_1p\)，\(\dots\)，\(x_n=\sum_{k=0}^{n-1}a_kp^k\)。

    设\(y=(y_1,y_2,\dots)\in\Z_p\)，设它可写作\(b_0+b_1p+\dots\)，令\(z=x+y=(x_1+y_1,x_2+y_2,\dots)\)，
    将\(z\)写作\(\sum_{k=0}^\infty c_kp^k\)，则
    \begin{equation*}
    z_n=x_n+y_n=(\sum_{k=0}^{n-1}a_kp^k+\sum_{k=0}^{n-1}b_kp^k)(\mod p^k)
    \end{equation*}
    即\(z_n\)是\(x_n+y_n\)的\(p\)-进制展开的前\(n\)项。

    同理若\(z=xy\)，则\(z_n\)是\(x_ny_n\)的\(p\)-进制展开的前\(n\)项。

    故\(\Z_p\)中的运算是“\(p\)-进制”运算。
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:6
    若\(A,B\)是局部环，则\(f:A\to B\)是满同态，则\(a\in A\)是单位\(\Leftrightarrow\)\(f(a)\in B\)是单位
    #+END_lemma

    #+BEGIN_proof
    * 令\(\fm\)是\(B\)的极大理想，
    * 则\(\barf:A/f^{-1}(\fm)\to B/\fm\)是同构，
    * 而\(B/\fm\)是域，故\(A/f^{-1}(\fm)\)是域，故\(f^{-1}(\fm)\)是极大理想，
    * 故\(a\in A\)是单位\(\Leftrightarrow\)\(a\notin f^{-1}(\fm)\)\(\Leftrightarrow\) \(f(a)\notin\fm\)是\(B\)的单位。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(\Z_p\)是局部环
    2. \(\Z_p\)的理想排成降链
       \begin{equation*}
       p\Z_p\supseteq p^2\Z_p\supseteq\dots
       \end{equation*}
    3. \(\Z_p/p^n\Z_p\cong\Z/p^n\Z\)
    #+END_proposition

    #+BEGIN_proof
    1. 设\(x=(x_1,x_2,\dots)=a_0+a_1p+\dots\in\Z_p\)，即\(x_1=a_0\)，\(x_2=a_0+a_1p\)，\(\dots\)。

       #+BEGIN_claim
       \(x\)是单位\(\Leftrightarrow\) \(a_0\neq 0\)
       #+END_claim

       \begin{proof}
       \(\Leftarrow\)：
       \begin{itemize}
       \item 若\(a_0\neq 0\)，则\(a_0\in\Z/p\Z\)是单位，
       \item 故存在\(b_0\in\Z/p\Z\)使得\(a_0b_0\equiv 1\mod p\)。
       \item 由于 \(\pi_{21}\)是同态，而\(a_0=\pi_{21}(a_0+a_1p)\)是单位，由引理\ref{6}，\(a_0+a_1p\in\Z/p^2\Z\)也是单位，
       \item 同理，\(\forall b_1\in\{0,\dots,p-1\}\)，\(b_0+b_1p\in\Z/p^2\Z\)是单位，
       \item 令\(c_0+c_1p\in\Z/p^2\Z\)使得
       \begin{equation*}
       (a_0+a_1p)(c_0+c_1p)=1\in\Z/p^2\Z
       \end{equation*}
       \item 则\(\pi_{21}((a_0+a_1p)(c_0+c_1p))=a_0c_0=1=a_0b_0\)。
       \item 故\(a_0c_0-a_0b_0\equiv 0\mod p\)，因此\(c_0\equiv b_0\mod p\)，所以\(c_0=b_0\)。
       \item 一般地，设\(b_0+b_1x+\dots+b_{n-1}x^{n-1}\in\Z/(p^n)\)使得
       \((a_0+\dots+a_{n-1}x^{n-1})(b_0+\dots+b_{n-1}x^{n-1})=1\in\Z/p^n\Z\)，
       \item 则存在\(b_n\in\{0,\dots,p-1\}\)使得在\(\Z/(p^{n+1})\)中有
       \((a_0+\dots+a_nx^n)(b_0+\dots+b_nx^n)=1\)。
       \item 令\(y=b_0+b_1+\dots=(y_1,y_2,\dots)\)，则\(xy=1\)，故\(x\)是单位。
       \end{itemize}

       \(\Rightarrow\)：若\(a_0=0\)，则\(x=(0,x_2,\dots)\)显然不是单位。
       \end{proof}

       以上断言表明，所有非单位元形如\(x=(0,x_2,x_3,\dots)\)是一个加法群，故而是极大理想，恰好是\(p\Z_p\)

    2. 设\(J\subseteq\Z_p\)是一个非平凡理想
       * 令\(k=\min\{n\in\N\mid p^n\in J\}\)，显然\(k>0\)，\(p^k\Z_p\subseteq J\)
       * 断言\(p^k\Z_p=J\)。
       * 设\(x=a_0+a_1p+\dots\in J\)，令\(a_m\)是第一个非零系数
       * 则\(x=p^m(a_m+a_{m+1}p+\dots)\)，
       * 因为\(a_m\neq 0\)，\(a_m+a_{m+1}p+\dots\)是单位，故存在\(y\in\Z_p\)使得\(xy=p^m\in J\)
       * 由定义，\(k\le m\Rightarrow p^m\in p^k\Z_p\Rightarrow x\in p^k\Z_p\)，
       * 即\(\Z_p\)的每个非平反理想都形如\(p^k\Z_p\)。
    3. 投射函数诱导了一个同态
       \begin{center}\begin{tikzcd}
       \Z^*\ar[r,"\pi_n"]&\Z/(p^n)\\
       \Z_p\ar[u]\ar[ur,"\pi_n"']
       \end{tikzcd}\end{center}
       其中 \(\pi_n:\Z_p\to\Z/(p^n)\)，\(x=(x_1,\dots,x_n,\dots)\mapsto x_n\)，于是
       \begin{align*}
       x\in\ker(\pi_n)&\Leftrightarrow x_n=0\\
       &\Leftrightarrow x=(0,\dots,0,x_{n+1},\dots)\\
       &\Leftrightarrow x=a_{n}p^n+a_{n+1}p^{n+1}\dots\\
       &\Leftrightarrow x\in p^n\Z_p
       \end{align*}

    #+END_proof

    #+BEGIN_remark
    证明\(\Z_p\)是局部环的关键是验证
    \begin{equation*}
    x=a_0+a_1p+\dots\text{是单位}\Leftrightarrow a_0\neq 0
    \end{equation*}
    #+END_remark

    以下证明更简洁：
    * 设\(x=(x_1,x_2,\dots)\in\Z_p\subseteq\prod\Z/(p^n)\)，\(x_1=a_0,\dots,x_n=a_0+a_1p+\dots+a_{n-1}p^{n-1},\dots\)
    * 由于每个\(\Z/(p^n)\)都是局部环且\(p\Z/(p^n)\)是其极大理想，
    * 故每个\(x_n\)在\(\Z/(p^n)\)中可逆，令\(y_n\)是\(x_n\)在\(\Z/(p^n)\)的逆
    * \(\pi_{mn}(x_my_m)=\pi_{mn}(x_m)\pi_{mn}(y_m)=x_n\pi_{mn}(y_m)=1\)，
    * 故\(\forall n<m\)，\(\pi_{mn}(y_m)\)都是\(x_n\)的逆
    * 断言：\(\pi_{mn}(y_m)=y_n\)
    * \(x_n(y_n-\pi_{mn}(y_m))=0\Rightarrow y_nx_n(y_n-\pi_{mn}(y_m))=0\)，
    * 故\(y=(y_1,y_2,\dots)\)是\(x\)的逆

    更加简洁的方法：
    * 取\(b\in\{0,\dots,p-1\}\)使得\(a_0\cdot b\equiv 1\mod p\)，
    * 则\(bx=1+p(b_0+b_1p+\dots)=1-py\)，
    * 令\(c=1+py+p^2y^2+\dots\in\Z_p\)，
    * 则\(bxc=(1-py)(1+py+(py)^2+\dots)=1\)

    #+BEGIN_remark
    * \(\Z\mapsto\Z_p\), \(x\mapsto x\)的\(p\)-进制展开是一个单同态。
    * \(\Z\)中不能被\(p\)整除的元素都是\(\Z_p\)的单位。
    * 令\(S=\Z-(p)\)，则\(S\)是乘法集，\(\Z\)关于\((p)\)的局部化\(\Z_{(p)}=S^{-1}\Z\subseteq\Q\)是局部环，
      且\(pS^{-1}\Z\)是极大理想
    * \(\Z_{(p)}=\{\frac{a}{b}:a,b\in\Z,b\nmid b\}\subseteq\Q\)
    * \(\Z\)到\(\Z_p\)的嵌入自然地扩张为\(\Z_{(p)}\)到\(\Z_p\)的嵌入
      \begin{center}\begin{tikzcd}
      f:\Z\to\Z_p\ar[d]\\
      \parbox{3cm}{\centering \(\tilde{f}:S^{-1}\Z\to\Z_p\) \(\frac{a}{b}\mapsto(f(b))^{-1}a\)}
      \end{tikzcd}\end{center}
    * \(\Z_p\cap\Q=\Z_{(p)}\)
    * 在形式上，\(\Z_p\)与\(\F_p[[X]]\)有相似之处，然而\(\Char(\Z_p)=0\)，而\(\Char(\F_p[[X]])=p\)
    #+END_remark
* 亨泽尔局部环
** 亨泽尔局部环（Henselian）
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(R\)局部环，\(\fm\)极大理想，\(R\)是 *亨泽尔环* 如果对每个多项式\(f(x)\in R[x]\)，\(a\in R\)，有
    \begin{equation*}
    f(a)\in\fm\wedge f'(a)\notin\fm
    \end{equation*}
    则存在\(b\in R\)使得\(f(b)=0\)且\(a\equiv b\mod\fm\)
    #+END_definition

    #+BEGIN_remark
    1. 我们可以把\(\fm\)中的元素看作\(R\)中的“无穷小量”，则\(f(a)\in\fm\)且\(f'(a)\notin\fm\)可理解为\(f(a)\)在
       “0”点附近，而\(f(x)\)在“a”处的斜率不为“0”，此时\(f(x)=0\)在\(a\)点附近可能有解
    2. 设\(k=R/\fm\)是\(R\)的剩余域，设\(f(x)=\sum_{k=1}^nc_kx^k\in R[x]\)，定义，定义\(\barf(x)\in k[x]\)为
       \(\sum_{k=1}^n\barc_kx^k\)，其中
       \begin{equation*}
       \barc_k=c_k+\fm
       \end{equation*}
       则\(f(a)\in\fm\)且\(f'(a)\notin\fm\)\(\Leftrightarrow\)\(\barf(\bara)=0\)且\(\barf'(\bara)\neq 0\)\(\Leftrightarrow\)\(\bara\)
       是\(\barf(x)\)的非奇异零点（不是重根）
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(R\)是一个局部环，\(f(x)\in R[x]\), \(a\in R\),若\(f(a)\in\fm\)且\(f'(a)\notin\fm\)，则至多有一个\(b\in R\)使
    得\(f(b)=0\)且\(a\equiv b\mod\fm\)
    #+END_lemma

    #+BEGIN_proof
    设\(b\in R\)使得\(f(b)=0\)且\(a\equiv b\mod\fm\)，则\(\bara=\barb\)，故\(\barf'(\bara)=\barf'(\barb)\neq 0\)，
    故\(f'(b)\notin\fm\)是一个单位，考虑\(f(x)\)在\(b\)点的泰勒展开
    \begin{equation*}
    f(x+b)=f(b)+f'(b)x+cx^2
    \end{equation*}
    若\(x_0\in\fm\)，则
    \begin{equation*}
    f(x_0+b)=f'(b)x_0+cx_0^2=x_0(f'(b)+cx_0)
    \end{equation*}
    因为\(f'(b)\)是单位，因此\(f'(b)+cx_0\)是单位，故\(f(x_0+b)=0\Leftrightarrow x_0=0\)
    #+END_proof
** 剩余域的提升
    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    设\(k\)是一个域，\(R=k[[x]]\)，则\(R\)是一个局部环，\(\fm=(x)\)是极大理想

    \(a\in k\mapsto\bara=a+(x)\)是\(k\)到\(R/\fm\)的同构，即\(R\)中存在一个子域\(k\)使得自然投射\(x\mapsto\barx\)
    在\(k\)上是同构

    称\(k\)是\(R\)的剩余域的提升
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    设\(R=\Z/p^2\Z\)，其中\(p\)是素数，\(\fm=p\Z/p^2\Z\)，\(R/\fm\cong\F_p\)，而\(R\)中没有子域，故\(R/\fm\)在\(R\)中
    没有提升

    若有子域，一定有1，但是1可以生成整个\(R\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    考虑局部环\(\Z_p\)，\(\fm=p\Z_p\)，\(k=\Z_p/\fm\cong\F_p\)，\(\Char\Z_p=0\Rightarrow\F_p\not\subseteq\Z_p\)，故\(\Z_p/\fm\)在\(\Z_p\)
    中没有提升
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(R\)是一个局部环，\(\fm\)和\(k\)分别为其极大理想和剩余域，若存在\(R\)的子域\(E\)使
    得\(\barE=\{\barx=x+\fm\mid x\in E\}=k\)，则称\(E\)是\(k\)的提升
    #+END_definition

    #+BEGIN_remark
    * 若\(E\)是\(k\)的提升，则\(\pi:E\to\barE\)是同构，\(x\in\ker\pi\Leftrightarrow x\in\fm\Leftrightarrow x\)不可逆即\(x=0\)
    * 故而若\(k\)有提升，则提升唯一
    #+END_remark

    #+ATTR_LATEX: :options [提升定理]
    #+BEGIN_theorem
    设\(R,\fm,k\)如上，若\(R\)是亨泽尔的，且\(\Char k=0\)，则\(k\)在\(R\)中有提升
    #+END_theorem

    #+BEGIN_proof

    #+END_proof
** 域的扩张理论
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(K,L\)是两个域，若\(K\)是\(L\)的子域，则称\(L\)是\(K\)的一个扩张，记作\(L/K\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是一个域扩张，\(X\subseteq L\)，则
    1. \(K[X]\)表示由\(K\bigcup X\)生成的\(L\)的子环，
       \begin{equation*}
       K[X]=\la K\cup X\ra_L
       \end{equation*}
    2. \(K(X)\)表示\(K[X]\)的分式域
    3. 若\(X=\{a_1,\dots,a_n\}\)有穷，则\(K[X]\)记作\(K[a_1,\dots,a_n]\)，\(K(X)\)记作\(K(a_1,\dots,a_n)\)

    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    若\(L/K\)是域扩张，\(a_1,\dots,a_n\in L\)，则
    \begin{align*}
    &K[a_1,\dots,a_n]=\{f(a_1,\dots,a_n):f\in K[X_1,\dots,X_n]\}\\
    &K(a_1,\dots,a_n)=\{\frac{f(a_1,\dots,a_n)}{g(a_1,\dots,a_n)}\mid f,g\in K[X_1,\dots,X_n],g(a_1,\dots,a_n)\neq 0\}
    \end{align*}
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是一个域扩张，\(a\in L\)，称\(a\)在\(K\)上是代数的，如果存在一个非零多项式\(f(x)\in K[X]\)
    使得\(f(a)=0\)，如果\(a\)不是代数的，则\(a\)在\(K\)上是超越的
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是域扩张，\(a\in L\)在\(K\)上代数，若\(p(x)\in K[x]\)是使得\(p(a)=0\)的次数最小的首一多项式，
    则称\(p(x)\)是\(a\)在\(K\)上的极小多项式，记作\(\min(K,a)\)
    #+END_definition

    #+BEGIN_remark
    * 显然\(I=\{f(x)\in K[X]\mid f(a)=0\}\)是\(k[x]\)的一个理想
    * 由于\(K[x]\)是主理想整环，即每个理想都形如\((g(x))\)，故\(I=(p(x))\)，\(p\in I\)且\(\deg(p)\)最
      小，若要求\(p(x)\)首项为1，则\(p(x)\)唯一
    * 显然\(p(x)\)在\(K[X]\)中不可约
    * 设\(p=x^n+\sum_{k=0}^{n-1}c_kx^k\)
    * 将\(K[a]=\{f(a)\mid f\in K[x]\}\)视作\(K\)上的向量空间
    * 由于\(p\)是使得\(p(a)=0\)的次数最小的多项式
    * 故\(1,a,a^2,\dots,a^{n-1}\)在\(K\)上线性无关
    * \(a^n\)是\(\{1,\dots,a^{n-1}\}\)的线性组合
    * \(a^{n+1}\)也类似
    * 故\(\{1,a,\dots,a^{n-1}\}\)是\(k[a]\)的一组基
    * 现在\(K[a]\)是一个环，同时是\(K\)上的\(n\)维向量空间，基为\(\{1,\dots,a^{n-1}\}\)
    * \(\forall f(x)\in K[x]\), \(f(x)\)与\(p(x)\)互素
    * 故存在\(s(x),t(x)\in K[x]\)使得\(s(x)f(x)+t(x)p(x)=1\)，故每个\(f(a)\in K[a]\)都可逆，\(K[a]\)是一
      个域
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是一个域扩张，则\(L\)是\(K\)上的向量空间，\([L:K]\)表示\(L\)作为\(K\)空间的维数，
    称\(L/K\)是一个有穷扩张如果\([L:K]<\infty\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    设\(L/K\)是一个域扩张，且\(a\in L\)，在\(K\)上代数
    1. \(\min(K,a)\)是\(K\)上的不可约多项式
    2. \(\forall g(x)\in K[x]\)，\(g(a)=0\Leftrightarrow\min(K,a)\mid g(x)\)
    3. 若\(\min(K,a)\)的次数为\(n\)，则\(\{1,\dots,a^{n-1}\}\)是\(K[a]\)在\(K\)上的一组基
    4. \(K[a]=K(a)\)是域，\([K(a):K]=n\)
    5. \(K[a]\cong K[x]/\min(K,a)\)

    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    设\(F\subseteq K\subseteq L\)是域扩张，则
    \begin{equation*}
    [L:F]=[L:K][K:F]
    \end{equation*}
    #+END_proposition

    #+BEGIN_proof
    设\(\{a_i\mid i\in I\}\)是\(K/F\)的一组基， \(\{b_j\mid j\in J\}\)是\(L/K\)的一组基

    证明\(\{a_ib_j\mid i\in I,j\in J\}\)是\(L/F\)的基
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是域扩张，若每个\(a\in L\)都在\(K\)上代数，则称\(L\)是\(K\)的代数扩张
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若\(L/K\)是有穷扩张，则\(L\)是\(K\)的代数扩张且存在\(a_1,\dots,a_n\)使得
    \begin{equation*}
    L=K(a_1,\dots,a_n)
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    对\([L:K]\)归纳

    若\(L=K\)，则证明结束

    否则，取\(a\in L\setminus K\)，则\(1<[K(a):K]\le[L:K]<\infty\)

    故存在\(n\)使得\(\{1,a,\dots,a^{n-1}\}\)线性无关，\(a\)在\(K\)上是代数，故\(L/K\)是代数扩张，
    #+END_proof

    #+BEGIN_remark
    \(L\)可以由“更少”的元素生成，取\(b_1,\dots,b_m\in L\)使得\(b_1\notin K\), \(b_2\notin K(b_1)\)，
    \(\dots\), \(b_m\notin K(b_1,\dots,b_{m-1})\)，则
    \([K[b_1]:K]\ge 2\)，故\([K(b_1,\dots,b_m):K]\ge 2^M\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    若\(L/K\)是域扩张，\(a_1,\dots,a_n\in L\)，若每个\(a_i\)都在\(K\)上代数，则
    \(E=K[a_1,\dots,a_n]\)是域且\([K[a_1,\dots,a_n]:K]\le\prod_{i=1}^n[K(a_i):K]\)
    #+END_lemma

    #+BEGIN_proof
    \(a_2\)在\(K\)上代数推出\(a_2\)在\(K[a_1]\)代数

    若\(m\)时满足，令\(E=K[a_1,\dots,a_m]\)，则
    \begin{equation*}
    [E[a_{m+1}]:K]=[E[a_{m+1}]:E][E:K]\le\prod_{i1}^m[K[a_i]:K][E[a_{m+1}]:E]
    \end{equation*}
    令\(p(x)\)为\(\min(E,a_{m+1})\),\(q(x)\)为\(\min(K,a_{m+1})\)，当然\(\deg(p)\le\deg(q)\)

    于是\([E[a_{m+1}]:E]\le[K[a_{m+1}]:K]\)

    从而\([E[a_{m+1}]:K]\le\prod_{i=1}^{m+1}[K[a_i]:K]\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    * 设\(L/K\)是域扩张，\(a\in L\)，则\(a\)在\(K\)上代数当且仅当\([K(a):K]<\infty\)
    * \(L\)在\(K\)上代数当且仅当对每个有穷的\(X\subseteq L\)，都有\([K(X):X]<\infty\)
    * \(X\subseteq L\)使得每个\(a\in X\)都在\(K\)上代数，则\(K(X)/K\)是代数扩张
    #+END_corollary

    #+BEGIN_remark
    设\(a\in L\)在\(K\)上超越，则映射\(\ev_a:F[X]\to F[a]\)是同构
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    设\(F\subseteq K\subseteq L\)是域扩张，若\(K/F\)和\(L/K\)均是代数扩张，则\(L/F\)也是代数扩张
    #+END_proposition

    #+BEGIN_proof
    设\(a\in L\)，令\(f(x)=k_0+\dots+x^n\)是\(a\)在\(K\)的极小多项式，显然\(f(x)\in F[k_0,\dots,k_n]\)，故\(a\)
    在\(F[k_0,\dots,k_n]\)上代数，从而\([F[k_0,\dots,k_n][a]:F[k_0,\dots,k_n]]<\infty\)，故
    \([F[k_0,\dots,k_n,a]:F]<\infty\)，故\(F[k_0,\dots,k_n,a]/F\)是代数扩张，故\(a\)在\(F\)上代数。
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(L/K\)是一个域扩张，则称\(\{a\in L\mid a\text{在}K\text{上是代数的}\}\)为\(K\)在\(L\)中的 *代数闭包*
    ，若该闭包是\(K\)子自己，则称\(K\)在\(L\)中代数闭
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    设\(L/K\)是一个域扩张，令\(E\)为\(K\)在\(L\)中的代数闭包，则\(E\)是一个域，从而是\(K\)在\(L\)中
    最大的代数扩张
    #+END_corollary

    #+BEGIN_proof
    只需验证\(E\)中的元素关于加法乘法封闭

    设\(a,b\in E\)，则\([K[a]:K],[K[b]:K]<\infty\)，故\([K[a,b]:K]<\infty\)，
    \([K[a,b],K]\le[K[a]:K][K[b]:K]<\infty\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    设\(K\)是一个域，\(K\)是 *代数闭域* ，如果\(K\)的任何真扩张都不是代数扩张

    \(E\supseteq K\)是\(K\)的 *代数闭包* 如果\(E\)是代数闭的，且\(E\)的包含\(K\)的真子域都不是代数闭的
    #+END_definition

    #+BEGIN_remark
    1. \(K\)是代数闭域\(\Leftrightarrow\)任何非常数\(f(x)\in K[x]\)在\(K\)中有根\(\Leftrightarrow\)只有\(\deg\le 1\)的\(f(x)\in K[x]\)
       不可约
    2. 若\(L\)是代数闭的且\(K\subseteq L\)，则\(E=\{a\in L\mid a\text{在$K$上代数}\}\)是\(K\)的代数闭包
    #+END_remark

    下面给出代数闭包的构造

    设\(K\)是一个域且\(\lambda=\abs{K}+\omega\)，令\(\{f_i(x)\mid i<\lambda\}\)是\(K[x]\)的一个枚举（选择公理），令\(K_0=K\)

    若\(f_0(x)\)在\(K_0\)上可约，则\(K_1=K_0\)

    若不可约，则\(K_1=K_0[x]/(f_0(x))\)，于是\(f_0(x)\)在\(K_1\)中有根（\(x+(f_0(x))\)）

    一般地，若\(\{K_i\mid i<\alpha\}\)已构造，若\(\alpha=\beta+1\)，则\(K_\alpha=K_\beta\)或\(K_\alpha=K_\beta[x]/(f_\beta(x))\)

    若\(\alpha\)是极限序数，则\(K_\alpha=\bigcup_{\beta<\alpha}K_\beta\)

    于是每个\(K_{i+1}/K_i\)是代数扩张，每个\(f_i(x)\in K[X]\)在\(K_{i+1}\)中可约

    令\(E=\bigcup_{\alpha<\lambda}K_\alpha\)，断言\(E/K\)是代数的

    设\(a\in E\)，则\(\exists\alpha<\lambda\)使得\(a\in K_\alpha\)

    令\(\beta_0=\min\{\beta<\alpha\mid\alpha\text{在$K_\beta$上代数}\}\)，

    则存在\(c_0,\dots,c_{n-1}\in K_{\beta_0}\)使得\(\sum c_ia^i=0\)，

    若\(\beta_0\neq 0\)，则\(\exists\alpha_0<\beta_0\)使得\(c_0,\dots,c_{n-1}\)在\(K_{\alpha_0}\)上代数，从而\(a\)
    在\(K_{\alpha_0}[c_0,\dots,c_{n-1}]\)上代数，由传递性（index），\(a\)在\(K_{\alpha_0}\)上代数，与\(\beta_0\)的极小性矛盾，
    故\(\beta_0=0\)

    同理\(E\)是代数闭的，因为每个代数扩张对应一个极小多项式，但是在构造过程中多项式已经被用完了

    \(E\)是\(K\)的代数闭包

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    任何域\(K\)都有代数闭包，且其代数闭包相互同构，记作\(K^{\alg}\)
    #+END_proposition

    若\(E'\)是\(K\)的代数闭包，考虑\(E\to E'\)的部分同构，back-and-forth一步一步抓每个元素，极大同构就
    是真的同构
** 提升定理
    设\(R\)是亨泽尔局部环，\(\fm\subseteq R\)是极大理想，\(k=R/\fm\)是剩余域，若\(\Char k=0\)，则\(k\)可以被提升，
    即存在子域\(E\subseteq R\)使得
    \begin{equation*}
    k=\barE=\{a+\fm\mid a\in E\}
    \end{equation*}

    #+BEGIN_proof
    令\(n_R=\underbrace{1_R+\dots+1_R}_{n}\)，令\(n_k\)表示\(\underbrace{1_k+\dots+1_k}_{n}\)，
    则\(n_k=\barn_R=n_R+\fm\)，由于\(\Char k=0\)，故\(n_k\neq 0\)，从而\(n_R\notin\fm\)，故\(R\)的特征为0

    不妨假设\(\Z\subseteq R\)，\(\forall n\in\Z\)，\(n\notin\fm\)，由于\(R\)是局部环每个\(n\neq 0\)均可逆，故
    \(\Q\subseteq R\)

    令\(\calf=\{E\mid E\text{是}R\text{的子域}\}\)

    注意到每个\(E\in\calf\)中的非零元素都可逆，故而\(E\)到\(k\)都是单同态，\(\ker(\pi)\subseteq\fm\)，令\(E^*\)是\(\calf\)
    在\(\subseteq\)下的极大元，证明\(E^*\)就是\(k\)的提升

    *断言1*:\(E^*\)在\(R\)中代数闭

    否则，\(a\in R\setminus E^*\)在\(E^*\)上代数，则\(E^*[a]\)是\(E^*\)的真域扩张

    下面证明\(\barE^*=\{a+\fm\mid a\in E^*\}\)是\(k=R/\fm\)

    否则，设\(\barb=b+\fm\in k\setminus\barE^*\)，则
    \(\barb\)在\(\barE^*\)上代数或超越

    若\(\barb\)在\(\barE^*\)上代数，则存在\(f(x)\)使得\(\barf(x)\)是\(\barb\)在\(\barE^*\)上的极小多
    项式，即\(\barf(\barb)=0\)且\(\barf'(\barb)\neq 0\)，即\(f(b)\in\fm\)且\(f'(b)\notin\fm\)，由亨泽尔性，存
    在\(\epsilon\in\fm\)使得\(f(b+\epsilon)=0\)，即\(b+\epsilon\)在\(E^*\)上代数，而\(\ove{b+\epsilon}=\barb\notin\barE^*\)，于
    是\(\barE^*\)不是代数闭，矛盾

    若\(\barb\in k\setminus\barE^*\)是超越的，于是\(\forall f(x)\in E^*[X]\),\(f(b)\notin\fm\)，即\(E^*[b]\)中每个非零元都不
    属于\(\fm\)，从而可
    逆，故\(E^*(b)\)是\(R\)的一个子域，是\(E^*\)的真扩张，矛盾

    故\(\barE^*=k=R/\fm\)
    #+END_proof
* 超积与Ax-Kochen原理
** 环的一阶语言
    考虑环的一阶语言\(\call_{ring}=\{+,\times,0,1\}\)
** Łoś超积定理
** 局部Ax-Kochen原理
    观察：\(\Z_p=\{\sum_{n=0}^\infty a_np^n\mid a_n\in\{0,\dots,p-1\}\}\)与
    \(\F_p[[t]]=\{\sum_{n=0}^\infty a_nt^n\mid a_n\in\{0,\dots,p-1\}\}\)的相似之处：
    1. \(\Z_p/(p)=\F_p=\F_p[[t]]/(t)\)
    2. （局部）\(\Z_p\)是\(\{\Z/(p^n)\mid n\in\N^+\}\)的逆向极限
    3. （局部）\(\F_p[[t]]\)是\(\{\F_p[t]/(t^n)\mid n\in\N^+\}\)的逆向极限
    4. \(\Z\)在\(\Z_p\)稠密，\(\F_p[t]\)在\(\F_p[[t]]\)中稠密
    差异：
    1. \(\Char\Z_p=0\)，\(\Char(\F_p[[t]])=p\)
    2. \(\Char(\Z/p^n)=p^n\),\(\Char(\F_p[t]/(t^n))=p\)


    #+ATTR_LATEX: :options [局部Ax-Kochen同构定理]
    #+BEGIN_theorem
    令\(\calu\)是素数集上的一个非主超滤，则对每个\(n\in\N^+\)，有
    \begin{equation*}
    \prod_{\calu}(\Z/(p^n))\cong\prod_{\calu}(\F_p[t]/(t^n))
    \end{equation*}
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(\{A_i\mid i\in I\}\)是一组亨泽尔局部环，\(A_i\)的极大理想为\(\fm_i\)，剩余域为\(k_i\)，令\(\calu\)是\(I\)上的
    一个超滤，则
    1. \(\prod_{\calu}A_i\)是一个亨泽尔局部环
    2. \(\prod_{\calu}\fm_i=\{[(a_i)_{i\in I}]\mid a_i\in\fm_i\}\)是极大理想
    3. \(\prod_{\calu}k_i\)同构于\(\prod_{\calu}A_i/\prod_{\calu}\fm_i\)
    #+END_lemma

    #+BEGIN_proof
    1. 亨泽尔局部环是一阶句子
    2. 设\([a]\in\prod_{\calu}A_i\)，则
       \begin{align*}
       [a]\text{是单位}&\Leftrightarrow\exists[b],[a][b]=[1]\\
       &\Leftrightarrow\{i\in I\mid a_ib_i=1_i\}\in\calu\\
       &\Leftrightarrow\{i\in I\mid a_i\text{是单位}\}\in\calu\\
       &\Rightarrow[a]\notin\prod_{\calu}\fm_i
       \end{align*}
       若\([a]\notin\prod_{\calu}\fm_i\)，则显然\(\{i\in I\mid a_i\notin\fm_i\}\in\calu\)，故
       \(\pi(\prod_{i\in I}\fm_i)=\prod_{\calu}\fm_i\)是其极大理想
    3. 设\(k_i=A_i/\fm_i\)，令\(R_i:A_i\to k_i\)为自然投射，令\(\prod_{\calu}R_i:\prod_{\calu}A_i\to\prod_{\calu}(A_i/\fm_i)\)，
       \([(a_i)_{i\in I}]\mapsto[(R_i(a_i))_{i\in I}]\)，则\(\prod_{\calu}R_i\)是良定义的满同态，且\(\ker(\prod_{\calu}R_i)=\prod_{\calu}\fm_i\)

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:12
    若\(f(x)\in \Z[x]\)，\(n>0\)，\(a\in\Z\)使得\(f(a)\equiv 0\mod p^n\)，\(f'(a)\not\equiv 0\mod p\)，则存在
    \(b\in\Z\)使得\(a\equiv b\mod p^n\)且\(f(b)\equiv 0\mod p^{n+1}\)
    #+END_lemma

    #+BEGIN_proof
    对\(n\)归纳证明：
    1. 若\(n=1\)，考虑同态\(\pi:\Z\to\Z/(p^2)\)，\(f'(a)\not\equiv 0\mod p\)，于是\(\pi(f'(a))\)是\(\Z/(p^2)\)的单位，
       令\(c\in\Z/(p^2)\)是\(\pi(f'(a))\)的逆

       任取\(\tilc\in\Z\)为\(c\)的提升，令\(\epsilon_1=-\tilc f(a)\)，令\(b=a+\epsilon_1\)，则

       \(f(a)\equiv 0\mod p\Rightarrow\epsilon_1\equiv 0\mod p\Rightarrow a\equiv b\mod p\)

       \(f(b)=f(a+\epsilon_1)=f(a)+f'(a)\epsilon_1+\epsilon_1^2r\)，\(\pi(f(b))=\pi(f(a))+\pi(f'(a)\epsilon_1)+\pi(\epsilon_1^2r)=\pi(\epsilon_1^2r)\)

       \(\epsilon_1\equiv 0\mod p\)，因此\(\epsilon_1^2\equiv 0\mod p^2\)
    2. \(f(a)\equiv 0\mod p^n\)，\(f'(a)\not\equiv 0\mod p\)，令\(\pi_{n+1}:\Z\to\Z/(p^{n+1})\)，令\(c\in\Z/(p^{n+1})\)
       为\(\pi_{n+1}(f'(a))\)的逆，令\(\tilc\)为\(c\)在\(\Z\)的一个提升，令\(\epsilon_n=-\tilc\cdot f(a)\)，
       则\(\epsilon_n\equiv 0\mod p^n\)，令\(b=a+\epsilon_n\)，则\(a\equiv b\mod p^n\)，且
       \(f(a+\epsilon_n)=f(a)+f'(a)\epsilon_n+\epsilon_n^2\cdot r\)，
       \begin{align*}
       \pi_{n+1}(f(b))&=\pi_{n+1}(f(a))+\pi_{n+1}(f'(a))\pi_{n+1}(\epsilon_n)+0\\
       &=0
       \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    设\(f(x)\in\Z[x]\), \(a\in\Z\)使得\(f(a)\equiv 0\mod p\), \(f'(a)\not\equiv 0\mod p\)，则对任意\(n>0\)，存在整数
    序列\(b_1=a,b_2,\dots,b_n\)使得\(b_k\equiv b_{k+1}\mod p^k\)且\(f(b_k)\equiv 0\mod p^k\)
    #+END_corollary

    #+BEGIN_proof

    #+END_proof

    若要求\(b_k<p^k\)，则序列唯一

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    对每个\(n>0\)，\(\Z/(p^n)\)都是亨泽尔局部环
    #+END_corollary

    #+BEGIN_proof
    已知\(\Z/(p^n)\)是局部环，下面证明\(\Z/(p^n)\)的亨泽尔性。

    同态\(\pi_n:\Z\to\Z/(p^n)\)可以自然扩张为
    \begin{equation*}
    \Z[x]\to\Z/(p^n)[x]
    \end{equation*}
    记作\(\pi_n\)，用\(\tilf\)表示\(f(x)\in\Z/(p^n)[x]\)在\(\Z[x]\)中的提升，用\(\tila\)表示\(a\in\Z/(p^n)\)
    在\(\Z\)的一个提升，显然对任意\(f(x)\in\Z/(p^n)[x]\)以及\(a\in\Z/(p^n)\)有
    1. \(f(a)\in\fm\Leftrightarrow\tilf(\tila)\equiv\mod p\)
    2. \(f'(a)\notin\fm\Leftrightarrow\tilf'(\tila)\not\equiv 0\mod p\)
    设\(f,a\)满足条件1，2，则由引理 ref:12 存在\(\b^*\in\Z\)使得


    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    若\(R\)是一个局部环，如果存在\(t\in R\)使得\(\fm=tR\)是极大理想，则存在\(n>0\)使得\(t^n=0\)，则\(R\)
    是一个亨泽尔环
    #+END_theorem

    #+BEGIN_remark
    设\(R\)是局部环，\(\fm\)是极大理想，\(t\in R\)使得\(\fm=(t)\)，\(t^{n-1}\neq 0\)，\(t^n=0\)，则
    \begin{equation*}
    R=(t^0)\supsetneq(t)\supsetneq\dots\supsetneq(t^n)\supsetneq(t^{n+1}=\emptyset)
    \end{equation*}
    是一个严格降链

    对每个\(r\in R\)，存在\(m\le n\)使得
    \begin{equation*}
    r\in(t^m)\setminus(t^{m+1})
    \end{equation*}
    定义\(r\)的 *范数* \(\abs{r}\)为
    \begin{align*}
    &r\neq 0\Rightarrow\abs{r}=2^{-m}\\
    &r=0\Rightarrow\abs{r}=0
    \end{align*}

    则\((R,\abs{})\)是一个完备的（超度量）空间
    1. \(r=0\Leftrightarrow\abs{r}=0\)，\(\abs{1}=1\)
    2. \(\abs{r_1+r_2}\le\max\{\abs{r_1},\abs{r_2}\}\)
    3. \(\abs{r_1r_2}\le\abs{r_1}\abs{r_2}\)


    这种范数称为 *超范数* ，对应的度量称为 *超度量* 。
    #+END_remark

    \(\Z/(p^n)\)和\(k[t]/t^n\)都是完备的超度量空间

    #+BEGIN_remark
    若\(R\)是一个局部整环，\(t\in R\)使得\(\fm=(t)\)且\((t^n)\neq 0\)
    \begin{equation*}
    \bigcap_{n=0}^\infty(t^n)=\{0\}
    \end{equation*}
    则\((t^0)\supsetneq\dots\supsetneq(t^n)\supsetneq\dots\)是一个严格降链，设\(r\in R\)，定义
    \begin{equation*}
    \abs{r}=
    \begin{cases}
    2^{-m}&r\in(t^m)\setminus(t^{m-1})\\
    0^r=0
    \end{cases}
    \end{equation*}
    则\((R,\abs{})\)是一个超度量空间
    1.
    2.
    3. \(\abs{r_1r_2}=\abs{r_1}\abs{r_2}\)

    但\(R\)不一定完备
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    设\(R\)是一个亨泽尔局部环，\(\fm\)是极大理想，\(k\)是剩余域，若\(t\in R\)使得\(\fm=(t)\)且
    \begin{equation*}
    \Char(k)=0,t^{n-1}\neq 0,t^n=0
    \end{equation*}
    则\(R\cong k[X]/(x^n)\)
    #+END_lemma

    #+BEGIN_proof
    由提升定理，\(k\)在\(R\)中有提升\(E\)，则\(R\)是\(E\)上的向量空间。

    *断言1* ：\(\{1,t,\dots,t^{n-1}\}\)是\(R\)在\(E\)上的一组基。

    1. 线性无关：设\(e_0+\dots+e_{n-1}t^{n-1}=0\)，若\(e_0,\dots,e_{n-1}\in E\)不全为0，令\(i=\min\{k\mid e_k\neq 0\}\)，
       则\(e^it^i=-(e_{i+1}t^{i+1}+\dots+e_{n-1}t^{n-1})\)，两边乘\(t^{n-i-1}\)，
       则\(e_it^{n-1}=0\Rightarrow t^{n-1}=0\)，矛盾
    2. 设\(r\in R\)，我们找出

       断言2：若\(s\in(t^k)\)，则存在\(e\in E\)使得
       \begin{equation*}
       s-et^k\in(t^{k+1})
       \end{equation*}

       若\(s\in(t^{k+1})\)，则\(e=0\)；若\(s\notin(t^{k+1})\)，则\(s=at^k\)，\(a\notin(t)\)，由于\(E/\fm=R/\fm\)，故
       存在\(e\in E\)使得\(e/\fm=a/\fm\)，故\(et^k-s=et^k-at^k=(e-a)t^k\in(t^{k+1})\)

       由以上断言，可递归构造\(e_0,e_1,\dots,e_{n-1}\)如下

       * 取\(e_0\in E\)使得\(r-e_0\in(t)\)
       * 取\(e_1\in E\)使得\(r-e_0-e_1t\in(t^2)\)
       * 取\(e_{n-1}\in E\)使得\(r-e_0-\dots-e_{n-1}t\in(t^n)=\{0\}\)
       即\(r=e_0+e_1+\dots+e_{n-1}t^{n-1}\)

    定义\(\pi:E[X]\to R\)，\(f(x)\mapsto f(t)\)。

    则断言1保证\(\pi\)是满同态且\(\ker(\pi)=(x^n)\)，即
    \begin{equation*}
    R\cong E[X]/(x^n)\cong k[X]/(x^n)
    \end{equation*}

    #+END_proof

    若\(k\subseteq R\), \(a_1,\dots,a_n\in R\), \(R=k[a_1,\dots,a_n]\)，则\(\)

    #+ATTR_LATEX: :options [局部Ax-Kochen同构定理]
    #+BEGIN_theorem
    令\(\calu\)是素数集上的一个非主超滤，则对每个\(n\in\N^+\)，有
    \begin{equation*}
    \prod_{\calu}(\Z/(p^n))\cong\prod_{\calu}(\F_p[t]/(t^n))
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    令\(\calu\)是素数集\(\calp\)上的一个非主超滤，则\(\prod_{\calu}\F_p\)是\(\prod_{\calu}\Z/(p^n)\)与\(\prod_{\calu}\F_p[t_p]/(t_p^n)\)的剩余
    域

    对每个\(n>0\)，\(p>n\)能推出\(\F_p\vDash n\neq 0\)，故
    \(\{p\in\calp\mid\F_p\vDash n\neq 0\}\)是\(\calp\)的余有穷集，故\(\forall n>0\)，有\(\prod_{\calu}\F_p\vDash n\neq 0\)，
    故
    1. \(\Char\prod_{\calu}\F_p=0\)
    2. 同理\(a=[(p)_{p\in\calp}]\)满足
       \(a\)是\(\prod_{\calu}\Z/(p^n)\)的极大理想，且\(a^{n-1}\neq 0\)，\(a^n=0\)
    3.
    #+END_proof

    #+ATTR_LATEX: :options [局部Ax-Kochen转移原理]
    #+BEGIN_theorem
    给定\(n>0\)以及一个\(\call_{ring}\)-句子\(\sigma\)存在有限的素数集\(E_\sigma\)使得对每个\(p\notin E_\sigma\)有
    \begin{equation*}
    \Z/p^n\vDash\sigma\Leftrightarrow(\F_p[t]/t^n)\vDash\sigma
    \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    否则，
    \begin{equation*}
    X_\sigma=\{p\in\calp\mid\Z/p^n\vDash\sigma\Leftrightarrow(\F_p[t]/t^n)\vDash\sigma\}
    \end{equation*}
    的补集\(Y_\sigma=\calp\setminus X_\sigma\)是无穷集。

    则存在非主超滤\(\calu\)使得\(Y_\sigma\in\calu\)

    令\(Z_\sigma=\{p\in\calp\mid\Z/p^n\vDash\sigma\}\),\(F_\sigma=\{p\in\calp\mid\F_p[t]/t^n\vDash\sigma\}\)，则
    \(Z_\sigma\cap F_\sigma\cap Y_\sigma=\emptyset\)，故\(Z_\sigma\in\calu\Rightarrow F_\sigma\notin\calu\)，

    若\(\prod_{\calu}\Z/\)
    #+END_proof
