#+title: Valued field
#+AUTHOR: Jinhe Ye
#+EXPORT_FILE_NAME: ../latex/ValuedField/ValuedField.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{/Users/wu/notes/preamble.tex}
#+LATEX_HEADER: \makeindex
#+LATEX_HEADER: \DeclareMathOperator{\ch}{ch}


* Course 1
    Goal: cover some major results in the study of model theory of valued field
    1. Robinson's model completeness of algebraically closed valued fields
    2. AKE-theorem (transfer principle)
    3. Model theory of \(p\)-adic, denef's results on rationality of Poincare series


    Conventions:
    All rings are commutaive with 1

    \(U(A)\)= units in \(A\)

    \(A^\times=A\setminus\{0\}\)

    \(a\in A\), \(a A\) the ideal generated by \(a\)

    \(S\subseteq A\), \(SA\) ideal generated by \(S\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(A\) ring, a *norm* on \(A\), \(\abs{\cdot}:A\to\R_{\ge 0}\) satisfying
    1. \(\abs{x}=0\Leftrightarrow x=0\)
    2. \(\abs{x+y}\le\abs{x}+\abs{y}\)
    3. \(\abs{x\cdot y}\le\abs{x}\cdot\abs{y}\)
    #+END_definition

    \(\abs{1}=1\), \(\abs{x}=\abs{-x}\)

    \(d(x,y)=\abs{x-y}\), \(d\) is a metric

    \((A,\abs{\cdot})\) is *complete* if \(A\) is complete w.r.t. \(d\) given above (all cauchy sequence
    converges)

    If we replace 2 with
    \begin{equation*}
    \abs{x+y}\le\max\{\abs{x},\abs{y}\}
    \end{equation*}
    then \(\abs{\cdot}\) is *ultrametric*, or *non-archimedean*

    \(\Z\hookrightarrow A\) is bounded

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \((A,\abs{\cdot})\) complete. \(\abs{\cdot}\) non-archimedean, \((a_n)_{n\in\N}\) in \(A\),
    \begin{equation*}
    \lim_{n\infty}\sum_{i=0}^na_i\text{ converges iff }\lim_{n\to\infty}(a_n)=0
    \end{equation*}
    #+END_lemma

    #+BEGIN_proof
    \(\Rightarrow\): as usual

    \(\Leftarrow\): \(\abs{\sum_{i=n}^ma_i}\le\max\{\abs{a_n},\dots,\abs{a_m}\}\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(A\) domain, \(R=A[[T]]\),

    order \(\ord(f)=\min\{i:a_i\neq 0\}\), \(\ord(0)=\infty\)

    \(\ord(f\cdot g)=\ord(f)+\ord(g)\)

    \(\ord(f+g)\ge\min\{\ord(f),\ord(g)\}\)

    define \(\abs{f}=2^{-\ord(f)}\), then \(\abs{\cdot}\) is a non-archimedean norm
    #+END_examplle

    #+BEGIN_exercise
    \((R,\abs{\cdot})\) is complete, moreover, \(A[T]\subseteq R\) is dense
    #+END_exercise

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.5
    \((A,\abs{\cdot})\) complete, \(x\in A\), \(\abs{x}<1\), \(1-x\) is a unit, \((\sum_{i=0}^\infty x^i)(1-x)=1\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.6
    \((A,\abs{\cdot})\) complete, \(\forall a\in A\), \(\abs{a}\le 1\), \(I=\{x\in A:\abs{x}<1\}\). Then \(I\) is an
    ideal of \(A\), \(\barA=A/I\),
    #+BEGIN_center
    \(a\in A\) is a unit \(\Leftrightarrow\) \(\bara\in\barA\) is a unit
    #+END_center
    #+END_lemma

    #+BEGIN_proof
    \(\Leftarrow\):\(\bara\cdot\barb=1\), \(ab=1-c\) for some \(c\in I\), \(\abs{c}<1\), \(1-c\) is a unit
    #+END_proof

    #+ATTR_LATEX: :options [Hensel's lemma]
    #+BEGIN_lemma
    \((A,\abs{\cdot})\) complete, \(\forall a\in A\), \(\abs{a}\le 1\), \(f\in A[x]\), assume \(\exists\alpha\in A\)
    s.t. \(\abs{f(\alpha)}<1\), \(f'(\alpha)\in U(A)\), then there is \(a\in A\)
    s.t. \(f(a)=0\), \(\bara=\baralpha\) in \(\barA\). Moreover, \(a\) is unique in \(a+I\)
    #+END_lemma

    #+BEGIN_proof
    Newton's method

    \(a\) is a limit of a sequence \((a_n)_{n\in\N}\)

    \(a_0=\alpha\), \(\epsilon=\abs{f(\alpha)}<1\), \(\abs{f(a_n)}<\epsilon^{2^n}\), \(\bara_n=\bar\alpha\)

    \(\ove{f'(a_n)}=\ove{f'(\alpha)}\), Lemma ref:1.6 says \(f'(a_n)\) is a unit in \(A\),
    set \(a_{n+1}=a_n-f'(a_n)^{-1}f(a_n)\), \(h=-f'(a_n)^{-1}f(a_n)\)

    \(f(a_{n+1})=f(a_n+h)=f(a_n)+f'(a_n)h+g(a_n)h^2\) for some \(g\in A[x]\)
    \(=0+h^2g(a_n)=0+\) some multiple of \((f(a_n))^2\)

    \(\abs{f(a_{n+1})}\le\abs{f(a_n)}^2=(\epsilon^{2^n})^2=\epsilon^{2^{n+1}}\)

    \(\abs{a_{n+1}-\alpha}\le\max\{\abs{a_{n+1}-a_n},\abs{a_n-\alpha}\}<1\)

    \(\abs{a_{n+1}-a_n}=\abs{h}\le\epsilon^{2^n}\)

    \((a_n)_{n\in\N}\) is a cauchy  sequence

    \(f(a+x)\) expands around \(a\)
    \begin{align*}
    f(a+x)&=f(a)+f(a)'x+b\cdot x^2, b\in A\\
    &=f'(a)x+bx^2=f'(a)x(1+bf'(a)^{-1}x)\\
    &=cx, c\text{ is a unit}
    \end{align*}
    \(cx=0\Rightarrow x=0\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A ring \(A\) is *local* if it has a unique maximal ideal\(\Leftrightarrow\) all non-units of \(A\) forms an ideal
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:1.8
    \((A,\fm)\) local, \(f\in A[x]\), \(\alpha\in A\), \(f(\alpha)\in\fm\), \(f'(\alpha)\notin\fm\), then there is at most
    one \(a\in R\) s.t. \(f(a)=0\) and \(a\equiv\alpha\mod\fm\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((A,\fm)\) local, \(A\) is *henselian* if \(\forall f\in A[x]\), \(\alpha\in A\), \(f(\alpha)\in\fm\), \(f'(\alpha)\notin\fm\), then
    \(\exists a\in A\), \(f(a)=0\) and \(a\equiv\alpha\mod\fm\)
    #+END_definition

    Henselian local rings form an elementary class in \(\call_{ring}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:10
    \((A,\fm)\) local, TFAE
    1. \(A\) is henselian
    2. each \(1+X+cd_2X^2+\dots+cd_nX^n\), \(n\ge 2\), \(c\in\fm\), \(d_i\in A\), has a root in \(U(A)\)
    3. for each \(Y^n+Y^{n-1}+cd_2Y^{n-2}+\dots+cd_n\), \(c\in\fm\), \(d_i\in A\) has a root in \(U(A)\)
    4. for \(f(X)\in A[X]\), \(\alpha\in A\), \(c\in\fm\), \(f(\alpha)=cf'(\alpha)^2\), then there is \(a\in A\), \(f(a)=0\),
       \(a\equiv\alpha\mod c\cdot f'(\alpha)\)
    #+END_lemma

    #+BEGIN_proof
    \(1\Rightarrow 2\): \(f(X)=1+X+cd_2X^2+\dots+cd_nX^n\), \(f(-1)\in\fm\), \(f'(-1)\) is a unit

    Apply (1), \(f\) has a root \(a\) and \(a\equiv-1\mod\fm\), therefore \(a\) is a unit

    \(2\Leftrightarrow 3\) \(X=1/Y\)

    \(4\Rightarrow 1\) trivial

    \(2\Rightarrow 4\): \(f,\alpha,c\) is as given in (4), \(f(\alpha)=cf'(\alpha)^2\),

    \begin{align*}
    f(\alpha+x)&=f(\alpha)+f'(\alpha)x+\sum_{i=2}^nb_ix^i, b_i\in A\\
    &=cf'(\alpha)^2+f'(\alpha)x+\sum b_ix^i
    \end{align*}
    let \(x=cf'(\alpha)y\), then
    \begin{align*}
    f(\alpha+cf'(\alpha)y)&=cf'(\alpha)^2(1+y+\sum_{i\ge 2}c_iy^i)
    \end{align*}
    (2) says \(1+y+\sum_{i\ge 2}c_iy^i\) has a root \(h\) in units, then \(a=\alpha+cf'(\alpha)h\) is a root of \(f\)
    #+END_proof


    \(\ord:A\to\R_{\ge 0}\cup\{\infty\}\), \(\ord(a)=\max\{i:a\in\fm^i\}\), \(\ord(0)=\infty\)

    \(\abs{a}=e^{-\ord(a)}\)

    For a local ring \((A,\fm)\), we say \(A\) is *complete* if \(\bigcap_{i\in\N}\fm^i=\{0\}\) and \(A\) is complete
    w.r.t. \(\abs{\cdot}=e^{-\ord(\cdot)}\)

    \(A\) is complete \(\Rightarrow\) \((A,\abs{\cdot})\) is complete

    Hensel's lemma: complete local rings are henselian

    Algebraically, the completion of \(A\) is \(\varprojlim A/\fm^n\), \(\bigcap_{i\in\N}\fm^i=\{0\}\) ensures the
    map \(A\to\varprojlim A/\fm^n\)
    is injectives

    complete \(\Rightarrow\) \(A\cong\varprojlim A/\fm^n\)

    \((A,\abs{\cdot})\) normed ring, \(\hatA\), complete metric space, \(+,\cdot,-\) extends to \(\hatA\),
    \((\hatA,\abs{\cdot})\) is a ring, \((A,\abs{\cdot})\) is a dense subring

    if \(\abs{x\cdot y}=\abs{x}\abs{y}\), we call \(\abs{\cdot}\) an *absolute value*, \(A\) is a
    domain, \(\abs{1}=\abs{-1}\)

    If \((A,\abs{\cdot})\) is an absolute value, \(\abs{\cdot}\) extends uniquely
    to \(k=\Frac(A)\), \(\abs{\frac{a}{b}}=\frac{\abs{a}}{\abs{b}}\). \(\hatk\) completion
    of \(k\), \(\hatA\) is the closure of \(A\) in \(\hatk\)

    #+ATTR_LATEX: :options [\(p\)-adics]
    #+BEGIN_examplle
    \(p\) prime number
    \(V_p:\Z\to\N\cup\{\infty\}\)
    1. \(V_p(0)=\infty\)
    2. \(V_p(a)=m\) if \(a=p^mb\), \(p\nmid b\), \(b\in\Z\)


    (\(p\)-adic valuation)

    1. \(V_p(1)=0\), \(V_p(0)=\infty\)
    2. \(V_p(ab)=V_p(a)+V_p(b)\)
    3. \(V_p(a+b)\ge\min(V_p(a),V_p(b))\)


    \(V_p\) gives a norm/abs value via \(\abs{\cdot}_p=p^{-V_p(\cdot)}\)

    The more divisible by \(p\) \(a\) is, the closer  \(a\) is to 0

    \((\Q_p,\abs{\cdot}_p)\) the completion of \(\Q\) w.r.t. \(\abs{\cdot}_p\), \(p\)-adic numbers

    \(\Z_p\) is the closure of \(\Z\) in \(\Q_p\) or the completion of \((\Z,\abs{\cdot}_p)\)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For any \((a_n)_{n\in\N}\) sequence in \(\Z\), \(a=\lim_{n\to\infty}\sum_{i=0}^\infty a_ip^i\) exists
    in \(\Z_p\), \(p\mid a_0\Leftrightarrow a\in p\Z_p\Leftrightarrow\abs{a}_p<1\Leftrightarrow a\notin U(\Z_p)\).
    Moreover
    1. \((a_i)_{i\in\N}\mapsto\sum_{i=0}^\infty a_ip^i\), \(\{0,1,\dots,p-1\}^{\N}\to\Z_p\) is a bijection
    2. \(\Z_p\) is a henselian local ring
    3. \(\forall k\ge 1\), \(\Z\to\Z_p/p^k\Z_p\) is a surjection with kernel \(p^k\Z\)
    4. \(x\in\Q_p^\times\Rightarrow x=p^ku\), \(k\in\Z\), \(u\) is a unit in \(\Z_p\), that is, for
       any \(x\in\Q_p^\times\), \(x=\sum_{i=k}^\infty a_ip^i\), \(k\in\Z\)
    5. \(\Z_p=\{x\in\Q_p\mid\abs{x}_p\le 1\}=\{x\in\Q_p\mid\abs{x}_p<p\}\)
    6. \(\Z_p\) is clopen in \(\Q_p\). Moreover, \(\Z_p\) is compact
    #+END_proposition

    #+BEGIN_exercise
    if \(p\neq 2\), then \(x\in\Z_p\Leftrightarrow x\in\Q_p\) and \(1+px^2=y^2\) for some \(y\in\Q_p\)

    if \(p=2\), \(x\in\Z_2\Leftrightarrow x\in\Q_2\) and \(1+8x^2=y^2\) for some \(y\in\Q_2\)
    #+END_exercise

    we say two absolute value \(\abs{\cdot}_1,\abs{\cdot}_2\) (on \(A\)) are equivalent if they generate the
    same topology

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Up to equivalence, the only abs values on \(\Q\) are \(\abs{\cdot}_\infty\), \(\abs{\cdot}_p\), \(p\) prime
    #+END_theorem

    exercise
    1. check they are inequivalent
    2. \(\forall a\in\Q^\times\), \(\abs{a}_\infty\prod_{p\text{ prime}}\abs{a}_p=1\)


    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((A,\fm)\) local ring, \(k\) residue field, \(E\subseteq k\) subfield, \(F\subseteq A\) subfield. \(F\) is a *lift*
    of \(E\) if \(\barF=E\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    \(A\) henselian local, \(\tchar{k}=0\), then there is a lift of \(k\) in \(A\)
    #+END_theorem

    #+BEGIN_proof
    Zorn's lemma
    \begin{center}\begin{tikzcd}
    \Q\ar[r]\ar[rd]&A\ar[d]\\
    &k
    \end{tikzcd}\end{center}

    Given \(E\subseteq k\), \(F\subseteq A\) a lift, \(a\in k\setminus E\), one can extend the lift to \(E(a)\)

    then zorn's lemma gives the maximal lift is a lift of \(k\)

    case 1: \(a\) is transcendental over \(E\), take \(\alpha\) s.t. \(\baralpha=a\), then \(\alpha\notin\fm\), \(F(\alpha)\) is a lift
    of \(E(a)\)

    case 2: \(a\) is algebraic over \(E\)

    \(f\in E[x]\) is the minimal polynomial of \(a\), \(g\in F[x]\), if we can find a root \alpha of \(g\)
    in \(A\) s.t. \(\baralpha=a\), then \(F[\alpha]\) is a lift of \(E(a)\)

    take any \(\ove{\alpha'}=a\), then \(\ove{g(\alpha')}=f(a)=0\), \(g(\alpha')\in\fm\), \(\ove{g'(\alpha')}=f'(a)\neq 0\) (check)
    (\(\tchar(k)\neq 0\)), \(g'(\alpha')\notin\fm\)
    #+END_proof


    #+ATTR_LATEX: :options [Greenleaf, answered a question of Lang in 1950's]
    #+BEGIN_theorem
    \(f_1,\dots,f_m\in\Z[X_1,\dots,X_n]\), then for all but finitely many \(p\), any solution
    of \(f_1=f_2=\dots=f_m=0\) in \(\F_p\) can be lifted to a solution in \(\Z\)
    #+END_theorem

    #+BEGIN_proof
    \(\HLR\) denote the axioms of henselian local rings,

    \(\ch_p:1+\dots+1\in\fm\)

    \(\varphi:\forall x_1,\dots,x_n(f_1(x),\dots,f_m(x)\in\fm)\to\exists y(f_1(y)=\dots=f_m(y)=0\wedge y_i-x_i\in\fm)\)

    therefore
    \begin{equation*}
    \HLR\cup\{\neg\ch_p:p\text{ prime}\}\vDash\varphi
    \end{equation*}
    Then by compactness
    \begin{equation*}
    \HLR\cup\{\neg\ch_2,\neg\ch_3,\dots,\neg\ch_p\}\vDash\varphi
    \end{equation*}
    So any solution of \(f_1=\dots=f_m=0\) in \(\F_p\) can be lifted to \(\Z_p\) for \(p\) large
    #+END_proof

    #+BEGIN_proof
    \(\calu\) non principle ultrafilter on primes

    \(k=\prod_{p}\F_p/\calu\), \(\tchar(k)=0\)

    \(\prod_{p}\Z_p/\calu\vDash\varphi\)

    For all but
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A *valuation* on a domain \(A\) is a map \(v:A^\times\to\Gamma\), \(\Gamma\) is an ordered abelian group \((\Gamma,+,0,<)\)
    satisfying
    1. \(v(x+y)\ge\min\{v(x),v(y)\}\) if \(x+y\neq 0\)
    2. \(v(x\cdot y)=v(x)+v(y)\)
    Usually, we extend \(v\) to \(A\) by setting \(v(0)=\infty\), then \(v:A\to\Gamma_\infty=\Gamma\cup\{\infty\}\), \(\infty>\gamma\forall \gamma\in\Gamma\)
    #+END_definition

    If \(\Gamma\subseteq\R\), \(v\) is given by a non-archimedean abs value by setting \(\abs{}_v=e^{-v}\)

    \(v\) extends uniquely to \(K=\Frac(A)\) by setting \(v(x/y)=v(x)-v(y)\)

    \(v(K^\times)\) is a subgroup of \Gamma

    From now on, we always assume \(v(K^\times)=\Gamma\) when talking about valued fields, \Gamma is called the
    *value group* group of \((K,v)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(K=\C(t)\) (rational function in 1-variable), \(\forall a\in\C\), \(v_a:\C(t)\to\Z\), \(v_a(f)=k\)
    if \(f=(t-a)^k\frac{g(t)}{h(t)}\), \(g(a),h(a)\neq 0\), \(v_a(0)=\infty\)

     \(v_\infty:K\to\Z_\infty\), \(f=\frac{g}{h}\), \(v_\infty(f)=\deg(h)-\deg(g)\)

     \(\sum_{a\in\C\cup\{\infty\}}v_a(f)=0\) (#zeros=#poles)
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    \(\Q\) with \(p\)-adic valuation
    #+END_examplle

    Geometrically, \(K\) a field, \(v\) a valuation on \(K\), \(v\) is a point on some abstract
    space \(S\) and elements of \(K\) are functions on \(S\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \((k,v)\) valued field
    1. \(\calo_v=\{x\in k:v(x)\ge 0\}\), \(\calo_v\) is a local subring of \(k\)
    2. \(\fm_v=\{x\in k,v(x)>0\}\) is the maximal ideal of \(\calo_v\)
    3. \(k_v=\calo_v/\fm_v\)

    More generally, we say \(\calo\subseteq K\) a subring is a valuation ring if \(\forall x\in K^\times\), \(x\in\calo\)
    or \(x^{-1}\in\calo\), check \(\calo_v\) is a valuation ring
    #+END_definition

    \(\C(t_1,t_2)\), order \(\Z\times\Z\) by lexicographic order

    \(f\in\C[t_1,t_2]=\C[t_1][t_2]=A[t_2]\)

    \(\ord_{t_2}(f)=\min\{i:f=\sum a_it_2^i, a_i\in A,a_i\neq 0\}\)

    If \(\ord_{t_2}(f)=i\), then we have \(\ord_{t_1}\)

    \(v(f)=(\ord_{t_2}(f),\ord_{t_1}(f))\)

    non-archimedean gives: if \(v(a)\neq v(b)\), \(v(a+b)=\min\{v(a),v(b)\}\)

* Course 2
    \(v:k\to\Gamma_\infty\) valuation, \(\calo_v\), \(\fm_v\), \(\calo\subseteq K\)  is a valuation ring

    \(\Gamma=k^\times/U(\calo)\)

    \(x\le y\Leftrightarrow y/x\in\calo\)

    \(v_{\calo}:k^\times\to\Gamma\), \(x\mapsto[x]\), check this is a valuation

    Given two valuation \(v_1:k^\times\to\Gamma_1\), \(v_2:k^\times\to\Gamma_2\), \(v_1\) is equivalent to \(v_2\) if
    \begin{center}\begin{tikzcd}
    &k^\times\ar[dl,"v_1"]\ar[dr,"v_2"]\\
    \Gamma\ar[rr,"\cong"]&&\Gamma
    \end{tikzcd}\end{center}
    commutes

    \(v\mapsto\calo_v\mapsto v_{\calo}\), \(v\) is equivalent to \(v_{\calo}\)

    \((k,v)\) valued field, \(\gamma\in\Gamma_\infty\), \(a\in k\), define
    \begin{align*}
    &B_\gamma(a)=\{b\in k:v(b-a)>\gamma\}\\
    &\barB_\gamma(a)=\{b\in k:v(b-a)\ge\gamma\}
    \end{align*}
    \gamma is the *valuative radius* of the ball, \(a\) is the center of the ball

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(\forall b\in B_\gamma(a)\), \(B_\gamma(a)=B_\gamma(b)\)
    2. \(\forall b\in\barB_\gamma(a)\), \(\barB_\gamma(b)=\barB_\gamma(a)\)
    3. \(\forall B_1,B_2\) balls, \(B_1\cap B_2\neq\emptyset\Rightarrow B_1\subseteq B_2\vee B_2\subseteq B_1\)
    4. \(\calo_v=\barb_0(0)\), \(\fm_v=B_0(0)\)
    5. \(\calo_v\) contains \(\abs{k_v}\)-many open balls of valuative radius 0. Same for any closed ball
       of valuative radius \(\gamma\neq\infty\)
    #+END_proposition

    All \(B_\gamma(a)\) forms a basis of a topology, the induced topology is called the *valuation
    topology* or *\(v\)-topology*

    \(+,\cdot,-,^{-1}\) are continuous function on it

    #+ATTR_LATEX: :options [Hahn fields/series]
    #+BEGIN_examplle
    \(k\) field, \Gamma OAG, consider
    \begin{align*}
    &\sum_{\gamma\in\Gamma}a_\gamma t^\gamma=f,a_\gamma\in k\\
    &\supp(f)=\{\gamma:a_\gamma\neq 0\}
    \end{align*}
    define \(k((t^\Gamma))=\{f=\sum_{\gamma\in\Gamma}a_\gamma t^\gamma:\supp(f)\text{ is well-ordered}\}\)
    \begin{align*}
    &\sum_\gamma a_\gamma\cdot t^\gamma+\sum_\gamma b_\gamma t^\gamma=\sum_\gamma(a_\gamma+b_\gamma)t^\gamma\\
    &(\sum_\gamma a_\gamma t^\gamma)(\sum_\gamma b_\gamma t^\gamma)=\sum_\gamma(\sum_{\alpha+\beta=\gamma}a_\alpha b_\beta)t^\gamma
    \end{align*}
    \(k((t^\Gamma))\) is a field

    \(v:K^\times\to\Gamma\), \(v(f)=\min\supp(f)=\min\{\gamma:a_\gamma\neq 0\}\)
    #+END_examplle

    Extension of valuations \((K,v)\), consider extension \(L/K\),

    From now on, by a valued field, we usually mean \((K,\calo)\), \(\calo\subseteq K\), valuation ring,
    \begin{equation*}
    i:(K,\calo)\hookrightarrow(L,A)
    \end{equation*}
    \(i^{-1}(A)=\calo\)

    \((K,A)\) valued field, \(L/K\) extension, \(B\subseteq L\) a valuation ring, \(B\) *lies
    over* \(A\)/ \(B\) *dominates* \(A\) if \(B\cap K=A\), that is, \(\fm_A=\fm_B\cap A\)

    \(U(B)\cap K=U(A)\)

    \(\Gamma_A=K^\times/U(A)\hookrightarrow\Gamma_B=L^\times/U(B)\) order preserving

    \((K,A)\subseteq(L,B)\) valued field extension

    \((K,v_A)\subseteq(L,v_B)\), \(v_B\mid_K=v_A\)

    \(A\subseteq B\) rings, \(I\subseteq A\), \(IB\) is the ideal generated by \(I\)
    in \(B\), \(p\subseteq A\), \(q\subseteq B\) prime, \(q\) lies over \(p\) if \(q\cap A=p\)
    \begin{center}\begin{tikzcd}
    A\ar[r]\ar[d]&B\ar[d]\\
    A/p\ar[r]&B/q
    \end{tikzcd}\end{center}
    \(A\subseteq B\)  local, \(B\) lies over \(A\) if \(\fm_B\) lies over \(\fm_A\)

    A domain \(K=\Frac(A)\), \(\fp\subseteq A\) prime ideal, \(A_{\fp}=\{\frac{x}{y}\in K\mid x,y\in A,y\notin\fp\}\), \(A_{\fp}\)
    is a local ring with maximal ideal \(pA_{\fp}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(A\subseteq B\) rings, \(b\in B\), \(b\) is *integral over* \(A\) if there is a monic
    polynomial \(f\in A[x]\) s.t. \(f(b)=0\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(A\subseteq B\) rings, \(b\in B\), TFAE
    1. \(b\) integral over \(A\)
    2. \(A[b]\) is finite \(A\)-module
    3. \(A[b]\) is contained in a finite \(A\)-module \(A'\subseteq B\)
    #+END_lemma

    #+BEGIN_proof
    \(3\Rightarrow 1\): \(A'\) is generated by \(x_1,\dots,x_n\in B\), \(bx_i=\sum_{j}a_{ij}x_j\), \(a_{ij}\in A\)
    \begin{equation*}
    M=
    \begin{pmatrix}
    a_{11}-b&a_{12}&\dots&a_{1n}\\
    a_{21}&a_{22}-b&\dots&a_{2n}\\
    \vdots\\
    a_{n1}&\dots&\dots&a_{nn}-b\\
    \end{pmatrix}
    \end{equation*}
    then
    \begin{equation*}
    M
    \begin{pmatrix}
    x_1\\x_2\\\vdots\\ x_n
    \end{pmatrix}=0
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(A\subseteq B\subseteq C\) rings, \(B/A\), \(C/B\) integral, then \(C/A\) integral
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(A\subseteq B\) rings, \(S\)=elements in \(B\) that are integral over \(A\) is called the integral
    closure of \(A\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Integral closure is a ring
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(A\subseteq B\) domain, \(B/A\) integral, \(A\) is a field \(\Leftrightarrow\) \(B\) is a field
    #+END_lemma

    #+BEGIN_proof
    \(\Rightarrow\): \(b\in B\), \(b\neq 0\), take \(n\) minimal,
    \begin{equation*}
    b^n+a_{n-1}b^{n-1}+\dots+a_{0}=0
    \end{equation*}
    \(b(b^{n-1}+a_{n-1}b^{n-2}+\dots+a_1)=-a_0\), \(a_0\neq 0\) since \(n\) is the minimal
    \(\Leftarrow\): \(a\in A^\times\), \(a^{-1}\in B\),
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(A\subseteq B\) ring, integral, \(\fp\subseteq A\), \(\fq\subseteq B\) prime, \(\fq\) lies over \(\fp\), then \(\fp\) is
    maximal \(\Leftrightarrow\) \(\fq\) is maximal
    #+END_corollary

    #+ATTR_LATEX: :options [Lying over]
    #+BEGIN_theorem
    \(A\subseteq B\) integral, \(\fp\subseteq A\) prime, \(\exists\fq\subseteq B\) prime, \(\fq\) lies over \(\fp\)
    #+END_theorem

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(A\subseteq K\), \(K\) a field, \(A\) local, \(x\in K^\times\), \(1\in\fm A[x^{-1}]+x^{-1}A[x^{-1}]\), then \(x\)
    is integral over \(A\)
    #+END_lemma

    \(A[x^{-1}]\) contains a maximal ideal extending \(x^{-1}\) and \(\fm\)

    #+BEGIN_proof
    \(1=a_nx^{-n}+a_{n-1}x^{-n+1}+\dots+a_1x^{-1}+a_0\), \(a_0\in\fm\),
    then \(x^n=a_n+a_{n-1}x+\dots+a_0x^n\)
    #+END_proof

    #+ATTR_LATEX: :options [Chevalley]
    #+BEGIN_theorem
    \(A\subseteq K\) a ring, \(\fp\subseteq A\) prime, then there is \(\calo\subseteq K\) valuation ring s.t. \(\fm\) lies over \(\fp\)
    #+END_theorem

    #+BEGIN_proof
    assume \(A\) is local by localizing at \(\fp\) (replace \(A\) by \(A_{\fp}\)),
    Consider the set of local subrings of \(K\) that lies over \(A\), this is a poset ordered by
    inclusion. Take \(\calo\) to be the maximal elements

    Claim: \(\calo\) is a valuation ring

    we need to prove \(x\in K^\times\Rightarrow x\in\calo\vee x^{-1}\in\calo\)

    If \(x\) is integral over \(\calo\), \(\calo[x]\) is integral extension over \(\calo\), then \(\calo[x]\) has a
    maximal ideal \(\fn\) lying over \((\calo,\fm)\), \((\calo[x])_{\fn}\supseteq(\calo,\fm)\), \(x\in\calo\)

    If \(x\) is not integral over \(\calo\), then \(1\notin\fm\calo[x^{-1}]+x^{-1}\calo[x^{-1}]\), \(\calo[x^{-1}]\) has a
    maximal ideal \(\fn\supseteq\fm\), therefore \(\fn\cap\calo\subseteq\fm\), \(x^{-1}\in\calo\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \((k,v)\) valued field, \(L/K\) field extension, then there is \(v':L^\times\to\Gamma'\supseteq\Gamma\) s.t. \(v'|_K=v\)
    #+END_proposition

    Next we study the interactions between integral closures and valuation rings

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:33
    \(A\subseteq K\) , valuation ring, then \(A\) is integrally closed in \(K\) ()
    #+END_lemma

    \(A\) is integral closed if \(A\) is integral closed in \(\Frac(A)\)

    #+BEGIN_proof
    \(v\) denotes the associated valuation, \(b\in K\) integral over \(A\)

    \(v(b^n+a_{n-1}b^{n-1}+\dots+a_0)\)

    If \(b\notin\calo\), \(v(b)<0\), \(a_i\in A\), \(v(a_i)\ge 0\), if \(v(b^n)<v(a_ib^i)\) for any \(i\),
    since \(v(a)<v(b)\Rightarrow v(a+b)=v(a)\), therefore \(v(b^n+\dots+a_0)=v(b^n)=nv(b)<0\), contradiction
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:34
    \((K,\calo)\) valued field, \(K\) algebraically closed \(\Rightarrow\) \((K,\calo)\) is henselian (\(\calo\) henselian)
    #+END_lemma

    #+BEGIN_proof
    ref:10

    Given \(f:=Y^n+Y^{n-1}+c_2Y^{n-2}+\dots+c_n\), then
    \(f=\prod_{i=1}^n(Y+\alpha_i)\), Lemma ref:33 gives \(\alpha_i\in\calo\), \(\sum_{i=1}^n\alpha_i=1\), so some \(\alpha_i\) must lie
    outside \(\fm\), and hence a unit
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:35
    \(A\subseteq K\) local, \(B\)=integral closure of \(A\) in \(K\), \(B=\bigcap_i\calo_i\), \(\calo_i\) ranges over all
    valuation rings dominating over \(A\)
    #+END_proposition

    #+BEGIN_proof

    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:36
    \(A\subseteq K\) valuation ring, \(L/K\) algebraic extension, \(B=\)integral closure of \(A\) in \(L\),
    then any valuation ring \(\calo\subseteq L\)  dominating \(A\) are of the form \(B_{\fn}\) for some \(\fn\) lying
    over \((A,\fm)\)
    #+END_proposition

    #+BEGIN_proof
    Let \(\calo\subseteq L\) valuation ring lying over \(A\), Proposition ref:35 \(\Rightarrow\) \(B\subseteq\calo\), \(\fn=\fm_{\calo}\cap B\)

    Claim: \(\calo=B_{\fn}\)

    \(\fn\) is a prime ideal of \(B\), \(x\in B\setminus\fn\), \(x\) is invertible in \(\calo\) \(\Rightarrow\) \(B_{\fn}\subset\calo\)

    \(x\in\calo\), \(x\neq 0\), \(\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(L/K\) algebraic field extension, \(L/K\) is normal if \(f\in K[x]\) has a root in \(L\),
    then \(f\) splits into linear factors in \(L\)
    #+END_definition

    Particularly, \(K\subseteq L\subseteq K'\), \(L/K\) normal, \(\sigma\in\Aut(K'/K)\), then \(\sigma|_L\in\Aut(L/K)\)

    #+ATTR_LATEX: :options [Chinese remainder theorem]
    #+BEGIN_proposition
        \(A\) domain, \(\fm_1,\dots,\fm_n\) distinct maximal
        ideals, \(\forall a_1,\dots,a_n\in A\), \(\exists a\in A\), \(a\equiv a_i\mod\fm_i\) \(\forall i\)
    #+END_proposition

    #+BEGIN_proof
    Claim: for each \(i\), there is \(b_i\in\fm_j\)  for all \(j\neq i\), and \(b_i\equiv 1\mod\fm_i\)

    \(\fm_i+\fm_j=A\) for all \(i\neq j\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:38
    \(A\subseteq K\) local, \(A\) is integrally closed, \(L/K\) finite normal extension, \(\fn_1,\fn_2\) two
    maximal ideals of \(B\), then there is \(\sigma\in\Aut(L/K)\), \(\sigma(\fn_1)=\fn_2\)
    #+END_proposition









* Course 4
    Next goal is AKE-theorem

    We give other characterizations of henselianity

    Recall \((K,A)\) is *henselian* if \(A\) is
    henselian: \(\forall f\in A[x]\), \(\alpha\in A\), \(f(\alpha)\in\fm\), \(f'(\alpha)\notin\fm\), then there is \(a\in A\)
    s.t. \(a\equiv\alpha\mod\fm\) and \(f(a)=0\)

    NTS: Henselian \(\Leftrightarrow\) unique extension to all algebraic extension

    \((K,A)\) valued  field, \(L/K\) algeraic extension, \(B\) integral closure of \(A\) in \(L\).
    Then the map \(\fn\mapsto B_{\fn}\) is a bijection bettwen maximal ideals of \(B\) and valuation rings
    of \(L\) over \(A\)

    \(L/K\) is normal, then any two valuation rings are conjugate

    \(B=\bigcap_i\calo_i\), \(\calo_i\) ranges over all valuation rings in \(L\) over \(A\)

    We first want to show \(A\) henselian \(\Rightarrow\) \(B\) local

    \((K,A)\subseteq(L,B)\) extensions of valued field is *immediate* if \(k_A=k_B\), \(\Gamma_A=\Gamma_B\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:56
    \(F/K\) finite Galois (normal+separable), \((K,\calo)\) valued field, \(\calo_1,\dots,\calo_m\) all distinct
    valuation rings of \(F\) over \(\calo\). Let \(G=\{\sigma\in\Gal(F/K):\sigma(\calo_1)=\calo_1\}\), \(L=F^G=\)fixed field
    of \(G\), if \(m\ge 2\), then
    1. \((K,\calo)\) not henselian
    2. \((L,\calo_1\cap L)\) is a proper immediate extension of \((K,\calo)\)
    #+END_lemma

    #+BEGIN_proof
    proper extension: Galois correspondence

    Let \(\calo_i'=\calo_i\cap L\), \(\fm_i'​=\fm_i\cap L\), \(\fm_i\) maximal ideal of \(\calo_i\)

    Claim: \(\calo_i'\neq\calo_i\) for \(i\ge 2\)

    If not, \(\calo_i,\calo_1\) are two distinct extension of \(\calo'=\calo_i'\)
    #+END_proof
* Note on \texorpdfstring{\(p\)}{p}-adic
    From [[https://www.cs.mcgill.ca/~echern2/repo/padic.pdf][this]] and [[http://math.uchicago.edu/~may/REU2020/REUPapers/Pomerantz.pdf][this]]

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    An *ultra-metric* space is a non-empty set \(X\) with a function \(d:X\times X\to\R_{\ge 0}\) satisfying
    1. \(d(x,y)=0\Leftrightarrow x=y\)
    2. \(d(x,y)=d(y,x)\)
    3. \(d(x,y)\le\max\{d(x,z),d(z,y)\}\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A metric space \((X,d)\) is called *complete* if every Cauchy sequence is convergent in \(X\)
    #+END_definition



    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Given an absolute value \(\abs{\cdot}\) on \(K\), then
    \begin{equation*}
    d(x,y)=\abs{x-y}
    \end{equation*}
    is a metric, and if \(\abs{\cdot}\) is non-Archimedean, then the metric is ultra-metric
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(K\) be an ultrametric space and let \(x,y\in K\), then \(\abs{x}\neq\abs{y}\Rightarrow\abs{x+y}=\max\{\abs{x},\abs{y}\}\)
    #+END_lemma





    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    \(p\)-adic valuation does not depend on the representation of a rational number, i.e.,
    if \(\frac{a}{b}=\frac{a'}{b'}\), then \(v_p(a)-v_p(b)=v_p(a')-v_p(b')\)
    #+END_proposition





    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Prove that \(\lim_{n\to\infty}p^n=0\)
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A sequence \((a_n)\) is *Cauchy* if for every \(\epsilon>0\) there is some \(N\in\N\) s.t. for
    all \(m,n\ge N\),
    \begin{equation*}
    \abs{a_n-a_m}<\epsilon
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A metric space \(X\) is *complete* under a given metric if every Cauchy sequence in \(X\)
    converges to a point in \(X\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    The field of rational numbers, \(\Q\), is not complete under the \(p\)-adic metric
    #+END_proposition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(K\) be a field with an absolute value \(\abs{\cdot}\), then there exists a complete
    field \(K'\) with an absolute value \(\{\cdot\}''\) that extends \(K\). This completion \(K'\) is
    unique up to isomorphism.
    #+END_theorem
