#+TITLE: Homework6

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}

#+BEGIN_exercise
Recall that a linear order \((M,\le)\) is *well-ordered* if every non-empty subset \(S\subseteq M\) has a
minimum. Show that the class of well-ordered linear orders is *not* an elementary class. In other
words, show that there is no theory \(T\) whose models are exactly the well-ordered linear orders.
#+END_exercise

#+BEGIN_proof
The language is \(L=\{\le\}\). Let
\begin{align*}
&\varphi_n:=\exists x_1\dots x_n\left(\bigwedge_{1\le i<j\le n}(x_i\neq x_j\wedge x_i\le x_j)\right)\\
&\Phi:=\{\varphi_n:n\in\N\}
\end{align*}
If there is such theory \(T\) whose models are exactly the well-ordered linear orders. Consider the
theory \(\Gamma=T\cup\Phi\). For any finite subset \(\Delta\) of \(\Phi\), there is a \(\varphi_m\in\Phi\) with biggest \(m\) and
\(\vDash\bigwedge\Delta\le\leftrightarrow\varphi_m\). Since every ordinal is well-ordered, the ordinal \(m\) satisfies both \(T\)
and \(\varphi_m\), that is, \((m,\le)\vDash T\cup\varphi_m\), or equivalently, \((m,\le)\vDash T\cup\Delta\). Thus by compactness \(\Gamma\) is
satisfiable and we have a model \(\fM\vDash T\cup \Phi\). Hence \(\fM\) is well-ordered and has an infinite
descending sequence, a contradiction.
#+END_proof

#+BEGIN_exercise
Let \kappa be an infinite cardinal. A theory \(T\) is said to be \kappa-categorical if there is a
model \(M\vDash T\) of size \kappa, and any two models of size \kappa are isomorphic. Prove that: Suppose \(T\) is
\kappa-categorical for some infinite \(\kappa\ge\abs{L}\). Suppose \(T\) has no finite models. Then \(T\) is
complete: if \(M_1,M_2\vDash T\), then \(M_1\equiv M_2\)
#+END_exercise

#+BEGIN_proof
For any model \(M\) of \(T\), if \(\abs{M}>\kappa\), then choose a subset \(A\) of \(M\) such
that \(\abs{A}=\kappa\). Then \(\abs{L(A)}=\kappa\) and
\(M\) is the model of \(T(A)\) and by Löwenheim–Skolem Theorem, we can find
a model \(M'\vDash T(A)\) of cardinality \kappa. Then \(T(A)=T(M')\) and hence \(M'\prec M\).
Furthermore, \(M'\equiv M\).

If \(\abs{M}<\kappa\), by Löwenheim–Skolem Theorem, we can find a model \(M'\vDash T(M)\) with cardinality
\kappa such that \(M\prec M'\). Furthermore, \(M'\equiv M\).

If \(\abs{M}=\kappa\), let \(M'=M\). Then for any \(M_1,M_2\vDash T\), \(M'_1\equiv M_1\) and \(M'_2\equiv M_2\).
As \(\abs{M_1'} =\abs{M_2'} =\kappa\), we have \(M_1'\cong M_2'\) and hence \(M_1'\equiv M_2'\). Thus
\(M_1\equiv M_1'\equiv M_2'\equiv M_2\)
#+END_proof

#+BEGIN_exercise
Let \(M\) be an infinite \(L\)-structure. Let \kappa be a cardinal with \(\kappa\ge\abs{M}\) and \(\kappa\ge\abs{L}\).
Show that there is an elementary extension \(N\succeq M\) with \(\abs{N}=\kappa\).
#+END_exercise

#+BEGIN_proof
Consider the language \(L(M)\) and theory \(T(M)\) and \(M\) is the infinite model of \(T(M)\). Then
by Löwenheim–Skolem Theorem, \(T(M)\) has a model \(N\) of size \kappa and \(M\preceq N\).
#+END_proof

#+BEGIN_exercise
Let \(M\) be an \(L\)-structure and \(A\) be a subset of \(M\). For \(i=1,2\), let \(N_i\) be an
elementary extension of \(M\) and let \(\barb_i\) be an \(n\)-tuple in \(N_i\). Show that the
following are equivalent
1. \(\barb_1\) realizes \(\tp(\barb_2/A)\)
2. \(\tp(\barb_1/A)\supseteq\tp(\barb_2/A)\)
3. \(\tp(\barb_1/A)=\tp(\barb_2/A)\)
#+END_exercise

#+BEGIN_proof
\(1\to 2\). For any \(\varphi(\barx)\in\tp(\barb_2/A)\), \(N_1\vDash\varphi(\barb_1)\) as \(\barb_1\)
realizes \(\tp(\barb_2/A)\). Hence \(\tp(\barb_1/A)\supseteq\tp(\barb_2/A)\).

\(2\to 3\). For any \(\varphi(\barx)\in\tp(\barb_1/A)\). If \(N_2\not\vDash\varphi(\barb_2)\),
then \(\neg\varphi(\barx)\in\tp(\barb_2/A)\subseteq\tp(\barb_1/A)\). Then both \(\neg\varphi(\barx)\in\tp(\barb_1/A)\), a
contradiction.

\(3\to 1\). As \(\tp(\barb_1/A)=\tp(\barb_2/A)\), for any \(\varphi(\barx)\in\tp(\barb_2/A)\), \(N_1\vDash\varphi(\barb_1)\)
and thus \(\barb_1\) realizes \(\tp(\barb_2/A)\).
#+END_proof
