#+title: Generic Properties Of Groups

#+AUTHOR: Marcin Petrykowski
#+EXPORT_FILE_NAME: ../latex/papers/generic properties of groups.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    If \(p(\barx)\) is a type over \(A\), then we call the set of realizations of \(p\) in \(M\)
    \begin{equation*}
    p(M^n)=\{\bara\in M^n:(\forall\varphi(\barx)\in p(\barx))M\vDash\varphi(\bara)\}\vDash\bigcap_{\varphi(\barx)\in p(\barx)}\varphi(M^n)
    \end{equation*}
    *type definable over* \(A\). If \(V\) is a 0-type-definable subset of \(M^n\), then we sometimes
     identify \(V\) with the set
     \begin{equation*}
    [V]=\{\tp(\bara):\bara\in V\}\subseteq S_n(\emptyset)
     \end{equation*}

     A first order structure \(M\) is \kappa-saturated if for any \(A\subseteq M\) with \(\abs{A}<\kappa\), \(n<\omega\)
     and \(p\in S_n(A)\), \(p\) has a realization in \(M\).

     A group \((G,\cdot)\) is definable in a structure \(M\) is \(G\) is a definable subset of \(M^n\)
     for some \(n<\omega\) and the group action \(\cdot:G\times G\to G\) is a definable function in \(M\).
     If \(p(x)\) is a type over \(G\) and \(g\in G\), then
     \begin{equation*}
    g\cdot p(x)=\{g\cdot\varphi(x):\varphi(x)\in p(x)\}=\{\varphi(g^{-1}\cdot x):\varphi(x)\in p(x)\}
     \end{equation*}
     A group \((G,\cdot)\) is definable in a structure \(M\) if \(G\) is a definable

     An infinite totally ordered first order structure \((M,<,\dots)\) is *o-minimal* if every definable
     subset of \(M\) is a union of finitely many intervals and points.

     Let \((M,<,\dots)\) be an o-minimal structure. We usually say "ultimately" instead of "for all
     sufficiently large \(a\in M\)". We denote an open interval with endpoints \(a\) and \(b\)
     by \((a,b)\) and a closed one by \([a,b]\). In contrast, \(\la a,b\ra\) denotes the pair of
     elements \(a\) and \(b\).

     If \(a\in M\cup\{-\infty\}\), \(b\in M\cup\{+\infty\}\), \(a<b\) and \(f:(a,b)\to M\) is a definable function, then there
     are \(a=a_1<\dots<a_n=b\) s.t. each interval \((a_i,a_{i+1})\) of \(f\) is either constant or
     strictly monotone and continuous in the order topology. In particular, every definable
     function \(f:M\to M\) is ultimately continuous and monotone

* Weak generic types
** Introduction
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq G\) is *(left) generic* if some finitely many left \(G\)-translates of \(X\)
    cover \(G\). We say that a formula \(\varphi(x)\) is *(left) generic* if the set \(\varphi(G)\) of elements
    of \(G\) realizing \varphi is *(left) generic*. Finally, we say that a type \(p(x)\) of elements
    of \(G\) is *(left) generic* if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is (left) generic
    #+END_definition

    In the stable case left generic = right generic <<Problem1>>

    and each partial generic type extends to a complete generic type (since type is definable)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(A\subseteq G\) is *weak generic*, if for some non-generic \(B\subseteq G\) we have that \(A\cup B\) is
    generic. A formula \(\varphi(x)\) is *weak generic* if the set \(\varphi(G)\) is weak generic. A type \(p(x)\)
    of elements of \(G\) is weak generic if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is weak generic
    #+END_definition

** Basic properties of weak generic sets and types
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume that \(G\) is a group and \(X\) is a definable subset of \(G\). TFAE
    1. the set \(X\) is weak generic
    2. for some finitely many elements \(a_1,\dots,a_n\in G\) the set \(G\setminus\bigcup_{i=1}^na_i\cdot X\) is not generic
    3. for some definable non-generic set \(Y\subseteq G\) the set \(X\cup Y\) is generic
    #+END_lemma

    #+BEGIN_proof
    \(1\Rightarrow 2\): Assume \(X\) is weak generic, then there is non-generic set \(Y\subseteq G\) s.t. \(X\cup Y\) is
    generic. Then there are \(a_1,\dots,a_n\in G\) s.t.
    \begin{equation*}
    \bigcup_{i=1}^na_i\cdot(X\cup Y)=\bigcup_{i=1}^na_i\cdot X\cup\bigcup_{i=1}^na_i\cdot Y=G
    \end{equation*}
    This means that
    \begin{equation*}
    G\setminus\bigcup_{i=1}^na_i\cdot X\subseteq\bigcup_{i=1}^na_i\cdot Y
    \end{equation*}

    \(2\Rightarrow 3\): Let \(Y=G\setminus\bigcup_{i=1}^na_i\cdot X\). Then \(Y\) is definable and not generic so
    putting \(a_{n+1}=e\). Then \(G=\bigcup_{i=1}^{n+1}a_i\cdot(X\cup Y)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.2
    1. If \(X,Y\subseteq G\) are not weak generic, then \(X\cup Y\) is not weak generic
    2. If \(p(x)\) is a (partial) weak generic type over \(A\subseteq G\), then \(p(x)\) may be extended to
       a complete weak generic type over \(A\)
    #+END_lemma

    #+BEGIN_proof
    1. Let \(Z\subseteq G\)  be non-generic. \(Y\) is not weak generic so \(Y\cup Z\) is not generic,
       so \(Y\cup Z\cup X\) is not generic
    2. non weak generics form an ideal

       Let \(q(x)=\{\varphi(x)\in L(A):p(x)\cup\{\neg\varphi(x)\}\text{ is not weak generic}\}\). Then \(p\subseteq q\). We shall
       show that \(q\) is a consistent partial type over \(A\). If not, then
       \begin{equation*}
       G\vDash\neg\exists x\bigwedge_{k=1}^n\varphi_k(x)
       \end{equation*}
       for some \(n<\omega\) and \(\varphi_1,\dots,\varphi_n\in q\). By compactness, for each \(k\in\{1,\dots,n\}\) we can find a
       finite set of formulas \(p_k\subseteq p\) s.t. the type \(p_k(x)\cup\{\neg\varphi_k(x)\}\) is not weak generic.
       Let \(\psi(x)=\bigwedge\{p_k(x):1\le k\le n\}\) and note that for every \(k\in\{1,\dots,n\}\) the set \(\psi(G)\cap\neg\varphi_k(G)\)
       is not weak generic. By 1, neither is the union
       \begin{equation*}
       \bigcup_{k=1}^n(\psi(G)\cap\neg\varphi_k(G))=\psi(G)\cap\bigcup_{k=1}^n\neg\varphi_k(G)=\psi(G)\cap G=\psi(G)
       \end{equation*}
       contradicting the fact that \(p(x)\vdash\psi(x)\). Finally we take any \(r(x)\in S(A)\)
       with \(r\supseteq q\) and the proof is complete
    #+END_proof

    We see that (complete) weak generic types exist. By Lemma ref:3.2.2, the set
    \begin{equation*}
    WGEN(A)=\{p\in S(A):p\text{ is weak generic}\}
    \end{equation*}
    is closed and non-empty in \(S(A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume \(G\) is a group and \(A\subseteq G\)
    1. If some weak generic type \(p(x)\in S(G)\) is generic, then all weak generic
       types \(q(x)\in S(A)\) are generic
    2. If for every \(p,q\in WGEN(G)\) there is \(g\in G\) s.t. \(g\cdot p=q\), then all weak generic
       types \(q(x)\in S(A)\) are generic
    3. If there is just one weak generic type in \(S(A)\), then it is generic
    #+END_lemma

    #+BEGIN_proof
    1. Suppose that some weak generic type \(q(x)\in S(A)\) is not generic. Then some definable
       generic set \(X\subseteq G\) may be divided into two non-generic definable sets \(X_1,X_2\).
       Since \(X\) is generic, some left \(G\)-translates \(X'\) of \(X\) belongs to \(p(x)\). Then
       the corresponding translates \(X_1',X_2'\) of \(X_1,X_2\) are also non-generic and one of them
       belongs to \(p(x)\). Hence \(p(x)\) is not generic, a contradiction
    2. If not, then we can find a formula \(\varphi(x)\in L(A)\) which is weak generic but not generic. Note
       that \(\{\neg g\cdot\varphi(x):g\in G\}\) is a partial weak generic type over \(G\): for each \(m<\omega\)
       and \(g_1,\dots,g_m\in G\), the set \(\bigcup_{i=1}^mg_i\cdot\varphi(G)\) is not generic, which implies that the
       set \(\bigcap_{i=1}^m(G\setminus g_i\cdot\varphi(G))\) is weak generic. Extend the type \(\{\neg g\cdot\varphi(x):g\in G\}\) to
       some \(q(x)\in WGEN(G)\). Next extend \(\varphi(x)\) to \(p(x)\in WGEN(G)\). Then \(\forall g\in G\;g\cdot p\neq q\),
       a contradiction
    3. by 2, immediately
    #+END_proof

    By Lemma ref:3.2.3 (1), in the stable case weak generic = generic

    As an example not that if \(G=(G,<,+,\dots)\) is o-minimal, then there are exactly two complete weak
    generic types, corresponding to \(-\infty\) and \(+\infty\), and they are not generic

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume that \(G\prec H\) and \(\varphi(x)\in L(G)\)
    1. If \(\varphi(G)\) is weak generic in \(G\), then \(\varphi(H)\) is weak generic in \(H\)
    2.
    #+END_lemma

    #+BEGIN_proof
    1. There is a non-generic formula \(\psi(x)\in L(G)\) s.t. \(\varphi(G)\cup\psi(G)\) is generic in \(G\),
       therefore \(\psi(H)\) is not generic in \(H\) and \(\varphi(H)\cup\psi(H)\) is generic in \(H\).
       Thus \(\varphi(H)\) is weak generic in \(H\)
    #+END_proof

* Problems
    | [[Problem1]] |
    |          |
