#+title: Generic Properties Of Groups

#+AUTHOR: Marcin Petrykowski
#+EXPORT_FILE_NAME: ../latex/papers/generic properties of groups.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    If \(p(\barx)\) is a type over \(A\), then we call the set of realizations of \(p\) in \(M\)
    \begin{equation*}
    p(M^n)=\{\bara\in M^n:(\forall\varphi(\barx)\in p(\barx))M\vDash\varphi(\bara)\}\vDash\bigcap_{\varphi(\barx)\in p(\barx)}\varphi(M^n)
    \end{equation*}
    *type definable over* \(A\). If \(V\) is a 0-type-definable subset of \(M^n\), then we sometimes
     identify \(V\) with the set
     \begin{equation*}
    [V]=\{\tp(\bara):\bara\in V\}\subseteq S_n(\emptyset)
     \end{equation*}

     A first order structure \(M\) is \kappa-saturated if for any \(A\subseteq M\) with \(\abs{A}<\kappa\), \(n<\omega\)
     and \(p\in S_n(A)\), \(p\) has a realization in \(M\).

     A group \((G,\cdot)\) is definable in a structure \(M\) is \(G\) is a definable subset of \(M^n\)
     for some \(n<\omega\) and the group action \(\cdot:G\times G\to G\) is a definable function in \(M\).
     If \(p(x)\) is a type over \(G\) and \(g\in G\), then
     \begin{equation*}
    g\cdot p(x)=\{g\cdot\varphi(x):\varphi(x)\in p(x)\}=\{\varphi(g^{-1}\cdot x):\varphi(x)\in p(x)\}
     \end{equation*}
     A group \((G,\cdot)\) is definable in a structure \(M\) if \(G\) is a definable

     An infinite totally ordered first order structure \((M,<,\dots)\) is *o-minimal* if every definable
     subset of \(M\) is a union of finitely many intervals and points.

     Let \((M,<,\dots)\) be an o-minimal structure. We usually say "ultimately" instead of "for all
     sufficiently large \(a\in M\)". We denote an open interval with endpoints \(a\) and \(b\)
     by \((a,b)\) and a closed one by \([a,b]\). In contrast, \(\la a,b\ra\) denotes the pair of
     elements \(a\) and \(b\).

     If \(a\in M\cup\{-\infty\}\), \(b\in M\cup\{+\infty\}\), \(a<b\) and \(f:(a,b)\to M\) is a definable function, then there
     are \(a=a_1<\dots<a_n=b\) s.t. each interval \((a_i,a_{i+1})\) of \(f\) is either constant or
     strictly monotone and continuous in the order topology. In particular, every definable
     function \(f:M\to M\) is ultimately continuous and monotone

* Weak generic types
** Introduction
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq G\) is *(left) generic* if some finitely many left \(G\)-translates of \(X\)
    cover \(G\). We say that a formula \(\varphi(x)\) is *(left) generic* if the set \(\varphi(G)\) of elements
    of \(G\) realizing \varphi is *(left) generic*. Finally, we say that a type \(p(x)\) of elements
    of \(G\) is *(left) generic* if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is (left) generic
    #+END_definition

    In the stable case left generic = right generic <<Problem1>>

    and each partial generic type extends to a complete generic type (since type is definable)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(A\subseteq G\) is *weak generic*, if for some non-generic \(B\subseteq G\) we have that \(A\cup B\) is
    generic. A formula \(\varphi(x)\) is *weak generic* if the set \(\varphi(G)\) is weak generic. A type \(p(x)\)
    of elements of \(G\) is weak generic if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is weak generic
    #+END_definition

** Basic properties of weak generic sets and types
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.1
    Assume that \(G\) is a group and \(X\) is a definable subset of \(G\). TFAE
    1. the set \(X\) is weak generic
    2. for some finitely many elements \(a_1,\dots,a_n\in G\) the set \(G\setminus\bigcup_{i=1}^na_i\cdot X\) is not generic
    3. for some definable non-generic set \(Y\subseteq G\) the set \(X\cup Y\) is generic
    #+END_lemma

    #+BEGIN_proof
    \(1\Rightarrow 2\): Assume \(X\) is weak generic, then there is non-generic set \(Y\subseteq G\) s.t. \(X\cup Y\) is
    generic. Then there are \(a_1,\dots,a_n\in G\) s.t.
    \begin{equation*}
    \bigcup_{i=1}^na_i\cdot(X\cup Y)=\bigcup_{i=1}^na_i\cdot X\cup\bigcup_{i=1}^na_i\cdot Y=G
    \end{equation*}
    This means that
    \begin{equation*}
    G\setminus\bigcup_{i=1}^na_i\cdot X\subseteq\bigcup_{i=1}^na_i\cdot Y
    \end{equation*}

    \(2\Rightarrow 3\): Let \(Y=G\setminus\bigcup_{i=1}^na_i\cdot X\). Then \(Y\) is definable and not generic so
    putting \(a_{n+1}=e\). Then \(G=\bigcup_{i=1}^{n+1}a_i\cdot(X\cup Y)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.2
    1. If \(X,Y\subseteq G\) are not weak generic, then \(X\cup Y\) is not weak generic
    2. If \(p(x)\) is a (partial) weak generic type over \(A\subseteq G\), then \(p(x)\) may be extended to
       a complete weak generic type over \(A\)
    #+END_lemma

    #+BEGIN_proof
    1. Let \(Z\subseteq G\)  be non-generic. \(Y\) is not weak generic so \(Y\cup Z\) is not generic,
       so \(Y\cup Z\cup X\) is not generic
    2. non weak generics form an ideal

       Let \(q(x)=\{\varphi(x)\in L(A):p(x)\cup\{\neg\varphi(x)\}\text{ is not weak generic}\}\). Then \(p\subseteq q\). We shall
       show that \(q\) is a consistent partial type over \(A\). If not, then
       \begin{equation*}
       G\vDash\neg\exists x\bigwedge_{k=1}^n\varphi_k(x)
       \end{equation*}
       for some \(n<\omega\) and \(\varphi_1,\dots,\varphi_n\in q\). By compactness, for each \(k\in\{1,\dots,n\}\) we can find a
       finite set of formulas \(p_k\subseteq p\) s.t. the type \(p_k(x)\cup\{\neg\varphi_k(x)\}\) is not weak generic.
       Let \(\psi(x)=\bigwedge\{p_k(x):1\le k\le n\}\) and note that for every \(k\in\{1,\dots,n\}\) the set \(\psi(G)\cap\neg\varphi_k(G)\)
       is not weak generic. By 1, neither is the union
       \begin{equation*}
       \bigcup_{k=1}^n(\psi(G)\cap\neg\varphi_k(G))=\psi(G)\cap\bigcup_{k=1}^n\neg\varphi_k(G)=\psi(G)\cap G=\psi(G)
       \end{equation*}
       contradicting the fact that \(p(x)\vdash\psi(x)\). Finally we take any \(r(x)\in S(A)\)
       with \(r\supseteq q\) and the proof is complete
    #+END_proof

    We see that (complete) weak generic types exist. By Lemma ref:3.2.2, the set
    \begin{equation*}
    WGEN(A)=\{p\in S(A):p\text{ is weak generic}\}
    \end{equation*}
    is closed and non-empty in \(S(A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.3
    Assume \(G\) is a group and \(A\subseteq G\)
    1. If some weak generic type \(p(x)\in S(G)\) is generic, then all weak generic
       types \(q(x)\in S(A)\) are generic
    2. If for every \(p,q\in WGEN(G)\) there is \(g\in G\) s.t. \(g\cdot p=q\), then all weak generic
       types \(q(x)\in S(A)\) are generic
    3. If there is just one weak generic type in \(S(A)\), then it is generic
    #+END_lemma

    #+BEGIN_proof
    1. Suppose that some weak generic type \(q(x)\in S(A)\) is not generic. Then some definable
       generic set \(X\subseteq G\) may be divided into two non-generic definable sets \(X_1,X_2\).
       Since \(X\) is generic, some left \(G\)-translates \(X'\) of \(X\) belongs to \(p(x)\). Then
       the corresponding translates \(X_1',X_2'\) of \(X_1,X_2\) are also non-generic and one of them
       belongs to \(p(x)\). Hence \(p(x)\) is not generic, a contradiction
    2. If not, then we can find a formula \(\varphi(x)\in L(A)\) which is weak generic but not generic. Note
       that \(\{\neg g\cdot\varphi(x):g\in G\}\) is a partial weak generic type over \(G\): for each \(m<\omega\)
       and \(g_1,\dots,g_m\in G\), the set \(\bigcup_{i=1}^mg_i\cdot\varphi(G)\) is not generic, which implies that the
       set \(\bigcap_{i=1}^m(G\setminus g_i\cdot\varphi(G))\) is weak generic. Extend the type \(\{\neg g\cdot\varphi(x):g\in G\}\) to
       some \(q(x)\in WGEN(G)\). Next extend \(\varphi(x)\) to \(p(x)\in WGEN(G)\). Then \(\forall g\in G\;g\cdot p\neq q\),
       a contradiction
    3. by 2, immediately
    #+END_proof

    By Lemma ref:3.2.3 (1), in the stable case weak generic = generic

    As an example note that if \(G=(G,<,+,\dots)\) is o-minimal, then there are exactly two complete weak
    generic types, corresponding to \(-\infty\) and \(+\infty\), and they are not generic

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume that \(G\prec H\) and \(\varphi(x)\in L(G)\)
    1. If \(\varphi(G)\) is weak generic in \(G\), then \(\varphi(H)\) is weak generic in \(H\)
    2. If \(G\) is \(\aleph_0\)-saturated and \(\varphi(H)\) is weak generic in \(H\), then \(\varphi(G)\) is weak
       generic in \(G\)
    #+END_lemma

    #+BEGIN_proof
    1. There is a non-generic formula \(\psi(x)\in L(G)\) s.t. \(\varphi(G)\cup\psi(G)\) is generic in \(G\),
       therefore \(\psi(H)\) is not generic in \(H\) and \(\varphi(H)\cup\psi(H)\) is generic in \(H\).
       Thus \(\varphi(H)\) is weak generic in \(H\)
    2. There is a formula \(\psi(x)\in L(H)\) s.t. \(\psi(H)\) is not generic in \(H\) and \(\varphi(H)\cup\psi(H)\) is
       generic in \(H\). We have that \(\psi(x)=\psi(x,b)\) where \(b\subset H\). Let \(A\subseteq G\)  be a finite set
       containing all parameters of \(\varphi(x)\). By \(\aleph_0\)-saturation of \(G\), we are able to find
       in \(G\) a tuple \(a\subset G\) s.t. \(\tp(a/A)=\tp(b/A)\). Then \(\psi(x,a)\in L(G)\) has properties
       needed to deduce the weak genericity of the set \(\varphi(G)\) in \(G\). Namely \(\psi(G,a)\) is not
       generic in \(G\) and \(\varphi(G)\cup\psi(G,a)\) is generic in \(G\). If \(\psi(G,a)\) is generic in \(G\),
       then for some \(0<n<\omega\) we have that
       \begin{equation*}
       G\vDash\exists x_1,\dots,x_n\forall y\exists z(\psi(z,a)\wedge\bigvee_{k=1}^ny=x_k\cdot z)
       \end{equation*}
       and the same holds in \(H\) since \(G\prec H\), which would lead to a contradiction
    #+END_proof

    All lemmas in this section remain true if we consider a group \((G,\cdot)\) definable in a first
    order structure \(M\). Then \(G\) is a definable subset of \(M^n\) for some \(n<\omega\) and for
    every \(A\subseteq M\) we define the set \(WGEN(A)\) of complete weak generic types over \(A\) as the
    set
    \begin{equation*}
    \{p\in S_n(A):\forall\varphi(x_1,\dots,x_n)\in p,G\cap\varphi(M^n)\text{ is weak generic in }G\}
    \end{equation*}

** Characterizations of weak genericity
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:3.3.1
    Assume \(G\) is a definable group in an o-minimal structure \(M\) and \(X\) is a definable weak
    generic subset of \(G\). Then \(\dim(X)=\dim(G)\)
    #+END_proposition

    #+BEGIN_proof
    Suppose \(\dim(X)<\dim(G)\). Take a generic set \(A\) and a non-generic set \(B\)
    s.t. \(A=B\cup X\) (where \(A\) and \(B\) are definable subsets of \(G\), apply Lemma ref:3.2.1)
    Choose a finite \(S\subseteq G\) with \(S\cdot A=G\). Then \(G\setminus(S\cdot B)\subseteq S\cdot X\) and
    \begin{equation*}
    \dim(G\setminus(S\cdot B))\le\dim(S\cdot X)=\dim(X)<\dim(G)
    \end{equation*}
    Hence the set \(S\cdot B\) is large in the sense
    #+END_proof

    Assume \(G\) is a group and \(X,Y\subseteq G\). We say that the set \(X\) is *translation disjoint* from
    the set \(Y\) if for some \(a\in G\), \(a\cdot X\cap Y=\emptyset\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.3.2
    Assume \(G\) is a group and \(X\) is a weak generic subset of \(G\). Then for some
    finite \(A\subseteq G\) there is no finite covering of \(X\) by sets that are translation disjoint
    from \(A\cdot X\)
    #+END_lemma

    #+BEGIN_proof
    take \(Y\supseteq X\) generic and \(Y\setminus X\) not generic. We have that \(G=A\cdot Y\) for some
    finite \(A\subseteq G\). We shall prove that \(A\) meets conditions of the lemma.

    Suppose for some \(X_0,\dots,X_{n-1}\subseteq G\) and \(a_0,\dots,a_{n-1}\in G\) we have that
    \begin{equation*}
    X=\bigcup_{i<n}X_i\text{ and }\bigwedge_{i<n}(a_i\cdot X_i)\cap(A\cdot X)=\emptyset
    \end{equation*}
    Then for each \(i<n\), \(a_i\cdot X_i\subseteq G\setminus A\cdot X\subseteq A\cdot(Y\setminus X)\). So for
    each \(i<n\), \(X_i\subseteq a_i^{-1}\cdot A\cdot(Y\setminus X)\), which implies
    that \(X\subseteq\{a_0^{-1},\dots,a_{n-1}^{-1}\}\cdot A\cdot(Y\setminus X)\) and finally
    \begin{equation*}
    G=A\cdot Y=A\cdot(Y\setminus X)\cup A\cdot X\subseteq(A\cup(A\cdot\{a_0^{-1},\dots,a_{n-1}^{-1}\}\cdot A))\cdot(Y\setminus X)
    \end{equation*}
    Then \(G\) is covered by finitely many things
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume \(G\) is a group and \(X\) is a weak generic subset of \(G\). Then the set \(X\cdot X^{-1}\)
    is generic in \(G\)
    #+END_corollary

    #+BEGIN_proof
    Take a finite \(A\subseteq G\) as in Lemma ref:3.3.2. Then for each \(a\in G\), \(a\cdot X\cap A\cdot X\neq\emptyset\), which
    implies that \(a\in A\cdot X\cdot X^{-1}\). So \(G=A\cdot X\cdot X^{-1}\)
    #+END_proof

    From now on, let \((G,<,+,\dots)\) be an o-minimal expansion of an ordered group \((G,<,+)\). Then
    the group \(G\) is commutative, divisible and torsion-free. By \((G^n,+)\) we mean the product of
    groups \((G,+)\times\dots\times(G,+)\) (\(n\) times). The ordering of \(G\) is dense since for
    every \(a,b\in G\) with \(a<b\) we have that \(a<\frac{a+b}{2}<b\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:3.3.4
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n<\omega\)
    and \(\varphi(x_1,\dots,x_n)\in L(G)\). TFAE
    1. \(\varphi(x_1,\dots,x_n)\) is weak generic in \((G^n,+)\)
    2. \(\neg\varphi(x_1,\dots,x_n)\) is not generic in \((G^n,+)\)
    3. the set \(\varphi(G^n)\) contains arbitrarily large \(n\)-dimensional boxes
       \begin{equation*}
       (\forall R>0)(\exists a_1,\dots,a_n\in G)[a_1,a_1+R]\times\dots\times[a_n,a_n+R]\subseteq\varphi(G^n)
       \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    \(3\Rightarrow 2\): suppose there is \(k<\omega\) and \(\la g_1^1,\dots,g_n^1\ra,\dots,\la g_1^k,\dots,g_n^k\ra\in G^n\) we have that
    \begin{equation*}
    G^n=\bigcup_{j=1}^k(\la g_1^j,\dots,g_n^j)+(G^n\setminus\varphi(G^n))
    \end{equation*}
    Put \(M=\max\{\abs{g_i^j}:1\le i\le n,1\le j\le k\}\). Using 3 we are able to find \(a_1,\dots,a_n\in G\) s.t.
    \begin{equation*}
    [a_1-M,a_1+M]\times\dots\times[a_n-M,a_n+M]\subseteq\varphi(G^m)
    \end{equation*}
    Then
    \begin{equation*}
    \la a_1,\dots,a_n\ra\notin\bigcup_{j=1}^k(\la g_1^j,\dots,g^j_n\ra+(G^n\setminus\varphi(G^n)))
    \end{equation*}
    a contradiction

    \(2\Rightarrow 1\): since the set \(G^n=\varphi(G^n)\cup(G^n\setminus\varphi(G^n))\) is generic in \((G^n,+)\) and the
    set \(G^n\setminus\varphi(G^n)\) is not generic

    \(1\Rightarrow 3\): W.L.O.G., \(n\ge 2\). Using Lemma ref:3.2.2 (2) find \(p(x_1,\dots,x_n)\in S_n(G)\) s.t. \(p\)
    is a weak generic type in \((G^n,+)\) and \(\varphi\in p\). Extend \(G\) to a \(\abs{G}^+\)-saturated
    group \(H\succ G\). Take \(\la a_1,\dots,a_n\ra\in H^n\) realizing \(p\) and fix a positive \(R\in G\). We shall
    show that the follwing condition holds
    \begin{equation*}
    (\forall a\in H)(a_n\le a\le a_n+R\Rightarrow\tp(a/Ga_{<n})=\tp(a_n/Ga_{<n}))\tag{\star}
    \end{equation*}

    For the sake of contradiction assume that for some \(a\in[a_n,a_n+R]_H\) the
    types \(\tp(a/Ga_{<n})\) and \(\tp(a_n/Ga_{<n})\) are distinct. By the o-minimality of \(H\), we
    can find \(b\in[a_n,a_n+R]_H\) with \(b\in\dcl(Ga_{<n})\) (dense). Let \(\psi(x_1,\dots,x_{n-1},y)\in L(G)\)
    be s.t. \(H\vDash\psi(a_{<n},b)\wedge\exists!y \psi(a_{<n},y)\). As \(b-R\le a_n\le b\), we have that \(\chi\in p\) where
    \begin{equation*}
    \chi(x_1,\dots,x_n)=\exists!y\psi(x_{<n},y)\wedge\forall y(\psi(a_{<n},y))\to(y-R\le x_n\le y)
    \end{equation*}
    Since \(\chi\in p\), the set \(\chi(G^n)\) is weak generic in \((G^n,+)\)

    We define \(f:G^{n-1}\to G\) as follows. Take \(\la c_1,\dots,c_{n-1}\ra\in G^{n-1}\). If there is \(c_n\in G\)
    s.t. \(G\vDash\chi(c_1,\dots,c_n)\), then there exists just one \(d\in G\) with \(G\vDash\psi(c_1,\dots,c_{n-1},d)\) and we
    put \(f(c_1,\dots,c_{n-1})=d-R\). Otherwise we put \(f(c_1,\dots,c_{n-1})=0\). Then the function \(f\) is
    definable over \(G\) and we consider the following formula over \(G\):
    \begin{equation*}
    \delta(x_1,\dots,x_n)=f(x_1,\dots,x_{n-1})\le x_n\le f(x_1,\dots,x_{n-1})+R
    \end{equation*}
    Since \(\chi(G^n)\subseteq\delta(G^n)\subseteq G^n\), the set \(\delta(G^n)\) is weak generic in \((G^n,+)\). Let \(A\subseteq G^n\) be a
    finite set chosen for \(\delta(G^n)\) as in Lemma ref:3.3.2. Consider an
    arbitrary \(\la h_1,\dots,h_n\ra\in H^{n-1}\). Choose \(M_{h_{<n}}\in G\) s.t.
    \begin{equation*}
    \{\la h_1,\dots,h_n\ra:f(h_{<n})+M_{h_{<n}}\le h_n\le f(h_{<n})+M_{h_{<n}}+R\}
    \cap(A+\delta(H^n))=\emptyset
    \end{equation*}
    If \(\tp(h_{<n}/G)=\tp(h'_{<n}/G)\), then \(M_{h_{<n}}\) is good also for \(h'_{<n}\). By
    compactness, for each \(q(x_1,\dots,x_{n-1})\in S_{n-1}(G)\) we can find a
    formula \(\varphi_q(x_1,\dots,x_{n-1})\in L(G)\) and \(M_q\in G\) s.t. for every \(h_{<n}\in H^{n-1}\) with
    \(H\vDash\varphi_q(h_{<n})\) we have
    \begin{equation*}
    \{\la h_1,\dots,h_n\ra:f(h_{<n})+M_q\le h_n\le f(h_{<n})+M_q+R\}\cap(A+\delta(H^n))=\emptyset
    \end{equation*}
    Again by compactness, \(S_{n-1}(G)=[\varphi_{q_1}]\cup\dots\cup[\varphi_{q_k}]\) for some \(k<\omega\)
    and \(q_1,\dots,q_k\in S_{n-1}(G)\). For \(i\in\{1,\dots,k\}\) put \(X_i=(\varphi_{q_i}(G^{n-1})\times G)\cap\delta(G^n)\)
    and \(e_i=\la 0,\dots,0,M_{q_i}\ra\in G^n\). Then \(\delta(G^n)=X_1\cup\dots\cup X_k\) and for every \(i\in\{1,\dots,k\}\) we have
    that \((e_i+X_i)\cap(A+\delta(G^n))=\emptyset\). This contradicts the choice of \(A\) and finishes the proof of (\(\star\))
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n,k<\omega\)
    and \(\varphi(x_1,\dots,x_n,y_1,\dots,y_k)\in L\)
    1. there is \(\psi_1(y_1,\dots,y_k)\) s.t. for every \(\la a_1,\dots,a_k\ra\in G^k\) we have that \(G\vDash\psi_1(a)\)
       iff \(\varphi(G^n,a)\) is weak generic in \((G^n,+)\)
    2. There is \(\psi_2(y_1,\dots,y_k)\) s.t. for every \(\la a_1,\dots,a_k\ra\in G^k\) we have that \(G\vDash\psi_2(a)\)
       iff \(\varphi(G^n,a)\) is generic in \((G^n,+)\)
    3. there is a natural number \(N\) s.t. for every \varphi-definable \(X\subseteq G^n\) the set \(X\) is generic
       in \((G^n,+)\) iff \(G^n\) may be covered by at most \(N\) left translates of \(X\)
    #+END_corollary

    #+BEGIN_proof
    1. let \(\psi_1(y_1,\dots,y_k)\) be
       \begin{equation*}
       \forall r\exists z_1,\dots,z_n\forall x_1,\dots,x_n((\bigwedge_{i=1}^nz_i\le x_i\wedge x_i\le z_i+r)\to\varphi(x_1,\dots,x_n,y_1,\dots,y_k))
       \end{equation*}
    3. [@3] Assume that \(n=1\). Let \(\psi_2(y_1,\dots,y_k)\) be such as 2. Suppose for every \(N<\omega\) we can
       find \(\la a_1,\dots,a_k\ra\in G^k\) s.t. the set \(\varphi(G,a_1,\dots,a_k)\) is generic in \(G\) but
       not \(N\)-generic. Then the set of formulas
       \begin{equation*}
       \bigcup_{N<\omega}\{\psi_2(y_1,\dots,y_k)\wedge\forall z_1,\dots,z_N\exists t\forall x(\varphi(x,y_1,\dots,y_k)\to\bigwedge_{i=1}^Nt\neq z_i\cdot x)\}
       \end{equation*}
       is a type in variables \(y_1,\dots,y_k\) and has a realization \(\la b_1,\dots,b_k\ra\in H^k\) in
       some \(\aleph_0\)-saturated elementary extension \(H\) of \(G\). Then we reach a contradiction as
       the set \(\varphi(H,b_1,\dots,b_k)\) is simultaneously generic and not generic in \(H\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n<\omega\),
    and \(p(x_1,\dots,x_n)\in S_n(G)\). TFAE
    1. \(p(x_1,\dots,x_n)\) is weak generic in \((G^n,+)\)
    2. \(\la g_1,\dots,g_n\ra+p(x_1,\dots,x_n)=p(x_1,\dots,x_n)\) for every \(\la g_1,\dots,g_n\ra\in  G^n\)
    #+END_corollary

    #+BEGIN_proof
    \(1\Rightarrow 2\): suppose
    \begin{equation*}
    \la g_1,\dots,g_n\ra+p(x_1,\dots,x_n)\neq p(x_1,\dots,x_n)
    \end{equation*}
    for some \(\la g_1,\dots,g_n\ra\in G^n\). Then for some \(\varphi(x_1,\dots,x_n)\in p(x_1,\dots,x_n)\) we have that
    \((\la g_1,\dots,g_n\ra+\varphi(G^n))\cap\varphi(G^n)=\emptyset\). \(\varphi(G^n)\) is weak generic in \((G^n,+)\) and hence contains
    arbitrarily large boxes. Take any \(R>\max(\abs{g_1},\dots,\abs{g_n})\) and choose \(a_1,\dots,a_n\in G\)
    s.t.
    \begin{equation*}
    B=[a_1,a_1+R]\times\dots\times[a_n,a_n+R]\subseteq\varphi(G^n)
    \end{equation*}
    we obtain
    \begin{equation*}
    \emptyset\neq(\la g_1,\dots,g_n\ra+B)\cap B\subseteq(\la g_1,\dots,g_n\ra+\varphi(G^n))\cap\varphi(G^n)=\emptyset
    \end{equation*}
    a contradiction

    \(2\Rightarrow 1\): we shall prove a more general fact. Namely if \(G\) is a group and \(p(x)\in S(G)\) is
    s.t. for every \(g\in G\) we have that \(g\cdot p=p\), then \(p\) is weak generic in \(G\)

    If not, then we can find a formula \(\varphi(x)\in p(x)\) which is not weak generic in \(G\).
    Then \(\neg\varphi(x)\) is generic in \(G\) so there are \(m<\omega\) and \(g_1,\dots,g_m\in G\)
    s.t \(G=\bigcup_{i=1}^mg_i(G\setminus\varphi(G))\). Thus \(\bigcap_{i=1}^mg_i\cdot\varphi(G)=\emptyset\), which contradicts the fact that the
    formulas \(g_1\cdot\varphi,\dots,g_m\cdot\varphi\) belong to the consistent type \(p(x)\)
    #+END_proof

** Stationary
    In this section we assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered
    group \((G,<,+)\)

    Recall that in stable group all weak generic types are generic. <<Problem2>> Moreover, all of
    them are stationary over any model \(M\). This means that every (weak) generic type \(p\in S(M)\)
    has a unique extension to a (weak) generic type \(q\in S(A)\) for each \(A\supseteq M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call a weak generic type \(p\) over a set \(A\) *stationary* if for every \(B\supseteq A\) the
    type \(p\) has just one extension to a complete weak generic type over \(B\)
    #+END_definition

    In general weak generic types do not need to be stationary

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    we shall prove that the types \(p_1(x)=\{x<a:a\in G\}\) and \(p_2(x)=\{x>a:a\in G\}\) are the only two
    weak generic types in \((G,+)\) complete over \(G\) and that both of them are stationary

    By the o-minimality of \((G,<,+,\dots)\), every definable subset of \(G\) is a union of finitely
    many points and intervals. For every \(a,b\in G\) the interval \((a,b)\) is not weak generic
    in \((G,+)\) by Lemma ref:3.2.1 (2). Thus no type in \(S_1(G)\) but \(p_1\) and \(p_2\) is weak
    generic in \((G,+)\)

    On the other hand, all intervals of the form \((-\infty,a)\) or \((b,+\infty)\) are weak generic
    in \((G,+)\) since their complements in \(G\) are not generic in \((G,+)\).  This gives us the
    weak genericity of the types \(p_1\) and \(p_2\)

    If \(H\) is any elementary extension of \(G\), then there are also two complete (over \(H\))
    weak generic types in \((H,+)\). This means that \(p_1\) and \(p_2\) are stationary
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call an o-minimal structure \((M,<,\dots)\) *stationary* if for every elementary extension \(N\)
    of \(M\) and \(N\)-definable function \(g:N\to N\) there exists an \(M\)-definable
    function \(f:N\to N\) s.t. \(g(x)\le f(x)\) for all sufficiently large \(x\in N\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:3.4.4
    Assume \((M,<,\dots)\) is a stationary o-minimal structure and \(N\succ M\). For every \(N\)-definable
    map \(g:N\to N\) with \(\lim_{x\to+\infty}g(x)=+\infty\)  we can find an \(M\)-definable map \(f:N\to N\)
    s.t. \(\lim_{x\to+\infty}f(x)=+\infty\) and \(f(x)\le g(x)\) for all sufficiently large \(x\in N\)
    #+END_theorem


    #+BEGIN_proof
    First of all, assume that \(g\) is a bijection. Then \(g^{-1}\) exists and by the stationary
    of \((M,<,\dots)\) we can find an \(M\)-definable function \(f:N\to N\) s.t. ultimately \(g^{-1}\le f\).
    We have that \(\lim_{x\to+\infty}g^{-1}(x)=+\infty\), which implies that \(\lim_{x\to+\infty}f(x)=+\infty\). Since \(f\)
    is \(M\)-definable, we can choose \(a\in M\) s.t. \(f\) is strictly increasing on \((a,+\infty)\)
    (monotonicity theorem). We define a function \(f_1:N\to N\) as follows
    \begin{equation*}
    f_1(x)=
    \begin{cases}
    f(x)&x>a\\
    f(a)+x-a&x\le a
    \end{cases}
    \end{equation*}
    Then \(f_1\) is an \(M\)-definable bijection, hence \(f_1^{-1}\) exists and also
    is \(M\)-definable. Moreover, \(\lim_{x\to+\infty}f_1^{-1}(x)=+\infty\) and ultimately \(f^{-1}_1\le g\)
    so \(f_1^{-1}\) has the desired properties

    If \(g\) is not a bijection, then proceeding as above we can find an \(N\)-definable
    bijection \(g_1:N\to N\) s.t. ultimately \(g_1=g\)
    #+END_proof

    By the o-minimality of \((G,<,+,\dots)\), every definable subset of the set \(G\times G\) is a union of
    finitely many cells of dimension 0,1,2. By Proposition ref:3.3.1, we are interested only in
    cells of dimension 2. They are of the form
    \begin{equation*}
    C_{a,b}^{f,g}=\{\la x,y\ra\in G\times G:a<x<b\wedge f(x)<y<g(x)\}
    \end{equation*}
    where \(\{-\infty\}\cup G\ni a<b\in G\cup\{\infty\}\) and \(f,g:(a,b\to G\cup\{-\infty,\infty\}\) are definable maps s.t. \(f(x)<g(x)\)
    for each \(x\in(a,b)\). If \(a,b\in G\), then the cell \(C_{a,b}^{f,g}\) is not weak generic
    in \((G,+)\times(G,+)\) by Theorem ref:3.3.4





* Problems
    | [[Problem1]] | [[Problem2]]|
    |          |
