#+title: Mooncake: A KVCache-centric Disaggregated Architecture for LLM Serving

#+AUTHOR: 
#+LATEX_HEADER: \input{/Users/wu/notes/preamble.tex}
#+EXPORT_FILE_NAME: ../latex/papers/mooncake_kvcache_centric_disaggregated_architecture_for_llm_serving.tex
#+LATEX_HEADER: \graphicspath{{../../paper/}}
#+OPTIONS: toc:nil
#+STARTUP: shrink


* Introduction
** Motivation
        The optimization goal is to maximize overall effective throughput, which directly impacts revenue,
        while the  reflect varying levels of SLOs. These SLOs typically involve meeting latency-related
        requirements, mainly the time to first token (TTFT) and the time between tokens (TBT).

        Building on this idea, we found that the scheduling of KVCache is central to LLM serving scheduling.
        To improve overall throughput, there are typically two general approaches: 1) reuse KVCache as much as
        possible to reduce the required computation resources; and 2) maximize the number of tokens in each
        batch to improve the Model FLOPs Utilization (MFU). However, reusing KVCache from a remote location
        will prolong the TTFT, and a large batch size will lead to a larger TBT.

* Problems


* References
<<bibliographystyle link>>
bibliographystyle:alpha

\bibliography{/Users/wu/notes/notes/references.bib}

