#+title: On \(f\)-Generic Types in Presburger Arithmetic

#+EXPORT_FILE_NAME: ../latex/paper/on f-generic types in presburger arithmetic.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Introduction and Preliminaries
** Introduction
    Marcin Petrykowski gave a nice description of \(f\)-generic types in groups \((R,+)\times(R,+)\)
    with \((R,<,+,\cdot)\) with \((R,<,+,\cdot)\) an o-minimal expansion of real closed field. An analogs
    question is: What are the \(f\)-generic types of \(G^n\), the product of \(n\) copies of ordered
    additive groups \((\Z,+,<)\) of integers.

    Let \(M\) be an elementary extension of \((\Z,+,<,0)\), \(\M\succ M\) a monster model. \(G\) denotes
    the additive group \((\M,+)\), \(S_G(M)\) the space of complete types over \(M\) extending the
    formula '\(x\in G\)'. \(G^0\) is the definable connected component of \(G\). Namely, \(G^0\) is the
    intersection of all definable subgroups of \(G\) with finite index.

    Let \(L_n\) denote the space of homogeneous \(n\)-ary \(\Q\)-linear functions. For \(f,g\in L_n\)
    and \(\alpha,\beta\in\M^n\) s.t. \(\alpha\in\dom(f)\) and \(\beta\in\dom(g)\), by \(f(\alpha)\ll_Mg(\beta)\) we mean that for
    all \(a,b\in M\) and \(k,l\in\N^+\), \(kf(\alpha)+a<lg(\beta)+b\). By \(f(\alpha)\sim_Mg(\beta)\) we mean that
    neither \(f(\alpha)\ll_Mg(\beta)\) nor \(g(\beta)\ll_Mf(\alpha)\). Let \(f_0,\dots,f_m\in L_n\), we
    say \(0\ll_Mf_1(\alpha)\ll_M\dots\ll_Mf_m(\alpha)\) is a maximal positive chain of \alpha over \(M\) if for any \(g\in L_n\)
    with \(g(\alpha)>0\), neither \(f_m(\alpha)\ll_Mg(\alpha)\) nor \(g(\alpha)\ll_Mf_1(\alpha)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(M\succ\Z\), \(\alpha=(\alpha_1,\dots,\alpha_n)\in(G^n)^0\). Then there exists a finite subset \(\{f_0,\dots,f_m\}\subset L_n\)
    s.t. \(f_0(\alpha)=0\ll_Mf_1(\alpha)\ll_M\dots\ll_Mf_m(\alpha)\) is the maximal positive chain of \alpha over \(M\). If \alpha
    realizes an \(f\)-generic type \(p\in S_{G^n}(M)\) then for
    every \(\beta\in G^0\), \(p=\tp(\alpha,\beta/M)\in S_{G^{n+1}}(M)\) is an \(f\)-generic type iff one of the
    following holds:
    1. \(f_m(\alpha)\ll_M\beta\) or \(\beta\ll_M-f_m(\beta)\)
    2. there is \(i\) with \(0\le i<m\) and \(g\in L_n\) s.t. \(f_i(\alpha)\ll_M\epsilon(\beta-g(\alpha))\ll_Mf_{i+1}(\alpha)\)
       where \(\epsilon=\pm 1\)
    3. there is \(i\) with \(1\le i\le m\) and \(g\in L_n\) s.t. for all \(h\in L_n\) with \(h(\alpha)\sim_Mf_i(\alpha)\)
       there is an irrational number \(r_h\in\R\setminus\Q\) s.t. \(q_1h(\alpha)<\beta-g(\alpha)<q_2h(\alpha)\) for all \(q_1,q_2\in\Q\)
       with \(q_1<r_h<q_2\)
    #+END_theorem
** Preliminaries
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. A definable subset \(X\subseteq G\) is  *\(f\)-generic* if for some/any model \(M\) over which \(X\) is
       defined and any \(g\in G\), \(gX\) does not divide over \(M\). Namely, for
       any \(M\)-indiscernible sequence \((g_i:i<\omega)\) with \(g=g_0\), \(\{g_iX:i<\omega\}\)  is consistent.
    #+END_definition

    #+BEGIN_remark
    The class of all non-weakly generic formulas forms an ideal. So any weakly generic
    type \(p\in S_G(M)\) has a global extension \(\barp\in S_G(\M)\) which is weakly generic.
    #+END_remark

    \(T\) is said to be (or have) NIP if for any indiscernible sequence \((b_i:i<\omega)\)
    formula \(\psi(x,y)\) and \(a\in\M\), there is an eventual truth value of \(\psi(a,b_i)\) as \(i\to\infty\).

    A type definable over a subgroup \(H\le G\) has bounded index
    if \(\abs{G/H}<2^{\abs{T}+\abs{A}}\). For groups definbale

    We call \(G^{00}\) the type-definable connected component of \(G\).
