#+title: On Minimal Flows of Commutative \(p\)-adic Groups

#+AUTHOR: Yao & Zhang

#+EXPORT_FILE_NAME: ../latex/paper/paper.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \DeclareMathOperator{\ext}{\text{ext}}
#+LATEX_HEADER: \makeindex

* Introduction
** Notation and conventions
    A type \(p\in S_G(M)\) is *almost periodic* if the closure of its \(G(M)\)-orbit is a minimal
    subflow of \(S_G(M)\).

    A group \(G\) has finitely satisfiable generics (fsg) or definable \(f\)-generics (dfg) if there
    is a global type \(p\) on \(G\) and a small model \(M\) s.t. every left translate of \(p\) is
    finitely satisfiable in \(M\) or definable over \(M\), respectively.
** Shelah expansion

    By an externally definable set in \(M\) we mean a subset of \(M^n\) of the form \(\phi(N,b)\cap M^n\)
    where \(\phi(x,y)\) is an \(L\)-formula, \(N\succ M\) and \(b\in N^k\) with some \(n,k\in\N\). The *Shelah
    expansion* \(M^{\ext}\) of \(M\) is the expansion of \(M\) obtained by adding predicates for all
    externally definable set s in \(M\). We denote the language of \(M^{\ext}\) by \(L_M^{\ext}\) and the
    theory of \(M^{\ext}\) by \(T_M^{\ext}\). Let \(G\) be a group definable over \(M\). We denote the
    collection of quantifier-free types over \(M^{\ext}\) which concentrate on \(G\) by \(S_{G,\ext}(M)\).
    The space \(S_{G,\ext}(M)\) is naturally homeomorphic to the space \(S_{G,M}(\M)\) of global types
    concentrating on \(G\) which are finitely satisfiable in \(M\), via the map
    \begin{equation*}
    S_{G,M}(\M)\ni p\mapsto\{\psi(M)\mid \psi\in p\}\in S_{G,\ext}(M)
    \end{equation*}


** Definable topological dynamics
    Let \(G\) be a topological group, by a *\(G\)-flow* we mean an action \(G\times X\to X\) of \(G\)
    on a compact Hausdorff topological space \(X\) by homeomorphism, and denote it by \((G,X)\). We
    often assume that \(X\) has dense \(G\)-orbit.

    A *subflow* of \(X\) is a closed \(G\)-invariant subset of \(X\). Minimal subflows of \(X\) always
    exist by Zorn's lemma. A point \(x\in X\) is *almost periodic* if \(\cl(G\cdot x)\), the closure
    of it s \(G\)-orbit, is a minimal subflow of \(X\) or, equivalently, if \(x\) is in some minimal
    subflow of \(X\). We denote the space of all almost periodic points in \(X\) by \(AP(X)\), which
    is also the union of all minimal subflows.

    Given a \(G\)-flow \((G,X)\), its *enveloping semigroup* \(E(X)\) is the closure in the
    space \(X^X\) (with the product topology) of the set of maps \(\pi_g:X\to X\) for \(g\in G\),
    where \(\pi_g(x)=g\cdot x\), equipped with the composition (which is continuous on the left). So
    any \(e\in E(X)\) is a map from \(X\) to \(X\).

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(X\) be a \(G\)-flow. Then
    1. \(E(X)\) is also a \(G\)-flow and \(E(E(X))\cong E(X)\) as \(G\)-flows
    2. For any \(x\in X\), the closure of its \(G\)-orbit is exactly \(E(X)(x)\). Particularly, for
       any \(f\in E(X)\), \(E(X)\circ f\) is the closure of \(G\cdot f\).
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(X\) be a \(G\)-flow. Then \(AP(E(X))\) is a bi-ideal of \(E(X)\)
    #+END_fact

    #+BEGIN_proof
    For each \(f\in AP(E(X))\), \(E(X)\circ f\) is a minimal flow,
    so \(E(X)\circ f\subseteq AP(E(X))\), and thus \(AP(E(X))\) is a left ideal.

    Let \(f\in AP(E(X))\) and \(g\in E(X)\). It suffices to show that \(f\circ g\) is almost
    periodic.
    \begin{equation*}
    \cl(G\cdot(f\circ g))=E(X)\circ(f\circ g)=(E(X)\circ f)\circ g
    \end{equation*}
    For any \(h\in (E(X)\circ f)\), we have that \(E(X)\circ h=E(X)\circ f\) since \(E(X)\circ f\)
    is minimal. So \(\cl(G\cdot(h\circ g))=\cl(G\cdot(f\circ g))\). We conclude
    that \(\cl(G\cdot(f\circ g))\) is minimal since \(\cl(G\cdot h')=\cl(G\cdot(f\circ g))\) for
    each \(h'\in\cl(G\cdot(f\circ g))\), and hence \(f\circ g\) is almost periodic as required

    #+END_proof

    In the model theoretic context, we consider a group \(G\) definable over \(M\) and the action
    of \(G(M)\) on its type space \(S_G(M)\) as \(gp=\tp(ga/M)\) where \(g\in G(M)\) and \(a\)
    realizes \(p\). It is easy to see that \(S_G(M)\) is a \(G(M)\)-flow with a dense
    orbit \(\{\tp(g/M)\mid g\in G(M)\}\).

    Take a monster model \(\M\) and identify \(G\) with \(G(\M)\). We call a formula \(\varphi(x)\)
    with parameters in \(\M\) a *\(G\)-formula* if \(\varphi(\M)\) is a definable subset of \(G\). A
    partial type \(r\) is called a *\(G\)-type* if every formula in \(r\) is a \(G\)-formula. Suppose
    that \(\varphi(x)\) is a \(G\)-formula and \(g\in G\), then the left translate \(g\varphi(x)\)
    is defined to be \(\varphi(g^{-1}x)\). It is easy to check that \((g\varphi)(\M)=g\varphi(\M)\).
    For \(p\in S_G(M)\), \(gp=\{g\varphi(x)\mid \varphi\in p\}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. A definable subset \(X\subseteq G\) is (left) generic if finitely many left translates
       of \(X\) cover \(G\). Namely, there are \(g_1,\dots,g_n\in G\) s.t. \(\bigcup_{i=1}^ng_iX=G\)
    2. A definable subset \(X\subseteq G\) is weak generic if there is a non-generic definable
       subset \(Y\) s.t. \(X\cup Y\) is generic
    3. A \(G\)-formula \(\varphi(x)\) is generic (weak generic) if the definable set \(\varphi(\M)\)
       is generic (resp. weakly generic)
    4. A (partial) \(G\)-type \(p\) is generic (weak generic) if every formula in \(p\) is generic
       (resp. weakly generic)
    #+END_definition

    Let \(AP(S_G(M))\subseteq S_G(M)\) be the space of almost periodic
    types, \(WG(S_G(M))\subseteq S_G(M)\) the space of weakly generic types,
    and \(Gen(S_G(M))\subseteq S_G(M)\) the space of generic types.
    Then \(WG(S_G(M))=\cl(AP(S_G(M)))\).
    Moreover, if \(Gen(S_G(M))\neq\emptyset\), then \(WG(S_G(M))=Gen(S_G(M))\) is the unique minimal subflow
    of \(S_G(M)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    The enveloping semigroup \(E(S_{G,\ext}(M))\) of \(S_{G,\ext}(M)\) is isomorphic to \((S_{G,M}(\M),*)\)
    where \(*\) is defined as following: for any \(p,q\in S_{G,M}(\M)\), \(p*q=\tp(b\cdot c/\M)\) with \(b\)
    realizes \(p\) and \(c\) realizes \(q\), and \(\tp(b/\M,c)\) is finitely satisfiable in \(M\)
    #+END_fact


** NIP, definable amenability, and connected components
    Recall that \(T\) has NIP, which means that, for any indiscernible sequence \((b_i:i<\omega)\),
    formula \(\phi(x,y)\), and \(a\in\M\), there is an eventual truth value of \(\phi(a,b_i)\)

    Let \(G=G(\M)\) be a definable group. We say that \(H\) has bounded index
    if \(\abs{G/H}<2^{\abs{T}+\abs{A}}\). For groups definable in NIP structures, the smallest
    type-definable subgroup of bounded index exists, which is hte intersection of all type-definable
    subgroups of bounded index, we write it as \(G^{00}\), and call it the *type-definable connected
    component*. Another model invariant is \(G^0\), called the *definable-connected component*
    of \(G\), which is the intersection of all definable subgroups of \(G\) of finite index.
    Clearly \(G^{00}\le G^0\)

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    If \(M\vDash T\) and \(G\) is definable over \(M\), then \(G^{00}\) is the same no matter computed
    in \(T\) or \(T_M^{\ext}\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(G_1\) and \(G_2\) be definable groups and \(G=G_1\times G_2\). Then \(G^{00}=G_1^{00}\times G_2^{00}\). Here
    we identify \(G_1\) with \(G_1\times\{1_{G_2}\}\) and \(G_2\) with \(\{1_{G_1}\}\times G_2\), subgroups of \(G\)
    #+END_fact

    #+BEGIN_proof
    Because \([G_1\times G_2:G_1^{00}\times G_2^{00}]=[G_1:G_1^{00}][G_2:G_2^{00}]\) is bounded, we
    have that \(G^{00}\le G_1^{00}\times G_2^{00}\). For \(i=1,2\),
    since \(G_i/(G_i\cap G^{00})\cong(G^{00}G_i)/G^{00}\le G/G^{00}\), \(G_1\cap G^{00}\) is a type
    definable subgroup of \(G\), with bounded index, we see that \(G_i^{00}\le G_i\cap G^{00}\), and
    thus \(G_1^{00}\times G_2^{00}\le G^{00}\)
    #+END_proof


** Strongly \texorpdfstring{\(f\)}{f}-generics, definable \texorpdfstring{\(f\)}{f}, and finitely satisfiable generics
    Let \(\phi(x,y)\) be a formula. A formula \(\phi(x,b)\) *divides* over a set \(A\) if there is an
    infinite \(A\)-indiscernible sequence \((b=b_0,b_1,b_2,\dots)\)
    s.t. \(\{\phi(x,b_i)\mid i<\omega\}\) is inconsistent. A type \(p\in S(B)\) divides
    over \(A\subseteq B\) if there is a formula \(\phi\in p\) divides over \(A\). Since \(T\) has
    NIP, a global type \(p\in S(\M)\) does not divide over \(M\) iff \(p\)
    is \(\Aut(\M/M)\)-invariant

    Let \(G=G(\M)\) be a definable group and \(p\in S_G(\M)\) a global type on \(G\). We call a
    global type \(p\in S_G(\M)\) *strongly \(f\)-generic over \(M\)* if \(gp\) does not divide
    over \(M\) for each \(g\in G\). We call \(p\in S_G(\M)\) a strongly \(f\)-generic type if it is
    strongly \(f\)-generic over some small submodel.

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(G\) be a definably amenable group and \(p\) be a global \(G\)-type. Then
    1. \(p\) is weakly generic iff it is \(G^{00}\)-invariant iff it has a bounded \(G\)-orbit
    2. \(p\) is strongly \(f\)-generic over \(m\) iff it is weakly generic and \(M\)-invariant (or
       does not divide over \(M\))
    #+END_fact

    Among the strongly \(f\)-generics \(p\in S_G(\M)\), there are two extreme cases:
    1. There is a small submodel \(M\) s.t. every left \(G\)-translate of \(p\) is finitely
       satisfiable in \(M\), and we call such types the *fsg* (finitely satisfiable generic) types
       on \(G\) over \(M\)
    2. There is a small submodel \(M\) s.t. every left \(G\)-translate of \(p\) is definable
       over \(M\), we call such types the *dfg* (definable \(f\)-generic) types on \(G\) over \(M\)


    A definable group \(G\) is called fsg or dfg if it has a global fsg or dfg type, respectively.
    Both fsg and dfg groups are definably amenable.

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(G\) be an \(\emptyset\)-definable fsg group witnessed by a fsg type \(p\in S_G(\M)\). Then
    1. \(p\) is both left and right generic. So the space \(Gen(S_G(\M))\) of global generic types
       is the unique minimal subflow of \(S_G(\M)\)
    2. Any left (right) translate of \(q\in Gen(S_M(\M))\) is finitely satisfiable in any small
       submodel of \(\M\)
    3. For any \(N\prec\M\), every generic type \(q\in S_G(N)\) has a unique global generic extension
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(C\) be an \(\emptyset\)-definable fsg group and \(M\prec\M\)
    1. \(C\) also has fsg when we compute it in \(T_M^{\ext}\)
    2. \(q\mapsto\{\psi(M)\mid \psi\in q\}\) is a bijection between \(Gen(S_C(\M))\) and \(Gen(S_C(M^{\ext}))\)
    #+END_fact



** Commutative Definable groups over \(\Q_p\)
    Let \(p\) be a prime and \(\Q_p\) be the field of \(p\)-adic numbers. We call the complete
    theory of \(\Q_p\), in the language of rings, the theory of *\(p\)-adically closed fields*,
    written \(p\)CF. \(p\)CF has quantifier elimination in the language of rings together with new
    predicates \(P_n(x)\) for the \(n\)-th powers for each \(n\in\N^{>0}\). \(p\)CF has NIP.

    For any \(M\vDash\pCF\), \(\Gamma_M\) denote the value group, which is an elementary extension
    of \((\Z,+,<)\). If \(A\subseteq\Gamma_M\), we call \(\alpha\in\Gamma_M\) is *unbounded
    over* \(A\) if either \(\alpha<\dcl(A)\) or \(\alpha>\dcl(A)\). The relation \(v(x)\le v(y)\)
    is \(\emptyset\)-definable in the language of rings. The \(p\)-adic field \(\Q_p\) is a locally
    compact topological field, with basis given by the sets
    \begin{equation*}
    B(a,n)=\{x\in\Q_p\mid v(x-a)\ge n\}
    \end{equation*}
    for \(a\in\Q_p\) and \(n\in\Z\). We now assume that \(T=\pCF\) is the theory of \(\Q_p\) in the
    language of rings and \(\M\) a monster model of \(\pCF\)

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(G\) be an abelian group definable over \(\Q_p\). Then \(G^{00}=G^0\) and there is a
    definable short exact seuquence
    \begin{equation*}
    1\to H\to G\to_\pi C\to 1
    \end{equation*}
    with \(H\) a \(\Q_p\)-definable dfg group, \(C\) a \(\Q_p\)-definable fsg group, and \(\pi\)
    a \(\Q_p\) -definable homomorphism.
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(C\) be a group definable over \(\Q_p\)
    1. \(C\) is definably compact iff \(C\) has fsg
    2. If \(C\) is definably compact, then \(C^{00}=C^0\) coincides with \(\ker(st)\), and \(st\)
       induces a homeomorphism between \(C/C^0\) (with logic topology) and the \(p\)-adic analytic
       group \(C(\Q_p)\)
    #+END_fact

    We denote the additive group \((\M,+)\) by \(\G_a\) and the multiplicative
    group \((\M^*,\times)\) by \(\G_m\). We denote the direct product of \(n\) copies of \(\G_a\)
    by \(\G_a^n\). We call a \(p\)-adic algebraic group \(G\) *trigonalizable* over \(\Q_p\), if there
    is a normal sequence
    \begin{equation*}
    \{1_G\}=G_0\lhd\dots\lhd G_i\lhd G_{i+1}\lhd\dots\lhd G_n=G
    \end{equation*}
    s.t. each \(G_{i+1}/G_i\) is (quantifier free) definably isomorphic to \(\G_a\) or \(\G_m\)
    over \(\Q_p\)

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(H\) be a dfg group definable over \(\Q_p\). Then \(H\) is virtually a connected algebraic
    group which is trigonalizable over \(\Q_p\)
    #+END_fact

* Stationarity and badness
    Work in \(\pCF\)
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A \(\Q_p\)-definable group \(G\) is *stationary* if every weakly generic type \(p\in S_G(\Q_p)\)
    has just one global weakly generic extension.
    #+END_definition

    Suppose \(G\) is a \(\Q_p\)-definable group admitting a \(\Q_p\)-definable short exact sequence
    \begin{equation*}
    1\to H\to G\to_\pi C\to 1
    \end{equation*}
    where \(C\) is a fsg group and \(H\) is a dfg group:
    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    1. \(G\) is stationary iff \(H\) is stationary
    2. (Local case) If \(G\) is stationary, then \(AP(S_G(M^{\ext}))=WGen(S_G(M^{\ext}))\) for any
       model \(M\succ\Q_p\)
    3. (Gloabl case) if \(G\) is stationary, then \(AP(S_G(\M))=WGen(S_G(\M))\)
    #+END_fact

    For a dfg group definable over \(\Q_p\), we have that
    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(H\) be a dfg group definable over \(\Q_P\), then TFAE
    1. \(H\) is stationary
    2. \(H\) has boundedly many global weakly generic types
    3. There is a small model \(M\) s.t. every global weakly generic type is \(M\)-definable
    4. Every global weakly generic type is \(\Q_P\)-definable
    #+END_fact

    For definable groups \(H<G\) with \([G:H]\) finite, we have that \(H^{00}=G^{00}\) and any
    weakly generic type on \(G\) is indeed on \(H\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(G\) and \(A\) be groups definable over a model \(M\) and \(\pi:G\to A\) a surjective
    morphism definable over \(M\). If \(p\in S_A(M)\) and \(q=\pi(p)\), then \(\pi^{-1}(q)=\ker(\pi)p\)
    #+END_lemma

    #+BEGIN_proof
    Let \(r\in\pi^{-1}(q)\). Suppose that \(a\vDash q\). Let \(f\) be a definable section of \pi,
    then we have that \(a\in\ker(\pi)f(\pi(a))\), which means that \(r\in\ker(\pi)f(q)\),
    so \(\pi^{-1}(q)\subseteq\ker(\pi)f(q)\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(\pi:G\to A\) be a definable surjective morphism of definable groups. Then \(\pi(G^{00})=A^{00}\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(\pi:G\to A\) be a \(\Q_p\)-definable surjective morphism of \(\Q_p\)-definable groups.
    Suppose that \(N\) is sufficiently saturated small submodel of \(\M\) and \(p\in S_G(\M)\). Then
    we have
    1. If \(p\) is \(G^{00}(N)\)-invariant, then \(\pi(p)\) is \(A^{00}(N)\)-invariant
    2. If \(\pi(p)\) is \(A^{00}(N)\)-invariant, then \(G^{00}(N)p\subseteq\ker(\pi)p\)
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(G\) and \(A\) be definably amenable groups definable over \(\Q_p\) and \(\pi:G\to A\)
    a \(\Q_p\)-definable surjective morphism with a finite kernel. Let \(M\succ\Q_p\).
    Then \(p\in S_G(M)\) is weakly generic iff \(\pi(p)\in S_A(M)\) is weakly generic.
    #+END_lemma

    #+BEGIN_proof
    Since every weakly generic type over \(M\) extends to a global weakly generic type, it suffices
    to show that \(p\in S_G(\M)\) is weakly generic iff \(\pi(p)\in S_A(\M)\) is weakly generic.

    #+END_proof

    #+BEGIN_remark
    Suppose that \(G\) is virtually a finite index subgroup of \(A\), witnessed by
    a \(\Q_p\)-definable finite index subgroup \(X\subseteq G\) and a \(\Q_p\)-definable
    morphism \(f:X\to A\). We will always assume that \(\ker(f)\subseteq G^0(\Q)\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(G\) and \(A\) be definably amenable groups, both definable over \(\Q_p\). If \(G\) is
    virtually a finite index subgroup of \(A\) and \(G^0=G^{00}\), then \(G\) is stationary
    iff \(A\) is stationary
    #+END_lemma

    Now let \(H\) be a commutative dfg group over \(\Q_p\), then it is virtually a finite index
    subgroup of \(\G_a^s\times\G_m^t\) for some \(s,t\in\N\). By Lemma ref:2.9, to see the
    stationarity of \(H\), it is reasonable to assume that \(H=\G_a^s\times\G_m^t\) since \(H^0=H^{00}\).

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Let \(H\) be either \(\G_a\) or \(\G_m\). Let \(\Sigma_0(x)\) be the partial
    type \(\{v(x)>\gamma\mid\gamma\in\Gamma_{\M}\}\) and \(\Sigma_\infty(x)\) be the partial
    type \(\{v(x)<\gamma\mid \gamma\in\Gamma_{\M}\}\), then
    1. Every global weakly generic type on \(H\) is \(\emptyset\)-definable
    2. If \(H=\G_a\), then \(H^{00}=H^{0}=H\), and \(p\in S_H(\M)\) is weakly generic iff it is
       consistent with the partial type \(\Sigma_\infty(x)\)
    3. If \(H=\G_m\), then \(H^{00}=H^{0}=\bigcap_{n\in\N^+}P_n(\G_m)\), and \(p\in S_H(\M)\) is
       weakly generic iff it is either consistent with the partial type \(\Sigma_\infty(x)\), or
       consistent with the partial type \(\Sigma_0(x)\)
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    Any global weak generic type on \(\G_m^t\) is \(\emptyset\)-definable for each \(t\in\N^+\).
    Moreover, a global type \(\tp(a_1,\dots,a_t/\M)\) on \(\G^t_m\) is weakly generic
    iff \(k_1v(a_1)+\dots+k_tv(a_t)\) is unbounded over \(\Gamma_{\M}\) for
    all \(k_1,\dots,k_t\in\Z\) which are not all zero
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    \(\tp(a_1,\dots,a_t/\M)\) is a weakly generic type on \(\G_m^t\) iff
    each \(\tp(a_j/\M,a_i:i<j)\) is \(\G_m^0\)-invariant (\(\G^0_m=\G_m^0(\M)\)). Hence \(\G_m^t\)
    is stationary for each \(t\in\N^+\)
    #+END_lemma

    #+BEGIN_proof
    Suppose that \(\tp(a_1,\dots,a_t/\M)\) is weakly generic, then it is \((\G_m^0)^t\)-invariant,
    so each \(\tp(a_j/\M,a_i:i<j)\) is \(\G_m^0\)-invariant.

    We show the other direction by induction on \(t\in\N^+\). Assume that this lemma holds
    for \(t-1\). Then we have that \(\tp(a_1,\dots,a_{t-1}/\M)\) is a weakly generic type
    on \(\G_m^{t-1}\). Assume for a contradiction that \(\tp(a_1,\dots,a_t/\M)\) is not weakly
    generic, then there are \(k_1,\dots,k_t\in\Z\) which are not all zero
    s.t. \(k_1v(a_1)+\dots+k_tv(a_t)\) is bounded over \(\Gamma_{\M}\).
    Take \(\alpha<\beta\in\Gamma_{\M}\) s.t. \(\alpha<k_1(a_1)+\dots+k_tv(a_t)<\beta\).
    If \(k_t\neq 0\), then take any \(b\in\G_m^0\) s.t. \(k_tv(b)<\alpha-\beta\), we have that
    \begin{equation*}
    k_1v(a_1)+\dots+k_tv(ba_t)=k_1v(a_1)+\dots+k_tv(a_t)+k_tv(b)<\beta+\alpha-\beta=\alpha
    \end{equation*}
    which is also a contradiction as \(\tp(a_t/\M,a_1,\dots,a_{t-1})\) is \(\G_m^0\)-invariant
    #+END_proof
