#+TITLE: Topological Dynamics And Definable Group Actions
#+AUTHOR: Ludomir Newelski

#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Introduction
    Assume \(G\) is a group. By a *\(G\)-flow* we mean a compact Hausdorff topological space \(X\) together with
    a left action of \(G\) on \(X\) by homeomorphisms. A non-empty closed subset \(Y\) of \(X\) is a
    *subflow* of \(X\) if \(Y\) is closed under the action of \(G\). A flow is *minimal* if it has no
    proper subflow. A flow is *point-transitive*, if it contains a dense \(G\)-orbit.

    Topological dynamics is concerned with the orbits of the actions of \(G\) on
    various \(G\)-flows, and particularly with minimal flows

    Assume \(X\) is a \(G\)-flow. For \(x\in X\) let \(o(x)\) denote the orbit of \(X\). Then the
    closure \(\cl(o(x))\) is a subflow of \(X\) and for any orbit \(\calo\subseteq X\) and every \(x\in\cl(\calo)\) we
    have \(\cl(o(x))\subseteq\cl(\calo)\).

    By Zorn lemma, it follows that for any orbit \(\calo\subseteq X\), the closure \(\cl(\emptyset)\) contains a minimal
    flow.  If the flow \(\cl(o(x))\) is minimal, then we call the point \(x\) *almost periodic*. Every
    minimal flow is point transitive, any point in a minimal flow is almost periodic and any two
    distinct minimal subflows of \(X\) are disjoint

    A *morphism of \(G\)-flows* is a continuous \(\varphi:X_0\to X_1\) that commutes with the action of \(g\),
    i.e. s.t. for all \(p\in X_0\) and \(g\in G\) we have \(\varphi(g\cdot p)=g\cdot\varphi(p)\). Thus \(G\)-flows become a
    category. Point-transitive \(G\)-flows are a subcategory.



    There is a unique largest universal point-transitive \(G\)-flow, namely \(X=\beta G\), the space of
    ultrafilters on \(G\), where the action of \(G\) on \(\beta G\) is by left translation by \(G\)

    first consider boolean algebra \(\calp(G)\) and all ultrafilters on \(\calp(G)\), which is \(\beta G\), the
    stone spaces. compact, totally disconnected Hausdorff space

    \(X\in G\), define \([x]=\{p\in\beta G\mid x\in p\}\)

    \(j:G\to\beta G\), \(g\mapsto(g)=\{p\mid\{g\}\in p\}\), \(j(G)\) is dense in \(\beta G\)

    universal property: If there is \(f:G\to X\) embedding where \(X\) is closed and \(\ove{f(G)}=X\), then there is a
    unique \(\beta G\to X\), \((g)\mapsto f(g)\) surjection,

    Let \(T=\Th(M)\) be a complete theory, \(G\) is a definable group. A \(G\)-set \(V\) is
    *definable* if the underlying set \(V\) and the group action are both definable. If this action is
    transitive, we call \(V\) a *homogeneous \(G\)-set*

    \(M\preceq N\), \(V^N\) means that \(\varphi(N)\) where \(\varphi\) defines \(V\) in \(M\).
