#+TITLE: Topological Dynamics And Definable Group Actions
#+AUTHOR: Ludomir Newelski

#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Introduction
    Assume \(G\) is a group. By a *\(G\)-flow* we mean a compact Hausdorff topological space \(X\) together with
    a left action of \(G\) on \(X\) by homeomorphisms. A non-empty closed subset \(Y\) of \(X\) is a
    *subflow* of \(X\) if \(Y\) is closed under the action of \(G\). A flow is *minimal* if it has no
    proper subflow. A flow is *point-transitive*, if it contains a dense \(G\)-orbit.

    Topological dynamics is concerned with the orbits of the actions of \(G\) on
    various \(G\)-flows, and particularly with minimal flows

    Assume \(X\) is a \(G\)-flow. For \(x\in X\) let \(o(x)\) denote the orbit of \(X\). Then the
    closure \(\cl(o(x))\) is a subflow of \(X\) and for any orbit \(\calo\subseteq X\) and every \(x\in\cl(\calo)\) we
    have \(\cl(o(x))\subseteq\cl(\calo)\).

    By Zorn lemma, it follows that for any orbit \(\calo\subseteq X\), the closure \(\cl(\emptyset)\) contains a minimal
    flow.  If the flow \(\cl(o(x))\) is minimal, then we call the point \(x\) *almost periodic*. Every
    minimal flow is point transitive, any point in a minimal flow is almost periodic and any two
    distinct minimal subflows of \(X\) are disjoint

    A *morphism of \(G\)-flows* is a continuous \(\varphi:X_0\to X_1\) that commutes with the action of \(g\),
    i.e. s.t. for all \(p\in X_0\) and \(g\in G\) we have \(\varphi(g\cdot p)=g\cdot\varphi(p)\). Thus \(G\)-flows become a
    category. Point-transitive \(G\)-flows are a subcategory.



    There is a unique largest universal point-transitive \(G\)-flow, namely \(X=\beta G\), the space of
    ultrafilters on \(G\), where the action of \(G\) on \(\beta G\) is by left translation by \(G\)

    first consider boolean algebra \(\calp(G)\) and all ultrafilters on \(\calp(G)\), which is \(\beta G\), the
    stone spaces. compact, totally disconnected Hausdorff space

    \(X\in G\), define \([x]=\{p\in\beta G\mid x\in p\}\)

    \(j:G\to\beta G\), \(g\mapsto(g)=\{p\mid\{g\}\in p\}\), \(j(G)\) is dense in \(\beta G\)

    universal property: If there is \(f:G\to X\) embedding where \(X\) is closed and \(\ove{f(G)}=X\), then there is a
    unique \(\beta G\to X\), \((g)\mapsto f(g)\) surjection,

    Let \(T=\Th(M)\) be a complete theory, \(G\) is a definable group. A \(G\)-set \(V\) is
    *definable* if the underlying set \(V\) and the group action are both definable. If this action is
    transitive (there is \(v\in V\) s.t. \(G\cdot v=V\)), we call \(V\) a *homogeneous \(G\)-set*

    For a definable subset \(V\) of \(M\) and \(N\succ M\), by \(V^N\) we mean the set \(\varphi(N)\), where
    \varphi is a formula defining \(V\) in \(M\)

    Assume \(V\) is a definable \(G\)-set in \(M\). Then for any \(N\succ M\) also \(G^N\) acts
    on \(V^N\), in particular, \(G^{\fC}\) acts on \(V^{\fC}\). Also \(G\) is a subgroup of \(G^{\fC}\),
    hence \(G\) acts also on \(V^{\fC}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A subset of a structure is *type-definable* iff it can be written as the set of realizations of a
    partial types
    #+END_definition


    Assume \(E\) an equivalence relation on \(V^{\fC}\) type definable (definable by \omega formulas)
    over \(M\). For any formula \(\varphi(x,y)\in E(x,y)\) we may assume \(\varphi\vdash V(x)\wedge V(y)\). \(\varphi(x,y)\) is
    reflexive, and we can require it to be symmetric since \(\varphi(x,y)\wedge\varphi(y,x)\) is always symmetric

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(E\) be a equivalence relation on \(V^{\fC}\) type definable over \(M\), for any
    symmetric \(\psi(x,y)\in E\), there is a symmetric \(\varphi(x,y)\) s.t. \(\varphi(x,y)\wedge\varphi(y,z)\vdash\psi(x,z)\).
    Note \(\varphi(x,y)\vdash\psi(x,y)\) as \(z=y\)
    #+END_lemma

    #+BEGIN_proof
    \(\{\varphi(x,y)\wedge\varphi(x,z):\varphi\in E\}\vdash\psi(x,z)\) for any \(\psi\in E\) because \(E\) is an equivalence relation. By
    compactness, we get a desired \varphi
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is an equivalence relation on \(V^{\fC}\), type definable over \(M\). TFAE
    1. \(\abs{V^{\fC}/E}<\kappa\)
    2. \(\abs{V^{\fC}/E}\le 2^{\abs{T}+\abs{M}}\)
    3. For any symmetric \(\varphi(x,y)\) there is a number \(n_\varphi<\omega\) and \(n_\varphi\)
       elements \(a_1,\dots,a_{n_\varphi}\in V^{\fC}\) satisfying that for any \(i<j\), \(\neg\varphi(a_i,a_j)\) and for
       any \(c\in V^{\fC}\), \(\varphi(c,a_i)\) for some \(i\le n_\varphi\)
    4. For any symmetric \(\varphi(x,y)\) and \(a\in V^{\fC}\) there is \(c\in M\) with \(\varphi(a,c)\). So we can
       require the elements \(a_1,\dots,a_{n_\varphi}\) in 3 to live in \(M\)
    #+END_proposition

    #+BEGIN_proof
    \(1\to 3\): if not, we can build a \kappa-sequence by induction. Assume we have \(a_i\) for \(i<\alpha\),
    then we chose \(a_\alpha\) realizing \(\{\neg\varphi(x,a_i)\wedge V(x):i<\alpha\}\), which is finitely satisfiable. Since
    \(\neg\varphi(a_i,a_j)\Rightarrow\neg E(a_i,a_j)\), \((a_i)_{i<\kappa}\) are from different equivalence class of \(E\)

    \(3\to 4\): Assume \(a_1,\dots,a_k\) are the representitives, \(a_1,\dots,a_l\in M\), \(a_{l+1},\dots,a_k\notin M\),
    and for any \(c\in M\) and \(i>l\), there are \(\neg\varphi(c,a_i)\). Let \(\psi\equiv\bigwedge_{i=1}^l\neg\varphi(a_i,x)\),
    then \(\psi(M)=\emptyset\) while \(\{a_{l+1},\dots,a_k\}\subseteq\psi(\fC)\)

    \(4\to 2\): \(\abs{M}^{\abs{T}+\abs{M}}=2^{\abs{T}+\abs{M}}\)

    \(2\to 1\): trivial
    #+END_proof

    Assume \(E\) is an equivalence relation on \(V^{\fC}\), type definable over \(M\), with bounded
    number of classes (btde-relation). On \(V^{\fC}\) we have a natural topology where the closed set
    are the type definable set

    On the quotient set \(V^{\fC}/E\) (also denoted by \(V_E\)), there is a natural topology, with the
    closed set \(Z\) where \(\pi^{-1}(Z)\subseteq V^{\fC}\) is a type definable set. This topology is called the
    logic topology or the Kim-Pillay Topology on \(V_E\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is a equivalence relation type definable by \(M\), we equip \(V_E\) with logic
    topology
    1. \(Y\subseteq V_E\) is closed iff for some type definable set \(A\), \(Y=\{a_E:a\in A\}\)
    2. A basis of open sets is the collection of all \(U_{a\varphi}\).
       Here \(U_{a\varphi}=\{b_E:\varphi(a',b')\text{ for all }E(a,a'),E(b,b')\}\), \(\varphi\in E\)
    3. \(V_E\) is Hausdorff
    4. \(V_E\) is compact iff \(E\) is bounded
    #+END_proposition

    #+BEGIN_proof
    1. \(\Rightarrow\): trivial \(\Leftarrow\): \(\pi^{-1}(Y)=\{a:a_E\in Y\}\) is type defined by \(\exists y(E(x,y)\wedge A(y))\)
    2. \(U_{a\varphi}\) is open because \(\{b:b_E\notin U_{a\varphi}\}\) is type defined
       by \(\exists y\exists z(E(a,y)\wedge E(x,z)\wedge\neg\varphi(y,z))\)

       Assume \(U\) is open and \(a_E\in U\), \(V_E\setminus U\) is closed and type defined by a partial
       type \(\Sigma(x)\) where \(\Sigma(V^{\fC})=\pi^{-1}(V_E\setminus U)\). Choose \(\psi\in\Sigma\) s.t. \(\neg\psi(a)\).
       Since \(E(x,y)\wedge \Sigma(x)\vdash\Sigma(y)\), we have \(\varphi(x,y)\wedge\Sigma(y)\vdash\psi(y)\) for some \(\varphi\in E(x,y)\) by
       compactness. Then \(a_E\in U_{a\varphi}\subseteq U\)
    3. Suppose \(a_E\neq b_E\), then there is \(\varphi\in E\) s.t. \(\neg\varphi(a,b)\).
       Let \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\). Then \(a\in U_{a\varphi'}\) and \(b\in U_{b\varphi'}\)?
    4. Assume \(E\) is bounded, \((F_i)_{i\in I}\) is a family of closed sets with finite intersection
       property. The number of \(E\)-classes is bounded, so the number of closed set is also bounded

       Assume \(V_E\) is compact, for any \(\varphi\in E\), let \((a_i)_{i\in I}\) be representitives.
       Now \(V_E=\bigcup_{i\in I}U_{a_i\varphi}\), so there is finite \(I_0\subseteq I\) s.t. \(V_E=\bigcup_{i\in I_0}U_{a_i\varphi}\)
    #+END_proof

    A btde-relation \(E\) on \(V^{\fC}\) is \(G\)-invariant if for
    any \(x,y\in V^{\fC}\), \(xEy\Rightarrow gxEgy\). In this case, a group action of \(G\) on \(V\) (which is a
    homeomorphism) induces a homeomorphism on \(V_E\). Hence \(V_E\) becomes a \(G\)-flow. We call
    any \(G\)-flow of this kind a definable \(G\)-flow

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(V\) is a homogeneous \(G\)-set, then the flow \(V_E\) is point-transitive
    #+END_proposition

    #+BEGIN_proof
    We claim the orbit consisting \(a_E\) for \(a\in V\) is dense in \(V_E\).
    Suppose \([b]_E\cap W=\emptyset\) where \(W\) is a type definable set of \(V_E\). We need to
    prove \([a]_E\cap W=\emptyset\) for some \(a\in V\). Let symmetric \(\varphi,\varphi'\) be with \(\varphi(\fC,b)\cap W=\emptyset\), \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is a btde-relation, \(\tp(a/M)=\tp(b/M)\), then \(aEb\)
    #+END_proposition

    #+BEGIN_proof
    Assume symmetric \(\varphi'\) satisfying \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\). Because \(E\) is bounded, there
    is \(c\in M\) s.t. \(\varphi'(a,c)\). Since \(\tp(a/M)=\tp(b/M)\) we have \(\varphi'(b,c)\) and
    then \(\varphi(a,b)\). So for any \varphi we have \(\varphi(a,b)\), this is \(E(a,b)\)
    #+END_proof

* weaf
