#+title: Generic Properties of Groups

#+AUTHOR: Marcin Petrykowski
#+EXPORT_FILE_NAME: ../latex/papers/generic properties of groups.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Preliminaries
    If \(p(\barx)\) is a type over \(A\), then we call the set of realizations of \(p\) in \(M\)
    \begin{equation*}
    p(M^n)=\{\bara\in M^n:(\forall\varphi(\barx)\in p(\barx))M\vDash\varphi(\bara)\}\vDash\bigcap_{\varphi(\barx)\in p(\barx)}\varphi(M^n)
    \end{equation*}
    *type definable over* \(A\). If \(V\) is a 0-type-definable subset of \(M^n\), then we sometimes
     identify \(V\) with the set
     \begin{equation*}
    [V]=\{\tp(\bara):\bara\in V\}\subseteq S_n(\emptyset)
     \end{equation*}

     A first order structure \(M\) is \kappa-saturated if for any \(A\subseteq M\) with \(\abs{A}<\kappa\), \(n<\omega\)
     and \(p\in S_n(A)\), \(p\) has a realization in \(M\).

     A type \(p(\barx)\) is complete over \(A\) if for any formula \(\varphi(\barx)\in L\) we have
     that \(p(\barx)\vdash\varphi(\barx)\) or \(p(\barx)\vdash\neg\varphi(\barx)\).

     A group \((G,\cdot)\) is definable in a structure \(M\) if \(G\) is a definable subset of \(M^n\)
     for some \(n<\omega\) and the group action \(\cdot:G\times G\to G\) is a definable function in \(M\).
     If \(p(x)\) is a type over \(G\) and \(g\in G\), then

     We call a first order structure \((M,\cdot,\dots)\) a group if \((M,\cdot)\) satisfies group axioms. We
     usually denote it by \((G,\cdot,\dots)\). A structure of the form \((G,\cdot)\) is called a *pure* group.
     \begin{equation*}
    g\cdot p(x)=\{g\cdot\varphi(x):\varphi(x)\in p(x)\}=\{\varphi(g^{-1}\cdot x):\varphi(x)\in p(x)\}
     \end{equation*}
     A group \((G,\cdot)\) is definable in a structure \(M\) if \(G\) is a definable

     An infinite totally ordered first order structure \((M,<,\dots)\) is *o-minimal* if every definable
     subset of \(M\) is a union of finitely many intervals and points.

     Let \((M,<,\dots)\) be an o-minimal structure. We usually say "ultimately" instead of "for all
     sufficiently large \(a\in M\)". We denote an open interval with endpoints \(a\) and \(b\)
     by \((a,b)\) and a closed one by \([a,b]\). In contrast, \(\la a,b\ra\) denotes the pair of
     elements \(a\) and \(b\).

     If \(a\in M\cup\{-\infty\}\), \(b\in M\cup\{+\infty\}\), \(a<b\) and \(f:(a,b)\to M\) is a definable function, then there
     are \(a=a_1<\dots<a_n=b\) s.t. each interval \((a_i,a_{i+1})\) of \(f\) is either constant or
     strictly monotone and continuous in the order topology. In particular, every definable
     function \(f:M\to M\) is ultimately continuous and monotone

* Weak generic types
** Introduction
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(X\subseteq G\) is *(left) generic* if some finitely many left \(G\)-translates of \(X\)
    cover \(G\). We say that a formula \(\varphi(x)\) is *(left) generic* if the set \(\varphi(G)\) of elements
    of \(G\) realizing \varphi is *(left) generic*. Finally, we say that a type \(p(x)\) of elements
    of \(G\) is *(left) generic* if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is (left) generic
    #+END_definition

    In the stable case left generic = right generic <<Problem1>>

    and each partial generic type extends to a complete generic type (since type is definable)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A set \(A\subseteq G\) is *weak generic*, if for some non-generic \(B\subseteq G\) we have that \(A\cup B\) is
    generic. A formula \(\varphi(x)\) is *weak generic* if the set \(\varphi(G)\) is weak generic. A type \(p(x)\)
    of elements of \(G\) is weak generic if every formula \(\varphi(x)\) with \(p(x)\vdash\varphi(x)\) is weak generic
    #+END_definition

** Basic properties of weak generic sets and types
    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.1
    Assume that \(G\) is a group and \(X\) is a definable subset of \(G\). TFAE
    1. the set \(X\) is weak generic
    2. for some finitely many elements \(a_1,\dots,a_n\in G\) the set \(G\setminus\bigcup_{i=1}^na_i\cdot X\) is not generic
    3. for some definable non-generic set \(Y\subseteq G\) the set \(X\cup Y\) is generic
    #+END_lemma

    #+BEGIN_proof
    \(1\Rightarrow 2\): Assume \(X\) is weak generic, then there is non-generic set \(Y\subseteq G\) s.t. \(X\cup Y\) is
    generic. Then there are \(a_1,\dots,a_n\in G\) s.t.
    \begin{equation*}
    \bigcup_{i=1}^na_i\cdot(X\cup Y)=\bigcup_{i=1}^na_i\cdot X\cup\bigcup_{i=1}^na_i\cdot Y=G
    \end{equation*}
    This means that
    \begin{equation*}
    G\setminus\bigcup_{i=1}^na_i\cdot X\subseteq\bigcup_{i=1}^na_i\cdot Y
    \end{equation*}

    \(2\Rightarrow 3\): Let \(Y=G\setminus\bigcup_{i=1}^na_i\cdot X\). Then \(Y\) is definable and not generic so
    putting \(a_{n+1}=e\). Then \(G=\bigcup_{i=1}^{n+1}a_i\cdot(X\cup Y)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.2
    1. If \(X,Y\subseteq G\) are not weak generic, then \(X\cup Y\) is not weak generic
    2. If \(p(x)\) is a (partial) weak generic type over \(A\subseteq G\), then \(p(x)\) may be extended to
       a complete weak generic type over \(A\)
    #+END_lemma

    #+BEGIN_proof
    1. Let \(Z\subseteq G\)  be non-generic. \(Y\) is not weak generic so \(Y\cup Z\) is not generic,
       so \(Y\cup Z\cup X\) is not generic
    2. non weak generics form an ideal

       Let \(q(x)=\{\varphi(x)\in L(A):p(x)\cup\{\neg\varphi(x)\}\text{ is not weak generic}\}\). Then \(p\subseteq q\). We shall
       show that \(q\) is a consistent partial type over \(A\). If not, then
       \begin{equation*}
       G\vDash\neg\exists x\bigwedge_{k=1}^n\varphi_k(x)
       \end{equation*}
       for some \(n<\omega\) and \(\varphi_1,\dots,\varphi_n\in q\). By compactness, for each \(k\in\{1,\dots,n\}\) we can find a
       finite set of formulas \(p_k\subseteq p\) s.t. the type \(p_k(x)\cup\{\neg\varphi_k(x)\}\) is not weak generic.
       Let \(\psi(x)=\bigwedge\{p_k(x):1\le k\le n\}\) and note that for every \(k\in\{1,\dots,n\}\) the set \(\psi(G)\cap\neg\varphi_k(G)\)
       is not weak generic. By 1, neither is the union
       \begin{equation*}
       \bigcup_{k=1}^n(\psi(G)\cap\neg\varphi_k(G))=\psi(G)\cap\bigcup_{k=1}^n\neg\varphi_k(G)=\psi(G)\cap G=\psi(G)
       \end{equation*}
       contradicting the fact that \(p(x)\vdash\psi(x)\). Finally we take any \(r(x)\in S(A)\)
       with \(r\supseteq q\) and the proof is complete
    #+END_proof

    We see that (complete) weak generic types exist. By Lemma ref:3.2.2, the set
    \begin{equation*}
    WGEN(A)=\{p\in S(A):p\text{ is weak generic}\}
    \end{equation*}
    is closed and non-empty in \(S(A)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.3
    Assume \(G\) is a group and \(A\subseteq G\)
    1. If some weak generic type \(p(x)\in S(G)\) is generic, then all weak generic
       types \(q(x)\in S(A)\) are generic
    2. If for every \(p,q\in WGEN(G)\) there is \(g\in G\) s.t. \(g\cdot p=q\), then all weak generic
       types \(q(x)\in S(A)\) are generic
    3. If there is just one weak generic type in \(S(A)\), then it is generic
    #+END_lemma

    #+BEGIN_proof
    1. Suppose that some weak generic type \(q(x)\in S(A)\) is not generic. Then some definable
       generic set \(X\subseteq G\) may be divided into two non-generic definable sets \(X_1,X_2\).
       Since \(X\) is generic, some left \(G\)-translates \(X'\) of \(X\) belongs to \(p(x)\). Then
       the corresponding translates \(X_1',X_2'\) of \(X_1,X_2\) are also non-generic and one of them
       belongs to \(p(x)\). Hence \(p(x)\) is not generic, a contradiction
    2. If not, then we can find a formula \(\varphi(x)\in L(A)\) which is weak generic but not generic. Note
       that \(\{\neg g\cdot\varphi(x):g\in G\}\) is a partial weak generic type over \(G\): for each \(m<\omega\)
       and \(g_1,\dots,g_m\in G\), the set \(\bigcup_{i=1}^mg_i\cdot\varphi(G)\) is not generic, which implies that the
       set \(\bigcap_{i=1}^m(G\setminus g_i\cdot\varphi(G))\) is weak generic. Extend the type \(\{\neg g\cdot\varphi(x):g\in G\}\) to
       some \(q(x)\in WGEN(G)\). Next extend \(\varphi(x)\) to \(p(x)\in WGEN(G)\). Then \(\forall g\in G\;g\cdot p\neq q\),
       a contradiction
    3. by 2, immediately
    #+END_proof

    By Lemma ref:3.2.3 (1), in the stable case weak generic = generic

    As an example note that if \(G=(G,<,+,\dots)\) is o-minimal, then there are exactly two complete weak
    generic types, corresponding to \(-\infty\) and \(+\infty\), and they are not generic

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.2.4
    Assume that \(G\prec H\) and \(\varphi(x)\in L(G)\)
    1. If \(\varphi(G)\) is weak generic in \(G\), then \(\varphi(H)\) is weak generic in \(H\)
    2. If \(G\) is \(\aleph_0\)-saturated and \(\varphi(H)\) is weak generic in \(H\), then \(\varphi(G)\) is weak
       generic in \(G\)
    #+END_lemma

    #+BEGIN_proof
    1. There is a non-generic formula \(\psi(x)\in L(G)\) s.t. \(\varphi(G)\cup\psi(G)\) is generic in \(G\),
       therefore \(\psi(H)\) is not generic in \(H\) and \(\varphi(H)\cup\psi(H)\) is generic in \(H\).
       Thus \(\varphi(H)\) is weak generic in \(H\)
    2. There is a formula \(\psi(x)\in L(H)\) s.t. \(\psi(H)\) is not generic in \(H\) and \(\varphi(H)\cup\psi(H)\) is
       generic in \(H\). We have that \(\psi(x)=\psi(x,b)\) where \(b\subset H\). Let \(A\subseteq G\)  be a finite set
       containing all parameters of \(\varphi(x)\). By \(\aleph_0\)-saturation of \(G\), we are able to find
       in \(G\) a tuple \(a\subset G\) s.t. \(\tp(a/A)=\tp(b/A)\). Then \(\psi(x,a)\in L(G)\) has properties
       needed to deduce the weak genericity of the set \(\varphi(G)\) in \(G\). Namely \(\psi(G,a)\) is not
       generic in \(G\) and \(\varphi(G)\cup\psi(G,a)\) is generic in \(G\). If \(\psi(G,a)\) is generic in \(G\),
       then for some \(0<n<\omega\) we have that
       \begin{equation*}
       G\vDash\exists x_1,\dots,x_n\forall y\exists z(\psi(z,a)\wedge\bigvee_{k=1}^ny=x_k\cdot z)
       \end{equation*}
       and the same holds in \(H\) since \(G\prec H\), which would lead to a contradiction
    #+END_proof

    All lemmas in this section remain true if we consider a group \((G,\cdot)\) definable in a first
    order structure \(M\). Then \(G\) is a definable subset of \(M^n\) for some \(n<\omega\) and for
    every \(A\subseteq M\) we define the set \(WGEN(A)\) of complete weak generic types over \(A\) as the
    set
    \begin{equation*}
    \{p\in S_n(A):\forall\varphi(x_1,\dots,x_n)\in p,G\cap\varphi(M^n)\text{ is weak generic in }G\}
    \end{equation*}

** Characterizations of weak genericity
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(Y\subset X\subset M^n  \), \(Y\) is *large* in \(X\) is \(\dim(X-Y)<\dim(X)\).
    #+END_definition

    #+ATTR_LATEX: :options [Lemma 2.4 of \cite{PILLAY1988239}]
    #+BEGIN_lemma
    label:P2.4
    Let \(X\) be a large definable subset of \(G\). Then finitely many translates of \(X\)cover \(G\).
    #+END_lemma

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:3.3.1
    Assume \(G\) is a definable group in an o-minimal structure \(M\) and \(X\) is a definable weak
    generic subset of \(G\). Then \(\dim(X)=\dim(G)\)
    #+END_proposition

    #+BEGIN_proof
    Suppose \(\dim(X)<\dim(G)\). Take a generic set \(A\) and a non-generic set \(B\)
    s.t. \(A=B\cup X\) (where \(A\) and \(B\) are definable subsets of \(G\), apply Lemma ref:3.2.1)
    Choose a finite \(S\subseteq G\) with \(S\cdot A=G\). Then \(G\setminus(S\cdot B)\subseteq S\cdot X\) and
    \begin{equation*}
    \dim(G\setminus(S\cdot B))\le\dim(S\cdot X)=\dim(X)<\dim(G)
    \end{equation*}
    Hence the set \(S\cdot B\) is large in the sense of [[cite:&PILLAY1988239]] and it must be generic by
    Lemma ref:P2.4. But then \(B\) is also  generic, a contradiction.
    #+END_proof

    Assume \(G\) is a group and \(X,Y\subseteq G\). We say that the set \(X\) is *translation disjoint* from
    the set \(Y\) if for some \(a\in G\), \(a\cdot X\cap Y=\emptyset\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:3.3.2
    Assume \(G\) is a group and \(X\) is a weak generic subset of \(G\). Then for some
    finite \(A\subseteq G\) there is no finite covering of \(X\) by sets that are translation disjoint
    from \(A\cdot X\)
    #+END_lemma

    #+BEGIN_proof
    take \(Y\supseteq X\) generic and \(Y\setminus X\) not generic. We have that \(G=A\cdot Y\) for some
    finite \(A\subseteq G\). We shall prove that \(A\) meets conditions of the lemma.

    Suppose for some \(X_0,\dots,X_{n-1}\subseteq G\) and \(a_0,\dots,a_{n-1}\in G\) we have that
    \begin{equation*}
    X=\bigcup_{i<n}X_i\text{ and }\bigwedge_{i<n}(a_i\cdot X_i)\cap(A\cdot X)=\emptyset
    \end{equation*}
    Then for each \(i<n\), \(a_i\cdot X_i\subseteq G\setminus A\cdot X\subseteq A\cdot(Y\setminus X)\). So for
    each \(i<n\), \(X_i\subseteq a_i^{-1}\cdot A\cdot(Y\setminus X)\), which implies
    that \(X\subseteq\{a_0^{-1},\dots,a_{n-1}^{-1}\}\cdot A\cdot(Y\setminus X)\) and finally
    \begin{equation*}
    G=A\cdot Y=A\cdot(Y\setminus X)\cup A\cdot X\subseteq(A\cup(A\cdot\{a_0^{-1},\dots,a_{n-1}^{-1}\}\cdot A))\cdot(Y\setminus X)
    \end{equation*}
    Then \(G\) is covered by finitely many things
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:3.3.3
    Assume \(G\) is a group and \(X\) is a weak generic subset of \(G\). Then the set \(X\cdot X^{-1}\)
    is generic in \(G\)
    #+END_corollary

    #+BEGIN_proof
    Take a finite \(A\subseteq G\) as in Lemma ref:3.3.2. Then for each \(a\in G\), \(a\cdot X\cap A\cdot X\neq\emptyset\), which
    implies that \(a\in A\cdot X\cdot X^{-1}\). So \(G=A\cdot X\cdot X^{-1}\)
    #+END_proof

    From now on, let \((G,<,+,\dots)\) be an o-minimal expansion of an ordered group \((G,<,+)\). Then
    the group \(G\) is commutative, divisible and torsion-free. By \((G^n,+)\) we mean the product of
    groups \((G,+)\times\dots\times(G,+)\) (\(n\) times). The ordering of \(G\) is dense since for
    every \(a,b\in G\) with \(a<b\) we have that \(a<\frac{a+b}{2}<b\)

    #+ATTR_LATEX: :options [3.3.4]
    #+BEGIN_theorem
    label:3.3.4
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n<\omega\)
    and \(\varphi(x_1,\dots,x_n)\in L(G)\). TFAE
    1. \(\varphi(x_1,\dots,x_n)\) is weak generic in \((G^n,+)\)
    2. \(\neg\varphi(x_1,\dots,x_n)\) is not generic in \((G^n,+)\)
    3. the set \(\varphi(G^n)\) contains arbitrarily large \(n\)-dimensional boxes
       \begin{equation*}
       (\forall R>0)(\exists a_1,\dots,a_n\in G)[a_1,a_1+R]\times\dots\times[a_n,a_n+R]\subseteq\varphi(G^n)
       \end{equation*}
    #+END_theorem

    #+BEGIN_proof
    \(3\Rightarrow 2\): suppose there is \(k<\omega\) and \(\la g_1^1,\dots,g_n^1\ra,\dots,\la g_1^k,\dots,g_n^k\ra\in G^n\) we have that
    \begin{equation*}
    G^n=\bigcup_{j=1}^k(\la g_1^j,\dots,g_n^j)+(G^n\setminus\varphi(G^n))
    \end{equation*}
    Put \(M=\max\{\abs{g_i^j}:1\le i\le n,1\le j\le k\}\). Using 3 we are able to find \(a_1,\dots,a_n\in G\) s.t.
    \begin{equation*}
    [a_1-M,a_1+M]\times\dots\times[a_n-M,a_n+M]\subseteq\varphi(G^m)
    \end{equation*}
    Then
    \begin{equation*}
    \la a_1,\dots,a_n\ra\notin\bigcup_{j=1}^k(\la g_1^j,\dots,g^j_n\ra+(G^n\setminus\varphi(G^n)))
    \end{equation*}
    a contradiction

    \(2\Rightarrow 1\): since the set \(G^n=\varphi(G^n)\cup(G^n\setminus\varphi(G^n))\) is generic in \((G^n,+)\) and the
    set \(G^n\setminus\varphi(G^n)\) is not generic

    \(1\Rightarrow 3\): W.L.O.G., \(n\ge 2\). Using Lemma ref:3.2.2 (2) find \(p(x_1,\dots,x_n)\in S_n(G)\) s.t. \(p\)
    is a weak generic type in \((G^n,+)\) and \(\varphi\in p\). Extend \(G\) to a \(\abs{G}^+\)-saturated
    group \(H\succ G\). Take \(\la a_1,\dots,a_n\ra\in H^n\) realizing \(p\) and fix a positive \(R\in G\). We shall
    show that the follwing condition holds
    \begin{equation*}
    (\forall a\in H)(a_n\le a\le a_n+R\Rightarrow\tp(a/Ga_{<n})=\tp(a_n/Ga_{<n}))\tag{\star}
    \end{equation*}

    For the sake of contradiction assume that for some \(a\in[a_n,a_n+R]_H\) the
    types \(\tp(a/Ga_{<n})\) and \(\tp(a_n/Ga_{<n})\) are distinct. By the o-minimality of \(H\), we
    can find \(b\in[a_n,a_n+R]_H\) with \(b\in\dcl(Ga_{<n})\) (dense). Let \(\psi(x_1,\dots,x_{n-1},y)\in L(G)\)
    be s.t. \(H\vDash\psi(a_{<n},b)\wedge\exists!y \psi(a_{<n},y)\). As \(b-R\le a_n\le b\), we have that \(\chi\in p\) where
    \begin{equation*}
    \chi(x_1,\dots,x_n)=\exists!y\psi(x_{<n},y)\wedge\forall y(\psi(y_{<n},y)\to(y-R\le x_n\le y))
    \end{equation*}
    Since \(\chi\in p\), the set \(\chi(G^n)\) is weak generic in \((G^n,+)\)

    We define \(f:G^{n-1}\to G\) as:
    \begin{equation*}
    f(c_{<n})=
    \begin{cases}
    c_n-R&G\vDash\chi(\barc)\\
    0&\text{otherwise}
    \end{cases}
    \end{equation*}
    Take \(\la c_1,\dots,c_{n-1}\ra\in G^{n-1}\). If there is \(c_n\in G\)
    s.t. \(G\vDash\chi(c_1,\dots,c_n)\), then there exists just one \(d\in G\) with \(G\vDash\psi(c_1,\dots,c_{n-1},d)\) and we
    put \(f(c_1,\dots,c_{n-1})=d-R\). Otherwise we put \(f(c_1,\dots,c_{n-1})=0\). Then the function \(f\) is
    definable over \(G\) and we consider the following formula over \(G\):
    \begin{equation*}
    \delta(x_1,\dots,x_n)=f(x_1,\dots,x_{n-1})\le x_n\le f(x_1,\dots,x_{n-1})+R
    \end{equation*}
    Since \(\chi(G^n)\subseteq\delta(G^n)\subseteq G^n\), the set \(\delta(G^n)\) is weak generic in \((G^n,+)\). Let \(A\subseteq G^n\) be a
    finite set chosen for \(\delta(G^n)\) as in Lemma ref:3.3.2. Consider an
    arbitrary \(\la h_1,\dots,h_{n-1}\ra\in H^{n-1}\). Choose \(M_{h_{<n}}\in G\) s.t.
    \begin{equation*}
    \{\la h_1,\dots,h_n\ra:f(h_{<n})+M_{h_{<n}}\le h_n\le f(h_{<n})+M_{h_{<n}}+R\}
    \cap(A+\delta(H^n))=\emptyset
    \end{equation*}
    (exists since is bounded and \(A\) is finite)
    If \(\tp(h_{<n}/G)=\tp(h'_{<n}/G)\), then \(M_{h_{<n}}\) is good also for \(h'_{<n}\). By
    compactness, for each \(q(x_1,\dots,x_{n-1})\in S_{n-1}(G)\) we can find a
    formula \(\varphi_q(x_1,\dots,x_{n-1})\in L(G)\) and \(M_q\in G\) s.t. for every \(h_{<n}\in H^{n-1}\) with
    \(H\vDash\varphi_q(h_{<n})\) we have
    \begin{equation*}
    \{\la h_1,\dots,h_n\ra:f(h_{<n})+M_q\le h_n\le f(h_{<n})+M_q+R\}\cap(A+\delta(H^n))=\emptyset
    \end{equation*}
    Again by compactness, \(S_{n-1}(G)=[\varphi_{q_1}]\cup\dots\cup[\varphi_{q_k}]\) for some \(k<\omega\)
    and \(q_1,\dots,q_k\in S_{n-1}(G)\).
    #+LATEX: \wu{
    If not, then \(\forall n\in\omega\), \(G\vDash\bigwedge_{i=1}^n\neg\varphi_q{i}\), that is, \(\{\neg\varphi_{q_i}:i\in\omega\}\) is consistent
    with \(G\), then realized by \(H\), which leads to a contradiction.
    #+LATEX: }
    For \(i\in\{1,\dots,k\}\) put \(X_i=(\varphi_{q_i}(G^{n-1})\times G)\cap\delta(G^n)\)
    and \(e_i=\la 0,\dots,0,M_{q_i}\ra\in G^n\). Then \(\delta(G^n)=X_1\cup\dots\cup X_k\) and for every \(i\in\{1,\dots,k\}\) we have
    that \((e_i+X_i)\cap(A+\delta(G^n))=\emptyset\). This contradicts the choice of \(A\) and finishes the proof of
    (\(\star\))

    By (\(\star\)), we have that
    \begin{equation*}
    H\vDash\forall y((a_n\le y\wedge y\le a_n+R)\to\varphi(a_1,\dots,a_{n-1},y))
    \end{equation*}
    Therefore the formula \(\forall y((x_n\le y\le x_n+R\to\varphi(x_1,\dots,x_{n-1},y)))\) belongs to \(p\). In general,
    for each formula \(\psi(x_1,\dots,x_n)\in p(x_1,\dots,x_n)\), \(k\in\{1,\dots,n\}\) and positive \(R\in G\) the formula
    \begin{equation*}
    \forall y((x_k\le y\le x_k+R)\to\psi(x_1,\dots,x_{k-1},y,x_{k+1},\dots,x_n))
    \end{equation*}
    belongs to \(p\). We inductively create formulas \(\varphi_k(x_1,\dots,x_n)\in p(x_1,\dots,x_n)\), \(k=\{1,\dots,n\}\),.
    Namely, provided that \(\varphi_1(x_1,\dots,x_n),\dots,\varphi_{k-1}(x_1,\dots,x_n)\) have already been defined,
    let \(\varphi_k(x_1,\dots,x_n)\) be the formula
    \begin{equation*}
    \forall y((x_k\le y\le x_k+R)\to(\varphi\wedge\varphi_1\wedge\dots\wedge\varphi_{k-1}(x_1,\dots,x_{k-1},y,x_{k+1},\dots,x_n)))
    \end{equation*}
    Finally, we take any \(\barg\in(\varphi\wedge\varphi_1\wedge\dots\wedge\varphi_n)(G^n)\) and see that
    \begin{equation*}
    [g_1,g_1+R]\times\dots\times[g_n,g_n+R]\subseteq\varphi(G^n)
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options [3.3.5]
    #+BEGIN_corollary
    label:3.3.5
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n,k<\omega\)
    and \(\varphi(x_1,\dots,x_n,y_1,\dots,y_k)\in L\)
    1. there is \(\psi_1(y_1,\dots,y_k)\) s.t. for every \(\la a_1,\dots,a_k\ra\in G^k\) we have that \(G\vDash\psi_1(a)\)
       iff \(\varphi(G^n,a)\) is weak generic in \((G^n,+)\)
    2. There is \(\psi_2(y_1,\dots,y_k)\) s.t. for every \(\la a_1,\dots,a_k\ra\in G^k\) we have that \(G\vDash\psi_2(a)\)
       iff \(\varphi(G^n,a)\) is generic in \((G^n,+)\)
    3. there is a natural number \(N\) s.t. for every \varphi-definable \(X\subseteq G^n\) the set \(X\) is generic
       in \((G^n,+)\) iff \(G^n\) may be covered by at most \(N\) left translates of \(X\)
    #+END_corollary

    #+BEGIN_proof
    1. let \(\psi_1(y_1,\dots,y_k)\) be
       \begin{equation*}
       \forall r\exists z_1,\dots,z_n\forall x_1,\dots,x_n((\bigwedge_{i=1}^nz_i\le x_i\wedge x_i\le z_i+r)\to\varphi(x_1,\dots,x_n,y_1,\dots,y_k))
       \end{equation*}
    3. [@3] Assume that \(n=1\). Let \(\psi_2(y_1,\dots,y_k)\) be such as 2. Suppose for every \(N<\omega\) we can
       find \(\la a_1,\dots,a_k\ra\in G^k\) s.t. the set \(\varphi(G,a_1,\dots,a_k)\) is generic in \(G\) but
       not \(N\)-generic. Then the set of formulas
       \begin{equation*}
       \bigcup_{N<\omega}\{\psi_2(y_1,\dots,y_k)\wedge\forall z_1,\dots,z_N\exists t\forall x(\varphi(x,y_1,\dots,y_k)\to\bigwedge_{i=1}^Nt\neq z_i\cdot x)\}
       \end{equation*}
       is a type in variables \(y_1,\dots,y_k\) and has a realization \(\la b_1,\dots,b_k\ra\in H^k\) in
       some \(\aleph_0\)-saturated elementary extension \(H\) of \(G\). Then we reach a contradiction as
       the set \(\varphi(H,b_1,\dots,b_k)\) is simultaneously generic and not generic in \(H\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\), \(0<n<\omega\),
    and \(p(x_1,\dots,x_n)\in S_n(G)\). TFAE
    1. \(p(x_1,\dots,x_n)\) is weak generic in \((G^n,+)\)
    2. \(\la g_1,\dots,g_n\ra+p(x_1,\dots,x_n)=p(x_1,\dots,x_n)\) for every \(\la g_1,\dots,g_n\ra\in  G^n\)
    #+END_corollary

    #+BEGIN_proof
    \(1\Rightarrow 2\): suppose
    \begin{equation*}
    \la g_1,\dots,g_n\ra+p(x_1,\dots,x_n)\neq p(x_1,\dots,x_n)
    \end{equation*}
    for some \(\la g_1,\dots,g_n\ra\in G^n\). Then for some \(\varphi(x_1,\dots,x_n)\in p(x_1,\dots,x_n)\) we have that
    \((\la g_1,\dots,g_n\ra+\varphi(G^n))\cap\varphi(G^n)=\emptyset\). \(\varphi(G^n)\) is weak generic in \((G^n,+)\) and hence contains
    arbitrarily large boxes. Take any \(R>\max(\abs{g_1},\dots,\abs{g_n})\) and choose \(a_1,\dots,a_n\in G\)
    s.t.
    \begin{equation*}
    B=[a_1,a_1+R]\times\dots\times[a_n,a_n+R]\subseteq\varphi(G^n)
    \end{equation*}
    we obtain
    \begin{equation*}
    \emptyset\neq(\la g_1,\dots,g_n\ra+B)\cap B\subseteq(\la g_1,\dots,g_n\ra+\varphi(G^n))\cap\varphi(G^n)=\emptyset
    \end{equation*}
    a contradiction

    \(2\Rightarrow 1\): we shall prove a more general fact. Namely if \(G\) is a group and \(p(x)\in S(G)\) is
    s.t. for every \(g\in G\) we have that \(g\cdot p=p\), then \(p\) is weak generic in \(G\)

    If not, then we can find a formula \(\varphi(x)\in p(x)\) which is not weak generic in \(G\).
    Then \(\neg\varphi(x)\) is generic in \(G\) so there are \(m<\omega\) and \(g_1,\dots,g_m\in G\)
    s.t \(G=\bigcup_{i=1}^mg_i(G\setminus\varphi(G))\). Thus \(\bigcap_{i=1}^mg_i\cdot\varphi(G)=\emptyset\), which contradicts the fact that the
    formulas \(g_1\cdot\varphi,\dots,g_m\cdot\varphi\) belong to the consistent type \(p(x)\)
    #+END_proof

** Stationary
    In this section we assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered
    group \((G,<,+)\)

    Recall that in stable group all weak generic types are generic. <<Problem2>> Moreover, all of
    them are stationary over any model \(M\). This means that every (weak) generic type \(p\in S(M)\)
    has a unique extension to a (weak) generic type \(q\in S(A)\) for each \(A\supseteq M\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call a weak generic type \(p\) over a set \(A\) *stationary* if for every \(B\supseteq A\) the
    type \(p\) has just one extension to a complete weak generic type over \(B\)
    #+END_definition

    In general weak generic types do not need to be stationary

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    we shall prove that the types \(p_1(x)=\{x<a:a\in G\}\) and \(p_2(x)=\{x>a:a\in G\}\) are the only two
    weak generic types in \((G,+)\) complete over \(G\) and that both of them are stationary

    By the o-minimality of \((G,<,+,\dots)\), every definable subset of \(G\) is a union of finitely
    many points and intervals. For every \(a,b\in G\) the interval \((a,b)\) is not weak generic
    in \((G,+)\) by Lemma ref:3.2.1 (2). Thus no type in \(S_1(G)\) but \(p_1\) and \(p_2\) is weak
    generic in \((G,+)\)

    On the other hand, all intervals of the form \((-\infty,a)\) or \((b,+\infty)\) are weak generic
    in \((G,+)\) since their complements in \(G\) are not generic in \((G,+)\).  This gives us the
    weak genericity of the types \(p_1\) and \(p_2\)

    If \(H\) is any elementary extension of \(G\), then there are also two complete (over \(H\))
    weak generic types in \((H,+)\). This means that \(p_1\) and \(p_2\) are stationary
    #+END_examplle

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call an o-minimal structure \((M,<,\dots)\) *stationary* if for every elementary extension \(N\)
    of \(M\) and \(N\)-definable function \(g:N\to N\) there exists an \(M\)-definable
    function \(f:N\to N\) s.t. \(g(x)\le f(x)\) for all sufficiently large \(x\in N\)
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:3.4.4
    Assume \((M,<,\dots)\) is a stationary o-minimal structure and \(N\succ M\). For every \(N\)-definable
    map \(g:N\to N\) with \(\lim_{x\to+\infty}g(x)=+\infty\)  we can find an \(M\)-definable map \(f:N\to N\)
    s.t. \(\lim_{x\to+\infty}f(x)=+\infty\) and \(f(x)\le g(x)\) for all sufficiently large \(x\in N\)
    #+END_theorem

    #+BEGIN_proof
    First of all, assume that \(g\) is a bijection. Then \(g^{-1}\) exists and by the stationary
    of \((M,<,\dots)\) we can find an \(M\)-definable function \(f:N\to N\) s.t. ultimately \(g^{-1}\le f\).
    We have that \(\lim_{x\to+\infty}g^{-1}(x)=+\infty\), which implies that \(\lim_{x\to+\infty}f(x)=+\infty\). Since \(f\)
    is \(M\)-definable, we can choose \(a\in M\) s.t. \(f\) is strictly increasing on \((a,+\infty)\)
    (monotonicity theorem). We define a function \(f_1:N\to N\) as follows
    \begin{equation*}
    f_1(x)=
    \begin{cases}
    f(x)&x>a\\
    f(a)+x-a&x\le a
    \end{cases}
    \end{equation*}
    Then \(f_1\) is an \(M\)-definable bijection, hence \(f_1^{-1}\) exists and also
    is \(M\)-definable. Moreover, \(\lim_{x\to+\infty}f_1^{-1}(x)=+\infty\) and ultimately \(f^{-1}_1\le g\)
    so \(f_1^{-1}\) has the desired properties

    If \(g\) is not a bijection, then proceeding as above we can find an \(N\)-definable
    bijection \(g_1:N\to N\) s.t. ultimately \(g_1=g\)
    #+END_proof

    By the o-minimality of \((G,<,+,\dots)\), every definable subset of the set \(G\times G\) is a union of
    finitely many cells of dimension 0,1,2. By Proposition ref:3.3.1, we are interested only in
    cells of dimension 2 (since we are interested in weak generic subsets). They are of the form
    \begin{equation*}
    C_{a,b}^{f,g}=\{\la x,y\ra\in G\times G:a<x<b\wedge f(x)<y<g(x)\}
    \end{equation*}
    where \(\{-\infty\}\cup G\ni a<b\in G\cup\{\infty\}\) and \(f,g:(a,b)\to G\cup\{-\infty,\infty\}\) are definable maps s.t. \(f(x)<g(x)\)
    for each \(x\in(a,b)\). If \(a,b\in G\), then the cell \(C_{a,b}^{f,g}\) is not weak generic
    in \((G,+)\times(G,+)\) by Theorem ref:3.3.4. Since we shall consider only weak generic
    types \(p(x,y)\) in \((G,+)\times (G,+)\) s.t. \(\{x>a:a\in G\}\subseteq p(x,y)\) <<Problem3>>, we shall be interested only in
    weak generic cells of the form \(C_{a,b}^{f,g}\) where \(a\in G\) and \(b=+\infty\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Assume that functions \(f,g:G\to G\) are definable
    1. \(f\ll g\) if \(f(x)<g(x)\) for all sufficiently large \(x\in G\) and the set
       \begin{equation*}
       \{\la x,y\ra\in G\times G:x>0\wedge f(x)<y\wedge y<g(x)\}
       \end{equation*}
       is weak generic in \((G,+)\times (G,+)\) (\(C_{0,+\infty}^{f,g}\))
    2. \(f\sim g\) if
       \begin{equation*}
       \{\la x,y\ra\in G\times G:x>0\wedge f(x)<y\wedge y<g(x)\}
       \end{equation*}
       is not weak generic in \((G,+)\times (G,+)\)
    #+END_definition

    \(\sim\) is an equivalence relation on the set of all definable functions from \(G\) to \(G\) and
    that equivalence classes of \(\sim\) are convex (i.e., if \(f,g,h:G\to G\) are definable, \(f\sim h\)
    and ultimately \(f(x)\le g(x)\le h(x)\), then \(f\sim g\) and \(g\sim h\))

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(f:G\to G\) be a definable function
    1. Let \(p_f^+(x,y)\) denote the only extension of the type
       \begin{equation*}
       \{x>a:a\in G\}\cup\{y>f(x)\}\cup\{y<g(x):g\gg f\}
       \end{equation*}
       to a type which is complete over \(G\) and weak generic in \((G,+)\times(G,+)\)
    2. Let \(p_f^-(x,y)\) denote the only extension of the type
       \begin{equation*}
       \{x>a:a\in G\}\cup\{y<f(x)\}\cup\{y>g(x):g\ll f\}
       \end{equation*}
       to a type which is complete over \(G\) and weak generic in \((G,+)\times(G,+)\)
    3. Let \(p_{+\infty}(x,y)\) denote the weak generic type
       \begin{equation*}
       \{x>a:a\in G\}\cup\{y>g(x):g:G\to G\text{ definable}\}
       \end{equation*}
    4. Let \(p_{-\infty}(x,y)\) denote the weak generic type
       \begin{equation*}
       \{x>a:a\in G\}\cup\{y<g(x):g:G\to G\text{ definable}\}
       \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:3.4.7
    Assume that \((G,<,+,\dots)\) is an o-minimal expansion of an ordered group \((G,<,+)\). TFAE
    1. \(p_f^+(x,y)\) and \(p_f^-(x,y)\) are stationary for each definable function \(f:G\to G\)
    2. \(p_{+\infty}(x,y)\) and \(p_{-\infty}(x,y)\) are stationary
    3. \((G,<,+,\dots)\) are stationary
    #+END_theorem

    #+BEGIN_proof
    \(1\Rightarrow 2\): Let \(f:G\to G\) be a map constantly equal to 0. Then \(p_{+\infty}(x,y)=p_f^+(y,x)\) and
    therefore \(p_{​+\infty}\) is stationary <<Problem4>>

    Below is an illustration of \(p_f^+(x,y)=p_{+\infty}(y,x)\)
    \begin{center}
     \begin{tikzpicture}
       \draw[->] (-1.2, 0) -- (2.2, 0) node[right] {$x$};
       \draw[->] (0, -1) -- (0, 2) node[above] {$y$};
       \node at (2.2,2.2) {\(g(x)\)};
       \draw[domain=-1:2, smooth, variable=\x] plot ({\x}, {0.3*\x+1});
       \fill [gray, domain=-1:2, variable=\x,opacity=0.3]
       (-1, 0)
       -- plot ({\x}, {\x*0.3+1})
       -- (2, 0)
       -- cycle;
     \end{tikzpicture}
    \end{center}
    where \(g(x)\gg f(x)\).

    \(2\Rightarrow 3\): Suppose the structure \((G,<,+,\dots)\) is not stationary. Then there exist an \(H\succ G\)
    and a \(H\)-definable function \(g:H\to H\) s.t. no \(G\)-definable map \(f:H\to H\) dominates \(g\)

    Consider the following partial types over \(H\):
    \begin{gather*}
    p_1(x,y)=p_{+\infty}(x,y)\cup\{y<g(x)\}\\
    p_2(x,y)=p_{+\infty}(x,y)\cup\{y>g(x)\}
    \end{gather*}
    To reach a contradiction, it is enough to prove that both of them are weak generic
    in \((H,+)\times(H,+)\), and therefore \(p_+(x,y)\) is not stationary. We begin with \(p_1\).

    Goal:
    \begin{equation*}
    (\bigwedge_{i=1}^mx>a_i)\wedge(\bigwedge_{i=1}^ny>f_i(x))\wedge y<g(x)
    \end{equation*}
    is weak generic in \((H,+)\times(H,+)\) where \(a_1,\dots,a_m\in G\) and \(f_1,\dots,f_n\) are functions
    from \(H\) to \(H\) definable over \(G\).

    Take \(a=\max(a_1,\dots,a_n)\) and \(f=\max(f_1,\dots,f_n)\) we can confine our attention to the
    sets \(X\) of the form
    \begin{equation*}
    X=\{\la x,y\ra\in H\times H:x>a\wedge y>f(x)\wedge y<g(x)\}
    \end{equation*}
    where \(a\in G\) and \(f:H\to H\) is definable over \(G\). W.L.O.G., we can assume that \(f\) is
    ultimately non-decreasing

    Consider a map \(h:H\to H\) defined as follows: \(h(a)=f(2a)+a\) for each \(a\in H\). Since \(h\)
    is \(G\)-definable, \(g\) dominates \(h\) <<Problem5>>.
    #+LATEX: \wu{
    Non-stationarity means \(\forall x\in N\exists x<y\in N\) s.t. \(g(y)>h(y)\) and we can assume \(g\) is
    ultimately increasing. Therefore we can define \(g'\) to be
    \begin{equation*}
    g'(x)=\min\{g(y):x<y\wedge g(y)>h(y)\}
    \end{equation*}
    Since \(h\) is non-decreasing, \(g'\) dominates \(h\).
    #+LATEX: }
    Note that for each large enough \(M\in H\) the area
    between the graphs of \(f\) and \(g\) in \(H\times H\) contains the square whose vertices are
    \begin{equation*}
    \la M,f(2M)\ra,\la M,f(2M)+M\ra, \la 2M,f(2M)\ra, \la 2M,f(2M)+M\ra
    \end{equation*}
    By Theorem ref:3.3.4, \(X\) is weak generic in \((H,+)\times(H,+)\). As a result, the type \(p_1\) is
    weak generic in \((H,+)\times(H,+)\)

    \(3\Rightarrow 1\): Take any definable \(f:G\to G\). We shall show that both \(p_f^+\) and \(p_f^-\) are
    stationary weak generic types

    By the o-minimality of \(G\), \(f\) is ultimately non-negative or ultimately non-positive. It is
    easy to see that \(p_f^+\) is stationary iff \(p_{-f}^-\) is stationary and \(p_f^-\) is stationary
    iff \(p_{-f}^+\) is stationary. Therefore, W.L.O.G, we can assume that \(f\) is ultimately
    non-negative. Moreover, \(f\) is ultimately non-increasing or ultimately non-decreasing.
    If \(f\) is ultimately non-increasing, then \(p_f^+=p_z^+\) and \(p_f^-=p_z^-\) where \(z:G\to G\) is
    constantly equal to 0.
    So we can assume that \(f\) is ultimately non-decreasing (this includes the constant case)

    Consider definable sets:
    \begin{align*}
    A&=\{a\in G:(\exists b>a)(\forall c\in(a,b))f(c)-f(a)\le c-a\}\\
    B&=\{a\in G:(\exists b>a)(\forall c\in(a,b))f(c)-f(a)>c-a\}
    \end{align*}
    Note that by the o-minimality of \(G\), we have that \(G=A\cup B\) and for some \(M\in G\)
    either \((M,+\infty)\subseteq A\) or \((M,+\infty)\subseteq B\). Enlarge \(M\) in order to ensure that \(f\) is continuous
    on \((M,+\infty)\)

    *Case 1*: \((M,+\infty)\subseteq A\). Then \(f\) grows "slowly" on \((M,+\infty)\):
    \begin{equation*}
    (\forall a>M)(\exists b>0)(\forall c\in(0,b))f(a+c)\le f(a)+c\tag{\star}
    \end{equation*}
    By (\star) and the continuity of \(f\)
    \begin{equation*}
    (\forall a>M)(\forall c>0)f(a+c)\le f(a)+c\tag{\star\star}
    \end{equation*}
    Because if not, then the opposite holds: \((\exists a>M)(\exists c>0)f(a+c)>f(a)+c\).
    Let \(C=\{c>0:f(a+c)>f(a)+c\}\) and \(c_0=\inf(C)\).
    Assertion (\(\star\)) implies that \(c_0>0\). Since \(f\) is continuous at \(c_0\), \(c_0\notin C\).
    Choose \(d>c_0\) s.t. \((c_0,d)\subseteq C\). Since \(c_0\notin C\), \(f(a+c_0)\le f(a)+c_0\). On the other
    hand, by the continuity of \(f\) at \(a+c_0\), we have that \(f(a+c_0)\ge f(a)+c_0\).
    Thus \(f(a+c_0)=f(a)+c_0\) and for every \(e\in(0,d-c_0)\) we have that
    \begin{equation*}
    f(a+c_0+e)>f(a)+c_0+e=f(a+c_0)+e
    \end{equation*}
    which implies that \(a+c_0\notin A\). But \(a+c_0\in(M,+\infty)\subseteq A\), a contradiction. So (\(\star\star\) holds)

    For the sake of contradiction assume that \(p_f^+\) is not stationary. Then for some \(H\succ G\) and
    \(H\)-definable \(g:H\to H\) we have that \(f\ll g\) and \(g\ll h\) for each \(G\)-definable \(h:H\to H\)
    with \(f\ll h\).
    #+LATEX: \wu{
    Use the same technique above. If \(p_f^+\) is not stationary, then there is some \(H\)-definable
    function \(g\) s.t. both
    \begin{gather*}
    p_f^+(x,y)\cup\{y>g(x)\}\\
    p_f^+(x,y)\cup\{y\le g(x)\}
    \end{gather*}
    are weak generic, which implies that \(f\ll g\ll h\) for each \(G\)-definable \(h:H\to H\)
    with \(f\ll h\).
    #+LATEX: }
    Since \(\lim_{x\to+\infty}(g(x)-f(x))=+\infty\), there exists an increasing
    to \(+\infty\) \(G\)-definable function \(h:H\to H\) s.t. ultimately \(h\le g-f\) by ref:3.4.4.
    Enlarging \(M\) we can assume that \(h\) is increasing on \((M,​+\infty)\).

    Now fix any positive \(R\in H\) and find \(a>M\) with \(h(a)\ge 2R\). By (\(\star\star\)), we have
    that \(f(a+R)\le f(a)+R\). So the area between the graphs of \(f\) and \(f+h\) contains the square
    whose vertices are
    \begin{equation*}
    \la a,f(a)+R\ra,\la a,f(a)+2R\ra,\la a+R,f(a)+R\ra,\la a+R,f(a)+2R\ra
    \end{equation*}
    As \(R\) was arbitrary, we can use Theorem ref:3.3.4 to conclude that the area between the
    graphs of \(f\) and \(f+h\) is weak generic in \((H,+)\times(H,+)\). So \(f\ll f+h\) and
    therefore \(g\ll f+h\), which contradicts the fact that ultimately \(g\ge f+h\). So the
    type \(p_f^+\) is stationary

    *Case 2*: \((M,+\infty)\subseteq B\).  Then \(f\) grows "quickly" on \((M,+\infty)\), which implies
    that \(\lim_{x\to+\infty}f(x)=+\infty\). As in ref:3.4.4 find a definable bijection \(f_1:G\to G\)
    s.t. \(f_1(a)=f(a)\) for each \(a\in(M,+\infty)\). If \(g=f_1^{-1}\), then \(g\) grows "slowly"
    on \((M,+\infty)\) and from the previous case we know that the types \(p_g^+\) and \(p_g^-\) are
    stationary. The proof is complete since
    \(p_f^+(x,y)=p_{f_1}^+(x,y)=p_g^-(y,x)\) and \(p_f^-(x,y)=p_{f_1}^-(x,y)=p_g^+(x,y)\)
    #+END_proof

    #+ATTR_LATEX: :options [1.7.6 of \cite{van1998tame}]
    #+BEGIN_corollary
    label:V1.7.6
    Let \(\cals_m\) be the boolean algebra of semilinear subsets of \(R^m\). Then \(\cals:=(\cals_m)_{m\in\N}\) is
    an o-minimal structure on the ordered set \((R,<)\). Each function in \(\cals\) is piecewise affine,
    more precisely, given a function \(f:A\to R\) in \(\cals\) with \(A\subseteq R^m\), there is a partition
    of \(A\) into basic semilinear sets \(A_i\) (\(1\le i\le k\)) s.t. \(f|A_i\) is the restriction
    to \(A_i\) of an affine function on \(R^m\), for each \(i\in\{1,\dots,k\}\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_examplle
    If \((G,<,+)\) is an o-minimal ordered group, then every definable function \(f:G\to G\) is
    ultimately equal to \(f_q(x)+a\) for some \(a\in G\) and \(q\in\Q\) where \(f_q(x)=q\cdot x\)
    (ref:V1.7.6) by considering \(G\) as a \(\Q\)-vector space. Below we list
    all weak generic types in \((G,+)\times(G,+)\)
    that are complete over \(G\) and contain the formula \(x>0\)
    1. \(p_{-\infty}(x,y)\) and \(p_{+\infty}(x,y)\)
    2. \(p_{f_q}^-(x,y)\) and \(p_{f_q}^+(x,y)\), \(q\in\Q\)
    3. \(\{x>a:a\in G\}\cup\{y>q\cdot x:q\in\Q\wedge q<r\}\cup\{y<q\cdot x:q\in\Q\wedge q>r\}\), \(r\in\R\setminus\Q\)
    The structure \((G,<,+)\) is stationary since its elementary extensions are all linearly
    bounded. Thus by Theorem ref:3.4.7, weak generic types of the form (1) and (2) are stationary.
    <<Problem7>>
    #+END_examplle

** Expansions of real closed fields
    In this section, \((R,<,+,\cdot,0,1,\dots)\) is an o-minimal expansion of an ordered
    ring \((R,<,+,\cdot,-,0,1)\). Such a ring must be a real closed field. Since \((R,<,+,\cdot,0,1,\dots)\) is an
    o-minimal expansion of the ordered group \((R,<,+)\), all results obtained in the previous
    section apply

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call a structure \((R,<,+,\cdot,\dots)\) *polynomially bounded* if for every definable
    function \(f:R\to R\) there is \(n\in\N^+\) s.t. \(\abs{f(x)}\le x^n\) for all sufficiently large \(x\in R\)
    #+END_definition

    #+BEGIN_remark
    label:3.5.2
    If a real closed field \((R,<,+,\cdot,\dots)\) is polynomially bounded and o-minimal, then for every
    definable \(f:R\to R\) with \(\lim_{x\to+\infty}f(x)=+\infty\) we can find \(n\in\N_+\) s.t. \(f(x)\ge\sqrt[n]{x}\)
    for all sufficiently large \(x\in R\)
    #+END_remark

    #+BEGIN_proof
    We proceed as in the proof of ref:3.4.4. Since \(f\) is ultimately increasing, we are able to
    find a definable bijection \(g:R\to R\) s.t. \(f(x)=g(x)\) for all sufficiently large \(x\in R\). We
    know that the inverse map \(g^{-1}\) is ultimately dominated by the polynomial
    function \(x\mapsto x^n\) for some \(n\in\N_+\). And this implies \(f(x)=g(x)\ge\sqrt[n]{x}\) for
    sufficiently large \(x\)
    #+END_proof

    #+ATTR_LATEX: :options [2.6.1 of \cite{bochnak2013real}]
    #+BEGIN_proposition
    label:B2.6.1
    Given a real closed field \(R\), let \(f\) be a semi-algebraic function (not necessarily
    continuous) from \((a,+\infty)\subset R\) to \(R\). There exists \(r,c\in R\), \(r>a\), and \(p\in\N\), s.t.,
    for every \(x\ge r\), we have \(\abs{f(x)}\le cx^p\). Moreover, if \(h\in R[X,Y]\) is a nonzero
    polynomial, s.t. \(h(x,f(x))=0\) on \((a,+\infty)\), we can take \(p\) to be the degree of \(h\) w.r.t. \(X\)
    #+END_proposition


    Assume \((R,<,+,\cdot)\) is a pure real closed field. Since every definable map \(f:R\to R\) is
    semi-algebraic, it follows from ref:B2.6.1 that the
    structure \((R,<,+,\cdot)\) is polynomially bounded.

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Every pure real closed field \((R,<,+,\cdot)\) is stationary and so are the weak generic
    types \(p_f^-(x,y)\) and \(p_f^+(x,y)\) for each definable \(f:R\to R\)
    #+END_corollary

    #+BEGIN_proof
    Consider an arbitrary elementary extension \(S\) of \(R\) and any definable map \(f:S\to S\).
    Since the real closed field \((S,<,+,\cdot)\) is polynomially bounded, there exists \(n\in\N_+\) s.t.
    ultimately \(\abs{f(x)}\le x^n\). This gives us the stationary of the structure \((R,<,+,\cdot)\)
    #+END_proof

    On the other hand, the structure \((\R,<,+,\cdot,e^x)\) is not polynomially bounded but it is still an
    o-minimal expansion of the ordered field of real numbers ([[cite:&Wilkie1996ModelCR]])

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Assume \((R,+,\cdot,0,1)\) is a field, \(f,g:R\to R\) and \(g(x)\neq 0\) for all sufficiently
    large \(x\in R\). We write \(f\approx g\) iff
    \begin{equation*}
    \lim_{x\to+\infty}\frac{f(x)}{g(x)}=1
    \end{equation*}
    #+END_definition

    #+ATTR_LATEX: :options [2.5.2 of \cite{bochnak2013real}]
    #+BEGIN_lemma
    label:B2.5.2
    Let \(A\subset R\) be a semi-algebraic set and \(\varphi:A\to R\) a semialgebraic function. There exists a
    nonzero polynomial \(f\in R[X,Y]\) s.t. for every \(x\in A\), \(f(x,\varphi(x))=0\).
    #+END_lemma

    #+ATTR_LATEX: :options [3.5.5]
    #+BEGIN_lemma
    label:3.5.5
    Assume \((R,<,+,\cdot)\) is a pure real closed field. If a function \(f:R\to R\) is definable and
    ultimately non-zero, then for some \(q\in\Q\) and \(c\in R\setminus\{0\}\) we have that \(f(x)\approx c\cdot x^q\)
    #+END_lemma

    #+BEGIN_proof
    Let \(S\) be an arbitrary \(\abs{R}^+\)-saturated elementary extension of \(R\). We can
    find \(a\in S\) s.t. \(a>r\) for every \(r\in R\). Let
    \begin{equation*}
    T=\{s\in S:\abs{s}<r\text{ for some }r\in R\}
    \end{equation*}
    Then \(T\) is a convex subring of \(S\),
    \begin{equation*}
    T^*=\{s\in S:\frac{1}{r}<\abs{s}<r\text{ for some }r\in R\}
    \end{equation*}
    and \((T^*,\cdot)\) is a subgroup of the multiplicative group \((S^*,\cdot)\).

    The quotient group \((S^*/T^*,*,\bone)\) may be ordered in the following way:
    \begin{equation*}
    s_1/T^*\le s_2/T^*\Leftrightarrow\frac{s_1}{s_2}\in T
    \end{equation*}
    We define a function \(\nu:S\to S^*/T^*\cup\{-\infty\}\) (where for every \(s\in S^*\), \(-\infty<s/T^*\)
    and \((-\infty)* s/T^*=-\infty\)) as follows:
    \begin{equation*}
    \nu(s)=
    \begin{cases}
    -\infty&s=0\\
    s/T^*&\text{otherwise}
    \end{cases}
    \end{equation*}
    Then \nu is a valuation of the field \(S\), i.e., \(\forall x,y\in S\),
    1. [@1] \(\nu(x\cdot y)=\nu(x)*\nu(y)\)
    2. \(\nu(x+y)\le\max(\nu(x),\nu(y))\)

       Suppose \(x,y\neq 0\) and \(\nu(x)\le\nu(y)\), then \(\frac{x}{y}\in T\), \(1+\frac{x}{y}\in T\) and
       therefore \(\nu(x+y)\le\nu(y)\).
       Since \(\frac{\frac{x}{y}}{\frac{x}{y}+1}\in T\), \(\frac{x}{x+y}\in T\) and so \(\nu(x+y)\ge\nu(y)\).
    3. \(\nu(x)\neq\nu(y)\Rightarrow\nu(x+y)=\max(\nu(x),\nu(y))\)


    Since \(f\) is semi-algebraic, by Lemma ref:B2.5.2, there exists a
    non-zero polynomial \(P(X,Y)\in R[X,Y]\) s.t. \(R\vDash\forall x(P(x,f(x))=0)\). So \(S\vDash\forall x(P(x,f(x))=0)\)
    and, in particular, \(P(a,f(a))=0\). The polynomial \(P(X,Y)\) is of the form
    \begin{equation*}
    P(X,Y)=\sum_{i=1}^nr_i\cdot X^{k_i}\cdot Y^{l_i}
    \end{equation*}
    for some \(n\in\N_+\), \(r_i\in R\setminus\{0\}\) and \(k_i,l_i<\omega\) s.t. \(\la k_i,l_i\ra\neq\la k_j,l_j\ra\) for
    every \(i\neq j\in\{1,\dots,n\}\). Thus
    \begin{equation*}
    0=\sum_{i=1}^nr_i\cdot a^{k_i}\cdot f(a)^{l_i}
    \end{equation*}
    and for some \(i\neq j\in\{1,\dots,n\}\) we have that
    \begin{equation*}
    \nu(r_i\cdot a^{k_i}\cdot f(a)^{l_i})=\nu(r_j\cdot a^{k_j}\cdot f(a)^{l_j})\neq-\infty
    \end{equation*}
    since \(f(a)\neq 0\) (if \(f(a)=0\), then \(f:R\to R\) would be ultimately equal to 0)

    This implies that \(\nu(\frac{r_i}{r_j}\cdot a^{k_i-k_j}\cdot f(a)^{l_i-l_j})=\bone\)
    and \(\nu(a^{k_i-k_j}\cdot f(a)^{l_i-l_j})=\bone\). So \(a^{k_i-k_j}\cdot f(a)^{l_i-l_j}\in T^*\). If \(l_i=l_j\),
    then \(k_i\neq k_j\) and \(a^{k_i-k_j}\in T^*\), which implies that \(a\in T^*\), a contradiction.

    So \(l_i\neq l_j\). Let \(q=-\frac{k_i-k_j}{l_i-l_j}\in\Q\) we obtain \(\frac{f(a)}{a^q}\in T^*\).
    Therefore \(\frac{1}{r}<\abs{\frac{f(a)}{a^q}}<r\) for some \(r\in R\). If \(b\in S\) and \(b>a\),
    then \(\tp(a/R)=\tp(b/R)\). Hence for every \(b>a\) we have
    that \(\frac{1}{r}<\abs{\frac{f(b)}{b^q}}<r\) and consequently
    \begin{equation*}
    S\vDash\exists y\forall x(x>y\to\frac{1}{r}<\abs{\frac{f(x)}{x^q}}<r)
    \end{equation*}
    As \(R\prec S\), this implies that \(\frac{1}{r}<\abs{\frac{f(x)}{x^q}}<r\) for all sufficiently
    large \(x\in R\). By the o-minimality of \(R\), for some \(c\in R\) with \(\frac{1}{r}\le\abs{c}\le r\)
    we have that \(\lim_{x\to+\infty}\frac{f(x)}{x^q}=c\), which finishes the proof
    #+END_proof

    #+ATTR_LATEX: :options [3.5.6]
    #+BEGIN_theorem
    label:3.5.6
    Assume \((R,<,+,\cdot)\) is a pure real closed field. Let
    \begin{equation*}
    f(x)=\sum_{i=1}^ma_i\cdot x^{p_i}\quad\text{ and }\quad g(x)=\sum_{j=1}^nb_j\cdot x^{q_j}
    \end{equation*}
    where \(m,n\in\N_+\), \(a_1,\dots,a_m,b_1,\dots,b_n\in R\), \(a_1,b_1>0\), \(p_1>\dots>p_m\in\Q\) and \(q_1>\dots>q_n\in\Q\). TFAE
    1. \(f\ll f+g\)
    2. \(q_1>\max(0,p_1-1)\)
    #+END_theorem

    #+BEGIN_proof
    Goal: Ultimately, for each \(M\in R\), \(x^{p_1}+x^{q_1}\ge (x+M)^{p_1}+M\). Then
    ultimately, \(x^{q_1}\ge k(M)\cdot x^{p_1-1}+M\) for some constant \(k\) relevant to \(M\).

    We define a rate of growth \(gr(f)\) of a definable map \(f:R\to R\) as follows:
    if \(f(x)\approx c\cdot x^q\) for some \(c\in R\setminus\{0\}\) and \(q\in\Q\), then \(gr(f)=q\) (Lemma ref:3.5.5 implies
    that \(gr(f)\) is well defined for each ultimately non-zero definable function \(f:R\to R\))
    and \(gr(f)=0\) otherwise.
    \begin{equation*}
    gr(f)=
    \begin{cases}
    q&\exists c\in R\setminus\{0\}\exists q\in\Q\text{ s.t. }f(x)\approx c\cdot x^q\\
    0&\text{otherwise}
    \end{cases}
    \end{equation*}
    Then \(gr(f\cdot g)=gr(f)+gr(g)\) and \(gr(f+g)=\max(gr(f),gr(g))\) provided \(gr(f)\neq gr(g)\)

    First, we prove that \((x+c)^q-x^q\approx c\cdot q\cdot x^{q-1}\) for every \(c\in R\setminus\{0\}\) and \(q\in\Q_+\).

    Let \(q=\frac{p}{p'}\) where \(p,p'\in\Z_+\). For each \(x\in R_+\) let \(\Delta(x)=(x+c)^q-x^q\) and note
    that \(\lim_{x\to+\infty}(\Delta(x)\cdot x^{-q})=0\), which implies that \(gr(\Delta(x))<q\).
    Since \((x+c)^p=(\Delta(x)+x^q)^{p'}\), we have that
    \begin{equation*}
    \sum_{i=0}^p\binom{p}{i}\cdot x^i\cdot c^{p-i}=\sum_{i=0}^{p'}\binom{p'}{i}\cdot\Delta(x)^i\cdot(x^q)^{p'-i}
    \end{equation*}
    and
    \begin{equation*}
    L(x)=\sum_{i=0}^{p-1}\binom{p}{i}\cdot x^i\cdot c^{p-i}=\sum_{i=1}^{p'}\binom{p'}{i}\cdot\Delta(x)^i\cdot(x^q)^{p'-i}=R(x)
    \end{equation*}
    Obviously, \(gr(L(x))=gr(\binom{p}{p-1}\cdot x^{p-1}\cdot c)=p-1\). On the other hand,
    since \(gr(\Delta(x))<q\), we have that
    \begin{equation*}
    gr(R(x))=gr(\binom{p'}{1}\cdot\Delta(x)\cdot(x^q)^{p'-1})=gr(\Delta(x))+q\cdot(p'-1)
    \end{equation*}
    Thus \(gr(\Delta(x))=p-1-q\cdot(p'-1)=q-1\) and \(\Delta(x)\approx c\cdot q\cdot x^{q-1}\)

    \(1\Rightarrow 2\): We see that \(q_1>0\) because otherwise for some \(c\in R\) we would have
    that \(\abs{g(x)}\le c\) for large \(x\in R\) and consequently \(f\sim f+g\). Now if \(p_1-1\le 0\),
    then \(q_1>p_1-1\), which finishes the proof. So we can assume \(p_1>1\)

    We know that \(f(x)<f(x)+g(x)\) for all sufficiently large \(x\in R\) and the set
    \begin{equation*}
    A_f^{f+g}=\{\la x,y\ra\in R\times R:x> 0\wedge f(x)<y\wedge y<f(x)+g(x)\}
    \end{equation*}
    is weak generic in \((R\times R,+)\). By Theorem ref:3.3.4, for every \(M\in R_+\) there
    exist \(x_M,y_M\in R\) s.t.
    \begin{equation*}
    \{\la x,y\ra\in R\times R:x_M<x\wedge x<x_M+M\wedge y_M<y\wedge y<y_M+M\}\subseteq A_f^{f+g}
    \end{equation*}
    This implies that \(f(x_M)+g(x_M)\ge f(x_M+M)+M\) for all sufficiently large \(M\in R\). Note
    that \(\lim_{M\to+\infty}x_M=+\infty\)

    Put \(M_0=\frac{b_1+1}{a_1p_1}\). Then still for all sufficiently large \(M\in R\) we have
    that \(f(x_M)+g(x_M)\ge f(x_M+M_0)+M_0\) and by the o-minimality
    of \((R,<,+,\cdot)\), \(f(x)+g(x)\ge f(x+M_0)+M_0\) for all sufficiently large \(x\in R\). So ultimately
    \begin{equation*}
    \sum_{i=1}^ma_i\cdot x^{p_i}+\sum_{j=1}^nb_j\cdot x^{q_j}\ge M_0+\sum_{i=1}^ma_i\cdot(x+M_0)^{p_i}
    \end{equation*}
    and
    \begin{equation*}
    \sum_{j=1}^nb_j\cdot x^{q_j}\ge M_0+\sum_{i=1}^ma_i\cdot((x+M_0)^{p_i}-x^{p_i})
    \end{equation*}
    Finally, comparing the ingredients of the sums with the biggest value of gr we see that
    ultimately
    \begin{equation*}
    b_1\cdot x^{q_1}\ge a_1\cdot((x+M_0)^{p_1}-x^{p_1})\approx a_1\cdot M_0\cdot p_1\cdot x^{p_1-1}=(b_1+1)\cdot x^{p_1-1}
    \end{equation*}
    Hence \(q_1>p_1-1\)

    \(2\Rightarrow 1\): Fix \(M\in R_+\). Since \(q_1>\max(0,p_1-1)\), similar as above, we can show that for all
    sufficiently large \(x\in R\)
    \begin{equation*}
    \sum_{i=1}^ma_i\cdot x^{p_i}+\sum_{j=1}^nb_j\cdot x^{q_j}\ge M+\sum_{i=1}^ma_i\cdot(x+M)^{p_i}
    \end{equation*}
    This means that ultimately \(f(x)+g(x)\ge f(x+M)+M\). Choose \(x_M\in R_+\) satisfying the latter
    inequality and s.t. \(f\) and \(g\) are increasing on the interval \((x_M,+\infty)\). Then
    for \(y_M=f(x_M+M)\) we have that
    \begin{equation*}
    \{\la x,y\ra\in R\times R:x_M<x\wedge x<x_M+M\wedge y_M<y\wedge y<y_M+M\}\subseteq A^{f+g}_f
    \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options [3.5.7]
    #+BEGIN_examplle
    label:3.5.7
    Let \((R,<,+,\cdot)\) be a pure real closed field and for \(a\in\R_+\setminus\Q\) let
    \begin{equation*}
    p(x,y)=\{x>r:r\in R\}\cup\{y>x^q:a>q\in\Q\}\cup\{y<x^q:a<q\in\Q\}
    \end{equation*}
    We shall prove that \(p\) is a stationary (complete) weak generic type in the group \((R,+)\times(R,+)\)
    and \(p\) is not of the form \(p_f^-\) or \(p_f^+\) for any definable \(f:R\to R\)

    The weak genericity of \(p\) follows from Theorem ref:3.5.6. Indeed, the set
    \begin{equation*}
    \{\la x,y\ra\in R\times R:x>r\wedge y>x^{q_1}\wedge y<x^{q_2}\}
    \end{equation*}
    is weak generic in \((R,+)\times(R,+)\) since \(q_2>\max(0,q_1-1)\)

    The stationary (and the completeness) of \(p\) follows from Lemma ref:3.5.5. Namely, if \(p\)
    were non-stationary, then for some \(S\succ R\) and definable \(f:S\to S\) we would have that
    ultimately \(f(x)>x^q\) for each \(q\in\Q\cap(-\infty,a)\) and ultimately \(f(x)<x^q\) for
    each \(q\in\Q\cap(a,+\infty)\). By Lemma ref:3.5.5, \(f(x)\approx c\cdot x^q\) for some \(q\in\Q\) and \(c\in S_+\)
    (\(c>0\) since \(f\) is ultimately increasing). Assume that \(q>a\) and take any \(r\in\Q\cap(a,q)\).
    Then ultimately \(f(x)>x^r\) (since \(q>r\)). On the other hand, ultimately \(f(x)<x^r\)
    (since \(r\in\Q\cap(a,+\infty)\)). If \(q<a\), then we reach a contradiction in a similar way. As a
    result, \(p\) is stationary (and complete) <<Problem6>>

    Suppose \(p(x,y)=p'(x,y)\) for some definable function \(f:R\to R\) and a type
    \(p'(x,y)\in\{p_f^-(x,y),p_f^+(x,y)\}\). Then \(f(x)\approx c\cdot x^q\) for some \(q\in\Q\) and \(c\in R_+\).
    W.L.O.G., \(q>a\). Take any \(r\in\Q\cap(a,q)\). Then \((y<x^r)\in p(x,y)\) and \((y>x^r)\in p'(x,y)\), a
    contradiction.
    #+END_examplle

    #+ATTR_LATEX: :options [3.5.8]
    #+BEGIN_examplle
    label:3.5.8
    Let \((R,<,+,\cdot,\dots)\) be an o-minimal polynomially bounded expansion of a real closed
    field \((R,<,+,\cdot)\) and for \(q_0\in\Q_+\) let
    \begin{equation*}
    p(x,y)=\{x>r:r\in R\}\cup\{y>r\cdot x^{q_0}:r\in R\}\cup\{y<x^q:q_0<q\in\Q\}
    \end{equation*}
    We shall prove that \(p\) is a non-stationary complete weak generic type in the
    group \((R,+)\times(R,+)\)

    It \(p\) were not complete, then we could find a definable function \(f:R\to R\) s.t.
    ultimately \(f(x)<x^q\) for each \(q\in\Q\cap(q_0,+\infty)\) and ultimately \(f(x)>r\cdot x^{q_0}\) for
    each \(r\in R\) (thus \(\lim_{x\to+\infty}\frac{f(x)}{x^{q_0}}=+\infty\)). By Remark
    ref:3.5.2, \(\frac{f(x)}{x^{q_0}}\ge\sqrt[n]{x}\) for some \(n\in\N_+\) and all sufficiently
    large \(x\in R\). But then ultimately \(f(x)\ge x^{q_0+\frac{1}{n}}\), a contradiction.

    To obtain non-stationarity of \(p\), let \(S\) be an \(\abs{R}^+\)-saturated elementary extension
    of \(R\) and choose any \(a\in S\) s.t. \(a>r\) for every \(r\in R\). Then
    \begin{equation*}
    \{x>r:r\in R\}\cup\{y>r\cdot x^{q_0}:r\in R\}\cup\{y<x^q:q_0<q\in\Q\}\cup\{y<a\cdot x^{q_0}\}
    \end{equation*}
    and
    \begin{equation*}
    \{x>r:r\in R\}\cup\{y>r\cdot x^{q_0}:r\in R\}\cup\{y<x^q:q_0<q\in\Q\}\cup\{y>a\cdot x^{q_0}\}
    \end{equation*}
    are two distinct extensions of \(p\) to weak generic types in \((S,+)\times(S,+)\)

    #+END_examplle
    In \(\RCF\), we can approximate the definable function .

*** Weak generic types in \texorpdfstring{\((\R,+)\times(\R,+)\)}{R^2}
    Now we give a description of complete (over \(\R\)) weak generic types in the
    group \((\R,+)\times(\R,+)\) derived in the theory \(\Th(\R,<,+,\cdot)\).

    Let \(S\) be a \((2^{\aleph_0})^+\)-saturated elementary extension of the field of reals.
    Choose \(a\in S\) s.t. \(a>r\) for every \(r\in\R\). Let \(b_0\in S\) be s.t. \(b_0\neq\sum_{i=1}^nr_i\cdot a^{q_i}\)
    for all \(n\in\N_+\), \(r_i\in\R\) and \(q_i\in\Q\) (in this case we say that \(b_0\) is non-polynomial over
    \(a\)). We describe a recursive procedure of defining \(b_1,b_2,\dots\in S\setminus\{0\}\), \(r_1,r_2,\dots\in\R\setminus\{0\}\)
    and \(q_1,q_2,\dots\in\Q_+\) so that \(q_1>q_2>\dots\) and \(b_n=b_0-r_1\cdot a^{q_1}-\dots-r_n\cdot a^{q_n}\) for
    every \(n\in\N_+\).

    First we define \(b_1,r_1\) and \(q_1\). We consider two cases, depending on whether \(b_0\) is
    positive or negative.

    * *Case P*. \(b_0>0\). Consider the following subsets of \(\Q_+\):
        \begin{align*}
        A&=\{q\in\Q_+:(\forall r\in\R_+)b_0>r\cdot a^q\}\\
        B&=\{q\in\Q_+:(\forall r\in\R_+)b_0<r\cdot a^q\}
        \end{align*}
        The sets \(A\) and \(B\) are disjoint and there is a unique \(c\in\R_{\ge 0}\cup\{+​\infty\}\)
        s.t. \(A\subseteq(0,c]\), \(B\subseteq[c,+\infty)\) and \(\Q_+\cup\{c\}=A\cup B\cup\{c\}\). We
        define \(b_1,r_1,q_1\) only in the case where the following condition holds:
        \begin{equation*}
        c\in\Q_+,A=\Q_+\cap(0,c),B=\Q_+\cap(c,+\infty)\tag{\(\dagger\)}
        \end{equation*}
        Otherwise the procedure stops and no \(b_1,r_1,q_1\) are defined

        If (\(\dagger\)) holds, then we put \(q_1=c\). We have that \(r'\cdot a^{q_1}<b_0<r''\cdot a^{q_1}\) for
        some \(r'<r''\in\R_+\). Since the ordering \((\R,<)\) is Dedekind complete, there exists a
        unique \(r\in\R_+\) s.t. for every \(r',r''\in\R_+\) with \(r'<r<r''\) we have
        that \(r'\cdot a^{q_1}<b_0<r''\cdot a^{q_1}\). We put \(r_1=r\) and \(b_1=b_0-r_1\cdot a^{q_1}\).

    * *Case N*. \(b_0<0\). Here we proceed similarly. Consider the following subsets of \(\Q_+\):
        \begin{align*}
        &A=\{q\in\Q_+:(\forall r\in\R_-)b_0<r\cdot a^q\}\\
        &B=\{q\in\Q_+:(\forall r\in\R_-)b_0>r\cdot a^q\}
        \end{align*}
        The sets \(A\) and \(B\) are disjoint and there is a unique \(c\in\R_{\ge 0}\cup\{+\infty\}\)
        s.t. \(A\subseteq(0,c]\), \(B\subseteq[c,+\infty)\) and \(\Q_{​+}\cup\{c\}=A\cup B\cup\{c\}\). We define \(b_1,r_1\) and \(q_1\) only in
        the case where (\(\dagger\)) holds. Otherwise the procedure stops and no \(b_1,r_1\) and \(q_1\) are
        defined.

        If (\(\dagger\)) holds, then we put \(q_1=c\). We have that \(r'\cdot a^{q_1}<b_0<r''\cdot a^{q_1}\) for
        some \(r'<r''\in\R_-\). Since the ordering \((\R,<)\) is Dedekind complete, there exists a
        unique \(r\in\R_-\) s.t. for every \(r',r''\in\R_-\) with \(r'<r<r''\) we have
        that \(r'\cdot a^{q_1}<b_0<r''\cdot a^{q_1}\). We put \(r_1=r\) and \(b_1=b_0-r_1\cdot a^{q_1}\).

    \begin{center}
      \begin{tikzpicture}
        \draw[->] (0, 0) -- (2.2, 0) node[right] {$\mathbb{Q}$};
        \draw[->] (0, -2) -- (0, 2) node[above] {$S$};
        \node at (1.3,1) {\(b_{0}\)};
        \node at (1.3,-1) {\(b_{0}\)};
        \node at (1,1) {\textbullet};
        \node at (1,1) {\textbullet};
        \node at (1,0) {\textbullet};
        \node at (1,-1) {\textbullet};
        \node at (1.3,0.5) {\(A\)};
        \node at (1.6,-0.2) {\(c=q_1\)};
        \node at (1.3,1.7) {\(B\)};
        \node at (1.3,-1.7) {\(B\)};
        \draw[-] (1,0.8) -- (1,-0.8);
        \draw[-] (1,1.2) -- (1,2);
        \draw[-] (1,-1.2) -- (1,-2);
      \end{tikzpicture}
    \end{center}

    Suppose  \(b_i,r_i\) and \(q_i\) have been defined so that \(b_i\neq 0\). Again we consider two cases,
    depending on whether \(b_i\) is positive or negative.

    * *Case P*. \(b_i>0\). We define the sets \(A,B\) and \(c\in\R_{\ge 0}\cup\{+\infty\}\) as in the case of \(b_0>0\).
        Again, if (\(\dagger\)) fails, then the procedure stops and \(b_j,r_j,q_j\) are not defined for
        any \(j>i\). If (\(\dagger\)) holds, then we put \(q_{i+1}=c\) and define \(r_{i+1}\), \(b_{i+1}\)
        analogously as in the case of \(b_0\).

    * *Case N*. \(b_i<0\). Similar.

    If \(b_1,\dots,b_i,q_1,\dots,q_i\) and \(r_1,\dots,r_i\) are defined, then \(q_1>\dots>q_i\). We shall only prove
    that \(q_1>q_2\). We have that
    \begin{equation*}
    b_2=b_1-r_2\cdot a^{q_2}=b_0-r_1\cdot a^{q_1}-r_2\cdot a^{q_2}
    \end{equation*}
    W.L.O.G., we can assume that \(r_2>0\). Choose any real number \(r\in(0,r_2)\).
    Then \(b_1>r\cdot a^{q_2}\). If \(q_1\le q_2\), then also \(b_1>r\cdot a^{q_1}\) and
    consequently \(b_0=b_1+r_1\cdot a^{q_1}>(r_1+r)\cdot a^{q_1}\), which contradicts the definition of \(r_1\).
    Hence \(q_1>q_2\).

    Secondly, note that \(b_k\neq 0\) for every \(k\in\{1,\dots,i\}\). Otherwise we would have that
    \begin{equation*}
    b_k=b_0-r_1\cdot a^{q_1}-\dots-r_n\cdot a^{q_n}=0
    \end{equation*}
    and \(b_0\) would be polynomial over \(a\), a contradiction.

    Now we are able to give a description of complete weak generic types in the
    group \((\R,+)\times(\R,+)\) (which implies that \(b_0\) is non-polynomial over \(a\)) and \(a>0\)
    (hence \(a>r\) for every \(r\in\R\)). Denote the type \(\tp(\la a,b_0\ra/\R)\) by \(p(x,y)\) and note
    that \(\{x>r:r\in\R\}\subseteq p(x,y)\).

    * *Case A*. Assume that no \(b_i\) are defined for \(i>0\).

      This happens only if (\(\dagger\)) fails. We
      shall consider one by one all possible cases. It turns out that each of these cases determines
      uniquely the weak generic type \(\tp(\la a,b_0\ra/\R)\).

      First, we consider the situation where \(b_0>0\). Let \(A,B\) be as in Case P.
      * *Case 1*. /\(A=\Q_+\cap(0,c)\) and \(B=\Q_+\cap(c,+\infty)\) for some \(c\in\R_+\setminus\Q\)/.

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y>x^q:q\in\Q\cap(0,c)\}\cup\{y<x^q:q\in\Q\cap(c,+\infty)\}
        \end{equation*}
        to a complete weak generic type over \(\R\). Every weak generic type of this form is
        stationary. (Example ref:3.5.7)
      * *Case 2*. /\(A=\Q_+\cap(0,q]\) and \(B=\Q_+\cap(q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y>r\cdot x^q:r\in\R_+\}\cup\{y<x^{q'}:q'\in\Q\cap(q,+\infty)\}
        \end{equation*}
        to a complete weak generic type over \(\R\). Every weak generic type of this form is
        non-stationary. (Example ref:3.5.8)
      * *Case 3.* /\(A=\Q_+\cap(0,q)\) and \(B=\Q_+\cap[q,+\infty)\) for some \(q\in\Q_+\)/.

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y>x^{q'}:q'\in\Q\cap(0,q)\}\cup\{y<r\cdot x^q:r\in\R_+\}
        \end{equation*}
        to a complete weak generic type over \(\R\). Every weak generic type of this form is
        non-stationary.
      * *Case 4*. /\(A=\emptyset\) and \(B=\Q_+\)/.

        Since \(p(x,y)\) is weak generic and \(b_0>0\), we also have that \(b_0>r\) for
        every \(r\in\R\). Therefore \(p(x,y)=p_z^+(x,y)\) where \(z:\R\to\R\), \(z(r)=0\) for all \(r\in\R\).
        By Theorem ref:3.4.7, \(p(x,y)\) is stationary.
        <<Problem9>>
      * *Case 5*. /\(A=\Q_+\) and \(B=\emptyset\)./

        Then \(p(x,y)=p_{+\infty}(x,y)\). By Theorem ref:3.4.7, \(p(x,y)\) is
        stationary.
      If \(b_0<0\), then we get the following cases.
      * *Case 1'*. /\(A=\Q_+\cap(0,c)\) and \(B=\Q_+\cap(c,+\infty)\) for some \(c\in\R_+\setminus\Q\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y<-x^q:q\in\Q\cap(0,c)\}\cup\{y>-x^q:q\in\Q\cap(c,+\infty)\}
        \end{equation*}
        to a complete weak generic type over \(\R\).
      * *Case 2'*. /\(A=\Q_+\cap(0,q]\) and \(B=\Q_+\cap(q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y<r\cdot x^q:r\in\R_-\}\cup\{y>-x^{q'}:q'\in\Q\cap(q,+\infty)\}
        \end{equation*}
        to a complete weak generic type over \(\R\).
      * *Case 3'.* /\(A=\Q_+\cap(0,q)\) and \(B=\Q_+\cap[q,+\infty)\) for some \(q\in\Q_+\)/.

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y<-x^{q'}:q'\in\Q\cap(0,q)\}\cup\{y>r\cdot x^q:r\in\R_-\}
        \end{equation*}
        to a complete weak generic type over \(\R\).
      * *Case 4'*. /\(A=\emptyset\) and \(B=\Q_+\)./

        Since \(p(x,y)\) is weak generic and \(b_0<0\), we also have
        that \(b_0<r\) for every \(r\in\R\). Therefore \(p(x,y)=p_z^-(x,y)\) where \(z:\R\to\R\) is
        constantly equal to 0.
      * *Case 5'*. /\(A=\Q_+\) and \(B=\emptyset\)/.

        Then \(p(x,y)=p_{-\infty}(x,y)\)
    * *Case B*. Now assume that for \(a\) and \(b_0\) with \(\tp(\la a,b_0\ra/\R)\) weak generic the
      procedure breaks down at some finite step so that \(b_i,r_i\) and \(q_i\) are defined only
      for \(i\in\{1,\dots,n\}\). This means that in the condition (\(\dagger\)) fails at step \(n\).
      Let \(f(x)=\sum_{i=1}^nr_i\cdot x^{q_i}\) and recall that \(r_i\in\R\setminus\{0\}\), \(q_i\in\Q_+\) and \(q_1>\dots>q_n\).

      First we consider the situation where \(b_n>0\). Let \(A,B\) be as in Case P.
      * *Case 1*. /\(A=\Q_+\cap(0,c)\) and \(B=\Q_+\cap(c,+\infty)\) for some \(c\in\R_+\setminus\Q\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{align*}
        r(x,y)=&\{x>r:r\in\R\}\cup\{y-f(x)>x^q:q\in\Q\cap(0,c)\}\cup\\
        &\{y-f(x)<x^q:q\in\Q\cap(c,+\infty)\}
        \end{align*}
        to a complete weak generic type over \(\R\). Moreover, \(c>q_1-1\) and \(c<q_n\) (definition).
        #+LATEX: \wu{
        For each \(p_1\in\Q\cap(c,+\infty)\) and \(p_2\in\Q\cap(0,c)\), ultimately, for each \(M\in\R_+\), we want
        \(x^{p_1}+x^{q_1}\ge(x+M)^{q_1}+(x+M)^{p_2}+M\), which is equivalent to
        \(x^{p_1}\ge k(M)x^{q_1-1}\) and \(p_1>q_1-1\). Therefore \(c>q_1-1\).
        #+LATEX: }
        <<Problem8>>
      * *Case 2*. /\(A=\Q_+\cap(0,q]\) and \(B=\Q_+\cap(q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f(x)>r\cdot x^q:r\in\R_+\}\cup\\
        \{y-f(x)<x^{q'}:q'\in\Q\cap(q,+\infty)\}
        \end{gather*}
        to a complete weak generic type over \(\R\). Moreover, \(q\ge q_1-1\)
        #+LATEX: \wu{
        since \(q'>q_1-1\) for any \(q'>q\)
        #+LATEX: }
        and \(q<q_n\).
        If \(q=q_1-1\), then \(p(x,y)\) is stationary (since then \(f(x)+r\cdot x^q\sim f(x)\) and
        \(p(x,y)=p_f^+(x,y)\)).
        If \(q>q_1-1\), then \(p(x,y)\) is non-stationary. (Example ref:3.5.8)
      * *Case 3*. /\(A=\Q_+\cap(0,q)\) and \(B=\Q_+\cap[q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f(x)>x^{q'}:q'\in\Q\cap(0,q)\}\cup\\
        \{y-f(x)<r\cdot x^q:r\in\R_+\}
        \end{gather*}
        to a complete weak generic type over \(\R\). Moreover, \(q>q_1-1\) and \(q<q_n\). Every weak
        generic type of this form is non-stationary.
      * *Case 4*. /\(A=\emptyset\) and \(B=\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y-f(x)>0\}\cup\{y-f(x)<x^q:q\in\Q_+\}
        \end{equation*}
        to a complete weak generic type over \(\R\). Moreover, \(q_1\le 1\) and \(p(x,y)=p_f^+(x,y)\). By
        Theorem ref:3.4.7, \(p(x,y)\) is stationary.
      * *Case 5.* /\(A=\Q_+\) and \(B=\emptyset\)./

        Then \(p(x,y)\) contains the following set of formulas
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y-f(x)>x^q:q\in\Q_+\}
        \end{equation*}
        Take any rational \(q>q_1\). Then \((y-f(x)>x^q)\in p(x,y)\), which implies
        that \(b_0-f(a)>a^q\). Hence
        \begin{equation*}
        b_0>a^q+\sum_{i=1}^n\cdot a^{q_i}
        \end{equation*}
        which contradicts the choice of \(q_1\). So case 5 can not hold.
      If \(b_n<0\), then we get the following cases: Let \(A,B\) be as in Case N.
      * *Case 1'*. /\(A=\Q_+\cap(0,c)\) and \(B=\Q_+\cap(c,+\infty)\) for some \(c\in\R_+\setminus\Q\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f(x)<-x^q:q\in\Q\cap(0,c)\}\cup\\
        \{y-f(x)>-x^q:q\in\Q\cap(c,+\infty)\}
        \end{gather*}
        to a complete weak generic type over \(\R\). Moreover, \(c>q_1-1\) and \(c<q_n\).
      * *Case 2'*. /\(A=\Q_+\cap(0,q]\) and \(B=\Q_+\cap(q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f(x)<r\cdot x^q:r\in\R_-\}\cup\\
        \{y-f(x)>-x^{q'}:q'\in\Q\cap(q,+\infty)\}
        \end{gather*}
        to a complete weak generic type over \(\R\). Moreover, \(q\ge q_1-1\) and \(q<q_n\).
        If \(q=q_1-1\), then \(p(x,y)=p_f^-(x,y)\).
      * *Case 3'*. /\(A=\Q_+\cap(0,q)\) and \(B=\Q_+\cap[q,+\infty)\) for some \(q\in\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f(x)<-x^{q'}:q'\in\Q\cap(0,q)\}\cup\\
        \{y-f(x)>r\cdot x^q:r\in\R_-\}
        \end{gather*}
        to a complete weak generic type over \(\R\). Moreover, \(q>q_1-1\) and \(q<q_n\).
      * *Case 4'*. /\(A=\emptyset\) and \(B=\Q_+\)./

        Then \(p(x,y)\) is the only extension of the type
        \begin{equation*}
        \{x>r:r\in\R\}\cup\{y-f(x)<0\}\cup\{y-f(x)>-x^q:q\in\Q_+\}
        \end{equation*}
        to a complete weak generic type over \(\R\). Moreover, \(q_1\le 1\) and \(p(x,y)=p_f^-(x,y)\).
      * *Case 5'*. /\(A=\Q_+\) and \(B=\emptyset\)./

        Impossible.
    * *Case C*. Now assume that for \(a\) and \(b_0\) with \(\tp(\la a,b_0\ra/\R)\) weak generic the
      procedure never stops and we have defined \(b_i,r_i\) and \(q_i\) for all \(i\in\N_+\).

      Recall that \(b_i\in S\setminus\{0\}\), \(r_i\in\R\setminus\{0\}\), \(q_i\in\Q_+\), \(q_1>q_2>\dots\) and for every \(i\in\N_+\) we have
      that \(b_i=b_0-r_1\cdot a^{q_1}-\dots-r_i\cdot a^{q_i}\).

      Let \(f\) be the formal power series \(\sum_{i=1}^{+\infty}r_i\cdot x^{q_i}\) and for each \(n\in\N\)
      let \(f_n(x)=\sum_{i=1}^nr_i\cdot x^{q_i}\) (in particular, \(f_0=0\)). We shall prove that the
      type \(p(x,y)=\tp(\la a,b_0\ra/\R)\) is the only extension of the type \(p_f(x,y)\) to a complete
      weak generic type over \(\R\) where the type \(p_f(x,y)\) is defined as follows:
      \begin{gather*}
        \{x>r:r\in\R\}\cup\{y-f_n(x)>r'\cdot x^{q_{n+1}}:n\in\N\wedge r'\in\R\wedge r'<r_{n+1}\}\cup\\
        \{y-f_n(x)<r''\cdot x^{q_{n+1}}:n\in\N\wedge r''\in\R\wedge r''>r_{n+1}\}
      \end{gather*}
      Then \(p_f(x,y)\subseteq p(x,y)\). Assume that the weak generic types \(p(x,y)=\tp(\la a,b_0\ra/\R)\)
      and \(p'(x,y)=\tp(\la a',b_0'\ra/\R)\) (\(a',b_0'\in S\)) are two distinct extensions of the
      type \(p_f(x,y)\) (hence \(\la a,b_0\ra\) and \(\la a',b_0'\ra\) produce the same formal power
      series \(f=\sum_{i=1}^{+\infty}r_i\cdot x^{q_i}\)). W.L.O.G., we can assume that \(a=a'\).

      Since \(p\neq p'\), there exists a definable (and thus semi-algebraic) function \(g:\R\to\R\)
      s.t. \((y<g(x))\in p\) and \((y>g(x))\in p'\). We shall prove that the map \(g\) can be replaced
      with the map of the form \(h(x)=\sum_{i=1}^ns_i\cdot x^{p_i}\) where \(n\in\N_+\), \(s_i\in\R\) and \(p_i\in\Q\).

      Random links: [[http://homepages.math.uic.edu/~jan/mcs563s14/puiseux.pdf][link1]], [[https://arxiv.org/pdf/0807.4674.pdf][link2]]

      We know that \(g\) has a Puiseux expansion of the form
      \begin{equation*}
      g(x)=\sum_{i=k}^{+\infty}c_i\cdot x^{\frac{-i}{d}}\tag{\star}
      \end{equation*}

      where \(k\in\Z\), \(d\in\Z_+\) and \(c_i\in\R\) for \(i\ge k\). Equality (\(\star\)) holds for all sufficiently
      large \(x\in\R\). One can prove that for some \(M\in\R_+\) we obtain ultimately
      \begin{equation*}
      \abs{g(x)-\sum_{i=k}^{-1}c_i\cdot x^{\frac{-i}{d}}}\le M
      \end{equation*}
      Let \(h(x)=\sum_{i=k}^{-1}c_i\cdot x^{\frac{-i}{d}}\). Then still \((y<h(x))\in p\)
      and \((y>h(x))\in p'\), which means that \(b_0<h(a)\) and \(b_0'>h(a)\).

      Choose unique \(n\in\N_+\), \(s_i\in\R\setminus\{0\}\) and \(p_i\in\Q_+\) s.t.
      (ultimately) \(h(x)=\sum_{i=1}^ns_i\cdot x^{p_i}\) and \(p_1>\dots>p_n\). Then for each \(i\in\{1,\dots,n\}\) we have
      that \(p_i=q_i\) and \(s_i=r_i\). We shall only prove that \(p_1=q_1\) and \(s_1=r_1\).

      In order to show that \(p_1=q_1\), we shall consider several possible cases.
      * If \(p_1<q_1\) and \(r_1>0\), then
        \begin{equation*}
        h(a)=s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}<\frac{r_1}{2}\cdot a^{q_1}<b_0<h(a)
        \end{equation*}
        a contradiction.
        #+LATEX: \wu{
        The first equality is because \(a>\R\) and \(q_1>p_1\) and \(r_1>0\), the
        second holds since \(b_0\) is close to \(r_1\cdot a^{q_1}\).
        #+LATEX: }
      * If \(p_1<q_1\) and \(r_1<0\), then
        \begin{equation*}
        h(a)=s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}>\frac{r_1}{2}\cdot a^{q_1}>b_0'>h(a)
        \end{equation*}
        a contradiction.
      * If \(p_1>q_1\) and \(s_1>0\), then
        \begin{equation*}
        (r_1+1)\cdot a^{q_1}<s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}<b_0'<(r_1+1)\cdot a^{q_1}
        \end{equation*}
      * If \(p_1>q_1\) and \(s_1<0\) then
        \begin{equation*}
        (r_1-1)\cdot a^{q_1}>s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}=h(a)>b_0>(r_1-1)\cdot a^{q_1}
        \end{equation*}
        a contradiction.
      Since \(r_1\neq 0\) and \(s_1\neq 0\), the contradictions above shows that \(p_1=q_1\).

      Suppose \(s_1\neq r_1\):
      * If \(s_1<r_1\), then
        \begin{equation*}
        b_0<h(a)=s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}<\frac{s_1+r_1}{2}\cdot a^{p_1}=\frac{s_1+r_1}{2}\cdot a^{q_1}<b_0
        \end{equation*}
        a contradiction.
      * If \(s_1>r_1\), then
        \begin{equation*}
        b_0'>h(a)=s_1\cdot a^{p_1}+\sum_{i=2}^ns_i\cdot a^{p_i}>\frac{s_1+r_1}{2}\cdot a^{p_1}=\frac{s_1+r_1}{2}\cdot a^{q_1}>b_0'
        \end{equation*}
        a contradiction. Hence \(s_1=r_1\).
      The proof that \(p_i=q_i\) and \(s_i=r_i\) for each \(i\in\{2,\dots,n\}\) is analogous.

      As a result, we obtain
      \begin{gather*}
      (y<\sum_{i=1}^nr_i\cdot x^{q_i})\in p(x,y)\\
      (y>\sum_{i=1}^nr_i\cdot x^{q_i})\in p'(x,y)
      \end{gather*}
      Thus \(b_0<\sum_{i=1}^nr_i\cdot a^{q_i}\) and \(b_0'>\sum_{i=1}^nr_i\cdot a^{q_i}\). We have that
      \begin{equation*}
      b_n=b_0-\sum_{i=1}^nr_i\cdot a^{q_i}<0
      \end{equation*}
      which implies that \(r_{n+1}<0\), and
      \begin{equation*}
      b_n'=b_0'-\sum_{i=1}^nr_i\cdot a^{q_i}>0
      \end{equation*}
      which implies that \(r_{n+1}>0\), a contradiction. Hence \(p_f(x,y)\vdash p(x,y)\).

      By Theorem ref:3.5.6, the sequence of the rational exponents \((q_n)_{n\in\N^+}\) has the
      following property: \(q_n>q_1-1\) for every \(n>1\). Otherwise the formal power series \(f\)
      could not be obtained as a final result of the recursive procedure described above (since the
      type \(\tp(\la a,b_0\ra/\R)=p(x,y)\supseteq p_f(x,y)\) is weak generic and so must be \(p_f(x,y)\)).

      Finally, proceeding as above we can shows that the weak generic type \(p(x,y)\) is stationary.
      The crucial fact needed to prove this is as follows: for every definable (thus semi-algebraic)
      function \(g:S\to S\) there exist a map \(h(x)=\sum_{i=1}^ns_i\cdot x^{p_i}\) (where \(n\in\N\), \(s_i\in\R\) and
      \(p_i\in\Q_+\)) and a constant \(M\in S_+\) s.t. \(\abs{g(x)-h(x)}\le M\) for all sufficiently
      large \(x\).

    If we are given an arbitrary formal power series \(f=\sum_{i=1}^\alpha r_i\cdot x^{q_i}\) (where \(\alpha\in\N\cup\{+\infty\}\),
    \(r_i\in\R\setminus\{0\}\), \(q_i\in\Q_+\) and \(q_1>q_2>\dots\)), then in each of the above cases \(f\) determines a
    unique complete (over \(\R\)) weak generic type in the group \((\R,+)\times(\R,+)\). In this way we have
    described complete weak generic types in \((\R,+)\times(\R,+)\) derived in the theory \(\Th(\R,<,+,\cdot)\).
*** Weak generic types in \texorpdfstring{\((\R,\cdot)\times(\R,\cdot)\)}{R^2}
    Assume \((R,<,+,\cdot,\dots)\) is an o-minimal expansion of an ordered field \((R,<,+,\cdot)\). A *power
    function* is a definable endomorphism of the group \((R_+,\cdot)\). Every power function is
    differentiable on \(R_+\). For each \(r\in R\) there is at most one power function \(f\)
    with \(f'(1)=r\). We denote such a map by \(x^r\) and write \(a^r\) for \(f(a)\). The field
    \begin{equation*}
    K=\{f'(1):f\text{ is a power function}\}\subseteq R
    \end{equation*}
    is called *the field of exponents* of \(R\). We say that the structure \(R\) is *power bounded* if
    for every definable \(f:R\to R\) there exists an \(r\in K\) s.t. ultimately \(\abs{f(x)}\le x^r\). An
    *exponential function* is an isomorphism of the structures \((R,<,+,0)\) and \((R_+,<,\cdot,1)\).

    The main result of [[cite:&miller1996growth]] says that either \(R\) defines (without parameters)
    an exponential function or \(R\) is power bounded and for each ultimately non-zero definable
    function \(f:R\to R\) there exist an \(a\in R\setminus\{0\}\) and a 0-definable power function \(x^r\)
    s.t. \(f(x)\approx a\cdot x^r\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:3.5.9
    If \(R=(R,<,+,\cdot,\dots)\)  is an o-minimal expansion of a real closed field \(R\), TFAE
    1. all complete (over \(R\)) weak generic types in \((R_+,\cdot)\times(R_+,\cdot)\) are stationary,
    2. the structure \(R\) is power bounded.
    #+END_theorem

    #+BEGIN_proof
    \(1\Rightarrow 2\): For the sake of contradiction assume that \(R\) is not power bounded. As we mentioned
    above, this implies that the exponential function \(\exp:R\to R_+\) is 0-definable in \(R\). Thus
    the map
    \begin{equation*}
    (\exp,\exp):(R,+)\times(R,+)\to(R_+,\cdot)\times(R_+,\cdot)
    \end{equation*}
    is a 0-definable isomorphism of groups. Hence the groups \((S,+)\times(S,+)\) and \((S,\cdot)\times(S,\cdot)\) are
    definably isomorphic for every \(S\succ R\) and it suffices to show that some weak generic type
    in \((R,+)\times(R,+)\) is not stationary. To do this, take an arbitrary \(S\succ R\), \(a\in S\setminus R\) and
    let \(f:S\to S\) be s.t. \(f(x)=a\cdot x\) for every \(x\in S\). We shall prove that the weak generic
    types \(p_f^-\) and \(p_f^+\) are extensions of the same complete weak generic type over \(R\).

    Since the structure \(R\) does not need to be \(\aleph_0\)-saturated, Lemma ref:3.2.4 itself is not
    sufficient to ensure that the restrictions of the types \(p_f^-\) and \(p_f^+\) to the complete
    types over \(R\) are weak generic in \((R,+)\times(R,+)\). Nevertheless, this follows from the
    corollary ref:3.3.5

    It is enough to show that \(f\not\sim g\) for each \(g:S\to S\) definable over \(R\). Suppose
    otherwise, then for some \(R\)-definable \(g:S\to S\) we have that \(S\vDash g\sim f\) (note that there is
    a first order formula \(\varphi\in L(S)\) expressing the fact that \(g\sim f\); namely, \varphi says that the
    area defined by the formula \((x>0\wedge f(x)<y\wedge y<g(x))\) doesn't contain arbitrarily large
    squares). So \(S\vDash\exists c(g(x)\sim c\cdot x)\) and \(R\vDash\exists c(g(x)\sim c\cdot x)\). Take \(b\in R\) s.t. \(g(x)\sim b\cdot x\)
    in \(R\). Then \(g(x)\sim b\cdot x\) in \(S\), hence \(f(x)\sim b\cdot x\) and \(a\cdot x\sim b\cdot x\), a contradiction.

    \(2\Rightarrow 1\): Note that it is enough to examine those weak generic types in \((R_+,\cdot)\times(R_+,\cdot)\) which
    contain the formula \((x\ge 1\wedge y\ge 1)\). To prove this, consider \(F,G:R_+\times R_+\to R_+\times R_+\) defined
    as: \(F(x,y)=\la x,\frac{1}{y}\ra\) and \(G(x,y)=\la\frac{1}{x},y\ra\) for every \(x,y\in R_+\). We see
    that \(F,G\) and \(F\circ G\) are 0-definable automorphisms of the group \((R_+,\cdot)\times(R_+,\cdot)\) that map
    the set \(\{\la x,y\ra:x\ge 1\wedge y\ge 1\}\) respectively onto the sets
    1. \(\{\la x,y\ra:x\ge 1\wedge 0<y\le 1\}\)
    2. \(\{\la x,y\ra:0<x\le 1\wedge y\le 1\}\)
    3. \(\{\la x,y\ra:0<x\le 1\wedge 0<y\le 1\}\)

    The same holds for any elementary extension \(S\) of \(R\), which enables us to "translate" an
    example of a non-stationary weak generic type to the set of
    types \([x\ge 1\wedge y\ge 1]=\{p\mid x\ge 1\wedge y\ge 1\in p\}\).

    In order to prove that each complete weak generic type in \((R_+,\cdot)\times(R_+,\cdot)\) containing the
    formula \((x\ge 1\wedge y\ge 1)\) is stationary, we are going to show that for every \(S\succ R\) and every
    definable function \(f:S\to S\cap[1,+\infty)\) we are able to find an \(R\)-definable map \(g:S\to S\) s.t.
    the set
    \begin{equation*}
    \{\la x,y\ra\in S\times S:x\ge 1\wedge y\ge 1\wedge(f(x)\le y\le g(x)\vee f(x)\ge y\ge g(x))\}
    \end{equation*}
    is not weak generic in \((S_+,\cdot)\times(S_+,\cdot)\). So take such \(S\) and \(f\). Let \(a,r\in S\) be
    s.t. \(f(x)\approx a\cdot x^r\). Then \(a>0\) and \(r\ge 0\). The power function \(x^r:S\to S\)
    is \(R\)-definable and we put \(g=x^r\).

    Choose any \(c\in S_+\) s.t. \(\frac{1}{c}\cdot x^r\le f(x)\le c\cdot x^r\) for all sufficiently large \(x\in S\).
    Without loss of generality, we can assume that \(f\) is on the whole interval \([1,+\infty]\) since
    for every \(M\ge 1\) the set \(X_M=[1,M]\times[1,+\infty]\) is not weak generic in \((S_+,\cdot)\times(S_+,\cdot)\)
    (otherwise, by Corollary ref:3.3.3, the set \(X_M\cdot X^{-1}_M=[\frac{1}{M},M]\times S_+\) would be
    generic in \((S_+,\cdot)\times(S_+,\cdot)\), which is not the case)

    Now it suffices to prove that the set
    \begin{equation*}
    X=\{\la x,y\ra\in S\times S:x\ge 1\wedge y\ge 1\wedge\frac{1}{c}\cdot x^r\le y\wedge y\le c\cdot x^r\}
    \end{equation*}
    is not weak generic in \((S_+,\cdot)\times(S_+,\cdot)\). Suppose otherwise, then the set \(X\cdot X^{-1}\) is
    generic in \((S_+,\cdot)\times(S_+,\cdot)\) by Corollary ref:3.3.3. We claim that
    \begin{equation*}
    X\cdot X^{-1}\subseteq Y=\{\la x,y\ra\in S\times S:x>0\wedge\frac{1}{c^2}\cdot x^r\le y\wedge y\le c^2\cdot x^r\}
    \end{equation*}
    To see this, take any \(\la x_1,y_1\ra,\la x_2,y_2\ra\in X\). We have that \(\frac{1}{c}\cdot x_1^r\le y_1\le c\cdot x_2^r\)
    and \(\frac{1}{c}\cdot x_2^r\le y_2\le c\cdot x_2^r\). So
    \begin{equation*}
    \frac{1}{c^2}\cdot\left(\frac{x_1}{x_2}\right)^r\le\frac{y_1}{y_2}\le c^2\cdot\left( \frac{x_1}{x_2} \right)^r
    \end{equation*}
    and \(\la x_1,y_1\ra\cdot\la x_2,y_2\ra^{-1}=\la u,v\ra\) where \(u=\frac{x_1}{x_2}\)
    and \(\frac{1}{c^2}\cdot u^r\le v\le c^2\cdot u^r\). Thus \(u=\frac{x_1}{x_2}\)
    and \(\frac{1}{c^2}\cdot u^r\le v\le c^2\cdot u^r\). Thus \(\la u,v\ra\in Y\) and \(X\cdot X^{-1}\subseteq Y\). In turn, since for
    every \(x\in(0,1)\), \(c^2\cdot x^r\le c^2\), we have that
    \begin{equation*}
    Y\subseteq Z=(S_+\times S_+)\setminus((0,1)\times (c^2,+\infty))
    \end{equation*}
    This implies that the set \(Z\) is generic in \((S_+,\cdot)\times(S_+,\cdot)\), a contradiction.
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(R=(R,<,+,\cdot,\dots)\) is an o-minimal expansion of an archimedean real closed field \(R\), then
    TFAE:
    1. all complete (over \(R\)) weak generic types in \((R_+,\cdot)\times(R_+,\cdot)\) are stationary,
    2. the structure \(R\) is polynomially bounded
    #+END_corollary

    #+BEGIN_proof
    By [[cite:&miller1996growth]], \(R\) is polynomially bounded iff \(R\) is power bounded and \(K\) is
    archimedean. But the field \(K\) is archimedean as a subfield of the archimedean field \(R\).
    The assertion of the corollary immediately follows from Theorem ref:3.5.9
    #+END_proof


* Problems
    | [[Problem1]] | [[Problem2]] |  |

    | ref      | problem               | status |
    |----------+-----------------------+--------|
    | [[Problem3]] |                       | done   |
    | [[Problem4]] |                       | done   |
    | [[Problem5]] |                       | done   |
    | [[Problem6]] | why complete?         | done   |
    | [[Problem7]] | why there only 3?     | done   |
    | [[Problem8]] | condition             | done   |
    | [[Problem9]] | what does S look like |        |

<<bibliographystyle link>>
bibliographystyle:alpha

<<bibliography link>>
bibliography:/Users/wu/notes/references.bib
