#+title: On \(f\)-Generic Types in Presburger Arithmetic

#+EXPORT_FILE_NAME: ../latex/papers/on f-generic types in presburger arithmetic.tex
#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}

* Definable types and f-generics in presburger arithmetic
[[https://people.math.osu.edu/conant.38/Math/presburger_note.pdf][Link]]
** Definable groups and \texorpdfstring{\(f\)}{f}-generics
    Presburger arithmetic: the complete first-order theory of the ordered group of
    integers \((\Z,+,<,0)\).

    Let \(T\) be a complete theory, with a monster model \(M\). We also work with a larger monster
    model \(M^*\) in which we can take realizations of global types over \(M\).

    Suppose \(G=G(M)\) is a definbale group in \(T\), let \(S_G(M)\) denote the space of global
    types containing the formula defining \(G\). Given \(p\in S_G(M)\) and \(g\in G\), we let \(gp\)
    denote the translate \(\{\varphi(g^{-1}x):\varphi(x)\in p\}\) of \(p\).

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(p\in S_G(M)\) be a global \(G\)-type.
    1. \(p\) is *definable (over \(G\))* if, for any formula \(\varphi(\barx,\bary)\) there is a
       formula \(d_p[\varphi](\bary)\) over \(G\) s.t., for any \(\barb\in G\), \(\varphi(\barx,\barb)\in p\)
       iff \(G\vDash d_p[\varphi](\barb)\)
    2. \(p\) is *\(f\)-generic* if, for every formula \(\phi(x)\in p\) there is a small
       model \(M_0\) s.t. no translate \(\phi(gx)\) of \(\phi(x)\) forks over \(M_0\)
    3. \(p\) is *strongly \(f\)-generic* if there is a small model \(M_0\) s.t. no translate \(gp\)
       of \(p\) forks over \(M_0\)
    4. \(p\) is *definably \(f\)-generic* if there is a small model \(M_0\) s.t. every translate
        \(gp\) is definable over \(M_0\)
    #+END_definition

** End extensions of discrete orders
    Assume \(\call\) contains a symbol < and \(T\) extends the theory of linear orders. We say
    that \(T\) is *definably complete* if any nonempty definable subset
    of \(M\), with an upper bound in \(M\), has a least upper bound in \(M\), and similarly for
    lower bounds. Note that this does not depend on the model \(M\).

    If \(T\) is definably complete, and we further assume that \(M\) is discretely ordered by <,
    then it follows that definable subsets of \(M\) contain their least upper bound and greatest
    lower bound. We will say \(T\) is *discretely ordered* to indicate that the ordering < on \(M\) is
    discrete.

    In a totally ordered structure, algebraic closure and definable closure coincide.

    Given a tuple \(\bara\in(M^*)^n\), we let \(M(\bara)=\dcl(M\bara)\).

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Given subsets \(A\subseteq B\) of \(M^*\), we say \(B\) is an *end extension* of \(A\) if, for
    all \(b\in B\setminus A\), either \(b<a\) for all \(a\in A\) or \(b>a\) for all \(a\in A\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:0.3
    Suppose \(T\) is discretely ordered and definably complete. Fix a non-isolated
    type \(p\in S_n(M)\) and a realization \(\bara\) in \(M^*\). If \(M(\bara)\) is not an end
    extension of \(M\) then
    1. \(p\) is not definable
    2. \(p\) has at least two distinct coheirs to \(M^*\)
    #+END_lemma

    #+BEGIN_proof
    Since \(M(\bara)\) is not an end extension of \(M\), we may fix an \(M\)-definable
    function \(f:(M^*)^n\to M^*\), and \(m_1,m_2\in M\) s.t. \(f(\bara)\notin M\) and \(m_1<f(\bara)<m_2\). Define
    the upwards closed set
    \begin{equation*}
    X=\{m\in M:p\vDash f(\bara)<m\}
    \end{equation*}
    Then \(m_1\) and \(m_2\) witness that \(X\) is nonempty and not all of \(M\). If \(X\) has a
    minimal element \(m_0\) and \(m_0^-\) is the immediate predecessor of \(m_0\) in \(M\), then we
    must have \(m_0^-\le f(\bara)<m_0\) and so \(f(\bara)=m_0^-\in M\), which is a contradiction. So \(X\)
    has no minimal element, and therefore cannot be \(M\)-definable. This proves part 1.

    Now define
    \begin{equation*}
    C=\{c\in M^*:m<c<m'\text{ for all }m\in M\setminus X\text{ and }m'\in X\}
    \end{equation*}
    Then \(f(\bara)\in C\), and so \(C\neq\emptyset\). We define the following partial types over \(M^*\):
    \begin{align*}
    q_1&=p\cup\{m<f(\barx)<c:m\in M\setminus X,c\in C\}\\
    q_2&=p\cup\{c<f(\barx)<m:c\in C,m\in X\}
    \end{align*}
    Note that \(q_1\) and \(q_2\) are distinct since \(C\neq\emptyset\). If we can show that they are each
    finitely satisfiable in \(M\), then they will extend to distinct coheirs of \(p\), which proves
    part 2. So we show \(q_1\) is finitely satisfiable in \(M\).

    Fix a formula \(\varphi(\barx)\in p\) and some \(m\in M\setminus X\) (which exists since \(X\) is not all
    of \(M\)) . Set
    \begin{equation*}
    A=\{m'\in f(\varphi(M^n)):m<m'\}
    \end{equation*}
    Then \(A\) is an \(M\)-definable subset of \(M\), which is nonempty since \(\bara\in A(M^*)\).
    Since \(A\) is bounded below by \(m\), we may fix a minimal element \(m_0\in A\). By
    elementarity, \(m_0\) is the minimal element of \(A(M^*)\). In particular, \(m_0<f(\bara)\), and
    so \(m_0\in M\setminus X\). In particular, \(m_0<f(\bara)\), and so \(m_0\in M\setminus X\). By definition
    of \(A\), \(m_0=f(\bara')\) for some \(\bara'\in M^n\) s.t. \(M\vDash\varphi(\bara')\). Altogether, we
    have \(M\vDash\varphi(\bara')\) and \(m<f(\bara')<c\) for any \(c\in C\).
    #+END_proof

    Suppose \(T\) is discretely ordered and definably complete. If, moreover, \(\dcl(\emptyset)\) is
    nonempty, then \(T\) has definable Skolem functions by picking out either the maximal element of
    a definable set or the least element greater than some \(\emptyset\)-definable constant. It follows
    that \(M(\bara)\) is the unique prime model over \(M\bara\). <<Problem3>>
** Presburger arithmetic
    Let \(T=\Th(\Z,+,<,0)\). Let \(G\) denote a sufficiently saturated model of \(T\), and
    let \(G^*\) denote a larger elementary extension of \(G\), which is sufficiently saturated
    w.r.t. \(G\). We treat types over \(G\) as /global types/, but use \(G^*\) as an even larger
    monster model in which we can realize such types.

    Note that \(T\) satisfies the properties discussed above: it is discretely ordered and definably
    complete, with \(\dcl(\emptyset)\) nonempty. Therefore, for \(\bara\in G^*\), \(G(\bara)\) is the prime
    model over \(G\bara\). Recall that \(T\) has quantifier elimination in the expanded language
    \(\call^*=\{+,<,0,1,(D_n)_{n<\omega}\}\) where \(D_n\) is a unary predicate interpreted as \(n\Z\).
    Consequently, given \(\bara\in G^*\), \(G(\bara)\) is the divisible hull of the subgroup
    of \(G^*\) generated by \(G\bara\).  <<Problem4>>

    Given \(a\in G^*\) and \(n>0\), let \([a]_n\in\{0,1,\dots,n-1\}\) be the unique remainder of \(a\)
    modulo \(n\). Given \(\bark\in\Z^n\), we let \(s_{\bark}(\barx)\) denote the definable function
    \(\barx\mapsto k_1x_1+\dots+k_nx_n\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    label:0.4
    1. Let \(G_0\prec G\) be a small model, and fix \(a,b\in G\)
       1. If \(G_0<a<b\) then there is some \(c\in G\) s.t. \(b<c\) and \(a\equiv_{G_0}c\)
       2. If \(a<b<G_0\) then there is some \(c\in G\) s.t. \(c<a\) and \(b\equiv_{G_0}c\)
    2. For any \(p\in S_n(G)\) and \(\bara\vDash p\), if \(G(\bara)\) is not an end extension of \(G\) then
       there are \(h_1,h_2\in G\) and \(\bark\in\Z^n\) s.t. \(h_1<s_{\bark}(\bara)<h_2\)
       and \(s_{\bark}(\bara)\notin G\).
    #+END_proposition

    #+BEGIN_proof
    1. By quantifier elimination and saturation of \(G\) it is enough to fix an integer \(N>0\) and
       find \(c\in G\) s.t. \(b<c\) and \([c]_n=[a]_n\) for all \(0<n\le N\). To find such an element,
       simply note that \(\bigcap_{0<n\le N}nG+[a]_n\) is nonempty as it contains \(a\) and is therefore a
       single coset \(mG+r\) for some \(m,r\in\Z\)(chinese remainder theorem). So we may
       choose \(c=b-[b]_m+m+r\)
    2. By assumption, there is \(b\in\dcl(G\bara)\setminus G\) and \(h_1',h_2'\in G\) s.t. \(h_1'<b<h_2'\). By the
       description of definable closure in Presburger arithmetic, there are
       integers \(r\in\Z^+\), \(\bark\in\Z^n\) and some \(h_0\in G\) s.t. \(rb=s_{\bark}(\bara)+h_0\). Now
       let \(h_i=rh_i'-h_0\).
    #+END_proof
** Definable types in Presburger arithmetic
    Consider the situation where \(G\) is the monster model \(M\), and the definable group
    is \(G^n=\Z^n(G)\), for a fixed \(n>0\), under coordinate addition. In particular.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A type \(p\in S_n(G)\) is *algebraically independent* if for all
    (some) \(\bara\vDash p\), \(a_i\notin G(\bara_{\neq i})\) for all \(1\le i\le n\).
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    label:0.6
    Suppose \(p\in S_n(G)\) is algebraically independent and for all (some) \(\bara\vDash p\), \(G(\bara)\)
    is an end extension of \(G\). Then \(p\) is definable over \(\emptyset\).
    #+END_lemma

    #+BEGIN_proof
    Let \(\Z^n_*\) denote \(\Z^n\setminus\{0\}\). By quantifier elimination, it suffices to give definitions  for
    atomic formulas of the following forms:
    * \(\varphi_1(\barx,\bary):=(s_{\bark}(\barx)=t(\bary))\), where \(\bark\in\Z^n_*\) and \(t(\bary)\) is a
      term in variables \(\bary\).
    * \(\varphi_2(\barx,\bary):=(s_{\bark}(\barx)>t(\bary))\), where \(\bark\in\Z^n_*\) and \(t(\bary)\) is a
      term in variables \(\bary\)
    * \(\varphi_3(\barx,\bary):=([s_{\bark}(\barx)+t(\bary)]_m=0)\), where \(\bark\in\Z^n_*\), \(m\in\Z^+\),
      and \(t(\bary)\) is a term in variables \(\bary\).

    Fix \(\bara\vDash p\) and fix \(\bark\in\Z_*^n\). Since \(p\) is algebraically independent, it follows
    that \(s_{\bark}(\bara)\notin G\). Since \(G(\bara)\) is an end extension of \(G\), we may
    partition \(\Z^n_*=S^+\cup S^-\) where
    \begin{equation*}
    S^+=\{\bark:s_{\bark}(\bara)>G\} \quad\text{ and }\quad S^-=\{\bark:s_{\bark}(\bara)<G\}
    \end{equation*}
    Note that \(S^+\) and \(S^-\) depends only on \(p\), and not choice of realization \(\bara\).
    Moreover, for any \(\bark\in\Z^n\) and \(m>0\), the integer \([s_{\bark}(\bara)]_m\in\{0,\dots,m-1\}\)
    depends only on \(p\). We now give the following definitions for \(p\) (note that they are
    formulas over \(\emptyset\)):
    \begin{align*}
    &d_p[\varphi_1](\bary):=(y_1\neq y_1)\\
    &d_p[\varphi_2](\bary):=
    \begin{cases}
    y_1=y_1&\bark\in S^+\\
    y_1\neq y_1&\bark\in S^-
    \end{cases}\\
    &d_p[\varphi_3](\bary):=([t(\bary)+[s_{\bark}(\bara)]_m]_m=0)
    \end{align*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:0.7
    Given \(p\in S_n(G)\), TFAE
    1. \(p\) is definable over \(G\)
    2. \(p\) has a unique coheir to \(G^*\)
    3. For any (some) \(\bara\vDash p\), \(G(\bara)\) is an end extension of \(G\)
    #+END_theorem

    #+BEGIN_proof
    \(1\Rightarrow 2\): True for any NIP theory

    \(2\Rightarrow 3\): ref:0.3

    \(3\Rightarrow 1\): We may assume \(p\) is non-isolated. We proceed by induction on \(n\). If \(n=1\)
    then \(p\) is algebraically independent since it is non-isolated, and so we apply Lemma ref:0.6.
    Assume the result for \(n'<n\) and fix \(p\in S_n(G)\). If \(p\) is algebraically independent then
    we apply Lemma ref:0.6. So assume, W.L.O.G., that we have \(\bara\vDash p\)
    with \(a_n\in G(\bara_{<n})\). Let \(q=\tp(\bara_{<n}/G)\in S_{n-1}(G)\). By
    assumption, \(G(\bara_{<n})=G(\bara)\) is an end extension of \(G\), and so \(q\) is definable
    by induction. Fix a \(G\)-definable function \(f:(G^*)^{n-1}\to G^*\) s.t. \(f(\bara{<n})=a_n\).
    Fix a formula \(\varphi(\barx,\bary)\) and define
    \begin{equation*}
    \psi(\barx_{<n},\bary):=\varphi(\barx_{<n},f(\barx_{<n}),\bary)
    \end{equation*}
    Let \(d_q[\psi](\bary)\) be an \(\call_G\)-formula s.t., for
    any \(\barb\in G\), \(\psi(\barx_{<n},\barb)\in q\) iff \(G\vDash d_q[\psi](\barb)\). Then for
    any \(\barb\in G\), we have
    \begin{equation*}
    \varphi(\barx,barb)\in p\Leftrightarrow G^*\vDash\varphi(\bara,\barb)\Leftrightarrow G^*\vDash\psi(\bara_{<n},\barb)\Leftrightarrow
    G\vDash d_q[\psi](\barb)
    \end{equation*}
    #+END_proof
** \texorpdfstring{\(f\)}{f}-generics in Presburger arithmetic
    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Any \(f\)-generic \(p\in S_n(G)\) is algebraically independent
    #+END_proposition

    #+BEGIN_proof
    Suppose \(p\) is not algebraically independent. W.L.O.G., fix \(\bara\vDash p\)
    with \(a_n\in G(\bara_{<n})\). Then there are \(r,k_1,\dots,k_{n-1}\in\Z\) and \(b\in G\)
    s.t. \(ra_n=b+k_1a_1+\dots+k_{n-1}a_{n-1}\). Consider the
    formula \(\phi(\barx;b):=rx_n=b+k_1x_1+\dots+k_{n-1}x_{n-1}\), and note that \(\phi(\barx;b)\in p\). We fix a
    small model \(G_0\prec G\), and find a translate of \(\phi(\barx;b)\) that forks over \(G_0\).

    Pick \(c\in rG\) s.t. \(b-c\notin G_0\), and set \(g=\frac{c}{r}\). Let \(\barg=(0,\dots,0,g)\) and
    set \(\psi(\barx;b,\barg):=\phi(\barx+\barg;b)\). By construction, we may find
    automorphism \(\sigma_i\in\Aut(G/G_0)\) s.t. \(\sigma_i(b-c)\neq\sigma_j(b-c)\) for all \(i\neq j\). (\(b-c\) is
    not almost \(G_0\)-definable, therefore it has infinite orbits)
    Setting \(b_i=\sigma_i(b)\) and \(\barg_i=\sigma_i(\barg)\), we have that \(\{\psi(\barx;b_i,\barg_i):i<\omega\}\) is
    2-inconsistent. So \(\psi(\barx;b,\barg)\) forks over \(G_0\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    label:0.10
    If \(p\in S_n(G)\) is algebraically independent, TFAE
    1. \(p\) is \(f\)-generic
    2. \(p\) is strongly \(f\)-generic
    3. \(p\) is definable \(f\)-generic
    4. \(p\) is definable over \(G\)
    5. \(p\) is definable over \(\emptyset\)
    6. For any (some) \(\bara\vDash p\), \(G(\bara)\) is an end extension of \(G\)
    #+END_theorem

    #+BEGIN_proof
    \(4\Leftrightarrow 6\): ref:0.7

    \(6\Rightarrow 5\): ref:0.6

    \(5\Rightarrow 4\): trivial

    \(1\Rightarrow 6\): Suppose \(G(\bara)\) is not an end extension of \(G\), and fix \(\bark\in\Z^n\)
    and \(h_1,h_2\in G\) s.t. \(s_{\bark}(\bara)\notin G\) and \(h_1<s_{\bark}(\bara)<h_2\). Consider the
    formula \(\phi(\barx;h_1,h_2):=h_1<s_{\bark}(\barx)<h_2\), and note that \(\phi(\barx;h_1,h_2)\in p\). We fix
    a small model \(G_0\prec G\), and find a translate of \(\phi(\barx;h_1,h_2)\) that forks over \(G_0\).
    W.L.O.G., assume \(b>0\) and also \(h_1>0\). Let \(k_i\) be a nonzero element of the
    tuple \(\bark\). By saturation of \(G\), we may find \(g\in G\) s.t. \(k_ig>c\) for all \(c\in G_0\).
    Let \(\barg\in G^n\) be s.t. \(g_j=0\) for all \(j\neq i\) and \(g_i=g\). For \(t\in\{1,2\}\),
    set \(c_t=h_t+k_ig\in G\) . Then \(\phi(\barx-\barg;h_1,h_2)\) is equivalent
    to \(c_1<s_{\bark}(\barx)<c_2\). Since \(c<c_1\) for all \(c\in G_0\), by Proposition ref:0.4,
    that \(\phi(\barx-\barg;h_1,h_2)\) forks over \(G_0\), as desired. (By increase \(g\), we can show
    that \(\phi(\barx;h_1,h_2;g_i)\)) is 2-inconsistent or something.
    So \(p\) is not \(f\)-generic.

    \(6\Rightarrow 3\): Suppose \(G(\bara)\) is an end extension of \(G\). For any \(\barg\in G^n\), we
    have \(G(\bara)=G(\barg+\bara)\), and \(\barg p\) is still algebraically independent. Therefore,
    for any \(\barg\in G^n\), we use Lemma ref:0.6 to conclude that \(\barg p\) is definable over \(\emptyset\).
    #+END_proof

* Introduction and Preliminaries
** Introduction
    Marcin Petrykowski gave a nice description of \(f\)-generic types in groups \((R,+)\times(R,+)\)
    with \((R,<,+,\cdot)\) with \((R,<,+,\cdot)\) an o-minimal expansion of real closed field. An analogs
    question is: What are the \(f\)-generic types of \(G^n\), the product of \(n\) copies of ordered
    additive groups \((\Z,+,<)\) of integers.

    Let \(M\) be an elementary extension of \((\Z,+,<,0)\), \(\M\succ M\) a monster model. \(G\) denotes
    the additive group \((\M,+)\), \(S_G(M)\) the space of complete types over \(M\) extending the
    formula '\(x\in G\)'. \(G^0\) is the definable connected component of \(G\). Namely, \(G^0\) is the
    intersection of all definable subgroups of \(G\) with finite index.

    Let \(L_n\) denote the space of homogeneous \(n\)-ary \(\Q\)-linear functions. For \(f,g\in L_n\)
    and \(\alpha,\beta\in\M^n\) s.t. \(\alpha\in\dom(f)\) and \(\beta\in\dom(g)\), by \(f(\alpha)\ll_Mg(\beta)\) we mean that for
    all \(a,b\in M\) and \(k,l\in\N^+\), \(kf(\alpha)+a<lg(\beta)+b\). By \(f(\alpha)\sim_Mg(\beta)\) we mean that
    neither v\(f(\alpha)\ll_Mg(\beta)\) nor \(g(\beta)\ll_Mf(\alpha)\). Let \(f_0,\dots,f_m\in L_n\), we
    say \(0\ll_Mf_1(\alpha)\ll_M\dots\ll_Mf_m(\alpha)\) is a maximal positive chain of \alpha over \(M\) if for any \(g\in L_n\)
    with \(g(\alpha)>0\), neither \(f_m(\alpha)\ll_Mg(\alpha)\) nor \(g(\alpha)\ll_Mf_1(\alpha)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_theorem
    Let \(M\succ\Z\), \(\alpha=(\alpha_1,\dots,\alpha_n)\in(G^n)^0\). Then there exists a finite subset \(\{f_0,\dots,f_m\}\subset L_n\)
    s.t. \(f_0(\alpha)=0\ll_Mf_1(\alpha)\ll_M\dots\ll_Mf_m(\alpha)\) is the maximal positive chain of \alpha over \(M\). If \alpha
    realizes an \(f\)-generic type \(p\in S_{G^n}(M)\) then for
    every \(\beta\in G^0\), \(p=\tp(\alpha,\beta/M)\in S_{G^{n+1}}(M)\) is an \(f\)-generic type iff one of the
    following holds:
    1. \(f_m(\alpha)\ll_M\beta\) or \(\beta\ll_M-f_m(\beta)\)
    2. there is \(i\) with \(0\le i<m\) and \(g\in L_n\) s.t. \(f_i(\alpha)\ll_M\epsilon(\beta-g(\alpha))\ll_Mf_{i+1}(\alpha)\)
       where \(\epsilon=\pm 1\)
    3. there is \(i\) with \(1\le i\le m\) and \(g\in L_n\) s.t. for all \(h\in L_n\) with \(h(\alpha)\sim_Mf_i(\alpha)\)
       there is an irrational number \(r_h\in\R\setminus\Q\) s.t. \(q_1h(\alpha)<\beta-g(\alpha)<q_2h(\alpha)\) for all \(q_1,q_2\in\Q\)
       with \(q_1<r_h<q_2\)
    #+END_theorem
** Preliminaries
    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    1. A definable subset \(X\subseteq G\) is  *\(f\)-generic* if for some/any model \(M\) over which \(X\) is
       defined and any \(g\in G\), \(gX\) does not divide over \(M\). Namely, for
       any \(M\)-indiscernible sequence \((g_i:i<\omega)\) with \(g=g_0\), \(\{g_iX:i<\omega\}\)  is consistent.
    #+END_definition

    #+BEGIN_remark
    label:1.2
    The class of all non-weakly generic formulas forms an ideal. So any weakly generic
    type \(p\in S_G(M)\) has a global extension \(\barp\in S_G(\M)\) which is weakly generic.
    #+END_remark

    \(T\) is said to be (or have) NIP if for any indiscernible sequence \((b_i:i<\omega)\)
    formula \(\psi(x,y)\) and \(a\in\M\), there is an eventual truth value of \(\psi(a,b_i)\) as \(i\to\infty\).

    A type definable over \(A\) subgroup \(H\le G\) has bounded index
    if \(\abs{G/H}<2^{\abs{T}+\abs{A}}\). For groups definbale in NIP structures, the smallest
    type-definable subgroup \(G^{00}\) exists. Namely, the intersection of all type-definable
    subgroup of bounded index still has bounded index. We call \(G^{00}\) the *type-definable
    connected component* of \(G\). Another model theoretic invariant is \(G^0\), called the
    definably-connected component of \(G\), which is the intersection of all definable subgroup
    of \(G\) of finite index.

    The Keisler measure over \(M\) on \(X\), with \(X\) a definable set over \(M\), is a finitely
    additive measure on the Boolean algebra of definable subsets of \(X\) over \(M\).

    A definable group \(G\) is *definably amenable* if it admits a global (left) \(G\)-invariant
    probability Keisler measure

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    label:fact1.3
    Assuming NIP, a nip group \(G\) is definably amenable iff it admits a global type \(p\in S_G(\M)\)
    with bounded \(G\)-orbit.
    #+END_fact

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    label:fact1.4
    For a definable amenable NIP group \(G\), we have
    * weakly generic definable subsets, formulas and types coincide with \(f\)-generic definable
      subsets, formulas, and types, respectively
    * \(p\in S_G(\M)\) is \(f\)-generic iff it has bounded \(G\)-orbit
    * \(p\in S_G(\M)\) is \(f\)-generic iff it is \(G^{00}\)-invariant
    * A type-definable subgroup \(H\) fixing a global \(f\)-generic type is exactly \(G^{00}\)
    #+END_fact

    #+BEGIN_remark
    label:1.5
    Assuming that \(G\) is definable amenable NIP group. By Remark ref:1.2, we see that
    any \(f\)-generic \(p\in S_G(M)\) has an \(f\)-generic global extension \(\barp\in S_G(\M)\)
    #+END_remark

    Assume that \(T=\Th(\Z,+,\{D_n\}_{n\in\N^+},<,0)\) is the first order theory of integers in Presburger
    language \(L_{Pres}=(+,\{D_n\}_{n\in\N^+},<,0)\) where each \(D_n\) is a unary predicate symbol
    for the set of elements divisible by \(n\). \(\M\) is the monster model of \(T\).

    \(T\) has quantifier elimination and cell decomposition.

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call a function \(f:X\subseteq M^m\to M\) *linear* if there is a constant \(\gamma\in M\) and
    integers \(a_i\), \(0\le c_i<n_i\) for \(i=1,\dots,m\) s.t. \(D_{n_i}(x_i-c_i)\) and
    \begin{equation*}
    f(x)=\sum_{1\le i\le m}a_i(\frac{x_i-c_i}{n_i})+\gamma
    \end{equation*}
    for all \(x=(x_1,\dots,x_m)\in X\). We call \(f\) *piecewise linear* if there is a finite partition \(\calp\)
    of \(X\) s.t. all restrictions \(f|_A\), \(A\in\calp\) are linear.
    #+END_definition

    Note that \(x\in\dom(f)\) iff \(D_{n_i}(x_i-c_i)\) for each \(i\).

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    * A (0)-cell is a point \(\{a\}\subset M\).
    * An (1)-cell is a set with infinite cardinality of the form
      \begin{equation*}
      \{x\in M|a\Box_1x\Box_2b,D_n(x-c)\}
      \end{equation*}
      with \(a,b\in M\), integers \(0\le c<n\) and \(\Box_i\) either \(\le\) or no condition.
    * Let \(i_j\in\{0,1\}\) for \(j=1,\dots,m\) and \(x=(x_1,\dots,x_m)\). A \((i_1,\dots,i_m,1)\)-cell is a set \(A\)
      of the form
      \begin{equation*}
      \{(x,t)\in M^{m+1}\mid x\in D,f(x)\Box_1t\Box_2g(x), D_n(t-c)\}
      \end{equation*}
      with \(D=\pi_m(A)\) an \((i_1,\dots,i_m)\)-cell. \(f,g:D\to M\) linear functions, \(\Box_i\) either \(\le\)
      or no condition and integers \(0\le c<n\) s.t. the cardinality of the
      fibers \(A_x=\{t\in M\mid (x,t)\in A\}\) can not be bounded uniformly in \(x\in D\) by an integers.
    * An \((i_1,\dots,i_m,0)\)-cell is a set \(A\) of the form
      \begin{equation*}
      \{(x,t)\in M^{m+1}\mid x\in D,t=g(x)\}
      \end{equation*}
      with \(g:D\to M\) a linear function and \(D\in M^m\) an \((i_1,\dots,i_m)\)-cell
    #+END_definition

    #+ATTR_LATEX: :options [\cite{10.2307/4147737}Cell Decomposition Theorem]
    #+BEGIN_fact
    label:1.8
    Let \(X\subset M^m\) and \(f:X\to G\) be definable. Then there exists a finite partition \(\calp\) of \(X\)
    into cells, s.t. the restriction \(f|_A:A\to M\) is linear for each cell \(A\in\calp\). Moreover,
    if \(X\) and \(f\) are \(S\)-definable, then the parts \(A\) can be taken \(S\)-definable.
    #+END_fact

    By the Cell Decomposition Theorem, we conclude that every definable subset of \(M^n\) is a finite
    union of cells. So every definable subset \(X\subseteq M\) is a finite union of points and intervals mod
    some \(n\in\N\). This implies that \(T\) has NIP. <<Problem2>>

    From now on, we assume that \(G=(\M,+)\) is the additive group of the Presburger arithmetic.
    Namely, \(G\) is defined by the formula "\(x=x\)", \(G=\M\) as a set, and \(G(M)=M\) for
    any \(M\prec\M\). For any \(n\)-tuple \(x=(x_1,\dots,x_n)\), by \(D_m(x)\) we mean \(\bigwedge_{1\le i\le n}D_m(x_i)\).
    For any \(\alpha\in\M\), and \(A\subseteq\M\), by \(\alpha>A\) we mean \(\alpha>a\) for all \(a\in\acl(A)\).

    \(\dcl(A)=\acl(A)\) since \(\M\) is a linear order  <<Problem1>>
    #+LATEX: \wu{
    If \(a\in \acl(A)\), then suppose \(\varphi(\M)\) is finite, then \(\varphi(\M)\) lies in some finite interval
    in \(A\)
    #+LATEX: }

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    For every \(n\in\N\)
    * \(G^n\) is definably amenable;
    * the type-definable connected component of \(G^n\) is \(\bigcap_{m\in\N^+}D_m(\M^n)\)
    #+END_fact

    #+BEGIN_proof
    Let \(x=(x_1,\dots,x_n)\) be an \(n\)-tuple. Let \(\Pi(x)\) be the partial type of form
    \begin{align*}
    \{x_1>\M\}&\wedge\{x_2>\dcl(\M,x_1)\}\wedge\dots\\
    &\wedge\{x_n>\dcl(\M,x_1,\dots,x_{n-1})\}\wedge\{D_m(x):m\in\N^+\}
    \end{align*}
    By the cell decomposition theorem, and induction on \(n\), it is easy to see that \Pi determines a
    unique type \(p\in S_{G^n}(\M)\). Moreover, \Pi is invariant under \(\bigcap_{m\in\N^+}D_m(\M^n)\).

    Since \(D_m(\M^n)\) is a definable subgroup of \(G^n\) of finite index, \(G^{00}\le\bigcap_{m\in\N^+}D_m(\M^n)\).
    Thus \(p\) is \(G^{00}\)-invariant and hence has a bounded orbit.

    By Fact ref:fact1.3 \(G^n\) is definably amenable and \(G^{n00}=\bigcap_{m\in\N^+}D_m(\M^n)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    \(G^{n0}=G^{n00}\) for all \(n\in\N^+\).
    #+END_corollary

    #+BEGIN_remark
    label:1.11
    * \(G^0\) is a densely linear ordered divisible abelian group, hence is isomorphic to an ordered
      vector space over \(\Q\).
    * For every \(n\in\N^+\), \((G^0)^n=(G^n)^0\)
    #+END_remark

    #+BEGIN_proof
    divisibility and abelian is trivial. For any \(a,b\in G^0\), \(\frac{a+b}{2}\in G^0\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_fact
    label:1.12
    Suppose that \(f\) is an \(M\)-definable function from \(X\subseteq\M^n\) to \(Y\subseteq\M\). Then for
    any \(\alpha\in(G^0)^n\) there are \(q_1,\dots,q_n\in\Q\) and \(a\in M\) s.t. \(f(\alpha)=q_1\alpha_1+\dots+q_n\alpha_n+a\)
    #+END_fact

    #+BEGIN_proof
    By Cell Decomposition we may assume \(f\) is linear. Then apply remark ref:1.11,
    \(\alpha\in(G^n)^0\), therefore \(\alpha_i\in G^0\) and we don't need the \(c_i\).
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    We call the function \(f\) of the form \(q_1x_1+\dots+q_nx_n+a\) with \(q_1,\dots,q_n\in\Q\) and \(a\in M\) an
    *\(n\)-ary \(\Q\)-linear function* over \(M\). If \(a=0\), we call \(f\) a
    *homogeneous* \(n\)-ary \(\Q\)-linear function. By \(L_n(M)\) we mean the space of
    all \(n\)-ary \(\Q\)-linear functions over \(M\), and \(L_n\) the space of all
    homogeneous \(n\)-ary \(\Q\)-linear functions.
    #+END_definition

    It is easy to see that any \(f\in L_n(M)\) is \(M\)-definable, and there is a natural number \(m\)
    s.t. \(D_m(\M^n)\subseteq\dom(f)\) (common factor). In particular, \((G^0)^n\subseteq\dom(f)\). By Fact ref:1.8 and Fact ref:1.12 we
    conclude that:
    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    If \(\alpha=(\alpha_1,\dots,\alpha_n)\in(G^0)^n\), then for any \(\phi(x_1,\dots,x_n)\in\tp(\alpha/M)\) there is a
    formula \(\psi(x_1,\dots,x_n)\in\tp(\alpha/M)\) of the form
    \begin{equation*}
    \theta(x_1,\dots,x_{n-1})\wedge D_m(x_n)\wedge(f_1(x_1,\dots,x_{n-1})\Box_1x_n\Box_2f_2(x_1,\dots,x_{n-1}))
    \end{equation*}
    with \(m\in\N\), \(\theta(M)\) a cell, \(f_i\in L_{n-1}(M)\), and \(\Box_i\) either \(\le\) or no condition,
    s.t. \(M\vDash\forall x(\psi(x)\to\phi(x))\).
    #+END_corollary

    #+BEGIN_remark
    label:1.15
    There are only 2 \(f\)-generic types contained in every coset of \(G^0\). More precisely, for any
    model \(M\),
    \begin{align*}
    p^+(x)&=\{D_n(x)\mid n\in\N^+\}\cup\{x>a\mid a\in M\}\\
    p^-(x)&=\{D_n(x)\mid n\in\N^-\}\cup\{x<a\mid a\in M\}
    \end{align*}
    Then every \(f\)-generic type over \(M\) is one of \(G(M)\)-translates of \(p^+\) or \(p^-\).
    #+END_remark
* Main results
** The \texorpdfstring{\(f\)}{f}-generics of \(G^2\)
    Let \(\M\) be the saturated model of \(\Th(\Z,+,D_n,<,0,1)_{n\in\N+}\), \(T\) the theory of
    Presburger Arithmetic.

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    For any \(M\succ\Z\), the \(f\)-generic type \(\tp(\alpha,\beta/M)\in S_{G^2}(M)\), with \(\alpha,\beta\in G^0\), has one of
    the following forms:
    * \(\beta>\dcl(M,\alpha)\) (\(+\infty\)-type)
    * \(\beta<\dcl(M,\alpha)\) (\(-\infty\)-type)
    * there is some \(q\in\Q\) s.t. \(q\alpha+m<\beta<(q+\frac{1}{n})\alpha\) for all \(m\in M\) and \(n\in\N\)
      (\(q^+\)-type)
    * there is some \(q\in\Q\) s.t. \((q-\frac{1}{n})\alpha<\beta<q\alpha+m\) for all \(m\in M\) and \(n\in\N\)
      (\(q^-\)-type)
    * there is some \(r\in\R\) s.t. \(q_1\alpha<\beta<q_2\alpha\) for all \(q_1,q_2\in\Q\) with \(q_1<r<q_2\) (\(r^0\)-type)
    #+END_proposition

    #+BEGIN_proof
    Let \(p=\tp(\alpha,\beta/M)\) be a \(f\)-generic type which contained in \((G^2)^0\). By the cell
    decomposition, we may assume that every formula \(\phi(x,y)\) in \(p\) is of the form
    \begin{equation*}
    D_n(x)\wedge(a<x)\wedge D_n(y)\wedge(f_1(x)\Box_1y\Box_2f_2(x))
    \end{equation*}
    with \(n\in\N\), \(a\in M\), \(f_i:D_n(M)\to M\) linear, and \(\Box_i\) either \(\le\) or no condition.

    If every formula in \(p\) contains a cell of the form \(D_n(x)\wedge D_n(y)\wedge f_1(x)\le y\), it's then
    a \(+\infty\)-type

    Similar for \(-\infty\)-type.

    Otherwise there are linear functions \(f_1(x)=q_1x+b_1\) and \(f_2(x)=q_2x+b_2\), with \(q_1,q_2\in\Q\)
    and \(b_1,b_2\in M\) s.t. the cell
    \begin{equation*}
    D_n(x)\wedge(a<x)\wedge D_n(y)\wedge(f_1(x)\le y\le f_2(x))
    \end{equation*}
    is contained in \(p\), where both \(nq_1\) and \(nq_2\) are some integers. We call the above cell
    a \((n,a,q_1,q_2)\)-cell.

    Let
    \begin{align*}
    &Q_1=\{t\in\Q:\text{there is an \((n,a,t,q_2)\)-cell which is contained in \(p(x,y)\)}\}\\
    &Q_2=\{t\in\Q:\text{there is an \((n,a,q_1,t)\)-cell which is contained in }p(x,y)\}
    \end{align*}
    Then both \(Q_1\) and \(Q_2\) are nonempty.

    #+BEGIN_claim
    \((Q_1,Q_2)\) is a cut of \(\Q\)
    #+END_claim

    \begin{proof}
    Clearly \(q_1\le q_2\)whenever \(q_1\in Q_1\) and \(q_2\in Q_2\). Otherwise \(p\) is inconsistent.

    By Remark ref:1.5, let \(\barp\in S_{G^2}(\M)\) be any global \(f\)-generic type containing \(p\). Now \(\barp\) is \(G^{2^0}\)-invariant.
    If there are \(q_1\in Q_1\) and \(q_2\in Q_2\) s.t. \(q_1=q_2\), take \(g\in G^{2^0}\) s.t. \(g>M\), we see that the partial type \((gp)\cup p\) is
     inconsistent, but \((gp)\cup p\subseteq\barp\), a contradiction. So \(q_1<q_2\) for all \(q_1\in Q_1\) and \(q_2\in Q_2\). <<Problem5>>

    Suppose that there is \(q\in\Q\) s.t. \(q_1<q\) for all \(q_1\in Q_1\). Then for some \(n\in\N\) and any \(a\in M\), any \((n,a,q_1,q)\)-cell
    is consistent with \(p\) and hence contained in \(p\). So \(q\in Q_2\). Similarly, if \(q<q_2\) for all \(q_2\in Q_2\), then \(q\in Q_1\).
    So \((Q_1,Q_2)\) is a cut of \(\Q\).
    \end{proof}

    Let \(r\in\R\) be the real number determined by the cut \((Q_1,Q_2)\). By the \(G^{2^0}\)-invariance
    of \(\barp\), we have
    * If \(r=q\in Q_1\), then \(p\) is a \(q^+\)-type
    * If \(r=q\in Q_2\), then \(p\) is a \(q^-\)-type
    * If \(r\notin\Q\), then \(p\) is a \(r\)-type
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(\alpha\in\M\) is *bounded* over \(M\) if there are \(a,b\in M\) s.t. \(a<\alpha<b\), and unbounded otherwise
    #+END_definition

    #+BEGIN_remark
    label:2.3
    By the above argument, it is easy to conclude that for any \(\alpha,\beta\in G^0\), if both \(\tp(\alpha/M)\)
    and \(\tp(\beta/M)\) are \(f\)-generic. Then either \(\tp(\alpha,\beta/M)\) is \(f\)-generic, or there
    is \(q_1,q_2\in\Q\) s.t. \(q_1\alpha+q_2\beta\) is bounded over \(M\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:2.4
    Let \(\tp(\alpha,\beta/M)\) be a \(f\)-generic type which contained in \(G^{2^0}\).
    Then \(\tp(q_1\alpha,q_2\beta/M)\) is \(f\)-generic for all \(q_1,q_2\in\Q\setminus\{0\}\).
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    label:2.5
    Let \(\alpha,\beta\in G^0\). Then \(\tp(\alpha,\beta/M)\) is an \(f\)-generic type iff for
    all \(q_1,q_2\in\Q\), \(q_1\alpha+q_2\beta\) is unbounded over \(M\) whenever \(q_1^2+q_2^2\neq 0\). In particular,
    both \alpha and \beta are unbounded over \(M\), and \(\{\alpha,\beta\}\) is algebraic independent over \(M\).
    #+END_corollary

    #+BEGIN_remark
    By Remark ref:1.15, every \(f\)-generic type of \(G^2\) over \(M\) is one of \(G^2(M)\)-translate
    of some \(f\)-generic type contained in \(G^{2^0}\). So it suffices to study the \(f\)-generic
    types contained in \(G^{2^0}\)
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Every global \(f\)-generic type of \(G^2\) contained in \(G^{2^0}\) is \(\emptyset\)-definable.
    #+END_corollary

    #+BEGIN_proof
    Let \(\phi(x,y,z)\) be a formula. Then we may assume that \phi is finitely many union of the following
    cells:
    \begin{align*}
    C_i(x,y,z)&=D_{n_{1i}}(z-c_{1i})\wedge D_{n_{2i}}(x-c_{2i})\wedge D_{n_{3i}}(y-c_{3i})\wedge\\
    &(a_{1i}\Box_{1i}z\Box_{2i}a_{2i})\wedge(h_{1i}(z)\Box_{3i}x\Box_{4i}h_{2i}(z))\wedge(f_{1i}(x,z)\Box_{5i}y\Box_{6i}f_{2i}(x,z))
    \end{align*}
    where \(i=1,\dots,m\), \(c_{1i},c_{2i},c_{3i},a_{1i},a_{2i}\in\Z\), \(\Box_{1i},\dots,\Box_{6i}\) either \(\le\) or
    no condition, \(h_{li}(x)=b_{li}(\frac{z-c_{1i}}{n_{1i}})+\gamma_{li}\)
    and \(f_{li}(x,z)=d_{li}(\frac{x-c_{2i}}{n_{2i}})+e_{li}(\frac{z-c_{1i}}{n_{1i}})+\xi_{li}\)
    for \(l=1,2\) and \(b_{li},d_{li},\gamma_{li},\xi_{li}\in\Z\)

    Let \(p=\tp(\alpha,\beta/\M)\) be a global \(f\)-generic type of \(G^2\) contained in \(G^{2^0}\). We assume
    that, for example, \(\alpha>\M\) and \(p\) is a \(q^+\)-type for some \(q\in\Q\). Then \(\phi(x,y,b)\in p\) iff
    there is some \(i\le m\) s.t.
    1. \(\M\vDash D_{n_{2i}}(c_{2i})\wedge D_{n_{2i}}(c_{3i})\)
    2. \(\Box_{4i}\) is no condition.
    #+END_proof

** An equivalence relation on homogeneous linear functions
    Let \(L_n=\{q_1x_1+\dots+q_nx_n\mid q_1,\dots,q_n\in\Q\}\) is the space of all
    homogeneous \(n\)-ary \(\Q\)-linear functions, and \(L_n(M)=\{f+a\mid f\in L_n,a\in M\}\) for
    any \(M\prec\M\). For each \(f\in L_n(M)\), there is \(m\in\N^+\) s.t. \(f\)
    is \(\emptyset\)-definable from \(D_m(G^n)\) to \(G\) <<Problem6>>

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    \(M\prec\M\), \(f,g\in L_n(M)\), \(\alpha\in(G^n)^0\)
    * \(f(\alpha)\ll_Mg(\alpha)\) if
      \begin{equation*}
      nf(\alpha)+a<mg(\alpha)+b
      \end{equation*}
      for all \(n,m\in\N^+\), and \(a,b\in M\)
    * \(f\sim_{M\alpha}g\) if neither \(f(\alpha)\ll_Mg(\alpha)\) nor \(g(\alpha)\ll_Mf(\alpha)\)
    #+END_definition

    For any \(f\in L_n(M)\), there is \(g\in L_n\) s.t. \(f\in[g]_{M\alpha}\).

    #+BEGIN_remark
    If both \(f(\alpha)\) and \(g(\alpha)\) are positive (or negative),
    then \(f(\alpha)\ll_Mg(\alpha)\) iff \(\dcl(M,f(\alpha))<g(\alpha)\) (or \(f(\alpha)<\dcl(M,g(\alpha))\))
    #+END_remark

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Suppose \(\alpha_1,\alpha_2\in G^0\). Then \(\{\abs{f}\mid f\in L_2(M)\}\) has at most 5 elements
    #+END_lemma

    #+BEGIN_proof
    Let \(p=\tp(\alpha_1,\alpha_2/M)\). Suppose \(p\) is not \(f\)-generic. Then by Corollary
    ref:2.5, \(q_1\alpha_1+q_2\alpha_2\) is bounded over \(M\) for some \(q_1,q_2\in\Q\).
    If \(q_1\neq 0\), then for each \(f\in L_2\) there is \(g\in L_1(M)\)
    s.t. \(f(\alpha_1,\alpha_2)\sim_Mg(\alpha_2)\). Assume that \(\alpha_2>0\). Then
    \begin{equation*}
    \{\abs{g}_{M\alpha_2}\mid g\in L_1(M)\}=\{[0]_{M\alpha_2}\}
    \end{equation*}
    if \(\alpha_2\) is bounded over \(M\), and
    \begin{equation*}
    \{\abs{g}_{M\alpha_2}\mid g\in L_1(M)\}=\{[-x_2]_{M\alpha_2},[0]_{M\alpha_2},
    [x_2]_{M_{\alpha_2}}\}
    \end{equation*}

    Now suppose that \(p\) is an \(f\)-generic type. W.L.O.G., we assume that \(\alpha_1>0\).
    * Suppose that \(p\) is a \(q\)-TYPE with \(q\in\Q\), say a \(q^+\)-type.

      Let \(h(x_1,x_2)=ax_1+bx_2\in L_2\) and \(g(x_1,x_2)=a'x_1+b'x_2\in L_2\)
      s.t. \(h(\alpha_1,\alpha_2)>0\), \(g(\alpha_1,\alpha_2)>0\) and \(h(\alpha)\gg_Mg(\alpha)\).
      Then we have
      \begin{equation*}
      a\alpha_1+b\alpha_2>n(a'\alpha_1+b'\alpha_2)
      \end{equation*}
      for all \(n\in\N^+\).

      If \(b'=0\), we conclude that either \(\alpha_2<\dcl(M,\alpha_1)\)
      or \(\alpha_2>\dcl(M,\alpha_1)\), and hence \(p\) should be an \(\infty\)-TYPE, a
      contradiction.

      If \(b'<0\), then \(a'>-b'q\) as \(a'\alpha_1+b'\alpha_2>0\). For any sufficiently
      large \(n\in\N^+\) we have
      \begin{equation*}
      (a-na')\alpha_1+(b-nb')\alpha_2>0
      \end{equation*}
      We now assume that \(b-nb'>0\). Since \(\alpha_2<(q+\frac{1}{m})\alpha_1\) for
      all \(m\in\N^+\), we have
      \begin{equation*}
      (a-na')\alpha_1+(b-nb')(q+\frac{1}{m})\alpha>0
      \end{equation*}
      which implies that for all sufficiently large \(m,n\in\N^+\),
      \begin{equation*}
      (a+b(q+\frac{1}{m}))-n(a'+b'(q+\frac{1}{m}))>0
      \end{equation*}
      So \(a'+b'(q+\frac{1}{m})\le 0\) for all \(0<m\in\N\). But \(a'>-b'q\), so for sufficiently
      large \(m\), \(a'>-b'(q+\frac{1}{m})\). A contradiction.

      We conclude that \(b'>0\). For sufficiently large \(n\), \((b-nb')<0\) and
      hence \((b-nb')q\alpha_1>(b-nb')\alpha_2\). So we have
      \begin{equation*}
      (a-na')\alpha_1+(b-nb')q\alpha_1>0
      \end{equation*}
      which implies that
      \begin{equation*}
      (a+bq)-n(a'+b'q)>0
      \end{equation*}
      for all sufficiently large \(n\in\N\), and hence \(a'+b'q\le 0\).
      Since \(a'\alpha_1+b'\alpha_2>0\), we have \(a'+b'q\ge 0\). So \(a'+b'q=0\). For
      any \(h'(x_1,x_2)=a''x_1+b''x_2\) with \(b''>0\) and \(a''+b''q=0\), there is some \(n\in\N\)
      s.t. \(h'=nh\) or \(h=nh'\). So in this case
      \begin{equation*}
      \{[f]_{M\alpha}\mid f\in L_2\}=\{[-h]_{M\alpha},[-g]_{M\alpha},
      [0]_{M\alpha},[g]_{M\alpha},[h]_{M\alpha}\}
      \end{equation*}
    * Suppose that \(p\) is an \(\infty\)-TYPE. \(p\) is an \(\infty\)-TYPE
      iff \(\tp(\alpha_2,\alpha_1/M)\) is a 0-TYPE
    * Suppose \(p\) is an \(r\)-TYPE with \(r\in\R\setminus\Q\), and let \(h(x_1,x_2)=ax_1+bx_2\)
      and \(g(x_1,x_2)=a'x_1+b'x_2\) as above.

      If \(b'<0\), then \(a'>-b'r\). Let \(r<q\in\Q\) s.t. \(a'>-b'q\). For all sufficiently
      large \(n\in\N\), we have
      \begin{equation*}
      (a-na')\alpha_1+(b-nb')q\alpha_1>(a-na')\alpha_1+(b-nb')\alpha_2>0
      \end{equation*}
      which implies that
      \begin{equation*}
      (a+bq)-n(a'+b'q)>0
      \end{equation*}
      This is a contradiction as \(a'+b'q>0\).

      If \(b'>0\), then \(a'\alpha_1+b'\alpha-2>0\) implies that there is some \(q\in\Q\)
      s.t. \(a'+b'q>0\) and \(q<r\).

      For all sufficiently large \(n\in\N\), we have
      \begin{equation*}
      (a-na')\alpha_1+(b-nb')q\alpha_1>(a-na')\alpha_1+(b-nb')\alpha_2>0
      \end{equation*}
      which implies that
      \begin{equation*}
      (a+bq)-n(a'+b'q)>0
      \end{equation*}
      This is a contradiction since \(a'+b'q>0\). So \([h]_{M\alpha}=[g]_{M\alpha}\)
      whenever \(h(\alpha)>0\), \(g(\alpha)>0\), and \(f,g\in L_2\), and hence
      \begin{equation*}
      \{[f]_{M\alpha}\mid f\in L_2(M)\}=\{[-h]_{M\alpha},[0]_{M\alpha},[h]_{M\alpha}\}
      \end{equation*}
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Suppose that \(p=\tp(\alpha_1,\alpha_2/M)\) is \(f\)-generic with \(\alpha_1,\alpha_2\in G^0\).
    Let \(f_1(x_1,x_2)=ax_1+bx_2\) and \(f_2(x_1,x_2)=a'x_1+b'x_2\) be lienar functions
    s.t. \(f_i(\alpha_1,\alpha_2)>0\). If \(f_1(\alpha_1,\alpha_2)\ll_Mf_2(\alpha_1,\alpha_2)\)
    then \(p\) is a \(q\)-TYPE with \(q\in\Q\) and \(a+bq=0\)
    #+END_corollary

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    For any \(\alpha=(\alpha_1,\dots,\alpha_n)\in G^{0^n}\)
    and \(\beta\in G^0\), \(\{[f]_{M\alpha\beta}\mid f\in L_{n+1}\}\) is finite
    #+END_lemma

    #+BEGIN_proof
    By IH, there are finitely many \(n\)-ary linear functions \(h_1,\dots,h_k\in L_n\)
    s.t. \(0\ll_Mh_1(\alpha)\ll_M\dots\ll_Mh_k(\alpha)\) and
    \begin{equation*}
    \{[h]_{M\alpha}\mid 0<h(\alpha)\in L_n\}=\{[h_1]_{M\alpha},\dots,[h_k]_{M\alpha}\}
    \end{equation*}
    #+BEGIN_claim
    For each \(\epsilon\in\{1,\dots,k\}\), there do not
    exist \(u_i\in[h_\epsilon]_{M\alpha}\), \(c_i\in\Q\), and \(\gamma\in G^0\), with \(i\in\N^+\)
    s.t.
    \begin{equation*}
    u_1(\alpha_1,\dots,\alpha_n)+c_1\gamma\ll_Mu_2(\alpha_1,\dots,\alpha_n)+c_2\gamma\ll_M\dots
    \end{equation*}
    is an infinite chain
    #+END_claim

    #+BEGIN_claim
    If there are \(\epsilon\in\{1,\dots,k\}\), \(u_i\in[h_\epsilon]_{M\alpha}\), \(c_i\in\Q\),
    and \(\gamma\in G^0\) with \(i\in\N^+\) s.t.
    \begin{equation*}
    u_1(\alpha_1,\dots,\alpha_n)+c_1\gamma\ll_Mu_2(\alpha_1,\dots,\alpha_n)+c_2\gamma\ll_M\dots
    \end{equation*}
    is an infinite chain. Then \(\tp(u_i(\alpha)/\gamma/M)\) is a \(q_i\)-TYPE
    with \(q_i\in\Q\setminus\{0\}\) for all \(i\in\N^+\)
    #+END_claim

    \begin{proof}
    If there are \(j\in\N^+\), \(d_1,d_2\in\Q\) s.t. \(d_1u_j(\alpha_1,\dots,\alpha_n)+d_2\gamma\) is bounded over \(M\), then
    \begin{equation*}
    -\frac{d_1}{d_2}u_j(\alpha_1,\dots,\alpha_n)+a<\gamma<-\frac{d_1}{d_2}u_j(\alpha_1,\dots,\alpha_n)+b
    \end{equation*}
    for some \(a,b\in M\). So we conclude that
    \begin{equation*}
    (u_1(\alpha_1,\dots,\alpha_n)+c_i\gamma)\sim_M
    (u_i(\alpha_1,\dots,\alpha_n)-c_i\frac{d_1}{d_2}u_j(\alpha_1,\dots,\alpha_n))
    \end{equation*}
    Let
    \begin{equation*}
    v_i(\alpha_1,\dots,\alpha_n)=u_i(\alpha_1,\dots,\alpha_n)-c_i
    \frac{d_1}{d_2}u_j(\alpha_1,\dots,\alpha_n)
    \end{equation*}
    then we have an infinite chain of
    \begin{equation*}
    v_1(\alpha_1,\dots,\alpha_n)\ll_Mv_2(\alpha_1,\dots,\alpha_n)\ll_M\dots
    \end{equation*}
    which contradicts IH.

    We now assume that \(d_1u_i(\alpha_1,\dots,\alpha_n)+d_2\gamma\) is unbounded over \(M\) for all
    \(i\in\N^+\) and \(d_1,d_2\in\Q\) s.t. \(d_1^2+d_2^2\neq 0\). Therefore \(\tp(u_i(\alpha),\gamma/M)\) is \(f\)-generic
    for each \(i\in\N^+\). As \(u_{i+1}\sim_{M\alpha}u_i\), there exists \(q\in\Q\) s.t.
    for all \(m\in\N^+\),
    \begin{equation*}
    qu_i(\alpha)+c_{i+1}\gamma>u_{i+1}(\alpha)+c_{i+1}\gamma>m(u_i(\alpha)+c_i\gamma)
    \end{equation*}
    By Corollary ref:2.14, \(\tp(u_i(\alpha),\gamma/M)\) is either non-\(f\)-generic, or a \(-c_i^{-1}\)-TYPE.
    \end{proof}


    We now turn to Claim 1.

    For a contradiction, let \(1\le t\le k\) be the least number s.t. there exist \(u_i\in[h_t]_{M\alpha}\), \(c_i\in\Q\)
    and \(\gamma\in G^0\) with \(i\in\N^+\) s.t.
    \begin{equation*}
    u_1(\alpha)+c_1\gamma\ll_Mu_2(\alpha)+c_2\gamma\ll_M\dots
    \end{equation*}
    is an infinite chain. By the Claim 2, we may assume that \(\tp(u_i(\alpha),\gamma/M)\) is
    a \(q_i\)-TYPE for each \(i\in\N^+\), with \(q_i\in\Q^+\). Moreover, we assume that
    each \(u_i\in L_n\). It is easy to see that \(\tp(u_1(\alpha),u_i(\alpha)/M)\) is either
    a \(\frac{q_1}{q_i}\)-TYPE, or \(u_i=\frac{q_1}{q_i}u_1\)
    * If \(t=1\), then for all \(i\in\N^+\), \(u_i=\frac{q_1}{q_i}u_1\).
      Otherwise, \(\tp(u_1(\alpha),u_i(\alpha)/M)\) will be a \(\frac{q_1}{q_i}\)-TYPE, and this
      implies that either \(0\ll_Mu_1(\alpha)-\frac{q_1}{q_i}u_i(\alpha)\ll_Mu_1(\alpha)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Let \(p=\tp(\alpha_1,\dots,\alpha_n/M)\) with \(\alpha_1,\dots,\alpha_n\in G^0\). By
    *maximal positive chain* of \(p\) we mean a finite ascending chain of
    form \(0\ll_Mf_1(\alpha)\ll_M\dots\ll_Mf_m(\alpha)\) with each \(f_i\in L_n\) s.t.
    \begin{equation*}
    \{[f]_{M\alpha}\mid f(\alpha)>0\in L_n\}=\{[f_1]_{M\alpha},\dots,[f_m]_{M\alpha}\}
    \end{equation*}
    #+END_definition


** The \(f\)-generics of \(G^n\)

* Problem
    | [[Problem1]]     |   |   |
    | [[Problem2]]     |   |   |
    | [[Problem3]]     |   |   |
    | [[Problem4]]     |   |   |
    |                  |   |   |
    | [[Problem6]] |   |   |
    |          |   |   |
