#+TITLE: Topological Dynamics And Definable Group Actions
#+AUTHOR: Ludomir Newelski

#+LATEX_HEADER: \graphicspath{{../../books/}}
#+LATEX_HEADER: \input{../preamble.tex}
#+LATEX_HEADER: \makeindex

* Introduction
    Assume \(G\) is a group. By a *\(G\)-flow* we mean a compact Hausdorff topological space \(X\) together with
    a left action of \(G\) on \(X\) by homeomorphisms. A non-empty closed subset \(Y\) of \(X\) is a
    *subflow* of \(X\) if \(Y\) is closed under the action of \(G\). A flow is *minimal* if it has no
    proper subflow. A flow is *point-transitive*, if it contains a dense \(G\)-orbit.

    Topological dynamics is concerned with the orbits of the actions of \(G\) on
    various \(G\)-flows, and particularly with minimal flows

    Assume \(X\) is a \(G\)-flow. For \(x\in X\) let \(o(x)\) denote the orbit of \(X\). Then the
    closure \(\cl(o(x))\) is a subflow of \(X\) and for any orbit \(\calo\subseteq X\) and every \(x\in\cl(\calo)\) we
    have \(\cl(o(x))\subseteq\cl(\calo)\).

    By Zorn lemma, it follows that for any orbit \(\calo\subseteq X\), the closure \(\cl(\emptyset)\) contains a minimal
    flow.  If the flow \(\cl(o(x))\) is minimal, then we call the point \(x\) *almost periodic*. Every
    minimal flow is point transitive, any point in a minimal flow is almost periodic and any two
    distinct minimal subflows of \(X\) are disjoint

    A *morphism of \(G\)-flows* is a continuous \(\varphi:X_0\to X_1\) that commutes with the action of \(g\),
    i.e. s.t. for all \(p\in X_0\) and \(g\in G\) we have \(\varphi(g\cdot p)=g\cdot\varphi(p)\). Thus \(G\)-flows become a
    category. Point-transitive \(G\)-flows are a subcategory.



    There is a unique largest universal point-transitive \(G\)-flow, namely \(X=\beta G\), the space of
    ultrafilters on \(G\), where the action of \(G\) on \(\beta G\) is by left translation by \(G\)

    first consider boolean algebra \(\calp(G)\) and all ultrafilters on \(\calp(G)\), which is \(\beta G\), the
    stone spaces. compact, totally disconnected Hausdorff space

    \(X\in G\), define \([x]=\{p\in\beta G\mid x\in p\}\)

    \(j:G\to\beta G\), \(g\mapsto(g)=\{p\mid\{g\}\in p\}\), \(j(G)\) is dense in \(\beta G\)

    universal property: If there is \(f:G\to X\) embedding where \(X\) is closed and \(\ove{f(G)}=X\), then there is a
    unique \(\beta G\to X\), \((g)\mapsto f(g)\) surjection,

    Let \(T=\Th(M)\) be a complete theory, \(G\) is a definable group. A \(G\)-set \(V\) is
    *definable* if the underlying set \(V\) and the group action are both definable. If this action is
    transitive (there is \(v\in V\) s.t. \(G\cdot v=V\)), we call \(V\) a *homogeneous \(G\)-set*

    For a definable subset \(V\) of \(M\) and \(N\succ M\), by \(V^N\) we mean the set \(\varphi(N)\), where
    \varphi is a formula defining \(V\) in \(M\)

    Assume \(V\) is a definable \(G\)-set in \(M\). Then for any \(N\succ M\) also \(G^N\) acts
    on \(V^N\), in particular, \(G^{\fC}\) acts on \(V^{\fC}\). Also \(G\) is a subgroup of \(G^{\fC}\),
    hence \(G\) acts also on \(V^{\fC}\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    A subset of a structure is *type-definable* iff it can be written as the set of realizations of a
    partial types
    #+END_definition


    Assume \(E\) an equivalence relation on \(V^{\fC}\) type definable (definable by \omega formulas)
    over \(M\). For any formula \(\varphi(x,y)\in E(x,y)\) we may assume \(\varphi\vdash V(x)\wedge V(y)\). \(\varphi(x,y)\) is
    reflexive, and we can require it to be symmetric since \(\varphi(x,y)\wedge\varphi(y,x)\) is always symmetric

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(E\) be a equivalence relation on \(V^{\fC}\) type definable over \(M\), for any
    symmetric \(\psi(x,y)\in E\), there is a symmetric \(\varphi(x,y)\) s.t. \(\varphi(x,y)\wedge\varphi(y,z)\vdash\psi(x,z)\).
    Note \(\varphi(x,y)\vdash\psi(x,y)\) as \(z=y\)
    #+END_lemma

    #+BEGIN_proof
    \(\{\varphi(x,y)\wedge\varphi(x,z):\varphi\in E\}\vdash\psi(x,z)\) for any \(\psi\in E\) because \(E\) is an equivalence relation. By
    compactness, we get a desired \varphi
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is an equivalence relation on \(V^{\fC}\), type definable over \(M\). TFAE
    1. \(\abs{V^{\fC}/E}<\kappa\)
    2. \(\abs{V^{\fC}/E}\le 2^{\abs{T}+\abs{M}}\)
    3. For any symmetric \(\varphi(x,y)\) there is a number \(n_\varphi<\omega\) and \(n_\varphi\)
       elements \(a_1,\dots,a_{n_\varphi}\in V^{\fC}\) satisfying that for any \(i<j\), \(\neg\varphi(a_i,a_j)\) and for
       any \(c\in V^{\fC}\), \(\varphi(c,a_i)\) for some \(i\le n_\varphi\)
    4. For any symmetric \(\varphi(x,y)\) and \(a\in V^{\fC}\) there is \(c\in M\) with \(\varphi(a,c)\). So we can
       require the elements \(a_1,\dots,a_{n_\varphi}\) in 3 to live in \(M\)
    #+END_proposition

    #+BEGIN_proof
    \(1\to 3\): if not, we can build a \kappa-sequence by induction. Assume we have \(a_i\) for \(i<\alpha\),
    then we chose \(a_\alpha\) realizing \(\{\neg\varphi(x,a_i)\wedge V(x):i<\alpha\}\), which is finitely satisfiable. Since
    \(\neg\varphi(a_i,a_j)\Rightarrow\neg E(a_i,a_j)\), \((a_i)_{i<\kappa}\) are from different equivalence class of \(E\)

    \(3\to 4\): Assume \(a_1,\dots,a_k\) are the representitives, \(a_1,\dots,a_l\in M\), \(a_{l+1},\dots,a_k\notin M\),
    and for any \(c\in M\) and \(i>l\), there are \(\neg\varphi(c,a_i)\). Let \(\psi\equiv\bigwedge_{i=1}^l\neg\varphi(a_i,x)\),
    then \(\psi(M)=\emptyset\) while \(\{a_{l+1},\dots,a_k\}\subseteq\psi(\fC)\)

    \(4\to 2\): \(\abs{M}^{\abs{T}+\abs{M}}=2^{\abs{T}+\abs{M}}\)

    \(2\to 1\): trivial
    #+END_proof

    Assume \(E\) is an equivalence relation on \(V^{\fC}\), type definable over \(M\), with bounded
    number of classes (btde-relation). On \(V^{\fC}\) we have a natural topology where the closed set
    are the type definable set

    On the quotient set \(V^{\fC}/E\) (also denoted by \(V_E\)), there is a natural topology, with the
    closed set \(Z\) where \(\pi^{-1}(Z)\subseteq V^{\fC}\) is a type definable set. This topology is called the
    logic topology or the Kim-Pillay Topology on \(V_E\)

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is a equivalence relation type definable by \(M\), we equip \(V_E\) with logic
    topology
    1. \(Y\subseteq V_E\) is closed iff for some type definable set \(A\), \(Y=\{a_E:a\in A\}\)
    2. A basis of open sets is the collection of all \(U_{a\varphi}\).
       Here \(U_{a\varphi}=\{b_E:\varphi(a',b')\text{ for all }E(a,a'),E(b,b')\}\), \(\varphi\in E\)
    3. \(V_E\) is Hausdorff
    4. \(V_E\) is compact iff \(E\) is bounded
    #+END_proposition

    #+BEGIN_proof
    1. \(\Rightarrow\): trivial \(\Leftarrow\): \(\pi^{-1}(Y)=\{a:a_E\in Y\}\) is type defined by \(\exists y(E(x,y)\wedge A(y))\)
    2. \(U_{a\varphi}\) is open because \(\{b:b_E\notin U_{a\varphi}\}\) is type defined
       by \(\exists y\exists z(E(a,y)\wedge E(x,z)\wedge\neg\varphi(y,z))\)

       Assume \(U\) is open and \(a_E\in U\), \(V_E\setminus U\) is closed and type defined by a partial
       type \(\Sigma(x)\) where \(\Sigma(V^{\fC})=\pi^{-1}(V_E\setminus U)\). Choose \(\psi\in\Sigma\) s.t. \(\neg\psi(a)\).
       Since \(E(x,y)\wedge \Sigma(x)\vdash\Sigma(y)\), we have \(\varphi(x,y)\wedge\Sigma(y)\vdash\psi(y)\) for some \(\varphi\in E(x,y)\) by
       compactness. Then \(a_E\in U_{a\varphi}\subseteq U\)
    3. Suppose \(a_E\neq b_E\), then there is \(\varphi\in E\) s.t. \(\neg\varphi(a,b)\).
       Let \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\). Then \(a\in U_{a\varphi'}\) and \(b\in U_{b\varphi'}\)?
    4. Assume \(E\) is bounded, \((F_i)_{i\in I}\) is a family of closed sets with finite intersection
       property. The number of \(E\)-classes is bounded, so the number of closed set is also bounded

       Assume \(V_E\) is compact, for any \(\varphi\in E\), let \((a_i)_{i\in I}\) be representitives.
       Now \(V_E=\bigcup_{i\in I}U_{a_i\varphi}\), so there is finite \(I_0\subseteq I\) s.t. \(V_E=\bigcup_{i\in I_0}U_{a_i\varphi}\)
    #+END_proof

    A btde-relation \(E\) on \(V^{\fC}\) is \(G\)-invariant if for
    any \(x,y\in V^{\fC}\), \(xEy\Rightarrow gxEgy\). In this case, a group action of \(G\) on \(V\) (which is a
    homeomorphism) induces a homeomorphism on \(V_E\). Hence \(V_E\) becomes a \(G\)-flow. We call
    any \(G\)-flow of this kind a definable \(G\)-flow

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    If \(V\) is a homogeneous \(G\)-set, then the flow \(V_E\) is point-transitive
    #+END_proposition

    #+BEGIN_proof
    We claim the orbit consisting \(a_E\) for \(a\in V\) is dense in \(V_E\).
    Suppose \([b]_E\cap W=\emptyset\) where \(W\) is a type definable set of \(V_E\). We need to
    prove \([a]_E\cap W=\emptyset\) for some \(a\in V\). Let symmetric \(\varphi,\varphi'\) be with \(\varphi(\fC,b)\cap W=\emptyset\), \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(E\) is a btde-relation, \(\tp(a/M)=\tp(b/M)\), then \(aEb\)
    #+END_proposition

    #+BEGIN_proof
    Assume symmetric \(\varphi'\) satisfying \(\varphi'(x,y)\wedge\varphi'(y,z)\vdash\varphi(x,z)\). Because \(E\) is bounded, there
    is \(c\in M\) s.t. \(\varphi'(a,c)\). Since \(\tp(a/M)=\tp(b/M)\) we have \(\varphi'(b,c)\) and
    then \(\varphi(a,b)\). So for any \varphi we have \(\varphi(a,b)\), this is \(E(a,b)\)
    #+END_proof

    Assume \(G\) is a definable group in \(M\) and \(N\prec\fC\) is an extension of \(M\). Let \(S_G(N)\)
    be the set of types \(\{\tp(g/N):g\in G^{\fC}\}\). Then \(S_G(N)\) is a point-transitive \(G^N\)-flow

* Generic and weak generic types
    Assume \(G\) is a definable group in \(M\) and \(V\) is a homogeneous definable \(G\)-set
    in \(M\). For \(A\subseteq G\) and \(U\subseteq V\) by \(AU\) we mean \(\bigcup_{g\in A}gU\).

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    label:1.1
    Assume \(U\subseteq V\)
    1. \(U\) is *(left) generic for the action \(G\) on \(V\)* if for some finite \(A\subseteq G\) we
       have \(V=AU\)
    2. \(U\) is *weak (left) generic* if for some non-generic \(U'\subseteq V\) we have \(U\cup U'\) is generic
    3. \(\varphi\) over \(M\) is *(weak) generic* if the set \(\varphi(M)\cap V\) is *(weak) generic*
    4. \(p(x)\in S(M)\cap V(x)\) *(weak) generic* if every formula \(\varphi(x)\in p(x)\) is (weak) generic
    #+END_definition

    By a (weak) generic subset (type) of \(G\) we mean a (weak) generic subset (type) of \(V=G\)
    acted upon by \(G\) by left translation

    #+BEGIN_remark
    Assume \(U\subseteq V\)
    1. \(U\) is weak generic iff for some finite \(A\subseteq G\) we have that the set \(V\setminus AU\) is not generic
    2. Assume \(U\) is definable. Then \(U\) is weak generic iff for some non-generic
       definable \(U'\subseteq V\) we have that \(U\cup U'\) is generic
    #+END_remark

    #+BEGIN_proof
    1. Obvious
    2. Since \(V\) is definable
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Assume \(X\) is a point-transitive \(G\)-flow and \(p\in X\). We say that \(p\) is *(weak) generic*
    if every open neighbourhood \(U\) of \(p\) in \(X\) is (weak) generic
    #+END_definition

    In the case where \(X=S_V(M)\) is the \(G\)-flow of complete types of elements of \(V^{\fC}\)
    over \(M\), this definition agrees with definition ref:1.1, since our basic open set is of the
    form \([\varphi]\)

    #+ATTR_LATEX: :options []
    #+BEGIN_definition
    Given a point-transitive \(G\)-flow \(X\) let \(Gen(X)\) and \(WGen(X)\) denote the sets of
    generic and weak generic points in \(X\), respectively.
    #+END_definition

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    1. \(Gen(X)\) and \(WGen(X)\) are closed
    2. \(Gen(X)\subseteq WGen(X)\)
    3. \(Gen(X)\neq\emptyset\Rightarrow Gen(X)=WGen(X)\)
    #+END_proposition

    #+BEGIN_proof
    1. For any \(p\in X\setminus Gen(X)\), there is open \(U_p\ni p\) that is not generic. Then \(U\cap Gen(X)=\emptyset\).
       Hence \(X\setminus Gen(X)=\bigcup_{p\in X\setminus Gen(X)}U_p\) is open
    3. [@3] If \(p\in WGen(X)\setminus Gen(X)\),
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume \(f:X\to Y\) is a surjective morphism of point-transitive \(G\)-flows.
    Then \(f(Gen(X))\subseteq Gen(Y)\) and \(f(WGen(X))=WGen(Y)\)
    #+END_lemma

    #+BEGIN_proof
    For any \(f(x)\in f(Gen(X))\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume \(E\) is a \(G\)-invariant btde-relation on \(V^{\fC}\) and \(a\in V^{\fC}\)
    1. \(a_E\) is weak generic in \(V_E\) iff for some \(a'\in[a]_E\) the type \(\tp(a'/M)\) is weak
       in \(S_V(M)\)
    2. If the type \(\tp(a/M)\) is generic in \(S_V(M)\), then \(a_E\) is generic in \(V_E\)
    3. \(a_E\) is generic in \(V_E\) iff for every formula \(\varphi(x,y)\in E(x,y)\) we have
       that \(\varphi(\fC,a)\) is generic for the action of \(G\) on \(V^{\fC}\)
    #+END_corollary

    #+BEGIN_proof
    3. [@3] By the definition of the topology on \(V_E\), \(a_E\) is generic in \(V_E\) iff

       (*) for every \(\varphi(x,y)\in E(x,y)\) the set \(\bigcup\{[b]_E:[b]_E\subseteq\varphi(\fC,a)\}\) is generic in \(V^{\fC}\)
       (regarded as a \(G\)-set)
    #+END_proof

* Extensions of types
    Assume \(M\preceq N\preceq\fC\) where \(M,N\) are both small. Assume \(G,V\) are definable in \(M\), \(G\)
    acts transitively on \(V\). Then \(G^N\) acts transitively on \(V^N\) because it's a first order
    property. There is a natural restriction function \(r:S_V(N)\to S_V(M)\) (a \(G^M\)-mapping). We
    can consider weakly generic types and almost periodic types both in \(S_V(N)\) and \(S_V(M)\)

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Let \(X\) be a flow
    1. If \(U_1,U_2\) are not weakly generic, then \(U_1\cup U_2\) is not weakly generic
    2. Every open set \(U\) containing \(WGen\) is generic
    3. Every partial weakly generic type extends to a complete weakly generic type
    #+END_lemma

    #+BEGIN_proof
    1. Suppose \(V\) is non-generic, then \(U_2\cup V\) is non-generic, hence \(U_1\cup U_2\cup V\) is not
       generic
    2. Since no point in \(X\setminus U\) is weakly generic, by compactness, we can find non-weakly-generic
       open sets \(V_1,\dots,V_k\) s.t. \(U\cup V_1\cup\dots\cup V_k=X\). Then \(V_1\cup\dots\cup V_k\) is not weakly generic
    3. Let \(\Sigma(x)\) be the partial weakly generic type. Let
       \begin{equation*}
       \Sigma^*(x)=\Sigma(x)\cup\{\neg\varphi(x)\mid\exists \psi(x)\in \Sigma(x)\text{ s.t. }\psi\wedge\varphi\text{ is not weakly generic}\}
       \end{equation*}
       any completion of \(\Sigma^*\) is weakly generic

       If \(\psi\wedge\varphi\) is not weakly generic, then by 1, \(\neg\psi\wedge\varphi\) is weakly generic, otherwise \varphi is not
       weakly generic

       If \(\psi\wedge\varphi\) and \(\neg\psi\wedge\varphi'\) are not weakly generic, then \(\neg\psi\wedge\varphi\) and \(\psi\wedge\varphi'\) are weakly
       generic。 Therefore \((\psi\wedge\varphi)\vee(\neg\psi\wedge\varphi')\) are weakly generic and not weakly generic
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume \(\varphi(x)\in L(M)\)
    1. \varphi is generic in \(V^M\) iff it's generic in \(V^N\)
    2. If \varphi is weakly generic in \(V^M\) then it's weakly generic in \(V^N\). If \(M\) is \omega-saturated,
       then the converse holds
    3. If \(p\in S_V(M)\) is weakly generic, then there is a weakly generic type \(q\in S_V(N)\)
       extending \(p\), that is \(WGen_V(M)\subseteq r(WGen(N))\)
    4. If \(M\) is \omega-saturated, then for every weakly generic type \(q\in S_V(N)\), \(q\uhr M\) is
       weakly generic in \(S_V(M)\). Together with 3, \(WGen_V(M)=r(WGen_V(N))\)
    #+END_lemma

    #+BEGIN_proof
    We may assume \(\varphi(x)\vdash V(x)\)
    1. As set is generic iff \(\exists A\subseteq G(\abs{A}=k)(\forall x\in V\bigvee_{a\in A}\varphi(a^{-1}x))\)
    2. If \varphi is weakly generic in \(V^M\), there is a non-generic \(\psi\in L(M)\) s.t. \(\varphi\vee\psi\) is generic
       in \(V^M\), then we apply 1.

       If \varphi is weakly generic in \(V^N\), then there is a non-generic \(\psi(x,y)\in L\) s.t. \(\varphi\vee\psi(x,b)\) is
       generic in \(V^N\) for some \(b\in N\). There is a partial type of \(y\) over finite parameters
       appearing in \varphi and \(\psi'\) forcing \(\varphi(x)\vee\psi'(x,y)\) be generic in \(V^M\) (one formula)
       and \(\psi'(x,y)\) non-generic in \(V^M\) (infinite formulas). If \(M\) is \omega-saturated, the
       realization of \(y\) is what we want
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_lemma
    Assume \(p\in S_V(M)\), \(q\in S_V(N)\), \(p\subseteq q\)
    1. If \(q\) is an heir of \(p\), then \(r(\cl(G^N\cdot q))\subseteq\cl(G^M\cdot p)\)
    2. \(r(\cl(G^N\cdot q))\) is \(G^M\)-invariant in \(S_V(M)\)
    #+END_lemma

    #+BEGIN_proof
    1. Suppose not, there is a formula \varphi over \(M\) s.t. \([\varphi]\cap\cl(G^M\cdot p)=\emptyset\) and \(\varphi\in g\cdot q\) for
       some \(g\in G^N\). So \(\varphi(g^{-1}\cdot x)\in q\). Since \(q\) is an heir of \(p\), we have \(g'\in G^M\)
       s.t. \(\varphi(g'^{-1}\cdot x)\in p\), so \(\varphi\in g'\cdot p\), a contradiction
    2. \(\cl(G^N\cdot q)\) is \(G^N\)-invariant, then it's \(G^M\)-invariant

       Since for each \(g\in G^N\), \(g\) is a homeomorphism. Then \(g(\ove{G^N\cdot q})\subseteq\ove{G^N\cdot q}\) and
       \(g^{-1}(\ove{G^N\cdot q})\subseteq G^N\cdot q\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_proposition
    Assume \(p\in S_V(M)\) is almost periodic, then there is an almost periodic \(q\in S_V(N)\)
    extending \(p\)
    #+END_proposition

    #+BEGIN_proof
    For any \(q\in S_V(M)\) extending \(p\), \(r(\cl(G^N\cdot q))\subseteq\cl(G^M\cdot p)\) and it's \(G^M\)-invariant,
    hence \(r(\cl(G^N\cdot q))=\cl(G^M\cdot p)\) by minimality

    Let \(q_0\in S_V(M)\) be an heir of \(p\),  \(r(\cl(G^N\cdot q_0))\) is a subflow of \(\cl(G^M\cdot p)\),
    hence \(r(\cl(G^N\cdot q_0))=\cl(G^M\cdot p)\). Let \(q_1\in\cl(G^N\cdot q_0)\) be almost periodic,
    then \(\cl(G^N\cdot q_1)\subseteq\cl(G^N\cdot q_0)\) and \(r(\cl(G^N\cdot q_1))\subseteq r(\cl(G^N\cdot q_0))\).
    Hence \(r(\cl(G^N\cdot q_1))=\cl(G^M\cdot p)\)

    Now every \(q\in\cl(G^N\cdot q_1)\) with \(r(q)=p\) is an almost periodic extension of \(p\)
    #+END_proof

    #+ATTR_LATEX: :options []
    #+BEGIN_corollary
    Assume \(G\) is 0-definable group in an \omega-saturated model \(N\) and \(p\in S_G(N)\). TFAE
    1. \(p\) is weakly generic
    2. For every \omega-saturated \(M\preceq N\), \(p\uhr M\) is weakly generic in \(S_G(M)\)
    3. For any finite \(A\subseteq N\) there is an \omega-saturated \(M\preceq N\) containing \(A\) s.t. \(p\uhr M\) is
       weakly generic in \(S_G(M)\)
    #+END_corollary

* Example
** I
    Consider the group \((\Z,+)\) acting on \(2^{\Z}\) by right shift. Namely,
    let \(k\in\Z\), \(f\in 2^{\Z}\), then \((k\cdot f)(n)=f(n-k)\). The topology of \(2^{\Z}\) is just the
    countable product of discrete topology \(2=\{0,1\}\)
** II
    \(\Q=(a_i)\),  \(X_0=\{a_0\}\), \(X_n=\{a_0,\dots,a_n\}\)
    Claim: there is a sequence \((A_n,B_n)\) s.t.
    1. \(A_n,B_n\subseteq_f\Q\)
    2. \(A_n\cap B_n=\emptyset\)
    3. \(A_n\subseteq A_{n+1}\), \(B_n\subseteq B_{n+1}\)
    4. \(\forall Y\subseteq X_n\exists q\in\Q\) s.t. \((q+A_n)\cap X_n=Y\), \((q+B_n)\cap X_n=X_n-Y\)


    If the claim is true, let \([\sigma_n]=\{f\in 2^{\Q}\mid f\uhr A_n=1,f\uhr B_n=0\}\), \(\bigcap[\sigma_n]\) is not empty
* weaf

    \((\Z,+,0)\), \(G^{00}\) is computed in a sufficiently saturated model, \((\Z,+,0)\prec(G,+,0)\)

    \(G^{00}=\bigcap_{n=1}^\infty nG\), \(G/nG\cong I_n\), \(G/G^{00}\cong\hat{\Z}=\lim_{n\to\infty}I_n\)

    \(G/G^{00}\to I_n\)

    inverse limit: \((I,<)\), \((X_i\mid i\in I)\) where \(X_i\) is some algebraic structure

    加\(nG\)有量词消去，只要有一个generic type就只有一个minimal subflow

    Ellis group = minimal subflow = Gen(S_G(M))

    \(G^{00}\)+weakly generic might suggest the element is idempotent

    \(p\in S_1(M)\), \(N\succ M\) \(\abs{M}^+\)-saturated, let \(q\in S_1(N)\) be a coheir of \(p\), then
    \(\exists!q^{\M}\in S_1(\M)\) s.t. \(q\subseteq q^{\M}\) and \(q^{\M}\) is a coheir of \(p\)

    #+BEGIN_proof
    let \(q_1,q_2\in S(\M)\) and \(q\subseteq q_1,q_2\) and they are coheirs of \(p\)

    take \(\varphi(x,b)\in q_1\), \(\neg\varphi(x,b)\in q_2\), \(\varphi(\M,b)\neq\emptyset\), \(\exists b_0\in N\), \(b\equiv_Mb_0\),
    then \(\varphi(x,b_0)\in q\), in same way, \(\neg\varphi(x,b_0)\in q\)
    #+END_proof

    If \(X\) is a externally definable subset of \(M\), if \(N\succ M\) is \(\abs{M}^+\)-saturated, then
    there is \(L_N\)-formula \(\varphi(x)\) s.t. \(X=\varphi(M)\)
