#+TITLE: Homework5

#+AUTHOR: Qi'ao Chen@@latex:\\@@21210160025
#+OPTIONS: toc:nil
#+LATEX_HEADER: \input{../../../../preamble-lite.tex}


#+BEGIN_exercise
Let \(M\) be a structure and \(\calu\) be an ultrafilter on \(\N\). Let \(M^{\calu}\) be the
ultrapower \(\prod_{i\in\N}M/\calu\). Let \(f:M\to M^{\calu}\) be the map sending \(a\in M\) to the class
of \((a,a,a,\dots)\), i.e., the class of constant function \(g_a(x)=a\). Show that \(f\) is an elementary
embedding.
#+END_exercise

#+BEGIN_proof
Let \(M_i=M\) for all \(i\in\N\), \(\alpha_a=f(a)\)


First we show that \(f\) is an embedding. \(f\) is injective from definition.

1. For any constant symbol \(c\), \(c^M\in M\). Then \(c^M=a\) and \(M\vDash c=a\). As \(\{i\in\N:M_i\vDash c=a\}=\N\in\calu\),
   we have \(M^{\calu}\vDash c=f(a)\) and \(f(c^M)=f(a)=c^{M^{\calu}}\).
1. For any function symbol \(h\) and suppose \(M\vDash h(a_1,\dots,a_n)=a\).
   Then \(\{i\in\N:M_i\vDash h(a_1,\dots,a_n)\}=\N\in\calu\). Hence \(M^{\calu}\vDash h(f(a_1),\dots,f(a_n))=f(a)\). Thus
   \(f(h^M(a_1,\dots,a_n))=f(a)=h^{M^{\calu}}(f(a_1),\dots,f(a_n))\).
2. For any relation symbol \(R\), \(M\vDash R(a_1,\dots,a_n)\) iff \(\{i\in\N:M_i\vDash R(a_1,\dots,a_n)\}\)
   iff \(M^{\calu}\vDash R(f(a_1),\dots,f(a_n))\)


Consequently \(f\) is an embedding. For arbitrary formula \(\varphi(x_1,\dots,x_n)\), if \(M\vDash\varphi(a_1,\dots,a_n)\) where \(a_1,\dots,a_n\in M\).
Then \(\{i\in\N:M\vDash\varphi(a_1,\dots,a_n)\}=\N\in\calu\). Thus \(M^{\calu}\vDash\varphi(f(a_1),\dots,f(a_n))\). If \(M^{\calu}\vDash\varphi(f(a_1),\dots,f(a_n))\),
then \(S=\{i\in\N:M\vDash\varphi(a_1,\dots,a_n)\}\in\calu\). As \(S\neq\emptyset\), \(M\vDash\varphi(a_1,\dots,a_n)\) and \(S=\calu\). Thus we have
\begin{equation*}
M\vDash\varphi(a_1,\dots,a_n)\Leftrightarrow M^{\calu}\vDash\varphi(f(a_1),\dots,f(a_n))
\end{equation*}
and \(f\) is elementary
#+END_proof

#+ATTR_LATEX: :options [2]
#+BEGIN_exercise
Say that a set \(S\subseteq\N\) is *cofinite* if \(\N\setminus S\) is finite. Show that there is an ultrafilter \(\calu\)
containing every cofinite set (and possibly other sets as well)
#+END_exercise

#+BEGIN_proof
Let \(A=\{S\subseteq\N:S\text{ is cofinite}\}\). For any \(S_1,S_2\), \(S_1\cap S_2=\N-((\N-S_1)\cup(\N-S_2))\). As \(\N-S_1\)
and \(\N-S_2\) is finite, \(S_1\cap S_2\) is still cofinite. Thus \(A\) has finite intersection property
and there is a filter \(\calf\supseteq A\). Hence there is an ultrafilter \(\calu\supseteq\calf\supseteq A\)
#+END_proof


#+BEGIN_exercise
For \(i\in\N\), let \(\calu_i\) be the set \(\{S\subseteq\N:i\in S\}\). Show that \(\calu_i\) is an ultrafilter on \(\N\)
#+END_exercise

#+BEGIN_proof
1. As \(i\in\N\) and \(i\notin\emptyset\), we have \(\N\in\calu_i\) and \(\emptyset\notin\calu_i\)
2. If \(A\in\calu_i\) and \(A\subseteq B\), then \(i\in A\subseteq B\), hence \(B\in\calu_i\)
3. If \(A,B\in\calu_i\), then \(i\in A\) and \(i\in B\), so \(i\in A\cap B\). Thus \(A\cap B\in\calu\)
4. For any \(A\subseteq\N\), either \(i\in A\) or \(i\notin A\), whence either \(A\in\calu\) or \(\N\setminus A\in\calu\)


Consequently, \(\calu\) is an ultrafilter
#+END_proof


#+BEGIN_exercise
Let \(\calu\) be a non-principal ultrafilter on \(\N\). Show that \(\calu\) contains every cofinite set.
#+END_exercise

#+BEGIN_proof
If there is a cofinite set \(S\) that isn't belong to \(\calu\). Then \(S'=\N\setminus S\) is finite and belongs
to \(\calu\). For every element \(s\in S'\), either \(\{s\}\in\calu\) or \(\N\setminus\{s\}\in\calu\). If \(\{s\}\in\calu\), then \(\calu\)
is principal. So for all \(s\in S'\), \(\N\setminus\{s\}\in\calu\). Then the finite intersection
\(S'\cap\bigcap_{s\in S'}(\N\setminus\{s\})=\emptyset\in\calu\), which is impossible. Thus \(\calu\) contains every cofinite set.
#+END_proof

#+ATTR_LATEX: :options []
#+BEGIN_exercise
Let \(\calu\) be an ultrafilter on \(\N\) containing every cofinite set. Let \(\R^{\calu}\) be the ultrapower
of the structure \((\R,+,\cdot,0,1)\). Show that \(\R^{\calu}\) is not isomorphic to \(\R\)
#+END_exercise

#+BEGIN_proof
Let \(a\in\R^{\calu}\) be the class of the tuple \((0,1,2,3,4,5,\dots)\). For each \(n\in\N\), let \(\varphi_n(x,y)\) be
\begin{equation*}
\underbrace{1+1+\dots+1}_{n\text{ times}}+y\cdot y=x
\end{equation*}
As \(a\) is a function \(\N\to \R\) s.t. for all \(i\in\N\), \(a(i)=i\). Let \(b:\N\to\R\) be
\begin{equation*}
b(i)=
\begin{cases}
0&i\le n\\
\sqrt{i-n}&i>n
\end{cases}
\end{equation*}
We claim that \(\R^{\calu}\vDash\varphi_n([a],[b])\). Let \(S=\{i\in\N:\R\vDash\phi(a(i),b(i))\}\). Then \(\N\setminus S=\{0,\dots,n-1\}\) is
finite. Thus \(S\in\calu\). As \(\R^{\calu}\vDash\varphi_n([a],[b])\Leftrightarrow S=\{i\in\N:\R\vDash\varphi_n(a(i),b(i))\}\in\calu\), we
have \(\R^{\calu}\vDash\varphi_n([a],[b])\) and \(\R^{\calu}\vDash\exists y\varphi_n([a],y)\). Let \(\Gamma(x)=\{\varphi_n(x,y):n\in\N\}\). Then \(\Gamma(x)\)
is realized in \(\R^{\calu}\) but not in \(\R\) since there is \(n\) s.t. \(x-n<0\). If there is such a
isomorphism \(f\), then \(f^{-1}([a])\) realizes \(\Gamma(x)\), which is impossible. Thus \(\R^{\calu}\) is
not isomorphic to \(\R\).
#+END_proof
